### ISSUE TITLE
Serbian translation for How to create a Lesson Plan

### ISSUE THREAD

**Issue by majadidit** [WordPress/Learn#1000]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/how-to-create-a-lesson-plan/
- Language you'll be translating to: Serbian
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: @zzap
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by majadidit** [comment]
https://learn.wordpress.org/wp-admin/post.php?post=24006&action=edit

**Comment by kaitohm** [comment]
@zzap has offered to review the translation for this lesson plan.

**Comment by zzap** [comment]
> Планове лекција могу да користе организатори Meetup-а, говорници на WordCamp-у, тренери, школе, радионице на Learn Вордпрес и креатори курсева, укључујући и друге сценарије.

@majadidit ja bih nekoliko izraza zamenila ovde:
- `Meetup-a` -> `окупљања`, 
- `говорници` -> `предавачи`
- `тренери` -> `добављачи обука` (training providers - ljudi koji snabdevaju druge ljude materijalom za obuku, ne znam kako to elegantno prevesti)

I ovde `окупљања` umesto `Meetup`:
> Планове лекција могу да користе Meetup организатори и креатори радионица
> Одговор: 1. Тачно. Планови лекција су и настали као помоћ организаторима Meetup-а да планирају садржај за полазнике.

Pod neophodnim veštinama nema potrebe da se stavlja crtica u `Вордпрес-ом`. Pošto je na ćirilici naziv zapravo prevod onda ga stavljamo normalno u padeže. 

> Да ли би сте желели да помогнете у тренирању тренера..

Ja bih koristila `едукатора` umesto `тренера`. Nije baš precizan prevod ali mislim da je bliži onome što žele da kažu.

> Постоји ли део WordPress-а у коме се добро сналазите?

Ovde samo prebaciti WP u ćirilicu i bez crtice.

> Изаберите тему у одељку [одобреним избор](http://github.com/WordPress/Learn/projects/2?card_filter_query=label%3A%22[content+type]+lesson+plan%22) како би сте је пренели у “Ти можеш да помогнеш” колону

Pretpostavljam da je `m` višak u `одобреним избор`. 

> Публика – Чије навике желите да промените?

Publika je tačan prevod ali možda `циљна група` više odgovara onome što žele da kažu. Pojavljuje se na još jednom mestu, u listi `Када завршите са писањем прилагођене таксономије плана лекција, имаћете:`

> користећи горе-поменути АБВГ модел

АБВГ :heart: 

Ispravila sam par slovnih grešaka i obrisala jednu rečenicu na engleskom. Ostalo je super :raised_hands:

**Comment by majadidit** [comment]
Thanks everyone! I think I have made all relevant changes. I think the doc is ready to go.

**Comment by kaitohm** [comment]
Yay! When publishing the post, I realized the translation had been made in a general Post content type, rather than our specific Lesson Plan content type. I copied all content across into a new Lesson Plan, and published it below:

[Како припремити план лекција?](https://learn.wordpress.org/lesson-plan/%d0%ba%d0%b0%d0%ba%d0%be-%d0%bf%d1%80%d0%b8%d0%bf%d1%80%d0%b5%d0%bc%d0%b8%d1%82%d0%b8-%d0%bf%d0%bb%d0%b0%d0%bd-%d0%bb%d0%b5%d0%ba%d1%86%d0%b8%d1%98%d0%b0/)

I've deleted the draft Post that was originally being worked on.

I'll mark this issue as complete. But please comment here if any updates or edits are needed 😀
