### ISSUE TITLE
Show video length on tutorials archive page

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#1006]
It would be great to show the video length on the tutorials archive page. This is stored in a meta field on the tutorial post type.

**Comment by adamwoodnz** [comment]
Is that this page @hlashbrooke ?

![Image](https://user-images.githubusercontent.com/1017872/194987833-1a848715-9064-4479-aa7a-0f023938b15a.jpg)

**Comment by hlashbrooke** [comment]
Yes, that's the page.
