### ISSUE TITLE
Learn WordPress Content Error Report - Ticket

### ISSUE THREAD

**Issue by bacoords** [WordPress/Learn#1010]
# Error Description
- Content URL: https://learn.wordpress.org/course/using-the-wordpress-data-layer/

Write a description of the error here.
- The link to the [finished app](https://github.com/WordPress/gutenberg-examples/tree/trunk/non-block-examples/09-code-data-basics-esnext) doesn't actually show the entire app, just the code after the first two lessons.

# Error Report Checklist:
- [ ] Error Validated
- [ ] Error fix proposed
- [ ] Error fix reviewed
- [ ] Error fix published

**Comment by hlashbrooke** [comment]
Thanks for reporting this @bacoords!

@adamziel Could you have a look at this when you get a moment?

**Comment by adamziel** [comment]
Thank you for reporting @bacoords! There is a related [Pull Request](https://github.com/WordPress/gutenberg-examples/pull/227) by @dgwyer to get it fixed, currently blocked on minor linting issues. I'll look into that.

**Comment by dgwyer** [comment]
> There is a related [Pull Request](https://github.com/WordPress/gutenberg-examples/pull/227) by @dgwyer to get it fixed, currently blocked on minor linting issues. I'll look into that.

I would have updated the PR but was unsure what the linting issue was exactly. Glad to have your input.

**Comment by nomad-skateboarding-dev** [comment]
> Thank you for reporting @bacoords! There is a related [Pull Request](https://github.com/WordPress/gutenberg-examples/pull/227) by @dgwyer to get it fixed, currently blocked on minor linting issues. I'll look into that.

Hey @adamziel ! Thank you for getting the Pull Request on this merged!

I was checking if we can then close this issue as well?

**Comment by adamziel** [comment]
Yes! Let's close this ticket

**Comment by adamziel** [comment]
cc @ryanwelcher  @hlashbrooke
