### ISSUE TITLE
Indonesian translation for How to create a Lesson Plan

### ISSUE THREAD

**Issue by kharissulistiyo** [WordPress/Learn#1012]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/how-to-create-a-lesson-plan/
- Language you'll be translating to: Indonesian
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: @agusmu
- Other info: Our reviewer is GTE for Indonesian.

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kharissulistiyo** [comment]
Hi Team,

The translation is done and was reviewed: https://docs.google.com/document/d/10fNerbhzRXjdu9FHwFsUZDpxPVyJqL4B1CwHm0Md3Uo/edit?usp=sharing. 

I think it is ready to go. Thanks!

**Comment by kaitohm** [comment]
@kharissulistiyo Great! The next step is to transfer that translation into a new Lesson Plan. I've duplicated the English lesson plan below. Please replace the title and content with your translation:

https://learn.wordpress.org/wp-admin/post.php?post=26046&action=edit

Once done, please save your changes (don't publish) and let us know again here. We'll update the information in the side bar, make a final check, and publish this for you.

Thank you for your contribution!

**Comment by kharissulistiyo** [comment]
Thank you for checking and replicating the work into a draft post. I'd like to replace the title in the draft post, but when visiting the link you shared, it is currently blocking me with `Sorry, you are not allowed to edit this item.` message.

![Screen Shot 2022-11-04 at 16 09 25](https://user-images.githubusercontent.com/1859092/199938969-33a615fe-0453-4eed-ab86-ca81d8535a97.png)

I can verify that I am being logged into the my .org account when visiting the link to that draft post.

**Comment by webtechpooja** [comment]
@kharissulistiyo This is because you did not have access to Learn WordPress admin. I have sent an invitation to you, please check your email and accept the invitation. Then you will able to access this page.

**Comment by kharissulistiyo** [comment]
@webtechpooja I accepted the invitation and now am able to access the site's admin area. But still seeing the `Sorry, you are not allowed to edit this item.` message when visiting the link to draft post.

**Comment by webtechpooja** [comment]
@kharissulistiyo Can you please check now, I just changed your user role?

**Comment by kharissulistiyo** [comment]
Thank you for your help @webtechpooja!

The page has updated with new title and content for Indonesian. Please let me know if there is any issue with it.

**Comment by kaitohm** [comment]
I have now published this. Nice work!
https://learn.wordpress.org/lesson-plan/panduan-membuat-rencana-pembelajaran/

**Comment by kharissulistiyo** [comment]
Thank you @webtechpooja, @bsanevans, and Training Team for making this post available. We (Indonesian WordPress Community) really appreciate your hard work!
