### ISSUE TITLE
Hacktoberfest Content Creators & Translators

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#1013]
# Hacktoberfest on Learn.WordPress.org

Hacktobertfest is an open source initiative that can help contributors find projects and submit contributions during the month of October.

> HACKTOBERFEST IS FOR EVERYONE. WHETHER IT’S YOUR FIRST TIME—OR YOUR NINTH—IT’S ALMOST TIME TO HACK OUT FOUR PRISTINE PULL/MERGE REQUESTS AND COMPLETE YOUR MISSION FOR OPEN SOURCE.

## Low & No-Code Contributions now accepted

>HACKTOBERFEST ISN’T ALL ABOUT CODE. ANYONE WHO WRITES, DESIGNS, TESTS, MENTORS, OR ORGANIZES OFFERS MUCH NEEDED SUPPORT FOR OPEN-SOURCE PROJECTS ALL OVER THE WORLD.

Areas for the Training team can contribute:

>
 &nbsp; | LOW-CODE | NON-CODE
-- | -- | --
WRITING | TECHNICAL DOCUMENTATION | TRANSLATING, COPY EDITING
DESIGN | TESTING | USER EXPERIENCE TESTING, GRAPHIC DESIGN, VIDEO PRODUCTION

[Learn more about low/no-code contributions](https://hacktoberfest.com/about/#low-or-non-code)

## How to Participate

>[Hacktoberfest Participation](https://hacktoberfest.com/participation/)

1. Find an issue labeled Hacktoberfest that you'd like to work on. Submit code changes for theme dev as a traditional PR.
  * [Creating Content for WordPress 6.1](https://github.com/wordpress/learn/issues?q=is%3Aissue+is%3Aopen+label%3A6.1) by commenting that you would like to be assigned for that issue and a teammember will assign it to you. If it does not already have a Hacktoberfest label, we can add it during the month of October.
  * Translate any existing content. We are just beginning this work with the team, so please leave a message in the [#training Slack channel](http://wordpress.slack.com/messages/training/) after selecting a topic
2. [Connect your GitHub account](https://hacktoberfest.com/auth/)
3. Contribute and create a Pull Request. 

>**Note: We usually do not generally use PRs for content on LearnWP (just theme development), as we create and store the content directly in a WordPress-powered site. However, to receive Hacktoberfest credit, please create a PR of the topic you've selected from the [LearnWP Content Management Project](https://github.com/orgs/WordPress/projects/33) and revise the issue content to include a link to your content on LearnWP.**  

>**Additionally, please also make a PR on this file to add your GitHub username as a contributor. [https://github.com/WordPress/Learn/blob/trunk/hacktoberfest-contributors-2022.md](https://github.com/WordPress/Learn/blob/trunk/hacktoberfest-contributors-2022.md)**

### How to create a Pull Request (PR)

https://youtu.be/nkuYH40cjo4

[At 9:44](https://youtu.be/nkuYH40cjo4?t=584), the presenter demonstrates editing the file's issue content on your own account and submitting the PR back, without needing to work in the terminal locally.

**Comment by ludovicobesana** [comment]
@courtneyr-dev Hello :)
I'm trying to join inside the slack for making some contributions but the slack invite didn't work.
I can't create an account.
<img width="489" alt="Schermata 2022-10-24 alle 22 18 18" src="https://user-images.githubusercontent.com/35035423/197621007-c25e6d6f-97db-4803-aa18-041273c234c7.png">
