### ISSUE TITLE
Classic Theme Template Parts - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#1014]
# Topic Description
How to enable block templates and template parts in classic themes (non-FSE)

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
Code example: 
[Very simple example theme](https://github.com/Mamaduka/block-fragments) with more details for implementation in [Testing and Feedback for using block based template parts in classic themes](https://make.wordpress.org/themes/2022/09/12/testing-and-feedback-for-using-block-based-template-parts-in-classic-themes/). 
For a more detailed guide, [review this post from the Gutenberg Times](https://gutenbergtimes.com/building-a-block-based-header-template-in-a-classic-theme/).

Visual: [video of the experience of using template parts in classic themes](https://drive.google.com/file/d/1qy6jonIbX9rTQSiqEvyVOe4W9Qrrmy2L/view?usp=sharing).

Key Make Posts/GitHub/Trac Issue(s): [Testing and Feedback for using block based template parts in classic themes](https://make.wordpress.org/themes/2022/09/12/testing-and-feedback-for-using-block-based-template-parts-in-classic-themes/). For a more detailed walkthrough, [review this post from the Gutenberg Times](https://gutenbergtimes.com/block-based-template-parts-for-classic-themes/).

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [x] Tutorial submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Tutorial submitted to WPTV https://wordpress.tv/submit-video/
- [x] Tutorial published on WPTV
- [x] Tutorial is captioned https://make.wordpress.org/training/handbook/tutorials/tutorial-subtitles-and-transcripts/
- [x] Tutorial created on Learn.WordPress.org
- [x] Tutorial post is reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial announced to training team
- [x] Tutorial announced to creator
- [x] Tutorial announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by jonathanbossenger** [comment]
@courtneyr-dev [I tested this when the call for testing came out](https://make.wordpress.org/themes/2022/09/12/testing-and-feedback-for-using-block-based-template-parts-in-classic-themes/#comment-44420), so if no one else wants this, I could definitely tackle it.

**Comment by jonathanbossenger** [comment]
I'm going to do my best to get this recorded and up for review by tomorrow, so it can be published to coincide with the 6.1 release on 1 November.

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/196468941-abd25385-22ee-45b5-afeb-7acf58e7179a.mp4

**Comment by vagelisp** [comment]
Looking good to me.
Such a great feature.

**Comment by jonathanbossenger** [comment]
Thanks @vagelisp 

A great feature to look forward too indeed.

**Comment by courtneyr-dev** [comment]
Please do release :)

**Comment by abhansnuk** [comment]
Enjoyed this video to review (which still had the ready to review label) @jonathanbossenger and it was a good pace. The approach of explaining what you could do, and then the showing users how to do the same will really help learners follow along. 

Before it is released, can we just put some space around the WordPress logo and learn in line with the trademark and enough spacing for more users to be able to read the website address, at least on the home screen? eg the video at https://github.com/WordPress/Learn/issues/1014

For the next video, suggest the speech when you are showing learners how to do something could be a little louder. I appreciate you are trying to differentiate the sound, in a couple of places it was just a bit too quiet for some people listening.

Look forward to your next video Jonathan.

**Comment by jonathanbossenger** [comment]
@courtneyr-dev thanks

@abhansnuk thanks for the review

> Before it is released, can we just put some space around the WordPress logo and learn in line with the trademark and enough spacing for more users to be able to read the website address, at least on the home screen

It's a bit tricky to edit that post-production, as it's part of my slides. But, I will make sure to edit my default slide deck on which I base all my slides so that there's a bit more space going forward.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2022/11/02/using-block-template-parts-in-classic-themes/

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/tutorial/using-block-template-parts-in-classic-themes/

**Comment by jonathanbossenger** [comment]
Tutorial is published
