### ISSUE TITLE
Content Error Report: Error in template hierarchy example snippet

### ISSUE THREAD

**Issue by audrasjb** [WordPress/Learn#1019]
Hi there!

First time here! Thanks for the amazing work. 
I hope it's the good place to report an issue with Learn content :)

# Error Description
- Content URL: https://learn.wordpress.org/lesson-plan/template-hierarchy/#example

In the example snippet 
```
    if(!is_array($templates) &amp;amp;amp;&amp;amp;amp; !empty($templates)) {
```
should be replaced with:
```
    if ( ! is_array( $templates ) && ! empty( $templates ) ) {
```

# Error Report Checklist:
- [ ] Error Validated
- [ ] Error fix proposed
- [ ] Error fix reviewed
- [ ] Error fix published

**Comment by vagelisp** [comment]
Hello @audrasjb. Thanks for reporting this.
It is now fixed.
( I replaced &amp;amp;amp;&amp;amp;amp; with '&&' but I didn't change the code styling )

**Comment by audrasjb** [comment]
Thanks @vagelisp
