### ISSUE TITLE
Add column for Video Language

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/Learn#102]
On the [All Workshops](https://learn.wordpress.org/wp-admin/edit.php?post_type=wporg_workshop) page, I think it'll be useful to see the Video Language shown as a new column after Topics (Title, Experience Levels, Topics, Language, Comments, Date).  I don't believe Video Language should be a taxonomy.  

Clicking on a language associated with a workshop should show a filtered set of workshops with that language. 

Nao has posted [this call ](https://make.wordpress.org/polyglots/2020/08/17/call-for-learn-wordpress-volunteers-video-translation-discussion-group/ )on the Polyglots P2.  This column will be important once we get some non-English videos recorded.

**Comment by coreymckrill** [comment]
👍 Sounds like a good idea.

Just noting that the video language (and the video captions) are already post meta fields, not taxonomies.
