### ISSUE TITLE
Online Workshop - Ideas for getting more views on your blog

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1022]
# Event Details
- Title: Ideas for getting more views on your blog
- Description: In this online workshop, we’ll be taking a look at some ideas you can take home and try in order to get more views to your blog.
- Target Audience: Beginner Users
- Date: October 27th
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/289128381/
- Co-host: @jonathanbossenger 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by kaitohm** [comment]
You can find my slides here: https://docs.google.com/presentation/d/1Pu_YfHfj2FpIj0F42evdnl0tpvawSnJEoQd-S6S_8jk/edit?usp=sharing

Just as a note, this Online Workshop is focusing on non-SEO methods of generating views. I plan on conducting a similar workshop soon on SEO, which I'll link here and in the slides once up.

**Comment by kharissulistiyo** [comment]
Hi @bsanevans, 

I reviewed the slides. Everything looks good. 

I have some suggestions:

* May I suggest adding _"Wear a t-shirt with your homepage URL printed on it"_ into [slide 25](https://docs.google.com/presentation/d/1Pu_YfHfj2FpIj0F42evdnl0tpvawSnJEoQd-S6S_8jk/edit#slide=id.g1438c4188b5_1_208)?
* May I suggest adding _"A short biography box to tell audience who is writing the post?"_ for _"What do they see on the screen?"_ in [slide 29](https://docs.google.com/presentation/d/1Pu_YfHfj2FpIj0F42evdnl0tpvawSnJEoQd-S6S_8jk/edit#slide=id.g168d7c66b0f_0_162)?

I really appreciate your hard work! Thank you, Ben!

**Comment by kaitohm** [comment]
Thanks for taking a look, @kharissulistiyo ! Your t-shirt idea was excellent! I went and added a new slide (new slide 25) all about that, and to encourage folks to get creative.

**Comment by kaitohm** [comment]
The WordPress.tv recording can be found here: https://wordpress.tv/2022/11/03/ideas-for-getting-more-views-on-your-blog/
