### ISSUE TITLE
Greek translation for Lesson Plan "How To Add and Remove Logo And Site Icon in Site Editor"

### ISSUE THREAD

**Issue by vagelisp** [WordPress/Learn#1023]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/how-to-add-and-remove-logo-and-site-icon-in-site-editor/
- Language you'll be translating to: Greek 
- Have you arranged for someone to review this translation?: No ( tagging ppl further down in the issue )
- Reviewer's GitHub username:
- The translated version of the Lesson Plan in google docs: https://docs.google.com/document/d/1oBaagnOmPSQKVmea3j4JHgFAP8Q_NtQIlQv__7_g0eI/

**Comment by vagelisp** [comment]
Hello 👋🏻  @lenasterg , @theo-gk, @o-samaras 
Can someone review this, please?
Thank you so much.

**Comment by lenasterg** [comment]
Ηi. 
@vagelisp, check by me. 
See the track changes.

**Comment by vagelisp** [comment]
Thank you so much @lenasterg , 
I merged your suggestions/edits

**Comment by o-samaras** [comment]
Hi @vagelisp. Couple more suggestions and a comment in there.
Thanks for taking care of this! 💪

**Comment by vagelisp** [comment]
Thanks, @o-samaras I accepted your suggestions!

**Comment by vagelisp** [comment]
Published here:

https://learn.wordpress.org/lesson-plan/%cf%80%cf%8e%cf%82-%ce%bd%ce%b1-%cf%80%cf%81%ce%bf%cf%83%ce%b8%ce%ad%cf%83%ce%b5%cf%84%ce%b5-%ce%ba%ce%b1%ce%b9-%ce%bd%ce%b1-%ce%b1%cf%86%ce%b1%ce%b9%cf%81%ce%ad%cf%83%ce%b5%cf%84%ce%b5-%ce%bb%ce%bf/
