### ISSUE TITLE
German translation for lesson plan "Dashboard Overview"

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1024]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/dashboard-overview/
- Language you'll be translating to: German
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username:
- Other info: This lesson plan was translated by [Gudrun](https://profiles.wordpress.org/weblink/). I'm creating an issue here so we can track their contribution, and the review process.

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
This lesson can be previewed here: <strike>https://learn.wordpress.org/?p=24030&post_type=lesson-plan&preview=1&_ppp=b6e8f04c61</strike>
https://learn.wordpress.org/?p=24030&post_type=lesson-plan&preview=1&_ppp=12122a3a91

This is ready for a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by gudrunfrank** [comment]
Thank you for reviewing this.

**Comment by MatzeKitt** [comment]
I will review it. 🙂

**Comment by MatzeKitt** [comment]
I stopped on the headline "Das Dashboard" (in original: "Page Body"). It seems that the original post has been updated in the meantime and the content following this headline (and also the content of following headlines) is out of date in this German version.

@gudrunfrank Could you please update the post to the latest version?

**Comment by gudrunfrank** [comment]
@MatzeKitt thank you for taking a look. I am not sure what you are referring to with the post being changed since the translation. The original was created on 8/9/2020 and I do not see any modification date. https://learn.wordpress.org/lesson-plan/dashboard-overview/
In any case, I do not see the lesson plan "translations" in a typical sentence for sentence translation. I view the original as a starting point and inspiration to make a German lesson plan. As we see in this case, we could be working with an older lesson plan. My intention was to create a lesson plan that makes sense, uses proper German and is useful to our audience. I will double-check with the training team to verify that my assumption is correct.

**Comment by kaitohm** [comment]
This issue was discussed here: https://wordpress.slack.com/archives/C02RW657Q/p1667851665845209?thread_ts=1666971296.988559&cid=C02RW657Q We'd like to keep the English and translated versions the same. 

@gudrunfrank Would you like to suggest edits to the English lesson plan? If so, you can create a new [Content Error Report Template](https://github.com/WordPress/Learn/issues/new/choose) with your suggestions.

Otherwise, you could also modify your German lesson plan translation to match the current English version. Once modified, we can request a translation review again.

**Comment by gudrunfrank** [comment]
@bsanevans Hi Ben, this should probably be closed. The lesson is already published. As far as I remember, it was reopened under a new ID as it was not a translation per se but rather a new lesson in German. What is the correct process closing this? Can I do it? Thanks!

**Comment by kaitohm** [comment]
Ah, thanks for following up with this, @gudrunfrank . I see, the new lesson plan was tracked here: https://github.com/WordPress/Learn/issues/1184

Yes, let's go and close this issue. I'll close it this time. In future, you just have to press `Close with comment` instead of `Comment`, and the issue will close 🙂
