### ISSUE TITLE
A Beginner Guide to the WordPress Template Hierarchy - Tutorial

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1028]
# Topic Description
A Beginner Guide to the WordPress Template Hierarchy, covering how the template hierarchy works, and how it affects both classic and block themes.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ Template Hierarchy](https://developer.wordpress.org/themes/basics/template-hierarchy/)

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [x] Tutorial submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Tutorial submitted to WPTV https://wordpress.tv/submit-video/
- [x] Tutorial published on WPTV
- [x] Tutorial is captioned https://make.wordpress.org/training/handbook/tutorials/tutorial-subtitles-and-transcripts/
- [x] Tutorial created on Learn.WordPress.org
- [x] Tutorial post is reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial announced to training team
- [x] Tutorial announced to creator
- [x] Tutorial announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/196209637-ba06101a-a9da-46a6-83f3-fbe7a9b0e502.mp4

**Comment by manzwebdesigns** [comment]
Looks good to me, @jonathanbossenger!

**Comment by jonathanbossenger** [comment]
Thanks very much, @manzwebdesigns

**Comment by vagelisp** [comment]
Looking good, well done.

**Comment by jonathanbossenger** [comment]
Thanks @vagelisp

**Comment by Piyopiyo-Kitsune** [comment]
Great work Jonathan! 

Some shoer feedback: 
- I loved the zoom into the link, but I felt that went very quick. 
- Around 3:40 you go on to list some items-- I know that you point to it with an arrow, but it would be cool if there were some red boxes or indicators of the sections you are referring to as you list them out on the image.

**Comment by jonathanbossenger** [comment]
Thanks for the feedback @Piyopiyo-Kitsune I'll make those tweaks before I publish.

**Comment by jonathanbossenger** [comment]
Video updated with feedback incorporated.

https://user-images.githubusercontent.com/180629/198276704-26b6004c-01dd-4267-8858-b95edc5b173b.mp4

**Comment by jonathanbossenger** [comment]
Published: https://learn.wordpress.org/tutorial/a-beginners-guide-to-the-wordpress-template-hierarchy/
