### ISSUE TITLE
GitHub sync is still happening

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#103]
It looks like the lesson plans are still being imported from GitHub. We are drafting posts and they're coming back each time the GitHub sync runs. I seem to remember this was disabled completely, but could we please check to make sure the GitHub sync is completely disabled and no content is pulled from the repos at all.

**Comment by coreymckrill** [comment]
I've confirmed that the sync is turned off. @hlashbrooke and I discussed that the perception that it's still syncing may be coming from the fact that in some cases there are multiple lesson plans on the same topic, so when one is removed, it seems like it's still there, but it is in fact a separate lesson plan.

Closing for now, but we can revisit if we have more evidence that the sync is actually happening.
