### ISSUE TITLE
Hindi translation for Lesson Plan "How to create a Lesson Plan"

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1032]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/how-to-create-a-lesson-plan/
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: Yes or No - Yes
- Reviewer's GitHub username: webtechpooja
- Other info: Google doc link - https://docs.google.com/document/d/1Yc7BVY7owV1ZqilnsVFuVbUqin0Xs9RCXXSKSj8Muj4/edit

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by dhanushreddy291** [comment]
The Google Doc is inaccessible

**Comment by hderashri** [comment]
I would like to work on this.

**Comment by webtechpooja** [comment]
Thank you for showing your interest. Could you please DM me your email ID? so I can add you to the Google docs to review it.

**Comment by webtechpooja** [comment]
I have added you to the google doc, please review it and leave any changes in the comments.
Let us know in this Github comment thread when you complete with the review. Thanks

**Comment by webtechpooja** [comment]
Done, now published on learn.wordpress.org

**Comment by kaitohm** [comment]
I just updated the very last line on the lesson plan so that it uses the `tip` shortcode. This is what I changed it to.

<img width="340" alt="tip-shortcode" src="https://user-images.githubusercontent.com/49054298/202120874-d42fed8b-bfce-46fe-9c99-10be92ba3872.png">

Nice work, team!
