### ISSUE TITLE
Nepali translation for Lesson Plan "How to create a Lesson Plan"

### ISSUE THREAD

**Issue by pragyaasapkota** [WordPress/Learn#1033]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/how-to-create-a-lesson-plan/
- Language you'll be translating to: Nepali
- Have you arranged for someone to review this translation?: Yes or No - No
- Reviewer's GitHub username: @kafleg 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by pragyaasapkota** [comment]
The link to the translated draft --
https://docs.google.com/document/d/1EkAZtln83CmEq0LAzq3QDTq3bm8SE_DYBjccWTf2uGQ/edit

**Comment by pragyaasapkota** [comment]
I request a review.

**Comment by pragyaasapkota** [comment]
@courtneyr-dev 
@bsanevans 
How can I get a reviewer?

**Comment by kaitohm** [comment]
I've pinged a [General Translation Editor](https://make.wordpress.org/polyglots/teams/?locale=ne_NP) in the Training Slack channel to see if they can review this for us. ([link to Slack message](https://wordpress.slack.com/archives/C02RW657Q/p1666329467950939))

**Comment by kafleg** [comment]
I'm on it. :)

**Comment by kafleg** [comment]
@Pragya2056 

Please translate:

Meetup - मिटअप
WordPress - वर्डप्रेस
Knowledge -?
 
Also, would you please give me the editing access so that I can suggest? 

Thank you

**Comment by pragyaasapkota** [comment]
@kafleg I will replace the words in general text - but I imagine that would be a confusion for links. Please let me know what you think.
I will also give you the editng access.

**Comment by pragyaasapkota** [comment]
> @Pragya2056
> 
> Please translate:
> 
> Meetup - मिटअप WordPress - वर्डप्रेस Knowledge -?
> 
> Also, would you please give me the editing access so that I can suggest?
> 
> Thank you

@kafleg 
I have corrected the mistakes and provided you editing access. 
Please let me know if I missed something. 
Thank you!!!

**Comment by Pragya2056** [comment]
@kafleg 
Are there any problems in the new corrected draft ?

**Comment by pragyaasapkota** [comment]
@kafleg 
Are there any problems in the new corrected draft ?

**Comment by kafleg** [comment]
> @kafleg Are there any problems in the new corrected draft ?

Checked and edited. Ready to go. 

CC: @courtneyr-dev

**Comment by Pragya2056** [comment]
Thank you @kafleg . 
Do I need to do something to process further ?

**Comment by pragyaasapkota** [comment]
@courtneyr-dev 
@bsanevans 
How to take this forward?
Do I need to do something? Please let me know.

**Comment by kaitohm** [comment]
@Pragya2056 Sorry for the delay.

Could you share you WordPress.org username here? I'll invite you as a Lesson Plan Editor on the Learn WordPress site. Once you accept the invitation, you'll then be able to copy your translation over from the Google document into the lesson plan below.
https://learn.wordpress.org/wp-admin/post.php?post=26056&action=edit
Once you've been added, please replace the English title and content in that post. Please leave the settings on the right as they are.

I look forward to hearing from you!

**Comment by pragyaasapkota** [comment]
My username in wordpress.org is -- pragyasapkota

**Comment by kaitohm** [comment]
@Pragya2056 I've just invited you to the site. Once you accept the invitation, you should be able to edit the post linked above.

**Comment by pragyaasapkota** [comment]
@bsanevans 
[Published the Nepali translation](https://learn.wordpress.org/lesson-plan/%e0%a4%aa%e0%a4%be%e0%a4%a0-%e0%a4%af%e0%a5%8b%e0%a4%9c%e0%a4%a8%e0%a4%be-%e0%a4%95%e0%a4%b8%e0%a4%b0%e0%a5%80-%e0%a4%ac%e0%a4%a8%e0%a4%be%e0%a4%89%e0%a4%a8%e0%a5%87/)

**Comment by pragyaasapkota** [comment]
The issue can be closed if everything is alright.

**Comment by kafleg** [comment]
I think the permalinks should be changed.

**Comment by pragyaasapkota** [comment]
Do I need to do it ? 
@kafleg

**Comment by kafleg** [comment]
I don't have access to do that. @bsanevans Can I have the editor access?

**Comment by kaitohm** [comment]
@kafleg You have been invited 👍 
BTW, how are you proposing editing the permalinks? Are you talking about the links listed here? https://github.com/WordPress/Learn/issues/1042 If so, please feel free to update them!

**Comment by kaitohm** [comment]
@Pragya2056 Thank you for your contributions in this work!

As a team, much of our communication is in Slack. Have you joined the Make WordPress Slack channel yet?
If not, you can follow this guide to join: https://make.wordpress.org/chat/
Once you've joined, please come over to the `#training` channel, as we'd love to have you join the team! 😃

**Comment by kafleg** [comment]
@bsanevans I think we need to use English permalink or atleast Post ID. The Nepali text in permalink won't look good. 

Example, 
![image](https://user-images.githubusercontent.com/13062231/201131628-43d50577-d1cb-4ce8-9b45-b0acec8bb23e.png)

**Comment by kaitohm** [comment]
Until now, each locale has left the permalink in their locale's language:
* https://learn.wordpress.org/lesson-plan/panduan-membuat-rencana-pembelajaran/
* https://learn.wordpress.org/lesson-plan/%d0%ba%d0%b0%d0%ba%d0%be-%d0%bf%d1%80%d0%b8%d0%bf%d1%80%d0%b5%d0%bc%d0%b8%d1%82%d0%b8-%d0%bf%d0%bb%d0%b0%d0%bd-%d0%bb%d0%b5%d0%ba%d1%86%d0%b8%d1%98%d0%b0/

I wonder which is better from an SEO perspective? I think this is something we should bring up in an upcoming team meeting and document a standard across the team for. What do you think?

**Comment by pragyaasapkota** [comment]
> @Pragya2056 Thank you for your contributions in this work!
> 
> As a team, much of our communication is in Slack. Have you joined the Make WordPress Slack channel yet? If not, you can follow this guide to join: https://make.wordpress.org/chat/ Once you've joined, please come over to the `#training` channel, as we'd love to have you join the team! 😃

Thanks I just joined the slack and the #training channel

**Comment by pragyaasapkota** [comment]
> Until now, each locale has left the permalink in their locale's language:
> 
> * https://learn.wordpress.org/lesson-plan/panduan-membuat-rencana-pembelajaran/
> * https://learn.wordpress.org/lesson-plan/%d0%ba%d0%b0%d0%ba%d0%be-%d0%bf%d1%80%d0%b8%d0%bf%d1%80%d0%b5%d0%bc%d0%b8%d1%82%d0%b8-%d0%bf%d0%bb%d0%b0%d0%bd-%d0%bb%d0%b5%d0%ba%d1%86%d0%b8%d1%98%d0%b0/
> 
> I wonder which is better from an SEO perspective? I think this is something we should bring up in an upcoming team meeting and document a standard across the team for. What do you think?

I think I agree with @kafleg 
It might be better if we have every translated lesson plan permalink as - lesson plan in {the language}

**Comment by kaitohm** [comment]
Alright, let me bring this up with the Training Team next week. We can come back and update the permalink once it has been discussed 👍

**Comment by pragyaasapkota** [comment]
@bsanevans 
I think this issue is good to close.
