### ISSUE TITLE
Tools: Site Health Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1036]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/197096106-102b10df-01a4-473b-bf57-d05f455a291d.mp4

**Comment by westnz** [comment]
https://wordpress.slack.com/archives/C02RW657Q/p1666318939908299

<img width="379" alt="image" src="https://user-images.githubusercontent.com/89751452/197631113-342a1181-e7f7-4225-b27c-90c6fd42cdbb.png">

**Comment by Piyopiyo-Kitsune** [comment]
Is this ready for publication @westnz ?

**Comment by westnz** [comment]
It is scheduled to be published in January.

**Comment by westnz** [comment]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/89751452/209237708-8fc2a5d4-a4fa-438f-80fe-11fe9da23310.png">

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/tools-site-health/

**Comment by westnz** [comment]
Updated for the Intermediate user learning pathway.

**Comment by westnz** [comment]
//published
