### ISSUE TITLE
Migrate Lesson Plan `wporg_lesson_category` taxonomy usage to `topic` taxonomy 

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#1037]
Depends on #1009 

Once all the Lesson Plan `wporg_lesson_category` data has been moved into the common `topic` taxonomy we need to:

1. Add icon and sticky meta fields to the `topic` taxonomy like the current `audience` and `wporg_lesson_category` taxonomies, and switch landing page Topic tiles over to use `topic`:

![Screen Shot 2022-11-04 at 1 07 46 PM](https://user-images.githubusercontent.com/1017872/199857833-4e23ab6a-1ff5-4239-8508-ba2a24300de6.jpg)

![Screen Shot 2022-11-04 at 1 05 36 PM](https://user-images.githubusercontent.com/1017872/199857640-59ebbb08-a61e-450f-83bd-7ccd6f1d60d9.jpg)

2. Remove the `wporg_lesson_category` taxonomy

**Comment by hlashbrooke** [comment]
Confirming that the lesson plan categories have all been migrated to the topic taxonomy and the content has been added to the appropriate topics, so everything is prepped for the three tasks in this issue to be worked on.

**Comment by adamwoodnz** [comment]
All the Topics required for the Lesson Plan landing pages have now had icons added and been made sticky, so this PR can land with no obvious change on the frontend, apart from possibly the order of the tiles changing.
