### ISSUE TITLE
Course: A Developers Guide To Block Theme Development - Part 2

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1041]
# IMPORTANT
**This course depends on the completion of  [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631)**

**Ideally that course should be completed before tackling any lesson related to this course**

**Please reach out to @jonathanbossenger (Jonathan Bossenger) in the #training team Slack if you would like to help with this course.**

See also [part 1](https://github.com/WordPress/Learn/issues/821).

## Needs Assessment Statement

A course about extending a low-code block theme should exist because intermediate or advanced theme developers will want to learn how to tackle more technical challenges when developing block themes.

This is part 2 of this course, which will cover advanced block theme development tactics

## Target Audience

Suzie is a theme developer who, before the advent of block themes,  has created a number of free themes for WordPress.org, commercial themes that she sells on a theme marketplace, and a few custom themes for specific clients. With the advent of the WordPress block editor, and the ability to create themes from the Site Editor, she wants to take her experience as a classic theme developer and learn how to build custom themes using blocks. 

Suzie has watched a few online tutorials on Block theme fundamentals OR completed the [Create a Block Theme (Low-Code) - Course](https://github.com/WordPress/Learn/issues/631#course-outline) OR read the relevant sections in the handbook on [Block Themes](https://developer.wordpress.org/themes/block-themes/) and understands the fundamentals of block themes, but can see the limitations of a block theme that’s only created in the Site Editor, and wants to understand how to extend a custom block theme beyond those limitations. 

## Course Objective

Intermediate and advanced developers will be able to extend the low code theme created in the [Create a Block Theme (Low-Code) - Course](https://github.com/WordPress/Learn/issues/631#course-outline), by understanding the underlying technologies better, and add advanced features like custom templates and template parts, custom fonts, images, custom styles etc.

### Module 1: Custom Fonts
- [x] #887 
- [x] #1099
- [x] #1100
- [x] #1101

### Module 2: Theme Patterns
- [ ] #894 
- [x] #1102
- [ ] #895 

### Module 3: Global Styles variations
- [x] #896 
- [x] #897 

### Module 4: Internationalization
- [x] #898 
- [x] #899 

### Module 5: Locking Down your Theme
 - [x] #996
 - [x] #846 

## Project Planning

| Module | Status | ETA |
|--------|--------|-----|
|Custom Fonts|Done|14/10|
|Theme Patterns|In Progress||
|Global Styles variations|Ready||
|Internationalization|Ready||
|Locking Down your Theme|In Progress||

 - Draft – module content is complete, some self-review/screenshots are still needed
 - In Progress – module is being worked on
 - Ready – module is ready to create
 - Done – module is complete and ready for review

**Comment by jonathanbossenger** [comment]
@justintadlock apologies if I didn't mention this to you earlier, but we're aiming to have this course ready for "beta review" by Friday 18 November.  Public beta means we're still working on it, but folks in the training team will be able to review it for two weeks and provide feedback. Then we'd like to have it ready to publish by the end of the month.

Besides the [one change suggestion](https://github.com/WordPress/Learn/issues/846#issuecomment-1311771542) I had, do you feel comfortable that you'll be able to create PRs to add the lessons to the main repo before the 18th?

**Comment by justintadlock** [comment]
@jonathanbossenger yes, will do. Will get to this first thing Monday.

**Comment by jonathanbossenger** [comment]
Created course in Sensei https://learn.wordpress.org/wp-admin/post.php?post=26187&action=edit

**Comment by jonathanbossenger** [comment]
[A Developers Guide To Block Theme Development - Part 2](https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-2/) is now available for beta review.

## Review period

This beta review period is to allow interested parties the opportunity to review the course content and provide feedback.

I intend to leave this open for any feedback until the **30th of November 2022**, to accommodate the US Thanksgiving weekend, as some folks might be offline during that time.

During this period, I am still working on updates to formatting and tone, as well as checking for consistency, grammar, and the general learning path of the course. 

## How to leave feedback

Each lesson in the course is linked to an open GitHub issue. All the related GitHub issues are linked in the main body of this ticket. As you work through each lesson, please leave any feedback for that lesson on the relevant ticket.

**Comment by westnz** [comment]
Intro page:
Should 'here' at the end of the paragraph have a link to the registration page?
<img width="683" alt="image" src="https://user-images.githubusercontent.com/89751452/203452225-bfe915a6-9d30-499a-8826-e213912f1bb7.png">

**Comment by westnz** [comment]
I love the recap section!  Allowing a learner to check if they are ready for Part 2.

**Comment by westnz** [comment]
Should Site Editor and Editor be in capital letters?

**Comment by westnz** [comment]
Brilliant work! 

Review Suggestions:

1. Adding some assessments or practical activities with instructions.  An idea for quiz questions where learners need to apply their knowledge is to add a screenshot of a code snippet, with an error, and then, of course, choose the correct answer or solution. 
2. Adding a conclusion to wrap things up at the end of the course.

**Comment by jonathanbossenger** [comment]
Thanks @westnz 

> Adding some assessments or practical activities with instructions. An idea for quiz questions where learners need to apply their knowledge is to add a screenshot of a code snippet, with an error, and then, of course, choose the correct answer or solution.
Adding a conclusion to wrap things up at the end of the course.

Yes, I plan to add quizzes at the end of each module, and a summary.

**Comment by jonathanbossenger** [comment]
Update, the quizzes and summary lesson have both been added, feel free to leave any suggestions on improvement there.

My last "internal" review step is to work through the course one more time, checking for any code, formatting, or technical instructional bugs, which I will do tomorrow morning. Once that is complete, the course will be ready to be featured on Learn WordPress.

**Comment by jonathanbossenger** [comment]
[This course has been published and featured in the courses list](https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-2/)
