### ISSUE TITLE
Learn WordPress Content Error Report - Ticket

### ISSUE THREAD

**Issue by pragyaasapkota** [WordPress/Learn#1042]
# Error Description
- Content URL: https://learn.wordpress.org/lesson-plan/how-to-create-a-lesson-plan/

Write a description of the error here.
Four of the links are not working - show a 404 error. 
1. Approved choices 
![image](https://user-images.githubusercontent.com/55945790/197166561-2852129d-1398-40c5-94ec-a1b9b73ba900.png) 
![image](https://user-images.githubusercontent.com/55945790/197166994-1084dc0b-cbfe-4672-a735-b8cd95b62fa2.png)

2. Copy Editing 
![image](https://user-images.githubusercontent.com/55945790/197166575-3467f3f8-8d62-4df6-a4c0-ce913a4f4ede.png) 
![image](https://user-images.githubusercontent.com/55945790/197167107-dcedc524-d574-4d27-92c2-73722f192acc.png)

4. Topic Ideas Column 
![image](https://user-images.githubusercontent.com/55945790/197166700-12a0afa4-0230-4a69-a211-a55c7a08c0c7.png) 
![image](https://user-images.githubusercontent.com/55945790/197167252-0e172259-fc45-4808-b1ed-9e32de488c38.png)

5. 'Ready to create - you can help' column 
![image](https://user-images.githubusercontent.com/55945790/197166703-400d1599-16d8-4c6b-a621-4c57cc57760e.png) 
![image](https://user-images.githubusercontent.com/55945790/197167403-5e9caae2-526d-499b-a306-baf40b07a754.png)

# Error Report Checklist:
- [x] Error Validated
- [x] Error fix proposed
- [ ] Error fix reviewed
- [x] Error fix published

**Comment by pragyaasapkota** [comment]
@courtneyr-dev 
@bsanevans 
Please check this issue once.

**Comment by kaitohm** [comment]
Thanks for raising this! The issue is, since we updated the GitHub repo, there is no way to link to a specific column on [the project board](https://github.com/orgs/WordPress/projects/33/views/1?layout=board). I've improvised the searches a bit so that the relevant issues are highlighted when clicking on the links.
