### ISSUE TITLE
Gujarati Pattern Lesson Plan Block 

### ISSUE THREAD

**Issue by SagarLadani** [WordPress/Learn#1043]
I made PR [SagarLadani/learn/pull/1] to add the Gujarati version of the block pattern for the Lesson plans.

I used what we already use for the translation content.

Thanks.

**Comment by kaitohm** [comment]
@SagarLadani Could you create a new pull request where the base is the WordPress/Learn repository? We can then commit that for you.

**Comment by kaitohm** [comment]
We are moving away from Lesson Plans into using one new content types - Lesson. I'm closing this as it won't be needed in the near future.
