### ISSUE TITLE
Trabalhando com estilos globais / Styling Your Site With Global Styles - Tutorial (Brazilian Portuguese)

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1052]

**Comment by westnz** [comment]
Link to video: https://wordpress.slack.com/archives/C02RW657Q/p1666335917778679

**Comment by paulopmt1** [comment]
Another great video!

Only two small notes, not sure if we need to fix them:
- at 0:14, we have the text `Personalizar tipografía` with an unnecessary accent at `í`. It should be `Personalizar tipografia`
- at 1:15, we have a duplicity of the audio `Como podemos ver`

Both issues are small and don't affect the video quality.

**Comment by fellyph** [comment]
Thanks @paulopmt1,

I will have a look on it!

**Comment by fellyph** [comment]
Hi @westnz @paulopmt1,

Follow the [updated version](https://wordpress.slack.com/files/U15AUKVNU/F0499FKPD6Y/gereciamento_de_estilos_globais.mp4)

**Comment by paulopmt1** [comment]
Perfect @fellyph, good job!!

**Comment by westnz** [comment]
Ready to publish when you have time @fellyph 

Great work!

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/trabalhando-com-estilos-globais/
