### ISSUE TITLE
Online Workshop - What is SEO? (Search Engine Optimization)

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1054]
# Event Details
- Title: What is SEO? (Search Engine Optimization)
- Description: Come prepared to learn, and to share your knowledge, about the relationships between websites and search engines.
- Target Audience: Beginner Users
- Date: I'll host this session twice to cover multiple timezones
  - ~November 3rd ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/289326093/)) - co-host @amitpatel0702~ _recheduled_
  - November 26th  ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/289535930/)) - **Needs Co-host**
  - December 19th ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/289959827/)) - @amitpatel0702 will co-host
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by kaitohm** [comment]
Due to personal circumstances, I have had to reschedule this session. (Sorry, @amitpatel0702)

The issue description above lists information for the new session.

**Comment by amitpatel0702** [comment]
Hi @bsanevans, It's completely fine. I might not be able to co-host this event with you because it will be too early for me.

**Comment by kaitohm** [comment]
The slides for this session can be found here: https://docs.google.com/presentation/d/10LIrjHPibJ8QVvmvhvuNkv91onRhZWKInMFBdEF1FzU/edit?usp=sharing

**Comment by fikekomala** [comment]
Great job, Ben! I love the bot illustrations.

A few things that I noticed:

- No typo (yay!)
- Sometimes there are too many exclamation marks. (!! or !!!) 
- On the 20th slide, to make sure the case is all sentence case, change to 'Visibility settings'.

**Comment by amitpatel0702** [comment]
Hi @bsanevans, SEO is one of my favorite topics. Glad to see all the key slides. I am sure it is going to be an amazing Workshop.

I am ready to co-host with you on **December 19th**

**Comment by kaitohm** [comment]
@fikekomala Thank you for the review! I've made the changes you've suggested 😄

@amitpatel0702 Wonderful! I'll add you as a cohost for the 19th 🙌

**Comment by kaitohm** [comment]
The recording from the first session has been uploaded to WordPress.tv: https://wordpress.tv/2022/11/25/what-is-seo-search-engine-optimization/

I'll close the session completely once I've run the second session.

**Comment by kaitohm** [comment]
I hosted the second session and am closing this now as complete!
