### ISSUE TITLE
Pull presenter bio from .org profile

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#106]
The bio for the workshop presenter is currently pulled from local user data on the site. This means that each presenter needs to be added as a user on the site, and then we have to copy/paste their bio from their WordPress.org profile over. This solves the problem for now, but in the long-run, this will become increasingly time-consuming. It would be much better if the bio could be pulled dynamically from the .org profile.

From what I understand this isn't as easy as it sounds, but it would be really great to have it figured out.

**Comment by coreymckrill** [comment]
Fixed by #115
