### ISSUE TITLE
Update markup and styling for My Courses page

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#1060]
The My Courses page is generated by Sensei and can be viewed here: https://learn.wordpress.org/my-courses - this is a draft page, so you need to be logged in to view it.

The page shows all of the courses the logged-in user has enrolled in, with tabs to filter to only active or completed courses.

We need the course cards on this page to have the same styling as the course cards on [the courses page](https://learn.wordpress.org/courses/). Since the My Courses page is generated by Sensei, I'm not sure how much control we have over the markup, but we may be able to override it with a template in the theme. Either way, if that page can look like the rest of the courses, then we can use it.

**Comment by jonathanbossenger** [comment]
I'd argue there's no reason not to publish it now, and then update the styling after it's live. It's such a huge benefit to course learners, I'd prefer to ship it and iterate on it once it's available.

In order to make it useful, we would need to have this linked somewhere. Some ideas: 

- Next to the **View All Courses** link at the top of the list of courses on the home page
- Somewhere at the top of the [Courses page](https://learn.wordpress.org/courses/) page

**Comment by digitalchild** [comment]
I would agree with @jonathanbossenger the benefit to learners having easy access to this information far outweighs the need for a clean style.

**Comment by digitalchild** [comment]
We also need to add this page to navigation, somewhere that is obvious and easy for learners to find.

**Comment by jonathanbossenger** [comment]
> We also need to add this page to navigation, somewhere that is obvious and easy for learners to find.

I just noticed the menu at the top of the Learn site once you get past the home page. 

I checked, and this is just a regular classic menu, so it would just be a case of publishing the page, and adding it to that menu.

**Comment by jonathanbossenger** [comment]
FWIW this ticket can remain open if the page is published because it's asking for a visual update.

**Comment by hlashbrooke** [comment]
I have published the page now: https://learn.wordpress.org/my-courses

I'm hesitant to add it to the top menu, mostly because it means that the menu won't fit in the space provided for it. We could add it as a drop-down under 'Courses' though, but that will likely require some CSS to make it work.

That being said - that top menu is actually hard-coded in the theme and not coming from the dashboard - there is a saved menu in the dashboard, but it isn't being used.

My thoughts about where we could add a 'My Courses' link:
* Alongside the 'view all courses' link on the home page - only show it if the user is logged in
* Alongside the 'search courses' label on the courses archive page - only show if the user is logged in
* Potentially in a drop-down menu underneath the 'courses' menu item - that will require more CSS though, so likely more work than the other simple text links

**Comment by jonathanbossenger** [comment]
> I have published the page now: https://learn.wordpress.org/my-courses
Yay!

> Alongside the 'view all courses' link on the home page - only show it if the user is logged in
> Alongside the 'search courses' label on the courses archive page - only show if the user is logged in

I agree, these two seem to be the highest-value wins with the lowest requirements to implement.

**Comment by digitalchild** [comment]
> Alongside the 'view all courses' link on the home page - only show it if the user is logged in
> Alongside the 'search courses' label on the courses archive page - only show if the user is logged in

Agreed that these are the best areas without having to modify the menu/etc.

**Comment by digitalchild** [comment]
@jonathanbossenger 

I've started working on adding the "My Courses" links to the front page and the course archive page. 

Front page: 
![Learn_-_front_page](https://user-images.githubusercontent.com/909468/213618381-4f20fe10-bce9-4ae3-80f3-aaa22327c45f.jpg)

Course Archive: 

![Courses___Learn](https://user-images.githubusercontent.com/909468/213618448-5f93e0b6-f4ff-4964-b48c-a7069db474ed.jpg)

I have a couple of questions: 

1. What if any CSS framework/system is the website using? 
2. How can we import the other [learn.wordpress.org](https://learn.wordpress.org) content to work on other parts of the site? I did find the REST API endpoints for the pages and that imported successfully, but the courses did not and resulted in database errors. 

If there is any documentation on the CSS we are using, I can fix the spacing on the frontpage links. As I would prefer to not need to add unnecessary CSS just to fix this spacing issue.

**Comment by digitalchild** [comment]
I have added more spacing on the front page. @jonathanbossenger thoughts?

![Learn](https://user-images.githubusercontent.com/909468/214780272-12e22719-d342-4de2-9a2d-198416a36569.jpg)

**Comment by jonathanbossenger** [comment]
@digitalchild LGTM

I'll try to answer your earlier questions:

> What if any CSS framework/system is the website using?

AFAIK there's no framework in place, but the wporg-learn-2020 theme uses Sass which you can find in the CSS directory of the theme. There's a README.md file in that directory that discusses the structure.

> How can we import the other [learn.wordpress.org](https://learn.wordpress.org/) content to work on other parts of the site?

Unfortunately, this is not possible at this time. You can read more about the history of this [here](https://github.com/WordPress/Learn/issues/194) and [here](https://github.com/WordPress/Learn/issues/792). We might need to either update the current script or add a new script, to import course data.

What I usually do is just grab one of the smaller courses, and manually copy the course content into the local site.

**Comment by alexstine** [comment]
Related PR reviewed, approved, and merged. 👍

**Comment by adamwoodnz** [comment]
... and deployed 

> Related PR reviewed, approved, and merged. 👍

**Comment by adamwoodnz** [comment]
There is still work to be done on styling the cards, as mentioned in the description, so I've moved this back to `TODO`

**Comment by unprintedch** [comment]
I would love to try make it look right but in my local instal  it looks like that:
https://capture.dropbox.com/mPPgxwLvUXk97iE5

Is there something I should do?

**Comment by unprintedch** [comment]
I would like to give it a shot, but the my-courses page in my local install still empty.
What I did:

- Set it up in the sensei settings
- create a bunch of courses
- Started one with my admin account

And it still looks like this:
![Image](https://github.com/WordPress/Learn/assets/2622001/ec2f65f2-198d-47ca-99fa-21e1c3a3c396)

**Comment by jonathanbossenger** [comment]
@unprintedch thanks for asking about this. This is a small undocumented requirement of courses. For a course to be included on the front end, it needs to have a manual excerpt. So if you edit the course and enter a manual excerpt in the excerpt meta box, it should appear.

**Comment by unprintedch** [comment]
I did add them as "featured" but thanks

**Comment by unprintedch** [comment]
There actualy was default content in the excerpt (down the right sidebar right?)
They still not appear in the "my-courses" page.

**Comment by jonathanbossenger** [comment]
Hmmm, that's weird. I will test this out and get back to you.

**Comment by adamwoodnz** [comment]
On hold pending new designs being finalized.

**Comment by adamwoodnz** [comment]
Login form also needs styling in new theme

![Image](https://github.com/WordPress/Learn/assets/1017872/03e7f78c-0d81-4f41-9272-fa617c458a35)

**Comment by dd32** [comment]
Surfacing this change here

https://github.com/WordPress/Learn/issues/2538#issuecomment-2172223322
> Just noting that after noticing this ticket, I've removed the Login & Registration functionality from the My Courses page.
>
> I've replaced these forms with a button to the login page, and most login links on Learn should direct straight to the login form rather than to the My Courses page.
>
> The reason was two fold:
>
> 1. While login was respecting 2FA, it wasn't respecting some other custom functionality we have for logins
> 2. The registration form was bypassing the anti-spam functionality we have on the registrations, and user emails were not being validated.
>
> This does mean that the signup process for learn now has a bit more friction in the process, there may be some issues around account creation, if you hear about any of that, let me know in #forums in slack so we can figure out a way forward with that.
>
> The page when logged out is a lot more minimal now, and probably needs some descriptive text added to the page when logged out. That can be worked on with the new Theme I guess.
