### ISSUE TITLE
Using Create Block Theme to manage your Block Theme fonts - Tutorial

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1062]
# Topic Description
Create Block Theme has a fantastic new feature that enables theme developers to add external fonts to their block theme. Whether you want to download a font from Google fonts, or install a font you've downloaded elsewhere, Create Block Theme makes it painless to add them to your block theme.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- (Create Block Theme)[https://wordpress.org/plugins/create-block-theme/]

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [x] Tutorial submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Tutorial submitted to WPTV https://wordpress.tv/submit-video/
- [x] Tutorial published on WPTV
- [x] Tutorial is captioned https://make.wordpress.org/training/handbook/tutorials/tutorial-subtitles-and-transcripts/
- [x] Tutorial created on Learn.WordPress.org
- [x] Tutorial post is reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial announced to training team
- [x] Tutorial announced to creator
- [x] Tutorial announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/199719520-efd77226-b040-4b63-9445-b5bdfd54371a.mp4

**Comment by kaitohm** [comment]
I moved this to the review column. I hope that was ok 🙂

**Comment by jonathanbossenger** [comment]
Thanks, @bsanevans. The reason I have not moved this to be reviewed yet, is I'm waiting on some feedback from my other [Create Block Theme tutorial](https://github.com/WordPress/Learn/issues/1061) first, as this one follows directly on from that one.

I'm also waiting on any specific updates on the [dark theme colors](https://make.wordpress.org/training/2022/11/09/choosing-accessible-contrasting-dark-theme-colors-for-online-workshops-and-tutorial-videos/) post, as I may have to edit the other tutorial to use any new colors defined. Once I've done that, I'll feel happy to make this available for review.

So for now I've taken this out of the review cycle, and I'll add it when I've wrapped up the review on the other tutorial.

**Comment by pbking** [comment]
I have reviewed the video for technical accuracy and overall helpfulness and give it my 👍 .  It pares nicely with the Create Block Theme tutorial.

**Comment by westnz** [comment]
Excellent video tutorial.  Very clear, logical and informative. I think it is good to go.

**Comment by jonathanbossenger** [comment]
Published! https://learn.wordpress.org/tutorial/manage-your-block-theme-fonts-with-create-block-theme/

**Comment by courtneyr-dev** [comment]
Please review for WP 6.4

- https://make.wordpress.org/core/?p=108291#font-management-with-the-font-library
- https://github.com/WordPress/gutenberg/issues/53307
- https://github.com/WordPress/gutenberg/pull/53884

**Comment by courtneyr-dev** [comment]
[Font Management with the Font Library](https://make.wordpress.org/core/?p=108291#font-management-with-the-font-library)

**Comment by jonathanbossenger** [comment]
The Font Library has been moved to WordPress 6.5. Additionally, we should rather include this content when creating the [Intermediate Theme Developer learning pathway](https://github.com/WordPress/Learn/issues/2045).

**Comment by cynthianorman** [comment]
suggestion noted
