### ISSUE TITLE
Wrong URL on Code of Conduct page

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/Learn#1065]
Hi,

I have visited https://learn.wordpress.org/online-workshops/code-of-conduct/ page.  and I can't access the below link which is mentioned in License And Attribution section. 

Can someone fix it?
**This site can’t be reached**  =>  http://opensourcebridge.org/about/code-of-conduct/ 

Thank you.

**Comment by rohini-ranjanR** [comment]
You should try this link https://opensource.com/code-of-conduct.

**Comment by kaitohm** [comment]
This has been fixed. Thanks for pointing it out.
