### ISSUE TITLE
The key to locking blocks - Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1079]
# Topic Description
What is block locking and how does it work

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ] https://github.com/WordPress/Learn/issues/739

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [x] Tutorial submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [ ] Tutorial submitted to WPTV https://wordpress.tv/submit-video/
- [ ] Tutorial published on WPTV
- [ ] Tutorial is captioned https://make.wordpress.org/training/handbook/tutorials/tutorial-subtitles-and-transcripts/
- [ ] Tutorial created on Learn.WordPress.org
- [ ] Tutorial post is reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial announced to training team
- [ ] Tutorial announced to creator
- [ ] Tutorial announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/200721346-241ae091-840f-4fb6-ac9f-1572bb911bb7.mp4

**Comment by jonathanbossenger** [comment]
@westnz great video on block locking. I only have two pieces of suggested feedback.

1. At 1:55 to 2:39, you show how the remove and move buttons are not available on locked blocks, but the unlock option is, as you are still logged in as the admin user. It might therefore be useful to show this from a different user's perspective. Eg. create an `author` user, log in as that user, and show how "unlock", "delete", and "move" options are not available to that user.
2. At around 2:40 you mention the word pattern, but you've not mentioned this word before, so it might be clearer to say something like, "even if a group of blocks or a block pattern is locked down"

**Comment by westnz** [comment]
Thank you for the actionable feedback, Jonathan!

**Comment by amitpatel0702** [comment]
@westnz, I must say - an amazing tutorial on Block Locking. Following are my comments.
- As always, this tutorial is to-the-point and extremely helpful.
- Just a Suggestion - It would be every more better if you can explain somewhere that this **locking-unlocking** mechanism applies to Blocks & **Block patterns**

**Comment by westnz** [comment]
Thank you so much @amitpatel0702 👍

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/the-key-to-locking-blocks/
