### ISSUE TITLE
Creating a Call To Action

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1080]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/202589503-bb92e9a2-6ef5-4f16-9a61-795e41c75bf2.mp4

**Comment by fikekomala** [comment]
Great work @westnz! Everything is really easy to follow. Only one thing that I think is missing, in your last example, can you also add how to customize a block's background color?

**Comment by westnz** [comment]
Thank you for the feedback @fikekomala!

**Comment by Piyopiyo-Kitsune** [comment]
Does this need another review @westnz ?

**Comment by westnz** [comment]
I think it is good to go.  It will be published this week.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/creating-a-call-to-action/
