### ISSUE TITLE
Faculty Member Getting Started Guide needs an update

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1085]
Many of the links in the [Faculty Member Getting Started Guide](https://make.wordpress.org/training/handbook/faculty-program/faculty-member-getting-started-guide/) in the Training Team handbook point to the old GitHub project board, and need to be updated.

**Comment by Piyopiyo-Kitsune** [comment]
Working through these now.

**Comment by Piyopiyo-Kitsune** [comment]
The links have been updated to their new corresponding views. Closing this out :-)
