### ISSUE TITLE
Lesson Plans: In non-English, lessons in all languages are displayed, not only the selected language

### ISSUE THREAD

**Issue by akirk** [WordPress/Learn#1087]
## Description
When browsing the Lesson Plans in non-English, you don't only see the courses in your language, or in your language + English but also courses in any other language.

## Step-by-step reproduction instructions
1. Go to https://learn.wordpress.org/lesson-plans/?locale=de_DE (lesson plans in German)
2. There are courses in Nepali and other languages.

## Expected behaviour

See only courses in the selected UI language, and maybe English so that there is some content.

## Actual behaviour
There is content in all available languages.

## Screenshot

<img width="1000" alt="Screenshot 2022-11-10 at 10 38 07" src="https://user-images.githubusercontent.com/203408/201167257-b60ee941-e31d-467c-8c32-948167560bc1.png">

**Comment by pkevan** [comment]
I spotted the same thing when browsing the site, and was guessing that the sort order is by descending ID.

Some improvements to this could be to filter by language through the locale, or add a filter on the right for language (or maybe even default the filter to the user's language).

**Comment by adamwoodnz** [comment]
Thanks for raising, this will be fixed in https://github.com/WordPress/Learn/issues/1004
