### ISSUE TITLE
Display course metrics on the frontend

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#1089]
Sensei tracks number of learners, passing metrics, etc. natively, but since this is only available in the dashboard it is not public information. In the interests of transparency and openness, I think it would be a great idea to make this available on the frontend.

We could either do this on a dedicated page where all the courses are listed, or have it in the sidebar of each course. The sidebar option would be my preference.

The data we could probably make available is:
* Number of learners enrolled in the course
* Number of learners who completed the course (possibly displayed as a percentage of people who have completed it)
* The average grade received for the course as a whole
* The average number of days it took learners to complete the course

That data is all available in the dashboard already, so getting it out on the frontend will most likely be a matter of finding the right functions to get it and using them in the right place.

If anyone has a good reason why we _shouldn't_ make this data public, please say so! I only see it as a positive step, but there could be sides to this that I'm not seeing.

_Thanks to @mikemcalister for asking about this [on Twitter](https://twitter.com/mikemcalister/status/1592533666580004866)._

**Comment by courtneyr-dev** [comment]
Important to note we do not want to publicly reveal an individual's own score connected with their name.

**Comment by hlashbrooke** [comment]
@courtneyr-dev 100% - we must definitely avoid doing that. The metrics I'm proposing here are averages across all learners, so there won't be any personal or specific information in any of this.

**Comment by mikemcalister** [comment]
Huge +1 on this. As we're talking about adding more courses, it would be great to know what is and isn't working. It may also help inform the kind of educational content that can be generated outside of Learn, out in the community. The more content we can get on the new editor, the better!

**Comment by hlashbrooke** [comment]
Working on this in a PR: https://github.com/WordPress/Learn/pull/1135 - happy to take feedback!
