### ISSUE TITLE
Training Team Badges

### ISSUE THREAD

**Issue by azhiya** [WordPress/Learn#1094]
Please use this link to request a Training Team contributor Badge.
https://profiles.wordpress.org/associations/training-contributor/ 

If you would like a badge on your WordPress.org profile that acknowledges your contributions to the Training Team, you must meet the criteria: https://make.wordpress.org/training/handbook/getting-started/team-profile-badges/

Awarding of profile badges: There will be a monthly review of contributions, and badges will be awarded at that time. A list of the new profile badges awarded will then be posted on https://make.wordpress.org/training/. If you feel you have earned the badge but were not listed, please comment on that month’s blog post and include your [WordPress.org](https://wordpress.org/) username.

**Comment by azhiya** [comment]
https://wordpress.slack.com/archives/C02RW657Q/p1668735074536709?thread_ts=1668665288.875619&cid=C02RW657Q
Micah Wood is to be awarded a badge for facilitating more than 3 online workshops: https://wordpress.tv/speakers/micah-wood/ 
.org handle is wpscholar

**Comment by azhiya** [comment]
Robin (robinwpdeveloper) and Abid Hasan (abidhassan112) for Online Workshops. https://wordpress.slack.com/archives/C02RW657Q/p1668742120855639?thread_ts=1668665288.875619&cid=C02RW657Q

**Comment by azhiya** [comment]
Ben Evans (bsanevans) who facilitated a number of workshops https://wordpress.slack.com/archives/C02RW657Q/p1668816088180909?thread_ts=1668665288.875619&cid=C02RW657Q

**Comment by webtechpooja** [comment]
Harshit (hderashri) audited 3 lesson plans, wrote 2 recap notes, and helped with one lesson plan translation to Hindi (Indian) language

**Comment by meaganhanes** [comment]
Myself (meaganhanes) contributing as an Administrator of the Training Team / Faculty Team, reviewing and providing feedback on work created by others (slides, lesson plans, videos, etc).

**Comment by amitpatel0702** [comment]
I had a question - How can we check our own contributions in reviewing and other related activities?

I did co-hosting for online workshops and reviewed tutorials and assisted in Administrative work as well. Let me know if I fit for any contributor badge.

**Comment by ghost** [comment]
Applying for my contributor badge. I completed my 3rd co-hosting  workshop. I have worked with @Piyopiyo-Kitsune @wparasae @ndiego

**Comment by kaitohm** [comment]
I nominate @amitpatel0702 for the contributor badge. Amit has [co-hosted 5 workshops](https://github.com/WordPress/Learn/issues?q=mentions%3Aamitpatel0702+label%3A%22%5BContent+Type%5D+Online+Workshop%22), [authored meeting notes](https://make.wordpress.org/training/2022/10/19/training-team-meeting-recap-for-october-18-2022/), facilitated team office hours, and has contributed as a faculty member for 4+ months.

I'm not sure if any of these fit completely under the [current criteria for badges](https://make.wordpress.org/training/handbook/getting-started/team-profile-badges/), so I am nominating him to receive a badge for this condition:
> Other – the team may choose to award the badge for other contributions at the team’s discretion.

**Comment by robinwpdeveloper** [comment]
Can we reward below contributors with Training Contributor badges? 
They have done good job with the recent online workshops. 

WordPress usernames: `rudlinkon ` and `mahbubshovan `

Github Tickets:
[Linkon Miyan](https://github.com/rudlinkon) - [#1169](https://github.com/WordPress/Learn/issues/1169), [#1177](https://github.com/WordPress/Learn/issues/1177), [#1185](https://github.com/WordPress/Learn/issues/1185)
[Mahbub Shovan](https://github.com/mahbubshovan) - [#1148](https://github.com/WordPress/Learn/issues/1148), [#1169](https://github.com/WordPress/Learn/issues/1169), [#1177](https://github.com/WordPress/Learn/issues/1177)

**Comment by robinwpdeveloper** [comment]
Recently @Afrin29 co-hosted 3 online workshops. 
Did wonderful job.

WordPress username: `afrin29`

Github Tickets:
[Syeda Sanjida Afrin](https://profiles.wordpress.org/afrin29/): #1201 #1202 #1203

**Comment by azhiya** [comment]
@lada7042 what is your .org id?

**Comment by azhiya** [comment]
@amitpatel0702 what is your .org id?

**Comment by digitalchild** [comment]
Hello, I would like to have a badge added as a contributor of the training team. username is digitalchild

**Comment by amitpatel0702** [comment]
Hi @azhiya, My .org username is **[amitpatelmd](https://profiles.wordpress.org/amitpatelmd/)**

**Comment by azhiya** [comment]
Hi @digitalchild I can see that you've been doing some work with @bsanevans on https://make.wordpress.org/training/2022/11/26/project-thread-training-team-onboarding-paths/#comment-3623. Is that correct?

**Comment by jonathanbossenger** [comment]
Hi folks. 

Tomorrow marks [the 12-month anniversary](https://wordpress.slack.com/archives/C02RW657Q/p1643874365252439) of my official joining of the training team, and what a year it has been 😁 I'd like to formally ask for my Training Team Badge. 

My .org id is [psykro](https://profiles.wordpress.org/psykro/).

Thanks

**Comment by vagelisp** [comment]
Hello all, 

I would also like to apply for the badge; 
So far, I've hosted two workshops, co-hosted one, created a couple of videos and translated many lesson plans into Greek. I also worked on the theme's code and provided feedback where needed. I hope that's enough, if not no worries.

My WP profile is[ eboxnet](https://profiles.wordpress.org/eboxnet)

**Comment by mumtahinafaguni** [comment]
Hello all, 
Can we get rewarded with Training Contributor badges?
We've done the recent online workshops in Bangla On WooCommerce.

WordPress usernames: `faguni22`  and `onlykawshar` 

Github Tickets:
#1231 #1232 #1233

**Comment by webtechpooja** [comment]
@mumtahinafaguni 
Please request here for the badge:
https://profiles.wordpress.org/associations/training-contributor/
Thanks.

**Comment by jonathanbossenger** [comment]
@webtechpooja I tried posting a request there, but I received the following error message

```You need to define a component parameter to insert activity.```

**Comment by courtneyr-dev** [comment]
@coffee2code is the above way @webtechpooja suggested an option for us? Should that work?

**Comment by fuadragib01** [comment]
Hello everyone,
We have done 3 online workshop on Block Editor (Gutenberg) and requesting for Training Contributor badges.

WordPress usernames: `esratpopy` and `fuadragib`

Github tickets: #1295 #1296 #1297

**Comment by kaitohm** [comment]
Thank you for your contributions, @fuadragib01 ! Could you request a badge on this link? Thanks!
https://profiles.wordpress.org/associations/training-contributor/

**Comment by kaitohm** [comment]
@courtneyr-dev This link has been working until very recently for folks requesting badges. I've reached out to Jonathan directly to see if it was a local issue on his end.

**Comment by coffee2code** [comment]
> @coffee2code is the above way @webtechpooja suggested an option for us? Should that work?

@courtneyr-dev: Yes, the badge request link is a viable approach. I've tested it on a test account and did not encounter the issue @jonathanbossenger reported. It should be working.

**Comment by webtechpooja** [comment]
@jonathanbossenger already has a Training contributor badge. I assume that's why he is getting an error when requesting the badge.

He wants the Training team badge that needs to be requested here. 
[https://profiles.wordpress.org/associations/training-team ](https://profiles.wordpress.org/associations/training-team )

**Comment by jonathanbossenger** [comment]
> @jonathanbossenger already has a Training contributor badge. I assume that's why he is getting an error when requesting the badge.
> 
> He wants the Training team badge that needs to be requested here. [https://profiles.wordpress.org/associations/training-team ](https://profiles.wordpress.org/associations/training-team)

Correct, thanks for clarifying @webtechpooja.

This raises another question, is this the correct place to ask for both a "Training Contributor" and a "Training Team" badge? 

[EDIT] Ok, I see where I went wrong here, @webtechpooja replied to Fuad with the link to the `training contributor` association, and I thought that was the relevant link for `training team` given that this was the place to request the `training team` badge. 

To avoid further confusion, I'm going to suggest that we update the handbook to reflect this. https://make.wordpress.org/training/handbook/about/team-profile-badges/

**Comment by webtechpooja** [comment]
I think we no longer need this Github issue. We can update our Handbook page with association profile links where people can request a badge for the Training contributors and Training team.  Then we can close this issue.

**Comment by kaitohm** [comment]
The handbook has been updated with the new process: https://make.wordpress.org/training/handbook/about/team-profile-badges/
