### ISSUE TITLE
Learn WordPress Content Error Report - Ticket

### ISSUE THREAD

**Issue by chthonic-ds** [WordPress/Learn#1096]
# Error Description
- Content URL: https://learn.wordpress.org/lesson/editing-wordpress-data-records/

Just noting a small issue in Step 3 of the [Editing WordPress data records](https://learn.wordpress.org/lesson/editing-wordpress-data-records/) section of the Using the WordPress Data Layer course.

The code block in question (directly follows the sentence, "Let's update `EditPageForm` accordingly:"):

```
export function EditPageForm( { pageId, onCancel, onSaveFinished } ) {
    const page = useSelect(
        select => select( coreDataStore ).getEntityRecord( 'postType', 'page', pageId ),
        [pageId]
    );
    return (
        <div className="my-gutenberg-form">
            <TextControl
                label='Page title:'
                value={ page.title }
            />
            { /* ... */ }
        </div>
    );
}
```
At this point in the lesson `value={ page.title }` returns `[object Object]` for the TextControl's `value` attribute. However, the expectation set by the accompanying screenshot is the label will display correctly as a string.

When Step 4 has been completed `value={ page.title }` renders the label as expected (as explained by the sentence, _"the title of an Entity Record is an object, but the title of an Edited Entity record is a string_").

Removing that Step 3 screenshot would help clear up potential/my confusion here?

# Error Report Checklist:
- [ ] Error Validated
- [ ] Error fix proposed
- [ ] Error fix reviewed
- [ ] Error fix published

**Comment by hlashbrooke** [comment]
@adamziel Tagging you in here since you know this content better than anyone else.

**Comment by kaitohm** [comment]
@adamziel I see you responded to the issue above with an eyes emoji. Have you been able to look into this since then?

**Comment by adamziel** [comment]
Thank you for the ping @bsanevans! I lost sight of this issue – I will fix the content and report back.

**Comment by adamziel** [comment]
Sorry for the long wait! I've updated the Step 3 to use `page.title.rendered` which puts the correct value in the text field. On the upside, it works. On the downside, an astute reader might notice that and ask _Wait, what is that `.rendered` business?_ However, we're in Step 3 and it's explained in Step 4 just below so I think it's okay.

**Comment by kaitohm** [comment]
Thanks so much for the update, @adamziel ! I think your proposed fix is perfect here. As you say, it's explained in step 4. If folks find that confusing, we can come back and address that then 😉 

I'm closing this comment. Thanks @chthonic-ds for raising this!
