### ISSUE TITLE
Online Workshop - Image SEO Best Practices to Make Your Content Discoverable

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1097]
# Event Details
- Title: Image SEO Best Practices to Make Your Content Discoverable
- Description: In this Online Workshop, we’ll be looking at Image SEO best practices for WordPress sites. Come share your experiences, and questions, as we learn together how to prepare site images for better discoverability.
- Target Audience: Users
- Date: I'll be holding this session twice for different timezones
  - December 2, 2022 ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/289884278/)) - co-host: @vagelisp
  - December 8, 2022 ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/289957619/)) - co-host: @westnz 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by vagelisp** [comment]
Hi Ben, happy to help. Assign me as your co-host

**Comment by kaitohm** [comment]
Thanks, you're assigned @vagelisp !

**Comment by kaitohm** [comment]
Slides can be viewed here: https://docs.google.com/presentation/d/1YjyhGgGgDG9CrO3VonLoSkk67cpO56SMIgLkxkb74ow/edit?usp=sharing

**Comment by fikekomala** [comment]
I didn't find a typo on your slides, @bsanevans 👏

**Comment by amitpatel0702** [comment]
Hi @bsanevans,
The presentation seems to be amazing.

- It would be great if you can add using topic -  .webp format for optimizations.
- Placement of image topic and its impact on optimization and conversation.

I think slides are already enough to cover for a great workshop. Best luck Ben.

**Comment by kaitohm** [comment]
Thank you for feedback, @fikekomala @amitpatel0702 and @digitalchild ([in Slack](https://wordpress.slack.com/archives/C02RW657Q/p1669712586529129?thread_ts=1669704875.850019&cid=C02RW657Q)) 🙇🏻‍♂️

> It would be great if you can add using topic - .webp format for optimizations.

I touched a little on this in slide 17 👍 

> Placement of image topic and its impact on optimization and conversation.

Could you tell me more about this? I think placing an image at the top of the article helps for conversion. What other things should I keep in mind regarding placement for optimization?

**Comment by kaitohm** [comment]
The recording from the first session can be found here: https://wordpress.tv/2022/12/05/image-seo-best-practices-to-make-your-content-discoverable/

My Google slides are linked above. Here is a PDF of my slides I handed out on the day:https://drive.google.com/file/d/1d9Gk9CXzYcxnnUohOZv8NQ4BubXeAF9n/view?usp=share_link

I'll close this issue once I've conducted the second workshop on the 8th.
