### ISSUE TITLE
Integrate Meetings calendar plugin

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#11]
The Make Meetings calendar uses a custom plugin: https://make.wordpress.org/meetings/ - could we activate that on Learn? We could use it for the discussion group sessions to show when they'll be happening.

CC @tellyworth

**Comment by StevenDufresne** [comment]
@hlashbrooke Where would this live (ie: url)?

**Comment by hlashbrooke** [comment]
This would be on its own page at a URL like `learn.wordpress.org/discussion-groups` or similar.

**Comment by hlashbrooke** [comment]
I'm going to remove this from the next iteration milestone because we haven't decided how we want to proceed here yet.

**Comment by hlashbrooke** [comment]
Bumping this back up to high priority. Could we please install the meetings calendar plugin and activate it to be displayed at this URL: `learn.wordpress.org/social-learning`.

We will continue to use the meetup.com group for the social learning groups, but this page will display all of the events in the user's local timezone, which is impossible with meetup.com itself. We can also use this page to display additional information about the initiative, so it would be great if this was ap age we could edit in the dashboard (as opposed to being purely defined by the plugin with no editing option).

**Comment by hlashbrooke** [comment]
I did some digging and it looks like this plugin can be activated and it just works exactly as needed 🎉 

I have gone and done that and will test things out - I'll open a new issue if there are any styling or other integration needs here.
