### ISSUE TITLE
Applying Font Families via the Styles Interface - Lesson

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1100]
# IMPORTANT
**This lesson plan belongs to part of a greater course, [Extend a Low Code Block Theme](https://github.com/WordPress/Learn/issues/821) which depends on the completion of  [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631)**

**Please reach out to @jonathanbossenger (Jonathan Bossenger) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
The goal of this lesson is to learn how to apply Font Families via the Styles Interface.

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

## Review checklist

Reviewers: this is not an extensive list, but it would be helpful if you can keep the following questions in mind while reviewing.

1. Are there any spelling/grammar issues or anything that doesn't make sense?
2. Is the content technically correct?
3. Does the layering of information successfully build from lesson to lesson
4. Can you follow the steps outlined in the course
5. Does the lesson contain enough relevant links to documentation (WordPress documentation, or any other relevant documentation)

**Comment by westnz** [comment]
Review:
Clear examples are used, and the screenshots are spot on to help learners visually.

Should you maybe add a screenshot below this call-out block?
<img width="933" alt="image" src="https://user-images.githubusercontent.com/89751452/203454508-a5d9ec75-e08e-4c51-8aa5-624a51264ae0.png">

**Comment by jonathanbossenger** [comment]
> Should you maybe add a screenshot below this call-out block?

As folks who take this course are expected to have already completed part 1, it has [a section, with screenshots](https://learn.wordpress.org/lesson/saving-changes-to-global-styles/) on saving Global Styles. So we're building on that knowledge here.
