### ISSUE TITLE
Applying Font Families via theme.json - Lesson

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1101]
# IMPORTANT
**This lesson plan belongs to part of a greater course, [Extend a Low Code Block Theme](https://github.com/WordPress/Learn/issues/821) which depends on the completion of  [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631)**

**Please reach out to @jonathanbossenger (Jonathan Bossenger) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
The goal of this lesson is to learn how to apply font families via theme.json.

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

## Review checklist

Reviewers: this is not an extensive list, but it would be helpful if you can keep the following questions in mind while reviewing.

1. Are there any spelling/grammar issues or anything that doesn't make sense?
2. Is the content technically correct?
3. Does the layering of information successfully build from lesson to lesson
4. Can you follow the steps outlined in the course
5. Does the lesson contain enough relevant links to documentation (WordPress documentation, or any other relevant documentation)

**Comment by westnz** [comment]
Review:

The Heading appears twice:
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/89751452/203460931-46db7a12-0b02-45ad-901f-fd95ffa05864.png">

Very practical: "Now, let’s take what you’ve learned and use it to set up font families."

I don't see any assessments for the 'Custom Blocks in Block Themes' module, but I assume it is because of all the practical steps and examples that learners must test out.

**Comment by jonathanbossenger** [comment]
> I don't see any assessments for the 'Custom Blocks in Block Themes' module, but I assume it is because of all the practical steps and examples that learners must test out.

Note, most of the lessons are practical lessons, that learners must follow. But I had also not added any quizzes at the end of each module, by the time you reviewed. Those quizzes are now added. So there are practical steps included in most lessons (except those that are informational) and now quizzes to recap the content at the end of each module.

**Comment by jonathanbossenger** [comment]
> The Heading appears twice:

Good spot, fixed.
