### ISSUE TITLE
Registering a Block Pattern in a Theme - Lesson

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1102]
# IMPORTANT
**This lesson plan belongs to part of a greater course, [Extend a Low Code Block Theme](https://github.com/WordPress/Learn/issues/821) which depends on the completion of  [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631)**

**Please reach out to @jonathanbossenger (Jonathan Bossenger) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
The goal of this lesson is to learn how to register a block pattern in a theme

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

## Review checklist

Reviewers: this is not an extensive list, but it would be helpful if you can keep the following questions in mind while reviewing.

1. Are there any spelling/grammar issues or anything that doesn't make sense?
2. Is the content technically correct?
3. Does the layering of information successfully build from lesson to lesson
4. Can you follow the steps outlined in the course
5. Does the lesson contain enough relevant links to documentation (WordPress documentation, or any other relevant documentation)

**Comment by westnz** [comment]
Review:

The registering process has been explained very clearly and systematically!
