### ISSUE TITLE
Learn WordPress Content Error Report - Ticket

### ISSUE THREAD

**Issue by ockham** [WordPress/Learn#1113]
# Error Description
- Content URL: https://learn.wordpress.org/lesson-plan/create-a-basic-child-theme-for-block-themes/

There's currently no mention of Style Variations: A block theme's child theme will currently _not_ automatically include the parent's Style Variations. To have them included, the child theme's author will have to copy the parent theme's `styles/` directory.

Originally reported in WP.org support forums [here](https://wordpress.org/support/topic/unsuccessful-in-making-child-theme/). I've filed a Gutenberg [issue](https://github.com/WordPress/gutenberg/issues/45965) to change that behavior (i.e. to auto-include the parent's style variations), but for the time being, it'd be good to explain how to include them manually.

Per discussion with @jonathanbossenger, we might want to review the behavior of child themes for other block theme capabilities (e.g. template parts of block patterns) and add instructions (rather than focusing on style variations only).

# Error Report Checklist:
- [ ] Error Validated
- [ ] Error fix proposed
- [ ] Error fix reviewed
- [ ] Error fix published

**Comment by jonathanbossenger** [comment]
I think a good way forward here is to create additional separate content about block theme capabilities in a child theme

1. Child theme basics (already covered by https://learn.wordpress.org/lesson-plan/create-a-basic-child-theme-for-block-themes/)
2. Theme.json in child themes 
3. Templates and template parts in child themes
4. Patterns in child themes
5. Styles in child themes

**Comment by ockham** [comment]
Update, per https://github.com/WordPress/gutenberg/pull/46554, child themes now inherit their parent theme's style variations. We might close this issue (and potentially file a new one for the items @jonathanbossenger mentioned in https://github.com/WordPress/Learn/issues/1113#issuecomment-1324839997).

**Comment by nomad-skateboarding-dev** [comment]
# Error Validated
Error was discussed by @ockham and @jonathanbossenger . Block child themes now inherit parent theme's style variations.

## Proposed Fix
Close issue and follow up with @jonathanbossenger recommendations as proposed by @ockham

**Comment by kaitohm** [comment]
Thank you for the feedback. I'm closing this issue now and will follow up with Jonathan about opening a new issue for his other suggestions.

**Comment by kaitohm** [comment]
I've submitted the content ideas above here: https://github.com/WordPress/Learn/issues/1556
