### ISSUE TITLE
Add description and anchor links to course archive page

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#1114]
It would be great if the top of [the course archive page](https://learn.wordpress.org/courses/) included a quick description/intro of what the page is all about (this must still be written - I'll circle back to this issue with the text) as well as anchor links to each of the categories on the page. This will make page navigation a bit easier, as well as prevent the issue of people only seeing development courses above the fold and not scrolling down (which is an issue that has been reported anecdotally).

Here is an imperfect mockup I made in the inspector to show what I mean:
<img width="1083" alt="Screenshot 2022-11-23 at 11 12 40 AM" src="https://user-images.githubusercontent.com/1543143/203431968-d9352dd2-3695-4231-8737-8104f5a42db9.png">

**Comment by hlashbrooke** [comment]
Some text we could use (just from my own head, so I'm happy to be overruled):

> WordPress provides limitless ways for people to craft and grow their online presence. The content in these courses is delivered in multiple formats, with a focus on text and video, working towards practical learning objectives to help you become a better WordPress developer, designer, user, and contributor.

**Comment by kaitohm** [comment]
I love the idea, and the text looks fine, too @hlashbrooke
