### ISSUE TITLE
Creating new onboarding paths - Content Creator

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1120]
This issue tracks the creation of a new onboarding handbook page for **the Content Creator role**. Editors can view/edit the draft handbook page here: https://make.wordpress.org/training/wp-admin/post.php?post=20153&action=edit

A public preview will be provided once the page is ready for general feedback.

---

An overview of this project can be found on the Training Team's blog - [Project Thread: Training Team Onboarding Paths](https://make.wordpress.org/training/2022/11/26/project-thread-training-team-onboarding-paths/)

Links to GitHub issues of other pages being created as part of this project are listed below:
* #1253 
* Content Creator - this issue
* #1254 
* #1121 
* #1122 
* #1123 
* #1124

**Comment by kaitohm** [comment]
I love this, Pooja! 😄 

At the moment, under `Your first contribution!`, the guide links to the LearnWP Content Development GitHub board. When looking at that page, I see that the team now has additional project vies at the top that correspond to each stage of content development. So that new contributors aren’t confused, how about linking to this view instead?
https://github.com/orgs/WordPress/projects/33/views/20

**Comment by kaitohm** [comment]
This page is ready for public review: https://make.wordpress.org/training/?p=20153&post_type=handbook&preview=1&_ppp=f4f84194de

**Please leave your feedback here in GitHub by February 4th** 😃🙇🏻‍♂️

**Comment by nomad-skateboarding-dev** [comment]
This felt to me just about perfect reading through the instructions. I felt I had all the links and the answer to my questions without information and link overload. This was awesome! 😎

For myself, I start to get confused once there's more than two or three highlighted links that explain more about whats on the page l'm currently viewing. I will usually stop clicking links when I feel that way.

Questions I might have after reading is:
1. Who are the Subject Matter Experts? They are spoken about in the first paragraph but then not mentioned unless I follow [the faculty link here](https://make.wordpress.org/training/faculty-program-members/) 
2. If I'm a content creator, why is the first assignment the same as if I'm onboarding for editing? Is editing and content creation the same and will I be in the same training team if so?

**Comment by kaitohm** [comment]
Thank you for your great feedback, @nomad-skateboarding-dev ! Here's a preview of the updated document: https://make.wordpress.org/training/?p=20153&post_type=handbook&preview=1&_ppp=b4c7390c6f

> 1. Who are the Subject Matter Experts?

We've updated the page explaining what an SME is, and where folks can go to see who active SMEs are ✅

> 2. If I'm a content creator, why is the first assignment the same as if I'm onboarding for editing?

Good point! We've added the following paragraph to the `Your first contribution!` section to hopefully make this clearer. How does the following sound?

> Content creation takes time. Even experienced contributors can take hours to make a good piece of content. (Large content like courses can take weeks to complete!) So for your first contribution, we invite you to try a task that takes less time - reviewing content that is already published. When reviewing content, look at all the parts that make that piece of content - you'll be writing those parts soon, too!

**Comment by nomad-skateboarding-dev** [comment]
@bsanevans Sincerely welcome on the feedback!

And the added paragraph for first time content creators sounds really good. Nicely done!

**Comment by kaitohm** [comment]
This page has now been published: https://make.wordpress.org/training/handbook/getting-started/content-creator-onboarding/

You can find a summary of the entire project here: https://make.wordpress.org/training/2023/02/10/training-teams-new-onboarding-program-is-now-live/
