### ISSUE TITLE
Creating new onboarding paths - Editor

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1121]
This issue tracks the creation of a new onboarding handbook page for **the Editor role**. Editors can view/edit the draft handbook page here: https://make.wordpress.org/training/wp-admin/post.php?post=20155&action=edit

A public preview will be provided once the page is ready for general feedback.

---

An overview of this project can be found on the Training Team's blog - [Project Thread: Training Team Onboarding Paths](https://make.wordpress.org/training/2022/11/26/project-thread-training-team-onboarding-paths/)

Links to GitHub issues of other pages being created as part of this project are listed below:
* #1253 
* #1120 
* #1254 
* Editor - this issue
* #1122 
* #1123 
* #1124

**Comment by kaitohm** [comment]
This page is ready for public review: https://make.wordpress.org/training/?p=20155&post_type=handbook&preview=1&_ppp=22a6392379

**Please leave your feedback here in GitHub by February 4th** 😃🙇🏻‍♂️

**Comment by nomad-skateboarding-dev** [comment]
This was really good. Clear, concise, and welcoming. All the information I needed was there and easily understood. Great job! 👏

Question I might have:
In the last section, What's Next, the link that says 'Copy edit a lesson plan' read to me as if I would click that link to make a copy of 'edit a lesson plan'. 'Copy edit' might be unfamiliar to those new to editing?

**Comment by nomad-skateboarding-dev** [comment]
This was really good. Clear, concise, and welcoming. All the information I needed was there and easily understood. Great job! 👏

Question I might have:
In the last section, What's Next, the link that says 'Copy edit a lesson plan' read to me as if I would click that link to make a copy of 'edit a lesson plan'. 'Copy edit' might be unfamiliar to those new to editing?

**Comment by kaitohm** [comment]
I can see how that would be confusing. "Copy" removed 😀

**Comment by kaitohm** [comment]
This page has now been published: https://make.wordpress.org/training/handbook/getting-started/editor-onboarding/

You can find a summary of the entire project here: https://make.wordpress.org/training/2023/02/10/training-teams-new-onboarding-program-is-now-live/
