### ISSUE TITLE
Creating new onboarding paths - Subject Matter Expert

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1122]
This issue tracks the creation of a new onboarding handbook page for **the Subject Matter Expert role**. Editors can view/edit the draft handbook page here: https://make.wordpress.org/training/wp-admin/post.php?post=20156&action=edit

A public preview will be provided once the page is ready for general feedback.

---

An overview of this project can be found on the Training Team's blog - [Project Thread: Training Team Onboarding Paths](https://make.wordpress.org/training/2022/11/26/project-thread-training-team-onboarding-paths/)

Links to GitHub issues of other pages being created as part of this project are listed below:
* #1253 
* #1120 
* #1254 
* #1121 
* Subject Matter Expert - this issue
* #1123 
* #1124

**Comment by kaitohm** [comment]
This page is ready for public review: https://make.wordpress.org/training/?p=20156&post_type=handbook&preview=1&_ppp=afa3aafd40

**Please leave your feedback here in GitHub by February 4th** 😃🙇🏻‍♂️

**Comment by nomad-skateboarding-dev** [comment]
This was awesome! I had no questions after reading through and following the steps. Fantastic job! 😀🙌

**Comment by kaitohm** [comment]
This page has now been published: https://make.wordpress.org/training/handbook/getting-started/subject-matter-expert-onboarding/

You can find a summary of the entire project here: https://make.wordpress.org/training/2023/02/10/training-teams-new-onboarding-program-is-now-live/
