### ISSUE TITLE
Creating new onboarding paths - Administrator

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1123]
This issue tracks the creation of a new onboarding handbook page for **the Administrator role**. Editors can view/edit the draft handbook page here: https://make.wordpress.org/training/wp-admin/post.php?post=20157&action=edit

A public preview will be provided once the page is ready for general feedback.

---

An overview of this project can be found on the Training Team's blog - [Project Thread: Training Team Onboarding Paths](https://make.wordpress.org/training/2022/11/26/project-thread-training-team-onboarding-paths/)

Links to GitHub issues of other pages being created as part of this project are listed below:
* #1253 
* #1120 
* #1254 
* #1121 
* #1122 
* Administrator - this issue
* #1124

**Comment by kaitohm** [comment]
This page is ready for public review: https://make.wordpress.org/training/?p=20157&post_type=handbook&preview=1&_ppp=bfeb72fee3

**Please leave your feedback here in GitHub by February 4th** 😃🙇🏻‍♂️

**Comment by nomad-skateboarding-dev** [comment]
This was great! 🙂 (I even found something else to contribute to, validating error reports 🙌) I had no questions after reading this and following the links and steps.

**Comment by kaitohm** [comment]
This page has now been published: https://make.wordpress.org/training/handbook/getting-started/administrator-onboarding/

You can find a summary of the entire project here: https://make.wordpress.org/training/2023/02/10/training-teams-new-onboarding-program-is-now-live/
