### ISSUE TITLE
Creating new onboarding paths - Quick contributions

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1124]
This issue tracks the creation of a new onboarding handbook page **that guides new contributor to quick contributions**. Editors can view/edit the draft handbook page here: https://make.wordpress.org/training/wp-admin/post.php?post=20163&action=edit

A public preview will be provided once the page is ready for general feedback.

---

An overview of this project can be found on the Training Team's blog - [Project Thread: Training Team Onboarding Paths](https://make.wordpress.org/training/2022/11/26/project-thread-training-team-onboarding-paths/)

Links to GitHub issues of other pages being created as part of this project are listed below:
* #1253 
* #1120 
* #1254 
* #1121 
* #1122 
* #1123 
* Quick contributions - this issue

**Comment by kaitohm** [comment]
This page is ready for public review: https://make.wordpress.org/training/?p=20163&post_type=handbook&preview=1&_ppp=72605ead02

**Please leave your feedback here in GitHub by February 4th** 😃🙇🏻‍♂️

**Comment by nomad-skateboarding-dev** [comment]
I really like the idea of a 'quick' onboarding path!

This was clear, especially with the table. Well done! 🙌

Possible grammatical feedback:
1. Under "Find a task that interests you" , it reads, "clicking on the area of contribution 'in' the right". Should that be 'on the right'?
![Screenshot_20230124-222344](https://user-images.githubusercontent.com/78917704/214495767-da04ae80-d7a4-4ec1-b69d-e78b86d8e084.png)

**Comment by wparasae** [comment]
I really like this idea. I wonder if we could aggregate a list of quick contributions people have made/continue to make as possible examples? Put out a call in the training channel asking for things people have done in 30-60 minutes (or less) as quick, drive-by contributions? Clearly defined examples can be very powerful.

Finding a content error and clicking, "Let us know!" and sharing the issue is one great example.
_Fixing_ a content error in learn.wordpress.org is another powerful one that might be a quick fix on lesson plans and/or text-based courses. 

What others could we think of/collect?

**Comment by kaitohm** [comment]
@nomad-skateboarding-dev Thanks! "in" is now "on".

**Comment by kaitohm** [comment]
@wparasae Thanks for the input! I've updated the table for now so that folks know what task they'll be led to once they click on the links on the right.

I'll be publishing a post announcing the launch of the new onboarding paths in the next day or two. Let me send out a call for input to the team then with other "quick wins" they can think of. This is just version 1, and I look forward to filling this page out with more "quick wins" as people find them 😀

**Comment by nomad-skateboarding-dev** [comment]
@wparasae

Asking those who have already contributed what things they've done or could do in 30 to 60 minutes, I think that's a wonderful idea! One that would draw the most actionable feedback I believe. 

I also feel that checking the content errors, or recommending fixes, are really good first tasks! 

For myself, those are the only two things I've undertaken as a contributor recently where I felt completely sure about what I was doing right from the start.

**Comment by kaitohm** [comment]
This page has now been published: https://make.wordpress.org/training/handbook/about/quick-contributions-you-can-make-now/

You can find a summary of the entire project here: https://make.wordpress.org/training/2023/02/10/training-teams-new-onboarding-program-is-now-live/
