### ISSUE TITLE
Online Workshop - How to Join Core Release Party | Bangla

### ISSUE THREAD

**Issue by abid112** [WordPress/Learn#1128]
# Event Details
- Title: How to Join Core Release Party | Bangla
- Description: WordPress versions are released often and every time a release party happens. We will learn how to join a core release party and how to participate on released version testing.
We are encouraging people to join and participate on testing of the newly released WordPress versions.
- Target Audience: Bangla Speaking People
- Date: 29th November, 2022
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290015012/
- Host: Robin (@robinwpdeveloper), Linkon Miyan (@rudlinkon)
- Co-host: Abid Hasan (@abid112)
- Other info: This is an online localized mini workshop (via Zoom).

# Online Workshop Checklist:
- [ ✅ ] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [ ✅ ] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ✅ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ✅ ] Hold Online Workshop
- [ ✅ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by webtechpooja** [comment]
Wordpress.tv link - https://wordpress.tv/2022/11/29/how-to-join-core-release-party-bangla/
