### ISSUE TITLE
Starter Patterns - Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1129]
# Topic Description
Write a description of the topic here.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the workshop
- [ ] Tutorial submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [ ] Tutorial submitted to WPTV https://wordpress.tv/submit-video/
- [ ] Tutorial published on WPTV
- [ ] Tutorial is captioned https://make.wordpress.org/training/handbook/tutorials/tutorial-subtitles-and-transcripts/
- [ ] Tutorial created on Learn.WordPress.org
- [ ] Tutorial post is reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial announced to training team
- [ ] Tutorial announced to creator
- [ ] Tutorial announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by getdave** [comment]
This looks good. I'd be interested in producing some content on this topic.

**Comment by kaitohm** [comment]
Hi @getdave ! Has there been any progress on this?

**Comment by getdave** [comment]
> Hi @getdave ! Has there been any progress on this?

Unfortunately not. I've been heavily focused on contributing to Gutenberg Core during this 6.2 cycle.

**Comment by kaitohm** [comment]
No problem 👍  If you'd like us to release the assignment so that others could potentially take this on, let us know. If you'd still like to work on it, we would love for you to do that, too. No pressure either way 😃

**Comment by getdave** [comment]
@bsanevans I can't see me getting to it in the near future. Apologies for that. Feel free to release 😢

**Comment by kaitohm** [comment]
Absolutely no problem, @getdave ! Feel free to come and work on something again in the future, when you have time 🙌

**Comment by kaitohm** [comment]
Closing, due to not enough information. 

If you'd still like to see this content created, please create [a new Topic Idea issue](https://wordpress.slack.com/archives/C03B11FA16D/p1688486841217239?thread_ts=1687827128.413619&cid=C03B11FA16D) and fill out the information listed.
