### ISSUE TITLE
Gujarati translation for Lesson Plan "Locking Blocks in the Full Site Editor"

### ISSUE THREAD

**Issue by SagarLadani** [WordPress/Learn#1130]
# Details
- Link to original content: [https://learn.wordpress.org/lesson-plan/locking-blocks-in-the-full-site-editor/](https://learn.wordpress.org/lesson-plan/locking-blocks-in-the-full-site-editor)
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes or No - No
- Reviewer's GitHub username: Reviewer needed (looking for a volunteer who can review my content in Gujarati)
- Other info: Google doc link -
[https://docs.google.com/document/d/1zkMPpDUlkiR2UXlsaB_2EQTj47jlBqFBgWSA16X6f88/edit?usp=sharing](https://docs.google.com/document/d/1zkMPpDUlkiR2UXlsaB_2EQTj47jlBqFBgWSA16X6f88/edit?usp=sharing)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
@vanpariyar Are you able to review this translation for the team, please?

**Comment by kaitohm** [comment]
@iamchetanp Are you able to review this?

**Comment by vanpariyar** [comment]
Hello @SagarLadani

The translation looks good to me, but we need to find a good word for Lock in Gujarati since I can also not find a good word that I can approve from my side.

CC: @bsanevans

**Comment by kaitohm** [comment]
Hmm, I tried looking for a translation in the consistency tool, but nothing showed up... https://translate.wordpress.org/consistency/?search=lock&set=gu%2Fdefault&project=

How is Lock translated in the Block Editor interface? Does it still show up in English, even when the dashboard language is set to Gujarati?

**Comment by vanpariyar** [comment]
When we set the language to Gujarati it still shows the Lock in english.

![SCR-20230711-j55](https://github.com/WordPress/Learn/assets/26689210/1c196cf0-5af9-41fc-9e2a-e02a5ba0e0b6)

**Comment by kaitohm** [comment]
Hmm... I'll leave it up to you two to decide on the best translation. I think we should publish this as-is then, and we can always come back and change the translation later if someone comes up with a better word.

@SagarLadani Here's a copy Lesson Plan you can move the translation into: https://learn.wordpress.org/wp-admin/post.php?post=40819&action=edit

If it would be better for @vanpariyar to copy the content across, I can reassign the post to Ronak, too. Just let me know 👍

**Comment by vanpariyar** [comment]
Hello @bsanevans 
https://learn.wordpress.org/wp-admin/post.php?post=40819&action=edit

I do not have access to the same. User name is ( `vanpariyar` )

**Comment by kaitohm** [comment]
I've updated the author and you should have access now. Thanks @vanpariyar 😃

**Comment by vanpariyar** [comment]
Hello @bsanevans Just added translated content on the [post](https://learn.wordpress.org/wp-admin/post.php?post=40819&action=edit)  PLeaase review if there is any information is missing.


Note curretly this post is in draft mode, Handing over to you for Publishing this post. https://learn.wordpress.org/wp-admin/post.php?post=40819&action=edit

**Comment by kaitohm** [comment]
Thanks, Ronak. This lesson plan is now published: https://learn.wordpress.org/lesson-plan/gu-locking-blocks-in-the-full-site-editor/

Thank you for the initial translation, too, Sagar!
