### ISSUE TITLE
Gujarati translation for Lesson Plan "Create a Basic Child Theme for Block Themes"

### ISSUE THREAD

**Issue by SagarLadani** [WordPress/Learn#1137]
# Details
- Link to original content: [https://learn.wordpress.org/lesson-plan/create-a-basic-child-theme-for-block-themes/](url)
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes or No - No
- Reviewer's GitHub username: Reviewer needed (looking for a volunteer who can review my content in Gujarati)
- Other info: Google doc link -
[https://docs.google.com/document/d/103ArifHEaIMszTKhztNepZudasws50bya0S_DzC5DVs/edit#](https://docs.google.com/document/d/103ArifHEaIMszTKhztNepZudasws50bya0S_DzC5DVs/edit#)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by ronak-multidots** [comment]
Hello Sagar 
I have read whole document, I think there is some need for improvement in some wording.

like `Differentiate between parent & child themes and explain their benefits` to `મુખ્ય અને બાળના વિષય વચ્ચે તફાવત કરો અને તેમના ફાયદા સમજાવો` but that does not seem we are using in the day to day life.

we can choose diffrent word for the `child theme` 🤔

**Comment by SagarLadani** [comment]
@ronak-multidots Thanks for your suggestion, I have updated the changes. Please review them.

**Comment by vanpariyar** [comment]
Thanks @SagarLadani for those changes. 

@amitpatel0702 from my side it is good to go.

**Comment by virallmehta** [comment]
Hello @SagarLadani 
How about this word Child theme with અનુયાયી થીમ

**Comment by sagarladani-multidots** [comment]
Thanks @virallmehta for your review I have also shared this document with some of the translation editors. We decided to go with "ચાઈલ્ડ થીમ" word because it is more relevant. Let me know if you have any thoughts about this.

**Comment by virallmehta** [comment]
Thanks @SagarLadani I am ok with it, sounds more relevant "ચાઈલ્ડ થીમ"

**Comment by Piyopiyo-Kitsune** [comment]
Is this ready to be published, friends? :-)

**Comment by ronak-multidots** [comment]
@Piyopiyo-Kitsune From my review, it is ready to be published.

**Comment by kaitohm** [comment]
This issue fell through the cracks for some reason 😱 

@SagarLadani I've created a draft post here: https://learn.wordpress.org/wp-admin/post.php?post=40153&action=edit
Could you copy the translation across, then let me know so that I can publish this? 🙇‍♂️

**Comment by SagarLadani** [comment]
Hello @bsanevans I have added my translation content on this draft page.

**Comment by kaitohm** [comment]
Thank you! I've now published this: https://learn.wordpress.org/lesson-plan/gu-create-a-basic-child-theme-for-block-themes/
