### ISSUE TITLE
Learn WordPress Content Error Report - Ticket

### ISSUE THREAD

**Issue by jomarieminney** [WordPress/Learn#1145]
# Error Description
- Content URL: [A Developers Guide to Block Themes – Part 1](https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-1/)

The following text needs to be updated to reflect the newly released part 2 in the first callout:
"Part 2 is coming soon, which will cover more advanced block theme development topics."

Suggested updated text in callout for second sentence:
"Part 2, which covers more advanced block theme development topics, can be found here: (link)"

# Error Report Checklist:
- [x] Error Validated
- [x] Error fix proposed
- [x] Error fix reviewed
- [ ] Error fix published

**Comment by kaitohm** [comment]
Thanks for reporting. This suggested fix looks good to me.

@jonathanbossenger Would you like to make the update, as the author of the course?

**Comment by jonathanbossenger** [comment]
Thanks folks, this is something on my todo list this week (updating any references to part 2, now that it was published last week)

**Comment by jonathanbossenger** [comment]
Updated.
