### ISSUE TITLE
Online Workshop - How to Test (with Report) a Core Trac Ticket | Bangla

### ISSUE THREAD

**Issue by abid112** [WordPress/Learn#1148]
# Event Details
- Title: How to Test (with Report) a Core Trac Ticket | Bangla
- Description: Testing a core trac ticket is a great way to start contribution on WordPress Core.
In this (mini) online workshop, we will demonstrate on how to contribute with testing on WordPress Core.
Attendees will get an idea of which tickets to test from WordPress core and what is the right way to test and share report on a Trac ticket.
This is a localized (Non English) online workshop.
- Target Audience: Bangla Speaking People
- Date: December 5, 2022
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290053068/
- Host: Robin (@robinwpdeveloper), Abid Hasan (@abid112)
- Co-host: Mahbub Shovan ( @Mahbubshovan )
- Other info: This is an online localized mini workshop (via Zoom).

# Online Workshop Checklist:
- [✅] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [✅] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [✅] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [✅] Hold Online Workshop
- [✅] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [✅] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by abid112** [comment]
WordPress.tv link - https://wordpress.tv/2022/12/08/how-to-test-with-report-a-core-trac-ticket-bangla/

**Comment by robinwpdeveloper** [comment]
[Mahbub Shovan (@mahbubshovan)](https://github.com/mahbubshovan) was co host of this workshop

**Comment by robinwpdeveloper** [comment]
Marking as completed.
