### ISSUE TITLE
Learn WordPress Content Error Report - All about templates Quiz

### ISSUE THREAD

**Issue by porg** [WordPress/Learn#1157]
# Error Description
- Content URL: [All about templates Quiz](https://learn.wordpress.org/quiz/all-about-templates/)

> When would you use templates? Select all that apply.
- "Creating a product landing page." is marked as a true answer.
- This is factually wrong.
  - In order to create a product landing page, I do not necessarily need to create a custom template.
  - I could simply create a new page of the content type "post" and fill it with product content, and as such designate it as a product landing page.
- Proposing an answer more in the direction of:
  - I want to create a product landing page whose presentation structure has custom requirements.

# Error Report Checklist:
- [x] Error Validated
- [x] Error fix proposed
- [ ] Error fix reviewed
- [ ] Error fix published

**Comment by bradley-mubenga** [comment]
Helping to validate content feedback.

**Comment by bradley-mubenga** [comment]
The solution to this issue would be to rephrase the multiple-choice option _"Creating a product landing page"_  in question 3 with  _"Creating a custom presentation structure for a product landing page"_. This will clarify why the user must use a template to create a product landing page.

**Comment by porg** [comment]
Correct. This added differentiation makes the answer logically true.

**Comment by kaitohm** [comment]
Thank you for the feedback! I have updated the multiple-choice option to reflect the above suggestion.

**Comment by bradley-mubenga** [comment]
Whoohoo! I have officially contributed to WordPress! What an adventure! Thanks @bsanevans

**Comment by kaitohm** [comment]
Congratulations, @bradley-mubenga ! 

The Training Team is still figuring out how to improve the Content Feedback Triage process. The access thing is a complicated thing to get around. If you're looking for another way to easily contribute, then I recommend [reviewing content before it is published](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/#are-you-reviewing-content-before-it-is-published). This also uses GitHub, but there's no special access required for that 😉 

Thank you for contributing 🌟
