### ISSUE TITLE
Online Workshop - Creating a Theme with the Create Block Theme Plugin Session 1

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1161]
# Event Details
- Title: Creating a Theme with the Create Block Theme Plugin Session 1
- Description: As of this event posting there are 190 Block Themes in the WordPress.org library. As WordPress advances to a more code-less (as in no need to use code) future, the ability to create and design themes is being made simpler and more accessible.

In this session we will explore how to create your very own theme using the [Create Block Theme plugin](https://wordpress.org/plugins/create-block-theme/).
- Target Audience: Intermediate WordPress users-- folks who are familiar with the Site Editor and using Blocks and Block Themes.
- Date: Thursday, December 22, 2022 at 9:00 AM to Thursday, December 22, 2022 at 10:00 AM JST
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290170454/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by kaitohm** [comment]
I'm interested in this content, and would love to co-host.

**Comment by Piyopiyo-Kitsune** [comment]
https://wordpress.tv/2022/12/22/creating-a-theme-with-the-create-block-theme-plugin/
