### ISSUE TITLE
Add 'apply to present' button to Tutorial archive header

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#1165]
The online workshops header includes the 'apply to facilitate' button - it would be great if we could add the same kind of thing to the tutorials header to appear below the search box. It should link to the presenter application form: https://learn.wordpress.org/tutorial-presenter-application/

**Comment by adamwoodnz** [comment]
Closing as Tutorials are no longer a core part of the Learn WordPress information architecture, and have become Lessons. Please reopen if there's a desire to do this for Lessons.
