### ISSUE TITLE
How to improve your SEO rankings - Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1167]

**Comment by westnz** [comment]
Based on the wonderful work done by @bsanevans  

[Online Workshop - What is SEO? (Search Engine Optimization)](https://github.com/WordPress/Learn/issues/1054)
[Online Workshop - Image SEO Best Practices to Make Your Content Discoverable](https://github.com/WordPress/Learn/issues/1097)

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/206352909-7f9ab2c9-c009-4d94-b6da-f635e412e342.mp4

**Comment by kaitohm** [comment]
Wow, you packed a lot of information in! I love the idea of taking Online Workshop content and using that to build Tutorials.

I reviewed this, and it looks good 👍🏼

**Comment by ghost** [comment]
A good resource for SEO. I watched Ben's presentation and this tutorial and you were able to take the key points and present them in an understandable way with the amount of time you had. I like showing a key point and then showing a real example. I think you could have used the full 10 min. haha

**Comment by westnz** [comment]
Thank you very much Ben and Laura! Kudos to @bsanevans for presenting these Online Workshops and sharing his resources. Go team!

**Comment by jonathanbossenger** [comment]
Great tutorial @westnz

**Comment by westnz** [comment]
Thank you @jonathanbossenger

**Comment by wparasae** [comment]
I really like how carefully you picked your graphics, Wes. No feedback, but I love this idea of making tutorials from online workshops! Well done! No suggested changes.

**Comment by westnz** [comment]
Thank you so much @wparasae

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/how-to-improve-seo-rankings/

**Comment by westnz** [comment]
Updated and added to the Beginner User learning pathway.

**Comment by westnz** [comment]
Notes for future update, thank you @kathrynwp 
- 0:13: Capitalize the E and the O, I think (edited) 
- 0:34:caption* should read “investigate” (not “investigates”)
- In this section, is it worth mentioning that this process of search engines sending bots to your site and analyzing it is also called “indexing” or “spidering” a site? You mentioned crawling, it could even be “once they are done crawing – or indexing – your site, bots…” That way when you show the setting for allowing “indexing” of the site, you’ve already mentioned the term previously
- 5:16: Small clarification: meta descriptions aren’t always what appears in search results… the text below the title in search results is called a “search snippet.” If a page or post has a “meta description” tag, search engines might display those as the search snippet in its results, but not always. If it thinks that a piece of text from the page or post is a better snippet, it might pull that and use it in search results, ignoring the meta description. And if a page or post doesn’t have a meta description tag at all, it will do the same thing – use its own judgement about what to display as the search snippet.
More about snippets from Google - https://developers.google.com/search/docs/appearance/snippet
- 5:45: WP doesn’t generate meta descriptions on its own. WordPress.com does use the post excerpt to create a meta description, but I think you need an SEO plugin for post, page, and site meta descriptions on a self-hosted site? (I think you were actually referring to search snippets here.) Unless your post excerpt is displayed somewhere on the front end of your site, I don’t think it will appear anywhere in the code that search engines can see it.
- 8:14: most sites do not display the image description anywhere at all, so I wouldn’t advise people to spend time adding them. (I think the only spot where it might be displayed anywhere is the image attachment page, which most people don’t even want to be indexed in search engines)
- 9:00: you mention most SEO plugins generate sitemaps for you automatically, but… is this the first time you’ve brought up SEO plugins? Do you want to add something earlier about how plugins can add extra SEO-related functionality but don’t in and of themselves “optimize” your site, that work still needs to be done by you.
- About the image-optimization section - you might want to add something about WebP, a modern image format that loads faster than traditional formats. (Not sure what WP currently does around this format or if you still need a plugin, and whether all browsers support it or not)
