### ISSUE TITLE
Gujarati translation for Tutorial "Getting to know the WordPress Dashboard"

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1168]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/getting-to-know-the-wordpress-dashboard/
- Translator: Ronak Vanpariya
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username:
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by vanpariyar** [comment]
I have done my first translation sharing google docs below 👇🏼 

https://docs.google.com/document/d/1ChlVfcUJMAp3wnYLM15ERn6aL5ygoOetbG_Tv9wZ-s8/edit?usp=sharing



I would like to get review from @amitpatel0702 @SagarLadani

**Comment by amitpatel0702** [comment]
Hi @vanpariyar

Thanks for your great efforts. Here are my inputs

- Correction for words **WordPress journey** -  વર્ડપ્રેસ યાત્રા
- Correction for word **elements** - તત્વો
- Correction for words **front-end of my site**
- Correction for word **wordpress.org**
- Correction for words **All the best as you start exploring and using WordPress**
- Correction for word **access** 

Thanks.

**Comment by vanpariyar** [comment]
Hello @amitpatel0702 
Thanks for your detailed review.

I have corrected  all of the suggestions that you provided.

**Comment by Piyopiyo-Kitsune** [comment]
Please let me know if this is ready to be published now.

**Comment by SagarLadani** [comment]
It looks good to me.

**Comment by ronak-multidots** [comment]
Just to confirm here, I have just translated the transcript.

no subtitle, and no Video voice.

**Comment by amitpatel0702** [comment]
Hi @ronak-multidots I noticed your 2 GitHub accounts. Please confirm on the same.

Also it would be great if you can also translate and create captions for the video. We can count full tutorial translation.

**Comment by vanpariyar** [comment]
please confirm @vanpariyar is the account we will use for contribution.

**Comment by sagarladani-multidots** [comment]
@vanpariyar, I suggest you refer to [this](https://learn.wordpress.org/tutorial/gerenciando-atualizacoes-no-wordpress/) example and make it the same as it is.

**Comment by SagarLadani** [comment]
@vanpariyar, I suggest you refer to [this](https://learn.wordpress.org/tutorial/gerenciando-atualizacoes-no-wordpress/) example and make it the same as it is.

**Comment by vanpariyar** [comment]
For translating the caption, Do I need edit access to a tutorial?

**Comment by kaitohm** [comment]
@vanpariyar I've updated the team handbook page to show how to translate subtitles. Please see this guide: https://make.wordpress.org/training/handbook/content-localization/translating-subtitles/

Once the translations are ready, please share them here for others to review. Thanks 🙌

**Comment by vanpariyar** [comment]
Hello @bsanevans 

The translation of the caption is uploaded on this video of WordPress.tv
https://wordpress.tv/2022/05/19/getting-to-know-the-wordpress-dashboard/

**Comment by vanpariyar** [comment]
@SagarLadani @amitpatel0702 

Please review my translation here of [translations](https://gist.githubusercontent.com/vanpariyar/2ab224a6eceb81c4c0e08b04dbdf73e9/raw/bf85d82e3985df9e1334b729f3c5eb216d165b6e/gujarati-caption-getting-to-know-the-wordpress-dashboard.ttml)

**Comment by kaitohm** [comment]
@vanpariyar Thank you for submitting subtitles. I've approved those ✅ 

I've upgraded your access on https://learn.wordpress.org to "Contributor". Could you edit the following Tutorial by removing the English and pasting your Gujarati translation instead? Once done, let me know, and I can publish this for you 😃 
https://learn.wordpress.org/wp-admin/post.php?post=34169&action=edit

**Comment by vanpariyar** [comment]
Hello, @bsanevans thank you for reviewing. I just added the content and save it as a draft.

Thank You.

**Comment by kaitohm** [comment]
Yay! This has now been published: https://learn.wordpress.org/tutorial/gu-getting-to-know-the-wordpress-dashboard/
I'm going to close this out. But if anyone reviews and notices any changes that need to be made, feel free to submit a content feedback report from https://github.com/WordPress/Learn/issues/new/choose

Thank you for your contribution, @vanpariyar 🎉
