### ISSUE TITLE
Online Workshop - EP1: WordPress Environment Setup (Local WP & Laravel Valet) | Bangla

### ISSUE THREAD

**Issue by rudlinkon** [WordPress/Learn#1169]
# Event Details
- Title: EP1: WordPress Environment Setup (Local WP & Laravel Valet) | Bangla
- Description: In this episode we will show various ways of WordPress Environment setup.
First we will demonstrate Local WP and then we will show how to install Laravel Valet on Mac.
This is a localized (Non English) online workshop.

- Target Audience: Bangla Speaking People
- Date: December 12, 2022
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290171648/
- Host: Linkon Miyan (@rudlinkon), Abid Hasan (@abid112)
- Co-host: Mahbub Shovan (@mahbubshovan)
- Other info: This is an online localized mini workshop (via Zoom).

# Online Workshop Checklist:
- [x] ✅ Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] ✅ Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] ✅ Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] ✅ Hold Online Workshop
- [x] ✅ Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] ✅ Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by rudlinkon** [comment]
WordPress.tv link - https://wordpress.tv/2022/12/12/wordpress-environment-setup-local-wp-laravel-valet-bangla/

**Comment by robinwpdeveloper** [comment]
Marking as completed.

**Comment by robinwpdeveloper** [comment]
https://github.com/mahbubshovan was co host

**Comment by robinwpdeveloper** [comment]
Marking as completed
