### ISSUE TITLE
Gujarati translation for Lesson Plan "Dashboard Overview"

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1170]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/dashboard-overview/
- Original content GitHub issue: https://github.com/WordPress/Learn/issues/423
- Language you'll be translating to: Gujarati
- Translator: Sadar Ladani
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username:
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by SagarLadani** [comment]
I have done my first translation sharing google docs below 👇🏼

[https://docs.google.com/document/d/1aToxZ6UU-RxfZdNAuEe15fqD1PZskcKJg8URvWU6-G4/edit#](https://docs.google.com/document/d/1aToxZ6UU-RxfZdNAuEe15fqD1PZskcKJg8URvWU6-G4/edit#)

I would like to get review from @amitpatel0702 @vanpariyar and @virallmehta

**Comment by vanpariyar** [comment]
It looks good to me 👌🏼.

**Comment by amitpatel0702** [comment]
Thanks @SagarLadani.

- The translation sounds good.
- If possible can you please execute side-by-side formatting and highlighting headings to bigger font and bolder ones?

**Comment by amitpatel0702** [comment]
Thanks @SagarLadani.

- The translation sounds good.
- If possible can you please execute side-by-side formatting and highlighting headings to bigger font and bolder ones?

**Comment by Piyopiyo-Kitsune** [comment]
Preview ready: https://learn.wordpress.org/?p=27470&post_type=lesson-plan&preview=1&_ppp=1539ade84a

Please approve for publication

**Comment by Piyopiyo-Kitsune** [comment]
Published - https://learn.wordpress.org/lesson-plan/gu-dashboard-overview/

**Comment by SagarLadani** [comment]
Everything is fine and I have published the lesson plan. Take a look at this [https://learn.wordpress.org/lesson-plan/gu-difference-between-reusable-blocks-block-pattern-templates-template-parts/](https://learn.wordpress.org/lesson-plan/gu-difference-between-reusable-blocks-block-pattern-templates-template-parts/)
