### ISSUE TITLE
Language meta field not being saved correctly on tutorials

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#1172]
When saving a new tutorial, the default language is set to 'English', so we would naturally leave it unchanged for new tutorials in English. However, it doesn't seem to save the language properly to the post meta. This causes a problem where the tutorial doesn't show up in the archive after saving because the archive query checks that the language meta field has been set.

The fix is to change it to any other language, save the post, change it back to English, and then save the post again. It's easy to work around, but also easy to forget and quite an annoying issue.

**Comment by adamwoodnz** [comment]
Possible cause:

> My guess would be the default value isn’t explicitly set in the DB, just displayed on screen when the DB value is empty. But the SQL query requires it to be actually set.

**Comment by westnz** [comment]
It would be great if this bug could be fixed, as our last three tutorials are not showing up.

**Comment by westnz** [comment]
I have just used Hugh's 'hack' to make them show up :-)
