### ISSUE TITLE
Gujarati translation for Lesson Plan "Pages vs. Posts"

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1173]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/pages-versus-posts/
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username:
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by amitpatel0702** [comment]
I have executed Gujarati translation shared in the google docs link below 👇🏼

[https://docs.google.com/document/d/1xbfFsHe6HrMsBcQYdePank_rWH9l7DtIc6xIlBxAcY8/edit?usp=sharing](url)

I would like to get review from [SagarLadani](https://github.com/SagarLadani) and [vanpariyar](https://github.com/vanpariyar)

**Comment by Piyopiyo-Kitsune** [comment]
Preview ready: https://learn.wordpress.org/?p=27480&post_type=lesson-plan&preview=1&_ppp=7260d86279

Please approve for publication

**Comment by vanpariyar** [comment]
I think this looks good to me. I am approving this content as per my knowledge.

**Comment by ronak-multidots** [comment]
I am not sure for,
One thing I want to add here is links that need to be added for this draft for reference and theme at the end of articles because the original content has links available.

**Comment by vanpariyar** [comment]
I am not sure for,
One thing I want to add here is links that need to be added for this draft for reference and theme at the end of articles because the original content has links available.

**Comment by Piyopiyo-Kitsune** [comment]
@vanpariyar I have added you as an Author on the Learn website-- can you kindly let me know when you've accepted the invite so I can add you as an author of this post? That will allow you to edit the post directly.

**Comment by amitpatel0702** [comment]
@SagarLadani / @virallmehta, plz help in second review so that we can get it towards publish state.

**Comment by virallmehta** [comment]
Sure will help you.

**Comment by virallmehta** [comment]
I have reviewed  ( https://learn.wordpress.org/?p=27480&post_type=lesson-plan&preview=1&_ppp=7260d86279 ) and it looks good to me. @amitpatel0702  @Piyopiyo-Kitsune

**Comment by Piyopiyo-Kitsune** [comment]
This is now published! https://learn.wordpress.org/lesson-plan/gu-pages-vs-posts/
