### ISSUE TITLE
Learn WordPress Content Error Report - Ticket

### ISSUE THREAD

**Issue by palewar** [WordPress/Learn#1174]
# Error Description
- Content URL: [Custom Fonts Summary Quiz](https://learn.wordpress.org/quiz/custom-fonts-summary/)

As far as I know .woff fonts are supported in block themes. Have seen them being used in Bricksy theme. So correct answer to following question should be **'False'**. Right now, correct answer is 'True' so anyone who takes the quiz and answers 'False', fails the quiz. 

_**True or False: You can’t use .woff or .woff2 fonts in a block theme.**_

# Error Report Checklist:
- [x] Error Validated
- [x] Error fix proposed
- [x] Error fix reviewed
- [x] Error fix published

**Comment by jonathanbossenger** [comment]
Thanks for logging this @palewar you are correct, and I have updated the question on the quiz.
