### ISSUE TITLE
Online Workshop - EP2: WordPress Installation on Local and Live (cPanel, FTP & MySQL) | Bangla

### ISSUE THREAD

**Issue by mahbubshovan** [WordPress/Learn#1177]
# Event Details
- Title: EP2: WordPress Installation on Local and Live (cPanel, FTP & MySQL) | Bangla
- Description: This is the 2nd episode of the WordPress for Beginner | Bangla series. Our main goal is to help new contributors (tech and non-tech) to get started quickly with WordPress. In this episode, we will show various ways of WordPress installation. First, we will demonstrate WordPress installation using Local WP, then show how to install WordPress on cPanel. Also, using FTP and MySQL. We will brief on domain & hosting as well.

This is a localized (Non-English) online workshop.
- Target Audience: Bangla Speaking People
- Date: December 13, 2022.
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290171683/
- Host: Linkon Miyan (@rudlinkon)
- Co-host: Mahbub Shovan (@mahbubshovan)
- Other info: This is an online localized mini workshop (via Zoom).

# Online Workshop Checklist:
- [x] ✅ Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] ✅ Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] ✅ Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] ✅ Hold Online Workshop
- [x] ✅ Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] ✅ Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by rudlinkon** [comment]
Please add me as a host or assign me. thank you.

**Comment by robinwpdeveloper** [comment]
Done

**Comment by mahbubshovan** [comment]
WordPress.tv link - https://wordpress.tv/2022/12/14/wordpress-installation-on-local-and-live-cpanel-ftp-mysql-bangla/

**Comment by robinwpdeveloper** [comment]
Marking as completed.
