### ISSUE TITLE
Learn WordPress Content Error Report - Ticket

### ISSUE THREAD

**Issue by tysonlmao** [WordPress/Learn#1178]
https://learn.wordpress.org/lesson/what-is-the-site-editor/

"What this helpful video tutorial." Maybe it should read as "Watch this helpful video tutorial".

**Comment by dilipbheda** [comment]
I would like to work on this

**Comment by dilipbheda** [comment]
I've fixed this issue, please check and let me know.

**Comment by iamchetanp** [comment]
@dilipbheda  Thank you for contribution!
