### ISSUE TITLE
Online Workshop - Let's code: Developing Blocks without React! - Review

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1181]
# Event Details
- Title: Let's code: Developing Blocks without React! - Review
- Description: Over the past few weeks, we've been learning to build a small WordPress block using plain JavaScript. In this session, I will review everything we've learned so far, by rebuilding the entire block from scratch.
- Target Audience: Developers
- Date: 2022-12-15
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290237910/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
@thelmachido and @mrfoxtalbot will be joining me on Thursday

**Comment by Thelmachido** [comment]
Thanks @jonathanbossenger

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/01/04/lets-code-developing-blocks-without-react-review/
