### ISSUE TITLE
Gujarati translation for Lesson Plan "Choosing And Installing Plugins"

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1182]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/choosing-and-installing-plugins/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/407
- Translator: Sagar Landani
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by SagarLadani** [comment]
I have done my translation and sharing google docs below 👇🏼

[https://docs.google.com/document/d/1pLlPy4cYqPlRlA41zbMsv0usvw2HpyKV_cMlM0_YPyQ/edit#heading=h.jza0uhpiuab3](https://docs.google.com/document/d/1pLlPy4cYqPlRlA41zbMsv0usvw2HpyKV_cMlM0_YPyQ/edit#heading=h.jza0uhpiuab3)

I would like to get review from @amitpatel0702 @vanpariyar and @virallmehta

**Comment by Piyopiyo-Kitsune** [comment]
Preview ready: https://learn.wordpress.org/?p=27475&post_type=lesson-plan&preview=1&_ppp=d949a91431

Please approve for publication

**Comment by kaitohm** [comment]
https://learn.wordpress.org/lesson-plan/gu-choosing-and-installing-plugins/
