### ISSUE TITLE
Topic - German Lesson Plan - Dashboard-Übersicht

### ISSUE THREAD

**Issue by gudrunfrank** [WordPress/Learn#1184]
# Topic Description
A basic introduction to the dashboard in German. It is inspired by https://learn.wordpress.org/lesson-plan/dashboard-overview/ 

The objectives are the same as in the English version, but it is not an exact translation. Please treat as editorial review. 

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ https://learn.wordpress.org/lesson-plan/dashboard-overview/]

The lesson plan can be reviewed here; https://learn.wordpress.org/wp-admin/post.php?post=24030&action=edit

**Comment by kaitohm** [comment]
@MatzeKitt Would you be available to review this one also?

**Comment by kaitohm** [comment]
@gudrunfrank When you have a moment, could you update the `Language` setting in the right side-bar of the editor, please? This is a new setting that was introduced to Learn content recently. It is currently set to English on this lesson plan. Thanks!

**Comment by gudrunfrank** [comment]
@bsanevans `Language` setting is updated to German.

**Comment by MatzeKitt** [comment]
Done!

@gudrunfrank You can see my changes in the revisions: https://learn.wordpress.org/wp-admin/revision.php?revision=27401

**Comment by gudrunfrank** [comment]
@MatzeKitt Thank you for the review! 
@bsanevans what is the next step to get this published?

**Comment by kaitohm** [comment]
Great work! I've conducted the final check, linked the Lesson Plan back to this GitHub issue, and published it! You can find the published lesson plan here: https://learn.wordpress.org/lesson-plan/dashboard-uebersicht/
