### ISSUE TITLE
Online Workshop - EP3: WordPress Migration (Local/Live to Local/Live) | Bangla

### ISSUE THREAD

**Issue by fuadragib01** [WordPress/Learn#1185]
# Event Details
- Title: EP3: WordPress Migration (Local/Live to Local/Live) | Bangla
- Description: In this episode we will show various ways of WordPress site migration.
First we will demonstrate how to migrate a WordPress site from Local to Local and Local to Live server. Then we will demonstrate how to migrate from Live to Local and Live to Live server.
- Target Audience: Bangla Speaking People
- Date: December 14, 2022.
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290268430/
- Host: Linkon Miyan (@rudlinkon)
- Co-host: Fuad Ragib (@fuadragib01)
- Other info: This is an online localized mini workshop (via Zoom).

# Online Workshop Checklist:
- [x] ✅ Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] ✅ Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] ✅ Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] ✅ Hold Online Workshop
- [x] ✅ Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] ✅ Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by rudlinkon** [comment]
Hello there please assign me.

**Comment by fuadragib01** [comment]
WordPress.tv link: https://wordpress.tv/2022/12/14/wordpress-migration-local-live-to-local-live-bangla/

**Comment by robinwpdeveloper** [comment]
Marking as completed
