### ISSUE TITLE
Gujarati translation for Lesson Plan "Difference between Reusable Blocks, Block Pattern, Templates, Template Parts"

### ISSUE THREAD

**Issue by SagarLadani** [WordPress/Learn#1188]
# Details
- Link to original content: [https://learn.wordpress.org/lesson-plan/difference-between-reusable-blocks-block-pattern-templates-template-parts/](https://learn.wordpress.org/lesson-plan/difference-between-reusable-blocks-block-pattern-templates-template-parts/)
- Link to original content GitHub issue: [https://github.com/WordPress/Learn/issues/450](https://github.com/WordPress/Learn/issues/450)
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: Google doc link - [https://docs.google.com/document/d/1uECk7mGNct4Ky5uEIwKne_V-d-Edwh56tTL5tjUBM4Q/edit#](https://docs.google.com/document/d/1uECk7mGNct4Ky5uEIwKne_V-d-Edwh56tTL5tjUBM4Q/edit#)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by SagarLadani** [comment]
I have completed my task, @amitpatel0702 @vanpariyar  and Ramesh, can you please review it and let me know if you have any questions.

**Comment by vanpariyar** [comment]
Hello @SagarLadani 

It looks good to me.

**Comment by Piyopiyo-Kitsune** [comment]
@SagarLadani Please approve for publication if it looks good :-) https://learn.wordpress.org/?p=27699&post_type=lesson-plan&preview=1&_ppp=af580719ac

**Comment by Piyopiyo-Kitsune** [comment]
Published: https://learn.wordpress.org/lesson-plan/gu-difference-between-reusable-blocks-block-pattern-templates-template-parts/
