### ISSUE TITLE
Online Workshop - Let’s make custom templates in the Site Editor!

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1191]
# Event Details
- Title: Let’s make custom templates in the Site Editor!
- Description: This will be a live demo of me making custom templates for a new blog. It is an English version of the Japanese workshops I'll be hosting here: #1190 
- Target Audience: Users, Designers of all ages
- Date: This workshop will be held twice to cater to multiple timezones.
  - January 20th: [Event 1 Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/290363952/) - @westnz 
  - February 3rd: [Event 2 Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/290971392/) - needs co-host
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by westnz** [comment]
I will co-host this Friday, 20 January.

**Comment by kaitohm** [comment]
Thanks, @westnz !

**Comment by kaitohm** [comment]
As this is a demo-centered workshop, there isn't much content to my slides. But here they are for the record: https://docs.google.com/presentation/d/1efPkqD2QKYBfXF0x1D92Go5qmQYc6XBY9BQJjFpp6Xo/edit?usp=sharing

**Comment by kaitohm** [comment]
Video uploaded here: https://wordpress.tv/2023/02/02/lets-make-custom-templates-in-the-site-editor/
