### ISSUE TITLE
Designing with the columns block - Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1192]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/209258837-7b9c411c-13c8-4e1f-b79c-6aa55cb8ffe3.mp4

**Comment by askdesign** [comment]
Review:
Excellent video! Clear explanation with beautiful and simple transitions. I learned a few new things.

There was 1 area where I had to stop and go back to see it again and digest the information:
1:26 - "When you click on the alignment icon.... You can get wide width or full width."
Maybe slow this down a bit so we can see the difference.

**Comment by westnz** [comment]
Thank you for the feedback! @askdesign

**Comment by maion11** [comment]
Review: 
Thanks for this amazing video. It easily shows how to implement column blocks. I didn't find anything hard to consume. All looks good to it.

**Comment by westnz** [comment]
Thank you for your feedback @maion11

**Comment by SierraTR** [comment]
Good job on covering the material - very little more could be added.
You might consider cutting down on the number of different types of slide transitions. I counted about 15 different ways one slide transitioned to the next slide.

**Comment by westnz** [comment]
Helpful comment, thank you @SierraTR

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/designing-with-the-columns-block/

**Comment by westnz** [comment]
Updated and published as part of the Intermediate User learning pathway in Sensei.

**Comment by westnz** [comment]
Updated for learning pathways project.
