### ISSUE TITLE
Content Error Report - Notice: "general" is not a supported wp_template_part area value and has been added as "uncategorized". in .../wp-includes/block-template-utils.php on line 219

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1194]
# Error Description
- Content URL: https://github.com/WordPress/Learn/issues/885

Tracy Rhodes: "Just completed the 'A Developers Guide to Block Themes - Part 1'. Good course but need some updates since the 6.1 release. Reason for this post, though is the info in the last section on Custom Template Parts.  After generating the custom template part (Post Meta) and selecting 'General" for the area all seems good - Then I manually copied the template part code into the html file for the part in the Assets/Parts directory and added it as directed to theme.json as a templatePart. Then when I accessed the site dashboard where I noticed at the top of the page the line:
"Notice: "general" is not a supported wp_template_part area value and has been added as "uncategorized". in .../wp-includes/block-template-utils.php on line 219"
This disables access to the site editor until theme.json is changed to indicate 'uncategorized' as the area for the templatePart."

# Error Report Checklist:
- [x] Error Validated
- [x] Error fix proposed
- [x] Error fix reviewed
- [x] Error fix published

**Comment by jonathanbossenger** [comment]
@westnz this has been fixed.
