### ISSUE TITLE
Online Workshop - Creating a photography website 

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1195]
# Event Details
- Title: Creating a photography website 
- Description: Using the block editor to create a photography website
- Target Audience: Beginner
- Date: 1 Feb and  7 Feb (New Zealand)
- Meetup.com event link: 
[Event 1](https://www.meetup.com/learn-wordpress-online-workshops/events/290414181/?isFirstPublish=true): Kathryn Presner
[Event 2](https://www.meetup.com/learn-wordpress-online-workshops/events/290414689/?isFirstPublish=true): Mark-Andrew

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by ghost** [comment]
I am available to co-host this workshop. I am assuming it is the same one listed in meetup as TUE, JAN 31 · 3:00 PM EST
Creating a photography website with the block editor. I am still figuring out GitHub so if this is not the same please let me know where to post.

**Comment by westnz** [comment]
Hey @lada7042 
Ah thanks so much, but I already confirmed a cohost before I saw this message. My apologies, I went to lunch without updating the GitHub Issue. Next time!! I realise the other event will not suit your time zone.

**Comment by westnz** [comment]
[https://wordpress.tv/2023/02/07/creating-a-photography-website-with-the-block-editor/.](https://wordpress.tv/2023/02/07/creating-a-photography-website-with-the-block-editor/)
