### ISSUE TITLE
Online Workshop - EP4: Introduction to WordPress (Dashboard, Frontend) | Bangla

### ISSUE THREAD

**Issue by abid112** [WordPress/Learn#1201]
# Event Details
- Title: EP4: Introduction to WordPress (Dashboard, Frontend) | Bangla
- Description: This is the 4th episode of WordPress for Beginner | Bangla series. Our main goal is to help new contributors (tech and non tech) to get started easily with WordPress. In this episode, we will show the WordPress Dashboard and explain all the Dashboard menu items. We will explain full WordPress Dashboard interface and how they reflect in frontend.
- Target Audience: Bangla Speaking People
- Date: December 26, 2022
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290471575/
- Co-host: [Syeda Sanjida Afrin](https://profiles.wordpress.org/afrin29/)
- Other info: This is an online localized mini workshop (via Zoom).

# Online Workshop Checklist:
- [✅] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [✅] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [✅] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [✅] Hold Online Workshop
- [✅] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [✅] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by Afrin29** [comment]
Kindly add me as a co-host. Thank you.

**Comment by abid112** [comment]
WordPress TV link: https://wordpress.tv/2022/12/31/ep4-introduction-to-wordpress-dashboard-frontend-bangla/
