### ISSUE TITLE
Online Workshop - EP5: Introduction to Themes (File Structure, Troubleshooting) | Bangla

### ISSUE THREAD

**Issue by abid112** [WordPress/Learn#1202]
# Event Details
- Title: EP5: Introduction to Themes (File Structure, Troubleshooting) | Bangla
- Description: This is the 5th episode of WordPress for Beginner | Bangla series. Our main goal is to help new contributors (tech and non tech) to get started easily with WordPress. In this episode we will show some popular themes and show how to use them. We will also explain about the WordPress theme file structure and give an idea about child theme.
- Target Audience: Bangla Speaking People
- Date: December 27, 2022.
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290471677/
- Co-host: [Syeda Sanjida Afrin](https://profiles.wordpress.org/afrin29/)
- Other info: This is an online localized mini workshop (via Zoom).

# Online Workshop Checklist:
- [✅] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [✅] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [✅] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [✅] Hold Online Workshop
- [✅] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [✅] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by Afrin29** [comment]
Kindly add me as a co-host. Thank you.

**Comment by abid112** [comment]
WordPress TV link: https://wordpress.tv/2022/12/31/ep5-introduction-to-themes-file-structure-troubleshooting-bangla/

**Comment by mumtahinafaguni** [comment]
Kindly add me as a co-host. Thank you.
