### ISSUE TITLE
Online Workshop - EP6: Introduction to Plugins (File Structure, Troubleshooting) | Bangla

### ISSUE THREAD

**Issue by abid112** [WordPress/Learn#1203]
# Event Details
- Title: EP6: Introduction to Plugins (File Structure, Troubleshooting) | Bangla
- Description: In this episode we will talk about plugins in WordPress. We will explain how to use plugins in WordPress. Additionally we will install some popular plugins and talk about their features and how to use them.
- Target Audience: Bangla Speaking People
- Date: December 28, 2022.
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290471702/
- Co-host: [Syeda Sanjida Afrin](https://profiles.wordpress.org/afrin29/)
- Other info: This is an online localized mini workshop (via Zoom).

# Online Workshop Checklist:
- [✅] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [✅] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [✅] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [✅] Hold Online Workshop
- [✅] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [✅] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by Afrin29** [comment]
Kindly add me as a co-host. Thank you.

**Comment by abid112** [comment]
WordPress TV Link: https://wordpress.tv/2022/12/31/ep6-introduction-to-plugins-file-structure-troubleshooting-bangla/
