### ISSUE TITLE
Gujarati translation for Handbook Page "Translating Subtitles"

### ISSUE THREAD

**Issue by SagarLadani** [WordPress/Learn#1206]
# Details
- Link to original content: [https://make.wordpress.org/training/handbook/tutorials/tutorial-subtitles-and-transcripts/translating-subtitles/](https://make.wordpress.org/training/handbook/tutorials/tutorial-subtitles-and-transcripts/translating-subtitles/)
- Link to original content GitHub issue: Not created yet
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [amitpatel0702](https://github.com/amitpatel0702), [vanpariyar](https://github.com/vanpariyar)
- Other info: Google doc link - [https://docs.google.com/document/d/1JUnzNqAbZkeCNYpUbZnLO0o1gUQp4tnz3v-_WPj1YkE/edit](https://docs.google.com/document/d/1JUnzNqAbZkeCNYpUbZnLO0o1gUQp4tnz3v-_WPj1YkE/edit)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@amitpatel0702 @vanpariyar Please review this translation when you get a moment :-)

**Comment by vanpariyar** [comment]
I reviewed 👍🏼 .

It looks good to me.

**Comment by Piyopiyo-Kitsune** [comment]
Thank you @vanpariyar . Marking this as closed for now-- note that we are not able to publish handbook pages yet and I'm seeing if GlotPress is an option for the Training Team site.

**Comment by kaitohm** [comment]
@SagarLadani This English handbook page has been updated extensively. Would you be available to create a new Google doc and re-translate the content?

The new URL for the original English handbook page - https://make.wordpress.org/training/handbook/content-localization/translating-subtitles/

**Comment by SagarLadani** [comment]
Sure @bsanevans

**Comment by kaitohm** [comment]
Hi @SagarLadani 👋 How is the progress for this translation?

**Comment by SagarLadani** [comment]
Hello @bsanevans, Since all the content on the page has changed, I have replaced it with new content and translated it.

Google Doc : [https://docs.google.com/document/d/1JUnzNqAbZkeCNYpUbZnLO0o1gUQp4tnz3v-_WPj1YkE/edit#heading=h.o4x7poatau37](https://docs.google.com/document/d/1JUnzNqAbZkeCNYpUbZnLO0o1gUQp4tnz3v-_WPj1YkE/edit#heading=h.o4x7poatau37)

**Comment by kaitohm** [comment]
Thanks so much! I've added a link to the Google Doc on [the handbook page](https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-subtitles/) 🎉
