### ISSUE TITLE
Feature request: Consider adding a date field to tutorial and course content

### ISSUE THREAD

**Issue by andreawetzel** [WordPress/Learn#1207]
## Description
Lack of date courses and tutorials were released makes it difficult to discern if a block development course or tutorial is new or not. 

## Step-by-step reproduction instructions
When looking at [Courses](https://learn.wordpress.org/courses/#developing-with-wordpress) there are a few titles including: 

- "Introduction to Block Development: Build your first custom block"  
- "A Developers Guide to Block Themes – Part 1"   

It would be good to see a date that these courses were released or updated to know if they are relevant before taking the course or watching the tutorial

When looking at the [Tutorials ](https://learn.wordpress.org/tutorials/) listing, there is no ability to filter by most recent or know if content is out of date. 

One of the Tutorial titles is "Intro to Gutenberg Block Development" but it is hard to tell if this content is new or not.

It is also easy to get confused between the tutorials and courses sections because they have overlapping content, but are not linked to each other.

## Expected behaviour
To be able to view and search courses and tutorials by date

## Actual behaviour
Being confused as to which content is new and which content is potentially out-of-date.

**Comment by jonathanbossenger** [comment]
Closed in favor of #1464
