### ISSUE TITLE
Hindi translation for Lesson Plan "Dashboard Overview"

### ISSUE THREAD

**Issue by pitamdey** [WordPress/Learn#1209]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/dashboard-overview/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/423
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?:  No
- Reviewer's GitHub username: 
- Link to Hindi Translated Content : https://docs.google.com/document/d/13iCDpOMAlAglwzhEdrVWlge0WaOxQSDchd7B1rbHEu0/edit?usp=sharing
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
Preview of publication: https://learn.wordpress.org/?p=27482&post_type=lesson-plan&preview=1&_ppp=22c6913f20

Please approve post for publications

**Comment by pitamdey** [comment]
Approved

**Comment by kaitohm** [comment]
This has been published: https://learn.wordpress.org/lesson-plan/hi-dashboard-overview/
