### ISSUE TITLE
Add a section translated lesson plans

### ISSUE THREAD

**Issue by naokomc** [WordPress/Learn#121]
Currently, workshops language can be filtered using the dropdown. Although there is only one language (English) at the moment, it's set up for multilingual content addition. [There are some polyglots](https://make.wordpress.org/polyglots/2020/08/17/call-for-learn-wordpress-volunteers-video-translation-discussion-group/) that want to help with the translation of [Lesson Plans page](https://learn.wordpress.org/lesson-plans/).

I don't have the clearest idea of where the translation contents will live - but maybe /languages/ja/ folder within each lesson repository, for example?

**Comment by adamwoodnz** [comment]
Closing as this will be addressed by https://github.com/WordPress/Learn/issues/2231
