### ISSUE TITLE
Hindi translation for Lesson Plan "Intro to the Site Editor and Templates "

### ISSUE THREAD

**Issue by piyushmultidots** [WordPress/Learn#1210]
# Details
- Link to original content: [https://learn.wordpress.org/lesson-plan/intro-to-site-editor-and-templates](https://learn.wordpress.org/lesson-plan/intro-to-site-editor-and-templates)
- Link to original content GitHub issue: Not yet created
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [askaryabbas](https://github.com/askaryabbas) [pitamdey](https://github.com/pitamdey)
- Other info: Google Doc [https://docs.google.com/document/d/16tERG2aB255WuAq9KKQpzoCQBwxz4DG0MAy2qj3fEv8/edit#](https://docs.google.com/document/d/16tERG2aB255WuAq9KKQpzoCQBwxz4DG0MAy2qj3fEv8/edit#) 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@askaryabbas @pitamdey Please review this translation when you get a moment 👍

**Comment by pitamdey** [comment]
@Piyopiyo-Kitsune All good from my side

**Comment by askaryabbas** [comment]
@Piyopiyo-Kitsune, Reviewed the translation, all good 👍

**Comment by Piyopiyo-Kitsune** [comment]
Thanks you two!

@piyushmultidots can you please review this draft and edit it as needed https://learn.wordpress.org/?p=27720&post_type=lesson-plan&preview=1&_ppp=e3f793dacf

Please let me know when it's good to publish.

**Comment by piyushmultidots** [comment]
@Piyopiyo-Kitsune i have Reviewed this draft , we can go for the publish

**Comment by Piyopiyo-Kitsune** [comment]
Thank you @piyushmultidots ! All published 😁 https://learn.wordpress.org/lesson-plan/hi-intro-to-the-site-editor-and-templates/
