### ISSUE TITLE
Gujarati translation for Handbook Page "Creating Tutorial Quizzes"

### ISSUE THREAD

**Issue by SagarLadani** [WordPress/Learn#1211]
# Details
- Link to original content: [https://make.wordpress.org/training/handbook/tutorials/creating-tutorial-quizzes/](https://make.wordpress.org/training/handbook/tutorials/creating-tutorial-quizzes/)
- Link to original content GitHub issue: Not created yet
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [amitpatel0702](https://github.com/amitpatel0702), [vanpariyar](https://github.com/vanpariyar)
- Other info: Google Doc - [https://docs.google.com/document/d/1sQCstfE95ZDfGPTFo7Tk3SPdeQrx60DKTExr9QV6C0A/edit](https://docs.google.com/document/d/1sQCstfE95ZDfGPTFo7Tk3SPdeQrx60DKTExr9QV6C0A/edit)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@amitpatel0702 @vanpariyar Please review this translation when you get a moment :-)

**Comment by vanpariyar** [comment]
I have reviewed 👍🏼 
It looks good to me.

**Comment by Piyopiyo-Kitsune** [comment]
Thank you for the review @vanpariyar Marking this as closed for now-- note that we are not able to publish handbook pages yet and I'm seeing if GlotPress is an option for the Training Team site.

**Comment by kaitohm** [comment]
In the meantime until the language switcher is implemented, the Google doc has been linked to the handbook page.
