### ISSUE TITLE
Gujarati translation for Handbook Page "Reviewing Tutorial Presenter Applications"

### ISSUE THREAD

**Issue by SagarLadani** [WordPress/Learn#1212]
# Details
- Link to original content: [https://make.wordpress.org/training/handbook/tutorials/reviewing-tutorial-presenter-applications/](https://make.wordpress.org/training/handbook/tutorials/reviewing-tutorial-presenter-applications/)
- Link to original content GitHub issue: Not created yet
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [amitpatel0702](https://github.com/amitpatel0702), [vanpariyar](https://github.com/vanpariyar)
- Other info: Google Doc - [https://docs.google.com/document/d/1szNdPIho4HSn4BVgCI7I9bf1RUzY5gE4FxWXY4kvnX8/edit](https://docs.google.com/document/d/1szNdPIho4HSn4BVgCI7I9bf1RUzY5gE4FxWXY4kvnX8/edit)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@amitpatel0702 @vanpariyar Please review this translation when you get a moment :-)

**Comment by vanpariyar** [comment]
I just read and reviewed content 👍🏼 
It looks nice.

**Comment by Piyopiyo-Kitsune** [comment]
Thanks for your review @vanpariyar Marking this as closed for now-- note that we are not able to publish handbook pages yet and I'm seeing if GlotPress is an option for the Training Team site.

**Comment by kaitohm** [comment]
In the meantime until the language switcher is implemented, the Google doc has been linked to the handbook page.
