### ISSUE TITLE
Hindi translation for Lesson Plan "Choosing And Installing Themes"

### ISSUE THREAD

**Issue by pitamdey** [WordPress/Learn#1213]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/choosing-and-installing-themes/
- Link to original content GitHub issue:  None
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Link to Hindi Translated Content : https://docs.google.com/document/d/1x-glRSonaoHxnxDJwzFmkBJ3kjHjFZ7cxUyVGB68c6E/edit?usp=sharing
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@askaryabbas @pitamdey Please review this translation when you get a moment 👍

**Comment by askaryabbas** [comment]
Hi @Piyopiyo-Kitsune, Reviewed the translation thoroughly, everything is fine, approved 👍

**Comment by Piyopiyo-Kitsune** [comment]
Thanks @askaryabbas ! @pitamdey can you review this draft https://learn.wordpress.org/?p=28401&post_type=lesson-plan&preview=1&_ppp=f67a0895ac and add the missing links for the following sections:

- विवरण
- चुने हुए विषय को स्थापित करना
- अपनी थीम को सक्रिय करें

**Comment by pitamdey** [comment]
Hi @Piyopiyo-Kitsune , I have done all the updates required & reviewed the draft...All Good from my side 👍

**Comment by Piyopiyo-Kitsune** [comment]
Great job @pitamdey ! All published https://learn.wordpress.org/lesson-plan/hi-choosing-and-installing-themes/
