### ISSUE TITLE
Hindi translation for Handbook Page "Tutorials" 

### ISSUE THREAD

**Issue by amitpatel0702** [WordPress/Learn#1214]
# Details
- Link to original content: [https://make.wordpress.org/training/handbook/tutorials/](https://make.wordpress.org/training/handbook/tutorials/)
- Link to original content GitHub issue: Not yet created
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [piyushmultidots](https://github.com/piyushmultidots), [pitamdey](https://github.com/pitamdey)
- Other info: Google Doc - [https://docs.google.com/document/d/1MxPtzifqCo3wpbznQd8fncCxFoTHx9RikuDLdLLvyMs/edit?usp=sharing](https://docs.google.com/document/d/1MxPtzifqCo3wpbznQd8fncCxFoTHx9RikuDLdLLvyMs/edit?usp=sharing)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@piyushmultidots @pitamdey Please review this translation when you get a moment 👍

**Comment by piyushmultidots** [comment]
@Piyopiyo-Kitsune I have reviewed this translation and it's  fine 🙂

**Comment by pitamdey** [comment]
@Piyopiyo-Kitsune All Good from my side 🙂

**Comment by Piyopiyo-Kitsune** [comment]
Published - https://make.wordpress.org/training/handbook/hi-tutorials/

**Comment by kaitohm** [comment]
Because we can't publish the handbook page until a language switcher is implemented, I have linked the Google Doc to the original English handbook page instead, so folks can still read the page in their language.
