### ISSUE TITLE
Gujarati translation for Handbook Page "Lesson Plan Testing Guide"

### ISSUE THREAD

**Issue by mayurbaroliya-multidots** [WordPress/Learn#1215]
# Details
- Link to original content: [https://make.wordpress.org/training/handbook/lesson-plans/lesson-plan-testing-guide/](https://make.wordpress.org/training/handbook/lesson-plans/lesson-plan-testing-guide/)
- Link to original content GitHub issue: Not yet created
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes 
- Reviewer's GitHub username: [SagarLadani](https://github.com/SagarLadani) [amitpatel0702](https://github.com/amitpatel0702)
- Other info: Google Doc [https://docs.google.com/document/d/1dkuF-qmNvwfoY_Nqs-7nHYLbS4GXzyXYFSQowq7QIj0/edit?usp=sharing](https://docs.google.com/document/d/1dkuF-qmNvwfoY_Nqs-7nHYLbS4GXzyXYFSQowq7QIj0/edit?usp=sharing)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@amitpatel0702 @sagarladani Please review this translation when you get a moment :-)

**Comment by kaitohm** [comment]
@vanpariyar @SagarLadani Please review this translation when you get a moment :-)

**Comment by SagarLadani** [comment]
Hello @mayurbaroliya-multidots 

As part of my review, I discovered some incorrect words, so I have added comments suggestions to [this](https://docs.google.com/document/d/1dkuF-qmNvwfoY_Nqs-7nHYLbS4GXzyXYFSQowq7QIj0/edit#) sheet, so please refer to them and replace them. Let me know if you have any questions.

Thanks

**Comment by kaitohm** [comment]
@mayurbaroliya-multidots Were you able to apply these changes? Is this translation ready to publish?

**Comment by amitpatel0702** [comment]
Hi @mayurbaroliya-multidots, I have reviewed the translation. It seems few of the translations are left. Please follow the comments and you will be able to get it done.
CC: @bsanevans

**Comment by kaitohm** [comment]
I'm closing this as we're deprioritizing translating handbook pages.
