### ISSUE TITLE
Hindi translation for Lesson Plan "Pages Vs. Posts"

### ISSUE THREAD

**Issue by pitamdey** [WordPress/Learn#1216]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/pages-versus-posts/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/432
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Link to Hindi Translated Content : https://docs.google.com/document/d/1iA7WZtvimemAUu4KMb7avck4nF0tyb-XEQ1PqDprQ3Q/edit?usp=sharing
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@askaryabbas @piyushmultidots Please review this translation when you get a moment 👍

**Comment by askaryabbas** [comment]
Hi @Piyopiyo-Kitsune, Reviewed the translation, all is good from my side 👍

**Comment by Piyopiyo-Kitsune** [comment]
Thank you @askaryabbas ! @pitamdey Please approve the draft for publication https://learn.wordpress.org/?p=27904&post_type=lesson-plan&preview=1&_ppp=026d29320f

**Comment by pitamdey** [comment]
Approved 👍

**Comment by Piyopiyo-Kitsune** [comment]
Published! 👍  https://learn.wordpress.org/lesson-plan/hi-pages-vs-posts/
