### ISSUE TITLE
Hindi translation for Lesson Plan "Choosing And Installing Plugins"

### ISSUE THREAD

**Issue by piyushmultidots** [WordPress/Learn#1217]
# Details
- Link to original content: [https://learn.wordpress.org/lesson-plan/choosing-and-installing-plugins/](https://learn.wordpress.org/lesson-plan/choosing-and-installing-plugins/)
- Link to original content GitHub issue: [https://github.com/WordPress/Learn/issues/407](https://github.com/WordPress/Learn/issues/407)
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [askaryabbas](https://github.com/askaryabbas) [pitamdey](https://github.com/pitamdey)
- Other info:  Google Doc: [https://docs.google.com/document/d/1MvBR7r3OhBabDv0hTuFo-LHZont4SxR8piEJT4y-0BU/edit?usp=sharing](https://docs.google.com/document/d/1MvBR7r3OhBabDv0hTuFo-LHZont4SxR8piEJT4y-0BU/edit?usp=sharing)
 
# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@askaryabbas @pitamdey can you kindly review the translation?

**Comment by piyushmultidots** [comment]
@Piyopiyo-Kitsune All Good From My End

**Comment by askaryabbas** [comment]
Hi @Piyopiyo-Kitsune , Reviewed the translation, all good from my side 👍

**Comment by pitamdey** [comment]
All good from my end 👍

**Comment by Piyopiyo-Kitsune** [comment]
Hey there @piyushmultidots -- sorry for the delay. Can you kindly review and edit this https://learn.wordpress.org/?p=32491&post_type=lesson-plan&preview=1&_ppp=9efb4e52a9 and let me know when it's ready to publish?

**Comment by kaitohm** [comment]
@piyushmultidots We've copy-pasted your translation into a Lesson Plan. Could you confirm the following post looks good? That is, have we copy-pasted the content across accurately?
https://learn.wordpress.org/wp-admin/post.php?post=32491&action=edit

Once you've checked, this will be ready to publish! 😃

**Comment by kaitohm** [comment]
This has now been published: https://learn.wordpress.org/lesson-plan/hi-choosing-and-installing-plugins/
