### ISSUE TITLE
Hindi translation for Lesson Plan "Difference between Reusable Blocks, Block Pattern, Templates, Template Parts"

### ISSUE THREAD

**Issue by mdaskary** [WordPress/Learn#1218]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/difference-between-reusable-blocks-block-pattern-templates-template-parts/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/450
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [Piyush Asthana](https://github.com/piyushmultidots), [Pitam Dey](https://github.com/pitamdey)
- Other info: Google Doc link - https://docs.google.com/document/d/1-4bXP-kQ-IgNxsODfndGndUIE0d8I6nZtbZseqtvIPs/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@piyushmultidots @pitamdey Please review this translation when you get a moment 👍

**Comment by piyushmultidots** [comment]
@Piyopiyo-Kitsune All good 👍

**Comment by Piyopiyo-Kitsune** [comment]
Hey there @piyushmultidots ! Can you review and approve the drafted lesson plan? :-) https://learn.wordpress.org/?p=27901&post_type=lesson-plan&preview=1&_ppp=bd9deddc1b

**Comment by pitamdey** [comment]
All Good from my end

**Comment by piyushmultidots** [comment]
@Piyopiyo-Kitsune All Good 👍

**Comment by Piyopiyo-Kitsune** [comment]
Published! - https://learn.wordpress.org/lesson-plan/hi-difference-between-reusable-blocks-block-pattern-templates-template-parts/
