### ISSUE TITLE
Hindi translation for Hanbook Page "How to Conduct an Instructional Review"

### ISSUE THREAD

**Issue by piyushmultidots** [WordPress/Learn#1219]
# Details
- Link to original content: [https://make.wordpress.org/training/handbook/lesson-plans/how-to-conduct-an-instructional-review/](https://make.wordpress.org/training/handbook/lesson-plans/how-to-conduct-an-instructional-review/)
- Link to original content GitHub issue: Not yet created
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [askaryabbas](https://github.com/askaryabbas) [pitamdey](https://github.com/pitamdey)
- Other info: Google Doc : [https://docs.google.com/document/d/1golMKMS_eVGUh11j4_76KB4A_Z2U0MtjoIcK4GVqkIk/edit#](https://docs.google.com/document/d/1golMKMS_eVGUh11j4_76KB4A_Z2U0MtjoIcK4GVqkIk/edit#)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
@piyushmultidots Is this ready for a translation review?

**Comment by piyushmultidots** [comment]
@bsanevans yes this is ready for the review

**Comment by kaitohm** [comment]
@askaryabbas @pitamdey can you kindly review the translation?

**Comment by pitamdey** [comment]
Hi @bsanevans I have reviewed the translation...All Good from my side 👍

**Comment by kaitohm** [comment]
Thank you, both @piyushmultidots and @pitamdey ! I've added the Google Doc link to the team handbook. I'll mark this as completed!

**Comment by SagarLadani** [comment]
I have reviewed the translation and from my perspective it is fine. No changes are needed.
