### ISSUE TITLE
Gujarati translation for Handbook Page "Copy Edit a Lesson Plan"

### ISSUE THREAD

**Issue by mayurbaroliya-multidots** [WordPress/Learn#1220]
# Details
- Link to original content: [https://make.wordpress.org/training/handbook/lesson-plans/copy-edit-a-lesson-plan/](https://make.wordpress.org/training/handbook/lesson-plans/copy-edit-a-lesson-plan/)
- Link to original content GitHub issue: Not yet created
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [SagarLadani](https://github.com/SagarLadani) [amitpatel0702](https://github.com/amitpatel0702)
- Other info: Google Doc [https://docs.google.com/document/d/1wA6XGCzgwheZLW4dxsdpnyDO_n-eHtboKbsGB6ZrXRo/edit?usp=sharing](https://docs.google.com/document/d/1wA6XGCzgwheZLW4dxsdpnyDO_n-eHtboKbsGB6ZrXRo/edit?usp=sharing)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@amitpatel0702 @sagarladani Please review this translation when you get a moment :-)

**Comment by amitpatel0702** [comment]
Thanks [mayurbaroliya-multidots](https://github.com/mayurbaroliya-multidots). Please find following notes

- Content translation seems accurate.
- Only one change - Please add title in the document and write Gujarati translation as well.

Thanks.

**Comment by Piyopiyo-Kitsune** [comment]
Hey there @mayurbaroliya-multidots -- were you able to make the suggested change? 😄

**Comment by kaitohm** [comment]
Hi @mayurbaroliya-multidots Could you confirm if you have applied Amit's suggestions, please?

**Comment by kaitohm** [comment]
I've linked the document here: https://make.wordpress.org/training/handbook/lesson-plans/copy-edit-a-lesson-plan/
