### ISSUE TITLE
Gujarati translation for Handbook Page "Lesson Plans"

### ISSUE THREAD

**Issue by SagarLadani** [WordPress/Learn#1221]
# Details
- Link to original content: [https://make.wordpress.org/training/handbook/lesson-plans/](https://make.wordpress.org/training/handbook/lesson-plans/)
- Link to original content GitHub issue: Not created yet
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [amitpatel0702](https://github.com/amitpatel0702), [vanpariyar](https://github.com/vanpariyar)
- Other info: Google Doc - [https://docs.google.com/document/d/1YNpY09h5yOPnazcJ3XvvpL0qGnAwdT34L_mFJkbdtys/edit](https://docs.google.com/document/d/1YNpY09h5yOPnazcJ3XvvpL0qGnAwdT34L_mFJkbdtys/edit)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@amitpatel0702 @vanpariyar Please review this translation when you get a moment :-)

**Comment by vanpariyar** [comment]
I just read and reviewed the content 👍🏼 
It looks nice. Small and concise article.

**Comment by Piyopiyo-Kitsune** [comment]
@vanpariyar thank you for checking! Marking this as closed for now-- note that we are not able to publish handbook pages yet and I'm seeing if GlotPress is an option for the Training Team site.

**Comment by kaitohm** [comment]
@SagarLadani Could you change the access on this Google Doc so that it is public, please? I'll then link it to the handbook.

**Comment by SagarLadani** [comment]
Hello @bsanevans, I have added public access.

**Comment by kaitohm** [comment]
Thanks! The handbook has been updated with a link to this doc.
