### ISSUE TITLE
Gujarati translation for Handbook Page "Content Localization"

### ISSUE THREAD

**Issue by SagarLadani** [WordPress/Learn#1222]
# Details
- Link to original content: [https://make.wordpress.org/training/handbook/content-localization/](https://make.wordpress.org/training/handbook/content-localization/)
- Link to original content GitHub issue: Not created yet
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [amitpatel0702](https://github.com/amitpatel0702), [vanpariyar](https://github.com/vanpariyar)
- Other info: Google Doc - [https://docs.google.com/document/d/1LbBG02xzcV4XMtBbK5BYYjMMuPgP7EoaULYW402aT_g/edit](https://docs.google.com/document/d/1LbBG02xzcV4XMtBbK5BYYjMMuPgP7EoaULYW402aT_g/edit)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@amitpatel0702 @vanpariyar Please review this translation when you get a moment :-)

**Comment by vanpariyar** [comment]
I just read and reviewed the content 👍🏼 
It looks nice to me.

**Comment by Piyopiyo-Kitsune** [comment]
Thank you @vanpariyar Marking this as closed for now-- note that we are not able to publish handbook pages yet and I'm seeing if GlotPress is an option for the Training Team site.

**Comment by kaitohm** [comment]
@SagarLadani The original English page has been updated. "Tutorials" is now split into two items. Also, some of the explanations under "Online Workshops" has been updated.

Would you be available to modify the Gujarati translation you already made to include these changes?

**Comment by SagarLadani** [comment]
Sure @bsanevans, I'll check updates and changes and let you know

**Comment by kaitohm** [comment]
I'm closing this for now, as we've deprioritized translating handbook pages.
