### ISSUE TITLE
Online Workshop - WordPress Plugin Security

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1223]
# Event Details
- Title: Let's Code - WordPress Plugin Security
- Description: In this Workshop, we'll be looking at one of the most vital but overlooked aspects of developing plugins for WordPress, and that's ensuring your plugin's code is secure! We will look at why this is important and learn how to implement a  security-first mindset as you add functionality to your plugins, using real-world examples. 
- Target Audience: Developers
- Date: 2023-01-05
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290667156/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by Thelmachido** [comment]
I can co-host

**Comment by jonathanbossenger** [comment]
Thanks @Thelmachido

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/01/06/lets-code-wordpress-plugin-security/
