### ISSUE TITLE
Gujarati translation for Handbook Page "Lesson Plan Testing Feedback"

### ISSUE THREAD

**Issue by SagarLadani** [WordPress/Learn#1228]
# Details
- Link to original content: [https://make.wordpress.org/training/handbook/lesson-plans/instructor-testing-feedback/](https://make.wordpress.org/training/handbook/lesson-plans/instructor-testing-feedback/)
- Link to original content GitHub issue: Not created yet
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [amitpatel0702](https://github.com/amitpatel0702), [vanpariyar](https://github.com/vanpariyar)
- Other info: Google Doc - [https://docs.google.com/document/d/1PvB0QHdwgorr4RM7fNveC5p1fNU9Q6afhuk8fUoguAM/edit](https://docs.google.com/document/d/1PvB0QHdwgorr4RM7fNveC5p1fNU9Q6afhuk8fUoguAM/edit)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@amitpatel0702 @vanpariyar Please review this translation when you get a moment :-)

**Comment by kaitohm** [comment]
@vanpariyar @SagarLadani Please review this translation when you get a moment :-)

**Comment by SagarLadani** [comment]
Hello @bsanevans I have reviewed this translation. It seems good to me.

**Comment by kaitohm** [comment]
OK, I'm going to close this issue for now. We can publish this handbook page once we have a language switcher for the Training Team handbook.

**Comment by kaitohm** [comment]
In the meantime until the language switcher is implemented, the Google doc has been linked to the handbook page.
