### ISSUE TITLE
Online Workshop - Let's Code! Using the WP REST API to access WordPress data

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1230]
# Event Details
- Title: Let's Code! Using the WP REST API
- Description: The WordPress REST API provides an interface for applications to interact with your WordPress site by sending and receiving data as [JSON](https://en.wikipedia.org/wiki/JSON) (JavaScript Object Notation) objects. It is the foundation of the [WordPress Block Editor](https://developer.wordpress.org/block-editor/). However, it also provides a more predictable and structured way to interact with your site’s content than using [admin-ajax](https://codex.wordpress.org/AJAX_in_Plugins). In this session, you will learn how to use the WP REST API in place of using admin-ajax, in order to interact with existing WordPress data.
- Target Audience: Developers
- Date: 2023-01-12 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290763316/
- Co-host: @thelmachido
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
Questions:

1. Can we use apiFetch
2. What can we fetch (posts on the front end, users on the backend)

**Comment by jonathanbossenger** [comment]
Notes: 

https://developer.wordpress.org/rest-api/

## Introduction
 
- Key Concepts
- Global Parameters 
- Pagination
- Ordering results
- Backbone

## Show admin-ajax example
 - return posts based on WP_Query object
 - show the use of wp_localize_script
 - show requirement to add admin_ajax callback function
 - cover security (nonces etc)

## Show the same REST API example
 - uses backbone.js client
 - uses WP REST API under the hood

## Consider introduction Postman

**Comment by jonathanbossenger** [comment]
@thelmachido has kindly offered to co-host again

**Comment by Thelmachido** [comment]
Yes

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/01/13/lets-code-using-the-wordpress-rest-api/
