### ISSUE TITLE
Online Workshop - EP7: Introduction to WooCommerce (Installation, Checkout flow) | Bangla

### ISSUE THREAD

**Issue by onlykawshar** [WordPress/Learn#1231]
# Event Details
- Title: EP7: Introduction to WooCommerce (Installation, Checkout flow) | Bangla
- Description: This is the 7th episode of the WordPress for Beginner | Bangla series.
Our main goal is to help new contributors (tech and non-tech) to get started easily with WordPress.

In this episode, we will show how to set up an eCommerce site using WooCommerce. We will show the complete installation setup and shop configuration.
We will also cover the full checkout flow including my account, shop, cart, and checkout page brief.

- Target Audience: Bangla Speaking People
- Date: January 09, 2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290731504/
- Co-host: [Mumtahina Faguni](https://profiles.wordpress.org/faguni22/)
- Other info: This is an online localized mini workshop (via Zoom).

# Online Workshop Checklist:
- [✅] Create an Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [✅] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [✅] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [✅] Hold Online Workshop
- [✅] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [✅] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by onlykawshar** [comment]
@mumtahinafaguni will co-host this event.

**Comment by mumtahinafaguni** [comment]
Kindly add me as a co-host. Thank you.

**Comment by onlykawshar** [comment]
WordPress TV Link - https://wordpress.tv/2023/01/17/ep7-introduction-to-woocommerce-installation-checkout-flow-bangla/
