### ISSUE TITLE
Online Workshop - EP8: Introduction to Products (Various types of Product) | Bangla

### ISSUE THREAD

**Issue by onlykawshar** [WordPress/Learn#1232]
# Event Details
- Title: EP8: Introduction to Products (Various types of Products) | Bangla
- Description: This is the 8th episode of the WordPress for Beginner | Bangla series.
Our main goal is to help new contributors (tech and non-tech) to get started easily with WordPress.

In this episode, we will brief you on various types of products and will demonstrate how to create each type of product with details.

- Target Audience: Bangla Speaking People
- Date: January 10, 2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290731557/
- Co-host: [Mumtahina Faguni](https://profiles.wordpress.org/faguni22/)
- Other info: This is an online localized mini workshop (via Zoom).

# Online Workshop Checklist:
- [✅] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [✅] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [✅] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [✅] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by onlykawshar** [comment]
@mumtahinafaguni will co-host this event.

**Comment by mumtahinafaguni** [comment]
Kindly add me as a co-host. Thank you.

**Comment by onlykawshar** [comment]
WordPress TV Link - https://wordpress.tv/2023/01/17/ep8-introduction-to-products-various-types-of-product-bangla/
