### ISSUE TITLE
Gujarati translation for Handbook Page "Creating a Tutorial"

### ISSUE THREAD

**Issue by SagarLadani** [WordPress/Learn#1235]
# Details
- Link to original content: [https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial/](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial/)
- Link to original content GitHub issue: Not created yet
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: Google Doc - [https://docs.google.com/document/d/1od1R9vbuGTACuaqEsttFjIUu__LjQdwJWaPHd9SUhvg/edit](https://docs.google.com/document/d/1od1R9vbuGTACuaqEsttFjIUu__LjQdwJWaPHd9SUhvg/edit)
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
Requested access to doc

**Comment by Piyopiyo-Kitsune** [comment]
@amitpatel0702 @vanpariyar Please review this translation when you get a moment :-)

**Comment by vanpariyar** [comment]
I have reviewed this translation.

It seems good to me.

**Comment by Piyopiyo-Kitsune** [comment]
@SagarLadani can you please review the drafted page and edit as needed? https://make.wordpress.org/training/?post_type=handbook&p=20771&preview=true

If it looks good to you, please publish.

**Comment by SagarLadani** [comment]
Nothing needs to be changed, it looks good. I am not able to publish I have show only **submit for review** option

**Comment by Piyopiyo-Kitsune** [comment]
Thank you @SagarLadani ! I'm going to close this out-- note that we are not able to publish handbook pages yet and I'm seeing if GlotPress is an option for the Training Team site.

**Comment by kaitohm** [comment]
This is where the draft page currently lives. I'm leaving this note here for when we're able to publish this: https://make.wordpress.org/training/wp-admin/post.php?post=20720&action=edit

**Comment by kaitohm** [comment]
In the meantime until the language switcher is implemented, the Google doc has been linked to the handbook page.
