### ISSUE TITLE
Online Workshop - Reviewing developer-focused features in Gutenberg 14.9

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/Learn#1241]
# Event Details
- Title: Reviewing developer-focused features in Gutenberg 14.9
- Description: We'll be taking a look at the developer-focus features that were released with Gutenberg 14.9 and if time allows, continue to work on the [Advanced Query Loop](https://wordpress.org/plugins/advanced-query-loop/) plugin by adding a [new feature from the list](https://github.com/ryanwelcher/advanced-query-loop/issues).
- Target Audience: Intermediate developers
- Date: Jan 12 2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290830522/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by ryanwelcher** [comment]
https://make.wordpress.org/core/2023/01/04/whats-new-in-gutenberg-14-9-4-january/

Items to go over:

https://github.com/WordPress/gutenberg/pull/46373
https://github.com/WordPress/gutenberg/pull/45814
https://github.com/WordPress/gutenberg/pull/46559
https://github.com/WordPress/gutenberg/pull/46813
https://github.com/WordPress/gutenberg/pull/42489

**Comment by justintadlock** [comment]
You've already got the things I would suggest listed.  But, if you want to dive into some of the theming-related items:

- The [post editor is now in an iframe](https://github.com/WordPress/gutenberg/pull/46212) like the site editor.
- `theme.json` now supports [box shadows for blocks](https://github.com/WordPress/gutenberg/pull/46813).  No UI yet.

**Comment by annezazu** [comment]
I'd touch on fluid typography still, even if it's just a quick reminder. +1 to iframing the post editor!

**Comment by ryanwelcher** [comment]
@justintadlock I've added the box shadows change but am wondering about the iframe issue. 

While it does address issues that users run into but is there an issue that extenders would run into that this fixes? Like CSS bleed? I'm definitely not against mentioning it but I'm trying to focus on things that affect or are enabled by 3rd party code. I may also just not know what I'm talking about :) I'd love to be able to show some code that is broken and then turn the plugin on and show it fixed - that's what I am thinking any way.

**Comment by ryanwelcher** [comment]
> I'd touch on fluid typography still, even if it's just a quick reminder. +1 to iframing the post editor!

Added! Thanks for the suggestion!

**Comment by justintadlock** [comment]
I'd say the biggest win with iframing the post editor is that there's no admin CSS bleed.  This makes it much easier to style themes (probably some plugins too) without conflicts or accidentally touching the admin UI with custom styles.  Theme authors are nearly 100% guaranteed to only need to worry about a single set of styles working on both the front and back ends.  I know I've personally had to create a few workarounds in the past, and am assuming (haven't tested yet) that this should fix those cases.

**Comment by ryanwelcher** [comment]
> I'd say the biggest win with iframing the post editor is that there's no admin CSS bleed. This makes it much easier to style themes (probably some plugins too) without conflicts or accidentally touching the admin UI with custom styles. Theme authors are nearly 100% guaranteed to only need to worry about a single set of styles working on both the front and back ends. I know I've personally had to create a few workarounds in the past, and am assuming (haven't tested yet) that this should fix those cases.

Awesome! Do you have an example I can test? I'll be doing my homework on these tomorrow so I can put it through it's paces.

**Comment by justintadlock** [comment]
> Awesome! Do you have an example I can test? I'll be doing my homework on these tomorrow so I can put it through it's paces.

Unfortunately, I don't have any examples off-hand.  It's been over a year since I've had a project where this was an issue (I tried to dig up the specifics, but I didn't find it).  Anyway, I see it as more or less of a footnote.

As an aside, which I didn't see mentioned specifically in the commit message, the post editor is only in an iframe if the custom fields panel is disabled (default).

**Comment by ryanwelcher** [comment]
Full Stream - https://www.youtube.com/watch?v=6xZgpngqslc
Gb Features only - https://www.youtube.com/watch?v=t9kqAvkthaE
