### ISSUE TITLE
Learn WordPress Content Error Report - Ticket

### ISSUE THREAD

**Issue by bengreeley** [WordPress/Learn#1245]
# Error Description
- Content URL: https://learn.wordpress.org/course/getting-started-with-wordpress-get-setup/

This is a minor grammatical issue, but the title of the course is "Getting Started With WordPress: Get Setup". The word "Setup" is being used incorrectly and should be two separate words, "Set Up". In general, it should be two separate words when it's used as a verb. 

https://grammarist.com/spelling/set-up-vs-setup/

# Error Report Checklist:
- [x] Error Validated
- [x] Error fix proposed
- [x] Error fix reviewed
- [x] Error fix published

**Comment by webtechpooja** [comment]
Thank @bengreeley, for reporting. This issue is fixed now, so I am closing it.
