### ISSUE TITLE
Online Workshop - Let's Code: Interacting with the WP REST API

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1247]
# Event Details
- Title: Let's Code: Interacting with the WP REST API
- Description: In the [previous session](https://github.com/WordPress/Learn/issues/1230) you were introduced to the WordPress REST API, as well as the Backbone.js client to interact with it. In this session, we will look at how you can interact with the WP REST API further, but adding and deleting data. We will also look at a useful developer tool for testing your REST API endpoints.
- Target Audience: Developers
- Date: 2022-01-19
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/290916495
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by leogopal** [comment]
Available to co-host for this event @jonathanbossenger -- I have signed up to the event.

**Comment by leogopal** [comment]
Available to co-host if still needed

**Comment by jonathanbossenger** [comment]
Thanks @leogopal

**Comment by jonathanbossenger** [comment]
Docs reference
- API Schema (For example posts -> https://developer.wordpress.org/rest-api/reference/posts/)

Notes:
- Let's clean up the JQuery
- Let's build a form
- API schema vs DB schema
- Create a post - https://developer.wordpress.org/rest-api/using-the-rest-api/backbone-javascript-client/#model-examples
- New post defaults
- Saves posts as draft by default
- Plain content vs block content

**Comment by nydame** [comment]
Thanks for this workshop! I would love to know more about creating custom endpoints. For example, fetch all authors with posts in a certain category. These sorts of queries are great for populating select fields.

**Comment by jonathanbossenger** [comment]
Thanks, @nydame I've made a note of this and will look to cover it in a future session.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/01/20/lets-code-interacting-with-the-wp-rest-api/
