### ISSUE TITLE
Online Workshop - Call for Testing: Find Your Style

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1250]
# Event Details
- Title: Call for Testing: Find Your Style (Interactive)
- Description: 

Are you curious about how you can contribute to WordPress?
Do you want to learn how to test new WordPress features collaboratively--_before_ they become available in core?
Do you want to provide invaluable feedback to catch bugs, explore workflow changes, and maybe suggest a wish-list item or two on future WordPress features?

If so, this Online Workshop is for you! Join Courtney Robertson and Sarah Snow as they test out beta features in WordPress in this interactive workshop. Over the course of this workshop, you will...

-Test WordPress alongside us on your own device (computers, tablets, or cellphones!) on a browser of your choice
-Thoughtfully record your observations throughout this test
-Share your feedback to make WordPress better for _everyone!_

Make your voice heard! We look forward to seeing you there.

All WordPress users are welcome, but it will be easier to follow along and share your thoughts if you are an intermediate WordPress user.

You will get the most out of this interactive workshop if...
-You are an intermediate WordPress user
-You are familiar with the block editor
-You are familiar with Full Site Editing (specifically templates)
-You want to contribute to WordPress
-You want to share your feedback to improve the next WordPress release

- Target Audience: Contributors / Intermediate Users
- Date: January 24, 2023
- Meetup.com event link:
- Host: Courtney Robertson
- Co-host: Sarah Snow
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by kaitohm** [comment]
Can we close this issue out, @wparasae ?
