### ISSUE TITLE
Creating new onboarding paths - Getting Started

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1253]
This issue tracks the creation of a new onboarding handbook page. This new **"Getting Started" page** will replace the page with [the same name currently in the handbook](https://make.wordpress.org/training/handbook/getting-started/), and will be the parent page to the other onboarding pages listed below.

Editors can view/edit the draft handbook page here: https://make.wordpress.org/training/wp-admin/post.php?post=20539&action=edit

A public preview will be provided once the page is ready for general feedback.

---

An overview of this project can be found on the Training Team's blog - [Project Thread: Training Team Onboarding Paths](https://make.wordpress.org/training/2022/11/26/project-thread-training-team-onboarding-paths/)

Links to GitHub issues of other pages being created as part of this project are listed below:
* Getting Started - this issue
* #1120 
* #1254 
* #1121 
* #1122 
* #1123 
* #1124

**Comment by kaitohm** [comment]
This page is ready for public review. https://make.wordpress.org/training/?p=20539&post_type=handbook&preview=1&_ppp=24a8c3b54c

**Please leave your feedback here in GitHub by February 4th** 😃🙇🏻‍♂️

Also, if you are interested in transcribing the video at the top of this page, please comment below. The video will be ready for transcription on February 6th, and will need to be completed by February 10th.

**Comment by nomad-skateboarding-dev** [comment]
My overall impression after reading this and watching the video was this was fantastic! Very clear, easy to understand but informative, and the video and the whole vibe felt welcoming. 🙂 Well done. 👏

Questions I might have after reading the content and watching the video:
1. In the video hand gestures are used to denote numbers. Different cultures use different fingers to denote different numbers. Would someone be confused watching? Or are the way the numbers were shown so common that everyone gets it? 
2. It mentions picking your first area for contribution multiple times. Does that mean there is a set order for contributing once I pick an area? Or can I contribute across multiple training team areas when I begin? 
3. The last paragraph advises to ping in Slack for help. Who do I ping in the Slack channel?

For 3, I really like how this was done in the [Content Creator Onboarding](https://make.wordpress.org/training/?p=20153&post_type=handbook&preview=1&_ppp=f4f84194de) section that follows.

**Comment by kaitohm** [comment]
Thank you for your feedback @nomad-skateboarding-dev !! Here's a preview of the updated page. If you have time to review this in the next day or two, we'd appreciate that:

https://make.wordpress.org/training/?p=20539&post_type=handbook&preview=1&_ppp=3f6121350b (Please note, the onboarding paths aren't linked in the table yet. We'll make sure those are linked when the pages are published.)

> 1. In the video hand gestures are used to denote numbers... Would someone be confused watching?

Great comment! We decided to re-take the video without hand gestures. How does the new video look? 😀

> 2. Or can I contribute across multiple training team areas when I begin?

We've clarified people can go through multiple paths if they want under `Find your interest, and make your first contribution`. How does that look now?

> 3. The last paragraph advises to ping in Slack for help. Who do I ping in the Slack channel?

We've added an example there, like on the individual onboarding pages 👍🏼

**Comment by nomad-skateboarding-dev** [comment]
@bsanevans The page and the video are fantastic! 🙌

The entire page is one of the clearest examples of background information and next steps to take I've seen on Learn. Well done. 🙂

### Grammatical correction
There should be a comma before the word "too" in the transcript.

![Screenshot_20230207-083125.png](https://user-images.githubusercontent.com/78917704/217306760-6cb6d02d-3995-41c3-b403-9619e2e85feb.png)

**Comment by kaitohm** [comment]
Nice catch! Comma added ✅

**Comment by kaitohm** [comment]
This page has now been published: https://make.wordpress.org/training/handbook/getting-started/

You can find a summary of the entire project here: https://make.wordpress.org/training/2023/02/10/training-teams-new-onboarding-program-is-now-live/
