### ISSUE TITLE
Creating new onboarding paths - Content Translator

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1254]
This issue tracks the creation of a new onboarding handbook page for **the Content Translator role**. Editors can view/edit the draft handbook page here: https://make.wordpress.org/training/wp-admin/post.php?post=20554&action=edit

A public preview will be provided once the page is ready for general feedback.

---

An overview of this project can be found on the Training Team's blog - [Project Thread: Training Team Onboarding Paths](https://make.wordpress.org/training/2022/11/26/project-thread-training-team-onboarding-paths/)

Links to GitHub issues of other pages being created as part of this project are listed below:

* #1253 
* https://github.com/WordPress/Learn/issues/1120
* Content Translator - this issue
* https://github.com/WordPress/Learn/issues/1121
* https://github.com/WordPress/Learn/issues/1122
* https://github.com/WordPress/Learn/issues/1122
* https://github.com/WordPress/Learn/issues/1124

**Comment by kaitohm** [comment]
This page is ready for public review: https://make.wordpress.org/training/?p=20554&post_type=handbook&preview=1&_ppp=79e5d0b71b

**Please leave your feedback here in GitHub by February 4th** 😃🙇🏻‍♂️

**Comment by nomad-skateboarding-dev** [comment]
I am not a translator and don't endeavor to be. But the instructions in this onboarding felt perfect for me. I really liked the section listing a ready to go lesson plan in need of translation if I didn't find my language!

Possible punctuation feedback:
Every one of the steps listed ends with a period, except for step 1. 
![Screenshot_20230124-185634](https://user-images.githubusercontent.com/78917704/214470534-8e420cef-3524-4f1d-8c77-b07d1f2e0f5a.png)

**Comment by kaitohm** [comment]
Punctuation added!

**Comment by kaitohm** [comment]
This page has now been published: https://make.wordpress.org/training/handbook/getting-started/content-translator-onboarding/

You can find a summary of the entire project here: https://make.wordpress.org/training/2023/02/10/training-teams-new-onboarding-program-is-now-live/
