### ISSUE TITLE
Tamil translation for Lesson Plan "Dashboard Overview"

### ISSUE THREAD

**Issue by karthick-murugan** [WordPress/Learn#1255]
# Details
- Link to original content: [https://learn.wordpress.org/lesson-plan/dashboard-overview/](https://learn.wordpress.org/lesson-plan/dashboard-overview/)
- Link to original content GitHub issue: [https://github.com/WordPress/Learn/issues/423](https://github.com/WordPress/Learn/issues/423)
- Language you'll be translating to: Tamil
- Have you arranged for someone to review this translation?: No ( Please assign someone to review )
- Reviewer's GitHub username: -
- Other info: [https://docs.google.com/document/d/1mbBqM5AMInoTdmyGca_HeeATe4xAtjNr22FfJheH8MM/edit#heading=h.8pl1c3jx28q5](https://docs.google.com/document/d/1mbBqM5AMInoTdmyGca_HeeATe4xAtjNr22FfJheH8MM/edit#heading=h.8pl1c3jx28q5)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Piyopiyo-Kitsune** [comment]
@karthick-murugan is this ready for review? :-)

**Comment by karthick-murugan** [comment]
@Piyopiyo-Kitsune  - No I am still doing some edits. Will post here when completed.

**Comment by karthick-murugan** [comment]
@Piyopiyo-Kitsune - This is ready for review now.

**Comment by ibndawood** [comment]
@karthick-murugan - மிக்க நன்றி. I'll review this document and shall add my comments if any.

**Comment by karthick-murugan** [comment]
நன்றி @ibndawood

**Comment by ibndawood** [comment]
@karthick-murugan - உங்கள் மொழி பெயர்ப்புக்கு ரொம்ப நன்றிங்க ! கடுமையான வேல, ரொம்ப எளிமையா பண்ணிருக்கீங்க. என்னோட யோசனைகளை கொஞ்சம் சேர்த்துருக்கேன். உங்களுக்கு சரி'ன்னா அத சேர்த்துக்கோங்க. மீண்டும் ரொம்ப நன்றிங்க.

@Piyopiyo-Kitsune  - I've completed my review and have added my suggestions to the document. Thank you for this opportunity.

**Comment by karthick-murugan** [comment]
@ibndawood - உங்கள் பரபரப்பான நேரத்தில், சமூகத்திற்கு மிகவும் உதவியாக இருக்கும் இந்த மதிப்பாய்வில் அதிக நேரம் ஒதுக்கியுள்ளீர்கள். மிக்க நன்றி. :raised_hands::pray:

@Piyopiyo-Kitsune - All the reviews points has been updated and the lesson plan is ready for next phase.

**Comment by Piyopiyo-Kitsune** [comment]
Thank you for the review @ibndawood :D 

@karthick-murugan Please review the page and approve for publication if everything looks good https://learn.wordpress.org/?p=32489&post_type=lesson-plan&preview=1&_ppp=e3d2b7de49

**Comment by karthick-murugan** [comment]
@Piyopiyo-Kitsune Thanks for your efforts. All the required changes are made and it is ready to publish. Thank you.

**Comment by Piyopiyo-Kitsune** [comment]
Published! :D https://learn.wordpress.org/lesson-plan/ta-dashboard-overview/ 🎉
