### ISSUE TITLE
Dashicon use

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#126]
The Training team has been creating slides for 5 years.  We'd like to be clear on the home page that the Workshops shown are video, not slides.  The dashicon used is for slides.  https://cloudup.com/cOQEQjqSk9t.  https://github.com/WordPress/dashicons/blob/master/svg-min/slides.svg

We are working toward integration on our slides being accessed within the lesson plans.  This issue was pointed out to me by a general community member, not particularly from a Training team member.  It is an additional layer of confusion.  

Can the video workshop area use a video dashicon? Or something representing events?

**Comment by hlashbrooke** [comment]
That's fair. We could switch it out for the desktop computer dashicon: https://developer.wordpress.org/resource/dashicons/#desktop
