### ISSUE TITLE
Indonesian translation for Lesson Plan "Dashboard Overview"

### ISSUE THREAD

**Issue by fikekomala** [WordPress/Learn#1260]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/dashboard-overview/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/423
- Translators: Kharis Sulistiyono, Ascencia Fike Komala, Irfan Nurhamid, Ahmad Syarifuddin Latif, Arif Mu'amar Wahid
- Language you'll be translating to: Indonesian
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: Juan Akbary
- Other info: Translated document https://docs.google.com/document/d/1wv2-d6og3i7nwHDAwwu9lKTeTIUEQCzVWlA5dbidL74/edit#

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by fikekomala** [comment]
Translated lesson plan: https://learn.wordpress.org/lesson-plan/id-dashboard-overview/

**Comment by Piyopiyo-Kitsune** [comment]
Added to the Content Localization Foundations Project spreadsheet. Great work everyone!
