### ISSUE TITLE
Learn WordPress Content Error Report - Exporting Custom Templates

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#1261]
# Error Description
- Content URL: https://learn.wordpress.org/lesson/exporting-custom-templates-and-template-parts/

Under the heading "Exporting Custom Templates using the Site Editor export tool" the content states that:

```The export will create the file in the templates’ directory, with the following filename structure, where {template-slug} is a “slugified” version of the template name you specified when you create the template: wp-custom-template-{template-slug}.html```

When exporting the theme (through the Site Editor as mentioned), the prefix `wp-custom-template-` is no longer added and doesn't seem necessary either. I have a custom template like `landing-page.html` that works perfectly fine.

# Error Report Checklist:
- [ ] Error Validated
- [ ] Error fix proposed
- [ ] Error fix reviewed
- [ ] Error fix published

**Comment by jonathanbossenger** [comment]
@thomasdevisser I've tested this out on WordPress 6.1.1, and the export functionality still exports custom templates with the wp-custom-template prefix.

Are you perhaps running WordPress with the latest Gutenberg plugin, which might be why this is happening?

**Comment by ghost** [comment]
@jonathanbossenger You're right, it was the Gutenberg plugin. Thanks for checking!

**Comment by jonathanbossenger** [comment]
Thanks for confirming @thomasdevisser 

I'll make a note to update the course content once that update comes to core.
