### ISSUE TITLE
Learn WordPress Content Error Report - WordPress Coding Standards

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#1262]
# Error Description
- Content URL: https://learn.wordpress.org/lesson/using-block-patterns-to-enable-internationalization/

I've come across quite a few code snippets that don't strictly follow the WordPress Coding Standards, is this something I can easily change somewhere? E.g. the provided link, under "Apply the Translation Function":

`<?php echo __('Proudly powered by', 'block-course-theme'); ?>`

should probably be changed to

`<?php _e( 'Proudly powered by', 'block-course-theme' ); ?>`

Necessary: add spaces next to the function's parentheses.
Optional: `_e(` would be cleaner than `echo __(`.

# Error Report Checklist:
- [x] Error Validated
- [x] Error fix proposed
- [x] Error fix reviewed
- [x] Error fix published

**Comment by kaitohm** [comment]
@jonathanbossenger Would you be able to review this feedback and apply necessary changes?

**Comment by jonathanbossenger** [comment]
Good catch @tomdevisser. Logging GitHub issues is the best way to get any code snippets updated.

> Necessary: add spaces next to the function's parentheses.

Fixed

> Optional: _e( would be cleaner than echo __(.

You'll note later on in the lesson, there's an explanation that the the _e function is a wrapper for echo __(), which is why the lesson is presented in this way.
