### ISSUE TITLE
Learn WordPress Content Error Report - Grammatical Error

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#1264]
# Error Description
- Content URL: https://learn.wordpress.org/quiz/create-custom-inspector-panel-controls/?

There's a grammatical error in the third question, should be an easy fix.

> A component that is only used in the editor, such as in the Inspector Panel, must still added to save.js.

should of course be:

> A component that is only used in the editor, such as in the Inspector Panel, must still **be** added to save.js.

# Error Report Checklist:
- [x] Error Validated
- [x] Error fix proposed
- [x] Error fix reviewed
- [x] Error fix published

**Comment by nomad-skateboarding-dev** [comment]
@Piyopiyo-Kitsune Commenting here to get issue assigned to myself.

**Comment by nomad-skateboarding-dev** [comment]
`Error Validated`
`Error Fix Proposed`

### Original
```
A component that is only used in the editor, such as in the Inspector Panel, must still added to save.js.
```
### Proposed Fix
```
A component that is only used in the editor, such as in the Inspector Panel, must still **be** added to save.js.
```

**Comment by webtechpooja** [comment]
Thanks @tomdevisser for reporting and @nomad-skateboarding-dev for your proposed change, The issue is fixed now.
