### ISSUE TITLE
Bite-sized content exploration

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1265]
We are in the process of creating three different 1-minute training videos which would be suitable for social media. This is a trial and exploration project.

**Comment by westnz** [comment]
Reference - bite-sized content on Learn: https://make.wordpress.org/training/2023/01/18/bite-sized-content-on-learn-wordpress/

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/213335159-18de7808-28e6-4335-825d-a543cbf08110.mp4

**Comment by westnz** [comment]
Here is the first example I created @vagelisp and @courtneyr-dev. I finished it today.

**Comment by westnz** [comment]
The process I followed:
- Targeted a topic that would lean towards a shorter video tutorial.
- Reviewed the reusable block feature.
- Planned out the tutorial and wrote a short script highlighting the main features.
- Created an intro slide.
- Searched for suitable background music.
- Completed the screen recordings.  I usually record in chunks.
- Added the voice recordings over the screen recordings.
- Added the background music (5% volume)
- Added the slide transitions and cursor effects

Please feel free to complete it any way you feel comfortable.  You might prefer recording it in one go and not including any add-ons.

**Comment by vagelisp** [comment]
That's brilliant; well-done @westnz!
Would it be a good idea to use the same intro and music for consistency?

Also, what did you use for recording? I usually use OBS.

**Comment by westnz** [comment]
Thanks! @vagelisp 
I used Camtasia for the recording.  You are more than welcome to use OBS. 
Here is the link to my WordPress Foundation Canva slide deck: https://www.canva.com/design/DAFX-u4svKs/oT9mMyFQ4rV2CmwzFCxJ-g/edit?utm_content=DAFX-u4svKs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton 
Let me know if you have trouble accessing it.
Unsure how to send the background music as it is part of the Camtasia Media Library. Having different types of background music would be a nice touch.

**Comment by vagelisp** [comment]
Thanks, @westnz.
I am on it!

**Comment by westnz** [comment]
Thank you @vagelisp!

Is everything in order from your side @courtneyr-dev?

**Comment by westnz** [comment]
I have changed the name of this issue so that all our examples and communication can be added here.  Then it will be centralised.

**Comment by ghost** [comment]
Great job Wes! My only comment is that for me the music is too loud and distracts from what you are saying.  Maybe turn the music down so it is more of a background.

**Comment by vagelisp** [comment]
Here's my video; I've learned a lot through the process and hope the next one will improve.
I made two versions of the video, one Horizontal ( 1920x1080 ) and one Vertical ( 1080x1920 )


https://user-images.githubusercontent.com/9304640/216171582-9518dcf8-578b-4a4f-8363-18e42b288374.mp4


https://user-images.githubusercontent.com/9304640/216171616-67a46567-af3c-4f44-b696-05f94435648f.mp4

**Comment by westnz** [comment]
This is fantastic, @vagelisp

**Comment by vagelisp** [comment]
Thanks @westnz 
That kind of content would be excellent under a category on Learn website.
And a collection of these could cover an entire topic

**Comment by westnz** [comment]
Interesting idea Vagelis!

**Comment by sereedmedia** [comment]
This is so awesome! Thank you for these examples. I know it's so hard to make short content, but, I wonder if these could be even shorter? I think 50 seconds should be the absolute longest. Maybe each video really focuses on just one small task or feature. Then the short bites could be strung together as a series.

**Comment by sereedmedia** [comment]
Just to flag, there are a lot of redesigns going on across the project so that might be something to consider before deciding what to work on. It would be good to avoid having to redo folks' hard work or to have content go out-of-date too quickly. 

Example: the Theme Directory [https://make.wordpress.org/design/2023/01/16/a-refresh-of-wordpress-org-themes/](https://make.wordpress.org/design/2023/01/16/a-refresh-of-wordpress-org-themes/)),

**Comment by vagelisp** [comment]
I think that's a great idea, @sereedmedia; my video could be split into smaller videos.

In example:
-  Where to find block patterns.
-  How to search for a block pattern.
-  How to Copy a pattern for the directory and paste it on your website.
-  How to edit/customise a Pattern.
- ...

And all these together, "How to use the Block Pattern Directory."

**Comment by becreativemkt** [comment]
@westnz great video! +1 on the music volume recommendation from @lada7042

**Comment by westnz** [comment]
Thank you very much @becreativemkt

**Comment by westnz** [comment]
[Feedback from Dan Soschin](https://wordpress.slack.com/archives/C0GKJ7TFA/p1676042491245949?thread_ts=1675892287.485239&cid=C0GKJ7TFA):
"Looking at yours, I think it’s great. I love feature-specific explainers. No real feedback other than NICE JOB, can we get more? :slightly_smiling_face:"

**Comment by sereedmedia** [comment]
Just dropping by to let you know I'll be sending some folks your way. :)

**Comment by courtneyr-dev** [comment]
I love @vagelisp including both layouts for the video. @vagelisp do you have the exact dimensions for Instagram Reels/TikTok style videos (vertically)? 

@westnz I'm thinking about using this: https://jetpack.com/support/jetpack-blocks/story-block/.  It is enabled in LearnWP already :) 

Kraft in Jetpack is reviewing hosting vids on WPTV and then embedding them into content on LearnWP.  I'm inquiring for where we store the videos.  Also we could experiment with the photos method of Story Block as well. These would live as Posts or a Custom Post Type possibly. Need to think on this a bit more.

**Comment by vagelisp** [comment]
Hey @courtneyr-dev , both Instagram and TikTok use 1080p x 1920p for the videos

**Comment by courtneyr-dev** [comment]
Referencing an early warm up I started - the first vid could really be refined. None have audio. I want to rework these as vertical vids with brief narration. Feedback welcome. 
 https://twitter.com/courtneyr_dev/status/1630324455439323140

**Comment by westnz** [comment]
@courtneyr-dev These are great for highlighting changes that will come with the 6.2 release.  Well done! Adding narration sounds like the best step forward. 

I noticed the first video had over 1200 views, but the others all had under 40 views. @sereedmedia, I know you mentioned, 'Maybe each video focuses on just one small task or feature. Then the short bites could be strung together as a series.' Wouldn't most folks prefer to watch one video at a time?  Would separate short videos be better compared to a string? Also, is a string more aimed at Twitter?

**Comment by courtneyr-dev** [comment]
I think Twitter prefers threads, but can experiment on my own timeline uploading the others individually to see how they perform as well. 

It'd be great to know the target platforms for bite sized content that are horizontal, and vertical. 

- On LearnWP itself as stories (these can be images or videos)
- Twitter, IG posts, FB posts, LinkedIn posts - square or horizontal?
- TikTok, IG reels/stories, FB stories, Youtube shorts vertical
- Youtube channel horizontal


@sereedmedia do we know the intended social channels? 

All: up for exploring using LearnWP stories for these?

**Comment by westnz** [comment]
Dan Soschin has scheduled the first example to be published on March 8th on Twitter, LinkedIn, Instagram and Facebook to see what happens. He mentioned that video sharing usually does well on social media. Furthermore, he also mentioned: "I still think we should do two more things - if we decide to do more of these: (a) store these all in a single place somewhere online so they can be viewed on-demand as social posts have a short shelf life (b) maybe do a 2-second preroll with some WordPress branding."

**Comment by courtneyr-dev** [comment]
@westnz we do have a shared folder used in the training team. Is that an ideal place for Dan?

**Comment by westnz** [comment]
@courtneyr-dev, Dan was referencing to a public place, like YouTube, or [WP.tv](http://wp.tv/), etc., so that people can browse the whole library, and we’d have long-term value for brand awareness, SEO, etc.

**Comment by courtneyr-dev** [comment]
Ah good thinking. We do have a training team Youtube channel as a temporary or side-project place if we need it for any testing. We'd need to work with @eidolonnight for any access to Youtube on the proper .org account.

**Comment by westnz** [comment]
Yes, the .org account is probably our best bet to keep everything centralised.

**Comment by westnz** [comment]
Twitter post (Reusable blocks): https://twitter.com/WordPress/status/1633520065739132928

**Comment by westnz** [comment]
Feedback from Dan about the social media post: 
- Decent engagement and impressions.
- Consistent with the other type of LearnWP content we push out. 
- Sharing video directly on social tends to do “above average” vs posts without video. The “regular” learnWP posts we link to the video (vs post the video), do well, but they won’t do as well as embedding the video. It’s just not apples to apples. 
- We want to raise awareness and drive traffic to [learn.wordpress.org](http://learn.wordpress.org/), so linking out to the 5-minute videos is still very useful. 
<img width="932" alt="Screenshot 2023-03-14 at 8 43 46 AM" src="https://user-images.githubusercontent.com/89751452/225485537-a32da70b-511b-4191-aea5-73cdc94d7426.png">

**Comment by sereedmedia** [comment]
In terms of shorter content and my comments as to that ... the original idea to my understanding was to do "bite-sized content" and that dovetailed nicely with a push within marketing to develop some content on WordPress' TikTok. TikTok content and YouTube/Twitter/LI/FB etc is definitely not the same in terms of format or approach. Reels is much more in line with TikTok, but neither are geared toward the traditional video format.

I think what we've ended up with is instead short clips of a longer, more traditional video. I think putting those clips on social media is a great way to support Learn! But it is not the same thing as developing content for TikTok. 

cc: @westnz

**Comment by westnz** [comment]
Understood, thanks for the feedback @sereedmedia

**Comment by kaitohm** [comment]
I'm closing this issue now, as it seems the exploration stage of this project has concluded. If/when the Training Team picks bite-sized content up as a regular task again in future, we can reference the findings here. Thanks to all who contributed!
