### ISSUE TITLE
Lesson - Creating a custom template 

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1266]
# Topic Description
Creating a custom template for different types of posts or pages.

//tutorial

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/214428742-14b3605e-1820-4b24-8b4a-eccaf1cc1997.mp4

**Comment by wparasae** [comment]
Your sample website is really lovely, Wes. I also really appreciate how well you use cursor effects here. It makes it very easy to follow what you're doing and when!

A consideration for change: Since the vast majority of WordPress themes are still classic themes, you might consider adding a brief mention somewhere (beginning or end) about how this method of creating a custom template will only work with block themes--classic themes require coding to make custom templates. 

Overall, this is very clear and I cannot wait until it's published so I can add it to a course or two! :)

**Comment by westnz** [comment]
Thank you for the feedback Sarah!

**Comment by digitalchild** [comment]
Re-iterating what @wparasae I suggest naming the tutorial Creating a Template with the WordPress site editor. 

At 0:38 you say 'a site editor' isn't it the site editor? 

The only other thing is it might be good to also outline that you can use quick edit to change the template. 

Other than that, clear and concise as always.

**Comment by westnz** [comment]
Thanks so much! @digitalchild

**Comment by nomad-skateboarding-dev** [comment]
This was great, Wes! Well done. 🙌

Anecdotally, I've seen more confusion over exactly what you've explained here than most other questions regarding the site editor combined. 

I felt the duration was about perfect to really get a handle on what was going on with templates. The examples used were great. I especially liked that you kept everything simple, as I didn't feel overwhelmed when you jumped back and forth between templates and pages. 👍

**My only thought for possible editing**
-  In some spots I felt I couldn't quite focus in on what you were clicking in the menus until we were on the next screen. The descriptors and the voiceover felt perfect, just maybe half a second too far ahead for my eyes to focus in on what was about to happen before it did.

That feedback is if I'm stretching to find something off! Again, this was a fantastic video, Wes! Great work. 😀👏

**Comment by westnz** [comment]
Thank you very much for the feedback @nomad-skateboarding-dev 😃

**Comment by westnz** [comment]
Thank you, I have implemented everyone's feedback and re-recorded large parts for the 6.2 release. 

https://user-images.githubusercontent.com/89751452/221866868-ce2f1f0c-815b-4ad9-b3d8-513ad01eecfa.mp4

**Comment by courtneyr-dev** [comment]
To @nomad-skateboarding-dev 's point, I think zooming in to the maximum amount before mobile mode kicks in would be ideal. 

https://learn.wordpress.org/lesson-plan/best-practices-when-capturing-images/ (works for videos as well). When we are looking at the list view, it looks rather small, or the admin dashboard. `CMD +` in as much as you can!

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/creating-a-custom-template-with-the-wordpress-site-editor/

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/15e8870c-72b8-4285-a989-ec503de19f7f

**Comment by devmuhib009** [comment]
@westnz,  video ended at 5:09, and rest of the part is blank. Please check.

**Comment by westnz** [comment]
Ah, thank you for catching that @devmuhib009. I see it is because of the red arrow I forgot to remove at 6:53. I will add a new copy of the video.

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/6e18a6ff-b991-45b2-bd5b-2bd125dee4ad

**Comment by kathrynwp** [comment]
Looks great, Wes!

I had just two small, optional, suggestions – but the tutorial is solid without these changes.

- When you start to show the Drone landing page in the page editor, might also be good to briefly show the front end as well, to emphasize the fact that this page still has the same standard header & footer. 
- When you show how to create the custom template for the landing page, it could be an idea to show the alternative way of getting here, i.e. via the button in the Manage All Templates area – see screenshot below. (On the other hand, I could understand if you wouldn't want to confuse things, and focus on a single way of getting there!)

<img width="1488" alt="Blog_Home_‹_Template_‹_Food_Connection_‹_Editor_—_WordPress" src="https://github.com/WordPress/Learn/assets/7662449/5f9666dd-b4c8-482d-8e43-5880b8e8c8b6">

Again, I don't think either of these is critical, and the tutorial is good to go as is.

**Comment by westnz** [comment]
Thank you very much @kathrynwp

**Comment by westnz** [comment]
Updated and published as part of the Intermediate user learning pathway in Sensei.
