### ISSUE TITLE
Tutorial - Interacting with the WP REST API

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1267]
# Topic Description
In the [previous session](https://wordpress.tv/2023/01/13/lets-code-using-the-wordpress-rest-api/) you were introduced to the WordPress REST API, as well as the Backbone.js client to interact with it.

In this session, we will look at how you can interact with the WP REST API further, but adding and deleting data. We will also look at a useful developer tool for testing your REST API endpoints.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [x] Tutorial submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Tutorial submitted to WPTV https://wordpress.tv/submit-video/
- [x] Tutorial published on WPTV
- [x] Tutorial is captioned https://make.wordpress.org/training/handbook/tutorials/tutorial-subtitles-and-transcripts/
- [x] Tutorial created on Learn.WordPress.org
- [x] Tutorial post is reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial announced to training team
- [x] Tutorial announced to creator
- [x] Tutorial announced to Marketing Team for promotion
- [x] Gather feedback from workshop viewers/participants

**Comment by jonathanbossenger** [comment]
Script https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/wp-rest-api-02-interacting.md

**Comment by jonathanbossenger** [comment]
Video for review:

https://user-images.githubusercontent.com/180629/216321378-26d3dd5e-4163-404d-9ce1-ab60f1cca7ff.mp4

Creators note: this tutorial is the longest one I've ever created, coming in at 20 minutes, around double the length of our usual content. However, given the nature of the content, I don't see how we could easily break this up into smaller videos, so I'm recommending we keep it at the current length.

**Comment by ghost** [comment]
Nice tutorial, I think this will be helpful for a lot of developers new to the REST API. 🙂

I have a few small pointers.

Firstly, have all the URLs (including the one that's now on screen in the beginning) in the video description and point the learners there (maybe you were already planning on doing this).

Secondly, you mention this video is longer than the usual tutorial. I think a way to cut this down without losing any of the content, is by pasting in code snippets instead of typing them as you go. This way you can focus on explaining what you just pasted in, instead of "mumbling" what you're doing while you're typing (we all know how hard it is to explain something while you're concentrating on code 😄).

This is especially true when you're repeating something you've already done (there's not that much difference between HTTP methods), or when you're doing something that's not really relevant for the subject of the video like creating the HTML form. Everyone that watches this is expected to know how to make an HTML form, so you can paste it in and then e.g. highlight the ID's you're using.

Lastly, for people watching on their phone or having the video float on top of their editor (so not watching full screen), it would be nice to have your screens a bit more zoomed in.

Overall, great job!

**Comment by jonathanbossenger** [comment]
Thanks for the review @thomasdevisser. 

> Firstly, have all the URLs (including the one that's now on screen in the beginning) in the video description and point the learners there (maybe you were already planning on doing this).

I am planning this indeed. If you look at the [script](https://github.com/WordPress/Learn/issues/1267#issuecomment-1397172390) you'll see I include all code snippets and links in clickable text form, which eventually will be included in the body of the tutorial on Learn WordPress. 

> I think a way to cut this down without losing any of the content, is by pasting in code snippets instead of typing them as you go.

One of the early pieces of feedback I've received from multiple sources is that doing it in a "live code" style, which includes my thoughts as a code, is useful for beginners, instead of copy/pasting the code, as it gives folks more time to digest the content. As most of these tutorials are aimed to be beginner friendly, I include this as part of my recording process. Again, the code examples will be in the body of the final tutorial, so more advanced folks can skip over this and just copy/paste what they need.

> Lastly, for people watching on their phone or having the video float on top of their editor (so not watching the full screen), it would be nice to have your screens a bit more zoomed in.

It's difficult to make a video coding tutorial that works across all screen sizes, which is yet another reason I include all code snippets etc in the body of the final tutorial. For now, I've had to find a good balance, which I'm sticking with.

**Comment by ghost** [comment]
No problem @jonathanbossenger! I didn't know the purpose of the script, good to know, thanks!

> One of the early pieces of feedback I've received from multiple sources is that doing it in a "live code" style, which includes my thoughts as a code, is useful for beginners, instead of copy/pasting the code, as it gives folks more time to digest the content.

I agree with this when it's code addressing the actual subject of the video, in this case working with the API, but when it's e.g. boilerplate HTML, there's nothing wrong with pasting that in. 🙂

**Comment by westnz** [comment]
Review:

1. Excellent tutorial
2. You do a good job at shedding light on the Endpoint reference/fields and clearing any confusion that may arise. 
3. I agree, the live code style is educationally sound as it helps learners to follow along and digest what is being taught. I also agree, depending on the context, it is also fine if you sometimes copy and paste code. 
4. You explain things very clearly and help learners to understand the 'why'! 💪 
5. I really appreciate the way you speak directly to the learner, as it makes it more personal.

**Comment by jonathanbossenger** [comment]
Thanks, @westnz 

In the future, I'll try and see if there are code blocks that could be copy pasted. 

Generally, I tend to try and make sure the tutorial video can speak to both the brand-new developer, as well as the experienced one. In this case, covering how HTML forms work seemed appropriate, as someone who's never coded a form before might get confused if I just pasted HTML and went from there.

My general rule of thumb is that I'd rather an experienced developer skip past code they already understand, than an inexperienced one not get the full benefit of the tutorial video.

**Comment by westnz** [comment]
I think your general rule of thumb is spot on!

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/tutorial/interacting-with-the-wordpress-rest-api/

**Comment by kaitohm** [comment]
Is this requiring any other attention, @jonathanbossenger ? Or can it be closed?

**Comment by jonathanbossenger** [comment]
Thanks Ben, I just had two more items to tick off before I could close it.
