### ISSUE TITLE
Learn WordPress Content Error Report - Adding extra context

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#1270]
# Error Description
- Content URL: https://learn.wordpress.org/lesson/make-the-block-interactive/

Not really an error, but a suggestion for extra context.

In the Slack channel [I asked why Edit() has a capital letter and save() is all lowercase](https://wordpress.slack.com/archives/C02RW657Q/p1674054228879729). Jonathan replied with a link to [a GitHub discussion](https://github.com/WordPress/gutenberg/pull/38139#issuecomment-1021039413) on this.

I think this would be a nice addition to the course, even if it's just a link to this issue for further reading, as it clears up a lot of the abstraction which actually makes the functions more clear.

# Error Report Checklist:
- [x] Error Validated
- [x] Error fix proposed
- [x] Error fix reviewed
- [x] Error fix published

**Comment by jonathanbossenger** [comment]
@mburridge you might want to take a look at this one.

**Comment by mburridge** [comment]
Thanks for the heads-up on this @thomasdevisser. I've added a callout box toward the bottom of [this page](https://learn.wordpress.org/lesson/understand-the-structure-of-the-project/) to explain the difference in casing between `Edit()` and `save()`.

Let me know if you think anything could be clarified or improved in any way.

**Comment by ghost** [comment]
This is great, @mburridge! Couldn't have written it better myself. The only thing you might want to change is the UK English for `is spelt` to `is spelled` which is used in both US English and UK English, WordPress being founded as an American company I believe.

**Comment by mburridge** [comment]
Fixed it. Funnily enough I originally put 'spelled', but Grammarly corrected me so I changed it. TBH there's probably lots of UK English throughout the course, probably lots of '-ise' instead of '-ize'. 🤷‍♂️

**Comment by mburridge** [comment]
>WordPress being founded as an American company I believe.

A bit nit-picky I know, but WordPress is not actually a company. WordPress was in fact created by two people, one American and the other British.

**Comment by ghost** [comment]
@mburridge I love nit-pickiness, thanks for the clarification! I think this issue can be closed now, thanks for picking this up so swiftly.
