### ISSUE TITLE
Online Workshop - Builder Basics: Adding Custom CSS to Block Themes

### ISSUE THREAD

**Issue by ndiego** [WordPress/Learn#1274]
# Event Details
- Title: Builder Basics: Adding Custom CSS to Block Themes
- Description: See Below
- Target Audience: Builder
- Date: 2/7/2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/291094663/
- Co-host: @lada7042 

### Details
One major benefit of block themes is that they can be built with very little CSS. For example, the Twenty Twenty-Three theme has none. All block styles are defined in a theme.json file. While theme.json is getting more powerful with each WordPress release, you will likely need to add some custom CSS in most projects.

This Online Workshop will explore ways to add custom CSS to a block theme while ensuring those styles work correctly in the Editor and on the site's frontend. If time permits, we will also discuss a Sass workflow you can employ to optimize per-block styles.

### Learning Objectives

- Understand when to use custom CSS in a block theme and when you probably don’t need it.
- Learn how to target specific block types with CSS.
- Learn how to use per-block stylesheets.
- Learn how to use the new custom CSS field in the Site Editor (coming in 6.2) and how it ties to theme.json.
- Learn how to combine per-block stylesheets with Sass. (if time permits)

### Meetup Information

- Where: Zoom (Link will be visible after RSVP)
- Audience: Builders
- Level: Intermediate
- Language: English with live Zoom transcription

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by ndiego** [comment]
This event can be easily run without a co-host, so removing the label. That said, if anyone wants to co-host, the more the merrier.

**Comment by ghost** [comment]
I am available to co-host this workshop too.

**Comment by ndiego** [comment]
Thanks @lada7042, I updated the description.

**Comment by ndiego** [comment]
The recording is available on [WordPress.tv](https://wordpress.tv/2023/02/08/builder-basics-adding-custom-css-to-block-themes/).
