### ISSUE TITLE
Online Workshop - Builder Basics: Block Styles vs. Block Variations

### ISSUE THREAD

**Issue by ndiego** [WordPress/Learn#1275]
# Event Details
- Title: Builder Basics: Block Styles vs. Block Variations
- Description: See below
- Target Audience: Builders
- Date: 2/28/2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/291095902/
- Co-host: @lada7042
- Other info: 

### Details
What’s a block style? What’s a block variation? Is there a difference between the two? When should you create a variation instead of a custom style?

In this Online Workshop, we will answer these questions and more. Block styles are a great way to modify the visual aesthetic of blocks, and block variations are one of the most overlooked tools for building customized block-based editing experiences in WordPress. Learn how to use this powerful functionality in your own projects.

### Learning Objectives

- Understand the difference between block styles and block variations and when to use each.
- Learn how to create a block style.
- Learn how to create a block variation.
- Learn how to modify a block style in the Site Editor, a new feature scheduled for WordPress 6.2.

### Meetup Information

- Where: Zoom (Link will be visible after RSVP)
- Audience: Builders
- Level: Intermediate/Advanced
- Language: English with live Zoom transcription

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by kaitohm** [comment]
I've confirmed the attendance has been recorded. Closing.
