### ISSUE TITLE
Tamil translation for Lesson Plan "Difference between Reusable Blocks, Block Pattern, Templates, Template Parts"

### ISSUE THREAD

**Issue by karthick-murugan** [WordPress/Learn#1276]
# Details
- Link to original content: [https://learn.wordpress.org/lesson-plan/difference-between-reusable-blocks-block-pattern-templates-template-parts/](https://learn.wordpress.org/lesson-plan/difference-between-reusable-blocks-block-pattern-templates-template-parts/)
- Link to original content GitHub issue: [https://github.com/WordPress/Learn/issues/450](https://github.com/WordPress/Learn/issues/450)
- Language you'll be translating to: Tamil
- Have you arranged for someone to review this translation?: No ( Please assign someone to review )
- Reviewer's GitHub username: -
- Other info: [https://docs.google.com/document/d/1yGmNPVmm9_3SpjnFF7gOugyB89iN_9e7r0N_raQiK_I/edit](https://docs.google.com/document/d/1yGmNPVmm9_3SpjnFF7gOugyB89iN_9e7r0N_raQiK_I/edit)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by karthick-murugan** [comment]
Hi @Piyopiyo-Kitsune.,

I have completed the second lesson page translation in Tamil language. Please assign a reviewer for reviewing the content and move forward. Thanks in advance.

**Comment by karthick-murugan** [comment]
@Piyopiyo-Kitsune - This is ready for review now.

**Comment by dhanendran** [comment]
@karthick-murugan @Piyopiyo-Kitsune I have reviewed the doc and added the suggestions. Everything looks good.

**Comment by Piyopiyo-Kitsune** [comment]
Hey there @karthick-murugan ! Can you kindly review this https://learn.wordpress.org/?p=32431&post_type=lesson-plan&preview=1&_ppp=440c8aa2cf fix any formatting issues, and approve for publication if it looks good?

**Comment by karthick-murugan** [comment]
sure @Piyopiyo-Kitsune. Will check and update.

**Comment by karthick-murugan** [comment]
@Piyopiyo-Kitsune - Checked all the contents and updated the main title, since it was in english. Now it is ready to publish. Thanks for your efforts.

**Comment by Piyopiyo-Kitsune** [comment]
Thank you for your hard work! We're published! https://learn.wordpress.org/lesson-plan/ta-difference-between-reusable-blocks-block-pattern-templates-template-parts/ 🎉
