### ISSUE TITLE
[Course Feedback] Create a Block Theme (Low-Code) - Module #5 Feedback Template

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1277]
Related to Course: Course: [Create a Block Theme (Low-Code) - Course #1 #631](https://github.com/WordPress/Learn/issues/631)

In an attempt to reduce clutter on the Training Team Github board and simplify everyone's lives, I'm creating this template to collect public feedback on the final module in the course, [Develop Your First Low-Code Block Theme](https://learn.wordpress.org/course/develop-your-first-low-code-block-theme/?preview_id=20124&preview=true).

**Lessons **
_Please review each lesson below in a comment on this Github issue_
1. [Completing Your Custom Theme: Taking a Screenshot (Preview here)](https://learn.wordpress.org/?post_type=lesson&p=20186&preview=true)
2. [Completing Your Custom Theme: Adding Information in style.css (Preview here)](https://learn.wordpress.org/?post_type=lesson&p=27558&preview=true)
3. [Theme Enhancements - Offering Reusable Blocks, Unique Templates, Unique Patterns, Style Variations (Review here)](https://learn.wordpress.org/?post_type=lesson&p=23882&preview=true)
4. [You're Almost Finished! What's Next? (Review here)](https://learn.wordpress.org/?post_type=lesson&p=20190&preview=true)

**Add a comment to this post. Some suggested questions:**
1. What was clear to you? What could use additional information?
2. Is anything technically incorrect with this information? If so, what change should be made?
3. Do you see any typos? What are they?

Please add comments for lessons in module #5 in this singular Github issue. Thank you!

**Comment by wparasae** [comment]
[Review #1 (Thanks @westnz !) - Google Doc](https://docs.google.com/document/d/1E0Nkoer4Le1Q0VubnqFuZkpG6dOS-WJS-7FvQGALPAI/edit?usp=sharing)

**Comment by nomad-skateboarding-dev** [comment]
Impression overall for this module: the most fun and informative module I've taken on Learn! I feel like this whole course gave me more knowledge and confidence as a block theme developer than most of my previous studies outside of WordPress.org. 🙂👏

**Completing your custom theme taking a screenshot**
1. The reminder to refresh to see changes is a key item. Well done.

**Adding information in style.css**
1. This might be the most helpful page I've come across so far for my block theme development journey. 😀🙌
2. Should the word "if" appear before "you"  highlighted in this screenshot?![Screenshot_20230125-194647.png](https://user-images.githubusercontent.com/78917704/214758642-66f3cd96-971d-4f42-ae8a-651a19048b61.png)

**Theme enhancements**
1.This was awesome. I really liked the reminder at the bottom on keeping it simple! 

**Final steps**
1. The second sentence of step 2 reads a little fuzzy to me? 🙂  For myself, 'Type the new name to the custom theme template name.' reads great! (It also makes the three steps seem that much shorter with less words. 😅)
![Screenshot_20230125-195945.png](https://user-images.githubusercontent.com/78917704/214759055-82e22138-c6f0-42d8-a0ff-36048e977767.png)

**In Course Menu**
In the course menu on mobile view, section 5 of module 3 doesn't display fully. All the other sections display. 
1. Tested on Chrome and Firefox mobile browsers.
![Screenshot_20230125-233534.png](https://user-images.githubusercontent.com/78917704/214781009-cdf10a50-9567-4bff-9681-7692990938f7.png)

**Comment by wparasae** [comment]
I've made all recommended changes ^ above -- I'm not sure what's going on with the mobile menu yet, so I will look into this once the course is published and see if we can replicate that somewhere else on another course, or if it's just this one. Thank you for pointing that out!

**Comment by wparasae** [comment]
I double-checked with @jonathanbossenger over a technical question I had; he also reviewed the last module for accuracy, and I corrected a small misconception of my own. I think this is just about ready!
