### ISSUE TITLE
Editing already live material

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#128]
As core updates are released, content will need to be updated.  The current method is awkward at best.  Copy/paste a lesson plan to a new post as a draft. Make changes, publish live.  Lesson plans need to be reviewed before going live for large changes, such as core updates.  

The post editor revision tool is better suited for comparing to past content, not well adapted to working into the future.  The team could start preparing updated materials with Release Candidate versions when there are significant changes (say WP5.5 Gutenberg integration) and hold on publishing until Core ships. 

It doesn't seem like a functionality Edit Flow can currently do.  I could see Docs using this same idea on articles as well.

**Comment by hlashbrooke** [comment]
@coreymckrill Do you know of an existing solution that makes this more possible? I agree that it's a tough thing to solve and there's a reason why GitHub is so frequently used for this purpose.

**Comment by coreymckrill** [comment]
I've run across [one plugin](https://wordpress.org/plugins/content-update-scheduler/) that provides this functionality, but after a quick skim, I'm not sure it's one we'd consider installing on wp.org.

It's honestly surprising to me that there aren't more options out there (or maybe I've failed at searching), given how common this use case is.

I'll do some more research to see what other previous efforts might be out there...

**Comment by hlashbrooke** [comment]
There's also [this similar plugin](https://wordpress.org/plugins/tao-schedule-update/), but it hasn't been updated in the last 2 years. It looks like it has a cleaner integration though, so from a UI perspective it might be a better fit.

**Comment by coreymckrill** [comment]
Since there isn't an easy answer to this, here's a potential workaround for the time being: I've enabled the [Copy Post](https://jetpack.com/support/copy-post/) module from Jetpack on the Learn site. With this functionality, when a lesson plan needs to be updated for a new release of WP or something, it can be copied to a separate post draft, edited, and then its content can be pasted into the original post when the time comes.

**Comment by coreymckrill** [comment]
Here's an update on this issue:
https://make.wordpress.org/meta/2021/02/04/in-progress-scheduling-updates-to-published-posts-on-wordpress-org/

**Comment by courtneyr-dev** [comment]
Linking back the testing feedback:

https://youtu.be/E5FBnVKPzCc Me testing and narrating my way through.
1. In the yellow notification area, reword "Edit Post" to "Edit Original Post"
2. Learning the new workflow on checking future update then set date before beginning to edit. It took me a few times through to remember that order.
3. Took just a moment to find the Updates item in dashboard admin menus.  If this goes to .org as a "plugin as a feature"  - possibly a introductory welcome trainer panel like Block Editor takes us through?

**Comment by coreymckrill** [comment]
Since our revisions plugin is now live on the Learn site, I'm going to go ahead and close this.
