### ISSUE TITLE
Online Workshop - Using the Columns Block

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1280]
# Event Details
- Title: Using the Columns Block
- Description: Demo: using the Columns block to create various designs.
- Target Audience: Users
- Date:
1. Event 1: 14 Feb @ 9am (New Zealand)
2. Event 2: 1 March @ 7pm (New Zealand)
- Meetup.com event link:
1. Event 1: https://www.meetup.com/learn-wordpress-online-workshops/events/291190192/
2. Event 2: https://www.meetup.com/learn-wordpress-online-workshops/events/291190641/
- Co-host: 
1. Event 1: Mark-Andrew
2. Event 2: Needs cohost
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by courtneyr-dev** [comment]
Can we be sure to close out the checklists too when closing @westnz ?

**Comment by westnz** [comment]
Thanks for the reminder.

Recording: https://drive.google.com/drive/folders/1PJTR_VEUikMnBSBJexthcxss9ctl4VZu
