### ISSUE TITLE
Learn WordPress Content Error Report - Custom Fonts Quiz

### ISSUE THREAD

**Issue by admturner** [WordPress/Learn#1282]
# Error Description
- Content URL: https://learn.wordpress.org/quiz/custom-fonts-summary/
- Content title: A Developers Guide to Block Themes – Part 2 - Custom Fonts Quiz

One of the questions in the Custom Fonts Summary quiz appears to be broken. For the question "What will be the CSS variable created for a custom font registered with the slug “open-sans”?", selecting the correct answer: " ––wp––preset––font–family––open–sans" produces an incorrect result. But the correct answer shown on the results page is: "––wp––preset––font–family––open–sans".

# Error Report Checklist:
- [ ] Error Validated
- [ ] Error fix proposed
- [ ] Error fix reviewed
- [ ] Error fix published

**Comment by jonathanbossenger** [comment]
Thanks for logging this @admturner. There are some issues with rendering HTML special characters like `--` as answers in the Sensei course software, so I'm going to remove that quiz question for now.

**Comment by kaitohm** [comment]
@jonathanbossenger Is this something we should move to the Website Development project board, or can we close this out for now?

**Comment by kaitohm** [comment]
Noting a similar issue: https://github.com/WordPress/Learn/issues/1259

**Comment by jonathanbossenger** [comment]
@bsanevans I think we should close this and #1259 for now. I have noted this and will adjust my quizzes accordingly in the future.
