### ISSUE TITLE
Online Workshop - Let's code: extending the WP REST API - modifying responses

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1283]
# Event Details
- Title: Let's code: extending the WP REST API - modifying responses
- Description: The WordPress REST API provides an interface for applications to interact with your WordPress site by sending and receiving data as [JSON](https://en.wikipedia.org/wiki/JSON) (JavaScript Object Notation) objects. By default, it provides REST endpoints (URLs) representing the posts, pages, taxonomies, and other built-in WordPress data types. Your application can send and receive JSON data to these endpoints to query, modify and create content on your site. However, it is also possible to extend the WP REST API, in order to perform specific actions that are outside of the scope of the default routes and endpoints. In this session, you will learn about one of the ways you can extend the WP REST API, by modifying REST responses.
- Target Audience: Developers
- Date: 2023-02-02 14:00 UTC
- Meetup.com event link: https://us06web.zoom.us/j/81213167660?pwd=bDdqR0F6L3FkOHcrNjRRMkxkY2pOUT09
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
Notes: 

- https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/
- register_meta - if the object_subtype argument is left out, it will be registered on all CPT of the parent post
- register_rest_field, should be hooked into rest_api_init
- register_rest_field creates a top-level REST API field on the resource, not a meta field in the meta object
- get_callback is passed an array of the prepared data
- update_callback is passed the resource object
- overview of different types
- overview of links

**Comment by nomad-skateboarding-dev** [comment]
I'd like to volunteer to co-host this workshop, Jonathan. 🙂

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/02/03/lets-code-wp-rest-api-modifying-responses/
