### ISSUE TITLE
Tutorial - Plugin Security: Common Vulnerabilities

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1286]
# Topic Description
In the plugin security best practices tutorial we covered the 5 top ways you can ensure your plugin is developed securely. However, it's important to understand why you need to follow these principles. 

In this tutorial, we will cover the top 3 Common Vulnerabilities that are found in plugins, and how to use the practices taught in the previous tutorial to combat them.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ Common Vulnerabilities](https://developer.wordpress.org/apis/security/common-vulnerabilities/)

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
A great list of additional improvements is [mentioned here](https://github.com/WordPress/Learn/issues/949#issuecomment-1410881462).

**Comment by jonathanbossenger** [comment]
Lesson plan/script for this tutorial: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/wordpress-common-vulnerabilities.md

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/224724537-60cce794-4aba-4936-94de-fbbc70d2a78e.mp4

Video for review.

**Comment by westnz** [comment]
Good job, Jonathan!

Review
- Clear video and instructions 
- Annotations effectively used
- Check the voice recording at 3:38 / 3:39 seconds

**Comment by nomad-skateboarding-dev** [comment]
# Overall Impression
Well done!
## Specific Feedback
- Agree with @westnz that this is a clear video and instructions.
- As Wes also noted, only non-technical part that was off was the transition at 3:38. I can tell you're saying, "The most", but it cuts in a millisecond late.

**Comment by jonathanbossenger** [comment]
Thanks, @westnz and @nomad-skateboarding-dev for the reviews.

With regards to the voice cut-off, this happens due to the Krisp software I use to filter out white noise, etc. It sometimes cuts off the first word I speak. I'll try and do my best to cough or click my fingers before I speak in the future 😁

**Comment by jonathanbossenger** [comment]
Published https://learn.wordpress.org/tutorial/extending-wordpress-common-security-vulnerabilities/
