### ISSUE TITLE
Online Workshop - EP10: Block Editor (Gutenberg) : What and How | Bangla

### ISSUE THREAD

**Issue by esrat71** [WordPress/Learn#1295]
# Event Details

- Title: EP10: Block Editor (Gutenberg) : What and How | Bangla
- Description: This is the 10th (of 12th) episode of WordPress for Beginner | Bangla series.
Our main goal is to help new contributors (tech and non tech) to get started easily with WordPress.
In this episode we will know about the Gutenberg Block Editor and usage of basic Gutenberg Blocks.
We will explain all Gutneberg Blocks and how they reflects in frontend.

- Target Audience:  Bangla Speaking People
- Date: February 6, 2023 
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/291324452/
- Co-host: Fuad Ragib
- Other info: This is an online localized mini workshop (via Zoom).

# Online Workshop Checklist:
- [✅] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [✅] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by fuadragib01** [comment]
Please assign me as co-host.

**Comment by esrat71** [comment]
WordPress.tv video Link : https://wordpress.tv/2023/02/10/ep-10-block-editor-gutenberg-what-and-how-bangla/
