### ISSUE TITLE
Online Workshop - EP11: Block Editor (Gutenberg) : Settings | Bangla

### ISSUE THREAD

**Issue by fuadragib01** [WordPress/Learn#1296]
# Event Details
- Title: EP11: Block Editor (Gutenberg) : Settings | Bangla
- Description: This is the 11th episode of WordPress for Beginner | Bangla series. Our main goal is to help new contributors (tech and non tech) to get started easily with WordPress. In this episode, we will show the WordPress Dashboard and explain all the Dashboard menu items. We will explain full WordPress Dashboard interface and how they reflect in frontend.
- Target Audience: Bangla Speaking People
- Date: February 07, 2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/291324588/
- Co-host: Fuad Ragib (@fuadragib01)
- Other info: This is an online localized mini workshop (via Zoom).

# Online Workshop Checklist:
- [✅] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [✅] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [✅] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [✅] Hold Online Workshop
- [✅] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [✅] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by esrat71** [comment]
Kindly Assign Me. Thank You

**Comment by fuadragib01** [comment]
WordPress.tv video link: https://wordpress.tv/2023/02/10/ep-11-block-editor-gutenberg-settings-bangla/
