### ISSUE TITLE
Tutorial - Displaying testimonials on your website

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1298]
# Topic Description
Adding a testimonial to your site.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
Uploading Testimonial Tutorial.mp4…

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/217472894-abcbe188-3544-4074-9762-a453f908fd2a.mp4

**Comment by digitalchild** [comment]
At the beginning of the video, you outline that there are two ways to add a testimonial to your site; patterns and blocks. However, if the video, you mention a third which is via plugins and plugins are usually more directed towards classic themes, while the rest of the video is directed at the Site editor.

**Comment by westnz** [comment]
Thank you for taking the time to review @digitalchild.  I will ensure that I highlight I am using a block theme. To clarify, though, I added the pattern and the block to a page - you can do this with a classic theme as well. I didn't use the Site Editor as the Site Editor is mainly used for managing your templates, template parts and global styles.

**Comment by NadaElSharkawy** [comment]
Thank you for the great tutorial, an idea to enhance the lesson, in the beginning when you start explaining the importance of testimonials is to add some tips on where to add it in the website and perhaps at the end show some examples of them after they're published.

**Comment by westnz** [comment]
Thank you for the feedback @NadaElSharkawy!

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/displaying-testimonials-on-your-website/
