### ISSUE TITLE
Bug: Images on Post Formats (Theme) are broken

### ISSUE THREAD

**Issue by nielslange** [WordPress/Learn#130]
**Steps to reproduce**

1. Go to https://learn.wordpress.org/lesson-plan/post-formats-theme/
2. Scroll down to sections _Introduction: What are Post Formats?_ and _How Post Formats Work_

**Expected behavior**

The images are visible.

**Current behavior**

The images are not visible.

**Comment by coreymckrill** [comment]
Thanks for the report! I'm going to close this issue, as this repo is intended for technical issues and feature enhancements, but I've flagged this lesson plan as having missing images. If you find other content issues with lesson plans, the best place to mention is in the [#training](https://wordpress.slack.com/archives/C02RW657Q) channel in WP Slack.

**Comment by nielslange** [comment]
Thanks, @coreymckrill. I wasn't aware where to report this issue, that's why I created it here. Thanks for closing it and pointing me into the right direction. 😀
