### ISSUE TITLE
Online Workshop - WP REST API - custom routes and endpoints

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1304]
# Event Details
- Title: Let's code: WP REST API - custom routes and endpoints
- Description: The WordPress REST API is more than just a set of default routes. It is also a tool for creating custom routes and endpoints. In this session, you'll learn how to create custom routes and endpoints, and test them using Postman.
- Target Audience: Developers
- Date: 2023-02-09 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/291383615/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by joshwinny** [comment]
Hi @jonathanbossenger, I'm will to Co-host with you. Would you please let me know what I should do?

**Comment by jonathanbossenger** [comment]
Hi @joshwinny 

If you haven't read it already, here are some general guidelines around co-hosting https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/.

From my perspective the most important tasks I need from a co-host are:

- Once the workshop has started, and the recording is going, admit any latecomers into the Zoom meeting
- Keep an eye on the chat, and let me know if I miss any important questions
- About halfway through, take a head count of the participants
- Keep an ear out for any folks who have background noise coming through their mics, and mute them

Let me know if this works for you, and I can add you as a co-host.

**Comment by joshwinny** [comment]
Thank you Jonathan, I'm in.

**Comment by jonathanbossenger** [comment]
Thanks, @joshwinny.

Please also RSVP to the [meetup.com](https://www.meetup.com/learn-wordpress-online-workshops/events/291383615/) event, if you haven't already, so I can make you co-host there.

**Comment by jonathanbossenger** [comment]
Prep notes: 

- https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/
- https://developer.wordpress.org/rest-api/extending-the-rest-api/routes-and-endpoints/
- https://developer.wordpress.org/reference/functions/register_activation_hook/
- https://github.com/CastosHQ/Seriously-Simple-Podcasting/tree/master/php/classes/rest
- https://developer.wordpress.org/reference/functions/register_rest_route/

Learning outcomes
1. Build a plugin which registers a custom form submissions table.
2. Add some test data
3. Create a form-submissions route, with a GET endpoint
4. Create a form-submissions route, with a POST endpoint
5. Create a form-submission route, with a GET endpoint and a id path variable
6. Ensure data validation and sanitization is in place
7. Mention that this can be used for various examples.

Follow up notes: 

- Why did I not need to specify a permissions_callback when I registered my routes?

**Comment by joshwinny** [comment]
Hi @jonathanbossenger, halfway through there were 10 participants.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/02/10/lets-code-wp-rest-api-custom-routes-and-endpoints/
