### ISSUE TITLE
Online Workshop - Updating a blog's design (Informal live stream)

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1306]
# Event Details
- Title: Updating a blog's design (Informal live stream)
- Description: This is a multi-part informal live stream of me updating my personal blog's design from the Twenty Twenty-Two theme to the Twenty Twenty-Three theme while answering questions from viewers.
- Target Audience: Users
- Dates:
  - ~February 24th ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/291393998/)): **needs co-host**~
  - March 3rd ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/291394412/)): co-host @dev-sabbir 
  - March 24th ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/291927281/)): co-host @dev-sabbir 
  - April 7th ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/292148436/)): **needs co-host**
  - May 5th ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/292655435/)): **needs co-host**
  - May 26th ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/293339217/)): **needs co-host**
- Other info: As this is an informal live stream, there will be no slides.

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by dev-sabbir** [comment]
I am willing to co-host.

**Comment by kaitohm** [comment]
Part one's recording has now been uploaded to WordPress.tv: https://wordpress.tv/2023/03/02/updating-a-blogs-design-informal-live-stream-part-1/

**Comment by kaitohm** [comment]
@dev-sabbir Based on how the last session went, I've scheduled [a 3rd session in this series for April 7th](https://www.meetup.com/learn-wordpress-online-workshops/events/292148436/). Would you like to co-host that session, too? There is no pressure. I just wanted to give you the first chance to raise your hand for that, if you were interested 😊

**Comment by dev-sabbir** [comment]
> @dev-sabbir Based on how the last session went, I've scheduled [a 3rd session in this series for April 7th](https://www.meetup.com/learn-wordpress-online-workshops/events/292148436/). Would you like to co-host that session, too? There is no pressure. I just wanted to give you the first chance to raise your hand for that, if you were interested 😊

HI @bsanevans, even though I am really interested, I don't think I will be able to co-host for 7th April. Thanks for the opportunity though 👍

**Comment by kaitohm** [comment]
No problem, @dev-sabbir ! I'll open it up to other folks, then 👍

**Comment by kaitohm** [comment]
Part two's recording can be found here: https://wordpress.tv/2023/03/23/updating-a-blogs-design-informal-live-stream-part-2/

**Comment by kaitohm** [comment]
Part three's recording can be found here: https://wordpress.tv/2023/04/06/updating-a-blogs-design-informal-live-stream-part-3/

**Comment by kaitohm** [comment]
Part four's recording can be found here: https://wordpress.tv/2023/05/04/updating-a-blogs-design-informal-live-stream-part-4/

**Comment by kaitohm** [comment]
Part five's recording is here: https://wordpress.tv/2023/05/25/updating-a-blogs-design-informal-live-stream-part-5/

And this workshop is finally completed! 🎉
