### ISSUE TITLE
Tutorial - WP REST API - Custom Fields, Authentication

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1316]
# Topic Description
So far, you've learned how to access core WordPress data using the REST API and the Backbone.js client, as well as how to create, delete, and update Posts. In this session, we will look at how to create or update custom field values in your REST API endpoints, the built-in authentication options for authenticating WP REST API requests, and how to test REST API routes and endpoints using a third party too.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/wp-rest-api-03-custom-fields-authentication.md

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/217823619-e2dc1ecf-643c-4138-b2ac-895022713c97.mp4

The tutorial is ready for review.

Note to the reviewer, at the 0:28 mark I intend to replace that slide with a shot of the tutorial on Learn WordPress, [but it's still in review](https://github.com/WordPress/Learn/issues/1267). So as soon as it's published I'll update the video.

**Comment by courtneyr-dev** [comment]
This is great pacing. It really helps break down how to get started with Rest API in custom fields.

**Comment by jonathanbossenger** [comment]
Published https://learn.wordpress.org/tutorial/wp-rest-api-custom-fields-authentication-and-testing/
