### ISSUE TITLE
Online Workshop - How to create a video tutorial about WordPress (using free computer software)

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1319]
# Event Details
- Title: How to create a video tutorial about WordPress (using free computer software)
- Description: 
Are you interested in learning how to create video tutorials about WordPress?

Have you learned something helpful about WordPress from a tutorial on learn.wordpress.org?

Did you know that you can share your brilliance and create learning material for learn.wordpress.org?

If so, this online workshop is for you! Join us in a collaborative learning space to learn how you can create video tutorials about WordPress--using free or already-built-in technology.

The primary focus of this workshop will be on using free or open-source technology, as well as built-in programs that likely already exists on your computer. We will also touch on how to contribute tutorials specifically for learn.wordpress.org by joining the training team, but this workshop is open to anyone interested in learning how to make video tutorials about WordPress--for any reason you'd like!

We will explore...

The WordPress Training Team (Briefly)
Where learn.wordpress.org tutorial topic ideas come from
How and where to volunteer to create a tutorial with the WordPress training team
Tutorial Creation Planning:
Writing a strong script
How you can get feedback as you get started
The Recording Process: Using Zoom + Built-In Recording Technology!
Creating a cursor highlight effect on your computer
Setting Up a Local Environment
Finding free images you are allowed to use in your tutorials
Using Google Slides (using a template,
Audio setup, sound comparison, and some considerations
Editing your work using built-in computer programs and/or open-source technology
Getting your work reviewed and publishing steps for tutorials
- Target Audience: Contributors / Users
- Date: February 10th, 2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/291471911/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by kaitohm** [comment]
@wparasae Will you be completing any more from the Online Workshop checklist, or can we close this out?
