### ISSUE TITLE
Online Workshop - What is Learn WordPress?

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Learn#1320]
# Event Details
- Title: What is Learn WordPress?
- Description: WordPress.org’s Learn WordPress platform is a comprehensive resource for users looking to learn more about the WordPress content management system and its various features and functions. The platform offers a variety of resources which are designed to help people learn to use, extend, and contribute to WordPress through synchronous and asynchronous learning.
In this workshop, we will discuss:
    - An overview of the Learn WordPress platform
    - Content Types on Learn WordPress
    - Sharing Learn WordPress
    - How to Contribute to Learn WordPress
- Target Audience: Users
- Date: 15 February 2023 19:00 UTC and 16 February at 00:00 UTC
- Meetup.com event link: [Timezone 1](https://www.meetup.com/learn-wordpress-online-workshops/events/291520488/), [Timezone 2](https://www.meetup.com/learn-wordpress-online-workshops/events/291539304/)
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I can help out with the co-host if you still need someone. First time, so just let me know what to do next.

**Comment by courtney-pk** [comment]
Hi @SierraTR, thanks for offering! [Here is the information on co-hosting](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/). This includes filling out an [application form](https://learn.wordpress.org/online-workshops/#apply-to-facilitate), so I'm not sure if that process can be completed in time for tomorrow's event. But the team would be happy to have you on board as a co-host in the future!

**Comment by courtney-pk** [comment]
Links to [video recording](https://wordpress.tv/2023/02/15/what-is-learn-wordpress/) and [slides](https://drive.google.com/file/d/1Z9g4Vp5J7iqrY90D7ccwAdf5bV6TaIt9/view?usp=sharing)
