### ISSUE TITLE
The og:image tag image references the old content types

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1329]
## Description
When sharing the learn.wordpress.org site on social media (like Facebook) the social sharing image, which is fetched from the og:image meta tag, still references the old content types

https://s.w.org/images/learn-thumbnail-fallback.jpg

'Workshops' are now 'Tutorials'
'Discussion Groups' are now 'Online Workshops'

It would be great if we could get that image updated.

**Comment by jonathanbossenger** [comment]
Props to @DaisyOlsen who first reported this.

**Comment by jonathanbossenger** [comment]
@adamwoodnz would you be able to look into this in the coming week?

**Comment by adamwoodnz** [comment]
> @adamwoodnz would you be able to look into this in the coming week?

Yep!

**Comment by adamwoodnz** [comment]
Requested a new asset be created https://wordpress.slack.com/archives/C02S78ZAL/p1676317990048819

**Comment by jasmussen** [comment]
Hey @adamwoodnz sorry for the belated response here. 

I wonder if we should create this asset as part of the overall Learn refresh, rather than before? Otherwise, CC: @WordPress/meta-design for awareness.

**Comment by adamwoodnz** [comment]
Managed to update this myself and have redeployed https://wordpress.org/images/learn-thumbnail-fallback.jpg

The new CDN url is https://s.w.org/images/learn-thumbnail-fallback.jpg?v=3

See https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Flearn.wordpress.org

**Comment by adamwoodnz** [comment]
Commits
https://dotorg.trac.wordpress.org/changeset/20120
https://meta.trac.wordpress.org/changeset/12473

**Comment by courtneyr-dev** [comment]
Let's get courses on there yet too folks.

**Comment by adamwoodnz** [comment]
> Let's get courses on there yet too folks.

We don't have an icon for courses as far as I can see, and it seems like adding that might change the format of the image. I think it needs more design attention. Could it wait til the redesign as @jasmussen suggested?

**Comment by adamwoodnz** [comment]
Closing as Course and Lesson thumbnails are scraping as expected with the new theme

| Course | Lesson |
|--------|--------|
| ![Image](https://github.com/user-attachments/assets/4ae61b98-aac5-4d5a-af1f-574b5e26fb86) | ![Image](https://github.com/user-attachments/assets/33af5489-3836-45ef-878c-4516eb60c3ae) |
