### ISSUE TITLE
Learn WordPress Content Feedback - Taxonomies in WordPress Tutorial

### ISSUE THREAD

**Issue by SierraTR** [WordPress/Learn#1332]
# Feedback Details
- Content title:  Taxonomies in WordPress Tutorial
- Content URL:  https://learn.wordpress.org/tutorial/wordpress-taxonomies/
- Are you reporting an error (such as outdated information), or providing improvement ideas?:  Yes

Write a description of your feedback here:

1.  Suggest Title change to Using Categories and Tags in a Classic Theme
     Reason:  New WordPress users have no idea what a taxonomy is or what the term means. The word taxonomy does not appear anywhere in the WordPress dashboard but the terms Category and/or Tag do appear under both Posts and Settings/Writing

2.  When the tutorial moves from the initial 'talking head' section to the WordPress dashboard screencast portion (at 2:45) the tutorial volume drops at least 50%

3.  At about 10:55 the tutorial covers establishing sub and sub-sub categories successfully. At about 18:35 the tutorial moves to a demonstration of the Categories Widget displayed in the website footer. The options for the widget display are described and demonstrated but when the Show Hierarchy option is selected and the example is shown there is no display of the sub and sub-sub categories. A clear explanation is not given for their non-display which is confusing having previously watched the sub-categories being generated. Either dummy content should have been placed in posts using those sub-categories or a statement made that a category, parent or child, will not display until at least one post is published in the category.

4. No mention was made of the establishment of the 'default' category and its use, changing the name of the default category from the unhelpful 'uncategorized' to something else or how the default category is shown on the Post/Categories page. Opinion: It should be emphasized that, while WordPress needs a category for it's operation, the ultimate use of both categories and tags is for website visitors to more easily find content relevant to their needs. Perhaps relate Categories to Chapter Titles in a text book and sub-categories as sections of the Chapter and relate Tags to entries in the Index at the back of the book that provide a more granular search.

5. The tutorial uses the 2016 default theme and WordPress version 5.5.3. It obviously needs to either be updated or a new tutorial showing category and tag use in a FSE/block theme. The question is how long that classic theme tutorials will remain on learn.wordpress.org. Perhaps sections could be set up for classic theme tutorials and block theme/FSE tutorials so that new users don't have to sift through both types of content to find training.
---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by ironnysh** [comment]
There's a [new taxonomy-focused lesson](https://github.com/WordPress/Learn/issues/2541) in the Advanced User Learning Pathway that addresses many of the issues listed above.

**Comment by jonathanbossenger** [comment]
Added a notice to redirect the user to the new learning pathway lesson.
