### ISSUE TITLE
Tamil translation for Lesson Plan "Choosing And Installing Plugins"

### ISSUE THREAD

**Issue by karthick-murugan** [WordPress/Learn#1338]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/choosing-and-installing-plugins/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/407
- Language you'll be translating to: Tamil
- Have you arranged for someone to review this translation?: No ( Please assign someone to review )
- Reviewer's GitHub username: 
- Other info: https://docs.google.com/document/d/1mNHPXf-qFWoNIRdsifl7IDHgcJlUxuCoROBwv1JqiJo/edit

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by karthick-murugan** [comment]
@Piyopiyo-Kitsune - Completed this lesson plan. Please assign some one to review.

**Comment by kaitohm** [comment]
@ibndawood or @dhanendran , would either of you be available to review this translation?

**Comment by ibndawood** [comment]
@bsanevans - I'll look into this translation this week.

**Comment by dhanendran** [comment]
@ibndawood are reviewing this one? If not shall I take over?

**Comment by ibndawood** [comment]
@dhanendran - Sure. Thank you for the helping hand.

**Comment by kaitohm** [comment]
@dhanendran Just checking in... Were you able to review this translation? Thanks 🙂

**Comment by dhanendran** [comment]
@bsanevans @karthick-murugan I have reviewed the document and made a few adjustments. Now this looks good to me.

**Comment by kaitohm** [comment]
That's great, @dhanendran . Thanks!

@karthick-murugan I've created a draft post for the Tamil translation. Could you copy-paste your translation into the following, and remove the English?
https://learn.wordpress.org/wp-admin/post.php?post=36585&action=edit

Let me know once done, and I can publish this for you 🙂

**Comment by karthick-murugan** [comment]
@bsanevans - The translated content has been updated in the draft post link. Please have a look and publish it.

**Comment by kaitohm** [comment]
Wonderful! This has now been published: https://learn.wordpress.org/lesson-plan/ta-choosing-and-installing-plugins/

Thank you to everyone involved 🎉
