### ISSUE TITLE
ITALIAN translation for LESSON PLAN "PAGES VS. POSTS"

### ISSUE THREAD

**Issue by margheweb** [WordPress/Learn#1339]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/pages-versus-posts/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/432
- Language you'll be translating to: Italian
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @piermario
- Other info: https://docs.google.com/document/d/1DxXIHMB2iijewaXEjr6ViVrSos07D1wyst2PecS6Nq0/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by margheweb** [comment]
@bsanevans 
https://learn.wordpress.org/lesson-plan/pagine-vs-articoli/ 

Please check if all is well and let me know.

**Comment by kaitohm** [comment]
This looks good. Thanks so much for getting that published! 🎉
