### ISSUE TITLE
Tamil translation for Lesson Plan "Pages vs. Posts"

### ISSUE THREAD

**Issue by karthick-murugan** [WordPress/Learn#1342]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/pages-versus-posts/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/432
- Language you'll be translating to: Tamil
- Have you arranged for someone to review this translation?: No ( Please assign someone to review )
- Reviewer's GitHub username: 
- Other info: https://docs.google.com/document/d/1QeWB1HqrJ5AbQ3Bt6g3Y_eW40qhst0TCi1FF324pZ70/edit#heading=h.prnzy2sn1lgm

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by karthick-murugan** [comment]
@Piyopiyo-Kitsune - This lesson page is also completed. Please assign a reviewer.

**Comment by kaitohm** [comment]
@ibndawood or @dhanendran , would either of you be available to review this translation?

**Comment by ibndawood** [comment]
@bsanevans - I'll look into this translation this week.

**Comment by dhanendran** [comment]
@ibndawood are reviewing this one? If not shall I take over?

**Comment by ibndawood** [comment]
@dhanendran - Thank you. The review for this one is in progress. I hope to complete the review this week.

**Comment by ibndawood** [comment]
@karthick-murugan - I've completed my review and have added my suggestions. Please take a look.

**Comment by karthick-murugan** [comment]
@ibndawood  - All your suggestions has been updated.

@bsanevans - This lesson plan is ready to publish.

**Comment by kaitohm** [comment]
Great! @karthick-murugan could you copy-paste your translation into this lesson plan draft? You can delete the English that is there. https://learn.wordpress.org/wp-admin/post.php?post=33225&action=edit

Once done, please let me know. I'll make a final check and then publish.

**Comment by karthick-murugan** [comment]
@bsanevans - Copy pasted the translation content in the lesson plan draft. Please have a look. Thanks.

**Comment by kaitohm** [comment]
Yay, this is now published 🎉 Thank you to everyone who contributed!
https://learn.wordpress.org/lesson-plan/ta-pages-vs-posts/
