### ISSUE TITLE
Tamil translation for Hanbook Page "Tutorials"

### ISSUE THREAD

**Issue by karthick-murugan** [WordPress/Learn#1343]
# Details
- Link to original content: https://make.wordpress.org/training/handbook/tutorials/
- Link to original content GitHub issue: Not created yet
- Language you'll be translating to: Tamil
- Have you arranged for someone to review this translation?: No ( Please assign someone)
- Reviewer's GitHub username: 
- Other info: https://docs.google.com/document/d/1zreKu0fsmsm64i_yBI24y0MMX4FO3yMNdeer0Jo5mic/edit#

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by karthick-murugan** [comment]
@Piyopiyo-Kitsune - This Handbook Page is completed. Please assign a reviewer.

**Comment by kaitohm** [comment]
@ibndawood or @dhanendran , would either of you be available to review this translation?

**Comment by dhanendran** [comment]
@bsanevans I will review this one.

**Comment by dhanendran** [comment]
@bsanevans @karthick-murugan Added one suggestion otherwise it looks great.

**Comment by karthick-murugan** [comment]
Hi @dhanendran,

The suggestion has been updated in the document.

@bsanevans this handbook is ready to move forward.

**Comment by kaitohm** [comment]
Great! While we're waiting on a language switcher to be implemented on the Training Team's handbook, I've linked the Google Doc to the handbook page instead.

This is completed!
