### ISSUE TITLE
Tamil translation for Hanbook Page "Creating a Tutorial"

### ISSUE THREAD

**Issue by karthick-murugan** [WordPress/Learn#1344]
# Details
- Link to original content: https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial/
- Link to original content GitHub issue: Not yet created
- Language you'll be translating to: Tamil
- Have you arranged for someone to review this translation?: No ( Please assign a reviewer )
- Reviewer's GitHub username: 
- Other info: https://docs.google.com/document/d/1Eh7Bi77fgFElsbQSSnkPuiIjPKh2SEsAemZJxfpwGXA/edit#heading=h.wy1gu655m07b

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by karthick-murugan** [comment]
Hi @Piyopiyo-Kitsune - This Hanbook page is done. Please assign some reviewer

**Comment by kaitohm** [comment]
@ibndawood or @dhanendran , would either of you be available to review this translation?

**Comment by dhanendran** [comment]
@bsanevans I will review this one.

**Comment by dhanendran** [comment]
@bsanevans @karthick-murugan I have added a few suggestions in the doc.

**Comment by karthick-murugan** [comment]
Hi @dhanendran, 

Thank you for your great insights in this translation. All the suggestions are updated in the document. 

@bsanevans this handbook is ready to move forward.

**Comment by kaitohm** [comment]
Great! While we're waiting on a language switcher to be implemented on the Training Team's handbook, I've linked the Google Doc to the handbook page instead.

This is completed!
