### ISSUE TITLE
Tamil translation for Lesson Plan "Choosing And Installing Themes"

### ISSUE THREAD

**Issue by karthick-murugan** [WordPress/Learn#1345]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/choosing-and-installing-themes/
- Link to original content GitHub issue: Not yet created
- Language you'll be translating to: Tamil
- Have you arranged for someone to review this translation?: No ( Please assign a reviewer )
- Reviewer's GitHub username: 
- Other info: https://docs.google.com/document/d/1dmZiyvOVkcgKdogW6_MBzBfG6GQKCxvojc3anOQH7-o/edit#heading=h.prnzy2sn1lgm

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by karthick-murugan** [comment]
Hi @Piyopiyo-Kitsune - Completed this Lesson Plan page. Please assign a reviewer.

**Comment by kaitohm** [comment]
@ibndawood or @dhanendran , would either of you be available to review this translation?

**Comment by ibndawood** [comment]
@bsanevans - I'll look into this translation this week.

**Comment by karthick-murugan** [comment]
@ibndawood - I have updated all the translation suggestion that you have mentioned in the sheet. Please have a look and we are good to go. Thanks,

**Comment by ibndawood** [comment]
I've reviewed the translations and made suggestions, and they were implemented. My review for this translation is complete.

@karthick-murugan - உங்கள் மொழிபெயர்ப்புக்கு ரொம்ப நன்றி. மிகப்பெரிய பங்களிப்பு !!

**Comment by ibndawood** [comment]
> Please have a look and we are good to go.

Thank you for accepting my suggestions. The changes look good to me.

**Comment by karthick-murugan** [comment]
@ibndawood  - Thank you very much.

@bsanevans - This Lesson plan is ready to publish. Thanks.

**Comment by webtechpooja** [comment]
@karthick-murugan for drafting it and @ibndawood, thank you for reviewing it.
I have drafted it here: [https://learn.wordpress.org/?p=33075&post_type=lesson-plan&preview=1&_ppp=da12b6297a](https://learn.wordpress.org/?p=33075&post_type=lesson-plan&preview=1&_ppp=da12b6297a)
Please have a look and let me know if it looks good. So I can hit publish.

**Comment by karthick-murugan** [comment]
@webtechpooja - Yes it is good to go. Thanks for jumping in here.

**Comment by webtechpooja** [comment]
Published!

**Comment by kaitohm** [comment]
I've just updated the slug to match the other localized content we've been publishing: https://learn.wordpress.org/lesson-plan/ta-choosing-and-installing-themes/

Thanks everyone!
