### ISSUE TITLE
Tutorial - What kind of WordPress theme do I have? Classic, block, or something else?

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1349]
# Topic Description
For new users who are trying to understand Learn's content, they may need a little help figuring out what kind of theme they have. This tutorial is meant to serve as a resource/scaffold to point folks to when creating tutorials that encompass both block and classic themes. It has been recorded with 6.2 release visuals.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ] https://learn.wordpress.org/tutorial/choosing-and-installing-theme/

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [ ] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [ ] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [ ] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by wparasae** [comment]
Tutorial Draft can be found here: 
https://drive.google.com/file/d/1vLSjf4il5iWbO8gJtiJx9QSizj5Fl-Bs/view?usp=sharing

Targeted Questions for review:
1. Have I covered everything well and briefly enough for people to identify what kind of themes they have?
2. Is this entirely accurate?

Feel free to drop other feedback as well!

**Comment by nomad-skateboarding-dev** [comment]
This was great, Sarah!

I feel having this quick explanation of where you're beginning from, not assuming I know what street I'm on 😅, is needed.

Anecdotally, someone I know who runs their businesses with WordPress is always asking me for step zero. This is exactly that!

# Review Feedback
- Beta label will be removed in 6.2, so we on the training team need to keep this on the update track for next month.
- I'm not sure if the differentiation matters, but you could also have the Customize option showing under Appearance with certain plugins installed, like WooCommerce.
- Your thought to include learners using page builders was great! So many people are coming from that perspective, but content exactly like this is what's moving more and more of them towards the beauty of core. 🙂

**Comment by SierraTR** [comment]
I agree with the 6.2 comment - perhaps add a screen showing Appearance/Themes with 6.2+ installed (no red Beta tag)  and differentiate for those who will be slow to update to 6.2 but are using a block theme.

Personally I think we are getting too many different things labeled the same way -- too many 'Editor" labels and too many "Settings" labels. There should be some way to differentiate between them  (Site Editor/Template Editor ?) so the new user knows where the link is really taking them.

Great idea to put this together - too often we don't step back and look at things from the eyes of the brand new user.

**Comment by askdesign** [comment]
A very enjoyable tut, Sarah! Clear and concise, easy to follow. Some specific thoughts:

- Beta label - I agree with the previous reviewers about this. It might be OK to show the Editor link with the Beta label so long as you mention that the label will eventually be removed.
- "Customize" - this link shows up in 2 areas: Appearance > Customize and the button on top of the active theme. You call it a button in the sidebar, while I just think of that as a nav link. Maybe you'd want to mention that the active theme button leads the user to the same Customizer area.

1. Have I covered everything well and briefly enough for people to identify what kind of themes they have?
Yes, definitely.
2. Is this entirely accurate?
Yes, I think so!

**Comment by wparasae** [comment]
Oh, fascinating! I actually had the 6.2 release up and running for this one using the Beta tester plugin (or so I thought?)

I'll have to double-check that my settings were correct. On the bright side, I think removing that 'beta' button may be relatively easy (maybe, we'll see) with a simple color overlay and just cutting out the audio that says 'beta', but it's a good one to keep in mind.

Thank you all for your feedback, this is fantastic! Really excellent food for thought, and I will make these changes.

**Comment by webtechpooja** [comment]
This was great, @wparasae. One thing must be updated `Beta` from the screen and the audio. Rest is good to publish.
