### ISSUE TITLE
Online Workshop - How to Confidently Migrate from a Classic Theme to a Block Theme

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1350]
# Event Details
- Title: How to Confidently Migrate from a Classic Theme to a Block Theme
- Description: 
Do you have a WordPress website utilizing a classic WordPress theme that you'd like to migrate to a block theme?

Are you worried about potential down-time on your live website if you make a mistake when switching from theme to theme?

Would you like to learn how to move widget areas from your classic theme to a new block theme?

If this sounds exciting, please join Sarah Snow in a live workshop to learn how to safely and comfortably migrate from a classic theme to a block theme.

We will cover...

The importance of backups & setting up a local development environment

What to expect when switching from a classic to a block theme

The pros and cons of replicating an existing classic theme

Additional resources to help set you up for block theme design success

Ride along with Sarah Snow as she migrates a real, live blog from a classic theme to a block theme--complete with all the hiccups!

- Target Audience: Users
- Date: February 2, 2023
- Meetup.com event link:
- Co-host: Kathryn Presner
- Other info: 
Test drive of [this [draft] Lesson Plan](https://learn.wordpress.org/wp-admin/post.php?post=28450&action=edit)

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [ ] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by kaitohm** [comment]
I don't see this event on Meetup.com any longer. Are you still working on this, @wparasae ?

**Comment by annezazu** [comment]
Sharing this from recent YouTube video for some context/inspiration: https://www.youtube.com/watch?v=1jRJKl9Tf74

**Comment by annezazu** [comment]
Can someone share a link to where this is now live? :D

**Comment by kaitohm** [comment]
Sure! https://wordpress.tv/2023/02/23/how-to-confidently-migrate-from-a-classic-theme-to-a-block-theme/
