### ISSUE TITLE
Lesson Plan - content correction

### ISSUE THREAD

**Issue by dhanendran** [WordPress/Learn#1352]
# Feedback Details
- Content title: Difference between Reusable Blocks, Block Pattern, Templates, Template Parts
- Content URL: https://learn.wordpress.org/lesson-plan/difference-between-reusable-blocks-block-pattern-templates-template-parts/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: improvement

Write a description of your feedback here:

The "Notes for the Presenter" section talks about the presenter guiding the participants, so the working for the 3rd point should be like below;

Ask participants to either complete the exercise independently or guide ~~you~~ them through how to complete the exercise.
-------------------

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by webtechpooja** [comment]
Thanks, @dhanendran, for reporting this issue. I have fixed it.
