### ISSUE TITLE
Japanese translation for Lesson Plan "Pages Vs. Posts"

### ISSUE THREAD

**Issue by scaltinov** [WordPress/Learn#1355]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/pages-versus-posts/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/432
- Language you'll be translating to: Japanese
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: https://docs.google.com/document/d/1Sr5IXM1JHQn6r623hmH54uVCYlL0sjm9ah4eUDzzlXg/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
Ryo started on the translation, but is opening this up for anyone else to continue translating 😀

**Comment by kaitohm** [comment]
Closing, as this is low priority.
