### ISSUE TITLE
Khmer translation for Lesson Plan  "Dashboard Overview"

### ISSUE THREAD

**Issue by tepkenvannkorn** [WordPress/Learn#1357]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/dashboard-overview/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/423
- Language you'll be translating to: Khmer
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: https://docs.google.com/document/d/1zRRzq3bgjgVuDSYcJ1EuOuj_v1M5zNUMTBe-Hr62siU/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by tepkenvannkorn** [comment]
Hello,
I've just finished my translation. Please kindly take a look. 
https://docs.google.com/document/d/1zRRzq3bgjgVuDSYcJ1EuOuj_v1M5zNUMTBe-Hr62siU/edit?usp=sharing

**Comment by kaitohm** [comment]
@S-mardii Would you be able to review this translation?

**Comment by S-mardii** [comment]
Thank you for the follow up, I will support in reviewing this translation within this week.

**Comment by kaitohm** [comment]
@S-mardii I'm just following up to see if you were able to review this. Thanks 🙂

**Comment by S-mardii** [comment]
@bsanevans Sorry for a long delay in having this review ready.

I have reviewed and made minor adjustment on the Google Doc.

**Comment by kaitohm** [comment]
Thank you, @S-mardii !

@tepkenvannkorn I've sent you an email to add you to https://learn.wordpress.org/ as a Contributor. Once you've accepted, I can assign the following Lesson Plan to you, for you to copy-paste the translation there:

https://learn.wordpress.org/wp-admin/post.php?post=40249&action=edit

Once done, we'll be able to publish this. Let me know once you've accepted the email invite 😃

**Comment by tepkenvannkorn** [comment]
Dear Ben,

Thank you so much for the invitation. I'll check it out.

Regards,

Vannkorn

**Comment by tepkenvannkorn** [comment]
Dear Ben,

I've accepted the invitation.

Best regards,

*Vannkorn Tepken*
Full Stack Web Developer
Tel: +855 92 808 839
Email: ***@***.***
Website: https <http://vannkorn.info/>://vannkorn.com
<https://www.vannkorn.com/>

**Comment by kaitohm** [comment]
Great! You should now be able to open the following lesson plan and copy the content across. You can delete the English when you do:
https://learn.wordpress.org/wp-admin/post.php?post=40249&action=edit

Please comment here when that is complete. We can then make a final check and publish the content for you 🙂

**Comment by tepkenvannkorn** [comment]
Hi @bsanevans I have replaced the English content with the Khmer ones. Please note that I have fixed some typos and paraphrasing so that it's smooth to read. And I also have saved it as a draft. Any comments, please kindly let me know.

**Comment by kaitohm** [comment]
Yay! I've published this lesson plan here: https://learn.wordpress.org/lesson-plan/kh-dashboard-overview/

Thank you for your contributions, @tepkenvannkorn and @S-mardii  !!
