### ISSUE TITLE
Online Workshop - Help test WordPress - developer edition

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1358]
# Event Details
- Title: Help test WordPress - developer edition
- Description: WordPress 6.2 is scheduled to be released on March 28, 2023, with the first Release Candidate (RC) to be available to test on March 7, 2023. Testing an upcoming release is a great way to make sure your themes and plugins will work with the newest release, while also making sure you keep up to date with upcoming features. In this session, you'll learn how to use the WordPress Beta Tester plugin to test a new WordPress release, and where to find information to test the new features. We'll also cover how to log an issue in the WordPress release ticketing system, should you come across a bug.
- Target Audience: Developers
- Date: 2023-02-23 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/291680854
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by joshwinny** [comment]
Hi @jonathanbossenger, I'm willing to co-host.

**Comment by jonathanbossenger** [comment]
Awesome, thanks @joshwinny

**Comment by joshwinny** [comment]
Hi @jonathanbossenger, we started with 10 participants and midway we had 13.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/02/24/help-test-wordpress-developer-edition/
