### ISSUE TITLE
Learn WordPress Content Feedback -

### ISSUE THREAD

**Issue by hwcjd** [WordPress/Learn#1359]
# Feedback Details
- Content title: Creating Custom Fields
- Content URL: https://learn.wordpress.org/tutorial/creating-custom-fields/
- Are you reporting an error (such as outdated information), or providing improvement ideas?:
I'm reporting an error!
Write a description of your feedback here:
In the content the following link https://learn.wordpress.org/workshop/creating-custom-post-types/
redirects to a 'Page can't found error'.

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by webtechpooja** [comment]
The same issue was reported here: [https://github.com/WordPress/Learn/issues/1403](https://github.com/WordPress/Learn/issues/1403), and I resolved it, So we can close this issue. Thanks @hwcjd for reporting
