### ISSUE TITLE
Tutorial - WP REST API modifying responses

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1361]
# Topic Description
The WordPress REST API provides an interface for applications to interact with your WordPress site by sending and receiving data as JSON (JavaScript Object Notation) objects. By default, it provides REST endpoints (URLs) representing the posts, pages, taxonomies, and other built-in WordPress data types. Your application can send and receive JSON data to these endpoints to query, modify and create content on your site. However, it is also possible to extend the WP REST API, in order to perform specific actions that are outside of the scope of the default routes and endpoints. In this session, you will learn about one of the ways you can extend the WP REST API, by modifying REST responses.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/wp-rest-api-04-modifying-responses.md

**Comment by jonathanbossenger** [comment]
Tutorial ready for review

https://user-images.githubusercontent.com/180629/220912851-fc7621d7-53cb-41a8-b406-1ce406361f63.mp4

Note to reviewers:

- The final tutorial on Learn WordPress will include the full script, which includes all links to resources and code snippets.
- At the 2:02 minute mark, there is a placeholder for a screen that still needs to be added. That tutorial is not yet live, and so I can't add that screenshot. I will make sure to do so before the tutorial is published.

**Comment by nomad-skateboarding-dev** [comment]
As per usual, this is a non-developer review. However, you do such a good job on these tutorials, Jonathan, that I'll be changing my developer label soon! Great job! 🥇 

## Specific Feedback

- 3:58 Volume drops by half and is distorted.
- 4:41 - 4:51 it sounds like all sound dropped? But you could just be pausing as you're typing the example?
- 7:26 volume returns to original level and distortion gone.
- Overall this was easy to follow and paced perfectly for myself.
- I really felt it helpful when you used the colored border and arrow to highlight the code at 2:16
- The way you highlighted or retyped the specific code throughout was very helpful and easy for me to follow.

**Comment by courtneyr-dev** [comment]
Watching the video in GitHub's width leaves me wanting to zoom in more to see the sidebars and top nav buttons in Postman. If the video player is rather small, exaggerating zoom to stop before mobile breakpoints tends to be my preference. 

Same notices about the audio. It sounds like a background sound removal tool over-processed those areas. 

The content is fantastic though.

**Comment by jonathanbossenger** [comment]
Thanks for the feedback folks

>3:58 Volume drops by half and is distorted.
> 4:41 - 4:51 it sounds like all sound dropped? But you could just be pausing as you're typing the example?

Yeah I was experimenting with sound removal tools on this video, this one didn't seem to turn out great. I'll upload a better version shortly. 

> Watching the video in GitHub's width leaves me wanting to zoom in more to see the sidebars and top nav buttons in Postman. If the video player is rather small, exaggerating zoom to stop before mobile breakpoints tends to be my preference.

The difficulty, especially with an app like Postman, is the more you Zoom in, the less space you have to show the various panels of data. I'm currently at a +2 zoom (whatever that works out to on an electron app, I have no way to check) and if I go a level higher, it's difficult to see the full response on screen.

**Comment by jonathanbossenger** [comment]
Updated video with better audio

https://user-images.githubusercontent.com/180629/222927129-512ee415-97cd-44f9-9fd7-fd4acd2f038e.mp4

**Comment by nomad-skateboarding-dev** [comment]
This sounds fantastic @jonathanbossenger . Well done. 🙂

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/tutorial/wordpress-rest-api-modifying-responses/
