### ISSUE TITLE
Tutorial: BasicTooling for Wordpress

### ISSUE THREAD

**Issue by caraya** [WordPress/Learn#1364]
# Details

- Topic title: BasicTooling for WordPress
- Topic description: Regardless of the type of content you're creating, there are tools that you need beyond createscripts, createblocks and other WordPress-provided tools.  The idea behind this lesson plan / workshop is to cover some of these basic features such as image compression, script transpilation, CSS transpilation (from SASS and PostCSS)
- Objective:  Provide knowledge and a template for creating a tooling pipeline beyond what WordPress offers with the scripts and create block packages
- Content type:  Lesson plan initially, possibly a workshop later
- WordPress version:  N/A. Independent of the WordPress version you use
- Will you be creating this content?: Yes

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Triage Checklist
Please follow this [Vetting content topic ideas handbook page]() guide.

- [ ] SME assigned
- [ ] Remove Needs Subject Matter Expert label
- [ ] Content Category applied (Ex. PHP, Gutenberg, Block Theme)
- [ ] Topic idea has passed vetting checks
- [ ] Content type label applied
- [ ] Priority set
- [ ] Content Type Checklist applied
- [ ] Content type
- [ ] Audience set
- [ ] Experience Level set
- [ ] Product type (theme, plugin)
- [ ] WordPress Version applied through Milestone (Ex. milestone 5.9)
- [ ] If the Topic Idea reporter has not opted to create the content, apply Needs Content Creator label
- [ ] Ticket moved to Ready to Create

**Comment by courtneyr-dev** [comment]
Lesson plan issue: https://github.com/WordPress/Learn/issues/1390

**Comment by Piyopiyo-Kitsune** [comment]
@westnz Is this going to be part of a Learning Pathway lesson?

**Comment by westnz** [comment]
No, this is not part of the Learning Pathway Project.
