### ISSUE TITLE
There is a difference in the size of the video on the page.

### ISSUE THREAD

**Issue by aezazs-multidots** [WordPress/Learn#1369]
## Description
There is a difference in the size of the video on the page.

## Step-by-step reproduction instructions
When we open [this](https://learn.wordpress.org/contribute/) page, the size of the videos on this page is different.

## Expected behaviour
The sizes of the videos are different.

## Actual behaviour
Videos should be of the same size.

## Screenshots or screen recording (optional)
![CleanShot 2023-02-22 at 17 12 45@2x](https://user-images.githubusercontent.com/72435501/220610399-6fa41190-0443-4dc4-aa5d-9992dd778a14.png)

**Comment by shail-mehta** [comment]
Pull Request :   https://github.com/WordPress/Learn/pull/1765  (Both Issues Changes are included in this pull request)

After Applying Patch Video Size Issue will Resolved.

## Screenshot : 

![Contribute-video-issue](https://github.com/WordPress/Learn/assets/22027190/2ac5db9f-cee6-4d3f-8e70-a16308a26919)

**Comment by shail-mehta** [comment]
After Applying Patch Video Size Issue will Resolved.

## Screenshot : 

![Contribute-video-issue](https://github.com/WordPress/Learn/assets/22027190/2ac5db9f-cee6-4d3f-8e70-a16308a26919)

**Comment by adamwoodnz** [comment]
No longer an issue, with the launch of the 2024 block theme. The page layout has been updated.
