### ISSUE TITLE
Broken link in "Tutorial Presenter Application" - Learn site

### ISSUE THREAD

**Issue by lidialab** [WordPress/Learn#1370]
## Description

In the page https://learn.wordpress.org/tutorial-presenter-application/ 
in the phrase "We have instructions on creating a tutorial in our handbook here"
there is a broken link for "handbook here" text.

## Expected behaviour
I think it should point to https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial/

## Actual behaviour
It points to https://make.wordpress.org/training/handbook/workshops/creating-a-workshop/

## Screenshots or screen recording (optional)

![2023-02-22_14h08_31](https://user-images.githubusercontent.com/12560308/220628368-0c594524-12a7-452e-9707-585d55c9ba4e.png)

**Comment by jonathanbossenger** [comment]
Fixed, thanks for logging this @lidialab
