### ISSUE TITLE
Italian translation for Lesson Plan "Choosing And Installing Plugins"

### ISSUE THREAD

**Issue by margheweb** [WordPress/Learn#1371]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/choosing-and-installing-plugins/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/407
- Language you'll be translating to: ITALIAN
- Have you arranged for someone to review this translation?: Yes 
- Reviewer's GitHub username: @lidialab
- Other info: https://docs.google.com/document/d/191aMc6bOCWKoUCe2DRsCThBnH_PtrpBVMPar8QFD9sc/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by margheweb** [comment]
Published: https://learn.wordpress.org/lesson-plan/scegliere-e-installare-i-plugin/

**Comment by kaitohm** [comment]
Just noting the slug was updated: https://learn.wordpress.org/lesson-plan/it-choosing-and-installing-plugins/

Great job, everyone!
