### ISSUE TITLE
Italian translation for Handbook Page "Tutorials"

### ISSUE THREAD

**Issue by lidialab** [WordPress/Learn#1373]
# Details
- Link to original content: https://make.wordpress.org/training/handbook/tutorials/
- Link to original content GitHub issue: not available
- Language you'll be translating to: Italian
- Have you arranged for someone to review this translation?: @margheweb, @piermario
- Other info: when reviewed and approved, I will create the corresponding locale Handbook in the Italian Rosetta site (I have the permissions, like I do for the Polyglots team)

**Comment by lidialab** [comment]
@margheweb, @piermario, translation ready to be reviewed:
https://docs.google.com/document/d/1sYjIUqU0HfklNToAq0araHEvyY8PfyefohqhiHZUqx4/edit

**Comment by lidialab** [comment]
Hi @bsanevans Ben!

@piermario reviewed the Italian translation for the Handbook page "Tutorials".

Since we (translator and reviewer) are also GTEs and Locale Managers, we already published the page on the Italian Handbook at this URL:

https://it.wordpress.org/team/handbook/training/tutorial/

Thanks!

**Comment by kaitohm** [comment]
Yay! I've updated the Training Team handbook with a link to this page. I've also updated the project spreadsheet. Thank you for your contributions!
