### ISSUE TITLE
Online Workshop - Customizing the Single Template and 404 Template

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1374]
# Event Details
- Title: Customizing the Single Template and 404 Template
- Description: Customizing templates to meet design needs
- Target Audience: Beginners
- Date: 16 March, 9 am (New Zealand)
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/291792657/?isFirstPublish=true
- Co-host: @SierraTR 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I am available to co-host for you. Just let me know your preferences. 
It will be my first co-host operation, I'll do my best.

**Comment by westnz** [comment]
Hey @SierraTR! That is great.  Have you filled out this form and heard back from the Learn Team? https://learn.wordpress.org/online-workshops/#apply-to-facilitate

**Comment by westnz** [comment]
Recording: https://wordpress.tv/2023/03/16/customizing-the-single-template-and-404-template/
