### ISSUE TITLE
Italian translation for Lesson Plan " What to do when you forget your password"

### ISSUE THREAD

**Issue by piermario** [WordPress/Learn#1376]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/what-to-do-when-you-forget-your-password/
- Link to original content GitHub issue: n/a - couldn't find it
- Language you'll be translating to: Italian (translator: @matteospi)
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @lidialab, @piermario, @deadpool76, @margheweb
- Other info: This lesson plan already had a draft on Learn before the new translation process was put in place. We are opening a new issue in order to track this Lesson Plan and publish it as soon as we complete the final editing of the translated content.

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by piermario** [comment]
Translated draft on Google Docs: 
https://docs.google.com/document/d/1wMGME2Hkc9pR1lV8-dzkILZTSrpYffLdow17yvitwWw/edit#

**Comment by matteospi** [comment]
Hi! I am Matteo, the translator!

**Comment by piermario** [comment]
Hello @bsanevans!

We have reviewed and just published the Italian translation of the Lesson Plan, contributed by Matteo. 

Here's the Lesson Plan URL: https://learn.wordpress.org/lesson-plan/cosa-fare-quando-non-ti-ricordi-la-password/

I'm going to add the translation to the Google Sheet 2023 Published Learn Content

Let us know if there's anything we can improve in our process. We're getting up to speed as Italian Learn Team :) 

Thanks!

**Comment by kaitohm** [comment]
This is wonderful! Thanks so much! I've checked the steps you've followed, and all looks perfect!

**Comment by kaitohm** [comment]
Thank you for commenting on this issue, too, @matteospi ! Though now closed, I've assigned you to the issue so we can track your contributions to the Training Team 😃
