### ISSUE TITLE
Italian translation for Handbook Page  "Content Localization"

### ISSUE THREAD

**Issue by piermario** [WordPress/Learn#1378]
# Details
- Link to original content: https://make.wordpress.org/training/handbook/content-localization/
- Link to original content GitHub issue: n/a - couldn't find it
- Language you'll be translating to: Itlaian
- Have you arranged for someone to review this translation?: Yes 
- Reviewer's GitHub username: @lidialab, @deadpool76, @margheweb
- Other info: once reviewed and approved, we will create the corresponding locale Handbook in the Italian Rosetta site (we have writing permissions as Locale Managers)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by piermario** [comment]
Hello, @bsanevans! 

We reviewed and completed the Italian translation for the Handbook page "Content Localization".

Since we (translator and reviewer) are also GTEs and Locale Managers, we already published the page on the Italian Handbook at this URL:

https://it.wordpress.org/team/handbook/training/tradurre-contenuti-learn-in-italiano/

I hope we followed the procedure correctly. If anything can be improved, please let us know! Thanks! ☁️

**Comment by kaitohm** [comment]
Wonderful! I have updated [the project spreadsheet](https://docs.google.com/spreadsheets/d/102zlfZa1pVsTxYFZ09k3uBHf3c3qlPxwQvwffodCSJs/edit#gid=86878242), and also linked the Italian page from [the Training Team's handbook](https://make.wordpress.org/training/handbook/content-localization/).
