### ISSUE TITLE
The two links in the Lesson Wrap Up are not working.

### ISSUE THREAD

**Issue by aezazs-multidots** [WordPress/Learn#1379]
## Description
The two links in the Lesson Wrap Up section at the end of [this](https://learn.wordpress.org/lesson-plan/what-to-do-when-you-forget-your-password/#Exercises) page are not working.

## Screenshots or screen recording (optional)
![CleanShot 2023-02-23 at 20 15 04@2x](https://user-images.githubusercontent.com/72435501/220940067-d11615cf-fc8f-47fa-bf25-eff50fa9b9b0.png)

**Comment by webtechpooja** [comment]
Thank You, @aezazs-multidots, for reporting this issue. I have resolved this issue.
