### ISSUE TITLE
Italian translation for Handbook Page "Creating a Tutorial"

### ISSUE THREAD

**Issue by lidialab** [WordPress/Learn#1380]
# Details
- Link to original content: https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial/
- Link to original content GitHub issue: not found
- Language you'll be translating to: Italian
- Have you arranged for someone to review this translation: not yet, but I have pre-informed 2/3 persons
- Other info: work in progress here: https://docs.google.com/document/d/1J_sjXk1xrrSAzYHRul6kOedW9fRJJsNWsPfZTHkVypI/edit#

**Comment by lidialab** [comment]
@margheweb, @piermario, @deadpool76, translation ready to be reviewed:
https://docs.google.com/document/d/1J_sjXk1xrrSAzYHRul6kOedW9fRJJsNWsPfZTHkVypI/edit#

**Comment by lidialab** [comment]
Hi @bsanevans Ben!

@piermario reviewed the Italian translation for the Handbook page "Creating a Tutorial".

Since we (translator and reviewer) are also GTEs and Locale Managers, we already published the page on the Italian Handbook at this URL:

https://it.wordpress.org/team/handbook/training/tutorial/creare-un-tutorial/

Thanks!

**Comment by kaitohm** [comment]
Yay! I've updated the Training Team handbook with a link to this page. I've also updated the project spreadsheet. Great work!
