### ISSUE TITLE
Enqueueing Scripts And Styles - Lesson Plan

### ISSUE THREAD

**Issue by VipulUpadala** [WordPress/Learn#1383]
## Description

Page URL: https://learn.wordpress.org/lesson-plan/enqueueing-scripts-and-styles/

When we learn the above page on mobile devices then that is breaking. 

## Step-by-step reproduction instructions

Open the above page on mobile devices and see it is breaking

## Expected behaviour
do not show a horizontal scroll and the code tag need to be text wrapping.

## Actual behaviour
code tag does not wrap the text and for that reason, Horizontal scroll issues generate.

## Screenshots or screen recording (optional)
https://share.cleanshot.com/tbTCxMFVY5Hsj9X4TWDD

## Environment information
- Tested in chrome and safari

**Comment by adamwoodnz** [comment]
No longer an issue, with the launch of the 2024 block theme
