### ISSUE TITLE
Tutorial - WP REST API - custom routes and endpoints

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1385]
# Topic Description
The WordPress REST API is more than just a set of default routes. It is also a tool for creating custom routes and endpoints. In this tutorial, you’ll learn how to create custom routes and endpoints, and test them using Postman.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/wp-rest-api-05-custom-routes-endpoints.md

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/222927804-cb6bafb7-84f5-45f6-a5aa-9b1b86c11688.mp4
Video for review

**Comment by westnz** [comment]
Fantastic tutorial!  Easy to follow and clear explanations. You have used annotations effectively and talked learners through what you are doing.  I like how you shed light on the format of the path variable.

**Comment by nomad-skateboarding-dev** [comment]
# Overall Impression
Not hyperbole, you teach coding as well as anyone I've seen, Jonathan. Nicely done! I'm going to end up a developer without ever knowing I was on the path! Like Daniel in The Karate Kid! 😃 🏆 
## Specific Feedback
- I find your use of the bright blue box/border to highlight exactly what you're speaking about to be very helpful.
- This may not be appropriate or relevant to those with more developer knowledge, but as someone who is ignorant on most of this, I feel I  would benefit from seeing exactly what your stack or setup is, even if just to name it. Example: I'm on a MacBook Pro, I open Chrome, my local dev environment is, etc.

Edit: typo

**Comment by jonathanbossenger** [comment]
Thanks for the review @nomad-skateboarding-dev 

> This may not be appropriate or relevant to those with more developer knowledge, but as someone who is ignorant on most of this, I feel I would benefit from seeing exactly what your stack or setup is, even if just to name it. Example: I'm on a MacBook Pro, I open Chrome, my local dev environment is, etc.

Interesting. I would add that I don't use a conventional local development environment, so if I mention that, it might cause more confusion than not 😁

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/tutorial/wordpress-rest-api-custom-routes-endpoints/
