### ISSUE TITLE
Individual Learner Survey Bug report

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#1386]
## Description
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/5519705/221323355-f7a89137-f6fc-4bd2-ae3e-ab46b197a5db.png">
The Individual Learner Survey should be taken down from across LearnWP as the survey closed. It is shown in the photo on the home page and at the top of all other pages.

**Comment by jonathanbossenger** [comment]
I merged a PR to remove this on Friday, but it seems to not have been deployed yet. I'll follow up on Monday to find out what's needed there.

**Comment by jonathanbossenger** [comment]
This was fixed by #1381
