### ISSUE TITLE
Tamil translation for Lesson Plan "Intro to the Site Editor and Templates"

### ISSUE THREAD

**Issue by karthick-murugan** [WordPress/Learn#1387]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/intro-to-site-editor-and-templates/
- Link to original content GitHub issue: Not yet created.
- Language you'll be translating to: Tamil
- Have you arranged for someone to review this translation?: No ( Please assign a reviewer )
- Reviewer's GitHub username: 
- Other info: https://docs.google.com/document/d/1m7j_RN9JyIsHwLXpe2wTZyDMvWInknu4xSicHg1HC-w/edit#heading=h.tfq9aubq4ecj

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by karthick-murugan** [comment]
@Piyopiyo-Kitsune - This is ready for review now.

**Comment by kaitohm** [comment]
I've created a draft Lesson Plan here for us to transfer the translation into: https://learn.wordpress.org/wp-admin/post.php?post=32694&action=edit

**Comment by dhanendran** [comment]
@bsanevans I can review this one

**Comment by webtechpooja** [comment]
Thank you, @dhanendran for showing interest. I assigned this issue to you.

**Comment by kaitohm** [comment]
@karthick-murugan It seems access is restricted on the [Google Doc](https://docs.google.com/document/d/1m7j_RN9JyIsHwLXpe2wTZyDMvWInknu4xSicHg1HC-w/edit#heading=h.tfq9aubq4ecj) you shared. Could you transfer your translations into this draft post? https://learn.wordpress.org/wp-admin/post.php?post=32694&action=edit There will then be a public review link in the right sidebar you can share here in GitHub for @dhanendran to review.

**Comment by dhanendran** [comment]
@karthick-murugan @bsanevans  I have added few suggestions, otherwise it looks great 👍

**Comment by karthick-murugan** [comment]
@dhanendran - All your suggestions has been updated. 

@bsanevans - This lesson plan is ready to publish.

**Comment by kaitohm** [comment]
Great! @karthick-murugan could you copy-paste your translation into this lesson plan draft? You can delete the English that is there. https://learn.wordpress.org/wp-admin/post.php?post=32694&action=edit

Once done, please let me know. I'll make a final check and then publish.

**Comment by karthick-murugan** [comment]
@bsanevans - Copy pasted the translation content in the lesson plan draft. Please have a look. Thanks.

**Comment by kaitohm** [comment]
Yay, this is now published 🎉 Thank you to everyone who contributed!
https://learn.wordpress.org/lesson-plan/ta-intro-to-the-site-editor-and-templates/
