### ISSUE TITLE
Empty lesson plan categories don't display "No items found"

### ISSUE THREAD

**Issue by dd32** [WordPress/Learn#139]
When accessing empty lesson plan categories, multiple PHP Notices are generated and the "No posts found" message is not displayed.

This is because the code is effectively:
```
if ( ! have_posts() ) {
  echo esc_html( get_post_type_object( get_post_type() )->labels->not_found );
}
```
and in those cases, `get_post_type()` has nothing to return, since there's no posts.

I'm not sure if the empty lesson plan categories should be hidden, or if the lesson plan / workshop archives should be fixed instead.

Currently the Speaker & Template lesson plan categories are empty.
https://learn.wordpress.org/lesson-plans/speaker/
https://learn.wordpress.org/lesson-plans/templates/

**Comment by coreymckrill** [comment]
In the **component-lesson-filters.php** file, it looks like we're intentionally not hiding empty taxonomy terms, so fixing the errors on the archive views seems like the best plan.
