### ISSUE TITLE
Photo prie par le telescope Webb-

### ISSUE THREAD

**Issue by Alexonso** [WordPress/Learn#1394]
![Nebulleuse(2)](https://user-images.githubusercontent.com/110059755/222195496-2851a0cf-2c47-46fe-9ff0-0d7677f960f6.jpg)
Thank you for taking the time to report feedback about content hosted on https://learn.wordpress.org.
To start, please add a brief description of your feedback to the title above.
Then, fill out the details below under Feedback Details.

You can leave "Feedback Report Checklist" as-is.

Thank you for your feedback!

# Feedback DetailsVstruct Post {

  var message: String = ""

  var likes: Int = 0

  var numberOfComments: Int = 0

  

  mutating func like() {

    likes += 1

  }

}

var post = Post()

post.likes

post.like()

post.likes
- Content title:
- Content URL:
- Are you reporting an error (such as outdated information), or providing improvement ideas?:

Write a description of your feedback here:

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by jonathanbossenger** [comment]
Closing as spam
