### ISSUE TITLE
Become a full stack Developer with Wordpress.

### ISSUE THREAD

**Issue by MICALDSOUZA** [WordPress/Learn#1396]
# Details

- Topic title: 
- Topic description: 
- Objective: 
- Content type: 
- WordPress version: 
- Will you be creating this content?: Yes/No

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Triage Checklist
Please follow this [Vetting content topic ideas handbook page]() guide.

- [ ] SME assigned
- [ ] Remove Needs Subject Matter Expert label
- [ ] Content Category applied (Ex. PHP, Gutenberg, Block Theme)
- [ ] Topic idea has passed vetting checks
- [ ] Content type label applied
- [ ] Priority set
- [ ] Content Type Checklist applied
- [ ] Content type
- [ ] Audience set
- [ ] Experience Level set
- [ ] Product type (theme, plugin)
- [ ] WordPress Version applied through Milestone (Ex. milestone 5.9)
- [ ] If the Topic Idea reporter has not opted to create the content, apply Needs Content Creator label
- [ ] Ticket moved to Ready to Create

**Comment by jonathanbossenger** [comment]
Hi @MICALDSOUZA, are you suggesting this as a topic, or are you wanting to create this content?

**Comment by kaitohm** [comment]
Closing, due to not enough information. 

If you'd still like to see this content created, please create [a new Topic Idea issue](https://wordpress.slack.com/archives/C03B11FA16D/p1688486841217239?thread_ts=1687827128.413619&cid=C03B11FA16D) and fill out the information listed.
