### ISSUE TITLE
Workshop submission flow

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#14]
Since we're just getting started with all this, we're using [a Crowdsignal form](https://wordcampcentral.survey.fm/learn-wordpress-workshop-application) to accept submissions. Ultimately we would need this to be more integrated into the site, so here's a proposal for how that flow could work:

**Step 1:** Presenter submits their workshop details in a custom form. This saves their details as a new post in the `workshop` CPT, but in `draft` status (ref #3 for the post type discussion).

**Step 2:** Reviewers are given a user role that permits them to edit posts in the `workshop` CPT (`editor`? A custom user role?). They can log in to review the workshop and leave notes on it as needed.

**Step 3:** For a workshop that is approved, the reviewer would get any additional info from the presenter, and also inform them that they should go ahead and record the workshop.

**Step 4:** The recorded workshop, along with any other missing info, is added to the post and it is scheduled to be published.

As you can see, this would work in a similar way to how WordCamp sessions are submitted since they are saved in `draft` status until approved and complete. It would also need to have the notes feature that WordCamps and meetups have on central.wordcamp.org.

How does this sound? I don't expect this to be ready for the launch on 12 August, since we can continue with the Crowdsignal form in the meantime, but it would be good to have this done as soon as possible afterwards.

/cc @StevenDufresne @coreymckrill

**Comment by coreymckrill** [comment]
We might be able to adapt some of the [WordCamp Forms to Drafts](https://github.com/WordPress/wordcamp.org/tree/production/public_html/wp-content/plugins/wordcamp-forms-to-drafts) plugin code for this. And/or [WCPT](https://github.com/WordPress/wordcamp.org/tree/production/public_html/wp-content/plugins/wcpt).

**Comment by tellyworth** [comment]
I posted a quick PR that uses Hugh's Crowdsignal links for the time being. (I think I'm correct that the "submit a workshop idea" is intended to go there, right @hlashbrooke?)

**Comment by hlashbrooke** [comment]
Yeah - this looks good to me for now.

**Comment by CdrMarks** [comment]
This is more involved than I thought.  I'm unassigning this so that I don't delay progress if someone else has the time.

**Comment by hlashbrooke** [comment]
Duplicate of #23 

Closing in favour of #23
