### ISSUE TITLE
Learn WordPress Content Feedback - Using the create-block Tool

### ISSUE THREAD

**Issue by mikeritter** [WordPress/Learn#1400]
# Feedback Details
- Content title: Using the create-block Tool
- Content URL: https://learn.wordpress.org/tutorial/using-the-create-block-tool/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: Improvement

Write a description of your feedback here:

Requires link to next tutorial or should not reference said tutorial.

See last paragraph:

   And that wraps up this lesson on using Create Block. In the next lesson, you’ll use this scaffolded code, and apply it to an existing shortcode plugin.

---

# Feedback Report Checklist:
- [x] Feedback validated
- [x] Update proposed
- [x] Update reviewed
- [x] Update published

**Comment by webtechpooja** [comment]
Thank you, @mikeritter, for reporting this issue.

@jonathanbossenger, You are the original author of this tutorial. Could you please review this issue? At the end of the article, it is mentioned that: "**And that wraps up this lesson on using Create Block. In the next lesson, you’ll use this scaffolded code, and apply it to an existing shortcode plugin**."
It would be great if you could link the next lesson.

**Comment by jonathanbossenger** [comment]
Thanks for logging this folks, I've updated the tutorial to link to the next tutorial in this series.
