### ISSUE TITLE
Online Workshop - Let's Code: preventing CSRF security vulnerabilities

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1401]
# Event Details
- Title: Let's Code: preventing CSRF security vulnerabilities
- Description: This workshop picks up from [the last session](https://github.com/WordPress/Learn/issues/1384), where we cover how to use nonces to prevent cross-site request forgery vulnerabilities
- Target Audience: Developers
- Date: 2023-03-09 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/292032256
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I'll co-host for you if you still need someone. This will be my first co-host event so go easy on me.

**Comment by jonathanbossenger** [comment]
Thanks, @SierraTR. Does the time work for you, according to my timezone checker, 14:00 UTC is pretty early for Nevada.

**Comment by SierraTR** [comment]
Yes, that's fine - 6 am here in Reno, Nevada. It's your 4 am Twitch streams that hurt a bit.

**Comment by jonathanbossenger** [comment]
Hi, @SierraTR ok, that's good to know.

Given that it's now the day of the workshop, I'm not going to be able to send you the co-host notes, etc beforehand, and I'd have preferred to have been able to give you at least 24 hours time to prepare (my fault, sorry about that). 

So how about we try and work towards you co-hosting a future workshop? I can ping you in the comments when I post my next workshop here on GitHub, would that work for you?

**Comment by SierraTR** [comment]
Yeah, that's fine.  I'll just watch today. Maybe we can work some time in the future.

**Comment by jonathanbossenger** [comment]
Thanks, @SierraTR

**Comment by jonathanbossenger** [comment]
Note to self: 13 attendees today

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/03/10/lets-code-preventing-csrf-security-vulnerabilities/
