### ISSUE TITLE
Learn WordPress Content Feedback - Creating Custom Fields Tutorial

### ISSUE THREAD

**Issue by mikeritter** [WordPress/Learn#1403]
# Feedback Details
- Content title: Creating Custom Fields
- Content URL: https://learn.wordpress.org/tutorial/creating-custom-fields/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: Improvement

Write a description of your feedback here:

Current tutorial references different tutorial videos not available. Link to https://learn.wordpress.org/workshop/creating-custom-post-types/ returns 404. No link to displaying custom fields tutorial.

Tutorial *should* at least reference documented methods from WordPress including structure of Post Metadata and CPTs.

It is understandable the author referenced a plugin approach since this is regrettably complex in WP (i.e., CPTs, forms).

Block Editor upends traditional approaches.

This tutorial necessitates creation of tutorials for Creating CPT and Displaying Metadata / Custom Fields.
---

# Feedback Report Checklist:
- [x] Feedback validated
- [x] Update proposed
- [x] Update reviewed
- [x] Update published

**Comment by webtechpooja** [comment]
Thank you @mikeritter for reporting the issue. I have fixed this issue.
