### ISSUE TITLE
Course: Creating a 4 page business website with a block theme

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1407]
Many people would like to start a business website but don't know where to start.  This course will help learners to create their own site from start to finish with a block theme.

**Comment by westnz** [comment]
DRAFT OUTLINE:

Course layout and resources

Module 1: Planning (the 'thought work' behind a website)
Module 2: Designing (headers, footers, main pages, blog pages)
Module 3: Extending and Testing (adding plugins, user management, optional extras)

Module 1: Planning (the 'thought work' behind a website)
Lesson 1: Planning for Success (Sarah) (March 30)
Lesson 2: Planning Your Content

Module 2: Designing Your Website
Lesson 3: Selecting a theme and customizing it (Wes)
Lesson 4: Styling your Site Globally (Sarah) (April 14)
Lesson 5: Building your header and footer in the site editor  (Wes)
Lesson 6: Setting up main pages and adding content (Wes)

Module 3: Extending your Website
Lesson 7: (Optional) Include a Blog - Publishing posts for a blog or news page (April 21)
Lesson 8: Using plugins and extending the features of your website (Wes)

Conclusion
Links to extra resources on Learn

**Comment by westnz** [comment]
Update: work on this is underway.  The plan is to get this out for review by the end of April.
Sensei: https://learn.wordpress.org/?post_type=course&p=32582&preview=true

**Comment by wparasae** [comment]
This course's first draft is complete and is now ready for preliminary review! Go ahead and take a look at it here:

https://learn.wordpress.org/course/creating-a-4-page-business-website/

**Specific Feedback Requests:**
1. What works for you? Which parts are most effective?
2. What needs to be made clearer? Is there anything inaccurate, or needs work?
3. What changes might we make? Don't forget to include the specific lesson name so we can work efficiently. :) 

Please leave feedback as a comment on this Github issue. We will take comments into consideration as we work on our second draft!

Please note that we have tried to incorporate some new features that may or may not work entirely as expected--we're learning with you! Do let us know if you observe anything odd, and we will continue to iterate upon this in its second draft.

**Comment by gudrunfrank** [comment]
This course is a great idea, and I know people are looking for these kinds of step-by step tutorials. Here are some general observations. 

- When clicking "Take course Now" while you are not logged in to WordPress, you can only create a new login. There is no option of logging in to an existing account. 
- The line-braking hyphens make text harder to read. Can that be turned off?
- I know there is a lot of discussion going on about usability and outside links opening in a new tab. For me, outside links opening in a new tab help me keep track where I left off. Consider opening those links in a new tab while providing a visual clue about that technique.

**Comment by westnz** [comment]
**Review: Lesson 1 (Planning Content for Success)**

Looks great. 

Practical steps outlined. Love the link to the graphic organizer and keyword thought organizer. 

The quiz works!  

**Review: Lesson 2 (Planning your website's look and feel)**

Great advice provided.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/89751452/236367007-ef3c6ae0-2ca1-43e3-8071-33de97a6bb77.png">

Before this area or below. Can't we add a screencast of the theme styles that come with the 2023  theme as an example?  We can highlight that some themes already provide different styles they can select or use as inspiration for their own colour combination. Some people might feel overwhelmed by this process. It would be good for them to know they can check if their theme provides

Picking fonts - I would suggest shortening this section a bit.

**Lesson 4 (The Site Editor and the Page Editor)**
Needs to be updated/expanded.

**Lesson 5: Styling your site globally**

Stylebook clearly explained

**Lesson 8: (Website Self-evaluation)**
Needs to be updated or removed. I suggest only having a rubric and nothing else.

**Lesson 9: (Creating a blog or news page)**
Solid work! 

PS: 
- Remember to add alt text to all your images. I saw a few that were missing. 
- Ensure that links outside links open in a different tab

**Comment by jonathanbossenger** [comment]
> * I know there is a lot of discussion going on about usability and outside links opening in a new tab. For me, outside links opening in a new tab help me keep track where I left off. Consider opening those links in a new tab while providing a visual clue about that technique.

I just wanted to comment on this. I feel 100% the same way, but it's been pointed out to me that opening external links in a new tab is an accessibility issue, especially for folks with screen readers, and therefore not recommended as the default.

**Comment by wparasae** [comment]
We have a few non-descriptive links in here so far (for example, having "link" as the word instead of "the course about getting setup with WordPress" as the link, so I'm going to make some changes to those now for accessibility.

**Comment by wparasae** [comment]
Issues:

- Quiz isn't appearing in "Planning Content for Success" underneath "One way to begin determining your own messaging is to see what already exists in the world. So, let's get started!" However, the second quiz at the bottom does seem to be working, so we should look into that.

Selecting and Activating a Block Theme:
- Quiz issue: options marked correctly are being marked as "incorrect". See screenshot: https://d.pr/i/tDhy6g

Site Editor Vs. Page Editor:
- Image at the bottom has a title in one and a blanked out title in another. Good idea to correct it.

Building your Header / Footer in the Site Editor:
Quiz is awaiting grade rather than autograded: https://d.pr/i/FlZgRk

Include a Blog or News Page (Optional) Quiz
Quiz has the issue that the answers are incorrect.

Questions:
Planning Your Website's Look and Feel
- Should we add a question about font contrast checkers on "Planning Your Website's Look and Feel" or is that too much?
- Do we have enough images?

Overall
- Where else could / should we add quiz questions? They seem to be creating some problems.
