### ISSUE TITLE
Japanese Online Workshop - Tips when moving from the Classic to Block Editor

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1409]
# Event Details
- Title: クラシックエディターからブロックエディターに移行するノウハウ
- English Title: Tips when moving from the Classic Editor to the Block Editor
- Description: Megane-san will share tips he has learned running his site creation agency regarding making the switch from the Classic Editor to the Block Editor.
- Target Audience: User, Developers, Designers
- Date: April 1sr, 2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/292127519/
- Speaker: @megane9988
- Co-host: @bsanevans 
- Other info: This Online Workshop will be hosted as part of a virtual Sapporo WordPress Meetup event. After the OW concludes in an hour, the local Meetup event will continue for additional program content. ([クラシックエディターからブロックエディターに移行するノウハウ | Sapporo WordPress Meetup](https://www.meetup.com/sapporo-wordpress-meetup/events/292126425/))

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by megane9988** [comment]
Looking forward to it!
I will do my best.

**Comment by kaitohm** [comment]
Thanks for a great presentation today, @megane9988 !!

WordPress.tv recording: [クラシックエディターからブロックエディターに移行するノウハウ](https://wordpress.tv/2023/04/01/%e3%82%af%e3%83%a9%e3%82%b7%e3%83%83%e3%82%af%e3%82%a8%e3%83%87%e3%82%a3%e3%82%bf%e3%83%bc%e3%81%8b%e3%82%89%e3%83%96%e3%83%ad%e3%83%83%e3%82%af%e3%82%a8%e3%83%87%e3%82%a3%e3%82%bf%e3%83%bc%e3%81%ab/)
Slides: https://paper.dropbox.com/doc/SWPHLSgqnmweTOzSsxOxC
