### ISSUE TITLE
Online Workshop - Let's code: Developing WordPress User Roles and Capabilities

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1410]
# Event Details
- Title: Developing WordPress User Roles and Capabilities
- Description: A primer on how to develop with the built-in WordPress Roles and Capabilities system to manage user access across a WordPress site. Session 1 will contain: How to create and apply user roles, How to add/remove capabilities from a user role, How to check user capabilities
- Target Audience: Developers 
- Date: 2023-03-16 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/292167530/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
@SierraTR checking in to see if you're free to co-host my next workshop.

If so, please read the [Co-hosting an online workshop handbook doc,](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) and complete the application at the bottom of that page.

Thanks

**Comment by SierraTR** [comment]
Thanks for the invite. I have gone through the co-hosting doc a couple of times and my application was approved for co-hosting last month. Having said that I am going to have to decline. I'm not available on Tuesday this week.
After watching you last week, I'd probably just slow you down anyway.
Thanks again.

By the way - if the Date entry in Event Details above is to refer to the scheduled event date, it says March 16 at 14:00 UTC which doesn't match the Meetup event information which says March 14th at noon UTC. For a new guy like me that is just one more layer of confusion.

**Comment by jonathanbossenger** [comment]
> it says March 16 at 14:00 UTC which doesn't match the Meetup event information which says March 14th at noon UTC

Thanks for picking this up, I'd added the link to the live stream and not the workshop to this GH ticket. So the correct date of the workshop is Thursday, March 16, at 14:00 UTC.

> After watching you last week, I'd probably just slow you down anyway. 

As mentioned above, I included the wrong link, so if you're free on Thursday, I'd be delighted if you're available to co-host.

**Comment by jonathanbossenger** [comment]
Note to self, adding the live stream link here so I can track it against the workshop planning https://www.meetup.com/learn-wordpress-online-workshops/events/292167395/

**Comment by SierraTR** [comment]
OK, if I did the math right in my time zone that would be Thursday at 7 am.  Yes, I'm available then for co-hosting.

I have registered to attend in Meetup.

**Comment by jonathanbossenger** [comment]
Excellent, it seems DST is giving you an extra hour to wake up for the workshop time now.

I've added you as a co-host, and I'll send over some details via Slack in the coming days.

**Comment by SierraTR** [comment]
OK, thanks. I'll be looking for it.

**Comment by SierraTR** [comment]
Really good session!  There were 13 attendees - the really great part is that once they signed in, nobody left until you ended the session. That's a reflection on your presentation abilities and, I believe, the level of the presentation.
I really enjoyed the session. I hope I will be able to work with you in the future. I always learn something.

**Comment by jonathanbossenger** [comment]
Thanks so much for the kind words @SierraTR. If one attendee learns something then my job is done.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/03/17/lets-code-developing-wordpress-user-roles-and-capabilities/
