### ISSUE TITLE
Learn WordPress Content Feedback - theme working without theme.json?

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1411]
# Feedback Details
- Content title: Introduction to block theme development (for beginners)
- Content URL: https://learn.wordpress.org/tutorial/introduction-to-block-theme-development-for-beginners/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: possible error

Write a description of your feedback here:

When making a new Block theme, a `theme.json` file is required or the Site Editor will WSOD with no further details. The video shows the Block theme working without having created the `theme.json` file, but this does not work on a fresh WordPress 6.1.1 install for me.

_Reported in ticket 154262._

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by devmuhib009** [comment]
@bsanevans I just tested with latest 6.4.3 version and it's working fine. Without theme.json file, theme is being active. I only created index.php and style.csss. Multiple time I activated and tested by enabling WP_DEBUG, true.

**Comment by kaitohm** [comment]
Thanks for testing, @devmuhib009 . Let's close this issue out then.
