### ISSUE TITLE
Learn WordPress Content Feedback - Adding an option to a question

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1412]
# Feedback Details
- Content title: WordCamp Organizer Training - Food and Beverage
- Content URL: https://learn.wordpress.org/lesson/food-and-beverage-2/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: improvement idea

Write a description of your feedback here:

One of the questions:
"Can you ask participants to take care of their own lunch?"

And one of the answer options:
"Yes, but only if you organize a potluck lunch instead."

_This feedback was provided on ticket 153832._

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by ironnysh** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? No: 

The new option has been added to the [quiz](https://learn.wordpress.org/quiz/food-and-beverage-2-3/):
![Image](https://github.com/WordPress/Learn/assets/63248335/4d94e72a-19d3-4cad-b288-ad87027d9e3f)

**Comment by kaitohm** [comment]
Thanks for taking a look, @ironnysh 🙌
