### ISSUE TITLE
Learn WordPress Content Feedback - Not clear that a block theme is needed

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1413]
# Feedback Details
- Content title: Building Sidebars With the Site Editor
- Content URL: https://learn.wordpress.org/tutorial/building-sidebars-with-the-site-editor/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: Improvement idea.

Write a description of your feedback here:

> I'm new to wp.
All is baffling.
I'm taking a course to learn how to build a sidebar.
The video says, "Open the Editor. It's located under "Appearance".
I click on "Appearance".
There is NO "Editor" listed.
For me, this is the end of the course.
I can go no further.

Please see if the need for a block theme could be highlighted or better iterated in this resource.

_This feedback was provided in ticket 153768._

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by devmuhib009** [comment]
Block theme is a requirement, I can see it at the starting of the video and text content. So, this is not valid.

**Comment by devmuhib009** [comment]
As this issue is not valid, I'm going to close this.
