### ISSUE TITLE
Learn WordPress Content Feedback - broken link in course

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1414]
# Feedback Details
- Content title: Setting up your development environment
- Content URL: https://learn.wordpress.org/lesson/setting-up-your-development-environment/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: error

Write a description of your feedback here:

>In section Setting up the build pipeline of the first lesson (Setting up your development environment) it states:
>
> This tutorial will proceed to assume the reader is familiar with ESNext syntax and the concept of build tools (like webpack). If that sounds confusing, you may want to review the Getting started with JavaScript Build Setup first.
>
> "Getting started with JavaScript Build Setup" is a link, pointing to `url: https://learn.wordpress.org/docs/how-to-guides/javascript/js-build-setup.md` which leads to a Page Not Found. Even if I remove the `md` suffix, the link does not work.

_This error was reported in ticket 152935._

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by SierraTR** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): No
- What should happen next to apply the feedback?: 
- The link has been updated to lead to the correct page: https://developer.wordpress.org/block-editor/how-to-guides/javascript/js-build-setup/
