### ISSUE TITLE
Italian translation for Handbook Page "Copy Edit a Lesson Plan"

### ISSUE THREAD

**Issue by piermario** [WordPress/Learn#1415]
# Details
- Link to original content: https://make.wordpress.org/training/handbook/lesson-plans/copy-edit-a-lesson-plan/
- Link to original content GitHub issue: n/a
- Language you'll be translating to: Italian
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @lidialab
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by piermario** [comment]
Here's the translation draft on Google Docs: 
https://docs.google.com/document/d/1zPcnZqICxT1eMx3wJ98RdprJzECX0W8fRKFVBYX75Ic/edit?usp=sharing

**Comment by piermario** [comment]
Hello, @bsanevans!

We reviewed and completed the Italian translation for the Handbook page "Copy Edit a Lesson Plan".

Since we (translator and reviewer) are also GTEs and Locale Managers, we already published the page on the Italian Handbook at this URL:

https://it.wordpress.org/team/handbook/training/fare-editing-di-un-piano-delle-lezioni/

Thanks! 🌟

**Comment by kaitohm** [comment]
I've updated the Training Team Handbook to link to the Italian page: https://make.wordpress.org/training/handbook/lesson-plans/copy-edit-a-lesson-plan/

Great work!
