### ISSUE TITLE
Italian translation for Handbook Page "Lesson Plans"

### ISSUE THREAD

**Issue by piermario** [WordPress/Learn#1416]
# Details
- Link to original content: https://make.wordpress.org/training/handbook/lesson-plans/
- Link to original content GitHub issue: n/a
- Language you'll be translating to: Italian
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @lidialab
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by piermario** [comment]
Link to the Italian translation draft on Google Docs: 
https://docs.google.com/document/d/19LBSc7fZiJxN5tj1DPE7PQ-jR0VFHTHDakt8NP1-Jdo/edit?usp=sharing

**Comment by piermario** [comment]
Hello, @bsanevans!

We reviewed and completed the Italian translation for the Handbook page "Lesson Plans".

Since we (translator and reviewer) are also GTEs and Locale Managers, we already published the page on the Italian Handbook at this URL:

https://it.wordpress.org/team/handbook/training/piani-delle-lezioni/

Thanks! 🌟

**Comment by kaitohm** [comment]
I have linked the translated page back to the Training Team Handbook.
https://make.wordpress.org/training/handbook/lesson-plans/

Great work!
