### ISSUE TITLE
Tutorial - Add media and Openverse images to your content directly from the Inserter

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1418]
# Topic Description
With WordPress 6.2, you will be able to both add media directly from your library from the Inserter and search/select images from Openverse for openly-licensed media. 

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/225780586-4f27cd35-a467-46cd-9895-f45443d83590.mp4

**Comment by vagelisp** [comment]
Looking good to me. Well done @westnz !

**Comment by westnz** [comment]
Thanks @vagelisp

**Comment by nomad-skateboarding-dev** [comment]
# Overall Impression
Great job on this, Wes! I thought the presentation, delivery, and length were spot on. Easy to understand, and enjoyable to listen to. 🙂 
## Specific Feedback
- At 2:29, you say, "set the overlay to 30 pixels". I'm not sure what the correct term is here? Opacity, transparency, overlay percentage, or something else?

#### This is a general thought for all Learn content: Do we want to explore best practices,  the block's settings, or both in tutorials? 
-  Example: Text on image overlay is the biggest contributor to accessibility issues along with missing link tags. Note in example to especially check the contrast if it's text on image?
-  Example: We could show both how the Border Radius can be set on all four sides, while at the same time pointing out that making a cool border by using different radius' not only looks great, but decreases page load time and environmental impacts.

**Comment by westnz** [comment]
Hi @nomad-skateboarding-dev 
Thank you for the helpful feedback.  I used the term 'Overlay Opacity' as that is what it is called in the sidebar settings. Opacity by itself could also work.

Your thought about best practices is something I will definitely take on board, depending on the context.  This is something we can chat about more.  

The second example you mentioned is something I didn't know.

**Comment by nomad-skateboarding-dev** [comment]
> Thank you for the helpful feedback.  I used the term 'Overlay Opacity' as that is what it is called in the sidebar settings. Opacity by itself could also work.
> 

I apologies my feedback wasn't clearer, Wes!

I was referring specifically to the word "pixels". 🙂🙌


Should I edit my feedback above, Wes?

**Comment by westnz** [comment]
Ah!  Got it 😆 Thank you

**Comment by westnz** [comment]
Yes, should be 'percentage'

**Comment by nomad-skateboarding-dev** [comment]
> Yes, should be 'percentage' 

Thank you for the update, now I know as well. 🙂🙌

**Comment by wparasae** [comment]
Review:
_Suggestion:_ Add a transition between :10 and :11
_Suggestion:_ The images shown between :11 and :23 all show a particular demographic--is there another example you could use here from the start that might be more inclusive to people of differing cultures, genders, abilities, or racial backgrounds? The rest of your images are thoughtfully chosen, but this would make our content stronger and more inclusive from the very beginning. :) 

Overall, this looks fabulous, Wes! Another stellar tutorial. Thank you for all your great work!

**Comment by westnz** [comment]
Thank you for the feedback and suggestions @wparasae

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/add-media-and-openverse-images-to-your-content-directly-from-the-inserter/

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/issues/51132 Lightbox added in WP 6.4

**Comment by westnz** [comment]
Lightbox is not relevant to this tutorial 👍
