### ISSUE TITLE
Lesson - Designing with Row and Stack Blocks

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1419]
# Topic Description
The Row block and the Stack block are a design block type that allows you to insert multiple blocks in a row (or column with the Stack block) and space them out evenly. You can use the Row or Stack block to create separators or add various elements on the same line as if included in columns.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/f2fc0257-49ea-438e-a6af-655dd9c04c8d

**Comment by quitevisible** [comment]
Good one @westnz . I liked the section where you show how the row/stack blocks work within columns. I thought it was a great way to demonstrate how they are different, but also how they can be used together. I felt the animated transition slides kept the mood light. Nicely done 👍

**Comment by westnz** [comment]
Thank you so much, @quitevisible. I appreciate your feedback.

**Comment by ghost** [comment]
@westnz Great job on the tutorial. It has a lot of useful information. I struggled with my pricing columns lining up right and this would have helped. The speed was good.

**Comment by westnz** [comment]
Thank you! @lada7042

**Comment by kaitohm** [comment]
@westnz As we've had two reviews, feel free to publish this tutorial 👍

**Comment by westnz** [comment]
I plan to publish this at the start of July.  Thank you, Ben.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/designing-with-row-and-stack-blocks/

**Comment by courtneyr-dev** [comment]
Update to include Grid block as well.  Differentiate between all 3.  6.3 
https://github.com/WordPress/gutenberg/pull/49018

**Comment by westnz** [comment]
I think the Grid block should rather form part of the Query Loop block tutorial?

**Comment by westnz** [comment]
Updated for the Intermediate user learning pathway.

**Comment by westnz** [comment]
//publish
