### ISSUE TITLE
Add field to workshops for quiz URL

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#142]
Thanks to the updates in #141, we now have usable quizzes on the site :D 

I have manually linked some workshops to their quizzes by adding it into the post content ([example](https://learn.wordpress.org/workshop/intro-to-publishing-with-the-block-editor/)), but it would be great if this could either be a meta field or a custom block that comes as a part of the template. Te only data that will need t be given will be the URL for the quiz, and then it can show a button the frontend to take the quiz. I quite like the block with the button showing up above the content like it is in that example, but it might make more sense for it to be in the sidebar above the 'join a discussion group' button so long as it doesn't get lost in the visuals and can be prominent enough for people to see it.

**Comment by coreymckrill** [comment]
@hlashbrooke with #150 this field has been added, and you can now start linking quizzes to workshops.

**Comment by hlashbrooke** [comment]
Excellent - thanks!
