### ISSUE TITLE
Tutorial - Capabilities by Custom Post Type

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1420]
# Topic Description
In the previous tutorial, Developing WordPress User Roles and Capabilities, you learned how to create and apply user roles, how to add/remove capabilities from a user role, and how to check user capabilities. In this tutorial, you will learn about the built-in support for capabilities when you register a custom post type, and how you can refine these capabilities to suit your specific requirements.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [Roles and Capabilities](https://developer.wordpress.org/plugins/users/roles-and-capabilities/) developer doc
- [Capabilities](https://developer.wordpress.org/reference/functions/register_post_type/#capabilities) section of register_post_type

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
## Notes

When registering a custom post type, and leaving the capability_type, capabilities, and map_meta_cap parameters in the custom post type arguments array as default, the following happens:
- capability_type = post - this means this CPT has the same capability_type as a Post
- capabilities == whatever was set on the post (see above)
- map_meta_cap => true (1) - determines how capabilities are created for this CPT
 - registers meta capabilities of edit_post, read_post, and delete_post
 - registers initial primitive capabilities of edit_posts, edit_others_posts, publish_posts, and read_private_posts
 - registers additional primitive capabilities of read, delete_posts, delete_private_posts, delete_private_posts, delete_others_posts, edit_private_posts, edit_published_posts, create_posts

**Comment by kaitohm** [comment]
Are you going to work on this @jonathanbossenger ? Or is this a topic idea for others to take up?

**Comment by jonathanbossenger** [comment]
Thanks @bsanevans, I created the ticket but forgot to assign and label it. I've updated those now.

**Comment by jonathanbossenger** [comment]
Oh, no, wait, what I did was create this, forget about it, and then created #1436. So closing as a duplicate.

**Comment by jonathanbossenger** [comment]
Leaving this open because it has my original notes. Closing #1436 as a duplicate.

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/wordpress-roles-capabilities-02-custom-post-types.md

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/229571120-9b9475a5-ed94-412e-8e2d-71bf8d063795.mp4

Video for review

**Comment by wparasae** [comment]
I cannot review this for coding accuracy, but I'll do my best for general video content!

I really appreciate the speed at which you speak. It should allow developers who speak English as a second language to clearly follow this tutorial. The example you provide at the end of this tutorial is stellar! I love being able to see what you've done in the dashboard. Excellent callback to the documentation as well! Your transitions were smooth and slow, which is also a bonus.

Option for change:
Around 3:42: Consider adding annotations -- also 3:48, 3:49, 3:51, 4:12, 4:23, 6:15-- it's pretty clear, but it might allow someone on mobile to focus in a bit more on what you're saying :)

Looks great, though! Well done!

**Comment by jonathanbossenger** [comment]
Thanks for the review @wparasae I've added annotations in the places you've suggested.

https://user-images.githubusercontent.com/180629/234266192-2d261a7d-f9d7-4b70-95c5-0f14b7c96a69.mp4

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/tutorial/custom-post-types-and-capabilities/
