### ISSUE TITLE
Online Workshop - Let's code: custom content & custom capabilities

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1424]
# Event Details
- Title: Let's code: custom content & custom capabilities
- Description:  The WordPress User Roles and Capabilities system provides a robust way to control user access to sensitive data on your WordPress site. It's not only possible to create custom roles and assign capabilities to those roles, but it's also possible to assign content type capabilities to your custom post types. This adds another layer of control over your site content, especially if you require different levels of access. In this session, we'll be taking a look at the specific functionality that exists in the register_post_type function that pertains to post type capabilities, learn how this works, and how to best make use of it.
- Target Audience: Developers
- Date: 2023-03-23 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/292300126/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
Note to self: livestream link -> https://www.meetup.com/learn-wordpress-online-workshops/events/292300064/

**Comment by SierraTR** [comment]
If you want to try it again, I'm available to co-host.

**Comment by jonathanbossenger** [comment]
Perfect, thanks @SierraTR

**Comment by jonathanbossenger** [comment]
## Notes:

- https://developer.wordpress.org/reference/functions/register_post_type/#capability_type
- https://developer.wordpress.org/reference/functions/register_post_type/#capabilities
- https://developer.wordpress.org/reference/functions/register_post_type/#map_meta_cap

1. Setting the capability_type to book
    - map_meta_cap is set to false
    - therefore only 3 primitive and 4 meta capabilities are set
2. Because the new capabilities are not set for the admin role, the admin user, can no longer access books
    - we need to manually add the new capabilities to the administrator role
3. Adding a new user role for a writer, and allowing access to read, edit_books, delete_books
   - allows the writer user to see the books, but not edit them in the block editor
4. Adding map_meta_cap to true on the custom post type, and setting the user capabilities to 'read', 'edit_books', 'delete_books', 'publish_books', 'edit_published_books', 'delete_published_books'
5. Define the above capabilities using the capabilities array

**Comment by SierraTR** [comment]
Excellent session - as always. I don't think it could have been clearer without studying before the session.
Until Mark-Andrew had to leave there were 15 attendees.

That one attendee must have been sending private chat messages - I never saw any of her questions. And I believe you answered directly to her in the chat once or twice by replying so those weren't visible either. Might be another thing to cover in the intro to the sessions - not to use private chat so that the rest of  the group can benefit from the question and answer.

Good explanation of the map_met_cap not actually assigning anything, just making it available to assign. I hadn't caught that in the Twitch session yesterday.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/03/24/lets-code-custom-content-custom-capabilities/
