### ISSUE TITLE
Build a blog with WordPress 6.2 (Released today!)

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1425]
# Event Details
- Title: Build a blog with WordPress 6.2 (Released today!)
- Description: 
Have you ever wanted to build a blog with WordPress, but weren't sure where to start?

Do you want to get familiar with new block themes' site editing features?

Or, are you already familiar with WordPress and want to see what's changing with the 6.2 release?

If so, this online workshop is for you!

Join Host Sarah Snow as she explores how to build a blog with some of the newest features coming to WordPress on March 28th (TODAY!)

We will briefly touch on...

The fundamentals of building a blog with an eye toward new features coming to WordPress
How to access these new features before the March 28th release
As we build a blog of our very own, we will explore the following features:

Utilizing the WordPress Stylebook
New ways of adding beautifully designed patterns
Adding open source images directly from the site editor
Sticky headers and footers
"Pushing" color options and styles such as text formatting from a block to your global website
And post display options
Want to build with us?
If you'd like to follow along with us and experiment with building a blog alongside the demo, please make sure to set up a playground ahead of time.

Suggestion: Use a free local environment such as [XAMPP](https://www.apachefriends.org/), [MAMP](https://www.mamp.info/en/windows/), or [Local](https://localwp.com/). We will be using Local by Flywheel for the demo.

Not sure where to start? To learn how to set up a free, local WordPress installation on your computer in five minutes or less, check out our "[Local WordPress Installations (For Beginners)](https://learn.wordpress.org/tutorial/local-wordpress-installations-for-beginners/)" tutorial.

Who? Beginners to Block Themes
When? Tuesday, March 28th at 2pm Pacific / 5pm Eastern
Where? Zoom link available after RSVP
Language? English - Closed Captions provided by Zoom

We look forward to seeing you there!
- Target Audience: Beginning Users
- Date: March 28, 2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/292308299
- Co-host: TBD
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
If you still need someone to co-host, I am available. If you want a reference, so far I have worked with Ben and Jonathan.
