### ISSUE TITLE
Italian translation for tutorial "Choosing and Installing a Theme"

### ISSUE THREAD

**Issue by lidialab** [WordPress/Learn#1428]
- Link to original content: https://learn.wordpress.org/tutorial/choosing-and-installing-theme/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/758
- Language you'll be translating to: Italian
- Have you arranged for someone to review this translation?: I will ping one or some of our "Learn IT" members team.

**Comment by kaitohm** [comment]
Hi @lidialab 👋  How is the progress for this translation?

**Comment by lidialab** [comment]
Hi @bsanevans! I will proceed next week, I had unexpected things to do in the last days :)

**Comment by kaitohm** [comment]
No problem. And thanks!

**Comment by lidialab** [comment]
- Reviewers' GitHub usernames: @margheweb, @piermario
- Translation to review: https://docs.google.com/document/d/1spJoXYhonW0tPfjagfnLMx0QeBAGEy9W3WyOxudywQo/edit?usp=sharing

**Comment by margheweb** [comment]
https://learn.wordpress.org/tutorial/it-choosing-and-installing-a-theme/ published.
