### ISSUE TITLE
Italian translation for Handbook page "Preparing a Technical Tutorial"

### ISSUE THREAD

**Issue by lidialab** [WordPress/Learn#1429]
- Link to original content: https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial/preparing-technical-tutorial/
- Link to original content GitHub issue: not found
- Language you'll be translating to: Italian
- Have you arranged for someone to review this translation?: I will ping one or some of our "Learn IT" members team.

**Comment by kaitohm** [comment]
Hi @lidialab 👋 How is the progress of this translation?

**Comment by lidialab** [comment]
> Hi @lidialab 👋 How is the progress of this translation?

Hi @bsanevans! I will proceed next week, I had unexpected things to do in the last days :)

**Comment by kaitohm** [comment]
No problem. And thanks!

**Comment by lidialab** [comment]
- Reviewers' GitHub usernames: @margheweb, @piermario
- Translation to review: https://docs.google.com/document/d/1Pr3V2gFB64vHEJ8uxFMEpAsZRS-nht7bWDcUi5kTBDw/edit#heading=h.nli7pucnccgs

**Comment by margheweb** [comment]
published: https://it.wordpress.org/team/handbook/training/tutorial/creare-un-tutorial/preparazione-di-un-tutorial-tecnico/
