### ISSUE TITLE
Online Workshop - How to join the Training Team's Welcome Committee

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1431]
# Event Details
- Title: How to join the Training Team's Welcome Committee
- Description: This will be a walkthrough of the Training Team's Welcome Committee role, inviting members to join if they're interested.
- Target Audience: Contributors, Users
- Date: April 14th, 2023
  - [Event 1 - 00:00 UTC](https://www.meetup.com/learn-wordpress-online-workshops/events/292353527/) - co-host: @nomad-skateboarding-dev 
  - [Event 2 - 08:00 UTC](https://www.meetup.com/learn-wordpress-online-workshops/events/292353552/) - co-host: @amitpatel0702 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by nomad-skateboarding-dev** [comment]
Hey, Ben!
I can commit to Event 1. 👍 
> Date: April 14th, 2023
Event 1 - 00:00 UTC - needs co-host

**Comment by kaitohm** [comment]
Thanks, @nomad-skateboarding-dev ! I've assigned you to the issue so that you can follow along.

As a side note, I don't plan on using any slides for this workshop, and instead just utilizing the handbook pages etc. that are already available.

**Comment by nomad-skateboarding-dev** [comment]
Sounds great @bsanevans 🙂🙌

**Comment by kaitohm** [comment]
Video uploaded here: https://wordpress.tv/2023/04/15/how-to-join-the-training-teams-welcome-committee/
