### ISSUE TITLE
Add redirect for Validating and Triaging Content Feedback

### ISSUE THREAD

**Issue by nomad-skateboarding-dev** [WordPress/Learn#1432]
# Feedback Details
- Content title: Validating and Triaging Content Feedback
- Content URL: [https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-triaging-content-feedback/](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-triaging-content-feedback/)
- Reporting an error.

When you search on .org for "validating content errors" the first search result is an old link that goes to 404/Page Not Found.
- https://make.wordpress.org/training/handbook/getting-started/training-team-how-to-guides/how-to-use-helpscout/reviewing-learn-content-errors/
---

# Feedback Report Checklist:
- [x] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by SierraTR** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): Yes 
- What should happen next to apply the feedback?: 
- The issue states that the search phrase used is "validating content errors". The content that is desired to be returned is associated with "validating content feedback". 
- If the search phase is changed to "validating content feedback" when searching on WordPress.org the top search result leads to the appropriate page in the Training Team Handbook: https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/
