### ISSUE TITLE
French translation for Tutorial "Getting to know the WordPress Dashboard"

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Learn#1438]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/getting-to-know-the-wordpress-dashboard/
- Translator: Jenny Dupuy
- Language you'll be translating to: french
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by jennydupuy** [comment]
[Getting to know the WordPress Dashboard.zip](https://github.com/WordPress/Learn/files/11183467/Getting.to.know.the.WordPress.Dashboard.zip)
This zip contains: subtitles.ttml (the source) and subtitles-fr.ttml (the translate in french)

**Comment by lmwp** [comment]
Review OK

**Comment by jennydupuy** [comment]
In this file, the french translate of content proposed below the video.
[content.txt](https://github.com/WordPress/Learn/files/11250124/content.txt)
Note that the text of Transcript is equivalent to text of subtitles.

**Comment by kaitohm** [comment]
@lmwp Are you able to review these translations?

**Comment by lmwp** [comment]
Yes, I continue the review Monday ( I was very busy with the Wordcamp Paris)

**Comment by lmwp** [comment]
Review Ok now. Translations are ready to publish

**Comment by jennydupuy** [comment]
the edited files
[Getting to know the WordPress Dashboard - edited.zip](https://github.com/WordPress/Learn/files/11344135/Getting.to.know.the.WordPress.Dashboard.-.edited.zip)

**Comment by kaitohm** [comment]
I’ve created a copy of the Tutorial. I've also given @jennydupuy access to edit on Learn WordPress. Please replace the English with the French translation here:
https://learn.wordpress.org/wp-admin/post.php?post=36913&action=edit

Once done, let me know, and I will make some final checks and publish the Tutorial 👍

**Comment by kaitohm** [comment]
@lmwp The Training Team would like to make sure we recognize your contribution in a project recap post we're publishing soon. Could you share your WordPress.org username with us please? 🙇

**Comment by jennydupuy** [comment]
Done, the text is now in french
https://learn.wordpress.org/wp-admin/post.php?post=36913&action=edit

**Comment by jennydupuy** [comment]
the Laurent Millet pseudo is wplmillet on wordpress.org

**Comment by lmwp** [comment]
That's right I'm wplmillet on wp.org 
Thank's @bsanevans and @jennydupuy

**Comment by kaitohm** [comment]
@jennydupuy What would the title "Getting to know the WordPress Dashboard" be in French? Once we've replaced that, I think this is ready to publish.

**Comment by jennydupuy** [comment]
I have replaced the title "Getting to know the WordPress Dashboard" by "Se familiariser avec le tableau de bord de WordPress".
You can publish.
🎉❤

**Comment by kaitohm** [comment]
Yay, this has been published: https://learn.wordpress.org/tutorial/fr-getting-to-know-the-wordpress-dashboard/

Thank you!
