### ISSUE TITLE
Add “Interested in running a discussion group?” CTA next to current “Have an Idea for a Workshop?“ CTA

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/Learn#144]
_As per the [discussion in Community Team blog](https://make.wordpress.org/community/2020/10/30/getting-more-learn-wordpress-discussion-group-leaders-and-attendees/)._

Title and image should be quite self-explanatory.

![](https://make.wordpress.org/community/files/2020/10/image.png)

This still needs some copywriting checks and the new "Become a Discussion Group Leader" page being created.

**Comment by coreymckrill** [comment]
Putting this on hold until the "Become a Discussion Group Leader" page is ready.

**Comment by hlashbrooke** [comment]
Here's a page for that: https://learn.wordpress.org/facilitate-a-discussion-group/

**Comment by coreymckrill** [comment]
Do we really want to have two CTAs right next to each other? On every page? That seems... antithetical to the idea of a CTA.

**Comment by hlashbrooke** [comment]
That's a good point! Maybe instead of highlighted CTA this could be included as text underneath the "Upcoming discussion groups" heading. Like a line saying "Want to facilitate a discussion group about a workshop? [Apply to become a facilitator.](https://learn.wordpress.org/facilitate-a-discussion-group/)"

@timiwahalahti How does that sound to you?

**Comment by timiwahalahti** [comment]
Sounds good to me. Getting the message to the front page is more important than the way how it is presented.

**Comment by coreymckrill** [comment]
@hlashbrooke #161 should fix this issue, but it appears that this page doesn't exist yet:
https://learn.wordpress.org/facilitate-a-discussion-group/

**Comment by hlashbrooke** [comment]
Oh whoops - I changed the slug for that page - it's here now: https://learn.wordpress.org/discussion-groups/
