### ISSUE TITLE
Tutorial - WordPress editor modes for streamlining content creation

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1440]
# Topic Description
Distraction-free mode
Full screen mode
Spoghtligh mode 
top toolbar
Always open list view
Template Editing Mode

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
-[ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/231041836-a6495fac-5cfc-44a3-85a1-a519d557dbf6.mp4

**Comment by westnz** [comment]
Review:

Note to self: add cursor effects

**Comment by ghost** [comment]
Great job. Your speaking voice was at a good slow pace. I remember reading that was one of the things people who translate into other languages would like.  I liked the pace of moving around the mouse and clicking on things. I liked the addition of the arrow to highlight the area. The information was very informative and highlighted some of the new features that beginners might not know how to use and their benefits.

**Comment by westnz** [comment]
Appreciate the feedback @lada7042

**Comment by wparasae** [comment]
This looks great, Wes. I like that you're responding to the feedback from our greater community to slow it down for an international audience. The new transitions you're using are interesting and add visual appeal. 

I didn't see any opportunities for change, so I think this is good to go!

**Comment by westnz** [comment]
Thank you @wparasae

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/wordpress-editor-modes-for-streamlining-content-creation/
