### ISSUE TITLE
Online Workshop - A Guide to Open Source and WordPress

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Learn#1441]
# Event Details
- Title: A Guide to Open Source and WordPress
- Description: You may have heard the term “Open Source” mentioned when talking about WordPress and other software, but what does it mean? In this workshop, we will talk about:
   - The meaning of the term “Open Source” when referring to software
   - What the GPL software license provides
   - Why WordPress is an Open Source project, and how this is important
- Target Audience: All
- Date: Replay of Oct 17 session on [Oct 19 2023 at 19:30 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20231019T1230&p1=224)
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/296779348/
- Previous sessions:
  - [Oct 17 2023](https://www.meetup.com/learn-wordpress-online-workshops/events/296777674)
  - [July 25 2023](https://www.meetup.com/learn-wordpress-online-workshops/events/294677746/) co-host @SierraTR 
  - Apr 11-12 2023: [Timezone 1](https://www.meetup.com/learn-wordpress-online-workshops/events/292612005/), [Timezone 2](https://www.meetup.com/learn-wordpress-online-workshops/events/292612924/)
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by courtney-pk** [comment]
Recording with slide deck link at: https://wordpress.tv/2023/04/12/a-guide-to-open-source-and-wordpress/

**Comment by courtney-pk** [comment]
Re-opening this, as I am scheduling a repeat session in July 2023.

**Comment by SierraTR** [comment]
I can co-host on July 25th at 19:00 UTC.

**Comment by courtney-pk** [comment]
Thank you, @SierraTR! I've added you as Co-host to this session.

**Comment by courtney-pk** [comment]
Content was not revised, so refer to [the previous recording](https://wordpress.tv/2023/04/12/a-guide-to-open-source-and-wordpress/).

**Comment by courtney-pk** [comment]
Reopening to hold a session in October 2023

**Comment by courtney-pk** [comment]
- [Previous recording](https://wordpress.tv/2023/04/12/a-guide-to-open-source-and-wordpress/)
- [Slides](https://drive.google.com/file/d/1VAy5xJTSmX-8WO9NVXID1RVJT8qQ8cuJ/view) only updated to update the design and update contact info.
