### ISSUE TITLE
Add details about discussion groups in workshop pages

### ISSUE THREAD

**Issue by timiwahalahti** [WordPress/Learn#145]
_As per the [discussion in Community Team blog](https://make.wordpress.org/community/2020/10/30/getting-more-learn-wordpress-discussion-group-leaders-and-attendees/)._

On a single workshop page, add a small blurb on top of the "Join a Discussion Group" button explaining what is a discussion group. Below the button could be a small text, much like the CoC notice, saying that if there’s no scheduled discussion group for this workshop, apply to be a discussion group leader to run one.

This needs copy and the new "Become a Discussion Group Leader" page being created before fully implementing.

**Comment by coreymckrill** [comment]
Putting this on hold until the "Become a Discussion Group Leader" page is ready.

**Comment by hlashbrooke** [comment]
Here's a page for that: https://learn.wordpress.org/facilitate-a-discussion-group/

**Comment by coreymckrill** [comment]
I think adding another text blurb to the sidebar of every workshop would get kind of messy and distracting. What if the "Join a Group Discussion" button linked to a dedicated page that explained everything and then linked out to the meetup group, and then additionally had all the info about becoming a facilitator?

**Comment by hlashbrooke** [comment]
Fair point yeah.

I think it would be good if we could update that discussion group page to have information about discussion groups at the top, then a block showing the upcoming discussion groups, followed by the form as it stands now.

@coreymckrill Is that 'upcoming discussion groups' block ou made for the home page a block that we could just insert here too? Or is it exclusively tied to the homepage template?

**Comment by timiwahalahti** [comment]
Agree with Corey.

I can work with the copy for that page.

**Comment by coreymckrill** [comment]
> Is that 'upcoming discussion groups' block ou made for the home page a block that we could just insert here too? Or is it exclusively tied to the homepage template?

Right now it's just hard coded into the front page template, but we could make a block for it too.

**Comment by hlashbrooke** [comment]
This is looking great on the homepage! If you're able to make it a block/shortcode then that would be great, but it's not essential if that will be too much to work on here.

**Comment by coreymckrill** [comment]
#163 is a draft PR for adding a block, but it's probably not going to get done before the launch, so I'm going to remove this issue from that milestone.

**Comment by hlashbrooke** [comment]
Works for me - this is lower priority than the other launch items.

**Comment by hlashbrooke** [comment]
We have renamed 'discussion groups' to 'social learning spaces' and have a dedicated page for them here: https://learn.wordpress.org/social-learning/ - the copy being discussed in this issue will need to be added there, so I'm going to close this issue as that won't be a code change.

#265 updates the button text and link to the new page.
