### ISSUE TITLE
Online Workshop - The WordPress request lifecycle

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1451]
# Event Details
- Title: The WordPress request lifecycle
- Description: When working with any CMS or web framework, it's a good idea to understand the basics of how it works under the hood. When you understand how your development tools function, you feel more comfortable and confident using them. In this session, you'll learn the basics of the WordPress request lifecycle, walking through the process that happens on the web server when a browser makes a request to a WordPress URI.
- Target Audience: Developers
- Date: 2023-04-06
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/292621835/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
Livestream prep: https://www.meetup.com/learn-wordpress-online-workshops/events/292621835/

**Comment by nomad-skateboarding-dev** [comment]
I'm free and interested in co-hosting this session @jonathanbossenger. 🙌

**Comment by jonathanbossenger** [comment]
Cool. Thanks @nomad-skateboarding-dev

**Comment by jonathanbossenger** [comment]
## Notes:

* index.php is the entry point for all front end requests
    * require __DIR__ . '/wp-blog-header.php';
    * include() statement generates a PHP alert but allows script execution to proceed if the file to be included cannot be found, the require() statement generates a fatal error and terminates the script.
        * require_once __DIR__ . '/wp-load.php';
        * ABSPATH is the first WordPress defined constant
            * require_once ABSPATH . 'wp-config.php';
                * require_once ABSPATH . 'wp-settings.php';
                * https://developer.wordpress.org/reference/functions/shutdown_action_hook/
                * SHORTINIT - https://wp-kama.com/1581/shortinit-constant
                * Load active plugins.
                * https://codex.wordpress.org/Pluggable_Functions
                * wp_magic_quotes();
                * Sets up all global variables
                * Sets up the theme
                * Sets up WP_Site_Health
                * $GLOBALS['wp']->init();
    * Set up the WordPress query.
    * wp();
        * $wp->main( $query_vars );
        * This will set up the query object with all the data from the database, based on the query variables
    * require_once ABSPATH . WPINC . '/template-loader.php';
        * $tag_templates
            * Home page and a single page

**Comment by jonathanbossenger** [comment]
VS Code Preview setting https://vscode.one/new-tab-vscode/
PHP Intelephense https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

**Comment by nomad-skateboarding-dev** [comment]
@jonathanbossenger attendees number for today was 20.

* And by the anecdotal immediate feedback at the end, this was one of the most needed and well received dev presentations from the attendees point of view!

I would add my own feedback, that I concur. 🙂 Seeing the exact foundational structure and code, and getting an understanding of how it all relates within WordPress, was very beneficial for me.

Well done, Jonathan.

**Comment by jonathanbossenger** [comment]
Thanks for your kind words @nomad-skateboarding-dev

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/04/07/workshop-the-wordpress-request-lifecycle/
