### ISSUE TITLE
Omit "teach" "teaching" and troublesome terminology

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#146]
Marketing has worked with Training over several years to reach the terminology ideas shown here: https://docs.google.com/document/d/1XoNUfSFRQh5o7Cr2HnVZdpUiEtBXh6cGbpm7Ekz-7VQ/edit?usp=sharing 

The term "teach" is using in various forms on the front page of Learn. Facilitate would be a better option.

**Comment by hlashbrooke** [comment]
Could we please update the text on the home page in the following areas:

**At the very end of the text in the main site description above the search box ([file](https://github.com/WordPress/learn/blob/49a011b0d85dcf472f0c0d97aa138f5c14d40a90/wp-content/themes/pub/wporg-learn-2020/header.php)):**

> these vast resources will help you learn more about WordPress and share it with others.


**The placeholder text in the search input box ([file](https://github.com/WordPress/learn/blob/2b9e66afc2060e7e6c9ae0a861779c83e35d82eb/wp-content/themes/pub/wporg-learn-2020/searchform.php)):**

> Search for a learning resource


**In the blue Lesson Plans block below the search box ([file](https://github.com/WordPress/learn/blob/a6ae6245072d01899ca30ad1245e085af8f821af/wp-content/themes/pub/wporg-learn-2020/front-page.php)):**

The first sentence in the block:
> Are you sharing WordPress with others?

The link text at the bottom of the block:
> Access Lesson Plans

**Comment by abhansnuk** [comment]
Thanks Hugh for helping me with this ticket.
