### ISSUE TITLE
Documentation: missing contribution guidelines 

### ISSUE THREAD

**Issue by Aymenboch** [WordPress/Learn#1460]
the project missing CONTRIBUTING.md that can contain some details from the [Training Team Handbook].
Most of the CONTRIBUTING.md contains: 
- Filing Bugs
- Enhancements
- Contributing Code 
- Code of Conduct

**Comment by kaitohm** [comment]
Thank you for raising this, @Aymenboch ! We'll work on adding that file to our repo.

(For internal records, this was discussed in this Slack thread: https://wordpress.slack.com/archives/C02RW657Q/p1681106142469649)

**Comment by jonathanbossenger** [comment]
Added a [Contributing](https://github.com/WordPress/Learn#contributing) section to the readme which links to the [Code contributions](https://make.wordpress.org/training/handbook/training-team-how-to-guides/code-contributions/) guidelines in our handbook.
