### ISSUE TITLE
Indonesian translation for Tutorial -  The Difference Between Reusable Blocks, Block Patterns, Templates & Template Parts

### ISSUE THREAD

**Issue by ardianimaya** [WordPress/Learn#1461]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/the-difference-between-reusable-blocks-block-patterns-templates-and-template-parts/ 
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/450 
- Translators: @ardianimaya 
- Language you'll be translating to: Indonesian
- Reviewer's GitHub username: @situstarget
- Other info: https://docs.google.com/document/d/1Phd2lPAg_3jeXoECmpjbUt11qx5Rd62A3SF3bDNg8GM/edit

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by ardianimaya** [comment]
Hello! I've finished translating this tutorial: https://docs.google.com/document/d/1Phd2lPAg_3jeXoECmpjbUt11qx5Rd62A3SF3bDNg8GM/edit . Currently still trying to reach out to fellow ID translators to find a reviewer, will update here once I found one :)

**Comment by kharissulistiyo** [comment]
Hi @ardianimaya, 

As per this conversation on [WordPress Indonesia Slack](https://wp-id.slack.com/archives/C53826D9B/p1680860726164269), the translation has been reviewed by [Robi Erwin Setiawan](https://profiles.wordpress.org/situstarget/) (GTE for Indonesian). Thank you!

**Comment by kaitohm** [comment]
I've created a copy of the English Tutorial here: https://learn.wordpress.org/wp-admin/post.php?post=33197&action=edit

@ardianimaya once you have accepted the email invitation, please transfer your Indonesian translation directly into the Tutorial above. You can delete the English you see there.

Then, please follow [Translating Subtitles](https://make.wordpress.org/training/handbook/content-localization/translating-subtitles/) to translate and submit the subtitle file to WordPress.tv. You've already translated the transcript in the Google doc, so this will mostly be copy-pasting.

Once done, let me know again, and I can publish the Tutorial, and approve the subtitles for you 😃

**Comment by ardianimaya** [comment]
Hi @bsanevans , I've submitted the subtitle, and saved the Tutorial as a draft (since I assume it still needs to be vetted, and only faculty members can publish it?). Thanks in advance and let me know if anything! :D

**Comment by kaitohm** [comment]
Thank you, @ardianimaya ! The Tutorial has now been published here: https://learn.wordpress.org/tutorial/id-the-difference-between-reusable-blocks-block-patterns-templates-amp-template-parts/ 🎉
