### ISSUE TITLE
Online Workshop - Creating a WordPress Multisite Network

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1467]
# Event Details
- Title: Let's code: creating a WordPress Multisite Network
- Description: A multisite network can be very similar to your own personal version of WordPress.com. End users of your network can create their own sites on demand, or you can create a multisite network in which only you, the administrator, can add new sites. In this session, you'll learn about creating a multisite network, as well as walk through the steps to setting one up.  
- Target Audience: Developers
- Date: 2023-04-13 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/292771973/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by Thelmachido** [comment]
I can co-host

**Comment by jonathanbossenger** [comment]
Thanks @Thelmachido

**Comment by jonathanbossenger** [comment]
Top level domain to multisite sub site.

**Comment by jonathanbossenger** [comment]
It would be great to have a separate session on converting multisite to a single site and taking a subsite out of the network! mad science experiments!

**Comment by jonathanbossenger** [comment]
If you have an existing site (Bob LA), can you create a multisite main site above it (Bob USA) to keep the first site as a subsite?

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/04/14/lets-code-creating-a-wordpress-multisite-network/
