### ISSUE TITLE
Migrate WPSandbox resources in content to InstaWP

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1469]
Original message by @courtneyr-dev [in Slack](https://wordpress.slack.com/archives/C03B11FA16D/p1680742321709719):

---

Hey folks, I've learned from StellarWP that they will be retiring [WPSandbox.io](http://wpsandbox.io/).  This isn't public, but I have permission to bring it up here. We have at least 90 days from when they do publicly announce the information to move off.
It is still an option in a few of our courses I think.  What we'll need to do is:

- Find all times WPSandbox links are provided
- Determine any unique configuration needed in the context of the course
- Recreate that in InstaWP on its own master site
- Create a template from each
- Place the template into the course.
- Perhaps one day we'll see WordPress Playground be retrievable in such a setup, and/or GitHub Codespaces.  Until then, we should start to assess the courses needing changes.

**Comment by kaitohm** [comment]
Related: https://make.wordpress.org/training/2022/04/07/demo-sites-for-learn-wordpress-users/

**Comment by jonathanbossenger** [comment]
I am not aware of this still being in use anywhere, and if it is, whoever spots it can open a content feedback issue. So I'm going to close this out for now.

**Comment by courtneyr-dev** [comment]
The content is in InstaWP, and also Playground.  InstaWP has updates available via the plugin Beta Tester at release. I maintain this and attend each release party I can (missing usually only when traveling).  Playground is being automated, and takes about 35 minutes to detect. These are usually used when preparing materials ahead of releases, having pre-loaded content AND the proper version available.
