### ISSUE TITLE
Lesson Plans: Create 'series' taxonomy to group lesson plans together

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#147]
Lesson Plan + Lesson Plan + Lesson Plan = Workshop (the term the team originally used before Community Video Workshops were created).  We can adjust the word "workshop" but the idea here remains for filtering https://wp.invisionapp.com/share/BNP0V7QXRF8#/screens/330323718

**Comment by coreymckrill** [comment]
@courane01 Can you say more about this? I understand the idea of grouping multiple lesson plans together, but I'm not following how the linked screenshot relates to that, or how we would implement the groupings on the site.

**Comment by courtneyr-dev** [comment]
Our lesson plans show no logical progression. I'm mostly digging back through visions the team had on layout & functionality and found this. The original goal was that Meetup facilitators could fetch a series of plans to run a half/full day workshop.

**Comment by courtneyr-dev** [comment]
https://github.com/wptrainingteam/learn-theme-beta/issues shows several filtering issues that were left in that state before Learn went live.

**Comment by courtneyr-dev** [comment]
https://wordpress.slack.com/archives/C02RW657Q/p1605720465134900?thread_ts=1579550929.007200&cid=C02RW657Q "series" taxonomy similar to video workshops

**Comment by courtneyr-dev** [comment]
This ticket represents the screenshot shown above. I would envision the filter tools to display somewhere near the nav bar, not to be a lander page.

**Comment by hlashbrooke** [comment]
Renamed for clarity based on above discussion.

Lesson plans need a taxonomy like the workshop 'series' taxonomy. I'm happy for the lesson plans tax to be called 'series' as well, so perhaps we could use the same one as workshops and just apply it to multiple post types? Would that cause any conflicts? If that's not feasible, then just create a new taxonomy.
