### ISSUE TITLE
Tutorial - Building a page with only patterns

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1489]
# Topic Description
Using templates to simplify the design process and save time.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
Recording to OW: https://wordpress.tv/2023/04/18/building-a-page-with-only-patterns/

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/233554260-10d210c6-0a24-45e0-ac42-bde81110a18e.mp4

**Comment by askdesign** [comment]
Hi Wes,
Great work! This tut shows a lot of possibilities.
2:47 - linger a bit longer on the Copy Pattern button, so people can see the tooltip/help text underneath.
-- CTA buttons and links: there are 3 different styles, which I think is confusing. You could, instead, apply that rectangle style to each CTA.
-- Might be good to mention: Unlike reusable blocks, you can modify the patterns you've pasted into your WP site without affecting the original in the repository.

**Comment by westnz** [comment]
Review:
<img width="930" alt="image" src="https://user-images.githubusercontent.com/89751452/234428772-309b4305-b229-43b2-851f-653f6c8c81a8.png">

**Comment by westnz** [comment]
Thank you for the feedback @askdesign and Jamie!

**Comment by ghost** [comment]
Great job! I saw this was still on the review list for this week's agenda. Very easy to understand. Slow speaking voice for people to understand.

**Comment by westnz** [comment]
Thank you @lada7042

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/building-a-page-with-only-patterns/

**Comment by courtneyr-dev** [comment]
6.4 https://github.com/WordPress/gutenberg/pull/51946

**Comment by westnz** [comment]
Updated and published as part of the Intermediate user learning pathway in Sensei: https://youtu.be/PF8e1Z0GkK8
