### ISSUE TITLE
Meeting Agenda for April 18, 2023

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1492]
This week’s meeting will be held in the APAC timezone and in the Make WordPress [#training](https://wordpress.slack.com/archives/C02RW657Q) Slack channel on Tuesday, April 18th, 2023, at 07:00 UTC, and @bsanevans will be hosting.

### 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

### 2. News
1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)

    - April 18 - [@idrissathiam01](https://profiles.wordpress.org/idrissathiam01/)
    - April 25 - Need volunteer
    - May 2 - Need Volunteer
    - May 9 - Need Volunteer
    - May 16 - Need Volunteer
    - May 23 - Need Volunteer
    - May 30 - Need Volunteer

2. Looking for feedback

    - [Next Steps for the Faculty Program](https://make.wordpress.org/training/2023/04/07/next-steps-for-the-faculty-program/) (feedback welcome from both Faculty and non-Faculty members)
    - [Proposal: Creating Learning Pathways for Learn WordPress](https://make.wordpress.org/training/2023/04/05/proposal-creating-learning-pathways-for-learn-wordpress/) (by May 1)
    - [Discussion on Gutenberg Rapid Website Recreation Videos](https://github.com/WordPress/Learn/issues/1439)
    - #1487 
    - Should sharing presentation slides be a requirement for Online Workshop presenters? ([Slack thread](https://wordpress.slack.com/archives/C02RW657Q/p1681778344180559))

3. Looking for volunteers

    - Would anyone like to update https://learn.wordpress.org/pathways-to-learn-wordpress (See [this Slack message](https://wordpress.slack.com/archives/C02RW657Q/p1680726322111219) for the initial call for help)

4.  [Building Blocks: The Evolution of WordPress 2013-2023](https://make.wordpress.org/project/2023/04/13/wordpress-at-20-in-print/) - Provide feedback via GitHub with first-look access to the upcoming WP20 Book.

###  3. Content published in the last week

- Tutorials 
    - [Using Template Parts](https://learn.wordpress.org/tutorial/using-template-parts/)
    - [Creating a custom template with the WordPress site editor](https://learn.wordpress.org/tutorial/creating-a-custom-template-with-the-wordpress-site-editor/)

- Lesson Plans
    - [பக்கங்கள் Vs. இடுகைகள்](https://learn.wordpress.org/lesson-plan/ta-pages-vs-posts/)

### 4. Open requests for review

- Tutorials

    - [Using Page Templates - Tutorial](https://github.com/WordPress/Learn/issues/455)
    - [Tutorial - Developing WordPress User Roles and Capabilities](https://github.com/WordPress/Learn/issues/1417)
    - [Tutorial - WordPress editor modes for streamlining content creation](https://github.com/WordPress/Learn/issues/1440)
    - [Tutorial - The WordPress request lifecycle](https://github.com/WordPress/Learn/issues/1454)
    - [Tutorial - Introduction to WordPress Multisite](https://github.com/WordPress/Learn/issues/1497)

- Lesson Plans

    - [CSS Flexbox - Lesson Plan](https://github.com/WordPress/Learn/issues/713)
    - [WordPress Action Hooks - Lesson Plan](https://github.com/WordPress/Learn/issues/806)

- [Translated Content](https://github.com/WordPress/Learn/issues?q=is%3Aissue+is%3Aopen+label%3A%22Needs+Translation+Reviewer%22) 

    - Spanish - [Spanish translation for Lesson Plan “Managing Comments”](https://github.com/WordPress/Learn/issues/1133)
    - Tamil - [Tamil translation for Lesson Plan “Choosing And Installing Plugins”](https://github.com/WordPress/Learn/issues/1338)
    - Khmer - [Khmer translation for Lesson Plan “Dashboard Overview”](https://github.com/WordPress/Learn/issues/1357)
    - Indonesian - [Indonesian translation for Lesson Plan "Intro to the Site Editor and Templates"](https://github.com/WordPress/Learn/issues/1488)
    - Bengali - [Bengali translation for Lesson Plan "Dashboard Overview"](https://github.com/WordPress/Learn/issues/1392)

### 5. Project updates

- [Content Localization Foundation](https://make.wordpress.org/training/2022/11/07/project-thread-content-localization-foundations/) – [@bsanevans](https://profiles.wordpress.org/bsanevans/) - wrapping up on April 30

    - See [April 8 update](https://make.wordpress.org/training/2022/11/07/project-thread-content-localization-foundations/#comment-3804) for project details.

    - We’re looking for ideas to streamline the process of reviewing subtitle files, as GitHub doesn’t accept .ttml file uploads. Please leave your comments on [this Slack thread](https://wordpress.slack.com/archives/C02RW657Q/p1680915510177869).

- [Individual Learning Survey for the Needs Analysis](https://make.wordpress.org/training/2023/01/16/project-thread-learning-needs-analysis/) – [@west7](https://profiles.wordpress.org/west7/)

    - Due to unforeseen circumstances, the data analysis publication date has been postponed until further notice. An update will be posted once we have more information.

### 6. Open Discussions
If you have topics you’d liked discussed in the meeting, please leave them as a comment on this post.
<hr>

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in the [#training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kaitohm** [comment]
Notes published here: [Meeting Recap for April 18th, 2023](https://make.wordpress.org/training/2023/04/18/meeting-recap-for-april-18th-2023/)
