### ISSUE TITLE
Online Workshop - Let's code: WordPress multisite mad science experiments!

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1493]
# Event Details
- Title: Let's code: WordPress multisite mad science experiments!
- Description: The firs time you learn about a WordPress multisite network, you might find you have a bunch of questions. Things like, "Can I point top-level domains to subdomain sites?", "Can I convert a multisite back to a single site?", "Can I extract a subsite out of the network?", "If you have an existing site, can you create a multisite main site above it to keep the first site as a subsite?" and many more. In this session, we'll look at some of the things that are possible with a multisite network, and hopefully answer all these questions. 
- Target Audience: Developers
- Date: 2023-04-20
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/292894358/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
Livestream: https://www.meetup.com/learn-wordpress-online-workshops/events/292894399/

**Comment by jonathanbossenger** [comment]
# Experiment 1

Pointing a top-level domain to a multisite sub-site?

Yes:

1. New top-level domain must be pointing to the multisite install
2. In the Network Admin - Sites - Edit Site
3. Change **Site Address (URL)** to the new top-level domain

## Notes

1. The subsite admin can login via the multisite URL or the new subsite TLD url
2. The same user can be given access to multiple subsites on the network

**Comment by jonathanbossenger** [comment]
# Experiment 2

Taking a subsite out of the network!

Yes, with caveats:

1. Use the WordPress export tool for your posts, pages, comments etc,
2. Create the new site
3. Use the importer to import the data
4. Copy the uploads directory over manually
5. Test

Caveats: 
1. This might not cover any custom data/tables

Third-party options:

- https://servmask.com/products/multisite-extension
- https://deliciousbrains.com/wp-migrate-db-pro/doc/multisite-tools-addon/

**Comment by jonathanbossenger** [comment]
# Experiement 3

Converting multisite to a single site

Yes:

1. Remove multisite-related constants in wp-config
2. Reset .htaccess by resetting permalinks
3. Delete any tables created during the multisite installation
5. Delete any multisite users

## Tables to delete
- wp_blogmeta
- wp_blogs
- wp_registration_log
- wp_signups
- wp_site
- wp_site_meta
- and any specific blog content tables (eg wp_2, wp_3 etc)

**Comment by jonathanbossenger** [comment]
# Experiment 4

If you have an existing site can you create a multisite main site above it to keep the first site as a subsite?

No:

If you wanted this, you would need to move sites around.

Changing the constant values does not alter the main site. Nor is it possible to change the main site in the dashboard.

**Comment by jonathanbossenger** [comment]
# Experiment 5

Sub-domains vs sub directories

WordPress will attempt to request a random sub domain URL on the TLD

```
Warning! Wildcard DNS may not be configured correctly!

The installer attempted to contact a random hostname (0f8bfe.multipress.test) on your domain. This resulted in an error message: cURL error 6: Could not resolve host: 0f8bfe.multipress.test

To use a subdomain configuration, you must have a wildcard entry in your DNS. This usually means adding a * hostname record pointing at your web server in your DNS configuration tool.

You can still use your site but any subdomain you create may not be accessible. If you know your DNS is correct, ignore this message.
```

**Comment by jonathanbossenger** [comment]
# Experiment 6

Allow site registrations

Network settings -> Both sites and user accounts can be registered

Log out and register a new site

There seems to be a [bug with block themes](https://core.trac.wordpress.org/ticket/55023).

**Comment by nomad-skateboarding-dev** [comment]
I'm available to co-host with you @jonathanbossenger 🙌

**Comment by jonathanbossenger** [comment]
Thanks @nomad-skateboarding-dev

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/04/21/lets-code-wordpress-multisite-experiments/

**Comment by jonathanbossenger** [comment]
20 attendees
