### ISSUE TITLE
Learn WordPress Content Feedback -

### ISSUE THREAD

**Issue by pmbaldha** [WordPress/Learn#1495]
# Feedback Details
- Content title: Migrate, Copy, Or Clone A Site
- Content URL: https://learn.wordpress.org/lesson-plan/migrate-copy-or-clone-a-site/
- Are you reporting an error (such as outdated information), or providing improvement ideas?:

Write a description of your feedback here:
Typo mistakes in the code snippets

![image](https://user-images.githubusercontent.com/15802539/232183816-7f572a95-c1c3-44bd-a7eb-23f23772ab28.png)

---

# Feedback Report Checklist:
- [x] Feedback validated
- [x] Update proposed
- [ ] Update reviewed
- [x] Update published

**Comment by devmuhib009** [comment]
@pmbaldha Thanks for reporting. I just fixed the typo. :raised_hands:
