### ISSUE TITLE
Tutorial - Introduction to WordPress Multisite

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1497]
# Topic Description
A multisite network is a collection of sites that all run off the same WordPress installation. In this tutorial, you’ll learn what a multisite network is, why you might consider using a multisite network, and walk through the steps to set one up.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [Create A Network](https://wordpress.org/documentation/article/create-a-network/)

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [X] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/wp-multisite-01-create-a-network.md

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/232550857-c487d784-9a9f-4485-a322-fe382cead55b.mp4

Video for review

**Comment by nomad-skateboarding-dev** [comment]
This is a great overview @jonathanbossenger ! It inspired me to start a new project involving the use of Multisite. 🙂 👍 

## Specific feedback
- The transition slides you used worked really well for me. I knew what was happening with the arrows denoting movement, and it felt engaging.
- I would have liked to view the code and directories @ 6:00-6:20 for a few seconds longer each time you copy and pasted. But this could certainly be my own unfamiliarity with viewing the .htaccess and wp.config.php files, and pausing the video is an easy answer, as well.

**Comment by westnz** [comment]
Solid Tutorial! You have effectively used slides and annotations, and have provided good examples. The steps are clearly outlined.

**Comment by naomi060397** [comment]
Well done. Good examples are given and I like how you highlight key areas of the screen with arrows and boxes and such to make it clear.

Most projects I’ve worked on have used subdirectories over subdomain, so it’s good you explained the difference and pointed to directories as being the simpler option.

You show the wp-config and .htaccess files, but maybe you could mention these would be useful to make backups of. Though maybe that’s redundant if the viewer has any experience setting up WP sites and has read the backup doc resource you provided.

**Comment by jonathanbossenger** [comment]
Thanks @naomi060397 for the review.

> You show the wp-config and .htaccess files, but maybe you could mention these would be useful to make backups of.  Though maybe that’s redundant if the viewer has any experience setting up WP sites and has read the backup doc resource you provided.

This is actually a good point, and while I don't disagree with your thinking around redundancy, I do think it's valuable to add to the tutorial, so I'll do so. I did include this when I presented this content as an online workshop, and I think it's important to include it. Thanks for catching this.

**Comment by jonathanbossenger** [comment]
Published: https://learn.wordpress.org/tutorial/introduction-to-wordpress-multisite-networks/
