### ISSUE TITLE
Online Workshop - WordPress & the IndieWeb

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Learn#1498]
# Event Details
- Title: WordPress & the IndieWeb (with David Wolfpaw)
- Description: In this presentation, we will discuss the IndieWeb movement and how you can use WordPress to build your own IndieWeb site.
The IndieWeb is a movement to take back control of our online identities and relationships. It's based on the principles of openness, decentralization, and ownership. This may sound familiar to WordPress users!
- Target Audience: Any user
- Date: June 21, 2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/294071517/
- Co-host: @boogah 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by boogah** [comment]
So long as this is shooting to be in AMER, I'm happy to volunteer as co-host for this one.

**Comment by courtney-pk** [comment]
@boogah Since I am hosting with David presenting, co-host duties will be pretty light for this one — largely just helping monitor the chat and waiting room. We've settled on June 21, 2023 at 2pm Pacific.

If you're still up for this, please [submit an application to co-host](https://learn.wordpress.org/online-workshops/#apply-to-facilitate). Note: In the case you're not currently interested in creating/facilitating your own workshops just yet, make sure to mention in the application that you're just interested in co-hosting at this time. Thanks!

**Comment by boogah** [comment]
I've gone ahead and submitted an application to co-host! Looking forward to helping out in the chat and waiting room with this one.

**Comment by courtney-pk** [comment]
As your application has been processed and approved, I've added you as co-host on this event, @boogah! Let's connect on Slack sometime before the event so we can go over what to expect.

**Comment by courtney-pk** [comment]
Recording with captions and link to slides at: https://wordpress.tv/2023/06/22/wordpress-and-the-indieweb/
