### ISSUE TITLE
Custom Gutenberg block development for Learn and Training websites.

### ISSUE THREAD

**Issue by karthick-murugan** [WordPress/Learn#1499]
## Description

Custom Gutenberg block development

Proposing custom Gutenberg blocks for meeting recap notes, faculty meetings, onboarding posts, etc. This will help to speed up adding/editing the content part.

The idea is to give the simplest user interface for adding required data for meeting recap notes, agenda posts, etc in no time. This will also encourage new contributors to create and work on posts.

## Screenshots or screen recording (optional)

![step-1](https://user-images.githubusercontent.com/97787966/232786627-fbd06501-c3c9-444b-8d9f-aef5d388c023.png)
![step-2](https://user-images.githubusercontent.com/97787966/232786644-c732df59-935e-454a-838e-eb700385916f.png)

**Comment by karthickmurugan2911** [comment]
Hi @bsanevans , @jonathanbossenger @all.,

For the Training team recap custom block that we are working, do we need to create a separate plugin for our block? Or we can integrate our code in the "[Wordpress.org](http://wordpress.org/) Learn" plugin, which is already available. Please have a look at this screenshot https://share.cleanshot.com/zgmCRffrGYJw7Gty1l4K  Please advise.

**Comment by kaitohm** [comment]
@karthick-murugan The custom block you are recommending is for https://make.wordpress.org/training/ , correct? I think the screenshot you shared shows plugins for https://learn.wordpress.org - a different site. I'm not sure what steps are needed to add a custom block to the https://make.wordpress.org/training/ site. Please ask for guidance in the [Meta team's Slack channel](https://wordpress.slack.com/archives/C02QB8GMM). That team looks after each team's site.

**Comment by amitpatel0702** [comment]
Thanks @karthick-murugan, @bsanevans.
I have few inputs to share here for https://make.wordpress.org being a main website or a Multisite network. @karthick-murugan my idea is to make a parent block with the parent theme so that any subsite can utilize it in future. While you connect with Meta team, please mention you need to create a parent custom Gutenberg block so that any team can utilize it in future.

**Comment by karthick-murugan** [comment]
@bsanevans - Yes the custom block is for the training subsite. Will post the question in the meta slack channel.
@amitpatel0702 - Thanks Amit for your insights. Yes it will be great if we create it as Parent custom gutenberg block. Will post the same.

**Comment by kaitohm** [comment]
I'm just noting this conversation was raised with the Meta team here: https://wordpress.slack.com/archives/C02QB8GMM/p1682574141450849
