### ISSUE TITLE
Tutorial - Managing a WordPress Multisite Network

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1501]
# Topic Description
In this tutorial, you'll be guided through managing a multisite network, including an overview of the Network Admin dashboard, the Network Settings page, and the process of creating and Managing Sub-sites.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [Network Admin](https://wordpress.org/documentation/article/network-admin/)
- [Network Admin Settings](https://wordpress.org/documentation/article/network-admin-settings-screen/)

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/wp-multisite-02-manage-a-network.md

**Comment by jonathanbossenger** [comment]
Video for review

https://user-images.githubusercontent.com/180629/233676107-40d2048f-47eb-4d1d-83c2-b2e7a5c9159f.mp4

**Comment by westnz** [comment]
Great pace and steps clearly explained!

**Comment by quitevisible** [comment]
I setup a multisite several years ago. This was a great refresher and allowed me a sneak peak at the latest admin dashboard without having to set one up first! Good one @jonathanbossenger

**Comment by jonathanbossenger** [comment]
Thanks so much for the review @quitevisible I'm glad it was useful.

**Comment by jonathanbossenger** [comment]
Published https://learn.wordpress.org/tutorial/managing-a-wordpress-multisite-network/
