### ISSUE TITLE
Tutorial - Advanced Multisite Management

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1502]
# Topic Description
Looking at some advanced multisite topics, like exporting a sub-site to a single site install, or converting a multisite back to a single site install. 

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [X] Review any related material on Learn
- [X] Define several SEO keywords to use in the article and where they should be prominently used
- [X] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
Note to self, site statues are boolean columns in the blogs table. Edit tutorial accordingly.

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/wordpress-roles-capabilities-02-custom-post-types.md

**Comment by jonathanbossenger** [comment]
Video for review. 


https://github.com/WordPress/Learn/assets/180629/617302c7-0cb8-49e2-ae80-fdf34a844964

**Comment by quitevisible** [comment]
@jonathanbossenger is this the right video? The video was on a CPT plugin but title for this issue says “Advanced Multisite Management”. The video was still pretty good, I was just waiting to see how it related to multisite :)

**Comment by jonathanbossenger** [comment]
Whoops! Thanks for picking this up @quitevisible, it should be the right video now.

**Comment by quitevisible** [comment]
Ok cool, @jonathanbossenger - yes that video makes more sense! Here's thoughts...

- I like the TOC laid out at the beginning of the video. It let's me know what to expect. 
- On setting a subsite to Spam, I know you mentioned no additional hooks are fired, but one question might then be, "what exactly does that do?". In other words, why not just delete or archive the subsite?
- The progressing sections on converting sub/multi/single sites was well done. 

Great tutorial!

**Comment by jonathanbossenger** [comment]
@quitevisible thanks for the feedback and review.

> On setting a subsite to Spam, I know you mentioned no additional hooks are fired, but one question might then be, "what exactly does that do?". In other words, why not just delete or archive the subsite?

Honestly, that was my question as well, it's literally just a 0 or 1 change in the database for that field, and nothing else happens. 

I assume the idea is that developers could then build their own functionality depending on the status, but that's based on the use case, and not specific to core WordPress, which is why I didn't go deeper.

**Comment by jonathanbossenger** [comment]
Tutorial published https://learn.wordpress.org/tutorial/advanced-multisite-management/
