### ISSUE TITLE
Online Workshop - How to add a blog or news page to a WordPress website

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1504]
# Event Details
- Title: How to add a blog or news page to a WordPress website
- Description: 
Details
Do you have an existing WordPress website and want to set up a blog, news, or updates page to it?

Did you just attend the session on setting up a WordPress test website and want to experiment in a group setting?

If someone says the word, "Query Loop", is your first thought, "Query what?"

If so, please join us in this interactive, experimental workshop!

We will explore two different ways to add a blog/posts page to your website, as well as how to add and remove demo content so you can see what you're doing on a blank website.

How will we learn?
This workshop is meant to be hands-on; it's an "I do / you do / we help!" session where Sarah Snow (your instructor) will guide you step by step through the setup of a blog page, help you create some easy-to-remove demo content so you can really see what you're doing ahead of time, give you time to experiment on your own device, and then help learners collaboratively troubleshoot problems that occur along the way.

Important!
We will be using a test website for this experiment; it is important to get set up with a test website before you arrive to respect the time of all.

How do I get a test website?

You can [join us in the short session scheduled BEFORE this one to learn how to get set up with a free test WordPress website](https://www.meetup.com/learn-wordpress-online-workshops/events/289674776/).
You can follow the [written instructions on this website](https://adventuresinwpland.com/2023/04/14/setting-up-a-free-wordpress-playground/).
You can join us at this time without a test website, use the instructions above, and then [watch the recording on WordPress.tv](https://wordpress.tv/category/learn-wordpress-online-workshops/) as you test it out later on your own time.
We look forward to seeing you there!

Audience: Users
Level: Beginner
Language: English (Closed captioning provided)
Where? Zoom link available after signup.
- Target Audience: Users / Beginners
- Date: April 21, 2023 at 1530 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/293006021/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by wparasae** [comment]
Hi there, this workshop is ready to review.

I tried to keep it as simple as possible, and make sure to speak slowly + add pauses per the feedback from the most recent feedback we received in the training team channel during our meeting. 

Please click this link to review:

https://drive.google.com/file/d/1G6FYLvNq7TF-PkrSnv5MlTq9dC5go3Uy/view?usp=sharing

Specific feedback:

1. Is this slow and clear enough so that someone who didn't speak English as a first language would be able to follow?
2. Is the content accurate?
3. Any final thoughts?

**Comment by westnz** [comment]
Review:

Thank you, Sarah! Some thoughts...

1. I think the introduction 0 - 0:46 could be slightly faster :-) I think the pace works well for your demos. 
2. When you say let's learn 0:30, I would add a different slide with the words "Create a posts page and add a Query Loop block' to emphasise the strategy you will show in the tutorial.
3. 0:52 - 1:10 The silence may be too long. I suggest saying the words as you are clicking on the relevant button/action.
4. 1:24 I think adding a sentence about the function of the Query Loop block could be helpful. Something like... "The Query loop is used to display all your blog posts or other post types."
5. 2:34/35 + 2:40 The sound cuts out
6. 4:14/15 Can you add an arrow or annotation to draw your eye to the news menu item?
7. 4:15 - 20 The left side of the page looks like it is cut off.
8. 4:21 - 4:50 This section was a bit unclear to me. An idea: Could you re-record 4:21 - 4:25 and show step by step how you are creating a new post and how to add the Post featured image. Then you can show the front end of your News page and then click on the post you have created to show how it appears. 
9. 5:09 Could you add an annotation to point out 'Publishing'?

Well done!  I hope the feedback is helpful

**Comment by westnz** [comment]
Hey @wparasae I think the review should've happened in this Issue 😄 https://github.com/WordPress/Learn/issues/1506

I only realised now that this is the Issue for the Online Workshop and not the Tutorial.

**Comment by wparasae** [comment]
Edits made - remaining ones for future reference: 

4:15 - 20 The left side of the page looks like it is cut off.

4:21 - 4:50 This section was a bit unclear to me. An idea: Could you re-record 4:21 - 4:25 and show step by step how you are creating a new post and how to add the Post featured image. Then you can show the front end of your News page and then click on the post you have created to show how it appears.

5:09 Could you add an annotation to point out 'Publishing'?
