### ISSUE TITLE
Meeting Agenda April 25, 2023

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1509]
This week’s meeting will be held in EMEA/Americas timezone on Tuesday, April 25th, 2023, at 16:00 UTC, and @webtechpooja will be hosting.

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- April 25th – need volunteer
- May 2nd – need volunteer
- May 9th – [@faguni22](https://profiles.wordpress.org/faguni22/)
- May 16th – need volunteer

**2. Looking for feedback**

- [Proposal: Creating Learning Pathways for Learn WordPress](https://make.wordpress.org/training/2023/04/05/proposal-creating-learning-pathways-for-learn-wordpress/) (feedback by May 1)
- #1487 
- Should sharing presentation slides be a requirement for Online Workshop presenters? ([Slack thread](https://wordpress.slack.com/archives/C02RW657Q/p1681778344180559))
- Repurposing https://github.com/wptrainingteam to house all educational code examples for the WordPress community. ([more info](https://github.com/WordPress/Learn/issues/1509#issuecomment-1518985453))
- #830 
   - Many comments have been added so far. For the moment, we're looking for thoughts on the [two questions written out in this comment](https://github.com/WordPress/Learn/issues/830#issuecomment-1521384897).

**3. Looking for volunteers**

- WordPress Community Summit 2023 - Leadership is looking especially for newer contributors to join, who can bring fresh perspective to the WordPress project. If you are even a little interested in joining, please [apply to attend](https://communitysummit.wordcamp.org/2023/application/).

**4. Other news**

- We've published a new handbook page that details each of the Faculty roles: [Faculty Role Guides](https://make.wordpress.org/training/handbook/faculty-program/faculty-role-guide/)
- [Building Blocks: The Evolution of WordPress 2013-2023](https://make.wordpress.org/project/2023/04/13/wordpress-at-20-in-print/) - Provide feedback via GitHub with first-look access to the upcoming WP20 Book.
- The marketing team is looking for blogging prompts for the 20th anniversary. ([Slack thread with more details](https://wordpress.slack.com/archives/C02RW657Q/p1682034444419289))
- [Cultivating More Effective Contributing on Contributor Days](https://make.wordpress.org/community/2023/04/19/cultivating-more-effective-contributing-on-contributor-days/)

## 3. Content published in the last week

- **Tutorials**
  - [Developing with user roles and capabilities](https://learn.wordpress.org/tutorial/developing-with-user-roles-and-capabilities/)
  - [વર્ડપ્રેસ ડેશબોર્ડને જાણવું](https://learn.wordpress.org/tutorial/gu-getting-to-know-the-wordpress-dashboard/) - Gujarati
- **Lesson Plans**
  - [செருகுநிரல்களைத் தேர்ந்தெடுத்து நிறுவுதல்](https://learn.wordpress.org/lesson-plan/ta-choosing-and-installing-plugins/) - Tamil

## 4. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

- **Tutorials**
  - [Tutorial - WordPress editor modes for streamlining content creation](https://github.com/WordPress/Learn/issues/1440)
  - [Using Page Templates - Tutorial](https://github.com/WordPress/Learn/issues/455)
  - [Tutorial - The WordPress request lifecycle](https://github.com/WordPress/Learn/issues/1454)
  - [Tutorial - Building a page with only patterns](https://github.com/WordPress/Learn/issues/1489)
  - [Tutorial - Introduction to WordPress Multisite](https://github.com/WordPress/Learn/issues/1497)
  - [Tutorial - Managing a WordPress Multisite Network](https://github.com/WordPress/Learn/issues/1501)
  - [Rapid website recreation video re-edit](https://github.com/WordPress/Learn/issues/1515)
- **Lesson Plans**
  - [CSS Flexbox - Lesson Plan](https://github.com/WordPress/Learn/issues/713)
  - [WordPress Action Hooks - Lesson Plan](https://github.com/WordPress/Learn/issues/806)
- **Translated Content**
  - [Spanish translation for Lesson Plan "Managing Comments"](https://github.com/WordPress/Learn/issues/1133)
  - [Khmer translation for Lesson Plan "Dashboard Overview"](https://github.com/WordPress/Learn/issues/1357)
  - [French translation for Tutorial "Getting to know the WordPress Dashboard"](https://github.com/WordPress/Learn/issues/1438)

## 5. Project updates

- [Content Localization Foundation](https://make.wordpress.org/training/2022/11/07/project-thread-content-localization-foundations/) – [@bsanevans](https://profiles.wordpress.org/bsanevans/) - wrapping up on April 30
  - See most recent update: [April 24th update](https://make.wordpress.org/training/2022/11/07/project-thread-content-localization-foundations/#comment-3833)
- [Individual Learning Survey for the Needs Analysis](https://make.wordpress.org/training/2023/01/16/project-thread-learning-needs-analysis/) – [@west7](https://profiles.wordpress.org/west7/)
- [Developments and Customizations for Training and Learn Website](https://make.wordpress.org/training/2023/04/18/developments-and-customizations-for-training-and-learn-website/) - [@amitpatelmd](https://profiles.wordpress.org/amitpatelmd/)

## 6. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kaitohm** [comment]
The following will be updated closer to the meeting.
* 2-3 Looking for volunteers
* 3 Content published in the last week
* 4 Open requests for review

**Comment by jonathanbossenger** [comment]
**Discussion item: repurposing https://github.com/wptrainingteam to house all educational code examples for the WordPress community.**

As many of you may know, the [WordPress Developer Blog](https://developer.wordpress.org/news/) was officially launched recently, spearheaded by @bph. Many of those articles contain links to code example repositories, usually in the author's GitHub account.

I, and other developer educators in the team, also create code example repositories for our workshops, tutorials, and courses for Learn WordPress, also hosted on our own accounts.

Birgit and I got to chatting about having an official WordPress place to host these code examples, and after asking around a bit, @josephahaden suggested it might be useful to repurpose the wptrainingteam organization, renaming it to something like learn-wordpress.

So we'd like to find out what the training team thinks of this idea. As far as I know that GitHub organization isn't actively used anymore, so repurposing it as the official place for example code for all Learning related content for WordPress makes sense.

**Comment by kaitohm** [comment]
I've updated the content ✅

**Comment by webtechpooja** [comment]
@nomad-skateboarding-dev
To make note-taking a little easier, here's a link to the Slack thread the meeting started at: 
https://wordpress.slack.com/archives/C02RW657Q/p1682438442710029

**Comment by webtechpooja** [comment]
Here is the recap notes: https://make.wordpress.org/training/2023/05/04/training-team-meeting-recap-for-april-25th-2023/
