### ISSUE TITLE
Online Workshop - Developing for multisite

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1512]
# Event Details
- Title: Let's code: developing for multisite
- Description: When developing plugins or themes there are certain considerations one needs to make if you want to make sure your plugin or theme supports multsite. In this session, we'll cover those considerations, look at some specific multisite APIs, and convert an existing plugin to support multsite. 
- Target Audience: Developers
- Date: 2023-05-04 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/293145629/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
Livestream: https://www.meetup.com/learn-wordpress-online-workshops/events/293045334/

**Comment by jonathanbossenger** [comment]
Prep notes https://stackoverflow.com/questions/13960514/how-to-adapt-my-plugin-to-multisite/

**Comment by jonathanbossenger** [comment]
## Some multisite development notes/useful functions:

1. When registering a Multisite network with a subdirectory install, the main site has the suffix `blog`: https://wordpress.org/documentation/article/multisite-network-administration/#permalinks-in-subfolder-installs
1. get_current_blog_id
2. switch_to_blog
3. restore_current_blog

Task: Adapt the WP Learn Plugin Security plugin for a multisite install.
Task: Make a change to the wp-admin on a per site basis
Task: Create a child theme that can be used on multiple subsites.

**Comment by jonathanbossenger** [comment]
Task: Adapt the WP Learn Plugin Security plugin for a multisite install.

https://github.com/jonathanbossenger/wp-learn-plugin-security/releases/download/1.0.3/wp-learn-plugin-security.1.0.3.zip

Step 1: Update the activation hook so that it installs the table for each site on the network.

Before:

```
register_activation_hook( __FILE__, 'wp_learn_setup_table' );
function wp_learn_setup_table() {
	global $wpdb;
	$table_name = $wpdb->prefix . 'form_submissions';

	$sql = "CREATE TABLE $table_name (
	  id mediumint(9) NOT NULL AUTO_INCREMENT,
	  name varchar (100) NOT NULL,
	  email varchar (100) NOT NULL,
	  PRIMARY KEY  (id)
	)";

	require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
	dbDelta( $sql );
}
```

After: 

```
register_activation_hook( __FILE__, 'wp_learn_setup_table' );
function wp_learn_setup_table( $network_wide ) {
	if ( is_multisite() && $network_wide ) {
		$sites = get_sites();
		foreach ( $sites as $site ) {
			switch_to_blog( $site->blog_id );
			wp_learn_create_table();
			restore_current_blog();
		}
	} else {
		wp_learn_create_table();
	}
}

function wp_learn_create_table(){
	global $wpdb;
	$table_name = $wpdb->prefix . 'form_submissions';

	$sql = "CREATE TABLE $table_name (
	  id mediumint(9) NOT NULL AUTO_INCREMENT,
	  name varchar (100) NOT NULL,
	  email varchar (100) NOT NULL,
	  PRIMARY KEY  (id)
	)";

	require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );
	dbDelta( $sql );
}
```

- [switch_to_blog](https://developer.wordpress.org/reference/functions/switch_to_blog/)
- [restore_current_blog](https://developer.wordpress.org/reference/functions/restore_current_blog/)

**Comment by jonathanbossenger** [comment]
Task: Adapt the WP Learn Plugin Security plugin for a multisite install.

Step 2: Ensure the data is being inserted into the right table

- because we're using $wpdb->prefix, the WordPress database object will determine the correct prefix, and submit the data to the right table. However, this is why we should create the correct tables for the content
- Note that the redirection worked as well, WordPress will work with the current site URL and the page slugs
- Note that the admin menu also works, because we're using the correct wpdb->prefix

**Comment by jonathanbossenger** [comment]
Task: Create a child theme that can be used on multiple subsites.

Create a child theme, that loads a different stylesheet on a per-subsite basis.

- [get_current_blog_id](https://developer.wordpress.org/reference/functions/get_current_blog_id/)

**Comment by Thelmachido** [comment]
I can co-host

**Comment by jonathanbossenger** [comment]
Thanks @Thelmachido

**Comment by jonathanbossenger** [comment]
Additional notes

Network: true in the plugin header

**Comment by Thelmachido** [comment]
The learning session had 19 participants excluding the Host and Co-Host

**Comment by jonathanbossenger** [comment]
Slides: https://www.slideshare.net/psykro/developing-for-multisite

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/05/05/developing-for-multisite/

**Comment by LittleBigThing** [comment]
Hi @jonathanbossenger,

First of all, thanks for the great workshops, really helpful! :-)

You've mentioned planning to contribute to the plugin handbook, for example, for a page specific about developing for multisite. I think it's a great idea. I love to use multisite a lot, and because/although I'm not that experienced with it, I'd be glad to assist if I can to help with that.

Cheers,
Csaba

**Comment by jonathanbossenger** [comment]
Hey @LittleBigThing, you're more than welcome to get started. The most straightforward way would be to join [the docs team](https://make.wordpress.org/docs/) in their [Slack channel](https://app.slack.com/client/T024MFP4J/C02RP4WU5/) and start a conversation there.
