### ISSUE TITLE
French translation for Lesson Plan - "Setting A Static Page As Your Homepage"

### ISSUE THREAD

**Issue by 83kryss** [WordPress/Learn#1514]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/setting-a-static-page-as-your-homepage/
- Link to original content GitHub issue: 
- Language you'll be translating to: French
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: débutante, premier essai

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by jennydupuy** [comment]
I will do the proofreading (pseudo wp.org: jdy68)

**Comment by jennydupuy** [comment]
I finished the proofreading and the content is ok.
Could you create a new article for this content translated into French? I could then put the translation there.
Will it be possible to put screenshots in French?
Thanks.

**Comment by kaitohm** [comment]
Thanks for working on this. The French document is here: https://learn.wordpress.org/wp-admin/post.php?post=37246&action=edit

Yes, please replace screenshots with French versions, too. Let me know when this is ready to publish 🙇

**Comment by jennydupuy** [comment]
Hi,
French content has been integrated except for the screenshots.
I can't access the media library to choose the uploaded image (the name of file uploaded is: ecran-reglages-lecture-defaut.png).
Could you help me for that?

**Comment by kaitohm** [comment]
Oh, no access to Media Library... I wasn't aware of that, so thanks for letting me know. We'll need to figure a way around that...

I've searched the Media Library, but I'm not finding an image with that name. Could you upload the image to GitHub here? I'll then replace the image, and publish the content.

**Comment by jennydupuy** [comment]
Hi,
There are four images in total in the order:
![ecran-reglages-lecture-defaut](https://user-images.githubusercontent.com/75045144/236622356-ec868f90-6750-4860-be40-4aba93310037.png)
![page-accueil-derniers-articles](https://user-images.githubusercontent.com/75045144/236622362-13f5f50f-1703-48d3-8fc9-3197da308abd.png)
![ecran-reglages-lecture-page-statique](https://user-images.githubusercontent.com/75045144/236622364-cc73b397-6f7b-4de7-8c78-b54beb72b064.png)
![page-accueil-statique](https://user-images.githubusercontent.com/75045144/236622374-b5d34658-15f6-466b-bdbf-1357e59f60a1.png)
Thanks

**Comment by kaitohm** [comment]
Thank you! This is now published: https://learn.wordpress.org/lesson-plan/fr-setting-a-static-page-as-your-homepage/

**Comment by jennydupuy** [comment]
Thanks @bsanevans.
