### ISSUE TITLE
Rapid website recreation video re-edit

### ISSUE THREAD

**Issue by jamiemarsland** [WordPress/Learn#1515]
# Topic Description
The rapid website recreation video has now been edited with a different ending, here's the link https://vimeo.com/818643828

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [ ] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [ ] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
Looks good to me.

**Comment by jonathanbossenger** [comment]
@bsanevans Given that this video was already [reviewed by multiple folks elsewhere](https://github.com/WordPress/Learn/issues/1439), are you happy for us to go ahead and get this uploaded and published?

**Comment by kaitohm** [comment]
Sure! 👍

**Comment by jonathanbossenger** [comment]
@jamiemarsland if you haven't already, could I ask you to complete the Tutorial Presenter Application [here](https://learn.wordpress.org/tutorial-presenter-application/)? (If you have already done this, please just let me know here, and I'll pick it up.)

**Comment by jamiemarsland** [comment]
tks @jonathanbossenger - just submitted 👍

**Comment by kaitohm** [comment]
@jamiemarsland has been vetted, and this content is ready to be published: @westnz

**Comment by westnz** [comment]
Hi @jamiemarsland 

Step 1 is complete. Your video has been published. 🥳 Here is the wptv link: https://wordpress.tv/2023/04/27/rapid-website-recreation/

You can now go ahead with the subtitles and create a tutorial post.  Here are the steps Jonathan has probably already shared: https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/

We also suggest proofreading the transcript before exporting for subtitles and adding it to the post. 

I am also attaching an example of what it will look like once the tutorial is live: https://learn.wordpress.org/tutorial/developing-with-user-roles-and-capabilities/

Please let us know if you have any questions.

**Comment by westnz** [comment]
Great work!

Published: https://learn.wordpress.org/tutorial/rapid-website-recreation/
