### ISSUE TITLE
Learn WordPress Content Feedback - color attribute error in course code

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1518]
# Feedback Details
- Content title: Develop Your First Low-Code Block Theme
- Content URL: https://learn.wordpress.org/course/develop-your-first-low-code-block-theme/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: error

**Write a description of your feedback here:**

When I use the code at the end of the page I get several warnings/errors that the color attribute is missing above the slugs.

_This feedback was originally submitted in ticket 157368._

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by ironnysh** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? No: 
- What should happen next to apply the feedback?: 

Not sure to which code snippet on which lesson this is referring:
> When I use the code at the end of the page I get several warnings/errors that the color attribute is missing above the slugs.

**Comment by kaitohm** [comment]
Thanks. I'll close this, as we don't have enough information.
