### ISSUE TITLE
Online Workshop - Creating a custom template in the Site Editor

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1521]
# Event Details
- Title: Creating a custom template
- Description: creating a custom template for a landing page, different blog pages etc in the Site Editor
- Target Audience: Users 
- Date: 9 May 10am NZST
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/293138672/?isFirstPublish=true
- Co-host: Lada7402
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by ghost** [comment]
Be happy to co-host

**Comment by westnz** [comment]
Great, thank you Laura

**Comment by westnz** [comment]
Recording: https://wordpress.tv/2023/05/08/creating-a-custom-template-in-the-site-editor/
