### ISSUE TITLE
Learn WordPress Content Feedback -

### ISSUE THREAD

**Issue by regmidt** [WordPress/Learn#1522]
# Feedback Details
- Content title:
- Content URL:
- Are you reporting an error (such as outdated information), or providing improvement ideas?:

Write a description of your feedback here:

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by webtechpooja** [comment]
@regmidt,
 It seems like you haven't submitted any content feedback on this issue. Could you please explain what error you wanted to add here?
