### ISSUE TITLE
Meeting Agenda May 2, 2023

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1526]
This week’s meeting will be held in APAC timezone on Tuesday, May 2, 2023, at 07:00 UTC, and @bsanevans will be hosting.

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- May 2 – [@jonathanbossenger](https://profiles.wordpress.org/psykro)  
- May 9 – [@faguni22](https://profiles.wordpress.org/faguni22/)
- May 16 – Need Volunteer
- May 23 – Need Volunteer

**2. Looking for feedback**

- https://github.com/WordPress/Learn/issues/1487
    - Should sharing presentation slides be a requirement for Online Workshop presenters? ([Slack thread](https://wordpress.slack.com/archives/C02RW657Q/p1681778344180559))
- Repurposing https://github.com/wptrainingteam to house all educational code examples for the WordPress community. ([More Info](https://github.com/WordPress/Learn/issues/1509#issuecomment-1518985453))
- https://github.com/WordPress/Learn/issues/830
    - Many comments have been added so far. For the moment, we're looking for thoughts on the [two questions written out in this comment](https://github.com/WordPress/Learn/issues/830#issuecomment-1521384897)
- #1532 

**3. Looking for volunteers**

- WordPress Community Summit 2023 - Leadership is looking especially for newer contributors to join, who can bring fresh perspective to the WordPress project. If you are even a little interested in joining, please [apply to attend](https://communitysummit.wordcamp.org/2023/application/).

**4. Other news**

- [@bsanevans](https://profiles.wordpress.org/bsanevans/) merged 6.1 and 6.2 issues to create a “Recent releases” view in the content development GitHub project board: https://github.com/orgs/WordPress/projects/33/views/10
- We've published a new handbook page that details each of the Faculty roles: [Faculty Role Guides](https://make.wordpress.org/training/handbook/faculty-program/faculty-role-guide/)
- Let's remember to speak slowly and insert pauses when publishing video content. (Raised by Gudrun in [this Slack message](https://wordpress.slack.com/archives/C02RW657Q/p1682784167569539).)

## 3. Content published in the last week

- **Tutorials**
  - [Rapid Website Recreation | Learn WordPress](https://learn.wordpress.org/tutorial/rapid-website-recreation/)
  - [Importing widget areas from a classic theme to a block theme](https://learn.wordpress.org/tutorial/importing-widget-areas-from-a-classic-theme-to-a-block-theme/)
  - [Se familiariser avec le tableau de bord de WordPress](https://learn.wordpress.org/tutorial/fr-getting-to-know-the-wordpress-dashboard/)
  - [Importing widget areas from a classic theme to a block theme](https://learn.wordpress.org/tutorial/importing-widget-areas-from-a-classic-theme-to-a-block-theme/)
  - [Custom post types and capabilities](https://learn.wordpress.org/tutorial/custom-post-types-and-capabilities/)

## 4. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

- **Tutorials**
  - https://github.com/WordPress/Learn/issues/1440
  - https://github.com/WordPress/Learn/issues/455
  - https://github.com/WordPress/Learn/issues/1454
  - https://github.com/WordPress/Learn/issues/1489
  - https://github.com/WordPress/Learn/issues/1497
  -  https://github.com/WordPress/Learn/issues/1501
- **Lesson Plans**
  - https://github.com/WordPress/Learn/issues/713
  - https://github.com/WordPress/Learn/issues/806
- **Course** [Creating a 4 page business website with a block theme](https://github.com/WordPress/Learn/issues/1407)
  - https://github.com/WordPress/Learn/issues/1407#issuecomment-1528164034
- **Translated Content**
  - https://github.com/WordPress/Learn/issues/1133
  - https://github.com/WordPress/Learn/issues/1357
  - https://github.com/WordPress/Learn/issues/1529
  - https://github.com/WordPress/Learn/issues/1528 (Tutorial)

## 5. Project updates

- [Content Localization Foundation](https://make.wordpress.org/training/2022/11/07/project-thread-content-localization-foundations/) – [@bsanevans](https://profiles.wordpress.org/bsanevans/)
    - This is now completed!! 🎉 Please see [Recap: Content Localization Foundations Project](https://make.wordpress.org/training/2023/05/01/recap-content-localization-foundations-project/)
- [Individual Learning Survey for the Needs Analysis](https://make.wordpress.org/training/2023/01/16/project-thread-learning-needs-analysis/) – [@west7](https://profiles.wordpress.org/west7/)
- [Developments and Customizations for Training and Learn Website](https://make.wordpress.org/training/2023/04/18/developments-and-customizations-for-training-and-learn-website/) - [@amitpatelmd](https://profiles.wordpress.org/amitpatelmd/)

## 6. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

## 7. Faculty Members' May check-in

(This is a new idea we're testing. Slack message to follow.) If you're a Faculty Member, please thread an update here about something you're working on, an idea you had, or any other insight you have for the team. If you're not a Faculty member, then feel free to follow this message so that you can be notified of updates Faculty Members will post here.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by webtechpooja** [comment]
The following will be updated closer to the meeting.
- 3 Content published in the last week
- 4 Open requests for review

Please do comment on any other topic you want to discuss in the agenda.

**Comment by webtechpooja** [comment]
I have updated the content published and need to be reviewed section!

**Comment by kaitohm** [comment]
@jonathanbossenger To make note-taking a little easier, here's a link to the Slack thread the meeting started at: https://wordpress.slack.com/archives/C02RW657Q/p1683010835749439

**Comment by jonathanbossenger** [comment]
Preview link: https://make.wordpress.org/training/?p=25558&preview=1&_ppp=0596b5ba0d

**Comment by jonathanbossenger** [comment]
The meeting recap has been posted, thanks everyone for their help in getting it done https://make.wordpress.org/training/2023/05/09/training-team-meeting-recap-for-may-2nd-2023/
