### ISSUE TITLE
French translation for Tutorial "Choosing and Installing a Plugin"

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Learn#1530]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/searching-and-installing-a-plugin/
- Link to original content GitHub issue: none
- Language you'll be translating to: french
- Have you arranged for someone to review this translation?: No 
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
@jennydupuy I've created a draft post for you to add the French to: https://learn.wordpress.org/wp-admin/post.php?post=37117&action=edit

**Comment by jennydupuy** [comment]
Here is the translation corresponding to the content of the tutorial page:
[Choosing and installing a plugin.zip](https://github.com/WordPress/Learn/files/11380836/Choosing.and.installing.a.plugin.zip)

**Comment by beryl-dlg** [comment]
@jennydupuy ok for reviewing your translation "Choosing and Installing a Plugin". Thanks.

**Comment by beryl-dlg** [comment]
Hello @jennydupuy here the reviewed file with comments. 
[content-proposition-relecture.txt](https://github.com/WordPress/Learn/files/11415263/content-proposition-relecture.txt)

**Comment by jennydupuy** [comment]
Hi, @bsanevans 
The reviewer (@beryl-dlg ) is ok
I submitted the subtitle file on wordpress.tv and translated the post on learn.wordpress.org.
You can publish whenever you want!
Thanks.

**Comment by kaitohm** [comment]
This has been published. Thanks you for your contributions! 🎉 
https://learn.wordpress.org/tutorial/fr-searching-and-installing-a-plugin/

**Comment by jennydupuy** [comment]
Thanks @bsanevans
