### ISSUE TITLE
Online Workshop - Demystifying the Navigation Block

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Learn#1531]
# Event Details
- Title: Demystifying The Navigation Block: How To Set Up Your Site's Navigation Now And In The Future
- Description: The navigation block is one of the most complex and confusing blocks to work with using the Gutenberg block editor.
But it doesn't have to be.
This presentation will show you how to set your site's navigation using only blocks and not the classic menu system. We'll also have a look at what's coming including a sneak peek at mega menus (if available).
- Target Audience:  Users, Intermediate
- Date: July 11, 2023 at 3pm EDT
- Meetup.com event link:https://www.meetup.com/learn-wordpress-online-workshops/events/294340444/
- Co-host: @courtney-pk 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I registered in Meetup for the July 11 workshop but no Zoom link is provided.

**Comment by courtney-pk** [comment]
[Recording with captions and presentation slides uploaded to WordPress.TV.](https://wordpress.tv/2023/07/12/demystifying-the-navigation-block-how-to-set-up-your-sites-navigation-now-and-in-the-future/)
