### ISSUE TITLE
Discussion - adding publication date to content

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1532]
We received feedback in ticket 158021 asking why we don't show publication dates on content, such as https://learn.wordpress.org/tutorial/creating-a-front-page-for-a-block-theme/ Showing a publication date may help learners identify new/fresh content easier.

I'm not sure if this is an intentional decision the team made at some point, so wanted to open the idea up for discussion.

What pros/cons do folks see with adding publication dates to content?

**Comment by ghost** [comment]
I agree that there should be a publication date so that you can filter current materials. When we look at a theme or plugin we look for when it was last updated. With WordPress continuing to update and evolve it is important to document materials chronologically.

**Comment by kaitohm** [comment]
I see no reason why we _shouldn't_ add publication dates. If we add a publication date, I think we should also show the date it was recently updated, too.

**Comment by webtechpooja** [comment]
I agree with your point. We can have two dates — one Original Publication date and another one recently updated, with version detail. That version will show the content is updated till which version.

**Comment by kaitohm** [comment]
Thank you for input! I've opened a feature request for developers to triage and work on in #1570 . In that issue, I've suggested where to add the dates. But if you have other ideas, feel free to leave those in that issue, too.
