### ISSUE TITLE
Report typographical error

### ISSUE THREAD

**Issue by Olein-jp** [WordPress/Learn#1536]
# Feedback Details
- Content title: Develop Your First Low-Code Block Theme
- Content URL: https://learn.wordpress.org/lesson/different-types-of-themes-overview/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: No, just typo.

Write a description of your feedback here:
> Yes! It’s possible to create or use themes that have some elements of both the block editor and the classic customer. These themes are called “Hybrid” and “Classic” themes, which are much more advanced topics than this course will cover.

I think `"Classic"` is not correct, and need to replace `"Universal"`.

Because after this you will find explanations of the Hybrid theme and the Universal theme.

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by jonathanbossenger** [comment]
Hi @Olein-jp, thanks for submitting this issue.

At the present moment, the official project terms for themes built using PHP and associated PHP templating functions are [classic themes](https://developer.wordpress.org/themes/classic-themes/), while themes built using blocks and markup are [block themes](https://developer.wordpress.org/themes/block-themes/). 

For any Learn WordPress content, we are required to official project terminology, and therefore we follow what these types of themes are called by the WordPress project. If the project decides to rename classic themes, then we will follow that decision.
