### ISSUE TITLE
Enhancement Idea: consider supporting presenter bios on Lesson Plans.

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1542]
At the moment, tutorials on Learn WordPress have a Presenters meta box, which allows the tutorial to be linked to the person who presented it.

When entered, their bio is included at the bottom of the tutorial and pulls data from the user's WordPress.org profile.

Lesson plans, on the other hand, do not include this bio. 

However, creating a Lesson plan can be a lot of work, especially if it's a translation.

Therefore I would like to suggest that we consider adding the same Presenter meta box and associated functionality to Lesson Plans so that the creator of the Lesson plan can be correctly attributed.

**Comment by kaitohm** [comment]
As a similar idea, a "Props Block" was recently suggested for Make blogs. The same block could be used on Learn, too: https://meta.trac.wordpress.org/ticket/6945

**Comment by jonathanbossenger** [comment]
I like the idea of the props block, as this would give the tutorial or lesson plan author the ability to thank anyone who helped with the process (reviews etc). Combining that with support for the Presenter field on Lesson plans would be a great addition.

**Comment by jonathanbossenger** [comment]
Closing in favour of the work being done for the new Learn site redesign and the Learning Pathways
