### ISSUE TITLE
"uneducated"

### ISSUE THREAD

**Issue by dkett214** [WordPress/Learn#1547]
Details, Some of us, or maybe just myself are having a very hard time understanding what the point of this coding/ git/ GitHub are. ill be honest, i have no clue, and furthermore how it is important for my entity.  This is no way taking bad about this club or environment  of humans.  I am simply trying to find my role in the evolution of technology.  [[[Removed email address]]]

---

- Topic title: 
- Topic description: 
- Objective: 
- Content type: 
- WordPress version: 
- Will you be creating this content?: Yes/No

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Triage Checklist
Please follow this [Vetting content topic ideas handbook page]() guide.

- [ ] SME assigned
- [ ] Remove Needs Subject Matter Expert label
- [ ] Content Category applied (Ex. PHP, Gutenberg, Block Theme)
- [ ] Topic idea has passed vetting checks
- [ ] Content type label applied
- [ ] Priority set
- [ ] Content Type Checklist applied
- [ ] Content type
- [ ] Audience set
- [ ] Experience Level set
- [ ] Product type (theme, plugin)
- [ ] WordPress Version applied through Milestone (Ex. milestone 5.9)
- [ ] If the Topic Idea reporter has not opted to create the content, apply Needs Content Creator label
- [ ] Ticket moved to Ready to Create

**Comment by dkett214** [comment]
@bsanevans , closed this? Wrong location to ask for help?

**Comment by kaitohm** [comment]
Hi @dkett214 ! This repository is for the WordPress Training Team to create content about WordPress. People can also submit feedback about the content on https://learn.wordpress.org/.

I interpreted your question to be about GitHub and coding in general. If that is so, then it is outside the scope of what this team works on. Reaching out to GitHub support asking for resources would be a good next step.

If I misunderstood your question, then feel free to add more context here. Thanks 🙂
