### ISSUE TITLE
Tutorial - Using the block editor: tips and shortcuts for efficiency

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1548]
# Topic Description
Block editor tips and shortcuts

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/237003279-d5e324c3-cd7a-4879-9964-230888b63978.mp4

**Comment by meaganhanes** [comment]
I've just realized all of our video tutorials presume we're on Desktop instead of Mobile...

**Comment by meaganhanes** [comment]
May I ask where we are in the checklist in this issue's description @westnz? I'm not seeing any items checked off yet.

**Comment by westnz** [comment]
Hey @meaganhanes. Yes, most of our video tutorials are focused on Desktop. There is definitely scope for more tutorials about using mobile.
FYI, I have been working for Mark-Andrew, and he has run two great Online Workshops about designing on mobile:
[How to create a website on mobile (Part 1)](https://wordpress.tv/2023/03/09/how-to-create-a-website-on-mobile-part-1/)
[How to create a website on mobile (Part 2)](https://wordpress.tv/2023/04/04/how-to-create-a-website-on-mobile-part-2/)

Thanks for the reminder to update the checklist.

**Comment by naomi060397** [comment]
Definitely some helpful tips, nice. Some of my feedback is: 

- In the text of your title cards at the start of each section, the letter spacing makes it kind of hard to read. 
- In the Drag and Drop section, you could also cover that you can drag blocks around with the: 
![Screenshot 2023-05-18 at 4 08 09 PM](https://github.com/WordPress/Learn/assets/94168410/db58393f-0c6a-49c9-845a-509c12c9f07a)

**Comment by westnz** [comment]
Thank you for the feedback @naomi060397

**Comment by quitevisible** [comment]
This is a great reference tutorial @westnz . Very useful set of Block Editor Tips n Tricks for any user. Some thoughts…

- I agree with @naomi060397 about the letter spacing on the transition/title slides. 
- At almost 8:00m, it’s a little on the longer side for a tutorial. But not out of line for the subject matter. I thought maybe a table of contents (TOC) at the beginning of the video might help manage expectations upfront. Then include the corresponding number for each topic at the beginning of each new transition slide. 
- I think this might even help when people return to view certain sections of the tutorial for a refresher. They can easily scrub to the section they’re looking for.
- Lastly, the audio was off by default when I watched the video. Not sure if that’s a policy, but I had to restart the video since I missed the first part looking to turn on the audio.

Overall, great job!

**Comment by westnz** [comment]
Thank you for the suggestions @quitevisible 
PS: GitHub puts the sound of videos off by default

**Comment by quitevisible** [comment]
Ah ok. Ya - I’m finding that’s the case with audio off by default as I get into a few more videos here. Thx for clarification!

**Comment by askdesign** [comment]
Terrific compilation of tips and shortcuts, explained clearly and smoothly! Some feedback:
4:29 - "left click" - I am not familiar with this mouse action. Is there an equivalent, like CMMD-click or something?
4:56 - selecting a group of images and dragging them into the media library. While good to know, this isn't specifically a block feature, so I'm not sure if it should be included.

**Comment by westnz** [comment]
Thank you for the review @askdesign

**Comment by westnz** [comment]
Updates made. Thanks, everyone!

Published: https://learn.wordpress.org/tutorial/using-the-block-editor-tips-and-shortcuts-for-efficiency/

**Comment by ibexayala** [comment]
I very much needed this tutorial on how to change the amount of space between blocks! But now the user interface has changed and it says, "Looking for other block settings? They've moved to the styles tab." and I can't find the "styles tab" anywhere?  Can you help this newbie, self-taught website builder?

**Comment by westnz** [comment]
Hey @ibexayala 

For future inquiries of this nature, I recommend utilizing the Dotorg support forum: [[link].](https://wordpress.org/support/welcome/#asking-for-support.) Our use of GitHub primarily focuses on overseeing content creation and managing pertinent projects for the Training Team. 

Please note that the Styles tab is still located at the top right when you click on Settings. 
<img width="310" alt="image" src="https://github.com/WordPress/Learn/assets/89751452/a9cabaed-069e-4345-93fe-b910d0532693">
