### ISSUE TITLE
Tutorial - 7 Tips for improving website security

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1551]
# Topic Description
Practical steps to improve website security and protect your site from hackers. 

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/3240dc1e-ef44-47b2-8c05-52166085de9f

**Comment by digitalchild** [comment]
I would suggest Patchstack as another security plugin, as you mention it in the security focused blogs. Everything else, great.

**Comment by bhowe** [comment]
One point a lot of users (at least my clients have a problem with) two factors is some of these plugins offer too many options. It's great that (wp 2fa) offers email with OTP in the free version maybe some mention of that?

**Comment by westnz** [comment]
Thank you @bhowe

**Comment by askdesign** [comment]
Hi Wes, 
This is good topic and I think you narrowed it down to most of the key things to consider. Here are my thoughts:
2:29 - Do you want to mention the PHP version?
2:34 - Before updating themes and plugins, users should make sure they have backed up the site.
3:22 - I recently used All in One Security on a couple of sites and think it's great. Maybe you could mention that in addition to the others.

Other important things to mention, which may take you beyond "7" steps:
- use a reliable webhost
- usernames: never use "admin"
- install an SSL certificate
- use a SPAM detector

**Comment by westnz** [comment]
Thank you for the helpful feedback @askdesign

**Comment by a-newcomer** [comment]
Hi Wes,

Great tutorial, I especially admired the examples you gave for every point, they struck me as clear and straightforward for people new to WordPress. 
Some minor points - I might add a modifier to the title to let people know in the title what level the tutorial is for - "7 basic Tips...", "7 Easy Tips...", "7 First Tips" so beginners know it's for them - I know that the tutorial is labelled as beginner, but are those classes going to show up in search engine results outside of WordPress? The title will. Also, the final point you made, following security blogs, might be a useful tip for people who are a bit more advanced - I might switch that point out with the username reminder suggested by @askdesign.

**Comment by westnz** [comment]
Thank you very much @a-newcomer 😉

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/7-tips-to-improve-website-security/

**Comment by westnz** [comment]
Updated and added to the Beginner User learning pathway.
