### ISSUE TITLE
Learn WordPress Content Feedback - broken link

### ISSUE THREAD

**Issue by RockyKev** [WordPress/Learn#1558]
# Feedback Details
- Content title: Setting up your development environment
- Content URL: https://learn.wordpress.org/lesson/setting-up-your-development-environment/
- Are you reporting an error (such as outdated information), or providing improvement ideas?:

This link is broken

> [Getting started with JavaScript Build Setup](https://learn.wordpress.org/docs/how-to-guides/javascript/js-build-setup.md) first.

This is the correct link? https://developer.wordpress.org/block-editor/how-to-guides/javascript/js-build-setup/

---

# Feedback Report Checklist:
- [x] Feedback validated
- [x] Update proposed
- [x] Update reviewed
- [x] Update published

**Comment by jonathanbossenger** [comment]
@adamziel As the course content creator, could I ask you to check this, please?

**Comment by adamziel** [comment]
I just fixed it, thank you!

**Comment by jonathanbossenger** [comment]
Thank you @RockyKev for logging this issue, and @adamziel for fixing it so quickly.
