### ISSUE TITLE
Learn WordPress Content Feedback - Replace instruction with the link to the tutorial

### ISSUE THREAD

**Issue by Rahmon** [WordPress/Learn#1559]
# Feedback Details
- Content title: Primary Templates
- Content URL: https://learn.wordpress.org/lesson/recap-of-the-primary-templates/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: An error

Write a description of your feedback here:

There is an instruction in the content that says: `[Include this tutorial, once published https://github.com/WordPress/Learn/issues/1028]`

![image](https://github.com/WordPress/Learn/assets/6010232/fe4a3a78-7a1f-40f6-aa68-7efe78567515)

Since the tutorial is already published, this instruction can be replaced for https://learn.wordpress.org/tutorial/a-beginners-guide-to-the-wordpress-template-hierarchy/

Thanks for this course. Really helpful :pray: 

---

# Feedback Report Checklist:
- [x] Feedback validated
- [x] Update proposed
- [x] Update reviewed
- [x] Update published

**Comment by jonathanbossenger** [comment]
@Rahmon thank you for logging this, I have updated the lesson with the link to the tutorial.

I am glad you found the course helpful.
