### ISSUE TITLE
Online Workshop - Debugging in WordPress

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1563]
# Event Details
- Title: Debugging in WordPress
- Description: When developing WordPress plugins or themes, it's a good idea to have tools in place to help improve your code quality and debug your code in the case of errors. Enabling error logs, inspecting the values of variables during code execution, and looking at the database queries being run are all tools that developers can use to find and fix problems. In this workshop, we'll dive into some of the options built into WordPress that you have at your disposal, learn about various debugging plugins and their uses, as well as look at one or two third-party tools to consider.
- Target Audience: Developers
- Date: 2023-05-25 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/293657810/
- Co-host: @meaganhanes 
- Other info: Code is Poetry. Editing is a-ok! Let us observe how...

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by meaganhanes** [comment]
I'm available to co-host with you @jonathanbossenger. Feel free to assign as you see fit!

**Comment by jonathanbossenger** [comment]
Thanks, @meaganhanes, I've assigned you as co-host.

If you haven't read them already, there are [these great guidelines](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) you can read to prepare for co-hosting an online workshop.

However, every workshop presenter has different needs, so these are the most important things I need from a co-host:

- Once the workshop has started, and the recording is going, please admit any latecomers into the Zoom meeting
- Keep an eye on the chat, and let me know if I miss any important questions
- About halfway through, take a count of the total participants, as we need to report the attendee numbers afterward
- Listen out for any folks who have background noise coming through their mics, and please mute them. This doesn't happen often, but it can be distracting.

I will start the Zoom meeting about 5-10 minutes before, to let you in and make you co-host of the Zoom session.

Also, please let me know if you have any questions.

**Comment by meaganhanes** [comment]
Today's class was around 26-28 people consistently, with a mid-class high of 26. 🛬🌄

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/05/26/debugging-in-wordpress/

**Comment by meaganhanes** [comment]
Actually, I'm not credited as co-host @jonathanbossenger - thoughts?

**Comment by jonathanbossenger** [comment]
That's a good question and one I don't have the answer to. 

Since I joined the training team last year what I noticed on other online workshops is that folks who present the topics are usually given the speaker credit on [WordPress.tv](https://wordpress.tv/), so I've followed that. 

As the co-host role is generally an assistive role, and one specific to the online workshops that the training team presents, there's no co-host field when adding a video to WordPress.tv. 

Perhaps you'd like to bring this up as a question for the next training team meeting?

**Comment by jonathanbossenger** [comment]
Hi @meaganhanes just following up on this conversation, were you able to bring this question in in a training team meeting?

**Comment by jonathanbossenger** [comment]
I will raise this at the next training team meeting, which will be held the week after WCUS.

**Comment by kaitohm** [comment]
Was there a conclusion to this discussion, @jonathanbossenger ?

**Comment by jonathanbossenger** [comment]
I think I may have forgotten to raise this. I'm for closing this for now, and we can reopen it if needed.
