### ISSUE TITLE
Learn WordPress Content Feedback - potential package.json typo?

### ISSUE THREAD

**Issue by RockyKev** [WordPress/Learn#1564]
# Feedback Details
- Content title:  Setting up your development environment
- Content URL: https://learn.wordpress.org/lesson/setting-up-your-development-environment/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: Improvement Ideas

Write a description of your feedback here:

The package.json seems like a copy/paste from another project?

```json
{
    "name": "05-recipe-card-esnext",
    "version": "1.1.0",
    "private": true,
    "description": "Example: Recipe Card (ESNext).",
   // ... 
}
```

Proposal: 
```json
{
    "name": "my-first-gutenberg-app",
    "version": "1.0.0",
    "private": true,
    "description": "My first Gutenberg App.",
  // ...
}
```

---

# Feedback Report Checklist:
- [x] Feedback validated
- [x] Update proposed
- [x] Update reviewed
- [x] Update published

**Comment by devmuhib009** [comment]
@RockyKev nice catch. I am moving the issue to fixing stage. Thanks you. :wave:

**Comment by devmuhib009** [comment]
Just fixed the issue. Thanks for the suggestion.
