### ISSUE TITLE
Learn WordPress Content Feedback - Missing import statement in the final code

### ISSUE THREAD

**Issue by RockyKev** [WordPress/Learn#1566]
# Feedback Details
- Content title: Retrieving WordPress data records
- Content URL: https://learn.wordpress.org/lesson/retrieving-wordpress-data-records/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: missing import statement

Write a description of your feedback here:

Assuming the student will copy/paste this final code. If they try to run it, they'll run into a error.

![](https://i.imgur.com/R8ImhrS.png)

Proposed change:
```js
import { SearchControl, Spinner } from "@wordpress/components";
import { useState, render } from "@wordpress/element";
import { useSelect } from "@wordpress/data";
import { store as coreDataStore } from "@wordpress/core-data";
import { decodeEntities } from "@wordpress/html-entities";

```

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by ironnysh** [comment]
# Feedback Validation Checklist:
Can you confirm/reproduce the issue? **Yes**:

As @RockyKev mentions, the following is missing from the final code snippet that's provided at the bottom of [this page](https://learn.wordpress.org/lesson/retrieving-wordpress-data-records/#wiring-it-all-together):
```js
import { decodeEntities } from "@wordpress/html-entities";
```
This results in an error logged in the browser console (and in VS Code). See screenshots below:
<img width="673" alt="Screenshot 2024-06-07 at 14 50 07" src="https://github.com/WordPress/Learn/assets/63248335/2e409579-ea3e-455a-85ff-c2549bb976fe">
<img width="889" alt="Screenshot 2024-06-07 at 14 40 58" src="https://github.com/WordPress/Learn/assets/63248335/7bec0cf9-982e-4bc0-a615-cc6fa8d0d75d">

---

What should happen next to apply the feedback?: Add the missing `import` to the code sample.

**Comment by jonathanbossenger** [comment]
@ironnysh thanks, I've updated the final code snippet, could you please test and verify that it's not correct.

**Comment by ironnysh** [comment]
Yup, works as expected. Thanks, @jonathanbossenger.
