### ISSUE TITLE
Meeting Agenda May 23, 2023

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1567]
This week’s meeting will be held in EMEA/AMER timezone on Tuesday, May 23, 2023, at 16:00 UTC, and @webtechpooja will be hosting.

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- May 23 – Need Volunteer
- May 30 - Need Volunteer

**2. Looking for feedback**

- [Repurposing the wptrainingteam GH organisation](https://github.com/wptrainingteam/wptrainingteam.github.io/issues/66)- headed by @jonathanbossenger
- [Pathways to Learn WordPress](https://learn.wordpress.org/pathways-to-learn-wordpress/)

**3. Looking for volunteers**

- [Team Meeting Hosts](https://make.wordpress.org/training/handbook/training-team-how-to-guides/hosting-training-team-meetings/#hosting-team-meetings)
[Coffee Hour Hosts](https://make.wordpress.org/training/handbook/training-team-how-to-guides/hosting-training-team-meetings/#hosting-coffee-hours)

**4. Other news**

- [WordPress Community Team Discussion #9: The Next Generation of WordCamps](https://make.wordpress.org/community/2023/05/20/wordpress-community-team-discussion-9-the-next-generation-of-wordcamps/)
- [WordPress 6.3 Planning Roundup](https://make.wordpress.org/core/2023/05/18/wordpress-6-3-planning-roundup/)
- [WordPress Contributor Mentorship Program: Pilot Program Proposal](https://make.wordpress.org/project/2023/05/17/wordpress-contributor-mentorship-program-pilot-program-proposal/)
- [WordCamp Europe 2023 schedule](https://europe.wordcamp.org/2023/schedule/)
- [WordCamp EU Contributor Day ideas](https://make.wordpress.org/training/2023/05/09/brainstorm-wordcamp-europe-2023-contributor-day/)

## 3. Content published in the last week

- **Tutorials**
  - [How to add a blog or news page to any WordPress website](https://learn.wordpress.org/tutorial/how-to-add-a-blog-or-news-page-to-any-wordpress-website/)
  - [Introduction to WordPress Multisite Networks](https://learn.wordpress.org/tutorial/introduction-to-wordpress-multisite-networks/)
- **Courses**
  - [Creating a 4-Page Business Website](https://learn.wordpress.org/course/creating-a-4-page-business-website/)

## 4. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

- **Tutorials**
  - https://github.com/WordPress/Learn/issues/1502 
  - https://github.com/WordPress/Learn/issues/1501
  - https://github.com/WordPress/Learn/issues/806
  - https://github.com/WordPress/Learn/issues/455
- **Lesson Plans**
  - https://github.com/WordPress/Learn/issues/713
  - https://github.com/WordPress/Learn/issues/806
- **Translated Content**
  - https://github.com/WordPress/Learn/issues/1529 (Greek)
  - https://github.com/WordPress/Learn/issues/1528 (Greeek)
  - https://github.com/WordPress/Learn/issues/1527 (Greek)
  - https://github.com/WordPress/Learn/issues/1525(Greek)

## 5. Project updates
No active projects right now.

## 6. Open Discussions
WordPress 20th Birthday celebration.

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kaitohm** [comment]
@amitpatel0702 and I finally published the SEO Expert handbook page that Amit has been working on for a while. Could we mention this in today's meeting, please? 🙇‍♂️  ([Slack thread](https://wordpress.slack.com/archives/C02RW657Q/p1684831067303179))

**Comment by webtechpooja** [comment]
Here is the link to where the meeting has started!
https://wordpress.slack.com/archives/C02RW657Q/p1684857613753479 
@quitevisible I think this will help you to write recap notes. Thanks

**Comment by webtechpooja** [comment]
Here is the Recap notes: https://make.wordpress.org/training/2023/05/24/training-team-meeting-recap-for-may-23rd-2023/
