### ISSUE TITLE
Lesson Plans: Collecting feedback from users

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#157]
Training has https://make.wordpress.org/training/handbook/guidelines/instructor-testing-feedback/.  We have found super valuable insights from those that test (use) our materials in a live setting. https://wordpress.slack.com/archives/C02RW657Q/p1503430123000596

Let's house the feedback where the content lives.  Can we tuck this into buttons on the lesson plans and workshops and capture which lesson / workshop the feedback is for specifically?

**Comment by adamwoodnz** [comment]
Fixed as part of https://github.com/WordPress/Learn/issues/1860
