### ISSUE TITLE
Add publication and "last edit" dates to all content

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1570]
The team discussed the benefits of showing a publication date, and a "last edited" date, on all content on Learn. (Discussion in #1532 ) **I propose we add these dates to the sidebar of content.**

* Tutorials ([example content](https://learn.wordpress.org/tutorial/introduction-to-wordpress-multisite-networks/)): Below `Subtitles` and above `Print View`
* Lesson Plans ([example content](https://learn.wordpress.org/lesson-plan/how-to-add-and-remove-logo-and-site-icon-in-site-editor/)): Below `WordPress Version:`
* Courses ([example content](https://learn.wordpress.org/course/introduction-to-block-development-build-your-first-custom-block/)): Below `Average days to completion`

**Comment by jonathanbossenger** [comment]
@bsanevans During the dev-squad triage, it was decided to close this ticket in favor of #1464, and mark this as a duplicate. The main reason for this is that #1464 was reported first, and it has some suggested design choices, which we can iterate on.

Could I ask you to add your comments on that issue, which we'll track as the main issue for this feature enhancement?

**Comment by kaitohm** [comment]
Sure thing! ✅ Thanks for triaging.
