### ISSUE TITLE
Indonesian translation for Tutorials "Building a home page with a block theme"

### ISSUE THREAD

**Issue by ardianimaya** [WordPress/Learn#1572]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/building-a-home-page-with-a-block-theme/ 
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/788 
- Translator: @ardianimaya
- Language you'll be translating to: Indonesian
- Reviewer's GitHub username: @kharissulistiyo
- Other info: https://docs.google.com/document/d/188Vuf57OCdGAU7nXrNyfXUaadTbmECGMqnOWlp32cBI/edit#

**Comment by ardianimaya** [comment]
Translation completed https://docs.google.com/document/d/188Vuf57OCdGAU7nXrNyfXUaadTbmECGMqnOWlp32cBI/edit?pli=1

Currently reaching out to WP ID community to find a reviewer, will update here once I found one.

**Comment by kaitohm** [comment]
Hi @ardianimaya and @kharissulistiyo 👋  How is the progress of this content? Does it look like we'll be able to publish this by the end of the year? 🙂

**Comment by ardianimaya** [comment]
Tutorials and subtitle published https://learn.wordpress.org/tutorial/membuat-halaman-beranda-dengan-tema-blok/.
