### ISSUE TITLE
Japanese Online Workshop - Updates and Vulnerabilities

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1573]
# Event Details
- Title: アップデートと脆弱性 (English: Updates and Vulnerabilities)
- Description: This workshops looks at how to avoid vulnerabilities potentially introduced when updating WordPress core, by first testing an update on a local site.
- Target Audience: Japanese Users
- Date: June 21st
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/293710561/
- Host: @megane9988
- Co-host: @bsanevans 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by megane9988** [comment]
I will do my best!

**Comment by kaitohm** [comment]
Video uploaded to WordPress.tv: https://wordpress.tv/2023/06/23/%e3%82%a2%e3%83%83%e3%83%97%e3%83%87%e3%83%bc%e3%83%88%e3%81%a8%e8%84%86%e5%bc%b1%e6%80%a7/
