### ISSUE TITLE
Tutorial - Debugging in WordPress

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1574]
# Topic Description
When developing WordPress plugins or themes, it's a good idea to have tools in place to help improve your code quality and debug your code in the case of errors. Enabling error logs, inspecting the values of variables during code execution, and looking at the database queries being run are all tools that developers can use to find and fix problems. In this workshop, we'll dive into some of the options built into WordPress that you have at your disposal, learn about various debugging plugins and their uses, as well as look at one or two third-party tools to consider.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
WIP Script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/debugging-wordpress.md

Please leave any review feedback in the comments on this issue.

**Comment by jessecowens** [comment]
Learning Objectives
Upon completion of this lesson the participant will be able to:
- Describe how the 3 debug constants configure PHP to set error reporting, display errors, and define the log file.
- Use the error_log function to add information to the log file.
- Set the SAVEQUERIES constant and print the wpdb->queries array to the error log.
- Name and describe two popular plugins that assist with debugging WordPress.

Content Feedback

- It may not be useful **for this audience** to direct attention to wp-load.php, it may be sufficient to simply describe what the constants do to PHP settings.
- You mention two errors in the script, only one is shown.

Grammar nitpicks

> In this tutorial, you're going to learn ~~how~~ about debugging in WordPress.

> ...display_errors PHP ini setting to 1, which means ~~turn on~~ display*ing* these errors on screen.

> ...For example, if you wanted to log a ~~sql~~SQL query being run ~~g~~ to the debug.log file

**Comment by jonathanbossenger** [comment]
Thanks, for the review feedback on the script @jessecowens. I need to review it after recording the tutorial and will make the necessary changes.

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/assets/180629/9a551f60-e316-429d-b5ad-f48ef675d286

Uploading the tutorial video for review. 

Note to the reviewer, I had some weird audio glitches on this tutorial that I've not experienced before. So at some points, my voice cuts out for a split second. 

I'm hoping it's not too jarring and we can leave the audio in, but if you find sections that are not super clear, please leave the timestamp in your review, and I'll try and re-record those audio portions.

**Comment by westnz** [comment]
Hey Jonathan

Nicely done - you maintained an easy-to-follow pace and explained everything step-by-step.

It might be worth adding something to the blank screen (3:39 -3:58) to make it clear that the page will be empty.

I think it would be best to re-record those sections where you experienced some glitches. Tbh, it is a bit jarring 😬 I will send you some timestamps I jotted down.

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/tutorial/debugging-in-wordpress/
