### ISSUE TITLE
French translation for Lesson Plan "Dashboard Overview"

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Learn#1575]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/dashboard-overview/
- Link to original content GitHub issue: https://github.com/WordPress/Learn/issues/423
- Language you'll be translating to: french
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @lmwp
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by jennydupuy** [comment]
Published in french

**Comment by webtechpooja** [comment]
Updated Content Link: https://learn.wordpress.org/lesson-plan/fr-dashboard-overview/

**Comment by jennydupuy** [comment]
Nope, excuse me, i forgot to modify the slug before publish.
The correct slug is `fr-dashboard-overview`.

**Comment by lmwp** [comment]
I review this translation and all is ok. Thank's all
