### ISSUE TITLE
French translation for tutorial "The Difference Between Reusable Blocks, Block Patterns, Templates & Template Parts"

### ISSUE THREAD

**Issue by beryl-dlg** [WordPress/Learn#1576]
## Details
- Link to original content: https://learn.wordpress.org/tutorial/the-difference-between-reusable-blocks-block-patterns-templates-and-template-parts/
- Link to original content GitHub issue:  https://github.com/WordPress/Learn/issues/511
- Language you'll be translating to: FRENCH
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: @jennydupuy
- Other info: The translation is open for comments on a FramaPad file : https://mypads2.framapad.org/p/the-difference-between-reusable-t-5m31nc975

**Comment by jennydupuy** [comment]
Hi, ok I will review the translation

**Comment by beryl-dlg** [comment]
Hello @jennydupuy 
Subtitles review needed, thanks !
[subtitles-fr.zip](https://github.com/WordPress/Learn/files/11593369/subtitles-fr.zip)

**Comment by beryl-dlg** [comment]
Here's the subtitles translation file
[subtitles-fr.zip](https://github.com/WordPress/Learn/files/11593394/subtitles-fr.zip)

**Comment by jennydupuy** [comment]
I've corrected a typo.
The content is now validated and you can upload it to WordPress.tv.
Let me know when it's done, I'll take care of the article on learn.wordpress.org.
Thanks for this contribution.


[subtitles-fr-valide.zip](https://github.com/WordPress/Learn/files/11610962/subtitles-fr-valide.zip)

**Comment by beryl-dlg** [comment]
I've uploaded the subtitles file to WordPress.tv
It is now awaiting moderation. 
Thank you @jennydupuy

**Comment by jennydupuy** [comment]
Please @bsanevans could you check if the metadata are corrects in
https://learn.wordpress.org/wp-admin/post.php?post=40381&action=edit
and tell me the missing or incorrect ones?

**Comment by kaitohm** [comment]
This looks great, @jennydupuy !

One thing is, we link the GitHub issue inside all content, so that the two are connected. You can do this by:

1. Scroll down to "Editorial Comments"
2. Click "Respond to this post"
3. Copy-paste the GitHub link... in this case `https://github.com/WordPress/Learn/issues/1576`
4. Click "Submit Response"

Otherwise, this looks good to publish 🎉

**Comment by kaitohm** [comment]
Oh, sorry, one more thing. The slug of the content should be the two letter language code, followed by the English slug. In this case: `fr-the-difference-between-reusable-blocks-block-patterns-templates-and-template-parts`

Please change the slug before publishing 😉

**Comment by jennydupuy** [comment]
This content is published here: 
https://learn.wordpress.org/tutorial/fr-the-difference-between-reusable-blocks-block-patterns-templates-and-template-parts/
