### ISSUE TITLE
Implementing Learning Pathways

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#1577]
### Objective:

This project aims to integrate a series of structured learning pathways into the learn.wordpress.org platform, providing users with a comprehensive and guided learning experience about WordPress and its open-source contribution methods. [Proposal: Creating Learning Pathways for Learn WordPress](https://make.wordpress.org/training/2023/04/05/proposal-creating-learning-pathways-for-learn-wordpress/) introduced the terminology of the series of courses and has been reviewed by the Training, Marketing, and Polyglots teams.

### Background:

Learning pathways are a series of courses designed to help individuals acquire knowledge and skills in a specific field. The WordPress Training Team has proposed creating these pathways to increase engagement, personalize learning, improve outcomes, encourage collaboration, enhance retention, and create a unifying learner-based strategy​.

### Scope:

**Identify Audiences:** Determine the baseline audiences for the learning pathways. This could include developers, designers, content creators, site administrators, and others. 

**Develop Learning Content**: Use the identified competencies and required content to develop educational material. This could involve creating new content, or curating and organizing existing content.

[WordPress Contributor Mentorship Program: Pilot Program Proposal](https://make.wordpress.org/project/2023/05/17/wordpress-contributor-mentorship-program-pilot-program-proposal/) seeks to include these courses:

- [Open source basics](https://learn.wordpress.org/course/open-source-basics-and-wordpress/)
- [How Decisions Are Made in the WordPress Project](https://learn.wordpress.org/course/how-decisions-are-made-in-the-wordpress-project/)
- [Community Meeting Etiquette](https://learn.wordpress.org/course/community-meeting-etiquette/)
- [Writing in the WordPress Voice](https://learn.wordpress.org/course/writing-in-the-wordpress-voice/)
- [Basic Principles of Conflict Resolution](https://learn.wordpress.org/course/basic-principles-of-conflict-resolution/)

These would make a strong contender for our first Learning Pathway. 

**Design Learning Pathway Interface**: Design an interface within the learn.wordpress.org platform that allows users to access and navigate the learning pathways in an intuitive and user-friendly manner.

**Implement Learning Pathway Functionality**: Implement the designed interface and ensure the learning content is properly integrated.

**Test & Refine:** Conduct comprehensive testing to ensure the learning pathway functionality works as expected and refine based on user feedback.

### Tasks:

1. Identify the primary audiences for the learning pathways.
2. Identify and curate existing content that can be used in the learning pathways.
3. Design an intuitive interface within the learn.wordpress.org platform for accessing and navigating the learning pathways.
4. Implement the designed interface and integrate the learning content.
5. Conduct comprehensive testing of the learning pathway functionality and refine based on user feedback.

### Additional Considerations:

Please note that this is a high-level plan and each task will likely need to be broken down into smaller, more manageable sub-tasks.

**Comment by kaitohm** [comment]
I am excited about this project, and am following along to see what sub-tasks I might be able to contribute to 🎉 

As this issue itself contains multiple tasks beyond website development, I've moved the issue into the team's Administration project board to track progress there. We can create new development-related issues for each sub task once details are finalized 👍 

Could you also add a rough timeline to the issue, please, so folks (and team reps) have a basic understanding of the duration of this project? At the moment, it's unclear whether signing up is a 3 week commitment, 3 month commitment, or even longer. Thanks.

**Comment by jomarieminney** [comment]
I think a priority here is that we need to work out **how we are going to visualise the Pathways on the learn website**. In general, the learn UX is already pretty confusing with no real structure for users. There are so many different user types (meetup organisers, WordPress beginners, developers, contributors...) and so many different content types (Tutorials, Courses, Online Workshops, Lesson Plans, now we're adding Pathways) and as someone who recently has been *using* Learn (both for self-learning and as a meetup organiser), it's already overwhelming. 

If we're going to be reviewing content anyway for the Pathways project and the Contributor Mentor Project, is this a reasonable and prudent time to review the [Learn.WordPress.org](http://learn.wordpress.org/) Information Architecture and perhaps approach this with a plan...? 

I'd be happy to assist with this, Information Architecture is my primary area of expertise... Feel free to put me to work! :)

**Comment by kaitohm** [comment]
As we consider details, we'll want to take into account the results from [Analysis of the Individual Learner Survey results](https://make.wordpress.org/training/2023/05/30/analysis-of-the-individual-learner-survey-results/).

**Comment by Weissheiten** [comment]
To answer the question of Courtney from the thread which is now closed:

Question
_I love the idea of the API from WordPress. Likely this would include their profiles right? If someone has completed a series of courses successfully, the API would then let the organizations wanting learners to go through the coursework to know if it were done._

Yes, it allows to track Learners and their Organizations know which skills they managed to pick up. (along with some more features like matching persons looking for training with trainers, etc.)

**Comment by courtneyr-dev** [comment]
@jomarieminney 
Your expertise in Information Architecture will be invaluable as we navigate the complexity of this project. It's been on the team's radar for quite some time, but the redesign efforts across all of .org have created many starts/stops to any progress. I agree with your perspective; as we add new elements to the Learn WordPress platform, we must prioritize the user experience and ensure the content remains accessible and intuitive. We need to make a better user journey throughout the sites.

Here are some next steps based on your feedback:

**Review the Information Architecture of Learn.WordPress.org**: Given your expertise in this area, it would be beneficial if you could conduct an audit of the current structure of the site and provide recommendations on how to improve the user experience. This could involve reorganizing the existing content, developing a new site navigation strategy, or implementing a tagging system to make content more searchable. Also review [https://make.wordpress.org/training/2022/10/07/ux-feedback/](https://make.wordpress.org/training/2022/10/07/ux-feedback/ ). As @bsanevans noted, reviewing the Individual Learner Survey will also be vital to the future of the site's functionality.

**Visualize Pathways**: Collaboratively, we can devise a strategy to visualize the learning pathways on the Learn WordPress site. This could involve developing a new user interface component or adapting an existing one.

**Revisit Content Structure**: As we're already reviewing content for the Pathways project, it would be a good time to reevaluate how content is organized and presented. This could involve re-categorizing existing content or revising the content hierarchy.

**Collaboration with the team**: Would you prefer a few Zoom-based work sessions to hear ideas, or to conduct some initial feedback in an async manner? We want to ensure all perspectives are considered and there's a shared understanding of the proposed changes.

**Create and Implement a Plan**: Based on the findings from the steps above, create an execution plan. This should include a timeline, assigned responsibilities, and key deliverables. We will need to check in with the redesign team as well to avoid conflicting on any changes or to really work well together on implementation.

**Comment by jomarieminney** [comment]
This sounds like an excellent approach - I'll look through the existing work that has been done in this area already and then complete an IA/UX audit on learn.wordpress.org. 
I don't want to reinvent the wheel and a lot of talented folx have already tried to tackle this, so I'll start by reviewing the following and basically just presenting it all in a single place so that we can use it to push forward:
[UX Feedback from Piccia Neri](https://make.wordpress.org/training/2022/10/07/ux-feedback/)
[2021 Learn WordPress Needs Analysis by AllenComm](https://make.wordpress.org/training/2021/09/14/learn-wordpress-needs-assessment-results/)
[Recent individual learner survey results](https://make.wordpress.org/training/2023/05/30/analysis-of-the-individual-learner-survey-results/)
[This GitHub issue that provides some history on current UX](https://github.com/WordPress/learn/issues/153)

If anyone else has important prior work relating to the Interface or Information Architecture of learn.wordpress.org, I'd love if you could link it in a comment on this thread so I don't miss it.

With regards to collaboration, I think a combination of async and Zoom would be ideal! It would be superb if we could do a few focus group sessions based around some of the user avatars identified in the recent learner survey results. I'm thinking something like:

- Freelancers/Solopreneurs/Boutique Agencies
- Developers/Engineers
- Educators & WordPress Meetup Organisers
- Personal Project/Content Creators

Another focus group that isn't really captured by the learner survey but would still be ideal to tap into would be those who want to contribute but aren't sure how - and I think that it would be a great opportunity to leverage some of the work that @harishankerr has been doing with the proposed [WordPress Contributor Mentorship Program](https://make.wordpress.org/project/2023/05/17/wordpress-contributor-mentorship-program-pilot-program-proposal/).

I'm excited at the opportunity to bring together all the work that so many people have contributed over the past few years to help make learn.wordpress.org a valuable tool for the whole WP community!

**Comment by kaitohm** [comment]
@courtneyr-dev I appreciate you breaking down the project into smaller pieces. Could you also add a rough timeline to the issue, please, so folks (and team reps) have a basic understanding of the duration of this project? It will help keep the project accountable to the team, and allow us to consider what assistance may be needed along the way.

**Comment by kaitohm** [comment]
@jomarieminney 

> If anyone else has important prior work relating to the Interface or Information Architecture of learn.wordpress.org, I'd love if you could link it in a comment on this thread so I don't miss it.

I think you've covered all the significant articles 👍  And the contributor focus group you've noted would be a great addition, too.

**Comment by kaitohm** [comment]
I just remembered, there is a related team goal this year, tentatively tracked in the following GitHub issue. The team said December was the projected end-date for this: [Plan a structured way to showcase Learn WordPress content](https://github.com/WordPress/Learn/issues/1481)

**Comment by courtneyr-dev** [comment]
I think the first step is to get sorted on estimated timeframe of @jomarieminney availability for initial scope. Then we need to assess contribution availability.  Unlike content creation, this would have dependencies of dev/design availability.  I will check in tomorrow on the meta-learn efforts from Meta team's table. I should also know more from [WordPress Contributor Mentorship Program](https://make.wordpress.org/project/2023/05/17/wordpress-contributor-mentorship-program-pilot-program-proposal/) at the end of contributor day WCEU

**Comment by kaitohm** [comment]
This project is now being tracked here: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/
