### ISSUE TITLE
Online Workshop - WordPress Coding Standards

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1594]
# Event Details
- Title: WordPress Coding Standards
- Description: Writing code, especially in a collaborative environment like open source, requires all participants to follow specific standards. Coding standards help avoid common coding errors, improve the readability of code, and simplify modification. In this workshop, you'll learn about the WordPress Coding Standards, where to find information about them, as well as how to automate the process of formatting your code to meet the coding standards.
- Target Audience: Developers
- Date: 2023-06-01 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/293787237/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by ghost** [comment]
@jonathanbossenger I can go-host.

**Comment by jonathanbossenger** [comment]
Thanks @lada7042

**Comment by jonathanbossenger** [comment]
Thank you @lada7042 for offering to co-host. As far as I know, you have co-hosted before, so you're probably already familiar with the guidelines, but I'm sharing them [here](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) anyway.  

However, every workshop presenter has different needs, so these are the most important things I need from a co-host:

- I usually start the workshop by hitting Invite all, and then Record. Please keep an eye out for anyone joining after I hit record, and admit them into the Zoom meeting
- Keep an eye on the chat, and let me know if I miss any important questions. I usually leave breaks for questions, so this is mostly for questions that come up while I'm presenting, that are relevant to what I'm presenting. 
- About halfway through, please take a count of the total participants, as we need to report the attendee numbers afterward
- Listen out for any folks who have background noise coming through their mics, and please mute them. This doesn't happen often, but it can be distracting.
- I will start the Zoom meeting about 5-10 minutes before, to let you in and make you co-host of the Zoom session. The Zoom URL is in the meetup.com event, but let me know if you need it and I'll share it here. 

Also, please let me know if you have any questions.

**Comment by jonathanbossenger** [comment]
@lada7042 apologies for the late update, I've adjusted the workshop duration to 1.5 hours, to make sure I cover everything. If you are only available for one hour, that's perfectly fine, and you're welcome to sign out if/when you need to.

**Comment by ghost** [comment]
@jonathanbossenger I am able to stay the whole time.

**Comment by jonathanbossenger** [comment]
Published https://wordpress.tv/2023/06/02/wordpress-coding-standards/
