### ISSUE TITLE
Learn WordPress Content Feedback - sentence needs update

### ISSUE THREAD

**Issue by senseilein** [WordPress/Learn#1595]
# Feedback Details
- Content title: What will I get out of this course?
- Content URL: [https://learn.wordpress.org/lesson/1-getting-started-with-wordpress-is-wordpress-right-for-you/](https://learn.wordpress.org/lesson/1-getting-started-with-wordpress-is-wordpress-right-for-you/) 
- Are you reporting an error (such as outdated information), or providing improvement ideas?: improvement 

Write a description of your feedback here:

- Issue: 
The last sentence states: **"To navigate to the next section, click the ‘Complete Lesson’ button in the top right-hand corner of your screen, then click ‘next’."**
**However, on my screen (desktop), the 'Complete Lesson' button appear at the bottom, right below that sentence** and it seems like it's no longer necessary to click 'next' (that link doesn't appear on the page).

- Screenshot: 
![Complete button - Wordpress](https://github.com/WordPress/Learn/assets/73607360/3791fd76-f81b-4ed1-95a7-04311e4a71e3)

- Suggestion: "To navigate to the next section, click the ‘Complete Lesson’ button at the bottom of the page."

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by akshaya-rane** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No):  Yes
- What should happen next to apply the feedback?:  Content change - 
"To navigate to the next section, click the ‘Complete Lesson’ button at the bottom of the page."

**Comment by SierraTR** [comment]
content change completed as suggested
