### ISSUE TITLE
Learn WordPress Content Feedback - location of 'Take Quiz' button

### ISSUE THREAD

**Issue by senseilein** [WordPress/Learn#1596]
# Feedback Details
- Content title: Choose your own adventure.
- Content URL: https://learn.wordpress.org/lesson/3-why-wordpress-is-for-everyone/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: error

Write a description of your feedback here:

The last sentence on the page is " Next: Select the “Take Quiz” button in the top right-hand corner to test your understanding."

However, on the desktop site, the 'Take Quiz' button is located at the bottom of the page, right below that sentence.
 
Screenshot:
![Take Quiz button - Wordpress](https://github.com/WordPress/Learn/assets/73607360/213505ee-b152-41bc-bd9c-f3dcdc048569)

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by akshaya-rane** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No):  Yes
- What should happen next to apply the feedback?: Text changes

Current text:

`Next: Select the “Take Quiz” button in the top right-hand corner to test your understanding.`

To : 

`Next: Select the “Take Quiz” button at the bottom of the page to test your understanding.`

**Comment by SierraTR** [comment]
Changed the text 'in the top right-hand corner' to single word 'below'
