### ISSUE TITLE
Meeting Agenda May 30, 2023

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1597]
This week’s meeting will be held in APAC timezone on Tuesday, May 30, 2023, at 07:00 UTC, and @bsanevans will be hosting.

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- May 30 – [@hderashri](https://profiles.wordpress.org/hderashri/)
- June 6 – Need Volunteer
- June 13 – Need Volunteer
- June 20 – Need Volunteer
- June 27 – Need Volunteer

**2. Looking for feedback**

- It's been a month since we moved meeting agendas from [the team blog](https://make.wordpress.org/training/) to GitHub. What is your feedback about the switch?
- [Analysis of the Individual Learner Survey results](https://make.wordpress.org/training/2023/05/30/analysis-of-the-individual-learner-survey-results/) has finally been published 🎉 Please leave your comments on the post. This data and discussions will be a big factor the team will consider as we prioritize our activities from here on.

**3. Looking for volunteers**

- #1577 - Please indicate interest in the GitHub issue
- [WordPress Contributor Mentorship Program: Pilot Program Proposal](https://make.wordpress.org/project/2023/05/17/wordpress-contributor-mentorship-program-pilot-program-proposal/): Each team has been asked to devote at least one team member. Would any Faculty like to volunteer?
- [Team Meeting Hosts](https://make.wordpress.org/training/handbook/training-team-how-to-guides/hosting-training-team-meetings/#hosting-team-meetings) and [Coffee Hour Hosts](https://make.wordpress.org/training/handbook/training-team-how-to-guides/hosting-training-team-meetings/#hosting-coffee-hours)

**4. Other news**

- The Training Team's GitHub project boards are being updated ([Slack thread](https://wordpress.slack.com/archives/C02RW657Q/p1685091027301509))
- [WordPress 6.3 Planning Roundup](https://make.wordpress.org/core/2023/05/18/wordpress-6-3-planning-roundup/)
- [WordCamp Europe 2023 schedule](https://europe.wordcamp.org/2023/schedule/)
- [WordCamp EU Contributor Day ideas](https://make.wordpress.org/training/2023/05/09/brainstorm-wordcamp-europe-2023-contributor-day/)
- WordPress turned 20 on May 27th 🎉 

## 3. Content published in the last week

- **Tutorials**
  - [Building a page with only patterns](https://learn.wordpress.org/tutorial/building-a-page-with-only-patterns/)
- **Lesson Plans**
  - [બ્લોક થીમ માટે મૂળભૂત ચાઈલ્ડ થીમ બનાવો](https://learn.wordpress.org/lesson-plan/gu-create-a-basic-child-theme-for-block-themes/) (Gujarati)
  - [Flexbox in CSS and WordPress](https://learn.wordpress.org/lesson-plan/flexbox-in-css-and-wordpress/)

## 4. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

- **Tutorials**
  - #1309
  - #1419
  - #1501 
  - #1502 
  - #1543 
  - #1551   
- **Lesson Plans**
  - #739 
  - #806 
- **Courses**
  - #1453 
- **Translated Content**
  - French: #1576 
  - Gujarati: #1130 
  - Hindi: #1552 
  - Indonesian: #1488 
  - Indonesian: #1508 
  - Khmer: #1357 
  - Spanish: #1133 

## 5. Project updates

- [Proposal: Creating GitHub project boards for SMEs and Translators](https://make.wordpress.org/training/2023/05/05/proposal-creating-github-project-boards-for-smes-and-translators/) @bsanevans 
  - New project boards have been made. Workflows have been set so that new issues are automatically added to these project boards. l plan on finish moving non-vetted topics out of the Content Development board and into the Subject Matter Expert board this week.
- [Analysis of the Individual Learner Survey results](https://make.wordpress.org/training/2023/05/30/analysis-of-the-individual-learner-survey-results/) - A big Thank You to @abhansnuk and @westnz for publishing these results.
  - This is an important post for the team as we prioritize future activities. Please leave any comments you have on the post.

## 6. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kaitohm** [comment]
I'm just noting, the meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1685430054171919

**Comment by webtechpooja** [comment]
The Published Recap notes link - https://make.wordpress.org/training/2023/06/05/training-team-meeting-recap-30-may-2023/
