### ISSUE TITLE
Online Workshop - WordCamp EU 2023 Contributor Day

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1599]
# Event Details
- Title: Training Team Contributor Day Online Session
- Description: Join the Training Team online at the [WordCamp Europe 2023 Contributor Day](https://europe.wordcamp.org/2023/contributor-day/)!
- Target Audience: Users
- Date: June 8th, 2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/293858174/
- Co-host: @jonathanbossenger 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
@bsanevans is this the one you need me to help co-host from the event?

**Comment by kaitohm** [comment]
It is. I've added you now 👍
