### ISSUE TITLE
Tutorial - Onboard new moderators for the WPPhotos project

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1600]
# Topic Description
Video tutorial to onboard new moderators for the WPPhotos team

# Related Resources
- NA

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by webtechpooja** [comment]
Here is the draft video link - https://drive.google.com/file/d/1WHMBdJEAwKwhs2WSF0GUIRs4dJCABtyy/view?usp=share_link

**Comment by topher1kenobe** [comment]
Final video

![Learn Workshop cover template 2023-05-29](https://github.com/WordPress/Learn/assets/341412/697d133e-fd7a-49e4-b041-af0d283ce013)

**Comment by westnz** [comment]
Hey @topher1kenobe !  I hope you are doing great!  When would you like to publish?  Please let me know if you need any help getting it posted.

 @webtechpooja, we can probably add the 'ready for review' tag and move it to the 'Review in progress' column. 😃

**Comment by webtechpooja** [comment]
Sure, I'll Move it to the 'Ready for Review' column!

**Comment by topher1kenobe** [comment]
Now that WCEU is over I'm going to circle back with some folks on the training team about how to proceed.

**Comment by topher1kenobe** [comment]
The video itself is too big, it's shared here: https://drive.google.com/file/d/1WHMBdJEAwKwhs2WSF0GUIRs4dJCABtyy/view?usp=sharing

**Comment by westnz** [comment]
Review:

The video provides clear step-by-step instructions on moderating images.  The video's pace is spot on, and you highlight anomalies moderators might face clearly. 

I also appreciate the way you encourage moderators to do as much they wish to or as time allows. 

You've created a great onboarding video! 

One thing I was unsure about is if it will be an issue having the image and names of contributors such as Josh or Devanshi mentioned in the video. 

Well done, Topher!

**Comment by jonathanbossenger** [comment]
> The video itself is too big
I've found that running the video through Handbrake at the "Fast 1080p30" preset creates a version of the video that can be easily uploaded here as well as save space on WordPress.tv.

**Comment by topher1kenobe** [comment]
> > The video itself is too big
> > I've found that running the video through Handbrake at the "Fast 1080p30" preset creates a version of the video that can be easily uploaded here as well as save space on WordPress.tv.

Ah, I made it 4k.  I can re-render at 1080.

**Comment by jonathanbossenger** [comment]
Not to worry this time, just mentioning it for uploading here in the future. WordPress.tv allows 4k, I just tend to default to 1080p, as that appears to be the most widely used resolution worldwide at the moment. But feel free to upload at 4k to WordPress.tv for the 4k viewers 😁 

Review notes, great video, I especially like the way you've shown what happens if you don't have the Chrome extension installed, for our non-Chrome users. 

Additionally, I echo @westnz's sentiment, are we allowed to include contributor names in videos? Perhaps you're able to blur these out, or do we think that's not going to be an issue?

**Comment by topher1kenobe** [comment]
How do we get a transcription prepared? @webtechpooja

**Comment by webtechpooja** [comment]
@topher1kenobe 
Do you want to work on your own or want some volunteer to take care of this?


You can find more details on our handbook page - https://make.wordpress.org/training/handbook/tutorials/tutorial-subtitles-and-transcripts/

Hope this will work for you! Thanks

**Comment by jonathanbossenger** [comment]
I will be taking over the process of creating the transcription and vetting the tutorial on Learn WordPress.

@topher1kenobe Once I've added it to the video, I'll vet the tutorial on Learn and if it's all ready, I'll publish it and update you with the published link here.

**Comment by topher1kenobe** [comment]
@jonathanbossenger I've already gotten this far: https://learn.wordpress.org/wp-admin/post.php?post=40465&action=edit

The transcription from Otter needs a lot of help.  :(

**Comment by jonathanbossenger** [comment]
Yeah, the Otter transcriptions do require some help. It's one of the reasons I write a full script of my tutorial first, and then upload that in the body of the tutorial. I'll be cleaning things up here in a bit.

**Comment by jonathanbossenger** [comment]
@topher1kenobe I've run through the transcription, cleaned it up, added it as subtitles to the wp.tv video, and to the body of the tutorial, and published it on Learn WordPress. 

https://wordpress.tv/2023/06/19/wpphotos-moderator-training/

If you're happy with it, feel free to close this issue.

**Comment by jonathanbossenger** [comment]
Oh, and you can also let the Marketing team know by [adding it to this spreadsheet](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion
