### ISSUE TITLE
Online Workshop - New to WordPress? Getting to know the Dashboard

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1605]
# Event Details
- Title: New to WordPress? Getting to know the Dashboard
- Description: Walkthrough of the Dashboard + Q&As
- Target Audience: Users / Beginners
- Date: 19 June 21:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/293927263/?isFirstPublish=true
- Co-host: Tracy Rhodes
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I'll co-host with you Wes.

**Comment by westnz** [comment]
Great, thank you @SierraTR. See you then
