### ISSUE TITLE
Tutorial for review: 1543 | Suggestions 

### ISSUE THREAD

**Issue by valzya** [WordPress/Learn#1610]
Tutorial for review: https://github.com/WordPress/Learn/assets/180629/e3229c9f-872a-4775-b97d-27c292de11c9

_Originally posted by @jonathanbossenger in https://github.com/WordPress/Learn/issues/1543#issuecomment-1564529369_

**Comment by valzya** [comment]
Reviewing the tutorial 'Developing for sites in a network.'
Missing periods on 1. 2. lists under titles. I would suggest a step by step instructional design format for this lesson. When the information is in depth that may provide the learner with greater detail. If the goal is a summary then the video is adequate.

**Comment by jonathanbossenger** [comment]
@valzya 

Is it possible for you to leave your review in the comments [on the original GitHub issue](https://github.com/WordPress/Learn/issues/1543)? That way all review feedback is gathered in one place.

**Comment by jonathanbossenger** [comment]
Closing this as the comments have been added to the original issue
