### ISSUE TITLE
Learn WordPress Content Feedback For Create a Basic Child Theme for Block Themes

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/Learn#1614]
# Feedback Details
- Content title: Create a Basic Child Theme for Block Themes
- Content URL:https://learn.wordpress.org/lesson-plan/create-a-basic-child-theme-for-block-themes/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: Yes

Some links are broken and some link with nothing happened anything on this lesson plan. Can you check, please?
https://learn.wordpress.org/lesson-plan/create-a-basic-child-theme-for-block-themes/

Basic HTML and [CSS](https://make.wordpress.org/training/handbook/theme-school/intro-to-css/)  => 404 error on here (https://make.wordpress.org/training/handbook/theme-school/intro-to-css/)
[Installing and activating WordPress themes](https://make.wordpress.org/training/handbook/user-lessons/choosing-and-installing-a-theme/) => 404 error on here ( https://make.wordpress.org/training/handbook/user-lessons/choosing-and-installing-a-theme/ )

Write a description of your feedback here: No
---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published
![image_720](https://github.com/WordPress/Learn/assets/23701579/9912360a-ef38-4051-a7e7-4780a0f5f453)
![image_480](https://github.com/WordPress/Learn/assets/23701579/1b8cce6d-9e42-4043-98c2-d1b77a78317a)

**Comment by ironnysh** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? Yes.
- What should happen next to apply the feedback?: 

1. Change the link from [CSS](https://make.wordpress.org/training/handbook/theme-school/intro-to-css/) to [CSS](https://learn.wordpress.org/lesson-plan/introduction-to-css/).
2. Change the link from [Installing and activating WordPress themes](https://make.wordpress.org/training/handbook/user-lessons/choosing-and-installing-a-theme/) to [Installing and activating WordPress themes](https://learn.wordpress.org/tutorial/choosing-and-installing-theme/)

**Comment by kaitohm** [comment]
I've made the updates. Thanks for the feedback, and the validation 😃
