### ISSUE TITLE
Tutorial - Embedding media and third-party content on your website

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1616]
# Topic Description
How to use embed blocks and highlight that some services cannot be embedded. 

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- https://wordpress.org/documentation/article/embeds/
- https://wordpress.org/documentation/article/embed-block/

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/0b3f2ef9-a87b-4f2b-850b-a717e55431fe

**Comment by quitevisible** [comment]
Another great little tutorial @westnz . Embeds: the secret trick to extending content on your website! I like the bit on columns, too. I'm curious what the SEO impact might be on one's site when using embeds/iframes.

**Comment by westnz** [comment]
Thank you @quitevisible!
I will also need to do some research about the impact on SEO.

**Comment by digitalchild** [comment]
Great tutorial. I learned from this. No suggestions with this one.

**Comment by westnz** [comment]
Thanks man @digitalchild

**Comment by westnz** [comment]
This tutorial will be published this week.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/embedding-media-and-third-party-content-on-your-website/
