### ISSUE TITLE
Tutorial- How to use the spacer block

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#1617]
# Topic Description
Learn how to use the spacer block and how to use the different resizing and styling tools available in the site editor. 

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.

-  https://wordpress.org/documentation/article/spacer-block/
- Template Parts- https://learn.wordpress.org/lesson-plan/template-parts/
-  Uncovering the Cover block- https://learn.wordpress.org/tutorial/uncovering-the-cover-block/

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion#

 Vetting Checklist for SMEs
Please follow the team handbook: [Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/).

- [x] Set a Priority label
- [x] Assess topic details, and provide feedback as necessary.
- [x] Move issue to "Vetted Topics" status

**Comment by jonathanbossenger** [comment]
I think this is a great idea. I look forward to seeing this tutorial created! Thank you @lada7042 for your contributions.

**Comment by courtneyr-dev** [comment]
https://make.wordpress.org/core/2023/04/19/whats-new-in-gutenberg-15-6-19-april/#spacer-block-gets-spacing-presets 

Calling out the new spacing presets

**Comment by ghost** [comment]
@courtneyr-dev I haven't finished this tutorial but I have been using the Gutenberg plugin. I will make sure to have the 6.3 updates. I am going to delete the 6.2 from this tutorial.

**Comment by ghost** [comment]
https://github.com/WordPress/Learn/assets/24979729/85e7165c-af35-407e-bb3f-4088779e837e

**Comment by ghost** [comment]
I used the Descript free version recording/editing software. The free version leaves a watermark. Here is the information from the site. Videos exported from projects stored on a Free drive, or exported by basic members of a Creator or Pro drive, will include a Descript watermark in the bottom right-hand corner. Upgrading to a paid Creator or Pro subscription will remove the watermark from any future exports. Is this ok to leave?

**Comment by jonathanbossenger** [comment]
@lada7042 I'm not sure if this is helpful, but I'm also trying out Descript, and I noticed that there is an option to remove the watermark, but only once, when you publish the video. The toggle is towards the bottom of the settings when publishing a video. 

<img width="1368" alt="Descript" src="https://github.com/WordPress/Learn/assets/180629/b873d25d-1b1e-4b8f-b38e-8a707d787360">

What I don't know if this is once per project, or one time only, but either way it might be useful to keep this for when the final version of this tutorial is ready.

**Comment by ghost** [comment]
@jonathanbossenger Thank you. I think it is once per project. I clicked on that toggle for the main video, but when I made the intro. that was not an option. I am going to try and just add the image and may need to re-record. I was able to just add an image layer over the video part so no more watermark.

**Comment by ghost** [comment]
Updated video with no watermark at the beginning

https://github.com/WordPress/Learn/assets/24979729/e87c146b-a652-4755-a67d-1f434b0e7115

**Comment by westnz** [comment]
Great work @lada7042 💥 

I think you have clearly explained how to use the Spacer block and used appropriate examples. Adding a spacer to a group to change the colour was a clever idea! You maintain a steady pace and speak very clearly! I like how you kept the list view open to help viewers see exactly where you edited content.  

One suggestion is to improve the transitions between the different scenes at the start: 0:00 - 1:00min. You might also consider adding the objectives to the beginning of the tutorial.

**Comment by ghost** [comment]
@westnz thank you for taking the time to do a review. Yes, I agree with moving the objectives to the front. Moving it should also help with the transitions in the beginning.

**Comment by wparasae** [comment]
Laura, you've done such a good job of implementing the changes I suggested when we worked together! Well done, and thank you so much for your time!

I know you've heard this from me before, but I want to reiterate how much I appreciate the way you describe the way you've set up the page and the way you describe what you're seeing on the page. Bravo! You speak very clearly and at a wonderful pace, which will be excellent for people who don't speak English as a first language. 

**Options for Change**

1. I second Wes' suggestion -- right after your introduction, adding a screen with the objectives you list at 6:18 would be super helpful! **If it would be helpful, I can add this in pretty quickly using iMovie or another program -- it would take me probably ~5 minutes, so if that is a better use of your time, please let me know!**

2. MAYBE a helpful tip: To improve some transitions, if you notice any cursor jumps, the "Cross Fade" transition might work. I THINK it can be applied to all clips, which MIGHT give a smoothing effect in a quick sweep. I use this a lot in another program, so I hope this helps! Here's a guide: https://help.descript.com/hc/en-us/articles/10255989387661-Transitions-overview

If that doesn't work (don't spend more than 10 minutes on it), I'm happy to help, just DM me this week. :) 

3. You do a good job of using your cursor to show what you're describing as you describe it. I'm not sure how to add annotations with descript, but a few red boxes over what you're describing may make this even clearer. Again, consider it an option for change, but not necessary.

This is an extremely helpful and clear tutorial -- people are going to benefit from this. I love what you've done here, and I hope you are feeling a strong sense of accomplishment.

**Comment by annezazu** [comment]
Offering a third review! Great job showing the various tools, keeping it contained, and guiding folks in a calm kind voice. My biggest point of feedback is that I'm not sure how this relates to block themes specifically. For example, you aren't editing a template but a page! I wonder if we can have more block theme specific examples -- like changing the spacing in a Query Loop block or between a header template part and the rest of the template. I also think it would be beneficial if we can include some of the thoughts of the spacer block being easier to use and apply for folks than something like margin in this discussion: https://github.com/WordPress/gutenberg/pull/37344#issuecomment-1034998300

**Comment by ghost** [comment]
@annezazu Thank you so much for taking the time out of your busy schedule to write a review. I agree with using the wording block themes. I hesitated when naming the tutorial and will update the title. I love the suggestions for future tutorials on spacer block focused on the templates. The query loop has always confused me but with added styling tools it is better to work with. Good luck with the release!

**Comment by annezazu** [comment]
Of course! Thanks so much for all your efforts here :)

**Comment by itsjustdj** [comment]
Very well done. Your voice is clear and calm, yet still engaging. The workflow you outline is practical for anyone to use right away.

One small point of feedback is at 4:50 where you go over putting the spacer in a group. You could  explain the reasoning a bit more before getting into the settings, mentioning that the Group gives you more style options than using the spacer block on its own.

**Comment by ghost** [comment]
@itsjustdj Thank you for reviewing the tutorial.

**Comment by lada7042** [comment]
Published- https://learn.wordpress.org/tutorial/how-to-use-the-spacer-block/

**Comment by ghost** [comment]
Published- https://learn.wordpress.org/tutorial/how-to-use-the-spacer-block/
