### ISSUE TITLE
Tutorial - Using Categories & Tags with Block Themes

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1618]
# Topic Description
This tutorial serves to condense the topic of categories & tags into a more bite-sized chunks than the existing tutorial (~24 minutes), as well as bring new information about how to utilize related theme blocks (archive title, term description) and templates (archive and custom). It will also provide a brief focus on SEO. 

# Objectives
Learners will be able to...
- Describe the difference between categories and tags
- Use theme blocks and templates related to categories and tags
- Create categories and tags effectively for organization and SEO purposes

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ] Tutorial: https://learn.wordpress.org/tutorial/wordpress-taxonomies/
- [ ] Lesson Plan: https://learn.wordpress.org/lesson-plan/categories-versus-tags/

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [ ] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by wparasae** [comment]
**Research (To Condense)**

**Overview Categories & Tags**
Categories and tags in WordPress are two types of taxonomies used to organize and classify content on your website. They help users and search engines understand and navigate through your content easily.

1. Categories: Categories are primarily used to group related content on your website into sections or topics. They are hierarchical, allowing you to create subcategories to further organize your content. Categories are best suited for broad topics and are generally required when creating a post in WordPress.

2. Tags: Tags are used to label specific details, keywords, or attributes related to your content. They are non-hierarchical and can be used across different categories. Tags are optional and can be added to your posts to provide more specific or granular information for better content discoverability. Tags help identify content topics that may not be covered by categories and allow for cross-referencing of related content.

Both categories and tags help improve the overall user experience, allowing your website visitors to easily find related content and navigate through your site. They also play a role in SEO by providing search engines with better context about the content's focus and structure.

**Categories and Tags for SEO**
Use these to organize and structure your content in a clear and purposeful manner. Here are some best practices to follow:

1. Be strategic with categories: Use categories to group your content into main topics or themes. Limit the number of categories, and make sure each post is assigned to only one category, whenever possible. This prevents content from being spread across multiple categories and reduces the chances of search engine confusion.

2. Use subcategories wisely: When needed, you can create subcategories to further organize content within main categories. This can help create a structured, hierarchical organization that is easier for both users and search engines to understand.

3. Be selective with tags: Use tags to provide specific details or keywords related to your content. Don't overuse tags or create duplicates; it's better to have a limited number of well-utilized tags rather than hundreds of rarely-used ones. This can prevent diluting the focus of your indexed content and reduce the possibility of having duplicate content issues.

4. Optimize category and tag names: Choose descriptive and relevant names for categories and tags. They should reflect your target keywords and phrases since they can appear in the URL, title tags, and header tags, which contribute to SEO.

5. Be consistent: Maintain a consistent approach to categorizing and tagging your content. Use a standardized naming convention and style for both categories and tags, making it easier for users and search engines to identify related content.

6. Use noindex for low-value pages: If you have tag or category pages with thin content or low value, you can apply the "noindex" tag to discourage search engines from indexing these pages. This can prevent these pages from causing potential duplicate content issues or consuming crawl budget.

7. Regularly audit and clean up: Periodically, review your categories and tags for any redundant or outdated terms. Consolidate or delete them to keep your site taxonomy clean, efficient, and user-friendly.

By following these best practices, you can effectively leverage categories and tags in WordPress to improve your site's SEO, enhance user experience, and make it easier for search engines to understand your content.


There are several practices to avoid when dealing with categories and tags in WordPress. Steering clear of these mistakes can prevent potential SEO issues and ensure a better user experience:

1. Don't assign too many categories: Avoid assigning a single post to multiple categories, as it may lead to content duplication and make it difficult for users and search engines to understand your site's structure. Generally, one category per post is sufficient.

2. Don't overuse tags: Using too many tags can dilute the focus of your content and cause confusion for both search engines and users. Instead, use a limited number of relevant and specific tags to describe your content.

3. Avoid empty or irrelevant categories and tags: Ensure that all your categories and tags serve a purpose, and avoid creating them without actual content. Empty or irrelevant categories and tags can negatively impact your site's SEO and confuse users.

4. Don't use non-descriptive names: Avoid using vague, generic, or non-descriptive names for categories and tags that don't provide any context or value to users or search engines. Opt for meaningful and keyword-rich terms that reflect the content's topic.

5. Avoid keyword stuffing: While it's essential to use keywords in your categories and tags, don't overdo it by stuffing multiple, unrelated keywords. This practice can lead to SEO penalties and confuse your users.

6. Don't create duplicate categories or tags: Ensure that each category and tag is unique and doesn't have a synonymous counterpart on your site. This prevents redundancy and makes it easier for users to navigate your content.

7. Don't neglect your site structure: Relying solely on categories and tags won't be sufficient for your site's organization. Maintain a clear site structure through proper use of menus, internal linking, and breadcrumbs to aid search engines and improve user navigation.

By avoiding these common pitfalls, you can better optimize your WordPress website's categories and tags for SEO and enhance the overall user experience.

**6.2 and Beyond Content: Categories & Tags Blocks**
-Archive Title
-Term Description

Where do these pull from? The WordPress Dashboard > Posts > Categories OR Tags.
Here, you can manage your categories and tags (with examples) and their descriptions.

Where are these blocks most commonly used?
- Archive Template
- Category & Tag Template

**Comment by wparasae** [comment]
**Draft**

If you're new to blogging, you may have noticed in a post's settings two options: categories and tags. When you start to experiment with them, at first, they can seem very similar! These are known as "taxonomies", and both are used to organize and classify content on your website. They help users and search engines understand and navigate through your content easily. They also play a role in SEO by providing search engines with better context about the content's focus and structure.

By the end of this tutorial, you will be able to

-Describe the difference between categories and tags
-Use theme blocks and templates related to categories and tags in a block theme
-Create categories and tags effectively for organization and SEO purposes

What's the difference between categories and tags?

The short answer is that categories SEPARATE a blog's topics so that readers can discover what interests them most and skip what doesn't. Meanwhile, tags JOIN a blog's topics, allowing readers to find related content. 

Think of a big library. The library contains many different types of books. How do we find a book that we want?

Just like the library has different sections for different topics such as comics, novels, poetry, and so on, WordPress categories are like these sections. They help to broadly group your posts into major topics--this allows people looking for non-fiction find the right books. For example, on a cooking blog, you can have categories like 'Appetizers', 'Main Courses', 'Desserts' and 'Drinks'. Someone who is hungry for dessert doesn't necessarily want to read through every single appetizer and main course on that blog, so these kinds of categories help them to quickly locate the content they want--and avoid what they don't.

Now, just knowing the section isn't always enough. What if you wanted to read ALL the books in the library that mentioned, say, 'dinosaurs'? The books about dinosaurs could be in different sections: fiction, non-fiction, children's books, etc.

That's what tags in WordPress do. They're like detailed labels, allowing people to find similar content. They aren't meant for grouping your posts, but to help describe specific details of your post. For instance, in a recipe post categorized under 'Desserts', you would use tags like 'Chocolate', 'Quick and Easy', or 'Gluten Free' to help users find the recipe more easily. Someone who needs to cook without sugar, for example, would then be able to quickly hop from one sugar-free recipe to another!

Categories: Categories are hierarchical, allowing you to create subcategories to further organize your content into more specific sections--for example, this travel blog separates its content by continent, but you could also add sub-categories, such as by country--which are within each continent, and thus suitable for a subcategory. Categories are best suited for broad topics and are generally required when creating a post in WordPress. You can rename your default category -- the category that is already selected for each new post -- by going to Posts > Categories > Hovering your mouse over "Uncategorized", then giving it a new title, slug (which is the actual website address of your category), and optionally, a description.

Meanwhile, tags are non-hierarchical and can be used across different categories. Tags are optional and can be added to your posts to provide more specific or granular information for better content discoverability. Tags help identify content topics that may not be covered by categories and allow for cross-referencing of related content. For example, this blog post might have tags such as "waterfall" and "mountains" and "hikes".

By design, WordPress creates pages to display only the select tag, or only the selected category.

Now that you know the key differences between categories and tags, how can you use them with WordPress block themes?

Categories & Tags in Block Themes
Many block themes come pre-packaged with an 'archives' template, which allows you to control how your categories & tags display when someone clicks on one in a post or through a link. You also have the option to make individual category or tag templates, which allows you to display your categories and tag pages in different ways. 

If you head to the "single" post template, you'll notice a few other related theme blocks. You may decide to include a 'tag' block in your Single or another post template. To help people navigate to the content they're MOST interested in, many people include links in their navigation to category pages as well as well.

For more information about designing templates, see https://learn.wordpress.org/tutorial/templates/, and for more information about navigation, visiet learn.wordpress.org/tutorial/

Before you begin writing your blog, what are some quick do's and don'ts for using categories and tags?

DO

Primarily use one category per post: Limit the number of categories, and make sure each post is assigned to only one category, whenever possible. This prevents content from being spread across multiple categories and reduces the chances of search engine confusion. Generally, one category per post is sufficient.

Use subcategories wisely: When needed, you can create subcategories to further organize content within main categories. This can help create a structured, hierarchical organization that is easier for both users and search engines to understand.

Be selective with tags: Use tags to provide specific details or keywords related to your content. Don't overuse tags or create duplicates; it's better to have a limited number of well-utilized tags rather than hundreds of rarely-used ones. 

Optimize category and tag names: Choose descriptive and relevant names for categories and tags. They should reflect your target keywords and phrases since they can appear in the URL, title tags, and header tags, which contribute to SEO. DON'T add tags that aren't relevant to your content; while it might be tempting to include a popular search term, if that particular post is unrelated, people may get frustrated, and search engines may rank your website lower.

DON'T

Don't overuse tags: Using too many tags can dilute the focus of your content and cause confusion for both search engines and users. Instead, use a limited number of relevant and specific tags to describe your content.

Avoid empty or irrelevant categories and tags: Ensure that all your categories and tags serve a purpose, and avoid creating them without actual content. Empty or irrelevant categories and tags can negatively impact your site's SEO and confuse users.

Don't create duplicate categories or tags: Ensure that each category and tag is unique and doesn't have a synonymous counterpart on your site. This prevents redundancy and makes it easier for users to navigate your content.

By avoiding these common pitfalls, you can better optimize your WordPress website's categories and tags for SEO and enhance the overall user experience.

Regularly audit and clean up: Periodically, review your categories and tags for any redundant or outdated terms. Consolidate or delete them to keep your site taxonomy clean, efficient, and user-friendly.

**Comment by wparasae** [comment]
Resource: [Using Categories & Tags with Block Themes Google Slide Deck ](https://docs.google.com/presentation/d/1YqWaHV6GQz-r1mTmJIt-9U7Kq7AIz8RLx74zJ5t2DCk/edit?usp=sharing)

**Comment by wparasae** [comment]
This is ready for review. I tried to use a few AI tools to assist me with this tutorial, but it ultimately feels... clumsy? 

I also shortened the text quite a bit to make sure we don't duplicate material on learn.wordpress.org revolving around block themes; I also renamed the tutorial to more accurately reflect its content.

Here is the rough draft of this video:

https://drive.google.com/file/d/1f7eWY71VegAlqXMMxyyugt71pUrKuwYV/view?usp=sharing

Please provide feedback on this issue below:

1. Is the sound quality okay? (Any bird whistles or barking in the background that I need to be made aware of?)
2. Is the content accurate?
3. Do you have any other feedback? 

Thank you so much for your time, team!

**Comment by westnz** [comment]
Review:

Nicely done, Sarah!

- **0:26** 'Used to organize and classify information on your site' + **0:28** 'Help users and search engines understand and navigate through your content' + **0.46** ' 'Create categories and tags effectively for organization and SEO purposes **4:57** 'Use sub-categories wisely' comes in too late on the slides - after you have said them. Could you check and correct the timing?
- 1:10 onwards. The bookshelves are not aligned 😉 
- Clever use of graphics and good examples used throughout

**Comment by jasonsnow12** [comment]
I didn’t notice anything that I would recommend as a change. I really like the varied use of examples between recipes and dinosaurs (books). It will create examples for people across a wider audience base. Very accurate description of taxonomy.

**Comment by wparasae** [comment]
Published!

**Comment by courtneyr-dev** [comment]
WP 6.4 https://github.com/WordPress/gutenberg/pull/52521

**Comment by Rashigupta2999** [comment]
The video is clear and helpful in explaining Categories and Tags, and I really like the use of different examples. 

Suggestion:
It would be beneficial to include a section on deleting categories and tags to provide a more comprehensive understanding.
