### ISSUE TITLE
Online Workshops page, the under form sentence are being appearing twice

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/Learn#1622]
## Description
Online Workshops page, the under the form sentences are being appearing twice. This seems to be a problem with the page's entry. I suggest reviewing the page content and ensuring that the under form sentences are properly implemented. By resolving this issue, you can ensure a more seamless and user-friendly experience on the Online Workshops page.

## Step-by-step reproduction instructions
1. Go to this url, https://learn.wordpress.org/online-workshops/
2. Scroll down to last section

## Expected behaviour
Remove duplicate sentences

## Actual behaviour
Need to show this sentences only one time

## Screenshots or screen recording (optional)
Check given screenshot URL, https://www.awesomescreenshot.com/image/40579830?key=e21abef67ed529a51be2e7203180a52e

## Environment information
- Mac mini

**Comment by sumitsinghwp** [comment]
@utsavtilava yes,  I have checked the shared link, and showing twice time.

**Comment by kaitohm** [comment]
Thank you for reporting this! I have confirmed the issue and removed the duplicated content. All fixed now 🎉
