### ISSUE TITLE
Duplicate content on /online-workshops/ page.

### ISSUE THREAD

**Issue by VipulUpadala** [WordPress/Learn#1623]
## Description
I have reviewed the above "/online-workshops/" page and found the form below "If you do not receive a response in about a week, please reach out in the #training channel in Slack to follow up." content is two times display. 

## Step-by-step reproduction instructions

1. Open first https://learn.wordpress.org/online-workshops/ page
2. Scroll down to "Apply to Facilitate or Co-host" form section below.
3.  Please check "If you do not receive a response in about a week, please reach out in the [#training channel in Slack](https://wordpress.slack.com/archives/C02RW657Q) to follow up." content is two times display.

## Expected behaviour
Content display only one time.

## Actual behaviour
Content display two times.

## Screenshots or screen recording (optional)
 https://share.cleanshot.com/DgGFDTSx9T2yZVwdKR2L

## Environment information
- Chrome
- MacBook  with macOS 13.2

**Comment by utsavtilava** [comment]
Hello @VipulUpadala 

I have already submitted a pull request for this change. Therefore, I kindly request you to close your pull request as it is considered a duplicate.

https://github.com/WordPress/Learn/issues/1622
