### ISSUE TITLE
Tutorial - Local WordPress Installations (For Beginners) [Revision]

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1624]
# Topic Description
The existing tutorial on local WordPress installations for beginners is out of date due to ServerPress no longer existing. This tutorial needs to be updated to remove references to ServerPress, and a potential alternative needs to be explored.

Laragon has been recommended, but it is not available across different devices; exploring DevKinsta instead.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ] https://learn.wordpress.org/tutorial/local-wordpress-installations-for-beginners/
- [ ] https://developer.wordpress.org/themes/getting-started/setting-up-a-development-environment/

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [ ] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [ ] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [ ] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by wparasae** [comment]
A tutorial in draft form for this exists, but needs significant updates. Unassigning myself in case another contributor would like to work on this (either revise the existing one, or make a new one) -- feel free to ping @wparasae (arasae in Slack) for questions.

**Comment by kaitohm** [comment]
Closing in favor of prioritizing Learning Pathways content.
