### ISSUE TITLE
Learn WordPress Content Feedback - Lots of pages in which we need to update links as a hindi domain URL - https://hi.wordpress.org/ .

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/Learn#1625]
# Feedback Details - I have visited lots of Hindi language pages. and there should be added a Hindi language link on the mentioned link in the tutorial. I am sharing a few page links here. 
- Content title: प्लगइन्स को चुनना और इंस्टॉल करना
- Content URL: https://learn.wordpress.org/lesson-plan/hi-choosing-and-installing-plugins/
- Are you reporting an error (such as outdated information), or providing improvement ideas?:
[आधिकारिक WordPress.org प्लगइन निर्देशिका](https://wordpress.org/plugins/) => [आधिकारिक WordPress.org प्लगइन निर्देशिका](https://hi.wordpress.org/plugins/)
[हैलो डॉली](https://wordpress.org/plugins/hello-dolly/) =>  [हैलो डॉली](https://hi.wordpress.org/plugins/hello-dolly/) 
Write a description of your feedback here:
if the "hi" domain link is available then it should be added "hi" subdomain link on the Hindi page.

---

# Feedback Report Checklist:
- [x] Feedback validated
- [x] Update proposed
- [x] Update reviewed
- [x] Update published

**Comment by kaitohm** [comment]
@piyushmultidots Are you available to make these updates?

**Comment by sumitsinghwp** [comment]
If I can access page then I can update all page link in hindi lesson @bsanevans

**Comment by kaitohm** [comment]
Thank you, Sumit. I've set you as the author of the lesson plan, so you should be able to edit the links now 👍

**Comment by sumitsinghwp** [comment]
Thank you so much @bsanevans

**Comment by sumitsinghwp** [comment]
@bsanevans I have checked and I am an author. but still, I am not able to edit posts :(
![image](https://github.com/WordPress/Learn/assets/23701579/b3440c53-05f4-4a54-8af6-d2828348edb0)

**Comment by kaitohm** [comment]
@sumitsinghwp I've just changed your user role to "Author". Could you try again now? 🙇‍♂️

**Comment by sumitsinghwp** [comment]
Hey @bsanevans , 

I have updated the link on https://learn.wordpress.org/lesson-plan/hi-choosing-and-installing-plugins/ post. Also, I have updated one old URL as per mentioned below.

I have updated the old URL to the new one (https://codex.wordpress.org/Plugins)
![image](https://github.com/WordPress/Learn/assets/23701579/3996b94c-288a-4626-a2fc-d90e000a44a7)
