### ISSUE TITLE
Topic Idea: Server Side Validation and Client Side Validation in WordPress

### ISSUE THREAD

**Issue by utsavtilava** [WordPress/Learn#1626]
# Details

- Topic description: Server-Side Validation and Client-Side Validation in WordPress
- Learning objectives: 
   Understand the importance of server side validation and client side validation in WordPress.
- Content type: Text
- WordPress version (optional): 
- Will you be creating this content?: Yes

# Related Resources
[Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.](https://docs.google.com/presentation/d/1UKi7EdS17mxyAidBsQ8X3M7oZ8naDz2s-d4QiGl_s34/edit?usp=sharing)

# Vetting Checklist for SMEs
Please follow the team handbook: [Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/).

- [ ] Set a Priority label
- [ ] Assess topic details, and provide feedback as necessary.
- [ ] Move issue to "Vetted Topics" status

**Comment by utsavtilava** [comment]
I have attached my content here :
https://docs.google.com/presentation/d/1UKi7EdS17mxyAidBsQ8X3M7oZ8naDz2s-d4QiGl_s34/edit?usp=sharing

**Comment by kaitohm** [comment]
I see you've submitted some slides here, @utsavtilava . We don't have slide-only content on Learn.WordPress.org right now. The closest content types would be either:
* Online Workshop (live workshop via zoom), or
* Tutorial (recorded 5-10 minute video)

Do you have a preference with which type of content to turn this into? We can also assign an experienced content creator to work along side you, if you'd like. Let us know what you think.

**Comment by utsavtilava** [comment]
Hello @bsanevans 

Thank you for reviewing the content I submitted. I apologize for the misunderstanding regarding the content type on Learn.WordPress.org. I appreciate your clarification.

Considering the options you provided, I believe converting the slides into a recorded tutorial video would be the most suitable format for the content. This way, viewers can follow along and learn at their own pace.

Please let me know how you would like to proceed, and If you want i will share the content with you, So i will share it in a single document file. Once you confirm, I will be ready to review and provide feedback on the content you've created specifically regarding server-side and client-side validation.

**Comment by utsavtilava** [comment]
And also, @bsanevans , could you please share a reference URL on how to structure content using? This would be helpful for me to ensure consistency in my writing.

**Comment by kaitohm** [comment]
@utsavtilava Here are the steps for creating a Tutorial: https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial/ You will also find other resources about making a Tutorial in the team handbook:

<img width="1066" alt="Screenshot 2023-06-17 at 17 13 26" src="https://github.com/WordPress/Learn/assets/49054298/f8dfb883-6de0-4101-bb4c-89e67fd29827">

If you haven't done so yet, then you'll want to start by submitting a [tutorial presenter application](https://learn.wordpress.org/tutorial-presenter-application/).

I've also reached out for experienced Subject Matter Experts and Content Creators to assist with the creation in this Slack thread: https://wordpress.slack.com/archives/C02RW657Q/p1686291641083529

**Comment by kaitohm** [comment]
# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by courtneyr-dev** [comment]
# Topic Description

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [ ] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [ ] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [ ] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
Hi @utsavtilava I think this would make a great topic for either an online workshop or a tutorial, or even both. 

One comment I do have is that I notice in your slides you don't have any specific examples of Server-Side or Client-Side Validation in WordPress. I think adding some code examples to the content would be really helpful, as it would show folks how to implement the theory in the real world.

**Comment by DHLeCommerceAsia** [comment]
Hello @jonathanbossenger 

Thank you for your feedback.

Can you please check again, I have attached example slides in sheet.

**Comment by utsavtilava** [comment]
Hello @jonathanbossenger 

Thank you for your feedback.

Can you please check again, I have attached example slides in sheet.

**Comment by jonathanbossenger** [comment]
Hi @utsavtilava I'm not sure if I am looking at the correct slides, but I don't see any code examples in the slides linked above (this is the URL I am looking at: https://docs.google.com/presentation/d/1UKi7EdS17mxyAidBsQ8X3M7oZ8naDz2s-d4QiGl_s34/edit?usp=sharing)

**Comment by utsavtilava** [comment]
Hello @jonathanbossenger 

I have atteched both screenshot which i am added in slide. Can you please have a look into this.
Let me know if you have any question or changes.

**Server Side Validation :** 

![Screenshot 2023-08-28 at 2 24 03 PM](https://github.com/WordPress/Learn/assets/45058029/88cb9cf7-6ad1-4d71-b013-3eedf6f0ecca)

**Client Side Validation :** 
![Screenshot 2023-08-28 at 2 24 15 PM](https://github.com/WordPress/Learn/assets/45058029/29d6c9f3-960c-4b3d-b7fe-b1413dfdfad0)

**Comment by jonathanbossenger** [comment]
Hello @utsavtilava 

Thanks for the update. What I was hoping for was more detailed example code using the core WordPress functions & APIs, HTML attributes, and JavaScript functions you are describing, which relate to the content in the slides.

Below are some examples of what I'm looking for when I review this presentation:
 - In slide 3 you talk about some of the [sanitization](https://developer.wordpress.org/apis/security/sanitizing/) functions like sanitize_text_field or sanitize_email. It would be useful to show an example of how these functions would work.
- In slide 5 you talk about some of the possible [validation](https://developer.wordpress.org/apis/security/data-validation/) functions like is_email. Again, it would be useful here to show an example of how this function works.
- In side 10 you talk about HTML form field validation using HTML5 form validation attributes. It would be useful here to show how they are applied to a form field, and then what happens on the form when it is rendered.
- In slide 11 you talk about JavaScript Validation, it would be great if you could include a code snippet of what this could look like, and how you validate the data in JavaScript.

So the content in the slides is the theory behind these topics, but to really help the learner understand what you are presenting, it would be great if you could show some actual examples of the functionality you are describing. 

Given that you are planning to convert the slides into a recorded tutorial video, it might be easier to do this in a text or markdown format, where you can include these code examples to go along with the theory. 

I also note that for your Server Side Validation example, you have linked to a jQuery Validation Plugin, but this is client-side validation. It even says it on the site "This jQuery plugin makes simple clientside form validation easy". 

Last note, If you can, I would include both plain JavaScript solutions as well as jQuery-based ones. Many developers are moving away from using jQuery. Plain JavaScript currently can do much of what we used to need jQuery for so if it's possible without jQuery, I would show that as well.

**Comment by Piyopiyo-Kitsune** [comment]
Is server side / client side validation a topic that will come up in a developer learning pathways @jonathanbossenger ?

**Comment by jonathanbossenger** [comment]
Most, if not all, of this content, is covered in [module 9 of the beginner developer learning pathway](https://github.com/WordPress/Learn/issues/1984#module-09), so I think it's safe to close this out for now.

If we get new information we want to use to add lessons to that module, we can create new issues for that.
