### ISSUE TITLE
Learn WordPress Content Feedback - Content translation issue

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/Learn#1627]
# Feedback Details - a content translation issue on the 404 page in Hi domain URL.
- Content title:
- Content URL: https://hi.wordpress.org/documentation/article/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: Yes, Currently showing "उफ़! यह पेज ’t नहीं मिल सकता हैं।.".  it should be "यह पृष्ठ मौजूद नहीं है।" when 404 page in Hindi domain.

Write a description of your feedback here: I have added a page screenshot with the current transition content issue and solution text.

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published
![image](https://github.com/WordPress/Learn/assets/23701579/66de7d6f-05e9-4a49-bf70-eba17a3a447b)
![image](https://github.com/WordPress/Learn/assets/23701579/836d2026-3fe4-4dcf-97d7-0e86b7b16bd8)

**Comment by jonathanbossenger** [comment]
Hey @sumitsinghwp it looks like this is an issue on the Documentation site, so it would be best to connect with the [docs team](https://make.wordpress.org/docs/), as they manage the docs sites. I am closing this issue as it's not related to learn.wordpress.org
