### ISSUE TITLE
Learn WordPress Content Feedback - Image highlight incorrect

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1628]
# Feedback Details
- Content title: Part 2: Personalized Site Design with Full Site Editing and Theme Blocks
- Content URL: https://learn.wordpress.org/lesson/the-query-loop-block/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: error

Write a description of your feedback here:

In the Block Toolbar Options/Display Options section the image is wrong. It has highlighted the Grid View icon in a red box rather than the display settings icon.

_This feedback was submitted in ticket 159234._

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by nikonikobsan** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): Yes
- What should happen next to apply the feedback?: Replace the image under Block Toolbar Options > Display Settings to the screenshot below:

<img width="361" alt="Screenshot 2023-08-10 at 17 42 20" src="https://github.com/WordPress/Learn/assets/130729551/bfedda0b-cc29-4228-92b3-38a09fc1058b">
