### ISSUE TITLE
Add locale code to URL structure

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1629]
I'm bringing this Slack conversation into a GitHub issue: https://wordpress.slack.com/archives/C01KC5VDQBC/p1686295808105149

We're looking to include the two-letter locale code into a content's URL structure systematically. Currently, we manually include it in the slug:
* https://learn.wordpress.org/lesson-plan/hi-dashboard-overview/

We'd like to change this to:
* https://learn.wordpress.org/lesson-plan/hi/dashboard-overview/

This needs to be set up for the custom post types: Tutorials, and Lesson Plans

This also needs to be implemented for Sensei Courses.

Once the structure is in place, I can go through and update content we've already published.

**Comment by unprintedch** [comment]
This will be fixed with the multilingual plugin? Should we find a solution? Or could we change the priority?

**Comment by kaitohm** [comment]
Yeh, this will be resolved with the translation plugin. We can close this one in favor of #2231 .
