### ISSUE TITLE
Meeting Agenda June 13, 2023

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1630]
This week’s meeting will be held in the APAC timezone on Tuesday, June 13, 2023, at 07:00 UTC. @Piyopiyo-Kitsune will be hosting.

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- June 13 – [Nahid Sharif Komol](https://profiles.wordpress.org/nahidsharifkomol/)
- June 20 – [Sumit Singh](https://profiles.wordpress.org/sumitsingh/)
- June 27 – [jominney](https://profiles.wordpress.org/jominney/)
- July 4 - Need Volunteer

**2. Looking for feedback**

- [Recap and Next Steps: Training Team Onboarding](https://make.wordpress.org/training/2023/06/03/recap-and-next-steps-training-team-onboarding/)
- [Marketing and Communications is looking for what important things/features to highlight in the upcoming 6.3 release](https://wordpress.slack.com/archives/C02RW657Q/p1686336271463589)
- New Learn WordPress website designs [have been shared ](https://wordpress.slack.com/archives/C04U953K77A/p1686133148473099)

**3. Looking for volunteers**

- [Come join the Training Team as a Translation Coordinator (Faculty role)](https://make.wordpress.org/training/2023/06/05/come-join-the-training-team-as-a-translation-coordinator-faculty-role/)
- https://github.com/WordPress/Learn/issues/1577 - Please indicate interest in the GitHub issue
- [WordPress Contributor Mentorship Program: Pilot Program Proposal](https://make.wordpress.org/project/2023/05/17/wordpress-contributor-mentorship-program-pilot-program-proposal/): Each team has been asked to devote at least one team member. Would any Faculty like to volunteer?
- [Team Meeting Hosts](https://make.wordpress.org/training/handbook/training-team-how-to-guides/hosting-training-team-meetings/#hosting-team-meetings) and [Coffee Hour Hosts](https://make.wordpress.org/training/handbook/training-team-how-to-guides/hosting-training-team-meetings/#hosting-coffee-hours)
- WordCamp US Contributor Day

**4. Other news**

- [Learners can now submit feedback when completing a course](https://make.wordpress.org/training/2023/06/09/learners-can-now-submit-feedback-when-completing-a-course/)
- The [WordCamp Europe Contributor Day 2023 Recap](https://make.wordpress.org/training/2023/06/08/wordcamp-europe-contributor-day-2023/) is out!
- [Analysis and results of the Individual Learner Survey](https://make.wordpress.org/training/2023/05/30/analysis-of-the-individual-learner-survey-results/) has finally been published 🎉 Please leave your comments on the post. This data and discussions will be a big factor the team will consider as we prioritize our activities from here on.
- [Information Sources for 6.3](https://make.wordpress.org/training/2023/06/07/information-sources-for-6-3/) is now published to help us prepare for the upcoming release.
- Synchronous/Asynchronous Contributor Hour. Please add what dates and times work best for you [in this survey](https://rallly.co/p/U1X6xZtgedQN).
- [The Training Team is officially part of the 6.4 release](https://make.wordpress.org/core/2023/06/05/wordpress-6-4-development-cycle/)

## 3. Content published in the last week

- **Tutorials**
  - [Using Page Templates](https://learn.wordpress.org/tutorial/templates/)
- **Lesson Plans**
  - [ទិដ្ឋភាពទូទៅនៃផ្ទាំងព័ត៌មាន](https://learn.wordpress.org/lesson-plan/kh-dashboard-overview/)

## 4. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

- **Tutorials**
  - https://github.com/WordPress/Learn/issues/1579
  - https://github.com/WordPress/Learn/issues/1419
  - https://github.com/WordPress/Learn/issues/1551
  - https://github.com/WordPress/Learn/issues/1583
- **Lesson Plans**
  - https://github.com/WordPress/Learn/issues/739
- **Courses**
  - https://github.com/WordPress/Learn/issues/1453
- [**Translated Content**](https://github.com/orgs/WordPress/projects/104/views/10?filterQuery=label%3A%22Needs+Translation+Reviewer%22+status%3A%22Review+in+Progress%22)
  - https://github.com/WordPress/Learn/issues/1130 
  - https://github.com/WordPress/Learn/issues/1133 
  - https://github.com/WordPress/Learn/issues/1535 
  - https://github.com/WordPress/Learn/issues/1488 
  - https://github.com/WordPress/Learn/issues/1508
  - https://github.com/WordPress/Learn/issues/1356 

## 6. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by webtechpooja** [comment]
Recap post - https://make.wordpress.org/training/2023/06/19/training-team-meeting-recap-13th-june-2023/
