### ISSUE TITLE
Meeting Agenda June 20, 2023

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1634]
This week’s meeting will be held in EMEA/AMER timezone on Tuesday, June 20, 2023, at 16:00 UTC, and @webtechpooja will be hosting.

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- June 20 – [Sumit Singh](https://profiles.wordpress.org/sumitsingh/)
- June 27 – [jominney](https://profiles.wordpress.org/jominney/)
- July 4 - Need Volunteer
- July 11 - [Nahid Sharif Komol](https://profiles.wordpress.org/nahidsharifkomol/)

**2. Looking for feedback**

- New Learn WordPress website designs [have been shared ](https://wordpress.slack.com/archives/C04U953K77A/p1686133148473099) 
- Let’s re-evaluate how we currently host our meetings
  - EMEA/AMER meetings Currently seeing low synchronous engagement in the past few months
  - Team members are joining APAC meeting async and providing their feedback
  - Unable to find hosts or co-hosts for EMEA/AMER
  - Can we run a Global meeting instead of two (APAC and EMEA/AMER) - if needed, we can reconsider meeting time and Day
  -  1 Coffee hour for EMEA, 1 Coffee hour for APAC, 1 Global meeting
- Weekly Roundup of what happened published on Monday, so we can focus our meetings around what needs to be created, reviewed, or discussed, and meetings can be more engaging. 
- [Brainstorm & Table Lead – WordCamp US 2023 Contributor Day](https://make.wordpress.org/training/2023/06/19/brainstorm-table-lead-wordcamp-us-2023-contributor-day)

**3. Looking for volunteers**

- Audit and Translate Learn WordPress courses  - As part of the Contributor Mentorship Program, we need to review the following course on priority, 
  - [Open source basics](https://learn.wordpress.org/course/open-source-basics-and-wordpress/)
  - [How Decisions Are Made in the WordPress Project](https://learn.wordpress.org/course/how-decisions-are-made-in-the-wordpress-project/)
  - [Community Meeting Etiquette](https://learn.wordpress.org/course/community-meeting-etiquette/)
  - [Writing in the WordPress Voice](https://learn.wordpress.org/course/writing-in-the-wordpress-voice/)
  - [Basic Principles of Conflict Resolution](https://learn.wordpress.org/course/basic-principles-of-conflict-resolution/)
- [Come join the Training Team as a Translation Coordinator (Faculty role)](https://make.wordpress.org/training/2023/06/05/come-join-the-training-team-as-a-translation-coordinator-faculty-role/)
  - Gujarati Translation Coordinator - [Chetan Prajapati](chetan200891)
  - Indonesian Translation Coordinator - [Nadia Maya Ardiani](https://profiles.wordpress.org/ardianimaya/)
  - Italian Translation Coordinator -[Margherita Pelonara](https://profiles.wordpress.org/margheweb/)
  - French Translation Coordinator - [Jenny Dupuy](https://profiles.wordpress.org/jdy68/)
- Creating guiding documents / advising on accessibility - Looking for a volunteer, who can work on a handbook page that has an accessibility checklist that can be used by content creators, editors, and meetup note-takers.
- https://github.com/WordPress/Learn/issues/1577 - Please indicate interest in the GitHub issue
- [WordPress Contributor Mentorship Program: Pilot Program Proposal](https://make.wordpress.org/project/2023/05/17/wordpress-contributor-mentorship-program-pilot-program-proposal/): Each team has been asked to devote at least one team member. Would any Faculty like to volunteer?
- [Team Meeting Hosts](https://make.wordpress.org/training/handbook/training-team-how-to-guides/hosting-training-team-meetings/#hosting-team-meetings) and [Coffee Hour Hosts](https://make.wordpress.org/training/handbook/training-team-how-to-guides/hosting-training-team-meetings/#hosting-coffee-hours)
- [High priority content to translate](https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/high-priority-content-to-translate/) - We have created this based on past interest and pick. We will update the content list when the Learning Paths have been finalized.

**4. Other news**

- Time change Update on Dev-Squad meeting times [here](https://make.wordpress.org/training/2023/03/10/dev-squad-update-triage-sessions-planning/#comment-3897). dev-squad meetings will move to 07:00 UTC on Thursdays, starting next Thursday, 22 June 2023.
- [Learners can now submit feedback when completing a course](https://make.wordpress.org/training/2023/06/09/learners-can-now-submit-feedback-when-completing-a-course/)
- The [WordCamp Europe Contributor Day 2023 Recap](https://make.wordpress.org/training/2023/06/08/wordcamp-europe-contributor-day-2023/) is out!
- [Information Sources for 6.3](https://make.wordpress.org/training/2023/06/07/information-sources-for-6-3/) is now published to help us prepare for the upcoming release.
- Synchronous/Asynchronous [Contributor Hour](https://make.wordpress.org/training/handbook/training-team-how-to-guides/contributor-hour/). Please add what dates and times work best for you [in this survey](https://rallly.co/p/U1X6xZtgedQN).
- [The Training Team is officially part of the 6.4 release](https://make.wordpress.org/core/2023/06/05/wordpress-6-4-development-cycle/)

## 3. Content published in the last week

- **Tutorials**
  - [How to use headings for accessibility and SEO](https://learn.wordpress.org/tutorial/using-headings-for-accessibility-and-seo/)
  - [Advanced Multisite Management](https://learn.wordpress.org/tutorial/advanced-multisite-management/)
  - [Using the block editor: Tips and shortcuts for efficiency](https://learn.wordpress.org/tutorial/using-the-block-editor-tips-and-shortcuts-for-efficiency/)

## 4. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

- **Tutorials**
  - [Embedding media and third-party content on your website](https://github.com/WordPress/Learn/issues/1616)
  - https://github.com/WordPress/Learn/issues/1579
  - https://github.com/WordPress/Learn/issues/1419
  - https://github.com/WordPress/Learn/issues/1551
  - https://github.com/WordPress/Learn/issues/1583

- **Lesson Plans**
  - https://github.com/WordPress/Learn/issues/739

-  **Courses**
   - https://github.com/WordPress/Learn/issues/1453

-  **[Translated Content](https://github.com/orgs/WordPress/projects/104/views/10?filterQuery=label%3A%22Needs+Translation+Reviewer%22+status%3A%22Review+in+Progress%22)**
   - https://github.com/WordPress/Learn/issues/1130
   - https://github.com/WordPress/Learn/issues/1133
   - https://github.com/WordPress/Learn/issues/1535
   - https://github.com/WordPress/Learn/issues/1488
   - https://github.com/WordPress/Learn/issues/1508

## 5. Project updates
 No project is active right now.

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kaitohm** [comment]
> New Learn WordPress website designs [have been shared](https://wordpress.slack.com/archives/C04U953K77A/p1686133148473099)

Just noting the bottom of this post has some more details, too: https://make.wordpress.org/design/2023/06/19/design-share-jun-5-jun-16/ (Originally shared in [this Slack comment](https://wordpress.slack.com/archives/C02RW657Q/p1687165198517699))

**Comment by webtechpooja** [comment]
Recap Notes: https://make.wordpress.org/training/2023/06/22/training-team-meeting-recap-20th-june-2023/
