### ISSUE TITLE
Online Workshop - Create a four page WordPress website: Explore Plugins + Contact Forms

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1635]
# Event Details
- Title: Create a four page WordPress website: Explore Plugins + Contact Forms
- Description: 
Details
Welcome to the series, Create a Four Page WordPress Website! This series is geared toward small businesses, but anyone who would like to create a four page WordPress website using a block theme is welcome to join us.

This is a rescheduled event.

What we covered previously:

So far during this series, learners have:

installed a block theme of their choice,
found and downloaded fonts of their choice,
installed fonts using a plugin,
styled their website using the WordPress Stylebook,
created a header,
created a footer,
brainstormed quality content,
explored templates and template parts
This is session #5 - Explore Plugins and Add a Contact Page

By the end of today’s session, you will learn how to vet plugins (to make sure they don't break your website!), learn which plugins work with your block themes (and which don't!), and add a contact plugin so that you protect your email address from spam.

What if I missed a previous session?
No worries! You are still welcome to attend and learn about this topic.

We look forward to seeing you there.

Audience: Users
Level: Beginners
Language: English with Zoom Captions Provided
RSVP link available after sign-up.
- Target Audience:  Users
- Date: June 22, 2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/294215062
- Co-host: Kathryn Presner
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by kaitohm** [comment]
@wparasae Have the final steps been completed for this workshop? Can the issue be closed?
