### ISSUE TITLE
Topic Idea: TOPIC TITLE

### ISSUE THREAD

**Issue by Online-Cloud** [WordPress/Learn#1636]
# Details

- Topic description: 
- Learning objectives: 
- Content type: 
- WordPress version (optional): 
- Will you be creating this content?: Yes/No

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.

# Vetting Checklist for SMEs
Please follow the team handbook: [Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/).

- [ ] Set a Priority label
- [ ] Assess topic details, and provide feedback as necessary.
- [ ] Move issue to "Vetted Topics" status

**Comment by jonathanbossenger** [comment]
Closing as spam
