### ISSUE TITLE
Online Workshop - The WordPress database

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1638]
# Event Details
- Title: The WordPress database
- Description: In order to extend WordPress, a developer needs to have a foundational understanding of the WordPress database as well as knowledge of how to interact with and manipulate the data stored there. In this session, we'll take a high-level overview of the WordPress database, review the default ways to interact with the core schema and data, as well as learn how to add and use custom tables for additional functionality. 
- Target Audience: Developers
- Date: 2023-06-22 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/294280261
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
Jonathan, if you still need a co-host I can be available to help out.

**Comment by jonathanbossenger** [comment]
@SierraTR that would indeed be helpful, thank you.

**Comment by SierraTR** [comment]
Very nice!
We had 35 attendees today.

**Comment by jonathanbossenger** [comment]
Wow, thanks, Tracy. It seems folks like these deep-dive topics.

**Comment by SierraTR** [comment]
I'm sure you have some of them attending each session to see what is next. You'll have to come up with a name for your developer 'groupies.' 

Most of the sessions on Learn seem to be directed toward the newer users who are trying the grasp the block theme/FSE concepts. You appear to be the only one that consistently publishes developer content that digs into the actual code - at least you're the only one who I have noticed. 

I think your efforts toward a 'developer track' for Learn is a great idea - and a huge project. It would be amazing to find some sort of super-website project or plugin development project that incorporated all of your track concepts and could be continued throughout a 'developer course'. Move from one concept to another with a couple of introductory workshops and then, using the introductory learning add that concept into the main project. Might even be able to incorporate Git and branching into the mix. 

All it takes is time, money, focus, energy, vision, knowledge, etc., etc.  As you alluded to at the beginning of today's session, you only really learn something when you are able to accurately teach it.

**Comment by jonathanbossenger** [comment]
> It would be amazing to find some sort of super-website project or plugin development project that incorporated all of your track concepts and could be continued throughout a 'developer course'.

If you're interested, this is something we're working on as part of the Learning Pathways project. 

https://github.com/WordPress/Learn/issues/1577

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/06/23/the-wordpress-database/
