### ISSUE TITLE
Tutorial - Installing Node.js and npm for local WordPress development

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1639]
# Topic Description
Node.js is a [cross-platform](https://en.wikipedia.org/wiki/Cross-platform), [open-source](https://en.wikipedia.org/wiki/Open-source_software) server environment that can run on most popular operating systems. Node.js lets developers use JavaScript to write command line tools and for [server-side scripting](https://en.wikipedia.org/wiki/Server-side_scripting). When you install Node.js on your operating system, it comes preinstalled with npm, a command line tool that allows developers to share and use software packages as dependencies in their own projects.   

While not specifically a requirement for WordPress development, if you want to develop blocks, contribute to Gutenberg, or use modern tools like wp-env or wp-now, you will need to have Node.js and npm installed on your computer.

In this tutorial, you will learn how to install Node.js and npm on macOS, Ubuntu, and Windows. 

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [The information for this tutorial will be extracted from the Create Block tool tutorial ](https://learn.wordpress.org/tutorial/using-the-create-block-tool/)

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
WIP script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/fundamentals-nodejs-npm.md

**Comment by courtneyr-dev** [comment]
Love that this is happening. I remember my early days getting stuck figuring out what to do to get set up.

**Comment by jonathanbossenger** [comment]
Tutorial video for review:


https://github.com/WordPress/Learn/assets/180629/9dd91548-01ac-4067-af66-9a257b063954

**Comment by digitalchild** [comment]
Great, easy to follow tutorial @jonathanbossenger. I would maybe suggest brew in there as well? As that is available across windows, mac and Linux to install nvm and manage updates to nvm as well.

**Comment by jonathanbossenger** [comment]
@digitalchild thanks for the review. 

> As that is available across windows, mac and Linux to install nvm and manage updates to nvm as well.

For Windows, do you mean via [WSL](https://docs.brew.sh/Installation#linux-or-windows-10-subsystem-for-linux)? I don't see any other way to install homebrew on Windows. 

While I agree that installing homebrew on Mac certainly makes things easier on a mac, I'm trying to limit the amount of things that need to be installed, especially for someone new to the terminal. Hence going with the one copy/paste command to install nvm on mac and Linux, and one copy/paste to install choco, and then one choco install command on Windows.

Those that already have homebrew installed can probably manage all this without needing this beginner tutorial.

**Comment by drussell17** [comment]
I had set up a local dev environment for use with trunk a few months ago.
https://make.wordpress.org/core/handbook/tutorials/installing-wordpress-locally/from-svn/
The above page was what I attempted to follow.  After struggling with it I contributed the section "For those using Windows 11".  AFAIK I didn't use Powershell or a package manager as described in your video.  (I do have Powershell installed and NGINX is probably there as well from earlier local web server installs.)  
Also please note that at the time of my install V14 of NodeJS was required.  So I'm not confident that procedure outlined in your video would work with trunk.

**Comment by jonathanbossenger** [comment]
@drussell17 thanks for the feedback

> So I'm not confident that procedure outlined in your video would work with trunk.

That's the reason I recommend installing nvm, so that one can then install and use node version 14 if one needs to set up WordPress trunk for any reason. 

It's also worth noting that the core team are working on updating the requirements to [Node.js to 18 and npm to 9](https://github.com/WordPress/gutenberg/pull/48950).

**Comment by digitalchild** [comment]
Hi @jonathanbossenger 

Thanks for the response, that makes total sense. Are there any tutorials on using WSL, or maybe you could add some links in the tutorial resources? To WSL & Brew?

**Comment by westnz** [comment]
Clearly explained, Jonathan! Learning outcomes are achieved. I like the fact that you have catered for various users.

**Comment by jonathanbossenger** [comment]
> Are there any tutorials on using WSL

Not yet, but I am gathering data as to how valuable this would be. 

I'm of the opinion that installing and configuring WSL is a bit more of an "intermediate developer" thing, and at the moment I'm still focusing on the [beginner-level content](https://make.wordpress.org/training/2023/03/29/introduction-to-wordpress-development-syllabus/).

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/tutorial/installing-node-js-and-npm-for-local-wordpress-development/
