### ISSUE TITLE
Online Workshop - Exploring global styles and the stylebook (Site Editor)

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1640]
# Event Details
- Title: Exploring global styles and the stylebook (Site Editor)
- Description: 

Global styles help users change the overall style of their website. It lets you avoid the hassle of editing individual blocks or pages. With Global styles, users have improved control over the layout and design of their websites.

In WordPress 6.2, a new feature has been added to the global styles interface that allows users to preview every block that can be inserted into their site.

- Target Audience: Users
- Date: 28 June 22:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/294320486/?isFirstPublish=true
- Co-host: Kathryn Presner
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I can co-host for you again, Wes.

**Comment by westnz** [comment]
Hey @SierraTR thank you very much! I just got confirmation that Katryn Presner will co-host this one with me before I read your message.  Next time! 😉

**Comment by westnz** [comment]
https://wordpress.tv/2023/06/28/exploring-global-styles-and-the-stylebook-site-editor/
