### ISSUE TITLE
Learn WordPress Content Feedback - Page with incorrect content

### ISSUE THREAD

**Issue by jazbek** [WordPress/Learn#1643]
# Feedback Details
- Content title: Custom post types and capabilities
- Content URL: https://learn.wordpress.org/tutorial/custom-post-types-and-capabilities/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: Error

Write a description of your feedback here:

The page described above has mostly the same content as another page, [Developing with user roles and capabilities](https://learn.wordpress.org/tutorial/developing-with-user-roles-and-capabilities/). I would expect this page to have completely different content, since it is a different topic.

The different elements are:

- Title
- Video
- Comprehension questions (though the questions listed seem to make more sense if this article was "Developing with user roles and capabilities")

The same elements are:

- Learning outcomes
- Everything from Introduction down (though strangely, this article seems to have some typos and author notes cleaned up, which probably should have been applied to the other article instead)

---

# Feedback Report Checklist:
- [x] Feedback validated
- [x] Update proposed
- [x] Update reviewed
- [x] Update published

**Comment by nikonikobsan** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): YES
- What should happen next to apply the feedback?: 

The content and video on this Tutorial match: https://learn.wordpress.org/tutorial/developing-with-user-roles-and-capabilities/

The content and video on this Tutorial DO NOT MATCH: https://learn.wordpress.org/tutorial/custom-post-types-and-capabilities/

Please update "Learning Outcomes" and everything from "Introduction" down to match the video content.

The feedback submitter noticed there are some typos and notes which were tidied up on https://learn.wordpress.org/tutorial/custom-post-types-and-capabilities/, which should have been applied to https://learn.wordpress.org/tutorial/developing-with-user-roles-and-capabilities/.

Summary:
1. Copy and apply the content from https://learn.wordpress.org/tutorial/custom-post-types-and-capabilities/ to https://learn.wordpress.org/tutorial/developing-with-user-roles-and-capabilities/
2. Rewrite the "Learning Outcomes" and all content from "Introduction" down on https://learn.wordpress.org/tutorial/custom-post-types-and-capabilities/ to match the actual video.

**Comment by jonathanbossenger** [comment]
Hi @jazbek and @nikonikobsan.

Thank you for raising this issue, I'm not quite sure what happened here, but I can only assume it was a copy/paste error.

I've updated the content with the correct information.
