### ISSUE TITLE
Layout for the single course and course archive pages

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#165]
This is the current single course page view: https://learn.wordpress.org/course/publishing-with-wordpress/
And this is the current course archive page view: http://learn.wordpress.org/courses/

Those are default page layouts provided by Sensei. We need to customise those so they are simpler and generally look better.

### Single course page
This page really just needs to have the "Lessons" bit changes to essentially be a list of links (kind of like [this example](https://wpcourses.com/syllabus-blogging-for-beginners/), except we don't use modules). We can also remove the "Lessons" heading and just have the links appear below the content. I hacked around in the browser inspector and made this, which is along the lines of what we need here:

![Screenshot 2020-12-10 at 13 54 05](https://user-images.githubusercontent.com/1543143/101707058-1f05a800-3a93-11eb-8af6-a62a0e32676c.png)

### Course archive page
This also needs to be simplified and improved. I'm thinking that we can have the courses display in a grid view with cards similar to the way we display [lesson plans](https://learn.wordpress.org/lesson-plans/). The courses will have a short text description (the Publishing with WordPress course has one already as an example on that current page) and the metadata to be displayed is what you already see there - the number of lessons and the number that have been completed.

**Comment by azhiya** [comment]
I like this idea (single course view). It's very much in line with most learning platforms.

**Comment by coreymckrill** [comment]
#168 takes care of the single course page. For the Course archive page, however, if we want it to resemble what we're doing with Lesson Plans, I think we should hold off until a solution for #153 is built and resolved.

**Comment by hlashbrooke** [comment]
Great!

For the course archive - we don't need the filters and other elements from the lesson plan archives - I was meaning purely the cards that the lesson plans currently use. As far as I can tell we're still going to stick with those card designs in #153, so we could copy those across to the courses here.

**Comment by coreymckrill** [comment]
The preferred design for the Lesson Plans archive now only has one column of cards:
https://user-images.githubusercontent.com/2846578/101833707-63329000-3b07-11eb-9794-ea0aa02a02e1.png

Even if we aren't going to have a sidebar with filters on the Courses archive, I'd prefer to standardize the markup used for the two CPTs, so I'll need to get that sorted before finishing this.

**Comment by hlashbrooke** [comment]
Ah right! In that case, yeah - rather get them done together with standardised markup.

**Comment by hlashbrooke** [comment]
@coreymckrill For the single course page, could you also please remove the next/previous course navigation at the bottom: https://learn.wordpress.org/course/publishing-with-wordpress/

Also, it would be great if we could have a heading at the top of the single course page like the single workshops have - right now, you have to look at the small breadcrumbs text to see the course title.
