### ISSUE TITLE
Japanese translation for Online Workshop "How to translate content for Learn.WordPress.org"

### ISSUE THREAD

**Issue by mayukojpn** [WordPress/Learn#1650]
# Details
- Link to original content: https://wordpress.tv/2023/06/20/how-to-translate-content-for-learn-wordpress-org/
- Link to translated content: https://amara.org/videos/i6rHS9ChxeHy/info/how-to-translate-content-for-learnwordpressorg/
- Link to original content GitHub issue: 
- Language you'll be translating to: Japanese
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
Will you be translating the subtitles for this video, @mayukojpn ? Or would you like to host this Online Workshop in Japanese?

**Comment by kaitohm** [comment]
I'm closing this for now. Please reopen if you're interested in translating this content.
