### ISSUE TITLE
Learn WordPress Content Feedback - Link to outdated tag list

### ISSUE THREAD

**Issue by mayukojpn** [WordPress/Learn#1651]
# Feedback Details
- Content title: Content Translator Onboarding
- Content URL: https://make.wordpress.org/training/handbook/getting-started/content-translator-onboarding/#does-content-already-exist-in-your-locale
- Are you reporting an error (such as outdated information), or providing improvement ideas?: an error

Write a description of your feedback here:
The link "[list of locale labels in GitHub](https://github.com/WordPress/Learn/labels?q=%5Bpolyglots%5D)" refers outdated page. It should be the link to the list of tags including `[locale]` instead: https://github.com/WordPress/Learn/labels?q=%5Blocale%5D+

---

# Feedback Report Checklist:
- [ ] Feedback validated
- [ ] Update proposed
- [ ] Update reviewed
- [ ] Update published

**Comment by j-admintech** [comment]
Test

**Comment by nikonikobsan** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): No
- What should happen next to apply the feedback?: This looks like it has been fixed already.
