### ISSUE TITLE
Bug report: Video player proportions for the "Contribute" page

### ISSUE THREAD

**Issue by felipevelzani** [WordPress/Learn#1660]
## Description

The player proportions for videos on steps 3 and 4 need to be corrected for [the Contribute page](https://learn.wordpress.org/contribute/). They are small and not aligned with step 5.

<img width="816" alt="Markup 2023-06-27 at 16 54 51" src="https://github.com/WordPress/Learn/assets/40555737/a2c6d1b3-e3c4-42c4-a7b7-88eb8eca4091">

## Step-by-step reproduction instructions

1. Go to [the Contribute page](https://learn.wordpress.org/contribute/).
2. Scroll down to steps 3 and 4, and see the difference compared with step 5.

## Expected behaviour

Show with the same dimensions (width and height) added to step 5.

## Actual behaviour

It is too small, and even the player controls aren't showing as expected because of the width.

<img width="1106" alt="Screenshot 2023-06-27 at 21 22 13" src="https://github.com/WordPress/Learn/assets/40555737/515591c2-14db-4d2c-9339-d2fe6a9c8889">

## Environment information

- Browser(s) are you seeing the problem on: Chrome Version 114.0.5735.133 (Official Build) (arm64)
- Device you are using and operating system: MacBook Pro (Apple M2 Pro) - macOS 13.4 (22F66)

**Comment by cynthianorman** [comment]
Just a note on the difference between #5 and the other 2 iframes (#3 & #4). The video for #5 looks like it was embedded using a different method. See screenshot. https://snipboard.io/Zpwihc.jpg

**Comment by jonathanbossenger** [comment]
In reviewing this page during dev-squad triage, the third video is added to the page via a shortcode, whereas the first two are added as video blocks. So we should either download and add that third video, or use the shortcode method for the first two.

**Comment by cynthianorman** [comment]
I can work on this one

**Comment by adamwoodnz** [comment]
Closing as these videos no longer exist on the redesigned page.
