### ISSUE TITLE
Online Workshop - WP-CLI for PHP developers

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Learn#1664]
# Event Details
- Title: WP-CLI for PHP developers
- Description: When was the last time you tested code in production? Your own website doesn’t count.
Conversations with the Terminal, or WP-CLI for PHP developers, is the sequel of WordPress through the Terminal workshop, focusing on a set of commands and tools useful for PHP developers.
This is not just a live demo of WP-CLI commands. This is zooming out and seeing WP-CLI in collaboration with other tools in the context of PHP developer needs and everyday tasks. We’ll probably release the Kraken as well.
- Target Audience: Developers and system admins
- Date: 12 July 2023 at 08:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/294625245
- Co-host: @jonathanbossenger 
- Other info: This session has been changed from “WordPress through the Terminal” to its current title/description. I am doing the admin work to get this Workshop published, but I cannot co-host due to my timezone.

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
@courtney-pk I should be able to co-host this workshop.

**Comment by courtney-pk** [comment]
Thank you @jonathanbossenger! [I have drafted the event on Meetup.com](https://www.meetup.com/learn-wordpress-online-workshops/events/294625245/), awaiting Milana's confirmation before publishing.

I will process the video and captions after the session, so please let me know when the recording is complete. Thanks!

**Comment by jonathanbossenger** [comment]
Thank you @courtney-pk 

As you are wrangling this, could I ask you to check with Milana if she has any specific requirements from a co-host? 

I know some folks like a co-host who is super chatty and asks questions if there aren't any, whereas others prefer a co-host to be more of a quiet administrator, performing specific tasks that they can't while presenting.

**Comment by courtney-pk** [comment]
@jonathanbossenger I will ask her and connect you in Slack!

**Comment by jonathanbossenger** [comment]
What a great workshop. Total of 18 in person attendees.

I'll work to get the video transcribed and uploaded to wp.tv tomorrow or Friday.

**Comment by courtney-pk** [comment]
@jonathanbossenger[ I uploaded the video](https://wordpress.tv/2023/07/13/wp-cli-for-php-developers/) but the captions are not quite ready. I'll share those details with you if you're able to help with the captions!

**Comment by jonathanbossenger** [comment]
Thanks @courtney-pk I've edited the captions, and uploaded them to the video. 

There's also an idea for a follow-up workshop in the meetup comments:

`I think a WP CLI session focusing on themers and plugin devs would be much appreciated.`

Not sure if Milana has scope for this, but I'll also keep it in mind as a future workshop/tutorial idea.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/07/13/wp-cli-for-php-developers/
