### ISSUE TITLE
Online Workshop - Tips and shortcuts for using the block editor & streamlining content creation

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1665]
# Event Details
**EVENT 1**
- Title: Tips and shortcuts for using the block editor & streamlining content creation
- Description: In this session, we will explore eight tips and shortcuts you could use to work faster and more efficiently in the block editor. We will also explore the various editor modes in the block editor that you can select to improve your writing or editing experience.
- Target Audience: Users
- Date: 10 July 22:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/294512825/
- Co-host: ?

**EVENT 2**
- Date: 11 July 04:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/294512871/?isFirstPublish=true
- Co-host: ?

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I can co-host for you on event 1 (10 Jul 2200 UTC)

**Comment by westnz** [comment]
Great, thank you @SierraTR

**Comment by westnz** [comment]
Published: https://wordpress.tv/2023/07/11/tips-and-shortcuts-for-using-the-block-editor-streamlining-content-creation/
