### ISSUE TITLE
Online Workshop - Common WordPress APIs: Dashboard Widgets

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1667]
# Event Details
- Title: Common WordPress APIs: Dashboard Widgets
- Description: WordPress contains an extensive list of APIs for performing common tasks across a WordPress site. From interacting with the database to creating responsive images, there's an API for practically everything. This session will be the first in a series of an introduction to the common WordPress APIs, starting with the Dashboard Widgets API.
- Target Audience: Developers
- Date: 2023-07-06 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/294525612/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by AsadPolash** [comment]
Hi There, I would like to be the co-host for your online event.

**Comment by jonathanbossenger** [comment]
Hi @AsadPolash, thank you for offering to co-host

If you haven't already, could I ask you to please read the [Co-hosting an online workshop handbook doc,](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) and complete the application at the bottom of that page?

Once you've read the handbook doc and completed that application, please leave a comment for me here.

Thanks

**Comment by AsadPolash** [comment]
Hi @jonathanbossenger 
I completed the application and I re-read the doc just to make sure.

**Comment by jonathanbossenger** [comment]
Thanks @AsadPolash. Everything looks good on this side. Thanks for offering to co-host with me on Thursday.

Besides the general guidelines around co-hosting, which I've shared with you, these are the most important tasks I need from a co-host:

- Once the workshop has started, and the recording is going, please admit any latecomers into the Zoom meeting
- Keep an eye on the chat, and let me know if I miss any important questions
- About halfway through, take a count of the total participants, as we need to report the attendee numbers afterwards
- Listen out for any folks who have background noise coming through their mics, and please mute them. This doesn't happen often, but it can be distracting.

I will start the Zoom meeting about 5 minutes before, to let you in and make you co-host of the Zoom session.

Also, please let me know if you have any questions.

**Comment by AsadPolash** [comment]
@jonathanbossenger  Thanks for considering me as the co-host. I will do my best to run this event smoothly. I understand your instructions fully. However, I do have something to say and ask.  Are you available on slack? I could really use max 5 minutes of your time. 

Thanks again. looking forward to it.

**Comment by jonathanbossenger** [comment]
Hey @AsadPolash you are welcome to DM me in Slack, and I will reply when I can. I'm not always around in the Make Slack, but I do reply to all questions.

**Comment by jonathanbossenger** [comment]
Thank you for co-hosting @AsadPolash, you did a great job.

Did you manage to get a count of how many attendees there were?

**Comment by AsadPolash** [comment]
Hi @jonathanbossenger 

First of all, thank you for accepting me as co-host. I really enjoyed it. 

To answer your question, Yes I did count all the attendees. In fact I counted with segmentation.
30 Minutes
45 Minutes (As you said)
60 Minutes, and
90 Minutes

All the time and count were sent you your Make Slack.

**Comment by jonathanbossenger** [comment]
Perfect, thank you.

I'll take the First 30 Minutes number of 25 Participants 😁 

And thank you for co-hosting, it was great having you run things for me.

**Comment by AsadPolash** [comment]
You're welcome. I would Love to do it again in future if needed.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/07/07/common-wordpress-apis-dashboard-widgets/
