### ISSUE TITLE
Mobile optimize landing page layouts

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#167]
As Learn becomes more known, we anticipate users that may be limited to using data on a mobile device to access the material.  Can we put some thought into the landing page layouts for Home, Workshops, and Lesson Plans that involve the images appearing smaller for phone breakpoints especially? 

Are there any great examples for a super limited bandwidth option as a fallback? (Like night-mode toggles for themes, but instead - low bandwidth)?

**Comment by hlashbrooke** [comment]
I did some testing and the landing pages (in fact, the whole site) works really well on mobile for all post types. I'm actually really impressed with the work done on the frontend here!

I'm going to close this issue as it's quite general, and if we notice specific things that need updating we can open new issues for each one.
