### ISSUE TITLE
Online Workshop - How to vet content topic ideas for the WordPress Training Team

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1671]
# Event Details
- Title: How to vet content topic ideas for the WordPress Training Team
- Description: A walkthrough of the Training Team's processes around vetting topic ideas
- Target Audience: Contributors
- Date:
   - July 13th ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/294536027/)) - **needs co-host**
   - July 14th ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/294536083/)) - co-host: @SierraTR 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I'll co-host with you for the one listed on the 14th - that's workable in my timezone (US Pacific).

**Comment by kaitohm** [comment]
Thanks, @SierraTR ! I've added you as a co-host 👍

**Comment by SierraTR** [comment]
We had 8 attendees for this session. Very well done, Ben. Clear, concise and well timed.

**Comment by kaitohm** [comment]
Thank you for co-hosting, Tracy. And for recording the attendance, too 🙌

**Comment by kaitohm** [comment]
The recording has been published here: https://wordpress.tv/2023/07/13/how-to-vet-content-topic-ideas-for-the-wordpress-training-team/
