### ISSUE TITLE
Content Feedback - Using the WordPress Data Layer

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1688]
## Overview
- Content title: Course: Using the WordPress Data Layer
- Content URL: https://learn.wordpress.org/course/using-the-wordpress-data-layer/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: 

## Feedback Details

Learner Feedback: See below

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by westnz** [comment]
**July Student Feedback:**

1. "Playground to view an actual demo of the example."
2. "Expand it"
3. "There is not an organized file structure.  When the example code is shown, you get lost in which part you must create the file, what kind of extension you must have, or which file you must modify, It would be very helpful to have acces to the source code.

**August Student Feedback:**

1. - make it possible to give direct feedback (e.g. a link to the GH repo [if not available: open source the content!]) - there was a dead link to https://learn.wordpress.org/docs/reference-guides/data/data-core/#getentityrecord in chapter 3 (editing) -> is spent ~30 minutes to find out that it isn't possible/dead easy to fix this with a pull request - highlight the browser console tryouts better (i.e. different background) to separate them from code - I found it confusing as I am not that super carefully reading, but focussing on code - do an advanced tutorial with CPTs that stand in relation to each other -> this is actually where the real challenge begins But in general - cudos - a great intro that makes the beginning easy. Thanks for that!
2. When utilizing the WordPress data layer, consider enhancing user experience through personalized content, optimizing site performance by reducing unnecessary data requests, and ensuring robust security measures against potential threats. Regularly assess and adapt these practices for an effective online presence.
3. in the Delete records chapter, there is no Notification component, it's been changed to Snackbarnotices, need to update the code in final example.
4. make it longer, show how to use more apis

**Comment by jonathanbossenger** [comment]
The Using the WordPress data layer course probably needs a complete revamp. 

I'm going to close this issue in favour of creating a new course to deprecate this one.

**Comment by jonathanbossenger** [comment]
Closing in favour of #2968
