### ISSUE TITLE
Workshop: Pagination breaks the filter

### ISSUE THREAD

**Issue by naokomc** [WordPress/Learn#169]
When you use the filter on a page other than the first one, the filtered URL has the pagination and doesn't return correct results.

For example, https://learn.wordpress.org/workshops/?series=&topic=&language=&captions=en_US works.
But https://learn.wordpress.org/workshops/page/2/?series=&topic=&language=&captions=en_US is not found

Steps to reproduce:

1. Go to https://learn.wordpress.org/workshops/page/2/
2. Select one of the filters that you know has at least one matched results and hit "Apply Filters"
3. You see the "Oops! That page can’t be found." error.

**Comment by coreymckrill** [comment]
🤔 So in the example links, the reason that the second one returns "Not found" is that there aren't enough workshops with English captions for the results to occupy more than one page. This makes me think that whenever a user changes the filter settings and clicks "Apply", it should load page 1 of the new results, regardless of what page they were on before...
