### ISSUE TITLE
Content Feedback - Course: Develop Your First Low-Code Block Theme

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1691]
## Overview
- Content title: Develop Your First Low-Code Block Theme
- Content URL: https://learn.wordpress.org/course/develop-your-first-low-code-block-theme/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: 

## Feedback Details

Learner Feedback
1. "Adding how to avoid conflict between block theme layout style and a user 's individual block customizations. Only color was mentioned. Some themes' layouts make it hard to customize. For example, a theme that used a block with three column was difficult to customize into one column."

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by jonathanbossenger** [comment]
Closing in favour of the work being done for learning pathways
