### ISSUE TITLE
Content Feedback -

### ISSUE THREAD

**Issue by acchang** [WordPress/Learn#1692]
## Overview
- Content title: Introduction to WordPress
- Content URL: https://learn.wordpress.org/tutorial/introduction-to-wordpress/
- Are you reporting an error (such as outdated information), or providing improvement ideas?:  Y

This is just my first stab at contributing as a reviewer/tester for WP developer training content. The fixes I suggest are nothing dramatic or urgent.

## Tutorial Review Checklist
Please tick all items you've confirmed:

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

Good tutorial, friendly host. Some of the content does not match current conditions though, since WPlocal has updated and the video is a few years old.

Timestamps:
10:45 The explanation of WordPress.com vs WordPress.org is a little confusing. "dot-com" is remote, distributed and free as a subdomain but not as only a domain. "dot-org" is open-source and fully free is the way I understood it. 
13:00 "to run wordpress locally..." It would be nice to know what is XAMPP and why choose that one over the others?
14:22 The screenshot of WPlocal is not the same. I was not sure where do I open the local app and get to the dashboard until I realized I need to turn on "One-click admin."
15:32 Advanced options no longer apply.
17:55 The "edit post" link is now at the top.
26:00 I don't think the menu is an option anymore. It looks like WP is creating pages just generates them on its own.
27:00 It's unclear where the secondary menu went from appearances; I could get it from "appearance/editor/templateparts/footerpatterns/footers" though.
30:50 there are only three themes, no "popular" option.

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by jonathanbossenger** [comment]
The content referenced is from 2021, and will probably get deprecated when we launch the new learning pathways. So editing this tutorial for updates won't make sense.
