### ISSUE TITLE
Hindi translation for Lesson Plan "Upload a Theme to the WordPress Repository"

### ISSUE THREAD

**Issue by markmemayank** [WordPress/Learn#1694]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/upload-a-theme-to-the-wordpress-repository/
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [Nincompop](https://github.com/Nincompop) [uptouplaksh](https://github.com/uptouplaksh/) 
- Other info:

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by markmemayank** [comment]
I am ready with the translation of this. Here is the link https://docs.google.com/document/d/1HHfodcEeshWqJmggmX89gTojAnBV_XHBCm8a-apTXRw/edit?usp=sharing

@webtechpooja Pls do the needful.

**Comment by Nincompop** [comment]
I reviewed the translation and As per me it is good to go.

**Comment by webtechpooja** [comment]
Great, thanks for all your contribution. @markmemayank and @Nincompop 
I'll give it a final review later today and will get back to you soon! @markmemayank

**Comment by webtechpooja** [comment]
We need one more review before the final review. @hderashri,  do you have some bandwidth to review this translation? any help is highly appreciated! thanks.

**Comment by markmemayank** [comment]
@uptouplaksh, If you can find some time to do please go ahead.
Or @saurabhmention if you could do that.

**Comment by saurabhmention** [comment]
Yeah Mayank, I go through it and looks fine for me.

**Comment by webtechpooja** [comment]
I have added a few comments, and Please check and update accordingly. 

Please go through this, We follow this Hindi glossary - https://translate.wordpress.org/locale/hi/default/glossary/

**Comment by webtechpooja** [comment]
Reviewed and published - 
https://learn.wordpress.org/lesson-plan/hi-upload-a-theme-to-the-wordpress-repository/

Thanks to all who reviewed and translated this content!
