### ISSUE TITLE
Online Workshop - Blogging with WordPress: Basics

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1696]
# Event Details
- Title: Blogging with WordPress: Basics
- Description: 

Details
Have you ever wanted to start a blog, but weren't sure how to get started with WordPress? Would you like to ask questions about blogging in a collaborative and fun environment?

If so, join us for an interactive session! This session is based around your questions

What we (might!) cover:

A place to experiment with the WordPress dashboard for free
The difference between posts and pages
Post settings & sharing on social media
Managing comments & boosting engagement
Share resources on where to find images you are free to use on your website
And more!
This session will be based and built around your user questions, so both sessions may be a little different.

Expect to share your ideas and hear the ideas of others! While we won't cover setting up a blog in WordPress step by step, we will provide resources from learn.wordpress.org to help you get setup and started with a WordPress installation on a host of your choice.

Audience: Users
Level: Beginner
Language: English - Closed captions provided by Zoom
Where: Zoom link available after you RSVP
Time Commitment: 1 hour

Please note that this session will be run 2x to cover two different time zones. You're welcome to attend the first or the second, but similar content will be shared in both.

We look forward to seeing you there!
- Target Audience: Users
- Date: July 28, 2023
- Meetup.com event link: 
- https://www.meetup.com/learn-wordpress-online-workshops/events/294668882/
- https://www.meetup.com/learn-wordpress-online-workshops/events/294668904
- Co-host: 
- Other info: 
This workshop is held 2x to cover two different timezones.

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by AsadPolash** [comment]
Hi @wparasae 
I would like to be the co-host for this online workshop.

**Comment by wparasae** [comment]
Asad has claimed the earlier of the two as cohost -- https://www.meetup.com/learn-wordpress-online-workshops/events/294668882/

If someone would like to cohost the later version of this, you are also welcome! https://www.meetup.com/learn-wordpress-online-workshops/events/294668904

**Comment by AsadPolash** [comment]
Hi @wparasae
I will be co-hosting with you on the later version too. As Saturday is my weekend, I will stay late night. So No problem with that.
