### ISSUE TITLE
Online Workshop - Overcoming Writer's Block: Planning a Blog's Content

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1697]
# Event Details
- Title: Overcoming Writer's Block: Planning a Blog's Content
- Description: 
Have you ever wanted to start a blog, but weren't sure what to write about? Or, have you ever started writing a blog, only to lose steam and interest within the first few posts?

If so, join us for an interactive planning session! This will be an interactive writer's workshop to help you get started blogging in 2023--and keep writing from July to December and beyond.

What to expect:

Brainstorm topics and create a list from which you can pull when you need inspiration throughout 2023
Explore different content types and decide what is right for you
Identify top level categories, sub-categories, and more granular tags
Schedule posts in your WordPress website to keep you going and honest
Expect to share your ideas and hear the ideas of others! While we won't cover setting up a blog in WordPress, we will provide resources from learn.wordpress.org to help you get setup and started with a WordPress installation on a host of your choice.

Audience: Users
Level: Beginner
Language: English - Closed captions provided by Zoom
Where: Zoom link available after you RSVP
Time Commitment: 1 hour

Please note that this session will be run 2x to cover two different time zones. You're welcome to attend the first or the second, but the same content will be provided in both.

We look forward to seeing you there!
- Target Audience: Users
- Date: July 26, 2023
- Meetup.com event link:
- https://www.meetup.com/learn-wordpress-online-workshops/events/294667357/
- https://www.meetup.com/learn-wordpress-online-workshops/events/294668775/
- Co-host: 
- Other info: 
This workshop will be held 2x; the content will differ slightly based on what users request.

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by AsadPolash** [comment]
Hi @wparasae 
I would like to be the co-host for this online workshop.

**Comment by wparasae** [comment]
Added! Asad is co-hosting the earlier of the two workshops: https://www.meetup.com/learn-wordpress-online-workshops/events/294667357/

We still need a cohost for the second of the two sessions if anyone is interested; otherwise, I will fly solo!
