### ISSUE TITLE
Online Workshop - Common WordPress APIs: Responsive Images

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1698]
# Event Details
- Title: Common WordPress APIs: Responsive Images
- Description: WordPress contains an extensive list of APIs for performing common tasks across a WordPress site. From interacting with the database to creating responsive images, there's an API for practically everything. This session will focus on the Responsive Images API, including a brief history of responsive images in WordPress, how the API works, and how it's used for theme development.
- Target Audience: Developers
- Date: 2023-07-13 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/294679245/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I'm available to co-host on the 13th if you still need someone.

**Comment by jonathanbossenger** [comment]
Thanks @SierraTR

**Comment by jonathanbossenger** [comment]
M: if cached, what happens if you replace the image with another of the same link/name?  does it display the old image or new?

**Comment by jonathanbossenger** [comment]
Anatoly: questions around management of the images.

**Comment by SierraTR** [comment]
We had 25 attendees today.  My fault on the muting - a new attendee came in, I clicked to admit but they had dropped off just before I clicked and that put my cursor over the button to mute you. 

Have a great trip -- enjoy the beach!

**Comment by kaitohm** [comment]
@jonathanbossenger Just a friendly reminder... Can this issue be closed now?

**Comment by jonathanbossenger** [comment]
@bsanevans thanks, I missed this. I will complete the last steps and close it out

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/07/14/common-wordpress-apis-responsive-images/
