### ISSUE TITLE
Online Workshop - Website auditing and conversion optimization

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1699]
# Event Details
- Title: Website auditing and conversion optimization
- Description: This is an Online Workshop, based on a this previous talk at a WordCamp - [Website auditing and conversion optimization](https://wordpress.tv/2022/11/03/website-auditing-and-conversion-optimization/)
- Target Audience: Website Owners (users, designers)
- Date: August 19th
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/295357648/
- Co-host: @bsanevans 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by vineettalwar** [comment]
Hey @bsanevans , Thank you for creating Github ticket. 
I’ll be presenting this .

**Comment by vineettalwar** [comment]
Hey @bsanevans , 
Here are the slides for review. 
https://speakerdeck.com/vineetsktalwar/website-auditing-and-conversion-optimization-f3bde269-e159-40b2-a439-c7242ee3c8ec

**Comment by kaitohm** [comment]
Thanks. These look good to me 👍

**Comment by kaitohm** [comment]
Thank you for speaking today, @vineettalwar 🙇 

The recording for this session can be found here: https://wordpress.tv/2023/08/19/website-auditing-and-conversion-optimization-2/
