### ISSUE TITLE
Content Feedback - Confusion with Group and Stack block

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1700]
## Overview
- Content title: Designing with row and stack blocks
- Content URL: https://learn.wordpress.org/tutorial/designing-with-row-and-stack-blocks/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: improvement ideas

## Feedback Details

1) From Transcript:
"Next, we will open up our list view, select the Heading and the Paragraph block and then group them using my block toolbar."

@westnz  used the Group option, but it worked as a Stack, tucking the new text below the heading. Why?

2) Another element I've been working to learn is removing space between lines. Often the setting will show zero, yet moving it shows it had a hidden value of say, two - and my move truely sets it to zero.

I'd like this to report the settings it's reading from, even if they're set in the Global Settings list.

This is my current favorite tutorial, as it's precisely where I've been stuck in design. (I also like the Using Patterns tip, as trying to reuse Template Parts, w/o knowing I needed to unlink them, was murdering me)

_This feedback was provided in ticket 162015_

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by westnz** [comment]
1. You could've grouped in a general Group or Stack block.  There are sometimes multiple ways of achieving the same outcome with WordPress.
2. The hidden values are default settings set by WordPress.

# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): N/A
- What should happen next to apply the feedback?: N/A

Thank you for the lovely feedback!
