### ISSUE TITLE
Meeting Agenda July 11, 2023

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1703]
Starting this week, [team meetings will be held at the same time each week](https://make.wordpress.org/training/2023/07/08/announcement-updates-to-team-meeting-times/) - Tuesdays at 07:00 UTC. We welcome anyone to contribute to the meeting asynchronously, by commenting on threads in Slack.

This week’s meeting will be hosted by @bsanevans.

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- July 11 – [@nahidsharifkomol](https://profiles.wordpress.org/nahidsharifkomol/)
- July 18 – [@rajkothari](https://profiles.wordpress.org/rajkothariv/)
- July 25– [@fahimmurshed](https://profiles.wordpress.org/fahimmurshed/)
- August 1- [@sancastiza](https://profiles.wordpress.org/sancastiza/)

**2. Looking for feedback**

- No projects looking for feedback!! 🎉 

**3. Looking for volunteers**

- [Next steps for GitHub updates](https://make.wordpress.org/training/2023/07/08/next-steps-for-github-updates/)
- Team reps are looking for any teammates who can help make sure the insights in [Analysis and results of the Individual Learner Survey](https://make.wordpress.org/training/2023/05/30/analysis-of-the-individual-learner-survey-results/) don’t get lost.
- The Training Team moved announcing published content from weekly meetings and tested [a weekly roundup message](https://wordpress.slack.com/archives/C02RW657Q/p1687756135946129). Was this helpful? Would the [#training-notifications Slack channel](https://wordpress.slack.com/archives/C04KDJJR0RX) suffice?

**4. Updates from last week's dev-squad triage session**

- @jonathanbossenger Would you be able to provide an update as a comment on this issue, before the meeting?

**5. Other news**

- [Announcement: Updates to team meeting times](https://make.wordpress.org/training/2023/07/08/announcement-updates-to-team-meeting-times/)
- [Expertise needed: Learn how to vet content topic ideas for the Training Team](https://make.wordpress.org/training/2023/07/04/expertise-needed-learn-how-to-vet-content-topic-ideas-for-the-training-team/)
- [Training Team 2023 Half Year Review](https://make.wordpress.org/training/2023/07/10/training-team-2023-half-year-review/)
- Online Workshop - [Come join the WordPress Training Team!](https://www.meetup.com/learn-wordpress-online-workshops/events/294592656/)
- The [Learn WordPress July 2023 Newsletter](https://learn.wordpress.org/learn-wordpress-july-2023-newsletter/) has been published.
- The [What’s new on Learn WordPress in June 2023](https://make.wordpress.org/updates/2023/07/03/whats-new-on-learn-wordpress-in-june-2023/) monthly update has been published.

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - #1579 
  - #1616 
  - #1639 
- **Lesson Plans**
  - #806 
- **Courses** - in preparation for the WordPress mentorship program
   - ~[Open source basics](https://learn.wordpress.org/course/open-source-basics-and-wordpress/)~ reviewed by @quitevisible
   - ~[How Decisions Are Made in the WordPress Project](https://learn.wordpress.org/course/how-decisions-are-made-in-the-wordpress-project/)~ reviewed by @quitevisible
   - [Community Meeting Etiquette](https://learn.wordpress.org/course/community-meeting-etiquette/)
   - [Writing in the WordPress Voice](https://learn.wordpress.org/course/writing-in-the-wordpress-voice/)
   - [Basic Principles of Conflict Resolution](https://learn.wordpress.org/course/basic-principles-of-conflict-resolution/)
- **Translated Content**
  - #1488 
  - #1508 
  - #1535 
  - #1130 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - The project has started! If you are interested in getting involved, please leave a comment on the post.
- [Proposal: New Contributor Guide Program](https://make.wordpress.org/training/2023/06/20/proposal-new-contributor-guide-program/) - @courtney-pk 
  - The project will next create handbook entries for the Guide Program (including an interest form), and do outreach to Faculty members to identify the first Guides.

## 5. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by webtechpooja** [comment]
We also have upcoming meetup this month, [Come join the WordPress Training Team!](https://www.meetup.com/learn-wordpress-online-workshops/events/294592656/) on Monday, July 17, 2023, at 7:00 UTC

**Comment by kaitohm** [comment]
Thanks @webtechpooja ! I'll mention that Online Workshop 👍

**Comment by kaitohm** [comment]
For the record, this meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1689058830921519

**Comment by webtechpooja** [comment]
Here is The recap Notes - https://make.wordpress.org/training/2023/07/17/training-team-meeting-recap-11th-july-2023/
