### ISSUE TITLE
Online Workshop - Come Join the WordPress Training Team!

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Learn#1704]
# Event Details
- Title: Come Join the WordPress Training Team!
- Description: Each joinee will walk through the Training Team's onboarding program at the same time individually, while Zoom will be open for chatting and asking any questions along the way.
- Target Audience: Contributors
- Dates: 
  - 1 August 2023 at 13:00 PDT (20:00 UTC)
  - 14 August 2023 at 18:00 PDT ([01:00 UTC on 15 Aug](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20230815T01&p1=1440))
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/294747625/
- Co-host: 
- Other info: The August 14 workshop will take place on the same day as a session of [“Contributing to the WordPress Training Team”](https://github.com/WordPress/Learn/issues/1669), hoping to capture folks that we introduced to the team and are excited to join right away. This workshop will not be recorded since individual, personalized support will be provided to attendees.

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by nayanchamp7** [comment]
@courtney-pk I'm Interested to be the co-host in this Workshop.

**Comment by courtney-pk** [comment]
@nayanchamp7 I see you have applied to be a co-host, so we still need to review your application and get back to you. There has been a backlog of applications, so thank you for your patience!

Also, it's actually possible that a co-host is not needed for this session, since this is an onboarding session.

**Comment by courtney-pk** [comment]
This session was not recorded, and there are no slides aside from the usual introductory slides.
