### ISSUE TITLE
Tutorial - The WordPress database

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1705]
# Topic Description
In order to extend WordPress, a developer needs to have a foundational understanding of the WordPress database as well as knowledge of how to interact with and manipulate the data stored there. In this session, we'll take a high-level overview of the WordPress database, review the default ways to interact with the core schema and data, as well as learn how to add and use custom tables for additional functionality.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [ ] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [ ] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [ ] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
WIP script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/fundamentals-01-the-wordpress-database.md

**Comment by iammehedi1** [comment]
I will assist you with recording the script. I will share my first recording draft as soon as possible.

**Comment by jonathanbossenger** [comment]
Hi @iammehedi1 thank you for your interest in collaborating.

Could I ask you to hold on the recording, I just want to make sure that the script linked above is the most up to date version. I'll have it verified in the next few hours.

**Comment by iammehedi1** [comment]
Hey @jonathanbossenger  - yes, of course. Let me know once its ready. TY

**Comment by jonathanbossenger** [comment]
@iammehedi1 I have updated the tutorial and it should be ready to record now.

I also included some recording notes in the raw version, but I will add them here as well.

- Any linked URLs do not need to be read out, as they will be displayed on the screen.
- Headings do not need to be read out, as they will be displayed on the screen.
- When reading things like function names or table names, it's not required to read out the _'s. So wp_posts can be read as "wp posts".

If it's possible, please record with a few seconds break between each paragraph, and a few seconds more break at the end of each logical section. This makes it easier to cut the audio where it's needed. If it helps, I find it's easier to record each section on it's own. I don't mind if you share multiple audio files, one for each section. 

Once the audio is ready, you can upload it to this GitHub issue. 

I will handle the video part of the tutorial, and I will share it with you here to make sure you're happy with it before I make it available for review.

There's no hard deadline on this, but if it's possible to have it done by the end of the week, that would be great. 

Please let me know if you have any questions.

**Comment by jonathanbossenger** [comment]
I forgot to add if you need any tips on the actual recording, this handbook section should help https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial/#creating-your-tutorial

**Comment by jonathanbossenger** [comment]
Hi @iammehedi1. I don't want to put any pressure on you, but I wanted to find out how it was going with the voice recording. Anything I can do to help?

**Comment by iammehedi1** [comment]
Hey @jonathanbossenger, I hope you are doing well. The voice recording is already completed. I am adding the recordings serially according to the script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/fundamentals-01-the-wordpress-database.md

Here is how you will find the audio recordings inside the zip file named **Audios.zip**

```
1 - Introduction.mp3
2 - The WordPress Database.mp3
3 - Interacting with your WordPress database-.mp3
4 - Database Tables.mp3
5 - wp_posts and wp_postmeta.mp3
6 - wp_comments and wp_commentmeta.mp3
7 - wp_user and wp_usermeta.mp3
8 - Functions to interact with posts, comments, and users.mp3
9 - wp_terms, wp_termmeta, wp_term_relationships, and wp_term_taxonomy.mp3
10 - Functions to interact with terms and taxonomies.mp3
11 - wp_options.mp3
12 - Functions to interact with options + wp_links.mp3
13 - Conclusion.mp3
```
I am also adding a screenshot from the folder:


![image](https://github.com/WordPress/Learn/assets/48856522/2da28795-e76c-4c3d-b321-620b5a4e82f5)


Here is the zip file:  [Audios.zip](https://github.com/WordPress/Learn/files/12342975/Audios.zip)

Here is the backup download link if it requires: [Download Directly From Drive Using Worker](https://tv2.mehedi8401.workers.dev/0:/Audios.zip)

I don't really have professional tools to make it Studio/Podcast quality, but I've tried my best

Let me know how it goes. I am open for comments/revisions

Thanks

**Comment by jonathanbossenger** [comment]
Hey @iammehedi1 that's awesome news, thank you.

Not to worry about the Audio quality, there are tools we can use to clean it up if needed.

I'll download the files, and let you know if I need anything else while I am preparing the video.

**Comment by jonathanbossenger** [comment]
View for review

https://github.com/WordPress/Learn/assets/180629/0d16ff07-b4d8-44d0-8f87-0a1418c281db

**Comment by jonathanbossenger** [comment]
The tutorial has been published and announced to marketing for promotion. Thanks to @iammehedi1 for the voice work! 

https://learn.wordpress.org/tutorial/the-wordpress-database/
