### ISSUE TITLE
Content Feedback - Broken Quiz Link

### ISSUE THREAD

**Issue by JenGodin** [WordPress/Learn#1707]
## Overview
- Content title: Develop Your First Low-Code Block Theme > Saving Your Work: Create Block Theme
- Content URL: https://learn.wordpress.org/lesson/saving-your-work-create-block-theme/
- Reporting a broken Quiz Link

## Feedback Details

Simply wanted to share a broken Quiz I found at https://learn.wordpress.org/lesson/saving-your-work-create-block-theme/.

The "Take Quiz" button/link at the bottom of the page links to this broken page https://learn.wordpress.org/?post_type=quiz&p=26850.

I confirmed I was logged in at the time.

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by cynthianorman** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): Yes
- What should happen next to apply the feedback?: The correct link needs to be added for the quiz - maybe the quiz wasn't published as the slug is missing eg. https://learn.wordpress.org/quiz/different-types-of-themes-overview/

**Comment by utsavtilava** [comment]
Hello @JenGodin 
Nice Catch for me. Thanks for the update. @bsanevans Can you please check and fix this issue ?

**Comment by kaitohm** [comment]
@wparasae I've had a look, but I can't figure out what is wrong. The quiz shows ok for me, though I do see the URL (https://learn.wordpress.org/?post_type=quiz&p=26850) is different to what this other quiz's URL is (https://learn.wordpress.org/quiz/different-types-of-themes-overview/). I believe you created this lesson. Could you confirm all quiz settings are ok?

**Comment by Piyopiyo-Kitsune** [comment]
Reviewed the lesson once more, and when we clicked on the "Take Quiz" button it lead us to the quiz without issue.

Closing out this issue.
