### ISSUE TITLE
Online Workshop - Testing WordPress 6.3

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#1710]
# Event Details
- Title: Testing WordPress 6.3
- Description: Get a first look at what's new in WordPress 6.3 and help test new features. We'll be following the directions in https://make.wordpress.org/test/2023/06/27/help-test-wordpress-6-3/. 
- Target Audience: WordPress users interested in testing the newest features coming in WordPress 6.3
- Date: July 20 2023, 1 - 2PM EDT
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/294764578/?isFirstPublish=true
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I'm available to co-host if you still need one.

**Comment by nayanchamp7** [comment]
I'm Interested to be co-host in this Workshop.
