### ISSUE TITLE
Spanish translation for Lesson Plan "How to create a Lesson Plan"

### ISSUE THREAD

**Issue by Sancastiza** [WordPress/Learn#1711]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/how-to-create-a-lesson-plan/
- Language you'll be translating to: Spanish 
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @mjaragon
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Sancastiza** [comment]
https://docs.google.com/document/d/1mSSXAfzZK5UFKVHdnPbqUg6B7WfO5SfUs05YkHyYSV4/edit?usp=sharing

I did the translation. Here is the link, please help me to review.

**Comment by Sancastiza** [comment]
Thank you so much @webtechpooja

**Comment by kaitohm** [comment]
@mjaragon Are you able to review this translation?

**Comment by mjaragon** [comment]
@bsanevans : I've reviewed the translation.
Since it was in Google, I've created a copy to make the changes on the copy (also because I didn't have edit access to the original): https://docs.google.com/document/d/1yKwOkH0gIRoC8Vbq3kKd3X0eMlAR_2qzZ7YDA11PtLk/edit?usp=sharing 

I've left some notes in the document, because I noticed:
* A) There is a broken link in the [original lesson](https://learn.wordpress.org/lesson-plan/how-to-create-a-lesson-plan/) (_"and[ Copy Editing](https://make.wordpress.org/training/handbook/guidelines/training-team-how-to-guides/how-to-copy-edit-a-lesson-plan/)"_)
* B) We name specific templates and columns in the project board, so I've left those names in both languages (because I wasn't sure the names in GitHub would be translated)
  
Please let me know if this is OK, if you need me to adjust anything, or how can I help next :)

**Comment by kaitohm** [comment]
Thank you, @mjaragon ✨ 

> A) There is a broken link in the [original lesson](https://learn.wordpress.org/lesson-plan/how-to-create-a-lesson-plan/) ("and[ Copy Editing](https://make.wordpress.org/training/handbook/guidelines/training-team-how-to-guides/how-to-copy-edit-a-lesson-plan/)")

Great find! I've corrected the English lesson plan. Could you update the link in the Spanish translation too, please?

> B) We name specific templates and columns in the project board, so I've left those names in both languages (because I wasn't sure the names in GitHub would be translated)

I think the approach you took is perfect 👍 

@Sancastiza I've inited you to become a Contributor on Learn.WordPress.org. Once you accept the email invite, please let me know here. I'll assign a Spanish lesson plan draft to you, which you'll then be able to copy the Spanish translation into. We'll then be able to publish this! 😃

**Comment by mjaragon** [comment]
> Could you update the link in the Spanish translation too, please?

Yes 👍 
I've changed the link in the [Google Doc with the Spanish translation](https://docs.google.com/document/d/1yKwOkH0gIRoC8Vbq3kKd3X0eMlAR_2qzZ7YDA11PtLk/edit?usp=sharing) as well

> I think the approach you took is perfect 👍 

Woohoo! :) Great.
Thanks

**Comment by Sancastiza** [comment]
Thank you @mjaragon to helping me review the translation.

**Comment by Sancastiza** [comment]
@bsanevans Hi there, yes i already accepted the email invite, please help me assign a Spanish lesson plan draft. Thank in advance!

**Comment by kaitohm** [comment]
@Sancastiza Great! You should now be able to access this draft: https://learn.wordpress.org/wp-admin/post.php?post=42032&action=edit

Let me know once the content has been copied across. I'll do a final check and publish this ✨

**Comment by Sancastiza** [comment]
Hi @bsanevans  Thank you so much! Here is link : https://learn.wordpress.org/wp-admin/post.php?post=42032&action=edit
I already posted the content, please help me to double check and publish this. This is my first time doing this job, so I'm still confused, please be patient with me.

**Comment by kaitohm** [comment]
Thanks, @Sancastiza . We appreciate you working on this, and you're welcome to take your time 😊 

When the content was copied across, the heading information, and some of the lists, were over ridden. I've gone through and changed the block types again. I don't read Spanish, though, so I hope I've converted those correctly 😅 

There are two blocks at the end of the page that weren't translated yet - `Lesson Wrap Up` and `Follow with the Exercises and Assessment outlined above.` Could you translate those two sentences, and then let me know again? Once I do a final check once more, this should be ready to publish ✨

**Comment by Sancastiza** [comment]
Hi @bsanevans 
I have edited it once again, and I think this time everything looks quite okay. Please help me check it once more and post it when ready. Here is link: https://learn.wordpress.org/wp-admin/post.php?post=42032&action=edit
Thank in advance!

**Comment by kaitohm** [comment]
Thank you very much! I've published this here: https://learn.wordpress.org/lesson-plan/es-how-to-create-a-lesson-plan/

Thank you for your contributions 🙇‍♂️
