### ISSUE TITLE
Online Workshop - What is the Domain Name System?

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1714]
# Event Details
- Title: What is the Domain Name System?
- Description: This is a repeat of #904 
- Target Audience: Users
- Date:
   - ~August 3 ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/294801525/)) - @AsadPolash~
   - ~August 4 ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/294801575/)) - **needs co-host**~
   - August 17 ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/295316206/)) - @AsadPolash 
   - August 18 ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/295316498/)) - **need co-host**
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by AsadPolash** [comment]
Hi @bsanevans, I would like to be the co-host for this event.

**Comment by kaitohm** [comment]
@AsadPolash I apologize for last week. I fell ill and had to suddenly cancel the Online Workshop.

I've rescheduled this workshop for August 17th. Would you be interested in co-hosting this session with me? https://www.meetup.com/learn-wordpress-online-workshops/events/295316206/

**Comment by kaitohm** [comment]
For reference, here are last year's slides, which I plan on updating for this session - https://docs.google.com/presentation/d/1XD8oGKkAs_m-PwRKAdr6fOtQ2fLCFxHLWgvVuTRwHeM/edit?usp=drive_link

**Comment by AsadPolash** [comment]
Hi @bsanevans  
Thanks for the heads up. I would like to be the co-host for the online workshop.

**Comment by kaitohm** [comment]
Thanks, Asad. I've assigned you as my co-host above 📝

**Comment by kaitohm** [comment]
I've tweaked last year's slides. Here are the slides for this year's presentation: https://docs.google.com/presentation/d/1kI1x4MhECRqs_xGljXsEnGpff4rvskLf2kaRRiyM3Mk/edit?usp=sharing

**Comment by AsadPolash** [comment]
Hi @bsanevans 
The presentation looks quite organized. I saw both previous and the new one. I am looking forward for the workshop.

**Comment by AsadPolash** [comment]
Session Participants

15 Minutes -  6 Participants including the Host and Co-host
30 Minutes -  8 Participants including the Host and Co-host
45 Minutes -  7 Participants including the Host and Co-host
60 Minutes -  7 Participants including the Host and Co-host

**Comment by kaitohm** [comment]
PDF version of this presentation's slides: https://drive.google.com/file/d/14FeztpdZxNxNj5JmejlW0f-HYEWOaVht/view?usp=drive_link

Recording: https://wordpress.tv/2023/08/17/what-is-the-domain-name-system-2/
