### ISSUE TITLE
Online Workshop - Mentorship Program: Introduction to the WordPress Open Source Project

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1715]
# Event Details
- Title: Mentorship Program: Introduction to the WordPress Open Source Project
- Description: This online workshop is held as part of the [WordPress Contributor Mentorship Program](https://make.wordpress.org/community/2023/07/12/announcing-the-inaugural-cohort-of-the-wordpress-contributor-mentorship-program/), but is aimed at attendees all over the world who wish to learn how the WordPress open source project operates.
- Target Audience: Contributors
- Date: 14-07-2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/294759860/
- Host:  Hari Shankar
- Co-Host: Pooja Derashri
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by harishankerr** [comment]
### Updates

- The video of the workshop has been uploaded to wordpress.tv: https://wordpress.tv/2023/07/25/mentorship-program-introduction-to-the-wordpress-open-source-project/
- Here are the slides: https://docs.google.com/presentation/d/1vMSnanAW38SV07X7QxxNvSHaSMQZELdze5CDs7dRGdA/edit#slide=id.p
-  I have also completed the required task as mentioned here: https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/

**Comment by webtechpooja** [comment]
Thank you for the update @harishankerr
