### ISSUE TITLE
Online Workshop - How to validate content feedback for the WordPress Training Team

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1716]
# Event Details
- Title: How to validate content feedback for the WordPress Training Team
- Description: This session is aimed at Training Team contributors, showing them how to follow instructions in the handbook to validate feedback people submit about content on Learn.WordPress.org.
- Target Audience: Contributors
- Date:
   - August 10 ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/294801660/)) - **needs co-host**
   - August 11 ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/294802072/)) - @SierraTR 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by Sancastiza** [comment]
Hello, I would like to assign a co-host to the event. However, I am actually a newbie and do not know how to get started. Is there a link available to guide me on this topic?

**Comment by SierraTR** [comment]
I'm available to co-host on the listed Aug 11 event if you need me.

**Comment by kaitohm** [comment]
@Sancastiza Thanks for your interest! And yes, we do have a link:
https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/

Does that look like something you'd be interested in? If so, let me know which session you'd be available to co-hosting.

@SierraTR If Sancastiza is available for the 11th, I'll assign them as a co-host. Otherwise, I'll assign you 😉

**Comment by Sancastiza** [comment]
Hi @bsanevans 
Thank you for your guidance, I believe I am suitable and capable of co-hosting. I am ready to start working in the 11th. This is my first time doing it, and it makes me quite anxious. I really hope to receive guidance from you.

**Comment by SierraTR** [comment]
OK Ben,  I thought maybe @Sancastiza was referring to the event on the 10th. The 10th doesn't work for my time zone. I'll be attending on the 11th anyway.  See you then!

**Comment by Sancastiza** [comment]
@SierraTR Sure, actually, i can move on the event on the 10th, and therefore you can assign on 11th. What do you think? @bsanevans

**Comment by SierraTR** [comment]
That's fine with me - I'll be there anyway so I can Co-host - for me that is 5 pm on Thursday Aug 10th - though it's listed as the 11th above. I didn't know what time zone she is in or if she wanted to do both sessions.

**Comment by kaitohm** [comment]
I'm terribly sorry for the delay, folks. I was traveling, and then was out sick for the last week, and am now just catching up on everything.

I realize this is last minute. But @SierraTR , would you still be available to co-host the second session?

@Sancastiza We won't make it for today's session. Thank you for offering to help, though. I look forward to collaborating with you in future 😃

**Comment by kaitohm** [comment]
Recording published here: https://wordpress.tv/2023/08/10/how-to-validate-content-feedback-for-the-wordpress-training-team/
