### ISSUE TITLE
Hindi translation for Lesson Plan "Speaker Training Workshop"

### ISSUE THREAD

**Issue by markmemayank** [WordPress/Learn#1717]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/speaker-training-workshop/
- Link to original content GitHub issue: 
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @saurabhmention @nincompop @uptouplaksh
- Other info: https://docs.google.com/document/d/174IHTZKNl_sAFHeX7AVNP8IuEPmLfdPBD2OITsxrYmc/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by webtechpooja** [comment]
Thanks @markmemayank for translating it to Hindi
This is the doc link - https://docs.google.com/document/d/174IHTZKNl_sAFHeX7AVNP8IuEPmLfdPBD2OITsxrYmc/edit?usp=sharing

@saurabhmention @Nincompop @uptouplaksh
Please help us in reviewing this piece of content and provide your feedback!

**Comment by Nincompop** [comment]
I reviewed this and it looks fine as per me.

**Comment by markmemayank** [comment]
@sayhi2sakshi If you can also review then pls do the needful.

**Comment by sayhi2sakshi** [comment]
Hi Mayank, I have reviewed the translation. All good as per me.

**Comment by kaitohm** [comment]
Thank you for the reviews, @Nincompop and @sayhi2sakshi 🙌 

@markmemayank Could you copy-paste the translation into this draft please? You may remove the English when you do.
https://learn.wordpress.org/wp-admin/post.php?post=42096&action=edit

Once done, please let us know here and we'll publish the lesson plan ✨

**Comment by markmemayank** [comment]
@bsanevans Sure I will do it in a while.

**Comment by markmemayank** [comment]
Hey @bsanevans I have updated the draft.

**Comment by kaitohm** [comment]
Wonderful! This lesson plan is now published: https://learn.wordpress.org/lesson-plan/hi-speaker-training-workshop/

Thank you, to everyone, for your contributions 🌟

**Comment by kaitohm** [comment]
Team reps have moved this lesson plan to draft and are reopening this issue, due to some unresolved discussions.

**Comment by markmemayank** [comment]
This blog has been published successfully.

https://learn.wordpress.org/lesson-plan/hi-speaker-training-workshop/
