### ISSUE TITLE
Bug report : Content Overlap on Sidebar in View All Lesson Plans Page

### ISSUE THREAD

**Issue by shail-mehta** [WordPress/Learn#1718]
## Description
Content Overlap on Sidebar in View All Lesson Plans Page (In Firefox Browser)
Link:  https://learn.wordpress.org/lesson-plans/?_view=all

## Step-by-step reproduction instructions
- Go to learn.WordPress.org Website
- Click on Lesson Plans (https://prnt.sc/0XCuYsyrvd36)
- Then Click on Browse All Plans Button (https://prnt.sc/9UWIV8QaUyrZ)

you can see the content overlap Issue (https://prnt.sc/7UqXuoV-H3PO)

## Expected behavior
- Content Should be Display Properly Like this

![view-all-lesson-plan](https://github.com/WordPress/Learn/assets/22027190/5ea86354-cdc7-4801-a9df-c6ce863526f3)

## Actual behavior
- Content Overlap with Sidebar

![content-overlap-with-sidebar](https://github.com/WordPress/Learn/assets/22027190/50360ceb-c8dd-4bf3-abe6-c5cc669da68f)

## Environment information
- Browser : Firefox
- Device:  Laptop With Windows 10

## Solution
- Add  word-break: break-all;  in wp-content/themes/pub/wporg-learn-2020/css/components/_card.scss

![content-overlap-with-sidebar-soluion](https://github.com/WordPress/Learn/assets/22027190/83448d44-38c5-419a-a16a-c04ad9ce0980)

**Comment by shail-mehta** [comment]
Added Pull Request #1765

**Comment by shail-mehta** [comment]
Any update on https://github.com/WordPress/Learn/issues/1718 ?

**Comment by adamwoodnz** [comment]
No longer an issue, with the launch of the 2024 block theme.
