### ISSUE TITLE
Content Feedback - Wrong Language Display in Lesson Plan Listing

### ISSUE THREAD

**Issue by shail-mehta** [WordPress/Learn#1719]
## Overview
- Content title: वर्डप्रेस रिपॉजिटरी में थीम अपलोड करें
- Content URL: https://learn.wordpress.org/lesson-plan/hi-upload-a-theme-to-the-wordpress-repository/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: **Reporting an Error**

## Feedback Details
-  वर्डप्रेस रिपॉजिटरी में थीम अपलोड करें Lessons Content Language is Hindi but in Lesson Listing its Language is showing English,  **It Should be Hindi.**
- वर्डप्रेस रिपॉजिटरी में थीम अपलोड करें Lesson Should Show When Hindi Language is Selected Not English (Currently its showing when English Language Selected) 

![theme-upload-in-wordpress-repo](https://github.com/WordPress/Learn/assets/22027190/26ba3dda-e551-475b-96c6-97bf2a5e97f9)

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by webtechpooja** [comment]
Thank you for indicating it. I have changed the language, now it is showing Hindi.
