### ISSUE TITLE
Tutorial - Footnotes

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#1731]
# Topic Description
The WordPress Footnotes block allows users to add and format footnotes within their site text. This tutorial provides step-by-step instructions on how to use the Footnotes block effectively, offering options for customization and organization of footnotes.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ] https://github.com/WordPress/gutenberg/issues/1890
- [ ] https://drive.google.com/file/d/1Dp8cqsfsZ0TUHubTswWGfMZOexDfcbQZ/view?usp=sharing
- [ ] https://github.com/WordPress/gutenberg/pull/51201
- [ ] https://github.com/WordPress/gutenberg/pull/52024

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [ ] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [ ] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [ ] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

## SEO Keywords

-  Footnotes in WordPress
- WordPress Footnotes block
- Adding footnotes in WordPress
- Customizing footnotes in WordPress
- Using the Footnotes block in WordPress
- WordPress post/page footnotes
- Enhancing content with footnotes
- Citations in WordPress
- References in WordPress
- WordPress content enhancement

**Comment by 8thpalmerik** [comment]
I am going to work on this.

**Comment by 8thpalmerik** [comment]
Learning Objectives for this Tutorial
After Completing this tutorial users will be able to:
1.	Insert, edit, and delete the footnotes block within a page or post. 
2.	Write, edit, and delete individual footnotes.

**Comment by 8thpalmerik** [comment]
The footnotes block is a convenient addition to WordPress 6.3. The Footnotes block will allow content creators, academics, and many others to quickly add footnotes to their posts or pages. 
Pre-Requisites to use this block
•	WordPress site must be updated to 6.3+
•	The post or page must be edited via the block editor. 

The footnotes block is simple to insert into your post.
Once you identify the location you would like to place a footnote, place your cursor next to the text would like to footnote. Click the dropdown for the “more” option on the block controls. At this point the first footnote number will be displayed in the text and at the bottom of the post a footnotes block will automatically be inserted. This process can be repeated for each footnote being added into a post.

The block at the bottom will display a corresponding line for each footnote added throughout the post above. This block will default to being at the bottom of the page, but it can be moved around the post the same as any other block.  

Once you have added at least one footnote, within the footnotes block you can then select the corresponding line for each footnote to type the footnote text.
 
If you want to delete a footnote, simply place the cursor next to the footnote you want to delete and then click delete. Not only will this delete the footnote, but it will also automatically update the numbering of the footnotes on the post, as necessary. This will also delete the corresponding footnote at the bottom of the post. However, if you delete the footnotes block itself the footnotes text won’t be permanently deleted. You simply need to reinsert the footnotes block by selecting it from the block inserter. This will bring back all of the previously created footnotes. 

You should now be able to add, edit and delete the footnotes and the footnotes block on your page or post. Good luck using this handy new tool!

**Comment by westnz** [comment]
Hey @8thpalmerik 

The script and learning objectives are solid.  Short and sweet! I think it would be helpful to also see a professional example of where references have been added to a research doc for example.

> Once you identify the location you would like to place a footnote, place your cursor next to the text would like to footnote.

I think you can also highlight the paragraph or section you want to footnote.

Nice work!!

**Comment by courtneyr-dev** [comment]
WP 6.4 https://github.com/WordPress/gutenberg/pull/53044

**Comment by kaitohm** [comment]
Hi @8thpalmerik 👋 How is this going? Can the team support you in any way?

**Comment by kaitohm** [comment]
I'm closing this issue for now as there hasn't been any activity for a while. But if you'd like to pick it up and continue working on it, feel free to reopen the issue 👍
