### ISSUE TITLE
Lesson Plan - Grid Block

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#1734]
Lesson Plan: WordPress CSS Grid Block

# Topic Description
The topic of this lesson plan is the WordPress CSS Grid block. Students will learn how to utilize CSS Grid Layout to create flexible and responsive grid-based layouts in WordPress.

# Related Resources
- https://github.com/WordPress/gutenberg/pull/49018

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/) for further assistance.

# Development Checklist:
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the example lesson walk-through
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Announce to the Training team
- [ ] Announce to the lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

## SEO Keywords

- WordPress CSS Grid block
- CSS Grid Layout in WordPress
- Flexible grid-based layouts
- Responsive grid layouts
- CSS Grid properties
- Implementing CSS Grid in WordPress
- Customizing grid layouts
- Advanced CSS Grid techniques
- Best practices for CSS Grid in WordPress
- Grid-based web design in WordPress

# Repo Structure and Lesson Plan Template
Please refer to the provided [repo](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/) for the lesson plan structure and template.

## Description
This lesson plan focuses on teaching participants how to use the WordPress CSS Grid block effectively. Students will learn how to create advanced grid-based layouts in WordPress using CSS Grid Layout.

## Objectives
After completing this lesson, participants will be able to:
* Utilize the CSS Grid block in WordPress to create flexible and responsive grid layouts.
* Implement various CSS Grid properties to customize grid layouts.

## Target Audience
Who is this lesson intended for? What interests/skills would they bring? Put an "x" in the brackets for all that apply.
* [ ] Users / Content Writers
* [ ] Designers
* [x] Developers
* [ ] Speakers
* [ ] Organizers
* [ ] Kids

## Experience Level
How much experience would a participant need to get the most from this lesson? Put an "x" in the brackets for all that apply.
* [ ] Beginner
* [x] Intermediate
* [ ] Advanced

## Type of Instruction
Which strategies will be used for this lesson plan? Put an "x" in the brackets for all that apply.
* [x] Demonstration
* [ ] Discussion
* [x] Exercises
* [ ] Feedback
* [ ] Lecture (Presentation)
* [x] Slides
* [ ] Show & Tell
* [ ] Tutorial

## Time Estimate (Duration)
How long will it take to present this lesson? Put an "x" in the brackets for the one that applies.
* [x] 1 hour or less
* [ ] 2-4 hours (half-day)
* [ ] 5-8 hours (full-day)
* [ ] 2 days
* [ ] 3 days or more

## Prerequisite Skills
Participants will get the most from this lesson if they have familiarity with:
* Experience with HTML and CSS
* Completed the Basic WordPress Concepts lesson

## Readiness Questions
* Do you have experience with HTML and CSS?
* Have you completed the Basic WordPress Concepts lesson?

## Slides
Access the lesson plan slides [here](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/).

## Materials Needed
* Laptop or computer with internet access
* Local WordPress installation
* Text editor

## Notes for the Presenter
* Ensure participants have a local WordPress installation ready before starting the lesson.
* Guide on accessing the WordPress CSS Grid block within the WordPress editor.
* Encourage participants to experiment with different CSS Grid properties to reinforce learning.

## Lesson Outline
1. Introduction to CSS Grid Layout
2. Overview of CSS Grid Properties
3. Implementing CSS Grid in WordPress
4. Customizing Grid Layouts
5. Advanced Techniques and Best Practices
6. Q&A and Wrap-up

## Exercises

**Exercise: Grid Layout Creation**

In this exercise, participants will create a grid layout using the WordPress CSS Grid block.

1. Create a new post or page in WordPress.
2. Add a CSS Grid block to the content area.
3. Configure the grid properties to define the desired layout.
4. Insert content elements within the grid cells.
5. Preview and adjust the grid layout as needed.

## Assessment

**Question: What is the purpose of CSS Grid Layout in WordPress?**

1. To create flexible and responsive grid-based layouts.
2. To style the typography of the website.
3. To manage user authentication and permissions.
4. To optimize website performance.

**Answer:** 1. To create flexible and responsive grid-based layouts.

## Additional Resources
* [The Ultimate CSS Grid Tutorial for Beginners in 2023](https://www.codeinwp.com/blog/css-grid-tutorial-layout/) [1]
* [Integrating Simple CSS Grid Layouts into WordPress](https://www.hongkiat.com/blog/css-grid-wordpress/) [2]

### Introduction to CSS Grid Layout
Welcome, everyone, to today's lesson on the WordPress CSS Grid block. In this lesson, we will explore how to utilize CSS Grid Layout to create flexible and responsive grid-based layouts in WordPress.

### Overview of CSS Grid Properties
To get started, let's understand the key properties of CSS Grid Layout. CSS Grid provides fine-grained control over layouts, enabling us to create common designs with minimal code. We will learn about the `display: grid` property and its impact on margins. Additionally, we will delve into defining rows and columns using `grid-template-rows` and `grid-template-columns`. We will also explore the usage of `fr` unit for flexible sizes and how to define grid areas using `grid-template-areas`. The concept of implicitly sized rows and columns with `grid-auto-rows` and `grid-auto-columns` will be covered. Lastly, we will discuss automatic item placement with `grid-auto-flow` and common alignment properties.

### Implementing CSS Grid in WordPress
Now that we have a good understanding of CSS Grid properties, let's see how we can implement CSS Grid in WordPress. We will walk through the steps of creating a new post or page in WordPress and adding the CSS Grid block to the content area. We will demonstrate how to configure the grid properties to define the desired layout. We will also cover inserting content elements within the grid cells and provide guidance on previewing and adjusting the grid layout as needed.

### Customizing Grid Layouts
CSS Grid Layout offers extensive customization options. We will explore how to modify the grid layout by adjusting the number of columns, changing row heights, and adding or removing grid items. We will also discuss best practices for styling the background of the entire grid and tweaking the layout to avoid browser compatibility issues.

### Advanced Techniques and Best Practices
In this section, we will dive into advanced techniques and best practices for working with CSS Grid in WordPress. We will introduce inline grids, subgrids, and the masonry layout. We will also explore repeating rows and columns to streamline the grid creation process. Throughout the lesson, we will emphasize the importance of optimizing the grid layout for various devices and screen sizes.

### Q&A and Wrap-up
Before we conclude, let's address any questions you may have regarding CSS Grid in WordPress. Feel free to ask about specific use cases or seek further clarification on any topic covered in this lesson. Once the Q&A session is complete, we will wrap up the lesson and encourage you to continue exploring CSS Grid Layout in your WordPress projects.

![](https://raw.githubusercontent.com/wptrainingteam/contributor-resources/master/images/lightbulb.png) Now, let's proceed to the [Exercises](#Exercises) and [Assessment](#Assessment) sections to reinforce your learning.

For further resources and references, please check the [Additional Resources](#Additional-Resources) section.

I hope this lesson plan provides you with a comprehensive guide to teaching the WordPress CSS Grid block.

**Comment by annezazu** [comment]
There is not a Grid block! Please read this for more information about what's changing: https://make.wordpress.org/core/2023/07/14/layout-updates-in-the-editor-for-wordpress-6-3/
