### ISSUE TITLE
Lesson Plan - Command Palette API

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#1739]
# Command Palette API
This lesson plan will cover the WordPress Command Palette API, a new feature that allows developers to interact with WordPress more efficiently and user-friendly. It will also guide on how to use it.

# Related Resources
- [Introducing the WordPress Command Palette API](https://make.wordpress.org/core/2023/07/17/introducing-the-wordpress-command-palette-api/)

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Development Checklist:
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the example lesson walk-through
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Announce to the Training team
- [ ] Announce to the lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

## SEO Keywords
- WordPress Command Palette API
- Using Command Palette API
- WordPress Development
- WordPress API

# Repo Structure and Lesson Plan Template

## Description
This lesson plan provides an understanding of the WordPress Command Palette API and guides on how to use it.

## Objectives
After completing this lesson, participants will be able to:
* Explain what WordPress Command Palette API is
* Use the Command Palette API in their WordPress development

## Target Audience
* [ ] Users / Content Writers
* [x] Designers
* [x] Developers
* [ ] Speakers
* [ ] Organizers
* [ ] Kids

## Experience Level
* [ ] Beginner
* [x] Intermediate
* [ ] Advanced

## Type of Instruction
* [x] Demonstration
* [x] Discussion
* [x] Exercises
* [ ] Feedback
* [ ] Lecture (Presentation)
* [ ] Slides
* [ ] Show & Tell
* [ ] Tutorial

## Time Estimate (Duration)
* [x] 1 hour or less
* [ ] 2-4 hours (half-day)
* [ ] 5-8 hours (full-day)
* [ ] 2 days
* [ ] 3 days or more

## Prerequisite Skills
Participants will get the most from this lesson if they have familiarity with:
* Basic understanding of WordPress
* Basic coding skills

## Readiness Questions
* Are you familiar with WordPress?
* Do you have basic coding skills?

## Slides
* [Slides](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/) (files included in this repo)

## Materials Needed
* Computer with internet access
* WordPress installed

## Notes for the Presenter
* Ensure participants have WordPress installed on their computers
* Remind participants to follow along with the practical exercises

## Lesson Outline
* Introduction to WordPress Command Palette API
* Understanding WordPress Command Palette API
* Using WordPress Command Palette API
* Practical Exercise
* Review and Questions

## Exercises
**Using WordPress Command Palette API**
Practice using the Command Palette API on your own WordPress installations.

## Assessment
**What is the WordPress Command Palette API?**
1. A tool that allows developers to interact with WordPress in a more efficient and user-friendly way
2. A tool that allows developers to publish their websites
3. A tool that allows developers to design their websites
4. A tool that allows developers to secure their websites

**Answer:** 1\. A tool that allows developers to interact with WordPress in a more efficient and user-friendly way

## Additional Resources
* [WordPress Codex](https://codex.wordpress.org/)
* [WordPress Developer Resources](https://developer.wordpress.org/)

### Introduction to WordPress Command Palette API
Start by explaining what WordPress is and its uses. Introduce the concept of WordPress Command Palette API and its benefits.

### Understanding WordPress Command Palette API
Explain that WordPress Command Palette API is a tool that allows developers to interact with WordPress in a more efficient and user-friendly way.

### Using WordPress Command Palette API
Guide students on how to use the Command Palette API in their WordPress development.

### Practical Exercise
**Practical Exercise: Using the WordPress Command Palette API**

In this exercise, you will practice using the WordPress Command Palette API to interact with your WordPress site in a more efficient and user-friendly way.

**Step 1: Access the Command Palette**

First, open your WordPress site and log in to the admin dashboard. Press `Shift + Cmd + P` on Mac or `Shift + Ctrl + P` on Windows to open the Command Palette.

**Step 2: Explore the Command Palette**

Take a moment to explore the Command Palette. You'll see a list of commands that you can run directly from here. Notice how the commands are grouped by category for easy navigation.

**Step 3: Run a Command**

Now, let's run a command. Start typing the name of the command you want to run. For example, type "New Post" to create a new post. You'll see the command appear in the Command Palette. Press `Enter` to run the command.

**Step 4: Create a Custom Command**

The Command Palette API also allows you to create custom commands. Let's create a command that opens the theme customizer. 

In your theme's `functions.php` file, add the following code:

```php
add_action( 'admin_enqueue_scripts', function() {
    wp_enqueue_script( 'my-custom-command', get_theme_file_uri( 'my-custom-command.js' ), array( 'wp-command-palette' ), '1.0', true );
} );
```

Then, in the `my-custom-command.js` file, add the following code:

```javascript
wp.commandPalette.registerCommand( 'my-custom-command', {
    name: 'Open Theme Customizer',
    onInvoke: () => window.location.href = 'customize.php',
} );
```

When you open the Command Palette and start typing "Open Theme Customizer", you'll see your custom command. Press `Enter` to run the command and open the theme customizer.

**Step 5: Reflect on the Exercise**

Reflect on how the Command Palette API can streamline your workflow and make interacting with WordPress more efficient. Consider other custom commands you might want to create to further enhance your productivity.

Remember, the Command Palette API is a powerful tool that can greatly enhance your WordPress development experience. Use it wisely and happy coding!

### Lesson Wrap Up
Recap the main points of the lesson. Open the floor for any questions or clarifications.

[End of Lesson Plan]

**Comment by Greennc** [comment]
WP 6.4 https://github.com/WordPress/gutenberg/pull/53073 Add common commands (breadcrumbs, live preview, pre-publish checklist) https://make.wordpress.org/core/?p=107380#new-commands-in-the-command-palette
