### ISSUE TITLE
Content Feedback - Assessment section needs update on article for create-a-basic-child-theme-for-block-themes

### ISSUE THREAD

**Issue by mujuonly** [WordPress/Learn#1741]
## Overview
- Content title: Assessment section needs update on article for create-a-basic-child-theme-for-block-themes
- Content URL: https://learn.wordpress.org/lesson-plan/create-a-basic-child-theme-for-block-themes/
- Are you reporting an error (such as outdated information), or providing improvement ideas?:  Yes

## Feedback Details

![child-theme-functions-php-not-needed](https://github.com/WordPress/Learn/assets/459367/6b144b7a-252e-4a6e-85ca-287b3e6254cb)

What is the only file you need for a child theme to exist?

Style.css
Theme.json
Functions.php
Index.html

**functions.php is not mandate for block themes**

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by jonathanbossenger** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): No
- What should happen next to apply the feedback?: Close

The answer to the multiple choice question is #1, style.css, which is the correct answer, no change needed.
