### ISSUE TITLE
Duplicate content on /online-workshops/ page.

### ISSUE THREAD

**Issue by VipulUpadala** [WordPress/Learn#1742]
## Description
I have reviewed the above "/online-workshops/" page and found the form below "If you do not receive a response in about a week, please reach out in the #training channel in Slack to follow up." content is third times display.

## Step-by-step reproduction instructions
1. Open first https://learn.wordpress.org/online-workshops/ page
2. Scroll down to the page below and check `If you do not receive a response in about a week, please reach out in the [#training channel in Slack](https://wordpress.slack.com/archives/C02RW657Q) to follow up.` content is third times display.

## Expected behaviour
Content display only one time.

## Actual behaviour
Content display third times.

## Screenshots or screen recording (optional)
Screenshot: https://share.cleanshot.com/wd4f4QBxy3TCKFbM6Bnm

## Environment information
- Chrome
- MacBook with macOS 13.2

**Comment by webtechpooja** [comment]
I have checked it and can confirm this issue, and this is showing to me as well!

**Comment by webtechpooja** [comment]
I fixed it! @VipulUpadala Could you please check it and confirm? Is it still showing to you?

**Comment by SierraTR** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): No
- What should happen next to apply the feedback?: 
- The issue has been corrected and the described content now is displayed only once at the bottom of the page.
