### ISSUE TITLE
Meeting Agenda July 25, 2023

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1744]
This week's meeting will be held on Tuesdays at 07:00 UTC. 

We welcome anyone to contribute to the meeting asynchronously, by commenting on threads in Slack.

This week’s meeting will be hosted by @Piyopiyo-Kitsune .

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- July 18 – [@rajkothari](https://profiles.wordpress.org/rajkothariv/)
- July 25 – [@fahimmurshed](https://profiles.wordpress.org/fahimmurshed/)
- August 1 – [@sancastiza](https://profiles.wordpress.org/sancastiza/)
- August 8 – Need volunteer

**2. Looking for feedback**

- No projects looking for feedback!! 🎉 

**3. Looking for volunteers**

- [Next steps for GitHub updates](https://make.wordpress.org/training/2023/07/08/next-steps-for-github-updates/)
- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) is currently recruiting team members-- please read the post and comment if you are able to get involved.
- [Proposal: New Contributor Guide Program](https://make.wordpress.org/training/2023/06/20/proposal-new-contributor-guide-program/) - @courtney-pk -- we are looking for Faculty members to volunteer as guides!

**4. Updates from last week's dev-squad triage session**

- @jonathanbossenger Would you be able to provide an update as a comment on this issue, before the meeting?

**5. Other news**

- [Announcement: Updates to team meeting times](https://make.wordpress.org/training/2023/07/08/announcement-updates-to-team-meeting-times/)
- Thank you to Courtney Robertson, Leif Quitevis (quitevisible), Jo Minney for volunteering to help us create digestable insights posts for the [Analysis and results of the Individual Learner Survey](https://make.wordpress.org/training/2023/05/30/analysis-of-the-individual-learner-survey-results/).
- [Brainstorm & Table Lead – WordCamp US 2023 Contributor Day](https://make.wordpress.org/training/2023/06/19/brainstorm-table-lead-wordcamp-us-2023-contributor-day/) -- thanks to all who contributed their thoughts to how to make this an impactful session together. [Destiny has touched base with volunteers](https://make.wordpress.org/training/2023/06/19/brainstorm-table-lead-wordcamp-us-2023-contributor-day/#comment-3946) and is working to finalize the Contributor Day plan by end of next week, August 4th.

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - #1579 
  - #1631 
  - #1616 
- **Lesson Plans**
  - #806 
  - #379 
- **Courses** - in preparation for the WordPress mentorship program
- [x] [Open source basics](https://learn.wordpress.org/course/open-source-basics-and-wordpress/) reviewed by [@quitevisible](https://github.com/quitevisible)
- [x] [How Decisions Are Made in the WordPress Project](https://learn.wordpress.org/course/how-decisions-are-made-in-the-wordpress-project/) reviewed by [@quitevisible](https://github.com/quitevisible)
- [x] [Community Meeting Etiquette](https://learn.wordpress.org/course/community-meeting-etiquette/)  reviewed by [@quitevisible](https://github.com/quitevisible)
- [x] [Writing in the WordPress Voice](https://learn.wordpress.org/course/writing-in-the-wordpress-voice/)  reviewed by [@quitevisible](https://github.com/quitevisible)
- [x] [Basic Principles of Conflict Resolution](https://learn.wordpress.org/course/basic-principles-of-conflict-resolution/)  reviewed by [@quitevisible](https://github.com/quitevisible)
- **Translated Content**
  - #1488 
  - #1508 
  - #1535 

## 4. Project updates

None this week!

## 5. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by webtechpooja** [comment]
Recap Notes - https://make.wordpress.org/training/2023/07/26/training-team-meeting-recap-25th-july-2023/
