### ISSUE TITLE
Content Feedback - Basic Principles of Conflict Resolution Typo error "crises"

### ISSUE THREAD

**Issue by subashcpoudel** [WordPress/Learn#1748]
## Overview
- Content title: Basic Principles of Conflict Resolution
- Content URL: https://learn.wordpress.org/course/basic-principles-of-conflict-resolution/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: Typo Error

## Feedback Details
The content of the URL contains the following sentence: "Responding to crises such as harassment, physical danger..."

There is no word "crises" in English. I think it should instead be crisis or cases.

https://monosnap.com/file/YhDQuIOaU3zJjDAtzPRK75tUb0RPCj

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by kafleg** [comment]
English speakers know better I guess.

**Comment by SierraTR** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? :
- Yes, the text appears in the front page of the course, the last sentence in the course overview.
- 
- What should happen next to apply the feedback?: 
-The Merriam-Webster English dictionary [ https://www.merriam-webster.com/dictionary/crisis ] shows that the spelling 'crises' is the plural of the word 'crisis' which would be the correct usage in this instance. This may also be found at: [https://www.thesaurus.com/e/grammar/crises-vs-crisis/](url)
