### ISSUE TITLE
Bug report - Repeated footer text in course - Develop Your First Low-Code Block Theme

### ISSUE THREAD

**Issue by nagpai** [WordPress/Learn#1750]
## Description

There is a repeated text block appearing across the contents of the - [Develop Your First Low-Code Block Theme](https://learn.wordpress.org/lesson/different-types-of-themes-overview/) course. It reads as 

```
If you do not receive a response in about a week, please reach out in the [#training channel in Slack](https://wordpress.slack.com/archives/C02RW657Q) to follow up.
```

## Step-by-step reproduction instructions
Please login to your WP.org account and browse to [Develop Your First Low-Code Block Theme](https://learn.wordpress.org/lesson/different-types-of-themes-overview/). Check the other sections on the page too. You will see abrupt and repeated insertions of the text block mentioned above. 

## Expected behaviour
The text block is probably a footer note , and should appear only once at the bottom of the page or end of the course. 

## Actual behaviour
The text block appears perhaps at the end of every other text block and makes it difficult to read the course. 

## Screenshots or screen recording (optional)

<img width="1227" alt="image" src="https://github.com/WordPress/Learn/assets/4162931/cdbc6796-1940-4922-aaa3-e98f07e01ae2">

## Environment information
- Browser: Vivaldi - 6.1.3035.204 (Stable channel) (x86_64) 
- Device you are using and operating system : iMac 2017,  Ventura 13.4.1.

**Comment by SierraTR** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): YES
- What should happen next to apply the feedback?: 
- Problem appears to be the repeated use of a synced pattern that is a spacer and paragraph with the described text.
- Issue has been validated and has been moved to LearnWP Content - Feedback and Awaiting Fix

**Comment by SierraTR** [comment]
I believe I fixed this a while ago but neglected to move it to 'Done' status.

There was a reusable block that contained both a spacer and a the "If you do not receive..." message that was being used multiple times throughout the lessons as a spacer block.
