### ISSUE TITLE
Online Workshop - Testing WordPress 6.3 - Developer Edition

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1751]
# Event Details
- Title: Testing WordPress 6.3 - Developer Edition
- Description: With WordPress 6.3 due on August 8, 2023, now would be a great time to help test the release candidate, as well as confirm that your plugins and themes are ready for the 6.3 release. In this session we'll be installing the WordPress Beta Tester plugin, convert a local install to WordPress 6.3 for testing, test it against a theme that is in active development, and then revert it back to WordPress 6.2.
- Target Audience: Developers
- Date: 2023-07-27
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/295028674/?isFirstPublish=true
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I'm available to co-host.

**Comment by jonathanbossenger** [comment]
Thanks @SierraTR

**Comment by jonathanbossenger** [comment]
@SierraTR I've moved this meetup to 30 minutes later than the original time, I hope this still works out for you?

**Comment by SierraTR** [comment]
OOOOh, I get to sleep in!  Yes, no problems. I'll see you then.

**Comment by SierraTR** [comment]
Another great session in spite of the jet lag - you had 20 attendees.

I know the feeling, having flown internationally for 20+ years. After a trip the rule at home was "no power tools or check book operations for 3 days - and don't even consider a serious conversation..."

**Comment by jonathanbossenger** [comment]
> I know the feeling, having flown internationally for 20+ years. After a trip the rule at home was "no power tools or check book operations for 3 days - and don't even consider a serious conversation..."

Yeah, I had planned a different workshop for this week, but defaulting to an already-known path was much easier.

Thanks again for co-hosting.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/07/28/testing-wordpress-6-3-developer-edition/
