### ISSUE TITLE
Tutorial - Using Sidebars with 6.3 [Needs Accessibility Update]

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1752]
# Topic Description
An existing 6.2 (?) tutorial shows users how to create a sidebar for visual effect. However, this is not accessible; with the 6.3 update, we should update this tutorial to include the following:

- A theme developer can change the tag surrounding the sidebar to be an aside, that’s something you can do within the editor, but it’s something that they need to know they should be doing.
- [Research needed] Not all sidebars are necessarily “aside” content, depending on how they are used. It’d be good to include a section about properly marking layout areas that are meant to be used for secondary content.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ] https://learn.wordpress.org/tutorial/building-sidebars-with-the-site-editor/

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [ ] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [ ] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [ ] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by wparasae** [comment]
I have updated the existing tutorial with an accessibility note that reads:

> It’s important to tag the content in your template for assistive technologies (ie screen readers). Use <main> for the main content on the page, and the Skip to Content can target it. Use <aside> or <section> for sidebar content that is the same on all or many pages or posts.”

> How to assign these tags:
> The HTML Elements assignment controls are only available via the Group block in the block settings sidebar’s Advanced section. It’s important to wrap the content into a group block and use the controls to assign <main> and or <aside> to the respective content.

> This video is set to be updated to include these important steps with the WordPress 6.3 release.

**Comment by wparasae** [comment]
Due to a transition, I have removed myself from this issue to allow someone else to work on this. :) If I find time to work on this in the next two weeks, I will comment below and happily reassign myself to this issue.

**Comment by kaitohm** [comment]
I've removed the following line from the post.
> This video is set to be updated to include these important steps with the WordPress 6.3 release.

I'm closing this issue for now as we prioritize Learning Pathways content.
