### ISSUE TITLE
Online Workshop - Onboarding to the WordPress Test Team

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1754]
# Event Details
- Title: Onboarding to the WordPress Test Team
- Description: This Online Workshop is to onboard new contributors to the Test Team.
- Target Audience: Beginner
- Date: 03-08-2023
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/295046197/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
Shouldn't the title be Onboarding to the WordPress Training Team ?   That's what the description indicates.
