### ISSUE TITLE
Bug report: Fix the "Let us know" button within the Tutorials

### ISSUE THREAD

**Issue by stvsimons** [WordPress/Learn#1758]
# Details

As the prompt by the button says, "Found a typo, grammar error or outdated screenshot?" 
Appears that button everywhere, Safari Mac, Safari iPadOS, Chrome Mac - button does nothing. Disabling all security and ad blocker-like plugins doesn't seem to make a difference. No indication of error in console.

_Issue content modified by @bsanevans , as it was original submitted as Content Feedback, but is actually reporting a potential bug on the site._

**Comment by jonathanbossenger** [comment]
Hi @stvsimons 

Do you have an example URL of where this is happening?

I just tested this [tutorial](https://learn.wordpress.org/tutorial/intro-to-the-site-editor-and-template-editor/), and clicking on the Let us know link opens the [Report Content Feedback](https://learn.wordpress.org/report-content-feedback/) form as expected.

**Comment by adamwoodnz** [comment]
Tested on our new Tutorial template and the link appears to work as expected too.
