### ISSUE TITLE
Content Feedback - Shortcode example "Converting a shortcode to a block - course"

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1759]
## Overview
- Content title: Converting a shortcode to a block
- Content URL: https://learn.wordpress.org/course/converting-a-shortcode-to-a-block/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: 

## Feedback Details
The example shortcode was too simple, handling no attributes as almost every shortcode would. The last lesson on adding attributes I thought maybe you’d show or at least provide some direction on how within the block js code leverage the PHP code most shortcode’s would need to call. For example how would the block’s interface interact with getting data from the database - some magic must exist for the react js code to pass the user’s attribute data to an PHP endpoint and return the HTML to render onscreen.

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by jonathanbossenger** [comment]
@westnz thanks for this feedback. 

I have long had the thought that a more "advanced" course on converting shortcodes to blocks would be a good idea, covering some of the ways you can interact with the database (WP REST API, The core data module, etc). I will add this to my list of courses that would make sense to create, especially when we implement learning pathways.

**Comment by jonathanbossenger** [comment]
I have created this course issue in order to plan the content for this follow-up course: #1760 

I am going to close this issue now, but I will refer back to it when this course is being developed.

**Comment by westnz** [comment]
Excellent

Thank you, Jonathan.
