### ISSUE TITLE
Gujarati translation for Lesson Plan "Upload a Theme to the WordPress Repository"

### ISSUE THREAD

**Issue by harshgajipara** [WordPress/Learn#1761]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/upload-a-theme-to-the-wordpress-repository/
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: Google Doc - https://docs.google.com/document/d/1rj8M3Eu4enO7hKZD6YPWuGD7e3ebi3NPU9TGqC_hbcE/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by harshgajipara** [comment]
@webtechpooja Pls do the needful.

**Comment by webtechpooja** [comment]
Hi @harshgajipara, Thank you for translating the lesson plan. I have removed Awaited Triage label and added ready for review. 
@iamchetanp, @amitpatel0702  if you have some time, could you please reveiw it? Thanks

**Comment by harshgajipara** [comment]
@bsanevans I reviewed the translations and looks good to me. Let me ask @shail-mehta to help reviewing translations as he is also translation editor for Gujarati (#gu) locale on polyglots.

**Comment by shail-mehta** [comment]
@harshgajipara I have reviewed this [Google docs](https://docs.google.com/document/d/1rj8M3Eu4enO7hKZD6YPWuGD7e3ebi3NPU9TGqC_hbcE/edit?usp=sharing) & All good as per me.

**Comment by kaitohm** [comment]
@harshgajipara This content is ready to publish! Please follow these steps.

1. I've invited you as a Contributor on https://learn.wordpress.org/. **Please accept the email invitation, then comment here**.
2. Once you've accepted, I'll be able to make you the author of this lesson plan: https://learn.wordpress.org/wp-admin/post.php?post=41302&action=edit
3. You can then copy-paste your translation into the lesson plan above.
4. Once done, I'll do a final check and publish the content for you.

In future, if you find translating into a draft post is easier than using Google Docs, then you will now be able to do that too. You will then be able to create a "public preview" of your post to share with reviewers.

**Comment by harshgajipara** [comment]
Hi @bsanevans ,
Thanks for the information. I accepted the invitation. but when I clicked the invitation link for the first time, it showed the message the I successfully joined but when I am trying to click the invitation link from my laptop it shows an error occurred message so may I know using which login credentials I will be able to edit the draft translations?

https://prnt.sc/NHHuNzoI03qO

Thanks

**Comment by kaitohm** [comment]
Thanks for accepting the invite. You'll now be able to login to https://learn.wordpress.org/ with the user id `harshgajipara`. I've assigned you as the author of the lesson plan draft https://learn.wordpress.org/wp-admin/post.php?post=41302&action=edit . Let me know if you still face problems opening that.

**Comment by harshgajipara** [comment]
Hi @bsanevans,
I was able to login and edit the draft. I completed adding the translations to the draft post. Please verify it.
Thanks

**Comment by kaitohm** [comment]
This looks great! I changed one things. At the very end, there was:

> [ટિપ] 💡 ઉપર દર્શાવેલ કસરતો અને મૂલ્યાંકન સાથે અનુસરો.[/ટિપ]

Because this is a shortcode, I've changed this to:

> [tip] 💡 ઉપર દર્શાવેલ કસરતો અને મૂલ્યાંકન સાથે અનુસરો.[/tip]

Otherwise, all good 👍 I've published this here: https://learn.wordpress.org/lesson-plan/gu-upload-a-theme-to-the-wordpress-repository/

Thank you for your contribution, @harshgajipara and @shail-mehta 🎉
