### ISSUE TITLE
Meeting Agenda August 1, 2023

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1762]
This week's meeting will be held on Tuesdays at 07:00 UTC.
We welcome anyone to contribute to the meeting asynchronously, by commenting on threads in Slack.
This week’s meeting will be hosted by @bsanevans .

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

Icebreaker for the week: _What is your favorite food?_

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- August 1 – [@sancastiza](https://profiles.wordpress.org/sancastiza/)
- August 8 – [@nayanchamp7](https://profiles.wordpress.org/nayanchamp7/)
- August 15 – [@nahidsharifkomol](https://profiles.wordpress.org/nahidsharifkomol/)

**2. Looking for feedback**

No projects looking for feedback!! 🎉

**3. Looking for volunteers**

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) is currently recruiting team members-- please read the post and comment if you are able to get involved.
- [Call for Volunteers to help with 6.3 Learn WordPress updates](https://make.wordpress.org/training/2023/07/25/call-for-volunteers-to-help-with-6-3-learn-wordpress-updates/)
- Who is interested in attending a [Contributor Hour](https://make.wordpress.org/training/handbook/training-team-how-to-guides/contributor-hour/)?
- [Brainstorm & Table Lead – WordCamp US 2023 Contributor Day](https://make.wordpress.org/training/2023/06/19/brainstorm-table-lead-wordcamp-us-2023-contributor-day/) -- we are looking for a volunteer to monitor Slack and help with questions during Contributor Day.

**4. Updates from last week's dev-squad triage session**

No triage session was conducted this week.

**5. Other news**

- WordCamp US Contributor Day prep is underway. @Piyopiyo-Kitsune and @lada7042 are finalizing details with volunteers by August 4th. A post outlining what the team will be working on will be published shortly after.
-- @wparasae, @courtney-pk, and @amitpatel0702 -- any updates to share on what you'll be owning?
- Learn WordPress Monthly Updates - https://make.wordpress.org/updates/2023/08/01/whats-new-on-learn-wordpress-in-july-2023/
- Learn WordPress Newsletter - https://learn.wordpress.org/learn-wordpress-august-newsletter/
- @SierraTR  and [Emily Rapport](https://profiles.wordpress.org/eatpaintchic/) were awarded the Training Contributor badge this month 🎉 

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - #1562 
  - #1616 
  - #1631 
  - #1617 
- **Lesson Plans**
  - #806 
- **Translated Content**
  - Indonesian
     - #1488
     - #1508 
   - Khmer #1535 
   - Spanish #1711 
   - Gujarati
      - #1722 
      - #1761 
      - #1764 

## 4. Project updates

- [Proposal: New Contributor Guide Program](https://make.wordpress.org/training/2023/06/20/proposal-new-contributor-guide-program/) - @courtney-pk 
   - Are there any updates you'd like to share with the team?
- Creating digestable insight posts from the [Analysis and results of the Individual Learner Survey](https://make.wordpress.org/training/2023/05/30/analysis-of-the-individual-learner-survey-results/).
  - Thank you to Courtney Robertson, Leif Quitevis (quitevisible), Jo Minney for volunteering to work on this. Are there any updates you'd like to share with the team?

## 5. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kaitohm** [comment]
I will update the issue with open requests for review next week. I'll also note 4 or 5 high priority items to be created for the 6.3 release by the meeting, too.

**Comment by harshgajipara** [comment]
Some of the Gujarati (#gu) translations of Lessons plan are remaining to be reviewed. The urls of issues are listed below : 
https://github.com/WordPress/Learn/issues/1761
https://github.com/WordPress/Learn/issues/1764

Also, there is one Gujarati (#gu) translation of a video subtitle remaining to be reviewed which was originally published on wordpress.tv but also exists on learn.wordpress.org :
https://github.com/WordPress/Learn/issues/1722

I'd like to provide any help if needed for reviewing process as well as with the translations.
Thanks!

**Comment by webtechpooja** [comment]
Learn WordPress Monthly Updates - https://make.wordpress.org/updates/2023/08/01/whats-new-on-learn-wordpress-in-july-2023/

Learn WordPress Newsletter - https://learn.wordpress.org/learn-wordpress-august-newsletter/

**Comment by kaitohm** [comment]
This meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1690873244701569
