### ISSUE TITLE
Gujarati translation for Lesson Plan "How to Build Low-Code Block Patterns"

### ISSUE THREAD

**Issue by harshgajipara** [WordPress/Learn#1764]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/how-to-build-low-code-block-patterns/
- Link to original content GitHub issue: 
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @shail-mehta
- Other info: Gujarati translation : https://docs.google.com/document/d/1aqWRcFwiYqJpl-Aa4JAxF0U_h4PoJlnwS3EdddFOIJc/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by harshgajipara** [comment]
@bsanevans I am translation editor for Gujarati (#gu) locale on polyglots. As I translated and reviewed the translations. it looks good to me. Let me ask @shail-mehta to help reviewing translations as he is also translation editor for Gujarati (#gu) locale on polyglots. 
Thanks!

**Comment by kaitohm** [comment]
@shail-mehta Please let us know once you have reviewed this translation. Thanks!

**Comment by shail-mehta** [comment]
@bsanevans @harshgajipara, I have reviewed this [Google docs](https://docs.google.com/document/u/0/d/1aqWRcFwiYqJpl-Aa4JAxF0U_h4PoJlnwS3EdddFOIJc/edit?usp=sharing&pli=1) & All good as per me.

**Comment by kaitohm** [comment]
Wonderful!

@harshgajipara I've created a draft post below and assigned you as the author. Could you copy the translation across, and then let us know in this issue once you're done? Thanks!
https://learn.wordpress.org/wp-admin/post.php?post=41347&action=edit

**Comment by harshgajipara** [comment]
Hi @bsanevans,
Thanks for creating a draft post. I completed copying the translations in the draft post. Please verify it.
Thanks!

**Comment by kaitohm** [comment]
Wonderful! This lesson plan has been published: https://learn.wordpress.org/lesson-plan/gu-how-to-build-low-code-block-patterns/ 🎉
