### ISSUE TITLE
Online Workshop - Common WordPress APIs: Internationalization

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1766]
# Event Details
- Title: Common WordPress APIs: Internationalization
- Description: Internationalization is the process of developing your application in a way it can easily be translated into other languages. WordPress is used all over the world, by people who speak many different languages. If you're building a plugin or theme, you need add any text strings in your code in such a way that they can be easily translated into other languages. The process of translating those strings is known as localization. In this session, we will define what Internationalization and localization is, why it's important, and show you examples of how to implement this in your code.
- Target Audience: Developers
- Date: 2023-08-03 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/295125838/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by AsadPolash** [comment]
Hi @jonathanbossenger 
I would like to co-host this session with you.

**Comment by jonathanbossenger** [comment]
Hi @AsadPolash sure thing

**Comment by AsadPolash** [comment]
Thanks a lot. I am looking forward to it.

**Comment by AsadPolash** [comment]
Workshop Participants (Including the Host and Co-Host)
15 Minutes - 13
30 Minutes - 12
45 Minutes - 11
60 Minutes - 12

**Comment by jonathanbossenger** [comment]
Thank you @AsadPolash.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/08/04/common-wordpress-apis-internationalization/
