### ISSUE TITLE
Content Feedback - Some Spelling Mistake in Lesson

### ISSUE THREAD

**Issue by shail-mehta** [WordPress/Learn#1767]
## Overview
- Content title: Anonymizing information in the browser
- Content URL: https://learn.wordpress.org/lesson-plan/anonymizing-information-in-the-browser/
- Reporting a typo / grammar error 

## Feedback Details
I have checked this Lessons & found some spelling mistakes.
- **Dicsuss :** It Should be Discuss 
- **webite :**  It Should be Website

![tutorial](https://github.com/WordPress/Learn/assets/22027190/57055578-71f9-41ea-bba2-2a1ccaed3e97)

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by SierraTR** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No):  Yes
- What should happen next to apply the feedback?: 
- Errors corrected
