### ISSUE TITLE
Online Workshop - How to start contributing to the WordPress Core

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1768]
# Event Details
- Title: How to start contributing to the WordPress Core
- Description:  This Online Workshop is to onboard new contributors to the core Team
- Target Audience: Beginner, whoever is interested to learn about Core
- Date: 03-08-2023
- Meetup.com event link:https://www.meetup.com/learn-wordpress-online-workshops/events/295148319/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by oglekler** [comment]
Thank you @webtechpooja!
