### ISSUE TITLE
Content Feedback - Typo "Which or the following is NOT" in What is a WordCamp Quiz

### ISSUE THREAD

**Issue by subashcpoudel** [WordPress/Learn#1769]
## Overview
- Content title:  What is a WordCamp Quiz
- Content URL: https://learn.wordpress.org/quiz/what-is-a-wordcamp-3/
- Are you reporting an error (such as outdated information), or providing improvement ideas?:  Typo.

## Feedback Details
The quiz "Which or the following is NOT among the characteristics expected of a WordCamp?" contains a typo.

I think it should instead be "Which or the following is NOT among ..."

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by SierraTR** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No):  Yes
- What should happen next to apply the feedback?: 
- Typo in the quiz question has been corrected
