### ISSUE TITLE
Feature Request - Jetpack Social plugin on Make, HelpHub, and LearnWP

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#1772]
We now have a way to make better featured images for our 4 content types on LearnWP using Jetpack Social. 

- Lesson Plans
- Tutorials
- Courses
- Online Workshops

We need to ensure each has featured images enabled, then test using Jetpack Social. If we need support from Design around a featured image layout, let's get that elevated

https://meta.trac.wordpress.org/ticket/7110

**Comment by adamwoodnz** [comment]
Jetpack social is activated on Learn, see featured image examples on https://github.com/WordPress/Learn/issues/1329#issuecomment-2510348405

I'll leave the meta ticket open for other sites.
