### ISSUE TITLE
Online Workshop - Contributing to the WordPress Community Team: Events and Roles

### ISSUE THREAD

**Issue by naokomc** [WordPress/Learn#1773]
# Event Details
- Title: Contributing to the WordPress Community Team: Events and Roles
- Description: Online workshop to onboard new contributors to the Community Team
- Target Audience: Mentorship Program Pilot mentees an any new contributors interested in Community Team
- Date: August 7, 2023
- Meetup.com event link: https://www.meetup.com/ja-JP/learn-wordpress-online-workshops/events/295188699/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

cc: @peiraisotta

**Comment by jonathanbossenger** [comment]
Thank you for creating the ticket @naokomc.

Could I confirm, @peiraisotta is the main workshop host, so, therefore, I assume you will be co-hosting?

I just want to make sure I triage the issue correctly.

**Comment by naokomc** [comment]
@jonathanbossenger Correct, Isotta is the main host. I'm planning to attend and be a co-host, yes.

**Comment by peiraisotta** [comment]
Hello @jonathanbossenger , I'll be the host. Thank you!

@naokomc , thank you for wrangling everything!

**Comment by jonathanbossenger** [comment]
Thanks for confirming everyone.

Once the session has been held, if anyone needs assistance with the [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps, please let me know.

**Comment by peiraisotta** [comment]
Hello there! Workshop completed, video submitted. Waiting for approval

**Comment by jonathanbossenger** [comment]
I have approved the video on WordPress.tv.

https://wordpress.tv/2023/08/07/contributing-to-the-wordpress-community-team/

**Comment by peiraisotta** [comment]
Video: https://wordpress.tv/2023/08/07/contributing-to-the-wordpress-community-team/
Slides: https://docs.google.com/presentation/d/1aGyFbdkSLJ09ff_LuXjdD6FKrpOPor_1isdqoR1E-WQ/edit?usp=sharing
