### ISSUE TITLE
ITALIAN translation for LESSON PLAN "HOW TO CREATE A LESSON PLAN"

### ISSUE THREAD

**Issue by margheweb** [WordPress/Learn#1775]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/how-to-create-a-lesson-plan/
- Link to original content GitHub issue: 
- Language you'll be translating to: ITALIAN
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @margheweb @piermario @lidialab
- Other info: translator: @emanuela-s 
- GDocs: [https://docs.google.com/document/d/1It-3c2jG4dZRMTtrnGliy1QoSSbJJP04euH6RqQDkz0/edit?usp=sharing](https://docs.google.com/document/d/1It-3c2jG4dZRMTtrnGliy1QoSSbJJP04euH6RqQDkz0/edit?usp=sharing)

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by margheweb** [comment]
translator: @emanuela-s

**Comment by margheweb** [comment]
Preview before publishing: https://learn.wordpress.org/?p=82994&post_type=lesson-plan&preview=1&_ppp=4c99c0c98f 
Hi @bsanevans, how are you? Since I haven't posted translations for a while, could you please check, when you have a moment, that I have done everything correctly before I post it? URLs, taxonomies, etc.?

**Comment by kaitohm** [comment]
This looks great, @margheweb . Thanks for preparing this lesson plan 👍 
The only thing I did was add an Editorial Comment at the bottom of the post edit screen, linking back to this GitHub issue. Other than that, this is ready to be published 🎉 I'll let you press "Publish" 😉

**Comment by margheweb** [comment]
published: https://learn.wordpress.org/lesson-plan/it-how-to-create-a-lesson-plan/
