### ISSUE TITLE
Tutorial - Create your own custom synced or non-synced patterns

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1776]
# Topic Description
Now you have the freedom to create your own custom patterns in WordPress. You can choose whether you want each pattern to be synchronized with all other instances or not. This new feature allows you to create unique patterns and decide their synchronization status. As a result, the concept of Reusable blocks has evolved into something called "Synced Patterns."

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/3b95a502-1b3f-4c15-8918-e47a413ed2de

**Comment by SierraTR** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [ ] Learning outcomes/objectives are clear.
- [X ] Technical concepts introduced in the content are accurate.
- [X] The speed of demonstrations are easy to follow.
- [X ] The narration audio matches what is shown visually.
- [X ] Spelling and grammar are correct.
- [X ] Sound quality is consistent throughout the video.
- [X ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [X ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.
There was no real intro to the tutorial it just went right into the content. Perhaps a short intro screen that describes what types of information and the learning objectives for the tutorial would be appropriate. It would alert people to what they can expect to learn if they proceed through the video.
Other than that, very well done.

**Comment by westnz** [comment]
That is helpful feedback, thank you @SierraTR

**Comment by courtneyr-dev** [comment]
6.4 https://make.wordpress.org/core/2023/07/14/whats-new-in-gutenberg-16-2-12-july/#consolidating-patterns

**Comment by courtneyr-dev** [comment]
6.4 from Site Editor https://github.com/WordPress/gutenberg/pull/51946

**Comment by Jogendra-web** [comment]
The tutorial is well-structured, and the objectives are met and Professional sound quality.

**Comment by westnz** [comment]
Thank you @Jogendra-web

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/creating-your-own-custom-synced-or-non-synced-patterns/

**Comment by westnz** [comment]
Updated and added to the Intermediate user learning pathway in Sensei.

**Comment by westnz** [comment]
Updated and added to the Intermediate user learning pathway in Sensei.
