### ISSUE TITLE
Online Workshop - Common WordPress APIs: Global Variables

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1777]
# Event Details
- Title: Common WordPress APIs: Global Variables
- Description: Global variables are a concept in PHP that allow you to access these variables from any scope during a page request. WordPress ships with a specific set of global variables, and it's useful to know what they are, and how to use them correctly. In this session you'll learn how global variables work, the list of global variables available in a typical WordPress request, and now to correctly use and interact with them.
- Target Audience: Developers
- Date: 2023-08-10
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/295240268/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by nayanchamp7** [comment]
Hello @jonathanbossenger,

Please consider me as co-host of this event.

**Comment by jonathanbossenger** [comment]
Hi @nayanchamp7 thanks for your interest in co-hosting. I was going to ask you to complete the workshop facilitator application, but I see you have already done that, thank you.

I have replied to that email, so if you could get back to me there that would be great.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/08/11/common-wordpress-apis-global-variables/
