### ISSUE TITLE
Tutorial - Scheduling Posts and Pages

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#1778]
# Topic Description
One of the first post settings a user might want to learn is how to schedule a post or a page -- especially in new block themes, these settings can be a bit tricky to find. This tutorial aims to demystify how to schedule a post or page in WordPress, how to set the time so that the post or page goes live at the correct time, how to reschedule or unschedule a post or a page, and how to backdate a post or a page.

# Learning Objectives
- Locate and utilize the post or page settings that allow a user to schedule or backdate posts
- Locate and modify a WordPress' date and time settings to schedule posts on the desired date and time
- Reschedule, unschedule, or backdate a post or a page

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ] https://wordpress.org/documentation/article/page-post-settings-sidebar/
- [ ] https://wordpress.org/documentation/article/post-status/

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [ ] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [ ] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [ ] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [ ] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by wparasae** [comment]
How to schedule WordPress posts and pages (Tutorial Script)

Did you know that you don't have to publish a post or page immediately? Many people maintain a consistent posting habit due to one well-known secret: you can schedule posts to publish in the future, or even backdate them to the past--as long as you know where to look!

In this tutorial, you will learn how to
-Locate and utilize the post or page settings that allow a user to schedule or backdate posts
-Locate and modify a WordPress' date and time settings to schedule posts on the desired date and time
-Reschedule, unschedule, or backdate a post or a page

To find this setting, first

1. Log in to your WordPress admin dashboard.
2. Go to "Posts" and select "Add New" if you want to create a new post. If you want to schedule an existing draft then click on "All Posts” and select your draft.
3. Write or edit your post as you wish.
4. On the right-hand side, you'll see a box labelled "Publish." Here, you'll see an option that says ‘Publish Immediately’. Click on the "Edit" link next to it.
5. A calendar and a clock will appear. Select the date and time you want your post to be published. You can choose to set this post to publish sometime in the future, or you can backdate the post to a time in the past. If you choose to backdate and publish your post, it will most often appear chronologically in standard blog posts pages, like you see here.
6. Select a time you'd like your post or page to publish on in the future. Click "OK" after you've set your time.
7. Confirm the time and date are correct. The "Publish" button at the top of the "Publish" box will have changed to "Schedule." Click on this to schedule your post.
8. A note at the top of your screen will let you know your post has been scheduled, and you'll also see a countdown to the posting time in the "Publish" box.

Your post will publish at the scheduled date and time. If you'd like to edit it further, you can find the post or page in your dashboard with the word, "Scheduled" next to it. Edit it like you would a standard post 

But wait, you may be thinking. Aren't there lots of different time zones in the world? How does WordPress know which time zone to publish this post or page in?

Good news: You can set this in your WordPress dashboard.

**Correcting the Time**
To set the WordPress date and time, you need to adjust your website's general settings. Here's how you do it:
1. Navigate to "Settings" in the left sidebar menu. A dropdown menu will appear, click on "General".
2. Once you're on the "General Settings" page, you will see "Timezone". You can select a city that is in the same timezone as you, or set the UTC code.
3. Just below the "Timezone", you will see the "Date Format" and "Time Format". WordPress allows you to specify how dates and time are displayed on your website. Choose the style which suits your preference.
4. Be sure to click "Save Changes" at the bottom of the page when done.

Now, your WordPress settings will align with your desired date and time configuration. The setting affects the publishing of posts and pages, comment timestamps, and more. 

What if you want to unscheduled a post?
If you want to unschedule a scheduled post or page in WordPress, follow these steps:
1. Go to "Posts" if you want to unschedule a post. If you want to unschedule a page, go to "Pages". Then click on "All Posts" or "All Pages".
2. Find the post or page you've scheduled. You can use the search bar or filters at the top if you're having any trouble.
3. Once you've found the post or page, click on the title to open the editor.
4. On the right-hand side, you'll see a box labeled "Document". Inside this, you'll see a tab labeled "Status & Visibility". Click on this.
5. Next to "Publish", you will see the scheduled date and time. Click on the "Cancel" link next to it.
6. After clicking "Cancel", the button that used to say "Schedule" at the top right corner of your screen will have changed back to "Publish".

To unschedule the post, you do not have to do anything else. You can leave the post as a draft, which will not show on the front of your website.

There you have it! You can now schedule, backdate, or unschedule WordPress posts or pages. Happy blogging!

**Comment by wparasae** [comment]
August 16th Edit: This comment exists as an example for another tutorial. I don't actually need help with this script. :) Team, before I start recording, would someone please check over this tutorial script for accuracy / content? Please write any feedback below; I will move forward when I have had two people comment with suggested changes, or telling me to proceed. Thank you!

**Comment by wparasae** [comment]
Here's a link to the google slide deck I used for this tutorial: https://docs.google.com/presentation/d/1nBv80ecM1PtjDQtgg5wbmTOC07F9RV79BXJ0UDLl1SM/edit?usp=sharing

**Comment by wparasae** [comment]
Here is a link to the WordPress playground website used to create this tutorial:

[wordpress-playground-animal-photography.zip](https://github.com/WordPress/Learn/files/12306596/wordpress-playground-animal-photography.zip)

**Comment by wparasae** [comment]
Here is a link to the finalized WordPress playground, the "after" in case this needs to be re-recorded:

[wordpress-playground-animal-blog-final.zip](https://github.com/WordPress/Learn/files/12362740/wordpress-playground-animal-blog-final.zip)

**Comment by wparasae** [comment]
Ready for Review - Please view this at this Google Link, and provide feedback below.

https://drive.google.com/file/d/1bxD5Hjh-zeMTsNvQ6stex8cL0ZecLOUK/view?usp=sharing

Due to my own time constraints, I need to be able to polish this video no later than next Thursday, August 24th. Thank you so much for your time, team!

**Comment by jonathanbossenger** [comment]
Great tutorial @wparasae, clear and detailed steps about post and page scheduling.

I especially appreciated how you also covered the timezone settings, that's a question I had very early on when I started using WordPress.

**Comment by westnz** [comment]
Well done, Sarah! You explain how to schedule posts/pages clearly and succinctly. 

Two suggestions:
1. Change the slide 'By the end of this tutorial' at 0:16s already.
2. Double-check that the objectives slide 'By the end of this tutorial' correlates with what you are saying.

**Comment by davekellam** [comment]
Hi first time contributing to the training team (at WCUS contributor day)

Great tutorial! Very clear instructions. I don't use the schedule post feature too often, so learned something new with the blue dots indicating all of your scheduled posts.

I had one comment on the use of WordPress Playground. Should the dashboard screencasts all be zoomed into to the main wp-admin window, like at the 2:00 minute mark? Would it be confusing to see the browser within a browser for people who haven't encountered the Playground before? Maybe it doesn't matter for this tutorial, but a larger question for tutorials where seeing the address in address bar is useful?

**Comment by wparasae** [comment]
Thank you so much for your review, @davekellam! I know I'm doing a good job when people are learning new things. :D Congratulations on your first contribution!

> I had one comment on the use of WordPress Playground. Should the dashboard screencasts all be zoomed into to the main wp-admin window, like at the 2:00 minute mark? Would it be confusing to see the browser within a browser for people who haven't encountered the Playground before? Maybe it doesn't matter for this tutorial, but a larger question for tutorials where seeing the address in address bar is useful?

This is a good question! 

My first thought is that I like the idea of showing that WordPress Playground because it shows folks a way they can experiment with and learn about WordPress for free.

I can see why that may be a little confusing for new users, though; I'll double-check this tutorial and either change it to match your suggestions, or mention that the screen is using WordPress playground with a brief explanation.

**Comment by wparasae** [comment]
Okay, changes made! I'm not sure what my capacity will look like in the coming weeks, so let's go ahead and close feedback here. I've made the suggested changes (thank you so much, fellow contributors!) to the video. :D

**Comment by wparasae** [comment]
Passing the torch to Jonathan Bossenger to ensure this gets published. :)

**Comment by kaitohm** [comment]
@jonathanbossenger Just noting I've removed this from content needing a review and have applied `Ready to publish` to it.

**Comment by westnz** [comment]
Well done @wparasae and thanks for publishing @jonathanbossenger 
 https://learn.wordpress.org/tutorial/scheduling-posts-and-pages/
