### ISSUE TITLE
Filter course archive to only show featured courses

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#178]
Since only some of our courses are complete and ready for public consumption, we can only show some of them on the course archive page. These ones are marked as "featured" using the "feature this course" option that Sensei provides. We need to filter the course archive page to show only the courses that are marked as featured - it should be a matter of adding the appropriate meta_query to the source archive page query.

**Comment by coreymckrill** [comment]
Fixed with 3f3679bc381b58618220464979363b3ab24c4e57
