### ISSUE TITLE
Meeting Agenda August 8, 2023

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1780]
This week's meeting will be held on Tuesday, August 8, at 07:00 UTC.
We welcome anyone to contribute to the meeting asynchronously by commenting on threads in Slack.
This week’s meeting will be hosted by @webtechpooja.

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!
Ice Breaker - What is your favorite BOOK?

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- August 8 –  [@nayanchamp7](https://profiles.wordpress.org/nayanchamp7/)
- August 15 – [@nahidsharifkomol](https://profiles.wordpress.org/nahidsharifkomol/)
- August 22 - [@sumitsingh](https://profiles.wordpress.org/sumitsingh/)
- August 29 - [@fahimmurshed](https://profiles.wordpress.org/fahimmurshed/)

**2. Looking for feedback**

- Let’s elevate [Team Values](https://make.wordpress.org/training/handbook/about/team-values/) again
  - On July 18 Weekly Global Meeting, we discussed [DEIB(Diversity, Equity, Inclusion, and Belonging) Team value](https://wordpress.slack.com/archives/C02RW657Q/p1689664848465019)
  - This week, we will be evaluating another Team Value, Collaborative: We foster trust and cooperation through mentorship and respect. This is a supportive place that encourages reliability and motivation. 

**3. Looking for volunteers**

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) is currently recruiting team members-- please read the post and comment if you are able to get involved.
- [Call for Volunteers to help with 6.3 Learn WordPress updates](https://make.wordpress.org/training/2023/07/25/call-for-volunteers-to-help-with-6-3-learn-wordpress-updates/)
- [Contributor Hour](https://make.wordpress.org/training/handbook/training-team-how-to-guides/contributor-hour/) - Our First Contributor Hour will be on Aug 16 at 07:00 UTC and @Piyopiyo-Kitsune will be the host.

**4. Updates from last week's dev-squad triage session**

- No triage session was conducted this week.

**5. Other news**

- WordPress 6.3 will be released on August 8.
- [Proposal for Establishing a Make Diversity, Equity, Inclusion, and Belonging (“DEIB”) Team within the WordPress Community](https://make.wordpress.org/project/2023/07/13/proposal-for-establishing-a-make-diversity-equity-inclusion-and-belonging-deib-team-within-the-wordpress-community/)
- [WordCamp US Contributor Day](https://make.wordpress.org/training/2023/07/25/wordcamp-us-2023-contributor-day/)
- [WCUS Contributor Day: Tutorials Workshop (In-Person & Remote)](https://make.wordpress.org/training/2023/08/04/wcus-contributor-day-tutorials-workshop-in-person-remote/)
- [Concerns over the European Union’s Cyber Resilience Act (CRA)](https://wordpress.org/news/2023/08/concerns-over-the-european-unions-cyber-resilience-act-cra/)
- Training Team Badge awarded: Amit Patel, Sarah Snow, and Wes Theron

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - [Tutorial - Testing plugins for PHP 8](https://github.com/WordPress/Learn/issues/1562)
  - [Tutorial - Embedding media and third-party content on your website](https://github.com/WordPress/Learn/issues/1616)
  - [Tutorial- How to use the spacer block in block themes](https://github.com/WordPress/Learn/issues/1617)
  - [Tutorial - Exploring WordPress 6.3](https://github.com/WordPress/Learn/issues/1770)
- **Lesson Plans**
  - [WordPress Action Hooks - Lesson Plan](https://github.com/WordPress/Learn/issues/806)
- **Translated Content**
  - [Indonesian translation for Lesson Plan "Intro to the Site Editor and Templates "](https://github.com/WordPress/Learn/issues/1488)
  - [Indonesian translation for Tutorial "Choosing and Installing a Theme"](https://github.com/WordPress/Learn/issues/1508)
  - [Khmer translation for Tutorial "Getting to know the WordPress Dashboard"](https://github.com/WordPress/Learn/issues/1535)
  - [Spanish translation for Lesson Plan "How to create a Lesson Plan"](https://github.com/WordPress/Learn/issues/1711)
  - [Gujrati translation for Tutorial "How to start using WordPress Playground"](https://github.com/WordPress/Learn/issues/1722)
  - [Gujarati translation for Lesson Plan "Upload a Theme to the WordPress Repository"](https://github.com/WordPress/Learn/issues/1761)
  - [Gujarati translation for Lesson Plan "How to Build Low-Code Block Patterns"](https://github.com/WordPress/Learn/issues/1764)

## 4. Project updates

- [Introducing the Training Team Guide Program!](https://make.wordpress.org/training/2023/08/03/introducing-the-training-team-guide-program/) - @courtney-pk 
  - Are there any updates you'd like to share with the team?
- Creating digestible insight posts from the [Analysis and results of the Individual Learner Survey](https://make.wordpress.org/training/2023/05/30/analysis-of-the-individual-learner-survey-results/).
  - Thank you to Courtney Robertson, Leif Quitevis (quitevisible), and Jo Minney for volunteering to work on this. Are there any updates you'd like to share with the team?
- [Announcing the first Learn WordPress Course Cohort.](https://make.wordpress.org/training/2023/08/02/announcing-the-first-learn-wordpress-course-cohort/) - @jonathanbossenger has announced course cohort.
- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) - [A GitHub project](https://github.com/orgs/WordPress/projects/130/views/1) has been created to help assign, organize and project manage the ongoing work.

## 5. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
> Updates from last week's dev-squad triage session

My apologies to the team, I've been struggling with recovering from a cold, and I forgot to host dev-squad triage this past week. I'm planning to pick it up next week.

**Comment by webtechpooja** [comment]
meeting started in slack: https://wordpress.slack.com/archives/C02RW657Q/p1691478077367879
