### ISSUE TITLE
Online Workshop - Contributing to Learn WordPress with code

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1788]
# Event Details
- Title: TBD
- Description: TBD
- Target Audience: Developers 
- Date: TBD
- Meetup.com event link:
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
Often when presenting developer-focused online workshops, I will be asked by folks to run a "live coding" workshop, where I solve some problem, or fix some bug. Attendees seem to enjoy the process of watching someone debug a problem live, and the steps they take to solve this problem. 

This is one of the reasons I run a [weekly live stream](https://www.meetup.com/learn-wordpress-online-workshops/events/295240206/), where I am building a block theme in public, along with some external support from @eatpaintchic and @aurooba.

However, another common request I get is to show how to set up the local development environment for Learn WordPress, and how to create a PR to add or fix something on the Learn WordPress code base.

I'm starting this issue as a way to plan out that idea. I'm not sure if this will be a single workshop, or multiple workshops over the course of a week. If multiple, there will be some parts that make sense to do offline, and some that make sense to do live. 

As I flesh this out, I'll add more details to this issue.

**Comment by jonathanbossenger** [comment]
This looks like a good first issue to work on for this topic https://github.com/WordPress/Learn/issues/1464

**Comment by jonathanbossenger** [comment]
Things that will need to be covered:

- [ ] Setting up any required software
- [ ] Creating a fork in your local GitHub account
- [ ] Setting up the local development environment using your fork
- [ ] Creating a branch to work on
- [ ] Coding the feature
- [ ] Tests?
- [ ] Committing and pushing the code
- [ ] Creating the PR
- [ ] PR review
- [ ] Merging the PR

**Comment by jonathanbossenger** [comment]
Part 1:

- [ ] GitHub account (register new user)
- [ ] Local development environment requirements (nvm, npm, yarn, Docker, Composer, SVN) for *nix and Windows
- [ ] Fork Learn WordPress code base
- [ ] Clone forked repository
- [ ] Create a branch based on an issue
- [ ] Spin up wp-env and ensure the local site works

**Comment by jonathanbossenger** [comment]
https://www.meetup.com/learn-wordpress-online-workshops/events/295404664/

**Comment by jonathanbossenger** [comment]
https://www.meetup.com/learn-wordpress-online-workshops/events/295504728/

**Comment by SierraTR** [comment]
If you want a co-host for Part 2, I'll be attending.

**Comment by jonathanbossenger** [comment]
Thanks, @SierraTR.

**Comment by SierraTR** [comment]
Thanks again, another great session. Looking forward to the SSH session. I'll have to do some reading to be able to stay with you .

Three of us were watching today.

**Comment by jonathanbossenger** [comment]
Part 2:

- [ ] Creating a local branch
- [ ] Working on the initial fix for #1464 
- [ ] Committing and pushing the code
- [ ] Creating the pull request

**Comment by jonathanbossenger** [comment]
https://www.meetup.com/learn-wordpress-online-workshops/events/295504728/

**Comment by jonathanbossenger** [comment]
Closing this now while we wait for the PR to be finalized. I might run a follow up session once the PR is ready.
