### ISSUE TITLE
Course - Introduction to WordPress 6.3

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1789]
## Outline <a href="#outline" id="outline">#</a>

- [ ] 

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Course Development Checklist

- [ ] Needs Assessment Statement, Target Audience, Course Objective, and [Outline created](https://make.wordpress.org/training/handbook/courses/content-outline-and-draft/) 
- [ ] Needs Assessment Statement, Target Audience, Course Objective, and Outline vetted by an ID and feedback given 
- [ ] Overall topic and Outline Vetted by a Subject Matter Expert and feedback given
- [ ] Gather links to Support and Developer Docs
- [ ] Review any related material on Learn
- [ ] [Course created](https://make.wordpress.org/training/handbook/courses/content-creation/) and announced to the team for Q/A review
- [ ] Course review completed and [ready to publish](https://make.wordpress.org/training/handbook/courses/publishing-a-course/)
- [ ] Course excerpt created and featured on Learn WordPress
- [ ] Course [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
@annezazu would you like to either upload (if they're small enough) or link to a shared folder, the 6.3 videos here we discussed turning into a course for Learn WordPress? 

My thinking is I'll take the videos, transcribe the audio into text, edit it a little so each one reads more like a lesson, grab some screenshots to include in the text portion and wrap this all up into a short course folks can take.

**Comment by annezazu** [comment]
Real quick, I just noticed this: https://learn.wordpress.org/tutorial/exploring-wordpress-6-3/ Perhaps this would duplicate too much?

**Comment by jonathanbossenger** [comment]
That's a valid point. If you feel that the tutorial covers the same content you're covering in your videos, we can always can this idea.

**Comment by annezazu** [comment]
Yeah, let's keep with what is there! I know the product demo was used as inspiration and my videos cover much of the same stuff :D
