### ISSUE TITLE
Online Workshop - What’s new for developers? (August 2023)

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1793]
# Event Details
- Title: What’s new for developers? (August 2023)
- Description: Every month, Justin Tadlock publishes a "What's new for developers" post to the [WordPress developer blog](https://developer.wordpress.org/news/), highlighting some of the new developer-focused features added to WordPress. In this session, we'll be reviewing some of the features included in this month's post, with a specific focus on plugin and theme developer additions.
- Target Audience: Developers
- Date: 2023-08-18 14:30 UTC 
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/295383410/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I'm available to co-host on the 17th if you need one.

**Comment by jonathanbossenger** [comment]
Thanks @SierraTR, I accept your kind offer.

**Comment by jonathanbossenger** [comment]
@SierraTR I've had to adjust the workshop time to 14:30UTC.

**Comment by SierraTR** [comment]
No problem with the time change, thanks for letting me know.

**Comment by jonathanbossenger** [comment]
Hi @SierraTR. Due to a lower back injury yesterday, I'm moving this workshop to tomorrow, to allow me a little more time to heal. I understand if this might mean you can't co-host anymore.

**Comment by SierraTR** [comment]
I'll be there to help out on Friday but I'll have to head out at the 1-hour mark for a Dr. Appointment.
Take it easy today.

**Comment by jonathanbossenger** [comment]
No problem and thanks for letting me know, if we do get to the 1-hour mark and we're not wrapped up yet, please don't feel the need to stay. I'll do my best to stick to one hour anyway.

**Comment by SierraTR** [comment]
Another nice session.  And good timing too!

You had 16 attendees.

**Comment by jonathanbossenger** [comment]
Thanks, Tracy. The timing did work well 😁 Have a great weekend.

**Comment by SierraTR** [comment]
You too. Try to stay away from furniture-moving for a few more days.

Just a reminder - next Thursday (24th) is WordCamp US Contributor Day.

I'll see you Wednesday.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/08/22/whats-new-for-developers-august-2023/
