### ISSUE TITLE
Meeting Agenda August 15, 2023

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1795]
This week's meeting will be held on Tuesday, August 15, at 07:00 UTC.
We welcome anyone to contribute to the meeting asynchronously by commenting on threads in Slack.
This week’s meeting will be hosted by @Piyopiyo-Kitsune .

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- August 15 – [@nahidsharifkomol](https://profiles.wordpress.org/nahidsharifkomol/)
- August 22 - No meeting
- August 29 - [@fahimmurshed](https://profiles.wordpress.org/fahimmurshed/)
- September 5 - **Needs volunteer**
[@sumitsingh](https://profiles.wordpress.org/sumitsingh/), would you like to help us with September 5th since the August 22nd meeting is cancelled?

**2. Looking for feedback**

- Let’s elevate [Team Values](https://make.wordpress.org/training/handbook/about/team-values/) again
  - This week, we will be evaluating another Team Value, Sustainable Growth: As individual contributors and as a team, we hope for constant improvement! However, we aim to accomplish this by maintaining sustainable, innovative, and adaptable practices that uphold the team’s energy as well as the consistency and quality of content.

**3. Looking for volunteers**

- [Call for Volunteers to help with 6.3 Learn WordPress updates](https://make.wordpress.org/training/2023/07/25/call-for-volunteers-to-help-with-6-3-learn-wordpress-updates/)
- Help us prepare the Learn Newsletter!
  - We are looking for a Training Team Contributor to help us in compiling the August monthly Learn Newsletter ([Example of last month's newsletter](https://learn.wordpress.org/learn-wordpress-july-2023-newsletter/))

**4. Updates from last week's dev-squad triage session**

@jonathanbossenger any updates to share?

**5. Other news**

- [Contributor Hour](https://make.wordpress.org/training/handbook/training-team-how-to-guides/contributor-hour/) - Our First Contributor Hour will be on Aug 16 at 07:00 UTC and @Piyopiyo-Kitsune and @webtechpooja will be the host.
- [WordCamp US 2023 Contributor Day](https://make.wordpress.org/training/2023/07/25/wordcamp-us-2023-contributor-day/) next week on August 24th!
  - There are online and in-person opportunities to contribute to the [Training Team's goals](https://make.wordpress.org/training/2023/03/02/training-team-goals-for-2023/) together.
- **No global meeting next week during WordCamp US**

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - #1616 
- **Lesson Plans**
  - #806 
- **Translated Content**
  - #1488 
  - #1508 
  - #1535 
  - #1722 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - Rough drafts for the Designer, Developer, and End-User Learning Pathways are being finalized for review ahead of WordPress Contributor Day
- [Announcing the first Learn WordPress Course Cohort.](https://make.wordpress.org/training/2023/08/02/announcing-the-first-learn-wordpress-course-cohort/)
  - Signups close on August 20th

## 5. Open Discussions

- Let's discuss WordCamp US!

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kaitohm** [comment]
Please also raise this call for feedback regarding the site redesign: https://wordpress.slack.com/archives/C04U953K77A/p1692004103599749

**Comment by jonathanbossenger** [comment]
### Updates from last week's dev-squad triage session

PRs triaged:
- #1765 
Issues triaged
- #1718 (above PR fixes this issue)
- #1533
- #1569
- #1571 

We ended the session with 6 untriaged issues!

Calling all training team members who like to write code to look into any of the above-mentioned issues if they are interested in ways to contribute. 

If anyone is interested in learning how to contribute with code, I'm running a series of online workshops on the process of developing for the Learn WordPress platform. [Part 1 is happening on Wednesday the 16th](https://www.meetup.com/learn-wordpress-online-workshops/events/295404664/)

**Comment by courtney-pk** [comment]
Can we please add a call for new and experienced contributors to join the [Guide Program](https://make.wordpress.org/training/2023/08/03/introducing-the-training-team-guide-program/)?

**Comment by jonathanbossenger** [comment]
If possible, can we discuss [this issue](https://github.com/WordPress/Learn/issues/1782) that was logged recently with regard to Sensei emails? I have disabled the emails for now, but I think it's a good time to start a discussion about what emails Learn WordPress should be sending learners.

**Comment by webtechpooja** [comment]
Meeting recap notes - https://make.wordpress.org/training/2023/08/22/training-team-meeting-recap-15th-august-2023/
