### ISSUE TITLE
Tutorial - Common WordPress APIs: Dashboard Widgets

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1797]
# Topic Description
WordPress contains an extensive list of APIs for performing common tasks across a WordPress site. From interacting with the database to creating responsive images, there's an API for practically everything. This session will be the first in a series of an introduction to the common WordPress APIs, starting with the Dashboard Widgets API.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [Dashboard widgets online workshop](https://wordpress.tv/2023/07/07/common-wordpress-apis-dashboard-widgets/)
- [Common APIs page](https://developer.wordpress.org/apis/dashboard-widgets/)

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/common-apis-dashboard-widgets.md

**Comment by jonathanbossenger** [comment]
Video for review

https://github.com/WordPress/Learn/assets/180629/d6de30c5-bf78-407c-9de8-9c3541d7d28f

**Comment by westnz** [comment]
Review:
- The tutorial is well-structured, and the objectives are met.
- Professional sound quality. 
- Annotations are used well to help explain the content visually.
- I particularly liked the practical example of creating a dashboard widget, which was explained step-by-step.

**Comment by jonathanbossenger** [comment]
Thanks @westnz

**Comment by jonathanbossenger** [comment]
Tutorial has been published https://learn.wordpress.org/tutorial/common-apis-dashboard-widgets/
