### ISSUE TITLE
Online Workshop - How to facilitate or co-host an Online Workshop

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1800]
# Event Details
- Title: How to facilitate or co-host an Online Workshop for the WordPress Training Team
- Description: If you're interested in facilitating or co-hosting Online Workshops for the WordPress Training Team, then this workshop is for you! Come join Ben as he walks through the process of facilitating and co-hosting an Online Workshop. You'll get an overview of the vetting process, and also a behind-the-scenes view into how facilitators and co-hosts prepare for an Online Workshop.
- Target Audience: Contributors
- Date:
   - September 13 ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/295523553/)) - @lada7042 
   - September 14 ([Meetup.com event link](https://www.meetup.com/learn-wordpress-online-workshops/events/295523561/)) - @AsadPolash 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I'm available to co-host if you would like some help.

**Comment by kaitohm** [comment]
Thanks, @SierraTR . I've put you down as a co-host for the first session ✅

**Comment by kaitohm** [comment]
Sue to circumstances, @SierraTR has had to step down from being co-host. Anyone is free to volunteer for either session 🙌

**Comment by AsadPolash** [comment]
Hi @bsanevans 
I would like to be the co-host for the session on September 14th ([This Event](https://www.meetup.com/learn-wordpress-online-workshops/events/295523561/))

**Comment by kaitohm** [comment]
Recording from session one was uploaded to WordPress.tv: https://wordpress.tv/2023/09/12/how-to-facilitate-or-co-host-an-online-workshop-for-the-wordpress-training-team/

I also embedded the video to the Training Team handbook here: https://make.wordpress.org/training/handbook/online-workshops/

**Comment by AsadPolash** [comment]
Workshop Participants for [This Event](https://www.meetup.com/learn-wordpress-online-workshops/events/295523561/)
On 15 Minutes - 08 Including Host and Co-Host
On 30 Minutes - 09 Including Host and Co-Host
On 45 Minutes - 07 Including Host and Co-Host
On 60 Minutes - 07 Including Host and Co-Host

**Comment by kaitohm** [comment]
I've replaced the recording of session one linked above with that of session two, as that session went even better: https://wordpress.tv/2023/09/16/how-to-facilitate-or-co-host-an-online-workshop-for-the-wordpress-training-team/
