### ISSUE TITLE
Content Feedback - videos refuse to play when using adblocker

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1801]
## Overview
- Content title: Advanced Multisite Management
- Content URL: https://learn.wordpress.org/tutorial/advanced-multisite-management/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: error

## Feedback Details

When using an adblocker, the video refuses to play. In Firefox devtools Network panel, I see a blocked attempt to connect to…

https://pixel.wp.com/v.gif?v=wpcomv&sid=0&site=default&blog=5089392&post=118799&video_fmt=fmt_dvd&page_url=httpsvideo.wordpress.comembedF1LyQVI0hd1cover1&rand=ey4kom&video_play=1

…and then nothing else.

As per the UK's Information Commissioner's Office guidance on analytics cookies, site analytics are a 'nice to have' and are not strictly necessary for the functioning of the website. So why break the site just for analytics?

_This feedback was originally submitted in ticket number 2302800776._

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by ironnysh** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? No: 
- What should happen next to apply the feedback?: 

The video plays correctly in Safari, Firefox, and Chromium (Arc)—all with multiple ad-blockers and strict privacy settings.

**Comment by kaitohm** [comment]
Thanks for checking. I'll close this for now. We can reopen later if the issue is reported again.
