### ISSUE TITLE
Content Feedback - potential typo in community course

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1802]
## Overview
- Content title: Discussing Issues on Team Blogs
- Content URL: https://learn.wordpress.org/lesson/discussing-issues-on-team-blogs/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: error

## Feedback Details

Please check this screenshot which is typo error or gramatical mistake

<img width="324" alt="2023-07-19_23h11_54" src="https://github.com/WordPress/Learn/assets/49054298/5e0a034b-c7b1-4623-bee5-e85d07bce73e">

_This feedback was originally submitted in ticket number 2306233303._

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by devmuhib009** [comment]
In my check, I did not find any issue similar to this.
