### ISSUE TITLE
Content Feedback - wrong order in course blocks

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1803]
## Overview
- Content title: Saving Your Work: Create Block Theme
- Content URL: https://learn.wordpress.org/lesson/saving-your-work-create-block-theme/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: error

## Feedback Details

I just wanted to let you know that the link to the second quiz in the "Develop Your First Low-Code Block Theme" is broken.

You might also want to know that there is an issue in the ordering of the course blocks, "Completing Your Custom Theme" is in second place both in the lesson overview and the side menu, but it should be in last place.

_This feedback was originally submitted in ticket number 2327055866._

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by digitalchild** [comment]
While addressing the order issue reported in Help scout and this ticket, I checked the link for the quiz and it is working. 

@bsanevans if you're ok with it, I think we can close this one out.

**Comment by kaitohm** [comment]
Absolutely. Thanks for checking, Jamie 🙌
