### ISSUE TITLE
Search bar alignment issue

### ISSUE THREAD

**Issue by dd32** [WordPress/Learn#1804]
Migrated from https://meta.trac.wordpress.org/ticket/6377 

## Description

> In mobile version search bar alignment is not proper. It should be full width or left align.
>
> https://learn.wordpress.org/course-category/contributing-to-wordpress

## Screenshots or screen recording (optional)

![image](https://github.com/WordPress/Learn/assets/767313/0a6be471-fb93-47c5-9bc9-1d37f2cd1f1c)

**Comment by shail-mehta** [comment]
it showing properly in mobile.

## **Screenshot:** 
![contribute-wordpress-page-mobile](https://github.com/WordPress/Learn/assets/22027190/2b8fc6ca-bea9-416c-b216-599719b887fd)

## **Environment:** 
 Browser : Chrome
 Device: Mobile (Android)

**Comment by adamwoodnz** [comment]
Cannot repro
