### ISSUE TITLE
Content Feedback - alternative to Chocolatey for windows users

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1805]
## Overview
- Content title: Installing Node.js and npm for local WordPress development
- Content URL: https://learn.wordpress.org/tutorial/installing-node-js-and-npm-for-local-wordpress-development/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: error

## Feedback Details

As an alternative, Windows users who don't want to install Chocolatey just to add NVM do have another option: NVM for Windows (https://github.com/coreybutler/nvm-windows).

_This feedback was originally submitted in ticket number 2332918493._

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by kaitohm** [comment]
@jonathanbossenger You might be particularly interested in checking out this feedback.

**Comment by jonathanbossenger** [comment]
Thanks, @bsanevans. This is indeed interesting.

FWIW one of the other reasons I suggested Chocolatey in this video, is that installing Chocolatey means you can install other software, like PHP, svn, or git, using Chocolatey, without needing to go and download and manage separate installers.

It's one of the things I personally disliked about working in Windows, having to download different installers for each piece of software. 

However, I appreciate that not everyone wants this, so I think what I will do in this case is add this as an alternative under additional resources at the bottom of the tutorial, but not change the tutorial content at this time.

**Comment by jonathanbossenger** [comment]
- Added a note at the bottom of the Windows section to mention nvm-windows, with a link to the Additional Resources.
- Added the Additional Resources section at the bottom of the tutorial

**Comment by eddt** [comment]
This was my suggestion - The video/tutorial is most excellent, @jonathanbossenger - I just thought some PC users might not want/need what Chocolately brings to the table!

**Comment by jonathanbossenger** [comment]
Thanks, @eddt, I appreciate your input, it's always nice to offer folks alternatives.
