### ISSUE TITLE
Online Workshop - Common APIs - Metadata

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1807]
# Event Details
- Title: Common APIs - Metadata
- Description: One of the things that makes WordPress so extendable is its support for metadata on its core data object types (posts, comments, users, terms). The Metadata API and associated functions create a standardized way for retrieving and manipulating metadata for these object types. In this session, we will look at how metadata is stored, and which functions can be used to store and retrieve metadata. 
- Target Audience: Developers
- Date: 2023-08-31 14:30 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/295731435/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by AsadPolash** [comment]
Hi @jonathanbossenger ,
I would like to be the co-host for this online workshop with you.

**Comment by jonathanbossenger** [comment]
Hi @AsadPolash, thanks for offering to co-host.

It was pointed out that this workshop is at the same time as the WCUS Training Team Contributor Day session, so I am moving this workshop to next week, 31 August. If you're still available for that day, I'd be glad to have you on board as a co-host.

**Comment by AsadPolash** [comment]
Hi There, Thanks for the information. I just have one question. At 31st, Is it on the same time as It was at 24th?

**Comment by jonathanbossenger** [comment]
Hi @AsadPolash sorry, I missed this comment. Yes, the workshop will be at the same time. If you are still available to co-host, that would be great, but if not, I do understand.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/09/01/common-wordpress-apis-metadata-api/
