### ISSUE TITLE
yo soy Director de una academia de cursos talleres o carreras cortas  el CECCEL Consultoría Evaluación CAPACITACION y Certificación por Estándares Laborales con menos gastos basados en la educacion por competencias laborales y quisera me ayudaran a hacer mas facil el aprendizaje para adultos que van a mejorar su trabajo o van a Emprender con una certificación con validez oficial y con Registro nacional desarrollados a nivel mundial Topic Idea: TOPIC TITLE

### ISSUE THREAD

**Issue by R3691** [WordPress/Learn#1810]
# Details

- Topic description: 
- Audience (User, Developer, Contributor, etc.): 
- Learning objectives (What will the learner be able to do as a result of this content?): 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): 
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by moranjosep** [comment]
Proposal for a translation into Spanish from Spain. I hope you find it useful. Greetings!

Como Director de la academia de cursos, talleres o carreras cortas CECCEL, siglas de; consultoría, evaluación, capacitación y certificación, para estándares laborales. 
CECCEL, está ofreciendo educación en nuevas competencias laborales con unos gastos reducidos.
Me gustaría recibir ayuda para conseguir que el aprendizaje para adultos sea lo más fácil posible, ya que conseguirán obtener una certificación con validez oficial y, registros nacionales a nivel mundial. Esta educación les proporcionará las mejores herramientas para emprender o mejorar a nivel profesional.

**Comment by kaitohm** [comment]
English translation:
> I am the Director of an academy of courses, workshops or short careers, CECCEL Consultancy Evaluation TRAINING and Certification for Labor Standards with less expenses based on education for work skills and I would like you to help me make learning easier for adults who are going to improve their work or they are going to undertake with a certification with official validity and with national registration developed worldwide Topic Idea: TOPIC TITLE

@R3691 Please complete the Training Team's onboarding below to join the team.
https://make.wordpress.org/training/handbook/getting-started/
