### ISSUE TITLE
Content Feedback -

### ISSUE THREAD

**Issue by julietcroc** [WordPress/Learn#1811]
## Overview
- Content title: Designing Your Website: the site editor....
- Content URL: https://learn.wordpress.org/lesson/the-site-editor-and-the-page-editor/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: Error - the four things that the lesson says we have completed are inaccurate. 

## Feedback Details
In the intro it says: 
You are well on your way to having a strong WordPress website! So far you have:

1. Planned a rough draft of your website’s content
2. Stylized your website with colors and fonts
3. Chosen and activated a block theme
4. Stylized the way your website looks

While in fact we have only completed 1 and 3. 2 & 4 are coming up in the next lessons. It's not a HUGE deal, but it is inaccurate and so detail oriented people like myself will get frustrated. I am actually using this course in a college class so I appreciate it so much! 

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by jonathanbossenger** [comment]
Updated
