### ISSUE TITLE
Topic Idea: How to test and create for Accessibility

### ISSUE THREAD

**Issue by annezazu** [WordPress/Learn#1814]
# Details

- Topic description: A course dedicated to how to test and cover base accessibility requirements for contributing to the WordPress project. This covers everything from PRs to Design prototyping to marketing materials.
- Audience (User, Developer, Contributor, etc.): Contributors
- Learning objectives (What will the learner be able to do as a result of this content?): How to create accessibility content, including everything from code to writing marketing content (alt text, voice overs for videos, etc). 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Course
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): No. 

# Additional notes

We might need to separate this into buckets rather than an overarching course or have subitems: designing, coding, writing. I trust you all here! Ideally, we can include both show demos of folks using screen readers going through content and provide ways to experience it yourself using WP Sandbox (and some light instruction). 

# Next steps for SMEs

Tagging in @jomarieminney @alexstine @ryelle as this came up during the WordPress Community Summit 2023.

**Comment by annezazu** [comment]
Top three items from @joedolson for developers:
- Introduction to keyboard testing
- Accessible naming
- Fundamentals of HTML structure


Bonus: Screen reader testing as a more advanced section.

**Comment by jomarieminney** [comment]
@bsanevans @Piyopiyo-Kitsune if someone can do initial triage on this I will vet it as an SME as discussed today.

**Comment by afercia** [comment]
Thank  you for starting this ❤️ I'd think a good training or course should start from a good understanding of what the user needs are. That is not liited to no vision (blind screen reader users). It should include all the different kinds of disabilities and impairments, from mild to severe.

There's some resource around with personas to illustrate various users needs. I think webaim.org has some good ones. I'd suggest to ping the accessibility team for more resources.

After understanding these users needs, all contributors should have at least a basic understanding of how the different kind of assistive technologies work. I wouldn't expect all contributors to be pro users of these technologies. They should know how they work though. macOS does have some built-in accessibility technology that all contributors should try and be familiar with. For example:
- Screen reader: Safari + VoiceOver
- Worth noting that Safari + VoiceOver can be used only for basic testing. VoiceOver works pretty differently from 'classic' Windows screen readers. Testing advanced UIs with Safari + VoiceOver is not sufficient. Highly dynamic, comples UIs must be tested with other screen readers on Windows e.g. NVDA (free and open source) or JAWS.
- Speech recongition: Voice Control
- Screen magnification: Zoom
- Sever motor diabilities: Switch Control 
- Other technologies require specific devices and software

There are many other user needs that need to be understood before any design and coding. Cognitive impairments for example.

Overall, I think the testing part can be partially covered by the documentation the Accesisbiliyt team provided across the years. Instead, the training part is more challenging. I would recommend to consider to get in touch with accessibility experts specialized in training. There are wordl renowned professionals in the US and in the UK who specialize in training. I think the accessibility team can point to some of them, if needed.

**Comment by kaitohm** [comment]
@jomarieminney I've done the initial triaging. Feel free to vet this 👍  This looks like a highly impactful topic! 💡

**Comment by jomarieminney** [comment]
@nickthegeek looping you in as someone who could likely help with creating some of the requested content once we have some firm requirements around what is needed.

**Comment by joedolson** [comment]
@afercia I agree that some more foundational content focused on the principles of accessibility and user interaction would be extremely valuable. I don't think we should view these as "training" courses, however; more as introduction to the concepts and interactions that are important for accessibility. The courses should definitely point users to resources for additional information that are produced externally. 

It needs to be quite clear that these materials are introductory only.

**Comment by NicktheGeek** [comment]
> user interaction

Would it be helpful to have disabled users do short videos explaining how they consume content? Maybe interview style, 5 minutes or so, with links to more extensive courses to help developers and content creators account for these methods and test for them?

we could also make a couple primers that do a very brief walk through using some minimal testing with links to more extensive materials. 

Is there any value in content that explains “these are the steps to this certification”?

For links to resources, are there limits that they must be open source/free? For example Dequeue university has some amazing courses but they are paid. I can certainly link to free resources as well and dequeue offers steep discounts for people with disabilities and for those who live in impoverished countries.

**Comment by afercia** [comment]
> Would it be helpful to have disabled users do short videos explaining how they consume c

There's some videos already on the internet, especially from screen reader users. More rarely from users who use other assistive technology. There is something around about speech recognition posted also on this GitHub repository, see for example https://github.com/WordPress/gutenberg/issues/5468 and other feedback posted by @ewaccess 
Videos about other technologies and needs are more rare e.g. screen magnificiton or switch input.

**Comment by NicktheGeek** [comment]
> Videos about other technologies and needs are more rare

That was my exact thought so I was wondering if a series of short videos with actual end users showing how they consume content. 

If they goal here is more primer level then pointing to resources it seems like that could be a good starting place. It's the kind of demonstration that got me interested in testing plug-ins I built.

**Comment by afercia** [comment]
There's always something to consider before asking users to provide videorecordings and similar kind of in depth feedback. For some users, that would be a very tiring and time consuming process. Many of the agencies and professionals specialized in user testing recommend providing some kind of reward for users. It doesn't necessarily need to be some financial reward, coupons, software licenses, free subscriptions to some service could be a good alternative. I'm not sure it would be fari to ask users to provide their feedback for free..

That said, there are resources already published online. For example:
https://www.24a11y.com/2018/i-used-a-switch-control-for-a-day/

**Comment by ironnysh** [comment]
Hi all, just noting that we covered accessibility primers (guidelines and testing) in two Learning Pathways:
1. Module 5 in the [Learning Pathway: Intermediate User](https://github.com/WordPress/Learn/issues/2002)
2. [Learning Pathway: Intermediate Theme Developer](https://github.com/WordPress/Learn/issues/2045#module-05)

There’s always room for more content, of course! :-)

**Comment by kaitohm** [comment]
Thanks for noting, @ironnysh . I'm going to close this issue for now as something already covered in our scheduled content.
