### ISSUE TITLE
Spanish translation for tutorial "Posts vs. Pages: What’s the Difference?"

### ISSUE THREAD

**Issue by brezocordero** [WordPress/Learn#1816]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/posts-vs-pages-whats-the-difference/
- Language you'll be translating to: Spanish
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @carladoria

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
@brezocordero Thanks for translating! I have made a copy of the English content and assigned you as a author here: https://learn.wordpress.org/wp-admin/post.php?post=41644&action=edit

Once your translation has been reviewed, feel free to copy-paste the content into this draft. Please comment in this issue once you've done that, and we'll do a final check and publish the content for you.

**Comment by brezocordero** [comment]
@carladoria  the translation is ready for review here: https://docs.google.com/document/d/1n51QSDLsQCDQITjUxDAv3lsOWwCaJ0gC4oVYjPpwyLM/edit?usp=sharing

Could you please take a look? Thanks so much!

**Comment by carladoria** [comment]
@brezocordero I've added my comments to the Google doc. Thanks for translating!

**Comment by brezocordero** [comment]
Thank you for the review @carladoria 
I made the change you suggested.

**Comment by brezocordero** [comment]
@bsanevans 
I copied the reviewed translation and saved it as draft in the [post](https://learn.wordpress.org/wp-admin/post.php?post=41644&action=edit).
Thanks!

**Comment by kaitohm** [comment]
@brezocordero Thanks! This looks good.

As a final step, could you follow this guide to create and upload the subtitle file to the video? The subtitles are already translated in the post, so it should be a matter of copy-pasting that into a `ttml` file.
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-subtitles/

Once done, let me know in this issue. I'll be able to approve the captions and also publish the Tutorial 👍

**Comment by brezocordero** [comment]
Thank you @bsanevans 
I uploaded the translation for the subtitles.

**Comment by kaitohm** [comment]
Wonderful! This has now been published: https://learn.wordpress.org/tutorial/es-posts-vs-pages-whats-the-difference/

Thank you for your contribution 🎉
