### ISSUE TITLE
SPANISH translation for TUTORIAL "Getting to know the WordPress Dashboard"

### ISSUE THREAD

**Issue by carladoria** [WordPress/Learn#1817]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/getting-to-know-the-wordpress-dashboard/
- Link to original content GitHub issue: 
- Language you'll be translating to: SPANISH
- Have you arranged for someone to review this translation?: YES
- Reviewer's GitHub username: @brezocordero 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
@carladoria  Thanks for translating! I have made a copy of the English content and assigned you as a author here: https://learn.wordpress.org/wp-admin/post.php?post=41651&action=edit

Once your translation has been reviewed, feel free to copy-paste the content into this draft. Please comment in this issue once you've done that, and we'll do a final check and publish the content for you.

**Comment by carladoria** [comment]
@brezocorder the translation is ready here:
https://docs.google.com/document/d/1lzarQmM4sD7omhXZhc0vfd2RJyfC5KLu9uSrtGTzl-U/edit?usp=sharing
Can you please take a look at it? 
Thanks!

**Comment by brezocordero** [comment]
@carladoria Looks great! I added some small comments in the doc.
Let me know what you think.

**Comment by carladoria** [comment]
I worked on the suggested changes. Thanks so much @brezocordero

**Comment by carladoria** [comment]
Draft post is already here @bsanevans 
https://learn.wordpress.org/wp-admin/post.php?post=41651&action=edit

**Comment by kaitohm** [comment]
@carladoria  Thanks! This looks good.

As a final step, could you follow this guide to create and upload the subtitle file to the video? The subtitles are already translated in the post, so it should be a matter of copy-pasting that into a ttml file.
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-subtitles/

Once done, let me know in this issue. I'll be able to approve the captions and also publish the Tutorial 👍

**Comment by carladoria** [comment]
Sure, I'll try to get to it next week.

**Comment by carladoria** [comment]
@bsanevans I keep getting "Error: invalid file type." when trying to submit even though it is a ttml file
[subtitles (1) Spanish translated.ttml.txt](https://github.com/WordPress/Learn/files/12647819/subtitles.1.Spanish.translated.ttml.txt)

**Comment by kaitohm** [comment]
Thanks for working on that, @carladoria . Were you trying to upload the file with the `.txt` at the end of the file name? That may have been causing the error. I removed that, and the file uploaded ok 👍 

I uploaded the subtitle file and processed that for you. I then noticed the first line in the subtitle file was Japanese?? I replaced that with the first line of Spanish listed under `Transcript` in the post. Could you play the video and just check that is showing correctly?

All in all, this looks good now, so I've published the Tutorial here: https://learn.wordpress.org/tutorial/es-getting-to-know-the-wordpress-dashboard/ Thank you for your contribution 🙌

**Comment by carladoria** [comment]
`Thanks for working on that, @carladoria . Were you trying to upload the file with the .txt at the end of the file name? That may have been causing the error. I removed that, and the file uploaded ok 👍`
I don't recall seeing that .txt extension but perhaps I was overseeing it somehow. Thanks so much for fixing that! 

`I uploaded the subtitle file and processed that for you. I then noticed the first line in the subtitle file was Japanese?? I replaced that with the first line of Spanish listed under Transcript in the post. Could you play the video and just check that is showing correctly?`
Everything looks great! Thanks. Sorry I missed translating that Japanese line. 

This was fun to work on! Hopefully I will get to contribute more now that I know how the process is. Thanks so much again for your support!
