### ISSUE TITLE
Finnish translation for Tutorial "Getting to know the WordPress Dashboard"

### ISSUE THREAD

**Issue by Sarimarianna** [WordPress/Learn#1818]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/getting-to-know-the-wordpress-dashboard/#transcript
- Link to original content GitHub issue (optional): 
- Language you'll be translating to: Finnish
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @aurigit
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
@Sarimarianna  Thanks for translating! I have made a copy of the English content and assigned you as a author here: https://learn.wordpress.org/wp-admin/post.php?post=41656&action=edit

Later on in the translation process, we'll want to copy-paste the translation into this post draft. I'm just making sure you're set up for success 😉

**Comment by Sarimarianna** [comment]
Finally found the time to continue this at WCFI. :tada: I wonder if @aurigit could review this :slightly_smiling_face: 
https://docs.google.com/document/d/1UBI2Zv3kk876ucrZrR0MAxWL1-mEIC2BhNt85KRDPAk/edit

**Comment by aurigit** [comment]
Sorry for the delay, I've now proofread the document and done some small fixes. I'd say it's now finished (and finnished)! :D
https://docs.google.com/document/d/1UBI2Zv3kk876ucrZrR0MAxWL1-mEIC2BhNt85KRDPAk/edit

**Comment by Sarimarianna** [comment]
I have now added this to the post here https://learn.wordpress.org/wp-admin/post.php?post=41656&action=edit
@bsanevans is it now okay to be published or do I need to do the subtitles before that too?

**Comment by kaitohm** [comment]
Thank you for moving this forward, team!

@Sarimarianna We like to have the subtitles added to the video at the time of publishing. Could you work on creating those next, please? 🙇‍♂️

**Comment by Sarimarianna** [comment]
Yes, I started it already, hopefully will finish this week

**Comment by kaitohm** [comment]
Hi @Sarimarianna 👋 How is this going? Were you able to work on creating subtitles from the translation? Can the team support you in any way? 🙂  (The steps for creating subtitles are in this handbook page: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video )

**Comment by Sarimarianna** [comment]
Finallyyyy translated subtitles and uploaded them here: https://wordpress.tv/2022/05/19/getting-to-know-the-wordpress-dashboard/

So if all looks ok, this should be finished.

**Comment by kaitohm** [comment]
Congratulations! This tutorial has been published here: https://learn.wordpress.org/tutorial/fi-getting-to-know-the-wordpress-dashboard/

Thank you for your contributions @Sarimarianna and @aurigit 🎉
