### ISSUE TITLE
Content Feedback - Spelling error in "Testing your plugins for PHP version compatibility" tutorial

### ISSUE THREAD

**Issue by kls803** [WordPress/Learn#1819]
## Overview
- Content title: Testing your plugins for PHP version compatibility
- Content URL: https://learn.wordpress.org/tutorial/testing-your-plugins-for-php-version-compatibility/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: Spelling error

## Feedback Details
_There is a spelling error on the section of text below. 'tru' should be 'true'._

Additionally, add the WP_DEBUG_DISPLAY constant and set it to false and add the WP_DEBUG_LOG constant and set it to tru, so that errors are logged to a debug.log file in the wp-content directory.

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by SierraTR** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): Yes
- What should happen next to apply the feedback?: 
- Misspelling has been corrected
