### ISSUE TITLE
Searching on learn.w.org is buggy.

### ISSUE THREAD

**Issue by jeroenrotty** [WordPress/Learn#182]
Tried to search for something on learn.w.org today:

https://learn.wordpress.org/workshops/?search=yoast
Works (no results)

Searching on another page, such as:
https://learn.wordpress.org/workshops/page/4/?search=yoast
Gives a 404.

Searching on the courses page:
https://learn.wordpress.org/courses/?search=yoast
Seems to do nothing ...

**Comment by coreymckrill** [comment]
Thanks for the report @jeroenrotty! Should be fixed now.
