### ISSUE TITLE
Tagalog translation for Tutorial "Introduction to Contributing to WordPress"

### ISSUE THREAD

**Issue by jhimross** [WordPress/Learn#1820]
# Details
- Link to original content:  https://learn.wordpress.org/tutorial/an-introduction-to-contributing
- Link to original content GitHub issue (optional):  
- Language you'll be translating to:  Tagalog
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @onealtr
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
Thank you for translating content 🙌 
@jhimross Please share your WordPress.org username here, and I will add you to https://learn.wordpress.org/ as an Author.

**Comment by jhimross** [comment]
Hi @bsanevans my WordPress.org username is also @jhimross :)

**Comment by kaitohm** [comment]
I'm so sorry for the delay, @jhimross  . I caught covid and was out for a while 😷

I've sent you an invite to become an author on https://learn.wordpress.org/. Please let me know once you've accepted, and I'll then be able to assign the following post to you:

https://learn.wordpress.org/wp-admin/post.php?post=44451&action=edit

Once assigned, you can translate directly in the post, or in another doc. Please ping Oneal once the translation is ready for a review. We'll then continue from step 4 here: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video

**Comment by jhimross** [comment]
Hi @bsanevans hope you feel better soon and praying for your speedy recovery. 

I already accepted the invite, and I can now access the dashboard.

This is well noted.

**Comment by kaitohm** [comment]
Great! You should now have access to the post linked above 👍

**Comment by jhimross** [comment]
Hi @onealtr I'd like to request for your review for my translation from English to Tagalog.
 
See the draft post here:- https://learn.wordpress.org/wp-admin/post.php?post=44451&action=edit)

**Comment by onealtr** [comment]
@jhimross This translation has been reviewed and approved. 
@bsanevans

**Comment by jhimross** [comment]
Thanks! @onealtr :)

**Comment by kaitohm** [comment]
Great! The final piece needed now are the translated subtitles for the video.

@jhimross Please follow step 6 from the link below and submit the subtitle file to WordPress.tv. Once uploaded, let us know once more here and we'll be able to publish this 🙂 
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video

**Comment by jhimross** [comment]
Hi @onealtr @kaitohm sorry for the super delay translation of subtitles. Followed the article, and translated the English subtitle to Tagalog. ![Image](https://github.com/user-attachments/assets/1cdd9e22-6c93-42d1-a0f3-d312ecb6bd19)

Submitted it in WordPress.tv as mentioned in the article. Thank you!

**Comment by kaitohm** [comment]
Great! Captions have been approved, and this tutorial has now been published: https://learn.wordpress.org/tutorial/tl-an-introduction-to-contributing/

//published

**Comment by kaitohm** [comment]
Thanks for your contributions, @jhimross 🙌
