### ISSUE TITLE
Korean translation for Tutorial "Getting to know the WordPress Dashboard"

### ISSUE THREAD

**Issue by nayeonk** [WordPress/Learn#1821]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/getting-to-know-the-wordpress-dashboard/
- Link to original content GitHub issue (optional): 
- Language you'll be translating to: Korean
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
Thank you for translating content 🙌 

@nayeonk Please share your WordPress.org username, and we will add you as an Author on https://learn.wordpress.org/

**Comment by kaitohm** [comment]
Hi @nayeonk 👋  How is the progress of this content? Can the team support you in any way? 🙂

**Comment by kaitohm** [comment]
I'm closing this issue for now as there hasn't been any activity for a while. But if you'd like to pick it up and continue working on it, feel free to reopen the issue 👍

**Comment by Jiwoon-Kim** [comment]
Hi @nayeonk ,

While reviewing the Learn WordPress Korean translation project progress here:
👉 https://github.com/orgs/WordPress/projects/104/views/14

I came across the issue you created back in 2023:
👉 https://github.com/WordPress/Learn/issues/1821

I assume the previous translation draft might no longer exist by now, but I wanted to check in and ask — if there’s a chance for a new reviewer or contributor to join the project later, would you still be interested in contributing again?

We’re currently working on building up the Korean content team and would be happy to reconnect if you’re open to it.

Thank you! 🙏
