### ISSUE TITLE
Finnish translation for Tutorial "Choosing and Installing a Theme"

### ISSUE THREAD

**Issue by pekkakortelainen** [WordPress/Learn#1822]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/choosing-and-installing-theme/
- Link to original content GitHub issue (optional): 
- Language you'll be translating to: Finnish
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
Thank you for translating content 🙌 

@pekkakortelainen Please share your WordPress.org username, and we will add you as an Author on https://learn.wordpress.org/

**Comment by kaitohm** [comment]
Hi @pekkakortelainen  👋 How is the progress of this content? Can the team support you in any way? 🙂

**Comment by kaitohm** [comment]
I'm closing this issue for now as there hasn't been any activity for a while. But if you'd like to pick it up and continue working on it, feel free to reopen the issue 👍
