### ISSUE TITLE
Tutorial - What is a theme

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1823]
# Topic Description
Describe what a theme is

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- https://learn.wordpress.org/lesson-plan/what-is-a-theme/ (needs to be updated)
- #425 

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [ ] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [ ] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [ ] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by margheweb** [comment]
I'm going to do this during WCUS Contributor Day.

**Comment by margheweb** [comment]
Learning Objectives

Learners will be able to:
- identify what a theme is 
- tell the differences between a theme and a template and
- search a theme in the Repository to install in their website.

**Comment by margheweb** [comment]
**Introduction:** Welcome to this tutorial where we'll delve into the world of WordPress themes and templates. In this guide, you'll learn how to identify themes, distinguish between themes and templates, and search for and install a theme from the WordPress Repository for your website. Let's get started!

**Section 1:** Identifying Themes: A theme in WordPress is like the design and layout blueprint for your website. It dictates how your site looks, including color schemes, fonts, header and footer styles, and more. To identify a theme being used on a website, follow these steps:
- _Right-click and Inspect:_ Right-click on the website, then select "Inspect" or "Inspect Element." Look for a line that starts with_ <link rel="stylesheet" href="...">_. This link usually points to the active theme's stylesheet.
- _WordPress Theme Detector Tools:_ Use online tools like "What WordPress Theme Is That?" or "Scan WP" to analyze a website's theme based on its URL.

**Section 2:** Theme vs. Template: 
Themes and templates are closely related but serve different purposes:
- **Themes**: Themes are comprehensive design packages that control the overall appearance and functionality of your site. They determine layout, style, and some features.
- **Templates**: Templates are subsets of themes. They control the layout of specific parts of your site, like single blog posts, pages, or archive pages. Themes consist of multiple templates.

**Section 3**: Finding and Installing a Theme: 
WordPress Repository is a treasure trove of themes. Here's how to find and install one:
- Access the WordPress Dashboard: Log in to your WordPress admin panel.
- Navigate to Appearance: In the left-hand menu, hover over "Appearance" and click on "Themes."Click on "Add New": You'll be taken to the theme selection screen.
- Search or Browse: Use the search bar to look for specific themes or browse through the Featured, Popular, Latest, and Favorites sections.
- Preview Themes: Hover over a theme and click "Preview" to see how your site might look with it.
- Install the Theme: Once you've found the perfect theme, click "Install." After installation, click "Activate" to make it live on your site.
- Customize Your Theme: Access the "Customizer" under "Appearance" to modify the theme's settings, colors, fonts, and more.

**Conclusion**: By now, you should have a solid understanding of themes and templates in WordPress. You've learned how to identify themes, differentiate between themes and templates, and successfully find and install a theme from the WordPress Repository. With this knowledge, you're well on your way to creating a visually appealing and functional website. Happy WordPressing!

But I don't know if is ok regarding with FSE

**Comment by gudrunfrank** [comment]
@margheweb 
I know you had only very little time to work on this during WCUS, and it cannot be expected to be complete in just one day. Here are some thoughts as I try to learn the system myself :-).

I think we need to make clear in all tutorials that there are "old" classic themes and the newer Site-Editor Themes. Beginner users are very confused about the very different options in each. A link to this video may help to explain the difference 
[https://wordpress.tv/2023/03/17/what-kind-of-wordpress-theme-do-i-have-classic-block-or-something-else/](url)
Suggested edits: 

- Spend more time explaining what a theme is and what makes a good theme. I see a lot of beginners who think they have to switch themes because the color of the header bar is not to their liking. 
- Add that you can see the website's theme under >Appearance > Themes 
- Site Editor Themes have no customizer

**Comment by kaitohm** [comment]
Hi @margheweb 👋 How is this going? Can the team support you in any way?

**Comment by Piyopiyo-Kitsune** [comment]
@westnz Is this going to be part of a Learning Pathway lesson?

**Comment by westnz** [comment]
We have covered this in other lessons.
