### ISSUE TITLE
Learning & Earning With Digitaly

### ISSUE THREAD

**Issue by Rabindra54** [WordPress/Learn#1826]
# Details
<!-- I am Rabindra Chandra Ukil introduce myself as a learner & earner digitaly ,last 21 years i am serving LICI and others Financial Services physicaly but it is not so easy to serve all my clients , 
Last year i atract with Sandeep Banshali Sir Digital Azadi Course in Hindi , I am very much excitet return from Pune Manthan Progame held on 14 th & 15 th August 23 and also take decesion Next on 25th & 26th January 24 , i am a retired Govt Organisation for 28 yrs for my last Activity i have Serve maney Client  , I accept all new thing very easily ,Our organisaton insisted to work with ANANDA aps digitaly

**Comment by SierraTR** [comment]
# Vetting Checklist for SMEs
- Priority - either High, Medium or Low: None
- Feedback regarding the topic description: none provided
- Feedback regarding the learning objectives: none provided
- Any other feedback: 
- This is a proposal for learning content to be generated on how to use a third party, paid resource (agency). This type of content should be provided by the service provider, not generated on Learn.

# Related Resources
