### ISSUE TITLE
Online Workshop: Contributing to WordPress core

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1828]
# Details

During WCUS 2023 contributor day, a number of folks showed interest in Learn WordPress content around contributing to WordPress core. Recently we hosted a 2 part series on Contributing to Learn WordPress with code, and so my suggestion would be to do something similar for WordPress core.

I am suggesting a series of workshops covering the following topics:

- Where to find information: the Make/core team blog, core team handbook, and useful Slack meetings. Where code is hosted, both SVN and GitHub and how issues are logged and monitored on Trac. Also briefly cover how Gutenberg is developed separately from core, but merged into core during a release cycle, and usually one or two versions ahead of core. 
- Getting set up: all the required software, cloning the repo locally, and getting it up and running. Because WordPress core is closer to a default WordPress install, show how this can be done with pretty much any local development environment, but then also show how it's possible using wp-env or wp-now.
- Contributing: walk attendees through the process of finding and submitting a patch to a core ticket. With the fact that [WordPress core is mirrored on GitHub](https://github.com/WordPress/wordpress-develop/), with a connection to WordPress Trac and SVN, it is my suggestion that we focus on doing all this via Github, but also mention the connection to Trac and SVN, especially as most issues are logged in Trac. 

Once the workshops have been held, this content could then be turned into a series of tutorials, and maybe even a course for Learn WordPress.

- Topic description: Contributing to WordPress core
- Audience (User, Developer, Contributor, etc.): Contributor/Developer
- Learning objectives (What will the learner be able to do as a result of this content?): How to contribute to WordPress core
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Workshop, Tutorials, Course
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): TBD, I am happy to create this content, but I would love to collaborate with others as well. 

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by chaion07** [comment]
Really love the idea. Happy to collaborate and translate the content to Bengali. Thanks!

**Comment by kaitohm** [comment]
The first step is to conduct some Online Workshops on this content. If you are interested, please follow the handbook page [Online Workshops](https://make.wordpress.org/training/handbook/online-workshops/) for next steps.

**Comment by jonathanbossenger** [comment]
(Wow, I forgot that I created this issue...).

I am actually in the process of running a few live stream/workshops on this content, so I'm going to self assign this, and I will share links of the uploaded videos once they are live.

**Comment by jonathanbossenger** [comment]
https://www.youtube.com/watch?v=uQ0_0nhkZ3c

**Comment by jonathanbossenger** [comment]
https://www.youtube.com/watch?v=Q5GfQsoIIpw

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/issues/2199

**Comment by jonathanbossenger** [comment]
Going forward I'm simply going to use this issue to track my weekly contributing to WordPress livestreams.

**Comment by jonathanbossenger** [comment]
## Online Workshop Details
- Date: Wednesday, February 7, 2024, 3:30 pm (UTC+02:00)
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/298970226
- Co-host: N/A

## Online Workshop Development Checklist
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
https://www.youtube.com/watch?v=gCNz1IXyg1A

**Comment by jonathanbossenger** [comment]
## Online Workshop Details
- Date: Wednesday, February 29, 2024, 4:00 pm (UTC+02:00)
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/299435758/
- Co-host: N/A

## Online Workshop Development Checklist
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue
