### ISSUE TITLE
Tutorial - Common APIs – Responsive Images

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1830]
# Topic Description
WordPress contains an extensive list of APIs for performing common tasks across a WordPress site. From interacting with the database to creating responsive images, there's an API for practically everything. This session will focus on the Responsive Images API, including a brief history of responsive images in WordPress, how the API works, and how it's used for theme development.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [Responsive Images](https://developer.wordpress.org/apis/responsive-images/)
- [Online Workshop](https://wordpress.tv/2023/07/14/common-wordpress-apis-responsive-images/)

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/common-apis-responsive-images.md

**Comment by ndiego** [comment]
Just reviewed the script, and this is looking good Jonathan! It's a topic I really know nothing about, but I would definitely benefit from this.

I am curious how this interacts with the Block Editor and blocks that contain images, Image, Cover, Media & Text, etc. I believe "everything just works", but might be good to simply mention that the blocks already use the API and the customization section is really for very specific use cases. In other words, it's there if you really need it, but you probably won't.

**Comment by jonathanbossenger** [comment]
Thanks for the review @ndiego 

That's a valid point. I recorded the video yesterday, so I'll share it here in the meantime for further review, but I'll amend it in the week to include a section along the lines of what you've suggested.

**Comment by jonathanbossenger** [comment]
Video for review:

https://github.com/WordPress/Learn/assets/180629/f957f244-bae5-4e95-9f98-3ddb33d7f501

Noting that I plan to add a section towards the end based on @ndiego's suggestion [above](https://github.com/WordPress/Learn/issues/1830#issuecomment-1721179799)

**Comment by westnz** [comment]
Review:
1. Objectives are clear and met 
2. You provide helpful visual examples throughout the tutorial 
3. Remove sound: 2:04/2:05
4. 3:41 - 3:49 You might want to consider blurring out your private and work email address 
5. 8:31/8:3:32 - the sound cuts out

Great tutorial @jonathanbossenger

**Comment by jonathanbossenger** [comment]
Thanks for the review @westnz 

> 3:41 - 3:49 You might want to consider blurring out your private and work email address

Nice catch, I didn't even pick that up. I'll make sure to blur them out in the final video.

**Comment by TinaCollier** [comment]
Great tutorial! My takeaways:

1. Achievement objectives are clearly met: You clearly explained responsive images and why to use them, how the WP Responsive Images API works, and how to customize the markup.
2. You thoroughly explained how the browser identifies the correct image size to display based on the device, and gave a great example when comparing the header image to the image in the content.
3. I appreciate the time you took to explain the functions and hooks in the API, as well as, customizing the responsive image markup. The example you provided was informative, but it felt like it ended abruptly. I would've liked to see what the result would look like in the frontend.

**Comment by jonathanbossenger** [comment]
Thank you for your review feedback @TinaCollier.

**Comment by wparasae** [comment]
This is fantastic, Jonathan! TIL about the different browsing modes with the inspector. That was very clear to me as an intermediate user, so thank you for that! I very much appreciate the way you provide learners a link to additional resources and keep the focus of your tutorial razor-sharp. Well done!

My only note: Speaking of responsive images -- or tutorials! -- I watched this on mobile and the text is _tiny_. Observe:

<img width="345" alt="Screenshot 2023-09-19 at 12 23 42 PM" src="https://github.com/WordPress/Learn/assets/101278360/9cdace6b-ce78-48de-95eb-4d7b4c4ba87b">

For future tutorials, you might consider making that text a bit bigger for folks on mobile and zooming in a bit more while recording for future tutorials. I don't think it would be a good use of your time to re-record the whole thing, especially considering that people who are developing will probably not be doing so from their mobile devices, but it's just something to be aware of. :)  

This feels like a strong topic for beginning developers to start experimenting with, hands-on. This was clear to the point where I felt like I might actually be able to drop into my own experiment and actually dabble. Bravo!

**Comment by Zebedeu** [comment]
1. I consider the tutorial quite useful. It's natural that a tutorial doesn't cover all aspects and usually some details are left out. However, for a beginner user, the content is adequate.

2. It was necessary to emphasize that the tutorial is aimed at beginner users and that various topics have been omitted.

3. It would also be helpful to mention the version of WordPress used in the lesson. Additionally, in the text, the use of the 'return' command is mentioned in the code example, but this command is not present in the code documentation. It would be useful to explain the reason for this change.

**Comment by jonathanbossenger** [comment]
Thank you @wparasae for the review.

> For future tutorials, you might consider making that text a bit bigger for folks on mobile and zooming in a bit more while recording for future tutorials.

I will certainly look into increasing the font sizes for the slides in the future.

Out of interest, the tutorials are recorded in landscape and not portrait, so I'd be interested to know how they view if you flip your phone to landscape orientation. This is going to be a common problem with all videos recorded in landscape mode, which is really not responsive at all, and one of the reasons I always include all code snippets, etc. in the written part of a tutorial as well.

**Comment by jonathanbossenger** [comment]
Thank you @Zebedeu for the review.

**Comment by jonathanbossenger** [comment]
I have updated the tutorial to include a better description of how the responsive image `srcset` and `sizes` attributes work, as well as re-recorded the section at the end, showing how to use the custom image markup in a block theme pattern. 


https://github.com/WordPress/Learn/assets/180629/e2fafc0e-330c-40d0-b743-dd929dd63b39

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/tutorial/common-apis-responsive-images/
