### ISSUE TITLE
Hacktoberfest 2023

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1832]
Hacktobertfest is a yearly event focused on supporting open-source projects during the month of October. Participants join from around the world to fix bugs, submit features, and generally help improve open-source projects of their choice.

Hacktoberfest isn’t all about code. Anyone who writes, designs, tests, mentors, or organizes offers much-needed support for open-source projects all over the world.

This issue has been opened to prepare the Learn WordPress Github repository for Hacktoberfest and will be updated as new details and requirements emerge for this year's event.

**Comment by kafleg** [comment]
This is going to be a good for those who are not able to write codes.

**Comment by jonathanbossenger** [comment]
# Hacktoberfest 2023

Hacktoberfest is an annual worldwide event held during the month of October. The event encourages interested individuals to contribute to open-source projects by having 4 pull requests (PRs) accepted on GitHub and GitLab repositories.

Since 2022, Hacktoberfest has allowed non-code contributions to count towards the 4 required PRs. meaning that things like documentation updates, meeting agendas, and content creation can also count towards participation for Hacktoberfest.

So join us in working on 4 GitHub issues on the [Learn WordPress repository](https://github.com/WordPress/learn/), and take part in the fun.

## How to participate

1. Visit the [Hacktoberfest](https://hacktoberfest.com/) website and register your GitHub account
2. Find an open [issue](https://github.com/WordPress/Learn/issues) labeled `hacktoberfest` that you'd like to work on. If you find an issue that interests you and does not already have a `hacktoberfest` label, ping @jonathanbossenger and we will add it for you
3. Create a [pull request](https://github.com/WordPress/Learn/pulls) linking the issue you are working on.
4. Remember, to complete Hacktoberfest, you need 4 accepted/merged Pull Requests. So only open one pull request per issue you are working on. 

## New to Learn WordPress

We have a [detailed getting started guide](https://make.wordpress.org/training/handbook/getting-started/), which includes all the information you might need to know about contributing to this project. Please read through it and select your area of contribution. 

It may also help you to read our help doc on [how we use Github](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/) as a project.

If you are planning to contribute with code, you can read all about our local development environment, which is based on Docker, in the [project readme](https://github.com/WordPress/Learn#readme).

## Code contributions

Found a [bug](https://github.com/WordPress/Learn/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BType%5D+Bug%22) you'd like to fix? Create new a [pull request](https://github.com/WordPress/Learn/pulls) which includes the required changes and a link to the issue. Please read the Code Contributions guide on [creating new Pull Requests](https://make.wordpress.org/training/handbook/training-team-how-to-guides/code-contributions/#creating-a-pull-request)

## Non-code contributions

Learn.WordPress.org has many non-code areas of contribution, including (but not limited to) creating, reviewing, editing, or translating content, updating documentation, drafting meeting recap notes, and more. 

Hacktoberfest also supports non-code contributions, so if you're working in any of these areas, you can also take part. 

To facilitate creating a pull request for these contributions, we have created the [hacktoberfest-2023.md](https://github.com/WordPress/Learn/blob/trunk/hacktoberfest-2023.md) file. You can use this file to create the pull request for your work, to take part in Hacktoberfest. 

Instructions to create your pull request are in the file. 

## Need help

If you have any questions or need any help, please ping either @jonathanbossenger or @digitalchild

**Comment by devmuhib009** [comment]
My one issue marked as hacktoberfest, I created pull request for that. Can I update others issues in md file as well?

**Comment by jonathanbossenger** [comment]
> Can I update others issues in md file as well?

If you mean there are other issues you're working on this month that you would like to include, please go ahead and create separate PRs for each one, adding them to the [hacktoberfest-2023.md](https://github.com/WordPress/Learn/blob/trunk/hacktoberfest-2023.md) file.

**Comment by jonathanbossenger** [comment]
Please also add me as the reviewer, so I get a notification to review. I'll see them anyway on Thursdays when I do dev-squad triage, but it will help the process.

**Comment by devmuhib009** [comment]
Ok thanks

**Comment by devmuhib009** [comment]
https://github.com/WordPress/Learn/issues/1890

I worked only on one issue this month. I already added that on md file and created a PR. I did not worked on above mentioned ticket #1890 My question is, can I update md file for this issue and create a new PR?

**Comment by kaitohm** [comment]
Can this be closed now, @jonathanbossenger ?

**Comment by kaitohm** [comment]
Oh, now that October is over, could we remove the hacktoberfest label from all remaining open issues? That will reset the slate for next year, and also visually clear up the project boards - if they're no longer needed this year.

**Comment by jonathanbossenger** [comment]
Yep, we can close this now, and remove all hacktoberfest labels.

**Comment by kaitohm** [comment]
Great! The label has been removed from all open issues ✅
