### ISSUE TITLE
Content Feedback - Introduction to block development course

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1835]
## Overview
- Content title: Introduction to block development course
- Content URL: https://learn.wordpress.org/course/introduction-to-block-development-build-your-first-custom-block/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: 

## Feedback Details

See below

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by westnz** [comment]
Please validate the feedback received.

July / August Student Feedback:

**Question: What could we add or change?**

1. Adding color controls to the "styles" tab of the block instead of the settings tab
2. Having created the custom block, I was not sure how to produce a production version using npm. Some help on this would have been useful.
3. Extend this course and create several blocks in one plugin
4. Please provide more examples of attributes.
5. Add more exercises

**Comment by jonathanbossenger** [comment]
Some initial thoughts

> Having created the custom block, I was not sure how to produce a production version using npm. Some help on this would have been useful.

This is covered in the https://learn.wordpress.org/lesson/build-and-run-your-project/ lesson in this course, so maybe just a reminder of the build steps from that lesson somewhere along the line is necessary

> Please provide more examples of attributes.
> Add more exercises

How far should an "Introduction" course go in showing examples and adding exercises?

**Comment by westnz** [comment]
Hey @jonathanbossenger 
A few examples and one or two exercises/practical challenges should suffice.

**Comment by jonathanbossenger** [comment]
Closing in favour of the work being done on learning pathways
