### ISSUE TITLE
Content Feedback - A Developers Guide to Block Themes – Part 1 + 2 (courses)

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1836]
## Overview
- Content title: A Developers Guide to Block Themes – Part 1
- Content URL: https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-1/ + https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-2/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: 

## Feedback Details

See below

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by westnz** [comment]
Student Feedback July/August:

**Part 1**

**Question: What can we add or change?**

I loved this one: "I am too satisfied with the course to think of anything at the moment." ❤️ 

Please validate the feedback:

1. Using the Create Block Theme refers to "Overwrite" when saving to the current theme files, I believe this is actually "Save Changes"?
2. Video demonstration
3. Something missing for the Search template file. You don't get a result.
4. Suggestion: WP Block API evolves over time and might invalidate some of the course materials. Pls do update this course when that happens. Thanks!
5. Course images looked different than on my local WP installation, 6.2.2. It would help for them to match.

**Part 2**

**Question: What can we add or change?**

1. A video tutorial that covers WordPress version 6.3
2. include more images or instructions when it says things like "open block theme editor." I think the most current version of WordPress (6.2.2) is different than in the tutorial.
3. Make it more in-depth please.

**Comment by cynthianorman** [comment]
Here's the Content Feedback for Part 1 https://github.com/WordPress/Learn/issues/1794

**Comment by jonathanbossenger** [comment]
Closing in favour of the work being done for learning pathways
