### ISSUE TITLE
Online Workshop - How to contribute to WordPress by just being helpful

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1839]
# Event Details
- Title: How to contribute to WordPress by just being helpful
- Description: If you're the type of person who likes to help others, then one of the least complicated ways you can contribute to WordPress is helping out in the support forums. Every day WordPress users from all over the world post questions in the WordPress support forums, with topics ranging from first time installation problems all the way to plugin and theme errors. All you need to help out in the forums, is a local WordPress installation to test out the problem, and a WordPress.org profile in order to be able to reply to the forum thread. In this online workshop, we'll take a look at how the support forums work, how to find topics to reply to, and maybe even help troubleshoot and reply to a few forum threads.
- Target Audience: Any WordPress user
- Date: 2023-09-07 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/295844300/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by sumitsinghwp** [comment]
Hey @jonathanbossenger, I am available as a Co-host for this event.

**Comment by jonathanbossenger** [comment]
Thanks @sumitsinghwp, this will be a slightly different than usual workshop, so I'm not needing a co-host for this one.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/09/11/how-to-contribute-to-wordpress-by-just-being-helpful/
