### ISSUE TITLE
Meeting Agenda September 5, 2023

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1840]
Training Team meetings start at 07:00 UTC weekly on Tuesdays. Anyone is welcome to contribute to the meeting by commenting in Slack threads throughout the week. Meeting notes will be published at the end of the week to also incoporate these asynchronous conversations.

_This week’s meeting will be hosted by @bsanevans ._

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- September 5 – [@sumitsingh](https://profiles.wordpress.org/sumitsingh/)
- September 12 – [@nayanchamp7](https://profiles.wordpress.org/nayanchamp7/)
- September 19 – [@sancastiza](https://profiles.wordpress.org/sancastiza/)
- September 26 – **Needs volunteer**

**2. Looking for feedback**

- Team value refresher: **Impact**.
- [Looking for feedback: Learning pathway outlines](https://make.wordpress.org/training/2023/08/24/looking-for-feedback-learning-pathway-outlines/)
- The [Training Team Accessibility Checklist](https://make.wordpress.org/training/handbook/guidelines/training-team-accessibility-checklist/) has been published. Please review and leave any feedback here in the channel.

**3. Looking for volunteers**

- We're looking for volunteers to author the October edition of the Learn WordPress newsletter. ([Learn WordPress Newsletter – September 2023](https://learn.wordpress.org/learn-wordpress-newsletter-september-2023/) was published last week.)

**4. Updates from last week's dev-squad triage session**

- Dev squad triaged the following PRs and open issues
  - #1815 
  - #1829
  - #1834 
  - #1633 
  - #1657 
  - #1659
- Additionally, the following discussions took place
  - A need for a clearer difference between PR/issue labels for platform and content items
  - Ensure when we are reviewing the new .org redesign, we take Sensei's course layouts into account

**5. Other news**

- Learn's first [Announcing the first Learn WordPress Course Cohort](https://make.wordpress.org/training/2023/08/02/announcing-the-first-learn-wordpress-course-cohort/).
- If you attended the [the Community Summit](https://communitysummit.wordcamp.org/2023/), come leave your observations/learnings that relate to the Training Team on this post: [Let’s share our notes from the Community Summit](https://make.wordpress.org/training/2023/09/05/lets-share-our-notes-from-the-community-summit/)
   -  You can also find the official notes from each session on https://make.wordpress.org/summit/
- Contributor day post: 
- The Training Contributor badge was awarded to [Nahid Sharif Komol](https://profiles.wordpress.org/nahidsharifkomol/) and [Asad Polash](https://profiles.wordpress.org/iamasadpolash/).

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - #443 
  - #1776 
- **Lesson Plans**
  - #806 
- **[Translated Content](https://github.com/orgs/WordPress/projects/104/views/1?filterQuery=label%3A%22Ready+for+Review%22)**
  - #1427 
  - #1488 
  - #1508 
  - #1535 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) - @westnz 
   - [Looking for feedback: Learning pathway outlines](https://make.wordpress.org/training/2023/08/24/looking-for-feedback-learning-pathway-outlines/) - **due September 12**
- [Training joining Hacktoberfest](https://github.com/WordPress/Learn/issues/1832)
  - @jonathanbossenger will explain this event and what it means for the team to participate.
- [Introducing the Training Team Guide Program!](https://make.wordpress.org/training/2023/08/03/introducing-the-training-team-guide-program/) - @courtney-pk 
  - We have introduced 11 new contributors to our roster of 5 Guides! They are expected to complete the program within the month of September. We're excited to kick off this initial cohort of new contributors and look forward to their first contributions to the team.
  - _Note: Create thread for both participants and guides to introduce themselves._
- [Next steps for GitHub updates](https://make.wordpress.org/training/2023/07/08/next-steps-for-github-updates/) - @bsanevans 
   -  Jo, Pooja, and Ben are meeting later today to brainstorm. Look forward to announcements about the next steps for GitHub coming soon.

## 5. Open Discussions

- [WordCamp Kathmandu ](https://kathmandu.wordcamp.org/2023/contributor-day/)has a Contributor Day on September 8, and @webtechpooja is leading a Training team table! If anyone is attending WC Kathmandu, please come and join the team at that table.

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by courtney-pk** [comment]
Thanks for the ping! Regarding the Guide Program, we have introduced 11 new contributors to our roster of 5 Guides! They are expected to complete the program within the month of September. We're excited to kick off this initial cohort of new contributors and look forward to their first contributions to the team.

Perhaps you can also welcome the new contributors participating in the Guide Program, and encourage them to say hello in a thread? And maybe Guides could also be encouraged to say hello so we can give them recognition.

**Comment by webtechpooja** [comment]
Can we mention [WordCamp Kathmandu ](https://kathmandu.wordcamp.org/2023/contributor-day/)has contributor day on September 8, and there we have a Training team table? If anyone is attending WC Kathmandu, please come and join us at the Training team table.

**Comment by kaitohm** [comment]
@courtney-pk Thanks for the update 📝 

@webtechpooja Sure! I've added that to today's agenda ✅

**Comment by jonathanbossenger** [comment]
@bsanevans @webtechpooja I have added the dev-squad triage update to the agenda.

**Comment by Piyopiyo-Kitsune** [comment]
A few points

- Let's announce @aurooba joining the Faculty team!
- Can we ping Jo Minney to see if she has an update re: information architecture next steps for the Learning Pathways project? <3 
- Contributor Day recap https://make.wordpress.org/training/2023/09/05/wordcamp-us-2023-contributor-day-recap/

**Comment by kaitohm** [comment]
This week's meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1693897273940369

**Comment by kaitohm** [comment]
Meeting notes published here: https://make.wordpress.org/training/2023/09/11/training-team-meeting-recap-5th-september-2023/
