### ISSUE TITLE
Bug Report - Training Contributor Badge on broken image 

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/Learn#1842]
## Description
showing broken image on "[Training Contributor Badge](https://make.wordpress.org/training/handbook/about/team-profile-badges/#training-contributor-badge)"

## Expected behaviour
Broken image showing right now
![image](https://github.com/WordPress/Learn/assets/23701579/193ba11e-ee32-4b5a-8d5b-4d5f46abf8b9)

## Screenshots or screen recording (optional)
![image](https://github.com/WordPress/Learn/assets/23701579/945775ad-faa9-4aae-96e3-7a9724031177)

**Comment by kafleg** [comment]
Same issue for me as well.

**Comment by kaitohm** [comment]
Thanks for flagging this! I have corrected the images: https://make.wordpress.org/training/handbook/about/team-profile-badges/
