### ISSUE TITLE
Bangla translation for Tutorial "Choosing and Installing a Theme"

### ISSUE THREAD

**Issue by devmuhib009** [WordPress/Learn#1845]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/choosing-and-installing-theme/
- Link to original content GitHub issue (optional): https://github.com/WordPress/Learn/issues/758
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by devmuhib009** [comment]
Any reviewer please?

**Comment by devmuhib009** [comment]
I just translated the content. Please check this [document](https://docs.google.com/document/d/1vrEnaWwM9EK8TaMi204vh9ym9g-jL5y5ja8vFJRrgQ0/edit?usp=sharing) on Google drive.

**Comment by robinwpdeveloper** [comment]
@devmuhib009 I have checked first 3 pages. Here are some suggestions: 

> অফিসিয়াল WordPress.org ডিরেক্টরিতে হাজার হাজার ফ্রি থিম আছে এবং হিসাবে অনেক,  অন্ততপক্ষে একটি বাণিজ্যিক জায়গায় আছে।

অফিসিয়াল WordPress.org ডিরেক্টরিতে হাজার হাজার ফ্রি থিম আছে এবং বাণিজ্যিক জায়গাতেও অন্ততপক্ষে সমসংখ্যক আছে।


> ১। ভোক্তাদের কাছে এভেইলেবল থিমগুলোর বিশালতা চিনুন।

১। ভোক্তাদের কাছে উপলব্ধ থিমগুলোর বিশালতা চিনুন।


> সম্পূরক জিজ্ঞাসা

সম্পূরক প্রশ্ন


> ১। থিম রিপোসিটরি

১। থিম রিপোজিটরি


> হাই, এবং ওয়ার্ডপ্রেস শিখায় আপনাকে স্বাগতম

হাই, এবং লার্ন ওয়ার্ডপ্রেসে আপনাকে স্বাগতম


> অনেক ফ্রি ভার্শন আরও প্রিমিয়াম থিম অফার করে ডেভেলপার বা থিম-বিক্রির সাইট থেকে ।

অনেক ফ্রি ভার্শন প্রিমিয়াম থিম অফার করে ডেভেলপার বা থিম-বিক্রির সাইট থেকে ।

> গুটেনবার্গ ব্লক পরিচয় করানো হয়েছে পোস্ট এবং পেইজগুলি রচনা করার 

গুটেনবার্গ ব্লক এডিটরে পোস্ট এবং পেজ বানানোর ব্লকের পরিচয় করানো হয়েছে


> সম্পূর্ণ সাইট এডিটিং এর সাথে, ব্লকের অভিজ্ঞতা এবং প্রসারিততা এখন আপনার সাইটের সমস্ত অংশে এভেইলেবল 

ফুল সাইট এডিটর এর সাথে, ব্লকের অভিজ্ঞতা এবং প্রসারিততা এখন আপনার সাইটের সমস্ত অংশে এভেইলেবল


>  ফুল সাইট এডিটিং মুলত ফিচারগুলির একটি সংগ্রহ এবং ক্লাসিক থিমগুলি তাদের কিছু ফিচার ব্যবহার করার জন্য অপ্ট-ইন করতে পারে৷ 

 ফুল সাইট এডিটর এর মধ্যে অনেকগুলো  ফিচার রয়েছে যার মধ্যে কিছু ক্লাসিক থিমগুলি অপ্ট-ইন করতে পারে৷

**Comment by devmuhib009** [comment]
Thanks for review and advice. I will update and inform.

**Comment by devmuhib009** [comment]
Considering your advices, I just updated the [translation](https://docs.google.com/document/d/1vrEnaWwM9EK8TaMi204vh9ym9g-jL5y5ja8vFJRrgQ0/edit?usp=sharing) file. Please take a look and advice me if I need to modify it again.

**Comment by robinwpdeveloper** [comment]
> ১। থিম রিপোসিটরি

১। থিম রিপোজিটরি


> থিমগুলিতে ক্লিক করুন

থিমস্ এ  ক্লিক করুন

Another observation: We need to be consistent regarding the term "Available". এভেইলেবল অথবা উপলব্ধ। 

Overall looks good to me 👍

**Comment by devmuhib009** [comment]
I will update both and use the word উপলব্ধ.

**Comment by devmuhib009** [comment]
Just updated the file according to your suggestion. Here is the [updated file](https://docs.google.com/document/d/1vrEnaWwM9EK8TaMi204vh9ym9g-jL5y5ja8vFJRrgQ0/edit?usp=sharing). Please suggest me what to do next?

**Comment by robinwpdeveloper** [comment]
Here is the process.
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/ 

Feel free to post on #training team slack.  
A translation coordinator will publish the post on Learn WordPress website.

**Comment by devmuhib009** [comment]
Thanks a lot

**Comment by kafleg** [comment]
I have created a draft on the learning site. I'll inform you if I need any help.

**Comment by devmuhib009** [comment]
ok thanks a lot.

**Comment by webtechpooja** [comment]
@kafleg, you have created a lesson plan, and the Tutorial Transcript falls under the Tutorial menu. I have drafted a Tutorial with the transcript. here is the draft link: https://learn.wordpress.org/?p=42759&post_type=wporg_workshop&preview=1&_ppp=4133f129d7
@devmuhib009, please have a look at the draft and confirm if everything is OK. Then I'll hit publish it. Thank you all for your contribution.

**Comment by devmuhib009** [comment]
Hello @webtechpooja and @kafleg 
Everything looks, fine. But bullet point is not required in this section. Because I already marked the numbers in Bangla. So, please remove the bullet points and rest of the things are looking good. Thanks a lot.
![bullet](https://github.com/WordPress/Learn/assets/142894870/7e1e05a8-6385-4325-97e7-f494fe15c5d2)

**Comment by webtechpooja** [comment]
Updated, please check now

**Comment by devmuhib009** [comment]
Awesome, looking nice. You can publish now. Thanks

**Comment by webtechpooja** [comment]
Tutorial published - https://learn.wordpress.org/tutorial/bn-choosing-and-installing-theme/
