### ISSUE TITLE
Meeting Agenda September 12, 2023

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1849]
Training Team meetings start at 07:00 UTC weekly on Tuesdays. Anyone is welcome to contribute to the meeting by commenting in Slack threads throughout the week. Meeting notes will be published at the end of the week to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune ._

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

September 12 – [@nayanchamp7](https://profiles.wordpress.org/nayanchamp7/)
September 19 – [@sancastiza](https://profiles.wordpress.org/sancastiza/)
September 26 – [@benjirahmed](https://profiles.wordpress.org/benjirahmed/)
October 3  – Needs volunteer

**2. Looking for feedback**

- [Looking for feedback: Learning pathway outlines](https://make.wordpress.org/training/2023/08/24/looking-for-feedback-learning-pathway-outlines/)
  - This is the final week to provide feedback on these outlines-- please share your thoughts by Friday, September 15th.
- The [Training Team Accessibility Checklist](https://make.wordpress.org/training/handbook/guidelines/training-team-accessibility-checklist/) has been published. Please review and leave any feedback here in the channel.

**3. Looking for volunteers**

- We're looking for volunteers to author the October edition of the Learn WordPress newsletter. (See the [Learn WordPress Newsletter – September 2023](https://learn.wordpress.org/learn-wordpress-newsletter-september-2023/) to see how its structured)

**4. Updates from last week's dev-squad triage session**

- No new PRs to be triaged
- Triaged the following open issues
  - #1660 
  - #1712 
  - #1758 
  - #1808 
  - #1813 
  - At the end of the session, all bugs awaiting triage were triaged, a first since the dev-squad inception! 🎉 

**5. Other news**

- Come check out [Let’s share our notes from the Community Summit](https://make.wordpress.org/training/2023/09/05/lets-share-our-notes-from-the-community-summit/)
- [Training Team joining Hacktoberfest](https://github.com/WordPress/Learn/issues/1832)
 - @jonathanbossenger is helping us our repository ready for folks to be able to pick up work.
- Educational content from Learn WordPress has been added to [this Hosting Handbook page](https://make.wordpress.org/hosting/handbook/learn-hosting/).
-  The Learning Pathways post [has been highlighted on WPTavern](https://wptavern.com/wordpress-training-team-seeks-community-feedback-on-learning-pathways)

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
   - #443 
   - #1776 
- **Lesson Plans**
   - #806 
- [**Translated Content**](https://github.com/orgs/WordPress/projects/104/views/1?filterQuery=label%3A%22Ready+for+Review%22)
  - #1427 
  - #1488 
  - #1508 
  - #1535 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) 
  - [Looking for feedback: Learning pathway outlines](https://make.wordpress.org/training/2023/08/24/looking-for-feedback-learning-pathway-outlines/) - due September 15
  - A meeting was held today to discuss final plans for the Learn website's new information architecture ([see notes here](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-3985)). The plan will be shared with the wider Training Team for review in a week.
- [Next steps for GitHub updates](https://make.wordpress.org/training/2023/07/08/next-steps-for-github-updates/)
  - Recent update published on [the project post](https://make.wordpress.org/training/2023/07/08/next-steps-for-github-updates/#comment-3984).
  - The team will be publishing a proposal for reducing the number of GitHub issue templates by September 22nd.
  - Jo is currently exporting the list of GitHub labels for the team to then sort through and document together.

## 7. Faculty Updates
Time for a Faculty check-in! @faculty please answer any that apply:
• What have you been working on and how has it been going?
• Anything you’ve accomplished since the last meeting?
• Do you have any blockers?
• Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions
- Regarding [course cohorts,](https://make.wordpress.org/training/2023/08/02/announcing-the-first-learn-wordpress-course-cohort/) how do we indicate that folks have completed the cohort?
- When can an interested contributor take over developing a piece of content which had originally been assigned to another contributor, but no progress has been made for some time?

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
I'd like to bring up an idea that I had from my course cohort: how do we indicate that folks have completed the cohort? 

I was thinking it might be interesting to somehow list completed courses on folks' WordPress.org profiles, perhaps similar to the current Activity tab, so I'd like to see what the rest of the team thinks about this idea.

**Comment by courtney-pk** [comment]
Can we please add a thread for Faculty check-ins? Feel free to introduce this as a new weekly thread that we're trying out during team meetings.

It can look something like:
> Time for a Faculty check-in! `@faculty` please answer any that apply:
> • What have you been working on and how has it been going?
> • Anything you’ve accomplished since the last meeting?
> • Do you have any blockers?
> • Can other Faculty or Training Team members help you in some way?

**Comment by kaitohm** [comment]
A need has risen lately to clarify when an interested contributor can take over developing a piece of content which had originally been assigned to another contributor, but no progress has been made for some time.

The [content localization handbook currently mentions](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/triaging-content-localization-issues/#issues-in-the-translation-in-progress-column):
* If a GitHub issue has been stale for 2 weeks, ping the person assigned to see how they're going
* If no response is received after a further 2 weeks, then the issue should be triaged and either closed, reassigned, or opened for others to take on

I propose we introduce a similar timeframe to content development issues, and clarify this in the handbook: [Triaging Content Development Issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/triaging-content-development-issues/)

Could we see what other folks think of this, too, please?

**Comment by kaitohm** [comment]
I've updated the issue above with an additional note taker who volunteered for the 26th, and an update from the GitHub updates project.

**Comment by jonathanbossenger** [comment]
I've updated the agenda with the updates from last week's dev-squad triage session. 

Thank you @Piyopiyo-Kitsune for posting the agenda so early! 🙌

**Comment by jonathanbossenger** [comment]
Last minute addition, the Learning Pathways post has been highlighted on WPTavern https://wptavern.com/wordpress-training-team-seeks-community-feedback-on-learning-pathways

**Comment by Piyopiyo-Kitsune** [comment]
Updated above with folks' additions-- thanks all!
