### ISSUE TITLE
Make clear that quizzes that come up in search results are quizzes

### ISSUE THREAD

**Issue by andreamiddleton** [WordPress/Learn#185]
I really like our search function, and I like that it's so easy to find on the landing page. However, when I searched the term "ecommerce," the first result was a quiz for a workshop. 

I'm not sure about the wisdom about having workshop quizzes come up in search results, BUT I do think that if we're going to serve them up, we should make clear on the results page, that a quiz is a quiz. See below: 

![Search results screen shot](https://user-images.githubusercontent.com/2285933/102936609-57c35b00-445d-11eb-9b03-226ae066821b.png)

I recommend adding a tag or category or something to the cards that show up in search results, to clarify that a certain result is a quiz, rather than a course landing page or a workshop. :)

**Comment by hlashbrooke** [comment]
Better yet - we should actually exclude quizzes from search results entirely. It's just a matter of excluding the post type of `quiz` from search queries.

**Comment by hlashbrooke** [comment]
We also need to exclude the `lesson` post type from search results.

**Comment by hlashbrooke** [comment]
@coreymckrill Could we please get this issue fixed as a matter of urgency? I doesn't sound like a big job to fix, but either way, it's something we need sorted out ASAP.
