### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by sakaruk** [WordPress/Learn#1852]
## Description
The Project board link under the Heading [Organizing task](https://make.wordpress.org/training/handbook/about/how-we-work-together/#organizing-tasks) in Page **How We Work Together** in Training handbook is broken

## Step-by-step reproduction instructions
1. Go to the page [How we Work Together](https://make.wordpress.org/training/handbook/about/how-we-work-together/#organizing-tasks) 
2. Scroll to the Sub Heading Organizing task
3. Click the link project board under scrum link

## Expected behaviour
Should point to the project board of Learn

## Actual behaviour
Is broken link

## Environment information
- All browsers
- Mac (IOS)

**Comment by jonathanbossenger** [comment]
Thank you for reporting this @sakaruk I have updated the link.

@bsanevans in reviewing this issue, I realize that we have more than one project board now, so might be worthwhile revising this section at some point.

**Comment by kaitohm** [comment]
Thanks for the ping. I've updated the sections corresponding to the team's GitHub project boards. The sections related to the team's content creation flows need an overhaul, too. I'll get back to this as part of the [GitHub updates project](https://make.wordpress.org/training/2023/07/08/next-steps-for-github-updates/).
