### ISSUE TITLE
Content Feedback - Typo in Simple Site Design and Site Editing Course

### ISSUE THREAD

**Issue by pablinos** [WordPress/Learn#1855]
## Overview
- Content title: How do you insert a block pattern?
- Content URL: https://learn.wordpress.org/lesson/how-do-you-insert-a-block-pattern/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: Yes, it's possibly a typo

## Feedback Details

<img width="747" alt="image" src="https://github.com/WordPress/Learn/assets/96462/dfc7d57e-40d1-4945-bc84-8c58a5574727">

The title for the video says "What this helpful online workshop about using block patterns". I think that could be "Watch this helpful..."

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by SierraTR** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? (Yes or No): Yes
- What should happen next to apply the feedback?:  Issue correctly identifies what appears to be a typo/auto-correct error in wording for the introduction to a video.
- Wording corrected as suggested by  the submitter.
