### ISSUE TITLE
Online Workshop - Common WordPress APIs:  HTTP Request API

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1857]
# Event Details
- Title: 
- Description: The WordPress HTTP Request API allows you to make requests to external services to fetch and send data between a WordPress site and the external service. This is very useful if you need to interact with external APIs. In this session, we'll look at the helper functions that the HTTP Request API provides, and how to use them. 
- Target Audience: Developers
- Date: 2023-09-14 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/296032972/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by AsadPolash** [comment]
Hi @jonathanbossenger 
I would like to be the co-host for the session.

**Comment by jonathanbossenger** [comment]
Thanks @AsadPolash that would be very helpful of you. 🙏

**Comment by AsadPolash** [comment]
There were 22 total workshop participants

**Comment by jonathanbossenger** [comment]
Thank you @AsadPolash

**Comment by jonathanbossenger** [comment]
https://www.meetup.com/learn-wordpress-online-workshops/events/296032972/
