### ISSUE TITLE
Chinese Traditional translation for Lesson Plan "What You Can Do With WordPress"

### ISSUE THREAD

**Issue by yuliyang** [WordPress/Learn#1858]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/what-you-can-do-with-wordpress/
- Link to original content GitHub issue (optional): https://github.com/WordPress/Learn/issues/421
- Language you'll be translating to:  Chinese Traditional
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: @huanyichuang
- Other info: I will update original content to newer style format before translating the content.
https://docs.google.com/document/d/1ijzQpay7P_jJMTYvNcPZKMqYyjz2FTy6Sny79Fd73js/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by yuliyang** [comment]
I found a Chinese Traditional content translation reviewer. @huanyichuang is the locale manager. I will try to finish the translation content next week.

**Comment by kaitohm** [comment]
Thanks for translating, @yulilan ! Here is a draft lesson plan you can put the translation into: https://learn.wordpress.org/wp-admin/post.php?post=43246&action=edit

@huanyichuang Please let us know when the translation review has been done 🙌

**Comment by yuliyang** [comment]
Chinese Traditional Translation is done. However, I would like to make some changes to the original content (English). Can I get someone to review my editing suggestions and comments? @bsanevans 

@huanyichuang Can you help me review the translation? Thank you!

**Comment by kaitohm** [comment]
Are these larger changes, @yuliyang ? If they are minor (like typing mistakes), then you are free to edit them directly in Learn WordPress. (You should already have access to do that 👍 )

If they are larger changes to the content itself, then could you submit a new "Content Feedback" GitHub issue from https://github.com/WordPress/Learn/issues/new/choose ? That will then go through a review process before the updates are applied.

**Comment by yuliyang** [comment]
Thank you @bsanevans I've created a new issue for content feedback here: https://github.com/WordPress/Learn/issues/1966

**Comment by kaitohm** [comment]
Thanks for creating a new issue.

Feel free to replace the English in https://learn.wordpress.org/wp-admin/post.php?post=43246&action=edit with the Chinese translation. Once done, let me know, and I will do a final check and publish the content.

**Comment by yuliyang** [comment]
@bsanevans Lesson plan is ready for publish review: https://learn.wordpress.org/lesson-plan/what-you-can-do-with-wordpress-zh-tw/

**Comment by kaitohm** [comment]
Thanks! I've changed the slug to put the language first to math our other content. Otherwise, this looks great. Thank you!
https://learn.wordpress.org/lesson-plan/zh-tw-what-you-can-do-with-wordpress/
