### ISSUE TITLE
Feature request - add link to feedback page on every content type within a course

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1860]
@westnz currently manually adds a request for feedback message on every course. The message is aimed at course learners, directing them to leave feedback from https://learn.wordpress.org/report-content-feedback/.

A link to this page is currently shown in the sidebar of Tutorials and Lesson Plans in a `Suggestions > Let us know` button. We would like a similar button to show on every page within a course, too. An update to the site theme will most likely be needed.

**Comment by jonathanbossenger** [comment]
@bsanevans please explain what you mean by "every page within a course". I assume you mean on the main course landing page, as well as on individual lessons within a course.

**Comment by kaitohm** [comment]
Yup 👍 I also mean the quiz pages, and course completion pages. Basically, it would be great to have a consistent way for folks to reach out with feedback, no matter at what point in their learning journey they get stuck.

**Comment by jonathanbossenger** [comment]
Got it. I think what we'd need to do here is do a review of those pages, and then see what is possible. I know that Sensei has the ability to edit some of these templates in the editor, and possibly also as theme files that override Sensei theme files. 

The reason I say this is that I created a [similar issue around reporting errors on courses](https://github.com/WordPress/Learn/issues/1709) some time back, and then went down a rabbit hole of trying to find a quick fix, which didn't work out as well as I hoped.

I think a good first step would be for us to select one of the shorter courses, screenshot all the relevant pages, detail what we'd like to add, and then investigate options and report back.

**Comment by SierraTR** [comment]
Johnathan, I believe this is like the button you removed a couple of months ago because it did not have an href tag. 
It was a button in the lesson template, left column under the course content navigation section.
![feedback-button-sensei-lesson-template](https://github.com/WordPress/Learn/assets/3642121/8f450ff2-810c-4a65-adca-110c9e139bf3)

**Comment by jonathanbossenger** [comment]
@SierraTR yes, this was the one, I was trying to see if there was a quick win solution.

**Comment by digitalchild** [comment]
I will first investigate the possibility of updating the sensei templates and then if that doesn't work, I will investigate a code solution.

**Comment by digitalchild** [comment]
**Courses**
Courses have learning mode which provides a FSE default template. This would allow us to add buttons for feedback as well as for #1709 (Allowing users to report errors on courses). 

![Xnapper-2023-12-07-16 41 10](https://github.com/WordPress/Learn/assets/909468/2c8f76ef-c7d5-47d3-92bd-ed57d098de5a)

**Quiz**

Quizzes do not use this FSE template, so we would need to hook into the bottom of the template to add these buttons/links. 

**Course completion**

This also doesn't have an FSE template so this would need to be a template override.

**Comment by jonathanbossenger** [comment]
Thanks, @digitalchild 

@bsanevans at this stage, I wonder if it would make sense to create separate issues for each item:
1. Lesson page
2. Quiz page
3. Course completion page
All being tracked as separate tasks in this issue?

**Comment by kaitohm** [comment]
Sure 👍

**Comment by kaitohm** [comment]
@adamwoodnz Is this feature request (adding a link to the feedback page on each lesson and quiz) something that can be looked at as part of the redesign process?

**Comment by adamwoodnz** [comment]
> @adamwoodnz Is this feature request (adding a link to the feedback page on each lesson and quiz) something that can be looked at as part of the redesign process?

Yep, I'll add it to the [project](https://github.com/orgs/WordPress/projects/40/views/26), and we'll try to get it done for launch.

**Comment by adamwoodnz** [comment]
I think we already have this on the course completed page:

<img src="https://github.com/user-attachments/assets/cb60b2b1-c573-44cd-b14a-14162d3376eb" width="300">

Which leaves lessons and quizzes. The course completed survey has specific wording so it seems we'd need to new survey forms created.

@WordPress/meta-design thoughts on design for single lesson and quiz views please?

**Comment by kathrynwp** [comment]
> I think we already have this on the course completed page:

Correct, the course survey is already done!

The course survey is for overall feedback on a course. It is structured and includes a 1-5 rating that allows us to calculate an average satisfaction rating for each course.

On the other hand, the type of feedback link we'd like to add to lessons and quizzes is for reporting specific issues like:

- typos
- outdated screenshots
- confusing instructions
- malfunctioning quiz
- other types of specific problems

The wording we had for soliciting this feedback before the remake was:

> Suggestions

> Found a typo, grammar error, or outdated screenshot? 

> Let us know (this was a button)

I would propose condensing things a bit, to something like this:

> Report an issue (make this a button)

> Let us know if you've found a typo, grammar error, or outdated screenshot/video.

I think we can continue to use the feedback form here, so no new form needs to be created: 

https://learn.wordpress.org/report-content-feedback/

Hope this clarifies!

**Comment by adamwoodnz** [comment]
Redesigned UI reused from course sidebar:

| Lesson | Standalone Lesson | Quiz |
|--------|--------|-|
| ![Image](https://github.com/user-attachments/assets/47355da7-0f9e-4c35-afdc-83016a7698f3) | ![Image](https://github.com/user-attachments/assets/d39b5d22-3ee8-4f47-b337-28f55c343921) | ![Image](https://github.com/user-attachments/assets/4044afea-6198-4545-b41d-4b7b60123c38) |
