### ISSUE TITLE
Bug report - Broken Link in Handbook 

### ISSUE THREAD

**Issue by yuliyang** [WordPress/Learn#1861]
## Description

Broken link in Handbook - How to Conduct an Instructional Review

## Step-by-step reproduction instructions

1. Go to Learn Handbook - How to Conduct an Instructional Review: https://make.wordpress.org/training/handbook/lesson-plans/how-to-conduct-an-instructional-review/
2. Scroll to the section "Instructional Review Checklist" and click the link in 1st bullet point

## Expected behaviour

Should link to https://make.wordpress.org/training/handbook/lesson-plans/lesson-plan-style-guide/

## Actual behaviour

Original link is going to page not found: https://make.wordpress.org/training/getting-started/lesson-style-guide/

## Environment information
- Browser(s) are you seeing the problem on: Arc
- Device you are using and operating system: Mac

**Comment by SierraTR** [comment]
Yes, the issue is duplicated 
The intended destination of the link is correctly identified in the issue
The link on this page has been corrected and tested to operate correctly.
