### ISSUE TITLE
Online Workshop - Common APIs - Options

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1866]
# Event Details
- Title: 
- Description: The Options API is a simple and standardized way of storing general data about a WordPress site in the database. The API makes it easy to create, access, update, and delete options. In this session, we will look at what types of data you would store using this API, how and where the options are stored, and how to use to API to create, access, update and delete options.
- Target Audience: Developers
- Date: 2023-09-21 @ 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/296107277/
- Co-host: @SierraTR 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I'm available to co-host if you still need one.

**Comment by jonathanbossenger** [comment]
Thanks @SierraTR you're always welcome.

**Comment by SierraTR** [comment]
Another great session, thank-you.  You had 19 attendees.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/09/22/common-apis-options/
