### ISSUE TITLE
Meeting Agenda September 19, 2023

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#1868]
Training Team meetings start at 07:00 UTC weekly on Tuesdays. Anyone is welcome to contribute to the meeting by commenting in Slack threads throughout the week. Meeting notes will be published at the end of the week to also incoporate these asynchronous conversations.

_This week’s meeting will be hosted by @bsanevans ._

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- September 19 – [@sancastiza](https://profiles.wordpress.org/sancastiza/)
- September 26 – [@benjirahmed](https://profiles.wordpress.org/benjirahmed/)
- October 3 – Needs volunteer
- October 10 - Needs volunteer

**2. Looking for feedback**

- The team started a conversation last week about how we could indicate folks have completed a [course cohort](https://make.wordpress.org/training/2023/08/02/announcing-the-first-learn-wordpress-course-cohort/). Please leave your ideas in [this Slack thread from last week's meeting](https://wordpress.slack.com/archives/C02RW657Q/p1694504434505029).
- The team also started discussing: "When can an interested contributor take over developing a piece of content which had originally been assigned to another contributor, but no progress has been made for some time?" Please leave your feedback in [this Slack thread from last week's meeting](https://wordpress.slack.com/archives/C02RW657Q/p1694504869204909).

**3. Looking for volunteers**

- We're looking for volunteers to author the October edition of the Learn WordPress newsletter. (See the [Learn WordPress Newsletter – September 2023](https://learn.wordpress.org/learn-wordpress-newsletter-september-2023/) to see how its structured)
- Abha is looking for volunteers to help present about Learn WordPress for a Portsmouth Meetup in November.

**4. Updates from last week's dev-squad triage session**

@psykro got stuck into something else and completely missed running the dev-squad triage last week. However, there were only 2 open untriaged bugs, [so he quickly triaged them later in that day].(https://wordpress.slack.com/archives/C03B11FA16D/p1694677478691369).

- Fixed and closed #1861
- Triaged #1860

**5. Other news**

- Come check out [Let’s share our notes from the Community Summit](https://make.wordpress.org/training/2023/09/05/lets-share-our-notes-from-the-community-summit/)
- Educational content from Learn WordPress has been added to [this Hosting Handbook page](https://make.wordpress.org/hosting/handbook/learn-hosting/).

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - #758 
  - #455 
  - #1830 
- **Lesson Plans**
  - #806 
- **Translated Content**
  - https://github.com/orgs/WordPress/projects/104/views/10

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - details
- [Next steps for GitHub updates](https://make.wordpress.org/training/2023/07/08/next-steps-for-github-updates/)
  - details

## 5. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kaitohm** [comment]
Some of the agenda items will be filled out closer to the meeting.

@jonathanbossenger Could you share an update from last week's dev-squad triage session, please? 🙇‍♂️

**Comment by jonathanbossenger** [comment]
dev-squad triage update added.

**Comment by jonathanbossenger** [comment]
An additional agenda item, Sensei Pro, which we have a license key for and use on Learn WordPress, has had a few updates since [we last updated it on Learn](https://github.com/WordPress/Learn/issues/1606), so it might be a good time to create a new PR to merge the latest updates.

Additionally, it might be a good idea to somehow set a quarterly reminder to check on the Sensei Pro version and wrangle a Learn WordPress update.

**Comment by Piyopiyo-Kitsune** [comment]
Can we do a call to remind folks that they can put on Online Workshops or co-host them?

**Comment by kaitohm** [comment]
This week's meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1695106889426949
