### ISSUE TITLE
Add language switcher to Learn WordPress for UI translations

### ISSUE THREAD

**Issue by varlese** [WordPress/Learn#187]
All static strings for Learn WordPress are currently [available for translation via GlotPress](https://translate.wordpress.org/projects/meta/learn-wordpress/). To be able to display these strings on the front-end of the Learn WordPress site, can we implement a language switcher like the one available on https://wp15.wordpress.net/?

The language switcher should show all locale variants that have 90% or more of the strings translated. (This percentage mimics the [threshold for language packs](https://make.wordpress.org/polyglots/handbook/translating/after-your-contribution/#the-threshold-for-language-pack-creation) for plugins and themes.) Locales with a smaller amount of strings translated, then, can be hidden from the language switcher to help filter available languages for visitors to the site. 

Likewise, adding the ability to search for a language like the example language switcher will help filter choices for site visitors as the number of translated locales increases. We might also want to add the locale abbreviation for clarity, as well - i.e. `Français (fr_FR)`.

<img width="294" alt="language switcher" src="https://user-images.githubusercontent.com/1361760/106633268-a419b480-654c-11eb-8829-2d5c42309f6c.png">

[Related discussion (Polyglots P2).](https://make.wordpress.org/polyglots/2021/01/13/proposal-translating-learn-wordpress/)

**Comment by tobifjellner** [comment]
> ...90% or more of the strings translated. (This percentage mimics the threshold for language packs for plugins and themes.)

On meta projects, translations are usually applied string-by-string. Then there's a delay, consisting of a cron-task for committing changes plus waiting for next deploy. (If there are no commits made for several days, and thus no deploys, then translations won't propagate.)
I'd vote for NOT setting a threshold of 90%. If at least one string is translated, then I'd say that the language is established. (Perhaps, though, it could get some kind of "badge" at the top "This UI is translated to __% and contains some strings in English. You can contribute to the translation at ______(link to language-specific translation project)".

**Comment by varlese** [comment]
My one concern about not setting a threshold is that experience could come across as a little buggy (namely, when you click on the language switcher, if there are only a few strings translated it might seem like nothing changed). Including some sort of badge/tooltip with a call to action, however, sounds like it could both address that _and_ encourage contributions, which I'm a fan of 😄 

Perhaps we can start with implementing the switcher for any language with 1 < strings translated, and then, as a second step, see if we can get some design input for tooltip ideas.

**Comment by hlashbrooke** [comment]
@coreymckrill Can this issue be closed now? The local switcher is live and looks like it works well, but I might be missing something.

**Comment by coreymckrill** [comment]
Hmm, yep, I think this can be closed. Not sure now why I kept it open...
