### ISSUE TITLE
Typo Error

### ISSUE THREAD

**Issue by iqbalpb** [WordPress/Learn#1872]
## Description
Typo error in an announcement of **Reviewing Facilitator Applications** posted in **online workshop** section

## Step-by-step reproduction instructions
Please list the steps needed to reproduce the bug. For example:
1. Go to [Reviewing Facilitator Applications](https://make.wordpress.org/training/handbook/online-workshops/reviewing-facilitator-applications/)
2. Scroll down to **Identifying spam applications**
3. Instead of "application letter" mistakenly typed "application vetter"

## Expected Word
application letter

## Actual Word
application vetter

## Screenshots or screen recording (optional)
<img width="766" alt="Screenshot 2023-09-19 at 7 35 24 PM" src="https://github.com/WordPress/Learn/assets/19872875/a5d42e83-51ee-4f65-bc1d-31235cac646e">

## Environment information
- Browser: Safari
- Device: Mac OS

**Comment by SierraTR** [comment]
I believe that this phrasing is correct and what the writer intended - "application vetter" is referring to the person accomplishing the vetting of the content. When that person comes across a spam application...
