### ISSUE TITLE
Search box is working differently on same page

### ISSUE THREAD

**Issue by himshekhar97** [WordPress/Learn#1875]
## Description
On this page, https://learn.wordpress.org/ on the Recent Courses search box - https://learn.wordpress.org/courses/ is searching exactly the same title search.
But on the Tutorials https://learn.wordpress.org/tutorials/ is not showing only the exact search. Is this intentional?

## Step-by-step reproduction instructions
1. Go to 'https://learn.wordpress.org/'
2. On the Recent Courses section click on [View All Courses](https://learn.wordpress.org/courses/)
3. Search any course title you will get the exact same search result.
4. On the Recent Tutorials section click on [View All Tutorials](https://learn.wordpress.org/tutorials/)
5. Search any recent tutorial title you will get lots of results not only the title you search.

## Expected behaviour
Only search the exact result same as on recent courses [View All Courses](https://learn.wordpress.org/courses/)

## Actual behaviour
Searching all the results related to search string keywords.

## Screenshots or screen recording (optional)
Issue video [https://share.cleanshot.com/72rfjD7hlfSJyhk4XV1t]

## Environment information
- Browser(s) are you seeing a problem with Google Chrome
- Device you are using and operating system - Mac OS and Version 116.0.5845.187 (Official Build) (arm64)

**Comment by adamwoodnz** [comment]
Closing as Course search is working as expected with the new theme, eg. https://learn.wordpress.org/?s=block&post_type=course
