### ISSUE TITLE
how to clean my website

### ISSUE THREAD

**Issue by Rabindra54** [WordPress/Learn#1879]
# Details

- Topic description: 
- Audience (User, Developer, Contributor, etc.): 
- Learning objectives (What will the learner be able to do as a result of this content?): 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): 
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by Rabindra54** [comment]
clean my website and reinstal for practise of website design

**Comment by kaitohm** [comment]
Please reach out on https://wordpress.org/support/forums/ for questions with individual websites. Thanks.
