### ISSUE TITLE
Sort content based on language selected

### ISSUE THREAD

**Issue by varlese** [WordPress/Learn#188]
Related to #187 and [this discussion](https://make.wordpress.org/polyglots/2021/01/13/proposal-translating-learn-wordpress/).

Currently, visitors to Learn WordPress can use the filter options on the workshops page to filter content by language. To help create a more holistic, multi-lingual experience, can we explore connecting the content that appears _first_ to the language selected in the language switcher?

For example, if I select ja/Japanese from the language switcher, content in Japanese should appear first on the workshops page, prioritized by content recorded (audio) in Japanese and then content with available Japanese subtitles.

<img width="990" alt="Workshop Filters" src="https://user-images.githubusercontent.com/1361760/106633178-8c423080-654c-11eb-9f44-853624e75348.png">

In this case, it would be ideal to filter by root language rather than locale variants, unlike the proposal for the language switcher. In other words, filter by all Spanish content (`es_*`) if a visitor selects a Spanish language variant in the language switcher (i.e., `es_VE`). The idea here is that, while the UI translations will be customized according to a visitors' language variant, they will still be able to benefit from content in their language _in general_.

**Comment by tobifjellner** [comment]
I'd like to see a possibility to select more than one content language (perhaps still marking one language as the "primary" choice).
(and perhaps making sure that the choices are reflected in the URL, so that one could bookmark or share a specific view via the URL?)
