### ISSUE TITLE
Gujarati translation for "7 Tips to improve website security"

### ISSUE THREAD

**Issue by shail-mehta** [WordPress/Learn#1881]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/7-tips-to-improve-website-security/
- Link to original content GitHub issue (optional): 
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: Gujarati translation : https://docs.google.com/document/d/1WJcIlYD8Cnv3a2pdSPOOxVcFjT8hnEAGtdCkoMxI8TU/edit

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by shail-mehta** [comment]
Translated content: https://docs.google.com/document/d/1WJcIlYD8Cnv3a2pdSPOOxVcFjT8hnEAGtdCkoMxI8TU/edit

**Comment by shail-mehta** [comment]
@harshgajipara can you please review this?

**Comment by shail-mehta** [comment]
@webtechpooja Please do the needful

**Comment by shail-mehta** [comment]
@webtechpooja Any Update ?

**Comment by webtechpooja** [comment]
Hi @shail-mehta,
We have updated our handbook page to find the Translation reviewer. Do you want to give it a try?

https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translation-reviews/#working-with-the-polyglots-team-to-find-a-reviewer

**Comment by shail-mehta** [comment]
Thank you @webtechpooja

I have Created Request https://make.wordpress.org/polyglots/?p=51423

**Comment by harshgajipara** [comment]
Hi @webtechpooja, I am PTE on polyglots for #gu. Can I proceed with reviewing translations?

**Comment by webtechpooja** [comment]
@harshgajipara yes, ofcourse, please review it. Thanks for offering help

**Comment by harshgajipara** [comment]
Hi @webtechpooja, I reviewed the translations and it looks good to me. 
Thanks!

**Comment by shail-mehta** [comment]
Thank you @harshgajipara For Translation Review

**Comment by shail-mehta** [comment]
@webtechpooja  Please do the needful

**Comment by shail-mehta** [comment]
@webtechpooja Any Update?

**Comment by webtechpooja** [comment]
Hey @shail-mehta and @harshgajipara, Thank you for all your contributions to the Training team. I'll look into it by the end of the day and get back to you. Thanks

**Comment by shail-mehta** [comment]
Hi @webtechpooja 

Did you get a chance to review it?

**Comment by webtechpooja** [comment]
Published - https://learn.wordpress.org/tutorial/gu-7-tips-to-improve-website-security/
Thanks, @shail-mehta, for all your contributions to the team.

**Comment by shail-mehta** [comment]
Thank you @webtechpooja for Publish Article.
