### ISSUE TITLE
Bangla translation for Tutorial "Getting to know the WordPress Dashboard"

### ISSUE THREAD

**Issue by devmuhib009** [WordPress/Learn#1882]
Link to original content: https://learn.wordpress.org/tutorial/getting-to-know-the-wordpress-dashboard/
Link to original content GitHub issue (optional):
Language you'll be translating to: Bangla
Have you arranged for someone to review this translation?: No
Reviewer's GitHub username: @huzaifaalmesbah
Other info:

Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by devmuhib009** [comment]
Started translating the content. Still working on it. Here is the [Doc File](https://docs.google.com/document/d/10DASjm72OHNzo_LY5FfdrL4LOEBCf0FkCPRa3PKM-HI/edit?usp=sharing) where I am editing the translation.

**Comment by devmuhib009** [comment]
Hello @kafleg and @webtechpooja. 
I just completed the translation of this content. Here is the [Document File](https://docs.google.com/document/d/10DASjm72OHNzo_LY5FfdrL4LOEBCf0FkCPRa3PKM-HI/edit?usp=sharing). I need translation reviewer.

**Comment by devmuhib009** [comment]
@huzaifaalmesbah can you review this content if you can manage time?

**Comment by huzaifaalmesbah** [comment]
I read a few paragraphs. I will submit the report tonight.

**Comment by devmuhib009** [comment]
Thanks a lot.

**Comment by huzaifaalmesbah** [comment]
I think more needs to be improved.
> আপনার সাইটে লগ ইন করতে, ওয়েব ব্রাউজারের নির্দিষ্ট অংশে যান এবং আপনার বিস্তারিত দিয়ে লগিন এ ক্লিক করুন। 

> আপনি যে পোস্টগুলিতে ফিরে আসতে চান এবং পরে শেষ করতে চান, তার জন্য কুইক নোট লেখা খুবই উপকারী। 

> এক নজরে উইজেট বর্তমানে আপনার সাইটে থাকা সকল পেইজ, পোস্ট এবং মন্তব্যের মোট সংখ্যা জানতে দেয়।

> আপনার অবস্থানের উপর ভিত্তি করে, আপনি বিভিন্ন ওয়ার্ডপ্রেস সম্পর্কিত ইভেন্ট এবং মিটআপের একটি তালিকা দেখতে পাবেন।

**Comment by huzaifaalmesbah** [comment]
> আসুন পেইজগুলি সম্পর্কে কথা বলি। সুতরাং একটি পেইজ স্ট্যাটিক কন্টেন্টের জন্য ব্যভহৃত হয় এবং পেইজটি সর্বদা একই থাকে, যদিও একটি পোস্টের মতো, আপনি যখনই চান এটি আপডেট করতে পারেন। 

> ওয়ার্ডপ্রেসের এক্সপ্লোর এবং ব্যবহার শুরু করার জন্য আপনাকে জানাই শুভকামনা।

**Comment by devmuhib009** [comment]
I will update and inform you. Thanks for reviewing.

**Comment by devmuhib009** [comment]
Hello @huzaifaalmesbah 

I just [updated the document](https://docs.google.com/document/d/10DASjm72OHNzo_LY5FfdrL4LOEBCf0FkCPRa3PKM-HI/edit?usp=sharing). Here is the link. Please check and provide your feedback. Thanks

**Comment by huzaifaalmesbah** [comment]
Looks good now. I think it can be published now.

**Comment by devmuhib009** [comment]
Thanks for your review. @huzaifaalmesbah.

@webtechpooja can you please help me to publish the translation?

**Comment by kafleg** [comment]
@webtechpooja Added in the draft, https://learn.wordpress.org/?p=43055&post_type=lesson-plan&preview_id=43055&preview=true

**Comment by webtechpooja** [comment]
@kafleg, you have created a lesson plan, and the Tutorial Transcript falls under the Tutorial menu. If you have the bandwidth, Can you please create a draft for the tutorial and remove it from the lesson plan? Thanks

**Comment by kafleg** [comment]
> @kafleg, you have created a lesson plan, and the Tutorial Transcript falls under the Tutorial menu. If you have the bandwidth, Can you please create a draft for the tutorial and remove it from the lesson plan? Thanks

Sorry, I don't have access in it. Can you please add me there?

**Comment by webtechpooja** [comment]
@kafleg I have upgraded your role to author. Kindly check and let me know if you face any difficulty in creating a tutorial.

**Comment by kafleg** [comment]
> @kafleg I have upgraded your role to author. Kindly check and let me know if you face any difficulty in creating a tutorial.

Please check now, https://learn.wordpress.org/wp-admin/post.php?post=43062&action=edit

**Comment by webtechpooja** [comment]
Published - https://learn.wordpress.org/tutorial/bn-getting-to-know-the-wordpress-dashboard/
Thanks, @devmuhib009 and @kafleg, for all your contribution. Thanks

**Comment by kafleg** [comment]
> Published - https://learn.wordpress.org/tutorial/bn-getting-to-know-the-wordpress-dashboard/ Thanks, @devmuhib009 and @kafleg, for all your contribution. Thanks

Thank you @webtechpooja
