### ISSUE TITLE
Meeting Agenda September 26, 2023

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1883]
Training Team meetings start at 07:00 UTC weekly on Tuesdays. Anyone is welcome to contribute to the meeting by commenting on Slack threads throughout the week. Meeting notes will be published at the end of the week to incorporate these asynchronous conversations.

This week’s meeting will be hosted by @webtechpooja.

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- September 26 – [@benjirahmed](https://profiles.wordpress.org/benjirahmed/)
- October 3 – [@Sancastiza](https://profiles.wordpress.org/sancastiza/)
- October 10 – [@sumitsingh](https://profiles.wordpress.org/sumitsingh/)
- October 17 – Needs Volunteer

**2. Looking for feedback**

- [Proposal: Updating the Contributor Ladder to a five-path model](https://make.wordpress.org/training/2023/09/21/proposal-updating-the-contributor-ladder-to-a-five-path-model/)
- What data should we collect to highlight the Training Team’s impact on the WordPress Community and on Learn?
- The team started a conversation last to last week about how we could indicate folks have completed a [course cohort](https://make.wordpress.org/training/2023/08/02/announcing-the-first-learn-wordpress-course-cohort/). Please leave your ideas in [this Slack thread from last week's meeting](https://wordpress.slack.com/archives/C02RW657Q/p1694504434505029).
- The team also started discussing: "When can an interested contributor take over developing a piece of content which had originally been assigned to another contributor, but no progress has been made for some time?" Please leave your feedback in [this Slack thread from last week's meeting](https://wordpress.slack.com/archives/C02RW657Q/p1694504869204909).
- [Looking for Feedback: Learn Website Information Architecture](https://make.wordpress.org/training/2023/09/26/looking-for-feedback-learn-website-information-architecture/) - We’d love to receive more feedback from Training Team members on proposed changes to the site IA, and ask folks to review and share feedback on this post on what has been drafted.

**3. Looking for volunteers**

- We're looking for volunteers to author the October edition of the Learn WordPress newsletter. (See the [Learn WordPress Newsletter – September 2023](https://learn.wordpress.org/learn-wordpress-newsletter-september-2023/) to see how its structured)
- Abha is looking for volunteers to help present about Learn WordPress for a Portsmouth Meetup in November.

**4. Updates from last week's dev-squad triage session**

Triaged one new open PR and two new open bugs

- #1871
- #1874
- #1875 

**5. Other news**

- Contributor Badges Awarded: [Harsh Gajipara](https://profiles.wordpress.org/harshgajipara/), [Akshaya Rane](https://profiles.wordpress.org/akshayar/)
- WordPress 6.4 Beta 1 releasing on Sept 26
- Come check out [Let’s share our notes from the Community Summit](https://make.wordpress.org/training/2023/09/05/lets-share-our-notes-from-the-community-summit/)
- Educational content from Learn WordPress has been added to [this Hosting Handbook page](https://make.wordpress.org/hosting/handbook/learn-hosting/).
- [Hallway Hangout: What's new for developers in WordPress 6.4](https://make.wordpress.org/core/2023/09/14/hallway-hangout-whats-new-for-developers-in-wordpress-6-4/#comment-45656)

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - https://github.com/WordPress/Learn/issues/758
  - https://github.com/WordPress/Learn/issues/455
  - https://github.com/WordPress/Learn/issues/1830
- **Lesson Plans**
  - https://github.com/WordPress/Learn/issues/806
- **[Translated Content](https://github.com/WordPress/Learn/labels/Needs%20Translation%20Reviewer)**
  - https://github.com/WordPress/Learn/issues/1873 (German)
  - https://github.com/WordPress/Learn/issues/1882 (Bangla)
  - https://github.com/WordPress/Learn/issues/1881 (Gujrati)
  - https://github.com/WordPress/Learn/issues/1865 (Finnish)
  - https://github.com/WordPress/Learn/issues/1858 (Chinese)

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
- [Next steps for GitHub updates](https://make.wordpress.org/training/2023/07/08/next-steps-for-github-updates/)

## 5 Faculty Updates
Time for a Faculty check-in! @faculty please answer any that apply:
• What have you been working on and how has it been going?
• Anything you’ve accomplished since the last meeting?
• Do you have any blockers?
• Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by webtechpooja** [comment]
@jonathanbossenger Could you share an update from last week's dev-squad triage session, please? 🙇‍♂️

**Comment by kaitohm** [comment]
> What data should we collect to highlight the Training Team’s impact on the WordPress Community and on Learn?

This recent post by Courtney Robertson ties in nicely with this topic. Please highlight this post: https://make.wordpress.org/project/2023/09/25/request-for-feedback-make-team-dashboards/

**Comment by Piyopiyo-Kitsune** [comment]
Added this above: [Looking for Feedback: Learn Website Information Architecture](https://make.wordpress.org/training/2023/09/26/looking-for-feedback-learn-website-information-architecture/)

**Comment by jonathanbossenger** [comment]
dev squad triage update added.

**Comment by webtechpooja** [comment]
Recap notes are published - https://make.wordpress.org/training/2023/10/12/training-team-meeting-recap-26th-september-2023/
