### ISSUE TITLE
Online Workshop – How to Start Contributing to Translating a WP Project into Your Local Language

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/Learn#1884]
# Event Details
- Title: 
- Description: 
In this event, we will walk you through the process of translating a WordPress project from the official WordPress directory and requesting an approval review. You will also gain a basic understanding of the documentation required to produce consistent translations and the process of publishing translations.

- Understand where to find English and other translation documentation.
- Understand the types of projects that can be translated on [translate.wordpress.org .](https://translate.wordpress.org/)
- Understand the difference between subprojects.
- Understand the next steps after proposing a translation.
- How do I access the WordPress your local language style guide and glossary?
- what can I translate with translate.wordpress.org?
- How do I suggest translations?
- Questions & Answer

- Target Audience: anyone can join this event.
- Date: Saturday, October 14, 2023 at 9:00 PM to Saturday, October 14, 2023 at 10:30 PM IST
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/296329144/

# Online Workshop Checklist:
- [x] Create an Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to the event (Remove the "Needs Co-host" tag from the issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by sumitsinghiih** [comment]
Here is the presentation link. I will share the video link soon - https://www.canva.com/design/DAFxNqwCKzo/_XSLsh-WleyDuqqmpezDxA/view

**Comment by sumitsinghwp** [comment]
Here is the presentation link. I will share the video link soon - https://www.canva.com/design/DAFxNqwCKzo/_XSLsh-WleyDuqqmpezDxA/view

**Comment by kaitohm** [comment]
Hi @sumitsinghwp ! Can this issue be closed now?
