### ISSUE TITLE
Online Workshop - Common APIS - Settings API

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1885]
# Event Details
- Title:  Common APIS - Settings API
- Description: Added to WordPress in version [2.7](https://developer.wordpress.org/support/wordpress-version/version-2-7), The Settings API allows developers to develop admin pages containing settings forms to be managed semi-automatically. It lets you define settings pages, sections within those pages, and fields within the sections. In this session, you'll learn how to use the Settings API with the Options API to greate settings pages for your plugins or themes.
- Target Audience: Developers
- Date: 2023-09-28 @ 14:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/296333350/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I'm available to co-host.

**Comment by jonathanbossenger** [comment]
Thanks @SierraTR

**Comment by jonathanbossenger** [comment]
Slides: https://www.slideshare.net/psykro/common-wordpress-apis-settings-api

**Comment by SierraTR** [comment]
Great session again - very clear and well paced.  You had 19 attendees this time.

**Comment by jonathanbossenger** [comment]
Thank you @SierraTR

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/09/29/common-wordpress-apis-settings-api/
