### ISSUE TITLE
Typo on Translating Subtitles Handbook page

### ISSUE THREAD

**Issue by gudrunfrank** [WordPress/Learn#1887]
## Overview
- Content title: Translating Subtitles; Section: Updating existing subtitle translations
- Content URL: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-subtitles/#updating-existing-subtitle-translations
- Are you reporting an error (such as outdated information), or providing improvement ideas?: 
Grammatical correction
## Feedback Details
Original: If you find any mistakes in an existing subtitle file, you can fix them by updating the file and replacing it with the old one.
Suggestion: If you find any mistakes in an existing subtitle file, you can fix them by updating the file and replacing the old one.

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by devmuhib009** [comment]
Thank you for the suggestion. Just updated the handbook.
