### ISSUE TITLE
Khmer Language causes overlay on Lesson Plan listings, hiding selection boxes (Firefox only)

### ISSUE THREAD

**Issue by gudrunfrank** [WordPress/Learn#1888]
## Description

When the list contains an item in Khmer, the layout extends over the selection boxes

## Expected behaviour

I expect that all languages fit in the allocated space.

## Actual behaviour

The Khmer language listings extend the provided space and therefore overlaps the selection boxes. 
The problem seems to exist only on Firefox, but not on Chrome or Edge.
## Screenshots or screen recording (optional)

![image](https://github.com/WordPress/Learn/assets/828253/82fe8f61-1c20-4a10-9679-93edee99be16)

## Environment information
- Browser(s) are you seeing the problem on. Firefox 118.0

- Device you are using and operating system (e.g. "Desktop with Windows 10", "iPhone with iOS 14", etc.).
- Desktop, Windows 11

**Comment by shail-mehta** [comment]
**Created PR:**  https://github.com/WordPress/Learn/pull/1936

**Comment by ironnysh** [comment]
The redesign resolved this issue (tested [this page](https://learn.wordpress.org/lesson-plans/?language%5B%5D=km&post_type=lesson-plan) in Safari and Firefox to confirm).

We can close the related PR (#1936)

CC @jonathanbossenger
