### ISSUE TITLE
Tutorial - Twenty Twenty Four Theme

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#1890]
# Topic Description
Write a description of the topic here.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]https://make.wordpress.org/core/2023/08/24/introducing-twenty-twenty-four/

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/191dc63b-0217-4370-85d4-8d7f4f071e5b

**Comment by TinaCollier** [comment]
Hi @westnz 👋 Great tutorial as always! Here are some of my thoughts on the video:

1. The graphics and video clips went perfectly with your voice over. The sections flowed smoothly and it was easily to follow along.
2. You gave great examples of Patterns, Templates, and Styling. I like that you reviewed several examples of each and their use cases.
3. I would like to see the objectives listed at the beginning for reference. For example:
- What makes this theme so special
- How to create a page
- Patterns
- Templates
- Setting the style
- Who can benefit from this theme
4. You mentioned use cases (I.e. photographers, bloggers, and businesses), but maybe make this a bit clearer either through a visual or through a concise statement such as "The Twenty Twenty-Four theme is versatile and designed for various website types, with a focus on three use cases: entrepreneurs/small businesses, photographers/artists, and writers/bloggers." as mentioned in **The Concept** section of the [Make.WordPress.org Core article] (https://make.wordpress.org/core/2023/08/24/introducing-twenty-twenty-four/)
Awesome work on this tutorial and I look forward to reviewing the next one.

Best regards,
Tina

**Comment by westnz** [comment]
Thank you for the helpful feedback @TinaCollier

**Comment by SierraTR** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [ ] Learning outcomes/objectives are clear.
- [X] Technical concepts introduced in the content are accurate.
- [X ] The speed of demonstrations are easy to follow.
- [X ] The narration audio matches what is shown visually.
- [X ] Spelling and grammar are correct.
- [X ] Sound quality is consistent throughout the video.
- [X ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- X ] Media assets are all in the public domain 

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

Great job Wes!
I do agree with Tina's points 3 & 4 - #3 to state up front the objectives of the tutorial (what you will learn in this tutorial). For her point #4 perhaps mention the proposed use cases for the new theme at the beginning where you introduce the new default theme.

**Comment by westnz** [comment]
Thank you very much @SierraTR 👍

**Comment by cynthianorman** [comment]
Hi @westnz 

- You may want to add in your first statement something like this 
The new Twenty Twenty-Four theme is designed to take advantage of the new design tools introduced in WordPress 6.4.

**Comment by westnz** [comment]
Good point, thanks @cynthianorman

**Comment by priyanshi-vijay** [comment]
Hi @westnz,
I have reviewed the video, and from my perspective, the video is highly informative and presented in an easy-to-understand manner.

**Comment by westnz** [comment]
Thank you very much @priyanshi-vijay!

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/introducing-the-twenty-twenty-four-theme/
