### ISSUE TITLE
Tutorial - Re-creating Techcrunch in 30 mins

### ISSUE THREAD

**Issue by jamiemarsland** [WordPress/Learn#1891]
# Topic Description
In today's video I try to recreate the https://techcrunch.com/ website in just 30 minutes using WordPress and no plugins.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by jonathanbossenger** [comment]
Great idea @jamiemarsland 

I've triaged this and requested an SME to review, which should happen sometime next week.

**Comment by jonathanbossenger** [comment]
Linking the original Youtube video for context: https://www.youtube.com/watch?v=RghKQZmYwYI

@jamiemarsland this all looks good from my point of view. As with your previous [rapid website recreation](https://github.com/WordPress/Learn/issues/1515), please add the link of the video you want to submit to Learn WordPress here, following the same branding guidelines as before.

Once that's done, you can add the Ready to Review label to this issue and share the link to this issue in the training team channel in Slack, so that we get the training team to review the video.

Thanks

**Comment by jamiemarsland** [comment]
Hi, this has now been edited, so it's ready for review https://vimeo.com/882521303?share=copy

**Comment by digitalchild** [comment]
Hi @jamiemarsland 

This is a great way to show the power of WordPress in just 13 minutes. The topic shows a real world example of how great WordPress is as well as the power of the block editor. 

Feedback
- You mention that it's a recreation in 30 mins, however the video is less than half, which is great. 
- For the speed, I would say some parts for getting element properties were a bit fast. I turned away from the screen for just a second and had to rewind to make sure I could review it. 
- I assume the video will be uploaded with the branded screenshot like your previous video? 

## Tutorial Review Checklist
Please tick all items you've confirmed:
- [X] Learning outcomes/objectives are clear.
- [X] Technical concepts introduced in the content are accurate.
- [ ] The speed of demonstrations is easy to follow.
- [X] The narration audio matches what is shown visually.
- [X] Spelling and grammar are correct.
- [X] Sound quality is consistent throughout the video.
- [] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by westnz** [comment]
Review:

Fantastic video and demonstration! Many folks will benefit from learning how to create a sticky sidebar. The zooming effect you use throughout the video is also very helpful. 

It would be great to host this tutorial on Learn as well! 💥

**Comment by westnz** [comment]
Hey @jamiemarsland. You can go ahead and publish after looking through the feedback. 💪

**Comment by jamiemarsland** [comment]
Hi Wes, 

I've uploaded to WordPress TV (I think) - what happens now?

**Comment by westnz** [comment]
That's great. I see the video has been approved: https://wordpress.tv/2023/11/21/recreating-techcrunch-com-in-30-minutes/.

Now you can complete steps 2 and 3 from this link: https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/ 

The goal is, of course, to look like this again: https://learn.wordpress.org/tutorial/rapid-website-recreation/
