### ISSUE TITLE
Online Workshop - Building a home page 

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1896]
# Event Details
- Title: Building a home page
- Description: Setting static home page, create a header and footer with partners and build a page with a variety of blocks
- Target Audience: Users
- Date: 2 October at 1pm Pacific Time
- Meetup.com event link:  https://www.meetup.com/learn-wordpress-online-workshops/events/296263535/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by westnz** [comment]
Co-host: @SierraTR

**Comment by SierraTR** [comment]
Well done, as usual. You covered it all!  There were 37 attendees.

**Comment by westnz** [comment]
Thank you Tracy!  You are an awesome co-host!

**Comment by westnz** [comment]
Recording: https://wordpress.tv/2023/10/03/building-a-home-page/
