### ISSUE TITLE
Meeting Agenda October 3, 2023

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1897]
Training Team meetings start at 07:00 UTC weekly on Tuesdays. Anyone is welcome to contribute to the meeting by commenting in Slack threads throughout the week. Meeting notes will be published at the end of the week to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune_

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- October 3 – [@Sancastiza](https://profiles.wordpress.org/sancastiza/)
- October 10 – [@sumitsingh](https://profiles.wordpress.org/sumitsingh/)
- October 17 –  [@huzaifaalmesbah](https://profiles.wordpress.org/huzaifaalmesbah)
- October 27 - Needs volunteer

**2. Looking for feedback**

- [Proposal: Updating the Contributor Ladder to a five-path model](https://make.wordpress.org/training/2023/09/21/proposal-updating-the-contributor-ladder-to-a-five-path-model/) - this is the second week we are asking for feedback-- please share your thoughts so that we can compile them and share next steps next week.
- [Looking for feedback: Updates to GitHub issue templates and labels](https://make.wordpress.org/training/2023/09/27/looking-for-feedback-updates-to-github-issue-templates-and-labels/)
- [Looking for Feedback: Learn Website Information Architecture](https://make.wordpress.org/training/2023/09/26/looking-for-feedback-learn-website-information-architecture/) - Please share feedback on the post

**3. Looking for volunteers**

- N/A

**4. Updates from last week's dev-squad triage session**

There was no dev-squad triage this week, due to scheduling conflicts.

**5. Other news**

- [Discussion: Defining Active and Engaged Faculty](https://make.wordpress.org/training/2023/09/28/discussion-defining-active-and-engaged-faculty/)
  - How can we better define "activity" and "engagement" for Faculty members in the Faculty program?
  - [September Monthly Update published](https://make.wordpress.org/updates/2023/10/02/whats-new-on-learn-wordpress-in-september-2023/)
  - [October Learn Newsletter](https://learn.wordpress.org/learn-wordpress-newsletter-october-2023/)

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - #758 
- **Lesson Plans**
  - #806 
- **Translated Content**
  - #1488 
  - #1508 
  - #1535 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - Learning Pathways will be published on October 3rd / @westnz 

## 5. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by courtneyr-dev** [comment]
Can we have an update on https://github.com/WordPress/Learn/issues/1832? The month has begun.

**Comment by courtneyr-dev** [comment]
Content for WordPress 6.4 that needs to be revised or created can be found at https://github.com/WordPress/Learn/issues?q=is%3Aissue+is%3Aopen+label%3A6.4. 

@courtney-pk and I are discussing a contributor day event, similar to Docs team, that can assist more team members get involved in revising/creating content for the release.  The release date is November 7. Let's aim to get all content we can revised/created and published on release day.

**Comment by courtney-pk** [comment]
Can we please add something about the first month of the Guide Program? Something like:

> Guide Program Update: [At the beginning of September](https://make.wordpress.org/training/2023/08/03/introducing-the-training-team-guide-program/), 11 new Training Team contributors were each matched to one of 5 Guides that graciously volunteered their time and expertise to help them along their contribution journey. Since the program is estimated to take 3 weeks, the first participants should have completed the program by now.
> 
> We hope these participants have learned all about the Training Team and have been empowered to make their first contributions!
> 
> - **If you were a new contributor** in the Guide Program, we'd love to hear what you have completed for your first contribution, so we can celebrate with you!
> - **If you were a Guide**, feel free to celebrate the folks you were guiding this past month!

**Comment by webtechpooja** [comment]
Recap notes are published - https://make.wordpress.org/training/2023/10/11/training-team-meeting-recap-3rd-october-2023/
