### ISSUE TITLE
Bengali translation for Tutorial "Creating your own custom synced or non-synced patterns"

### ISSUE THREAD

**Issue by huzaifaalmesbah** [WordPress/Learn#1903]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/creating-your-own-custom-synced-or-non-synced-patterns/
- Link to original content GitHub issue (optional): https://github.com/WordPress/Learn/issues/1776
- Language you'll be translating to: Bangla/Bengali
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: Translation work in progress

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by huzaifaalmesbah** [comment]
I completed the translation. Here is the [Doc File](https://docs.google.com/document/d/1CIPxTMEukLZpwTcq-PXjsAd7fgCqO9hwEREgW9VDgjw). I need translation reviewer.

**Comment by kamrulhasanj** [comment]
I want to review translation.

**Comment by huzaifaalmesbah** [comment]
Certainly. You can start review and submit report.

**Comment by huzaifaalmesbah** [comment]
@kamrulhasanj Thank you for your interest.

**Comment by kamrulhasanj** [comment]
You may change this mentioned word  

সনাক্ত করুন  
> সনাক্ত করা

তৈরি করুন
> তৈরি করা

**Comment by huzaifaalmesbah** [comment]
i already update please check. [Update Doc File](https://docs.google.com/document/d/1CIPxTMEukLZpwTcq-PXjsAd7fgCqO9hwEREgW9VDgjw)

**Comment by kamrulhasanj** [comment]
I have reviewed your translation doc, and all is good.

**Comment by huzaifaalmesbah** [comment]
@kamrulhasanj  Thanks For Review.

**Comment by huzaifaalmesbah** [comment]
@kafleg & @webtechpooja can you please help me to publish the translation?

**Comment by kafleg** [comment]
> @kafleg & @webtechpooja can you please help me to publish the translation?

I can help you.

**Comment by kafleg** [comment]
Added in the Dashboard, https://learn.wordpress.org/?p=43158&post_type=wporg_workshop&preview=1&_ppp=e3167574f6 

@webtechpooja Please check it once.

**Comment by webtechpooja** [comment]
Published https://learn.wordpress.org/tutorial/bn-creating-your-own-custom-synced-or-non-synced-patterns/
