### ISSUE TITLE
Meeting Agenda October 10,  2023

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1905]
Training Team meetings start at 07:00 UTC weekly on Tuesdays. Anyone is welcome to contribute to the meeting by commenting in Slack threads throughout the week. Meeting notes will be published at the end of the week to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune_

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- October 10 – [@sumitsingh](https://profiles.wordpress.org/sumitsingh/)
- October 17 –  [@huzaifaalmesbah](https://profiles.wordpress.org/huzaifaalmesbah)
- October 24 –  [@nayanchamp7](https://profiles.wordpress.org/nayanchamp7)
- October 31 –  Needs volunteer (this could be you!)

**2. Looking for feedback**

- [Proposal: Updating the Contributor Ladder to a five-path model](https://make.wordpress.org/training/2023/09/21/proposal-updating-the-contributor-ladder-to-a-five-path-model/) - this is the second week we are asking for feedback-- please share your thoughts so that we can compile them and share next steps next week.
- [Looking for feedback: Updates to GitHub issue templates and labels](https://make.wordpress.org/training/2023/09/27/looking-for-feedback-updates-to-github-issue-templates-and-labels/)
   - See [see sheet](https://docs.google.com/spreadsheets/d/1XGJKG26N1T59dPM-G_oT6eI67mlgaaGV4YQm_XbGDqg/edit#gid=0) and comment to help in this effort
- [We have priority issues that need updating open in GitHub that are labeled 6.4](https://github.com/WordPress/Learn/issues?q=is%3Aissue+is%3Aopen+label%3A6.4)
   - Looking for a Contributor Hour host
   - Help validate the issue and comment on the issue what specifically needs to change
- Content Audit for Learning Pathways -- we need volunteers to help us identify the content we can utilize or enhance and incorporate it into our lessons. [Learn more about how to get involved in this post](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4009).
- Share your thoughts on these updates to the [Team Roles handbook page, specifically the Team Representatives section](https://make.wordpress.org/training/handbook/training-team-how-to-guides/team-roles/#training-team-rep). By [reviewing and commenting on this document](https://docs.google.com/document/d/1vKWoH4DnIiZbYuyQbFfgJHPbGqrfmFqOQ6VcTCC1XY0/edit?usp=sharing).

**3. Looking for volunteers**

- [Help us audit Learn WordPress for content](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4009) we can add to our Learning Pathways

**4. Updates from last week's dev-squad triage session**

This week the dev-squad triaged 2 new PRs and one new bug:
 - #1880
 - #1900 
 - #1888

There was some discussion around #1880, which we would like to bring to the team. 

Generally, when implementing internal [anchor link fragments](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Identifying_resources_on_the_Web#fragment) (where an HTML anchor tag links to the id attribute of another element on the same page instead of an external URL) the fragment uses lowercase, not sentence case. While this does not seem to be a requirement according to the HTML spec, it's not something commonly used, as most developers will use lowercase when defining id attributes of HTML elements. 

However, the Tip box in the lesson plan saved pattern defines the links as sentence-case, but there are also some instances where it might be all lowercase. So while we're not sure that the case ultimately matters, we do think it should be formalized, documented, and then used accordingly across the site. 

So this leaves us with a question, and a follow-up problem: 

1. Should we stick to sentence case, or switch to all lowercase.
2. Whatever we decide, once implemented, we'll need to review both the lesson plan saved pattern, and any existing lesson plans, to ensure the links work as expected. 

Therefore we'd like to bring this to the training team to discuss, decide on, and implement a plan to get the relevant parts updated. 

**5. Other news**

- [Discussion: Defining Active and Engaged Faculty](https://make.wordpress.org/training/2023/09/28/discussion-defining-active-and-engaged-faculty/)
  - How can we better define "activity" and "engagement" for Faculty members in the Faculty program?
- Hacktoberfest -- [a new post detailing how to get involved is now up on our website](https://make.wordpress.org/training/2023/10/06/take-part-in-hacktoberfest-2023-by-contributing-to-the-training-team/)
- Badges Rewarded - [Muhibul Haque](https://profiles.wordpress.org/devmuhib/) 🎉
- Training Team Nominations are coming!

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - #758 
  - #513 
  - #1898 
- **Translated Content**
  - #1488 
  - #1508 
  - #1535 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - Learning Pathway outlines have been published

## 5. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
Thank you @Piyopiyo-Kitsune. Notes from the dev-squad triage session have been added, with a new discussion item. You are welcome to move the discussion item to the open discussions part of the meeting, or wherever you prefer.

**Comment by jonathanbossenger** [comment]
Discussion item: I have created the PR for the Sensei Pro upgrade. I would like to ask any members of the faculty dev-squad, or any other contributors with developer experience, to help review and test the PR. 

https://github.com/WordPress/Learn/pull/1909

**Comment by webtechpooja** [comment]
Recap notes - https://make.wordpress.org/training/2023/10/13/training-team-meeting-recap-10th-october-2023/
