### ISSUE TITLE
Online Workshop - Using the query loop block and category templates

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1906]
# Event Details
- Title: Using the query loop block and category templates
- Description: 
- Target Audience: Users
- Date: 17 Oct at 20:00 UTC
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/296575670/?isFirstPublish=true
- Co-host: Felipe Santos
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
Wes, I'm available to co-host if you want.

**Comment by westnz** [comment]
Hey @SierraTR, I got a message from another co-host in a different time zone on Friday when I was already in weekend mode. Next time!  😉
