### ISSUE TITLE
Online Workshop - The WordPress Create Block tool

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1913]
# Event Details
- Title: 
- Description: The WordPress Create Block command line tool allows you to quickly scaffold a new block plugin. In this workshop, you will learn what you need to get started with Create Block, how to use it, and dive into the code it generates.
- Target Audience: Developers
- Date: 2023-10-12
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/296580191/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by SierraTR** [comment]
I'm available if you want a co-host.

**Comment by jonathanbossenger** [comment]
Thanks @SierraTR, that would be great!

**Comment by jonathanbossenger** [comment]
Slides: https://www.slideshare.net/psykro/the-wordpress-create-block-tool

**Comment by SierraTR** [comment]
Another action-packed workshop - very good!  You had 34 attendees which, to me, is a great number for the level of the workshop.  You're getting quite a following!

**Comment by jonathanbossenger** [comment]
Recording: https://wordpress.tv/2023/10/13/the-wordpress-create-block-tool/
