### ISSUE TITLE
Content Feedback - Typo in the lesson plan title

### ISSUE THREAD

**Issue by nabincodes** [WordPress/Learn#1915]
## Overview
- Content title: What Is W3 Total Cache
- Content URL: https://learn.wordpress.org/lesson-plan/what-is-w3-total-cache/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: No.

## Feedback Details
"Is" is capitalized. It should be in a normal case i.e What is W3 Total Cache.

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by webtechpooja** [comment]
Thank you for giving feedback on this. I have fixed it. @nabincodes
