### ISSUE TITLE
Understanding the WordPress dashboard and its key components.

### ISSUE THREAD

**Issue by RituPriya11** [WordPress/Learn#1916]
# Details

**- Topic description:** Here's a very small description of the topic 

The WordPress dashboard is like the main control center of your website. It's where you go as soon as you log in. It helps you do things and control what happens on your website. It's easy to use for everyone, whether you're just starting or have experience using websites.

Important Parts:

Admin Toolbar:
This is at the very top. It's like a quick menu for important jobs, such as making new posts, adding pages, or changing how your site looks.

Sidebar Menu:
On the left side, there's a menu with lots of options. It's like a menu in a restaurant, but for your website. You can choose what you want to do, like write a new post, change how things look, and more.

At a glance:
Here, you get a simple summary of what's happening on your site. It's like a quick look at the important stuff, such as how many posts or pages you have.

Quick Draft and Activity:
If you have an idea for something to write, you can quickly jot it down here. You can also see what's been happening recently on your site.

WordPress News:
This part tells you the latest news about WordPress. It's like staying updated on what's new and cool with WordPress.

Understanding these parts of the WordPress dashboard helps you use and make your website just the way you want it.

- Audience (User, Developer, Contributor, etc.): 

Individuals new to website management, especially those with limited technical experience, small business owners, casual bloggers, students learning web design, and seniors or individuals with less tech familiarity, making it accessible and easy to understand.

- Learning objectives (What will the learner be able to do as a result of this content?): 
Know the Dashboard:
Understand that the WordPress dashboard is like a control center for your website where you can do important things.

Recognize Parts:
Recognize and remember the main parts of the dashboard, like the toolbar at the top and the menu on the left.

Understand Each Part:
Learn what each part does, such as how to make new posts or see what's happening on your site.

Importance of Dashboard:
Understand that knowing the dashboard helps you manage your website the way you want, even if you're new to it.

Practice Simple Tasks:
Practice basic tasks like making a new post or checking your site's activity to get comfortable using the dashboard.

These objectives aim to provide a basic understanding and encourage practical learning to navigate and utilize the WordPress dashboard effectively.

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): 
Course

- WordPress version (optional): Latest version - 6.4
- Will you be creating this content? (Yes or No): Yes

# Related Resources
https://wordpress.org/documentation/article/dashboard-screen/
https://www.tutorialspoint.com/wordpress/wordpress_dashboard.htm

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by westnz** [comment]
Hi @RituPriya11 
Just wanted to note we have the following video published on Learn: Getting to know the WordPress Dashboard: https://www.youtube.com/watch?v=VCgWDVu-tOw

**Comment by jonathanbossenger** [comment]
Closing in favor of the lesson that already exists in the [Beginner User Learning Pathway](https://github.com/WordPress/Learn/issues/694).
