### ISSUE TITLE
Content Feedback -

### ISSUE THREAD

**Issue by RituPriya11** [WordPress/Learn#1917]
## Overview
- Content title: High-Level Overview
- Content URL: https://learn.wordpress.org/lesson-plan/high-level-overview/
- Are you reporting an error (such as outdated information), or providing improvement ideas?: 
Improvement ideas
## Feedback Details
The content is really great, I just had some more pointers that can make the course more understandable to new users:

A detailed section on how to make a fully functional website. I like how diff aspects like themes, plugins are explained, but a detailed section on how these come together to make a fully functional website will be beneficial.

## Next steps for Training Team member
Please follow the team handbook "[Validating Content Feedback issues](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/#validating-content-feedback-issues)" to validate this feedback.

**Comment by jonathanbossenger** [comment]
Closing in favour of the work currently being done for learning pathways
