### ISSUE TITLE
Workshop & Lesson Plans: Add links to meta info in the sidebar

### ISSUE THREAD

**Issue by naokomc** [WordPress/Learn#192]
It'd be useful for users if the meta info on the sidebar of workshops (topic, level, language, and captions) is linked.
![image](https://user-images.githubusercontent.com/34067/108649392-924e8000-7500-11eb-9e5b-b042d1b48ae8.png)

We already have filters for them (except for levels), so how about linking to the filtered result page?
![image](https://user-images.githubusercontent.com/34067/108648861-8910e380-74ff-11eb-9142-fa00948b453e.png)
e.g. Send users to https://learn.wordpress.org/workshops/?series=&topic=7&language=&captions= when "Block Editor" topic is clicked.

**Comment by courtneyr-dev** [comment]
As we plan out a series of lesson plans (previously named Workshops), it would be great to do likewise in lesson plans as well. 

![image](https://user-images.githubusercontent.com/5519705/109295215-536c4300-77fc-11eb-8182-f966f1ac21ef.png)
