### ISSUE TITLE
Securely developing plugins and themes

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1925]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Securely developing plugins and themesI
- Topic description: A short introduction to developing with a security mindset, covering the most common principles to consider when writing code.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Explain what it means to develop with security in mind
- Describe steps to follow to ensure code is secure
- Define where to find more information about developing securely

# Related Resources and Other Notes
- https://learn.wordpress.org/tutorial/introduction-to-securely-developing-plugins/
- https://developer.wordpress.org/apis/security/

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/assets/180629/16550713-eeab-459f-a731-8082b92f8cc0

Video ready for review

Please follow the [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review this lesson.

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).


Great intro to this critical topic, @jonathanbossenger. Very thorough and informative.

Two minor audio issues:
* At 1:32, there’s a weird jump, like there’s a fraction of a second pause missing
* At 2:06, there’s a word missing at the end of the sentence.

**Comment by jonathanbossenger** [comment]
Thanks Ronny

I was able to fix the error at 1:32, but the missing word at 2:06 is actually just my voice trailing off, so I can't fix that one 😁 

I will upload the new video shortly

**Comment by jonathanbossenger** [comment]
Updated video.


https://github.com/WordPress/Learn/assets/180629/cdd59bbc-b987-4158-90d7-7fb721e4bff5

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/05/11/securely-developing-plugins-and-themes/

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/securely-developing-plugins-and-themes/

**Comment by jonathanbossenger** [comment]
//publish
