### ISSUE TITLE
Bengali translation for Tutorial "How to Submit a Workshop"

### ISSUE THREAD

**Issue by huzaifaalmesbah** [WordPress/Learn#1933]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/how-to-submit-a-workshop/
- Link to original content GitHub issue (optional): 
- Language you'll be translating to: Bangla/Bengali
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by huzaifaalmesbah** [comment]
Ready For Review [Doc File](https://docs.google.com/document/d/1-hJ91KLQBGvvPiK2eckA-q1Rx2JCW7WrmR3kdAXxYSA/edit?usp=sharing)

**Comment by devmuhib009** [comment]
I will review the content and let you know the improvements.

**Comment by devmuhib009** [comment]
> অংশগ্রহণকারীরা কীভাবে একটি কর্মশালার বিষয় প্রস্তাবিত হয়, দল কীভাবে জমা দেওয়া বিষয়গুলি পর্যালোচনা করে এবং ধারণা থেকে প্রকাশিত পরিকল্পনার যাত্রার সাথে পরিচিত হবে।

অংশগ্রহণকারীরা পরিচিত হবে কীভাবে একটি কর্মশালার বিষয় প্রস্তাবিত হয়, জমা দেওয়া বিষয়গুলি দল কীভাবে পর্যালোচনা করে এবং ধারণা থেকে প্রকাশ পরিকল্পনার যাত্রার সাথে।

> তাই আমি দেখছি যে পরবর্তী আলোচনা গ্রুপে আমি যোগ দিতে আগ্রহী 15 জুন ঘটছে।

তাই আমি দেখেছি যে পরবর্তী আলোচনা গ্রুপ যেটায় আমি যোগ দিতে আগ্রহী সেটি ১৫ জুন অনুষ্ঠিত হবে।

> আপনি যদি একটি কর্মশালা জমা দিতে আগ্রহী হন, তাহলে আপনি এখানে যেতে পারেন কীভাবে অবদান রাখতে হয় তা শিখুন।

আপনি যদি একটি কর্মশালা জমা দিতে আগ্রহী হন, তাহলে আপনি এখানে যেতে পারেন কীভাবে অবদান রাখতে হয় তা শিখতে।

> এবং এর মধ্যে, আপনি দেখতে পারেন যে আপনি আপনার কর্মশালা জমা দিতে পারেন।

এবং এর মধ্যে, আপনি দেখতে পাবেন যে আপনি আপনার কর্মশালা জমা দিতে পারেন।

> আপনি কোন ভাষায় এটি উপস্থিত হতে চান

আপনি কোন ভাষায় এটিতে উপস্থিত হতে চান

> এছাড়াও আপনি সম্পূর্ণ কর্মশালার অভিজ্ঞতা এবং প্রক্রিয়ায় অংশগ্রহণ চালিয়ে যেতে শিথিলভাবে প্রশিক্ষণ চ্যানেলে যোগ দিতে পারেন।

এছাড়াও আপনি সম্পূর্ণ কর্মশালার অভিজ্ঞতা এবং প্রক্রিয়ায় অংশগ্রহণ চালিয়ে যেতে স্ল্যাক প্রশিক্ষণ চ্যানেলে যোগ দিতে পারেন।

**Comment by huzaifaalmesbah** [comment]
Thank for Review and Suggesting.  Here Update [Doc File](https://docs.google.com/document/d/1-hJ91KLQBGvvPiK2eckA-q1Rx2JCW7WrmR3kdAXxYSA/edit?usp=sharing)

**Comment by devmuhib009** [comment]
I will check in morning and update you here.

**Comment by devmuhib009** [comment]
Thanks for updating. Ready for publish.

**Comment by huzaifaalmesbah** [comment]
@webtechpooja can you please help me to publish the translation?

**Comment by huzaifaalmesbah** [comment]
@webtechpooja can you help me to publish the translation?

**Comment by kaitohm** [comment]
Thank you for translating, and reviewing content 🙌 

@huzaifaalmesbah  Please share your WordPress.org username, and we will add you as an Author on https://learn.wordpress.org/. Once added, we'll guide you with next steps.

**Comment by huzaifaalmesbah** [comment]
Thanks For Response @bsanevans 
my wp.org username `huzaifaalmesbah`

**Comment by kaitohm** [comment]
I'm so sorry for the delay, @huzaifaalmesbah . I caught covid and was out for a while 😷

I've sent you an invite to become an author on https://learn.wordpress.org/. Please let me know once you've accepted, and I'll then be able to assign the following post to you:

https://learn.wordpress.org/wp-admin/post.php?post=44447&action=edit

Once assigned, please continue with step 5 here: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video

**Comment by huzaifaalmesbah** [comment]
No problem. I'm sorry to hear that you've been unwell @bsanevans.  I hope you recover swiftly from COVID. 
I accepted the invitation. now you can assign me.

**Comment by kaitohm** [comment]
Great! You should have access to the post now.

**Comment by huzaifaalmesbah** [comment]
i update post and save as a draft please check. Is everything ok?

**Comment by huzaifaalmesbah** [comment]
Hello, I've uploaded subtitle file. please check

**Comment by kaitohm** [comment]
Yay! I've approved the subtitles, and published the content: https://learn.wordpress.org/tutorial/bn-how-to-submit-a-workshop/

Thank you so much for your contribution ✨
