### ISSUE TITLE
Bengali translation for Tutorial "Adding a sticky header or banner"

### ISSUE THREAD

**Issue by huzaifaalmesbah** [WordPress/Learn#1934]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/adding-a-sticky-header-or-banner/
- Link to original content GitHub issue (optional): https://github.com/WordPress/Learn/issues/1435
- Language you'll be translating to: Bangla/Bengali
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by devmuhib009** [comment]
I want to review the content. Please send me the translation file when ready.

**Comment by huzaifaalmesbah** [comment]
Thanks for interesting. Ready For Review [Doc File](https://docs.google.com/document/d/1AmaJj-ksITk4oGB9rnEBlKk8g-UtpxrF8UC5AsZuuv4/edit?usp=sharing) Here

**Comment by huzaifaalmesbah** [comment]
Thanks for your interest @devmuhib009 

Now Ready For Review [Doc File](https://docs.google.com/document/d/1AmaJj-ksITk4oGB9rnEBlKk8g-UtpxrF8UC5AsZuuv4/edit?usp=sharing) Here

**Comment by devmuhib009** [comment]
> একটি গ্রুপ ব্লকে একটি শিরোনাম বা ব্যানার মোড়ানোর সময় একটি নতুন স্টিকি বিকল্প উপলব্ধ।

একটি নতুন স্টিকি অপশন উপলব্ধ আছে একটি গ্রুপ ব্লকে একটি শিরোনাম বা ব্যানার মোড়ানোর সময়।

> এখন কোড জানার দরকার নেই।

ভাল, এখন আপনি কোড না জেনেই এটি করতে পারেন। 

> এটি যদি আপনি চান যে পৃষ্ঠার স্ক্রল অবস্থানের প্রতিরূপে একটি শীর্ষক বা প্রচার ব্যানার স্ক্রীনে থাকে, তবে এটি দরকার। 

এটি উপকারী যদি আপনি চান হেডাআর অথবা প্রচার ব্যানারটি পেইজ স্ক্রল করার সাথে সাথে অপরিবর্তিত থাকবে। 

> আমরা দুটি উদাহরণ দেখতে যাচ্ছি

চলুন আমরা দুটি উদাহরণ দেখি। 

> একটি স্টিকি হেডার তৈরি করতে, আপনার দিকে যান Appearance এবং Editor এ ক্লিক করুন।

একটি স্টিকি হেডার তৈরি করতে Appearance এ যান এবং Editor এ ক্লিক করুন।

> তিনটি উঁচু বাঁশে

তিনটি উল্লম্ব বিন্দুতে

**Comment by huzaifaalmesbah** [comment]
Thank for Review and Suggesting @devmuhib009  Here Update [Doc File](https://docs.google.com/document/d/1AmaJj-ksITk4oGB9rnEBlKk8g-UtpxrF8UC5AsZuuv4/edit?usp=sharing)

**Comment by devmuhib009** [comment]
Just checked. Ready for publish.

**Comment by huzaifaalmesbah** [comment]
@webtechpooja can you help me to publish the translation?

**Comment by kaitohm** [comment]
Thank you for translating, and reviewing content 🙌

@huzaifaalmesbah Please share your WordPress.org username, and we will add you as an Author on https://learn.wordpress.org/. Once added, we'll guide you with next steps.

**Comment by huzaifaalmesbah** [comment]
Thanks For Response @bsanevans 
my wp.org username `huzaifaalmesbah`

**Comment by kaitohm** [comment]
I'm so sorry for the delay, @huzaifaalmesbah . I caught covid and was out for a while 😷 

I've sent you an invite to become an author on https://learn.wordpress.org/. Please let me know once you've accepted, and I'll then be able to assign the following post to you:

https://learn.wordpress.org/wp-admin/post.php?post=44445&action=edit

Once assigned, please continue with step 5 here: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video

**Comment by huzaifaalmesbah** [comment]
No problem. I'm sorry to hear that you've been unwell @bsanevans.  I hope you recover swiftly from COVID. 
I accepted the invitation. now you can assign me.

**Comment by kaitohm** [comment]
Great! You should have access to the post now.

**Comment by huzaifaalmesbah** [comment]
i update post and save as a draft please check. Is everything ok?

**Comment by kaitohm** [comment]
The post looks great 👍 

The final thing is to upload the translated subtitles to WordPress.tv. Could you follow step 6 here: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video

Once the subtitles are done, we can publish this. (Same for issue #1933 )

**Comment by huzaifaalmesbah** [comment]
Hello, I've uploaded subtitle file. please check

**Comment by kaitohm** [comment]
Yay! I've approved the subtitles, and published this content: https://learn.wordpress.org/tutorial/bn-adding-a-sticky-header-or-banner/

Thank you for your contributions ✨
