### ISSUE TITLE
Meeting Agenda October 17, 2023

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1937]
Training Team meetings start at 07:00 UTC weekly on Tuesdays. Anyone is welcome to contribute to the meeting by commenting in Slack threads throughout the week. Meeting notes will be published at the end of the week to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @bsanevans ._

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- October 17 – [@huzaifaalmesbah](https://profiles.wordpress.org/huzaifaalmesbah)
- October 24 – [@nayanchamp7](https://profiles.wordpress.org/nayanchamp7)
- October 31 - [@devmuhib](https://profiles.wordpress.org/devmuhib/)

**2. Looking for feedback**

- [Looking for feedback: Updates to GitHub issue templates and labels](https://make.wordpress.org/training/2023/09/27/looking-for-feedback-updates-to-github-issue-templates-and-labels/)
See [see sheet](https://docs.google.com/spreadsheets/d/1XGJKG26N1T59dPM-G_oT6eI67mlgaaGV4YQm_XbGDqg/edit#gid=0) and comment to help in this effort.
- [We have priority issues that need updating open in GitHub that are labeled 6.4](https://github.com/WordPress/Learn/issues?q=is%3Aissue+is%3Aopen+label%3A6.4)
  - Looking for a Contributor Hour host
  - Help validate the issue and comment on the issue what specifically needs to change
- Audit for Learning Pathways -- we need volunteers to help us identify the content we can utilize or enhance and incorporate it into our lessons. [Learn more about how to get involved in this post](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4009).

**3. Looking for volunteers**

- [Help us audit Learn WordPress for content](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4009) we can add to our Learning Pathways

**4. Updates from last week's dev-squad triage session**

- item 1
- item 2

**5. Other news**

- Badges awarded: [Rashi Gupta](https://profiles.wordpress.org/rashigupta)
- Handbook page updates
  - [Training Team rep information and nominations process handbook page update](https://make.wordpress.org/training/handbook/training-team-how-to-guides/team-roles/#training-team-rep)
  - [Contributor Hour](https://make.wordpress.org/training/handbook/training-team-how-to-guides/contributor-hour/)
  - [Meeting note recap](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-to-write-a-meeting-agenda-or-recap/#publishing-training-team-meeting-recap-posts)
- [Discussion: Defining Active and Engaged Faculty](https://make.wordpress.org/training/2023/09/28/discussion-defining-active-and-engaged-faculty/)
- [Guide Program first cohort is complete](https://make.wordpress.org/training/2023/10/13/project-update-the-guide-programs-first-month/)
- First course cohort is complete
- Hacktoberfest -- [a new post detailing how to get involved is now up on our website](https://make.wordpress.org/training/2023/10/06/take-part-in-hacktoberfest-2023-by-contributing-to-the-training-team/)
- Training Team nominations are coming.
- Team rep AFK
  - Ben + Destiny away Oct 21 - Oct 28 on business trip
  - Destiny AFK Oct 30 week
  - Pooja away Oct 28 - Oct 29 to attend WordCamp Mumbai

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - a
- **Lesson Plans**
  - b
- **Courses**
  - c
- **Translated Content**
  - d

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - Learning Pathway outlines have been published

## 5. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by webtechpooja** [comment]
@jonathanbossenger Could you share an update from last week's dev-squad triage session, please? 🙇‍♂️

**Comment by webtechpooja** [comment]
Point number 3 will be updated closer to the meeting. Thanks

**Comment by jonathanbossenger** [comment]
Updates from last week's dev-squad triage session

A quiet triage session this week, with 4 PRs and 1 new bug triaged.

PRs
- #1909
- #1910
- #1920
- #1932

Bugs
- #1880

**Comment by webtechpooja** [comment]
Recap notes- https://make.wordpress.org/training/2023/10/23/training-team-meeting-recap-17th-october-2023/
