### ISSUE TITLE
Online Workshop - WordPress 6.4 improvements - developer edition

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1942]
# Event Details
- Title: WordPress 6.4 improvements - developer edition
- Description: With WordPress 6.4 due to be released on the 7th of November, now would be a great time to test the new release, and start looking at the developer-focused improvements that are included. In this workshop, you'll learn how to install and use the WordPress Beta Tester plugin to test WordPress 6.4, as well as look into some of the plugin and theme developer improvements coming in 6.4.
- Target Audience: Developers
- Date: 2023-10-19 @ 14:00 UTC
- Meetup.com event link: https://meetup.com/learn-wordpress-online-workshops/events/296729393/
- Co-host: 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
Pre workshop pre livestream (no co host needed for this): https://www.meetup.com/learn-wordpress-online-workshops/events/296729447/

**Comment by SierraTR** [comment]
I'm available to co-host again.

**Comment by jonathanbossenger** [comment]
Thanks @SierraTR

**Comment by jonathanbossenger** [comment]
[WordPress 6.4 Source of Truth
](https://nomad.blog/2023/10/09/wordpress-6-4-source-of-truth/)

## New TT4 theme

https://make.wordpress.org/core/2023/08/24/introducing-twenty-twenty-four/

## Create Block Theme

Theme creator tools right inside the editor!!!!

## Block hooks

https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/#block-hooks-optional

- Still very new!
- Only works on block theme templates, template parts, and block patterns. These must be loaded from the theme's files, and not from user changes.
- The block must NOT render anything from the save function, currently only seems to work with dynamic blocks (ie using PHP to render the block output)
- [List of core blocks](https://developer.wordpress.org/block-editor/reference-guides/core-blocks/)

Add render to block.json
```
"render": "file:./render.php"
```
Create render.php file
```
<div <?php echo get_block_wrapper_attributes(); ?> >
	<p><?php echo esc_html( $attributes['content'] ); ?></p>
</div>
```
Remove save function from block.js

## Rename Group blocks for improved organization

## useBlockEditingMode

https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/#useblockeditingmode
```
var useBlockProps = blockEditor.useBlockProps; 
```
```
useBlockEditingMode('disabled');
```
## PHP Compatibility notes

https://make.wordpress.org/hosting/handbook/server-environment/#php

**Comment by SierraTR** [comment]
Nice overview of what is coming up.  You had 29 attendees.  Have a good team meeting and enjoy your vacation - decompress.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/10/20/wordpress-6-4-improvements-developer-edition/
