### ISSUE TITLE
how to start

### ISSUE THREAD

**Issue by normmccord** [WordPress/Learn#1961]
just... how to start.

what to download, why I need a database, why php or mySQL or what they even are, what if I'm using a hosting provider that's not bluehost.

**Comment by kaitohm** [comment]
Thank you for the suggestion. This content is currently being created in the Learning Pathways project.

* #1984 is for the beginner developer, and module 1 covers the ideas raised here.
* #1977 is for the beginner user, and gives a briefer overview of the technicality, and jumps right into getting a site set up.

I'll close this issue in favor of the two issues listed above. Feel free to comment on those if you'd like to contribute to the creation of this content.
