### ISSUE TITLE
Tutorial - Introduction to WordPress

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1962]
# Topic Description
Gain a basic understanding of what you can achieve with WordPress at a beginner-level
1. Make a website or blog
2. Web-based content management system

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
Uploading Introduction to WordPress.mp4…

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/9209e414-e8d2-45e2-89c7-d56f5b084cd0

**Comment by TinaCollier** [comment]
Hiya @westnz,

I'm excited to help you kick off the user learning pathway with this first tutorial video! This tutorial was a perfect introduction to the pathway. 

Here are some thoughts I had rom watching the tutorial:
1. The first slide needs capitalization and grammar, or to say something else. For example, "We'll delve into the basics." or "WordPress: The Basics"
2. Learning outcomes look great and are all addressed during the tutorial
- [x] Define WordPress
- [x] What can be achieved using WordPress
- [x] Explore examples of WordPress sites
- [x] Clarify what open-source means
- [x] Briefly discuss the importance of themes and plugins
3. Great explanation of what a WordPress site/CMS is
4. Great explanation of open-source
5. I like the examples of WordPress site uses
(BONUS) Could we mention some popular sites that use WordPress? For example: Nasa, The White House, Katy Perry's website, or BBC America

Thank you for the great tutorial! Please let me know if you need any help or additional support with these tutorials. 

Best regards,
Tina

**Comment by westnz** [comment]
I value your feedback @TinaCollier 🥇

**Comment by westnz** [comment]
@TinaCollier Please let us know if you are keen to help create any tutorials as well.

**Comment by TinaCollier** [comment]
@westnz Absolutely! I have the time.

**Comment by digitalchild** [comment]
@westnz This is a great quick introduction to WordPress. This would be great to link to people when they ask. "What is WordPress?"

**Comment by westnz** [comment]
That is precisely what I was hoping for @digitalchild. Thank you!

**Comment by Zebedeu** [comment]
Hi @westnz  this video does an excellent job of introducing new users to WordPress. You explain in a clear and detailed way what WordPress is, and how to get started using it. The presentation is very well organized and easy to follow even for beginners. Congratulations on the great tutorial! This video will certainly be very useful for anyone just starting out with WordPress.

**Comment by westnz** [comment]
Thank you so much @Zebedeu

**Comment by stutitech** [comment]
Hey @westnz , your video about WordPress is really good for people who are just starting. Your explanations are clear, detailed, and easy for beginners to understand. The way you've organized the information makes it simple for anyone who's new to WordPress.

**Comment by itsgajendraSingh** [comment]
Great job, @westnz ! Your clarity makes this video perfect for beginners. A very helpful introduction indeed.

**Comment by westnz** [comment]
Thank you very much @stutitech and @itsgajendraSingh

**Comment by abhansnuk** [comment]
Hello @westnz I came across this when sourcing short clips to include in a presentation tomorrow on Learn WordPress. It is very well presented and a good pace. Great job.

A question on the video, I think there should be something on the last screen making clear that the websites and plugins featured are just some of the examples available, and their inclusion is not a recommendation of their services by WordPress.org? I recall this was one of the guidelines previously discussed for Learn, @courtneyr-dev may have advice as remember she was involved with that guidance. 

The dairy site coming fairly fast after the learning objectives may confuse watchers with why it is there as the examples are not mentioned until later and there is no commentary relating to it. I personally think a screen which showed more than one might have worked better so early in the video. It is probably too late a comment.

**Comment by abhansnuk** [comment]
The guidance is at https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/ under the 'When brands are mentioned in training content'. The content also needs to be reviewed in case the sites are no longer on WP in the future. If we have the ability to add a date to review the brands featured in the workflow this would be super useful.

**Comment by westnz** [comment]
Thank you @abhansnuk, for the feedback! Your comment came just in time, as I was going to consider/implement suggestions next week.

**Comment by westnz** [comment]
Published in Sensei: https://learn.wordpress.org/?post_type=lesson&p=56333
