### ISSUE TITLE
Tutorial - Choosing a domain name and hosting service 

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1963]
# Topic Description
Choose website hosting that bundles domains and be able to describe the difference between a host and a domain
1. Gain a basic understanding of how a host and domain interact and their different roles.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/3aefab19-c48e-4ef3-8cdd-3658d8bcba0f

**Comment by digitalchild** [comment]
Another great overview @westnz One thing I would like to see is a section that is just on domain registration separated from domain+hosting options. You mention that you can easily change your hosting if without changing your domain, but that isn't really the case when you bundle your domain with your hosting company.

**Comment by westnz** [comment]
Thank you for flagging this @digitalchild. I will revise this section and do some more research.

**Comment by westnz** [comment]
@digitalchild 

I got this feedback from one of our Happiness Engineers: "This is possible, without too much hassle, but being sure to be careful with how and when the settings for the domain are changed. This influences the connectedness of the domain, once any change is made. There is a propagation time for changes like [name server changes](https://wordpress.com/support/domains/change-name-servers/#changing-name-servers-to-point-away-from-word-press-com), and to a lesser degree, A record changes. Although this article outlines our own process for [connecting a domain vs transferring](https://wordpress.com/support/domain-connection-vs-domain-transfer/), it is indicative of how similar it could be for other hosts, in terms of process."

Is it then fair to say?: "It is possible to change your hosting without changing your domain, but reach out to the new hosting company to ensure you follow the correct steps."

**Comment by SierraTR** [comment]
Wes, Yes, that would be a fair and correct statement. I have done it many times. Perhaps that would be a topic for a follow-on tutorial - Moving your website to a different hosting company - and/or changing domain registrars. Two different processes explained in general terms.

**Comment by westnz** [comment]
Thanks @SierraTR! Any chance you will be interested in writing a short script for this type of tutorial?

**Comment by SierraTR** [comment]
I'll see what I can do later this week.

## Tutorial Review Checklist
Please tick all items you've confirmed:
- [X] Technical concepts introduced in the content are accurate.
- [ X] The speed of demonstrations are easy to follow.
- [X ] The narration audio matches what is shown visually.
- [X ] Spelling and grammar are correct.
- [ X] Sound quality is consistent throughout the video.
- [X ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [X ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.
Well done. I agree with @digitalchild and have made a suggestion about a future tutorial.

**Comment by westnz** [comment]
Awesome!  Thanks @SierraTR

**Comment by SierraTR** [comment]
You must be working too hard. You published a website migration tutorial 9 months ago.
[https://youtu.be/N3iPNpJQfpc?si=VUi37RE32Uw0O41b]

**Comment by westnz** [comment]
@SierraTR  Hehe! 😆  I remember that one, but it covers using a plugin, changing your domain name + 301 redirects. It would be good to have a tutorial that covers keeping your domain name when changing to a new hosting company?

**Comment by stutitech** [comment]
Hello @westnz, your tutorial on domain and hosting is fantastic. The sound quality is good, the speed is just right, and your narration matches the audio seamlessly. Your explanations are clear, the content is well-organized, and you've used examples excellently. Great job!

**Comment by westnz** [comment]
Many thanks for the feedback @stutitech 👍

**Comment by nazsakib** [comment]
Well-descriptive and beginner-friendly, and your way of delivering the speech is outstanding, engaging, and informative, making the video both enjoyable and educational. Keep going!

**Comment by westnz** [comment]
Thank you very much @nazsakib

**Comment by abhansnuk** [comment]
Hello @westnz great information and pace in this tutorial. I like the caravan imagery.

As in the other issue on 'An introduction to WordPress', I suggest there should be a disclaimer that the host examples shown are just some of those available'. Could this be in a final slide? There are more hosts than in the slide on hosts. Also the final screen could give the disclaimer on products/ companies featured.

I think the hold on the first website example is quite a long time, and think this would have benefited from more than one site being shown during this hold. 

https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/ 

In the section on things to consider about domain names, I think country-specific domains may be worth including in future, as some countries have restrictions on certain domains.

**Comment by westnz** [comment]
Thank you, @abhansnuk 🙏

**Comment by westnz** [comment]
Published in Sensei: https://learn.wordpress.org/?post_type=lesson&p=56348
