### ISSUE TITLE
Tracking `build` clutters `git stat | diff | etc`

### ISSUE THREAD

**Issue by iandunn** [WordPress/Learn#197]
@coreymckrill , do you remember the reason for tracking `plugins/wporg-learn/build` in this repo?

I'm finding it distracting and frustrating to work with commands like `git stat`, `diff`, etc because most of the output is unrelated & obfuscated. I don't see an obvious benefit to it tracking it, since we're not deploying from this repo directly, but could be missing something.

Would there be any downside to removing it from this repo, but still keeping it in the SVN deploy repo?

**Comment by coreymckrill** [comment]
The only downside I can think of to removing the build directory from git is that it will require an additional step for people who set up the local dev environment before they can get it running. But that seems pretty minor. I don't have a problem with removing it. It would be good to update the `create` script to include the build step, and update the readme to reflect the change.

**Comment by iandunn** [comment]
👍🏻
