### ISSUE TITLE
Meeting Agenda November 14, 2023

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1972]
Training Team meetings start at 07:00 UTC weekly on Tuesdays. Anyone is welcome to contribute to the meeting by commenting in Slack threads throughout the week. Meeting notes will be published at the end of the week to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune ._

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- November 14th – @devmuhib009 
- November 21st – need volunteer
- November 28th – need volunteer
- December 5th – need volunteer

**2. Looking for feedback**

- [Nomination for 2024 Training Team Reps](https://make.wordpress.org/training/2023/10/23/nomination-for-2024-training-team-reps/)
  - Today is the final day to nominate someone!

**3. Looking for volunteers**

- Learning Pathway Content Creators
  - We need help creating lessons for the Designer, User, and Developer pathways.

**4. Updates from last week's dev-squad triage session**

There was no dev-squad session last week. 

**5. Other news**

- [Recap: The first Learn WordPress course cohort](https://make.wordpress.org/training/2023/11/13/recap-the-first-learn-wordpress-course-cohort/)
  - We are looking for feedback to the questions noted in this post! Please thread replies or comment on the linked post.
- 6.4 is out and was the first release where we had the Training Team as part of the release squad. @courtneyr-dev @courtney-pk -- do you have any feedback on how the process went for you and what you'd like to see happen for future releases? Any guidance for anyone from the team looking to work in this capacity in the future?

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - #1963 
  - #1891 
- **Translated Content**
  - We're looking for Indonesian, Khmer, and German translation reviewers. ([Link to content needing a Translation Reviewer](https://github.com/orgs/WordPress/projects/104/views/10).) -- suggestion, can we do an AI review?

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) -- [see latest update](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4037)
  - The information architecture has been decided
  - Content creation work has begun on the Developer and User pathways

## 5. Open Discussions

- #1974 

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by devmuhib009** [comment]
Want to take notes on Nov 14th.

**Comment by kaitohm** [comment]
Please also bring this issue up #1974 
Perhaps we can discuss it live during the meeting?

**Comment by jonathanbossenger** [comment]
The course cohort recap post has been published.

https://make.wordpress.org/training/2023/11/13/recap-the-first-learn-wordpress-course-cohort/

I want to ask any interested training team members to help answer the follow-up questions on that post.

**Comment by devmuhib009** [comment]
I am drafting the post and just noticed the issue title has a small mistake. The date will be 2023 , not 2024.

**Comment by kaitohm** [comment]
Haha, good catch. I've fixed that 👍

**Comment by kaitohm** [comment]
https://make.wordpress.org/training/2023/11/20/training-team-meeting-recap-14th-november-2023/
