### ISSUE TITLE
Learning Pathway: Beginner User

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#1977]
See full User pathway [outlined in this document](https://docs.google.com/spreadsheets/d/1uOm1I62zZLoZGm1rMI2_Ihvul_Z8hwbCExFirr_zhjI/edit#gid=0). 

_This course has 25 lessons over 7 modules._

# Beginner

## Module 1
Objective: Getting started with WordPress 

### Lessons
- [x] #1962 
- [x] #1963 
- [x] #758 
- [x] #696

## Module 2
Objective: Gain a familiarity with the WordPress Interface: be able to comfortably navigate the WordPress dashboard and understand its basic layout and terminology. 

### Lessons
- [x] #706 
- [x] #704 
- [x] #750 
- [x] #2071
- [x] #694
- [x] #2099 

## Module 3
Objective; Site Editing: Basics of how you can modify and customize WordPress block themes. This will include changing colors, fonts, and basic minor layout adjustments.

### Lessons
- [x] #456
- [x] #455
- [x] #1462

## Module 4
Objective: Content creation

### Lessons
- [x] #2116 
- [x] #2152 
- [x] #1616 
- [x] #443 
- [x] #2166

## Module 5
Objective: Spam, backups and, and security

### Lessons
- [x] #2174 
- [x] #2175
- [x] #1551 

## Module 6

Objective: SEO 

### Lessons
- [x] #1167 
- [x] #1602 

## Module 7

Objective: Where to get support

### Lessons
- [x] #2216

**Comment by westnz** [comment]
//published
