### ISSUE TITLE
Bengali translation for Tutorial "Managing Settings: Reading"

### ISSUE THREAD

**Issue by devmuhib009** [WordPress/Learn#1978]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/managing-settings-reading/
- Link to original content GitHub issue (optional): 
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by mhasanmeet** [comment]
I want to review this translation. Please add the translation file here once you are ready.

**Comment by devmuhib009** [comment]
Hello @mhasanmeet 

Thanks for your interest to review the content. Here is the [translation file](https://docs.google.com/document/d/1wbCJGkHlQneZ-aEAJziaypcG6ImTkXINIX_tAbBdUps/edit?usp=sharing). Please suggest me what else I can improve in this document.

**Comment by mhasanmeet** [comment]
Everything looks good. You can move further.

**Comment by mhasanmeet** [comment]
As you already added me as an editor on Google Docs, I checked and updated few lines. So, everything looks fine. You can move forward.

**Comment by kaitohm** [comment]
Thanks for reviewing the translation, @mhasanmeet 🙌 

@devmuhib009 I've assigned you as the author on https://learn.wordpress.org/wp-admin/post.php?post=55607&action=edit

Please continue from step 5 listed here: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video Thanks for translating! 🌟

**Comment by devmuhib009** [comment]
Thanks @bsanevans 

I will upload the content and update here.

**Comment by devmuhib009** [comment]
Hello Ben Evans

I just updated the post and uploaded subtitle to [WordPress TV](https://wordpress.tv/2021/10/21/roxy-kohilakis-managing-reading-settings/) as well. Can you please check?

**Comment by kaitohm** [comment]
Thanks! I've approved the subtitles. I also noticed the Tutorial post title was left in English. I've replaced it with `সেটিংস ম্যানেজঃ পড়া`, which I found in your translation doc above. Feel free to update this yourself in future 😉 

Otherwise, the rest looks perfect! This content has now been published here: https://learn.wordpress.org/tutorial/bn-managing-settings-reading/

Thank you for your contribution!
