### ISSUE TITLE
Tutorial - Getting started with WordPress security

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#1981]
# Topic Description
This lesson is part of the beginner user learning pathway.  It will cover the basic security steps to put in place when starting a new site.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/9da543dc-0da2-46f0-afef-ab88d76521e8

**Comment by abhansnuk** [comment]
Another really good narrated tutorial, and my favorite to date. Can we add a final slide that makes it clear that there are more plugins and hosts that may have been shown and appearing in the tutorial does not imply an endorsement.

I would suggest a change in the title as 'WordPress foundation' is a term already well known in the community and people may think it is about that and securing the legacy/ work of that foundation. I think to help people find this in search a more direct title would also help, referencing site or website.

On learning outcomes, I appreciate you are probably trying to save space. How to do those things or an ability to do those things would be a learning outcome. Perhaps adding in future - 'how to' after 'learning outcomes' would still save you space and turn them  into learning outcomes.

**Comment by abhansnuk** [comment]
On the 'controlling who has access to your site' image, about 5.06, should there be a '6' in the bottom left @westnz ? Thanks.

Is there another image you could use for 'assign these users' about 5.56 in the timeline? I am not sure it goes with the audio, and I think has been used earlier.

**Comment by westnz** [comment]
Thank you @abhansnuk 👍

**Comment by nazsakib** [comment]
This tutorial is great for understanding the security of WordPress sites.  The clear and concise voiceover, informative slides, and adherence to the concepts are quite commendable.

However, I'd like to mention that it would be great if you included in the subtitle an explanation of what SSL/SFTP actually means. To clarify, SSL stands for Secure Sockets Layer, and SFTP stands for Secure File Transfer Protocol.

Rest is incredible!

**Comment by westnz** [comment]
Many thanks @nazsakib

**Comment by askhellosatya** [comment]
The tutorial is concise, clear, and effectively imparts the understanding of WordPress security. Kudos to @westnz for another impressive presentation with excellent slides! Apart from the two issues already addressed, I have no further concerns.

**Comment by westnz** [comment]
Thanks so much @askhellosatya

**Comment by itsgajendraSingh** [comment]
Great job to @westnz for simplifying WordPress security in the tutorial. The presentation was easy to follow with clear explanations and great slides. Thanks for another fantastic presentation!

**Comment by westnz** [comment]
Thank you for the feedback @itsgajendraSingh

**Comment by westnz** [comment]
Published in Sensei as part of the draft Beginner User learning pathway.

**Comment by westnz** [comment]
I reached out to Tim Nash to help update/improve this lesson. I have removed it from the pathway for the time being as we already have a lesson about security in the pathway.
