### ISSUE TITLE
Bangla translation for Introducing the twenty twenty-four theme

### ISSUE THREAD

**Issue by yasinsarkar** [WordPress/Learn#1982]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/introducing-the-twenty-twenty-four-theme/
- Link to original content GitHub issue (optional): 
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: https://github.com/devmuhib009
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by mhasanmeet** [comment]
Hi @yasinsarkar I also want to be a transition reviewer.

**Comment by yasinsarkar** [comment]
Here is the file please check : https://docs.google.com/document/d/1WOPJw-Gm8RyEBSRaabTfSzwoHGMxcxv_CVBgC3ecduM/edit?usp=sharing

**Comment by yasinsarkar** [comment]
@mhasanmeet  I will appreciate if you review the content as well.

**Comment by devmuhib009** [comment]
I just reviewed first few paragraph's till the transcript and suggested some replacement. You can consider these suggestions and improve rest of the translation. Once update, please comment here, I will recheck.

> বোধগম্য প্রশ্ন

সম্পূরক প্রশ্ন

> টুয়েন্টি টুয়েন্টি-ফোর থিমের সাথে আসা বিভিন্ন নিদর্শন এবং টেমপ্লেটগুলি অন্বেষণ করা।

টুয়েন্টি টুয়েন্টি-ফোর থিমের সাথে আসা বিভিন্ন প্যাটার্ন এবং টেমপ্লেটগুলি অন্বেষণ করা।

> উপলব্ধ স্টাইল বৈচিত্র আবিষ্কার.

এভেইলেবেল স্টাইল ভেরিয়েশন আবিষ্কার করা। 

> উপলব্ধ

এভেইলেবেল 

> চলুন, এখন উপলব্ধ টোয়েন্টি টুয়েন্টি-ফোরের দুর্দান্ত নতুন থিমটি ঘনিষ্ঠভাবে দেখে নেওয়া যাক।

চলুন নতুন থিমটি নিবিড়ভাবে পর্যালোচনা করি, টোয়েন্টি টুয়েন্টি-ফোর, যেটি এখন এভেইলেবেল।

**Comment by mhasanmeet** [comment]
ভাই ট্রান্সলেশনগুলো আরো সময় নিয়ে ট্রান্সলেট করা উচিত, ট্রান্সলেশনগুলো অনেকটাই যান্ত্রিক হয়ে যাচ্ছে। তাই আমি বলবো ডকে অল্প অল্প করে ট্রান্সলেশন করুন, এক্ষেত্রে সময় ১-২ সপ্তাহ নিতে পারেন।

**Comment by yasinsarkar** [comment]
Here is my updated file, please check https://docs.google.com/document/d/1WOPJw-Gm8RyEBSRaabTfSzwoHGMxcxv_CVBgC3ecduM/edit?usp=sharing

**Comment by mhasanmeet** [comment]
Thanks, I'll check

**Comment by mhasanmeet** [comment]
Just completed the review and made several changes.

**Comment by yasinsarkar** [comment]
I updated my docs file. @mhasanmeet vai thank you for reviewing my file.  Please check

**Comment by mhasanmeet** [comment]
It looks great now, ready for publishing. @bsanevans please take care of this translation.

**Comment by kaitohm** [comment]
Thank you all for reviewing!

@yasinsarkar I've just sent you an email, inviting you to become a Contributor on https://learn.wordpress.org/. Please let me know once you've accepted this, and I will guide you with next steps.

**Comment by yasinsarkar** [comment]
I accepted the invitation. Please guide what to do next?

**Comment by devmuhib009** [comment]
Hi, @yasinsarkar 

I've added you as author to the post. https://learn.wordpress.org/wp-admin/post.php?post=62547&action=edit
Please continue from step 5 in this handbook page: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video

**Comment by yasinsarkar** [comment]
I already updated the Subtitle file and submitted https://wordpress.tv/. Please check

**Comment by devmuhib009** [comment]
Thanks @yasinsarkar I just published the post. https://learn.wordpress.org/tutorial/bn-introducing-the-twenty-twenty-four-theme/

**Comment by yasinsarkar** [comment]
Thank you
