### ISSUE TITLE
Topic Idea: Transfer staging site design and layout to the live site without losing current data from the live site.

### ISSUE THREAD

**Issue by DjWellz** [WordPress/Learn#1983]
# Details

- Topic description: 
- Audience (User, Developer, Contributor, etc.): User. 
- Learning objectives (What will the learner be able to do as a result of this content?):  Learn how to update a live site to a new theme without losing the current data and files of the live site. When going from a Classic theme to a block theme, it would be great if we had the ability to design the new layout on the staging site (using the new block theme), and then, rather than having to push a staging site that might not be fully updated (data wise since its content is older than that which is on the live site), we could just use the design and layout created on the staging site  almost like a theme. 
For example, on the live site we install the new block theme to match the one used on the staging site, and then when ready, activate it, and then import the design/layout info from the staging site so that the live site now looks the same as the staging site but it also remains up to date since the current data on the live site would not be overwritten. 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): tutorial
- WordPress version (optional): 6.4 plus
- Will you be creating this content? (Yes or No): No

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by askdesign** [comment]
Isn't this basically designing a block theme on a staging area (local or cloud)? Then, when finished, uploading the new theme to the live site so it can be used?

**Comment by jonathanbossenger** [comment]
@DjWellz is the process that @askdesign is describing what you are looking for? So
1. Copy live to staging.
2. Create new block theme on staging, to meet requirements
3. Export block theme from staging, as an installable theme zip file, using the [Create Block Theme plugin](https://wordpress.org/plugins/create-block-theme/)
4. Install and activate the new block theme on the live site.

**Comment by Piyopiyo-Kitsune** [comment]
@jonathanbossenger This sounds like an Advanced WordPress User / Developer lesson -- is this something you're considering in the current learning pathways or could be for a new course?

**Comment by jonathanbossenger** [comment]
@Piyopiyo-Kitsune, thanks for tagging me here. 

We cover how to use Create Block theme to export themes to an installable zip in [this lesson](https://github.com/WordPress/Learn/issues/2197) so I'm inclined to close this for now. 

Anyone who feels that this should still be added somewhere can re-open it and provide more context.

**Comment by DjWellz** [comment]
I apologize for the late reply. I'm an end user who has been struggling to understand why a staging site can't maintain and sync data (posts, sales info, comments, etc.) with the live site at all times. This would allow the staging site to be activated once the design is complete, without any data loss.
In my case, the live site was created in 2015 using Genesis and a child theme. The new design would utilize the Ollie block theme only. My hosting company, SiteGround, has a feature that allows you to create a staging site from a copy of the live site, provided you have enough hosting space available. However, once the staging site is created, it will only contain the data that was initially copied. This means that if a week or more has passed, and the live site has grown (with new posts, comments, etc.), none of that new data would be on the staging site. In this case, the only way to add the new data to the staging site is by creating a new staging site from a fresh copy of the live site. However, this will remove or overwrite any changes already made on the staging site.
I thought perhaps someone could develop a process or feature that would allow users to create and design the layout on the staging site and then apply it to the live site like a skin. The key point would be for the live site to adopt the full redesign from the staging site without looking strange afterwards. Since the staging site is already a copy of the live site, all the changes could be bundled into this "skin" and then activated on the live site.
As I'm not well-versed in this area, I'm unsure of the feasibility or the effort required to create such a feature. I understand it may sound like simply activating a new theme, but as we know, activating a new theme doesn't guarantee the desired appearance. Elements can shift, disappear, or be incompatible, which is why I was searching for an alternative method to facilitate an easier transition from the staging site to the live site.

**Comment by jonathanbossenger** [comment]
Hi @DjWellz I'm also sorry to only reply so late, but I've been on leave for 2 weeks.

> I'm an end user who has been struggling to understand why a staging site can't maintain and sync data (posts, sales info, comments, etc.) with the live site at all times. This would allow the staging site to be activated once the design is complete, without any data loss.

The reason this happens is that a staging site will usually have its own database, and when it's created, it will simply be a copy of the existing data from the live site. This is done intentionally, as you wouldn't want any testing data from the staging site to be populated over to the live site. 

As mentioned earlier, it is currently possible to design the layout on the staging site and then export it as a custom theme to be populated to the live site using something like the [Create Block Theme plugin](https://wordpress.org/plugins/create-block-theme/).

@westnz Does the above sound like something that might make sense as part of the advanced user learning pathway? Perhaps you've already planning a module on this?

**Comment by westnz** [comment]
Yes, we do plan to cover that in the Advanced user learning pathway 😃

**Comment by DjWellz** [comment]
@jonathanbossenger 
Thanks for the follow up. On my journey to make the switch from the classic theme to the Ollie block theme, I ended up using parts of the Create Block theme plugin. I'll confess that there were parts that were not clear to me, but I pushed forward anyway since I also had a deadline with the hosting company.  My hosting plan was up for renewal, and I wanted to make the switch and downsize my hosting plan prior to the renewal (I had to double the plan size in order to create the staging site). I used a repair mode plugin to temporarily limit access to the live site while I made the switch. I'm still working on tweaks for the site, but at least it is up and running. 

I'm sure that others with similar situations to mine would very much appreciate a tutorial showing the process for going from classic theme to block theme with minimal loss. 

All the best,
Wellz

**Comment by jonathanbossenger** [comment]
It looks like this is planned for the Advanced user learning pathway, my guess would be this lesson on [Create Block Theme](https://github.com/WordPress/Learn/issues/2552), so I'm going to close this issue again, while that lesson is in development.
