### ISSUE TITLE
Learning Pathway Course: Beginner Developer

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1984]
# Learning Pathway Course: Beginner Developer

The beginner level can be defined as the fundamental knowledge that a new WordPress developer should know, from having no knowledge to being able to develop with and extend WordPress. 

Once completed, the developer can move onto one of the following learning pathways:

- #2045 
- #2044

See the full Developer pathway [outlined in this document](https://docs.google.com/spreadsheets/d/1uOm1I62zZLoZGm1rMI2_Ihvul_Z8hwbCExFirr_zhjI/edit#gid=227009618).

To learn more about creating content for these lessons, please read the [Guidelines for creating, reviewing, and publishing lessons](https://make.wordpress.org/training/handbook/lessons/). 

_This course has 56 lessons over 12 modules._

_56/56 (100%) completed._

https://www.youtube.com/watch?v=nh1qC1la3og&list=PL1pJFUVKQ7ETYqC5F_z4BOJ4FoT7xZy_u

Total watch time: 5 hours, 58 minutes, 25 seconds

## [Module 1: A brief overview of how WordPress works](#module-01)

Objective: Understand how a web server powers a WordPress site, from the hardware stack through to the database. Review and follow a standard front-end and admin page request.

### Lessons

- [x] #1985
- [x] #1986
- [x] #1987
- [x] #1988
- [x] #1990
- [x] #1989

## [Module 2: Local development requirements](#module-02)

Objective: Identify the different pieces of software needed to develop for WordPress, as well as some additional useful tools for developers.

- [x] #2147
- [x] #2148
- [x] #2149
- [x] #2150

## [Module 3: The programming languages of WordPress](#module-03)

Objective: Introduce the 5 programming languages of WordPress, HTML, CSS, JavaScript, PHP, and MySQL
covering HTML and Accessibility, HTML Block markup, and React as a JavaScript framework.

### Lessons

- [x] #2074
- [x] #2075
- [x] #2076
- [x] #2077
- [x] #2078 

## [Module 4: WordPress Hooks](#module-04)

Objective: Understand the WordPress hooks system

- [x] #2079
- [x] #2080
- [x] #2081
- [x] #2209

## [Module 5: An introduction to developing WordPress themes](#module-05)

Objective: Introduce the foundational elements of WordPress theme development, with a brief overview of classic themes.

### Lessons

- [x] #2082
- [x] #2085
- [x] #2086
- [x] #2087
- [x] #2090
- [x] #2197

## [Module 6: An introduction to developing WordPress plugins](#module-06)

Objective: Introduce the foundational elements of WordPress plugin development.

### Lessons

- [x] #2113
- [x] #2127
- [x] #2180
- [x] #2208 
- [x] #2181
- [x] #2183

## [Module 7: An introduction to developing WordPress blocks](#module-07)

Objective: Introduce the foundational elements of block development for WordPress.

### Lessons

- [x] #2236
- [x] #2237
- [x] #2238
- [x] #2263
- [x] #2240
- [x] #2239
- [x] #2241
## [Module 8: An introduction to the WordPress REST API](#module-08)

Objective: Introduce the WordPress REST API, and how to use it to interact with core WordPress data.

### Lessons

- [x] #2265
- [x] #2266 
- [x] #2267
- [x] #2268

## [Module 9: An introduction to developing for WordPress securely](#module-09)

Objective: Covers the guiding principles of developing plugins and themes securely, with examples of the five most common security problems, and how to avoid them.

### Lessons

- [x] #1925
- [x] #1926
- [x] #1927

## [Module 10: An introduction to Internationalization](#module-10)

Objective: Introduce the concept of internationalizing your WordPress code.

### Lessons

- [x] #2279
- [x] #2342

## [Module 11: An introduction to WordPress multisite](#module-12)

Objective: An overview of how to set up and manage a WordPress multisite, as well as how to develop themes and plugins for multisite.

### Lessons

- [x] #2365
- [x] #2374
- [x] #2375
- [x] #2377
- [x] #2376

## [Module 12: Debugging in WordPress](#module-13)

Objective: Introduce built in tools and techniques for debugging WordPress plugin or theme code.

### Lessons

- [x] #2378
- [x] #2379
- [x] #2380
- [x] #2381

**Comment by cynthianorman** [comment]
@jonathanbossenger I would like to work on creating lessons for Module 3: An introduction to developing WordPress themes

**Comment by jonathanbossenger** [comment]
Thanks @cynthianorman, I have assigned you to this ticket. Feel free to unassign yourself once you have completed those lessons.

**Comment by jonathanbossenger** [comment]
As of 2023-12-11 I have removed the module on the Common APIs, for two reasons:

a) this list only includes PHP based APIS
b) I'm still not convinced this needs an entire module, and perhaps it would make more sense just to link to relevant APIS when they are used inside lessons.

I am adding the list here for reference.

## [Module xx: An introduction to Common WordPress APIs](#module-11)

Objective: Introduce the most common WordPress APIs, and how to use them.

### Lessons

- [ ] Responsive Images
- [ ] Dashboard widgets
- [ ] Database
- [ ] Filesystem
- [ ] Global Variables
- [ ] Metadata
- [ ] Options
- [ ] HTTP Requests
- [ ] Rewrite
- [ ] Settings
- [ ] Shortcode
- [ ] Transients

**Comment by jonathanbossenger** [comment]
Hi @cynthianorman 

When you have a moment, I wanted to touch base with you regarding [Module 4: An introduction to developing WordPress themes](https://github.com/WordPress/Learn/issues/1984#module-04).

I want to make sure that contributors can set their own deadlines, but also be mindful of the fact that we're aiming to launch the new Learn redesign with learning pathways by July 2024.

So I wanted to get an idea from you when you feel like you'll be able to complete the first iteration of that module.

Thanks

**Comment by cynthianorman** [comment]
Hi @jonathanbossenger . I feel confident that this will change into Feb. I would expect to have the Beginner Developer Module 4 lessons done by end of Feb.

**Comment by jonathanbossenger** [comment]
Thanks @cynthianorman 

Today I was reviewing the learning pathway outline, and I discovered that the lesson on the Create Block Theme plugin was added to the Block Development module, and not the Theme Development module. The objective of this lesson would just be to introduce the learning to the plugin, and it's basic functionality. 

I've moved it to the right place, but I wanted to check if you would prefer me to handle this lesson, or if would you be able to squeeze it into your February plans.

I completely understand if you don't have time to add another lesson, and I am happy to create this specific one.

**Comment by cynthianorman** [comment]
Hi @jonathanbossenger 

Thank you for the offer but I'm more than happy to add that lesson. I think cohesiveness within a given module was a great idea you had during our previous talks.

**Comment by jonathanbossenger** [comment]
Ok, thanks @cynthianorman.

**Comment by jonathanbossenger** [comment]
Note to contributors, while working on the plugin module today, I realized that we need to cover the concept of hooks earlier on because most plugin and theme development requires an understanding of hooks.

I have therefore moved the hooks module to module 3, and tomorrow I will work on the introductory lesson of that module, as well as reworking the original tutorials on action and filter hooks for the learning pathways.

You can find the original tutorials linked in action and filter hook issues, if you want to get an idea of what will be covered.

**Comment by jonathanbossenger** [comment]
Noting that #2088 and #2089 have been moved to #2045.

**Comment by jonathanbossenger** [comment]
Issue #2266 created for this learning pathway

**Comment by jonathanbossenger** [comment]
Update, moved the Roles and Capabilities module to the Plugin developer pathway. 

Added the lesson on enqueuing CSS and JS to the Introduction to plugin development module.

**Comment by jonathanbossenger** [comment]
@cynthianorman all your introduction to developing WordPress themes videos have been published on YouTube. I've left a comment on each issue, asking for the YouTube chapter markers, so I can add them. (Let me know if you have any questions about that).

You should also have the required access to add the lessons to learn.wordpress.org, so feel free to go ahead and update/publish those lessons, and close the issue once the lesson is published.

**Comment by cynthianorman** [comment]
@jonathanbossenger sounds good - thank you!

**Comment by jonathanbossenger** [comment]
@cynthianorman I just wanted to check in to see how it's going with getting the lessons for the [An introduction to developing WordPress themes](https://github.com/WordPress/Learn/issues/1984#module-04) module published on Learn.WordPress.org?

**Comment by cynthianorman** [comment]
@jonathanbossenger that shouldn't be a problem for me to fit into this month.

**Comment by jonathanbossenger** [comment]
@cynthianorman I've closed all the issues in module 4 [An introduction to developing WordPress themes](https://github.com/WordPress/Learn/issues/1984#module-04) that are published on Learn.WordPress.org. Once you publish the final two, please go ahead and close those issues as well. Thanks
