### ISSUE TITLE
WordPress and web servers

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1985]
# Learning Objective

Define what a web server is, identify the different parts of a web server.

# Relevant Links

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for Q/A review
- [x] Lesson submitted and published to WPTV
- [x] Lesson transferred to YouTube
- [x] Lesson reviewed and ready to publish
- [x] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/how-wordpress-works/web-servers.md

Video for review:

https://github.com/WordPress/Learn/assets/180629/59b17823-05d5-430b-8300-9a5a2b7caad5

**Comment by cynthianorman** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [ ] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.

Your timing is off a bit when you speak of Linux and Apache. The Apache slide shows up when you are giving more details about Linux (0:51) and then there's a small glitch (0:59) as you are still speaking generally of LAMP. I would suggest showing the Apache slide at 1:07

At 3:48 you missed saying a "w" in the directory

**Comment by jonathanbossenger** [comment]
Thanks @cynthianorman for the review, I'll get those two items fixed.

**Comment by nftushar** [comment]
# Learning Objective Review Checklist
Please tick all items you've confirmed:
> * [ ] **Learning objective is clear:** Define what a web server is, identify the different parts of a web server.
> * [ ] **Relevant links are provided:**
   - [ ] [Support, Docs, or related material](https://wordpress.org/documentation/)
> * [ ] **Lesson creation checklist is complete:**
   - [ ] [Gather any relevant links to Support, Docs, or related material](insert_gather_links_here)
   - [ ] Description and Objectives finalized
   - [ ] Lesson created and announced to the team for Q/A review
   - [ ] Lesson submitted and published to WPTV
   - [ ] Lesson transferred to YouTube
   - [ ] Lesson reviewed and ready to publish
   - [ ] Lesson published to Learn.WordPress.org

# Feedback:
The learning objective is precise in defining what a web server is and its components. However, to enhance practical understanding, it might be beneficial to incorporate specific examples or scenarios.

**Comment by nftushar** [comment]
# Learning Objective Review Checklist
Please tick all items you've confirmed:
> * [ ] **Learning objective is clear:** Identify and describe the different tables in the WordPress database, and the core functions to interact with these tables.
> * [ ] **Relevant links are provided:**
   - [ ] [WordPress Database Tutorial](https://learn.wordpress.org/tutorial/the-wordpress-database/)
> * [ ] **Lesson creation checklist is complete:**
   - [ ] Gather any relevant links to Support, Docs, or related material
   - [ ] Description and Objectives finalized
   - [ ] Lesson created and announced to the team for Q/A review
   - [ ] Lesson submitted and published to WPTV
   - [ ] Lesson transferred to YouTube
   - [ ] Lesson reviewed and ready to publish
   - [ ] Lesson published to Learn.WordPress.org

# Feedback:
The learning objective is clear and focuses on identifying and describing different tables in the WordPress database along with core functions for interaction. The provided link to the WordPress Database Tutorial is relevant and adds value to the objective.

Once the comment has been published, go through and check off items as you review the comment. Leave an additional comment on the GitHub issue with any additional feedback you have.

And you’re done! Thank you for contributing to the Training Team. If you have any more thoughts or questions, feel free to share!

**Comment by jonathanbossenger** [comment]
Hi @nftushar, thank you for the review, however, it seems to be incomplete.

If you follow the Guidelines for reviewing content, specifically the section on [Are you reviewing content before it is published?](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/#are-you-reviewing-content-before-it-is-published), you will see the steps outline are to:

1. Copy-paste the appropriate checklist, you can use the one for Tutorials and Learning Pathway Lessons
2. Once the comment has been published, you’ll notice it has turned into a checklist. Go through and check off items as you review the comment.
3. Leave an additional comment on the GitHub issue with any additional feedback you have.

If you could please update your comment to use the correct checklist, mark off the items you feel are completed, and leave any additional actionable feedback, that would be appreciated.

> it might be beneficial to incorporate specific examples or scenarios.

As this is an introduction to the concept of a web server, do you have any suggestions of specific examples or scenarios you feel would enhance the lesson?

**Comment by jonathanbossenger** [comment]
> Your timing is off a bit when you speak of Linux and Apache. The Apache slide shows up when you are giving more details about Linux (0:51) and then there's a small glitch (0:59) as you are still speaking generally of LAMP. I would suggest showing the Apache slide at 1:07

I'm having issues with my video editing tool on this one, it's all correct in the timeline view, but when I export the error happens. I've logged a support ticket and I'm waiting on feedback.

**Comment by jonathanbossenger** [comment]
Updated video

https://github.com/WordPress/Learn/assets/180629/1775f904-ad0d-4027-aa58-6164b955d5bb

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/wordpress-and-web-servers/

**Comment by jonathanbossenger** [comment]
## YouTube chapters

(0:00) Introduction
(0:24) What is a web server?
(3:10) Apache/Nginx configuration
(4:16) Directory Index
(5:37) WordPress request flow
