### ISSUE TITLE
The WordPress file system

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1986]
# Learning Objective

Describe the files and directories that make up a WordPress installation

# Relevant Links

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for Q/A review
- [x] Lesson submitted and published to WPTV
- [x] Lesson transferred to YouTube
- [x] Lesson reviewed and ready to publish
- [x] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/how-wordpress-works/file-structure.md

Video for review:

https://github.com/WordPress/Learn/assets/180629/72b2f3a0-65a2-460c-be6f-34ce03689cd7

**Comment by cynthianorman** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.

**Comment by nftushar** [comment]
# Learning Objective Review Checklist
Please tick all items you've confirmed:
> * [ ] **Learning objective is clear:** Describe the files and directories that make up a WordPress installation.
> * [ ] **Relevant links are provided:**
   - [ ] [WordPress File and Directory Structure](insert_structure_guide_link_here)
> * [ ] **Lesson creation checklist is complete:**
   - [ ] Gather any relevant links to Support, Docs, or related material
   - [ ] Description and Objectives finalized
   - [ ] Lesson created and announced to the team for Q/A review
   - [ ] Lesson submitted and published to WPTV
   - [ ] Lesson transferred to YouTube
   - [ ] Lesson reviewed and ready to publish
   - [ ] Lesson published to Learn.WordPress.org

# Feedback:
The learning objective is clear, focusing on describing the files and directories constituting a WordPress installation. Consider providing a link to a comprehensive guide on the WordPress File and Directory Structure for additional reference.

Once the comment has been published, go through and check off items as you review the comment. Leave an additional comment on the GitHub issue with any additional feedback you have.

And you’re done! Thank you for contributing to the Training Team. If you have any more thoughts or questions, feel free to share!

**Comment by nftushar** [comment]
# Learning Objective Review Checklist
Please tick all items you've confirmed:
> * [ ] **Learning objective is clear:** Describe the files and directories that make up a WordPress installation.
> * [ ] **Relevant links are provided:**
   - [ ] [WordPress File and Directory Structure](https://developer.wordpress.org/themes/basics/template-hierarchy/)
> * [ ] **Lesson creation checklist is complete:**
   - [ ] Gather any relevant links to Support, Docs, or related material
   - [ ] Description and Objectives finalized
   - [ ] Lesson created and announced to the team for Q/A review
   - [ ] Lesson submitted and published to WPTV
   - [ ] Lesson transferred to YouTube
   - [ ] Lesson reviewed and ready to publish
   - [ ] Lesson published to Learn.WordPress.org

# Feedback:
The learning objective is clear, focusing on describing the files and directories constituting a WordPress installation. Consider providing a link to a comprehensive guide on the WordPress File and Directory Structure for additional reference.

Once the comment has been published, go through and check off items as you review the comment. Leave an additional comment on the GitHub issue with any additional feedback you have.

And you’re done! Thank you for contributing to the Training Team. If you have any more thoughts or questions, feel free to share!

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/the-wordpress-file-structure/

**Comment by jonathanbossenger** [comment]
## YouTube Chapters

(0:00) Introduction 
(0:29) The root directory
(0:35) Static files 
(1:53) PHP files that control a WordPress request 
(3:00) Additional PHP files in the root directory 
(5:32) Root directories
