### ISSUE TITLE
The WordPress database

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1987]
# Learning Objective

Identify and describe the different tables in the WordPress database, and the core functions to interact with these tables.

# Relevant Links

- https://learn.wordpress.org/tutorial/the-wordpress-database/

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for Q/A review
- [x] Lesson submitted and published to WPTV
- [x] Lesson transferred to YouTube
- [x] Lesson reviewed and ready to publish
- [x] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/how-wordpress-works/wordpress-database.md

Video for review:

https://github.com/WordPress/Learn/assets/180629/008d158e-fd86-466e-9245-b100b090aee7

**Comment by cynthianorman** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.

**Comment by nftushar** [comment]
# Learning Objective Review Checklist
Please tick all items you've confirmed:
> * [ ] **Learning objective is clear:** Identify and describe the different tables in the WordPress database, and the core functions to interact with these tables.
> * [ ] **Relevant links are provided:**
   - [ ] [WordPress Database Tutorial](https://learn.wordpress.org/tutorial/the-wordpress-database/)
> * [ ] **Lesson creation checklist is complete:**
   - [ ] Gather any relevant links to Support, Docs, or related material
   - [ ] Description and Objectives finalized
   - [ ] Lesson created and announced to the team for Q/A review
   - [ ] Lesson submitted and published to WPTV
   - [ ] Lesson transferred to YouTube
   - [ ] Lesson reviewed and ready to publish
   - [ ] Lesson published to Learn.WordPress.org

# Feedback:
The learning objective is clear, focusing on identifying and describing different tables in the WordPress database, along with core functions for interaction. The provided link to the WordPress Database Tutorial is relevant and adds value to the objective.

Once the comment has been published, go through and check off items as you review the comment. Leave an additional comment on the GitHub issue with any additional feedback you have.

And you’re done! Thank you for contributing to the Training Team. If you have any more thoughts or questions, feel free to share!

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [ ] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by ironnysh** [comment]
Hi @jonathanbossenger, 
Very nice tutorial, as always :-)

I have one suggestion and a few "bugs" I spotted while watching:
- It might be worth mentioning that the database may include other non-`wp_` tables created by plugins. It will ensure people don't get alarmed about potential security risks.

1. At 1:29 and again at 3:59, 4:05, and 4:27, the lesson presentation briefly pops on the screen when you move between browser tabs.
2. At 5:40, you click the `wp_term_taxonomy` table, then there's silence, and then you click it again at 5:45 and continue talking.
3. Both the [WordPress Database tutorial](https://learn.wordpress.org/tutorial/the-wordpress-database/) and the [script](https://github.com/jonathanbossenger/wp-content/blob/bfab1cd779c2ab48c40e6303f9f7b6dbaacd24c8/developer-learning-pathway/how-wordpress-works/wordpress-database.md?plain=1#L117) include a mention of the _Links Manager plugin_, but it's missing from the narration. Then again, this plugin [was last updated](https://wordpress.org/plugins/link-manager/) 11 years ago, so it's probably better to find an alternative :-)
4. The tutorial ends a bit abruptly, without a summary or even parting words.

**Comment by jonathanbossenger** [comment]
Hey @ironnysh, thanks for the feedback.

> It might be worth mentioning that the database may include other non-wp_ tables created by plugins. It will ensure people don't get alarmed about potential security risks.

The specific learning outcome for this video is to focus on the default schema in a WordPress database. There is a planned module in one of the future developer pathways that deals with custom tables, and prefixes.

> At 1:29 and again at 3:59, 4:05, and 4:27, the lesson presentation briefly pops on the screen when you move between browser tabs.

Yes, this is annoying, because I'm experiencing this [on another video](https://github.com/WordPress/Learn/issues/1985#issuecomment-1884962769) where the content is correct in my video editing software, but not in the export. I'll hopefully have a fix for this soon

> Both the [WordPress Database tutorial](https://learn.wordpress.org/tutorial/the-wordpress-database/) and the [script](https://github.com/jonathanbossenger/wp-content/blob/bfab1cd779c2ab48c40e6303f9f7b6dbaacd24c8/developer-learning-pathway/how-wordpress-works/wordpress-database.md?plain=1#L117) include a mention of the Links Manager plugin, but it's missing from the narration. Then again, this plugin [was last updated](https://wordpress.org/plugins/link-manager/) 11 years ago, so it's probably better to find an alternative :-)

This is a tough one, because the feature was removed from WordPress, but the table still exists in the database. So I didn't want to dive to deep into the ins and outs of the functionality. While the plugin has not been updated since it was removed from WordPress, it still works as expected, and uses the table. 

> The tutorial ends a bit abruptly, without a summary or even parting words.

Thanks, I think that got lost somehow. When I sort out the weird video issues I'll record a closing.

**Comment by ironnysh** [comment]
Hi @jonathanbossenger, thanks for the explanations--appreciate it.

> While the plugin has not been updated since it was removed from WordPress, it still works as expected

The immortal one-liner!😄

**Comment by jonathanbossenger** [comment]
Updated video. The new video was just too large for GitHub, so uploading to my CloudUp account.

https://cloudup.com/c1yVwsMYqe2

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/the-wordpress-database/

**Comment by jonathanbossenger** [comment]
## YouTube chapters

(0:00) Introduction
(0:35) Interacting with your WordPress database
(1:36) Database Tables
(8:12) Conclusion
