### ISSUE TITLE
Admin page request

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1989]
# Learning Objective

Describe a typical WordPress admin request and step through the code execution

# Relevant Links

# Lesson creation checklist

- [ ] Gather any relevant links to Support, Docs, or related material
- [ ] Description and Objectives finalized
- [ ] Lesson created and announced to the team for Q/A review
- [ ] Lesson submitted and published to WPTV
- [ ] Lesson transferred to YouTube
- [ ] Lesson reviewed and ready to publish
- [ ] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/how-wordpress-works/admin-request.md

Video for review

https://github.com/WordPress/Learn/assets/180629/e59d038c-ab67-4a6d-9dce-1d676f88474b

**Comment by cynthianorman** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.

**Comment by nftushar** [comment]
# Learning Objective Review Checklist 🌐💻
Please tick all items you've confirmed:
> * [ ] **Learning objective is illuminating:** Unveil the inner workings of a typical WordPress admin request, guiding through the intricate steps of code execution.
> * [ ] **Relevant links are provided as beacons:**
   - [ ] [Demystifying WordPress Admin Requests][(https://example.com/admin-request-guide](https://wordpress.org/support/topic/plugin-wrongly-makes-a-request-to-wp-admin/))
> * [ ] **Lesson creation checklist is a roadmap to success:**
   - [ ] Navigate through relevant links, creating a compass to Support, Docs, or related material
   - [ ] Sculpt an enticing Description and Objectives, beckoning learners into the WordPress admin realm
   - [ ] Announce the Lesson to the team, inviting their scrutiny in the grand Q/A review
   - [ ] Present the Lesson on the grand stage of WPTV, a theater for WordPress virtuosos
   - [ ] Transport the Lesson to the vastness of YouTube, where knowledge echoes
   - [ ] Polish the Lesson until it gleams, ready to be showcased on the prestigious Learn.WordPress.org

# Feedback 🚀🧑‍💻:
This learning objective is a beacon for WordPress explorers, providing a detailed map to navigate through the complex landscape of admin requests. To enhance the educational journey, consider incorporating real-life scenarios or interactive elements to engage learners actively.

For those eager to embark on this adventure, [Demystifying WordPress Admin Requests](https://wordpress.org/support/topic/plugin-wrongly-makes-a-request-to-wp-admin/) is your treasure map, leading to a trove of insights.

Once the comment has been published, guide your cursor to gracefully check off each item. Leave an additional comment on the GitHub issue, sharing any insights or suggestions to make this lesson an enlightening experience.

And there you have it! Thank you for being a guiding star in the Training Team. If you have more ideas or questions, feel free to share! 🚀📚

**Comment by Andenga** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/admin-page-request/

**Comment by jonathanbossenger** [comment]
## YouTube chapters

(0:00) Introduction
(0:15) What is an admin request?
