### ISSUE TITLE
Standardize filter layouts for workshops and lesson plans

### ISSUE THREAD

**Issue by varlese** [WordPress/Learn#199]
Inspired by my request for a [UX review/feedback by the Design team](https://make.wordpress.org/design/2021/02/03/review-feedback-request-ux-for-learn-wordpress-org/), I'd like to suggest that we change/unify the filters layout for both workshops and lesson plans.

Currently, the filter appears across the top of the page for workshops:
<img width="984" alt="Screen Shot 2021-03-19 at 14 32 39" src="https://user-images.githubusercontent.com/1361760/111827171-fa09a800-88bf-11eb-94a1-9874c9fd3d6e.png">

And, for lesson plans, it appears on the right side of the page in a sidebar:
<img width="986" alt="Screen Shot 2021-03-19 at 14 34 09" src="https://user-images.githubusercontent.com/1361760/111827362-2fae9100-88c0-11eb-902e-bf43b024b9d5.png">

To create a more holistic experience across the site for visitors, can we have:
- both filters appear in a sidebar on the left side of the page? (This is [based on Kelly's feedback](https://make.wordpress.org/design/2021/02/03/review-feedback-request-ux-for-learn-wordpress-org/#comment-26254).)
- both filters use checkboxes to allow visitors to easily compare/contrast? I think the big exception here would likely be for languages and captions, since I think we can expect those to get a bit unwieldy in the future :D

**Comment by hlashbrooke** [comment]
With the needs assessment recently completed, we're going to be looking into some big changes for the frontend of Learn, so I'm going to close this issue and we'll incorporate this need into the other frontend updates.
