### ISSUE TITLE
Front-end page request

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#1990]
# Learning Objective

Describe a typical WordPress front end request and step through the code execution

# Relevant Links

# Lesson creation checklist

- [ ] Gather any relevant links to Support, Docs, or related material
- [ ] Description and Objectives finalized
- [ ] Lesson created and announced to the team for Q/A review
- [ ] Lesson submitted and published to WPTV
- [ ] Lesson transferred to YouTube
- [ ] Lesson reviewed and ready to publish
- [ ] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/how-wordpress-works/front-end-request.md

**Comment by jonathanbossenger** [comment]
Video for review: 

https://github.com/WordPress/Learn/assets/180629/e722fc19-a009-4471-be5b-ca51750b8a0b

**Comment by cynthianorman** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.

Consider highlighting or indicating where you're at in your code walkthroughs in future videos so our eye can follow a bit better

**Comment by nftushar** [comment]
# Learning Objective Review Checklist 🚀✨
Please tick all items you've confirmed:
> * [ ] **Learning objective is crystal clear:** Dive into the intricate workings of a typical WordPress front-end request and gracefully navigate the code execution dance.
> * [ ] **Relevant links are elegantly provided:**
   - [ ] [Mastering the Symphony of WordPress Core](insert_core_understanding_link_here)
> * [ ] **Lesson creation checklist is a masterpiece:**
   - [ ] Artfully gather links to Support, Docs, or related material
   - [ ] Sculpt the Description and Objectives into a work of educational art
   - [ ] Unveil the Lesson to the team for a mesmerizing Q/A review
   - [ ] Premiere the Lesson on WPTV, a stage fit for WordPress brilliance
   - [ ] Transfer the Lesson's essence to YouTube, reaching the far corners of the digital realm
   - [ ] Polish the Lesson until it gleams, ready to be published on the prestigious Learn.WordPress.org

# Feedback 🎨💡:
The learning objective invites you on a journey to unravel the magic behind a WordPress front-end request. To enhance this enchanting experience, consider weaving in real-world examples or captivating visuals that dance with the code.

For those seeking further wisdom, explore the profound depths of [Understanding WordPress Core](insert_core_understanding_link_here) – a treasure trove of knowledge.

Once the comment has been published, gracefully check off each item as you review the comment. Leave an additional comment on the GitHub issue, sharing any creative strokes or suggestions you may have.

And voilà! Thank you for crafting a piece of art for the Training Team. If you have any more visions or questions, feel free to share! 🎭📚

**Comment by Andenga** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by jonathanbossenger** [comment]
> Consider highlighting or indicating where you're at in your code walkthroughs in future videos so our eye can follow a bit better

That's a good point. I'll see if I can add this to the video before the learning pathway is published.

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/front-end-page-request/

**Comment by jonathanbossenger** [comment]
## YouTube Chapters

(0:00) Introduction
(0:12) What is a front-end request?
(0:33) A note on require, require_once, include, include_once
(0:57) wp-blog-header.php
(1:03) wp-load.php
(1:43) wp-config.php
(1:57) wp-settings.php
(4:45) wp() function
(6:53) template-loader.php
