### ISSUE TITLE
Meeting Agenda November 21, 2023

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#1991]
Training Team meetings start at 07:00 UTC weekly on Tuesdays. Anyone is welcome to contribute to the meeting by commenting in Slack threads throughout the week. Meeting notes will be published at the end of the week to also incoporate these asynchronous conversations.

_This week’s meeting will be hosted by @webtechpooja ._

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- November 21 – [Sumit Singh](https://profiles.wordpress.org/sumitsingh/)
- November 28 – Need Volunteer
- December 5 – Need Volunteer
- December 12 – Need Volunteer

**2. Looking for feedback**

- [Matrix](https://make.wordpress.org/chat/matrix/) set up and testing esp. for accessibility ([See slack thread](https://wordpress.slack.com/archives/C03B11FA16D/p1700039527817559))
- [Proposal: Hosting Learn videos on YouTube](https://make.wordpress.org/training/2023/11/17/proposal-hosting-learn-videos-on-youtube/)

**3. Looking for volunteers**

- Audit [Training team handbook](https://make.wordpress.org/training/handbook/) 
- Call for Guides in Guide Program - The [Guide Program](https://make.wordpress.org/training/handbook/guide-program/) is seeking experienced contributors to help guide new Training Team members in their contribution journey. If you are an experienced Training Team contributor and would like to be a Guide for new contributors, please [complete the application form](https://forms.gle/dTUxVu798DwvPzRn8)!
- Learning Pathway Content Creators
  - We need help creating lessons for the Designer, User, and Developer pathways.
  
**4. Updates from last week's dev-squad triage session**

The following PRs were triaged:
- #1936
- #1950 

The following bugs were triaged:
- #1952 

We also discussed options to improve the dev-squad triage sessions, which resulted in this post: [What's next for dev-squad](https://github.com/WordPress/Learn/pull/1936). 

We would like to invite anyone interested in joining the team and helping to improve the process to comment on that post and join the next session this Thursday at 07:00 UTC in the #meta-learn channel. 

**5. Other news**

- [Vote for Training Team Rep 2024](https://make.wordpress.org/training/2023/11/17/vote-for-training-team-rep-2024/)
- Training Team Badge requirements have been clarified in [our handbook page](https://make.wordpress.org/training/handbook/about/team-profile-badges/#training-team-badge)
- [Training Team 2023 Year-End Review](https://make.wordpress.org/training/2023/11/20/training-team-2023-year-end-review/)
- [What’s next for Dev-Squad?](https://make.wordpress.org/training/2023/11/20/whats-next-for-dev-squad/)
- Badge awarded - [Nazrul Islam Nayan](https://profiles.wordpress.org/nayanchamp7/), [Sancastiza](https://profiles.wordpress.org/sancastiza/), [Priyanshii Vijayvargiya](https://profiles.wordpress.org/priyanshii5/), [megane9988](https://profiles.wordpress.org/megane9988/), [Shail Mehta](https://profiles.wordpress.org/shailu25/)
- Team reps AFK
  - Destiny: Dec 25th — Jan 2nd 2024
  - Pooja - Nov 27 - Nov 29 
  - Ben: Dec 23rd - Jan 5th 2024
 
## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - [Tutorial - Re-creating Techcrunch in 30 mins](https://github.com/WordPress/Learn/issues/1891)
  - [Tutorial - Choosing a domain name and hosting service ](https://github.com/WordPress/Learn/issues/1963)
  - [Tutorial - Introduction to WordPress](https://github.com/WordPress/Learn/issues/1962)
  - [Tutorial - Building a secure WordPress foundation](https://github.com/WordPress/Learn/issues/1981)
  
- **Translated Content**
  - We're looking for Indonesian, Khmer, and German translation reviewers. ([Link to content needing a Translation Reviewer](https://github.com/orgs/WordPress/projects/104/views/10).)

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) -- [see latest update](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4037)
- [GitHub project](https://make.wordpress.org/training/2023/09/27/looking-for-feedback-updates-to-github-issue-templates-and-labels/) -  A lot of the planing work is done, and we're now ready to start switching things around. These are the action items that remain:
  - Implement new GitHub labels
  - Implement and document GitHub automations
  - Update Handbook pages for current structure and announce with the team in a P2 post
If you have availability over the next two weeks and would like to help, please comment here and Ben will share more details.

## 5. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by courtney-pk** [comment]
Could we please add a call for more Guides in the Guide Program? Something like:
> The [Guide Program](https://make.wordpress.org/training/handbook/guide-program/) is seeking experienced contributors to help guide new Training Team members in their contribution journey. If you are an experienced Training Team contributor and would like to be a Guide for new contributors, please [complete the application form](https://forms.gle/dTUxVu798DwvPzRn8)!

**Comment by webtechpooja** [comment]
@jonathanbossenger Could you share an update from last week's dev-squad triage session, please? 🙇‍♂️

**Comment by kaitohm** [comment]
I'd like to give an update for the [GitHub project](https://make.wordpress.org/training/2023/09/27/looking-for-feedback-updates-to-github-issue-templates-and-labels/) too. Could we share something like this?

> A lot of the planing work is done, and we're now ready to start switching things around. These are the action items that remain:
> - Implement new GitHub labels
> - Implement and document GitHub automations
> - Update Handbook pages for current structure and announce with the team in a P2 post
> 
> If you have availability over the next two weeks and would like to help, please comment here and Ben will share more details.

**Comment by Piyopiyo-Kitsune** [comment]
I added @jonathanbossenger 's [What’s next for Dev-Squad?](https://make.wordpress.org/training/2023/11/20/whats-next-for-dev-squad/) in the News section.
- Getting the handbook pages updated is the highest priority
- Getting 1 extra host for the meetings (would love up to 5)

**Comment by webtechpooja** [comment]
Recap post link - https://make.wordpress.org/training/2023/11/24/training-team-meeting-recap-21th-november-2023/

**Comment by devmuhib009** [comment]
I want to work as note taker for November 28.

**Comment by kaitohm** [comment]
Thanks you, @devmuhib009 🙌 I'll put your name down for this week ✅
