### ISSUE TITLE
Bangla translation for 7 Tips to improve website security

### ISSUE THREAD

**Issue by nazsakib** [WordPress/Learn#1999]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/7-tips-to-improve-website-security/#transcript
- Link to original content GitHub issue (optional): 
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @devmuhib009 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by nazsakib** [comment]
Please check. Here's the translated document file link:
https://docs.google.com/document/d/1_-wiMSMQxn8TTYpciVBIw-0n-0iVHzcYGke_5HugHHQ/edit?usp=sharing

**Comment by devmuhib009** [comment]
I will review the content soon and update here.

**Comment by nazsakib** [comment]
Thank you, @devmuhib009. I'm adding you as a reviewer.

**Comment by kaitohm** [comment]
@nazsakib I've sent you an invite to become a `Author` on the Learn WordPress website. Please let me know once you've accepted this, so we can set you up to transfer the content to Learn WordPress once the review has completed.

**Comment by nazsakib** [comment]
Thank you! @bsanevans
I've accepted the invitation you sent me.

**Comment by devmuhib009** [comment]
> দঢ়, ব্যপকভাবে, ক্রে, ইনষ্টক (Spelling mistakes or typo’s)

দৃঢ়, ব্যাপকভাবে, করে ,ইনস্টল, 

> দিন দিন অত্যাধুনিক হয়ে উঠছে সাইবার হুমকি

দিন দিন সাইবার হুমকি অত্যাধুনিক হয়ে উঠছে 

>ব্যবহারকারীর একাউন্ট পর্যালোচনা এবং পরিচালনা করা।

ব্যবহারকারীদের একাউন্টগুলো পর্যালোচনা এবং পরিচালনা করা।

>নির্ভরযোগ্য একটি প্লাগইন এবং থিম ইনষ্টল করা।

একটি নির্ভরযোগ্য প্লাগইন এবং থিম ইনষ্টল করা।

>অনুধাবনকৃত প্রশ্নগুলো 

সম্পূরক প্রশ্ন

>প্রথমটি, দ্বিতীয়টি, তৃতীয়টি, চতুর্থটি ... 

প্রথমত, দ্বিতীয়ত, তৃতীয়ত, চতুর্থত ... 

>প্রথমটি, একটি পাসওয়ার্ড ম্যানেজার এবং সুরক্ষিত পাসওয়ার্ডগুলো ব্যবহার করা লগইন করার জন্যে। 

প্রথমত, লগইন করার জন্যে একটি পাসওয়ার্ড ম্যানেজার এবং সুরক্ষিত পাসওয়ার্ডগুলো ব্যবহার করা। 

> পাসওয়ার্ড ম্যানেজারগুলোর মধ্যে 1Password এবং Bitwarden ঘেঁটে দেখা যেতে পারে। 

 পাসওয়ার্ড ম্যানেজারগুলোর মধ্যে 1Password এবং Bitwarden ঘেঁটে দেখা মূল্যবান হয়ে উঠতে পারে।

> নিরাপত্তা ব্যর্থতার জন্য সবচেয়ে সাধারণ ক্ষেত্রগুলির মধ্যে একটি হল, দুর্ভাগ্যবশত, মানুষ নিজেই।

নিরাপত্তা ব্যর্থতার জন্য সবচেয়ে সাধারণ বিষয়গুলোর মধ্যে একটি হল, দুর্ভাগ্যজনকভাবে, মানুষ নিজেই।

>পাসওয়ার্ডগুলো কমপক্ষে ১০ থেকে ১২ ক্যারেক্টারের মধ্যে এবং এতে সংখ্যা এবং চিহ্ন থাকে।

পাসওয়ার্ডগুলো কমপক্ষে ১০ থেকে ১২ ক্যারেক্টারের মধ্যে হয় এবং এতে নাম্বার এবং ক্যারেক্টার থাকে।

>WP 2FA দুই-ধাপ যাচাইকরণ

WP 2FA two-factor authenticator

>ব্যবহারকারীদের ফিডব্যাক এবং পর্যালোচনা চেক করুন

ব্যবহারকারীদের ফিডব্যাক এবং রিভিউ চেক করুন

>এটি ওয়ার্ডপ্রেসের সর্বশেষ সংস্করণের সাথে সামঞ্জস্যপূর্ণ কিনা তা দুইবার চেক করুন।

এটি ওয়ার্ডপ্রেসের সর্বশেষ সংস্করণের সাথে সামঞ্জস্যপূর্ণ কিনা তা পুনঃনিরীক্ষণ করে নিন।

>যেগুলো আপনার সাইটকে স্ক্যান করবে কোনো রিপোর্টেড দুর্বলতার জন্যে।

যেগুলো আপনার সাইটকে স্ক্যান করবে যে কোনো রিপোর্টেড দুর্বলতার জন্যে।

>আরো টিউটোরিয়াল এবং প্রশিক্ষন ম্যাটেরিয়ালসের জন্যে Learn WordPress দেখুন।

আরো টিউটোরিয়াল এবং প্রশিক্ষন ম্যাটেরিয়ালসের জন্যে লার্ন ওয়ার্ডপ্রেসে ঘুরে দেখতে পারেন।

**Comment by nazsakib** [comment]
I just updated all of these typos you've found, @devmuhib009 in this translation and other twos as well.

**Comment by devmuhib009** [comment]
Awesome! I just rechecked the doc and it's looking good. Ready for publishing.

**Comment by nazsakib** [comment]
Hi @bsanevans, The reviewed translation is now ready for publication. I seek your guidance to proceed further. Your assistance is greatly appreciated.

**Comment by kaitohm** [comment]
Thanks both @nazsakib and @devmuhib009 for working as a team to translate and review Bangla content 🎉 (See also #2004 and #2009 )

@nazsakib I've added you to this draft post on Learn WordPress - https://learn.wordpress.org/wp-admin/post.php?post=56164&action=edit

Please continue from [step 5 listed in the team handbook](https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video). Feel free to ping Faculty members in the #training Slack channel for any assistance.

**Comment by nazsakib** [comment]
I've completed all the steps, from translating the draft post to uploading the subtitle file. @bsanevans

**Comment by kaitohm** [comment]
Wonderful! This content has now bee published: https://learn.wordpress.org/tutorial/bn-7-tips-to-improve-website-security/

Thank you for your contribution! Once you've translated a total of three pieces of content, you can apply for a Training Contributor Badge. Make sure to [check out our handbook page](https://make.wordpress.org/training/handbook/about/team-profile-badges/#training-contributor-badge) about that 😉

**Comment by devmuhib009** [comment]
> Wonderful! This content has now bee published: https://learn.wordpress.org/tutorial/bn-7-tips-to-improve-website-security/
> 
> Thank you for your contribution! Once you've translated a total of three pieces of content, you can apply for a Training Contributor Badge. Make sure to [check out our handbook page](https://make.wordpress.org/training/handbook/about/team-profile-badges/#training-contributor-badge) about that 😉

Just curious to know, as we are uploading subtitle to WordPress.tv, can we apply for WordPress Tv Contributor badge as well? 😊

**Comment by kaitohm** [comment]
Yes, you can apply got a WordPress.tv badge 👍 However, because those badges are maintained by the WordPress.tv team, you'll want to reach out in the [#wptv Slack channel](https://wordpress.slack.com/archives/C037W5MBT) to request it 🙂

**Comment by nazsakib** [comment]
Thank You so much @bsanevans
