### ISSUE TITLE
Creating a block child theme

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2000]
# Topic Description
Intermediate lesson: Creating a block child theme from a block theme. 

In this lesson, we will be describing and creating a block child theme for the new default Twenty Twenty-Four block theme.

The learning outcomes are to:
1. Understand the benefits of having a block child theme
2. Differentiate between a block theme and block child theme
3. Use the Create Block Theme plugin to create a basic, but fully functional block child theme from a block theme

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- https://learn.wordpress.org/lesson-plan/create-a-basic-child-theme-for-block-themes
- https://developer.wordpress.org/themes/advanced-topics/child-themes/#what-is-a-child-theme
- https://developer.wordpress.org/themes/core-concepts/main-stylesheet/#child-theme-header-fields

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Lesson Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [ ] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [ ] Tutorial published on WPTV
- [ ] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [ ] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [ ] Tutorial post reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

**Comment by cynthianorman** [comment]
I'd like to create this lesson for the User Learning Pathway

**Comment by cynthianorman** [comment]
Related Resource
- https://learn.wordpress.org/lesson-plan/create-a-basic-child-theme-for-block-themes
- https://developer.wordpress.org/themes/advanced-topics/child-themes/#what-is-a-child-theme
- https://developer.wordpress.org/themes/core-concepts/main-stylesheet/#child-theme-header-fields

**Comment by cynthianorman** [comment]
> # Tutorial Development Checklist
> * [x]  Vetted by instructional designers for content idea
> * [x]  Provide feedback of the idea
> * [x]  Gather links to Support and Developer Docs
> * [x]  Review any related material on Learn

**Comment by annezazu** [comment]
As noted on the prior issue, per usual, Carolina has an excellent resource on the topic: https://fullsiteediting.com/lessons/child-themes/

**Comment by cynthianorman** [comment]
https://github.com/WordPress/Learn/assets/12952283/8ba18361-bff7-49ca-89d0-6f47e5d4daa3

**Comment by askdesign** [comment]
Hi Cynthia,
Your explanations are so good!
Parts that I especially like:
-  3:41 - your description of the **theme.json** file as the configuration file that now houses the items previously placed in the **functions.php** file.
- 4:02 - child theme inherits parent theme's functionality, and also extends/overrides its parent theme.

A couple of minor suggestions:
- 3:08 - You mention the minimum files required and show the _FrostChild_ folder contents. It would be good to say that the minimum files required for a **child theme**...
- 6:17 - "... this will download the file for you" - I suggest being more specific right here: "compressed .zip archive of all the child theme files"

On another note, the video was a bit glitchy for me. There were spots where it stopped and brought me back to the beginning. I'm not sure if it's on my end, or the video itself.

**Comment by cynthianorman** [comment]
@askdesign thank you so much for your review and awesome suggestions! I will implement for sure. As for the video being glitchy I wonder if you get the same problem when you download the video first. I've had issues with watching videos on GitHub as well.

**Comment by westnz** [comment]
Hey @cynthianorman Congratulations on recording this lesson!!  I cannot seem to watch the video. It continues to jump back to the start of the video after a minute or more. I can't download it either.  I was wondering if you could share another link to the video. Many thanks

**Comment by cynthianorman** [comment]
Hi @westnz 
I've uploaded it as an unlisted video on my channel. Thanks for your help!
https://youtu.be/CmnXmHgTvE0

**Comment by westnz** [comment]
Fantastic job Cynthia!

[x ] Learning outcomes/objectives are clear.
[x ] The speed of demonstrations is easy to follow.
[x ] Technical concepts introduced in the content are accurate.
[x ] The narration audio matches what is shown visually.
[x ] Spelling and grammar are correct.
[x ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Hi @cynthianorman, that’s a lovely tutorial! 

I liked the practical use cases and explanations of why you would _still_ want to create a child theme.

One thing that should probably be rephrased, though, is the comment about `theme.json` as a “replacement” of `functions.php` (at around 3:50):
> “items that were previously placed within functions.php in a classic theme, will now be found here”

That’s only partially true, so it’s safer to go with something like, “**some** of the items…”, or “**style-related** items that…”.

**Comment by cynthianorman** [comment]
@ironnysh thanks so much for your review! 

I know some items will still have to be in functions.php but I'm thinking I should reserve digging into the details of theme.json for the planned theme.json developer lessons within the developer learning pathways. This tutorial is one that I believe has some details to help us navigate WordPress settings using theme.json https://learn.wordpress.org/tutorial/introduction-to-theme-json. 

Hopefully we'll be able to navigate the nuances together.

**Comment by ironnysh** [comment]
Hi @cynthianorman, you're right about that!
What I meant was that the current phrasing suggests _everything_ now lives in `theme.json`: Hooks, filters, functions, and all the logic and magic :-)

**Comment by cynthianorman** [comment]
@ironnysh I'll definitely be changing that wording in this video. Thanks again for your help!

**Comment by westnz** [comment]
Published: https://www.youtube.com/watch?v=m9A3HZ2cuZM
