### ISSUE TITLE
Learning Pathway: Intermediate User

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2002]
# Intermediate
See full User pathway [outlined in this document](https://docs.google.com/spreadsheets/d/1uOm1I62zZLoZGm1rMI2_Ihvul_Z8hwbCExFirr_zhjI/edit#gid=0).

_This course has 37 lessons over 10 modules._

## Module 1

Objective: Changing host / domain

### Lessons
- [x] #1187 
- [x] #2228

## Module 2

Objective: Learn the fundamentals of user management when collaborating with others to create a WordPress website

### Lessons
- [x] #695 

## Module 3

Objective: Block Theme Customization – as an intermediate-level user, understand patterns, including header and footer patterns, and how they affect the remainder of the website. 

### Lessons
- [x] #676 
- [x] #1340 
- [x] #2255 
- [x] #1278
- [x] #888
- [x] #2287
- [x] #827 
- [x] #1266

## Module 4

Objective: Content Creation 

### Lessons
- [x] #524 
- [x] #508
- [x] #1192
- [x] #1419 
- [x] #913 
- [x] #2286
- [x] #2288
- [x] #1489 
- [x] #1776 
- [x] #445

## Module 5

Objective: SEO & Accessibility 

### Lessons
- [x] #2291
- [x] #2370 
- [x] #2201 

## Module 6

Objective: Using WordPress Tools

### Lessons
- [x] #960 
- [x] #1036 

## Module 7

Objective: Settings

### Lessons
- [x] #634 
- [x] #2256
- [x] #2257
- [x] #2258
- [x] #970 
- [x] #393 
- [x] #394 

## Module 8

Objective: Steps to improve your website's performance, such as, optimizing images.

### Lessons
- [x] #2294
- [x] #855 

## Module 9

Objective: Domain Management

### Lessons
- [x] #2293

## Module 10

Objective: Website Security

### Lessons
- [x] #2296

**Comment by cynthianorman** [comment]
@westnz I can assist with developing this curriculum

**Comment by westnz** [comment]
Thanks @cynthianorman, I will send you a message.

**Comment by westnz** [comment]
//published
