### ISSUE TITLE
Bangla translation for Managing Comments

### ISSUE THREAD

**Issue by nazsakib** [WordPress/Learn#2004]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/managing-comments/
- Link to original content GitHub issue (optional): 
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @devmuhib009 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by nazsakib** [comment]
Here's the translated version doc file link: 
https://docs.google.com/document/d/1Q_eQk-DBpzs1jJi2fNj31ilQ2jNnM3kKFxoF4It9yBE/edit?usp=sharing

**Comment by kaitohm** [comment]
@devmuhib009 Would you be available to review this translation, too?

**Comment by devmuhib009** [comment]
Ok, I will review the content too.

**Comment by nazsakib** [comment]
Thanks again, @devmuhib009, for reviewing this translation too! I'm adding you as a reviewer.

**Comment by devmuhib009** [comment]
> উদাহারণ, কেও, নিয়ন্ত্রন, এখানই  (Fix Typo's)

 উদাহরণ, কেউ, নিয়ন্ত্রণ,  এখানেই

>দুজন এডমিন এর জায়গা চিহ্নিত করা যেখান থেকে মন্তব্যগুলো নিয়ন্ত্রণ করা যেতে পারে।

দুটি এডমিন অবস্থান চিহ্নিত করা যেখান থেকে মন্তব্যগুলো নিয়ন্ত্রণ করা যেতে পারে।

>মন্তব্য ব্যবস্থা কি আপনার সাইট এবং পরিচালনা করার ষ্টাইলের সাথে উপযুক্ত?

মন্তব্যগুলি কি আপনার সাইট এবং পরিচালনা শৈলীর সাথে সামঞ্জস্যপূর্ণ?

>কোন দুটি জায়গা থেকে আপনি আপনার মন্তব্যের অবস্থা আপডেট করতে পারেন?

কোন দুটি জায়গা থেকে আপনি আপনার মন্তব্যের অবস্থা পরিবর্তন করতে পারেন?

>সম্ভবত আপনি আগে সকল ধরণের ওয়েব সাইটে মন্তব্য দেখেছেন।

সম্ভবত আপনি আগে বিভিন্ন ধরনের ওয়েব সাইটের মন্তব্যগুলো দেখেছেন।

>নির্দ্বিধায় আপনি ভিডিওটি থামিয়ে থামিয়ে নিজে চেষ্টা করে দেখতে পারেন।

নির্দ্বিধায় আপনি ভিডিওটি থামিয়ে নিজে চেষ্টা করে দেখতে পারেন।

>ডিফল্টভাবে, দর্শকদের কাছে উপায় রয়েছে তাদের মন্তব্যের সাথে নাম, ইমেইল এবং একটি ব্যক্তিগত ওয়েবসাইট রেখে যাওয়া।

গতানুগতিকভাবে, মন্তব্যের সাথে তাদের নাম, ইমেইল এবং একটি ব্যক্তিগত ওয়েবসাইট রেখে যাওয়ার উপায় দর্শকদের কাছে রয়েছে। 

>চালু রাখার ভালো এবং খারাপ দিক রয়েছে

এগুলো চালু রাখার ভালো এবং খারাপ দিক রয়েছে

>অথবা তারা নতুন রেসিপি কখন চেষ্টা করবে।

অথবা তারা একটি নতুন রেসিপি কখন চেষ্টা করবে।

**Comment by nazsakib** [comment]
I fixed all of these in my doc file!

**Comment by devmuhib009** [comment]
It's now ready for publish.

**Comment by kaitohm** [comment]
@nazsakib I've added you to this draft post on Learn WordPress - https://learn.wordpress.org/wp-admin/post.php?post=56166&action=edit

Please continue from [step 5 listed in the team handbook](https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video). Feel free to ping Faculty members in the #training Slack channel for any assistance.

**Comment by nazsakib** [comment]
Hey, @bsanevans, hope you're doing well! I've completed all the steps you've said to follow. I translated the draft post and uploaded the Bangla subtitle on WordPress.tv!

**Comment by kaitohm** [comment]
Wonderful! I've published this content here: https://learn.wordpress.org/tutorial/bn-managing-comments/

Thank you for your contribution to Learn WordPress 🎉

**Comment by nazsakib** [comment]
Thank you so much @bsanevans
