### ISSUE TITLE
Bangla Translation for Image Optimization

### ISSUE THREAD

**Issue by nazsakib** [WordPress/Learn#2009]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/image-optimization
- Link to original content GitHub issue (optional): 
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @devmuhib009 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by nazsakib** [comment]
Here's the translated doc file: https://docs.google.com/document/d/1MjVyZp7XI0QG2CgbxW0o0g6SBLAhbcHSx13am2CSejk/edit?usp=sharing

I need a reviewer for this translation.

**Comment by devmuhib009** [comment]
I will be happy to translate this one as well.

**Comment by nazsakib** [comment]
Thanks, @devmuhib009 bhai, for your kind gesture! I'm adding you as a reviewer.

**Comment by kaitohm** [comment]
@nazsakib I've added you to this draft post on Learn WordPress - https://learn.wordpress.org/wp-admin/post.php?post=56168&action=edit

Once Muhibul has completed the translation review, please continue from step 5 listed in the team handbook. Feel free to ping Faculty members in the #training Slack channel for any assistance.

**Comment by devmuhib009** [comment]
In middle part of the translation, it seems you did not make major chances what you get from Google translation. Please recheck the translation and make it more readable. 

Here are some suggestions that for first eight paragraphs.

>কোন কোডিং দক্ষতার প্রয়োজন ছাড়াই আপনার ওয়ার্ডপ্রেস ওয়েবসাইটের কর্মক্ষমতা উন্নত করার একটি সহজ উপায় হল ছবি অপ্টিমাইজ করা!

কোন কোডিং দক্ষতা ছাড়াই আপনার ওয়ার্ডপ্রেস ওয়েবসাইটের কর্মক্ষমতা উন্নত করার একটি সহজ উপায় হল ছবি অপ্টিমাইজ করা!

>এই পাঠে, আমরা এই বিষয়ে কথা বলবঃ 

এই সেশনটিতে, আমরা এই বিষয়ে কথা বলবঃ 

>ছবি অপ্টিমাইজেশন কি এবং আমাদের এটি কেন প্রয়োজন

ছবি অপ্টিমাইজেশন কি এবং কেন এটি আমাদের প্রয়োজন

>টিপস, পদ্ধতি এবং টুলস

টিপস, পদ্ধতি সমূহ এবং টুলসগুলো

> বিকল্প টেক্সট

 বিকল্প লেখা

>এটি আদর্শ ফরম্যাট, আকার এবং ব্যবহারকারীদের এংগেইজম্যান্ট বৃদ্ধির সমাধানের জন্য উচ্চ মানের ছবি সরবরাহ করার একটা প্রক্রিয়া।

এটি আদর্শ ফরম্যাট, সাইজ এবং রেজোলিউশনের উচ্চমানের ছবি সরবরাহের মাধ্যমে ব্যবহারকারীদের এনগেইজমেন্ট বাড়ানোর একটি প্রক্রিয়া।

>এটি আরো সঠিকভাবে ছবিতে লেবেল যুক্ত করায় জড়িত যাতে অনুসন্ধান এঞ্জিনগুলো এগুলোকে ভালো করে পড়তে পারে এবং ছবির কন্টেক্সট বুঝতে পারে।

এছাড়াও এটি ছবিতে সঠিকভাবে লেবেল যুক্ত করায় জড়িত যাতে অনুসন্ধান ইঞ্জিনগুলো এগুলোকে সঠিকভাবে করে পড়তে পারে এবং ছবির কন্টেক্সট বুঝতে পারে।

>পৃষ্ঠার

পেইজের

>ডেভেলাপমেন্ট

ডেভেলপমেন্ট 

>আপ্লোড

আপলোড

>দৃষ্টি প্রতিবন্ধীদের আপনার ওয়েবসাইটের কন্টেন্ট বুঝতে সাহায্য করবে আপনার পৃষ্ঠার।

দৃষ্টি প্রতিবন্ধীদের আপনার ওয়েবসাইটের পেইজ কন্টেন্ট বুঝতে সাহায্য করবে 

>ফাইলের নাম সহ ছবি এসইও শুরু হয় এটা নোট করাও গুরুত্বপূর্ণ।

এটা নোট করা জরুরী যে ফাইলেই নাম দিয়েই ছবির এস ই ও শুরু হয়।

**Comment by nazsakib** [comment]
@devmuhib009 bhai, I just fixed all the errors you've mentioned; kindly check again when you're free!

**Comment by devmuhib009** [comment]
Looks great now. Ready for publish.

**Comment by nazsakib** [comment]
Thank @devmuhib009 bhai. Hello @bsanevans this one done with review, kindly check. I updated the draft and also uploaded the subtitle.

**Comment by kaitohm** [comment]
Subtitles have been approved, and the Tutorial has been published: https://learn.wordpress.org/tutorial/bn-image-optimization/

Thank you, Sakib and Muhibul, for your contributions 🎉

**Comment by nazsakib** [comment]
Thank you @bsanevans
