### ISSUE TITLE
Replace link on homepage to submit a topic idea

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2014]
We've updated the team's GitHub issue templates and need to update a button's link on the Learn homepage to reflect this.

Button in question: `Submit a topic idea` at the bottom of the homepage
Current link: https://github.com/WordPress/Learn/issues/new?assignees=&labels=Awaiting+Triage%2C+Needs+Subject+Matter+Expert&template=topic-idea.md&title=Topic+Idea%3A+TOPIC+TITLE
Suggeted link to update to: https://github.com/WordPress/Learn/issues/new/choose

Note, I'm suggesting we link to the general issue template list, rather than a specific template. Templates may still go through further updates, so this generalization should reduce future maintenance.

/dev

**Comment by jonathanbossenger** [comment]
This change needs to be made in the following file in the Learn theme: 

`/wp-content/themes/pub/wporg-learn-2020/template-parts/component-submit-idea-cta.php`

**Comment by jonathanbossenger** [comment]
@bsanevans noting that this has been merged, now we'll just have to wait for the next deployment.
