### ISSUE TITLE
Feedback - typo found on tutorial content

### ISSUE THREAD

**Issue by heybran** [WordPress/Learn#2016]
## Type of feedback

/content

## Description

Typo found on this tutorial: https://learn.wordpress.org/tutorial/extending-wordpress-common-security-vulnerabilities/, if you search `There are to possible CSRF vulnerabilities in this plugin.` on that page, `to` should be `two`?

**Comment by devmuhib009** [comment]
Thanks @heybran for your feedback. I just fixed the issue.
