### ISSUE TITLE
Online Workshop: Creating a one-page website

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2022]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Online Workshop
- Content title: Creating a one-page website  
- Topic description: Creating a site with one page for a service or business 
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate/Beginner

# Learning Objectives
Create a one-page site.

**Comment by SierraTR** [comment]
Looks like there is a problem with the event link on the Meetup page

I can co-host if you still need someone

**Comment by westnz** [comment]
Hey Tracy!  Thank you very much. I have added you as the co-host. Can you please check if the event link issue is sorted?

**Comment by SierraTR** [comment]
Yes, the link is working and showing to those who register.

I'll see you then!

**Comment by westnz** [comment]
Recording: https://wordpress.tv/2023/12/04/wes-theron-creating-a-one-page-website/
