### ISSUE TITLE
Feedback - Meetup Organizer Training quizzes contain questions that are numbered twice.

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2027]
## Type of feedback

/content

## Description
The Meetup Organizer Training quizzes contain questions that are numbered twice. Once with a small sized number and then a larger sized number.

## Step-by-step reproduction instructions (optional)

Please list the steps needed to reproduce or verify the feedback. For example:
1. Go to https://learn.wordpress.org/quiz/meetup-program-basics-2-3/
2. See questions numbered twice. 
3. Scroll down to '...'

## Screenshots or screen recording (optional)
![4c1lSte](https://github.com/WordPress/Learn/assets/909468/e8122a20-d52d-4520-905e-964010273646)

**Comment by ironnysh** [comment]
# Feedback Validation Checklist
- If this is reporting an issue, can you confirm/reproduce the issue? No: 
- What should happen next to apply the feedback?: the issue has been fixed

**Comment by devmuhib009** [comment]
I also checked the issue. I think its fixed already. Closing the issue as completed.
