### ISSUE TITLE
Theme: The child theme's `navigation.js` file is not used

### ISSUE THREAD

**Issue by ryelle** [WordPress/Learn#204]
I was looking for something else and happened to notice this:

https://github.com/WordPress/learn/blob/bfabc325f2aa70cdd0c6343ef189f960c2e16bf3/wp-content/themes/pub/wporg-learn-2020/functions.php#L44-L50

`get_template_directory_uri` fetches the file from the parent, `pub/wporg/js/navigation.js`, rather than the local child theme's `navigation.js`, but the versioning is still checking against the child theme file.

**Comment by coreymckrill** [comment]
Oops, good catch!
