### ISSUE TITLE
New WordPress Developer APIs - The Interactivity API

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2040]
# Details

- Topic description: The main goal of the Interactivity API is to provide a standard and simple way to handle the frontend interactivity of Gutenberg blocks. This standard would make it easier for developers to create rich, interactive user experiences, from simple cases like counters or popups to more complex features like instant search, or carts and checkouts. In this session, you will learn more about this new developer API, through a live coding example. 
- Audience (User, Developer, Designer, Contributor, etc.):  Developer
- Learning objectives (What will the learner be able to do as a result of this content?): Learners will gain an introductory understanding of how the Interactivity API works. 
- Content type (Tutorial, Online Workshop, Course or Lesson Plan): Online Workshop
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): Yes

# Related Resources
- [Proposal: The Interactivity API](https://make.wordpress.org/core/2023/03/30/proposal-the-interactivity-api-a-better-developer-experience-in-building-interactive-blocks/)

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
Meetup.com URL: https://www.meetup.com/learn-wordpress-online-workshops/events/297615509/

**Comment by SierraTR** [comment]
If you still need a co-host I'll set my alarm.

**Comment by jonathanbossenger** [comment]
Thanks @SierraTR 

I've had to cancel this weeks event and move it to next week, so if you're free next week, that would be great.

**Comment by SierraTR** [comment]
Sure, I'll give it a try again. Hope everything is OK.

**Comment by jonathanbossenger** [comment]
All good this side, just discovered that the code I want to demo is currently broken upstream 😁

**Comment by SierraTR** [comment]
oops

**Comment by jonathanbossenger** [comment]
New meetup link https://www.meetup.com/learn-wordpress-online-workshops/events/297698902/

**Comment by jonathanbossenger** [comment]
@SierraTR apologies, I had to cancel again. Will try for next week.

**Comment by SierraTR** [comment]
Sorry to hear that. I just checked my schedule and you will have to find a different co-host. That week (and the rest of the year) is already a mess for me. Take care.

**Comment by jonathanbossenger** [comment]
No problem, thanks @SierraTR

**Comment by jonathanbossenger** [comment]
Updated meetup link https://www.meetup.com/learn-wordpress-online-workshops/events/297864495/

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2023/12/15/new-wordpress-developer-apis-the-interactivity-api/
