### ISSUE TITLE
Online Workshop- To group or not to group: How to use the group block

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2043]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Online Workshop
- Content title: To group or not to group: How to use the group block
- Topic description: The workshop will give several demos about how to use the group block using the 2024 theme. 
There are several new features within the 6.4 that will be highlighted:

      - Renaming the group block
      - Add background image
      - Setting button & heading styling for group block
    

- Audience (User, Developer, Designer, Contributor, etc.): Designer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Set up and style a group block
- Rename a group block
- Add an image to a group block
- How to group and ungroup block
- Feel more confident using the group block tools

# Related Resources and Other Notes
https://github.com/WordPress/Learn/issues/674
https://wordpress.org/documentation/article/group-block/

# Automation Code
#online-workshop#

**Comment by sumitsinghwp** [comment]
@lada7042 I would love to join you as a co-host of your workshop :+1:

**Comment by courtney-pk** [comment]
I'm available to help co-host!

**Comment by ghost** [comment]
Workshop Complete- https://wordpress.tv/2023/12/14/to-group-or-not-to-group-how-to-use-the-group-block/
