### ISSUE TITLE
Learning Pathway: Intermediate Theme Developer

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2045]
# Learning Pathway: Intermediate Theme Developer

The intermediate theme developer has the [fundamental knowledge needed to develop for WordPress](https://github.com/WordPress/Learn/issues/1984), and has decided to focus on theme development.

See the full Developer pathway [outlined in this document](https://docs.google.com/spreadsheets/d/1uOm1I62zZLoZGm1rMI2_Ihvul_Z8hwbCExFirr_zhjI/edit#gid=227009618).

To learn more about creating content for these lessons, please read the [Guidelines for creating, reviewing, and publishing lessons](https://docs.google.com/document/d/1twvDGmVZsyjBZbi9abiqoA_a2G7O_WNis_iGL2Sccg0/edit](https://make.wordpress.org/training/handbook/lessons/)).

_This course has 32 lessons over 8 modules._

https://www.youtube.com/playlist?list=PL1pJFUVKQ7EQuGoWcrS2ElPx3A_zrCsM5

## [Module 1: Global Settings and Styles](#module-01) 

Objective:

### Lessons

- [x] #2190
- [x] #2191
- [x] #2192
- [x] #2193
- [x] #2194

## [Module 2: Templates](#module-02)

Objective:

### Lessons

- [x] #2271
- [x] #2272
- [x] #2273

## [Module 3: Block Theme Features](#module-03)

Objective:

### Lessons

- [x] #2088
- [x] #2089
- [x] #2275
- [x] #2276
- [x] #2277

## [Module 4: Classic themes](#module-04)

Objective:

### Lessons

- [x] #2515
- [x] #2516
- [x] #2517
- [x] #2518
- [x] #2520

## [Module 5: Accessibility](#module-05)

Objective:

### Lessons

- [x] #2188
- [x] #2465

## [Module 6: Privacy](#module-06)

Objective:

### Lessons

- [x] #2449

## [Module 7: Advanced Theme Development](#module-07)

Objective:

### Lessons

- [x] #2410
- [x] #2411
- [x] #2412
- [x] #2414
- [x] #2415
- [x] #2413

## [Module 8: Publishing Themes](#module-08)

Objective:

### Lessons

- [x] #2505
- [x] #2506
- [x] #2507
- [x] #2508
- [x] #2509

**Comment by cynthianorman** [comment]
@jonathanbossenger I would like to develop lessons for this Learning Pathway

**Comment by jonathanbossenger** [comment]
🎉 Thank you @cynthianorman. 

I have just updated this learning pathway to more closely follow the outline of the [Theme Developer Handbook](https://developer.wordpress.org/themes/). 

Additionally, If you are interested,  I think it would be beneficial for you to also create the lessons for **Module 4: An introduction to developing WordPress themes**, of the [Beginner Developer learning pathway](https://github.com/WordPress/Learn/issues/1984). 

Let me know if this idea resonates with you, and we can discuss it in our call tomorrow.

**Comment by jonathanbossenger** [comment]
Noting some previously created issues for new courses, that we should check against when creating content for this learning pathway. If the learning pathway covers the content suggested in those courses, we can close those issues once the learning pathway is launched. 

- #1263 
- #1272

**Comment by cynthianorman** [comment]
@jonathanbossenger Hi Jonathan and anyone else interested. 

How do you feel about my Beginner developer learning pathway lessons for themes having a focus on block themes? I was thinking of mentioning classic themes briefly when appropriate but using block themes (mostly TT4) for my examples and walkthroughs. I will make sure to give resources for further reading when it comes to classic themes. 

This Intermediate pathway has a dedicated module for classic themes so that will help. Lastly, I have a current client who I've decided to convert their classic theme to a hybrid theme. What are your thoughts in terms of adding a module just for hybrid themes?

**Comment by jonathanbossenger** [comment]
Hi @cynthianorman 

> How do you feel about my Beginner developer learning pathway lessons for themes having a focus on block themes?

100% agree with this. If you take a look at the [Core Concepts](https://developer.wordpress.org/themes/core-concepts/) section of theme developer handbook, you'll notice the lessons on the [Introduction to WordPress themes](https://github.com/WordPress/Learn/issues/1984#module-04) align with each page in that section, and the pages in that section are block theme first.

> I was thinking of mentioning classic themes briefly when appropriate but using block themes (mostly TT4) for my examples and walkthroughs.
 
> This Intermediate pathway has a dedicated module for classic themes so that will help.

To be honest, I'm of the opinion that at the beginner level, we probably shouldn't even mention classic themes, but you're welcome to add something about that if you prefer.

> Lastly, I have a current client who I've decided to convert their classic theme to a hybrid theme. What are your thoughts in terms of adding a module just for hybrid themes?

I think adding a module about hybrid themes to the Intermediate theme developer learning pathway is a great idea. Feel free to go ahead and think about the lessons you'd like to include in that module, and we can collaborate on that.

One last thing I would mention is that we should also be aware of adding too much to the learning pathways now, before the planned launch of the new Learn design with learning pathways in July 2024. We can always add modules to the learning pathways after the launch, and I can already see us doing this, as well as moving modules between pathways,  once we get feedback from folks, and so maybe hybrid themes is one such module we can add on later?

**Comment by cynthianorman** [comment]
Yes, later is perfect. I like to think ahead so just noting ideas down for now. Thanks for your input!

**Comment by jonathanbossenger** [comment]
Can I also just add I love that you are bringing real-world experience and examples to this process, this is what we need to get onto Learn, so we're helping folks navigate all the new things. So kudos for thinking of this!

**Comment by jonathanbossenger** [comment]
Hi @cynthianorman 

I want to make sure that contributors can set their own deadlines, but also be mindful of the fact that we're aiming to launch the new Learn redesign with learning pathways by July 2024.

So I wanted to get an idea from you how many of the modules in this learning pathway you feel you can create by the end of June 2024.

Once I know what you feel comfortable with, I can focus my efforts on the other modules/find other contributors to work on them.

**Comment by cynthianorman** [comment]
Hi @jonathanbossenger. For the Intermediate Theme Developer lessons, I can get up to Module 4 - Classic Themes completed by the end of June.

**Comment by jonathanbossenger** [comment]
Thank you @cynthianorman

**Comment by jonathanbossenger** [comment]
@cynthianorman I was reviewing the beginner and both plugin and theme developer learning pathways today, and I wanted to hear your thoughts about something.

I am wondering if the following two lessons should be moved out of the beginner learning pathway:

- #2088
- #2089

The reason I am suggesting this is that the theme module in the beginner learning pathway should serve as a very basic introduction to theme development. Then if the learner chooses to dive headlong into theme development, they would move onto the theme developer learning pathway. These two lessons strike me as being a little more advanced for the beginner-level developer to need to worry about.

I thought about this when I was working on these two lessons that were to be in the beginner developer pathway under the plugin module

- #2182
- #2183

As I researched and created the scripts for the first one, I realised these two topics were a little too much for the beginner, and so I moved them to the Intermediate Plugin developer pathway.

Given that theme functions.php and adding assets like JS/CSS and or images are common to both block and classic themes, it makes sense to me to move these two lessons into their own module in the theme developer pathway somewhere.

I would love to hear your opinions on this suggestion.

**Comment by cynthianorman** [comment]
@jonathanbossenger your suggestion is definitely something I had thought about and really should have said something. So yes, definitely best for us to move those 2 lessons into the Intermediate Theme Developer learning pathway. Within the Classic themes module, we could easily cover Custom Functionality and Including Assets so really issues #2088 and #2089 could be closed in favour of those lessons.

**Comment by jonathanbossenger** [comment]
> your suggestion is definitely something I had thought about and really should have said something.

Always feel free to reach out with any ideas like this. I'm glad we're on the same page.

For now, I have simply moved #2088 and #2089 into this learning pathway, in their own module titled Common theme features, and removed the Theme functionality lesson from the Classic themes module.

What I suggest is that when you're finished with the Introduction to themes module in the beginner pathway, we spend a bit of time reviewing what's set up here, have a bit of discussion to see if further changes are needed.

**Comment by cynthianorman** [comment]
@jonathanbossenger here are some thoughts I'd really like to hear your reaction to.

I'm feeling like each lesson we've planned is much too brief.

For example, the **Settings** lesson is a huge topic. 

My current impressions are that we are aiming for an "overview" methodology in our current outline. 

At this point, I believe the best way to introduce huge lessons within a 10 minute presentation is to demonstrate a couple examples then reference the theme handbook for more details.

I also want to keep in mind that since each of our video lessons will wind up in a Sensei lesson, we will be able to embellish them with activities and additional text/audio assets. This can create balance between the short video and the need to guide the learner further into the details.

Additionally in the future, we will clearly be able to add more video lessons as you've pointed out to me before.

**Comment by jonathanbossenger** [comment]
> At this point, I believe the best way to introduce huge lessons within a 10-minute presentation is to demonstrate a couple of examples then reference the theme handbook for more details.

That is probably the best way, and it's more or less what I'll be doing as well.

> I also want to keep in mind that since each of our video lessons will wind up in a Sensei lesson, we will be able to embellish them with activities and additional text/audio assets. This can create a balance between the short video and the need to guide the learner further into the details.

100%. One of the requests I've seen more than once is more practical activities. We will need to balance getting content created with creating more activities, but we can always add more activities once the content is done.

If it helps, I am looking at these learning pathways as an MVP, minimum viable product. What is the minimum set of knowledge and tools that I need to present to a new learner? Once I have the MVP, I can add more features (lessons) later, as I get feedback. But I can only get that feedback if I ship the MVP first.

**Comment by cynthianorman** [comment]
I've taken on a heavier client load for May and June than I originally anticipated. For that reason I'm going to push the Classic Theme lessons into July as it stands now.

**Comment by jonathanbossenger** [comment]
Thanks for the update.

**Comment by jonathanbossenger** [comment]
@cynthianorman just circling back here, as things stand at present, the learning pathways launch is targeted for end July, so pushing those lessons into July should be fine.

However, if this changes, we might need to collaborate on perhaps sharing the work on some of these modules, but I will let you know as soon as I hear anything different.

**Comment by jonathanbossenger** [comment]
Note: reworked all the lessons in Module 7: Advanced Theme Development, so that they are presented in a more logical order.

**Comment by jonathanbossenger** [comment]
@cynthianorman, I wanted to check in with you.

This week, I'll be wrapping up the recording of **Module 8: Publishing Themes**. 

Do you still feel comfortable that you'll be able to tackle **Module 4: Classic themes** in July?

I am asking because I am going to be on leave from Monday, June 24th, and will be returning Monday, July 8th. So I wanted to check in to see if you want any assistance on Module 4 or if I can start on the plugin developer pathway when I return. 

Thanks

**Comment by cynthianorman** [comment]
Yes, @jonathanbossenger, thank you for checking in with me. I am still planning of completing classic themes in July. Have a wonderful break!

**Comment by jonathanbossenger** [comment]
Thank you for confirming.

**Comment by jonathanbossenger** [comment]
@cynthianorman I wanted to touch base with you to make sure you're still feeling comfortable to complete the remaining lessons in this pathway for the end July date.

**Comment by cynthianorman** [comment]
@jonathanbossenger here's a quick update:
All outstanding videos will be finished recording tomorrow. I am then at WCEH for Thurs/Fri. 

Monday/Tues Jul 15/16 I'll Edit, Publish and Share with the team all of the outstanding lessons. My plan was to give people 1 week to review them. 

Mon Jul 22 is when I'd upload to WP tv and have you help me with YouTube/Sensei.

By Fri Jul 26th I'd like all outstanding lessons to be finished on Sensei.

**Comment by jonathanbossenger** [comment]
Thank you so much for the update.

**Comment by kathrynwp** [comment]
As Cynthia let me know that all lessons have been completed, I've published this course, as previously discussed!

I understand that the chapter information is still to come, so the remaining lessons are unchecked until that step is completed.

**Comment by jonathanbossenger** [comment]
Thank you for publishing @kathrynwp

**Comment by jonathanbossenger** [comment]
@cynthianorman please let me know here once those chapters are ready, thanks.

**Comment by jonathanbossenger** [comment]
Final Youtube updates required:

- [x] Add chapters
- [x] Update description to include link back to Learn WordPress

**Comment by jonathanbossenger** [comment]
//publish
