### ISSUE TITLE
Meeting Agenda December 05, 2023

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#2048]
Training Team meetings start at 07:00 UTC weekly on Tuesdays. Anyone is welcome to contribute to the meeting by commenting in Slack threads throughout the week. Meeting notes will be published at the end of the week to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune_

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- December 5 – `@Sakib MD Nazmush`
- December 12 – `@Sumit Singh`
- December 19 –  `@rabin kumar pal`

**Final meeting for the year is December 19th. We’ll resume on January 9th.**

**2. Looking for feedback**

- Gus from [#sustainability](https://wordpress.slack.com/archives/C03JNV77Y57) has shared a project where there is potentially an overlap in interest with us, the Training Team. 
  - Please review [#21 Extend the do_action hackathon format](https://github.com/WordPress/sustainability/issues/21) and provide feedback on which areas we can cross-team collaborate
- [Vote for Training Team Rep 2024](https://make.wordpress.org/training/2023/11/17/vote-for-training-team-rep-2024/)
  - The voting is open until December 6, 2023.
 
**3. Looking for volunteers**

- [Training Team 2023 Year-End Review](https://make.wordpress.org/training/2023/11/20/training-team-2023-year-end-review/)
  - Plan promotions with the Marketing Team
  - Establish monthly recurring onboarding Online Workshops in different timezones for training team roles
  - Figure out a method to manage localized content translation
  - Audit Handbook
- item 2

**4. Updates from last week's dev-squad triage session**

Attendees: @psykro, @properlypurple, @sumitsingh, and @devmuhib

PRs triaged
- There were no new open PRs to review

Bugs triaged
- #2014
- #2041

Call for developer input
- #2014 is a good first bug for a developer to work on, so anyone interested in submitting a PR to fix this, please comment on the issue

We wrapped up with a discussion on the WIP guidelines, which can be found [here](https://docs.google.com/document/d/1mH5lOCenx-to2tQnwZUV4egUAg_bEWkYjmgApFldQ80/edit?usp=sharing).  

**5. Faculty Updates**
- Time for a Faculty check-in! @faculty please answer any that apply:
  - What have you been working on and how has it been going?
  - Anything you’ve accomplished since the last meeting?
  - Do you have any blockers?
  - Can other Faculty or Training Team members help you in some way?

**6. Other news**

- [Proposal: Hosting Learn videos on YouTube](https://make.wordpress.org/training/2023/11/17/proposal-hosting-learn-videos-on-youtube/)
- On-site chat integration can be tested on https://make.wordpress.org/training/chat/
- Badges awarded
  - Contributor badge: [Jenny Dupuy](https://profiles.wordpress.org/jdy68/), [Sakib MD Nazmush](https://profiles.wordpress.org/sakibsnaz/)
- [Embracing Matrix for Enhanced Communication](https://make.wordpress.org/project/2023/11/30/embracing-matrix-for-enhanced-communication/)
- GitHub Updates Online Workshops -- join @bsanevans for a walkthrough of the GitHub process updates in the WordPress Training team. Two sessions are offered below:
  - [December 14 at 08:00 UTC](https://www.meetup.com/learn-wordpress-online-workshops/events/297747513/) and
  - [December 15 at 00:00 UTC](https://www.meetup.com/learn-wordpress-online-workshops/events/297748992/)

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

- **Tutorials**
  - #704 
- **Lesson Plans**
  - #652 
- [Translated Content looking for reviewers](https://github.com/orgs/WordPress/projects/104/views/10)
  - https://github.com/WordPress/Learn/issues/1488
  - https://github.com/WordPress/Learn/issues/1508
  - https://github.com/WordPress/Learn/issues/1535
  - https://github.com/WordPress/Learn/issues/1873
- **Learning Pathway Lessons**
  - #2049 
  - #1985 
  - #1986
  - #1987 
  - #1988 
  - #1990 
  - #1989 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
- [GitHub updates project](https://make.wordpress.org/training/2023/09/27/looking-for-feedback-updates-to-github-issue-templates-and-labels/)

## 5. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by courtney-pk** [comment]
Can we please bring back the Faculty update thread and make it a permanent part of subsequent agendas? Thank you :)

> Time for a Faculty check-in! `@faculty` please answer any that apply:
> • What have you been working on and how has it been going?
> • Anything you’ve accomplished since the last meeting?
> • Do you have any blockers?
> • Can other Faculty or Training Team members help you in some way?

**Comment by kaitohm** [comment]
I've scheduled two Online Workshops where I walk through the recent GitHub updates with the team. Could we announce these to the team? Anyone is welcome to join.

**A walkthrough of the GitHub process updates in the WordPress Training team**
[December 14 at 08:00 UTC](https://www.meetup.com/learn-wordpress-online-workshops/events/297747513/) and [December 15 at 00:00 UTC](https://www.meetup.com/learn-wordpress-online-workshops/events/297748992/)

**Comment by jonathanbossenger** [comment]
Dev squad triage session notes added.

**Comment by jonathanbossenger** [comment]
I have suggested a new section to the [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17) item called Learning Pathway Lessons, and listed the first 7 lessons of the 1st module of the beginner developer learning pathway. I suggest any future learning pathway content be included here. 

It's worth noting that these lessons will differ from tutorials, so the structure is slightly different (eg each lesson will not include the title card that most tutorials would have, and each lesson might not include a detailed list of learning outcomes, as this would probably be covered in the first lesson of the module, etc). If in doubt, it's recommended to reach out to the content creator in the comments of the issue to check.

**Comment by gusaus** [comment]
Realizing the project/issue is on the agenda, I've been outlining some more [ideas and questions](https://wordpress.slack.com/docs/T024MFP4J/F05SUHSBWGZ?focus_section_id=temp:C:QaO0e4b4b6adb3c44459e9dc1881) in the [Sustainability Team: NextGen and other Event ideas and suggestions](https://wordpress.slack.com/docs/T024MFP4J/F05SUHSBWGZ) (Slack Canvas).

I'm going to try and attend in real time so I can reference some of those ideas and ask followup questions. If I'm not able to make it tonight (11pm my time), I'll async participate tomorrow.

@Piyopiyo-Kitsune Thanks so much for including!

**Comment by kaitohm** [comment]
https://make.wordpress.org/training/2023/12/12/training-team-meeting-recap-5th-december-2023/
