### ISSUE TITLE
How WordPress Works

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2049]
# Learning Objective

Introduce the How WordPress Works module, and include the learning outcomes for this module

# Relevant Links

N/A

# Lesson creation checklist

- [ ] Gather any relevant links to Support, Docs, or related material
- [ ] Description and Objectives finalized
- [ ] Lesson created and announced to the team for Q/A review
- [ ] Lesson submitted and published to WPTV
- [ ] Lesson transferred to YouTube
- [ ] Lesson reviewed and ready to publish
- [ ] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/how-wordpress-works/introduction.md

Video for review:

https://github.com/WordPress/Learn/assets/180629/446755c4-1dcd-4992-8568-8a54630006cf

**Comment by cynthianorman** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

In this brief introduction we quickly learn that there's a large span of knowledge any aspiring WordPress developer should start with. I wondered if this is the video where we could take the opportunity to briefly introduce what a WordPress developer is typically responsible for and mention the 3 paths, namely plugin development, theme development, and expert generalist.

**Comment by jonathanbossenger** [comment]
First off, thanks @cynthianorman for the reivew. 

So this intro is specific to module 1 of the beginner developer pathway. I'm planning an intro video like this for each module. 

There is a good chance that once the new learning pathway infrastructure has launched, we'll need another video introducing all the developer-focused pathways, and that's where we can cover the 3 (or more) paths we offer.

**Comment by nftushar** [comment]
# Learning Objective Solution 🌐📘

## **Introduction to the "How WordPress Works" Module**

Welcome to the gateway of WordPress knowledge! The "How WordPress Works" module is your passport to understanding the intricate dance of code, content, and creativity that powers the WordPress ecosystem.

### **Learning Outcomes for this Module:**

1. **WordPress Fundamentals:** Dive into the foundational principles of WordPress, grasping the essence of its architecture and functionality.

2. **Workflow Deconstruction:** Unravel the magic behind WordPress workflows, dissecting the process of how content is created, managed, and displayed.

3. **Key Components Exploration:** Navigate through the core components of WordPress, from themes and plugins to databases and user roles.

4. **Troubleshooting Insights:** Equip yourself with troubleshooting skills, learning how to identify and resolve common challenges in the WordPress journey.

### **Relevant Links:**
N/A - This module serves as your central hub for WordPress enlightenment, offering an immersive learning experience without the need for external links.

### **Lesson Creation Checklist:**

1. **Gathering Supportive Material:** Explore the vast expanse of WordPress documentation to enhance your learning journey.

2. **Description and Objectives Finalization:** Craft a captivating description that beckons learners and ensures objectives are crystal clear.

3. **Team Announcement for Q/A Review:** Present your creation to the team, inviting their keen eyes for a thorough quality assurance review.

4. **Submission and Premiere on WPTV:** Share your insights on the grand stage of WPTV, reaching WordPress enthusiasts worldwide.

5. **YouTube Conveyance:** Extend the reach of your lesson by transporting it to YouTube, a hub for digital knowledge seekers.

6. **Thorough Review and Polishing:** Ensure your lesson sparkles with clarity and engagement, ready to be showcased on the prestigious Learn.WordPress.org.

### **Feedback and Iteration:**

Your journey doesn't end here! Embrace feedback, iterate on your content, and foster continuous improvement. Let the WordPress community benefit from your commitment to excellence.

Feel the excitement of unraveling the WordPress magic in the "How WordPress Works" module. Your adventure begins now!

Best of luck, and happy learning! 🚀🌟

**Comment by jonathanbossenger** [comment]
Hi there @nftushar thank you for your comment.

I'm not sure if this is a review, or if you are suggesting a possible lesson here. Could you let me know, thanks.

**Comment by nftushar** [comment]
hi @jonathanbossenger!
I appreciate your engagement with the content. I've shared a comprehensive overview of the "How WordPress Works" module along with the learning objectives and relevant steps for lesson creation. It's intended to guide learners through a structured and engaging learning experience.

If you have any questions or if there's a specific aspect you'd like to discuss or clarify, feel free to let me know. Looking forward to your insights! 🌟

**Comment by jonathanbossenger** [comment]
@nftushar Ok, thanks. 

My question is, is the overview you shared a review of the content [already created and added here](https://github.com/WordPress/Learn/issues/2049#issuecomment-1835627620)?

**Comment by nftushar** [comment]
@jonathanbossenger,  yes Thank you

**Comment by jonathanbossenger** [comment]
@nftushar I am confused, you say your overview is a review of the already shared content, but your overview and the content do not match up. So it looks like you are suggesting an alternative introduction for this module, but your overview does not [match up to the rest of the content planned for this module](https://github.com/WordPress/Learn/issues/1984#module-01). 

If you are reviewing this content, please use the relevant check list, and add any actionable feedback to your review.

**Comment by nftushar** [comment]
sorry for wasting your time, I am confused about this conversation, im='m quitting for now, thank you

**Comment by jonathanbossenger** [comment]
If you have any questions about the review process, you're welcome to post them in the #training team channel in the WordPress Slack.

**Comment by jonathanbossenger** [comment]
Closing this issue, and moving parts of this introduction to individual lessons within the rest of this course.
