### ISSUE TITLE
Bangla Translation for Scheduling posts and pages

### ISSUE THREAD

**Issue by faisalahammad** [WordPress/Learn#2052]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/scheduling-posts-and-pages/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @devmuhib009
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by faisalahammad** [comment]
Here is the translated doc file:

https://docs.google.com/document/d/15QBfXkmVVokeD_2mNzY5zEnmPsk8tl7oYAz7G97EnfM/edit?usp=sharing

Could you please review and share your feedback, @devmuhib009?

**Comment by devmuhib009** [comment]
Sure. I will review soon and share my feedback here.

**Comment by devmuhib009** [comment]
>এই টিউটোরিয়ালটির লক্ষ্য হল ওয়ার্ডপ্রেসে একটি পোস্ট বা পেজ কীভাবে শিডিউল করতে হয়, ঠিক সময়ে পোস্ট বা পেজটি লাইভ যাতে হয় তার জন্য সময় কীভাবে সেট করতে হয়, কীভাবে একটি পোস্ট বা পেজ পুনরায় শিডিউল বা আনশিডিউল করতে হয়, এবং কীভাবে একটি পোস্ট বা পেজ পিছিয়ে দিতে হয়।

 এই টিউটোরিয়ালটির লক্ষ্য হল সহজে বুঝিয়ে দেয়া কীভাবে ওয়ার্ডপ্রেসে একটি পোস্ট বা পেজ শিডিউল করতে হয়, ঠিক সময়ে পোস্ট বা পেজটি যেন লাইভ হয় তার জন্য সময় কীভাবে সেট করতে হয়, কীভাবে একটি পোস্ট বা পেজ পুনরায় শিডিউল বা আনশিডিউল করতে হয়, এবং কীভাবে একটি পোস্ট বা পেজ ব্যাকডেট করতে হয়।

>যা একজন ব্যবহারকারীকে পোস্টের শিডিউল বা পিছানো তারিখ দিতে সাহায্য করে।

যা একজন ব্যবহারকারীকে পোস্ট শিডিউল বা ব্যাকডেট করতে সাহায্য করে। 

>কেবল পোস্টগুলি কি শিডিউল করা যায়, নাকি পেজগুলিও শিডিউল করা যায়?

কেবল পোস্টগুলিই কি শিডিউল করা যায়, নাকি পেজগুলিও শিডিউল করা যায়?

>ওয়ার্ডপ্রেস ড্যাশবোর্ডে আপনি কোথায় সময় বর্তমান মুহূর্তের জন্য রিসেট করতে পারেন?

ওয়ার্ডপ্রেস ড্যাশবোর্ডের কোথায় আপনি বর্তমান মুহূর্তের জন্য সময় রিসেট করতে পারেন?

>বা এমনকি আপনি যদি সঠিক স্থান জানেন তাহলে অতীতে পিছানো তারিখেও তা করতে পারেন। 

অথবা এমনকি আপনি ব্যাকডেট করতে পারেন যদি আপনি জানেন কোথা থেকে তা করতে হবে।

>যা একজন ব্যবহারকারীকে পোস্টের সময়সূচী বা ব্যাকডেট করতে দেয়

যা একজন ব্যবহারকারীকে পোস্ট শিডিউল বা ব্যাকডেট করতে দেয়

>চলেন শুরু করি।

চলুন শুরু করি।

>যা একজন ব্যবহারকারীকে পোস্টগুলি শিডিউল বা পিছানো তারিখে দিতে দেয়

যা একজন ব্যবহারকারীকে পোস্টগুলি শিডিউল বা ব্যাকডেট করতে দেয়

>এবং একটি পোস্ট বা পেজ পুনরায় শিডিউল বা শিডিউল বাতিল বা পিছোনো তারিখে দিতে।

এবং একটি পোস্ট বা পেজ পুনরায় শিডিউল বা শিডিউল বাতিল বা ব্যাকডেট করা

#উপরের প্যারাগ্রাফটা ২ বার আছে মনে হচ্ছে

#assign#

**Comment by faisalahammad** [comment]
I've made the changes. Could you please check now and let me know how that goes? @devmuhib009

**Comment by devmuhib009** [comment]
Thanks for making the changes. It's now ready for publish.

**Comment by kaitohm** [comment]
@faisalahammad I've added you to this post as an author: https://learn.wordpress.org/wp-admin/post.php?post=56306&action=edit

You can now continue from step 5 here: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video 🙌

**Comment by faisalahammad** [comment]
Thank you @bsanevans 
I have added the translated post content and saved it as a draft. I have also submitted the subtitles for the video. Please review and let me know if there is anything else I need to do. Thank you.

**Comment by kaitohm** [comment]
I've approved the subtitles and published the content here: https://learn.wordpress.org/tutorial/bn-scheduling-posts-and-pages/

Thank you all for your contributions to the team 🙌
