### ISSUE TITLE
Bangla Translation for Create Block Theme Improvements

### ISSUE THREAD

**Issue by faisalahammad** [WordPress/Learn#2053]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/create-block-theme-improvements/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @devmuhib009
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by faisalahammad** [comment]
Here is the translated doc file:

https://docs.google.com/document/d/1XqP6N_iY20Bec_XLEcymbwrRjCBgGPjDKoQomc1_BAo/edit?usp=sharing

Could you please review and share your feedback, @devmuhib009?

**Comment by devmuhib009** [comment]
Sure, I will review the content soon and update you here.

**Comment by devmuhib009** [comment]
>ব্লক থিম উন্নতিসাধন তৈরি করুন

ক্রিয়েট ব্লক থিমের উন্নতিসমূহ 

>বর্ণনা করুন ওয়ার্ডপ্রেসের জন্য ক্রিয়েট ব্লক থিম-এ ৬.৩ এবং ৬.৪ রিলিজে কী কী উন্নতি সাধিত হয়েছে।

ওয়ার্ডপ্রেস ক্রিয়েট ব্লক থিম-এ ৬.৩ এবং ৬.৪ রিলিজে কী কী উন্নতি সাধিত হয়েছে তা বর্ণনা করুন।

>থিম ফন্ট পূর্বরূপসমূহ

থিম ফন্টের পূর্বরূপসমূহ

>পাশের তীরে ক্লিক করলে

পাশের তীর চিহ্নে ক্লিক করলে / পাশের এ্যারোতে ক্লিক করলে

>আপনি একটি ফন্ট যোগ করার সময় এই ফন্ট পূর্বরূপ পাওয়া যায়।

আপনি একটি ফন্ট যোগ করার সময় এই ফন্টের পূর্বরূপ দেখতে পাওয়া যায়।

>সাইট এডিটর অ্যাকশনসমূহ

সাইট এডিটরের ক্রিয়াকলাপ

>সামাপ্তি

সমাপ্তি

**Comment by faisalahammad** [comment]
Thank you for fixing my typo and improving the grammar. I have made the correction. Could you please check it now and let me know how it looks? @devmuhib009

**Comment by devmuhib009** [comment]
Thanks for fixing all the typo's and suggestions. It's now ready for publish. @bsanevans could you please help @faisalahammad to publish his translations?

**Comment by kaitohm** [comment]
@faisalahammad Could you share your WordPress.org username with me, please? I'll add you to https://learn.wordpress.org/ as a Contributor.

**Comment by faisalahammad** [comment]
Thank you, @devmuhib009 and @bsanevans. My WP.org username is `faisalahammad` or here is the profile URL: https://profiles.wordpress.org/faisalahammad/. 😄

**Comment by kaitohm** [comment]
Thanks, @faisalahammad ! I've sent you an email invite to become a Contributor on https://learn.wordpress.org/. Let me know once you've accepted that, and I'll guide you with next steps.

**Comment by faisalahammad** [comment]
Thank you, @bsanevans. I have accepted the invitation.

Please guide me for the next step. 😀

**Comment by kaitohm** [comment]
Great! I've now made you the author of this post: https://learn.wordpress.org/wp-admin/post.php?post=56382&action=edit

Please continue from step 5 in this handbook page: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video

**Comment by faisalahammad** [comment]
Thank you, @bsanevans.
I've drafted the post and submitted the translated subtitle. Please let me know if anything is missing. 😄

**Comment by kaitohm** [comment]
Thank you! I've approved the subtitles and published the Tutorial here: https://learn.wordpress.org/tutorial/bn-create-block-theme-improvements/

Great work 🙌
