### ISSUE TITLE
Bangla Translation for Adding a sticky header or banner

### ISSUE THREAD

**Issue by faisalahammad** [WordPress/Learn#2054]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/adding-a-sticky-header-or-banner/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @devmuhib009
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by faisalahammad** [comment]
Here is the translated doc file:

https://docs.google.com/document/d/13fH4Yeep69Kouo3zoJb-__eYKgGTzzTnyKgWJyZ7qCI/edit?usp=sharing

Could you please review and share your feedback, @devmuhib009?

**Comment by devmuhib009** [comment]
Sure, I will review the content soon and update you here.

**Comment by devmuhib009** [comment]
#assign#

**Comment by devmuhib009** [comment]
>হেডারটি স্বচ্ছ না হওয়ার জন্য গ্রুপ ব্লকের ব্যাকগ্রাউন্ড পরিবর্তন করা।

হেডারটি স্বচ্ছ নয় এটি নিশ্চিত করতে গ্রুপ ব্লকের ব্যাকগ্রাউন্ড পরিবর্তন করা

>প্রথমটি হাউস অফ ট্রাভেলের এবং দ্বিতীয় উদাহরণটি গ্ল্যাডর্যাপ ওয়েবসাইট থেকে।

প্রথমটি হাউস অফ ট্রাভেল এবং দ্বিতীয় উদাহরণটি গ্ল্যাডর্যা প ওয়েবসাইট থেকে।

>আপনি লক্ষ্য করবেন যে এটা বলা হচ্ছে যে ব্লকটি স্ক্রোলিং এর বদলে উইন্ডোর উপরে আটকে থাকবে।

আপনি লক্ষ্য করবেন এটি বলছে যে ব্লকটি স্ক্রোলিং এর বদলে উইন্ডোর উপরে আটকে থাকবে।

**Comment by faisalahammad** [comment]
Thank you for your time. I have made the recommended changes. Could you please check now and let me know how it goes? @devmuhib009

**Comment by devmuhib009** [comment]
Thanks for making changes. It's now ready for publish.

**Comment by kaitohm** [comment]
Thank you for working on this 🙌 

@faisalahammad I've added you as an author on https://learn.wordpress.org/wp-admin/post.php?post=56308&action=edit

Please follow the handbook and continue from step 5: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video

**Comment by faisalahammad** [comment]
Thank you, @bsanevans 
I've saved the post as a draft but couldn't submit it for review (publish) due to the following error. I've also submit the subtitle at WP.tv. 

Is there anything else I've to do? Thank you

![error](https://media.cleanshot.cloud/media/21037/IV65HZasvL1H8cbE1aXWuAYi00H3aObrwhAK5NwY.jpeg?Expires=1701900398&Signature=T634JFprpXxKL52FKjfu9wZlvNgDwMV1SVpNZ4l-j21RGP742dIM10VDc7gwLMOXCk3B52boxgi2WsxZ2Lg76iQyXWuiTRfhKAzLJDgmkGshEysGYZD3~cB82znZczy9T-F0h0DNz5IFqEQZDOgqCmw8DFwh8NRFQCoG3yNHGWk5ZaOhfX4a8kfClBsLt8sDah5lmVtb6T6cAZj-0kKQvFY6PwT8RCTrk8tfZpsQBKuWoIoZ2aW3IcLuZX73HquMzh0-xM5qV7m0QUX6YsTtrM17Xjn6hyMhyCxoPHN5CFKHv8OU74Hj5KFJY0C0bAvK--6bMZI7uhW1Kks6vhgYPQ__&Key-Pair-Id=K269JMAT9ZF4GZ)

**Comment by kaitohm** [comment]
Thanks, @faisalahammad ! Saving the post is enough, and an admin can publish this for you 👍 

I went and published this only to realize this tutorial had already been translated into Bengali and published earlier: https://learn.wordpress.org/tutorial/bn-adding-a-sticky-header-or-banner/ That translation was worked on in #1934 

I'm so sorry I did not confirm this sooner. While I will close this issue for now, would you be interested in translating a different tutorial again? Now that you have done it a couple of times, hopefully the process will be even smoother.

**Comment by faisalahammad** [comment]
Hi @bsanevans 
Thanks for confirming it. It's ok, I'll translate another post so you can help me to publish it.
