### ISSUE TITLE
Testing workflows

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2057]
#tutorial#
#course#
#online-workshop#
#lesson-plan#

Testing

**Comment by kaitohm** [comment]
Below, I'm testing each of the content types from within the issue.

**Comment by kaitohm** [comment]
OK, comments after here are triggered by a comment in the issue body.

**Comment by kaitohm** [comment]
Let's try again.

**Comment by kaitohm** [comment]
And again.

**Comment by kaitohm** [comment]
And now?

**Comment by kaitohm** [comment]
#tutorial#
#course#
#online-workshop#
#lesson-plan#

**Comment by kaitohm** [comment]
#tutorial#
#course#
#online-workshop#
#lesson-plan#

**Comment by nikonikobsan** [comment]
#assign#

**Comment by kaitohm** [comment]
#assign#
