### ISSUE TITLE
Strings not in english

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Learn#206]
Hi,

Some strings aren’t in english:
https://translate.wordpress.org/projects/meta/learn-wordpress/fr/default/?filters%5Boriginal_id%5D=11604734
https://translate.wordpress.org/projects/meta/learn-wordpress/fr/default/?filters%5Boriginal_id%5D=11604737
https://translate.wordpress.org/projects/meta/learn-wordpress/fr/default/?filters%5Boriginal_id%5D=11604731
https://translate.wordpress.org/projects/meta/learn-wordpress/fr/default/?filters%5Boriginal_id%5D=11604730
https://translate.wordpress.org/projects/meta/learn-wordpress/fr/default/?filters%5Boriginal_id%5D=11604716
in
https://github.com/WordPress/learn/blob/trunk/extra/translation-strings.php

**Comment by coreymckrill** [comment]
Hi, this is because taxonomy terms are now being added to the translation project, and some of the terms were labeled in other languages. More discussion here: https://github.com/WordPress/learn/pull/205#issuecomment-814639380
