### ISSUE TITLE
Bangla translation for Tutorial "How to add a blog or news page to any WordPress website"

### ISSUE THREAD

**Issue by nasirbabu** [WordPress/Learn#2065]
# Details
- Link to original content:  https://learn.wordpress.org/tutorial/how-to-add-a-blog-or-news-page-to-any-wordpress-website/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues?q=is%3Aissue+How+to+add+a+blog+or+news+page+to+any+WordPress+website
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by nasirbabu** [comment]
Bangla translated doc file link
https://docs.google.com/document/d/1Zhrh_lbNNUEJL8X1Hnvb3St5VFwKCooRb3HugPDEnvs/edit?usp=sharing

**Comment by devmuhib009** [comment]
#assign# 
Please update the github issue link: https://github.com/WordPress/Learn/issues/1506
I will review the content and update here soon. Thanks for the translation.

**Comment by devmuhib009** [comment]
>যেকোন ওয়ার্ডপ্রেস ওয়েবসাইটে কিভাবে ব্লগ বা নিউজ পেজ যোগ করবেন

কিভাবে যেকোন ওয়ার্ডপ্রেস ওয়েবসাইটে একটি ব্লগ বা নিউজ পেজ যোগ করবেন

> যা একটি ক্লাসিক বা ব্লক থিমে ব্যবহার করা যেতে পারে৷

যা একটি ক্লাসিক বা ব্লক থিম উভয়ের যে-কোনটির সাথেই ব্যবহার করা যেতে পারে৷

>বোধগম্য প্রশ্নগুলি

সম্পূরক প্রশ্নগুলি

>আপনার পোস্ট বা সংবাদ পৃষ্ঠায় আপনার ক্যোয়ারী লুপ প্রদর্শিত হওয়ার আগে আপনাকে কোন সেটিংটি বন্ধ করতে হবে?

আপনার পোস্ট বা নিউজ পেজে ক্যোয়ারী লুপটি প্রদর্শিত হওয়ার আগে আপনাকে কোন সেটিংসটি বন্ধ করতে হবে?

>অনুলিপি

প্রতিলিপি

>আপনি কি জানেন যে আপনার ওয়ার্ডপ্রেস ওয়েবসাইটে একটি ব্লগ বা নিউজ পেজ যোগ করলে অনেক সুবিধা ?

আপনি কি জানেন আপনার ওয়ার্ডপ্রেস ওয়েবসাইটে একটি ব্লগ বা নিউজ পেজ যুক্ত করার অনেক সুফল রয়েছে? 

>আপনি যদিও ব্লক থিম বা ক্লাসিক থিম ব্যবহার করছেন তারপরেও, আপনি একই কৌশলে আপনার ওয়েবসাইটে ব্লগ বা  নিউজ পেজ যুক্ত করতে পারেন৷

আপনি ব্লক বা ক্লাসিক থিম যাই ব্যবহার করুন না কেন, আপনি একই কৌশলে আপনার ওয়েবসাইটে ব্লগ বা  নিউজ পেজ যুক্ত করতে পারেন৷

>আসুন একটি পোস্ট পৃষ্ঠা তৈরি করে এবং এতে একটি ক্যোয়ারী লুপ ব্লক যোগ করে সবচেয়ে প্রাথমিকটি শিখি।

আসুন একটি পোস্ট পেজ তৈরি করে সবচেয়ে সহজ উপায়টি শিখি এবং এতে একটি ক্যুয়েরি ব্লক যুক্ত করি। 

>একটি দ্রষ্টব্য

একটি নোট / বিশেষ দ্রষ্টব্য

>আমি গত  ১৫ দিন থেকে ১০টি নতুন পোস্ট যোগ করার সিদ্ধান্ত নিয়েছি এবং কিছু অতিরিক্ত সেটিংস বাছাই করবো।

আমি বিগত ১৫ দিনের নতুন ১০টি পোস্ট যোগ করার সিদ্ধান্ত নিয়েছি এবং কিছু অতিরিক্ত সেটিংস বাছাই করবো।

>Edit বাটনে ক্লিক করুন

সম্পাদনা বাটনে ক্লিক করুন।

> আপনার নিজের সাথে সবচেয়ে যেটি মিলছে সেটি নির্বাচন করুন।

আপনার সাথে সবচেয়ে যেটি মিলছে সেটি নির্বাচন করুন।

> Taking advantage of Query Loops

ক্যুয়েরি লুপের সুবিধা নেওয়া

> Inherit Query From Template

কোয়েরি থেকে টেমপ্লেট ইনহেরিট

>"Learn" ড্রপডাউন সিলেক্ট করুন

লার্ন ড্রপডাউন সিলেক্ট করুন

>অবশেষে, "পাবলিশিং" বোতাম প্রেস করুন।

অবশেষে, "পাবলিশিং" বাটন প্রেস করুন।

**Comment by kaitohm** [comment]
@nasirbabu Thank you for translating content! I've just invited you to become a Contributor on https://learn.wordpress.org/. Please let me know once you've accepted this, and I will guide you with next steps.

**Comment by nasirbabu** [comment]
@devmuhib009 I have updated the document file as you suggested. https://docs.google.com/document/d/1Zhrh_lbNNUEJL8X1Hnvb3St5VFwKCooRb3HugPDEnvs/edit?usp=sharing

**Comment by nasirbabu** [comment]
@bsanevans Thanks for your invitation. I have joined https://learn.wordpress.org/  via your invitation.

**Comment by devmuhib009** [comment]
> @devmuhib009 I have updated the document file as you suggested. https://docs.google.com/document/d/1Zhrh_lbNNUEJL8X1Hnvb3St5VFwKCooRb3HugPDEnvs/edit?usp=sharing

Just checked the file. It's now ready for publish.

**Comment by kaitohm** [comment]
Thanks for reviewing, Muhibul 🙌 

Alright, @nasirbabu , I've added you as the author of this post: https://learn.wordpress.org/wp-admin/post.php?post=56276&action=edit

Please continue with step 5 in this handbook page: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video 🙂

**Comment by nasirbabu** [comment]
> Thanks for reviewing, Muhibul 🙌
> 
> Alright, @nasirbabu , I've added you as the author of this post: https://learn.wordpress.org/wp-admin/post.php?post=56276&action=edit
> 
> Please continue with step 5 in this handbook page: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video 🙂

@bsanevans step 5 is done.

**Comment by nasirbabu** [comment]
@bsanevans step 6 is also completed.

**Comment by kaitohm** [comment]
Wonderful! I've approved the subtitles and published the content here: https://learn.wordpress.org/tutorial/bn-how-to-add-a-blog-or-news-page-to-any-wordpress-website/

Thank you all for your contribution to the team 🙌

**Comment by kaitohm** [comment]
@nasirbabu I saw you left an _editorial comment_ in the post itself. I'm not sure why you got that error? But generally, you just need to press Save, and an admin will be able to check and publish the content for you 👍

**Comment by nasirbabu** [comment]
@bsanevans @devmuhib009 Thanks.
