### ISSUE TITLE
Online Workshop: A walkthrough of the GitHub process updates in the WordPress Training team

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2067]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Online Workshop
- Content title: A walkthrough of the GitHub process updates in the WordPress Training team
- Topic description: Over the last month, [many updates have been introduced](https://make.wordpress.org/training/2023/09/27/looking-for-feedback-updates-to-github-issue-templates-and-labels/) into the team's GitHub repository and processes. These were introduced with the goal of reducing complexity, opening up more processes to more contributors, and preparing for future updates to the Learn WordPress website itself. In this workshop, I will walkthrough these updates and demonstrate the new processes live. It'll be a great chance to see the new workflows in action, ask your questions, and even provide feedback on how things could be even better.
- Audience (User, Developer, Designer, Contributor, etc.): Contributors
- Experience Level (Beginner, Intermediate, Advanced, Any): Any

# Learning Objectives

* Use Training Team specific GitHub workflows to automate tasks
* Create and triage GitHub issues effectively
* Find documentation that explains GitHub processes and report issues

# Related Resources and Other Notes

# Automation Code

#online-workshop#

**Comment by jonathanbossenger** [comment]
@bsanevans let me know if you need a co-host for the December 14th event.

**Comment by SierraTR** [comment]
@bsanevans I'm available to co-host for the 08:00 UTC December 14th event. Wasn't sure if Johnathan volunteered for both...

**Comment by kaitohm** [comment]
Thank you both for volunteering! @jonathanbossenger , @SierraTR actually reached out in Slack first, asking if he could help out in any way, so I'll assign him co-host this time around 😃

**Comment by SierraTR** [comment]
Ben, I screwed that up - I can do the 0 UTC, which is 4 pm my time. The 8 UTC is midnight my time - way past my bed time and more suited for Jonathan.  I apologize for the mix-up.

**Comment by kaitohm** [comment]
No worries, Tracy! That's actually perfect. I've listed both of you as co-hosts then, one for each session 🙌

**Comment by kaitohm** [comment]
Video has been uploaded here: https://wordpress.tv/2023/12/15/a-walkthrough-of-the-github-process-updates-in-the-wordpress-training-team/
