### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2075]
# Learning Objectives

A brief introduction to CSS, how CSS can be added to an HTML page, and how to apply CSS to elements. Wrap up with additional links for further reading. 

# Relevant Links

- [CSS on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS)
- [CSS on Web.dev](https://web.dev/learn/css)
- [freeCodeCamp Responsive Web Design Course](https://www.freecodecamp.org/learn/2022/responsive-web-design/)

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [ ] Description and Objectives finalized
- [x] Lesson created and announced to the team for Q/A review
- [ ] Lesson submitted and published to WPTV
- [ ] Lesson transferred to YouTube
- [ ] Lesson reviewed and ready to publish
- [ ] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/the-programming-languages-of-wordpress/02-css.md

Video for review

https://github.com/WordPress/Learn/assets/180629/92366eec-d87a-48c7-b559-84c5608c29cb

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

Hi @jonathanbossenger, everything looks good—I just spotted one editing glitch: At 0:50, you start to type `style=` inside the `h1` element, then it disappears, and you go back to demonstrate it at 1:00 (after the explanation).

**Comment by SierraTR** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ x] Learning outcomes/objectives are clear.
- [x ] Technical concepts introduced in the content are accurate.
- [ x] The speed of demonstrations are easy to follow.
- [ x] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [x ] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Looks good. I second @ironnysh comment about needing a small video edit at the timestamp listed above. And I will assume that styling within the block editor will be covered in a subsequent lesson or pathway.

**Comment by jonathanbossenger** [comment]
Thank you @ironnysh and @SierraTR, another video editor glitch

Uploaded the fixed version


https://github.com/WordPress/Learn/assets/180629/f9baa0a0-7d6e-4477-ab9d-a03ccc68b273

@SierraTR to your last question, yes, this is purely an introduction to CSS as a language for the pure beginner, we will dive deep into styling in the block editor in later lessons.

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/css/
