### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2076]
# Learning Objectives

A brief introduction to JavaScript, how JavaScript can be added to an HTML page, and some examples of what is possible with JavaScript. Include an introduction to JavaScript libraries and frameworks, like the React framework. Wrap up with additional links for further reading.

# Relevant Links

- [JavaScript on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript)
- [JavaScript on Web.dev](https://web.dev/learn/javascript)
- [freeCodeCamp JavaScript Algorithms and Data Structures certification](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/)

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for Q/A review
- [ ] Lesson submitted and published to WPTV
- [ ] Lesson transferred to YouTube
- [ ] Lesson reviewed and ready to publish
- [ ] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/the-programming-languages-of-wordpress/03-javascript.md

Video for review

https://github.com/WordPress/Learn/assets/180629/ce27fb50-4ae7-402e-b561-31d0fb61ce49

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by cynthianorman** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

- "client-side" needs a hyphen
- Your example is great for illustrating the fundamentals and I really like your use of the lorem ipsum for photos (I may have to steal that idea from you)
- I'm wondering if we could provide a few more details with respect to the various ways to add JavaScript to a WordPress site:
1. Using a 3rd party WordPress JavaScript plugin
2. Using your child theme's functions.php file
3. Using a custom plugin

- You could follow up with stating that "you will be learning more about these methods of adding JavaScript to a WordPress site in future lessons"
- Another idea would be to add this additional link https://developer.wordpress.org/themes/basics/including-css-javascript/

**Comment by ironnysh** [comment]
Hi @cynthianorman, re point number 4 (adding JavaScript to a WordPress site), it’s mentioned at 3:08.

**Comment by cynthianorman** [comment]
@jonathanbossenger I'm looking more closely at the theme module's lessons today and see that the inclusion of JS is covered there so I'm happy with leaving the details until then if you are
https://developer.wordpress.org/themes/core-concepts/including-assets/#including-javascript

**Comment by SierraTR** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x ] Learning outcomes/objectives are clear.
- [x ] Technical concepts introduced in the content are accurate.
- [ x] The speed of demonstrations are easy to follow.
- [x ] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Another good one Johnathon. Short and to the point. In the additional resources closing you might consider pointing to additional learning pathway lessons/modules that will be available.

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/javascript/
