### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2077]
# Learning Objectives

A brief introduction to PHP, and some examples of PHP code. Use the example HTML code from the HTML lesson, and show how that might be achieved using PHP. Wrap up with links to the PHP Documentation for further reading.

# Relevant Links

- [PHP Getting Started guide](https://www.php.net/manual/en/getting-started.php)
- [Official PHP Documenation](https://www.php.net/docs.php)
- [Learn PHP for Beginners on freeCodeCamp](https://www.freecodecamp.org/news/the-php-handbook/)

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for Q/A review
- [ ] Lesson submitted and published to WPTV
- [ ] Lesson transferred to YouTube
- [ ] Lesson reviewed and ready to publish
- [ ] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/the-programming-languages-of-wordpress/04-php.md

Video for review


https://github.com/WordPress/Learn/assets/180629/871af25f-6c73-4f68-b6ed-f0df11d19a9d

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Hi @jonathanbossenger, a spot-on tutorial, as usual :-)

Two minor comments:
1. The Learning Objectives [above](https://github.com/WordPress/Learn/issues/2077#issue-2025546602) mention two examples that are missing from the video:
> a more basic "hello world" example, as well as an example of processing some form data.

2. Just a thought: How about showing what a WordPress PHP page looks like "behind the scenes" (either the dashboard or a theme page mentioned in the video.)

**Comment by jonathanbossenger** [comment]
Hey @ironnysh, thanks for the feedback

> The Learning Objectives https://github.com/WordPress/Learn/issues/2077#issue-2025546602 mention two examples that are missing from the video:

Yeah, when I wrote the learning objectives that was the idea, but as I wrote the scripts for all the lessons in this module, I liked the idea of using the header color change as the example for all the different languages. 

Personally, I also hate hello world, it's so predictable 😁 

I've updated the learning outcome to match the content.

> Just a thought: How about showing what a WordPress PHP page looks like "behind the scenes" (either the dashboard or a theme page mentioned in the video.)

Ooo, not going to lie, I think that's a great idea, I'm going to do that for both the dashboard and the front end page I use in the video examples. Thanks for this!

**Comment by ironnysh** [comment]
> Personally, I also hate hello world, it's so predictable 😁

😂 Fair point

**Comment by SierraTR** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ x] Learning outcomes/objectives are clear.
- [x ] Technical concepts introduced in the content are accurate.
- [x ] The speed of demonstrations are easy to follow.
- [x ] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [x ] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Looks good - were you going to make those page example changes suggested above in this video or a follow-on video?

**Comment by jonathanbossenger** [comment]
Updated video with suggested changes.


https://github.com/WordPress/Learn/assets/180629/d499db91-e1b4-4904-a7b2-2b22f75d4e99

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/php/
