### ISSUE TITLE
WordPress Hooks

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2079]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson
- Content title: WordPress Hooks
- Topic description: Introduce the concept of Hooks during a WordPress request
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Any

# Learning Objectives

- Identify what hooks are
- Describe how hooks work
- Explain how to use hooks with an example

# Related Resources and Other Notes
- https://developer.wordpress.org/plugins/hooks/
- https://developer.wordpress.org/apis/hooks/

**Comment by jonathanbossenger** [comment]
# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for Q/A review
- [x] Lesson submitted and published to WPTV
- [x] Lesson transferred to YouTube
- [x] Lesson reviewed and ready to publish
- [x] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script

https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/wordpress-hooks/01-hooks.md

**Comment by jonathanbossenger** [comment]
Video for review


https://github.com/WordPress/Learn/assets/180629/e8d7baf4-d3dd-4c33-b0a8-c5a3e9d8d819

**Comment by TinaCollier** [comment]
Hi @jonathanbossenger ,

I was attempting to review the video tutorial, but the video isn't accessible. Do you have a link to the video available?

<img width="512" alt="Screenshot 2024-02-27 at 7 22 04 AM" src="https://github.com/WordPress/Learn/assets/102442293/99d41bba-3929-4a66-af6a-68810b8d1232">

**Comment by jonathanbossenger** [comment]
Hi @TinaCollier I just tested the videos now, and they do work as expected. It's possible that there was a problem with the content delivery network at the time you were trying to review.

Would you be able to try again?

**Comment by backpocketACE** [comment]
I didn't have any issues with the video, but I have had times where it stops midway. I refreshed the page and started again where I left off. 

- [x ] Learning outcomes/objectives are clear.
- [x ] Technical concepts introduced in the content are accurate.
- [x ] The speed of demonstrations is easy to follow.
- [x ] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [x ] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines] and [Promotional Guidelines] are being followed.
- [x ] Media assets are all in the public domain ([CC0]).

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Looks good! :-)

**Comment by iankuan** [comment]
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations is easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines] and [Promotional Guidelines] are being followed.
- [x] Media assets are all in the public domain ([CC0]).

This is one of the neatest and clearest introduction for me. After wathcing this, I got one futher question about where to apply. It'll be cool to give more practical examples I could apply.

**Comment by jonathanbossenger** [comment]
> After wathcing this, I got one futher question about where to apply. It'll be cool to give more practical examples I could apply.

@yan-kuan thanks for the feedback. Once the videos are uploaded and the lessons are created on Learn.WordPress.org, I do intend to add a practical activity to allow learners to practice what they have learned. 

Out of interest sake, what is your question about where to apply?

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/wordpress-hooks/

**Comment by iankuan** [comment]
> > After wathcing this, I got one futher question about where to apply. It'll be cool to give more practical examples I could apply.
> 
> @yan-kuan thanks for the feedback. Once the videos are uploaded and the lessons are created on Learn.WordPress.org, I do intend to add a practical activity to allow learners to practice what they have learned.

That'll be awesome : )
> 
> Out of interest sake, what is your question about where to apply?

It'll be great to have an use case most people will need it. People can compare before and after. But I have no idea about it yet.

I came up with this idea because I just finished the another video review about spam management. I could immediately apply to my website. But I know WordPress developerment is another scenario, so just provide my oppion and want to learn some more from you : )
