### ISSUE TITLE
WordPress Filter Hooks

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2081]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson
- Content title: WordPress Filter Hooks
- Topic description: Explain the concept of filter hooks, how they work, and how to use them.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Any

# Learning Objectives

- Identify what filter hooks are
- Describe how filter hooks work
- Explain how to use filter hooks with an example

# Related Resources and Other Notes
- https://developer.wordpress.org/plugins/hooks/filters/
- https://developer.wordpress.org/apis/hooks/filter-reference/
- https://learn.wordpress.org/tutorial/wordpress-filter-hooks/

**Comment by jonathanbossenger** [comment]
Original tutorial content: https://learn.wordpress.org/tutorial/wordpress-filter-hooks/

**Comment by jonathanbossenger** [comment]
# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for Q/A review
- [x] Lesson submitted and published to WPTV
- [x] Lesson transferred to YouTube
- [x] Lesson reviewed and ready to publish
- [x] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: 

https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/wordpress-hooks/03-filter-hooks.md

**Comment by jonathanbossenger** [comment]
Video for review:


https://github.com/WordPress/Learn/assets/180629/76db3243-1d00-4964-969c-954a9ae382b4

**Comment by backpocketACE** [comment]
I watched Hooks, Action Hooks, I might as well finish with Filter Hooks. :) 
I had playback issues with this video at around the 3-minute mark. I refreshed and rewatched it from the beginning. 

- [ x] Learning outcomes/objectives are clear.
- [ x] Technical concepts introduced in the content are accurate.
- [ x] The speed of demonstrations is easy to follow.
- [ x] The narration audio matches what is shown visually.
- [ x] Spelling and grammar are correct.
- [ x] Sound quality is consistent throughout the video.
- [ x] [Brand Usage Guidelines] and [Promotional Guidelines] are being followed.
- [ x] Media assets are all in the public domain ([CC0].

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Same here, @JunebackpocketACE :-))

After watching all three, I wonder if it would make sense to show the snippets from the other lessons on screen, so people can better orient themselves inside the `functions.php` file. On the other hand, in the first tutorial (_Hooks_) you demonstrate the functionality using a plugin, which means going back to record a new section.

**Comment by jonathanbossenger** [comment]
> After watching all three, I wonder if it would make sense to show the snippets from the other lessons on screen, so people can better orient themselves inside the functions.php file. On the other hand, in the first tutorial (Hooks) you demonstrate the functionality using a plugin, which means going back to record a new section.

Yeah, this one I struggle with a lot, especially in the context of learning pathway lessons vs stand-alone tutorials. How much is too much/how little is too little.

I'm going to make a note of this, but publish the lesson as is anyway. If we get feedback from learners that it's confusing, I can always add the extra bits.

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/filter-hooks/
