### ISSUE TITLE
Feedback - typo on handbook getting started page

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Learn#2083]
## Step-by-step reproduction instructions (optional)

1. Go to https://make.wordpress.org/training/handbook/getting-started/
2a) Second sub-heading "Where we communicate"
- Current text: This is the team’s public facing discussion place. All decisions should be discussed and announced in blog posts to allow the widest audience to participate. These are also indexed by search engines and leave a public record of what the Training Team has worked on through it’s history."
- Change "it's history" should be "its history"

2b) Matrix
Can a link to the Matrix chat be added under the Slack section?
There will be need to be multiple changes to Slack references in the future based on the Slack migration plan, but for now, a link to start people using it and testing how it works for new contributors would be helpful.

2c) Fourth sub-heading WordPress.org account and in other sections
Suggest avoiding all references in the handbook to "you'll" and "you'd" as this can be confusing for people using speaking browsers for accessibility or practicality, and these can be difficult for people who are translating as they read.

The same for "we'd" which often will get read as 'wed' or 'weed'. This appears in the penultimate paragraph on the page.

2d) GitHub sub-heading
Change link word from 'here' as it is not good for accessibility. A descriptive word for the link is recommended.

2e) Find your interest sub-heading
Comma not needed before 'too'. "After you make your first contribution in one area, you are always welcome to come back and onboard to an additional area, too"

## Other information (optional)

Reviewed Getting started page as part of end of year tasks highlighted in training meeting today (Dec 5. 2023)

**Comment by kaitohm** [comment]
//handbook

**Comment by ghost** [comment]
2a- already changed
2b- WordPress has decided not to go with Matrix so I skipped that suggestion. 
2c- I went through the handbook page and removed all contractions as per suggestion. 
2d- already changed
2e- removed comma.
