### ISSUE TITLE
Theme structure

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2085]
# Learning Objectives

Walks through how a theme’s files and folders are structured following WordPress standards.

The learning objectives are to:

1. Familiarize yourself with the folders and files used in a WordPress theme.
2. Describe the required and optional files needed to create a block theme.
3. List the standard folders used with a block theme.

# Relevant Links
https://developer.wordpress.org/themes/core-concepts/theme-structure/

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for review
- [x] Lesson reviewed
- [x] Lesson video submitted and published to WPTV
- [x] Lesson created on Learn.WordPress.org 
- [x] Lesson video published to YouTube
- [x] Lesson on Learn.WordPress.org updated with YouTube video
- [x] Lesson published to Learn.WordPress.org

**Comment by cynthianorman** [comment]
Uploading Theme Structure _C.mp4…

**Comment by cynthianorman** [comment]
This Beginner Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

https://youtu.be/vWK8kCDQtS4 (unlisted video)

**Comment by jonathanbossenger** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great overview of the theme structure.

**Comment by cynthianorman** [comment]
@jonathanbossenger I appreciate your review - thank you!

**Comment by ironnysh** [comment]
Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

+1 to Jonathan’s review 😀 Great intro, @cynthianorman

**Comment by cynthianorman** [comment]
Thanks so much for taking the time to provide your feedback @ironnysh

**Comment by cynthianorman** [comment]
@jonathanbossenger I've uploaded this video to WordPress.tv and published it. We still need to add the transcript. Thank you!

**Comment by jonathanbossenger** [comment]
Video published to YouTube: https://youtu.be/ymPcbKVYsWo

When you have a moment, please add the [Chapter Markers](https://make.wordpress.org/training/handbook/lessons/upload-your-video/#chapter-markers) for the video as a comment in this issue.

**Comment by cynthianorman** [comment]
@jonathanbossenger 
### YouTube Chapters
(0:09) Learning objectives
(0:27) Familiarize yourself with the folder and files used in a WordPress theme
(1:44) Describe the required and optional files needed to create a block theme
(4:13) List the standard folders used with a block theme
