### ISSUE TITLE
Main stylesheet

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2086]
# Learning Objectives

Explains the importance of the theme’s style.css file and how to use it.

The learning objectives are to:

1. Create the style.css file header to configure data about the theme.
2. Describe the list of header fields available within a theme's style.css file.
3. Add the necessary header field to designate the parent theme’s folder in a child theme.

# Relevant Links
https://developer.wordpress.org/themes/core-concepts/main-stylesheet/

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for review
- [x] Lesson reviewed
- [x] Lesson video submitted and published to WPTV
- [x] Lesson created on Learn.WordPress.org 
- [x] Lesson video published to YouTube
- [x] Lesson on Learn.WordPress.org updated with YouTube video
- [x] Lesson published to Learn.WordPress.org

**Comment by cynthianorman** [comment]
This Beginner Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

https://youtu.be/wQ0GYGHWKMU (unlisted)

**Comment by jonathanbossenger** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

An excellent overview of the theme style.css file.

**Comment by cynthianorman** [comment]
Thanks @jonathanbossenger

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great tutorial, @cynthianorman. Referencing the header that defines the child-parent theme relationship is especially useful 👏

**Comment by cynthianorman** [comment]
Thanks so much for your review @ironnysh. Your feedback is important to me!

**Comment by cynthianorman** [comment]
@jonathanbossenger I've uploaded this video to WordPress.tv and published it. We still need to add the transcript. Thank you!

**Comment by jonathanbossenger** [comment]
Video published to YouTube: https://youtu.be/z3EynqghTbQ

When you have a moment, please add the [Chapter Markers](https://make.wordpress.org/training/handbook/lessons/upload-your-video/#chapter-markers) for the video as a comment in this issue.

**Comment by cynthianorman** [comment]
@jonathanbossenger 
### YouTube Chapters
(0:09) Learning objectives
(0:39) Create the style.css file header to configure data about the theme
(2:08) Describe the list of header fields available within a theme's style.css file
(4:48) Add the necessary header field to designate the parent theme’s folder in a child theme
