### ISSUE TITLE
Including assets

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2089]
# Details

- Content type: Lesson
- Content title: Custom functionality
- Topic description: A guide on including CSS, JavaScript, and images in your themes.
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

The learning objectives are to:

- Familiarize yourself with utility functions to include assets in your theme.
- Include CSS in your theme either using stylesheets or inline styles.
- Include JavaScript in your theme by either using an external file or inline JavaScript.
- Include images in your theme.
- Include fonts in your theme.

# Relevant Links
https://developer.wordpress.org/themes/core-concepts/including-assets/

**Comment by cynthianorman** [comment]
This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under Guidelines for reviewing content. Thank you for your contribution! ✨

https://youtu.be/mxEe9HquA4s

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great lesson, @cynthianorman.

Watching this, I thought it might be nice to add an explanation on how to [include fonts](https://developer.wordpress.org/themes/global-settings-and-styles/settings/typography/#registering-web-fonts-font-faces). What do you think?

**Comment by cynthianorman** [comment]
@ironnysh I was originally going to then opted out when I learned of the font library BUT of course there are many themes out there including fonts via functions.php so I'll add it in

Thank you!

**Comment by ironnysh** [comment]
The Font Library is a real _finallly_ for non-coders :-) But yeah, including fonts in the theme is very common. Check this out, as well: https://make.wordpress.org/core/2024/03/14/new-feature-font-library/.

**Comment by digitalchild** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

A nice overview for including assets @cynthianorman 

2:20 - You mention that they are located within the assets, JS folder. It might be a good visual to collapse the assets folder on the left to show where it is located, so there is no confusion.

**Comment by cynthianorman** [comment]
Thank you for your feedback @digitalchild.

**Comment by jonathanbossenger** [comment]
https://youtu.be/5Q9vRmDgKJ4

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### YouTube chapters
(0:07) Learning objectives
(0:30) Describe how to enqueue styles and scripts
(1:09) Include CSS in your theme either using stylesheets or inline styles
(1:59) Include JavaScript in your theme by either using an external file or inline JavaScript
(2:33) Include images in your theme
(3:01) Include fonts in your theme.
(4:14) Next steps

**Comment by cynthianorman** [comment]
//publish
