### ISSUE TITLE
Global Settings and Styles

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2090]
# Learning Objectives

Gives a basic overview of how the theme.json file works in themes with learning pathways to more advanced topics.

The learning objectives are to:

1. Describe the purpose of a WordPress theme's theme.json file.
2. Familiarize yourself with the JSON format and the structure of theme.json.
3. Understand the hierarchy used for loading the setting and style configurations of a website.

# Relevant Links
[Theme Handbook: Global Settings & Styles](https://developer.wordpress.org/themes/core-concepts/global-settings-and-styles/)
[Block Editor Handbook: Global Settings & Styles](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/)
[Block Editor Handbook: theme.json Version 2](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/)
https://learn.wordpress.org/tutorial/introduction-to-theme-json/
[Theme.json lesson plan](https://github.com/WordPress/Learn/issues/652)

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for review
- [x] Lesson reviewed
- [x] Lesson video submitted and published to WPTV
- [x] Lesson created on Learn.WordPress.org 
- [x] Lesson video published to YouTube
- [x] Lesson on Learn.WordPress.org updated with YouTube video
- [x] Lesson published to Learn.WordPress.org

**Comment by cynthianorman** [comment]
This Beginner Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

https://youtu.be/DkAqKbylDl8 (unlisted)

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

@cynthianorman kudos on successfully balancing a friendly introduction with relevant technical deep-dive.

Two thoughts that came up when I watched the tutorial:
- At 0:48, you mention that theme developers would have used the Customizer to build features for end users in classic themes. That's only partially true, and could confuse people about the use cases of the Customizer in block themes.

- At 5:10, you mention the pattern slugs reference assets pulled from the public Pattern directory but as far as I know, it’s also where developers can reference the theme’s custom patterns.

**Comment by cynthianorman** [comment]
ok @ironnysh you are making me rethink those 2 items for sure. I'm under the impression that as long as our patterns are placed within the patterns folder they are auto-registered. I'm wondering if mentioning the PHP registration method for patterns not found within the patterns folder is worth mentioning here or should we wait for the Intermediate LP lessons?

**Comment by ironnysh** [comment]
Hi @cynthianorman, thanks for being open for having this mini discussion.
**Patterns**: I found this in the [Theme Handbook](https://developer.wordpress.org/themes/global-settings-and-styles/patterns/) of the official Developer resources:
> The patterns property in theme.json lets you bundle patterns from the WordPress Pattern Directory with your theme.

Given that, it's probably better to stick with your original plan and pick this up in more advanced lessons.

**Customizer**: maybe adding a short "disclaimer" would do the job? Something like, "the Customizer has different uses, and some theme developers also used to..."

**Comment by cynthianorman** [comment]
@jonathanbossenger I've uploaded this video to WordPress.tv and published it. We still need to add the transcript. Thank you!

**Comment by jonathanbossenger** [comment]
Video published to YouTube: https://youtu.be/FPCN2E5vEhc

When you have a moment, please add the [Chapter Markers](https://make.wordpress.org/training/handbook/lessons/upload-your-video/#chapter-markers) for the video as a comment in this issue.

**Comment by cynthianorman** [comment]
@jonathanbossenger 
### YouTube Chapters
(0:09) Learning objectives
(0:32) Describe the purpose of a WordPress theme's theme.json file
(1:47) Familiarize yourself with the JSON format and the structure of theme.json
(5:17) Understand the hierarchy used for loading the setting and style configurations of a website
(7:24) WordPress developer resources

**Comment by jonathanbossenger** [comment]
Thanks, Chapters added to YT
