### ISSUE TITLE
Feedback - Embeds block not appearing correctly on the front end

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2091]
## Type of feedback
//dev 

## Description

Videos are not displaying correctly on the front end when added via the Embeds block. The video is more narrow than the text. 

## Step-by-step reproduction instructions (optional)
Please list the steps needed to reproduce or verify the feedback. For example:
1. Add a YouTube video to a Sensei lesson via the Embeds block.
2. Preview on the front end.

## Screenshots or screen recording (optional)
If possible, please upload a screenshot or screen recording illustrating the feedback. 
<img width="1917" alt="image" src="https://github.com/WordPress/Learn/assets/89751452/a0fc3923-791e-435b-9c49-bdc13bf86f42">

## Other information (optional)
Please see this thread for more details: https://a8c.slack.com/archives/C02P7FHLVR9/p1701978404354329

**Comment by jonathanbossenger** [comment]
It looks like the theme needs to have support for[ responsive embeds](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#responsive-embedded-content)

**Comment by jonathanbossenger** [comment]
@westnz can I check, is the plan to start publishing Learning Pathway Lessons before the new site launch is completed?

The reason I ask is that if we only need this once the new site is launched, then the new theme will have support for responsive embeds by default, and this work will not be required.

**Comment by westnz** [comment]
Good point! The aim is to publish the learning pathways end of July. I assume the new site will also be launched before that or coincide with the publishing of learning pathways.

**Comment by westnz** [comment]
@jonathanbossenger, if we aim to publish some pathways before launch, would this bug not need to be fixed before the new site launch?

**Comment by jonathanbossenger** [comment]
@westnz yeah, that's a valid point. I am doing some other dev work with @bsanevans next week for [student reporting](https://github.com/WordPress/Learn/pull/2161), so I will look into that at the same time.

**Comment by jonathanbossenger** [comment]
@westnz I have created the [PR](https://github.com/WordPress/Learn/pull/2179) to fix this, and it appears to work locally, but we'll just have to test it on Learn. I will get this merged and deployed alongside the student reporting fix sometime next week.
