### ISSUE TITLE
Feedback - Ticket 168843

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2093]
## Type of feedback

//content 

## Description

The narrator says they are using the Gutenberg plug in, but doesn't say which one. I'm new to this, but I know it's a block editor. There are two Gutenberg block related plugins.

## Step-by-step reproduction instructions (optional)

This is mentioned at 0:16 in the tutorial.

**Comment by ghost** [comment]
@digitalchild What advice do you have to fix this? I looked at the plugin site and there is only one Gutenberg plugin. The others have other wording with them. Or I just remove the whole phrase from the video & transcript?

**Comment by digitalchild** [comment]
@lada7042 Are you using the stand alone Gutenberg plugin or the built-in Block editor?

**Comment by ghost** [comment]
@digitalchild I used 2024 theme with 6.4. and I had the Gutenberg plugin turned on which I probably didn’t even need since most all the updates were in the core at that point. I don’t understand what you mean about built- in Block editor? Thanks for helping

**Comment by digitalchild** [comment]
@lada7042 Gutenberg and the block editor are essentially the same thing. However, there is a standalone Gutenberg plugin that includes all the latest test / beta features that are not yet available in the WordPress core. Generally speaking, you wouldn't install the standalone plugin unless you are testing specific features currently not available in the block editor.

**Comment by ghost** [comment]
@digitalchild Thanks for the link to the information. Definitely did not use the the standalone Gutenberg plugin. So, how should I handle my issue?

**Comment by digitalchild** [comment]
@lada7042 Generally speaking, the terminology is "The Block editor" which is powered by Gutenberg.  

> At the time of this recording, I’m using WordPress version 6.4 and the Gutenberg plugin. 

Here you mention the Gutenberg plugin which is causing the confusing. As there isn't a plugin being used, but the build-in block editor. 

I would suggest updating to 

> At the time of this recording, I’m using WordPress version 6.4 with the block editor.

**Comment by ghost** [comment]
@digitalchild thank you so much for the recommendation. I am assigning the ticket to me. I will update the video but will need till after the holidays. So I am putting Jan. 12 as a goal. Do I need to change any other settings? I am new to feedbacks.

**Comment by CharEdwards** [comment]
My name is Bruce Edwards. My twenty twenty-four username is Brucewildfire.
Thanks for the excellent tutorial Laura!  
I'm an absolute WP newbie so am not sure about how best to contact you and how to use this. 
Ticket?  
I too was confused by the reference to Gutenberg and agree with you changing it to "At the time of this recording, I’m using WordPress version 6.4.2 with the block editor." 
Could please also expand your tutorial to explain how to add sub-sub-menus/drop-downs and sub-sub-sub-menus/drop-downs etc. How many levels down does twenty twenty-four permit?
My primary comms means is email **[email address removed by admin]** so could you please email me so I don't miss your reply? Do you have an estimated time of completion for your updated video?
Happy New Year!

**Comment by ghost** [comment]
Updated- That was more difficult than I thought. I ended up removing the words "Gutenberg plugin". Here is the link for the updated version - https://wordpress.tv/2024/01/15/how-to-create-a-menu-with-the-navigation-block-3/ Thank you for your help and input. Every day is a learning experience.

**Comment by CharEdwards** [comment]
Thanks for the prompt reply Laura! I'm glad that this got through to you.
How can I create sub-sub-menus with twenty twenty-four? How many levels
down can we go?
Explaining this would be a valuable 5th topic for your clear and excellent
tutorial.
Bruce

**Comment by ghost** [comment]
@CharEdwards Thank you for your questions. The place to find help on issues you are having is the Support forum- [https://wordpress.org/support/welcome/] You can also look for upcoming Learn WordPress Meetups- [https://www.meetup.com/learn-wordpress-online-workshops/] or search for a local WordPress meetup. A lot of them are virtual and offer support for individual questions. I also removed your email. GitHub is open-source so you don't want personal info. out there.
