### ISSUE TITLE
Bangla Translation for What kind of WordPress theme do I have: classic, block, or something else?

### ISSUE THREAD

**Issue by faisalahammad** [WordPress/Learn#2094]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/what-kind-of-wordpress-theme-do-i-have-classic-block-or-something-else/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @devmuhib009
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by faisalahammad** [comment]
Here is the translated doc file:

https://docs.google.com/document/d/1o22gUTjfTFU2xL8c9kVMCrJXpI4LUDR4z8_VPzcnl-k/edit?usp=sharing

Could you please review and share your feedback, @devmuhib009?

**Comment by devmuhib009** [comment]
Sure, I will review the translation and update here soon. 😊

**Comment by devmuhib009** [comment]
//assign

**Comment by devmuhib009** [comment]
>বাম হাতের সাইডবারে 

বামদিকস্থ সাইডবারে

> তাহলে আপনি একটি হাইব্রিড বা সাধারণ থিম ব্যবহার করতে পারেন।

তাহলে আপনি সম্ভবত একটি হাইব্রিড বা সার্বজনীন থিম ব্যবহার করছেন। 

>তারা দুর্লভ, কিন্তু বিদ্যমান, এবং ক্লাসিক এবং ব্লক উভয় থিমের উপাদান ব্যবহার করে।

এগুলো দুর্লভ, কিন্তু বিদ্যমান, এবং ক্লাসিক ও ব্লক উভয় ধরণের থিমের উপাদান ব্যবহার করে।

**Comment by devmuhib009** [comment]
@faisalahammad please update these modifications, so we can move forward.  🚔🚘

**Comment by faisalahammad** [comment]
@devmuhib009, Sorry for the delay. I've made the changes. Could you please check and confirm?

**Comment by devmuhib009** [comment]
You used "বাম হাতের সাইডবারে" multiple times. I think all should keep same. So can you please replace all others with same line please "বামদিকস্থ সাইডবারে".

**Comment by faisalahammad** [comment]
I've made the corrections. I apologize for missing those strings that needed to be updated. @devmuhib009

**Comment by devmuhib009** [comment]
@faisalahammad, Thanks a lot for updating the file. It's now ready for publish. @bsanevans please take care of this translation please.

**Comment by kaitohm** [comment]
Sorry for the delay here, folks 🙇‍♂️ 

@faisalahammad Please continue from step 5 in this handbook page: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video You can move the translation into this post: https://learn.wordpress.org/wp-admin/post.php?post=56476&action=edit

**Comment by faisalahammad** [comment]
Thank you, @bsanevans. I have submitted the article and uploaded the subtitle. Could you please proceed and approve both?

**Comment by kaitohm** [comment]
Wonderful! I've published this content here: https://learn.wordpress.org/tutorial/bn-what-kind-of-wordpress-theme-do-i-have-classic-block-or-something-else/

Thank you again for your contribution 🙌
