### ISSUE TITLE
SyntaxHighlighter Code block: long code shows horizontal scrollbar

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/Learn#210]
Hi

@courane01 Courtney encouraged me to switch out the Code block and instead use the SyntaxHighlighter Code block. 
It seems like a good idea, but long code brings a horizontal scrollbar.

Setting up a local WordPress Development Environment for Core
https://learn.wordpress.org/?p=4248&post_type=wporg_workshop&preview=1&_ppp=a1fbfadc3d

The following shows duplicate code blocks.
Code block and the SyntaxHighlighter Code block. (At the moment I am comparing the two.)

![Screen Shot 2021-04-14 at 21 04 29](https://user-images.githubusercontent.com/5323259/114765174-23094580-9d65-11eb-8e11-6f8e519c5da2.png)

![Screen Shot 2021-04-14 at 21 04 39](https://user-images.githubusercontent.com/5323259/114765181-243a7280-9d65-11eb-8cc5-c6b71bd26342.png)

Here is the Code block issue: https://github.com/WordPress/learn/issues/207

**Comment by hlashbrooke** [comment]
If I'm not mistaken, that's the default behaviour of SyntaxHighlighter. It looks like there's a way we can force line-wrapping using CSS thought: http://notepad2.blogspot.com/2012/06/syntaxhighlighter-wrap-long-lines.html

**Comment by paaljoachim** [comment]
Hey @hlashbrooke Hugh.

It has been a while since I posted the comment.
The code block was fixed so it shows dark text in the grey box.

The SyntaxHighlighter block seems like a block made especially for Learn.
Having a way to line wrap the code will be helpful!

**Comment by hlashbrooke** [comment]
It looks like this has been resolved in a recent update, so closing this issue.
