### ISSUE TITLE
French translation for Tutorial "Posts vs. Pages: What’s the Difference?"

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Learn#2102]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/posts-vs-pages-whats-the-difference/
- Link to original content's GitHub issue (optional): N/A
- Language you'll be translating to: french
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: The translation is open for comments on a FramaPad file https://mypads2.framapad.org/mypads/?/mypads/group/learn-gd35829fb/pad/view/posts-vs-pages-what-s-the-difference-u3w2393t

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by lmwp** [comment]
Review in progress

**Comment by jennydupuy** [comment]
Great lmwp!

**Comment by lmwp** [comment]
Done .  Translation is ok.

**Comment by jennydupuy** [comment]
The content was created on learn.wordpress.org.
@bsanevans could you check the draft of the tutorial to see if everything is correct, please

**Comment by devmuhib009** [comment]
Article published here: https://learn.wordpress.org/tutorial/fr-posts-vs-pages-whats-the-difference/
Thanks @jennydupuy
