### ISSUE TITLE
Malayalam translation for Lesson Plan "Anonymizing information in the browser"

### ISSUE THREAD

**Issue by iqbalpb** [WordPress/Learn#2103]
# Details
- Link to original content: [Anonymizing information in the browser](https://learn.wordpress.org/lesson-plan/anonymizing-information-in-the-browser/)
- Link to original content's GitHub issue (optional): N/A
- Language you'll be translating to: Malayalam
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: 
- Other info: [Link to Google Doc](https://docs.google.com/document/d/1PD1pqJzc3iLe-JCsyGKmklwh4y_uJKgv-GmDT6-TLDQ/edit?usp=sharing). It is open for comments. I found a reviewer but he need some resources regrading the review process
# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
Thanks for translating this, @iqbalpb 🙌 

In order to recognize the reviewer's contribution, could you ask them to comment in this GitHub thread, too, please? This page provides information on how to conduct a translation review: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translation-reviews/

**Comment by iqbalpb** [comment]
@bsanevans Please add [Mbigul](https://github.com/mbigul) as reviewer. He is one of the [Local Manager](https://make.wordpress.org/polyglots/teams/?locale=ml_IN) for [Malayalam](https://translate.wordpress.org/locale/ml/). He is ready to contribute his time for review.

**Comment by kaitohm** [comment]
Unfortunately, due to the way the WordPress organization's GitHub is set up, I can only assign folks who have commented on an issue at least once 🙁 Just when he's completed the review is fine. If Mbigul could comment here with his review notes, I will then be able to assign him.

**Comment by mbigul** [comment]
@bsanevans Thank you for the updates. I have started to review the translation and completed half of the task. Please add me as a reviewer. I will complete the review tomorrow.

**Comment by kaitohm** [comment]
Done. Thanks!

**Comment by iqbalpb** [comment]
Thanks @mbigul for reviewing and pointing out the issue. Fixed all the mentioned issues @bsanevans

**Comment by mbigul** [comment]
I have completed the review of the document. There are a few more minor corrections

**Comment by kaitohm** [comment]
I'm back from the holidays, folks. Thanks for working on this in the meantime 🙇‍♂️ 

@iqbalpb I've sent you an email invitation to become a Contributor on https://learn.wordpress.org/. Please let me know once you've accepted. I'll then assign you to https://learn.wordpress.org/wp-admin/post.php?post=82760&action=edit so you can transfer the translated content there.

**Comment by kaitohm** [comment]
@iqbalpb Thanks for accepting the invite. Please continue from step 5 here: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#lesson-plans

**Comment by devmuhib009** [comment]
Hi @iqbalpb

I can help you updating the content. If you need any help, please write here. Thanks

**Comment by iqbalpb** [comment]
<img width="1426" alt="Screenshot 2024-05-05 at 12 14 05 PM" src="https://github.com/WordPress/Learn/assets/19872875/18779cc2-5809-4f6c-bd26-f59d9602d479">

**Comment by devmuhib009** [comment]
You will not able to publish the content. We will review the changes and publish the translation soon if everything is ok.

**Comment by devmuhib009** [comment]
Hi, I just checked you added the content, but did not save it. I restored the revised version, please check if all the content and links are correct or you can fix errors if you find any. Then save the post again, instead of trying to publish. Once you draft the post using the save button, let me know, I will publish it. Thanks

**Comment by iqbalpb** [comment]
@devmuhib009 saved as draft can you please review?

**Comment by devmuhib009** [comment]
Publish it here: https://learn.wordpress.org/lesson-plan/ml-anonymizing-information-in-the-browser/

//publish
