### ISSUE TITLE
Filter Dropdown alignment issue

### ISSUE THREAD

**Issue by DarshitRajyaguru** [WordPress/Learn#2110]
## Description
**On Page:** https://learn.wordpress.org/online-workshops/

Filter Items **DropDown** has an alignment issue. The dropdown does not properly align the middle cause of other margin-bottom CSS from the parent class.

## Steps
1. Go to https://learn.wordpress.org/online-workshops/ page.
2. Scroll down and Go to the Calendar of **Online Workshops**.
3. You have seen the issue at Filter Dropdown.(Screenshot given below)

## Screenshots
**Screenshot:** https://prnt.sc/K3FEHIiNoICQ

**Comment by kaitohm** [comment]
//dev

**Comment by jonathanbossenger** [comment]
The CSS being applied here:

```
.css-1t5ousf {
    margin-bottom: calc(8px); 
}
```

**Comment by stgeer** [comment]
@devmuhib009 if you are no longer working on this, feel free to assign to me and I can address.

**Comment by devmuhib009** [comment]
Hi, I am not working on this. Please take care of it.

**Comment by adamwoodnz** [comment]
No longer an issue, with the launch of the 2024 block theme
