### ISSUE TITLE
Script to count unique learners

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2111]
## Goal
We're looking to track the increase in learners we expect will occur when we launch Learning Pathways next year. To do this, we need to see the number of unique course subscribers (called "students" in Sensei) on Learn.

## Problem
Theoretically, this should be shown on https://learn.wordpress.org/wp-admin/admin.php?page=sensei_reports . However, due to the way bbPress is integrated with make.wordpress.org, we are only seeing a small subset there. This can be confirmed by going to https://learn.wordpress.org/wp-admin/admin.php?page=sensei_reports&course_id=8657&view=user, which shows we have at least 8,900 learners subscribed to that course alone.

## Solution
@m1r0 has written us a script that will count the number of unique learners on Learn and display this on [the Students report screen](https://learn.wordpress.org/wp-admin/admin.php?page=sensei_reports). It also includes a date filter which will only count students who started a course in that time period.

```
add_action( 'sensei_reports_overview_before_top_filters', 'wporg_learn_add_student_count_to_reports' );
function wporg_learn_add_student_count_to_reports( $type ) {
    if ( 'users' !== $type ) {
        return; // Only show the count on the students report screen.
    }
 
    $from_date = DateTime::createFromFormat( 'Y-m-d', $_GET['from_date'] ?? '', new DateTimeZone( 'UTC' ) );
    $to_date   = DateTime::createFromFormat( 'Y-m-d', $_GET['to_date'] ?? '', new DateTimeZone( 'UTC' ) );
 
    global $wpdb;
    $query = "SELECT COUNT(DISTINCT user_id)
FROM $wpdb->comments
WHERE comment_type = 'sensei_course_status'";
 
    if ( $from_date ) {
        $from_date->setTime( 0, 0, 0 );
 
        $query .= " AND comment_date_gmt >= '" . $from_date->format( 'Y-m-d H:i:s' ) . "'";
    }
 
    if ( $to_date ) {
        $to_date->setTime( 23, 59, 59 );
 
        $query .= " AND comment_date_gmt <= '" . $to_date->format( 'Y-m-d H:i:s' ) . "'";
    }
 
    $student_count = $wpdb->get_var( $query );
 
    ?>
    <div class="actions bulkactions">
        <label><?php esc_html_e( 'Total number of students', 'wporg-learn' ); ?></label>
        <input
            class="sensei-date-picker"
            name="from_date"
            type="text"
            autocomplete="off"
            placeholder="<?php echo esc_attr( __( 'From Date', 'sensei-lms' ) ); ?>"
            value="<?php echo esc_attr( $from_date ? $from_date->format( 'Y-m-d' ) : '' ); ?>"
        />
        <input
            class="sensei-date-picker"
            name="to_date"
            type="text"
            autocomplete="off"
            placeholder="<?php echo esc_attr( __( 'To Date', 'sensei-lms' ) ); ?>"
            value="<?php echo esc_attr( $to_date ? $to_date->format( 'Y-m-d' ) : '' ); ?>"
        />
        <label>: <?php echo (int) $student_count; ?></label>
    </div>
    <br>
    <?php
}
```

![image-13](https://github.com/WordPress/Learn/assets/49054298/f851f676-8c22-4b05-bbfc-f8545d604456)

## Next Steps
What is the best way to get this script deployed on Learn? (CC: @adamwoodnz )
//dev

**Comment by jonathanbossenger** [comment]
@bsanevans Adding this to the [wporg-learn plugin](https://github.com/WordPress/Learn/tree/trunk/wp-content/plugins/wporg-learn) would make the most sense. 

If this can wait till the new year, I can add a PR to have this merged when I get back from leave.

**Comment by kaitohm** [comment]
The new year will be just fine. Thanks, @jonathanbossenger 🙌

**Comment by jonathanbossenger** [comment]
Added to my todo list.

**Comment by jonathanbossenger** [comment]
@bsanevans a thought occurs. Would you like to learn to do this yourself? 

Requirements: 

1. Setting up the Learn local development environment, and creating a branch to work on
2. Once set up, I can guide you as to where to add this code
3. You create the pull request from your branch
4. I will review, and then we can ask someone from Meta to do a second round of review

Goals:

1. One more person who knows how to contribute to Learn with code
2. We can test if our new code contributor journey is clear, and improve it if not
3. You start feeling more comfortable to effect change to the codebase.

**Comment by kaitohm** [comment]
Ooh, yes please! I'd love that! Let's connect in 2024 🌟  Thanks for offering!

**Comment by SierraTR** [comment]
@jonathanbossenger @bsanevans   If it's ok with you two and the time zone thing works out, I'd like to sit in on the session. I've walked through your workshops Johnathan, but have not yet been successful in getting wp-env and a Learn local branch set up. I'll see if I can give it another try in the next week or so and see if I can find the problem.

**Comment by kaitohm** [comment]
Yay, I'd be perfectly fine with having another person sit in 👍 Let me reach out in a Slack DM and we can coordinate times.

**Comment by jonathanbossenger** [comment]
After some testing, @bsanevans reported that the count seems off, and pinged @m1r0.

@m1r0 suggested updating the query

> The current query is based on the comment date, but that date gets updated when the course status changes…
> Fortunately, there is a comment meta with the key start that stores the course start date.

```
SELECT COUNT(DISTINCT user_id)
FROM $wpdb->comments AS c
INNER JOIN $wpdb->commentmeta AS cm ON c.comment_ID = cm.comment_id
WHERE c.comment_type = 'sensei_course_status'
AND cm.meta_key = 'start'
AND cm.meta_value >= %s
AND cm.meta_value <= %s
```

Reopening this in order to get the query updated
