### ISSUE TITLE
What is a plugin?

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2113]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson
- Content title: What is a plugin? 
- Topic description: Introduce the new developer to the concept of a WordPress plugin, and what it can be used for.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Any

# Learning Objectives

- Describe what a plugin is
- Explain what plugins can be used for
- Briefly describe the structure of a plugin
- Find more information on plugin development

# Related Resources and Other Notes
- https://developer.wordpress.org/plugins/intro/what-is-a-plugin/

**Comment by jonathanbossenger** [comment]
//tutorial

**Comment by jonathanbossenger** [comment]
//tutorial

**Comment by jonathanbossenger** [comment]
//lesson

**Comment by jonathanbossenger** [comment]
# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for review
- [x] Lesson reviewed
- [x] Lesson video submitted and published to WPTV
- [x] Lesson created on Learn.WordPress.org 
- [x] Lesson video published to YouTube
- [x] Lesson on Learn.WordPress.org updated with YouTube video
- [x] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script:

https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/introduction-to-wordpress-plugins/01-what-is-a-plugin.md

**Comment by jonathanbossenger** [comment]
Video for review:

https://github.com/WordPress/Learn/assets/180629/0320c177-a24a-48f8-9f72-3a8b7c91a9c8

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Clear, concise, and informative. Great intro, @jonathanbossenger

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/what-is-a-plugin/
