### ISSUE TITLE
German translation for "Setting A Static Page As Your Homepage"

### ISSUE THREAD

**Issue by BenjaminZekavica** [WordPress/Learn#2114]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/setting-a-static-page-as-your-homepage/ 
- Language you'll be translating to: German/Deutsch (not Formal) 
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: BenjaminZekavica

# Next Steps
Here you can find the Translation and some Screenshots: 
https://drive.google.com/drive/folders/1mRJKbKhzSF5QiDAVMt7Woi4freYYKfri?usp=sharing

**Comment by kaitohm** [comment]
@BenjaminZekavica I've added you as an author on this post: https://learn.wordpress.org/wp-admin/post.php?post=56499&action=edit

We're still waiting for a review. But once reviewed, you'll be able to proceed from step 5 listed here: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#lesson-plans

**Comment by BenjaminZekavica** [comment]
@bsanevans I added the content to the page, but I can't upload images.

**Comment by kaitohm** [comment]
Thanks. We're just waiting for a review and then this is ready to publish.

I've pinged someone in the Training Team to take a look. But being the end of year, they may be absent. If you know of anyone who could review this for us, feel free to let them know, too :)

**Comment by BenjaminZekavica** [comment]
@bsanevans Review is done and I updated the content in WP Backend. It's ready for publishing :)

**Comment by kaitohm** [comment]
Great! I've replaced the screenshots with those you shared and published the lesson plan here: https://learn.wordpress.org/lesson-plan/de-setting-a-static-page-as-your-homepage/

Thank you for your contributions, Benjamin 🙌
