### ISSUE TITLE
Tutorial: Setting up your pages, posts, site logo and navigation menu

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2116]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Tutorial
- Content title: Setting up your pages, posts, site logo and navigation menu
- Topic description: Setting up the basics
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives
WordPress Kickstart: Title, tagline, logo, navigation menu, and post and page content
 - Settings: Static and blog pages
 - Categories and tags
 - Tagline, Logo, Navigation menu as part of header and footer

# Related Resources and Other Notes

### Automation Code
//tutorial

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/63547888-9cee-4093-8021-328cabe5a2b0

**Comment by ghost** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.
Great job! The tutorial gives a quick overview on how to get a basic website setup. Will this be part of the Learning Pathways? For me I am still confused by Blog Home and Home Page. Will the next video be about setting up blog, contact pages?

**Comment by westnz** [comment]
Thanks @lada7042. Yes, this will form part of the beginner learning pathway.  Here is another lesson being reviewed where I tried to cover setting the home page display: https://github.com/WordPress/Learn/issues/2099.

**Comment by ghost** [comment]
Thanks @westnz

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Hi @westnz, great tutorial. I like how you walk through setting up a complete blog in less than 10 minutes.
A quick question: Why not manage the navigation by clicking on _Navigation_ in the Site Editor (~3:45)?

**Comment by westnz** [comment]
Thanks so much @ironnysh 

> Why not manage the navigation by clicking on Navigation in the Site Editor (~3:45)?

I wanted to manage the navigation in context 😃

**Comment by ironnysh** [comment]
Greta point, hadn't thought about it this way

**Comment by SierraTR** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ x] Learning outcomes/objectives are clear.
- [x ] Technical concepts introduced in the content are accurate.
- [x ] The speed of demonstrations are easy to follow.
- [x ] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [x ] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Well done.  Again.

**Comment by westnz** [comment]
Thanks Tracy!!

**Comment by westnz** [comment]
I plan to publish by the end of this week.

**Comment by westnz** [comment]
Updated and published in Sensei as part of the draft Beginner User learning pathway.
