### ISSUE TITLE
Meeting Agenda December 19, 2023

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#2118]
Training Team meetings start at 07:00 UTC weekly on Tuesdays. Anyone is welcome to contribute to the meeting by commenting on Slack threads throughout the week. Meeting notes will be published at the end of the week to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @webtechpooja._

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- December 19 – [@rabin pal](https://profiles.wordpress.org/robinpal/)
- January 9 – Need volunteer
- January 16 – Need volunteer
- January 23 – [@NF Tushar](https://profiles.wordpress.org/nftushar/)

The final meeting for the year is Today, December 19th. We’ll resume on January 9th.

**2. Looking for feedback**

- Nothing for feedback

**3. Looking for volunteers**

- [Training Team 2023 Year-End Review](https://make.wordpress.org/training/2023/11/20/training-team-2023-year-end-review/)
  - Plan promotions with the Marketing Team
  - Establish monthly recurring onboarding Online Workshops in different timezones for training team roles
  - Figure out a method to manage localized content translation
  - Audit Handbook -- thank you to Abha and Sumit for your assistance here!

**4. Updates from last week's dev-squad triage session**

PRs triaged:
- #2098

Issues triaged 
- #1542 (closed)
- #1709 (closed)
- #2091 

**5. Other news**

- [Training Team 2023 Year In Review](https://make.wordpress.org/training/2023/12/19/training-team-2023-year-in-review/)
- [Contributor Spotlight: Laura Adamonis](https://make.wordpress.org/training/2023/12/12/contributor-spotlight-laura-adamonis/)
- [Update on Matrix Migration: Pausing the Transition](https://make.wordpress.org/project/2023/12/12/update-on-matrix-migration-pausing-the-transition/)- as per recently announced in the State of the Word - Matrix is on hold now, but please continue testing.
- [State of the Word 2023 Recap](https://wordpress.org/news/2023/12/state-of-the-word-2023-recap/)
  -  [Overflow Questions from State of the Word 2023 in Madrid, Spain](https://make.wordpress.org/project/2023/12/12/overflow-questions-from-state-of-the-word-2023/) 
-  [Toward a More Interconnected Web](https://wordpress.org/news/2023/12/episode-68-toward-a-more-interconnected-web/)
- Handbook pages updated
  - [How to Write Meeting Agendas and Recap Posts](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-to-write-a-meeting-agenda-or-recap/)
- [WordCamp Nepal](https://nepal.wordcamp.org/2024/) is on January 12- 13. Pooja will be leading the Training Table at Contributor Day on January 12
- I'm hosting my last meeting as a Team Rep.
- The December Monthly Update and January Learn Newsletters will be posted on January 8th, 2024.

**6. Meetings adjustment for 2024**
- Global meetings will take place on Thursday at 00:00 UTC. First meeting of the new year is on Jan 11
- Reminder about coffee hour - do folks still want to do this?
- Call for WordCamp Asia Contributor Day table leads volunteers

**7 Badges Awarded**
Contributor badges awarded to:
- [@Faisal Ahammad](https://wordpress.slack.com/team/U016RBRCP1U)
- [@Maya](https://wordpress.slack.com/team/U047ASADQPL)

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

See our [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review the following content.

## 4. Faculty Check-in
- I's time for a Faculty check-in! @faculty please answer any that apply:
  - What have you been working on and how has it been going?
  - Anything you’ve accomplished since the last meeting?
  - Do you have any blockers?
  - Can other Faculty or Training Team members help you in some way?

## 5. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - Update and next steps on the [Guidelines for creating, reviewing, and publishing lessons](https://make.wordpress.org/training/2023/11/29/request-for-feedback-lesson-handbook-pages/) handbook pages.
    - Thanks to everyone who shared their feedback on the guidelines
    - Jonathan would like to publish the first version of these guidelines to the Training Team Handbook by Friday, 22 December 2023
    - There may still be some open discussions in Google Docs. Jonathan would like to suggest that we publish what we have by Friday and pick up any open discussions in 2024 to revise the handbook pages accordingly.

## 6. Open Discussions
**1.  Let’s celebrate achievements from the year**
- Share your achievements/journey/stories/Plans or Goals for next year
- How you contributed to the Training Team

If you have topics you’d like to discuss in the meeting, please leave them as comments on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by webtechpooja** [comment]
@jonathanbossenger Could you share an update from last week's dev-squad triage session, please? 🙇‍♂️

**Comment by jonathanbossenger** [comment]
Under the Learning Pathways on Learn WordPress project discussion, could we share an update and next steps on the [Guidelines for creating, reviewing, and publishing lessons](https://make.wordpress.org/training/2023/11/29/request-for-feedback-lesson-handbook-pages/) handbook pages.
- Thanks to everyone who shared their feedback on the guidelines
- I would like to publish the first version of these guidelines to the Training Team Handbook by Friday 22 December 2023
- There may still be some open discussions in the Google Doc, I'd like to suggest that we publish what we have by Friday, and pick up any open discussions in 2024, to revise the handbook pages accordingly.

**Comment by courtney-pk** [comment]
Can we please bring back the Faculty update thread and make it a permanent part of subsequent agendas? Thank you :)

> Time for a Faculty check-in! `@faculty` please answer any that apply:
> • What have you been working on and how has it been going?
> • Anything you’ve accomplished since the last meeting?
> • Do you have any blockers?
> • Can other Faculty or Training Team members help you in some way?

**Comment by webtechpooja** [comment]
Thanks @courtney-pk and @jonathanbossenger, for sharing this. I have added them to the Agenda.

**Comment by webtechpooja** [comment]
Meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1702969208443829

**Comment by kaitohm** [comment]
Notes published here: https://make.wordpress.org/training/2023/12/22/training-team-meeting-recap-19th-december-2023/
