### ISSUE TITLE
Gujarati translation for Lesson Plan "Flexbox in CSS and WordPress"

### ISSUE THREAD

**Issue by DarshitRajyaguru** [WordPress/Learn#2122]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/flexbox-in-css-and-wordpress/
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @harshgajipara
- Other info: I am making an issue for a translation that was created here:
https://docs.google.com/document/d/15YCSnuOG38HwSPt9ECKXeQNwyhRdVpnAQxIzQfWAlUk/

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by DarshitRajyaguru** [comment]
@webtechpooja Please do needful.

**Comment by devmuhib009** [comment]
@DarshitRajyaguru do you complete the translation? Once you translate the content, please add the translation file here. So, @harshgajipara can review the content.

**Comment by DarshitRajyaguru** [comment]
@devmuhib009 I have already completed Gujarati translation and also attached the translation file above.

**Comment by devmuhib009** [comment]
Do you know @harshgajipara personally? Please tell him to review the translation and comment here. He need to comment here, so I can assign him as reviewer.

**Comment by DarshitRajyaguru** [comment]
@harshgajipara can you please review the translation for these documents?

**Comment by harshgajipara** [comment]
@DarshitRajyaguru I will review the translations soon. 
Thanks!

**Comment by devmuhib009** [comment]
Thanks @harshgajipara for reviewing the content, once you complete the review part, please notify here with your feedback, so I can move forward and take necessary steps to publish the content.

**Comment by harshgajipara** [comment]
@DarshitRajyaguru I completed translations review and it looks good to me.
Thanks!

**Comment by devmuhib009** [comment]
Thanks @harshgajipara for completing review.  @bsanevans as you are back from the vacation, you can now take control of the issue and move forward. However, if you don't have enough bandwidth, I can help you as well.

**Comment by kaitohm** [comment]
Please continue assisting with this issue, @devmuhib009 🙇‍♂️

**Comment by devmuhib009** [comment]
Ok, @DarshitRajyaguru please give your email address, so I can add you as author in learn WordPress website.

**Comment by kaitohm** [comment]
Ah, I see Muhibul needed me to add Darshit to https://learn.wordpress.org/ in order to copy the translation across.

@DarshitRajyaguru I've sent you an email inviting you to become a Contributor on Learn WordPress. Please comment here once you've accepted that.

Then, @devmuhib009 , you should be able to assist Darshit from step 5 listed here: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#lesson-plans

**Comment by devmuhib009** [comment]
@DarshitRajyaguru please check your email address and confirm the sign up on learn WordPress website. Then I can proceed from step 5 and 6.

**Comment by DarshitRajyaguru** [comment]
@devmuhib009 Please proceed for further steps I have confirmed sign up on Learn WordPress website.

**Comment by devmuhib009** [comment]
Hi @DarshitRajyaguru 

I've drafted the post. Here is the draft link: https://learn.wordpress.org/wp-admin/post.php?post=82812&action=edit

Please complete step 5 & 6 and update here. Thanks

**Comment by DarshitRajyaguru** [comment]
Hi @devmuhib009 I have updated the content in the post.
Link: https://learn.wordpress.org/wp-admin/post.php?post=82812&action=edit
Please Review and Publish.

Thanks!!!

**Comment by devmuhib009** [comment]
Published the lesson plan: https://learn.wordpress.org/lesson-plan/guj-flexbox-in-css-and-wordpress/
Thank you!

**Comment by DarshitRajyaguru** [comment]
Thank you!!!
