### ISSUE TITLE
Online Workshop: Optimizing WordPress for Core Web Vitals and Performance

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2126]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Online Workshop
- Content title: Optimizing WordPress for Core Web Vitals and Performance
- Topic description: Get ready for a deep dive into the world of WordPress optimization, where we’ll demystify the tech side of things, especially when it comes to meeting the demanding standards of Core Web Vitals and overall website performance.
- Audience (User, Developer, Designer, Contributor, etc.): User, Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner Intermediate

# Learning Objectives

- Understand what website vitals are and why they are important in regards to a site's performance.
- Apply strategies that will improve a website’s speed, boost interactivity, and ensure layout stability.

# Related Resources and Other Notes
This is a re-do of a presentation @vineettalwar previously conducted for WordCamp Skopje - [Optimizing WordPress for Core Web Vitals and Performance (language: EN)](https://skopje.wordcamp.org/2023/session/optimizing-wordpress-for-core-web-vitals-and-performance/)

### Automation Code

//online-workshop

**Comment by vineettalwar** [comment]
//asign

**Comment by vineettalwar** [comment]
Hi @bsanevans,
I will be doing this. 
Could you please //assign his issue to me.

**Comment by kaitohm** [comment]
That command you typed automatically assigned the issue to you 😉 
If you are comfortable with sharing your slides, then please share those here once they're ready. The Training team can review them for you for accuracy, accessibility, etc.

**Comment by kaitohm** [comment]
Recording uploaded: https://wordpress.tv/2024/01/28/optimizing-wordpress-for-core-web-vitals-and-performance/
