### ISSUE TITLE
Plugin Requirements

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2127]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson
- Content title:  Plugin requirements
- Topic description: Introduces the basic requirements needed for a valid plugin: a PHP file with a valid plugin header. Briefly cover the rest of the possible fields in the plugin header. Introduce some plugin best practices, like the ABSPATH check. 
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Describe the basic requirements for a valid WordPress plugin
- Identify all the plugin header fields
- Explain why some plugins make use of an ABSPATH check

# Related Resources and Other Notes
- https://developer.wordpress.org/plugins/intro/what-is-a-plugin/
- https://developer.wordpress.org/plugins/plugin-basics/header-requirements/
- https://developer.wordpress.org/plugins/plugin-basics/best-practices/

**Comment by jonathanbossenger** [comment]
//lesson

**Comment by jonathanbossenger** [comment]
# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for review
- [x] Lesson reviewed
- [x] Lesson video submitted and published to WPTV
- [x] Lesson created on Learn.WordPress.org 
- [x] Lesson video published to YouTube
- [x] Lesson on Learn.WordPress.org updated with YouTube video
- [x] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: 

https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/introduction-to-wordpress-plugins/02-plugin-requirements.md

**Comment by jonathanbossenger** [comment]
Video for review:

https://github.com/WordPress/Learn/assets/180629/5fc782a1-3a7d-40e2-8ef1-bc402ad7e9db

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great tutorial, @jonathanbossenger 👏

Not sure if this is the right place (from a Learning Pathways perspective), but it's worth mentioning somewhere that a plugin can also be used to create a block.

**Comment by jonathanbossenger** [comment]
> Not sure if this is the right place (from a Learning Pathways perspective), but it's worth mentioning somewhere that a plugin can also be used to create a block.

So I do cover this in the first lesson of the [Introduction to developing blocks](https://github.com/WordPress/Learn/issues/2236) module.

**Comment by ironnysh** [comment]
Oops, haven't watched this one yet 😄

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/plugin-requirements/
