### ISSUE TITLE
Bangla translation for  Tutorial  "Working faster with the command palette"

### ISSUE THREAD

**Issue by nasirbabu** [WordPress/Learn#2128]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/working-faster-with-the-command-palette/
- Link to original content's GitHub issue (optional):  https://github.com/WordPress/Learn/issues?q=is%3Aissue+Working+faster+with+the+command+palette
- Language you'll be translating to: Bangle
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by nasirbabu** [comment]
Bangla translated doc file link
https://docs.google.com/document/d/1UXWe4PnMzr7vj1ogpu0DE0hAVmYvndy6bSABckjHKJE/edit?usp=sharing

@devmuhib009 Please can you review.

**Comment by devmuhib009** [comment]
I already discussed with @nazsakib, he will review the content. I am in the middle of something right now, once I am free, I will take care of this issue as well.

**Comment by nazsakib** [comment]
I would like to review this content! @devmuhib009 @nasirbabu

**Comment by nazsakib** [comment]
এই টিউটোরিয়ালে, আমরা এক্সপ্লোর করতে যাচ্ছি কিভাবে আপনি দ্রুত কাজ করতে পারেন এবং কমান্ড প্যালেট ব্যবহার করে আপনার সাইট এডিটরের অভিজ্ঞতা বৃদ্ধি করতে পারেন।
> এই টিউটোরিয়ালে, আমরা কমান্ড প্যালেট ব্যবহার করে কিভাবে আপনি দ্রুত কাজ করতে পারেন এবং আপনার সাইট এডিটরের অভিজ্ঞতা উন্নত করতে পারেন সেটা এক্সপ্লোর করবো।

প্রথমত, আমরা কমান্ড প্যালেট কী তা নির্ধারণ করব। 
> প্রথমত, আমরা কমান্ড প্যালেট কী তা বের করব।

অবশেষে আমরা কীভাবে কার্যকরভাবে কমান্ড প্যালেট ব্যবহার করতে পারি এবং সেইসঙ্গে সুবিধাগুলি তুলে ধরতে পারি।
> অবশেষে আমরা দেখবো কীভাবে কার্যকরভাবে কমান্ড প্যালেট ব্যবহার করতে পারি এবং সেইসঙ্গে এর সুবিধাগুলিও তুলে ধরবো।

কমান্ড প্যালেট আপনাকে আপনার সাইটের বিভিন্ন এলাকায় দ্রুত নেভিগেট করতে, নতুন পেজ এবং পোস্ট তৈরি করতে এবং অন্যান্য কমান্ড চালানোর অনুমতি দেয়।
> কমান্ড প্যালেটের মাধ্যমে আপনি আপনার সাইটের বিভিন্ন জায়গায় দ্রুত নেভিগেট করতে, নতুন পাতা এবং পোস্ট তৈরি করতে এবং অন্যান্য কমান্ড চালাতে পারবেন।

কেবল সাইট এডিটর বা একটি পেজ বা একটি পোস্ট খুলুন
> শুধুমাত্র সাইট এডিটরে একটি পাতা বা একটি পোষ্ট খুলুন

আপনি এটিকে সাইট ভিউয়ের সাইডবারে অনুসন্ধান আইকনে বা একটি টেমপ্লেট বা পেজের শিরোনাম বারে ক্লিক করে খুঁজে পেতে পারেন।
> আপনি এটিকে সাইট ভিউয়ে থাকা সাইডবারের অনুসন্ধান আইকনে, এছাড়াও টেমপ্লেট বা পাতার শিরোনাম বারে ক্লিক করলেও দেখতে পাবেন।

আপনি একবার কমান্ড প্যালেট খুললে, আপনি পাত্তয়া যায় এমন কমান্ডগুলির একটি তালিকা দেখতে পাবেন।
> আপনি যখন একবার কমান্ড প্যালেট খুলবেন, তখন সমস্ত এভেইলেবল কমান্ডগুলির তালিকা দেখতে পাবেন।


***সরাসরি গুগল ট্রান্সলেট থেকে অনুবাদ তুলে না দেওয়ার অনুরোধ রইলো। বাক্যগুলো সাজাতে এবং বোধগম্য করে তুলতে হবে। তাহলে সবার জন্য বুঝতে সহজ হবে। দাঁড়ি দেওয়ার পরে একটা স্পেস দিয়ে তারপর নতুন বাক্য শুরু করলে সুন্দর দেখাবে এবং পড়তে সহজ হবে। এমন করে একটু সময় নিয়ে বাকিগুলোও এডিট করে ঠিক করার চেষ্টা করুন। আমি আবার চেক করে দেখে দিবো। ধন্যবাদ।***

**Comment by nasirbabu** [comment]
@nazsakib Thanks for your valuable suggestions. I have updated the document file as you suggested. 
https://docs.google.com/document/d/1UXWe4PnMzr7vj1ogpu0DE0hAVmYvndy6bSABckjHKJE/edit?usp=sharing

Note: I have used "পেজ" word against "পাতা" you have suggested.

**Comment by nasirbabu** [comment]
@nazsakib @devmuhib009 I have updated the document file as suggested.
https://docs.google.com/document/d/1UXWe4PnMzr7vj1ogpu0DE0hAVmYvndy6bSABckjHKJE/edit?usp=sharing

**Comment by devmuhib009** [comment]
@nasirbabu if you are not in the learn WordPress website, share your WordPress username, so I can add you to the website.
But if you already member of learn.wordpress.org, draft this post and share the preview link here. Thanks

**Comment by nasirbabu** [comment]
@devmuhib009 Draft the post , preview link:  https://learn.wordpress.org/wp-admin/post.php?post=138722&action=edit . Thanks

**Comment by devmuhib009** [comment]
Please complete step 6 & 7 and notify us when you submit the subtitle.
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials
Thanks

**Comment by nasirbabu** [comment]
@devmuhib009 Step 6 & 7 done. 
Thanks

**Comment by devmuhib009** [comment]
Tutorial has been published: https://learn.wordpress.org/tutorial/bn-working-faster-with-the-command-palette/
Thanks for your hardwork.
