### ISSUE TITLE
Comparing the layout of Workshops and Lesson Plan pages.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/Learn#213]
As I am in the process of moving my two tutorials from Workshops over to Lesson Plan pages I am seeing a few things that I believe would be helpful to have adjusted.

Here is the top area of the 
Workshops page:

![Workshops-page](https://user-images.githubusercontent.com/5323259/115445404-16c63200-a216-11eb-90a8-7ce14f0a6b2e.png)

Lesson Plans page:

![Screen Shot 2021-04-20 at 20 21 38](https://user-images.githubusercontent.com/5323259/115445454-280f3e80-a216-11eb-92ed-0d41717c8aaa.png)

-----------

What I am seeing....
Workshops do not have breadcrumbs. Lesson Plan pages do.
---> It would be helpful to add breadcrumbs to Workshop pages. As it gives a sense of where one is in relation to other content.

Workshops have a bigger font compared to Lesson Plan Pages.
---> It would be helpful to make the Lesson Plan pages use the same font size as is seen in a Workshop page.

-------------

Side by side correct size at 100% comparison.

![Workshops-left-Lesson-Plans-right](https://user-images.githubusercontent.com/5323259/115446129-0b273b00-a217-11eb-9b78-4d1ef4a6ba47.jpg)

Workshops have a right sidebar below the video. Lesson Plans page have a sidebar to the right of the video.
----> It would be helpful to move the Lesson Plan pages sidebar currently beside the video to below the video making it possible for content creators to also add additional content here.

Backend Workshop page:

![Backend-Workshop-page](https://user-images.githubusercontent.com/5323259/115447384-bd133700-a218-11eb-880d-98fdc6762c8a.jpg)

Backend Lessons Plan page:

![Backend-Lessons-Plans-page](https://user-images.githubusercontent.com/5323259/115447243-8ccb9880-a218-11eb-9814-bc4a787ea6a5.jpg)

-------------

The backend and frontend of a Workshop page looks more identical compared to the backend and frontend of a Lessons Plans page.

Here is a 5 minute video I made comparing the two.
https://youtu.be/5L8AxQR0VfA

**Comment by hlashbrooke** [comment]
What is actionable from this feedback? @paaljoachim could you summarise what you feel needs to be done based on your observations and experience?

**Comment by paaljoachim** [comment]
> What is actionable from this feedback?

A recap.
---> Actionable feedback on the bottom.

**Workshops**
The backend shows this:
![Screen Shot 2021-08-16 at 22 18 33](https://user-images.githubusercontent.com/5323259/129624542-cc1b9607-4f25-4f1d-aff1-2c677a3621de.jpg)
.
.
.
Frontend shows this:
![Screen Shot 2021-08-16 at 22 17 59](https://user-images.githubusercontent.com/5323259/129624589-4be46fca-1b24-4a71-be36-66c51496ba11.jpg)

Backend and frontend are pretty similar to each other.

--

**Lessons plans**
Backend.
![Screen Shot 2021-08-16 at 22 24 04](https://user-images.githubusercontent.com/5323259/129625183-3773d423-0b03-44fa-af4d-3d127cac5ffd.jpg)

Frontend.
![Screen Shot 2021-08-16 at 22 24 47](https://user-images.githubusercontent.com/5323259/129625195-db3f1378-c780-4478-80e5-2821ac1eb36f.jpg)

Lessons plans backend does not show the sidebar area:
![Screen Shot 2021-08-16 at 22 25 56](https://user-images.githubusercontent.com/5323259/129625270-dfafa2e9-50d4-4008-aba0-1433c3379723.jpg)

A Workshop the user who adds the information can see what the page in general looks like on the backend, and they will see the similar layout on the frontend.

Not so with Lesson plans. Backend and frontend do not match.

Actionable item.

**Example of the above Workshop where I removed the video and alternative title.**

![Screen Shot 2021-08-16 at 22 33 21](https://user-images.githubusercontent.com/5323259/129626037-97017111-8795-4254-ada7-28121e8a484f.jpg)

**Here is a mockup of what the above could look like in a Lesson plan.**
![Example-Lesson-plan](https://user-images.githubusercontent.com/5323259/129626265-6d182a0f-7b62-4731-9bc9-ca3d4858d258.jpg)

### Actionable feedback

**Move the Lessons sidebar into the content similar to the sidebar in a Workshop. So a Lesson creator will be able to see the sidebar similar to what a Workshop creator can do when creating a Workshop.**

**Comment by hlashbrooke** [comment]
Got it! Thanks for clarifying Paal :)

**Comment by hlashbrooke** [comment]
Since we're going to be setting up separate sidebar areas here (ref: #236) this issue can be closed as the sidebar content will be incorporated into that.
