### ISSUE TITLE
Bengali translation for Tutorial "Intro to the WordPress Block Directory"

### ISSUE THREAD

**Issue by KawsarAlamEven** [WordPress/Learn#2130]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/intro-to-the-block-directory/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/466
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by KawsarAlamEven** [comment]
Hi, i just translated the content, here is [the link](https://docs.google.com/document/d/15ZnbGbCu_AXRMHx2mImXqrvlqk1agheKBHEwc5cy810/edit?usp=sharing).

**Comment by devmuhib009** [comment]
Your translation file is not public. Please make it public, so anyone can review it.

**Comment by devmuhib009** [comment]
@nazsakib if you have bandwidth, can you please review the content as well?

**Comment by nazsakib** [comment]
Yes, I'd like to bhai, thank you! @devmuhib009

**Comment by nazsakib** [comment]
ব্লক ডিরেক্টরি কি, এবং আপনি কিভাবে নতুন ব্লক অনুসন্ধান করবেন?
> ব্লক ডিরেক্টরি কি, এবং আপনি কিভাবে নতুন ব্লকগুলো অনুসন্ধান করবেন?

ব্লক ডিরেক্টরি কি তা বুঝুন।
> ব্লক ডিরেক্টরি কি তা বুঝবেন।

কিভাবে ব্লক ডিরেক্টরি অ্যাক্সেস করতে হয়, নতুন ব্লক অনুসন্ধান এবং ডাউনলোড করতে হয় তা জানুন।
> জানবেন কিভাবে ব্লক ডিরেক্টরি অ্যাক্সেস করতে হয়, নতুন ব্লক অনুসন্ধান এবং ডাউনলোড করতে হয়।

আপনার সাইটে ডাউনলোড করা ব্লকগুলি কীভাবে পরিচালনা করবেন তা জানুন।
> শিখবেন কিভাবে আপনার সাইটে ডাউনলোড করা ব্লকগুলি পরিচালনা করবেন।

অনুধাবন প্রশ্ন
> সম্পূরক প্রশ্নগুলো

ব্লক ডিরেক্টরি কি, এবং আপনি কিভাবে নতুন ব্লক অনুসন্ধান করবেন?
> ব্লক ডিরেক্টরি কি, এবং আপনি কিভাবে নতুন ব্লকগুলো অনুসন্ধান করবেন?

হ্যালো, এবং ব্লক এডিটরের সাথে প্রকাশনার  ভূমিকার পরবর্তী পাঠে স্বাগতম।
> হ্যালো, এবং আমাদের ব্লক এডিটরের সাথে প্রকাশনা ভূমিকার পরবর্তী পাঠে স্বাগতম।

আমার নাম অ্যাঞ্জেলা এবং আমি অটোম্যাটিক দ্বারা স্পনসর করা একটি সম্প্রদায় সংগঠক।
> আমার নাম অ্যাঞ্জেলা এবং আমি অটোম্যাটিকের স্পনসর করা একটি কমিউনিটির অর্গানাইজার।

যা কভার করে যে এডিটর কী
> যেটি কভার করবে

আপনি এই ভিডিওর বিবরণে সিরিজের লিঙ্কগুলি খুঁজে পেতে পারেন।
> আপনি এই ভিডিওর বিবরণে সিরিজের লিঙ্কগুলি খুঁজে পাবেন।

আপনি যদি ইতিমধ্যেই ব্লক এডিটরের সাথে পরিচিত হন, বা ইতিমধ্যেই আগের ভিডিওটি দেখে থাকেন, দুর্দান্ত, এই ভিডিওটি এখন আপনাকে ব্লক ডিরেক্টরির সাথে পরিচয় করিয়ে দেবে এবং এটি কীভাবে ব্যবহার করতে হয়।
> আপনি যদি ইতিমধ্যেই ব্লক এডিটরের সাথে পরিচিত হন, বা ইতিমধ্যেই আগের ভিডিওটি দেখে থাকেন, তাহলে দুর্দান্ত, এই ভিডিওটি এখন আপনাকে ব্লক ডিরেক্টরির সাথে পরিচয় করিয়ে দেবে এবং কীভাবে তা ব্যবহার করতে হবে।

চলো যাই!
> চলুন শুরু করা যাক।


*ভালো হচ্ছে মোটামুটি তবে পুরোপুরি গুগল ট্রান্সলেট থেকে কপি না করে বাক্যগুলোতে কিছু পরিবর্তন করে বসালে পড়তে সুবিধা হবে। ইংলিশ থেকে অনেক শব্দ বাংলায় সরাসরি অনুবাদ করলে সেগুলো বুঝতে অসুবিধা হয়, সেসব ক্ষেত্রে ইংলিশ এবং পরিচিত শব্দটাই রেখে দিলে ভালো হয়। কিছু নমুনা এখানে আমি ঠিক করে দিয়েছি, বাকিগুলো এভাবে ঠিক করার চেষ্টা করলে হয়ে যাবে। আর একটু সময় নিয়ে করলে অনুবাদ সুন্দর হবে। রেফারেন্সের জন্যে [লোকাল গ্লোসারি](https://translate.wordpress.org/locale/bn/default/glossary/) দেখতে পারেন। ধন্যবাদ।*

**Comment by KawsarAlamEven** [comment]
[nazsakib](https://github.com/nazsakib) thank to you. I replace this sentence.
