### ISSUE TITLE
Bengali  translation for "Custom CSS in the Editor"

### ISSUE THREAD

**Issue by KawsarAlamEven** [WordPress/Learn#2131]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/custom-css-in-the-editor/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/1274
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by KawsarAlamEven** [comment]
Hi, i just translated the content, here is [the link](https://docs.google.com/document/d/16-EiieG19-SSlgaFGwa2I4X9ZZw6mW-4dudRRhG4rGE/edit?usp=sharing).

**Comment by devmuhib009** [comment]
I will review the content soon.

**Comment by devmuhib009** [comment]
Thank you for providing the translation. However, it seems the content closely resembles the output of a translation tool like Google Translate. To enhance readability and accuracy, could you please consider using the translation as a reference and rephrasing it in your own words? This will ensure a more natural and understandable version.

**Comment by KawsarAlamEven** [comment]
Thanks to you. Now i try translate my own words. now you can see that.

**Comment by devmuhib009** [comment]
Ok, as you granted permission to modify the doc file, I will suggest improvements there. As tomorrow is off day, I will try to review content tomorrow.

**Comment by KawsarAlamEven** [comment]
Thanks.
