### ISSUE TITLE
Bengali translation for "How to choose & install a theme"

### ISSUE THREAD

**Issue by KawsarAlamEven** [WordPress/Learn#2132]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/how-to-choose-install-a-theme/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/1312
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by KawsarAlamEven** [comment]
Hi, i just translated the content, here is [the link](https://docs.google.com/document/d/1TctmA79pWsA4zdVTAONPBki3XMNtHZV-Cj8N7IuOGxE/edit?usp=sharing).

**Comment by devmuhib009** [comment]
I will review the content soon.

**Comment by devmuhib009** [comment]
Appreciate your effort in translating the content. However, it seems quite similar to a direct output from translation software. To enhance the quality and coherence of the translation, I recommend using the translation as a guide and rewriting it in a more natural and readable manner. Your own interpretation would greatly improve the understanding and flow. Thank you!

**Comment by KawsarAlamEven** [comment]
I try to translate again.
