### ISSUE TITLE
Feedback - scoring is off

### ISSUE THREAD

**Issue by CodeByLine** [WordPress/Learn#2133]
## Description
The scoring is off for the quiz for "Block Theme Development Fundamentals Quiz". I know new tutorials are being created, but of all the misspelt words and sloppy work, this is annoying not because of the scoring but because there is no feedback.

## Step-by-step reproduction instructions (optional)

Please list the steps needed to reproduce or verify the feedback. For example:
1. Go to 'https://learn.wordpress.org/quiz/block-theme-development-fundamentals/?bypass_server_cache=658defddb3160'
2. Do the quizzes
3. Check the score - no matter what you do, it's 87%. No feedback

**Comment by kaitohm** [comment]
//content

**Comment by devmuhib009** [comment]
I tested the score and it was 25% also did not find any misspelled words. I suggest you to create a list of misspelled words and create a new ticket that will help us fixing those words easily. Thanks for your feedback. ❤️
