### ISSUE TITLE
German translation for "Themes/Plugins Relationship"

### ISSUE THREAD

**Issue by BenjaminZekavica** [WordPress/Learn#2135]
# Details
- Link to original content: Themes/Plugins Relationship 
- Language you'll be translating to:  German
- Have you arranged for someone to review this translation?: Yes  

# Next Steps
Here is my Google Doc File:  
https://docs.google.com/document/d/1t7CFCs-mFeFNYm7M8wNH_-y3VFunwz6MRL7uIDPbp-4/edit?usp=sharing 

ENG Article: https://learn.wordpress.org/lesson-plan/themes-plugins-relationship/

**Comment by gudrunfrank** [comment]
@BenjaminZekavica I reviewed the translation. Apologies for messing up the first bullet point. I am not very familiar with the functionality of Google Docs :-( Somehow there was no "undo".
As a general comment, the original lesson in English is of quite poor quality. I have lots of issues with a couple of the statements.

**Comment by BenjaminZekavica** [comment]
@gudrunfrank Thank you so much for your great work :) 

@bsanevans The new final version is now available: https://docs.google.com/document/d/1t7CFCs-mFeFNYm7M8wNH_-y3VFunwz6MRL7uIDPbp-4/edit 

Do you can create a post for me ? I will add the content in WP and after that you can publish it.

**Comment by devmuhib009** [comment]
Hi @BenjaminZekavica 

I've drafted the content here: https://learn.wordpress.org/wp-admin/post.php?post=82890&action=edit

Please complete step 5 & 6 from here. 
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#lesson-plans

Thanks

**Comment by BenjaminZekavica** [comment]
@devmuhib009 I added the content and it's ready for publishing: 
https://learn.wordpress.org/wp-admin/post.php?post=82890&action=edit

**Comment by devmuhib009** [comment]
Thanks @BenjaminZekavica 
Lesson plan has been published. 
Here is the live link: https://learn.wordpress.org/lesson-plan/de-themes-plugins-relationship/
