### ISSUE TITLE
Meeting Agenda January 11, 2024

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2136]
Training Team meetings start at 00:00 UTC weekly on Thursdays. Anyone is welcome to contribute to the meeting by commenting in Slack threads throughout the week. Meeting notes will be published at the end of the week to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @bsanevans ._

## 1. Intro/Welcome

Welcome to all new teammates who joined the Training Team this week!

## 2. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- January 11 – **need volunteer**
- January 18 – Sancastiza 
- January 25 – NF Tushar
- February 1 – **need volunteer**

**2. Looking for feedback**

- Come join the team's [2024 goal planning sessions](https://make.wordpress.org/training/2023/12/22/training-team-2024-goals-setting/).
- [Help the team brainstorm contribution ideas](https://make.wordpress.org/training/2023/12/22/brainstorm-table-lead-wordcamp-asia-2024-contributor-day/) for the team to work on at WordCamp Asia 2024.

**3. Looking for volunteers**

- Any developers want to work on any of the team's [17 good first issues](https://github.com/orgs/WordPress/projects/71/views/1?filterQuery=label%3A%22%5BType%5D+Good+First+Issue%22)?
- Who would like to facilitate an Online Workshop this year?

**4. Updates from last week's dev-squad triage session**

The triage sessions were cancelled during the holidays. They will start again this week.

**5. Other news**

- Next week's team meeting will be conducted over a video call and will focus on brainstorming 2024 goals. The call link will be published in the Training channel 5 minutes before the meeting starts.

## 3. [Open requests for review](https://github.com/orgs/WordPress/projects/33/views/17)

We have 15 pieces of content waiting reviews. Click this link to see the full list:
- https://github.com/orgs/WordPress/projects/33/views/17

Please refer to [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.

## 4. Project updates

- 2023 goals
  - If you haven't yet, check out [Training Team 2023 Year In Review](https://make.wordpress.org/training/2023/12/19/training-team-2023-year-in-review/) to see what the team accomplished.
- Learning pathways
  - We have some first draft redesign edits and thumbnails up for review, and will connect with Design re: next steps next week:
   -- [Learn Redesign](https://www.figma.com/file/ZKaf6u8mIHkAanluWafXAp/Learn?type=design&mode=design) (See Learn WordPress, alternate take section)
  -- [Video thumbnails](https://www.figma.com/file/1RXSQvg3UJcPCvxyQ9SGnl/Video-Thumbnails?type=design&node-id=0-1&mode=design)

## 5. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by askhellosatya** [comment]
Hi @bsanevans,

I'm not a developer, but I have a comprehensive understanding of WordPress as a non-code developer and possess basic knowledge of HTML, CSS, and PHP. I'm keen to volunteer and contribute to the [17 good first issues](https://github.com/orgs/WordPress/projects/71/views/1?filterQuery=label%3A%22%5BType%5D+Good+First+Issue%22).

Thank you!

**Comment by jonathanbossenger** [comment]
Hi @bsanevans. Could I ask you to add this post to the Looking for feedback section:

https://make.wordpress.org/training/2024/01/09/request-for-feedback-training-contributor-badge-requirements-for-code-contributions/

**Comment by courtney-pk** [comment]
Can we please continue to share the Faculty thread?

> Time for a Faculty check-in! `@faculty` please answer any that apply:
> • What have you been working on and how has it been going?
> • Anything you’ve accomplished since the last meeting?
> • Do you have any blockers?
> • Can other Faculty or Training Team members help you in some way?

@bsanevans can you please add the above to the agenda template so we can be sure this is included every meeting? Thank you!

**Comment by kaitohm** [comment]
Meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1704931321952729

**Comment by kaitohm** [comment]
Thank you for volunteering, @askhellosatya 🙌 Feel free to jump into any issue, [assign the issue to yourself](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/automated-workflows/#self-assign-an-issue), and start working on it. The team's handbook page [Code Contributions](https://make.wordpress.org/training/handbook/training-team-how-to-guides/code-contributions/) will guide you with more details 🙂

**Comment by kaitohm** [comment]
@courtney-pk Sure! This call for updates has been added in https://github.com/WordPress/Learn/pull/2141

**Comment by kaitohm** [comment]
https://make.wordpress.org/training/2024/01/16/training-team-meeting-recap-january-11-2024/
