### ISSUE TITLE
Gujarati translation for Lesson Plan "WordPress Action Hooks"

### ISSUE THREAD

**Issue by DarshitRajyaguru** [WordPress/Learn#2139]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/wordpress-action-hooks/
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @shail-mehta
- Other info: I am making an issue for a translation that was created here:
https://docs.google.com/document/d/1ASYnB5IuT1XB310IXOFD41osw-naGL20QWlDUi1JYgQ/

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by kaitohm** [comment]
@DarshitRajyaguru Could you change the access setting on the Google Doc to public, please? Thanks.

**Comment by DarshitRajyaguru** [comment]
@bsanevans Please check I have change the document access public.
Thanks!!!

**Comment by kaitohm** [comment]
Confirmed 👍 

@shail-mehta This is ready for review.

**Comment by shail-mehta** [comment]
@bsanevans @DarshitRajyaguru 

I will review this today

**Comment by shail-mehta** [comment]
@bsanevans @DarshitRajyaguru 

I have reviewed this translations and It's Looks good to me.

**Comment by DarshitRajyaguru** [comment]
@bsanevans Can you please do needful?

**Comment by devmuhib009** [comment]
@shail-mehta @DarshitRajyaguru I had a discussion with @bsanevans about this issue. I will take care of it.

**Comment by devmuhib009** [comment]
@DarshitRajyaguru Here is the draft link: https://learn.wordpress.org/wp-admin/post.php?post=82822&action=edit
Edit the content with your original content and notify here whenever you complete. 
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#lesson-plans

**Comment by DarshitRajyaguru** [comment]
Hi @devmuhib009 I have updated the translation in the drafted post.
Please Review and Publish.

Thanks!!!

**Comment by devmuhib009** [comment]
Lesson plan published: https://learn.wordpress.org/lesson-plan/guj-wordpress-action-hooks/
Thank you!
