### ISSUE TITLE
German translation for "How To Find Theme Specific Documentation"

### ISSUE THREAD

**Issue by BenjaminZekavica** [WordPress/Learn#2144]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/how-to-find-theme-specific-documentation/
- Language you'll be translating to: German
- Have you arranged for someone to review this translation?: Yes 
- Google Doc: https://docs.google.com/document/d/1tMSvH5xDXP7GVjTisx6UI96t0sFU3I_NVeeU0naclXQ/edit#heading=h.yx5nd85ak4og

**Comment by devmuhib009** [comment]
@gudrunfrank if you have bandwidth, can you please review this content. ❤️

**Comment by BenjaminZekavica** [comment]
@devmuhib009 Hi :) Do you can create a post for me. I want to set the translated content. @gudrunfrank had reviewed the content maybe 80%. She want's to review it again, to rewrite some sentences, but for beginning I could set up the translation in WP.org Backend.

**Comment by devmuhib009** [comment]
Sure, I'll create the post soon and update here.

**Comment by devmuhib009** [comment]
Hi, sorry for being late. I was attending my brothers wedding. Here is the draft: https://learn.wordpress.org/wp-admin/post.php?post=83665&action=edit

**Comment by BenjaminZekavica** [comment]
@devmuhib009 Thank you :) I added the content to the post.

**Comment by devmuhib009** [comment]
Lesson plan is published now: https://learn.wordpress.org/lesson-plan/de-how-to-find-theme-specific-documentation/
thanks ❤️
