### ISSUE TITLE
Online Workshop: Creating an About page using patterns

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2146]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): OW
- Content title: Creating an About page using patterns
- Topic description: Using patterns to build a page
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

Session 1: 31 January - **DONE**
Session 2: 5 Feb

# Learning Objectives

In this session, we will build an About page using a variety of patterns. We will explore using patterns more effectively and how it can save you time and effort.

# Related Resources and Other Notes
Meetup link: https://www.meetup.com/learn-wordpress-online-workshops/events/298556441/?isFirstPublish=true
Meetup link 2 (5 Feb 1:00am UTC): https://www.meetup.com/learn-wordpress-online-workshops/events/298895252/?isFirstPublish=true

### Automation Code

//online-workshop

**Comment by SierraTR** [comment]
I'll co-host for you Wes.

**Comment by westnz** [comment]
Great! Thanks @SierraTR

**Comment by westnz** [comment]
Repeat session: https://www.meetup.com/learn-wordpress-online-workshops/events/298895252/?isFirstPublish=true

**Comment by westnz** [comment]
Done: https://wordpress.tv/2024/02/04/creating-an-about-page-using-patterns/
