### ISSUE TITLE
Gujarati translation for "Registering Block Patterns"

### ISSUE THREAD

**Issue by Roshan-narola** [WordPress/Learn#2151]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/registering-block-patterns/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: Gujarati translation :
https://docs.google.com/document/d/1qGTIk9gM0CWaGNIrJBT3NPV6bIiy-X7ID0YOBaqY4jg/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by DarshitRajyaguru** [comment]
@devmuhib009 I will review and update very soon.

**Comment by DarshitRajyaguru** [comment]
@Roshan-narola Needs to add English translation also with the translated content so I can check accordingly.
I am attaching a reference document for better understanding:
https://docs.google.com/document/d/1ASYnB5IuT1XB310IXOFD41osw-naGL20QWlDUi1JYgQ/edit

**Comment by Roshan-narola** [comment]
Ok I'll update it

**Comment by Roshan-narola** [comment]
Update is done can you please check it.
https://docs.google.com/document/d/1qGTIk9gM0CWaGNIrJBT3NPV6bIiy-X7ID0YOBaqY4jg/edit?usp=sharing
Thank you

**Comment by DarshitRajyaguru** [comment]
@Roshan-narola I will check and update.

**Comment by DarshitRajyaguru** [comment]
Hi @devmuhib009 @Roshan-narola 
I have reviewed this translation and It's Looks good to me.

**Comment by devmuhib009** [comment]
Thanks @DarshitRajyaguru for reviewing the content. @bsanevans could you please add @Roshan-narola as author in Learn WordPress? So I can move forward and publish the content.

**Comment by jonathanbossenger** [comment]
The user has been added as an author, and the invitation email sent. @Roshan-narola please look out for and accept the invitation email.

**Comment by Roshan-narola** [comment]
We'll check the email.Thank you so much.

**Comment by Roshan-narola** [comment]
@DarshitRajyaguru  and @jonathanbossenger I accept the invitation from email can you please move for further process. Thank you.

**Comment by Roshan-narola** [comment]
@devmuhib009 sir I accept the invitation from email can you please move further process I'm still waiting for your response. Thank you

**Comment by devmuhib009** [comment]
@Roshan-narola I am attending a family program, so, I am little bit busy today. I've noticed you have two more issues active. Complete the review process of those tickets, so we can pubilsh all 3 at same day.

**Comment by Roshan-narola** [comment]
Okk. Thank you so much I'll do the same.

**Comment by devmuhib009** [comment]
@jonathanbossenger I think the user type you selected was not author. I could not find Roshan as author. Can you please recheck and assign him as author?

I already drafted the post here: https://learn.wordpress.org/wp-admin/post.php?post=82883&action=edit
@Roshan-narola once an admin change the user type, you will able to access this page. Thanks

**Comment by devmuhib009** [comment]
Hi, @Roshan-narola I have just assigned you as author in the post. Please edit and replace all English content with your Gujrati translation. https://learn.wordpress.org/wp-admin/post.php?post=82883&action=edit

Please complete step 6 & 7 from below handbook page and comment here when you are done.
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials

**Comment by Roshan-narola** [comment]
Ok, I'll do the same. I'll let you know once it's done. Thank you.

**Comment by Roshan-narola** [comment]
@devmuhib009 sir, I'm not able to upload subtitle file for video. it's give me error, I'm trying 2-3 times. Can you please help me with this?

**Comment by devmuhib009** [comment]
Sure, upload the file here. You can't upload .ttml here. So, I recommend change it to .txt extension and upload here. I will take a look on it.

**Comment by Roshan-narola** [comment]
@devmuhib009 sir,  I'm sending file here.
[subtitles.txt](https://github.com/WordPress/Learn/files/14021113/subtitles.txt)
[subtitles.zip](https://github.com/WordPress/Learn/files/14021115/subtitles.zip)

Thank you so much for your great support.

**Comment by devmuhib009** [comment]
I just checked the file and it's not minified. That's why it's causing the error. Please follow these steps.
1. Visit site: https://codebeautify.org/xmlviewer
2. upload the subtitles.txt file
3. Click on Minify 
4. Download the minified version and change the extension to .ttml
Upload again.

**Comment by Roshan-narola** [comment]
@devmuhib009 I'll check, Thank you your suggestion.

**Comment by Roshan-narola** [comment]
@devmuhib009 sir, I try minify file also but still same issue.
[SUBTITLES_2.zip](https://github.com/WordPress/Learn/files/14022687/SUBTITLES_2.zip)

Video link -https://wordpress.tv/2021/01/18/daisy-olsen-registering-block-patterns/
here I'm adding this, still same issue.

**Comment by devmuhib009** [comment]
Hi @Roshan-narola 
Thanks for your effort to translate the tutorial. Tutorial is published now.
https://learn.wordpress.org/tutorial/gu-registering-block-patterns/
