### ISSUE TITLE
Tutorial: Nesting and using blocks to create visually appealing content 

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2152]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Tutorial
- Content title: Nesting and using blocks to create visually appealing content 
- Topic description: Using blocks more effectively to build content
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

Nest blocks and use blocks to build content.

# Related Resources and Other Notes

### Automation Code

//tutorial

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/d378c3c7-6781-4395-bf50-a201152dac3a

**Comment by ghost** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

- Great tutorial! You covered all the points that you highlighted in the list of different types of nesting.
-  Tone and speed were good. 
- Steps were clear to follow.

**Comment by westnz** [comment]
Thank you @lada7042

**Comment by quitevisible** [comment]
@westnz Good job staying on point! So many features and ways of creating page layouts makes it hard to know what to include or omit. 

Feedback: 

- Around the 2:00 mark, perhaps mention or caption to use 'shift+click' to select multiple blocks when grouping.  
- One of the features I've found useful is custom naming the groups, especially for a longer Home Page or one-page site.

**Comment by askdesign** [comment]
Hi Wes, I always enjoy your tutorials. This is a wonderful guide showing a nice variety of nesting blocks. I think it will assist users in ways to achieve visual compelling layouts. 

There was only 1 moment where I was a wee bit confused. But, as you moved through the examples, I understood better. Here is the moment I'm referring to:
2:09 - you want to use the wide width.  But, you first deselect the Layout > inner blocks content width toggle off

I think it might be good to show what would happen if the toggle were left on. Then compare to what happens with the toggle off.

**Comment by SierraTR** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ x] Learning outcomes/objectives are clear.
- [ x] Technical concepts introduced in the content are accurate.
- [x ] The speed of demonstrations are easy to follow.
- [x ] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [ x] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Another good one, Wes. I agree with @askdesign that a demonstration of what the 'inner blocks use content width' does visually - perhaps switch to the front of the website with and without the toggle set. And @quitevisible has a good point about how multiple items are highlighted in the list view column.

**Comment by westnz** [comment]
Thank you all for the suggestions and reviews. Much appreciated

**Comment by westnz** [comment]
Published in Sensei as part of the Beginner User learning pathway.
