### ISSUE TITLE
Gujarati translation for "Intro to Gutenberg Block Development"

### ISSUE THREAD

**Issue by Roshan-narola** [WordPress/Learn#2153]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/intro-to-gutenberg-block-development/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [shail-mehta](https://github.com/shail-mehta)
- Other info: Gujarati translation :
https://docs.google.com/document/d/1RzDDK7wwlDwVnbU1UpTTJOyEPYvcPQYp9BguqjcREYE/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by shail-mehta** [comment]
Hi @Roshan-narola @devmuhib009 

I have reviewed translations. it looks good to me.

**Comment by devmuhib009** [comment]
Hi,
I've drafted the post here: https://learn.wordpress.org/wp-admin/post.php?post=82990&action=edit

Please complete step 5 to rest: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials

Please use this xml formatter to format subtitles: https://www.freeformatter.com/xml-formatter.html

Thanks

**Comment by Roshan-narola** [comment]
@devmuhib009, @bsanevans sir, I replace post content with Gujarati translation. now move forward with subtitles then still it's not working for me, I'm follow [[(https://www.freeformatter.com/xml-formatter.html) ](https://www.freeformatter.com/xml-formatter.html) this steps also but still it's give me same error.  I try both minify and simple formate both are not working. here I'm sharing video link- https://nimb.ws/8Cai6o. please tell me what can I do now? can you share video step how you can convert file or any other steps which I need to follow?

Thank you.

**Comment by devmuhib009** [comment]
Can you please use original gmail account to submit please. and if it still gives an error, upload the file here. I will take care of it. Thanks

**Comment by Roshan-narola** [comment]
@devmuhib009 sir, Thank you for your suggestion. I try with my original email account of wordpress.org but still it's not working. it's give same error. (video link- https://nimb.ws/8Cai6o ). Also I need solution of that problem because I want to contribute for wordpress.tv badge. If you upload file from your end then how I'm eligible for wordpress.tv badge as well as training contribution badge?

Thank you.

**Comment by devmuhib009** [comment]
Hi @Roshan-narola 

I am uploading with your user name. So, all the subtitles goes under your username.
![image](https://github.com/WordPress/Learn/assets/142894870/0ab860be-42aa-42e2-a14d-11a42dd6a952)

**Comment by Roshan-narola** [comment]
@devmuhib009 sir, Thank you so much. Here is my last file for upload in this tutorial. 
[subtls.zip](https://github.com/WordPress/Learn/files/14049179/subtls.zip)

Thank you so much for your support.

**Comment by devmuhib009** [comment]
Tutorial has been published: https://learn.wordpress.org/tutorial/gu-intro-to-gutenberg-block-development/
Thanks @Roshan-narola for your effort. ❤️
