### ISSUE TITLE
Upgrade Word Press(Topic Suggestion)

### ISSUE THREAD

**Issue by maneesh-halcyontek** [WordPress/Learn#2154]
Upgrading wordpress when shifting from older PHP to newer PHP 
for eg a project that was made in php 7.0  and now have to move it to  php 8 server so the proceess required so that the project runs smoothly

**Comment by jonathanbossenger** [comment]
@maneesh-halcyontek at the moment, WordPress is compatible with PHP 8.0, 8.1 and 8.2 with certain specific exceptions (details [here](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/) and [here](https://wordpress.org/news/2023/10/wordpress-6-4s-php-compatibility/)). So was there anything specific you wanted this piece of content to cover?
