### ISSUE TITLE
Gujarati translation for "Custom CSS in the Editor"

### ISSUE THREAD

**Issue by Roshan-narola** [WordPress/Learn#2155]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/custom-css-in-the-editor/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [pooja9712](https://github.com/pooja9712)
- Other info: Gujarati translation :
https://docs.google.com/document/d/1Aiy6P8tBv6mReImcaGxgDlzcs3Q6ns6N9wpwyxvoAQM/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by pooja9712** [comment]
@devmuhib009 sir,
 Can I review this translation?

**Comment by devmuhib009** [comment]
@pooja9712 madam,
You are already reviewer of this translation as @Roshan-narola added you when he was creating the issue. So, you can just review the doc file and tell your feedback here. Thanks

**Comment by pooja9712** [comment]
@devmuhib009  sir,  I review the translation and it's look good go for further process. Thank you

**Comment by devmuhib009** [comment]
ok, thanks. I will take care of it soon.

**Comment by devmuhib009** [comment]
Hi @Roshan-narola 

I have drafted the content here: https://learn.wordpress.org/wp-admin/post.php?post=82886&action=edit

Please complete step 6 & 7 from below handbook page and inform us when done.
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials

**Comment by devmuhib009** [comment]
I have just assigned you as author to this post. You can now access the post to edit. Please replace all the English content with Gujrati translation. Also, I have noticed, there has an excerpt in the draft. Please translate that excerpt as well. Thank you.

**Comment by Roshan-narola** [comment]
@devmuhib009, @bsanevans  sir, I replace all content with Gujarati translation, and here is my subtitle file.
[custom_css_mini_translation.zip](https://github.com/WordPress/Learn/files/14024100/custom_css_mini_translation.zip)
Can you please upload it. As you know I'm not able to upload it. so my all translation already going late for publish. Please help me so that my three translation publish successfully.
Thank you for your support.

**Comment by devmuhib009** [comment]
Hi, Translation is now published. 
https://learn.wordpress.org/tutorial/gu-custom-css-in-the-editor/

**Comment by Roshan-narola** [comment]
@devmuhib009 sir thank you so much for all your support.
