### ISSUE TITLE
Feedback - Duplicate numbers in lesson / course

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/Learn#2156]
_Psst, the `https://github.com/WordPress/gutenberg/issues` link in the leading, hidden comment in this Issue Template should probably be updated to `https://github.com/WordPress/Learn/issues`_

## Type of feedback

//dev

## Description

The lessons within, at least, the https://learn.wordpress.org/course/open-source-basics-and-wordpress/ course have duplicate numbers shown when numbered bullets / ordered lists are used.

## Step-by-step reproduction instructions (optional)

1. Go to the https://learn.wordpress.org/course/open-source-basics-and-wordpress/ course
2. Begin the course
3. View the first lesson that uses numbered bullets / ordered lists 
4. See that the lists repeat the numbers (e.g. `1. 1. <some text here>`, `2. 2. <some different text here>`).

## Screenshots or screen recording (optional)

![Learn_Lesson_Numbering_Issue](https://github.com/WordPress/Learn/assets/2818133/905bc052-3af0-40be-812a-5ea1ee6ebde1)

## Other information (optional)

Mac mini 2018
macOS Sonoma 14.2.1
Firefox 121.0 (64-bit)

**Comment by devmuhib009** [comment]
I just checked the issue. I found same duplicate number lists in my end. Need to fix.

**Comment by Piyopiyo-Kitsune** [comment]
https://github.com/WordPress/Learn/assets/17694715/11a297f8-7dbb-4114-88bc-e1636e8e9f76

Adding a video of the issue which is still present. We also see the answer choices having bullet points attached as well.

**Comment by adamwoodnz** [comment]
I disabled the Sensei option `Prevent the frontend stylesheets from loading. This will remove the default styles for all Sensei LMS elements.` and this appears to be fixed. Please reopen if you see any new issues with styles that might be related to this change.
