### ISSUE TITLE
Feedback - Mismatched quiz button styles and layout

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/Learn#2157]
_Psst, the `https://github.com/WordPress/gutenberg/issues` link in the leading, hidden comment in this Issue Template should probably be updated to `https://github.com/WordPress/Learn/issues`_

## Type of feedback

//dev

## Description

The `Complete Quiz`, `Restart Quiz`, and `Save Progress` buttons at the end of a quiz utilize different, conflicting styles (the `Save Progress` one appears possibly to be totally un-styled perhaps?).  They're also oddly stacked on top of each other and with the different styles/text alignments make them appear visually mismatched.  It might be helpful to (1) utilize the same styles for the buttons (admitting there's likely a primary, secondary, and tertiary button action/style desired) and (2) consider having them on the same horizontal row more akin to WordPress admin styles for button layouts? 

## Step-by-step reproduction instructions (optional)

1. Go to any course
2. Click through a lesson until you get to a quiz
3. View the buttons at the end of the quiz

## Screenshots or screen recording (optional)

Screenshot showing the default view of the `Complete Quiz`, `Restart Quiz`, and `Save Progress` buttons (note the markedly different style of the `Save Progress` button and that they're oddly stacked on top of each other):
![Learn_Lesson_Default_Buttons](https://github.com/WordPress/Learn/assets/2818133/12e62ada-6945-45d4-9e69-5b983b6cd884)

Screenshot showing the `Complete Quiz` button style on-hover:
![Learn_Lesson_Complete-Quiz_On-Hover](https://github.com/WordPress/Learn/assets/2818133/49538e48-4683-491a-9027-3690f8afb5c0)

Screenshot showing the `Restart Quiz` button style on-hover:
![Learn_Lesson_Restart-Quiz_On-Hover](https://github.com/WordPress/Learn/assets/2818133/6425333b-234c-471c-8314-27818a25c951)

Screenshot showing the `Save Progress` button style on-hover:
![Learn_Lesson_Save-Progress_On-Hover](https://github.com/WordPress/Learn/assets/2818133/3834cb11-c079-47b0-96b4-6c3bb1d7dc92)

## Other information (optional)

Mac mini 2018
macOS Sonoma 14.2.1
Firefox 121.0 (64-bit)

**Comment by jonathanbossenger** [comment]
Thanks for raising this @jeffpaul I have assigned it to myself to look into

**Comment by adamwoodnz** [comment]
No longer an issue, with the launch of the 2024 block theme

![Image](https://github.com/user-attachments/assets/64d7e527-3b4f-483d-8024-10e984885e1e)
