### ISSUE TITLE
Feedback - PHPCodeSniffer URL needs to be updated. 

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2160]
## Type of feedback
 

//content

## Description

https://learn.wordpress.org/tutorial/testing-your-products-for-php-version-compatibility/

The link to PHPCodeSniffer should be updated: https://github.com/PHPCSStandards/PHP_CodeSniffer, the original repo was abandoned (https://github.com/squizlabs/PHP_CodeSniffer/issues/3932).

**Comment by devmuhib009** [comment]
Updated the URL. Thanks @digitalchild.
