### ISSUE TITLE
Gujarati translation for "How to use GitHub for Gutenberg"

### ISSUE THREAD

**Issue by pooja9712** [WordPress/Learn#2162]
# Details
- Link to original content:  https://learn.wordpress.org/tutorial/how-to-use-github-for-gutenberg/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: Gujarati translation :
https://docs.google.com/document/d/1dTlnRsftKvmo-xuOmcHc2sXVDgv3FZXXI-YldE3eT4I/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by shail-mehta** [comment]
@devmuhib009 

Can I review this translation?

**Comment by devmuhib009** [comment]
Sure. I am assigning you as reviewer. Once you complete reviewing the translation, comment your feedback here.

**Comment by shail-mehta** [comment]
@pooja9712 @devmuhib009 

I have reviewed above translation and it looks good to me.

**Comment by devmuhib009** [comment]
Hi
I've drafted the content. https://learn.wordpress.org/wp-admin/post.php?post=82954&action=edit
Please complete step 5 to 7 and update here. 
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials

**Comment by pooja9712** [comment]
@devmuhib009 sir, I replace all the content with Gujarati content. for further process as you know I'm not able to upload subtitles file so I send it here, also same for my other 2 translation so that I'm apply for badge process.. 
[github.zip](https://github.com/WordPress/Learn/files/14034089/github.zip)
Thank you for your support.

**Comment by devmuhib009** [comment]
Thank you!
Content is published now: https://learn.wordpress.org/tutorial/gu-how-to-use-github-for-gutenberg/
