### ISSUE TITLE
Gujarati translation for "How to do triage on GitHub"

### ISSUE THREAD

**Issue by pooja9712** [WordPress/Learn#2163]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/how-to-do-triage-on-github/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [Roshan-narola](https://github.com/Roshan-narola)
- Other info: Gujarati Translation:
https://docs.google.com/document/d/1LHlXX_VB_9qlAce0kKRq0UJSdfnf_dV13iVxzu8s7nA/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by pooja9712** [comment]
@devmuhib009 sir, I review the translation and it's good to go for further process. Thank you

**Comment by Roshan-narola** [comment]
@devmuhib009 sir, I review the translation, it's good to go for further process. Thank you.

**Comment by devmuhib009** [comment]
Thanks @Roshan-narola for reviewing the content. @pooja9712 please check your email associated with your WordPress account. I've sent an invitation link to add you as contributor in Learn WordPress website. Once you accept the invitation, I can draft the post to publish.

**Comment by pooja9712** [comment]
@devmuhib009 sir, I check my email and it's give me error. Can you please send me again.

**Comment by devmuhib009** [comment]
No problem, as per my check, your account has been created. I've just drafted the post. 
https://learn.wordpress.org/wp-admin/post.php?post=82905&action=edit

Please complete step 5 to 7 and comment here.
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials

**Comment by pooja9712** [comment]
@devmuhib009 sir thank you so much, I'll let you know.

**Comment by pooja9712** [comment]
@devmuhib009 sir, I can replace English translation to Gujarati, now I move to the step 6,7 of your given link (https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials) but I'm not getting it how to translate subtitles? can you please help me for the same?

**Comment by devmuhib009** [comment]
**I recommend you to follow this guideline:** https://wordpress.tv/subtitle/?video=107277

**If you still do not understand. Follow below guides.**

1. While editing the post, you will find WordPress.tv url of the video.
![image](https://github.com/WordPress/Learn/assets/142894870/3a12c849-d95f-48e5-94dc-95600f170bfa)

2. Your next step is visiting the video page and download the English subtitle.
![image](https://github.com/WordPress/Learn/assets/142894870/b5176342-28db-4947-a31b-8e78489a2c6c)

3. Next step is visit https://codebeautify.org/xmlviewer and upload your subtitle. Click on Beautify button. Replace all the english title to Gujrati.
![image](https://github.com/WordPress/Learn/assets/142894870/533b8741-568b-42f0-a709-aba1f08b52fe)

4. After completing it, download the subtitle file and change the file extention to .ttml and upload it.
![image](https://github.com/WordPress/Learn/assets/142894870/49918117-43a6-4520-9515-75907f541ce8)

**Comment by pooja9712** [comment]
@devmuhib009 sir, I got the step but the problem which I'm facing when I upload file named like subtitles.ttml and click on submit, it's give me error "This site can’t be reachedThe webpage at https://wptv.wordpress.com/wp-admin/admin-post.php might be temporarily down or it may have moved permanently to a new web address.". So what's the exact issue, help me with it.

**Comment by devmuhib009** [comment]
Thanks @pooja9712 
@bsanevans what can we do in this situation?

**Comment by kaitohm** [comment]
No problem, I'll take a look 😃 

@pooja9712 Could you upload your subtitle file to this GitHub issue please? I'll upload it from my end and see if I get the same error.

Please note, GitHub won't allow uploading `.ttml` files. Please change the file extensiton to `.txt`, or compress the file as a `.zip` to upload it to this issue.

**Comment by pooja9712** [comment]
@bsanevans, thank you for your response, Here I'm sending .txt and zip both file just for safe side.
[subtitles.txt](https://github.com/WordPress/Learn/files/14021113/subtitles.txt)
[subtitles.zip](https://github.com/WordPress/Learn/files/14021115/subtitles.zip)

Thank you so much for your great support.

**Comment by pooja9712** [comment]
@bsanevans sir, Thank you for your response, here is my file, I can try minify file also but it's not working.
[triage_subtitles.zip](https://github.com/WordPress/Learn/files/14023892/triage_subtitles.zip)

Please check above file and let me know. Hope it's working fine for you. Thank you for your support.

**Comment by devmuhib009** [comment]
Please next time use below website to format subtitles. 
https://www.freeformatter.com/xml-formatter.html
I don't know why CodeBeautifier not working.

**Comment by devmuhib009** [comment]
Hi @pooja9712 
Tutorial has been published: https://learn.wordpress.org/tutorial/gu-how-to-do-triage-on-github/
