### ISSUE TITLE
Gujarati translation for Lesson Plan "How to use the List View"

### ISSUE THREAD

**Issue by DarshitRajyaguru** [WordPress/Learn#2165]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/how-to-use-the-list-view/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @harshgajipara
- Other info: https://docs.google.com/document/d/1f0wnckKHWIJxPP8GCMe-nCAuDVna3obwVOJoLvOt6Zc/edit

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by devmuhib009** [comment]
@DarshitRajyaguru Thanks for you excellent work. Please try to keep translation file public. So that anyone can review the content and leave there feedback here. This way we can ensure the quality of translation more accurately. ❤️

**Comment by DarshitRajyaguru** [comment]
@devmuhib009 I have update the access for the document. Please check it and
proceed further steps.

Thanks!!!

**Comment by devmuhib009** [comment]
Next step is reviewing the content. So, I will request @harshgajipara to review the content and tell his feedback here. Once a reviewer confirms that translation quality is good, we will move forward and prepare for publishing. 😊

**Comment by harshgajipara** [comment]
Hi,
I will review the translations soon. 
Thanks!

**Comment by harshgajipara** [comment]
Hi @devmuhib009 , @DarshitRajyaguru ,
I completed reviewing the translations and it looks good to me.
Thanks!

**Comment by devmuhib009** [comment]
Hi @DarshitRajyaguru 
I've drafted the content: https://learn.wordpress.org/wp-admin/post.php?post=82963&action=edit
Please complete step 5 & 6 from this handbook: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#lesson-plans

**Comment by DarshitRajyaguru** [comment]
Hi @devmuhib009,
I've added the Gujarati translation into drafted post: https://learn.wordpress.org/wp-admin/post.php?post=82963&action=edit
Please check and proceed further.

Thanks!!!

**Comment by devmuhib009** [comment]
Lesson plan published here: https://learn.wordpress.org/lesson-plan/gu-how-to-use-the-list-view/
