### ISSUE TITLE
Tutorial: Creating and customizing a header and footer

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2166]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Tutorial
- Content title: Adding and customizing a header and footer
- Topic description: Creating a header and footer 
- Audience (User, Developer, Designer, Contributor, etc.):
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner 

# Learning Objectives

Developing a header and footer with patterns

# Related Resources and Other Notes

### Automation Code

//tutorial

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/29c15b03-190a-4a24-8d35-ed38447880cf

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great job, @westnz!
I appreciate the distinction you made between _replacing_ and _editing_ these two template parts: had no idea the Replace option is relevant only to that specific page. 

Thanks for the TIL moment 🤓

**Comment by westnz** [comment]
Tank you so much for your review @ironnysh

**Comment by backpocketACE** [comment]
- [ x] Learning outcomes/objectives are clear.
- [x ] Technical concepts introduced in the content are accurate.
- [x ] The speed of demonstrations are easy to follow.
- [ x] The narration audio matches what is shown visually.
- [ x] Spelling and grammar are correct.
- [ x] Sound quality is consistent throughout the video.
- [ x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

I was able to follow along on my own practice site. And - similar to the previous comment, I appreciate the distinction between replace and edit. Thanks for the tutorial!

**Comment by westnz** [comment]
Great, thank you @JunebackpocketACE

**Comment by westnz** [comment]
Published as part of the Beginner User learning pathway.
