### ISSUE TITLE
Gujarati translation for "Regenerate Thumbnails"

### ISSUE THREAD

**Issue by pooja9712** [WordPress/Learn#2168]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/regenerate-thumbnails/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: [Roshan-narola](https://github.com/Roshan-narola)
- Other info: Gujarati translation:
https://docs.google.com/document/d/1a4YoKOLgUJ2nJBUB8qUloQvDeOw-GgN81sO2t9rnRwQ/edit?usp=sharing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by Roshan-narola** [comment]
@devmuhib009 sir, I review the translation and it's good to go for further process. 
Thank you.

**Comment by devmuhib009** [comment]
Hi, I've drafted the post here: https://learn.wordpress.org/wp-admin/post.php?post=82926&action=edit

Please complete from step 5 to 7 and update here. 
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials

**Comment by pooja9712** [comment]
@devmuhib009 sir, I replace all the content with Gujarati content. for further process as you know I'm not able to upload subtitles file so I send it here.

[Thumbnails_subtitles.zip](https://github.com/WordPress/Learn/files/14034116/Thumbnails_subtitles.zip)


Thank you for your support.

**Comment by devmuhib009** [comment]
Thank you.
Tutorial Published Here: https://learn.wordpress.org/tutorial/gu-regenerate-thumbnails/
