### ISSUE TITLE
Meeting Agenda January 25, 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2169]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @lada7042 ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

January 25 – NF Tushar
February 1 – need volunteer
February 8 – need volunteer
February 15 – need volunteer

2. Looking for feedback

- Come join the team's [2024 goal planning sessions](https://make.wordpress.org/training/2023/12/22/training-team-2024-goals-setting/) We would love to hear your thoughts and goals at the ([Slack async discussion](https://wordpress.slack.com/archives/C02RW657Q/p1705536014686119)) Closes January 29th.
- WordCamp Asia 2024 [Help the team brainstorm contribution ideas](https://make.wordpress.org/training/2023/12/22/brainstorm-table-lead-wordcamp-asia-2024-contributor-day/)  Closes January 30.
- Badge requirements -  [Request for feedback: Training Contributor badge requirements for code contributions](https://make.wordpress.org/training/2024/01/09/request-for-feedback-training-contributor-badge-requirements-for-code-contributions/) Closes January 26.
- [Discussion: Training’s contribution to the 6.5 release (and beyond)](https://make.wordpress.org/training/2024/01/22/discussion-trainings-contribution-to-the-6-5-release-and-beyond/) until February 5

3. Looking for volunteers

- Call for Hosts!!  Who would like to facilitate an Online Workshop this year?
- [Call for Mentors and Mentees](https://make.wordpress.org/community/2024/01/12/call-for-mentees-mentors-cohort-2/) for the project-wide Mentorship program - until February 7
- Request for Faculty reviewers to look at and audit the [Handbook](https://make.wordpress.org/training/handbook/).     [GitHub link for faculty](https://github.com/orgs/WordPress/projects/53/views/2)

**4. Updates from last week's dev-squad triage session**

Attendees: @psykro, @digitalchild, @devmuhib009, and @hellosatya

- Closed PR #2145 (with a [note](https://github.com/WordPress/Learn/pull/2145#issuecomment-1897943140))
- Triaged issue #2156 
- Triaged issue #2157 
- Triaged issue #2158 

Next week, @digitalchild is keen to host the dev squad session, and @psykro committed to getting the draft dev squad guidelines ready for that.

**5. Other news**

-Community Team [Proposal: Pilot program to test GatherPress on the WordPress.org network as a Meetup alternative](https://make.wordpress.org/community/2024/01/22/proposal-pilot-program-to-test-gatherpress-on-the-wordpress-org-network-as-a-meetup-alternative/)
- Badges- Congratulations to @benjamin_zekavica for receiving the Training Contributor badge for his German translation contributions.
-  If you would like more information on how you can receive one of the two badges the training team offers. [Badge Requirements](https://make.wordpress.org/training/handbook/about/team-profile-badges/)

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.

## 3. Project updates

- Learning pathways
We have some first draft redesign edits and thumbnails up for review, and will connect with Design re: next steps next week:
   - [Learn Redesign](https://www.figma.com/file/ZKaf6u8mIHkAanluWafXAp/Learn?type=design&mode=design) (See Learn WordPress, alternate take section)
   - [Video thumbnails](https://www.figma.com/file/1RXSQvg3UJcPCvxyQ9SGnl/Video-Thumbnails?type=design&node-id=0-1&mode=design)
-  [2024 goal planning sessions](https://make.wordpress.org/training/2023/12/22/training-team-2024-goals-setting/).
 

## 4. Faculty Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 5. Open Discussions

If you have topics you’d liked discussed in the meeting, please leave them as a comment on this issue.

- @devmuhib I am Translation Coordinator. I have a topic to discuss regarding content translation.
Someone has translated several pieces of content, all of which seem to be directly copied and pasted from Google Translate. I have personally reviewed this content and can confirm that the translations are not good in quality and, at times, not readable. Despite multiple requests to modify the content and maintain a certain standard, the issues persist, and the content remains unreadable. What is the appropriate course of action for such translations?
- @jonathanbossenger  brought up- our [use of InstaWP](https://github.com/WordPress/Learn/issues/2158) to be discussed by the team.
- @SierraTR asked does the content creator move issue over to ready to publish after third review. or can the third reviewer do it.
---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by devmuhib009** [comment]
I am Translation Coordinator. I have a topic to discuss regarding content translation.
Someone has translated several pieces of content, all of which seem to be directly copied and pasted from Google Translate. I have personally reviewed this content and can confirm that the translations are not good in quality and, at times, not readable. Despite multiple requests to modify the content and maintain a certain standard, the issues persist, and the content remains unreadable. What is the appropriate course of action for such translations?

**Comment by westnz** [comment]
Could we please highlight the need for more content to be reviewed and also share the following link: https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/

**Comment by ghost** [comment]
@westnz Ben has updated the meeting agenda so Section 2- Content ready for review will go to the GitHub link directly of content needing review.

**Comment by jonathanbossenger** [comment]
I would like to add the following issue raised about our [use of InstaWP](https://github.com/WordPress/Learn/issues/2158) to be discussed by the team.

**Comment by jonathanbossenger** [comment]
Added the dev-squad triage notes

**Comment by ghost** [comment]
Meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1706140806030049

**Comment by ghost** [comment]
Meeting Recap- https://make.wordpress.org/training/2024/02/01/training-team-meeting-recap-25th-january-2024/
