### ISSUE TITLE
Online Workshop: Starting your contributor journey with the WordPress Training Team

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2171]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Online Workshop
- Content title: Starting your contributor journey with the WordPress Training Team
- Topic description: This is an open session where I onboard folks to the Training Team.
- Audience (User, Developer, Designer, Contributor, etc.): Contributor
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Participants will learn what it means to be a Content Creator, Editor, Content Translator, Subject Matter Expert, and Administrator, for the team.
- Participants will leave with a clear understanding of what they can do next to contribute to the Training Team and its goals.

# Related Resources and Other Notes
I'll be using the team's blog and handbook as my resources, so there won't be any slides.

### Automation Code

//online-workshop

**Comment by devmuhib009** [comment]
What the duty of co-host? I need to understand the role.

**Comment by kaitohm** [comment]
Great question, @devmuhib009 👍 The Training Team has a guide that describes the role: https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/

In this particular workshop, I'm looking for someone to:
- keep an eye on the chat while I'm talking
- answer questions from users if they come in
- Record the maximum number of participants that join the session
- Remove someone from the call if they do not follow the code of conduct

The workload should be very light for the co-host in this workshop, and would be a great one to start in. As you are a Faculty member, you do not need to go through the application/vetting process. Let me know here if you're interested in the opportunity 😄

**Comment by devmuhib009** [comment]
Yes, I am interested.

**Comment by kaitohm** [comment]
Thanks for volunteering, @devmuhib009 🙌 I've noted your name in GitHub.

Please also sign up on Meetup.com. I'll then be able to set you as a co-host there, too.

**Comment by kaitohm** [comment]
Recording uploaded: https://wordpress.tv/2024/02/16/starting-your-contributor-journey-with-the-wordpress-training-team/

**Comment by kaitohm** [comment]
Also now on YouTube: https://www.youtube.com/watch?v=V0spoaaCvAY
