### ISSUE TITLE
Tutorial: Managing spam on your website

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2174]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Tutorial
- Content title: Managing spam on your website
- Topic description: Dealing with spam
- Audience (User, Developer, Designer, Contributor, etc.): Users
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

Reducing spam on your site

# Related Resources and Other Notes

### Automation Code

//tutorial

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/338c8bd9-c4d3-4787-833a-18659bad801b

**Comment by backpocketACE** [comment]
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations is easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines] and [Promotional Guidelines] are being followed.
- [x] Media assets are all in the public domain ([CC0].

wheew! Feel more confident about allowing comments on blog pages—Thx for a few solutions to manage them.

**Comment by westnz** [comment]
I appreciate the feedback @JunebackpocketACE

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Awesome tutorial, @westnz! Accessible, thorough, and informative 👏

One nitpicky comment: reCAPTCHA is _Google's_ CAPTCHA product. It's so popular it became synonymous with the technology but it's also very controversial ([see some background here](https://en.wikipedia.org/wiki/ReCAPTCHA#Criticism)).

**Comment by westnz** [comment]
Thank you @ironnysh 
Are you suggesting I mention it is a Google product? How would you word it? 😄

**Comment by ironnysh** [comment]
I personally resent it when machines force me to prove I'm human 😀 _BUT_, if you do want to include it as an option, how about scrubbing the "re" and referring to the general CAPTCHA?
Then you'd have a Plugins page that also presents alternative implementations (Cloudflare Turnstile, for example).

**Comment by westnz** [comment]
That is helpful. Thanks @ironnysh 😉

**Comment by iankuan** [comment]
- [x]  Learning outcomes/objectives are clear.
- [x]  Technical concepts introduced in the content are accurate.
- [x]  The speed of demonstrations is easy to follow.
- [x]  The narration audio matches what is shown visually.
- [x]  Spelling and grammar are correct.
- [x]  Sound quality is consistent throughout the video.
- [x]  [Brand Usage Guidelines] and [Promotional Guidelines] are being followed.
- [x]  Media assets are all in the public domain ([CC0].

Love this topic and demonstrations. Thank for the great work. I do find it's easy to follow and understand. I also follow the tutorial and get exact outcome I expected. Cheer!

**Comment by SierraTR** [comment]
Third review completed - moved to Preparing to Publish.

Nice job Wes. Ronny's comment is correct in that reCAPTCHA is a Google product based upon the original CAPTCHA system. You might just mention that part as another decision point for users looking for more options.

**Comment by westnz** [comment]
Thank you very much for the review @yan-kuan, and @SierraTR for confirming + moving to Preparing to Publish.

**Comment by westnz** [comment]
Updated and published as part of the Beginner user learning pathway in Sensei.
