### ISSUE TITLE
Bengali translation for Tutorial "Managing Settings: Writing"

### ISSUE THREAD

**Issue by KawsarAlamEven** [WordPress/Learn#2177]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/managing-settings-writing/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/2177
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by KawsarAlamEven** [comment]
Hi, i just translated the content, here is [the link](https://docs.google.com/document/d/1KM2Vsz1EYe3HRoKRlrZUwAM1eYKLwJDVAPcAmSO9zS0/edit?usp=sharing)

**Comment by devmuhib009** [comment]
Hi,
I've added some suggestion here. Please update these and try to keep some popular words as it is. Like the word "Uncategorized" is more understandable than "শ্রেণী বহির্ভূত" word. 

Try to use this Glossary Page: https://translate.wordpress.org/locale/bn/default/glossary/

> সেটিংস ম্যানেজঃ লেখা

ম্যানেজ সেটিংসঃ লেখা

> এই প্রদর্শনটি আপনাকে আপনার অনুপস্থিত পোস্ট ক্যাটাগরি, অনুপস্থিত পোস্ট ফরমেট পার্সোনালাইজ করার সুযোগ দেবে এবং ইমেলের মাধ্যমে কীভাবে একটি পোস্ট তৈরি করতে হয় তা শিখাবে।

এই প্রদর্শনটি আপনাকে আপনার ডিফল্ট পোস্ট ক্যাটাগরি, ডিফল্ট পোস্ট ফরমেট পার্সোনালাইজ করার সুযোগ দেবে এবং ইমেলের মাধ্যমে কীভাবে একটি পোস্ট তৈরি করতে হয় তা শিখাবে।

> Learning outcomes

শেখার ফলাফল

>আপনার ডিফল্ট পোস্ট বিভাগ আপডেট করার সুবিধা কি?

আপনার ডিফল্ট পোস্ট ক্যাটাগরি আপডেট করার সুবিধা কি?

> হভার

হোভার

>শ্রেণী বহির্ভূত
আন ক্যাটাগরাইজডগুলো

>প্রাক-নির্বাচিত

প্রি-সিলেক্টেড

>তবে কিছু লোকের তাদের ওয়েবসাইটে সীমিত অ্যাক্সেস থাকতে পারে, নতুন পোস্ট যোগ করা কঠিন করে তোলে।

তবে কিছু লোকের তাদের ওয়েবসাইটে সীমিত অ্যাক্সেস থাকতে পারে, যা নতুন পোস্ট যোগ করা কঠিন করে তোলে।

> যদিও এখানে একটি ধরা আছে
যদিও এখানে একটি  সমস্যা আছে

>সংস্থানগুলি

রিসোর্সগুলি

**Comment by KawsarAlamEven** [comment]
Thanks to your suggestion . And I have updated all of these.

**Comment by devmuhib009** [comment]
I've added you on Learn WordPress website as contributor. Please check your email associated with WordPress account and confirm the sign up. Then I will draft the post, so you can modify the translation.

**Comment by KawsarAlamEven** [comment]
I changed the translation.

**Comment by devmuhib009** [comment]
Do you verify email address?

**Comment by KawsarAlamEven** [comment]
yes i done.

**Comment by devmuhib009** [comment]
Ok I will draft the post soon.

**Comment by KawsarAlamEven** [comment]
ok.

**Comment by devmuhib009** [comment]
Hi, I've drafted the post here: https://learn.wordpress.org/wp-admin/post.php?post=83069&action=edit
Please complete from 5 to 7 and comment here when you are done. https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials

Thanks

**Comment by KawsarAlamEven** [comment]
Done my work..

**Comment by devmuhib009** [comment]
I cannot find the subtitle for the video you uploaded on WordPress.tv

**Comment by devmuhib009** [comment]
Hi, @KawsarAlamEven I've approved your subtitle on WordPress.tv and your post is live here: https://learn.wordpress.org/tutorial/bn-managing-settings-writing/

I will discuss about subtitle upload problem with faculty members. Thanks

**Comment by KawsarAlamEven** [comment]
Thanks.
