### ISSUE TITLE
Online Workshop: Dashboard & Documentation - Where to find the answers

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2184]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): online workshop
- Content title: Dashboard & Documentation - Where to find the answers
- Topic description: This workshop will highlight areas of the WordPress dashboard and the documentation area to find answers and information about each of the dashboard parts. When signing up for the workshop please add your dashboard questions in the comments to be answered during the workshop.
- Audience (User, Developer, Designer, Contributor, etc.): Designer, User
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Navigate the WordPress dashboard more confidently.
- Know where to find information more easily. 

# Related Resources and Other Notes
- https://wordpress.org/documentation/category/dashboard/
- https://wordpress.tv/2024/01/19/getting-started-with-the-wordpress-dashboard/
- https://github.com/orgs/WordPress/projects/33/views/1?filterQuery=694&pane=issue&itemId=5900732
- https://github.com/orgs/WordPress/projects/33/views/1?filterQuery=dashboard&pane=issue&itemId=5900750

### Automation Code
 //online-workshop

**Comment by zunaid321** [comment]
May I know what are the requirements and tasks to become a Co-host?

**Comment by ghost** [comment]
@zunaid321 Hi, thank you for inquiring about being a co-host. I see that you are already a member of the training team's Slack channel. The requirements to co-host are found in the handbook. [Co-Hosting](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) 
Is the time alright with you? I see that it would be the middle of the night for you. If you have any questions you can contact me on the #training channel on Slack. @lada7042

**Comment by lada7042** [comment]
//lesson

**Comment by ghost** [comment]
co-host added @backpocketace on WordPress.org

**Comment by ghost** [comment]
Had to reschedule due to tech problems opening Local. After I canceled I realized I could have switched to the playground which I will use next time. 
Rescheduled for Feb. 15- https://www.meetup.com/learn-wordpress-online-workshops/events/299178586/

**Comment by ghost** [comment]
Complete- https://wordpress.tv/2024/02/16/laura-adamonis-dashboard-documents-where-to-find-the-answers/
