### ISSUE TITLE
Meeting Agenda February 1, 2024

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2185]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @bsanevans ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- February 1 – Aanchal Singh
- February 8 – Zunaid Amin
- February 15 – **need volunteer**
- February 22 – **need volunteer**

**2. Looking for feedback**

- [Discussion: Training’s contribution to the 6.5 release (and beyond)](https://make.wordpress.org/training/2024/01/22/discussion-trainings-contribution-to-the-6-5-release-and-beyond/) **until February 5**
- Should we encourage reviewers who didn't use the checklist to re-add a review with the checklist? ([Slack conversation from last week](https://wordpress.slack.com/archives/C02RW657Q/p1706143006376859?thread_ts=1706142591.956799&cid=C02RW657Q).)
- The team discussed providing GitHub triage access to contributors who have shown consistent contribution and request the access. ([Last week's Slack message](https://wordpress.slack.com/archives/C02RW657Q/p1706144491183659))
   - What do folks think about the new processes documented in this handbook page? [Joining the Learn Content Triage Team](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/joining-the-learn-content-triage-team/)
- Add your thoughts about adding a "Completed Courses" section to one's WordPress.org profile page: https://meta.trac.wordpress.org/ticket/7411

**3. Looking for volunteers**

- Call for Hosts!! Who would like to facilitate an Online Workshop this year?
[Call for Mentors and Mentees](https://make.wordpress.org/community/2024/01/12/call-for-mentees-mentors-cohort-2/) for the project-wide Mentorship program - until February 7
- Request for Faculty reviewers to look at and audit the [Handbook](https://make.wordpress.org/training/handbook/). [GitHub link for faculty](https://github.com/orgs/WordPress/projects/53/views/2)
- Would you like to author a future Contributor Spotlight post for the team? ([Handbook guide](https://make.wordpress.org/training/handbook/faculty-program/writing-contributor-spotlight-posts/))
- Thanks to Courtney for publishing [Guide Program Management](https://make.wordpress.org/training/handbook/guide-program/guide-program-management/)
   - We're looking for Faculty to take over running this successful program.

**4. Updates from last week's dev-squad triage session**

(See comment below.)

**5. Other news**

- Community Team [Proposal: Pilot program to test GatherPress on the WordPress.org network as a Meetup alternative](https://make.wordpress.org/community/2024/01/22/proposal-pilot-program-to-test-gatherpress-on-the-wordpress-org-network-as-a-meetup-alternative/)
- Thank you, Jonathan, for updating the following handbook pages
   - [The Training Contributor Badge](https://make.wordpress.org/training/handbook/about/team-profile-badges/#training-contributor-badge) requirements for code contributions has been updated to provide more clarity.
   - The [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) handbook page now includes the content from the Contributing with code page, which is deleted.
   - The [dev-squad guidelines](https://make.wordpress.org/training/handbook/training-team-how-to-guides/dev-squad-guidelines/) have been published, which allows other training team contributors to host dev-squad triage on Thursdays.

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.

## 3. Project updates

- Learning Pathways
- [2024 goal planning sessions](https://make.wordpress.org/training/2023/12/22/training-team-2024-goals-setting/)
   - Reps will be publishing an outline of goals soon. The post will be putting out a call for folks to own projects and lead them for the team.

## 4. Faculty Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 5. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by digitalchild** [comment]
Updates from last week’s dev-squad triage session

@digitalchild hosted his first meeting with an assist from psykro tested the guidelines, and they were added to the handbook here - https://make.wordpress.org/training/handbook/training-team-how-to-guides/dev-squad-guidelines/

Attendees: psykro, digitalchild, devmuhib, melbos

Reviewed PR - https://github.com/WordPress/Learn/pull/2172 (Add script to count unique learners in Sensei)
No issues waiting to be triaged

For our last 15 minutes we decided to look into the Content Feedback that is awaiting validation. https://github.com/orgs/WordPress/projects/78/views/1

We looked at the two oldest issues

Closed https://github.com/WordPress/Learn/issues/832 [Related Course: Create a Custom Block Theme #1] How Classic and Block Themes Are Developed - Lesson Plan  
Closed After fixing - https://github.com/WordPress/Learn/issues/850 [Course Exercise] Creating Template Parts: Headers and Footers

**Comment by devmuhib009** [comment]
**Need to Discuss in Open Discussion:**
Multiple users are reporting an issue on WordPress.tv where normal users cannot upload subtitle files, while admins can. This needs attention and quick solution. 
https://github.com/WordPress/Learn/issues/2168
https://github.com/WordPress/Learn/issues/2151
https://meta.trac.wordpress.org/ticket/7419

**Comment by kaitohm** [comment]
This meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1706745649031559

**Comment by webtechpooja** [comment]
Recap notes are published- https://make.wordpress.org/training/2024/02/05/training-team-meeting-recap-1st-february-2024/
