### ISSUE TITLE
Learn.WordPress.org Deployment

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2186]
@pkevan 

We have had a couple of PRs merged recently:

- #2179 
- #2178 
- #1920 

Could we ask you to deploy these changes at your earliest convenience?

Please feel free to close this issue once the updates have been deployed.

Thanks in advance.

**Comment by pkevan** [comment]
Sure - can you provide some details on testing each of these PRs?

**Comment by pkevan** [comment]
#1920 - doesn't look like this needs to be deployed, as it's a github file, so won't exist on production.

**Comment by jonathanbossenger** [comment]
> Sure - can you provide some details on testing each of these PRs?

No problem.

For #2179, add a YouTube video to the content of any Sensei Course Lesson, and it should fill up the available area, and not display narrower than the text, as reported in #2091

For #2178, it should add two date fields with the label "Total number of students" at the top of the Sensei LMS -> Reports screen. Selecting a start and end date should display the total number of students for that period. This is an enhancement provided by the Sensei team to add the functionality requested in #2111. 

> doesn't look like this needs to be deployed, as it's a github file, so won't exist on production.

Agree, I was just listing any PRs that were merged recently

**Comment by pkevan** [comment]
Committed in https://meta.trac.wordpress.org/changeset/13159 and https://meta.trac.wordpress.org/changeset/13160, now deployed.
