### ISSUE TITLE
Bengali translation for Tutorial "Using the Block Editor List View"

### ISSUE THREAD

**Issue by KawsarAlamEven** [WordPress/Learn#2187]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/how-to-use-the-list-view/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/631
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by zunaid321** [comment]
Would like to review this one

**Comment by KawsarAlamEven** [comment]
Hi, i just translated the content, here is [the link](https://docs.google.com/document/d/1n2L65V6HQEpHnma9YE2A-LQrsqCcQVgcEebmXAqBUPQ/edit?usp=sharing)

**Comment by KawsarAlamEven** [comment]
> Would like to review this one

yes.

**Comment by KawsarAlamEven** [comment]
Thank You for your support.

**Comment by zunaid321** [comment]
@KawsarAlamEven Thank you for your work. It would be awesome if you can replace the strong bengali words with the original english words. For example:

তালিকা ভিউ: list view
অতিরিক্ত ব্লক: additional block
ব্লক সন্নিবেশ: insert blocks

Etc.

Thank you again for your hard work. Will be waiting to review your updated changes.

**Comment by KawsarAlamEven** [comment]
I have replaced strong Bengali words with original English words. thank you.

**Comment by devmuhib009** [comment]
I suggested some modifications. Please change these and keep in mind for next translation.

**Comment by KawsarAlamEven** [comment]
I have modified these translations. Thanks for your advice.

**Comment by devmuhib009** [comment]
Thanks @KawsarAlamEven 

I've just drafted the content here: https://learn.wordpress.org/wp-admin/post.php?post=83180&action=edit

Please complete from step 5 to 7 when @zunaid321 completes the review. 
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials

**Comment by zunaid321** [comment]
Thank you for your input @devmuhib009 

Everything seems okay now! Great work everyone! 🚀

**Comment by KawsarAlamEven** [comment]
Thanks.

**Comment by KawsarAlamEven** [comment]
> Thanks @KawsarAlamEven
> 
> I've just drafted the content here: https://learn.wordpress.org/wp-admin/post.php?post=83180&action=edit
> 
> Please complete from step 5 to 7 when @zunaid321 completes the review. https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials

Completed all steps.  Thanks All

**Comment by devmuhib009** [comment]
Tutorial translation published here: https://learn.wordpress.org/tutorial/bn-how-to-use-the-list-view/
