### ISSUE TITLE
Increase contrast for course module names/titles

### ISSUE THREAD

**Issue by varlese** [WordPress/Learn#219]
For courses on Learn WordPress that have multiple modules, the title of each module is somewhat hard to read since it's in a relatively dark color on a dark background. Here's an [example course](https://learn.wordpress.org/course/polyglots-contributor-training/), and a screenshot of how the module titles look right now.

<img width="646" alt="module name" src="https://user-images.githubusercontent.com/1361760/121945855-3e231200-cd22-11eb-82d0-13aaa900d44a.png">

To make the module titles clearer, it would help to change the class color to something brighter (i.e. `#fff`), like in this example.

<img width="624" alt="module name change" src="https://user-images.githubusercontent.com/1361760/121946467-f5b82400-cd22-11eb-9ec0-efb52fdd1952.png">

**Comment by hlashbrooke** [comment]
I added some CSS to the Customiser for #245 that also fixes this issue. Since it's in the Customiser it's only a temporary fix until it's submitted a proper patch though.

**Comment by askhellosatya** [comment]
//assign

**Comment by askhellosatya** [comment]
The issue seems that already been addressed. I haven't found any issue with the example course or any other course. Please @bsanevans have a look.

**Comment by kaitohm** [comment]
I can confirm the CSS added in #245 is no longer in the Customizer, and therefore this issue seems to now be resolved. Thanks for checking, @askhellosatya .
