### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2190]
# Details

- Content type: Lesson
- Content title: Settings
- Topic description: We will explore the WordPress theme configuration file theme.json and some of the available options for theme Settings.
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- Discover what theme Settings are for
- Explore the Settings available to end users
- Use theme.json to control available Settings

# Related Resources and Other Notes

- https://developer.wordpress.org/themes/global-settings-and-styles/settings/ 
- https://wordpress.org/documentation/article/work-with-blocks/#block-settings 
- https://developer.wordpress.org/block-editor/how-to-guides/themes/global-settings-and-styles/#settings 
- https://developer.wordpress.org/news/2023/08/31/adding-and-using-custom-settings-in-theme-json/ 
- https://developer.wordpress.org/themes/global-settings-and-styles/settings/color/
- https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/#color
- https://developer.wordpress.org/themes/global-settings-and-styles/settings/settings-reference/

**Comment by cynthianorman** [comment]
//lesson

**Comment by cynthianorman** [comment]
//lesson

**Comment by cynthianorman** [comment]
This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

https://youtu.be/Yom_gcMKxfE (unlisted)

**Comment by jonathanbossenger** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Looks good to me. I especially appreciated how you showed how the different levels of settings are prioritized.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/05/23/global-settings-and-styles-settings-overview/

**Comment by jonathanbossenger** [comment]
https://youtu.be/9Ux9U8qsAzQ

**Comment by cynthianorman** [comment]
@jonathanbossenger 
YouTube Chapters
(0:06) Learning objectives
(0:23) What are theme settings for?
(0:37) Explore the settings available to end users
(1:19) Use theme.json to control available settings
(3:49) Next steps

**Comment by jonathanbossenger** [comment]
Thanks @cynthianorman

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/global-theme-settings/

**Comment by jonathanbossenger** [comment]
//publish
