### ISSUE TITLE
Patterns

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2193]
# Details

- Content type: Lesson
- Content title: Patterns
- Topic description: We will cover the basics of how to create a pattern from scratch and register patterns within your theme.
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- List and describe the sources of patterns available within WordPress.
- Add the Patterns property to theme.json and list the patterns to include in your theme from the Pattern Directory.
- Describe the process of building a pattern from scratch in order to bundle it with your theme.

# Related Resources and Other Notes

- [Patterns](https://developer.wordpress.org/themes/global-settings-and-styles/patterns/)
- [Submit your block pattern to the Pattern Directory](https://wordpress.org/documentation/article/submit-your-block-pattern-to-the-directory/)

**Comment by cynthianorman** [comment]
This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

https://youtu.be/uK-RiXymPq8 (unlisted)

**Comment by jonathanbossenger** [comment]
## Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

An excellent introduction to patterns, I like that you included both patterns from the directory, patterns already bundled in a theme, but also how to create your own pattern.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/05/23/global-settings-and-styles-patterns-overview/

**Comment by jonathanbossenger** [comment]
https://youtu.be/91uatfIWkxw

**Comment by cynthianorman** [comment]
@jonathanbossenger 
### YouTube Chapters
(0:05) Learning objectives
(0:34) Sources of patterns
(1:09) The WordPress.org pattern directory
(1:48) Creating patterns
(2:47) Next steps

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/theme-patterns/
