### ISSUE TITLE
Style Variations

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2194]
# Details

- Content type: Lesson
- Content title: Style Variations
- Topic description: Creating style variations or simply theme.json variations
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- Define and describe style variations.
- Differentiate between theme and style variation JSON files.
- Differentiate between a child theme and a style variation.

# Related Resources and Other Notes

- [Style Variations](https://developer.wordpress.org/themes/global-settings-and-styles/style-variations/)

**Comment by cynthianorman** [comment]
This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

https://youtu.be/UKh7HvRarjs (unlisted)

**Comment by annezazu** [comment]
Thanks so much for working on this! Some feedback:

- Some of the slides change really quickly, including the first slide and the slide at 19-20s.
- Between 25s-45s style variations aren't really explained beyond calling it a different style combination. I'd be more specific: "Style variations allow you to quickly change the look and feel of your site with predefined styling options set by the theme. Theme authors can choose to bundle these style variations. They can change a wide range of design aspects globally including colors, spacing, and typography."  This is rough but you get the idea.
- When going through the theme.json file, I might go through a few more examples within a variation showing how things can change and shift.

**Comment by cynthianorman** [comment]
@annezazu thank you so much!

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great overview, @cynthianorman.
I think that implementing @annezazu's feedback could make it even better :-)

**Comment by cynthianorman** [comment]
Thank you so much @ironnysh - I appreciate you!

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/05/23/global-settings-and-styles-style-variations/

**Comment by jonathanbossenger** [comment]
https://youtu.be/8gKGwZgxlas

**Comment by cynthianorman** [comment]
@jonathanbossenger 
### YouTube Chapters
(0:05) Learning objectives
(0:21) What are style variations?
(2:36) Differentiate between theme and style variation JSON files
(3:07) Differentiate between a child theme and a style variation
(3:59) Next steps

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/style-variations/

**Comment by annezazu** [comment]
I want to note that if we are able to add in for style variations a section later on for color and typography only variations that would be super helpful for 6.6 and beyond: https://github.com/WordPress/gutenberg/issues/61215

**Comment by jonathanbossenger** [comment]
Thanks. @annezazu. Could we ask you to create a lesson "update" issue (similar to this [one](https://github.com/WordPress/Learn/issues/2514)) that links to this issue? You're welcome to use the blank issue template, as we don't have a specific format for lesson updates like this (yet). 

Then, we'll add it to a "Todos" section of the [Theme developer tracking issue](https://github.com/WordPress/Learn/issues/2045). This way, we don't lose the request but also don't lose momentum on completing the lessons initially planned for our launch date. 

Once the update issue is created, I'll add it to our to-do list on the tracking issue.
