### ISSUE TITLE
Create Block Theme plugin

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2197]
# Details

- Content type: Lesson
- Content title: Create Block Theme plugin
- Topic description: An introduction to the Create Block theme plugin, providing a high-level overview of its features.
- Audience: Developer
- Experience Level: Beginner

# Learning Objectives

 - Describe what the Create Block theme plugin is, and why you might use it
 - Identify the main features of the plugin and describe their functionality

# Related Resources and Other Notes

- https://learn.wordpress.org/tutorial/streamline-your-block-theme-development-with-create-block-theme/
- https://learn.wordpress.org/tutorial/manage-your-block-theme-fonts-with-create-block-theme/
- https://learn.wordpress.org/tutorial/create-block-theme-improvements/
- https://wordpress.org/plugins/create-block-theme/
- https://developer.wordpress.org/news/2023/12/05/a-walk-through-tutorial-on-using-create-block-theme-plugin/

# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for review
- [x] Lesson reviewed
- [x] Lesson video submitted and published to WPTV
- [x] Lesson created on Learn.WordPress.org 
- [x] Lesson video published to YouTube
- [x] Lesson on Learn.WordPress.org updated with YouTube video
- [x] Lesson published to Learn.WordPress.org

**Comment by cynthianorman** [comment]
//lesson

**Comment by cynthianorman** [comment]
This Beginner Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

https://youtu.be/fH5magKcq08 (unlisted)

**Comment by backpocketACE** [comment]
Thanks! That was nicely done. :) 

- [x ] Learning outcomes/objectives are clear.
- [x ] Technical concepts introduced in the content are accurate.
- [x ] The speed of demonstrations is easy to follow.
- [x ] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [x ] Sound quality is consistent throughout the video.
- [x ] [Brand Usage Guidelines] and [Promotional Guidelines]are being followed.
- [x ] Media assets are all in the public domain (CC0)

**Comment by cynthianorman** [comment]
Thank you so much for your feedback @JunebackpocketACE

**Comment by cynthianorman** [comment]
Given that WordPress 6.5 will include the new Font Library, this lesson will need to reflect this change.

**Comment by jonathanbossenger** [comment]
@cynthianorman In testing the Font Library during my live stream today, I discovered that the new font library only adds the fonts to the WordPress install. If you then apply the fonts to a theme, and either save the theme files or export to a new theme, using create block theme, then the paths to the font's point to the WordPress install.

So Create Block Themes Manage Theme Fonts tool is still useful for theme developers who want to keep the fonts with the theme.

**Comment by cynthianorman** [comment]
@jonathanbossenger I've uploaded this video to WordPress.tv and published it. We still need to add it to YouTube and create the subtitles. Thank you!

**Comment by jonathanbossenger** [comment]
Thanks @cynthianorman the video has been uploaded to YouTube. https://youtu.be/xzs7sJRn0bM

Please share the chapters here when you have a moment, and I'll update them on YT

**Comment by cynthianorman** [comment]
@jonathanbossenger do you know what happened to the video on YouTube? I was just trying to embed it into the Sensei lesson and got an error that it doesn't exist.

**Comment by jonathanbossenger** [comment]
Huh, that's weird, it's still there. I wonder if there was a network issue at the time?

**Comment by jonathanbossenger** [comment]
Whoops, I hadn't made it public. Apologies.

**Comment by cynthianorman** [comment]
@jonathanbossenger 
### YouTube Chapters
(0:10) Learning objectives
(0:21) Create Block Theme plugin options
(2:16) Managing fonts
(3:08) Exporting changes to theme files

**Comment by jonathanbossenger** [comment]
Thanks @cynthianorman I've updated the chapters.

**Comment by jonathanbossenger** [comment]
@cynthianorman I wanted to share this Create Block theme update with you: https://github.com/WordPress/create-block-theme/pull/595

It looks like CBT no longer has the font management User Interface, relying rather on the built in core Font library.

I did a quick review of your existing video, and it looks like all you'd need to do is cut out the Manage your Fonts section (from around 2:10 to about 3:07), and the rest of the video is still valid (nice work on making it so that this section could easily be removed).

I wouldn't worry about making this edit now, we can circle back to this once the rest of the learning pathway is complete, but I wanted to just give you a heads up.

**Comment by cynthianorman** [comment]
ok @jonathanbossenger sounds good

**Comment by jonathanbossenger** [comment]
Closing this again in favor of managing the update in #2514
