### ISSUE TITLE
Bengali translation for Tutorial "Finding Images Using the WordPress Photo Directory"

### ISSUE THREAD

**Issue by KawsarAlamEven** [WordPress/Learn#2198]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/finding-images-using-the-wordpress-photo-directory/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/522
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by devmuhib009** [comment]
Please replace the content title with your original titile.

**Comment by KawsarAlamEven** [comment]
> Please replace the content title with your original titile.

ok

**Comment by zunaid321** [comment]
Would like to review this one

**Comment by KawsarAlamEven** [comment]
Hi, i just translated the content, here is [the link](https://docs.google.com/document/d/1VkBw6i0WdL_FXazWynrjCJMmvF5TtLITvpacjXjI5iA/edit?usp=sharing)

**Comment by devmuhib009** [comment]
@zunaid321 please review the content.

**Comment by zunaid321** [comment]
@KawsarAlamEven I have suggested some edits. Please do look into it.

And as always, thank you for your hard work.

**Comment by KawsarAlamEven** [comment]
> @KawsarAlamEven I have suggested some edits. Please do look into it.
> 
> And as always, thank you for your hard work.

I have edited your proposal. And try my best to translate perfectly

**Comment by zunaid321** [comment]
@KawsarAlamEven There is one single change needed. I have mentioned it in the Docs. If that is changed, all is good.

Thanks for the good work as always!

**Comment by devmuhib009** [comment]
Hi,

I've just drafted the content here: https://learn.wordpress.org/wp-admin/post.php?post=83219&action=edit

https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials
After modifying the suggestion, please complete step 5 to 7 and notify here.

**Comment by KawsarAlamEven** [comment]
Complete step 5 to 7 . Thanks All.

**Comment by devmuhib009** [comment]
Tutorial published here: https://learn.wordpress.org/tutorial/bn-finding-images-using-the-wordpress-photo-directory/
Thanks
