### ISSUE TITLE
Meeting Agenda February 8th, 2024

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#2200]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- February 8 – [@Zunaid Amin](https://wordpress.slack.com/team/U057S7YUY95)
- February 15 – [@Saqib Ali ](https://wordpress.slack.com/team/U06FBSB6YA2)
- February 22 – need volunteer
- February 29 – [@Roshan Narola ](https://wordpress.slack.com/team/U06DY6WGZHA)

**2. Looking for feedback**

- What data do we want to know about folks using Learn WordPress? (P2 coming)
- [Discussion: Translation Plugin on Learn](https://make.wordpress.org/training/2024/02/07/discussion-translation-plugin-on-learn/) 

**3. Looking for volunteers**

- item 1
- item 2

**4. Updates from last week's dev-squad triage session**

Attendees: @psykro, @digitalchild, @devmuhib, @melbos

Triaged one new bug

- #2196 

Reviewed other open PRs to see if they could be moved along

- #304 

There was some discussion on this item, which you can read in the comments on that issue. I'd like to invite the training team to add their input on the suggested change. 

**5. Other news**

- [Discussion: Training’s contribution to the 6.5 release (and beyond)](https://make.wordpress.org/training/2024/01/22/discussion-trainings-contribution-to-the-6-5-release-and-beyond/)
- item 2

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.

## 3. Contribution Acknowledgement
- Badges awarded: [Darshit Rajyaguru](https://profiles.wordpress.org/darshitrajyaguru97/), [pooja9712](https://profiles.wordpress.org/pooja9712/), [narolainfotech](https://profiles.wordpress.org/narolainfotech/), Margherita Pelonara
- Props -- do you have someone you'd like to nominate to give props for their work on the team?

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - Design is still updating the design using the new .org design framework. [You can review the latest iteration here](https://href.li/?https://www.figma.com/file/ZKaf6u8mIHkAanluWafXAp/Learn?type=design&node-id=2211-18443&mode=design).

## 5. Faculty Updates

- [Faculty Survey Results – Q1 2024](https://make.wordpress.org/training/2024/02/02/faculty-survey-results-q1-2024/)
 - 1:1 chats with team reps
 - Faculty Program Online Workshop
 - [February 15th](https://www.meetup.com/learn-wordpress-online-workshops/events/298706726) and [February 16th](https://www.meetup.com/learn-wordpress-online-workshops/events/298706927)onboarding workshops
 - February 21st Faculty Program
   - [RSVP for Session 1](https://www.meetup.com/learn-wordpress-online-workshops/events/299049829/)
   - [RSVP for Session 2](https://www.meetup.com/learn-wordpress-online-workshops/events/299049832/)

## 6. Open Discussions

- [Google Slides Recording](https://support.google.com/docs/answer/14221290?hl=en)
You can only record your presentations in Google Chrome Browsers

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by saqib59** [comment]
I am interested in volunteering for 15th Feb.

**Comment by devmuhib009** [comment]
Want to give props to [@Shail Mehta](https://wordpress.slack.com/team/U03S4HG2KU1) for reviewing multiple Gujrati translations and [@Zunaid Amin](https://wordpress.slack.com/team/U057S7YUY95) for reviewing multiple Bengali translations.

**Comment by jonathanbossenger** [comment]
## Other news

During February @westnz and @Jonathan will be testing out learning pathway content creator office hours. This is an opportunity for anyone working on learning pathway content, or anyone interested in working on learning pathway content, to meet, discuss what content they are working on, ask questions, or find content to work on for the learning pathways. 

There will be two office hour sessions:

- Tuesday, 13 Feb @ 21:00 UTC hosted by @westnz
- Thursday 29 Feb @ 14:00 UTC hosted by @Jonathan

If you are currently working on any learning pathway lessons, or are interested in creating lessons for learning pathways, please feel free to join these sessions. 

Zoom meeting URLs for these office hours will be shared in the #training Slack channel closer to the time.

**Comment by jonathanbossenger** [comment]
Added the dev-squad update. I added the attendees with their .org profile name

**Comment by jonathanbossenger** [comment]
Props:

`@Jamie Madden` for successfully hosting dev squad for the first time last week, helping to draft the dev squad guidelines, and always being an enthusiastic dev-squad contributor.

`@Cynthia Norman` and `@iRonnysh` for their contributions to the learning pathways so far, and for the work they have committed to doing.

**Comment by Roshan-narola** [comment]
Hi there. I'm interested as note taker on 29 Feb.

**Comment by ghost** [comment]
Meetup recap- https://make.wordpress.org/training/2024/02/14/training-team-meeting-recap-8th-february-2024/
