### ISSUE TITLE
Tutorial: Font Library

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2203]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Tutorial
- Content title: Font Library
- Topic description: The Font Library makes it easy for anyone to install, remove, and activate fonts across your site. It’s available globally, independent of the theme activated, similar to the Media Library. Any installed font, whether installed by a user or a theme, can then be selected across the editing experience.
- Audience (User, Developer, Designer, Contributor, etc.): Users
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner-Intermediate

# Learning Objectives

Utilising the font library.

# Related Resources and Other Notes
https://github.com/WordPress/gutenberg/issues/55277

### Automation Code

//Tutorial

**Comment by ironnysh** [comment]
Hi @westnz, I’d like to write the script for this lesson.

There’s also #401, which I’d be happy to take on, but I’m not sure about the format (are we still doing lesson plans?).

**Comment by westnz** [comment]
This is not part of one of the learning pathways.  The Issue was created alongside the previous release. This would've not been a lesson plan but a normal video tutorial. In the future, we will only have lessons; some lessons might have a tab with more info for teachers/instructors. 

May I suggest we focus on lessons that form part of the Advanced user learning pathway next? 😃

**Comment by ironnysh** [comment]
Got it! Thanks for explaining 🙂 

> focus on lessons that form part of the Advanced user learning pathway

Sure!

**Comment by Piyopiyo-Kitsune** [comment]
@westnz Should we close this or mark it as a lesson?

**Comment by westnz** [comment]
We can close this as we have planned a different lesson about fonts for the Advanced user learning pathway.
