### ISSUE TITLE
Tutorial: Revisions in the Site Editor

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2204]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Tutorial
- Content title: Revisions in the Site Editor
- Topic description: WordPress 6.5 is slated to include some impactful changes and new features to current revision functionality in the Site Editor. 
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner-Intermediate

# Learning Objectives

Revisions are an integral part of the creation experience, providing a safety net and a way to see where you’ve been to know where to go next.

# Related Resources and Other Notes
https://make.wordpress.org/core/2024/01/22/core-editor-improvement-robust-revisions-in-the-site-editor/

Helpful video: https://www.youtube.com/watch?v=RMEFvZdNtUc&t=2s

### Automation Code

//Tutorial

**Comment by Piyopiyo-Kitsune** [comment]
@westnz Is this going to be part of a Learning Pathway lesson?

**Comment by westnz** [comment]
We have already covered this in another lesson.
