### ISSUE TITLE
Online Workshop: WordCamp Asia 2024 Contributor Day

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2205]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Online Workshop
- Content title: WordCamp Asia Training Team Contributor Day
- Topic description: This is an hour long session providing a space for contributors to join in on the contributor day excitement from afar.
- Audience (User, Developer, Designer, Contributor, etc.): Contributors
- Experience Level (Beginner, Intermediate, Advanced, Any): Any

# Learning Objectives

Contribute to the Training Team.

# Related Resources and Other Notes
This is a session the Training Team hosts at every flagship contributor day: https://make.wordpress.org/training/handbook/training-team-how-to-guides/preparing-for-a-flagship-wordcamp-contributor-day/

### Automation Code

//online-workshop //assign

**Comment by webtechpooja** [comment]
Thank you so much, @bsanevans, for assigning me as a co-host for this online workshop. But I suspect I would be busy with some Test team-related work at WCAsia contributor day, so I would not find time to manage both. Could you please remove me from this? Thanks

**Comment by kaitohm** [comment]
Oops, sorry for the misunderstanding @webtechpooja . I've removed you from this issue, and [the Contributor Day post](https://make.wordpress.org/training/2024/02/08/wordcamp-asia-2024-contributor-day/).

I wish you and the Testing team all the best at WordCamp Asia 😃

**Comment by kaitohm** [comment]
Workshop recording: https://wordpress.tv/2024/03/07/training-team-wordcamp-asia-2024-contributor-day-online-session/
