### ISSUE TITLE
Custom taxonomies

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2208]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson
- Content title: Custom taxonomies
- Topic description: Alongside custom post types and custom post type data, introduce the concept of custom taxonomies.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Any

# Learning Objectives

- Describe why custom taxonomies might be useful
- Explain how to create a custom taxonomy, with an example.

# Related Resources and Other Notes
- https://developer.wordpress.org/plugins/taxonomies/

**Comment by jonathanbossenger** [comment]
Script: 

https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/introduction-to-wordpress-plugins/05-custom-taxonomies.md

**Comment by jonathanbossenger** [comment]
Video for review:

https://github.com/WordPress/Learn/assets/180629/7c5869d8-10db-4bff-8aac-5673a011f0ac

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by quitevisible** [comment]
@jonathanbossenger looks good! 

- Are you still planning to add a closing slide + outro? That was the only thing that seems to be missing. 

Otherwise, nice beginner breakdown of a lesser-known topic!

**Comment by jonathanbossenger** [comment]
Hi @quitevisible thanks for the review

> Are you still planning to add a closing slide + outro? That was the only thing that seems to be missing.

I don't generally add a closing slide or outro unless there is something relevant to add at the end of the lesson. If there are additional reading, or documentation links that are relevant to the lesson, I add them at the end, as a wrap up/summary, as I have done in this case. If there are some considerations to be aware of, I might add those as well, as I did for the [custom post type lesson](https://github.com/WordPress/Learn/issues/2180). But otherwise, I don't like adding an outro or closing side just for the sake of having one, if it doesn't add value to the lesson.

**Comment by Soniabajpai** [comment]
That's a nice video tutorial on how to create a custom taxonomy as sometimes the traditional default taxonomy is not enough to work with.

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/custom-taxonomies/
