### ISSUE TITLE
Working with hooks

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2209]
# Details

- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson
- Content title: Working with hooks
- Topic description: With the basic understanding of hooks, learn about additional hook concepts like hook priority, hook parameters, and hook order
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Any

# Learning Objectives

- Describe how hook priority works, and how to alter it
- Identify the different hook parameters, and what they are used for
- Find more information on the order of the different hooks

# Related Resources and Other Notes
- https://developer.wordpress.org/plugins/hooks/actions/
- https://developer.wordpress.org/apis/hooks/action-reference/
- https://learn.wordpress.org/tutorial/wordpress-action-hooks/
- https://developer.wordpress.org/plugins/hooks/filters/
- https://developer.wordpress.org/apis/hooks/filter-reference/
- https://learn.wordpress.org/tutorial/wordpress-filter-hooks/

**Comment by jonathanbossenger** [comment]
# Lesson creation checklist

- [x] Gather any relevant links to Support, Docs, or related material
- [x] Description and Objectives finalized
- [x] Lesson created and announced to the team for review
- [x] Lesson reviewed
- [x] Lesson video submitted and published to WPTV
- [x] Lesson created on Learn.WordPress.org 
- [x] Lesson video published to YouTube
- [x] Lesson on Learn.WordPress.org updated with YouTube video
- [x] Lesson published to Learn.WordPress.org

**Comment by jonathanbossenger** [comment]
Script: 

https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/wordpress-hooks/04-working-with-hooks.md

**Comment by jonathanbossenger** [comment]
Video for review

https://github.com/WordPress/Learn/assets/180629/68e9717f-ac0f-4853-8f90-00beea5b2473

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by quitevisible** [comment]
@jonathanbossenger great high level overview of hooks. 

- I liked that you covered setting priorities
- Good pace, but might help to highlight the sections of code examples you're referring to 
	-(ex. talking about adding extra content or grabbing the post_title after post_excerpt). I went back and paused the video to see what you were referring to. 
- I was expecting a closing message/slide at the end. Thought maybe the video got hung up or was buffering before I realized it ended 😁. 

Overall, a nice clear & concise presentation as usual!

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/working-with-hooks/
