### ISSUE TITLE
The block width of each lesson plan in the lesson plan list is different in the Traditional Chinese version.

### ISSUE THREAD

**Issue by huanyichuang** [WordPress/Learn#221]
<img width="1030" alt="CleanShot 2021-06-16 at 22 10 20@2x" src="https://user-images.githubusercontent.com/18607348/122234756-b68afe00-ceef-11eb-990a-7a86fea3024f.png">
As shown in the attachment, there is a style issue of the lesson plan list in the Chinese version.

I assume that it's caused by the excerpt, as that seems to be the main difference between the Chinese and the English version.

**Comment by adamwoodnz** [comment]
No longer an issue, with the launch of the 2024 block theme
