### ISSUE TITLE
Tutorial: How to find help with WordPress

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2216]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Tutorial
- Content title: How to find help with WordPress
- Topic description: Getting support
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

Finding the right place to ask for help.

# Related Resources and Other Notes

### Automation Code

//tutorial

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/a66064a9-9378-4760-b91c-bdbaa6f7e84c

**Comment by TinaCollier** [comment]
Hi @westnz 

Thank you for another great tutorial! I believe you did a wonderful job describing how someone can find help with WordPress. There are the notes I took throughout the tutorial:

### - Discusses Forums
- Clear description of how to find forums
- Walks viewer through finding forums on WordPress.org
- Not able to find a thread? Return to the forum page
- Walks viewer through how to post in the forum
###  Recommends contacting the theme or plugin developer
- Walks viewer of how to find support for theme or plugin
- Models how to find the plugin/theme directory
- Shows viewer how to find help for the Jetpack support forum on plugin WP plugin profile
- Shows how to find support link for plugin on site dashboard
### - WordPress.org resources:
- Documentation - Guides, articles, etc.
- Learn.WordPress.org

This was clear, concise and quick tutorial of how to find help with WordPress for a beginner. Thank you for sharing.

Regards,
Tina

**Comment by westnz** [comment]
Many thanks @TinaCollier ⭐

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by quitevisible** [comment]
Great tutorial as usual @westnz 

I thought the red arrows and frames highlighting some of the different selection options on a page, were a nice touch.

**Comment by westnz** [comment]
Thank you @quitevisible!

**Comment by westnz** [comment]
Jordan Gillman: I just checked this out, and it is brilliant!

**Comment by westnz** [comment]
Updated and published as part of the Beginner user learning pathway in Sensei.
