### ISSUE TITLE
Hindi translation for "Applying duotone filters to change color effects"

### ISSUE THREAD

**Issue by speedyprem** [WordPress/Learn#2217]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/applying-duotone-filters-to-change-color-effects/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @sumitsinghwp
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by speedyprem** [comment]
Here translated Content for this - https://docs.google.com/document/d/1ykX_1M7BY3fXittQqZl1IbYEJGnpaRvV1whmG6XE8hs/edit?usp=sharing

**Comment by manuthalassery** [comment]
@speedyprem Could you please add English content also like you did for other translations.

**Comment by manuthalassery** [comment]
@speedyprem I have added the English content also and modified the table. I reviewed the translation and found only one suggestion as follows. Please see and accept the changes. 
front end :  फ्रंट एंड

**Comment by speedyprem** [comment]
Thanks for making the changes @manuthalassery I have accepted the changes. 👍

**Comment by speedyprem** [comment]
@manuthalassery or @sumitsinghwp Can you please review it again if it is good to go further?

**Comment by sumitsinghwp** [comment]
@speedyprem i have review and looking fine translation yet 😀.

**Comment by devmuhib009** [comment]
Thanks @sumitsinghwp and @manuthalassery for reviewing the content. I will draft the post soon and assign it to @speedyprem. ❤️

**Comment by devmuhib009** [comment]
Content published here. https://learn.wordpress.org/tutorial/hi-applying-duotone-filters-to-change-color-effects/
