### ISSUE TITLE
Hindi translation for "Custom CSS in the Editor"

### ISSUE THREAD

**Issue by speedyprem** [WordPress/Learn#2218]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/custom-css-in-the-editor/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @sumitsinghwp 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by speedyprem** [comment]
Here translated Content for this : https://docs.google.com/document/d/1FLSrVZvp1dcZrxHeaU0GuObJf3q-2ZCV5Hn2giPDgJg/edit?usp=sharing

**Comment by sumitsinghwp** [comment]
I think the wrong doc translation link was added here @speedyprem . This translation doc related this issues - https://github.com/WordPress/Learn/issues/2217


![image](https://github.com/WordPress/Learn/assets/23701579/9ff46af2-6ee6-4c20-a449-21bef3cb9ef5)

**Comment by speedyprem** [comment]
@sumitsinghwp I have updtaed the document. here is the updated docs: https://docs.google.com/document/d/1FLSrVZvp1dcZrxHeaU0GuObJf3q-2ZCV5Hn2giPDgJg

**Comment by speedyprem** [comment]
@sumitsinghwp Can you please review this change and share your valuable feedback?

**Comment by sumitsinghwp** [comment]
![Screenshot_2024-02-20-09-21-13-521_com google android apps docs](https://github.com/WordPress/Learn/assets/23701579/ecda03e0-d945-44c9-a96a-8e5106be063a)
@speedyprem i have reviewed and  all looking fine just fix punctuation mark small things as per share screenshot please.

**Comment by speedyprem** [comment]
@sumitsinghwp Fixed the punctuation error.

**Comment by sumitsinghwp** [comment]
Great, looking fine now @speedyprem 😀

**Comment by speedyprem** [comment]
@devmuhib009 I believe this one is also ready for process further. Thanks @sumitsinghwp for the review this translation. ❤️

**Comment by devmuhib009** [comment]
Great. I'll draft the post tomorrow and update here.

**Comment by devmuhib009** [comment]
Tutorial has been published here: https://learn.wordpress.org/tutorial/hi-custom-css-in-the-editor/
