### ISSUE TITLE
Meeting Agenda February 15, 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2219]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @lada7042

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- February 15 – [https://profiles.wordpress.org/saqib59/]
- February 22 – need volunteer 
-  February 29 – [https://profiles.wordpress.org/narolainfotech/]
- March 7 – need volunteer 

**2. Looking for feedback**

- [Discussion: Translation Plugin on Learn](https://make.wordpress.org/training/2024/02/07/discussion-translation-plugin-on-learn/) — we have just kicked off a discussion on what translation plugin we could use on the Learn WordPress website to facilitate the translation work contributors have been doing in the interim to the Phase 4 Multilingual release on native WordPress. If you have some recommendations, please join the conversation!
- [Brainstorm: What trends about Learn WordPress learners do we want to observe?](https://make.wordpress.org/training/2024/02/08/brainstorm-what-trends-about-learn-wordpress-leaners-do-we-want-to-observe/)

**3. Looking for volunteers**

- Looking for [@faculty](https://wordpress.slack.com/admin/user_groups) to help run the Guide Program? -- With the new [Guide Program Management](https://make.wordpress.org/training/handbook/guide-program/guide-program-management/) handbook page in hand, and we’re looking for Faculty to take on the administration of the program. Comment in the thread if you’re interested in helping :thread:
- [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/) we are looking for two more folks to volunteer to post notes. This is a great first contribution. 

**4. Updates from last week's dev-squad triage session**

- item 1
- item 2

**5. Other news**

- [Discussion: Training’s contribution to the 6.5 release (and beyond)](https://make.wordpress.org/training/2024/01/22/discussion-trainings-contribution-to-the-6-5-release-and-beyond/) — this discussion has concluded with the following action items the team will focus on this year:
Focus on hosting release-related Online Workshops around the time of releases.
Submit release-related feedback about content as new Feedback issues in GitHub. When doing so, link to original issues where possible to keep a trail of changes that happen on a piece of content.
- Update on GatherPress- [@LauraA](https://github.com/lada7042) has joined the GatherPress Slack group to help facilitate testing during the pilot program when ready. If you would like to follow [GatherPress page](https://gatherpress.org/event/gatherpress-weekly-huddle-28/)
- During February [@westnz](https://github.com/westnz) and [@jonathan](https://github.com/jonathan) will be testing out learning pathway content creator office hours. This is an opportunity for anyone working on learning pathway content, or anyone interested in working on learning pathway content, to meet, discuss what content they are working on, ask questions, or find content to work on for the learning pathways.
There will be two office hour sessions:
Thursday 29 Feb @ 14:00 UTC hosted by [@jonathan](https://github.com/jonathan)
If you are currently working on any learning pathway lessons, or are interested in creating lessons for learning pathways, please feel free to join these sessions.
Zoom meeting URLs for these office hours will be shared in the [#training](https://wordpress.slack.com/archives/C02RW657Q) Slack channel closer to the time.
The office hours yesterday with @westnz was were very productive. It is a great way to share ideas and to clarify projects. 

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.

❓  If you don’t know where to start or have questions about any of the above, feel free to ask in this thread or send a DM 😃  🧵 

## 3. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
Design is still updating the design using the new .org design framework. [You can review the latest iteration here](https://href.li/?https://www.figma.com/file/ZKaf6u8mIHkAanluWafXAp/Learn?type=design&node-id=2211-18443&mode=design).
  

## 4. Contribution Acknowledgement
Badges awarded: [Kawsar Alam Even](https://profiles.wordpress.org/kawsaralameven/)
Props -- do you have someone you'd like to nominate to give props for their work on the team?
- Ben gives props to [Cynthia Norman](https://profiles.wordpress.org/cnormandigital/) for putting two learning pathway lessons out for review.

## 5. Faculty Updates
- The [Faculty Survey Results – Q1 2024](https://make.wordpress.org/training/2024/02/02/faculty-survey-results-q1-2024/) were released and a lot of these updates are largely in response to the feedback shared. Thank you to [@faculty](https://wordpress.slack.com/admin/user_groups) for sharing your candid feedback on how we can improve this program.
- [@Ben Evans](https://wordpress.slack.com/team/U0381D1Q1RU)
 will be hosting two onboarding workshops on [February 15th](https://www.meetup.com/learn-wordpress-online-workshops/events/298706726) and [February 16th](https://www.meetup.com/learn-wordpress-online-workshops/events/298706927) titled Starting your contributor journey with the WordPress Training Team
- Faculty Program Online Workshop — [@Destiny] will be hosting two Make WordPress Training Team Faculty Program Information Sessions at the end of this month on February 21st at 00:00 UTC and 08:00 UTC
[RSVP for Session 1](https://www.meetup.com/learn-wordpress-online-workshops/events/299049829/)
[RSVP for Session 2](https://www.meetup.com/learn-wordpress-online-workshops/events/299049832/)

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by ghost** [comment]
Link for start of the meeting- https://wordpress.slack.com/archives/C02RW657Q/p1707955234110599

**Comment by devmuhib009** [comment]
Meeting is published here: https://make.wordpress.org/training/2024/02/20/training-team-meeting-recap-15th-february-2024/
