### ISSUE TITLE
Hindi translation for "Scheduling posts and pages"

### ISSUE THREAD

**Issue by speedyprem** [WordPress/Learn#2220]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/scheduling-posts-and-pages/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by speedyprem** [comment]
Here translated Content for this - https://docs.google.com/document/d/1wKRnrNwC2ahsHkAMtRMKmfD-ncktDnW_X7e8D-C6DIQ/edit?usp=sharing

**Comment by devmuhib009** [comment]
@Roshan-narola can you review this translation please?

**Comment by Roshan-narola** [comment]
Yes @devmuhib009 I'll let you know once it's done.

**Comment by Roshan-narola** [comment]
@speedyprem  can you please add English content also. 
Here is the example which you need to follow. https://docs.google.com/document/d/1RzDDK7wwlDwVnbU1UpTTJOyEPYvcPQYp9BguqjcREYE/edit?usp=sharing
you also do likewise. Let me know once your changes will be done.

**Comment by speedyprem** [comment]
Thanks for the quick review @Roshan-narola 
I have made the changes as per your suggestion. https://docs.google.com/document/d/1wKRnrNwC2ahsHkAMtRMKmfD-ncktDnW_X7e8D-C6DIQ/edit

**Comment by Roshan-narola** [comment]
@devmuhib009 I review the translation and it's look good to go for further process.

**Comment by speedyprem** [comment]
> @devmuhib009 I review the translation and it's look good to go for further process.

Thanks for the review @Roshan-narola 😄

**Comment by devmuhib009** [comment]
Thanks @Roshan-narola for reviewing the translation. @speedyprem please comment your WordPress.org username, so I can add you as contributor on Learn WordPress website.

**Comment by speedyprem** [comment]
@devmuhib009 This is my wordpress.org username: https://profiles.wordpress.org/freewebmentor/

**Comment by devmuhib009** [comment]
Hi
I've added you to learn.wordpress.org please accept the invitation. Then I will draft the post and provide rest of the instructions.

**Comment by speedyprem** [comment]
I have accepted the invitation.

**Comment by manuthalassery** [comment]
@devmuhib009 Please assign me as a reviewer for this translation. My wordpress.org username is https://profiles.wordpress.org/manukk/

**Comment by devmuhib009** [comment]
Hi @manuthalassery 
Thanks commenting. This one already reviewed by @Roshan-narola 
I see no problem reviewing a content twice. You can also check the translation and if you can suggest something better, its always accepted.

**Comment by devmuhib009** [comment]
Hi,

I just drafted the post here: https://learn.wordpress.org/wp-admin/post.php?post=83427&action=edit
Please complete step 5 to 7 and give update here.
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials
Thanks

**Comment by devmuhib009** [comment]
Thanks @speedyprem for your patience and hard work. Your translation has been published. https://learn.wordpress.org/tutorial/hi-scheduling-posts-and-pages/
