### ISSUE TITLE
LESSON: Migrating your website, Part 2: Changing your host while keeping your domain name

### ISSUE THREAD

**Issue by SierraTR** [WordPress/Learn#2228]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Migrating your website, Part 2: Changing your host while keeping your domain name
- Topic description: Instructions on how to move your WordPress website to a new hosting account while keeping the existing domain name.
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

1. Describe the steps necessary for moving your website to a new hosting company when you want to use your existing domain name.
2. Describe how the Internet knows where to look for your website.
3. Describe the steps necessary to update the location of your website at your new hosting company.

# Related Resources and Other Notes
Migrating your site: https://learn.wordpress.org/tutorial/migrating-your-wordpress-website-to-a-different-host-and-domain/ 
Migrate, copy or clone a site: https://learn.wordpress.org/lesson-plan/migrate-copy-or-clone-a-site/ 

# Lesson creation checklist

- [ x] Gather any relevant links to Support, Docs, or related material
- [ x] Description and Objectives finalized
- [ ] Lesson created and announced to the team for review
- [ ] Lesson reviewed
- [ ] Lesson video submitted and published to WPTV
- [ ] Lesson created on Learn.WordPress.org 
- [ ] Lesson video published to YouTube
- [ ] Lesson on Learn.WordPress.org updated with YouTube video
- [ ] Lesson published to Learn.WordPress.org

### Automation Code

//lesson

**Comment by SierraTR** [comment]
https://github.com/WordPress/Learn/assets/3642121/0cddab65-056a-43e2-af4e-f16451f95a1b

**Comment by westnz** [comment]
//review

**Comment by westnz** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations is easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.

Congratulations, @SierraTR. This is an excellent video tutorial with a well-written script. You explain things very clearly and methodically. 

A few suggestions:
- It will be helpful to use red arrows or boxes to help guide the reader's eye and highlight what is being spoken about. For example, 3:38 to 4:33.
- 1:58 - 2:41 Use 5 different slides to help the reader stay on track and follow what is being said. The slide has too much text/info, and I lost track of what was being said as I tried to read and listen.
- 5:16 - 5:40 Any chance you can add a screen recording of you actually doing it / dummy example?
- 5:41 - 6:17  Could you add one or two extra slides for variation?

Once again, well done!!

**Comment by SierraTR** [comment]
Thanks Wes, those are good suggestions. I'll begin working on them.

**Comment by SierraTR** [comment]
https://github.com/WordPress/Learn/assets/3642121/5215cc1f-7537-4c1f-9323-a554610b0916

**Comment by westnz** [comment]
Hey @SierraTR 
- 2:18 - 2:45 This part was a bit confusing to me. It is important for a learner to only see the words you are saying or an image /graphic, as it is tough to focus if you hear one thing and read something different. 
- 4:13 - 4:41 Same as the comment above 😉 
- 5:41 - 6:17 Still think adding one or two extra slides for variation would help
Will DM you with an idea.

**Comment by SierraTR** [comment]
https://github.com/WordPress/Learn/assets/3642121/32321ade-f4b5-42a2-a756-abbea5cdb6b6

**Comment by westnz** [comment]
Almost there 
Check: 2:04 - 2:11, that slide must not be there - was correct on previous version. 😃 

Thank you for all the work that has gone into this, @SierraTR

**Comment by SierraTR** [comment]
This looks a bit better.





https://github.com/WordPress/Learn/assets/3642121/d1de9fe6-40bc-4e38-83b1-9e0c1db4bca8

**Comment by westnz** [comment]
Great, please continue with publishing.

**Comment by westnz** [comment]
//published
