### ISSUE TITLE
Feedback - Accessibility: Ambiguous links on Learn home page

### ISSUE THREAD

**Issue by amberhinds** [WordPress/Learn#2233]
## Type of feedback
//content

## Description
There are two instances of the same link on the home page that don't have meaningful anchor text, just using the word "here."

`<a href="https://make.wordpress.org/community/community-deputies/" target="_blank" rel="noopener">here</a>`

A screen reader user would not have any context for these links or know where they go.

## Step-by-step reproduction instructions (optional)
View the Learn Home page and look for the "here" links in the recent courses section:

## Screenshots or screen recording (optional)
<img width="1096" alt="Screenshot ambiguous links and surrounding content" src="https://github.com/WordPress/Learn/assets/13153456/f22f7e67-742d-41ea-9ffa-27b99631930b">

## Other information (optional)
I would correct this by changing the sentence from "You can find out more about the deputy program [here](https://make.wordpress.org/community/community-deputies/)." to "[Find out more about the deputy program.](https://make.wordpress.org/community/community-deputies/)"

**Comment by jonathanbossenger** [comment]
@amberhinds thanks for logging this, I have fixed the two links on the landing page.

I have also raised this to be discussed in the next training team meeting tomorrow so that we do a review of all courses to ensure no more ambiguous links exist.

**Comment by amberhinds** [comment]
Thank you! 🎉
