### ISSUE TITLE
Block development environment

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2236]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Block development environment
- Topic description: Describe the software and tools needed in order to develop WordPress blocks
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Describe the software needed for block development
- Explain how to install and set up the required software

# Related Resources and Other Notes
- https://developer.wordpress.org/block-editor/getting-started/devenv/
- https://developer.wordpress.org/block-editor/getting-started/tutorial/
- https://learn.wordpress.org/tutorial/using-the-create-block-tool/

**Comment by jonathanbossenger** [comment]
//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/introduction-to-wordpress-blocks/01-getting-set-up-for-block-development.md

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/assets/180629/a2e9a98e-9fb2-4c0b-94ca-15ca0cc8e7e3

Video for review

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great intro, @jonathanbossenger! I like the thorough instructions for Windows users, and the helpful tips for people who are just starting their journey as developers. In this context, it might be worth mentioning the [Local Development Environment lesson](https://github.com/WordPress/Learn/issues/2147) from Module 2, for reference.

I noticed one "wierdness" at 4:41: you switch back from Windows to Mac without mentioning it, and then pick up on the instructions of how to install `node.js` (mentioned first at 3:48).

**Comment by jonathanbossenger** [comment]
Thanks for the review @ironnysh 

> I noticed one "wierdness" at 4:41: you switch back from Windows to Mac without mentioning it, and then pick up on the instructions of how to install node.js (mentioned first at 3:48).

It looks like there is a transition missing there, I will add it and re-export before publishing.

**Comment by jonathanbossenger** [comment]
Updated video

https://github.com/WordPress/Learn/assets/180629/131b3b65-5c53-4ec7-913e-e7e03644bd74

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/03/28/block-development-environment/

**Comment by jonathanbossenger** [comment]
https://youtu.be/29eZK-YzkP8

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/getting-set-up-2/
