### ISSUE TITLE
Scaffolding a new block

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2237]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Scaffolding a new block
- Topic description: In this lesson you will scaffold a new block using the create-block tool.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Describe what the create-block tool is, and how to use it
- Explain how to use create block to scaffold a new block
- Recognize the different parts of code that create-block scaffolds

# Related Resources and Other Notes
- https://developer.wordpress.org/block-editor/getting-started/devenv/get-started-with-create-block/
- https://developer.wordpress.org/block-editor/getting-started/tutorial/
- https://learn.wordpress.org/tutorial/using-the-create-block-tool/

**Comment by jonathanbossenger** [comment]
//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/introduction-to-wordpress-blocks/02-scaffolding-a-new-block.md

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/assets/180629/79c5daa9-d7d7-48cf-a64f-cb679717a0c7

Video for review

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [ ] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great overview of what's to come!
Only noticed a small repetition at ~8:15.

**Comment by jonathanbossenger** [comment]
> Only noticed a small repetition at ~8:15.

Noted, thanks.

**Comment by jonathanbossenger** [comment]
Updated video 

Uploading 02 Scaffolding a new block.mp4…

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/03/28/scaffolding-a-new-block/

**Comment by jonathanbossenger** [comment]
https://youtu.be/hTstd6CCbVs

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/scaffolding-a-new-block/
