### ISSUE TITLE
Building your first block

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2238]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Your first block
- Topic description: Building on the scaffolded code from the previous lesson, start customizing the block to meet the requirements
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Define the block requirements
- Describe the changes that can be made to start customizing the scaffolded block

# Related Resources and Other Notes
- https://developer.wordpress.org/block-editor/getting-started/tutorial/

**Comment by jonathanbossenger** [comment]
//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/introduction-to-wordpress-blocks/03-building-your-first-block.md

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/assets/180629/2b14abc6-97e9-4012-a9d0-d5acebe0d88e

Video for review

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great video, @jonathanbossenger!
Only noticed one issue: there's a little audio glitch at 1:55.

**Comment by jonathanbossenger** [comment]
> there's a little audio glitch at 1:55.

Thanks, that audio was clipped in the original recording, I'll see if I can record that line.

**Comment by jonathanbossenger** [comment]
Updated video with audio glitch fix


https://github.com/WordPress/Learn/assets/180629/8b02b7c4-c27f-4fd0-bde2-6eeab8590ac8

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/03/28/building-your-first-block/

**Comment by jonathanbossenger** [comment]
https://youtu.be/lxyeE_jZbts

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/building-your-first-block/
