### ISSUE TITLE
Block Supports and Styles

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2239]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Block Supports
- Topic description: Learn how to use Block Supports to add common functionality to a block
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Describe what block supports are, and how they are useful
- Explain the different between block supports and block styles
- Modify the block to include the alignment support, as well as some static styles

# Related Resources and Other Notes
- https://developer.wordpress.org/block-editor/getting-started/tutorial/

**Comment by jonathanbossenger** [comment]
//lessons

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/introduction-to-wordpress-blocks/06-block-supports-and-styles.md

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/assets/180629/711de6e4-4970-4a76-b9d1-22e28fbc089c

Video for review

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Another great tutorial, @jonathanbossenger!

**Comment by jonathanbossenger** [comment]
Thank you @ironnysh

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/03/28/block-supports-and-block-styles/

**Comment by jonathanbossenger** [comment]
https://youtu.be/pX85yXtp7nY

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/block-supports-and-styles/
