### ISSUE TITLE
Taxonomies for content tracking

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#224]
As per [this proposal](https://make.wordpress.org/training/2021/05/28/proposal-an-audit-tool-for-learn/) for a content audit tool on Learn, we need to implement two new taxonomies that will be made available to the following four post types: `lesson-plan`, `wporg_workshop`, `course` and `lesson`.

The taxonomies are:
* A taxonomy for indicating which WordPress version the content applies to or has been tested up to.
* A taxonomy for which UI elements or dashboard screens the content applies to.

I'm happy for them to be named whatever you feel is appropriate - something like `wp_version` and `interface` would work, but I'm not sure what naming conventions or standards you have for these things. The taxonomies will only need to be registered once and then applied to all of the post types listed above for them all to make use of.

Let me know if you need any further explanation or information.

**Comment by hlashbrooke** [comment]
List tables must include filters for both taxonomies.

**Comment by hlashbrooke** [comment]
As a small update here, please name the two taxonomies as follows:
* WP version / `wp_version`
* Included content / `included_content`

We need to keep the second one as generic as possible in order to cover a wide range of use cases without requiring multiple taxonomies or having to rename it in the future. They must still be applied to all the post types listed above.

**Comment by coreymckrill** [comment]
@hlashbrooke For the taxonomy labels I think those will be fine, but for the slugs, I think it would be best to namespace them. So they would be:

* `wporg_wp_version`
* `wporg_included_content`

**Comment by hlashbrooke** [comment]
Works for me.
