### ISSUE TITLE
Block Attributes

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2240]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Block attributes
- Topic description: Provide block users the ability to change block data using Block Attributes
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Describe what block attributes are, and how they are useful
- Modify the block to support a block attribute

# Related Resources and Other Notes
- https://developer.wordpress.org/block-editor/getting-started/tutorial/

**Comment by jonathanbossenger** [comment]
//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/introduction-to-wordpress-blocks/05-block-attributes.md

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/assets/180629/c21751eb-a449-4aa8-9668-b78a44cb84cd

Video for review

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [ ] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great tutorial! Clear and easy to follow. I appreciated the suggestion to switch to Code editor view, to see the attribute set there as well. It sort of ties the IDE and the Editor together :-)

I noticed a "bug" at 8:00: when you present [two ways to fix the React erros](https://github.com/jonathanbossenger/wp-content/blob/deecad1fb9d07a18f5616eb27e603e21f3b906f0/developer-learning-pathway/07-introduction-to-wordpress-blocks/05-block-attributes.md?plain=1#L157), the same React documentation page is shown (Fragment); seems like the `div` option is skipped.

**Comment by jonathanbossenger** [comment]
Thanks @ironnysh, another editing glitch, which is now fixed. 

https://github.com/WordPress/Learn/assets/180629/ed480c57-66fa-487f-86be-8f0fa8d4a421

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/03/28/block-attributes/

**Comment by jonathanbossenger** [comment]
https://youtu.be/dCGS8UUmP40

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/block-attributes-2/
