### ISSUE TITLE
Japanese Online Workshop: the solution how to distinguish Page and Post from your HTML&CSS Web site

### ISSUE THREAD

**Issue by hotacafukui** [WordPress/Learn#2244]
# Details

- Topic description:It is very difficult to learn the definition between Page and Post. I will explain the difference between Page and Post for Beginner learners(Japanese)
- Audience (User, Developer, Designer, Contributor, etc.): Japanese Users
- Learning objectives (What will the learner be able to do as a result of this content?): You can learn the definition between Page and Post
- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Online Workshop
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): Yes

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by kaitohm** [comment]
This topic is ready to be created. Please follow the handbook page [Online Workshops](https://make.wordpress.org/training/handbook/online-workshops/) for next steps.

**Comment by hotacafukui** [comment]
## Online Workshop Details
- Date:
- Meetup.com event link:
- Co-host: 

## Online Workshop Development Checklist
- [ ] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [ ] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [ ] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by hotacafukui** [comment]
HTML&CSSでWebサイトを作ったものをWordpressに変えたい！そんなことをよく周りから聞きます。でもページ階層が複雑で自分が作ったどのページが管理画面のどの場所とリンクしているの？どのphpページで作ればいいの？そういった構造部分をお話ししていこうと思います。初心者の方大歓迎です。ちょっとでも興味のある方はぜひお越しください！

**Comment by megane9988** [comment]
@hotacafukui 

すごくいいとおもいます！！
Looks great! thank so much. Such a Nice WorkShop!

つづいて、ワークショップのアジェンダを共有いただけますか？
So can you share your workshop agenda?

**Comment by hotacafukui** [comment]
・プロローグ（HTML＆CSSのページをWordPress化するって？）
　・すぐに作業をはじめる前に、まずページ構成を考えることが大切
　
・固定ページとは？
　1.　どんなページがWordPressの固定ページ？
　2.　管理ページから見た固定ページ
　3.　固定ページはどんなPHPファイル？

・投稿ページとは？
　1.　どんなページがWordPressの固定ページ？
　2.　管理ページから見た投稿ページ
　3.　投稿ページはどんなPHPファイル？

・実際のサイトを見ながら、一緒に考察

**Comment by megane9988** [comment]
@hotacafukui 大変良いと思います！
可能であればテーマのPHPテンプレートを紹介する際に
フルサイト編集に対応したブロックテーマでは、テンプレート page.htmlやsingle.htmlなどの説明を加えていただくか、今回はクラシックテーマ（PHPベースのテーマ）の説明に限定します。と加えていただくといいかもです

**Comment by hotacafukui** [comment]
すみません。一旦クローズし、時間に余裕が出たときに改めてイシューを立てます。
