### ISSUE TITLE
Japanese Online Workshop - WordPressの保守・メンテナンスをやってみよう！ / Let's try WordPress backup and maintenance!

### ISSUE THREAD

**Issue by megane9988** [WordPress/Learn#2246]
# Details

- Topic description: 
    - How to backup
    - How to restore
    - How to Update core, theme and Plugins
    - How to Create demo site
- Audience (User, Developer, Designer, Contributor, etc.): 
    - User
- Learning objectives (What will the learner be able to do as a result of this content?): 
    - Learner will be able to backup WordPress
    - Learner will be able to restore WordPress
    - Learner will be able to understand how to maintain WordPress
- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): 
    - Online Workshop
- WordPress version (optional): 
    - 6.5
- Will you be creating this content? (Yes or No): 
    - yes
# Related Resources

- Plugins
    - [All-in-One WP Migration](https://wordpress.org/plugins/all-in-one-wp-migration/)
    - [BackWPup](https://wordpress.org/plugins/backwpup/)
    - [UpdraftPlus](https://ja.wordpress.org/plugins/updraftplus/)

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by megane9988** [comment]
https://www.meetup.com/ja-JP/learn-wordpress-online-workshops/events/299375140/


# 詳細
WordPressのバックアップおよびアップデートなど、保守運用の方法
WordPressはとても便利で、使いやすいツールです。安全に使い続けるためにはバックアップや、アップデートなどの保守運用が必須です。
この部分について、汎用的な方法を、実際のデモを交えながら、紹介します。
この機会に、一緒にやってみましょう！


# こんな方にオススメ

WordPressの運用に不安のある方
WordPressのアップデートが滞っている方
WordPressのバックアップができているかどうか、不安な方

# 講座内容

バックアップの取得、定期的な設定方法
バックアップを元にした復元方法
バックアップを元にしたローカル環境の構築
アップデート時のチェックリストの作成方法
質疑応答

# イベント概要
対象：WordPress ユーザー
日時：2024年3月19日（火）　日本時間　午後 21 時
参加方法：参加登録後、Zoom リンクが表示されます
Note: This workshop will be hosted in Japanese, in a Japan-friendly time.

**Comment by kaitohm** [comment]
This topic is ready to be created. Please follow the handbook page [Online Workshops](https://make.wordpress.org/training/handbook/online-workshops/) for next steps.

**Comment by megane9988** [comment]
## Online Workshop Details
- Date: 2024年3月19日（火）　日本時間　午後 21 時
- Meetup.com event link: https://www.meetup.com/ja-JP/learn-wordpress-online-workshops/events/299375140/
- Co-host:  なし


## Online Workshop Development Checklist
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by megane9988** [comment]
slides
https://paper.dropbox.com/doc/WordPress--CLmahRh5UVkmLFboVizIcsOrAg-CuYDvDIe0CScVdYYMwXP6
 
WordPress.tv
https://wordpress.tv/2024/03/21/hajime-ogushi-lets-try-wordpress-backup-and-maintenance/
