### ISSUE TITLE
Manual expiration date field

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#225]
As outlined in the [audit tool proposal](https://make.wordpress.org/training/2021/05/28/proposal-an-audit-tool-for-learn/), we would like to have an additional custom date field for each content type (workshops, lesson plans, lessons and courses) that allows us to specify an 'expiration date' for the content. This wouldn't actually cause the content to expire or be removed, but it would be for internal management of content that needs to be re-checked on a certain date.

**Comment by hlashbrooke** [comment]
The expiration date must be displayed as a column in the post list table.

**Comment by coreymckrill** [comment]
Maybe instead of a column, we could put the expiration info in a post state... ?
