### ISSUE TITLE
Hindi translation for "7 Tips to improve website security"

### ISSUE THREAD

**Issue by speedyprem** [WordPress/Learn#2251]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/7-tips-to-improve-website-security/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by speedyprem** [comment]
Here translated Content for this - https://docs.google.com/document/d/1-MVcL8Te6PXbFr3lmjR0es9muyROb15TO4KjT4uG45w

**Comment by speedyprem** [comment]
@sumitsinghwp Can you please help here in reviewing this translation?

**Comment by sumitsinghwp** [comment]
just one manner issue then ready translation @speedyprem 
![image](https://github.com/WordPress/Learn/assets/23701579/9c9b6d4a-c176-4481-aa51-b8b8733d3907)

**Comment by speedyprem** [comment]
Thanks for the review @sumitsinghwp Just fixed the issue.

**Comment by sumitsinghwp** [comment]
Looking fine now @speedyprem :)

**Comment by devmuhib009** [comment]
Thanks @sumitsinghwp for reviewing the content. @speedyprem as you translated few contents already, please draft the post upload subtitle. If you need any help, I am always here.

**Comment by speedyprem** [comment]
@devmuhib009 I have drafted the tutorial here: I have drafted the article here: https://learn.wordpress.org/wp-admin/post.php?post=83658&action=edit

**Comment by speedyprem** [comment]
@devmuhib009 I have also submitted the subtitle in [wordpress.tv](http://wordpress.tv/) for https://github.com/WordPress/Learn/issues/2251

**Comment by devmuhib009** [comment]
Thanks for the update. Tutorial is published now: https://learn.wordpress.org/tutorial/hi-7-tips-to-improve-website-security/
