### ISSUE TITLE
Tutorial: ​​Differentiating between homepage display settings and various templates

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2255]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Tutorial
- Content title: ​​Differentiating between available templates
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

Knowing the difference between all the templates that come with your theme and which you can add. 

# Related Resources and Other Notes

### Automation Code

//tutorial

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/55eb11b2-32d5-4f72-96a2-0bcb8461ebaf

**Comment by kathrynwp** [comment]
@westnz - this is is an excellent tutorial clarifying common points of confusion among users.

I only noticed a couple of minor things:

- 0:28 - for the slide template that consists of black text on a white background, the line height (leading) looks too loose to my eye, making the text a bit hard to read. Consider tightening up the line height.

- On the same slides, perhaps the wording also be shortened/tightened up a bit, so it's just a summary of what you're saying?

- 0:37 - I think “Page template” should be “Pages template” (plural)

That's it from me. I think this lesson will be very useful for many people!

**Comment by westnz** [comment]
Thank you very much @kathrynwp

**Comment by westnz** [comment]
Updated and published as part of the Intermediate user learning pathway in Sensei.
