### ISSUE TITLE
Hindi translation for "Adding & Removing Images"

### ISSUE THREAD

**Issue by speedyprem** [WordPress/Learn#2260]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/adding-removing-images/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @sumitsinghwp
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by speedyprem** [comment]
Here translated Content for this - https://docs.google.com/document/d/1x0NcYktCegf_8NVZjcyoDMXSNlPtnnMIE5wHrtc1VYQ/

**Comment by speedyprem** [comment]
@sumitsinghwp Can you please review this tutorial as well, Thanks for helping me in reviewing. ❤️

**Comment by asharma198** [comment]
I review the translation and it's look good to go for further process.

**Comment by speedyprem** [comment]
@devmuhib009 I have drafted the tutorial here: https://learn.wordpress.org/wp-admin/post.php?post=87597&action=edit
Can you please take care to publish from here?

**Comment by devmuhib009** [comment]
Tutorial Published Here: https://learn.wordpress.org/tutorial/hi-adding-removing-images/
