### ISSUE TITLE
Meeting Agenda February 29, 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2262]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @lada7042 ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- February 29 – [narolainfotech](https://profiles.wordpress.org/narolainfotech)
- March 7 – [freewebmentor](https://profiles.wordpress.org/freewebmentor/)
- March 14 – [freewebmentor](https://profiles.wordpress.org/freewebmentor/)
- March 21 –  [@voboghure](https://profiles.wordpress.org/voboghure/)

**2. Looking for feedback**

- Last Call!!! [Brainstorm: What trends about Learn WordPress leaners do we want to observe?](https://make.wordpress.org/training/2024/02/08/brainstorm-what-trends-about-learn-wordpress-leaners-do-we-want-to-observe/) ] (https://make.wordpress.org/training/2024/02/08/brainstorm-what-trends-about-learn-wordpress-leaners-do-we-want-to-observe/)
- [Discussion: Bringing accessibility-first approaches into content development](https://make.wordpress.org/training/2024/02/20/discussion-bringing-accessibility-first-approaches-into-content-development/) Open till March 9

**3. Looking for volunteers**

- [Subject-Matter Experts](https://make.wordpress.org/training/handbook/getting-started/subject-matter-expert-onboarding/)
- [Editors/Reviewers](https://make.wordpress.org/training/handbook/getting-started/editor-onboarding/)

**4. Updates from last week's dev-squad triage session**

Attendees: Jonathan (@psykro) and Muhibul Haque (@devmuhib009 )

There were no new PRs or bugs to triage again this week, so we moved into triaging [Content Feedback issues](https://github.com/orgs/WordPress/projects/78/views/1).

- #1627 
- #1619 

We would also like to put out a call for any training team members with developer experience to help us test #2231 

**5. Other news**

- [WordCamp Asia 2024 Contributor Day](https://make.wordpress.org/training/2024/02/08/wordcamp-asia-2024-contributor-day/) is coming March 6, 2024 [@Chetan Prajapati](https://wordpress.slack.com/team/U2TPPR7U4)
- Who will be joining? In-person or virtually? 
- [Virtual Contributor Day Signup](https://www.meetup.com/learn-wordpress-online-workshops/events/299072655/)
- The next Content Creator Coffe Hour is this Thursday 29 Feb @ 14:00 UTC hosted by @Jonathan. Here is the [Zoom meeting URL](https://us02web.zoom.us/j/89156632542?pwd=d0ZPT3dXMlN6UFN4ajQzeDJvcjhkUT09) 

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
    - There are currently 16 issues requiring review cc/ [@faculty-editors](https://wordpress.slack.com/admin/user_groups)
    - 4 issues are almost done. They need a third review. 
    - Doing a review is a great first contribution. 

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
   - There are currently 25 issues awaiting validation cc/ [@faculty-editors](https://wordpress.slack.com/admin/user_groups) [@faculty-smes](https://wordpress.slack.com/admin/user_groups)

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
   -  There are currently 31 issues awaiting vetting cc/ [@faculty-smes](https://wordpress.slack.com/admin/user_groups)

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code. 
   - There are currently 15 issues requiring developer assistance

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
   - We currently have 15 issues requiring editor assistance

## 3. Contribution Acknowledgement

- Badges awarded: [Prem Tiwari](https://profiles.wordpress.org/freewebmentor/)
- Props: 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress] (https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - Thumbnail templates are currently being created
  

## 5. Faculty Updates ( not this week) 

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you would like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
Added the dev-squad triage notes, and the next Content Creator Coffe Hour link.

**Comment by voboghure-dev** [comment]
I would like to work as a note taker for March 21.

**Comment by ghost** [comment]
Meeting Recap- https://make.wordpress.org/training/2024/03/05/training-team-meeting-recap-29th-february-2024/
