### ISSUE TITLE
Interacting with the WordPress REST API

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2267]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Interacting with the WordPress REST API
- Topic description: This lesson will cover the WP REST API schema, methods to authenticate a WP REST API request, tools to test WP REST API endpoints, as well as a couple of ways to add, edit, or delete data via the WP REST API.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Identify the typical schema for a WP REST API endpoint
- Implement the use of an Application Password to authenticate a WP REST API Request
- Identify and use a tool to test REST API endpoints
- Execute adding, updating or deleting of data via the relevant WP REST API routes
- 
# Related Resources and Other Notes
- https://developer.wordpress.org/rest-api/using-the-rest-api/

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/08-wordpress-rest-api/03-interacting-with-the-wp-rest-api.md

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/assets/180629/4a8cfdd4-5230-445c-b483-278c6a6f9dbb

Video ready for review

Please follow the [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review this lesson.

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Another great tutorial, @jonathanbossenger!

I'm curious, why not use an open-source alternative to Postman, something like [Hoppscotch](https://hoppscotch.io/)?

**Comment by jonathanbossenger** [comment]
Thank you @ironnysh 

> I'm curious, why not use an open-source alternative to Postman, something like [Hoppscotch](https://hoppscotch.io/)?

Ironically, the [original tutorial](https://learn.wordpress.org/tutorial/wp-rest-api-custom-fields-authentication-and-testing/) did reference Hoppscotch, but at the time of recording this video, the site was giving me 404 errors, so I had to cut it. 

FWIW Postman is also [open source](https://github.com/postmanlabs) and is 100% free to download and use.

**Comment by ironnysh** [comment]
> the site was giving me 404 errors

Timing is everything 🤣

> Postman is also [open source](https://github.com/postmanlabs)

Oh, TIL :-)

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/04/07/interacting-with-the-wordpress-rest-api/

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/interacting-with-the-wordpress-rest-api/

**Comment by jonathanbossenger** [comment]
//publish
