### ISSUE TITLE
Extending the WordPress REST API

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2268]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Extending the WP REST API
- Topic description: This lesson will introduce two methods of adding fields to REST API requests, either by enabling custom fields in the REST API route, or by making custom fields available as top level fields, as well as the pros and cons of both approaches.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginnner

# Learning Objectives

- Register post meta for a custom post type that supports the WP REST API
- Add or update a custom post type via the WP REST API including this custom post meta
- Modify the custom post meta by moving it to a top-level field on the WP REST API endpoint

# Related Resources and Other Notes
- https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/08-wordpress-rest-api/04-extending-the-wp-rest-api.md

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/assets/180629/907d9a75-4042-4c8c-a361-16653d3411d8

Video ready for review

Please follow the [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) to review this lesson.

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Lots of good stuff here :-) 

- It might be worth mentioning that `show_in_rest` is required if you want to view the custom field in the editor.
- At 7:31, when you switch to the editor, the custom fields are already displayed below the main window, but this isn't the default behavior. It would be nice to show how to enable it.
- At 7:37, there's a little repetition: "It's also..."

**Comment by jonathanbossenger** [comment]
@ironnysh thanks for the review

```
the custom fields are already displayed below the main window, but this isn't the default behavior. It would be nice to show how to enable it.
```

This is covered in the Introduction to plugins [lesson on custom fields](https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/06-introduction-to-wordpress-plugins/05-custom-post-type-data.md#the-custom-fields-panel)

```
At 7:37, there's a little repetition: "It's also..."
```

Good catch, thanks.

**Comment by jonathanbossenger** [comment]
Updated video 

https://github.com/WordPress/Learn/assets/180629/715418c0-3aa5-4d5b-8ca5-3562b04e7e3e

**Comment by ironnysh** [comment]
> This is covered in the Introduction to plugins [lesson on custom fields](https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/06-introduction-to-wordpress-plugins/05-custom-post-type-data.md#the-custom-fields-panel)

@jonathanbossenger, but what if people _don't_ follow the linear path? :-)

BTW, there's been a change in 6.5, so [this line](https://github.com/jonathanbossenger/wp-content/blob/e1aebbf4b4362cb24ec9f8a35da3675303e3e403/developer-learning-pathway/06-introduction-to-wordpress-plugins/05-custom-post-type-data.md?plain=1#L45) should be updated:

<img width="791" alt="image" src="https://github.com/WordPress/Learn/assets/63248335/16508dd8-37b9-434e-a04a-15664c214833">

**Comment by jonathanbossenger** [comment]
```
BTW, there's been a change in 6.5, so [this line](https://github.com/jonathanbossenger/wp-content/blob/e1aebbf4b4362cb24ec9f8a35da3675303e3e403/developer-learning-pathway/06-introduction-to-wordpress-plugins/05-custom-post-type-data.md?plain=1#L45) should be updated:
```

Yeah, I saw that. I'll probably circle back and update that lesson once the full learning pathway is completed.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/04/07/extending-the-wordpress-rest-api/

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/extending-the-wordpress-rest-api/

**Comment by jonathanbossenger** [comment]
//publish
