### ISSUE TITLE
Content owner field for all post types

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#227]
We need a new field for all post types (lesson plans, workshops, lessons and courses) that allows us to indicate who the "content owner" is - this will be the person primarily responsible for that content and/or who has the most expertise in the area.

The most practical way to do this would be to have the field allow us to specify a WordPress.org user - whether that's a plain text field or an autocomplete is fine.

**Comment by hlashbrooke** [comment]
The data for the content owner field must be displayed as a column in the post list table.

**Comment by coreymckrill** [comment]
Maybe put the content owner in the post title field with the wporg username linked to their profiles.wordpress.org page.

**Comment by hlashbrooke** [comment]
Allow for multiple usernames.

**Comment by adamwoodnz** [comment]
@kaitohm is this still desirable? Otherwise let's close.

**Comment by kaitohm** [comment]
Not needed.
