### ISSUE TITLE
Templates overview

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2271]
# Details

- Content type: Lesson
- Content title: Templates overview
- Topic description: We will cover the purpose, structure and loading of templates.
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- Describe the purpose and structure of a template
- List the sequence templates are loaded by WordPress
- With theme starter files in place, create a template from scratch

# Related Resources and Other Notes

- [Templates](https://developer.wordpress.org/themes/templates/templates/)
- https://learn.wordpress.org/tutorial/wordpress-theme-template-tour/
- https://wordpress.tv/2024/04/01/untangling-templates/

**Comment by cynthianorman** [comment]
This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

https://youtu.be/laDWG1QkHVQ (unlisted)

**Comment by jagirbahesh** [comment]
Hello @cynthianorman,

Thank you for the lesson.

I have checked and here I have shared the feedback which we can improve.

In page.php section comment's are not properly added. you can find the space in the each line of comment which is not according to WordPress PHPCS standard.
![image](https://github.com/WordPress/Learn/assets/22549318/277c6314-6fcd-4451-896a-8a527a9fa9e8)

**When we copy the comments it is looks like this:**

![image](https://github.com/WordPress/Learn/assets/22549318/e3c30072-abf3-42d9-a9a1-dc479b94f761)

**Here I have shared the expected result:**

![image](https://github.com/WordPress/Learn/assets/22549318/1b011381-3043-4627-a6cc-b2698c84cabf)

Please let me know if you have any questions.

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great lesson, @cynthianorman.

I noticed that the part that starts at ~3:24 repeats much of the “drill down” into the TT4 `404` page (first mentioned at ~2:08).

**Comment by cynthianorman** [comment]
Ok, @ironnysh once again thank you so much for your feedback! I'll take a look an get rid of redundancy.

**Comment by jonathanbossenger** [comment]
Youtube URL: https://youtu.be/nQkvv-NX6wY

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### YouTube chapters
(0:05) Learning objectives
(0:22) Describe the purpose and structure of a template 
(2:05) List the sequence templates are loaded by WordPress
(2:34) With theme starter files in place, create a template from scratch
(4:52) Next steps

**Comment by cynthianorman** [comment]
https://learn.wordpress.org/lesson/template-overview/

**Comment by cynthianorman** [comment]
//publish
