### ISSUE TITLE
Template hierarchy

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2272]
# Details

- Content type: Lesson
- Content title: Template hierarchy
- Topic description: We will take a deep dive into the details of how WordPress loads templates in a browser.
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- Explain how WordPress uses the query string 
- Briefly explain the template hierarchy diagram
- Describe the template hierarchy for a given page being queried

# Related Resources and Other Notes

- [Template Hierarchy](https://developer.wordpress.org/themes/templates/template-hierarchy/)

**Comment by cynthianorman** [comment]
This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

https://youtu.be/VAgtcFktQZE (unlisted)

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

@cynthianorman, the lesson does a great job explaining the topic.

However, I'm a bit confused about the items mentioned in the _Learning Objectives_:

> Explain how WordPress uses the query string
> Briefly explain the template hierarchy diagram
> Describe the template hierarchy for a given page being queried

Can totally be my lack of understanding, but I couldn't figure out how the first part (query string/permalink) relates to the template hierarchy :-)

**Comment by cynthianorman** [comment]
@ironnysh if you think about how the data is stored within the wp_posts table. For a page we'll find post_type=page
The id of the page corresponds with the given post type so WordPress knows to look for page templates and follows left to right to see if the file exists.
Does this help?
Here's more info
https://developer.wordpress.org/themes/basics/template-hierarchy/#the-template-file-hierarchy

**Comment by ironnysh** [comment]
Thanks for the explanation and the link, @cynthianorman. Alright, this makes much more sense--I guess the part that threw me off was the focus on permalinks

**Comment by cynthianorman** [comment]
@ironnysh I was thinking after the Sample Page loads I could go into the database table and show how WordPress now knows what template to look for because of the post_type value. 

Would my example tie things together better? I want this concept to be solidified in people's minds.

Thanks for your help!

**Comment by ironnysh** [comment]
> go into the database table and show how WordPress now knows what template to look for because of the post_type value

Sounds perfect!

Thanks for being attentive :-)

**Comment by jonathanbossenger** [comment]
Youtube URL: https://youtu.be/sDWvuYzeW4E

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### YouTube chapters:
(0:07) Learning objectives
(0:23) Explain how WordPress uses the query string
(2:46) Briefly explain the template hierarchy diagram 
(3:23) Describe the template hierarchy for a given page being queried
(4:07) Next steps

**Comment by cynthianorman** [comment]
//publish
