### ISSUE TITLE
Template parts

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2273]
# Details

- Content type: Lesson
- Content title: Template Parts
- Topic description: We will explore how to create and add template parts to your theme.
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- Describe template parts and how they work
- Define template part areas
- Register, edit and add a template part to your theme

# Related Resources and Other Notes

- [Template Parts](https://developer.wordpress.org/themes/templates/template-parts/)

**Comment by cynthianorman** [comment]
This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

https://youtu.be/r2U0NzTd2jY (unlisted)

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Another great tutorial, @cynthianorman!

Only suggestion I have is to add an explanation about the _Create Block Theme_ plugin (mentioned at ~5:10). Why is it helpful, how to install it, etc.

**Comment by cynthianorman** [comment]
@ironnysh yes I definitely appreciate the gap of info here for using the plugin. We'll be including the Create Block Theme plugin lesson in the Beginners Learning Pathway. I think it would be as simple as my adding a reference to that lesson.

**Comment by ironnysh** [comment]
Got it. That's even better :-)

**Comment by jonathanbossenger** [comment]
Youtube URL: https://youtu.be/BqKb_hWUM1w

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### YouTube chapters
(0:05) Learning objectives
(0:20) Describe template parts and how they work
(1:31) Define template part areas
(2:31) Add template parts to your theme
(5:23) Next steps

**Comment by cynthianorman** [comment]
//publish
