### ISSUE TITLE
Block Patterns

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2274]
# Details

- Content type: Lesson
- Content title: Block Patterns
- Topic description: 
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- 

# Related Resources and Other Notes

- [Block Patterns](https://developer.wordpress.org/themes/features/block-patterns/)
- https://developer.wordpress.org/news/2024/03/19/pattern-design-tips-and-tricks-for-developers/

**Comment by cynthianorman** [comment]
@jonathanbossenger since the content is labelled Archived now, should we keep this lesson here?
https://developer.wordpress.org/themes/features/block-patterns/

**Comment by jonathanbossenger** [comment]
Hmmm, that's a good question. 

We do have the [Patterns](https://github.com/WordPress/Learn/issues/2193) lesson in the Global Settings and Styles module, so is there more information on Patterns we would need here?

If not, then I see no reason to keep this lesson.

**Comment by cynthianorman** [comment]
@jonathanbossenger I feel that after I've finished the remaining lessons that I would be proposing adding more advanced topics. Perhaps an Advanced Theme Developer learning pathway would be best. This is when the many things I skipped in the Intermediate lessons would be tackled for sure.

**Comment by jonathanbossenger** [comment]
@cynthianorman 100% I could see us adding either additional pathways, or merely adding additional modules/lessons to existing pathways.

I'd personally love to see an Advanced Developer pathway down the line.

**Comment by cynthianorman** [comment]
closing this issue as the topic has be archived in Theme Handbook and Patterns lesson covers the necessary getting started info for theme development 
https://github.com/WordPress/Learn/issues/2193
