### ISSUE TITLE
Block Stylesheets

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2275]
# Details

- Content type: Lesson
- Content title: Block stylesheets
- Topic description: We will explore creating block stylesheets without using the theme.json file. 
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- Describe a block stylesheet
- Create a custom block stylesheet

# Related Resources and Other Notes

- https://developer.wordpress.org/themes/features/block-stylesheets/

**Comment by cynthianorman** [comment]
https://youtu.be/pG_RdfUZxFQ

This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

**Comment by jonathanbossenger** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great lesson Cynthia.

The only piece of feedback I have is that I might be useful to either somehow highlight, or mention, that registering custom block stylesheets is done by using the [wp_enqueue_block_style](https://developer.wordpress.org/reference/functions/wp_enqueue_block_style/) function, with the block name as the first parameter.

The whole time I was watching this was interested to know how this is done, and then you show an example, but don't mention the function reference for [wp_enqueue_block_style](https://developer.wordpress.org/reference/functions/wp_enqueue_block_style/), which I think will be useful.

So my suggestion would be, at 2:35, just after you mention the naming conventions and before the example, to include a short sentence along the lines of 

`To register block stylesheets you use the wp_enqueue_block_style function (screen shows function reference page), passing the block name as the first parameter and an array of arguments as the second parameter`. 

And then that flows perfectly into the example code.

**Comment by cynthianorman** [comment]
@jonathanbossenger thanks so much - done

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great tutorial, @cynthianorman.

My favorite part is at 0:54, with the _best named_ theme in the directory ;-)

**Comment by jonathanbossenger** [comment]
https://youtu.be/_LFPvFi5Xcc

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### YouTube chapters
(0:05) Learning objectives
(0:17) Describe a block stylesheet
(2:07) Create a custom block stylesheet
(3:17) Next steps

**Comment by cynthianorman** [comment]
//publish
