### ISSUE TITLE
Block Style Variations

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2276]
# Details

- Content type: Lesson
- Content title: Block style variations
- Topic description: We will take a look at creating and using block style variations.
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- Describe block style variations and explain how to include them in your theme
- Register your new block style using either PHP or JavaScript
- Customize core WordPress block styles using the theme.json file

# Related Resources and Other Notes

- https://developer.wordpress.org/themes/features/block-style-variations/
- https://developer.wordpress.org/block-editor/reference-guides/block-api/block-styles/
- https://developer.wordpress.org/block-editor/how-to-guides/themes/global-settings-and-styles/
- [Builder Basics: Block Styles vs Block Variations](https://youtu.be/ICI0GW9vibk?feature=shared)

**Comment by cynthianorman** [comment]
https://youtu.be/7bdNPjb2MFw

This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

**Comment by jonathanbossenger** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great lesson, @cynthianorman—simple and to the point.

I only have one suggestion: increasing the font size of the code samples (at 1:08 and 1:31).

**Comment by jonathanbossenger** [comment]
When you are so cool, they name a theme after you...

**Comment by jonathanbossenger** [comment]
https://youtu.be/38crES_t-Qk

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### YouTube chapters
(0:05) Learning objectives
(0:27) Describe block style variations and explain how to include them in your theme
(0:54) Register your new block style using either PHP or JavaScript
(1:23) Customize core WordPress block styles using the theme.json file
(2:04) Next steps

**Comment by cynthianorman** [comment]
//publish
