### ISSUE TITLE
Hindi translation for "Adding a sticky header or banner"

### ISSUE THREAD

**Issue by speedyprem** [WordPress/Learn#2278]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/adding-a-sticky-header-or-banner/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by speedyprem** [comment]
Here translated Content for this - https://docs.google.com/document/d/1tcB8RidYOKw-TPqNgDBhqBGkeYIJBPu9FC6EkznrNKY/edit

**Comment by asharma198** [comment]
Reviewed this translation and looks good to proceed further

**Comment by speedyprem** [comment]
@devmuhib009 I have drafted the tutorial here: https://learn.wordpress.org/wp-admin/post.php?post=87622&action=edit

**Comment by devmuhib009** [comment]
Tutorial published: https://learn.wordpress.org/tutorial/hi-adding-a-sticky-header-or-banner/
Thanks a lot.
