### ISSUE TITLE
What is Internationalization

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2279]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: What is Internationalization
- Topic description: A brief introduction to Internationalization in WordPress, why it's important, and where to learn more about writing translatable code.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Explain what Internationalization is
- Describe it's importance when developing software
- Identify WordPress developer resources for further reading

# Related Resources and Other Notes
- https://developer.wordpress.org/apis/internationalization/
- https://learn.wordpress.org/tutorial/common-apis-internationalization/

**Comment by jonathanbossenger** [comment]
//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/10-introduction-to-internationalization.md/01-what-is-internationalization.md

**Comment by jonathanbossenger** [comment]
Video for review

https://github.com/WordPress/Learn/assets/180629/95d65c79-e3df-4c60-874c-804beedba31a

**Comment by ironnysh** [comment]
Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great tutorial, @Jonathan!

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/05/11/what-is-internationalization/

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/what-is-internationalization/

**Comment by jonathanbossenger** [comment]
//publish
