### ISSUE TITLE
Meeting Agenda March 7, 2024

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2280]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @bsanevans ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- March 7 – [freewebmentor](https://profiles.wordpress.org/freewebmentor/)
- March 14 – [freewebmentor](https://profiles.wordpress.org/freewebmentor/)
- March 21 – [@voboghure](https://profiles.wordpress.org/voboghure/)
- March 28 – [@pooja9712](https://profiles.wordpress.org/pooja9712/)

**2. Looking for feedback**

- Last call! [Discussion: Bringing accessibility-first approaches into content development](https://make.wordpress.org/training/2024/02/20/discussion-bringing-accessibility-first-approaches-into-content-development/) Open till March 9
- Ronny and Maya have volunteered to take on writing for the Contributor Spotlight series. We're looking for nominations for the next folks to introduce! Nominate contributors you've seen active contributing to the team's goals recently.

**3. Looking for volunteers**

- We're looking for volunteers to outline a new Learning Pathway for contributors to the WordPress project.
   - This will involve outlining a curriculum like #2002, identifying what resources already exist on Learn and what new resources need to be created.
- The team is currently gathering a list of requirements for #2231 and we invite folks to share their input directly on the GitHub issue.

**4. Updates from last week's dev-squad triage session**

Attendees: @psykro, @digitalchild, @freewebmentor, @devmuhib

PRs/issues triaged:
- #2264 
- #2261 

We also would like to raise #2231 to any interested team members who can help test translation plugins on the Learn.WordPress.org local development environment.

The team also decided to switch to holding 2 triage sessions a month going forward, on the 2nd and 4th week of the month. We have been very successful in keeping untriaged issues and PRs to a minimum, so this change will allow more time between triage sessions.

**5. Other news**

- [WordCamp Asia 2024 Contributor Day](https://make.wordpress.org/training/2024/02/08/wordcamp-asia-2024-contributor-day/) is happening in just a few hours! Sign up for the online session here: https://www.meetup.com/learn-wordpress-online-workshops/events/299072655/
- Wes and Jonathan will be hosting two more content creator office hours in March. The first session is scheduled for March 14, 2024, at 14:00 UTC ([meeting link](https://us02web.zoom.us/j/83146869068?pwd=bE5rQnFnTGozMHhHVDN5eEdzaW5rQT09)), and the second will be scheduled during the week of the 25th of March.

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.

## 3. Contribution Acknowledgement

- Badges awarded: Training Contributor badge awarded to @ironnysh 🎉 
- Props: 

## 4. Project updates

- [Learning Pathways](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - [Update from February 21](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4165)
  - We're looking for volunteers to map out a Contributor pathway
  - Check out [the new thumbnail designs in Figma](https://www.figma.com/file/1RXSQvg3UJcPCvxyQ9SGnl/Video-Thumbnails?type=design&node-id=145-12760&mode=design) (Please leave feedback directly in Figma)
- WordPress 6.5 release
  - Share your updates here

## 5. Faculty Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

- Discussion: [possible collaboration to transform learning pathways to Skill Trees](https://github.com/WordPress/Learn/issues/2280#issuecomment-1978276485)

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
Added dev-squad triage notes to the agenda.

**Comment by jonathanbossenger** [comment]
**Discussion: possible collaboration to transform learning pathways to Skill Trees**

During the feedback/discussions around Learning Pathways, `@Flo SkillDisplay` has offered to help [transform our learning pathways to a skill tree format](https://make.wordpress.org/training/2023/10/04/learning-pathway-outlines/#comment-4091). I was not aware of the Skill Tree format, but it appears to be a format that Flo offers on their [SkillDisplay](https://www.skilldisplay.eu/) platform, where they have collaborated with other open-source projects.

I would recommend that folks interested in this discussion read the original comment linked above, and the rest of the threaded conversation, to understand the benefits.

The idea here is that the skill tree format could allow teachers to "cherry pick the skills (aka learning path tree nodes) they really need, instantly render their own curriculum for a handout and get matching learning resources that are tailored towards her use case."

The process of converting Learning Pathways into Skill Sets would involve using the [SkillDisplay](https://packagist.org/packages/skilldisplay/core) tool for creating the Skill Set and then hosting the Skill Set somewhere on the Learn.WordPress.org website. 

I would like to invite anyone interested in this process to read through the suggestions and share their thoughts. If this is something we as a team would like to consider, then we might want to plan a) when we want to do this, and b) who will be managing the process. If this is something that needs further discussion, perhaps we should move that all to a separate team post, looking for feedback.

**Comment by jonathanbossenger** [comment]
Added new Content Creator office hours to the other news section.

**Comment by kaitohm** [comment]
The meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1709769679741009

**Comment by devmuhib009** [comment]
@pooja9712 expressed her interest to work as note taker for 28th march. So, I am updating it.

**Comment by devmuhib009** [comment]
Meeting Recap Published Here: https://make.wordpress.org/training/2024/03/11/training-team-meeting-recap-7th-march-2024/
