### ISSUE TITLE
Hindi translation for "Block Spacing"

### ISSUE THREAD

**Issue by speedyprem** [WordPress/Learn#2285]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/block-spacing/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by speedyprem** [comment]
Here is the translation content for review: https://docs.google.com/document/d/151DwbzwcefFPnrF0SLdg1L7Ej5loEVf_OK_gP1dw0D0/

**Comment by asharma198** [comment]
Looks good to me.

**Comment by speedyprem** [comment]
@devmuhib009 I have drafted the tutorial here: https://learn.wordpress.org/wp-admin/post.php?post=136207&action=edit and also finished the wordpress.tv subtitiles.

**Comment by devmuhib009** [comment]
Tutorial Published Here: https://learn.wordpress.org/tutorial/hi-block-spacing/
Thanks for your hard work.  ❤️
