### ISSUE TITLE
Migrating your website, Part 2: Changing your host while keeping your domain name

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2289]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: Migrating your website, Part 2: Changing your host while keeping your domain name
- Topic description:  
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any):Intermediate

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lesson

**Comment by westnz** [comment]
See this issue: https://github.com/WordPress/Learn/issues/2228
