### ISSUE TITLE
URL structure changes and why

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2292]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: URL structure changes and why
- Topic description: 
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate
 
# Learning Objectives

# Related Resources and Other Notes

**Comment by westnz** [comment]
See permalinks tutorial
