### ISSUE TITLE
Introduction to Domains: Understanding DNS records

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2293]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: Domain management: Understanding name servers + Basic understanding of DNS records
- Topic description: 
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lesson

**Comment by egleL** [comment]
I'm going to work on this one

**Comment by egleL** [comment]
Link to the document: https://docs.google.com/document/d/1k3HUuCQJGXHQVlt7zIYAuYzlVtv4-BB4WIpSlm_Ghc0/edit

**Comment by kaitohm** [comment]
Thanks for working on this, @egleL 🙌 
I've marked this as ready for a review. I hope that was correct 🙂

**Comment by westnz** [comment]
I have reverted it back to 'Drafts in Progress' as Egle worked on the draft script. Thank you, @egleL, for laying the groundwork during WCAsia Contributor Day. 

@cynthianorman will take over from here to create the actual video lesson.

**Comment by westnz** [comment]
Hey @cynthianorman 
I was wondering when you will be able to start working on this lesson? 😃

**Comment by cynthianorman** [comment]
I know you have deadlines to meet so feel free to reassign this one. I was thinking I'll be tackling this in August.

**Comment by westnz** [comment]
Thank you for the update @cynthianorman.  You are doing a superb job with the developer pathways.

**Comment by ironnysh** [comment]
Happy to pick this one up and bring it to the finish line

**Comment by ironnysh** [comment]
Hi @westnz, the [draft for the revised script](https://docs.google.com/document/d/1vcwKLUQ0L_rBFwrsnd8hbUfQ9wFbJAHGfMcNpvzIKbA/edit) is ready for your feedback.

**Comment by westnz** [comment]
Thank you for updating and completing the script @ironnysh. The lesson is now ready to be recorded.

**Comment by ervanyuff** [comment]
Hi team, I would like to be involved in recording this video

**Comment by westnz** [comment]
Hi @ervanyuff 
I shared the script and voice recording with you in Slack.

**Comment by westnz** [comment]
![Text + Guests + Editor](https://github.com/WordPress/Learn/assets/89751452/a6b954dd-f912-4b73-aa94-677cdb1fe262)

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/3fa8a870-a167-42b5-9dcf-fe61e4916215

**Comment by digitalchild** [comment]
Another great and informative tutorial, Wes. 

## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by westnz** [comment]
Fantastic video editing @ervanyuff ⭐  You are a pro!

Here are a few things to update:
1. 3:28 - 3.55 Can we include a screen recording of the process instead of having the slides 1.1 - 1.3. Happy for you to use Hostinger as an example. 
2. 4:13 - 4:18 Can we add another screenshot here related to what is being said?
3. 6:20 - 6:21 Sound issue to be fixed
4. Can we remove all the sound effects.

**Comment by westnz** [comment]
//published
