### ISSUE TITLE
Website optimization

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2294]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title:   Basic performance optimization
- Topic description: 
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lesson

**Comment by gmt-2** [comment]
Maybe mention some tools to track site performance like:
-Google Pagespeed
-GTMetrix
-WebPageTest.org

**Comment by ironnysh** [comment]
I'd like to work on this one. (testing //assign)

**Comment by ironnysh** [comment]
//assign

**Comment by ironnysh** [comment]
Hi @westnz, I noticed #855 was published in 2022.

Would it be okay to cover image optimization in this tutorial, too?

Unoptimized media is the biggest performance killer, and #855 is thorough but somewhat outdated.

**Comment by westnz** [comment]
@ironnysh I think we should split the two as we don't want the video to be too long. 
In this lesson, we can say we will thoroughly cover image optimization in the next lesson. Could you please share what needs to be updated in #855 so I can work on that next?

**Comment by ironnysh** [comment]
@westnz, I'll share an outline later today, just to make sure we're on the same page about what's considered "basic" 😄

**Comment by westnz** [comment]
Well, technically this is for intermediate level WordPress users so we can remove the word basic?

**Comment by westnz** [comment]
Hey @ironnysh 👋 
Can you please share an update on the script? 😃

**Comment by ironnysh** [comment]
Hi @westnz, the draft is ready in [this doc](https://docs.google.com/document/d/1Zc8uFbfDZfov6CbDAYvtJEZG13JSXF8SPX0zjILfbK8/edit?usp=sharing).

~it's almost ready--I'll share the link during the weekend.~
I saw your comment about intermediate/basic, and decided to just go ahead and write it (skipping the outline). Should've updated the issue, sorry

**Comment by westnz** [comment]
Perfect, thank you very much!!

Fantastic work as always!  I have left one or two notes for consideration.

**Comment by ervanyuff** [comment]
Hi team, I would like to be involved in recording this video

**Comment by ironnysh** [comment]
Thanks, @westnz! One open question left 😄

**Comment by westnz** [comment]
I have shared the voice recording and script with @ervanyuff 🚀

**Comment by westnz** [comment]
Hey @ervanyuff 
Can you please confirm when this lesson will be done? 😃

**Comment by ervanyuff** [comment]
Hi @westnz 
I will try to finish it by the middle of next week, or possibly sooner on Monday or Tuesday next week 🙏 

Also, I need access to the script document

**Comment by westnz** [comment]
@ervanyuff 
Can we aim for Monday to give us enough time to review? The aim is to complete the Intermediate Learning Pathway by the end of next week.

I have given you access to the script.

**Comment by ervanyuff** [comment]
@westnz Okay, I'll try my best to finish on Monday 🙏

**Comment by ervanyuff** [comment]
Hi team, here is [Website Optimization](https://drive.google.com/file/d/17hMmifjZ_O_kNPfAPbBAdQ7j2pqHvHu1/view?usp=sharing) video. Please feel free to provide any feedback. Thank you 🙏

**Comment by westnz** [comment]
Great work as always @ervanyuff 🥇 

Here are a few things I noticed:

1. 0.55 The Image on the right looks a bit fuzzy on my large external screen. I would replace this with a better image.
2. 1.36 That is a screen recording of the outdated version of this lesson.  Here is the URL of the new lesson that will form part of this Learning Pathway. I suggest having a screenshot rather than a static screen recording where you scroll down. https://learn.wordpress.org/lesson/image-optimization/
3. I feel too much text is used in some places. 1:56 - 2:22: Can you use a theme and plugin graphic instead of text?
4. 5:28 / 5:29: a thumping sound needs to be removed or lowered.
5. 5:30 -5:36 I suggest taking a static screenshot of the Performance Lab plugin—no scrolling.
6. 5:37 The transition is a bit jarring.  Can we slow the flip down?
7. 6:03 - 6:09 Great images. Can we have them as static images - no movement.
8. 6:43 - 6:56 To avoid using so much text, can we use a hosting graphic here instead of the bullet point of text?
9. 7:07 - 7:21 I love the map and images, but can you also make these images static—no movement? It would be better for accessibility. 
10. 7:47 - Can we make the images static again - no movement.
11. 7:58 Instead of having text only, can an image of the WordPress logo replace the first bullet point of text.

**Comment by digitalchild** [comment]
You go into the various details of basic web optimisation throughout the video but I think it would be good to have an overview slide that outlines what you will cover in the video. 

7:10 You mention plugins and then start talking about CDN. Except, CDNs are outside of plugins. Some plugins assist in providing more detail. I think CDNs should be under a caching, not plugins. 

Lightspeed plugin is only for light speed web servers, which is a very small market share compared to NGINX or Apache. 

## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by ironnysh** [comment]
> Lightspeed plugin is only for light speed web servers, which is a very small market share compared to NGINX or Apache.

Thanks for this comment, @digitalchild. Just to clarify why I included it in the script:
- Some features are indeed available only on LS servers, but many are server-agnostic. There's a list on the [plugin page](https://wordpress.org/plugins/litespeed-cache/).
- According to [the stats](https://wordpress.org/plugins/litespeed-cache/advanced/), it has over 5m active installations.

**Comment by ervanyuff** [comment]
Hi team, here is the updated [Website Optimization video](https://drive.google.com/file/d/1oM5xJSEly_cjcP3j6R-BCPt7PP4mQXfY/view?usp=sharing). Please let me know if there is anything missing 🙏

**Comment by westnz** [comment]
Thank you for making all the updates Ervan. I am happy with the final result. 

@digitalchild, when we get the green light from you we can publish. 😃

**Comment by digitalchild** [comment]
Green light! Thanks for addressing my concerns.

**Comment by westnz** [comment]
Thank you all for your hard work and helpful reviews!

**Comment by westnz** [comment]
//published
