### ISSUE TITLE
Setting up an XML sitemap

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2295]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: Setting up an XML sitemap
- Topic description:  
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lesson

**Comment by ironnysh** [comment]
I’d like to take this one

**Comment by ironnysh** [comment]
**Resources:**
[Building A Sitemap For A Site](https://learn.wordpress.org/lesson-plan/building-a-sitemap-for-a-site/)
[What are sitemaps](https://www.sitemaps.org)
[Search Engine Optimization on WordPress.org documentation](https://wordpress.org/documentation/article/search-engine-optimization/#sitemaps)

**Comment by ironnysh** [comment]
Hi @westnz, I wonder about the premise of this tutorial:

1. If users are running the latest versions of WordPress, a sitemap will be generated for them.
2. Search engine visibility is opt-out: people would have to _actively_ block search engines in **Settings > Reading**.

See [Building A Sitemap For A Site](https://learn.wordpress.org/lesson-plan/building-a-sitemap-for-a-site/#create-a-sitemap-for-your-website)
> Since the release of [WordPress 5.5](https://wordpress.org/support/wordpress-version/version-5-5/), sitemaps are now automatically generated for your website. The default sitemap for any WordPress site running 5.5 or later is located at [insert your domain name here]/wp-sitemap.xml.

*The [official WP stats](https://wordpress.org/about/stats/) indicate that 10.31% are still running version 4.4 or older.

***

I suggested including the relevant information (what is a sitemap and how to access it) in lessons #2257 and #2291.
What say you?

**Comment by westnz** [comment]
I agree. Let's close this issue out, then. Will touch base with you regarding the other lessons.
