### ISSUE TITLE
Workshop Presenter Application Form 

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/Learn#23]
To aid in the vetting and approval of applications to be a Workshop presenter, I'd like to propose a form be setup to create a Workshop Post Type (#3) with an initial, unpublished, post status.  The implementation would be similar to the CPTs in place for WordCamps and Meetups on central.wordcamp.org.  This [WordCamp Application Class code](https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/plugins/wcpt/wcpt-wordcamp/class-wordcamp-application.php) may be useful to review. 

The [current form](https://make.wordpress.org/community/2020/08/03/the-learn-wordpress-workshop-presenter-application-is-here/) asks questions that are good for vetting and approval for the presenter to start creating their video.  The WordCamp organizer form lives at https://central.wordcamp.org/wordcamp-organizer-application/.  For the Workshop presenter application form, I'd propose it live at https://learn.wordcamp.org/workshop-presenter-application/.

I believe there should be a series of Workshop post statuses setup as well.  I've reviewed the list of [WordCamp post statuses](https://github.com/WordPress/wordcamp.org/blob/f9236be586930447f1e15892d8cc311edb123a7d/public_html/wp-content/plugins/wcpt/wcpt-wordcamp/wordcamp-loader.php#L166) and propose the following:
* Needs Vetting
* More Information Requested
* Declined
* Approved to Create Video
* Needs Video Review
* Workshop Published
* Workshop Unlisted

The Workshop Unlisted status could have a different name.  It would be used to indicate a Workshop has been removed typically because the content is no longer accurate.

Some questions that might determine other statuses to consider: 
* Should there be a separate status to put a update the title and description?
* Does a Workshop Presenter need to sign an agreement?
* Are there other statuses which should be considered?

**Comment by hlashbrooke** [comment]
This follows the steps outlined in #14.

I quite like the idea of a series of custom statuses here - it would really help with the flow of reviewing and management. If that won't be possible to implement for the initial launch, we could go with the standard post statuses at first and then implement custom statuses later on.

**Comment by CdrMarks** [comment]
In case it's useful, I duplicated the [current form](https://make.wordpress.org/community/2020/08/03/the-learn-wordpress-workshop-presenter-application-is-here/) which can be found as a draft at https://learn.wordpress.org/wp-admin/post.php?post=289&action=edit.

I did see that WordCamp and Meetup applications are using an [HTML form](https://github.com/WordPress/wordcamp.org/blob/production/public_html/wp-content/plugins/wcpt/views/applications/wordcamp/shortcode-application.php) invoked via shortcode.  I had seen @coreymckrill [suggest](https://github.com/WordPress/learn/issues/14#issuecomment-669509209) WordCamp Forms to Drafts plugin code.  I believe this draft will head us down the right path for a new application form to create a Workshop post type.

**Comment by CdrMarks** [comment]
I'd like to work up a PR to initially support the series of statuses a Workshop could have.  I plan to port over some code from the the [WCPT plugin](https://github.com/WordPress/wordcamp.org/blob/f9236be586930447f1e15892d8cc311edb123a7d/public_html/wp-content/plugins/wcpt/wcpt-wordcamp/wordcamp-loader.php#L166).  Should the ported code be in /wp-content/plugins/wporg-learn/wporg-learn.php or another file?

**Comment by coreymckrill** [comment]
🤔 How about a new file at **plugins/wporg-learn/inc/post-statuses.php**?

**Comment by CdrMarks** [comment]
This is more involved than I thought.  I'm unassigning this so that I don't delay progress if someone else has the time.

**Comment by hlashbrooke** [comment]
I'm moving some of the content over here from #14 so we can use this as the issue for this feature going forward.

The workshop submission flow should work like this:

**Step 1:** Presenter submits their workshop details in a custom form. This saves their details as a new post in the workshop CPT, but in a custom `Needs vetting` status.

**Step 2:** Reviewers are given a user role that permits them to edit posts in the workshop CPT (editor? A custom user role?). They can log in to review the workshop and leave notes on it as needed.

**Step 3:** For a workshop that is approved, the reviewer would get any additional info from the presenter, and also inform them that they should go ahead and record the workshop.

**Step 4:** The recorded workshop, along with any other missing info, is added to the post and it is scheduled to be published.

**Comment by StevenDufresne** [comment]
This may be a naive question, and not code related, but why would we ever not want a video to be created? 
More content = 👍 

Is funding provided when the video is approved?

**Comment by hlashbrooke** [comment]
Funding is not provided - people can record on their computers at home.

Videos may be declined if the topic they applied for already exists, or if it's just not something we want on the site (like maybe a company promotional thing, or something that just doesn't fit).

**Comment by coreymckrill** [comment]
We just got Edit Flow installed on the Learn site today. I wonder if the custom status feature in that could work for this situation? Obviously we'd still need to build a submission form, but this might take care of the workflow once a workshop application is submitted.

**Comment by hlashbrooke** [comment]
If Edit Flow allows the custom statuses, then all we need is for the current application form (that uses Jetpack forms) to post directly to the workshop CPT into a 'needs vetting' status. That sounds like an excellent solution to me.

**Comment by coreymckrill** [comment]
@hlashbrooke The [current application form](https://learn.wordpress.org/workshop-presenter-application/) asks about the intended audience and experience level for the proposed workshop, but we aren't using those related taxonomies on the workshop post type (only on lesson plans). Do we still need those questions on the application form?

**Comment by hlashbrooke** [comment]
We have experience level as a meta field I think? Either way though, that info is useful to capture from a content review perspective, so we need the questions in there.

**Comment by coreymckrill** [comment]
@hlashbrooke @CdrMarks In #129 I built out a custom form for the Workshop Presenter Application. On a successful submission it creates a new workshop post in the "Needs Vetting" status. I set up all the other statuses listed in this issue using the Custom Statuses module in Edit Flow.

I created a private test page with the new form that I'd love for you to try out. Especially looking for feedback about the wording of the questions and anything that might be missing, either from the form or from the generated workshop post.
https://learn.wordpress.org/test-workshop-presenter-application/

You can give feedback here, and I'll create a new pull request for any necessary adjustments.

**Comment by hlashbrooke** [comment]
This looks great and works brilliantly!

A couple of changes that would be good:
* The text area boxes are quite small - could we increase the min-height of those a little to accommodate at least 4 lines each?
* You can actually remove the question about timezones from this form - it isn't relevant or useful here (I know it's in the current form, but we actually don't need it for the workshop presenters)

And that's it - this is really great work :)
