### ISSUE TITLE
Link content types

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#230]
It would be great if we could link different content types on the site, so we could have situations like this:
* If a workshop is based on a lesson plan, the workshop page we have a link that says "view the lesson plan for this workshop so you can teach it yourself"
* Similarly for the lesson plan - it can link to the workshop so people can see the plan being put to use
* Courses can be linked to lesson plans to show people how they can teach the course themselves
* Workshops can indicate which courses they appear in

In terms of implementation I can see this being an autocomplete multi-select custom field on each content type that allows you to select the linked content in other types.

**Comment by coreymckrill** [comment]
Would these links appear anywhere besides on the single post view? Could we just add a section in the content template called "Related Content" or something and then add links or embeds, instead of adding more custom UI and post meta?

**Comment by hlashbrooke** [comment]
Oh yeah - I like that! That sounds like a good way forward.

**Comment by azhiya** [comment]
With lesson plans, there is currently a section for additional resources that is used to list any related lesson plans or video workshops. Are you envisioning changing this to "Related Content"?

**Comment by coreymckrill** [comment]
I don't think the wording would need to change from whatever it is now.

**Comment by adamwoodnz** [comment]
Closing since the information architecture for the site has become simplified, and these links aren't necessary anymore.
