### ISSUE TITLE
Adding custom user roles using a WordPress plugin

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2300]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: Advanced user management: Utilize a plugin to manage additional user roles within WordPress
- Topic description:  
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lessons

**Comment by digitalchild** [comment]
//lessons

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/d2e8a58e-b92f-481f-9896-4cee2252e98b

**Comment by digitalchild** [comment]
Nice overview @westnz 

- Is there a reason this plugin was chosen over the more popular user role editor? 
- 2:06 you mention that if they make changes to default roles and disable the plugin, the changes don't revert. I would say making changes to roles with any plugin, the changes are saved and need to be reverted. It's recommended if you need to make changes to a default role to copy the role and make the changes in the new role. 
- At the end of the video, this feels like an advertisement for member press. Is it relevant to mention that you can create a membership site when the lesson is about roles? 
- Should there be an overview of what roles and capabilities are, or reference another lesson? 

## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [ ] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great lesson, @westnz.

Follow-up to @digitalchild's comments:
- At 0:18, when you mention the previous lesson, it would be helpful to provide the title of the LP/lesson, so people can find it. I think it's this one? https://learn.wordpress.org/lesson/user-management-2/

1. > I would say making changes to roles with any plugin, the changes are saved and need to be reverted. It's recommended if you need to make changes to a default role to copy the role and make the changes in the new role.

   There's a disclaimer on [Members's documentation page](https://members-plugin.com/docs/role-management/
):
   > Any changes you make to users and roles using this feature are permanent changes. This means that if you deactivate or uninstall this plugin, the changes won’t revert to their previous state. This plugin merely provides a user interface for you to make changes directly to your WordPress database. Please use this feature wisely.

   FWIW, the revert/reset issue also came up in one of [User Role Editor's support tickets](https://wordpress.org/support/topic/dont-use-27/).

2. > Is it relevant to mention that you can create a membership site when the lesson is about roles?

   A membership site is one of the use cases mentioned at 0:44, so it's not entirely out of the blue :-)

**Comment by westnz** [comment]
Really appreciate the solid feedback @digitalchild and @ironnysh

**Comment by westnz** [comment]
//published
