### ISSUE TITLE
Lesson: Unlocking advanced SEO techniques: Part 1

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2301]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: Advanced SEO
- Topic description: Understanding and Implementing robots.txt on WordPress for Improved SEO and Controlled Crawling with Semantic HTML
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lessons

**Comment by pricelessopoku** [comment]
I'd like to help out with writing the script for this lesson.

**Comment by westnz** [comment]
This is the intermediate lesson: https://github.com/WordPress/Learn/issues/2291

**Comment by patelamitn** [comment]
@westnz plz include me as assignee, i can help you on the topics.

**Comment by westnz** [comment]
Thank you, @patelamitn.

If you have anything to share, please do so. @pricelessopoku can then include it in the script. 

Once the script is done, your expertise and review will also be much appreciated. 🙏

**Comment by pricelessopoku** [comment]
Script - https://docs.google.com/document/d/1GLydla133YChmulr-E8KLga2H5ya-T9DNcfRI9f8b1s/edit?usp=sharing

**Comment by westnz** [comment]
Great work @pricelessopoku. @patelamitn, we would appreciate your review and input.

**Comment by patelamitn** [comment]
@westnz can you plz provide me commenting rights so that i can review and add inputs.

**Comment by patelamitn** [comment]
Hi  @pricelessopoku, @westnz 
I have added comment in the doc, Feel free to let me know if you need any help.

**Comment by pricelessopoku** [comment]
@patelamitn I have update the doc - https://docs.google.com/document/d/1GLydla133YChmulr-E8KLga2H5ya-T9DNcfRI9f8b1s/edit?usp=sharing

**Comment by pricelessopoku** [comment]
I will start working on the video on July 1st. I will need a contributor to help with the voice over recording.

**Comment by ghost** [comment]
I am happy to do the voice over recording.

**Comment by pricelessopoku** [comment]
Updated doc (Outline for review) - https://docs.google.com/document/d/1GLydla133YChmulr-E8KLga2H5ya-T9DNcfRI9f8b1s/edit?usp=sharing

@westnz

**Comment by westnz** [comment]
Thanks, Emmanuel!  @patelamitn and @ironnysh could you please review the updated outline? 😃

**Comment by patelamitn** [comment]
Hi @westnz I a bit confused. Few sections are missed. Also i see red highlighted area with no comments.

**Comment by westnz** [comment]
Thanks, @patelamitn and @pricelessopoku. Could you please shed light here?

**Comment by pricelessopoku** [comment]
Hi @westnz @patelamitn I have updated the script, let me know if this is clearer now. Thanks, https://docs.google.com/document/d/1GLydla133YChmulr-E8KLga2H5ya-T9DNcfRI9f8b1s/edit?usp=sharing

**Comment by patelamitn** [comment]
Thanks @pricelessopoku 
I have added comments in the document.

**Comment by pricelessopoku** [comment]
Hi @westnz @patelamitn updated script here - https://docs.google.com/document/d/1GLydla133YChmulr-E8KLga2H5ya-T9DNcfRI9f8b1s/edit?usp=sharing

This has being split into 2 lessons.

**Comment by patelamitn** [comment]
Hi @pricelessopoku 
The first lesson looks great.

However for the second lesson, i was expecting schema markup details and its implementations which is really crucial as part of advanced SEO.

**Comment by pricelessopoku** [comment]
@westnz Video Script for "Unlocking Advanced SEO Techniques: Part 1" https://docs.google.com/document/d/126ZCtR-nJqptXPNFrTREx0mA7GPTdlKXe_X4HjB4hzw/edit?usp=sharing

Working on part 2

**Comment by ironnysh** [comment]
Thanks @pricelessopoku! I'll have time to go over the script in the next few days.

**Comment by ironnysh** [comment]
Very informative lesson, @pricelessopoku 👏

I left some comments in the doc:
- Most are related to the formatting (standalone tutorial vs. a screenplay).
- There are a few topics that I feel should be fleshed out. In other words, you're an expert—don't hold back on the knowledge sharing! 🤓

**Comment by westnz** [comment]
Part 2: https://github.com/WordPress/Learn/issues/2624

**Comment by westnz** [comment]
Thank you for the hard work on the script. This lesson is now ready to be created. @lada7042, I will contact you about the voice recording. @pricelessopoku will edit the video. I will create Part 2 once the script is finished. I have created a separate GitHub Issue for this. See above.

**Comment by westnz** [comment]
Video thumbnail 
<img width="1280" alt="Text + Editor (1)" src="https://github.com/user-attachments/assets/1dbc612a-954b-4fce-8ceb-cb4e77064109">

**Comment by ghost** [comment]
@westnz  My goal for finishing audio recording is today, 8/28. May need extra time but will definitely be done by 8/29 ( US eastern time)

**Comment by ghost** [comment]
Finished audio recording.  Please let me know if I need to redo. The parts where their were lists I did not say the numbers. Is that something you would like me to say? I used OBS as Wes recommended. I may need guidance in setting up the settings. I am not able to add file here since it is a .mkv file so I added it to the training team drive. https://drive.google.com/file/d/1PQXHR_n4uts5-IfhY_C5QlguPbDIqwZS/view?usp=sharing

**Comment by westnz** [comment]
Thank you very much @lada7042 ⭐ 
@pricelessopoku, can you please check and confirm that everything is in order?

**Comment by pricelessopoku** [comment]
@westnz @lada7042 everything is in order. I will go ahead and start work on the video.

**Comment by westnz** [comment]
Thank you for confirming! Great teamwork!

**Comment by ghost** [comment]
@pricelessopoku @westnz Here is the the re-record of the audio with the updated script and correct pronunciations. https://drive.google.com/file/d/1UchbIqGctqUzGceoyVV9qi2jHwpvwBj7/view?usp=sharing Thank you for your patience. Please let me know if I need to redo any parts.

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/4376b2d9-0665-4f90-8bfb-8fa4fd278aeb

**Comment by digitalchild** [comment]
This is a good introduction to SEO technics. I found the speed to be a little slow but still very easy to follow. 

- For the robots.txt file examples. It might be a good idea to use standard WordPress URLs, such as /wp-admin/. 
- For the sitemaps section you might want to say where they can find the URL for their sitemaps as it might not be obvious for all. 

Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by cynthianorman** [comment]
//review

**Comment by kaitohm** [comment]
//review

**Comment by westnz** [comment]
Thank you for the reviews, folks!

**Comment by westnz** [comment]
@pricelessopoku The review has been completed.  Can you please go ahead and make the necessary updates?

**Comment by patelamitn** [comment]
- The video flow is smooth and well-structured.  
- At 4:19, consider adding realistic WordPress admin URLs for the blocked section.  
- The transition from 5:40 between canonical URLs and the sitemap is a bit unclear.  
- To improve clarity from 5:45 onward, please add an extra screen to better distinguish between canonical URLs and the sitemap.

**Comment by westnz** [comment]
//published
