### ISSUE TITLE
Use a CDN to enhance performance

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2302]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: Use a CDN to enhance performance
- Topic description:  
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lessons

**Comment by westnz** [comment]
Thank you @ironnysh for helping me write the [script](https://docs.google.com/document/d/1CR2v0BIUwC8jBGn378XB9A2gIaD8vupwcx-6MrFch5I/edit).

**Comment by ervanyuff** [comment]
Hi team, I would like to be involved in recording this video

**Comment by ironnysh** [comment]
Thanks for inviting me to be a co-writer/editor, @westnz! 😉

**Comment by westnz** [comment]
Hey @ervanyuff, I have shared the voice recording with you and also included some screen recordings you could use.

**Comment by ervanyuff** [comment]
Hi team, here is [CDN video](https://drive.google.com/file/d/11BPBHcbFRw6AyW5SxsvmAsOS9bp-euI9/view?usp=sharing). Please let me know if there anything missing. Thank you 🙏

**Comment by westnz** [comment]
Review:

Fantastic work @ervanyuff. 

- 2:19 We need to re-record the narration: 'Cloudflare' sounds like 'Cloud-fare'
- 2:56 - 2:58 Can you make the transition a bit smoother? Can you pause the screen for 3 seconds at 2:55 before you transition to the next screen? Once the transition is finished it should start with the words "I will install and activate the Super Page Cache for Cloudflare." You might need to pause the screen there as well to fit in with the timing.
- 3:07 Can you pause the screen for 3 seconds after saying, "Back on WordPress, the plugin will guide you through the setup process?" It moves too quickly to the next section.
- 3:37 Improve transition. Pause the screen for 3 seconds before moving to the next section. It moves too quickly to the next section.
- 4:01 Pause the screen for 3 seconds before moving to the next section. It moves too quickly to the next section.
- 4:17 - 4:20 The annotation or box is drawn around the wrong area.  The box should be drawn around the top section where it says 'QUIC.cloud CDN: OFF / ON ... Enable QUIC.cloud CDN API functionality'
- 4:20 Pause the screen for 2 seconds before moving to the next section which starts with '...and the Cloudflare option is available when you scroll to the bottom'
- 4:24 Pause the screen for 3 seconds before moving to the next section. It moves too quickly to the next section.
- 4:29 Pause the screen for 3 seconds before moving to the next section. It moves too quickly to the next section.

**Comment by ervanyuff** [comment]
Hi @westnz, here is the [updated CDN video](https://drive.google.com/file/d/1-3OENgJtGGcGtTE0b57VfYPp7NANjmns/view?usp=sharing). let me know if there are some things that need to be changed again :pray:

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great job, @westnz and @ervanyuff! 🙌

**Comment by westnz** [comment]
Thank you for the updates, @ervanyuff! Moving this to the 'Preparing to publish' column.

**Comment by westnz** [comment]
//published
