### ISSUE TITLE
Use WordPress to create a one-page site 

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2304]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: Use WordPress to create a one-page site
- Topic description:  Use WordPress to create a one-pager (basically, using [this](https://wordpress.org/documentation/article/page-jumps/) or recreating [this](https://wordpress.org/themes/stacks/)). See also [this workshop](https://www.youtube.com/watch?v=GyYgMdrXJiY&t=1952s).
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lessons

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/72a8e2be-2961-4756-b796-bab5f9931027

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

This is an excellent tutorial, @westnz! 💫

I have two comments:

**Links:** I wouldn't call the links in the Navigation block labels:
1. These are standard links that just happen to point to [a section on the same page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#linking_to_an_element_on_the_same_page). To differentiate them from external links, maybe they can be called “in-page links”?
2. [Labels are specific HTML elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) that are usually associated with forms.

It could be useful to clarify that the URL should either be one word (no spaces) or separated with hyphens/underscores (**-** or **_**). It's only mentioned later, when you get to the HTML anchor part.

**Smooth scrolling:** from an a11y perspective, it's good practice to wrap this functionality in a `prefers-reduced-motion` media query. This respects the user's preferences and only kicks in when they haven't explicitly [disabled the option on their device](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).
Here's the snippet:
```css
@media (prefers-reduced-motion: no-preference) {
  html {
    scroll-behavior: smooth;
  }
}
```

**Comment by lada7042** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ ] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [ ] The speed of demonstrations are easy to follow.
- [ ] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [ ] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by westnz** [comment]
Very helpful feedback @ironnysh 🥳 

> It could be useful to clarify that the URL should either be one word (no spaces) or separated with hyphens/underscores (- or _). It's only mentioned later, when you get to the HTML anchor part.

Could you elaborate what you meant here?

**Comment by Soir7** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
[+] Learning outcomes/objectives are clear.
[+] Technical concepts introduced in the content are accurate.
[+] The speed of demonstrations are easy to follow.
[+] The narration audio matches what is shown visually.
[+] Spelling and grammar are correct.
[+] Sound quality is consistent throughout the video.
[+] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
[o] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)). - **How may I verify following images are in public domain? Am I to find in cc.org link?**

Leave an additional comment below with feedback. You can also share what you liked about this Tutorials in in progress

Hi @westnz! Nice flow - beautifully methodical and concise. Love your positive, encouraging, and upbeat tone.

Some comments:

1 - If this video is meant to appeal to the most elementary level, please define 'sticky' menu.
2 - Comment added @ 3.08 about bookmarks & ids. Consider placing this descriptive info. to precede the actual tasks.
3 - I understand it can be challenging to decide which/how many definitions/explanations to add during video. Where/when applicable, consider supplementing video with glossary/definitions list.  
4 - Not sure how to specifically how to check if 3 media assets (guy @ laptop/Bilbao/head-shot are in public domain. Following resource seems vast:  https://creativecommons.org/share-your-work/public-domain/cc0.

Thank you.

**Comment by TinaCollier** [comment]
Hey @westnz Long time no see!

I watched your video lesson, and you knocked it out of the park with this tutorial. You addressed all four Learning objectives:

- [x] Create a front page template
- [x] Create a fixed header
- [x] Add labels and anchors
- [x] Implement smooth scrolling

You did a great job explaining how to create the template and all of the parts, what they do, and how to edit them. You also did well in explaining how HTML anchors work and why and how they have to be linked.

Regarding smooth scrolling, I like that you showed what the site would act like without the smooth-scrolling code snippet. This really brings attention to how different the behavior of the page is without that additional CSS.

Overall, this was an easily digestible lesson for a newbie. Thanks for sharing!

Best,
Tina

**Comment by westnz** [comment]
Thank you @TinaCollier

**Comment by ironnysh** [comment]
> > It could be useful to clarify that the URL should either be one word (no spaces) or separated with hyphens/underscores (- or _). It's only mentioned later, when you get to the HTML anchor part.
> 
> Could you elaborate what you meant here?

At 2:16, you demonstrate how to link to the “My work” section by typing `#mywork` as one word. People who don't know HTML may not know that URLs should be lowercase and without spaces. It wasn't mentioned until 3:24.

**Comment by westnz** [comment]
//published
