### ISSUE TITLE
Making the most of the Font Library

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2305]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title:  Making the most of the Font Library
- Topic description: A best practices lesson:
Avoid too many font families
What [to do](https://make.wordpress.org/core/2024/03/21/font-library-update-storage-of-font-files) if you can't install fonts (hosting)
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lessons

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/c061b76b-bf2b-4b68-8e85-fcbe821c6f6a

**Comment by westnz** [comment]
Thank you, @ironnysh, for reviewing the script.

**Comment by digitalchild** [comment]
Great video on the library and design tips. 

## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by westnz** [comment]
Thanks @digitalchild

**Comment by westnz** [comment]
//published
