### ISSUE TITLE
Use a more advanced plugin to create a custom post type

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2306]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title:  Use a more advanced plugin to create a custom post type
- Topic description:  
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lessons

**Comment by westnz** [comment]
See: https://github.com/WordPress/Learn/issues/2215
