### ISSUE TITLE
How styles are generated

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2308]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: How styles are generated
- Topic description:  
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced

# Learning Objectives

An advanced follow-up to these two lessons: [Styling your site with global styles | Learn WordPress](https://learn.wordpress.org/lesson/styling-your-site-with-global-styles/) and [Using the style book | Learn WordPress](https://learn.wordpress.org/lesson/using-the-style-book/))
Basic introduction
Why is it there, and how do we understand different parts of it?
Feel comfortable when encountering it.
If you want to learn more, go to the Developer LP
# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lessons

**Comment by ironnysh** [comment]
//assign

**Comment by ironnysh** [comment]
Hi @westnz, the draft is ready for feedback [in this doc](https://docs.google.com/document/d/1K37ovTbR35fwrS_oa6Zumle84EBdesrB9Gfgukywhj0/edit#heading=h.gd51j27kzlxi).

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/f0a2c3ba-d370-4a40-bd82-a69ea974a486

**Comment by teuila-mau** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial:

- speed is great
- easy to follow even for non-DEVs
- icons and diagrams are helpful and make the content easier to understand
- audio is very clear and there is zero background noise even when listening with headphones

**Comment by westnz** [comment]
Super helpful feedback. Thank you @teuila-mau 

> easy to follow even for non-DEVs

glad to hear this

**Comment by Soir7** [comment]
Please tick all items you've confirmed:

[x]     Learning outcomes/objectives are clear.
[x]     Technical concepts introduced in the content are accurate.
[x]     The speed of demonstrations are easy to follow.
[x]     The narration audio matches what is shown visually.
[x]     Spelling and grammar are correct.
[o]     Sound quality is consistent throughout the video. - Please see comment*
[x]     [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
[o]     Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comments on transcript**:

1. Third paragraph - Word **halfmoon** is listed as compound, should be two separate words (half moon) or add hyphen between words.
2. Seventh paragraph - Appears a period could be added between words **rem** and **Rem**.
3. Paragraph preceding **Conclusion** title - '....need to **do** change something...' - Remove word **do**.


**Comments on video**:

1. **0:44** - there is an abrupt jump to next topic, **font pairs** and speech sounds cut-off.
2.  ***** **Closing sentence** - sound is more clear then rest of video, with a more energetic and confident tone.

**Comment by westnz** [comment]
Thank you, @Soir7 😃

**Comment by Soir7** [comment]
You are welcome @westnz. I am about to review the next video for this ticket.

**Comment by Soir7** [comment]
**Video**:  **[Using the style book | Learn WordPress](https://learn.wordpress.org/lesson/using-the-style-book/))**

**Confirmed**:

[x] Learning outcomes/objectives are clear.
[x] Technical concepts introduced in the content are accurate.
[x] The speed of demonstrations are easy to follow.
[x] The narration audio matches what is shown visually.
[x] Spelling and grammar are correct.
[x] Sound quality is consistent throughout the video. - Please see comment*
[x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
[o] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comments on transcript**:

**Second  paragraph**:

1. Add hyphen between these two words - mini menu
2. '...it has **comes** with eight different style variations...' - change **comes** to **come**
3. '...so there’s actually a revisions that we can click on.' - Add revisions **link, text, section, or whatever**.

**Third paragraph**:
1. Word halfmoon is listed as compound, should be two separate words (half moon) or add hyphen between words.
2. Remove duplicate instance of word **in**:  '....a different color in in some...'.
3. Remove duplicate instance of word **your**:  '...your your buttons...'. 

**Comments on video**:

1. Nice pace and energy; warm, cheerful, and enthusiastic tone.
2. Like how you built up some excitement leading into presentation of tabs. I felt like I was getting a bonus. :->
3. Thinking of accessibility, this comment may be a bit picayune....there are several a roughly a handful of instance where pronoun **this** is used. May be preferable to indicate specific name of **this**. For example, @ point 6.31, where word **this**, is used, can you say **block with the button**?

**Comment by Soir7** [comment]
Confirmed:

x  Learning outcomes/objectives are clear.
x  Technical concepts introduced in the content are accurate.
x  The speed of demonstrations are easy to follow.
x  The narration audio matches what is shown visually.
x  Spelling and grammar are correct.
x  Sound quality is consistent throughout the video.
x  [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
o  Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Comments:

1. In the beginning, you modified you voice to clearly state the purpose of the theme files. Using the term 'single source of truth' solidified your point.
2. Nice how you punctuated the video with encouragements to learn and study, such as:
- 3.12 - take a moment to browse the json file
- 4.00 - showing us WP learning pathway
- 4.45 - indicating exact place to find more in-depth info. on themes

3. Towards the end, you firmly emphasized using the site editor to make changes, rather than doing so directly on the actual theme file.

Thanks, @westnz

**Comment by RoelofWobben** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [X] Learning outcomes/objectives are clear.
- [X] Technical concepts introduced in the content are accurate.
- [X] The speed of demonstrations are easy to follow.
- [X] The narration audio matches what is shown visually.
- [X] Spelling and grammar are correct.
- [X] Sound quality is consistent throughout the video.
- [X] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [X] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by lada7042** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ ] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [ ] The speed of demonstrations are easy to follow.
- [ ] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [ ] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by lada7042** [comment]
//review

**Comment by westnz** [comment]
//published
