### ISSUE TITLE
Introduction to phpMyAdmin

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2309]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Introduction to phpMyAdmin
- Topic description: 
Explore your site’s database using the phpMyAdmin UI.
Get a basic understanding of the structure and tables (wp_posts, wp_options).
IMPORTANT: Always use a plugin to interact with the database
If you want to learn more, go to the Developer LP

- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lessons

**Comment by westnz** [comment]
Thank you for the great work on the [script](https://docs.google.com/document/d/1VRuwr7m-qGectik5hTsECgI9Z-8BKhgL0uYSFvihvrs/edit#heading=h.zcd4wz22xiv) @ironnysh.

**Comment by jonathanbossenger** [comment]
I have requested access to the script, if its ok I'd like to give it a quick review.

**Comment by ironnysh** [comment]
More than okay! :-) It's open for everyone now

**Comment by jonathanbossenger** [comment]
Thanks @ironnysh. I've left some suggestions on the doc, feel free to let me know if you have any questions, or if you disagree with them.

**Comment by ironnysh** [comment]
Thanks, @jonathanbossenger! Much appreciated 😇

**Comment by ironnysh** [comment]
> left some suggestions on the doc

Great points, @jonathanbossenger, thank you.

— @westnz, I’ve updated the script.

**Comment by westnz** [comment]
Thank you very much, Jonathan! ⭐

**Comment by westnz** [comment]
I started working on this yesterday, so this is perfect timing.

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/0c994c1d-713d-4954-bf25-3bc4465ebe79

**Comment by digitalchild** [comment]
A nice overview Wes. 

1:43 - A database isn't really just a file. It is a service that is an organized collection of structured data that is included with your hosting package. 

## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0]

**Comment by westnz** [comment]
Thanks for reviewing @digitalchild

**Comment by rfluethi** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Excellent and informative video, as always.

**Comment by westnz** [comment]
Thank you @rfluethi! 👍

**Comment by Soir7** [comment]
- [+] Learning outcomes/objectives are clear.
- [+] Technical concepts introduced in the content are accurate.
- [+] The speed of demonstrations are easy to follow.
- [+] The narration audio matches what is shown visually.
- [+] Spelling and grammar are correct. - **DOES THIS APPLY TO TRANSCRIPT (WHEN PROVIDED)?**
- [+] Sound quality is consistent throughout the video.
- [+] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and
- [ +] (Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

@westnz .... 

- Your clear and upbeat delivery ease the learning journey.  
- Nice how you modify your voice to stress key points.
- Impactful use of stop sign as a full page image emphasizes the 'look but don't touch' message of avoiding direct database edits.
- Stated importance of deactivating DB plug @ end of use.
- Demonstrated locating DB name in WP/site health.

Thank you.

**Comment by westnz** [comment]
Thank you very much @Soir7!

**Comment by BSICTVince** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by westnz** [comment]
Hi @BSICTVince 
Thank you for reviewing. I noticed you didn't select the "Technical concepts introduced in the content are accurate." Is it related to what Jamie mentioned, or is there something else you want to highlight?

**Comment by westnz** [comment]
//published
