### ISSUE TITLE
The building blocks of WordPress templates

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2312]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title:  How blocks are made
- Topic description: 
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced 

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lessons

**Comment by ironnysh** [comment]
/ assign

**Comment by ironnysh** [comment]
// assign

**Comment by ironnysh** [comment]
//assign

**Comment by ironnysh** [comment]
Hi @westnz, the draft is ready for feedback [in this doc](https://docs.google.com/document/d/1K37ovTbR35fwrS_oa6Zumle84EBdesrB9Gfgukywhj0/edit?usp=sharing).

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/1e1332a6-59ea-4034-9e12-4e4d41cc6164

**Comment by jonathanbossenger** [comment]
Hi folks.

I'm sorry to chime in here so late; I'm wondering if the title of this lesson makes sense in respect to its content? 

When I see "How blocks are made" I think "making a block". So, I expect to see a lesson on how blocks (maybe core blocks, maybe custom blocs) are developed. 

Looking at the content of this lesson, a more suitable title might be "The building blocks of WordPress templates" (if you'll pardon the intentional pun), "What makes up a template," or "How templates are made," as it dives into what makes up a template —WordPress blocks, their structure, and how they work within the scope of a template. 

I hope this makes sense. Let me know if you have any questions.

**Comment by westnz** [comment]
Thanks @jonathanbossenger 

That's helpful feedback!!

**Comment by digitalchild** [comment]
I agree with @jonathanbossenger in regard to the title. This is more about how a template/structure is and now exactly how blocks are made. I too thought thig was a developer tutorial when I saw the title and thought Jonothan had posted it in the channel. 

The content is good discounting the title.

**Comment by ironnysh** [comment]
Thanks @jonathanbossenger and @digitalchild. Super valuable feedback 💯

**The building blocks of WordPress templates** is my favorite alternative.

**Comment by teuila-mau** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial:

- zooming into code is helpful
- referencing other lessons makes me want to learn more which is great
- 0:00: Does the new title ("The building blocks of WordPress templates") need to be reflected in the beginning of the video? If so, the thumbnail should be updated. You can find a new thumbnail [here](https://drive.google.com/file/d/1RMXBN7AjsKuI8V2NBXDB3MLTP2vjdOQS/view?usp=drive_link).
- 6:01: When it says "Paste the code from the transcript", will this be found in the transcript? Or, should this say "Paste the code from the previous post" or something similar?

**Comment by westnz** [comment]
Thank you for the review!!

> 0:00: Does the new title ("The building blocks of WordPress templates") need to be reflected in the beginning of the video? If so, the thumbnail should be updated.

I will update the new title + thumbnail after the review has been completed 👍 

> 6:01: When it says "Paste the code from the transcript", will this be found in the transcript? Or, should this say "Paste the code from the previous post" or something similar?

The code will be below the video and above the transcript. Agreed, will change the wording.

**Comment by RoelofWobben** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [X ] Learning outcomes/objectives are clear.
- [X ] Technical concepts introduced in the content are accurate.
- [X ] The speed of demonstrations are easy to follow.
- [X ] The narration audio matches what is shown visually.
- [X ] Spelling and grammar are correct.
- [ X] Sound quality is consistent throughout the video.
- [ X]  Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and - [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ X] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

I like it that it is a slow and that for html, css is reffered to a place where you can find more info.
Also I like is that a example is shown where things are changed. 

What I miss is a challenge you can do on your own

**Comment by westnz** [comment]
Thanks for the review @RoelofWobben 
When the learning pathway is published, the practical activity or challenge will be added below the lesson transcript.

**Comment by Soir7** [comment]
Confirmed following:
[X ] Learning outcomes/objectives are clear.
[X ] Technical concepts introduced in the content are accurate.
[X ] The speed of demonstrations are easy to follow.
[X ] The narration audio matches what is shown visually.
[X ] Spelling and grammar are correct.
[X] Sound quality is consistent throughout the video.
[X] Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and - [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
[o] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

@westnz, as always, love your upbeat, friendly, 'come in the water is fine' tone. :+>

Comments from a WP novice perspective:

1. **Revised title** - 'Building blocks of WP templates'...in WP, 'blocks' seems to be more of a noun connoting specific 'item' (singular).  'Building blocks' implies verb/action of using several pieces needed to build a template. 
2. **2.03** - Invitation to pause video to explore code in WP playground or 'any other code editor' is a nice touch. 
3. **5.32** - At the point where a person new to HTML may be feeling overwhelmed....helpful and practical how you have specifically indicated learning pathway as a place to expand learner's knowledge of HTML/WP.

The end.   :+>

**Comment by westnz** [comment]
Thank you for reviewing @Soir7!

**Comment by westnz** [comment]
//published
