### ISSUE TITLE
Managing a multisite network

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2315]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title:  Managing a multisite network
- Topic description: 
How to manage your network (sites, plugins, themes, users, etc.)?
Use [the documentation](https://developer.wordpress.org/advanced-administration/multisite/admin/) as a script.
If you want to learn more, go to the Developer LP
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced

# Learning Objectives

# Related Resources and Other Notes

**Comment by digitalchild** [comment]
//lessons

**Comment by jonathanbossenger** [comment]
I created a [similar lesson](https://github.com/WordPress/Learn/issues/2374) for the beginner developer module on multisite. It might save time by reusing that lesson here.

**Comment by westnz** [comment]
Thanks @jonathanbossenger 
This is fantastic! We are going to use this lesson as part of the Advanced user learning pathway, but we are going to re-record "Setting up a WordPress multisite" to make it more user-focused. 

At this stage, we can't use the same lesson in two different courses, so I will have to duplicate it in Sensei. What do you suggest? Should I select "Exclude this lesson from the archive" to avoid conflict?

**Comment by jonathanbossenger** [comment]
This is all new ground for us @westnz, so I honestly don't know myself :smile: 

I think that excluding it from the archive should work, so let's try that out and see what happens.

**Comment by westnz** [comment]
//published
