### ISSUE TITLE
Feedback - Error with code in course when using CS Code

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2325]
## Type of feedback

//content

## Description

The error occurred within the **[Introduction to Block Development: Build your first custom block](https://learn.wordpress.org/course/introduction-to-block-development-build-your-first-custom-block/)** course. However, the specific lesson is uncertain.

(first message)
>I found an error being reported in src/block.json stating that an "object" was expected with the word "true" underlined. This was using VS Code. After some investigation, it appeared that this can be a VS Code error rather than a json code error and is related to schema.
>
>I found that deleting the first line " "$schema": "https://schemas.wp.org/trunk/block.json", in src/block.json removed the error and allowed the multi-block to re-appear in the blocks list. Before this, it had disappeared and was reporting it did not exist even though it was displayed and activated as a plugin.
>
>Just a further item early on in the lessons the tag is removed and replaced with a but much of the code written in subsequent lessons still has the displayed instead of the so if you copy the code you end up replacing the out of date HTML.

(second message)
>The course was " Introduction to Block Development: Build your first custom block" which was a multi-column block. As far as I can now recall everything worked until I reached the point of adding some of the column attributes in the sidebar to offer drop-down options to column variations such as spacing, width, gap, etc.
>
>I cannot remember which one of these caused the block to appear with an error message and then disappear altogether and the error " in src/block.json stating that an "object" was expected with the word "true" underlined" then displayed in VScode. I investigated that error and found it appeared to relate to VScode and Schema so as a test I removed the first line of code in VScode referring to schema and the error disappeared enabling me to continue with the lessons and complete the block.

## Other information (optional)

_This feedback was provided in ticket 173706._

**Comment by jonathanbossenger** [comment]
This course needs to be deprecated. Tracking course deprecations in #2868
