### ISSUE TITLE
Bengali translation for Tutorial "Customizer Taglines (Classic and Hybrid Themes)"

### ISSUE THREAD

**Issue by voboghure-dev** [WordPress/Learn#2326]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/customizer-taglines/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/440
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @devmuhib009 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by voboghure-dev** [comment]
Hi :wave: I just completed the translation and here is the [google docs link](https://docs.google.com/document/d/18VVS8SwWvBaTpN6rllmuKfFPzVvqyJe_0joie1VFacs/edit?usp=sharing), please review and let me know your thoughts.
Thanks.

**Comment by devmuhib009** [comment]
Please modify below changes and we are ready to go.

> থিম কাস্টমাইজার ব্যাবহার করে ট্যাগলাইন এড অথবা এডিট
 ট্যাগলাইন এ্যাড অথবা এডিট করতে থিম কাস্টমাইজার ব্যবহার করা
 
 > সকল ওয়েবসাইটের কি ট্যাগলাইন প্রোয়েজন আছে?
 সকল ওয়েবসাইটের কি ট্যাগলাইন প্রয়োজন?
 
 > একটি কার্যকরী ট্যাগলাইন দেখতে শুনতে কেমন হবে?
 একটি কার্যকরী ট্যাগলাইন দেখতে এবং শুনতে কেমন হবে?
 
 > বিভিন্ন থিম কি কাস্টমাইজারের কার্যক্রমে প্রভাব ফেলবে?
 আপনি যে ধরণের থিম ব্যবহার করছেন, সেটি কি কাস্টমাইজারের কার্যক্রমে প্রভাব ফেলবে?

> হাই, ওয়ার্ডপ্রেস শিখতে স্বাগতম।
হাই এবং লার্ন ওয়ার্ডপ্রেসে আপনাকে স্বাগতম।

>যায়গা, নিশ্চই, ব্যাস্ত, চলুল, ফ্রন্টএন্ড এ, 
জায়গা, নিশ্চয়ই, ব্যস্ত, চলুন, ফ্রন্টন্ডে, 

>তাই কিছু থিমের অভিজ্ঞতা ডিফল্ট অভিজ্ঞতা থেকে ভিন্ন অভিজ্ঞতাহতে পারে।
তাই কিছু থিমের অভিজ্ঞতা ডিফল্ট অভিজ্ঞতা থেকে ভিন্ন হতে পারে।

**Comment by voboghure-dev** [comment]
@devmuhib009, thank you for bringing these issues to my attention. I have made the necessary fixes based on your suggestions. Could you kindly take a look and let me know if everything is in order and what should I do next?
Thanks

**Comment by devmuhib009** [comment]
Thanks for modifying the corrections, I've added you to learn WordPress website, you will receive an email shortly. Please confirm the email and update me here.

**Comment by voboghure-dev** [comment]
I got the invitation and joined the learn WordPress website.

**Comment by devmuhib009** [comment]
Please draft the tutorial and complete step 5 to 7. 
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials

**Comment by devmuhib009** [comment]
Tutorial published here: https://learn.wordpress.org/tutorial/bn-customizer-taglines/
Thanks for your hard work. ❤️

**Comment by voboghure-dev** [comment]
Thanks @devmuhib009 
It would never happened without your guidance.
