### ISSUE TITLE
Meeting Agenda March 14, 2024

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#2327]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- March 14 – [freewebmentor](https://profiles.wordpress.org/freewebmentor/)
- March 21 – [@voboghure](https://profiles.wordpress.org/voboghure/)
- March 28 – [@pooja9712](https://profiles.wordpress.org/pooja9712/)
- April 4 – Need volunteer

**2. Looking for feedback**

- [Discussion: possible collaboration to transform learning pathways to Skill Trees](https://make.wordpress.org/training/2024/03/07/discussion-possible-collaboration-to-transform-learning-pathways-to-skill-trees/)

**3. Looking for volunteers**

- We’re looking for volunteers to map out a Contributor pathway for the [Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) project. Leave a note in this thread if you're interested.
- The team is currently gathering a list of requirements for https://github.com/WordPress/Learn/issues/2231 and we invite folks to share their input directly on the GitHub issue.

**4. Other news**

- Thinking to speak about the Training Team or Learn WordPress at WordCamp Us? We are happy to mentor you! 
- Wes and Jonathan will be hosting two more content creator office hours in March. The first session is scheduled for today at 14:00 UTC ([meeting link](https://us02web.zoom.us/j/83146869068?pwd=bE5rQnFnTGozMHhHVDN5eEdzaW5rQT09)), and the second will be scheduled during the week of the 25th of March.

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
  - We currently have 14 issues requiring review.

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
  - We currently have 26 issues awaiting validation.

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
  - We have 31 issues requiring vetting.

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
  - We have 15 issues that are open to be worked on.

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
  - We have 16 issues awaiting fixes-- come an dive in :-)

## 3. Contribution Acknowledgement

- Props: 
  - Jamie & Wes for leading the WCAsia TT table
  - Chetan & Ben for owning the online portion of WCAsia Contributor Day
  - Ronny for publishing the  [Contributor Spotlight on Oneal Rosero](https://make.wordpress.org/training/2024/03/04/contributor-spotlight-oneal-rosero/)

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)

## 5. Open Discussions

- Learn WordPress Content Deprecation plan

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
With Dev-squad triage now taking place every two weeks, I will remove the triage update section from the agenda on alternate weeks.

**Comment by devmuhib009** [comment]
Meeting recap published here: https://make.wordpress.org/training/2024/03/19/training-team-meeting-recap-14th-march-2024/
