### ISSUE TITLE
Hindi translation for "How to Test WordPress Beta Release?"

### ISSUE THREAD

**Issue by speedyprem** [WordPress/Learn#2330]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/how-to-test-wordpress-beta-release/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by speedyprem** [comment]
Here is the translation content for review: https://docs.google.com/document/d/151DwbzwcefFPnrF0SLdg1L7Ej5loEVf_OK_gP1dw0D0/

**Comment by Roshan-narola** [comment]
@devmuhib009 I'll review it.

**Comment by devmuhib009** [comment]
Thanks, I am assigning you as reviewer.

**Comment by Roshan-narola** [comment]
@devmuhib009 it's look good to go for further process.

**Comment by devmuhib009** [comment]
@Roshan-narola thanks for reviewing. @speedyprem please draft the post.

**Comment by speedyprem** [comment]
@devmuhib009 I have drafted the tutorial here: https://learn.wordpress.org/wp-admin/post.php?post=140691&action=edit

**Comment by devmuhib009** [comment]
Tutorial Published Here: https://learn.wordpress.org/tutorial/hi-how-to-test-wordpress-beta-release/
Thanks
