### ISSUE TITLE
French translation for Tutorial "How to Test WordPress Beta Release?"

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Learn#2332]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/how-to-test-wordpress-beta-release/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/2269
- Language you'll be translating to: french
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: The translation is open for comments on a FramaPad file https://mypads2.framapad.org/mypads/?/mypads/group/learn-gd35829fb/pad/view/how-to-test-wordpress-beta-release-w12rcu9zj

**Comment by jennydupuy** [comment]
The translation is done. Proofreading/review requested.

**Comment by jennydupuy** [comment]
Thank to @beryl-dlg to review this translation.

**Comment by beryl-dlg** [comment]
> The translation is done. Proofreading/review requested.

Review done

**Comment by jennydupuy** [comment]
The tutorial is published
https://learn.wordpress.org/tutorial/fr-how-to-test-wordpress-beta-release/

**Comment by jennydupuy** [comment]
The subtitles were upload.
Translation completed!
