### ISSUE TITLE
French translation for Tutorial "Building a home page with a block theme"

### ISSUE THREAD

**Issue by quentin-ld** [WordPress/Learn#2333]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/building-a-home-page-with-a-block-theme/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/788
- Language you'll be translating to: french
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username:  @jennydupuy 
- Other info: The translation is open for comments on a FramaPad file
[https://mypads2.framapad.org/p/building-a-home-page-with-a-block-theme-if1moz9x4](https://mypads2.framapad.org/p/building-a-home-page-with-a-block-theme-if1moz9x4)

**Comment by jennydupuy** [comment]
Congratulations @quentin-ld  for this first contribution to Learn.
Translation finished and reviewed.
Content created on Learn.
[https://learn.wordpress.org/tutorial/fr-building-a-home-page-with-a-block-theme/](https://learn.wordpress.org/tutorial/fr-building-a-home-page-with-a-block-theme/)
Video subtitles are in progress...

**Comment by jennydupuy** [comment]
I made some changes in the subtitles file. You can submit this file on wordpress.tv, please specify the language fr.

[subtitles-fr.zip](https://github.com/WordPress/Learn/files/14627662/subtitles-fr.zip)

**Comment by jennydupuy** [comment]
Subtitles are approved and on line!
