### ISSUE TITLE
Feedback - continue to next lesson button in quiz page is clickable only in the area contains the text.

### ISSUE THREAD

**Issue by mujuonly** [WordPress/Learn#2335]
## Description
**continue to next lesson** button in quiz page is clickable only in the area contains the text.

## Step-by-step reproduction instructions (optional)

1. Go to '...' https://learn.wordpress.org/quiz/venue-and-date-2-2/
2. After completing, you will see a button to next lesson
3. The button is linked in the area containing the text only

## Screenshots or screen recording (optional)

![go-to-next](https://github.com/WordPress/Learn/assets/459367/3052d76b-5ddf-4fcf-95b5-5bcc50c6a485)

**Comment by kaitohm** [comment]
//dev

**Comment by mujuonly** [comment]
Either we can make it this way by removing the "wp-block-button" class for the parent div or expand the anchor tag with full width.
<img width="1108" alt="image" src="https://github.com/WordPress/Learn/assets/459367/19859705-31ae-427e-bd91-db207af48ab4">

**Comment by jonathanbossenger** [comment]
Hi @mujuonly thank you for logging this issue.

I'm going to ask @Imran92 from Sensei if he can help us shed some light on the issue.

This appears to happen only on the Continue to next lesson at the bottom of the quiz, and not the one at the top.

**Comment by adamwoodnz** [comment]
No longer an issue, with the launch of the 2024 block theme
