### ISSUE TITLE
Tutorial: Exploring WordPress 6.5

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2336]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Tutorial
- Content title: Exploring WordPress 6.5
- Topic description: Exploring new features
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

Review new features that will land with 6.5. 

# Related Resources and Other Notes

### Automation Code

//tutorial

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/6a1e681d-fc3e-400d-ba8d-94c0786717e3

**Comment by unprintedch** [comment]
This comment won't help much. 
I think it is great, the pace, the tone and the example are clear.
Nice Job.

**Comment by westnz** [comment]
Appreciate the feedback and vote of confidence @unprintedch 👍

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Spot on! :-)

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/exploring-wordpress-6-5/
