### ISSUE TITLE
Test TranslatePress

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2339]
Front-end requirements:

- Language selector does not show as country flags. (Many countries speak multiple languages, so describing a language with a flag should be avoided.)
- Languages can be changed without needing to log in to one's WordPress.org account.
- Once a language is selected, it is applied globally.
- Content of the selected language is shown above non-translated content.
- English content is still shown where translations don't exist.

Back-end requirements:

- Translators do not have permission to create or publish new content.
- Translators have permission to both translate any content, and review content translated by others.
- A flow can be implemented where translations must be approved (reviewed) before published.
- Sensei content types can be translated in the same way as native post types.
- Taxonomies can be translated.
- Translated content is indexed and searchable by Jetpack Search.

**Comment by sareiodata** [comment]
Hi Jonathan, 

Cristian Antohe, co-founder of TranslatePress here :) 

If you have questions or want a paid version to test out (the free version doesn't allow for more then 1 language) I would be happy to help. (we can create a perpetual license, so you get updates moving forward to the paid version). The paid version is just an addon. 

Some notes right of the bat regarding what doesn't work: 
- the one thing that we don't have is "A flow where translations must be approved (reviewed) before published"
- translated search is indexed and searchable by Jetpack Search might not work. Normal WordPress search works, because we're hooking into the WP_Query and we have an index with translated content we serve from. 
- you'll probably want to limit translation to the post content. For that you just need to add the CSS id's or classes of the other elements like header, sidebar, footer on the exclude selectors list in the Advanced settings. 

Best Regards!

**Comment by jonathanbossenger** [comment]
Hi @sareiodata thanks for the feedback. I'll take this into account during our testing.

**Comment by jonathanbossenger** [comment]
@sareiodata what would be really helpful here is a summary of which requirements (listed in the issue description above)  TranslatePress offers in either the free or the paid version.

If it's added to this issue as a check list (in a similar way as has been [done for WPML](https://github.com/WordPress/Learn/issues/2338#issuecomment-2010974864), that would help me create a comparison table of the three options we're currently looking at.

**Comment by sareiodata** [comment]
Sure thing. 

Front-end: 
- [x] Language selector does not show as country flags. (Many countries speak multiple languages, so describing a language with a flag should be avoided.)
- [x] Languages can be changed without needing to log in to one's WordPress.org account. 
- [x] Once a language is selected, it is applied globally.
- [ ] Content of the selected language is shown above non-translated content. - **I don't understand the requirement.** 
- [x] English content is still shown where translations don't exist.

Back-end: 

- [x] Translators do not have permission to create or publish new content - yes, available in the paid version.
- [x] Translators have permission to both translate any content, and review content translated by others. Yes, a translator has access to all secondary languages, but there are no logs as to who translated what. 
- [x] Translators do not have permission to create or publish new content.
- [ ] A flow can be implemented where translations must be approved (reviewed) before published. - This feature does not exist. 
- [x] Sensei content types can be translated in the same way as native post types.
- [x] Taxonomies can be translated.
- [ ] Translated content is indexed and searchable by Jetpack Search. - I haven't tested this myself. If it's a external index like the Google search that's found on other parts of wordpress.org, it might work. If it relies on WordPress internally for querying content and sending it to Jetpack servers, it might not as TranslatePress doesn't duplicate pages. 

Notes: 
- maybe you can move the review of translated content internally like a process to be followed (Translator A finishes translation on an article then manually pings Editor B for review; while waiting for review, please note the translation will be live)
- the main advantage for TranslatePress is how Translators interact with the website. Mainly point towards a paragraph, click, translate, save. They never have to see or work with the Editor. This might, or might not be a good thing depending on the flow you're looking for. 

If there are questions, please let me know!

**Comment by jonathanbossenger** [comment]
@sareiodata thank you so much. I'll feed this back to the team at the next meeting, and also get some answers to your questions.

**Comment by kathrynwp** [comment]
@jonathanbossenger Noting that in #2445 @adamwoodnz upgraded TranslatePress to 2.8.3 and re-enabled it on the [test site](https://learn.wordpress.org/test/). This should resolve the SQL issues that were occurring – so it's ready for testing again!

**Comment by jonathanbossenger** [comment]
Hi @sareiodata I'm going to be picking up the testing of TranslatePress this week.

>If you have questions or want a paid version to test out (the free version doesn't allow for more then 1 language) I would be happy to help. (we can create a perpetual license, so you get updates moving forward to the paid version). The paid version is just an addon.


Would it be possible to register this license to the learn@wordpress.org email address, which is shared with the administrators of the WordPress training team? That way I can test the pro features on the test site. 

Thanks

**Comment by sebastienserre** [comment]
Hello @jonathanbossenger 
As a part of the Polylang team, I think test with another plugin should be a great Idea to compare what is the best solution.
Le me know if you need anything about [Polylang](https://wordpress.org/plugins/polylang/).

**Comment by jonathanbossenger** [comment]
Hi @sebastienserre 

You will find the decision to test TranslatePress [in this discussion from earlier this year](https://github.com/WordPress/Learn/issues/2231#issuecomment-2024196003). 

May I suggest you add your input on that issue? I'm merely testing TranslatePress according to the team's decision at the end of March.

**Comment by sareiodata** [comment]
Hi @jonathanbossenger , 

A license already exists. You can access it by logging in using learn@wordpress.org over at https://translatepress.com/account/ 

You can do a password reset. If this is to complicated (you don't have access to the reset email, etc.), please let me know and we'll figure out a solution. 

Some notes on the license: 
* the only way to activate the license is on the main blog of the network. There, TP needs to be active (even if there are no extra languages and everything is disabled)
* lack of a license only disables automatic updates for the Pro version (a standalone plugin)
* lack of a license will show a notification in the backend from what I recall. If there aren't filters there to disabled it, let us know, we'll see how we can make that happen.

**Comment by jonathanbossenger** [comment]
> lack of a license only disables automatic updates for the Pro version (a standalone plugin)

Ah, got it, thank you. Can I assume this is the TranslatePress - Developer plugin? I see it is already installed on our test site, just not activated.

**Comment by sareiodata** [comment]
Yes, it's the TranslatePress - Developer plugin.

**Comment by jonathanbossenger** [comment]
@sareiodata, thanks, I was able to install the developer plugin and test out the Translator Accounts feature. I have a couple of questions about that feature:

- Can we set a per language per translator? For example, if I am an Afrikaans translator, I am only allowed the option to translate to Afrikaans. 
- Is it possible to translate an entire page in the page/post editor, or does the plugin only offer the Translation Editor UI
- Once strings have been submitted, is there a way to have them approved before they are available?

**Comment by sareiodata** [comment]
@jonathanbossenger 

- language per translator: we don't have this feature, but it's fairly simple to implement. It's something we can push an update for it on our end. 
- translate entire page: No. We only support the Translation Editor UI. That's how TP works, translating string by string. 
- approve strings: we don't have this feature. This is an interesting feature, but it's not simple to implement. I don't think this is feasible to implement on our end any time soon as it requires both data storage changes & UI changes.

**Comment by jonathanbossenger** [comment]
@sareiodata I would like to thank you for your support in our testing process. At this time, we have decided to move forward with #2284, with the main reason being the ability to translate an entire page or post in the editor, as this will match our existing workflows better.
