### ISSUE TITLE
Meeting Agenda March 21 , 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2341]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @lada7042 ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- March 21 – [@voboghure](https://profiles.wordpress.org/voboghure/)
- March 28 – [@pooja9712](https://profiles.wordpress.org/pooja9712/)
- April 4 – [@Sumit Singh](https://profiles.wordpress.org/sumitsingh/)
- April 11- Need volunteer

**2. Looking for feedback**

- [Discussion: possible collaboration to transform learning pathways to Skill Trees](https://make.wordpress.org/training/2024/03/07/discussion-possible-collaboration-to-transform-learning-pathways-to-skill-trees/) — Please leave your thoughts in the comments on this post by Friday 22 March, 2024.

**3. Looking for volunteers**

- Learning Pathways
We’re looking for volunteers to map out a Contributor pathway

**4. Other news**

- Interesting discussion with Josepha today in the [marketing Slack channel](https://wordpress.slack.com/archives/C0GKJ7TFA/p1710974238641199) around this post [Making a WordPress Media Corps](https://make.wordpress.org/marketing/2024/03/20/making-a-wordpress-media-corps/)
- [WordPress 6.5 RC3](https://wordpress.org/news/2024/03/wordpress-6-5-release-candidate-3/) released March 19, 2024

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
   - We currently have 16 issues requiring review.

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
   - We currently have 27 issues awaiting validation.

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
   - We have 31 issues requiring vetting.

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
   - We have 15 issues that are open to be worked on.

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
   - We have 16 issues awaiting fixes-- come and dive in :-)

## 3. Contribution Acknowledgement

- Badges awarded: 
-- [@zoonini](https://wordpress.slack.com/team/U02S3F8EK) Kathryn Presner- Training Contributor
- Props: 

## 4. Project updates

- The team is currently gathering a list of requirements for https://github.com/WordPress/Learn/issues/2231 and we invite folks to share their input directly on the GitHub issue.
   -  Several team members have been testing. 
     - [WPML does not have a free version](https://github.com/WordPress/Learn/issues/2231#issuecomment-2007182063). We will need to decide if this means we don't test this plugin, or if we try and contact the developers and ask for a copy. 
     - @cynthianorman has been testing Polylang, and you can find her testing results in the [relevant GitHub issue](https://github.com/WordPress/Learn/issues/2284)

## 5. Faculty Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
Testing translation plugins updates:

- [WPML does not have a free version](https://github.com/WordPress/Learn/issues/2231#issuecomment-2007182063). We will need to decide if this means we don't test this plugin, or if we try and contact the developers and ask for a copy. 
- @cynthianorman has been testing Polylang, and you can find her testing results in the [relevant GitHub issue](https://github.com/WordPress/Learn/issues/2284)

**Comment by ghost** [comment]
Meeting recaps by [@voboghure](https://profiles.wordpress.org/voboghure/)-  https://make.wordpress.org/training/2024/03/27/training-team-meeting-recap-21st-march-2024/
