### ISSUE TITLE
The commonly used Internationalization functions

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2342]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: The commonly used Internationalization Functions
- Topic description: A short introduction to the most commonly used Internationalization functions in both PHP and JavaScript
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Identify the most commonly used Internationalization functions
- Implement these functions in both PHP and JavaScript

# Related Resources and Other Notes
- https://developer.wordpress.org/apis/internationalization/
- https://learn.wordpress.org/tutorial/common-apis-internationalization/

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/10-introduction-to-internationalization.md/02-the-commonly-used-internationalization-functions.md

**Comment by jonathanbossenger** [comment]
Video for review:

https://github.com/WordPress/Learn/assets/180629/009bc3f0-cd04-4214-880c-f645d326f928

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Cool demo of the available functions.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/05/11/the-commonly-used-internationalization-functions/

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/the-commonly-used-internationalization-functions/

**Comment by jonathanbossenger** [comment]
//publish
