### ISSUE TITLE
Hindi translation for "Exploring category templates with block themes"

### ISSUE THREAD

**Issue by speedyprem** [WordPress/Learn#2348]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/exploring-category-templates-with-block-themes/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Hindi
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by speedyprem** [comment]
Here is the translated content: https://docs.google.com/document/d/151DwbzwcefFPnrF0SLdg1L7Ej5loEVf_OK_gP1dw0D0/

**Comment by dextorlobo** [comment]
Looks good, can proceed further.

**Comment by speedyprem** [comment]
@devmuhib009 I have drafted the tutorial here: https://learn.wordpress.org/wp-admin/post.php?post=170689&action=edit

**Comment by devmuhib009** [comment]
Thanks a lot. Tutorial published here: https://learn.wordpress.org/tutorial/gu-exploring-category-templates-with-block-themes/
