### ISSUE TITLE
Tips and tricks for creating patterns

### ISSUE THREAD

**Issue by annezazu** [WordPress/Learn#2349]
# Details

- Topic description: Learn some tips and tricks to create beautiful, high quality patterns and the details that make them stand out. 
- Audience (User, Developer, Designer, Contributor, etc.): developers, designers
- Learning objectives (What will the learner be able to do as a result of this content?): learn how to create high quality patterns
- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson (I think) or tutorial
- WordPress version (optional): 6.5 for the latest & greatest
- Will you be creating this content? (Yes or No): No

# Related Resources

https://developer.wordpress.org/news/2024/03/19/pattern-design-tips-and-tricks-for-developers/

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by annezazu** [comment]
# Vetting Checklist for SMEs
- Priority: medium, patterns are a big part of the current world of WordPress and we should help folks have best practices. 
- Any other feedback: I think much of this could be reused from Bea's great developer blog post!

**Comment by cynthianorman** [comment]
@annezazu I will be sure to take a close look when creating this lesson https://github.com/WordPress/Learn/issues/2274

**Comment by jonathanbossenger** [comment]
@annezazu as @cynthianorman has pointed out, we already have a lesson on Patterns planned for the theme developer learning pathway. Could Cynthia ping you on that lesson for a review once she has completed it?

**Comment by annezazu** [comment]
Yes! Closing this out. Apologies for the delay. Ping away when you need a review <3
