### ISSUE TITLE
Use "Subtitles" instead of "Captions"

### ISSUE THREAD

**Issue by naokomc** [WordPress/Learn#235]
Depending on the effort required, it's not a super high priority item – but I suggest an improvement to use "subtitles" terminology instead of "captions" to refer to the overlay transcription or its translation.

**Reason:**
WordPress.tv uses "subtitles" on the site UI and [documentation](https://wordpress.tv/using-amara-org-to-caption-or-subtitle-a-wordpress-tv-video/), so when we refer to the same thing as "captions", it can get confusing. We sometimes link to WPTV documentation from Learn WP [handbook](https://learn.wordpress.org/meta/handbook/workshops/workshop-captions-and-transcripts/), and the inconsistency makes it hard to understand the process.

**Comment by hlashbrooke** [comment]
Agreed - I can make the edits in the handbook, but the other areas are in template files and such that require dev changes.

**Comment by iamchetanp** [comment]
#255 PR created.
