### ISSUE TITLE
Feedback - Gujrati Local Content Linked to Docs File

### ISSUE THREAD

**Issue by devmuhib009** [WordPress/Learn#2351]
## Type of feedback
Content not linked to correct page. 

## Description

[Gujrati translation](https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/#translation-review) is not linked to correct page. It's linked on Google doc file. 
## Screenshots or screen recording (optional)

![IMG_20240326_224212](https://github.com/WordPress/Learn/assets/142894870/46984b4f-3d4a-40a3-bb8c-ad4345d0d7d2)

**Comment by digitalchild** [comment]
The current google doc needs to be added to the Gujarati site so that we can provide the correct link.  

Translation available here. 
https://docs.google.com/document/d/1LbBG02xzcV4XMtBbK5BYYjMMuPgP7EoaULYW402aT_g/edit?usp=sharing

**Comment by devmuhib009** [comment]
@bsanevans need your insight about this issue. [Original Ticket](https://github.com/WordPress/Learn/issues/1222).

**Comment by kaitohm** [comment]
This is actually working as expected. There is no Gujarati site. So, for locales where these is no Rosetta site, we're simply linking to the Google docs. 🙂
