### ISSUE TITLE
Feedback - small design changes on questions and radio

### ISSUE THREAD

**Issue by unprintedch** [WordPress/Learn#2353]
I have noticed some small adjustements that can be made to the "learn website"

## Description

# Learn – bug reporting

In my local versions i have some small bugs to report

The number are doubled and the radio looks broken
![Capture d’écran 2024-03-28 à 12 32 10](https://github.com/WordPress/Learn/assets/2622001/1d0f0932-839a-422b-bba7-c5c709998605)
The whole colored button has a cursor:pointer but only the <a> is clickable.
![Capture d’écran 2024-03-28 à 09 19 16](https://github.com/WordPress/Learn/assets/2622001/1300b958-49f7-406a-8473-5d3aaf01e932)

When answering a question with the reset button is in the center it feels strange
![Capture d’écran 2024-03-28 à 12 21 11](https://github.com/WordPress/Learn/assets/2622001/50d304e9-4d49-4298-8d3c-fa98a3675a67)
![Capture d’écran 2024-03-28 à 12 21 20](https://github.com/WordPress/Learn/assets/2622001/98dcf003-4fae-4403-9ecb-930776316f48)

Radio button are not the same in every questions (quiz or not):
In a quiz associated with a lesson
![Capture d’écran 2024-03-28 à 12 32 10](https://github.com/WordPress/Learn/assets/2622001/f136392f-d230-4c6c-ac8a-f707f15da32a)
In a question added directy in the lesson
![Capture d’écran 2024-03-28 à 12 32 23](https://github.com/WordPress/Learn/assets/2622001/3e86851e-dbca-43a9-92bd-7240f698566a)

And I think that  the message box looks too similar to the button.

I would do something like this:
![Capture résultat leçon 2, 28 mars 2024](https://github.com/WordPress/Learn/assets/2622001/35c07a99-2c9b-45fe-b5a5-54d4548af015)
![Capture leçon 2, 28 mars 2024](https://github.com/WordPress/Learn/assets/2622001/b5aa3181-a965-4f39-b480-c1171a58d147)

Also added some padding and separators, but that is probably too much since they can be added in the block editor.

That are smalls things... 

It is my first so feel free to correct me if i can do something better

**Comment by unprintedch** [comment]
I also made a branch in my fork with some actual fixes.
I know it is too soon since there was no triage, but i wanted to do the all process after watching the 2 great introduction workshops of @jonathanbossenger.

[Here it is](https://github.com/unprintedch/Learn/tree/2353---question-layout-and-radio-button)

I would really like feedbacks on what I have done.

**Comment by unprintedch** [comment]
And I remember that there was a command to self assign the issue... But can't find it!

**Comment by unprintedch** [comment]
This will also fix that [#2335](https://github.com/WordPress/Learn/issues/2335)

**Comment by adamwoodnz** [comment]
No longer an issue, with the launch of the 2024 block theme.
