### ISSUE TITLE
Feedback - Outdated Content Reported on Help Scout

### ISSUE THREAD

**Issue by devmuhib009** [WordPress/Learn#2355]
## Type of feedback

Outdated Content.
## Description

Unlike previous courses I took; this course does not go as smooth. At above URL, at Step 4: even thoug I copy and paste exactly what is presented as example(s) and overall summary (at the end of page), the code doesn't work as expected (or presented in screenshots).
## Step-by-step reproduction instructions (optional)

https://learn.wordpress.org/lesson/retrieving-wordpress-data-records/
## Other information (optional)

This ticket is created based on Help Scout Ticket #175218

**Comment by jonathanbossenger** [comment]
Closing in favour of #2968
