### ISSUE TITLE
what now

### ISSUE THREAD

**Issue by nigel3** [WordPress/Learn#2358]
# Details

- Topic description: 
- Audience (User, Developer, Designer, Contributor, etc.): 
- Learning objectives (What will the learner be able to do as a result of this content?): 
- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): 
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by nigel3** [comment]
What Now ?

**Comment by devmuhib009** [comment]
@nigel3 do you need any help? Can you please elaborate what is the purpose of this ticket?
