### ISSUE TITLE
Separate sidebar areas for post types

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#236]
We currently have only one sidebar option that shows on all post types that have it in their template. We need to distinguish these some more for different content types, so could we please have different sidebar areas for Courses and Lesson Plans? The other post types don't use sidebars, so it's just for those two.

The Lesson Plans already have a custom block in their sidebar, so that will need to still be available in the new sidebar area.

**Comment by courtneyr-dev** [comment]
As we get toward 5.9, it'd be great to see using widgets and full site editing for the team to make minor tweaks without needing coding.
