### ISSUE TITLE
Feedback - In desktop view , filter layout is not proper

### ISSUE THREAD

**Issue by pranitdug** [WordPress/Learn#2367]
In desktop view , after selecting any filter option in below page layout get broken.
Page Url - https://learn.wordpress.org/online-workshops/#https://www.meetup.com/learn-wordpress-online-workshops/events/297216786

![Screenshot 2024-04-05 at 9 02 18 AM](https://github.com/WordPress/Learn/assets/121865451/05b4fa30-72e3-4e29-b0ef-5fd80462a71b)

**Comment by pranitdug** [comment]
After adding this css in below path resolves the issue -
`https://learn.wordpress.org/wp-content/plugins/wporg-meeting-calendar/build/calendar.css?ver=5428dcf2cee6579bd890d3eea86decc5

.wporg-meeting-calendar__filter {
	display: flex;
	align-items: center;
	border: 1px solid #ddd;
	background: #eee;
	flex-wrap: wrap;
	justify-content: space-between;
}`

**Comment by adamwoodnz** [comment]
The data causing this issue was removed, see https://github.com/WordPress/Learn/issues/2674
