### ISSUE TITLE
Allow speaker bio override from local user profile

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#237]
Workshops currently display the full bio of individual speakers displayed dynamically from their WordPress.org profiles. In some cases this could potentially become problematic:
* The bio includes swear words
* The bio promotes non-GPL compatible companies or products
* The bio is a nonsense block of text that isn't meant to be taken seriously

In order to provide some control over this situation, could we please add a feature that allows us to override the displayed bio with one added to the user in the Learn WordPress dashboard itself?

The logic flow would then be to check for a bio in the user profile on the site itself and then, only if it does not exist or returns an empty string, then fetch the bio dynamically from profiles.wordpress.org.

**Comment by ronalfy** [comment]
@hlashbrooke are there any UI pieces to this?

From the code, it appears to look for the .org profile first, then load in the local user bio.

I can certainly change the order, but was wondering if there needs to be an override switch (global) or per-user?

**Comment by hlashbrooke** [comment]
In that case - it's really just a matter of switching the order it checks. That way we only need to use the local bio if needed and the field will remain blank otherwise, allowing it to use the .org profile bio instead. I didn't realise that check was already there, so that's great to hear. No global check is needed here - this would be per-user.

**Comment by ronalfy** [comment]
Thanks @hlashbrooke it may make sense to have a flag in meta for no bio to show at all, but I'll put together a PR shortly on this one.
