### ISSUE TITLE
Sensei blocks broken in the Course editor (and possibly elsewhere)

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2373]
The removal of a polyfill in the upcoming WordPress 6.6 release is currently affecting Sensei blocks.

When trying to edit an existing course, any Sensei blocks used are reported as not available.

![learn wordpress org_wp-admin_post php_post=56187 action=edit(Desktop)](https://github.com/WordPress/Learn/assets/180629/8fe5ea2b-9df6-41a1-8f1e-87f699ff2d81)

Thanks to the excellent investigation skills of @donnapep, who was able to determine this is due to an [update coming to WordPress 6.6](https://core.trac.wordpress.org/ticket/60962). All meta sites, including Learn.WordPress.org run the latest alpha version of WordPress, and this therefore currently affects the site.

Donna will be testing the proposed solution for Sensei and will report back once a solution is in place.

**Comment by donnapep** [comment]
PR can be found here - https://github.com/Automattic/sensei/pull/7591.

**Comment by jonathanbossenger** [comment]
The [Sensei PR](https://github.com/Automattic/sensei/pull/7591) has been tested and merged, and an update should be due later this week.

@pkevan or @adamwoodnz once Sensei is updated, what's the best way to get the plugin updated on Learn?

**Comment by pkevan** [comment]
On wp.org `sensei-lms` is checked out on trunk SVN, so as soon as it's there and there is a deploy it should update.

**Comment by donnapep** [comment]
An FYI that Sensei 4.24.0 has been released.

**Comment by jonathanbossenger** [comment]
Thanks @donnapep.

@adamwoodnz or @pkevan would it be possible to get this updated on Learn.

**Comment by pkevan** [comment]
> Thanks @donnapep.
> 
> @adamwoodnz or @pkevan would it be possible to get this updated on Learn.

it'll be out next time someone commits and deploys on wp.org - probably at some point today, or maybe Monday.

**Comment by jonathanbossenger** [comment]
Thanks @pkevan.

This has been resolved on Learn.WordPress.org
