### ISSUE TITLE
Building plugins and themes that support multisite

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2376]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Building plugins and themes that support multisite
- Topic description: Cover some of the common things to consider when developing themes and plugins that support multisite
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Use multisite specific functions in a theme or child theme
- Implement multisite support for a custom plugin

# Related Resources and Other Notes

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/11-introduction-to-wordpress-multisite/05-building-plugins-and-themes-for-multisite.md

**Comment by jonathanbossenger** [comment]
Video for review: 

https://github.com/WordPress/Learn/assets/180629/1d504fe4-d343-484d-b680-7caf2d8cbba1

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Perfect closure for an awesome series, @jonathanbossenger!

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/05/11/building-plugins-and-themes-that-support-multisite/

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/building-plugins-and-themes-that-support-multisite/

**Comment by jonathanbossenger** [comment]
//publish
