### ISSUE TITLE
Developing for a Multisite Network

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2377]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title:  Developing for a multisite netowkr
- Topic description: Introduce some of the differences to be aware of when developing for a multisite network.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner

# Learning Objectives

- Recognize some of the legacy naming conventions for multisite related functions
- Identify some commonly used multisite specific functions and hooks

# Related Resources and Other Notes
- https://learn.wordpress.org/tutorial/developing-for-multisite/

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/11-introduction-to-wordpress-multisite/04-developing-for-multisite-network.md

**Comment by jonathanbossenger** [comment]
Video for review: 

https://github.com/WordPress/Learn/assets/180629/218e1268-7823-4059-b4eb-db77dc4a2125

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial. 

-----  

Looks good! 
The pace was even and flowed well, except the section towards the end where the different code examples were being worked out. It seemed to slow a bit there, with slightly longer pauses in the audio commentary. 

Not sure what a better approach might be? Perhaps having all the code examples already written out, and then walking through them. But it's a minor issue and could also just be a personal preference. Digging into multisite code is pretty new to me, and I found the content helpful and informative.

**Comment by jonathanbossenger** [comment]
Thanks @quitevisible. It's a fine balance, I've had other reviewers say that I go too fast during live coding portions 😁 

It's worth noting that all lessons will include a full text version, with code snippets, so someone who wants to move faster can either just speed up the video, or skim the text version and grab the code snippets.

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Love the deep dive into the development side that's rarely discussed when talking about multisite.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/05/11/developing-for-a-multisite-network/

**Comment by pricelessopoku** [comment]
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Multisite code is pretty new to me and this content was very useful. Great tutorial. @jonathanbossenger

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/developing-for-a-multisite-network/

**Comment by jonathanbossenger** [comment]
//publish
