### ISSUE TITLE
The built-in WordPress debugging options

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2378]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title:  Enabling the built-in WordPress debugging options
- Topic description: Covers the various PHP constants that can be enabled to turn on the built-in WordPress debugging features
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Beginner
 
# Learning Objectives

- List the 5 common PHP constants that enable built-in WordPress debugging features
- Demonstrate what enabling each one of these constants does

# Related Resources and Other Notes
- https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/
- https://learn.wordpress.org/tutorial/debugging-in-wordpress/

### Automation Code

//lesson

**Comment by agiljulio** [comment]
Hi team, I would like to be involved in recording this video

**Comment by vinciunaite** [comment]
Hey, just dropping a comment so I can stay in the loop with this

**Comment by jonathanbossenger** [comment]
Thanks, everyone.

@agiljulio I will work on the script and voiceover next week.

Do you prefer one single audio file, or does it work better if I break up the logical sections into different audio files?

Also, what audio container (wav, mp3, etc) and encoding bitrate do you prefer?

**Comment by agiljulio** [comment]
Great, can't wait for it 👍

I prefer a single audio file, and for the audio format I usually use mp3 with a bitrate of 256kbps.

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/12-debugging-in-wordpress/01-built-in-wordpress-debugging-options.md

**Comment by jonathanbossenger** [comment]
Slides: https://docs.google.com/presentation/d/133KYHqkY0hyX_LQ8hyrT1w1D76rdFn1qSl0gxhkclaY/edit?usp=sharing

**Comment by jonathanbossenger** [comment]
Audio recording: https://drive.google.com/file/d/1P7uIfPf0l9yj3TVKhn8p6y0297H2nia9/view?usp=sharing

**Comment by jonathanbossenger** [comment]
@agiljulio I have updated this issue with as much information as possible along with the audio file.

1. In the issue description, under relevant links, is the link to the WordPress documentation as well as a tutorial that I previously recorded. The content of this lesson is mostly the same as the tutorial, but with a different intro, and without the plugin related content.
2. I have also included a copy of the script, which itself includes links to most of the resources referenced, as well as the example code and code snippets.
3. I have included my slides. You don't have to use them, but the training team does have a slide template you can find in our handbook on [creating lessons](https://make.wordpress.org/training/handbook/lessons/creating-a-lesson/), that uses the same colours and fonts.
4. I would also recommend reading through our [Lesson guidelines](https://make.wordpress.org/training/handbook/lessons/), as this describes the format of our lessons.
5. Finally, you can watch any of the videos in the [the beginner user pathway](https://github.com/WordPress/Learn/issues/1977) or [the beginner developer pathway](https://github.com/WordPress/Learn/issues/1984), to get a feel for how we create content.

Please let me know here if you have any questions.

Also, please could you give me an idea of how long you estimate it would take you to create the final video for this lesson. 

Thanks

**Comment by agiljulio** [comment]
Hi @jonathanbossenger , thank you for the script, slides, and audio files.

I have some questions in mind: 
- Regarding the color format and fonts, do I only need to follow the same format as in the slides?
- Will there be a video QA process after I edit the video?

The video editing takes about 2-3 days, depending on the complexity of the video itself. For this video I will try to complete it within 3 days, I will inform you as soon as the video is ready.

Thank you.

**Comment by jonathanbossenger** [comment]
Hi @agiljulio thanks for the questions

Regarding the color formats and fonts, I'm not sure if that's a hard requirement. What I will do is ask the question in the training team channel in Slack, and we can discuss it with the team there.

For the QA process, usually what happens is that we upload the video (or a link to the video) in a comment in the GitHub issue, and then one or more reviewers from the training team will review it, following [these guidelines](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/).

As we are collaborating on this together, I will probably review the video first, and then ask another member of the team for a second review.

**Comment by jonathanbossenger** [comment]
I have asked the question around [colours and fonts here](https://wordpress.slack.com/archives/C02RW657Q/p1714115846502309).

**Comment by agiljulio** [comment]
Thank you for the update @jonathanbossenger 

I've checked the discussion in the training team channel in Slack and I can start recording and editing the video.

If I have any other questions, I'll ask them here. Thank you.

**Comment by jonathanbossenger** [comment]
Perfect, thank you @agiljulio, I look forward to seeing the video.

**Comment by agiljulio** [comment]
Hi @jonathanbossenger , here is [the built-in WordPress debugging options video](https://drive.google.com/file/d/119Rzh2rmxlQ5WITC2QSK7tVYe_efmxs9/view?usp=sharing) has been edited. Could you please check the video, thank you 🙏

**Comment by jonathanbossenger** [comment]
Thank you @agiljulio I look forward to watching it.

**Comment by jonathanbossenger** [comment]
Hi @agiljulio 

First off, amazing work, I can see you are a skilled video content creator. 

I only really have 2 pieces of feedback:

1. Would it be possible to remove the sound effects? I know that sound effects increase engagement as well as a subconscious appreciation of quality, but for a developer focused audience, they can become a little overwhelming. 
2. At around 3:35, where you show the results of the REST API request, would it be possible to include the browser window, with the address bar which reflects the REST API route. This will help the learner connect their custom REST route with what's on screen.

Other than that, I have no other feedback, other than great work. Would you feel comfortable to work on the rest of the video lessons [in this module](https://github.com/WordPress/Learn/issues/1984#module-13)?

**Comment by agiljulio** [comment]
Hi @jonathanbossenger , thank you for the feedback, and here is the [video that has been fixed](https://drive.google.com/file/d/13klhu8cxZaGVsGzZ4qM9lqhujMM_Av1-/view?usp=sharing).

Yes, I could work on the rest of that video lessons.

**Comment by jonathanbossenger** [comment]
Awesome, thank you @agiljulio 

I will share this with the training team for further review.

Next week I'll prepare a script for the next lesson, https://github.com/WordPress/Learn/issues/2379.

**Comment by jonathanbossenger** [comment]
Video ready for review: https://drive.google.com/file/d/13klhu8cxZaGVsGzZ4qM9lqhujMM_Av1-/view

**Comment by digitalchild** [comment]
This is a great introduction to debugging, and there were even a few things in there I had forgotten. 

## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by agiljulio** [comment]
Alright, thank you @jonathanbossenger 🙏

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [ ] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great tutorial, content and production-wise!

I have one correction and two requests/suggestions :-)
- 0:44-0:49: it says “**Use to console.log() for the testing and debugging.**” -- the “_to_” and “_the_” are redundant.
- The scroll-from-bottom animations used during the PHP debugging section (including WordPress’ PHP files) are *sooo* fast :-) Any chance the transition can be eased? I think it may also cause accessibility issues.
- The blurred background shown when discussing `wp-config.php` and `wp-learn-debugging.php` (including `debug.log`) is a bit distracting.

**Comment by jonathanbossenger** [comment]
Thank you @ironnysh 

@agiljulio would you be able to make these updates?

**Comment by agiljulio** [comment]
thank you for the feedback @ironnysh and here is the [updated video](https://drive.google.com/file/d/1sgwOxEjgT-tz8BljC6Vg9YeUYNqHsnZ6/view?usp=sharing) @jonathanbossenger

**Comment by jonathanbossenger** [comment]
Hi @agiljulio 

First off, I want to thank you for your hard work and continued interactions and updates to this lesson.

One of the amazing things about collaborating in an open source space, is the ability to learn from each other. 

As such, I'd like to discuss some of the changes that have been requested to the video (by me and others) and get your input on those choices

- sound effects. As you know, I asked you to remove them. I've had some feedback from some folks that they thought the sound effects were a good idea, but could perhaps have been reduced by 50 - 70%. Others agree the sounds could be distracting. I'd be interested to learn your reasons for adding the sound effects, and the perceived pros and cons.
- code examples. I've always personally preferred to show a code editor in my tutorials (VS Code or something like that). I know that you created yours in a more minimal style, so I'd be interested to hear if you find this has better engagement.
- dark/light mode. There's not a lot of concrete data on this, but I've been lead to believe that displaying code in a light mode theme is more easily readable. However, I've never seen anyone complain about the use of dark mode, as long as the colour contrast is distinct enough so that the text is readable. I'd be interested to hear your thoughts on this. 

Thanks in advance.

**Comment by jonathanbossenger** [comment]
@agiljulio I have also asked the rest of the training team to share their thoughts and input, so that we can all come to a consensus. Please don't feel the need to make any further changes to the video though, I'm hoping through this process we can all learn and improve from each other.

**Comment by agiljulio** [comment]
Hi @jonathanbossenger , thank you very much for the input, it really helps me to improve and maintain the quality of the video.
- Sound effects. Depending on the target audience, because the target audience for this video is developers, I agree to remove the sound effects so the audience can focus on watching the video. In my opinion, the pros are the audience feels enjoyed and engaged, the cons are that maybe some audiences will feel distracted. I've made 2 different videos [with sound effects](https://drive.google.com/file/d/18MuDoRbmHLmA0hWGncCRJOiTYwepJsgn/view?usp=sharing) reduced to 75% and [without sound effects](https://drive.google.com/file/d/1bqyV2HPGf0jV4-jxUkxC9RK37K1-ue8S/view?usp=drive_link).
- Code examples. Actually, I just wanted to try to visualize the code but not with a code editor and just focus on code examples. I've also changed and used VS Code as a code editor.
- Dark/light mode. I don't have a preference for using dark/light mode, I use dark mode in this tutorial because I used to code in dark mode. And I also already changed into light mode.

Thank you once again 🙏

**Comment by jonathanbossenger** [comment]
@agiljulio I would like that take this opportunity to thank you for your continued and open collaboration on this lesson. 

At this stage, I think the video [without sound effects, using the code editor in light mode is the way to go](https://drive.google.com/file/d/1bqyV2HPGf0jV4-jxUkxC9RK37K1-ue8S/view). It helps alleviate any possible issues with accessibility, and creates uniformity with the rest of the lessons in the larger learning pathway.

If we decide to add sound effects to all our videos going forward, then I will certainly be leaning on your experience :-)

I'm going to start the process of getting this video uploaded to WordPress.tv/YouTube and learn.wordpress.org. I will also prepare the second script for the [second lesson in this module](https://github.com/WordPress/Learn/issues/2379), which I will upload by tomorrow.

**Comment by jonathanbossenger** [comment]
WordPress.tv https://wordpress.tv/2024/05/15/the-built-in-wordpress-debugging-options/

**Comment by jonathanbossenger** [comment]
YouTube: https://youtu.be/wCh2_LLYC2Q

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/the-built-in-wordpress-debugging-options/

**Comment by jonathanbossenger** [comment]
//publish
