### ISSUE TITLE
Examining the state of your PHP code

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2379]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):Lesson
- Content title: Examining the state of your PHP code
- Topic description: Discover a few different ways to output or log variables in PHP
- Audience (User, Developer, Designer, Contributor, etc.):Developer
- Experience Level (Beginner, Intermediate, Advanced, Any):Beginner

# Learning Objectives

- Describe why it would be useful to use debugging functions.
- List a few functions that aide debugging, with examples

# Related Resources and Other Notes
- [PHP error_log() function](https://www.php.net/manual/en/function.error-log.php)
- [PHP print_r() function](https://www.php.net/manual/en/function.print-r.php)
- [PHP var_dump() function](https://www.php.net/manual/en/function.var-dump.php)

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/12-debugging-in-wordpress/02-examining-the-state-of-your-php-code.md

**Comment by jonathanbossenger** [comment]
Audio track: https://drive.google.com/file/d/1IhnJR8a5qv5mwyKp0orXeslIpKlXHVbu/view?usp=sharing

**Comment by jonathanbossenger** [comment]
@agiljulio, here is the script and audio file. 

I don't have a pre-existing video, because this will be a brand new lesson, so you'll have to create the visuals yourself, in the same style as the previous lesson.

Are you comfortable to take on this lesson video next?

**Comment by agiljulio** [comment]
Hi @jonathanbossenger thank you for sending the script and audio file.

Noted it, I will adjust the style to the same as the previous video.

Yes, I feel comfortable taking on this lesson for the next video, If I have any questions, I will ask here 🙏

**Comment by jonathanbossenger** [comment]
Thank you @agiljulio I look forward to reviewing the next video.

**Comment by agiljulio** [comment]
Hi @jonathanbossenger [the video](https://drive.google.com/file/d/1RH6Fhd6GJCsjxyqiLMJY4Uy2PMb1tXz0/view?usp=sharing) has been edited and is ready for review. Please feel free to provide any feedback, thank you 🙏

**Comment by jonathanbossenger** [comment]
Thank you @agiljulio I will do my best to review it today or tomorrow.

**Comment by jonathanbossenger** [comment]
Hey @agiljulio sorry for the delay here. Great work on the video.

I'm going to open this for the training team to review, and then get started on the scripts and voice recordings for the next two videos. I'd like to try and get these to you by the end of this week.

**Comment by digitalchild** [comment]
Nice clear overview of debugging @jonathanbossenger 

I have one piece of feedback, i'm not sure if I missed it. 

- When you highlight enabling debugging in the wp-config is it worth showing what that looks like in the wp-config because by default, enabling debugging does not enable the debug.log file.

**Comment by jonathanbossenger** [comment]
Thanks @digitalchild 

This configuration was covered in the previous lesson in this module on [enabling the debugging options](https://github.com/WordPress/Learn/issues/2378). Do you think it would be beneficial to refer to this in the spot you mention?

**Comment by digitalchild** [comment]
@jonathanbossenger Yes I think if you mention its in the previous lesson that should be enough. The reason I ask is because you have the wp-config open in the IDE :)

**Comment by jonathanbossenger** [comment]
Aha, that's a solid point. I didn't actually create the video, Agil and I are collaborating on this one.

I'm planning my own review later, so I'll keep an eye out for this.

**Comment by jonathanbossenger** [comment]
> Yes I think if you mention its in the previous lesson that should be enough.

@digitalchild at 0:28 in this lesson, it directly references the "The built in WordPress debugging options" lesson, which contains the relevant settings to enable debug.log ([here is the relevant section in that lesson](https://youtu.be/wCh2_LLYC2Q?si=-oUpTPxNLx59vlF0&t=142)). 

As this is the next lesson in the learning pathway after that one, would you agree this is sufficient reference to that lesson, and the settings therein?

**Comment by jonathanbossenger** [comment]
Hi @agiljulio 

As always, a great video. I do have a few change requests. Mostly they are adding some additional pauses in the voice, to allow viewers to take in what's on the screen.

- at 0:58, after the transition to the IDE, would it be possible to insert a 1 second pause to show the use of error_log, before the voice explanation?
- at 1:47 - 2:00, would it be possible to insert additional pauses in the voice to display the PHP code and the output for a few more seconds each.
- at 2:22 could you add a pause before the var_dump explanation starts
- 2:37 - 2:39 could you add additional pauses for the example code and output
- 2:44 could you stay on the output in the browser here, and use annotations (eg arrows) to show how var_dump displays the value of the variable and the additional information about variable type and length. 
- at 2:57, when it's talking about var_dump not having a "return" option, the video can switch back to the code IDE
- at 3:30, would it be possible to show a screenshot of those actual pages on the php docs, it's helpful for folks to see what that page looks like, along with the url.

Thanks in advance.

**Comment by agiljulio** [comment]
Hi @jonathanbossenger , thank you for your feedback. It was very detailed and will help me maintain the quality of the video. Here is the [updated version](https://drive.google.com/file/d/1RH6Fhd6GJCsjxyqiLMJY4Uy2PMb1tXz0/view?usp=sharing).

**Comment by jonathanbossenger** [comment]
Thanks @agiljulio it's looking great.

I did pick up one additional small bug.

At 2:15 when you update the code to wrap `print_r` using the second parameter in the `error_log` call, you don't need the `<pre>` tags anymore, as the code is now logging to the `debug.log`

So instead of
 
```
$some_array = array( 'apple', 'banana', 'cherry' );
echo '<pre>';
error_log( print_r( $some_array, true ) );
echo '</pre>';
```

It should just be 
```
$some_array = array( 'apple', 'banana', 'cherry' );
error_log( print_r( $some_array, true ) );
```

Apologies if this wasn't clear in the script, I'll make sure to make these examples clearer going forward.

**Comment by agiljulio** [comment]
No problem @jonathanbossenger . Here is [another update](https://drive.google.com/file/d/1RH6Fhd6GJCsjxyqiLMJY4Uy2PMb1tXz0/view?usp=drive_link). Thank you for clarifying 🙏

**Comment by jonathanbossenger** [comment]
No problem, @agiljulio. Thank you for always being open to updates and changes.

I will work on getting this video lesson published this week and share the next two scripts with you.

**Comment by agiljulio** [comment]
My pleasure @jonathanbossenger 🙏 I look forward to receiving the next script.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/06/07/examining-the-state-of-your-php-code/

**Comment by jonathanbossenger** [comment]
https://youtu.be/ThyDq0misbk

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/examining-the-state-of-your-php-code/

//publish
