### ISSUE TITLE
Examining the state of your JavaScript

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2380]
# Details
 
 - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
 - Content title: Examining the state of your JavaScript
 - Topic description: Learn how to use the console object and it's methods to debug JavaScript when developing for WordPress. 
 - Audience (User, Developer, Designer, Contributor, etc.): Developer
 - Experience Level (Beginner, Intermediate, Advanced, Any): Beginner
 
 # Learning Objectives
 
- Explain why a developer can't use the WordPress debug.log for JavaScript code
- Demonstrate how to open Developer Tools in order to view the console
- Identify with examples, 2 common console object methods used during debugging 

 # Related Resources and Other Notes
- https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/What_are_browser_developer_tools
- https://developer.mozilla.org/en-US/docs/Web/API/console
 
 ### Automation Code
 
 //lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/12-debugging-in-wordpress/03-examining-the-state-of-your-javascript.md

**Comment by jonathanbossenger** [comment]
Audio file: https://drive.google.com/file/d/1P3rQdQCE_7SLKhl0VEIDstPs7yv6P2QJ/view?usp=sharing

**Comment by jonathanbossenger** [comment]
Hi @agiljulio I've added the script and the audio file to this issue. I also left some notes in the script, to hopefully help with the video creation process.

**Comment by agiljulio** [comment]
Hi @jonathanbossenger thank you for providing the script and audio, but I need access to download the audio. Could you please grant the access? Thank you.

**Comment by jonathanbossenger** [comment]
My apologies @agiljulio. I thought I had updated the permissions. You should have access to both now.

**Comment by agiljulio** [comment]
No problem @jonathanbossenger it works fine now, thank you. I will work on it 👍

**Comment by jonathanbossenger** [comment]
Thank you, @agiljulio it is always a great pleasure collaborating with you.

**Comment by agiljulio** [comment]
Hi @jonathanbossenger here is [the video](https://drive.google.com/file/d/1HnYkRLxx3_J7zZ3yAHjva4ak1c_ZxAYh/view?usp=sharing). Please feel free to provide any feedback. Thank you 🙏

**Comment by jonathanbossenger** [comment]
Hi @agiljulio, thanks for the video; another great job! 

At 1:00, thank you for showing how to find that specific article on MDN; that's exactly how I envisioned that section. 

I have two specific pieces of feedback, and I hope they are manageable on your part.

- At 1:10, and for any other visuals of the developer tools. Can the Developer Tools/Console tab be shown in light mode, following our light mode presentation of any code editor views we've used in previous lessons? 
- For the examples of `console.log()` at 1:44 - 2:25 and `console.table()` at 2:30 - 2:45, could we rather show the original code in the IDE in a plugin ([example plugin](https://github.com/jonathanbossenger/wp-learn-javascript-console/releases/download/1.0/wp-learn-javascript-console.1.0.zip)) and then show how it logs to the console, and the possibilities there.

What I envisioned for that last point is to show the code in the IDE like this:

![IDE](https://github.com/WordPress/Learn/assets/180629/0c07f42b-7fa1-460a-9e7b-b5fe792719f8)

And then show the output in the console, alongside the WordPress site, like this:

![browser](https://github.com/WordPress/Learn/assets/180629/935c2192-7f40-4870-8566-733df377891b)

There are two main reasons for this.

1. Up to this point in this course, the learner has not done anything in the console, so if they suddenly see JavaScript being pasted into the console, that might become confusing and lead to more questions.
2. I want to tie it directly back to WordPress so that they can see how console.logging works from their code in the editor of a WordPress site. 

Please let me know if you have any questions.

**Comment by agiljulio** [comment]
Hi @jonathanbossenger, sorry I didn't realize that my browser theme was set to dark mode 🙏 here is the [updated video](https://drive.google.com/file/d/1HnYkRLxx3_J7zZ3yAHjva4ak1c_ZxAYh/view?usp=sharing).

**Comment by jonathanbossenger** [comment]
No problem, thank you @agiljulio the new version looks great!

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/06/20/examining-the-state-of-your-javascript/

**Comment by jonathanbossenger** [comment]
https://youtu.be/4tMt--evXUk

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/examining-the-state-of-your-javascript-code/

**Comment by jonathanbossenger** [comment]
//publish
