### ISSUE TITLE
Useful debugging plugins

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2381]
# Details
 
 - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
 - Content title: Useful debugging plugins
 - Topic description: Learn about two popular plugins for debugging in WordPress
 - Audience (User, Developer, Designer, Contributor, etc.): Developer
 - Experience Level (Beginner, Intermediate, Advanced, Any): Beginner
 
 # Learning Objectives
 
- Describe how to find debugging plugins
- Identify two popular plugins for debugging.
 
 # Related Resources and Other Notes
 - https://wordpress.org/plugins/debug-bar/
 - https://wordpress.org/plugins/query-monitor/
 - 
 ### Automation Code
 
 //lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/developer-learning-pathway/12-debugging-in-wordpress/04-useful-debugging-plugins.md

**Comment by jonathanbossenger** [comment]
Audio file: https://drive.google.com/file/d/1pJ0mZSOqDaRSkbTUhVdu1bWUAiR6Sea-/view?usp=sharing

**Comment by jonathanbossenger** [comment]
Hi @agiljulio I've added the script and the audio file to this issue. I also left some notes in the script, to hopefully help with the video creation process.

**Comment by agiljulio** [comment]
Hi @jonathanbossenger thank you for providing the script and audio, but I need access to download the audio. Could you please grant the access? Thank you.

**Comment by agiljulio** [comment]
Hi @jonathanbossenger here is [the video](https://drive.google.com/file/d/1-6uq_62q9vh09kVUgH_oFgEi3KbahKkv/view?usp=sharing). Please feel free to provide any feedback. Thank you 🙏

**Comment by jonathanbossenger** [comment]
Thanks, @agiljulio looks great. 

Do you have a rough idea when #2380 will be ready? Thanks

**Comment by agiljulio** [comment]
Hi @jonathanbossenger I apologize for the delay in sending the third video. There was a national holiday in my country and I was on leave 🙏

Anyway, here is [the video](https://drive.google.com/file/d/1HnYkRLxx3_J7zZ3yAHjva4ak1c_ZxAYh/view?usp=sharing) and I have also updated it [here](https://github.com/WordPress/Learn/issues/2380#issuecomment-2174976929), thank you.

**Comment by jonathanbossenger** [comment]
Hey @agiljulio, no need to apologize at all; I was just curious. Thanks for the new video, I will review it this week.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/06/20/useful-debugging-plugins/

**Comment by jonathanbossenger** [comment]
https://youtu.be/mzQ6b0LKUrQ

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/useful-debugging-plugins/

**Comment by jonathanbossenger** [comment]
//publish
