### ISSUE TITLE
Meeting Agenda April 25, 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2386]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @bsanevans ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- April 25 – [@Sancastiza](https://profiles.wordpress.org/sancastiza/)
- May 2 – [@Jagir Bahesh](https://profiles.wordpress.org/jagirbahesh/)
- May 9 – [@Tapan](https://profiles.wordpress.org/voboghure/)
-  May 16 - NEED VOLUNTEER

**2. Looking for feedback**

- We are seeing inconsistency in the content review process, which makes it difficult to substantiate meaningful contributions. Any suggestions on how to make [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) easier ? Some suggestions. 
-- Ask content creators to link to the review checklist
-- Ask editors to use the review checklist
- What if we bridged the community team’s mentorship program with the guide program to funnel more people who may not know about Training directly into the team?

**3. Looking for volunteers**

- Are you going to WordCamp Europe? 
We are looking for volunteers for [Brainstorm & Table Lead – WordCamp Europe 2024 Contributor Day](https://make.wordpress.org/training/2024/04/23/brainstorm-table-lead-wordcamp-europe-2024-contributor-day/)

- item 2

**4. Other news**

- Give update on issue you(Ben) brought about last week about //publish https://wordpress.slack.com/archives/C02RW657Q/p1713399627084799
- item 2

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 15 issues ready for review 

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 24 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 31 issue that requires vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- 👏 We have 0 issues 

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 16 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: [davouid](https://profiles.wordpress.org/davouid/), [@voboghure](https://profiles.wordpress.org/voboghure/)
- Props: 

## 4. Project updates

- Project_1
  - details
- Project_2
  - details

## 5. Faculty Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
There was no dev-squad triage last week, so I've removed that item.

Also, there's an update to the [Sensei course blocks issue](https://github.com/WordPress/Learn/issues/2373#issuecomment-2072148464). Hopefully we can get this all resolved by the start of next week.

**Comment by kaitohm** [comment]
Meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1714003487168479
