### ISSUE TITLE
Tutorial data migration

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#2393]
Migrate Tutorial posts to become Lessons.

Add redirects from old URLs to new URLs (see https://github.com/WordPress/Learn/issues/2496)

**Comment by kathrynwp** [comment]
@adamwoodnz We are ready to do the migration of all non-deprecated tutorials to lessons. I've compiled the list here:

https://docs.google.com/spreadsheets/d/1D_caQxJs55eIinGTlIb7du_vE5FBxn4ri7pAWI5K2RE/edit?gid=0#gid=0

Could we please **keep the original publication date** of each tutorial. That way they will show further down the paginated list of lessons.

If we can also please keep the **language** and any other metadata that is also present in lessons that would be great. Thank you!

**Comment by adamwoodnz** [comment]
> Could we please **keep the original publication date** of each tutorial. That way they will show further down the paginated list of lessons.
> 
> If we can also please keep the **language** and any other metadata that is also present in lessons that would be great. Thank you!

I'll have a look at writing a script for this, but we should consider manual migration due to the following considerations.

Post meta will be complicated because lessons don't currently support some tutorial fields, and likely don't need to moving forward. We need to decide which need to be kept. The [Learn meta matrix](https://docs.google.com/spreadsheets/d/1OmxZLnyf1ncvU8zmtprUEOE_X_1Ye9B3glauzjzDUEk/edit?gid=0#gid=0) shows this disparity:

![Screenshot 2024-09-27 at 1 55 21 PM](https://github.com/user-attachments/assets/e4707be1-e6df-422b-b03c-88865e396046)

One important field to note is the WPTV URL, which if set automatically renders an embed at the start of a tutorial. For a lesson the author would be expected to add a WPTV embed block in the content for this. Scripting this would be complex, so we could either add this auto embed functionality to lessons (which may never be used moving forward), or add these blocks to the content manually.

### Approaches

There are three that I can think of:

1. Change the post type from `wporg_workshop` to `lesson`
2. Create a new lesson post for each tutorial, copying over the title, content, published date and author, and create new post meta records for any chosen fields.
3. Manual migration of 89 tutorials

For all three we'll need to add new post meta fields on the lesson post type for anything not currently supported which we want to migrate.

### Pros and cons

Approach 1 is simple, preserves all the post meta and relationships and reduces database duplication. We would still need redirects to ensure there is no SEO impact. We'd need to consider whether we have a backup to roll back changes if necessary.

Approach 2 is more complicated, but preserves the old tutorial in the database. I expect creating post meta during the migration may be more error prone.

Approach 3 is more work, but could be divided up and would be less risky.

@dd32 I remember asking about this before we started the project and I think I remember you saying that you thought manual migration would be the safest bet. Could you please add your thoughts on these approaches?

**Comment by kathrynwp** [comment]
Hi @adamwoodnz - thanks for the details and thoughts here.

> Scripting this would be complex, so we could either add this auto embed functionality to lessons (which may never be used moving forward), or add these blocks to the content manually.

Good to know. Since we no longer embed from WP.tv into lessons – instead embedding from the YouTube copy – writing time-consuming WP.tv-specific code for lessons may not make sense.

The information that seems important to carry over to lessons is **language**, so they will show up using the filter:

<img width="1228" alt="Lessons___Learn_WordPress" src="https://github.com/user-attachments/assets/f296f943-a638-4c19-9bab-3c524739b860">

I see that tutorials also have a specific **subtitle/caption language** option as well, which isn't tracked on lessons. Thinking we can probably drop this one, since subtitle language aren't being logged on the YouTube-embedded lessons at the moment.

The only other field I'm wondering if we should carry over is presenter name, since we are planning to have a contributor area. (see #1005) If not, these would need to be added manually later, I suppose.

cc @bsanevans to keep you in the loop and get your thoughts as well.

**Comment by kathrynwp** [comment]
One more field we should carry over – whether we do a manual or automated migration – is **Topics,** since the same topics list is used for Lessons and can be seen in filter form in the screenshot I posted just above. (Not sure which one this is in the meta matrix screenshot above.)

**Comment by adamwoodnz** [comment]
> One more field we should carry over – whether we do a manual or automated migration – is **Topics,** since the same topics list is used for Lessons and can be seen in filter form in the screenshot I posted just above. (Not sure which one this is in the meta matrix screenshot above.)

Good call, Topic is a taxonomy, so that's why it's not showing in the meta list. Should be possible to migrate, but again makes approach 2 more complex.

**Comment by adamwoodnz** [comment]
We're going to move forward with approach 1 (changing the post type using a script). Before doing this we'll ensure post meta and taxonomies we want to keep are compatible.

cc @kaitohm

**Comment by kaitohm** [comment]
Thanks for the update 🙌

**Comment by adamwoodnz** [comment]
Confirming that Lessons already have Topic taxonomy, and Language post meta.

Post meta that needs to be added to Lessons in order for existing data to be accessible after post type is changed:

1. `presenter_wporg_username`
2. `other_contributor_wporg_username`

**Comment by adamwoodnz** [comment]
Tested changing `post_type` locally, and as expected all post meta and taxonomy data remains intact. We can add the appropriate fields to Lessons for Tutorial data we want to use.

Next step will be to try this on the test site, and then create a CLI script to update the post_type for multiple posts.

**Comment by adamwoodnz** [comment]
The Tutorials have all been converted to Lessons now. I'll follow up with redirects, and then add the new post meta fields to Lessons.

**Comment by adamwoodnz** [comment]
> One important field to note is the WPTV URL, which if set automatically renders an embed at the start of a tutorial. For a lesson the author would be expected to add a WPTV embed block in the content for this. Scripting this would be complex, so we could either add this auto embed functionality to lessons (which may never be used moving forward), or add these blocks to the content manually.

> Good to know. Since we no longer embed from WP.tv into lessons – instead embedding from the YouTube copy – writing time-consuming WP.tv-specific code for lessons may not make sense.

Please note that all the Lessons will be missing the WP.tv embed, and either that or a YouTube embed will need to be added to the content via a block.

**Comment by kaitohm** [comment]
Thanks so much! I'll wait for all that to complete, then run through and check how things are.

**Comment by adamwoodnz** [comment]
Would it be useful to be able to see what the wordpress.tv url was? I imagined it would be so was about to add that meta box, as well as the presenter and other contributor boxes.

**Comment by kaitohm** [comment]
Yes please. We can then remove them once we're satisfied with the migration.

**Comment by adamwoodnz** [comment]
This should be complete now.

In the Lesson editor there are 3 new meta fields:

![Image](https://github.com/user-attachments/assets/94b7f5ed-b6a3-4055-889e-5aaa44f7a1bb)

I have added a WordPress.tv embed to [one converted Lesson](https://learn.wordpress.org/lesson/improving-website-performance-with-caching/) and added some styles to fix the embed display:

![Image](https://github.com/user-attachments/assets/0a89bca6-35ec-4658-8a49-e8a06732bae0)

So if you want to continue using that embed for some instead of YouTube it is possible.

**Comment by kaitohm** [comment]
Wonderful, thanks so much! I'll work through checking these with the team next week.
