### ISSUE TITLE
Feedback - Need to improve grammer for "Working faster with the command palette"

### ISSUE THREAD

**Issue by yagniksangani** [WordPress/Learn#2402]
## Type of feedback
//content

## Description
1. In the "Introduction" section, "Good day, and welcome to Learn WordPress." The comma after "Good day" is unnecessary. It should be: "Good day and welcome to Learn WordPress."

2. In the "Benefits of the Command Palette" section, "By providing quick access to frequently used actions, the Command Palette streamlines your workflow in the Site Editor." The phrase "streamlines your workflow in the Site Editor" should be "streamlines your workflow within the Site Editor."

3. In the "More commands" section, "For example Spotlight mode, if you select Spotlight mode, it will grey out all the blocks you are not working on and highlight the blocks you are editing." There should be a comma after "For example" to separate it from the rest of the sentence: "For example, Spotlight mode..."

4. In the "Conclusion" section, "With its quick access to frequently used actions and commands, it empowers you to work more efficiently and save valuable time." The phrase "save valuable time" should be "save valuable time."

## Step-by-step reproduction instructions
1. Go to https://learn.wordpress.org/tutorial/working-faster-with-the-command-palette/
2. Read the description.

**Comment by kaitohm** [comment]
//content

**Comment by yagniksangani** [comment]
Hi @bsanevans, Not getting, what's need to do further. Can you please guide me?

**Comment by kaitohm** [comment]
Thanks for submitting feedback 🙌  The command used in the issue body had an extra space between the slashes and the word `content`. I added the correct command so that the issue would get moved to the correct project board.

There's no further action needed from you for now. This has been added to other feedback issues waiting validation. Once validated, a Faculty member will apply the changes.

**Comment by yagniksangani** [comment]
Thanks @bsanevans

**Comment by jonathanbossenger** [comment]
I read through the suggestions and also ran the text through one or two grammar tools set to US English, and the tools didn't pick up any errors, so I think this is a case of US English rules being followed for lessons. I am closing this issue.
