### ISSUE TITLE
Missing images in some lessons

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2403]
## Type of feedback

//content

## Description
A learner has reported that some lessons appear to be missing images.

When I looked at the source code, it appears that at least one image is a Droplr image that has since been deleted or is otherwise unavailable.

## Step-by-step reproduction instructions 

1. Go to https://learn.wordpress.org/lesson/a-hands-on-experiment-with-the-block-editor/
2. Look below the line "https://learn.wordpress.org/lesson/a-hands-on-experiment-with-the-block-editor/" and view the browser source and note the following path in the `img` tag:

`src="https://cdn-std.droplr.net/files/acc_1185858/URIs3D`

## Screenshot

<img width="1007" alt="A_Hands-On_Experiment_With_The_Block_Editor___Learn_WordPress" src="https://github.com/WordPress/Learn/assets/7662449/591cc871-6382-48da-942b-2933697a7c90">

Because the Droplr image is not available, no image displays on the front end:

<img width="952" alt="A_Hands-On_Experiment_With_The_Block_Editor___Learn_WordPress" src="https://github.com/WordPress/Learn/assets/7662449/c6ded2a2-4cbe-4afc-91ca-ba37e862be90">

## Other information 

I don't know why a Droplr image was used in this lesson instead of the image being uploaded to the site, whether this is just a one-off occurrence, or something that's an issue in other lessons.

**Comment by kathrynwp** [comment]
Help Scout ticket reference: https://secure.helpscout.net/conversation/2577561692/176455?folderId=4035521

**Comment by ghost** [comment]
Updated image. Also noticed that the text needed to be updated since the Gutenberg experiment page wording had been changed. 

![Image](https://github.com/user-attachments/assets/74f74c48-af36-4ec8-8f2a-f9d9beb622ef)
