### ISSUE TITLE
Meeting Agenda May 2, 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2407]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @lada7042 ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- May 2 – [@Jagir Bahesh](https://wordpress.slack.com/team/UVDSVS9PD)
- May 9 – [@Tapan](https://wordpress.slack.com/team/U06MGLBUYUA)
- May 16 - [@Arun Sharma](https://wordpress.slack.com/team/U06SEMB4YPJ)
- May 23 - [@Zeel Thakkar](https://wordpress.slack.com/team/U06S6SL174K)

**2. Looking for feedback**

- Ben  received notice from the Sensei LMS plugin team that they will no longer be able to provide the following two features that were discussed at WordCamp US in summer 2023. For context, these were features #training had requested as part of our content type consolidation efforts around the site relaunch happening this year.

1. Adding an instructor notes section to lessons
2. Adding lessons to multiple courses

Based on this information, I'd like to discuss next steps with the team.

-- Regarding feature 1, I think we’ll will want to work with #meta to still create this feature as part of the site redesign. But this should probably be done with as minimal custom development as possible to reduce future maintenance overhead.
-- Feature 2 is something I propose we reassess and consider alternatives for. Technically, I think Learning Pathways could still be launched without this.

- The lesson page is getting a makeover too. [Learn Design](https://make.wordpress.org/training/2024/04/29/a-light-learn-lessons-visual-refresh/) (post by Joen)

- I am updating the wording in the [Training team contributor badge](https://make.wordpress.org/training/handbook/about/team-profile-badges/) reviewing section to make it more clear and add a link to the review template. I noticed under copyediting/reviewing there is wording "You should successfully move pieces of content from the “Review in Progress” stage to the “Published or closed” stage in Github." 
--Do we want the reviewers to publish or close an issue? 
--Is it the author's responsibility to publish or close an issue?
-- Thoughts? Should the wording be removed? 

**3. Looking for volunteers**

- Guides program
We currently have a couple of folks still waiting to be matched with a guide, but no guides are available. What are some ways we could attract more guides, ideally in a variety of time zones? A general call for new guides already went out a few weeks ago in the #training channel, but no one stepped forward, so other ideas are very welcome.
- Reviewers needed to review lesson videos. See Come & Contribute section

**4. Updates from last week's dev-squad triage session**

- item 1
- item 2

**5. Other news**
- [Our 2nd cohort course will be starting May 9- June 20](https://make.wordpress.org/training/2024/05/01/project-thread-the-second-learn-wordpress-course-cohort/).  The team reached out to people on the waitlist from the last cohort. Ben and Kathryn are admin and Jonathan will be speaking. Read about.  [Learn WordPress Course Cohort](https://make.wordpress.org/training/handbook/training-team-how-to-guides/course-cohorts/)

## 2. Come and Contribute
highlight- Validated feedback awaiting fix

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 22 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 25 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 31 issue that requires vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have 0 issues  2 weeks in a row with 0 issues. 

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 16 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: 
- Props: 

## 4. Project updates

- [Learning Pathways](: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4228) Updates
  - Thanks to Kathryn for the update. 
  - I know we would love more contributors involved. 

## 5. Faculty Updates ( DID LAST MEETING)

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kaitohm** [comment]
@lada7042 Could you raise the following point in tomorrow's meeting please? 🙏 

 I’ve received notice from the Sensei LMS plugin team that they will no longer be able to provide the following two features that were discussed at WordCamp US in summer 2023. For context, these were features #training had requested as part of our content type consolidation efforts around the site relaunch happening this year.

1. Adding an instructor notes section to lessons
2. Adding lessons to multiple courses

Based on this information, I'd like to discuss next steps with the team.

* Regarding feature 1, I think we’ll will want to work with #meta to still create this feature as part of the site redesign. But this should probably be done with as minimal custom development as possible to reduce future maintenance overhead.
* Feature 2 is something I propose we reassess and consider alternatives for. Technically, I think Learning Pathways could still be launched without this.

**Comment by kathrynwp** [comment]
@lada7042 We could add this item to the agenda, as an FYI:

**Project updates - Learning Pathways**

Update: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4228

**Guides program**

We currently have a couple of folks still waiting to be matched with a guide, but no guides are available. What are some ways we could attract more guides, ideally in a variety of time zones? A general call for new guides already went out a few weeks ago in the `#training` channel, but no one stepped forward, so other ideas are very welcome.

cc @bsanevans

**Comment by Zeelthakkar1207** [comment]
Hey @lada7042 

I'm interested as a Meeting note taker for May 23rd.

**Comment by ghost** [comment]
Thank you @Zeelthakkar1207

**Comment by ghost** [comment]
Issue is closed [Meeting Recap](https://make.wordpress.org/training/2024/05/07/training-team-meeting-recap-02nd-may-2024/)
