### ISSUE TITLE
Online Workshop: How to facilitate Online Workshop for the WordPress Training Team

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2408]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Online Workshop
- Content title: How to facilitate Online Workshop for the WordPress Training Team
- Topic description: A walkthrough of facilitating and co-hosting Online Workshops
- Audience (User, Developer, Designer, Contributor, etc.): Contributor
- Experience Level (Beginner, Intermediate, Advanced, Any): Any

# Learning Objectives

- Apply to facilitate and/or co-host Online Workshops
- Prepare to facilitate and/or co-host an Online Workshop
- Successfully facilitate and/or co-host Online Workshops 

# Related Resources and Other Notes

This is a repeat of #1800 with a focus of recruiting more Online Workshop facilitators for the team.

### Automation Code

//online-workshop

**Comment by devmuhib009** [comment]
I want to be the co-host for May 31st.

**Comment by kaitohm** [comment]
Thanks! I've added your name, Muhibul 🙌

**Comment by kaitohm** [comment]
@devmuhib009 I've had to change the date for the Online Workshop from May 31st to May 30th. The time of day hasn't changed. Are you still available to co-host at the new date? 🙇‍♂️

**Comment by devmuhib009** [comment]
Yes. I am available.

**Comment by kaitohm** [comment]
Thanks Muhibul 🙌

**Comment by kaitohm** [comment]
The recording has been uploaded: https://wordpress.tv/2024/06/02/how-to-facilitate-online-workshop-for-the-wordpress-training-team/
