### ISSUE TITLE
Child Themes

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2410]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Child Themes
- Topic description: Discover what child themes are, why you would use them, and how to create and use a child theme.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

- Explain what a child theme is
- Describe reasons why you would use a child theme
- Create a child theme manually
- Create a child theme using the Create Block Theme plugin

# Related Resources and Other Notes
https://developer.wordpress.org/themes/advanced-topics/child-themes/

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/theme-developer-learning-pathway/07-advanced-theme-development/01-child-themes.md

**Comment by jonathanbossenger** [comment]
Video for review: 
https://github.com/WordPress/Learn/assets/180629/f504fd0a-722e-4236-a189-eae4166e6367

**Comment by rosswintle** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

* Great work, @jonathanbossenger. Pacing is good. Content is good. Most of my comments below are small/nitpicks for quality, or small ideas for improvement. I hope the feedback is what you are looking for. I think my final bullet point is the one I'd really like addressed!
* The first slide has a series of statements with question marks. You should either remove the question marks, or turn them into questions. e.g. "What child themes are?" should be "What are child themes?" or "What child themes are."
* On slide 3, "an extension of it's parent theme" should be "an extension of its parent theme" (no apostrophe!)
* Can the cough at 0:47 be edited out?
* There are places where the narration moves to a new sentence without a pause. The pace of the narration is slow, but then suddenly skips and this is jarring. Examples are at around 0:51 and 1:09.
* At 4:00 it would be really good to explain what "Template" is in the style file header. I would probably also add at this point that while you can add other files, a style.css file with the header is the minimum needed to create a child theme. I know you do this later. Perhaps you just need to say "The information you need to put in this header will be explained later".
* It might be worth pointing out that the header format [is on the docs page](https://developer.wordpress.org/themes/advanced-topics/child-themes/#create-a-style-css) and can be copied and pasted from there (that's what I always do).
* I think that "All WordPress themes are technically parent themes" is incorrect. I would say that "Any WordPress theme (that is not a child theme) can be used as a parent theme"
* Can we edit out the "or slug" at 5:00? I think it's confusing.
* 6:20 - is it _really_ a good idea to copy and paste Block Editor content into theme files like this? Personally, I don't think this should be encouraged.
* I think the lesson lacks some information about how CSS styles and functional PHP code can be put in child themes. I came away feeling like I would only put markup in a child theme. But they are really good for styles and theme-related actions/filters too.

**Comment by jonathanbossenger** [comment]
@rosswintle thanks for the review and feedback

> Can the cough at 0:47 be edited out?

Whoops, I missed that one

> There are places where the narration moves to a new sentence without a pause. The pace of the narration is slow, but then suddenly skips and this is jarring. Examples are at around 0:51 and 1:09.

Thanks, I'll see if I can add a pause in there.

> At 4:00 it would be really good to explain what "Template" is in the style file header. I would probably also add at this point that while you can add other files, a style.css file with the header is the minimum needed to create a child theme. I know you do this later. Perhaps you just need to say "The information you need to put in this header will be explained later".

So this might be a style difference, but I prefer to teach with a bit of a "show, then tell" process. So first I show you how to do the thing, you get a quick win and the excitement of "I did the thing" and then I explain what you did and how it works.

I'm also relying that someone watching this lesson in the learning pathway has already watched the lesson on [Theme Structure](https://github.com/WordPress/Learn/issues/2085), which explains the theme header in a bit more detail. So perhaps what I could is reference that lesson and the relevant doc in the "further reading" section.

> It might be worth pointing out that the header format [is on the docs page](https://developer.wordpress.org/themes/advanced-topics/child-themes/#create-a-style-css) and can be copied and pasted from there (that's what I always do). 

As noted above, I'll add this to the further reading section

> I think that "All WordPress themes are technically parent themes" is incorrect. I would say that "Any WordPress theme (that is not a child theme) can be used as a parent theme"

Correct me if I'm wrong, but isn't the line there "All WordPress themes — unless they are specifically a child theme — are technically parent themes." which is the same as what you are saying?

> Can we edit out the "or slug" at 5:00? I think it's confusing.

Hmmm interesting, I think it's useful, because the word theme directory and theme slug are often used interchangeably. So maybe it would be better to have "The value of this field must match the folder name (which is also sometimes referred to as the theme slug)"

> 6:20 - is it really a good idea to copy and paste Block Editor content into theme files like this? Personally, I don't think this should be encouraged.

I'm interested to know your thoughts around why you feel this way. I don't think I'm saying it's the only way, but it is one way. For a single small change, it's certainly quicker and easier than first installing Create Block theme and using it's functionality. 

> I think the lesson lacks some information about how CSS styles and functional PHP code can be put in child themes. I came away feeling like I would only put markup in a child theme. But they are really good for styles and theme-related actions/filters too.

That's a good point, I'll add a note in the "How child themes work" section that this applies to all parts of the theme, not just template files.

**Comment by rosswintle** [comment]
If I don't reply to any particular comment then you can assume my response is "Aaah, right, I see" or "Yep, that's cool!"

> Correct me if I'm wrong, but isn't the line there "All WordPress themes — unless they are specifically a child theme — are technically parent themes." which is the same as what you are saying?

My change here was "are parent themes" to "can be used as a parent theme".

This may be a language difference thing? But intuitively - to me at least - a parent theme must have a child theme. So if every theme is a parent theme, then where are all the child themes that they are parent to?

I'm happy with your wording, but I thought "can be used as..." was clearer.

> maybe it would be better to have "The value of this field must match the folder name (which is also sometimes referred to as the theme slug)"

Yes, I like this. There me be previous lessons in the pathway where slugs are explained so I may be missing that.

> I'm interested to know your thoughts around why you feel this way. (About pasting block editor content into the child theme)

I chatted with Aurooba. It turns out I don't have an accurate mental model of how FSE themes work. So this is fine and you can ignore me.

It maybe makes the case for a "conversion course" learning pathway for an old-school non-FSE dev's like me! :-)

## Next steps

What happens next? Do I need to re-review this once you have made changes?

Also, was this the right level of feedback? Did you get what you needed from the review?

Thanks

**Comment by jonathanbossenger** [comment]
> My change here was "are parent themes" to "can be used as a parent theme".
> This may be a language difference thing? But intuitively - to me at least - a parent theme must have a child theme. So if every theme is a parent theme, then where are all the child themes that they are parent to?
> I'm happy with your wording, but I thought "can be used as..." was clearer.

So for what it's worth, this is the wording used in the [theme developer handbook](https://developer.wordpress.org/themes/advanced-topics/child-themes/) chapter on child themes. 

What I like about it is that it conveys the idea that all themes that aren't specifically child themes have the capacity to be parent themes, no specific change needs to be made to them to become a parent theme. 

But I do get what you're saying, an adult is not a parent until it has a child, which is probably why the parent/child analogy for themes is not a great one in the first place, but we work with what we have 😁 

> There me be previous lessons in the pathway where slugs are explained so I may be missing that. 

Probably not, it comes from the actual use of the term [slug](https://wordpress.org/documentation/article/wordpress-glossary/#slug) in the WordPress space, but it's also used for the lower case string name for a theme or plugin (theme slug or plugin slug). It's probably not used as much as it used to be though, so I might just delete that section.

> It maybe makes the case for a "conversion course" learning pathway for an old-school non-FSE dev's like me! :-)

This actually exists 😁 
- https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-1/
- https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-2/

> What happens next? Do I need to re-review this once you have made changes?

That's entirely up to you. Usually the content creator will update the video based on the feedback (if changes are required) and post the new video to the issue. I'll likely only get to that next week though. But there's also no requirement from you to re-review either.

**Comment by rosswintle** [comment]
Awesome! Thanks for all that. I'll keep an eye out for updates here.

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial. 

*****  

@jonathanbossenger I like how you spent almost equal time on the organic method of creating child themes, along with using the Create Block Theme plugin, which I'm assuming is the common method nowadays. 

In the past, I invested heavily in the Genesis framework which was based on child themes. Child themes in the age of FSE have seemingly become a "need?/don't need?" discussion topic. Especially if you're making all your style customizations in the Editor and not adding any custom functions. 

I wonder is there room for a short comparison on the most common reasons why one would likely need or not need a child theme?

Overall, great presentation!

**Comment by jonathanbossenger** [comment]
@quitevisible thanks for the review

> I wonder is there room for a short comparison on the most common reasons why one would likely need or not need a child theme?

Hmm, so I don't think that Learn.WordPress.org is the right place for that, maybe a post on the [developer blog](https://developer.wordpress.org/news/)?

>Especially if you're making all your style customizations in the Editor and not adding any custom functions.

IMO, the reasons for a child theme haven't changed, you want to build a custom theme experience based off a parent theme (like Genesis). If I was still developing sites for clients, I'd make the changes in the editor, sure, but I'd still export those changes to a child theme on a per client bases.

**Comment by jonathanbossenger** [comment]
Updated video


https://github.com/WordPress/Learn/assets/180629/62f4300a-76c9-43a3-ad2d-8759a5730b51

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Looks good :-)

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/05/24/child-themes/

**Comment by jonathanbossenger** [comment]
https://youtu.be/XTzWivuH10I

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/child-themes/

**Comment by askdesign** [comment]
@jonathanbossenger  - This is a very interesting video tut. It offers 2 ways to create a child theme, which is great. I usually create my child theme before making any modifications to the parent theme. But, in your video, you show how those modifications can be made first, then applied in the child theme. The other insight for me was to grab the code for those modifications and paste them directly into the html file. Interesting! Thank you for your hard work.

**Comment by jonathanbossenger** [comment]
Thanks @askdesign 

> It offers 2 ways to create a child theme, which is great.

IMO this is one of the great benefits of block themes and the site editor, the ability to design the changes in the editor, and then save them to a child theme.
