### ISSUE TITLE
Theme Testing

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2413]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Testing your theme
- Topic description: During development, or when you're ready to release your theme, it's a good idea to test it in a series of different scenarios. This lesson will explore tips and tools to use to test your theme. 
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

- Describe ways to test a theme both during and after development
- List plugins than can help with testing and debugging
- Identify other tools that can be used for testing themes.

# Related Resources and Other Notes
- https://developer.wordpress.org/themes/advanced-topics/testing/

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Script https://github.com/jonathanbossenger/wp-content/blob/main/theme-developer-learning-pathway/07-advanced-theme-development/06-theme-testing.md

**Comment by jonathanbossenger** [comment]
Video for review: 

https://github.com/WordPress/Learn/assets/180629/b7de69a9-601a-4ec0-9814-a3fce1e7af7b

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great overview of everything that's available for themers.

Don't forget to replace the placeholder screenshot for the A11Y module (at 5:17) ;-)

**Comment by jonathanbossenger** [comment]
Updated with placeholder replacement


https://github.com/WordPress/Learn/assets/180629/d781a37a-e198-42d9-a627-6d496b323a30

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/06/07/testing-your-theme/

**Comment by jonathanbossenger** [comment]
https://youtu.be/JUKag5vy_uk

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/testing-your-theme/
