### ISSUE TITLE
Build Process

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2414]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Build Process
- Topic description: An introduction to using @wordpress/scripts to implement a build process for theme development.
- Audience (User, Developer, Designer, Contributor, etc.):Developer
- Experience Level (Beginner, Intermediate, Advanced, Any):Intermediate

# Learning Objectives

- Describe what a build process is, and why it's useful
- Identify the required software to implement a build process
- Set up a build process using @wordpress/scripts and a custom theme development directory structure.

# Related Resources and Other Notes
- https://developer.wordpress.org/themes/advanced-topics/build-process/

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/theme-developer-learning-pathway/07-advanced-theme-development/04-build-process.md

**Comment by jonathanbossenger** [comment]
Video 
https://github.com/WordPress/Learn/assets/180629/94e8496f-b812-4883-b364-78ee9a008775

**Comment by rosswintle** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

Nice work. Couldn't see much wrong with this one!

* On the first slide "Why you should..." is not a question and therefore not worthy of a question mark (unless you change it to "Why should you...?"

**Comment by jonathanbossenger** [comment]
Updated video

https://github.com/WordPress/Learn/assets/180629/d34c1ad9-594b-4106-be8c-287a8a5bdbe0

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/05/24/theme-build-process/

**Comment by jonathanbossenger** [comment]
https://youtu.be/Qzg3IxcpEDk

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/build-process/
