### ISSUE TITLE
Plugin API Hooks in Classic Themes

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2415]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Plugin API Hooks
- Topic description: Covers the Plugin API hooks that developers of Classic themes should use in their theme templates.
- Audience (User, Developer, Designer, Contributor, etc.):Developer
- Experience Level (Beginner, Intermediate, Advanced, Any):Intermediate

# Learning Objectives

- Describe what Plugin API hooks are, and why they are needed
- List the template tags that should be implemented in Classic theme templates

# Related Resources and Other Notes
- https://developer.wordpress.org/themes/advanced-topics/plugin-api-hooks/

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/theme-developer-learning-pathway/07-advanced-theme-development/04-plugin-api-hooks.md

**Comment by jonathanbossenger** [comment]
Video for review:

https://github.com/WordPress/Learn/assets/180629/aebe5646-9f2c-46a8-a6ec-2c6647cc39e0

**Comment by rosswintle** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

Good work. Only very minor comments.

* On the first slide, it may be useful to change "to allow plugins to extend your theme" to include child themes as well: "to allow plugins and child themes to extend your theme". Though, thinking about it, that may be confusing given the content of the child themes lesson. I'll leave it up to you.
* This is SUPER nit-picky, but the use of full stops at the end of sentences/bullet points on the first slide is inconsistent.
* Would be nice to have a pause over the transition at 0:57

**Comment by jonathanbossenger** [comment]
> This is SUPER nit-picky, but the use of full stops at the end of sentences/bullet points on the first slide is inconsistent.

You are not wrong, but it's not worth the time to re-record that entire section. I'll be sure to look out for punctuation issues going forward. 

> Would be nice to have a pause over the transition at 0:57

Added.

**Comment by jonathanbossenger** [comment]
https://github.com/WordPress/Learn/assets/180629/e4b3d257-d057-4349-be44-71f98ec62a11

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/05/24/plugin-api-hooks/

**Comment by jonathanbossenger** [comment]
https://youtu.be/QNQrsOGeHRY

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/plugin-api-hooks/
