### ISSUE TITLE
Meeting Agenda May 9, 2024

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#2424]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- May 9 – [@Tapan](https://wordpress.slack.com/team/U06MGLBUYUA)
- May 16 - [@Arun Sharma](https://wordpress.slack.com/team/U06SEMB4YPJ)
- May 23 - [@Zeel Thakkar](https://wordpress.slack.com/team/U06S6SL174K)
- May 30 – Need volunteers

**2. Looking for feedback**

- The team reps reviewed [our 2024 goals](https://make.wordpress.org/training/2024/02/05/training-team-goals-for-2024/) this week and have a few questions for the team to discuss to provide clarity and achievability to some of the goals we created together.
  - Brainstorm the evolution of Online Workshops -- what are we hoping to accomplish with this goal? For example, Did we want to increase the programming ? Like having the same topics over different time zones to reach more audiences?
  - Create and maintain shared resources that promote the Training Team and Learn -- When do we feel satisfied that this is met? What resources are we lacking? We have slides and supporting materials for various things[ in our shared folder](https://drive.google.com/drive/folders/0B9sy5TrX_1i-a2F5cm1MMFZDcG8?resourcekey=0-W2tMm587DmaUPSNAhHFRhg).
- [Request for feedback: AI-generated voiceovers for video content](https://make.wordpress.org/training/2024/05/03/request-for-feedback-ai-generated-voiceovers-for-video-content/) -- what does the training team think of these AI voice videos? Please leave your feedback on the post!
- Sensei has been updated to [Sensei Pro to 1.24.0](https://github.com/Automattic/sensei-pro/releases/tag/version%2Fsensei-pro-1.24.0). Please [raise an issue](https://github.com/WordPress/Learn/issues/new?assignees=&labels=Awaiting+Triage&projects=&template=00-feedback.md&title=Feedback+-) if you find one
- https://github.com/WordPress/Learn/issues/2378 presents us with a new video editing features. Jonathan would like feedback on these videos, and asks that consider the following while reviewing (some of which have been altered during the initial review)
  - use of sound effects (please see the first version of the video), some like it, some do not
  - transition speeds and use of blur effects
  - code examples, showing them in an IDE (integrated development environment) or not
  - use of dark mode vs light mode

**3. Looking for volunteers**

- [WordCamp Europe 2024 Contributor Day](https://make.wordpress.org/training/2024/04/23/brainstorm-table-lead-wordcamp-europe-2024-contributor-day/) table leads -- do we have any volunteers?

**4. Other news**

- Who in the Training Team is going to [WCEU](https://europe.wordcamp.org/2024/)?
- We've cleaned up the Slack channel pins and Bookmarks to make our every day use links more accessible.
- [Training Team Update – May 2024](https://make.wordpress.org/updates/2024/05/03/training-team-update-may-2024/) is now out
- [Learn WordPress Newsletter – May 2024](https://learn.wordpress.org/learn-wordpress-newsletter-may-2024/) is now out
- There will be no [developer squad](https://make.wordpress.org/training/handbook/training-team-how-to-guides/dev-squad-guidelines/#what-is-dev-squad) meeting this week. Please join the team in #meta-learn for the meeting next week!

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 21 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 26 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 31 issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- All issues are clear for the 3rd week in a row! 👏 

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 16 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: 
- Props: 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - Ground work has started on the build while the finer details of the design are being finished.  ([See full update](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4229))
  - We need volunteers to help with creating the marketing campaign for the Learning Pathways
- [Project thread: The second Learn WordPress Course Cohort](https://make.wordpress.org/training/2024/05/01/project-thread-the-second-learn-wordpress-course-cohort/) has launched!
  - The aim of this project is to experiment applying the learnings from the last cohort, with the hopes of turning course cohorts into a sustainable educational offering on Learn.

## 5. Faculty Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

- From Jonathan -- out of date tutorials

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
I wanted to share [this content feedback on one of my original tutorials from 2020](https://github.com/WordPress/Learn/issues/2400).

The learner came across my (very long) tutorial and shared feedback that the content was out of date. I replied with the updated tutorials for that same content. 

However, I did note that the learner came to the tutorial via organic search, so it got me thinking, as we move towards the learning pathways/learn redesign, what should we plan for when it comes to older content.

We should probably do some sort of review as to what content is still coming up in online searches, and then add similar notices [to the ones I added on this tutorial](https://learn.wordpress.org/tutorial/intro-to-gutenberg-block-development/), about how there are updated versions. 

So I wanted to bring this up, and maybe start a larger conversation around formalising how we deprecate older content.

**Comment by jonathanbossenger** [comment]
Update: removed dev-squad as there was no triage last week.

**Comment by kathrynwp** [comment]
Update on the Learn WordPress remake from one of the developers on the project:
 
https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4229

**Comment by jonathanbossenger** [comment]
I'd like to ask content creators and developers in the training team to share their thoughts and feedback on the following lesson

https://github.com/WordPress/Learn/issues/2378

This is a collaboration between myself and @ agiljulio. Agil's style of content creation is sightly different from mine, s0 I want to use this to explore what we (the training team) think works and should be kept, and what not. 

Things to consider (some of which have been altered during the initial review):

- use of sound effects (please see the first version of the video), some like it, some do not
- transition speeds and use of blur effects
- code examples, showing them in an IDE or not
- use of dark mode vs light mode

Please watch the different versions of the video, as well as the review feedback shared so far, and share any other thoughts you might have in the comments.

**Comment by jonathanbossenger** [comment]
Please also make a note that no one from dev-squad is available to host triage this week, and so we've agreed to move it to next week.
