### ISSUE TITLE
Feedback - Introduction FULL-FEATUERD WP-Version

### ISSUE THREAD

**Issue by fizzlifax2** [WordPress/Learn#2426]
## Type of feedback
Styles and all the other stuff

## Description

I am mostly frustrated from a lot of CMSystems what integrates suplemental extensions what, after some updates, are running out and leaves me often behind with a completely DISFUNCTIONAL Website....
NOW since WP seems have resolved this problem, I would like to get a  Step by Step introduction for bulding up a WP-Site from scratch just WITHOUT all the dangerous extensions what could be stopped at any moment.

AND I would like to find a link for such a description clearly on TOP of the official WP Website to make it easier to join such description without diving in the deepest grounds of the WP site!

**Comment by kaitohm** [comment]
//content

**Comment by jonathanbossenger** [comment]
This content now exists in the form of the User Learning Pathways: https://learn.wordpress.org/learning-pathway/user/
