### ISSUE TITLE
Gujarati translation for "WordPress Hooks"

### ISSUE THREAD

**Issue by yagniksangani** [WordPress/Learn#2440]
# Details
- Link to original content: https://learn.wordpress.org/lesson/wordpress-hooks/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Gujarati
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by yagniksangani** [comment]
Gujarati Translation
https://docs.google.com/document/d/1UuDkFlLR0q_Ht74BBKEqsmYrdJ3OcEqFxv3DPn0Ipkc/edit?usp=sharing

**Comment by devmuhib009** [comment]
@pooja9712, @Roshan-narola, @DarshitRajyaguru, Hi all, if any of you have bandwidth, please review the content.

**Comment by DarshitRajyaguru** [comment]
Hi @devmuhib009 I will review and update ASAP

**Comment by DarshitRajyaguru** [comment]
Hi @devmuhib009,
I have reviewed this translation and It's Looks good to me.

**Comment by devmuhib009** [comment]
Thanks a lot. @DarshitRajyaguru for reviewing the translation.

**Comment by devmuhib009** [comment]
@yagniksangani give your WordPress username, so I can add you to the learn WordPress website.

**Comment by yagniksangani** [comment]
Here is my WordPress Profile Username: **yagniksangani**
Thank you @devmuhib009 @DarshitRajyaguru

**Comment by devmuhib009** [comment]
I just sent you the invitation, please accept it and draft the post.

**Comment by yagniksangani** [comment]
I have drafted a post for the Gujarati content, Can you please check and publish it?

Edit link: https://learn.wordpress.org/wp-admin/post.php?post=253583&action=edit
Preview link: https://learn.wordpress.org/?p=253583&post_type=lesson-plan&preview_id=253583

Also, can you please let me know if I need to do anything further?

Thanks @devmuhib009

**Comment by devmuhib009** [comment]
Hi @yagniksangani 
The content you translated is a course, not a lesson plan. So, you should add the content as course. https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-learning-pathway-courses

**Comment by yagniksangani** [comment]
Hi @devmuhib009 Thanks for letting me know, But i'm not sure, where to add the content as a course.
I tried to find the link to add the course in the WP dashboard, but not find it or I don't have access to this link,
https://learn.wordpress.org/wp-admin/edit.php?post_type=course
Can you please share a link or guide from where to add Gujarati-translated content as a course?

Thanks

**Comment by devmuhib009** [comment]
I'm out of my desk right now, I'll draft the post soon and give you the link. In meantime you can translate other contents like tutorial or lesson plans. Thanks

**Comment by devmuhib009** [comment]
Hi, @bsanevans, @Piyopiyo-Kitsune can you please take a look at this issue, I thought it's a lesson plan, but later I realized it's a single lesson of a course. Can we publish this lesson as translation or we need to translate the whole course all together?

**Comment by kaitohm** [comment]
Thanks for the ping. This depends on whether TranslatePress is going to be activated on Learn or not. There are some bugs that need to be looked into (see https://github.com/WordPress/Learn/issues/2445).

If this lesson has been reviewed, let's move it to "preparing to publish" and wait a little while to see if the TranslatePress issues will get resolved. If they get resolved, then we can put the translation into TranslatePress. If the issues don't get resolved, we'll want to create a new lesson for the translation.

@yagniksangani , separately to above, would you be interested in continuing to translate the other lessons in the course? Ideally, it would be great to see the whole course translated at some point 😃

**Comment by yagniksangani** [comment]
Hi @bsanevans Yes, i'm interested in continuing to translate the other lessons in the course. 

I have doubts about the whole course translation, Should I need to complete the translation for only the "WordPress Hooks" section? https://prnt.sc/AbfTlHoZl6LA

Can you please guide me further?

**Comment by kaitohm** [comment]
Translating a module at a time is a great idea. If you are available, then yes, please translate those lessons you've highlighted. we could continue to use this GitHub issue for the entire module.

**Comment by yagniksangani** [comment]
OK, thanks @bsanevans I will translate those highlighted lessons.

**Comment by yagniksangani** [comment]
@bsanevans @devmuhib009 
I have translated the content of all 4 lessons under the topic "WordPress Hooks". https://prnt.sc/N0uIEvkLVooF
Can anyone please review it and let me know the next steps? 

- https://learn.wordpress.org/lesson/wordpress-hooks/
Gujarati Translation: https://docs.google.com/document/d/1UuDkFlLR0q_Ht74BBKEqsmYrdJ3OcEqFxv3DPn0Ipkc/edit?usp=sharing

- https://learn.wordpress.org/lesson/action-hooks/
Gujarati Translation: https://docs.google.com/document/d/1j5Blj1OppKdtFYMG9T1uiFR8ByDmZrGG6LHI7_M6JUM/edit?usp=sharing

- https://learn.wordpress.org/lesson/filter-hooks/
Gujarati Translation: https://docs.google.com/document/d/19kWDVVxVGKKoqCvSSFE0TbHParMqMO-9O6obf9GQ8pA/edit?usp=sharing

- https://learn.wordpress.org/lesson/working-with-hooks/
Gujarati Translation: https://docs.google.com/document/d/1xJ9Nz-o2xCQdrxVPrqUBfELqxZ6N58MLdGdd3mt3trE/edit?usp=sharing

Thanks

**Comment by devmuhib009** [comment]
@DarshitRajyaguru can you please check newly translated lessons also?

**Comment by DarshitRajyaguru** [comment]
@devmuhib009 Sure, I will review and update you soon.

**Comment by yagniksangani** [comment]
@DarshitRajyaguru  @devmuhib009 Can you please update me once the review is done?

**Comment by devmuhib009** [comment]
@yagniksangani, sorry for the delay. Do you know someone who can review?

**Comment by yagniksangani** [comment]
@devmuhib009 Nope

**Comment by jagirbahesh** [comment]
@yagniksangani,
cc @devmuhib009 

Can you please provide the comment access? so, I will create the comment for you.
Here it is my Gmail id: bahesh.jagir@gmail.com

**Comment by yagniksangani** [comment]
@jagirbahesh I have given comment access for all translated docs.
cc: @devmuhib009

**Comment by pooja9712** [comment]
Hello @yagniksangani, @devmuhib009
I've checked your translation but you need to change it. Like first side original content and other side it's translation.
Here is referral url- https://docs.google.com/document/d/151DwbzwcefFPnrF0SLdg1L7Ej5loEVf_OK_gP1dw0D0/edit?usp=sharing
Please let me know for the same.

Thanks.

**Comment by yagniksangani** [comment]
OK @pooja9712 I will check on it.

**Comment by jagirbahesh** [comment]
Hello @devmuhib009  and @yagniksangani,

I have added suggestion in docs.
Kindly check and let me know if you have any questions.

Note: Here I have shared the Gujrati Local glossary words which is defined for Gujarati translation.
Please make sure we need to use in our translation.
https://translate.wordpress.org/locale/gu/default/glossary/ 

Thanks!

**Comment by yagniksangani** [comment]
Thanks @jagirbahesh for the suggestions. I have fixed all those in each doc, please verify it.

cc: @devmuhib009

**Comment by jagirbahesh** [comment]
@yagniksangani 

One one issue which we need to fix apart from that all is perfect.
https://docs.google.com/document/d/1j5Blj1OppKdtFYMG9T1uiFR8ByDmZrGG6LHI7_M6JUM/edit?disco=AAABQVnxJtc

Please check and let me know if you have any qustions.

Thanks!

**Comment by yagniksangani** [comment]
Thanks @jagirbahesh I have fixed that one.

Thank you

cc: @devmuhib009

**Comment by jagirbahesh** [comment]
Nice work @yagniksangani 
@devmuhib009  Now it is good to go.

**Comment by devmuhib009** [comment]
Hi @yagniksangani thanks for your hard work. I will publish the content soon and let you know. Also @jagirbahesh thanks for reviewing.

**Comment by devmuhib009** [comment]
Published all the lessons:
https://learn.wordpress.org/lesson/gu-wordpress-hooks/
https://learn.wordpress.org/lesson/gu-action-hooks/
https://learn.wordpress.org/lesson/gu-filter-hooks/
https://learn.wordpress.org/lesson/gu-working-with-hooks/

Thanks for translating all the contents. 
//published
