### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#2446]
### Requirements

- Single Lessons are indexed 
- Single Lesson social card assets (see [comment](https://github.com/WordPress/Learn/issues/2446#issuecomment-2116942010))
- Try to enable Lesson preview by default (see [comment](https://github.com/WordPress/Learn/issues/2446#issuecomment-2122057499))

**Comment by bph** [comment]
Thanks for making a note of this. If possible, I would add 
making single lessons have an enticing social card to the task list 
So they can be shared on LinkedIn or X or Mastodon, etc.

**Comment by jonathanbossenger** [comment]
@adamwoodnz during development of the learning pathway content, we discovered that Sensei has a featured to enable Lesson previews, which is what makes the individual lessons in the [Beginner WordPress User](https://learn.wordpress.org/course/beginner-wordpress-user/) course public.

Would it be possible to investigate whether we're able to simply enable this on all course lessons as default, instead of needing to enable it on each course lesson?

**Comment by adamwoodnz** [comment]
> Would it be possible to investigate whether we're able to simply enable this on all course lessons as default, instead of needing to enable it on each course lesson?

Sure, we can take a look as part of this.

**Comment by StevenDufresne** [comment]
> Single Lesson social card assets (see https://github.com/WordPress/Learn/issues/2446#issuecomment-2116942010)

Looking into this, lessons and courses appear to set the og:image to the featured image and since we have nice featured images, they look good:

| Example | Example |
|--------|--------|
| <img width="345" alt="Screenshot 2024-06-25 at 1 15 56 PM" src="https://github.com/WordPress/Learn/assets/1657336/fe5ef984-36a2-4bc1-94dd-e255c9ade504"> | <img width="344" alt="Screenshot 2024-06-25 at 1 15 27 PM" src="https://github.com/WordPress/Learn/assets/1657336/9e64f915-5910-48d2-9905-0a9326615d0a"> | 

However, the auto-generated descriptions are not great. I would suggest that content-wise, you create custom [excerpts for each course/lesson](https://senseilms.com/documentation/lessons/#excerpt).

**Comment by StevenDufresne** [comment]
> Would it be possible to investigate whether we're able to simply enable this on all course lessons as default, instead of needing to enable it on each course lesson?

This is saved in [meta field](https://github.com/Automattic/sensei/blob/e3ef1943bc965070fd59419f734af458035bcd81/includes/class-sensei-lesson.php#L630). You should be able to set it to `true` on lesson creation.

**Comment by adamwoodnz** [comment]
> > Would it be possible to investigate whether we're able to simply enable this on all course lessons as default, instead of needing to enable it on each course lesson?
> 
> This is saved in [meta field](https://github.com/Automattic/sensei/blob/e3ef1943bc965070fd59419f734af458035bcd81/includes/class-sensei-lesson.php#L630). You should be able to set it to `true` on lesson creation.

It's registered [here](https://github.com/Automattic/sensei/blob/e3ef1943bc965070fd59419f734af458035bcd81/includes/rest-api/class-sensei-rest-api-lessons-controller.php#L100), with no default value, and no way to set the default value to `true`, unless I'm missing something.

**Comment by adamwoodnz** [comment]
> It's registered [here](https://github.com/Automattic/sensei/blob/e3ef1943bc965070fd59419f734af458035bcd81/includes/rest-api/class-sensei-rest-api-lessons-controller.php#L100), with no default value, and no way to set the default value to `true`, unless I'm missing something.

Maybe we could deregister and reregister with a default value, but I think this is a post launch task.

Feels like all that remains is checking that single lessons are indexed. This might need checking post launch as I think single lessons might be excluded with the current theme activated. @renintw can I leave this with you?

**Comment by outdoor2kode** [comment]
No problem, I plan to first address the remaining reported tickets and fix some broken UI that gives a poor user experience. After that, I will check the indexing.

> However, the auto-generated descriptions are not great. I would suggest that content-wise, you create custom [excerpts for each course/lesson](https://senseilms.com/documentation/lessons/#excerpt).

This could also be specifically suggested to the training team to see if they want to enhance it?

**Comment by adamwoodnz** [comment]
> This could also be specifically suggested to the training team to see if they want to enhance it?

Yeah I believe they are aware that custom excerpts will improve presentation on the site generally, but copying @kathrynwp here to note that it's going to help with SEO too.

**Comment by kathrynwp** [comment]
> Yeah I believe they are aware that custom excerpts will improve presentation on the site generally, but copying @kathrynwp here to note that it's going to help with SEO too.

Totally. From what I understand, @jonathanbossenger and @westnz are making sure there are custom excerpts on all lessons belonging to the four Learning Pathways, but given other work on everyone's plate, they were not prioritizing older lessons. That said, it would still be ideal to make sure they all have custom excerpts over time.

There are also Community courses in the mix – perhaps @harishanker could coordinate getting custom excerpts added to those?

**Comment by pkevan** [comment]
> > > Would it be possible to investigate whether we're able to simply enable this on all course lessons as default, instead of needing to enable it on each course lesson?
> > 
> > 
> > This is saved in [meta field](https://github.com/Automattic/sensei/blob/e3ef1943bc965070fd59419f734af458035bcd81/includes/class-sensei-lesson.php#L630). You should be able to set it to `true` on lesson creation.
> 
> It's registered [here](https://github.com/Automattic/sensei/blob/e3ef1943bc965070fd59419f734af458035bcd81/includes/rest-api/class-sensei-rest-api-lessons-controller.php#L100), with no default value, and no way to set the default value to `true`, unless I'm missing something.

Not sure if this is still relevant, but you can set the default value of a post meta field via the filter here: https://github.com/WordPress/wordpress-develop/blob/6.6/src/wp-includes/meta.php#L717

**Comment by outdoor2kode** [comment]
> > > > Would it be possible to investigate whether we're able to simply enable this on all course lessons as default, instead of needing to enable it on each course lesson?
> > > 
> > > 
> > > This is saved in [meta field](https://github.com/Automattic/sensei/blob/e3ef1943bc965070fd59419f734af458035bcd81/includes/class-sensei-lesson.php#L630). You should be able to set it to `true` on lesson creation.
> > 
> > 
> > It's registered [here](https://github.com/Automattic/sensei/blob/e3ef1943bc965070fd59419f734af458035bcd81/includes/rest-api/class-sensei-rest-api-lessons-controller.php#L100), with no default value, and no way to set the default value to `true`, unless I'm missing something.
> 
> Not sure if this is still relevant, but you can set the default value of a post meta field via the filter here: https://github.com/WordPress/wordpress-develop/blob/6.6/src/wp-includes/meta.php#L717

I've added all the related discussions about this to a newly open issue https://github.com/WordPress/Learn/issues/2807.
