### ISSUE TITLE
Themes and user privacy

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2449]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Themes and user privacy
- Topic description: Learn how themes can impact user privacy, and what the theme developer needs to be aware of.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate.

# Learning Objectives

- Explain how Privacy features in WordPress can affect theme development
- Describe steps to take to ensure themes work with these Privacy features

# Related Resources and Other Notes
- https://wordpress.org/news/2018/05/wordpress-4-9-6-privacy-and-maintenance-release/
- https://developer.wordpress.org/themes/advanced-topics/privacy/

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/theme-developer-learning-pathway/06-Privacy/01-Themes-and-user-privacy.md

**Comment by jonathanbossenger** [comment]
Video for review: 

https://github.com/WordPress/Learn/assets/180629/d8ecebda-1321-483f-a11b-e4ab52fdb226

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great stuff

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/06/07/themes-and-user-privacy/

**Comment by jonathanbossenger** [comment]
https://youtu.be/fsWaaC4ajFI

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/themes-and-user-privacy/

//publish
