### ISSUE TITLE
Feedback - Outdated Content on - "Exploring WordPress 6.5"

### ISSUE THREAD

**Issue by devmuhib009** [WordPress/Learn#2450]
## Type of feedback
Reporting an error (such as outdated information)

## Description

1. The cover side panel no longer looks like this.
2. When clicking on an Image block, the Box shadow style settings do not appear. The sidebar does not appear as it does in the video for 6.5.3.

## Other information (optional)

This content feedback is based on Helpscout Tickets: #177548 & #177546 and reported by Jonathan Hammond

**Comment by jonathanbossenger** [comment]
@digitalchild @kaitohm I don't think "Exploring version X" videos should be updated, otherwise we'll be updating them in perpetuity.

**Comment by kaitohm** [comment]
I agree. These videos were created to introduce that version at the time of launch. Let's prioritize updating other content.
