### ISSUE TITLE
Meeting Agenda MAY 23, 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2454]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @lada7042 ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- May 23 - @Zeel Thakkar
- May 30 – @jagir Bahesh
- June 6 – @speedyprem
- June 13 – @Zeel Thakkar

**2. Looking for feedback**

- Would love everyone's feedback. With the introduction of the Learning Pathways. 
    - What content are we obligated to leave on Learn? Ex. Classic editor
    - Until what version do we need to support?
- [Training's 2024 goals](https://make.wordpress.org/training/2024/02/05/training-team-goals-for-2024/)
We'd like to send out a survey to the 10,000+ members of the [Meetup.com Online Workshop group](https://www.meetup.com/learn-wordpress-online-workshops/) to get their input. What do folks think about these three questions?
What is currently working well with Online Workshops?
What would you like to see changed with Online Workshops?
What Online Workshop topic(s) would you like to attend?
Answer in thread 🧵 
1️⃣ questions good 2️⃣ too vague, ask more specific questions 3️⃣ here is my feedback
- New handbook page - [Video Best Practices](https://make.wordpress.org/training/handbook/guidelines/video-best-practices/) :green_book:
[@zoonini](https://wordpress.slack.com/team/U02S3F8EK) has published a new page in the Resources section of the handbook called [Video Best Practices](https://make.wordpress.org/training/handbook/guidelines/video-best-practices/), which replaces the previous video and sound information in the [Creating a lesson page](https://make.wordpress.org/training/handbook/lessons/creating-a-lesson/#step-5-choose-video-software-and-ensure-clear-sound). This is intended as a starting point to help content creators create good quality video recordings for lessons on [Learn.WordPress.org](http://learn.wordpress.org/).
Please take a look at the new guide and share any feedback in [this thread](https://wordpress.slack.com/archives/C02RW657Q/p1715818867507559) :thread:

**3. Looking for volunteers**

- 👀 Is this the volunteer project you have been looking for? We are looking for someone/or several people to triage the [spreadsheet](https://docs.google.com/spreadsheets/d/15ZMa3GFLb7Pp9n2j32vxnojctdWrT0WRzheo56Q_qtk/edit?usp=sharing) of all the available tutorials and recommend which ones to keep, modify or deprecate.  There are only 255.  
-  [Brainstorming WordCamp Europe 2024 Contributor Day tasks](https://make.wordpress.org/training/2024/04/23/brainstorm-table-lead-wordcamp-europe-2024-contributor-day/). Please leave your ideas on the post by May 27th.
- Thank you to the following team members for volunteering to be WCEU Training Team Contributor Table
Onsite - Jamie and Sumit
Online - Muhibul and Jagir

**4. Updates from last week's dev-squad triage session**

Last week's dev squad session was held a week later than usually, due to the fact that most members were not available on the usually scheduled week. 

We discovered that there were no new bugs or PRs to triage. 

We therefore focused on any open PRs that were in need of a review/test:

- #1621 was merged, as it had already been previous reviewed.
- #1936 has been reviewed, and requires a refresh from the PR creator
- #2222 and #2359 seem to be PRs that fix the same issue. It would be great if someone with development experience could review these, and propose a way forward.
- #2368 needs a review. 

We would like to call on any developers with experience of the Learn WordPress codebase to help us get these PRs over the line.

**5. Other news**

- Learn redesign update
from @adamwood This week we made good progress, finalizing some technical decisions and shipping some important pieces:
The Learning Pathway taxonomy was created, allowing Courses to be classified as one of 4 Learning Pathways (designer, user, developer, contributor), and thereby be included on the new home page and taxonomy pages.
The [Online Workshops page](https://learn.wordpress.org/test/online-workshops/)
As always, you can follow along wit the build on the [staging site](https://learn.wordpress.org/test/) and [project board](https://github.com/orgs/WordPress/projects/40/views/26), and leave feedback on the [designs](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3199-20648&m=dev).
- As part of [the Learn Redesign project](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/), content types on Learn are getting streamlined. With [the Lesson content type](https://make.wordpress.org/training/handbook/lessons/) becoming the focus of Learn, the [Lesson Plan](https://make.wordpress.org/training/handbook/guidelines/lesson-plans/) and [Tutorial](https://make.wordpress.org/training/handbook/guidelines/tutorials/) handbook pages have been moved to under the [Resources section](https://make.wordpress.org/training/handbook/guidelines/) in the handbook.

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 9 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 27 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 31 issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have 0 issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 16 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: 
- Props:  Jamie, Sumit, Muhibul and Jagir for volunteering for Contributor day 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
As we near the tentative launch date of July 2024, we need volunteers to help with creating a marketing campaign for Learning Pathways. 
[@abhanonstopnewsuk](https://wordpress.slack.com/team/U6R2E3Y9Y)
 volunteered last week, and it would be great if we could have another 2 people or so join. Please comment in this thread if you’d like to help out :raised_hands::skin-tone-3:
Please read updated comments and add your thoughts in the thread 🧵 
- Project_2
  - details

## 5. Faculty Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by Zeelthakkar1207** [comment]
Hey @lada7042 
I am interested as a Meeting note taker for June 13.

**Comment by abhansnuk** [comment]
Not sure which part of the agenda this would come under. Possibly 5) as it is my update for Faculty focus. 

On the Learning Pathways collaboration with marketing, discussion to clarify this can be found on the Slack thread below to help prepare a GitHub ticket and a collaboration session. The clarification will help with the focus of the ticket and links to any background reading it needs to help people get involved. 
https://wordpress.slack.com/archives/C02RW657Q/p1715820610795189

More volunteers will be needed so it would be good if this can be highlighted at the Training Meeting please too. Thanks.

**Comment by ghost** [comment]
@abhansnuk I have added it to the other projects section with a link to the Slack conversation. Thank you for volunteer to lead this project.

**Comment by ghost** [comment]
@jonathanbossenger do you have any notes from last week's dev-squad meeting?

**Comment by ghost** [comment]
Link to start of Slack meeting- https://wordpress.slack.com/archives/C02RW657Q/p1716422432629439

**Comment by ghost** [comment]
Meetup recap published- https://make.wordpress.org/training/2024/05/29/training-team-meeting-recap-23rd-may-2024/
