### ISSUE TITLE
Feedback - Update node version number on the lesson.

### ISSUE THREAD

**Issue by laxmariappan** [WordPress/Learn#2458]
## Type of feedback

//content

## Description

https://learn.wordpress.org/lesson/introducing-create-block/ 

Please update the version number mention on this lession.

`nvm use 14` - I think this is outdated.

I got errors with this version and node 20+ worked

## Screenshots or screen recording (optional)

![image](https://github.com/WordPress/Learn/assets/22427070/0501096e-e763-48ec-a377-ab7b21fe974a)

**Comment by jonathanbossenger** [comment]
Added a note to the lesson about node versions.
