### ISSUE TITLE
Tutorial : How to enable/disable WP Debug (Bangla)

### ISSUE THREAD

**Issue by faisalahammad** [WordPress/Learn#2459]
# Details

- Topic description: In many cases, we have to enable debugging to find the root cause of an issue, such as a critical error generated by a theme/plugin or custom code. Sometimes we also have to disable debugging to hide PHP warnings that are displayed when visiting the website. In this video, I'll show you how to easily enable/disable WP Debug.
- Audience (User, Developer, Designer, Contributor, etc.): Users
- Learning objectives (What will the learner be able to do as a result of this content?): The learner will be able to enable/disable WP Debug to troubleshoot on their website.
- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Tutorial
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): Yes

# Related Resources
- https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by devmuhib009** [comment]
//tutorial

**Comment by kaitohm** [comment]
This is a great topic, @faisalahammad 👍 

Could you make this as a Lesson, please? The training team is now moving away from Tutorials, and are making Lessons instead. Lessons are still a video format content, but becomes a different post type on Learn. You will want to create this, following the steps listed here: https://make.wordpress.org/training/handbook/lessons/

The topic you've suggested is very similar to the recently published English content: #2378 Would you like to record a Bangla video, but using a translated version of the script from #2378? You would still need to create Bangla visuals for the video, but you could follow #2378 as an example to save time.

How does all that sound?

**Comment by Piyopiyo-Kitsune** [comment]
Hi @faisalahammad -- checking in here-- did you see Ben's comment above? :-)

**Comment by faisalahammad** [comment]
Sorry @Piyopiyo-Kitsune and @bsanevans,

I'd like to choose another topic and create a lesson later; it will be easier for me. Could you please close this topic? Thank you.
