### ISSUE TITLE
Bengali translation for Tutorial "Managing Settings: Media"

### ISSUE THREAD

**Issue by gmrafi** [WordPress/Learn#2463]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/managing-settings-media/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/970
- Language you'll be translating to: Bangla/Bengali
- Have you arranged for someone to review this translation?: Yes or No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by gmrafi** [comment]
I just translated the original content, here is the [Doc file link](https://docs.google.com/document/d/1_7XkPInE5VvPN88yuEnfa1NOqAGiUSP2XDPytRJ9B30/edit?usp=sharing)

**Comment by devmuhib009** [comment]
> ব্যাকইন্ড

ব্যাকএন্ড

> বাক্স

বক্স

> যদিনা

যদি না

> অনির্বাচন

আনসিলেক্ট

উপরে উল্লেখিত বানানগুলো ঠিক করতে হবে, বাকি সবকিছু আমার কাছে ভাল লেগেছে। এগুলো ঠিক করে কমেন্টে জানান।

**Comment by gmrafi** [comment]
Thank you for your suggestions and corrections. I have just implemented these suggestions. Here is the revised version. [file link](https://docs.google.com/document/d/1_7XkPInE5VvPN88yuEnfa1NOqAGiUSP2XDPytRJ9B30/edit?usp=sharing)

**Comment by devmuhib009** [comment]
Looking nice, ready for publish. Please give your WordPress username so I can add you to the learn.wordpress.org website.

**Comment by devmuhib009** [comment]
From your slack, I've added you to the website, please accept the invitation and draft the post using below instructions. 
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video
Please complete from step 5 to others and ask me here if you need any help. Thanks

**Comment by gmrafi** [comment]
Here is the draft of the post: https://learn.wordpress.org/wp-admin/post.php?post=254638&action=edit

**Comment by devmuhib009** [comment]
Hi, You've drafted in wrong content area. It will not publish under posts, it will be published under tutorial section. I've drafted it on [tutorial section](https://learn.wordpress.org/wp-admin/post.php?post=254645&action=edit) again.

Can you complete the subtitle submission part, so we can publish it together?
Subtitle this video: https://wordpress.tv/2022/10/19/managing-settings-media/
Instructions: https://wordpress.tv/subtitle/?video=114079

**Comment by gmrafi** [comment]
Thank you so much for correcting the drafting part and moving the content to the correct section. I appreciate your guidance, and I have completed the subtitle submission part as per the video instructions and submitted it.

**Comment by devmuhib009** [comment]
Tutorial published here: https://learn.wordpress.org/tutorial/bn-managing-settings-media/
Thanks for your afford. 
//publish
