### ISSUE TITLE
Tools for accessibility testing

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2465]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Tools for accessibility Testing
- Topic description: Cover tools and WordPress plugins that allow for accessibility testing.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

1. List online tools that can be used for accessibility testing.
2. Identify WordPress plugins that can be used for accessibility testing.

# Related Resources and Other Notes

### Automation Code

//lesson

**Comment by jonathanbossenger** [comment]
Original script: #2188

**Comment by jonathanbossenger** [comment]
Markdown version of script for recording: https://github.com/jonathanbossenger/wp-content/blob/main/theme-developer-learning-pathway/05-Accessiblity/02-tools-for-accessiblity-testing.md

**Comment by jonathanbossenger** [comment]
@ironnysh tagging you here so I can assign you to the ticket also.

**Comment by ironnysh** [comment]
Thanks, @jonathanbossenger

**Comment by jonathanbossenger** [comment]
Video for review: 

https://github.com/WordPress/Learn/assets/180629/104ed4da-8b02-496a-b59e-cff4d05b7e10

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Fun to see this taking shape 🎉 Thanks, @jonathanbossenger!

I spotted a few misspellings:
- Accessibility is capitalized in the lesson title (on all slides).
- On the testing slide (~2:10):
  - Try navigating your theme with a keyboard only **_?_** --remove the question mark
  - Change the **_colour_** scheme via Dev Tools. --color is spelled in British English.

**Comment by jonathanbossenger** [comment]
Thanks, @ironnysh. I will fix these (my slides are always my weak spot).

**Comment by jonathanbossenger** [comment]
Updated video: 

https://github.com/WordPress/Learn/assets/180629/fa6d0a9e-a30d-495c-9a66-536a0c3f7fa3

**Comment by hazeldrio** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Additional comment:
1. On the last slide consider recapping best practices for "accessibility testing" -  that helps make themes useable by everybody on the web.
2. I think the video should be labeled "beginner" not "intermediate"
3. At Contributor Day, I discussed this with @bsanevans. The video doesn't delve into the online accessibility tools enough. It is too short and too general. Please consider going into more detail on how to use the highlighted tools.
4. I think you could create a blog post with the current video transcript.

**Comment by jonathanbossenger** [comment]
Thanks for the review @hazeldrio 

> I think the video should be labeled "beginner" not "intermediate"

The lesson is part of a module in the intermediate theme developer learning pathway, so it's not specifically labeled as intermediate. We just felt it made more sense in this learning pathway, but that could always be changed in the future. 

> The video doesn't delve into the online accessibility tools enough. It is too short and too general. Please consider going into more detail on how to use the highlighted tools.

You're right there, and it would be great to be able to add lessons on how to use each tool. Is this perhaps something you'd be interesting in helping to create?

**Comment by ironnysh** [comment]
> going into more detail on how to use the highlighted tools

@jonathanbossenger, @hazeldrio, just wanted to mention that this lesson is an abridged version/variation on [this tutorial](https://github.com/WordPress/Learn/issues/2201) (from the _User_ Learning Pathway). The original is more elaborate and includes screenshots etc., but doesn't cover the manual testing.

Maybe there's a way to combine these two?

**Comment by jonathanbossenger** [comment]
@ironnysh, what we could do, once [that lesson is published](https://github.com/WordPress/Learn/issues/2201), is add an update to the end of this lesson.

What I will do is add this to the list of [Todos](https://github.com/WordPress/Learn/issues/2045#todos) that we're using to track any updates that surface during the course of lesson development

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/06/18/tools-for-accessibility-testing/

**Comment by jonathanbossenger** [comment]
https://youtu.be/7cCfX5tXJcU

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/tools-for-testing-theme-accessibility/

**Comment by jonathanbossenger** [comment]
//publish
