### ISSUE TITLE
Bangla translation for "How to use the spacer block"

### ISSUE THREAD

**Issue by ShiponKarmakar** [WordPress/Learn#2466]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/how-to-use-the-spacer-block/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by ShiponKarmakar** [comment]
Dear Translation Reviewer, 
I have translated this content. [Please review it here.](https://docs.google.com/document/d/e/2PACX-1vTAwm749PWeI1vzxab3ujmKZRNNVx-H4o2MU8Z0TK_LlrW8Hvh2ZPVRcwIDOrLPh9GSFzAWTRzya5K3/pub)

**Comment by ShiponKarmakar** [comment]
.

**Comment by devmuhib009** [comment]
I'll review the content soon and share the feedback as well.

**Comment by devmuhib009** [comment]
> কতরে

করতে

> যা যা শিখবেন:

শেখার ফলাফলঃ

> বোঝার কিছু প্রশ্নসমূহ

সম্পূরক প্রশ্ন

> প্রধান পৃষ্ঠায়

মেইন পেজ 
* সমস্ত কন্টেন্টে পেজ অথবা পৃষ্ঠা যে কোন একটি ব্যবহার করতে হবে

> গ্রন্থাগারে 

লাইব্রেরী

> তালিকা ভিউতে

লিস্ট ভিউতে

> মৌলিক টুলস

বেসিক টুলস

> বোতামটি

বাটনটি

> ইননার

ইনার

উপরে উল্লেখিত পরিবর্তনগুলো করে আমাকে জানান। ধন্যবাদ

**Comment by ShiponKarmakar** [comment]
I already fix all issues, please check now.

**Comment by devmuhib009** [comment]
As you are already added to the Learn WordPress website please draft the post using below instructions.
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video
Please complete from step 5 to others and ask me here if you need any help. Thanks

**Comment by ShiponKarmakar** [comment]
I have drafted this on learn.wordpress.org [please check here](https://learn.wordpress.org/wp-admin/post.php?post=254658&action=edit)

**Comment by devmuhib009** [comment]
Thanks for your effort. Tutorial has been published here : https://learn.wordpress.org/tutorial/bn-how-to-use-the-spacer-block/
//published
