### ISSUE TITLE
How to Change the WordPress Administration Email Address Without email Verification

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/Learn#2469]
# Details

- Topic Description: How to Change the WordPress Administration Email Address Without email Verification
- Audience (User, Developer, Designer, Contributor, etc.): **User, Developer, Designer, Contributor**
- Learning objectives (What will the learner be able to do as a result of this content?): **The user can easily update the Administration Email Address Without email Verification.**
- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): **Tutorial**
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): **Yes**

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by sumitsinghwp** [comment]
The video is already ready and uploaded on WPTV - https://wordpress.tv/2024/05/20/how-to-change-the-wordpress-admin-email-without-verification/

Drafted content below.

Updating the WordPress admin email directly from the `options.php` page in the WordPress admin panel is a straightforward process. This method allows you to change the email without the need for email verification. Here are the detailed steps:

### Step-by-Step Guide to Update the WordPress Admin Email from `localhost/wp-admin/options.php`

#### Step 1: Access Your WordPress Admin Dashboard
1. **Open your web browser** and navigate to your local WordPress installation.
2. **Log in to your WordPress admin dashboard** by going to `http://localhost/wp-admin/` and entering your credentials.

#### Step 2: Navigate to `options.php`
1. **In your WordPress admin dashboard**, type `http://localhost/wp-admin/options.php` directly into the address bar and press Enter. This will take you to the options configuration page where you can directly edit various WordPress settings.

#### Step 3: Locate the Admin Email Field
1. **Scroll down** or use your browser’s find function (Ctrl+F or Command+F) to locate the `admin_email` field. This field contains the current admin email address.

#### Step 4: Update the Admin Email
1. **Edit the value** in the `admin_email` field to the new email address you want to use.
2. **Scroll to the bottom of the page** and click the "Save Changes" button to apply the new email address.

#### Step 5: Verify the Change
1. **Navigate to "Settings" > "General"** in the WordPress admin dashboard to confirm that the new admin email address is displayed.
2. Optionally, you can also check if admin emails are being sent to the new address by triggering a password reset or another notification.

### Conclusion
By following these steps, you can quickly update the WordPress admin email directly from the `options.php` page in your admin dashboard. This method bypasses the need for email verification and ensures the change is applied immediately.

**Comment by Piyopiyo-Kitsune** [comment]
@jonathanbossenger is this something that will be covered in your developer lessons?

**Comment by jonathanbossenger** [comment]
@Piyopiyo-Kitsune this was not something I had considered for a couple of reasons.

1. If I were changing the admin_email on a live/production site, I'd rather have the email confirmation requirement in place in case anything goes wrong.
2. While the All Settings page (`/wp-admin/options.php`) does indeed exist, it does come with a warning: "Warning: This page allows direct access to your site settings. You can break things here. Please be cautious!"
3. If I really wanted to edit the admin user's email address directly, I would rather do it via WP-CLI or the database.

**Comment by kaitohm** [comment]
Based on Jonathan's feedback, I'm going to close this issue as something we won't prioritize.
