### ISSUE TITLE
Meeting Agenda May 30, 2024

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#2470]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- May 30 – @jagirbahesh 
- June 6 – @speedyprem
- June 13 – @Zeel Thakkar
- June 20 – @jagirbahesh 

**2. Looking for feedback**

- [Proposal: Learn WordPress Content Maintenance Process](https://make.wordpress.org/training/2024/05/29/proposal-learn-wordpress-content-maintenance-process/)

**3. Looking for volunteers**

- We are looking for volunteers to triage the [spreadsheet](https://docs.google.com/spreadsheets/d/15ZMa3GFLb7Pp9n2j32vxnojctdWrT0WRzheo56Q_qtk/edit?usp=sharing) of all the available tutorials and recommend which ones to keep, update or deprecate.

**4. Other news**

- [WordCamp Europe 2024 Contributor Day](https://make.wordpress.org/training/2024/05/28/wordcamp-europe-2024-contributor-day/)
- The Training Team Reps are drafting a survey to send out to our [Meetup.com](http://meetup.com/)[ Online Workshop group](https://www.meetup.com/learn-wordpress-online-workshops/)
- [We have a new handbook page](https://make.wordpress.org/design/handbook/resources/figma-thumbnail-generator/) on how to create video and event thumbnails for Learn WordPress and our Online Workshop group.
- Learn was mentioned in WordPress Briefing[ Episode 80: Unlocking Your WordPress Potential with Learn WordPress Tools](https://wordpress.org/news/2024/05/episode-80-unlocking-your-wordpress-potential-with-learn-wordpress-tools/)
- There will be an online workshop called "Recording awesome videos for WordPress demos, courses, and more" in which we'll go through the new [Video Best Practices handbook](https://make.wordpress.org/training/handbook/guidelines/video-best-practices/) content:
https://www.meetup.com/learn-wordpress-online-workshops/events/301277091/

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 8 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 26 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 33 issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have 0 issues requiring development -- All issues are clear for the 6th week in a row! :clap:

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 16 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: 
- Props: 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - [May 27th update](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4255) -- tl;dr thumbnail generator work is complete, and development progresses with the landing page receiving its first update with the new design

## 5. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jagirbahesh** [comment]
Hello @Piyopiyo-Kitsune 

I am interested as a meeting note taker for June 20.
Thank you!

**Comment by kathrynwp** [comment]
Update on Learn.WordPress.com remake: 
https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4255

There will be an online workshop called "Recording awesome videos for WordPress demos, courses, and more" in which we'll go through the new [Video Best Practices handbook](https://make.wordpress.org/training/handbook/guidelines/video-best-practices/) content:
https://www.meetup.com/learn-wordpress-online-workshops/events/301277091/

**Comment by ghost** [comment]
Meeting recap published- https://make.wordpress.org/training/2024/06/05/training-team-meeting-recap-30th-may-2024/
