### ISSUE TITLE
Add fallback image in cards for Courses and Lessons

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#2474]
Currently when a Course or Lesson has no featured image there is empty space in the cards:

![Screenshot 2024-05-29 at 2 31 11 PM](https://github.com/WordPress/Learn/assets/1017872/a969a1c5-4fa1-4d9f-a5fb-3ff7b5fb59ba)

New Lessons or Courses displayed on the front page are unlikely to have this missing, but older lessons shown in the archive are.

We need a solution which creates a block with a fallback image for these cards.

@WordPress/meta-design could you please advise on what this should look like?

**Comment by fcoveram** [comment]
I can work on an image in the following days and share it here

**Comment by fcoveram** [comment]
Here is a visual for this

<img width="1280" alt="Default Learn thumbnail" src="https://github.com/WordPress/Learn/assets/895819/bebb35b6-ff92-4ede-b437-ff1203717ed5">

**Comment by kathrynwp** [comment]
Thank you for working on fallback images for Courses and Lessons!

While the Training team is going to try to create unique thumbnails for all Tutorials – and this content type is eventually planned to be retired – it might be good to also add fallback for the Tutorial CPT as well, just in case.

**Comment by adamwoodnz** [comment]
Might be able to use this code from the old theme https://github.com/WordPress/Learn/blob/033b1ee56909f3648175b891923696fe0914a800/wp-content/themes/pub/wporg-learn-2020/functions.php#L1130

**Comment by adamwoodnz** [comment]
> Thank you for working on fallback images for Courses and Lessons!
> 
> While the Training team is going to try to create unique thumbnails for all Tutorials – and this content type is eventually planned to be retired – it might be good to also add fallback for the Tutorial CPT as well, just in case.

I'll use this image for all cards, regardless of post type, unless I hear otherwise.
