### ISSUE TITLE
Bangla translation for "Applying duotone filters to change color effects"

### ISSUE THREAD

**Issue by ShiponKarmakar** [WordPress/Learn#2477]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/applying-duotone-filters-to-change-color-effects/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: devmuhib009
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by ShiponKarmakar** [comment]
Dear Translation Reviewer,
I have translated this content. [Please review it here.](https://docs.google.com/document/d/e/2PACX-1vTq1ejUOMfPq8bvEyeT86ggdPHqXRQkvHhLjK3ZpXQbU60Z_kfyw10Fq1V6HAHnN4aXsmMlk9Jmpa5D/pub)

**Comment by devmuhib009** [comment]
> ডুওটোনে ফিল্টার ব্যাবহার করে কিভাবে কালার ইফেক্ট ব্যবহার করবেন

ডুয়োটোন ফিল্টার ব্যবহার করে কিভাবে কালার ইফেক্ট চেঞ্জ করতে হয়

The translation is need to be more readable. Please take care of spellings and make it readable as much as possible. ডুওটোন or ডুয়োটোন, but don't add both. 
Thanks

**Comment by ShiponKarmakar** [comment]
I already fix all issues, please check now.

**Comment by devmuhib009** [comment]
> উচ্চ-কনট্রাস্ট

হাই-কনট্রাস্ট

> প্রতিলিপি

ট্রান্সক্রিপ্ট

**Comment by ShiponKarmakar** [comment]
Thanks for your suggestion, 
I have solved all spelling issues, please check now.

**Comment by devmuhib009** [comment]
Thanks for solving the issues. Please draft the post and submit the subtitle file in WordPress TV. Thanks

**Comment by ShiponKarmakar** [comment]
I have drafted this on learn.wordpress.org [please check here](https://learn.wordpress.org/wp-admin/post.php?post=254826&action=edit)

**Comment by devmuhib009** [comment]
Tutorial Published: https://learn.wordpress.org/tutorial/bn-applying-duotone-filters-to-change-color-effects/

//published
