### ISSUE TITLE
Bangla translation for "Exploring category templates with block themes"

### ISSUE THREAD

**Issue by ShiponKarmakar** [WordPress/Learn#2478]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/exploring-category-templates-with-block-themes/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Bangla
- Have you arranged for someone to review this translation?:No
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by ShiponKarmakar** [comment]
Dear Translation Reviewer,
I have translated this content. [Please review it here](https://docs.google.com/document/d/e/2PACX-1vRNIWgYGt7HSmlUgOdVGTloJYdRFymlTB6_Uc6CQdl_r8nvQq7J4U0DbXwxgXYB31FqHdlnC_qiU_Y0/pub)

**Comment by ShiponKarmakar** [comment]
I have also Draft this post on [learn.wordpress.org](https://learn.wordpress.org/wp-admin/post.php?post=254901&action=edit)

**Comment by devmuhib009** [comment]
ok, let me check.

**Comment by devmuhib009** [comment]
Thanks for submitting subtitle file and drafting the post. Tutorial published here: https://learn.wordpress.org/tutorial/bn-exploring-category-templates-with-block-themes/

//published
