### ISSUE TITLE
RTL Audit

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#2483]
- [x] Change to a right to left language and browse the site
- [x] Log issues as comments below
- [x] Fix issues

**Comment by ironnysh** [comment]
Hi @adamwoodnz, happy to help with this audit.
As a native Hebrew speaker, RTL is the bane of my existence 😅

**Comment by adamwoodnz** [comment]
> Hi @adamwoodnz, happy to help with this audit. As a native Hebrew speaker, RTL is the bane of my existence 😅

Awesome! I'll move this into 'To do' once we're far enough along with the build to start. Thanks 🙂

**Comment by adamwoodnz** [comment]
Hi @ironnysh I think this is ready thanks

**Comment by ironnysh** [comment]
Great, thanks for the heads-up, @adamwoodnz!

Would screenshots work for logging the issues?

**Comment by adamwoodnz** [comment]
> Would screenshots work for logging the issues?

Yes please, with direct links to the page in question.

**Comment by ironnysh** [comment]
Hey @adamwoodnz, I checked the site as a logged-in and random user on desktop Safari and Chrome in different breakpoints.
Here's a list of findings:

## Lesson page
**URL:** https://learn.wordpress.org/lesson/how-to-find-help-with-wordpress-2/ (on all courses)
![lesson-inside-lp](https://github.com/WordPress/Learn/assets/63248335/29a824f9-34cb-4de2-8753-1249dcdb1ae0)
***
## Top nav / main nav
**URL:** https://learn.wordpress.org/ (across the site, different bugs depending on the breakpoint)
601-889 pixels breakpoint:
![drop-down-menu](https://github.com/WordPress/Learn/assets/63248335/5607146c-3208-4d41-b4fc-60be3e439aaf)

Mobile:
![mobile-menu](https://github.com/WordPress/Learn/assets/63248335/faa620d9-8bf8-45d2-9391-d6b2aea27259)

Standard desktop:
![top-menu-lp](https://github.com/WordPress/Learn/assets/63248335/2533ded7-6090-400e-8004-5c81f6ce0283)
![top-nav](https://github.com/WordPress/Learn/assets/63248335/28b6ca07-f1d1-4598-894a-fad069a571bb)

***
## Learning Pathway homepage
**URL:** https://learn.wordpress.org/learning-pathways/
![lp-homepage](https://github.com/WordPress/Learn/assets/63248335/ace0bf15-ccce-4e09-88fb-68d06a804446)
***

## Online workshops homepage
**URL:** https://learn.wordpress.org/online-workshops/
![spacing-workshops-page](https://github.com/WordPress/Learn/assets/63248335/dbf5967e-1ae6-4c83-b1d1-578bb7fcaae6)
***

## Course homepage
**URL:** https://learn.wordpress.org/course/beginner-wordpress-developer/ (on all courses)
![course-homepage_top](https://github.com/WordPress/Learn/assets/63248335/56e44707-b918-4b84-a0b8-3aa8cc6863a3)
![course-homepage](https://github.com/WordPress/Learn/assets/63248335/f64921b1-b2d4-499c-a638-cb691d921096)
***
## My courses
**URL:** https://learn.wordpress.org/my-courses/
![my-courses](https://github.com/WordPress/Learn/assets/63248335/88e57660-6553-4c34-ae98-bfd5f1c20053)
***

## Quiz
URL: https://learn.wordpress.org/quiz/wordpress-taxonomies-2/ (on all courses)
![quiz-spacing](https://github.com/WordPress/Learn/assets/63248335/9fd47c3c-f19f-4be4-926a-c8e752366c57)
***
## Query filter
**URLs:** https://learn.wordpress.org/lessons/, https://learn.wordpress.org/courses/, https://learn.wordpress.org/learning-pathway/developer/ (wherever there’s the `wp-block-wporg-query-filter` class):
![query-filter-cut](https://github.com/WordPress/Learn/assets/63248335/4d0a0e86-1d67-441a-9cec-38b1e7eb64a8)
![query-filter-cut_2](https://github.com/WordPress/Learn/assets/63248335/03f4bb22-756d-4ce1-b2d1-62a354644b21)
![query-filter_wrong-direction](https://github.com/WordPress/Learn/assets/63248335/04bad2b2-a0b7-4f03-b859-ad2ac96fa275)

**Comment by ryelle** [comment]
Some of these, especially the "Top nav / main nav" items, appear to be site-wide issues (across all wporg sites). I can handle these, since they're generally components I'm familiar with.

Local nav
- [x] Misaligned submenus
- [x] Missing left/right space on local nav
- [x] My courses has poor spacing with dot https://github.com/WordPress/Learn/commit/9661a4e67d21a73c1848145c0d5fe364f820b3af
- [x] Local nav W logo on the wrong side

My courses
- [x] Query filter misaligned (this is due to https://github.com/WordPress/wporg-parent-2021/commit/2a95d1718ad2d1a3fc54a3f6f97fbfa8e45decc2 which shouldn't apply when the layout is flex) https://github.com/WordPress/wporg-parent-2021/commit/357ff01f5d453a63308d774b06164b38730e3502 (not yet deployed)

Query Filters
- [x] Dropdown alignment should be switched on RTL

**Comment by adamwoodnz** [comment]
> Hey @adamwoodnz, I checked the site as a logged-in and random user on desktop Safari and Chrome in different breakpoints.

Thanks! Great work.
