### ISSUE TITLE
Online Workshop: How to install WordPress on an Ubuntu VPS

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2490]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Online Workshop
- Content title: How to install WordPress on an Ubuntu VPS
- Topic description: A step by step walkthrough on how to set up a WordPress installation on an Ubuntu VPS (Virtual Private Server)
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

- Summarize what a VPS is, why you might use it, and how to get one
- Identify key skills and knowledge required to manage a VPS
- Install and configure the required software for hosting a WordPress site, covering the Apache, Nginx, and OpenLiteSpeed servers
- Install WordPress as a single site
- Convert the single site to a multisite install, using the sub domain method.

# Related Resources and Other Notes
- Will cover both single-site installs as well as setting up a multisite using the subdomain method.
- Will cover Apache, Nginx, and OpenLiteSpeed
- May require different editions (multiple live streams) for the different web server configurations

### Automation Code

//online-workshop

**Comment by jonathanbossenger** [comment]
In a recent YouTube comment on a [learning pathway lesson](https://www.youtube.com/watch?v=LiYSx4gH0EQ&list=PL1pJFUVKQ7ETYqC5F_z4BOJ4FoT7xZy_u&index=50), a viewer requested a tutorial on the above topic. 

I'm considering covering this over two live streams hosted as Learn WordPress online workshops.

- Is this a good topic for a Learn WordPress online workshop?
- What concerns, if any, would you have around hosting this as an online workshop in a live stream format?

**Comment by kathrynwp** [comment]
I definitely think some folks might find interest in how to set up a WordPress multisite. I do tend to think it's probably more of a niche topic with a more limited audience. I also think if you were to run this workshop, it shouldn't target one specific server setup or operating system, so you don't further limit your potential audience. Making it platform-agnostic will ensure the workshop is useful to a wider range of people.

**Comment by jonathanbossenger** [comment]
@kathrynwp some great points here.

What might make more sense is if I cover both installing WordPress and converting it to a multisite, as well as covering all the common web server platforms (Apache, Nginx, and OpenLiteSpeed).

**Comment by jonathanbossenger** [comment]
Updated the title, description, and learning outcomes to reflect the planned content

**Comment by kathrynwp** [comment]
> What might make more sense is if I cover both installing WordPress and converting it to a multisite, as well as covering all the common web server platforms (Apache, Nginx, and OpenLiteSpeed).

@jonathanbossenger Agreed 100%!

**Comment by jonathanbossenger** [comment]
Updated the title, description, and learning outcomes to reflect the planned content

**Comment by jonathanbossenger** [comment]
Building a checklist for three separate online workshops to cover the three web server software options

- [x] Apache
- [ ] Nginx
- [ ] OpenLiteSpeed

**Comment by jonathanbossenger** [comment]
## Online Workshop Details
- Date: 2024/06/20 @ 12:00 UTC 
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/301593526/
- Co-host: N/A

## Online Workshop Development Checklist
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
Apache version: https://wordpress.tv/2024/06/21/how-to-install-wordpress-on-an-ubuntu-vps-apache-edition/

**Comment by jonathanbossenger** [comment]
https://youtu.be/d8SBvl-jtuk

**Comment by jonathanbossenger** [comment]
## Nginx edition: Online Workshop Details
- Date: 2024/07/18 @ 13:00 UTC 
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/302152709
- Co-host: N/A

## Online Workshop Development Checklist
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
Nginx edition: https://youtu.be/6wajEU5Bm3k

**Comment by jonathanbossenger** [comment]
## OpenLiteSpeed edition: Online Workshop Details
- Date: 2024/08/27 @ 13:00 UTC 
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/302918822/
- Co-host: N/A

## Online Workshop Development Checklist
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
Openlitespeed: https://wordpress.tv/2024/09/02/how-to-install-wordpress-on-an-ubuntu-vps-openlitespeed-edition/

**Comment by jonathanbossenger** [comment]
https://youtu.be/xgsmQ0g3TMg
