### ISSUE TITLE
"Bengali" LANGUAGE translation for "Managing a WordPress Multisite Network"

### ISSUE THREAD

**Issue by bdkoder** [WordPress/Learn#2494]
# Details
- Link to original content: [https://learn.wordpress.org/tutorial/managing-a-wordpress-multisite-network/](https://learn.wordpress.org/tutorial/managing-a-wordpress-multisite-network/)
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: @devmuhib009 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by bdkoder** [comment]
Hello @devmuhib009,
The translation was completed.
Here is the doc link - [https://docs.google.com/document/d/1CKwFwF_QTIuL08t2WYKyKuA2UDojaxTOVbUog9izvMs/edit?usp=sharing](https://docs.google.com/document/d/1CKwFwF_QTIuL08t2WYKyKuA2UDojaxTOVbUog9izvMs/edit?usp=sharing)

If you think, any changes would be perfect, please let me know.

Thanks.

**Comment by devmuhib009** [comment]
Hi @bdkoder 

Thanks for the translation. Can you just type english words at bangla? Because we are planning to use translation plugins in near future to translate contents in all languages. That time we may face difficulties with this type of translation. So, I will suggest you to type those specific english words in bangla. 

I reviewed the translation, overall it's seems good.

**Comment by bdkoder** [comment]
Hello @devmuhib009 ,
Done, you can check it on your side.

Thanks

**Comment by devmuhib009** [comment]
Thanks for the update. Here is the [glossary page](https://translate.wordpress.org/locale/bn/default/glossary/) that we need to follow.

> পৃষ্ঠা 

পেইজ (সব জায়গায় এটা ব্যবহার করুন প্লিজ)

> একটি মাল্টিসাইট নেটওয়ার্ক পরিচালনা আপনাকে শেখানো  হবে

একটি মাল্টিসাইট নেটওয়ার্ক পরিচালনা করা আপনাকে শেখানো  হবে

> এখানে যা শিখবেনঃ 

শেখার ফলাফলঃ ( * অন্য সব ট্রান্সলেশনে এটা ব্যবহার করা হয়েছে)

> প্রশ্ন অনুধাবনঃ

সম্পূরক প্রশ্ন:  ( * অন্য সব ট্রান্সলেশনে এটা ব্যবহার করা হয়েছে)

> ভিডিও ট্রান্সক্রিপশন দেখুন -

ট্রান্সক্রিপ্ট

> পৃষ্ঠায় উপলব্ধ

পেইজে এভেইলেবল (উপলব্ধ এর চেয়ে এভেইলেবল বেশি বোধগম্য )

* একটি শব্দের বাংলার চেয়ে ইংরেজি প্রতিশব্দ বেশি জনপ্রিয় হলে, সেটি বাংলাতে টাইপ করে ব্যবহার করাই ভাল। সময় স্বল্পতার জন্য পুরো কন্টেন্ট পরতে পারিনি। উপরের সাজেশন অনুযায়ী আরেকটু রিভাইস করে ঠিক করে নিবেন।


After updating the content, please share your WordPress username, so we can add you to the Learn WordPress website. Thanks

**Comment by bdkoder** [comment]
Thanks a lot @devmuhib009 
The whole content is updated from my side.
Now you can check it on your side.

My WP Username - **bdkoder**

Thanks.

**Comment by devmuhib009** [comment]
I can see there has a word "পৃষ্ঠা" still exists. 😁

I have added you to the Learn WordPress website. Please check your email and accept the invitation. Then draft the post on Learn Website and submit subtitle on WordPress TV please. Please follow from step 5 to 7. 
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials

**Comment by bdkoder** [comment]
Hello @devmuhib009 ,
Thanks again, apologize for the mistake.
Updated the doc.

Accepted - _[Learn WordPress] Joining confirmation_

Thanks.

**Comment by devmuhib009** [comment]
It's ok. 😀 Once drafted and submitted the subtitle, please let me know.

**Comment by bdkoder** [comment]
Hello @devmuhib009,
The post was drafted today.
You can check on your side.
Thanks.

**Comment by devmuhib009** [comment]
Please submit the subtitle on WPTV and I'll publish both together. Thanks

**Comment by devmuhib009** [comment]
Can you please draft the post in Tutorial Section. Not in default post.
Thanks

**Comment by devmuhib009** [comment]
Translation published: https://learn.wordpress.org/tutorial/bn-managing-a-wordpress-multisite-network/
Thanks for your hard work!
//published
