### ISSUE TITLE
Feedback - Issue when installing "Setup 2024 version": Fatal is thrown

### ISSUE THREAD

**Issue by freibergergarcia** [WordPress/Learn#2495]
## Type of feedback
//dev

## Description
I'm seeing a fatal error while running `yarn run create`:
```php
Fatal error: Uncaught Error: Call to undefined function WPOrg_Learn\Sensei\get_my_courses_page_url() in /var/www/html/wp-content/themes/pub/wporg-learn-2024/functions.php:113
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(324): WordPressdotorg\Theme\Learn_2024\add_site_navigation_menus(Array)
#1 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /var/www/html/wp-content/mu-plugins/wporg-mu-plugins/mu-plugins/blocks/navigation/index.php(29): apply_filters('wporg_block_nav...', Array)
#3 /var/www/html/wp-includes/class-wp-hook.php(324): WordPressdotorg\MU_Plugins\Navigation_Block\init('')
#4 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /var/www/html/wp-settings.php(700): do_action('init')
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1336): require('/var/www/html/w...')
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1 in /var/www/html/wp-content/themes/pub/wporg-learn-2024/functions.php on line 113
```

Looks like the **wporg-learn** plugin isn't active yet when the theme is activated.

The fatal occurs on https://github.com/WordPress/Learn/blob/trunk/wp-content/themes/pub/wporg-learn-2024/functions.php#L113C15-L113C38

### Proposed solution
I was able to make it work by adding `wporg-learn` at the end of:
https://github.com/WordPress/Learn/blob/trunk/bin/index.sh#L18

## Step-by-step reproduction instructions (optional)
Make sure to run `yarn run wp-env destroy` in case your installation has the plugin already active.

Follow the steps under "Setup 2024 version":
```
yarn
yarn run create
```

## Screenshots or screen recording (optional)
<img width="1236" alt="Screenshot 2024-06-03 at 10 43 04 PM" src="https://github.com/WordPress/Learn/assets/808069/61436fee-5cdd-4c84-9599-bc3825d284b9">

## Other information (optional)
Replicated on MacOS, with Node 18 and 20

**Comment by freibergergarcia** [comment]
@jonathanbossenger I notice this while going through your YouTube session: https://www.youtube.com/watch?v=3KU0Vdn5_6g.

If I'm not missing anything and this confirms an issue, I would like to work on it.

**Comment by jonathanbossenger** [comment]
Thanks @freibergergarcia. This session was recorded before the new theme was added.

@adamwoodnz would you be able to check if this is a valid issue?

**Comment by freibergergarcia** [comment]
@jonathanbossenger 👍 

I also noticed that the [import](https://github.com/WordPress/Learn/blob/trunk/bin/index.sh#L30C3-L30C59) command doesn't work with double quotes around the php command.

It works with:
```sh
npm run wp-env run cli php bin/import-test-content.php
```

**Comment by adamwoodnz** [comment]
> @jonathanbossenger I notice this while going through your YouTube session: https://www.youtube.com/watch?v=3KU0Vdn5_6g.
> 
> If I'm not missing anything and this confirms an issue, I would like to work on it.

I had no idea there was a session covering this!

The Learn plugin was a later addition to the new setup so I think that's why it was missed. We'd welcome a PR if you'd like to fix these issues, thanks!

**Comment by freibergergarcia** [comment]
@adamwoodnz @jonathanbossenger PR raised https://github.com/WordPress/Learn/pull/2503.
