### ISSUE TITLE
Meeting Agenda June 6, 2024

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2498]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @bsanevans._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- June 6 – @speedyprem
- June 13 – @zeel Thakkar
- June 20 – @jagirbahesh
- June 27 – **looking for volunteer** 

**2. Looking for feedback**

- [Proposal: Learn WordPress Content Maintenance Process](https://make.wordpress.org/training/2024/05/29/proposal-learn-wordpress-content-maintenance-process/) — please continue to contribute to this conversation by providing your thoughts by June 13th.
- The Training Team has had an [Administration project board](https://github.com/orgs/WordPress/projects/53) in GitHub for a couple of years. With the majority of project tracking now happening on the team blog, team reps are planning on cleaning out the board, leaving just meeting agenda and handbook feedback items. Are any team members still actively using this board?

**3. Looking for volunteers**

- Jonathan and Wes started triaging the Tutorials in [this spreadsheet](https://docs.google.com/spreadsheets/d/15ZMa3GFLb7Pp9n2j32vxnojctdWrT0WRzheo56Q_qtk/edit?usp=sharing), marking those which the team should keep, modify, or retire. There are still over 100 Tutorials that need triaging. Feel free to add your thoughts directly in the spreadsheet, or comment here if you need assistance.

**4. Other news**

- Our [WordCamp Europe 2024 Contributor Day](https://make.wordpress.org/training/2024/05/28/wordcamp-europe-2024-contributor-day/) post is now up for contributors to review. You can participate either in person or online, so click this link to find out how to contribute :blush:
- [We have a new handbook page](https://make.wordpress.org/design/handbook/resources/figma-thumbnail-generator/) on how to create video and event thumbnails for Learn WordPress and our Online Workshop group. Going forward, please use this thumbnail generator for all thumbnails that need to be created for Courses, Lessons, and Online Workshops.
- [Meet 2024 Interim Co-Rep: Jamie Madden](https://make.wordpress.org/training/2024/06/04/meet-2024-interim-co-rep-jamie-madden/)

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have # issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have # issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have # issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have # issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have # issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: 
- Props:
   - We found out this week that the Learn news letter wasn't sending to subscribers until now. Thanks to Adam for identifying this issue, and fixing it in preparation for the site relaunch.

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - [June 3rd Update](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4258): A theme switcher now lets you preview the new theme on the production site, with all its data. You can try it at: https://learn.wordpress.org/?new-theme=1

## 5. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by ghost** [comment]
Please add to the decision about using the new thumbnail generator a reminder to use sentence case for the titles on the thumbnail, in Meetup events, and online workshop calendar entries. This is from a Slack discussion [sentence case](https://wordpress.slack.com/archives/C02RW657Q/p1717482194059119?thread_ts=1715921466.413969&cid=C02RW657Q).

**Comment by kathrynwp** [comment]
### Faculty program retirement 

I'd like to share a proposal to retire [the Faculty program in its current form](https://make.wordpress.org/training/handbook/faculty-program/). This proposal was already discussed within the Faculty group, and since the overall consensus was to go ahead with retiring the program, I'm now sharing the proposal with the whole team before we move forward with any of the suggested steps.

> I wanted to share something that the three team reps and I have been discussing.
> 
> Firstly, we wanted to give a huge thank you for all your hard work in keeping things running so smoothly. Thanks to you all, we’ve been able to set up team processes, catch up on a backlog of tasks, and set ourselves up for future success.
> 
> Over the past while, we’ve observed that the Faculty program is due for a rethink. For example, many folks in the Faculty group are no longer active on the team at all, and there are many roles that are under-used and difficult to recruit for. As well, there’s a level of administrative overhead that’s somewhat complicated, and having to be part of the Faculty program may be seen by contributors as a barrier to doing certain types of work on the team. Finally, the now-established Guide Program serves as a welcoming path for people to get more involved in the team.
> 
> We’ve been thinking of ways to streamline things to make the team run more efficiently. In turn, this should free up time to focus more on higher-impact areas.
> 
> In thinking things over, we’d like to suggest retiring the Faculty program in its current form. We propose the following steps:
> 
> - Add a new area in the handbook, outlining the history of [Learn.WordPress.org](http://learn.wordpress.org/) and the Training team. This section would also include the names of past team reps and Faculty members, so that folks’ contributions are visible and recognized in the context of the Training team’s history.
> - Shift the work done by the current Faculty Admin group to a smaller group of administrators, starting with the team reps. Additional admins will be added over time, while the current admin needs of the team are reassessed. We will likely look for Training team members who have made consistent contributions over the last 6-12 months.
> - Update the handbook to remove the Faculty Program section.
> 
> Thank you again for all your contributions to the Faculty Program! We wouldn’t be in the strong position we are now without you.

**Comment by kathrynwp** [comment]
### Tutorial deprecation

To simplify Learn.WordPress.org, two content types will be gradually phased out: tutorials and lesson plans. As a first step, before launching the new site some outdated tutorials are going to be unpublished. A redirect will be added for each one, to send visitors to the most relevant alternative content.

Wes and Jonathan have already started going through all existing tutorials to note whether they should be kept, deprecated (unpublished), or updated. 

**We could use additional assistance continuing to go through the rest of the tutorials to indicate the status of each (keep/deprecate/update) and a potential redirect URL.** Is anyone available to help out? Note that some of this content is in languages other than English, but you could use an online translation tool to translate the tutorial title to help determine whether it's still relevant or has a more up-to-date equivalent tutorial or lesson.

**Comment by ghost** [comment]
[Training Team Update- June 2024](https://make.wordpress.org/updates/2024/06/04/training-team-update-june-2024/)
[Learn WordPress Newsletter – June 2024](https://learn.wordpress.org/learn-wordpress-newsletter-june-2024/)

**Comment by westnz** [comment]
June Content Creation Coffee Hours:
This is an opportunity for anyone working on learning pathway content or anyone interested in learning pathway content to meet, discuss what content they are working on, ask questions, or find content to work on for the learning pathways. Currently, we alternate meetings between two time zones each month. 
Jonathan—13 June 2024 @ 14:00 UTC (The Zoom link will be shared the day before the session and again on the day of the session, just before it begins.)
Wes - 25 June 2024 @ 21:00 UTC ([Zoom link](https://us02web.zoom.us/j/84635896082?pwd=xyOEwTbe9vHDQhyjM6ALpyTr5fy1oh.1))

**Comment by westnz** [comment]
Jonathan and Wes have identified a need for users to view their content creation process. They plan to add the following links as additional resources to the "Create a Lesson" page. They are also considering creating an informal video recording of these processes to support visual learners. We welcome any feedback or concerns you might have regarding this plan.

[Wes’s content creation process](https://href.li/?https://docs.google.com/document/d/1ACyTjzZmaHIdzZamWziLstxOb8d-bp8YpYbzotqejuo/edit)
[Jon’s content creation process](https://href.li/?https://docs.google.com/document/d/1IISSe-g072K9f5DCWkdc4OQZ1khD-nm2xo1PThKijW4/edit#heading=h.idgi22iyp5ga)

**Comment by kaitohm** [comment]
This meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1717632066828119

**Comment by ghost** [comment]
Meeting recap post published: https://make.wordpress.org/training/2024/06/08/training-team-meeting-recap-6th-june-2024/
