### ISSUE TITLE
404 template

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2499]
With the overhaul of Learn.WordPress.org, we will be retiring some outdated content and restructuring the existing content and navigation. While we plan to add redirects for old content – per #2496 – let's consider updating the Search template to welcome folks to the new site and perhaps explain the new structure.

Current search page for reference:

<img width="1490" alt="Page_not_found_–_Learn_WordPress" src="https://github.com/WordPress/Learn/assets/7662449/5aaed2cb-3d02-4403-bd98-45d04f7a577f">

**Comment by kathrynwp** [comment]
Text suggestion, open to feedback:

> Welcome to the new Learn.WordPress.org!

> The site has been revamped with new content and a fresh look. If you're having trouble finding what you're looking for, try a search:

> [ search box ]]

> You can also visit the [new homepage](https://learn.wordpress.org/) and check out the Learning Pathways geared to different groups of people who use WordPress.

**Comment by speedyprem** [comment]
@kathrynwp Content looks good to me. 👍

**Comment by adamwoodnz** [comment]
Note that this is actually the shared 404 (page not found) template, used across the entire wordpress.org site. If we implement a custom experience for Learn it will be the 404.html template.

**Comment by thetinyl** [comment]
I like the idea of contextualizing the 404 message to Learn. Thanks for taking a first stab at copy, @kathrynwp. I like what you've suggested tone-wise, I do wonder about explicitly calling out "new". The new Learn experience won't be new forever, so that does invite a need to update the content again down the road. (Unless that's something that's desireable?)

I'm thinking there's a way to make it seem new, while still be evergreen enough that we wouldn't need to revisit.

Here's a suggestion:

> **Sorry, we couldn’t find this page.**
> We’ve moved some things around to make the Learn WordPress experience better for you. Know what you’re looking for? Try a search:
>
> [search box]
> 
> Or, visit the [Learn WordPress homepage](https://learn.wordpress.org/) to explore the newest resources. 

I always like to view the 404 as an opportunity to further lead people where we want them to go. So as an alternative to linking to the homepage, I suggest the following for underneath the search bar (links are my recommended, but can be whatever makes the most sense if there are other needs):

> Or, explore some of the newest resources on Learn:
>
> [Learning Pathways](https://learn.wordpress.org/test/learning-pathways/): Go from beginner to expert at your own pace.
> [Online workshops](https://learn.wordpress.org/online-workshops/): Join a live session taught by experienced educators.
> [My courses](https://learn.wordpress.org/my-courses/): Track your progress and save courses you’re interested in.

**Comment by kathrynwp** [comment]
@thetinyl Thank you so much! I love all your suggestions, including the idea of linking to specific sections of the new site.

Two small things:

- Not sure about the word "educator" as we have workshops run by lots of folks who aren't educators. What do you think about "experienced WordPress pros," or open to your suggestions!
- Not sure about linking to "My courses" as that's just a login or registration page if you haven't yet registered for anything.

Perhaps just the two bullet points is enough, but open to other thoughts! We could also link to Courses - https://learn.wordpress.org/test/courses/ - which includes courses that are not necessarily part of a Learning Pathway.

**Comment by thetinyl** [comment]
> Not sure about the word "educator" as we have workshops run by lots of folks who aren't educators. What do you think about "experienced WordPress pros," or open to your suggestions!

@kathrynwp Ah, got it! Fair point. No personal issues with "pros", but let's say "professionals" so it's extra clear. 

> Not sure about linking to "My courses" as that's just a login or registration page if you haven't yet registered for anything.

My initial thought was that it could act as a prompt for unregistered folks to register (like pointing out their course load is empty.... why not fill it?). That being said, you're right about sending someone to a generic login page not being ideal.

> Perhaps just the two bullet points is enough

It could very well be. Visually, three does feel better. Like Learn has more to offer (without being overwhelming). Courses could work, though they do ultimately feel similar to Learning Pathways. What about Lessons instead? 

Here's an updated suggestion based on the feedback:

> **Sorry, we couldn’t find this page.**
We’ve moved some things around to make the Learn WordPress experience better for you. Know what you’re looking for? Try a search:
>
> [search box]
>
> Or, explore some of the newest resources on Learn:
>
> [Learning Pathways](https://learn.wordpress.org/test/learning-pathways/): Go from beginner to expert at your own pace.
> [Online workshops](https://learn.wordpress.org/online-workshops/): Join a live session taught by experienced WordPress professionals.
> [Lessons](https://learn.wordpress.org/lessons/): Find quick how-to videos to help level up your expertise—even when you're short on time.

**Comment by adamwoodnz** [comment]
Hi all, are we happy with the last suggestion?

**Comment by kathrynwp** [comment]
@adamwoodnz Oops sorry, thought I had replied!

Yes, I'm happy with the last suggestion. Two points:

- I think we always capitalize the "W" in "Online Workshops" as that's the branding, and it's spelled that way on all the thumbnails.
- Most, but not all lessons have video. Should we reword the third bullet item, @thetinyl ?

**Comment by thetinyl** [comment]
Based on the direction we're going with the site copy (and your notes above, @kathrynwp), here's another revised version:

> **Sorry, we couldn’t find this page.**
We’ve moved some things around to make the Learn WordPress experience better for you. Know what you’re looking for? Try a search:
>
>[search box]
>
>Or, explore some of the newest resources on Learn:
>
>[Learning Pathways](https://learn.wordpress.org/test/learning-pathways/): Go from beginner to expert at your own pace.
>[Online Workshops](https://learn.wordpress.org/online-workshops/): Join a live session taught by experienced WordPress professionals.
>[Lessons](https://learn.wordpress.org/lessons/): Improve your WordPress expertise with versatile lessons featuring a blend of videos, exercises, quizzes, and more.

**Comment by kathrynwp** [comment]
@thetinyl Looks good to me, thank you!

**Comment by thetinyl** [comment]
I've just made a quick edit to the 'Lessons' copy above based on additional feedback. Should be all consistent now. 👍

**Comment by kathrynwp** [comment]
I see this live and it's looking good!

<img width="1495" alt="Page_not_found_–_Learn_WordPress_and_Inbox__264__-_zoonini_gmail_com_-_Gmail" src="https://github.com/WordPress/Learn/assets/7662449/7954578b-0703-4e3e-8d15-163dd8454f22">

**Comment by thetinyl** [comment]
Oof, I just noticed a tiny copy update (for consistency). We're saying "expert" vs. "advanced" here. This was written at the same time as that was being sussed out elsewhere. 

It's not a blocking copy edit. @adamwoodnz would a new ticket (super low priority) be necessary for this change?

**Comment by adamwoodnz** [comment]
> @adamwoodnz would a new ticket (super low priority) be necessary for this change?

Nope, [done](https://github.com/WordPress/Learn/commit/f107511d0ecd86ff0155f23dc86787c9ac6c63a6)! Thanks.
