### ISSUE TITLE
The WordPress.org Theme Directory

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2505]
# Details
 
 - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
 - Content title: The WordPress.org Theme Directory
 - Topic description: Introduce the WordPress.org Theme Directory, reasons why developers might publish there, and provide an overview of the steps required to submit a theme.
 - Audience (User, Developer, Designer, Contributor, etc.): Developer
 - Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate
 
 # Learning Objectives
 
 - Explain what the WordPress.org Theme Directory is
 - Describe some of the benefits of publishing your theme to the theme directory
 - Explain the steps required to submit a theme

 # Related Resources and Other Notes
 - https://wordpress.org/themes/
 - https://developer.wordpress.org/themes/releasing-your-theme/
 - https://wordpress.org/themes/getting-started/
 - https://developer.wordpress.org/themes/advanced-topics/publishing-themes/

 ### Automation Code
 
 //lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/theme-developer-learning-pathway/08-publishing-themes/01-the-wordpress-org-theme-directory.md

**Comment by jonathanbossenger** [comment]
Video for review: https://drive.google.com/file/d/19v1nvlQS8G3dG9nNeBQ5h1UcaXk3HJsp/view?usp=sharing

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Solid intro, @jonathanbossenger.

The slides that show the Theme Directory homepage (at the beginning and end of the lesson) feature the soon-to-be-old design. It’s probably safe to replace them with the upcoming design that’s supposed to launch soon: https://wordpress.org/themes/?new-theme=1.

**Comment by Soir7** [comment]
Confirmed:
[+] Learning outcomes/objectives are clear.
[+] Technical concepts introduced in the content are accurate.
[+] The speed of demonstrations are easy to follow.
[+] The narration audio matches what is shown visually.
[+] Spelling and grammar are correct.
[+] Sound quality is consistent throughout the video.
[+] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed. - **NAMED 3 SOURCES FOR THEME CHECKER.**  
[o] Media assets are all in the public domain - N/A


Hi  @jonathanbossenger.

I neglected to note my initial post was a work in progress.  Here are my comments.

1. Your tone of voice is pleasant and engaging.  Keeps me interested in listening further.
2. Goals of video clear, progression logical and easy to follow.
3. Nice how you markedly identify each topic into which you segue.
4. Criteria for submitting theme succinct and direct.
5. Not sure if you had a time constraint - suggest adding a pause here and there (like using 'white space' on a page), or slowing down a second or two between topics.

Thank you.

**Comment by jonathanbossenger** [comment]
Thanks @ironnysh and @Soir7 

Updated view with new theme screenshots

https://github.com/WordPress/Learn/assets/180629/b662d5a5-71e8-4e4e-b93b-c43b81a8bd43

**Comment by Soir7** [comment]
Hi @jonathanbossenger, 

Please see addendum on comments I'd provided last week.

Thanks!

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/07/17/the-wordpress-org-theme-directory/

**Comment by jonathanbossenger** [comment]
https://www.youtube.com/watch?v=gx_XyBoJV-A

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/the-wordpress-org-theme-directory/

**Comment by jonathanbossenger** [comment]
//publish
