### ISSUE TITLE
Required theme files

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2506]
# Details
 
 - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
 - Content title: Required theme files
 - Topic description: Cover the core theme files required for both a block theme and a classic theme, for submission to the theme directory
 - Audience (User, Developer, Designer, Contributor, etc.): Developer
 - Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate
 
 # Learning Objectives
 
 - Identify the files required for a theme to be submitted to the theme directory.
 
 # Related Resources and Other Notes
 - https://developer.wordpress.org/themes/releasing-your-theme/required-theme-files/

 ### Automation Code
 
 //lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/theme-developer-learning-pathway/08-publishing-themes/02-required-theme-files.md

**Comment by jonathanbossenger** [comment]
Video for review: https://drive.google.com/file/d/1JR9gjP9T32rck5nKdAL3UDFCJj1L2emH/view?usp=sharing

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/07/17/required-theme-files/

**Comment by jonathanbossenger** [comment]
https://youtu.be/vhWis5HiUdY

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/required-theme-files/

**Comment by jonathanbossenger** [comment]
//publish
