### ISSUE TITLE
Preparing your theme for submission

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2507]
# Details
 
 - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
 - Content title: Preparing your theme
 - Topic description: Once development has been completed, review the additional steps required before submitting a theme to the theme directory: testing your theme, reviewing and following the theme review guidelines, and preparing documentation.
 - Audience (User, Developer, Designer, Contributor, etc.): Developer
 - Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate
 
 # Learning Objectives
 
- Describe ways to test a theme
- Implement the theme review guidelines 
- Prepare theme documentation
 
 # Related Resources and Other Notes
 
 ### Automation Code
 
 //lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/theme-developer-learning-pathway/08-publishing-themes/03-preparing-your-theme-for-submission.md

**Comment by jonathanbossenger** [comment]
Video for review: https://drive.google.com/file/d/1eI-wcXtphnSvT3G8p7Vbgxq3ycwCwuBI/view?usp=drive_link

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Very informative lesson👌

Suggestion: at 0:51, when referring to testing future WordPress versions, it’ll be nice to mention a “shortcut”: use Playground to test multiple WP and PHP versions. Playground also allows testing backward compatibility.

**Comment by jonathanbossenger** [comment]
Thanks @ironnysh 

> Suggestion: at 0:51, when referring to testing future WordPress versions, it’ll be nice to mention a “shortcut”: use Playground to test multiple WP and PHP versions. Playground also allows testing backward compatibility.

That's a great idea. I'm not going to have time to include it for the release, but I have created an update issue for tasks I plan to tackle once the pathway is published.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/07/17/preparing-your-theme-for-submission/

**Comment by jonathanbossenger** [comment]
https://youtu.be/U-Aba8l7nwU

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/preparing-your-theme-for-submission/

**Comment by jonathanbossenger** [comment]
//publish
