### ISSUE TITLE
Updating your theme

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2509]
# Details
 
 - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
 - Content title: Updating your theme
 - Topic description: Describes how to prepare an update for a theme, and upload it to the theme directory.
 - Audience (User, Developer, Designer, Contributor, etc.): Developer
 - Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate
 
 # Learning Objectives
 
 - Discuss reasons why a theme might need to be updated
 - Explain the process of updating a theme

 # Related Resources and Other Notes
 - https://developer.wordpress.org/themes/releasing-your-theme/updating-your-theme/
 ### Automation Code
 
 //lesson

**Comment by jonathanbossenger** [comment]
Script: https://github.com/jonathanbossenger/wp-content/blob/main/theme-developer-learning-pathway/08-publishing-themes/05-updating-your-theme.md

**Comment by jonathanbossenger** [comment]
Video for review: https://drive.google.com/file/d/1BJsxTD3TMAqBOq885OFoWKnQhi0_NJJj/view?usp=drive_link

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great finale for this miniseries! :-)

At 0:54, the slide shows the soon-to-be-old design of the submission page. It’s probably safe to replace it with the upcoming design that’s supposed to launch soon: https://wordpress.org/themes/upload/?new-theme=1.

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2024/07/17/updating-your-theme/

**Comment by jonathanbossenger** [comment]
https://youtu.be/uU1IFfpqy8s

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/updating-your-theme/

**Comment by jonathanbossenger** [comment]
//publish
