### ISSUE TITLE
Add a 'print' button to Lesson Plans

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#251]
Now that we have print stylesheets live for lesson plans and workshops, there's a lot of value in calling attention to this for lesson plans specifically. Adding a "print this page" link to the lesson plan template would be really valuable - it can appear underneath the lesson plan meta data in the sidebar and, if my memory serves correctly, it should just have to trigger `window.print()` since all we need to do is use the default browser printing function.

**Comment by courtneyr-dev** [comment]
That was the goal for these. Our original team goal was that all materials could be easily downloaded for offline access.  Additional uses for PDFs include educational organizations providing these in a standard format to their leadership.

**Comment by jonathanbossenger** [comment]
Do we have any requirements for where the link should reside? 

For lesson plans, I was thinking just above the Details sidebar (Duration etc)

![LessonPlanPrintView](https://user-images.githubusercontent.com/180629/138512196-ce023dfc-4114-4d2c-8d0d-cacd4c13b208.png)

For Workshops, probably a new item under the Transcript **View** button

![WorkshopsPrintView](https://user-images.githubusercontent.com/180629/138511858-131ee8ef-9b98-46a3-ac2d-5b384e5c5ba3.png)

**Comment by hlashbrooke** [comment]
Your idea for the workshop print view is perfect. For lesson plans I would say place it below the details, but above the "suggestions" bit. I think also change the text to more action-oriented - so something like "print this page" or similar.

**Comment by jonathanbossenger** [comment]
Thanks @hlashbrooke

**Comment by jonathanbossenger** [comment]
@hlashbrooke added #258 to implement the print button/link.

**Comment by courtneyr-dev** [comment]
We don't have a print option on lesson plans still. Reopening. 
https://learn.wordpress.org/lesson-plan/how-to-create-a-lesson-plan/

**Comment by hlashbrooke** [comment]
Hmm - I'm not sure where this went to - it was definitely there before! I'll dig into it and see what happened.
