### ISSUE TITLE
Align local nav & breadcrumbs of pages with design

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/Learn#2511]
See https://github.com/WordPress/Learn/pull/2491#issuecomment-2151818712 for design and discussion.

**Comment by adamwoodnz** [comment]
Seeing some issues with the local nav bar when scrolled.

Title of first item displayed on archives

![Image](https://github.com/WordPress/Learn/assets/1017872/1dfa1c65-f11e-47c8-8bd0-8e0b3cb71dea)

Post type name missing when viewing single

![Image](https://github.com/WordPress/Learn/assets/1017872/d9f9c49f-afdf-4bbf-98d2-522d519f39e0)
