### ISSUE TITLE
Introduction to Classic themes

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2515]
# Details

- Content type: Lesson
- Content title: Overview of classic themes
- Topic description: We will take a close look at how classic themes are built
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- Differentiate between classic and block themes
- List and describe the typical files included in a classic theme
- Organize your theme files

# Related Resources and Other Notes

- https://developer.wordpress.org/themes/getting-started/what-is-a-theme/#classic-themes
- https://developer.wordpress.org/themes/classic-themes/your-first-theme/#classic-theme

**Comment by cynthianorman** [comment]
https://youtu.be/W4XeDTNxhbA

This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

**Comment by jonathanbossenger** [comment]
https://youtu.be/yVS6d44NuvU

**Comment by westnz** [comment]
//published

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### YouTube Chapters
(0:08) Learning objectives
(0:26) Differentiate between classic and block themes
(3:44) List and describe the typical files included in a classic theme
(4:19) Organize your theme files
(5:01) Next steps
