### ISSUE TITLE
The Loop

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2516]
# Details

- Content type: Lesson
- Content title: The Loop
- Topic description: This lesson dives into the mechanism WordPress uses to output posts on a page.
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- Describe how the Loop is used within a theme
- List some examples of what the Loop can display
- Explore displaying data from Custom Post Types and Custom Fields

# Related Resources and Other Notes

- https://developer.wordpress.org/themes/basics/the-loop/

**Comment by cynthianorman** [comment]
https://youtu.be/g0ppRWeWw8w

This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

**Comment by jonathanbossenger** [comment]
https://youtu.be/jMI9oYI4ySk

**Comment by westnz** [comment]
//published

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### YouTube Chapters
(0:05) Learning objectives
(0:23) Describe how the Loop is used within a theme
(1:29) List some examples of what the Loop can display
(2:19) Explore displaying data from Custom Post Types and Custom Fields
(4:59) Next steps
