### ISSUE TITLE
Theme Options

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2517]
# Details

- Content type: Lesson
- Content title: Theme options
- Topic description: This lesson explores the Customize API  to add options to a classic theme.
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- Describe the Customize API otherwise known as the Customizer
- List examples of how the Customizer is used in a theme
- Register theme options using the Customizer

# Related Resources and Other Notes

- https://developer.wordpress.org/themes/customize-api/

**Comment by cynthianorman** [comment]
@jonathanbossenger are we duplicating efforts here? https://github.com/WordPress/Learn/issues/1902

**Comment by jonathanbossenger** [comment]
Good point, I've left a comment there to see if we can find a way forward together.

**Comment by jonathanbossenger** [comment]
@cynthianorman, let me know if you need any assistance reviewing and refining the learning outcomes from #1902. 

My suggestion here would be 
- Overview of the Theme Customizer in classic themes
- Registering one or two theme options using the Customizer API
- Further reading, pointing out the other parts of that chapter in the handbook

It also looks like the different sections of that chapter aren't in a great logical order at the moment, I'm going to see if I can get that fixed up.

**Comment by cynthianorman** [comment]
https://youtu.be/xsOMYgueEHk

This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

**Comment by jonathanbossenger** [comment]
https://youtu.be/SeJ1zx99fik

**Comment by westnz** [comment]
//published

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### YouTube Chapters
(0:04) Learning objectives
(0:22) Describe the Customize API otherwise known as the Customizer
(1:39) List examples of how the Customizer is used in a theme
(2:54) Register theme options using the Customizer
(5:00) Next steps
