### ISSUE TITLE
Theme.json in classic themes

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2518]
# Details

- Content type: Lesson
- Content title: Theme.json in classic themes
- Topic description: This lesson explores the option of adding theme.json to a classic theme.
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- List the benefits of having a theme.json added to a classic theme
- Describe the process of adding theme.json to a classic theme

# Related Resources and Other Notes

- https://learn.wordpress.org/tutorial/using-theme-json-with-classic-themes/
- https://developer.wordpress.org/block-editor/how-to-guides/curating-the-editor-experience/theme-json/

**Comment by cynthianorman** [comment]
https://youtu.be/r--f7Ara9W4

This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

**Comment by jonathanbossenger** [comment]
https://youtu.be/4hSCqBiyXgk

**Comment by westnz** [comment]
//published

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### YouTube Chapters
(0:07) Learning objectives
(0:22) List the benefits of having theme.json added to a classic theme
(1:29) Describe the process of adding theme.json to a classic theme
(2:47) Next steps
