### ISSUE TITLE
Block patterns in classic themes

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2519]
# Details

- Content type: Lesson
- Content title: Overview of classic themes
- Topic description: We will 
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- 

# Related Resources and Other Notes

-

### Automation Code

//lesson

**Comment by cynthianorman** [comment]
@jonathanbossenger I'm trying to create a list of objectives for this lesson but can't determine the motivation for having this part of this module - do you recall any early day discussions around this lesson being added?

**Comment by cynthianorman** [comment]
@jonathanbossenger how would you feel if we did Template Parts in classic themes instead?
https://learn.wordpress.org/tutorial/using-block-template-parts-in-classic-themes/

**Comment by cynthianorman** [comment]
closing - covered in #2520

**Comment by cynthianorman** [comment]
closing - covered in #2520

**Comment by jonathanbossenger** [comment]
Hi @cynthianorman sorry, I think I missed your initial message.

I also think this was titled incorrectly; it should have been Block Template Parts in Classic themes - https://learn.wordpress.org/tutorial/using-block-template-parts-in-classic-themes/

Does this still make sense as a separate lesson for this module?

**Comment by cynthianorman** [comment]
@jonathanbossenger I'm going to cover this topic in the Converting classic themes lesson. Thanks for your confirmation on the topic though as that's what I thought.
