### ISSUE TITLE
Set up two different workshop types

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#252]
As per [this concluded discussion](https://make.wordpress.org/training/2021/09/27/proposal-ensuring-high-quality-video-contributions-to-learn-wordpress/#comment-3182), we need to distinguish between two types of workshops on Learn WordPress:

* Workshops that meet the production quality standards we are setting
* Workshops that have valuable content, but do not meet the production quality standards

There are two sides to this:

### Data storage

We need a way to distinguish between these two types of workshops in the backend - this could either be a new taxonomy with just the two terms or it could be a meta field with a checkbox for indicating which type the workshop is. I think the decision here will be largely informed by the other major consideration - what happens on the front end.

### Front end display

This is going to need some design work to figure out the best layout and put it together.

When visiting `/workshops` it currently shows the post type archive for workshops (with some neat modifications for the current layout). This shows all of the workshops published on the site. For the two new workshop types, this needs to be separated so that we:
1. See both types of workshops on one page
2. Have a new title for the 'Community content' section (i.e. workshops that do not meet the production standards)

The current filtering and pagination systems need to apply to both types of workshops.

Here's an incredibly rudimentary mockup of what I'm thinking that I hacked together in the Inspector:

<a href="https://user-images.githubusercontent.com/1543143/137839147-ca8213b0-c70b-4e19-9ec5-25fb3b802c7b.png" target="_blank"><img src="https://user-images.githubusercontent.com/1543143/137839147-ca8213b0-c70b-4e19-9ec5-25fb3b802c7b.png" width="450" /></a>

That layout obviously won't work on its own - it's purely illustrative as a jumping-off point.

**Alternative layout option**
An alternative option would be to keep all the workshops in the same archive as they are now, but have a visual element distinguishing them from each other - either an overlay on the thumbnail or some kind of highlight or flag that indicates they are different in some way. I'm not sure what would be best so just throwing this out there.

Heck, maybe all we need to do is have a different type of thumbnail for each type of video and that's all the archive page needs, in which case the only frontend design/dev work will be on the single workshop page to indicate which type it is. I don't know how keen I am on that idea, but it's certainly an option, especially if we can't find the dev time to build something bigger.

<hr/>

Let's hash this out in here and then we can move forward with a decision.

**Comment by critterverse** [comment]
>An alternative option would be to keep all the workshops in the same archive as they are now, but have a visual element distinguishing them from each other

This like this solution. I wonder if the workshop tiles could be reworked to feature author information, including a badge for content that’s labeled “community.” I could see this reusing elements from [wordpress.org/patterns](https://wordpress.org/patterns/): 

![learn-content-labels](https://user-images.githubusercontent.com/77359364/137918575-960d727a-5adc-4d40-9ce5-fe98b76bb65b.jpg)

One more alternative option is that a new “Community” tab could be added to the Learn WordPress navigation with the same layout as the Workshops page:

![learn-wordpress-nav](https://user-images.githubusercontent.com/77359364/137917649-f118dcfb-3199-4bdd-bbda-62cd47d5512d.jpg)

**Comment by courtneyr-dev** [comment]
I think the first place to start is defining the purpose. I think yet another workshop format adds more confusion to the type of content folks can expect to find on Learn. It is very unclear for users currently navigating the site, and this would be one more type.  

I did not view [the proposal](https://make.wordpress.org/training/2021/09/27/proposal-ensuring-high-quality-video-contributions-to-learn-wordpress) as a proposal for another content type (lesson plans, workshops, courses), but thought it applied to the video production of courses. 

Some of these workshops would be better suited as small portions of video courses.  

Can we scope the purpose of a workshop vs video course first?

**Comment by hlashbrooke** [comment]
Thanks for the input @critterverse - I like the layout idea with the presenter name and 'community' tag alongside it!

> One more alternative option is that a new “Community” tab could be added to the Learn WordPress navigation

I think that would complicate things a bit too far - as @courane01 indicates, we don't want to create another new content type.

On that note, @courane01, I feel like the proposal does outline the purpose already, but to clarify here that what you said is correct:

> I did not view the proposal as a proposal for another content type (lesson plans, workshops, courses), but thought it applied to the video production of courses.

That's what the purpose of this issue is to discuss - how can we visually distinguish between the two levels of production quality.

> Some of these workshops would be better suited as small portions of video courses.
> Can we scope the purpose of a workshop vs video course first?

Some of these workshops can definitely be used in courses, but they also stand on their own very well so keeping them in the workshops section is still valuable. We can definitely scope courses like that, but that would be a different discussion not for this issue.

**Comment by rkohilakis** [comment]
I like the "Alternative layout option" of having that Community Content tag in the thumbnail itself so that Learn can get updated sooner.  We can look into a graphic image to use alongside the title to spruce up the thumbnail images and then "Community Content" can be along the bottom.

Maybe instead of just the newest workshop on the top, it can be a rotating gallery of the top 3-5 newest workshops.  It could also include the most popular workshop from the past month (not sure how to automate that, might be easier to stick with newest).

And then instead of dividing between community in the way it is presented, it can be broken up in different categories.  I'm almost thinking like Netflix: recommended for you, most popular right now, newest additions.  If that is too tricky it could be by topic: developers, plugins, themes, user basics.

**Comment by hlashbrooke** [comment]
In light of the fact that dev resources are fairly low for this project for the moment, I think we should move ahead with the following solution here:

1. Create a new taxonomy named `workshop_type`. It can include two terms: `Faculty` and `Community` - this will distinguish between the two types of workshops from an admin perspective. It was @rkohilakis' inspired idea to use 'Faculty' to describe the high-quality videos (in light of [the Faculty program plans](https://make.wordpress.org/training/2021/10/04/a-dedicated-volunteer-program-for-the-training-team/)).
2. Restructure the workshop archives to weight workshops tagged as 'Faculty' higher in the list - this can coincide with some other improvements like randomising the order of videos and highlighting videos related to the current WP release, but I'll open a separate issue for that.
3. The individual workshop pages can have a message or flag that indicates which type they are - Faculty or Community. This can link to a page on Learn itself that explains the difference.

The net result here is that the dev needs will be as follows:
1. Adding a new taxonomy
2. Modifying the workshop archive order
3. Adding a visual cue to the single workshop pages to indicate the workshop type

I'll open separate issues for these things since they can be done independently. I will close this issue once I have opened the other issues.

**Comment by hlashbrooke** [comment]
Closing this issue now, so we can focus on the others - we can reopen this if the discussion needs to continue here.
