### ISSUE TITLE
Converting a classic theme to a block theme

### ISSUE THREAD

**Issue by cynthianorman** [WordPress/Learn#2520]
# Details

- Content type: Lesson
- Content title: Converting a classic theme to a block theme
- Topic description: This lesson explores the possibilities of converting a classic theme into a hybrid theme or a complete block theme.
- Audience: Developer
- Experience Level: Intermediate

# Learning Objectives

- Describe the various requirements of converting a classic theme.
- Differentiate between a hybrid theme and a block theme.
- List the steps to take in order to convert a classic theme into a block theme.

# Related Resources and Other Notes

- https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/
- https://learn.wordpress.org/tutorial/using-block-template-parts-in-classic-themes/
- https://developer.wordpress.org/news/2024/07/04/15-ways-to-curate-the-wordpress-editing-experience/

**Comment by cynthianorman** [comment]
@jonathanbossenger for the 3rd learning objective of this lesson (List the steps to take in order to convert a classic theme into a block theme) I was hoping to get a little feedback before hitting record planned for July 10th.

1. Settings and styles

- Show Twenty Twenty
- Bridging the gap can start simply by adding theme.json and/or theme support within functions.php

2. Editing experience

- Curate the WP editing experience
- https://developer.wordpress.org/news/2024/07/04/15-ways-to-curate-the-wordpress-editing-experience/ 
- Use theme.json as much as possible, for example, applying styles to either the styles.typography.fontSize or styles.elements.link objects
- The goal being to reduce the amount of CSS in your stylesheets as possible, for example, TT3 doesn’t have any styles within a stylesheet as all styling is from theme.json
- Add support for block template parts
- This may require revising your CSS again by replacing some with theme.json (see Beginner WordPress Developer: Global Settings and Styles lesson)

3. Block Editor

- Start by building some pages with the Block Editor (not the Site Editor yet for building full on block templates)

4. Site Editor

- Building block templates and template parts  within the Site Editor and replacing the PHP templates with HTML ones
- Once all of your HTML templates contain nothing but block, you’ll have a Block Theme

**Comment by jonathanbossenger** [comment]
@cynthianorman Yes, I like what you have laid out here.

The only other thing I would mention is that the reason I included the 2nd objective "Differentiate between a hybrid theme and a block theme" is that, depending on your classic theme functionality, you might not be able to fully transition your classic theme to a block theme, and so you might have to go with a hybrid theme. 

I feel it's important that we include something about this in this lesson.

**Comment by cynthianorman** [comment]
@jonathanbossenger thanks so much for confirming (haha I wrote those learning objectives) So glad we're on the same page.

**Comment by jonathanbossenger** [comment]
:joy: that's funny; I thought I did. Sorry about that.

**Comment by cynthianorman** [comment]
https://youtu.be/B356yKKnCdw

This Intermediate Theme Developer Learning Pathway Lesson is ready to be reviewed. Please follow the steps listed under [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/). Thank you for your contribution! ✨

**Comment by jonathanbossenger** [comment]
https://youtu.be/ueNDRM3re08

**Comment by westnz** [comment]
//published

**Comment by cynthianorman** [comment]
@jonathanbossenger 

### YouTube Chapters
(0:05) Learning objectives
(0:25) Describe the various requirements of converting a classic theme
(1:04) Differentiate between a hybrid theme and a block theme 
(2:20) List the steps to take in order to convert a classic theme into a block theme
(5:12) Adding block template parts in a classic theme
