### ISSUE TITLE
Meeting Agenda June 13, 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2526]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @lada7042 ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**
- Notetakers please remember to wait until the Tuesday after the meeting to publish notes. This gives team members to read and comment async. 
- After publishing the notes please comment in the meeting agenda's GitHub issue and add the link for the notes and close.  See image. 
![Screenshot 2024-06-10 152921](https://github.com/WordPress/Learn/assets/24979729/efea5041-0d32-40cf-ab46-ef82393447d7)

- June 13 – @zeel Thakkar
- June 20 – @jagirbahesh
- June 27 – @Arun Sharma
- July 4- looking for volunteer

**2. Looking for feedback**

- [Proposal: Learn WordPress Content Maintenance Process](https://make.wordpress.org/training/2024/05/29/proposal-learn-wordpress-content-maintenance-process/) — please continue to contribute to this conversation by providing your thoughts by June 13th.
- The Training Team has had an [Administration project board](https://github.com/orgs/WordPress/projects/53) in GitHub for a couple of years. With the majority of project tracking now happening on the team blog, team reps are planning on cleaning out the board, leaving just meeting agenda and handbook feedback items. Are any team members still actively using this board?

**3. Looking for volunteers**

- Jonathan and Wes started triaging the Tutorials in [this spreadsheet](https://docs.google.com/spreadsheets/d/15ZMa3GFLb7Pp9n2j32vxnojctdWrT0WRzheo56Q_qtk/edit?usp=sharing), marking those which the team should keep, modify, or retire. There are still over 100 Tutorials that need triaging. Feel free to add your thoughts directly in the spreadsheet, or comment here if you need assistance.

**4. Updates from last week's dev-squad triage session**

- item 1
- item 2

**5. Other news**

- Our [WordCamp Europe 2024 Contributor Day](https://make.wordpress.org/training/2024/05/28/wordcamp-europe-2024-contributor-day/) post is now up for contributors to review. You can participate either in person or online, so click this link to find out how to contribute 😊 Try and get a group photo. 
--- One of the projects we are launching is to create thumbnail graphics for the new site, and we need lots of help! Find out how to take part, either at WCEU's Contributor Day, or remotely anytime. [Thumbnail Creation Project](https://make.wordpress.org/training/2024/06/10/thumbnail-creation-project/)
- [We have a new handbook page](https://make.wordpress.org/design/handbook/resources/figma-thumbnail-generator/) on how to create video and event thumbnails for Learn WordPress and our Online Workshop group. Going forward, please use this thumbnail generator for all thumbnails that need to be created for Courses, Lessons, and Online Workshops. 

![Image](https://github.com/WordPress/Learn/assets/24979729/6fe390ab-a910-43a4-be6d-b2bb50264467)
<img width="1280" alt="Guest + Name + Block text2" src="https://github.com/WordPress/Learn/assets/24979729/192aa5c7-fe3b-46b2-8872-3e39ec84e0e6">
<img width="1280" alt="Online Workshop" src="https://github.com/WordPress/Learn/assets/24979729/a9ec0c45-cde6-41db-81fc-75ce73f9547d">

- If you are attending WC Europe this week go say hi to Jamie! [Meet 2024 Interim Co-Rep: Jamie Madden](https://make.wordpress.org/training/2024/06/04/meet-2024-interim-co-rep-jamie-madden/)
- Make your calendar and stop in and say hi. 

- June Content Creation Coffee Hours
This is an opportunity for anyone working on learning pathway content or anyone interested in learning pathway content to meet, discuss what content they are working on, ask questions, or find content to work on for the learning pathways. Currently, we alternate meetings between two time zones each month.
Jonathan—[Thursday 13 June 2024 @ 13:30 UTC ](https://time.is/1330_13_June_2024_in_UTC)([Zoom Link](https://us02web.zoom.us/j/81989528568?pwd=v8mYqbt2nxxZinLHrfHt9QIclA5qyx.1))
Wes - [25 June 2024 @ 21:00 UTC](https://time.is/2100_25_June_2024_in_UTC) ([Zoom link](https://us02web.zoom.us/j/84635896082?pwd=xyOEwTbe9vHDQhyjM6ALpyTr5fy1oh.1))

- This week at WCEU, [@nao](https://wordpress.slack.com/team/U02S4UPK7)
 and I will host two informal discovery and Q&A sessions about the Five for the Future program for companies interested in joining and having questions.
Session 1 - Saturday, June 15, 9:00 AM
Session 2 - Saturday, June 15, 3:15 PM
Meeting Point: Community Booth. Depending on the number of participants, we might stay there or move to a nearby area.
Here is the link to the newly published [Five for the Future Handbook](https://wordpress.org/five-for-the-future/handbook/about-five-for-the-future/)! :heart_eyes:
Please help spread the word to anyone who might be interested in attending! :star2: Thank you! (edited)

## 2. Come and Contribute##
**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 6 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 26 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 33 issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have 0 issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 15 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: 
- Props: 
--- To @Ben Evans for being one of the featured contributors on [Do The Woo: WordPress Event Talk](https://dothewoo.io/podcasts/wordpress-event-talk/)https://dothewoo.io/and-now-some-speakers-from-wordcamp-europe/
--- To @Laura A for being interviewed by for [Do The Woo: The WordPress Way](https://dothewoo.io/the-wordpress-community-training-and-deib-with-laura-adamonis/)

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
[June 3rd Update](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4258): A theme switcher now lets you preview the new theme on the production site, with all its data. You can try it at: https://learn.wordpress.org/?new-theme=1
- Project_2
  - details

## 5. Faculty Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kathrynwp** [comment]
Feel free to add this wherever you think it's relevant (Contributor Day and "looking for volunteers"?)

I've published a guide to pitching in to create thumbnail graphics for the new site, and we need lots of help! Find out how to take part, either at WCEU's Contributor Day, or remotely anytime.

https://make.wordpress.org/training/2024/06/10/thumbnail-creation-project/

**Comment by kathrynwp** [comment]
A new handbook page on [Video Best Practices](https://make.wordpress.org/training/handbook/guidelines/video-best-practices/) was recently published. An online workshop on the same topic is now embedded on the page. Please share any other free video software editing tools you recommend for their excellent performance so they can be added to the list of resources.

**Comment by kathrynwp** [comment]
Update on the Learn remake: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4279

**Comment by ghost** [comment]
Slack meeting start- https://wordpress.slack.com/archives/C02RW657Q/p1718236849620229

**Comment by ghost** [comment]
Meeting recap- https://make.wordpress.org/training/2024/06/18/training-team-meeting-recap-13th-june-2024/
