### ISSUE TITLE
Course Completed page

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#2528]
Update the template to match the [design](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=4321-21492&m=dev).

<img src="https://github.com/WordPress/Learn/assets/1017872/145d6f24-aef5-4813-b73b-70e3e6b0c04d" width="300">

The default success message is shown in the design 'Congratulations on completing this course!'. This message will be customized if the Course is a Learning Pathway, and can differ depending on Level, [see copy](https://docs.google.com/document/d/1eYcuNUjUdPm1CL3P1Sd0J8hZsn2chBzmuZq4hz7RAdw/edit#heading=h.bp9e84t1ujl2).

For example there will be copy for a Beginner level Developer Learning Pathway Course.

We have existing copy per Learning Pathway level stored [here](https://github.com/WordPress/Learn/blob/trunk/wp-content/themes/pub/wporg-learn-2024/functions.php#L163). We can probably add a 'success' item to each array:

```
'developer' => array(
	'beginner' => array(
		'title' => '[TBD Beginner developer title]',
		'description' => '[TBD Beginner developer description]',
		'success' => '...'
	),
	...
),
```

Survey CTA link: https://docs.google.com/forms/d/e/1FAIpQLSf0QMflUedxjta0u5qS4_pl-9aY06BDBXgRn2PoZA1gRvD9jw/viewform

**Comment by kathrynwp** [comment]
Related: 

https://github.com/WordPress/Learn/issues/2532

**Comment by fcoveram** [comment]
Here is an idea for this page based on the suggestions dropped by @kathrynwp in #2532 

![Mockup of Course completed page](https://github.com/WordPress/Learn/assets/895819/5acdbd47-eb59-4aa0-956f-d637a7471fa1)

The styles applied are in line with the designs shared [here](https://github.com/WordPress/Learn/issues/2531#issuecomment-2180368486) (#2531)

---

Question: What is the total grade score about? It looks floating without context and perhaps there is room for improvement. cc @renintw

**Comment by kathrynwp** [comment]
> Question: What is the total grade score about? It looks floating without context and perhaps there is room for improvement. 

@fcoveram I think this refers to the average score of all the quizzes completed throughout the course. For example if a course includes two quizzes, and the learner scored 100% on one and 80% on the other, then their final grade would be 90% –  @westnz & @jonathanbossenger could one of you please confirm?

**Comment by outdoor2kode** [comment]
Yeah, like @kathrynwp said, a course can consist of multiple lessons, and each lesson can contain multiple quizzes. 

Each lesson has a grade. The final grade on the completed page is the average of these lesson grades.

![image](https://github.com/WordPress/Learn/assets/18050944/56f783d5-6fe1-46c4-9a3e-7c17071770b9)

**Comment by fcoveram** [comment]
Oh I see. I thought the "100%" label on the far right of the lesson name was a "completed" status. Does it make sense to put the total grade below all lessons and quizzes completed? As now, it's hard to understand the relationship. Otherwise, we can improve the copy to be more explicit about where the percentage comes from.

**Comment by fcoveram** [comment]
I included the page in the Course section in the Design page. Here is the mockup

![Mockup of course completed](https://github.com/WordPress/Learn/assets/895819/a0a07685-0d4b-4e96-a8c0-f2de5051f1f5)

What do you think?

**Comment by outdoor2kode** [comment]
> Does it make sense to put the total grade below all lessons and quizzes completed?

It looks good to me, and having a copy explicitly telling where the percentage comes from also makes sense to me. This would need some inputs from the learn fellows @kathrynwp @bsanevans @jonathanbossenger

**Comment by westnz** [comment]
> Does it make sense to put the total grade below all lessons and quizzes completed?

Looks good to me as well.

> having a copy explicitly telling where the percentage comes from also makes sense to me

Agreed

**Comment by kathrynwp** [comment]
@renintw I agree with de-emphasizing the percentage grade/mark by moving it below the table.

**Comment by adamwoodnz** [comment]
I've updated the ticket description to include the latest design, details about the success message, and the survey CTA link.
