### ISSUE TITLE
Lesson List on Course Single Page and Course Completed Page

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/Learn#2531]
Update the Lesson List style on the Course single page and the Completed page. Some details moved from [here](https://github.com/WordPress/Learn/pull/2524#issuecomment-2161457615):

> No further change has been discussed. But from the screenshots, I notice two use cases: Not started, and Completed. If there are more, can you share them?

Yes, there are three cases. Not started, In Progress, and Completed.

| In Progress & Not started | Completed |
|-|-|
| ![Screenshot 2024-06-12 at 03 45 25](https://github.com/WordPress/Learn/assets/18050944/fa5fb77d-ff15-4f5f-a0dc-f54495093b93) | ![Screenshot 2024-06-12 at 03 45 16](https://github.com/WordPress/Learn/assets/18050944/28b349b4-2cec-46a2-b783-62e7ef669ca7) |

> do we have room to improve this elements?

I think we can make changes, but I will open another ticket to handle it, as other than the statuses "Not Started," "In Progress," and "Completed," it looks like there are two different ways to present lessons: lessons that belong to a module and those that do not. Lessons that belong to a module have a blue border and a blue header. Those without a module only display the lesson name.

![image](https://github.com/WordPress/Learn/assets/18050944/2fbd0833-7cd4-4dfb-b149-d6c04b8dd01c)

Lessons without a module seem to be very few in production, but there are still some, although they were created quite a while ago. Whether to consider these needs to be discussed with the training team (~I plan to ask about this in the new ticket~ **Update:** see https://github.com/WordPress/Learn/issues/2531#issuecomment-2162368470).

Additionally, the "course completed" page also displays this lesson list, which I reckon needs to be changed as well.

![image](https://github.com/WordPress/Learn/assets/18050944/8f54bb3f-249d-432d-b0f0-ad0222afdb1f)

**Update**

Preview Button (When a user isn't enrolled)

| Not belong to a module | Belong to a module |
|-|-|
| <img width="648" alt="image" src="https://github.com/WordPress/Learn/assets/18050944/2fb57faf-cf6b-4646-a43d-de47d2157524"> | <img width="866" alt="image" src="https://github.com/WordPress/Learn/assets/18050944/da1bea45-77ee-400b-93d6-8d8ce6a07e14"> |

**Comment by outdoor2kode** [comment]
@WordPress/learn-team Is it possible for a lesson to not belong to a module? I haven't seen this for recently created lessons, but I've noticed it's the case for some older lessons. This could affect how a lesson is rendered.

**Update**

Lessons belong to a module: https://learn.wordpress.org/course/beginner-wordpress-user/
Not belong to a module: https://learn.wordpress.org/course/wordpress-community-team-program-supporter-tasks/
⬆️ Just found this course, it seems that lessons not belonging to a module currently exist and have been added to a course and there might be more in the future. So it seems to me this needs to be considered in the design. cc @fcoveram

**Comment by jonathanbossenger** [comment]
@renintw agreed. We have not created stand-alone lessons recently, but we would like to have the ability to have stand alone lessons that would be rendered on their own.

**Comment by fcoveram** [comment]
I took a look at this and here is an idea I made based on the screenshots attached in the first comment.

![Lessons list variants for Not started, In progress, and Completed](https://github.com/WordPress/Learn/assets/895819/9d53203c-a932-4afc-b459-2ed5638276e0)

## Users not enrolled

![Lessons list when they belong and don't belong to a module](https://github.com/WordPress/Learn/assets/895819/ac63e450-6f84-416a-b0d0-f9b8a3434be7)

## Interaction

Here is how the interaction could work

![Hover and Focus styles in Lessons list](https://github.com/WordPress/Learn/assets/895819/78812a86-535a-40d1-ba06-9e9a0e39695e)

---

**Notes**
* The "Preview" pill does not provide any new information, and clicking on it takes you to the same page as those without the pill.
* The progress bar has a new style for Not started, In progress, and Completed. If we go with this version, we could apply it to all places where it's visible.

What do you think of this @renintw? [Here is](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=4247-12723&m=dev) the section in Figma where all mockups are. If this works, I plan to update the mockups in Design

**Comment by outdoor2kode** [comment]
**Lesson list on a course page**
![image](https://github.com/WordPress/Learn/assets/18050944/79f7cca8-22a5-44df-8801-67ad69bf12b3)

I'm still not sure if the "in progress" status of a lesson can be retrieved on the course page. If it can, what do you think if we move the black semicircle indicator to the bottom for consistency, or to the left side?

**Lesson list on a lesson page**
![image](https://github.com/WordPress/Learn/assets/18050944/33248ed2-e6c9-4de3-9db6-c3296c94bfce)

**Comment by outdoor2kode** [comment]
> The "Preview" pill does not provide any new information, and clicking on it takes you to the same page as those without the pill.

I've looked into it a bit and it turns out the "Preview" pill comes from this setting of a lesson post. If it's not checked, there won't be a "Preview" pill:

| Preivew option | If not checked |
|-|-|
| ![image](https://github.com/WordPress/Learn/assets/18050944/d6892ad0-a011-41c8-a9c0-9630cd46c1ad) | ![image](https://github.com/WordPress/Learn/assets/18050944/2654d3ed-1925-4d4e-b102-06580c2c786e) |

| Logged-out users will see the following when clicking on it (No content display) | For logged-in users, it will look like this |
|-|-|
| ![image](https://github.com/WordPress/Learn/assets/18050944/2236cf54-0469-443f-b746-16144095502b) | ![image](https://github.com/WordPress/Learn/assets/18050944/1c3b41dc-9291-460c-a138-3fe52549e4da) |

ref: https://learn.wordpress.org/course/developing-your-first-wordpress-block/

## Note

1. The sign-in button style needs update. On production, it looks like: cc @adamwoodnz 
![image](https://github.com/WordPress/Learn/assets/18050944/fe6158e4-db03-41b4-8fb7-2062884602a1)


2. Do you think this eye icon needs to be displayed in the Lesson list on a course page, as it shows in the Lesson list on a lesson page?

| **Lesson list on a course page** | **Lesson list on a lesson page** |
|-|-|
| ![image](https://github.com/WordPress/Learn/assets/18050944/a4f9837a-04a1-4131-b41e-622108b3b21d) | ![image](https://github.com/WordPress/Learn/assets/18050944/6cdc8b59-2004-428d-bd35-246765ce02e0) |

**Comment by outdoor2kode** [comment]
@fcoveram Thanks for the design update! They look great, except for a few questions being brought up above.

> The progress bar has a new style for Not started, In progress, and Completed. If we go with this version, we could apply it to all places where it's visible.

I'd also like to know @adamwoodnz thoughts on the updated progress bar and other [updated design](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=4247-12723&m=dev).

**Comment by adamwoodnz** [comment]
> I'd also like to know @adamwoodnz thoughts on the updated progress bar and other [updated design](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=4247-12723&m=dev).

LGTM!

**Comment by fcoveram** [comment]
> I'm still not sure if the "in progress" status of a lesson can be retrieved on the course page. If it can, what do you think if we move the black semicircle indicator to the bottom for consistency, or to the left side?

Done. I moved it to the bottom

> I've looked into it a bit and it turns out the "Preview" pill comes from this setting of a lesson post. If it's not checked, there won't be a "Preview" pill:

To keep consistency, I included the `lock-outline` icon from the WordPress library. Here is a screenshot of the mockup added.

![Mockup of private lessons in a course page](https://github.com/WordPress/Learn/assets/895819/5089b6fa-4b50-40cd-9775-9b557af65ab6)

On the other hand, I cleaned up the sections in the [Design page](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=1705-79&m=dev) to distinguish between mockups for Courses and Lessons. In each, I included the sidebar and lesson list variants for courses as assets.

I hope this works. Let me know if I'm missing something.

---

Regarding your notes

> The sign-in button style needs update. On production, it looks like: cc [@adamwoodnz](https://github.com/adamwoodnz)

I would go with something very simple. Put the sign-in button next to the blue one with the same style as the “Practice on a private demo site” button on the course page.

> Do you think this eye icon needs to be displayed in the Lesson list on a course page, as it shows in the Lesson list on a lesson page?

I couldn’t find a Lesson showing this. Can you share a link to understand the context?

**Comment by outdoor2kode** [comment]
> > Do you think this eye icon needs to be displayed in the Lesson list on a course page, as it shows in the Lesson list on a lesson page?
> 
> I couldn’t find a Lesson showing this. Can you share a link to understand the context?

sorry that I missed attaching an example for that one: https://learn.wordpress.org/course/beginner-wordpress-developer/

**Comment by fcoveram** [comment]
Awesome. Now I understand.

> Do you think this eye icon needs to be displayed in the Lesson list on a course page, as it shows in the Lesson list on a lesson page?

Not really. The eye is redundant as the link itself conveys the preview action.
