### ISSUE TITLE
Survey CTA on Course Completed page

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2532]
On the **[Course Completed](https://learn.wordpress.org/test/course-completed/)** page, we would like to incorporate a link to a learner satisfaction survey.

Survey (content of which is still in progress) - https://docs.google.com/forms/d/e/1FAIpQLSf0QMflUedxjta0u5qS4_pl-9aY06BDBXgRn2PoZA1gRvD9jw/viewform

Let's add a CTA that stands out from everything else on the page, as this is an important element we want learners to notice and take action on.

Text (TBC):

> Please share your feedback on this course by [completing this brief survey.](https://docs.google.com/forms/d/e/1FAIpQLSf0QMflUedxjta0u5qS4_pl-9aY06BDBXgRn2PoZA1gRvD9jw/viewform)

I'd suggest placing the learner survey text below "Congratulations on completing this course! 🥳"
![Lesson_List_on_Course_Single_Page_and_Course_Completed_Page_·_Issue__2531_·_WordPress_Learn](https://github.com/WordPress/Learn/assets/7662449/9dd1e8d9-ddca-45ac-9a7f-75e4a81a4c36)

(I'd also suggest moving the "Find more courses" button below the table, toward the bottom of the page.)

**Comment by thetinyl** [comment]
@kathrynwp Looking at this page as a whole, I'm suggesting the following copy updates (including the survey CTA). I've included this copy in the overall copy document as well:

**HEAD:**
You completed the course!

**BODY COPY:**
Congratulations! You did it. Give yourself a high five, tell someone you care about, or take a proud moment to reflect on all the new things you know.

What did you think about the course? [Complete this brief survey](https://docs.google.com/forms/d/e/1FAIpQLSf0QMflUedxjta0u5qS4_pl-9aY06BDBXgRn2PoZA1gRvD9jw/viewform) to share your feedback.  

**CTA:**
Ready to keep learning?
[BUTTON] [Find another course](https://learn.wordpress.org/courses/)

**Comment by kathrynwp** [comment]
@thetinyl I like it! The only thing I think we might want to reconsider is the part specifically mentioning WordPress: "all the new WordPress things you know"... because there are quite a few courses that are not _directly_ WordPress-related, such as community-related courses like incident response handling, reimbursement requests, etc. What do you think? Maybe just remove the word "WordPress"?

**Comment by thetinyl** [comment]
@kathrynwp Great point! Thanks for mentioning that. _poof!_ It's gone! (I've edited above.)

**Comment by adamwoodnz** [comment]
Will be completed in https://github.com/WordPress/Learn/issues/2528
