### ISSUE TITLE
Meeting Agenda JUNE 20, 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2539]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @bsanevans and @digitalchild ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- June 20 – @jagirbahesh
- June 27 – @Arun Sharma
- July 4 - looking for volunteer
- July 11- looking for volunteer

**2. Looking for feedback**

- (Destiny will talk with you about this.) Ask team do we need a separate [LearnWP Topic Vetting board](https://github.com/orgs/WordPress/projects/105/views/1) for vetting topics? What is the value of having SME’s own the current board? Could we just add a column at the left of the [LearnWP Content- Development board](https://github.com/orgs/WordPress/projects/33/views/1) 
- Goals Half Year Review post by Destiny. 

**3. Looking for volunteers**

- item 1
- item 2

**4. Updates from last week's dev-squad triage session**

Attendees: @psykro (Jonathan) and @digitalchild (Jamie Madden)

Bugs triaged:
- #2533 
- #2487 
- #2480 
- #2461 

**5. Other news**

-  The Faculty Updates is a great place to see what contributors are working on. We would love for all training team members to share issues or projects they are working on. Starting next week the Faculty Updates section will be renamed the Contributor Updates to include all 2,652 of you. 
- Destiny is cleaning up the [Topic Vetting Board](https://github.com/orgs/WordPress/projects/105/views/1) since we are focusing on lessons and the Learning Pathways project several of the topics are no longer relevant. 

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have # issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have # issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have # issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have # issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have # issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: 
- Props: 

## 4. Project updates

- Project_1
  - details
- Project_2
  - details

## 5. Faculty Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by Piyopiyo-Kitsune** [comment]
Please add [Training Team 2024 Half Year Review](https://make.wordpress.org/training/2024/06/18/training-team-2024-half-year-review/) to the agenda 😄

**Comment by ghost** [comment]
Cynthia won Kim Parsell Scholarship- the https://us.wordcamp.org/2024/announcing-the-2024-kim-parsell-memorial-scholarship-recipient-cynthia-norman/

**Comment by kathrynwp** [comment]
### Props

Props to all the contributors who created [thumbnail graphics](https://make.wordpress.org/training/2024/06/10/thumbnail-creation-project/) for the new Learn WordPress site during and following WCEU Contributor Day. Special shout-out to Sumit Singh, Ben Evans, and last but not least, Rico F. Lüthi, who even made some spiffy custom screenshots to use in the thumbnails. Well done, everyone!

### Online Workshop

The thumbnail creation project could use more help – and guess what, it's actually fun to create these graphics that are used for courses, lessons, and tutorials on the new site. You can see examples of what the graphics look like in the Featured Courses and Courses sections [on the new site, which can be previewed here](https://learn.wordpress.org/?new-theme=1). I've scheduled a ["thumbnail-a-thon" online workshop](https://www.meetup.com/learn-wordpress-online-workshops/events/301712533/) on **June 25 at 17 UTC** to walk you through the process. ([convert to your time zone](https://time.is/1700_25_June_2024_in_UTC)) No graphic design skills needed, I'll show you everything you need to know. [Join us!](https://www.meetup.com/learn-wordpress-online-workshops/events/301712533/)

### Learner survey

The Training team first started discussing the idea of incorporating satisfaction surveys on the new Learn.WordPress.org site back in March, and I wanted to share the direction we're currently heading in. At the end of each course, we'd like to link to an anonymous learner satisfaction survey, with the main goal of measuring how satisfied people were with the course. We will aim to maintain a minimum average score of 4 out of 5 across all courses, where 5 is the most satisfied.

In the same survey, we'll solicit feedback on how the course can be improved, find out if people feel more confident in their skills now than before they took the course, and solicit optional testimonials for use in spreading the word about courses on Learn.WordPress.org.

[Here's the draft survey.](https://docs.google.com/forms/d/e/1FAIpQLSf0QMflUedxjta0u5qS4_pl-9aY06BDBXgRn2PoZA1gRvD9jw/viewform)

We'll regularly assess the survey results and create a feedback loop with content creators to share both positive feedback, and where there are areas for improvement, following the team's established feedback processes.

Please share any feedback on the survey before July 3.

**Comment by kathrynwp** [comment]
### Faculty program retirement

As there has been consensus around the [proposal put forward two weeks ago](https://wordpress.slack.com/archives/C02RW657Q/p1717632987733479) to retire the [Faculty program](https://make.wordpress.org/training/handbook/faculty-program/), we'll be moving ahead as discussed. I'll put together a plan of action on the steps needed to get this done.

**Comment by kathrynwp** [comment]
### Project Update 

#### Learn WordPress Remake

Posted an update here: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4283

**Comment by Zeelthakkar1207** [comment]
I am interested as a Meeting note taker for 4th July.

**Comment by kaitohm** [comment]
This meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1718842415767709

**Comment by ghost** [comment]
Recap: https://make.wordpress.org/training/2024/06/26/training-team-meeting-recap-20th-june-2024/
