### ISSUE TITLE
Lesson: Why would a WordPress user need to run a local site?

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2543]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan):
- Content title: Why would you need to run a local site?
- Topic description: 
Demonstrate GUI-based local tools: Local, Studio, and Playground.
What are the pros and cons of each tool?
Audience (User, Developer, Designer, Contributor, etc.): User
Experience Level (Beginner, Intermediate, Advanced, Any): Advanced

# Related Resources and Other Notes

### Automation Code

//lesson

**Comment by westnz** [comment]
Script: https://docs.google.com/document/d/1RchvLOZs8N4m_pLUbeFtRb0sXxBvU63XRD-tJ9F07xE/edit#heading=h.hqe4a9arucf

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/21c35231-1e78-4b99-9ff2-066d47c7f6e9

**Comment by RoelofWobben** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [X] Learning outcomes/objectives are clear.
- [X] Technical concepts introduced in the content are accurate.
- [X] The speed of demonstrations are easy to follow.
- [X] The narration audio matches what is shown visually.
- [X] Spelling and grammar are correct.
- [X] Sound quality is consistent throughout the video.
- [X] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [X] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

I like that you have a good slow speed to explain things and that there is a logical path in the video

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

A wonderful walkthrough of the alternatives, @westnz. I like the focus on **why** and user-friendly apps (as in, no terminal needed). 

I think that calling these **GUI** (at 1:37) isn’t necessary. Although it’s correct, it introduces the term without context (the opposite of CLI, basically). Maybe showing a slide with logos is enough?

**Comment by rfluethi** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

---

An excellent summary of the simple ways to run WordPress locally.

---

Wouldn't it be useful to include the links to Local and Studio in the script so users can download the software packages?
- [Local - Local WordPress development made simple](https://localwp.com/)
- [Studio by WordPress.com – Developer Resources](https://developer.wordpress.com/studio/)

It might also be helpful to add links to other options:
- [XAMPP Installers and Downloads for Apache Friends](https://www.apachefriends.org/index.html)
- [Docker: Accelerated Container Application Development](https://www.docker.com/)
- [MAMP & MAMP PRO](https://www.mamp.info/)
  
---

Additionally, you could include a note in the Playground on how to load language packs for WordPress. This is especially important for beginners.

Either go to the settings under "Customize Playground" and select "Network access (e.g., browsing plugins)" to load the language in WordPress.

Alternatively, this can also be done directly via URL, for example:
https://playground.wordpress.net/?language=fa_IR
for Persian.

**Comment by westnz** [comment]
Thank you for the helpful feedback and suggestions, folks!

**Comment by Soir7** [comment]
Please tick all items you've confirmed:

     Learning outcomes/objectives are clear.

 Technical concepts introduced in the content are accurate.
 The speed of demonstrations are easy to follow.
 The narration audio matches what is shown visually.
 Spelling and grammar are correct.
 Sound quality is consistent throughout the video.
 [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
 Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

opic description:
Demonstrate GUI-based local tools: Local, Studio, and Playground.
What are the pros and cons of each tool?

**Comment by Soir7** [comment]
Learning outcomes/objectives are clear.

 Technical concepts introduced in the content are accurate.
 The speed of demonstrations are easy to follow.
 The narration audio matches what is shown visually.
 Spelling and grammar are correct.
 Sound quality is consistent throughout the video.
 [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
 Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by Soir7** [comment]
Please tick all items you've confirmed:

     Learning outcomes/objectives are clear.

 Technical concepts introduced in the content are accurate.
 The speed of demonstrations are easy to follow.
 The narration audio matches what is shown visually.
 Spelling and grammar are correct.
 Sound quality is consistent throughout the video.
 [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
 Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by Soir7** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by Soir7** [comment]
@westnz clear and easy to understand presentation. Glad to see the three additional local options included.

Though I see this video is in 'preparing to publish state', it think this may be worth mentioning.  One of the goals of this video is stated as follows:  

**What are the pros and cons of each tool?**

In the aggregate, the video presents the **overall** benefit of using any of the local options.  No 'cons' are stated (individually). The exception could be when the the provisional nature (browser based) of playground was highlighted. 

As a general introduction to using local, the video beautifully hits the mark.

Have a great weekend!

**Comment by westnz** [comment]
Thank you very much for the feedback @Soir7.

**Comment by westnz** [comment]
//published
