### ISSUE TITLE
Links are broken on Courses page

### ISSUE THREAD

**Issue by samy** [WordPress/Learn#2544]
## Type of feedback
//content

## Description
On Cours page, all courses links are broken

## Step-by-step reproduction instructions (optional)
- Go to https://learn.wordpress.org/courses/
- Switch to a language which is not English (eg. French)
- Click on any course, like "Introduction to Block Development: Build your first custom block"
- The link is https://learn.wordpress.org/cours/introduction-to-block-development-build-your-first-custom-block/ but should be https://learn.wordpress.org/course/introduction-to-block-development-build-your-first-custom-block/

**Comment by clementpolito** [comment]
Hi ! 

There is the same problem on lesson pages.

On the page https://learn.wordpress.org/course/introduction-to-block-development-build-your-first-custom-block/, the URL link of the lesson "What is a block? " is https://learn.wordpress.org/lecon/what-is-a-block/ ("lecon")but the good page is https://learn.wordpress.org/lesson/what-is-a-block/ ("lesson")

Test realized in private browsing mode, not connected to my WP.org account.

![wp-course-lesson-url-bug](https://github.com/WordPress/Learn/assets/10175351/0767a3f3-8b43-45c9-9c73-8ef537b0982c)

**Comment by adamwoodnz** [comment]
Hi, thanks for reporting. It is not like this for me:

| Courses | Course |
|--------|--------|
| ![Screenshot 2024-06-18 at 9 43 21 PM](https://github.com/WordPress/Learn/assets/1017872/6a928fb0-8d63-484e-aa70-4cfd42e4a661) | ![Screenshot 2024-06-18 at 9 42 56 PM](https://github.com/WordPress/Learn/assets/1017872/c30389ef-0c4d-4d57-a3a2-e6fe649f999b) |

I'm wondering if the post type is being translated, I'm viewing the site in English, how about you?

**Comment by clementpolito** [comment]
Maybe I am on the french site, some texts are in french. But the URL does not contain fr subdomain. So I don't really know.

But I can say that the first 4 links "Developing with WordPress, Introduction to WordPress, 
Using the Site Editor, Contributing to WordPress points to /courses/ pages, while others links like "Introduction to Block Development: Build your first custom block", "Using the WordPress Data Layer", "A Developers Guide to Block Themes – Part 1", etc. in the same page point to /cours/.

![CleanShot 2024-06-18 at 16 48 54](https://github.com/WordPress/Learn/assets/10175351/09998dc3-a2a4-48c2-881c-696b84557e60)

![CleanShot 2024-06-18 at 16 53 27](https://github.com/WordPress/Learn/assets/10175351/ae77d36b-836e-4344-913b-4d6ae6392d0c)

**Comment by mjaragon** [comment]
This happened to me too.

When I'm in "My Courses" page: 
https://learn.wordpress.org/my-courses/ 

"Open Source Basics and WordPress" links to: https://learn.wordpress.org/kurs/open-source-basics-and-wordpress/

Which I think it's because based on my location (Germany), the browser shows me everything in German (de_DE).

![image](https://github.com/WordPress/Learn/assets/30312698/a1135bb9-34af-4aa9-a500-9c78cc2c20ba)


If I switch the language to English (en_US)

https://learn.wordpress.org/my-courses/?locale=en_US , then the link works and goes to: https://learn.wordpress.org/course/open-source-basics-and-wordpress/

**Comment by adamwoodnz** [comment]
> Maybe I am on the french site, some texts are in french. But the URL does not contain fr subdomain. So I don't really know.

Yes the site is definitely using French, I can tell from your screenshot, and if I switch to French I can reproduce.

> But I can say that the first 4 links "Developing with WordPress, Introduction to WordPress, Using the Site Editor, Contributing to WordPress points to /courses/ pages, while others links like "Introduction to Block Development: Build your first custom block", "Using the WordPress Data Layer", "A Developers Guide to Block Themes – Part 1", etc. in the same page point to /cours/.

The first 4 links are just internal links on the page, so they match the current URL, while the others are permalinks, and appear to have the post type translated, which doesn't match what the site expects for routes.

**Comment by samy** [comment]
thanks @adamwoodnz
