### ISSUE TITLE
Add wide alignment support to the current theme

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2557]
It would be great if the current theme supported the block editor 'align-wide' theme support. 

I want to be able to use the Playground block in the code editor mode for practical exercises in the developer learning pathway. 

However, I would like to create these exercises on separate pages, where the block can be set to take up the full page width, as this provides a better user experience when using the code editor. 

Adding it this way on a separate page also means I can link to it from the relevant lesson instead of forcing users to view/skip over the block in the lesson itself.

**Comment by jonathanbossenger** [comment]
I just tested this, and the page template itself needs to support wide alignment as well, so closing this out, will have to wait for the new theme.

**Comment by adamwoodnz** [comment]
> will have to wait for the new theme.

I believe we should still be waiting for a11y issues with the Playground Block to be fixed, or has that happened now?

**Comment by jonathanbossenger** [comment]
That's part of why I wanted to create specific separate pages with my playground implementations linked to the lesson content, not added to the block inside lessons. This would allow folks the choice to either open the playground implementation in a new window, or skip it and move on with the content.

**Comment by adamwoodnz** [comment]
> That's part of why I wanted to create specific separate pages with my playground implementations linked to the lesson content, not added to the block inside lessons. This would allow folks the choice to either open the playground implementation in a new window, or skip it and move on with the content.

Sorry, I missed that 🤦
