### ISSUE TITLE
Bengali translation for "How to test WordPress beta releases"

### ISSUE THREAD

**Issue by noruzzamans** [WordPress/Learn#2562]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/how-to-test-wordpress-beta-release/ 
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: devmuhib009
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by noruzzamans** [comment]
Hello, Translation reviewer. I have translated this document. [Please check it.](https://docs.google.com/document/d/1wYTapPZjsUFJneK16PyVFElXD7EoXd2DwCI_PJ-YRE4/edit?usp=sharing)

**Comment by devmuhib009** [comment]
I'll review the content soon.

**Comment by devmuhib009** [comment]
Please follow these [instructions](https://docs.google.com/document/d/1xNcEeFfg6ZySTZuU2zGii70BClepJC8XRYx73lr5HOg/edit?usp=sharing).

**Comment by noruzzamans** [comment]
Thanks for reviewing my content and providing your valuable instructions. I have followed your instructions and updated my content. [Please review it again](https://docs.google.com/document/d/1wYTapPZjsUFJneK16PyVFElXD7EoXd2DwCI_PJ-YRE4/edit?usp=sharing). Thanks.

**Comment by devmuhib009** [comment]
- Use বেটা or বিটা, not both.

> এই বিস্তারিত প্রদর্শনী ভিডিওর সাহায্যে ওয়ার্ডপ্রেস বিটা রিলিজগুলির ক্ষমতা উন্মোচন করুন!

এই কম্প্রিহেনসিভ ভিডিওটির মাধ্যমে ওয়ার্ডপ্রেস বেটা রিলিজ ক্ষমতা সম্পর্কে জানুন

> অন্তর্দৃষ্টিপূর্ণ

ইনসাইটফুল

There are lots of words and sentences you need to make understandable. Please try to translate it as we speak bengali. Revise whole content and update please.

**Comment by noruzzamans** [comment]
Apologies for this. I appreciate your patience. I have reviewed all the content and tried to make it understandable in the Bengali language. Could you review [it again](https://docs.google.com/document/d/1wYTapPZjsUFJneK16PyVFElXD7EoXd2DwCI_PJ-YRE4/edit?usp=sharing)?

**Comment by devmuhib009** [comment]
Thank you for making the corrections. The changes are excellent! I appreciate your hard work!

Please give your WordPress username so I can add you to the learn WordPress website. If you are already a member of learn.wordpress.org, just draft the post and submit the subtitle on wordpress.tv.

Thanks

**Comment by noruzzamans** [comment]
Thanks. My WordPress username is 'noruzzaman'. I don't know how to submit subtitles on WordPress.tv. Could you share any guideline videos or text on how to do this?

**Comment by devmuhib009** [comment]
Hi, I've added you to the learn.wordpress.org site. Please accept the invitation and draft the post following below instructions.
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video
Please complete step 5 to 7 and let me know. In step 5, you please create a post from wp-admin>tutorial>new-post. After drafting the post, submit the subtitle which is step 6.
Thanks

**Comment by noruzzamans** [comment]
Hi, thank you for adding me to the learn.wordpress.org site. I have added a new post following your guidelines. Please review and approve it. 
Thanks!

**Comment by devmuhib009** [comment]
Please submit the subtitle on WordPress tv, so I can approve both together.

**Comment by noruzzamans** [comment]
Hi, Apologies for this question. Could you please tell me how to post subtitles on WordPress TV? I now have access to learn.wordpress.org. Is it possible to post subtitles using learn.wordpress.org, or do I need a separate account like learn.wordpress.org? Thanks!

**Comment by devmuhib009** [comment]
Here is instruction to subtitle the video: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-subtitles/#adding-translated-subtitles-to-an-english-video

1. Visit the video from WP TV: https://wordpress.tv/2024/03/08/how-to-test-wordpress-beta-release/
2. Search for "SUBTITLES" and click on "Subtitle this video →"
In this page you can submit subtitle and below this you will find a video instruction for better understanding. 

If you don't understand the process, please call me in slack.
Thanks

**Comment by noruzzamans** [comment]
Hello,

I have submitted the subtitle file to WordPress TV and posted it on learn.wordpress. Please review both and approve them. Thanks

Noruzzaman

**Comment by devmuhib009** [comment]
Thanks for translating. Tutorial published here: https://learn.wordpress.org/tutorial/bn-how-to-test-wordpress-beta-release/
//published

**Comment by noruzzamans** [comment]
Thanks
