### ISSUE TITLE
Meeting Agenda June 27, 2024

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#2568]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- June 27 – [@Arun Sharma](https://wordpress.slack.com/team/U06SEMB4YPJ)
- July 4 – [@Zeel Thakkar](https://wordpress.slack.com/team/U06S6SL174K)
- July 11 – [@Kruti](https://wordpress.slack.com/team/U075SJR8RDZ)
- July 18 – looking for volunteer

**2. Looking for feedback**

- [WordCamp Europe 2024 presentation recap](https://make.wordpress.org/training/2024/06/21/wordcamp-europe-2024-presentation-recap/)
- @lada7042 set up a [GatherPress test site](https://demo.gatherpress.org/learn-wordpress-online-workshops/event/online-workshop-making-websites/) and needs help testing! Please Click the RSVP button and create a login to test RSVPing to the event!
- The [Training Team 2024 Half Year Review](https://make.wordpress.org/training/2024/06/18/training-team-2024-half-year-review/) is now up! Please share your feedback on the current progress of our goals.

**3. Looking for volunteers**

- We are looking for folks to [review tutorials](https://docs.google.com/spreadsheets/d/15ZMa3GFLb7Pp9n2j32vxnojctdWrT0WRzheo56Q_qtk/edit?gid=2045046859#gid=2045046859) and determine if we keep, update, or deprecate them.
- The [Thumbnail Creation Project](https://make.wordpress.org/training/2024/06/10/thumbnail-creation-project/) also requires volunteers to help make thumbnails for the new Learn site

**4. Other news**

- item 1
- item 2

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 14 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 27 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 4 issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have 0 issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 16 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: Training Contributor Badge awarded to [Shipon Karmakar](https://profiles.wordpress.org/shiponkarmakar/)
- Props: 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - details
- [Thumbnail Creation Project](https://make.wordpress.org/training/2024/06/10/thumbnail-creation-project/)
  - details

## 5. Contributor Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kathrynwp** [comment]
Props to Laura Adamonis for co-hosting the Thumbnail-a-thon Online Workshop with me at the last minute!

**Comment by kathrynwp** [comment]
Update on Learn.WordPress.org remake: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4288

**Comment by kathrynwp** [comment]
For this item – The [Thumbnail Creation Project](https://make.wordpress.org/training/2024/06/10/thumbnail-creation-project/) also requires volunteers to help make thumbnails for the new Learn site – you could also add that we held an Online Workshop Thumbnail-a-thon to look at the thumbnail-making process together, and the recording is available. All are welcome to watch it and help out: https://wordpress.tv/2024/06/25/thumbnail-a-thon-lets-make-graphics-together-for-the-new-learn-wordpress-org/

**Comment by kathrynwp** [comment]
Big props and thank yous to everyone who created thumbnails for the new Learn WP site during or following this week's Thumbnail-a-thon, including Laura Hartwig, Rico F. Lüthi, Kel Santiago Pilarski, Nilo Velez, and Satyam Vishwakarma!

**Comment by Piyopiyo-Kitsune** [comment]
Notes - https://make.wordpress.org/training/2024/07/12/training-team-meeting-recap-27th-june-2024/
