### ISSUE TITLE
Bengali translation for Tutorial "Add media and Openverse images to your content directly from the Inserter"

### ISSUE THREAD

**Issue by gmrafi** [WordPress/Learn#2570]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/add-media-and-openverse-images-to-your-content-directly-from-the-inserter/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/1418
- Language you'll be translating to: Bangla/Bengali
- Have you arranged for someone to review this translation?: 
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by gmrafi** [comment]
Just translated the original content, here is the [Doc file link](https://docs.google.com/document/d/1k49ggabl4iRcgT0T4YY5ueAqmDgWyxgWNC0z5R4uogo/edit?usp=sharing)

**Comment by devmuhib009** [comment]
This translation is fine to me. Just remove english words. You kept some words in english which is fine, but in future learn WordPress is planning to add translation plugin which will detect these as non-bengali word again. So I suggest just type the english words in bengali like "Inserter " to "ইনসার্টআর".


Please give your WordPress username, so I can add you as contributor to learn.wordpress.org website. Thanks

**Comment by gmrafi** [comment]
Here is the draft of the post: https://learn.wordpress.org/wp-admin/post.php?post=257626&action=edit

**Comment by devmuhib009** [comment]
Please complete step 6: https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video
After submitting subtitle, please let me know.

**Comment by gmrafi** [comment]
I have completed the subtitle submission part.

**Comment by devmuhib009** [comment]
Article Published Here: https://learn.wordpress.org/tutorial/bn-add-media-and-openverse-images-to-your-content-directly-from-the-inserter/

//published
