### ISSUE TITLE
Bengali translation for Tutorial "Horizontal Pyramid Gallery"

### ISSUE THREAD

**Issue by gmrafi** [WordPress/Learn#2571]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/horizontal-pyramid-gallery/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/789
- Language you'll be translating to: Bangla/Bengali
- Have you arranged for someone to review this translation?: 
- Reviewer's GitHub username: 
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by gmrafi** [comment]
I just translated the original content, here is the [Doc file link](https://docs.google.com/document/d/1STkqGnaczbuIGzZcfMZbXtEmzUf1vbheUi7EDRWgNmE/edit)

**Comment by devmuhib009** [comment]
> অনুভূমিক

হরিজনটাল

> সারি ব্লক

রো ব্লক

> এই সেশনে, আমরা শিখব শুধুমাত্র একটি সারি ব্লক এবং কভার ব্লক ব্যবহার করে কিভাবে একটি অনুভূমিক পিরামিড গ্যালারি তৈরি করা যায়।

এই সেশনে, আমরা শিখব কিভাবে একটি হরিজনটাল পিরামিড গ্যালারি তৈরি করা যায় শুধুমাত্র একটি রো ব্লক এবং কভার ব্লক ব্যবহার করে।

Here are some guidelines you can follow. 
https://docs.google.com/document/d/1xNcEeFfg6ZySTZuU2zGii70BClepJC8XRYx73lr5HOg/edit?usp=sharing
Also I am not sure why you used some red marks. Please modify the content again and resubmit please.

Thanks

**Comment by gmrafi** [comment]
I have implemented your suggestions. Here is the link to the document: (https://docs.google.com/document/d/1STkqGnaczbuIGzZcfMZbXtEmzUf1vbheUi7EDRWgNmE/edit)). 

Also drafting the post: https://learn.wordpress.org/wp-admin/post.php?post=257630&action=edit 

I am unsure about my translation of this line: 
Nesting the Row block and multiple Cover blocks.
>রো ব্লক এবং একাধিক কভার ব্লক নেস্টিং করা ।

 which I have marked. Is it correct?

**Comment by devmuhib009** [comment]
Yes correct.
Draft the post and submit subtitle. 
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-add-subtitles-to-the-english-video

**Comment by gmrafi** [comment]
I have completed the subtitle submission part. Also drafting the post: https://learn.wordpress.org/wp-admin/post.php?post=257630&action=edit

**Comment by devmuhib009** [comment]
Thanks for your hard work! Post published here: https://learn.wordpress.org/tutorial/bn-horizontal-pyramid-gallery/

//published
