### ISSUE TITLE
Featured Lessons on home page

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#2575]
Currently the 6 Lessons on the home page are simple the most recent Lessons published. This means there is very little control over what shows up there.

To match the behaviour of the Featured Courses section above, we can follow the same approach and add a `featured` post meta field to Lessons, enabling precise selection of the Lesson set.

The query loop for that section will then need a custom query loop block (following that created for featured courses) which enables filtering by the post meta field.

- [ ] Add featured Lesson post meta to plugin
- [ ] Add featured Lessons block variation to theme
- [ ] Update home page template to use featured Lessons

**Comment by kathrynwp** [comment]
If we are not able to get to this in time for launch, two temporary ideas:

- Hide the Lessons section on the homepage for now:

<img width="1000" alt="Learn_WordPress_-_There_s_always_more_to_learn___Learn_WordPress_and_Learn_WordPress_org_Remake_–_Todoist" src="https://github.com/WordPress/Learn/assets/7662449/e2410c7d-2ca1-460c-947d-101eabe35705">

- Reorder the Lessons on the homepage so they are not displayed by most recent. Could they be randomized easily, for example?

**Comment by adamwoodnz** [comment]
> If we are not able to get to this in time for launch

No worries with this, it's about to ship

**Comment by kathrynwp** [comment]
This is amazing, thank you, @adamwoodnz! I've set six lessons to be featured, wrote a custom excerpt, and set the level for each. They appear very nicely on the homepage now:

<img width="817" alt="Learn_WordPress_-_There_s_always_more_to_learn___Learn_WordPress" src="https://github.com/WordPress/Learn/assets/7662449/10a8960c-3cfb-4dd5-9a5e-683b7a3b9b2e">
