### ISSUE TITLE
Feedback - Beginner WordPress Developer Course code blocks displayed in single line

### ISSUE THREAD

**Issue by martynmjones** [WordPress/Learn#2579]
## Type of feedback
// content

## Description
All the code samples included in the `Beginner WordPress Developer` are displaying in a single line regardless of their length making them difficult to read.

## Step-by-step reproduction instructions (optional)
1. Go to https://learn.wordpress.org/lesson/php/ or any other lesson involving code samples
2. Scroll down to any code block

## Screenshots or screen recording (optional)
<img width="1063" alt="Screenshot 2024-06-28 at 06 28 58" src="https://github.com/WordPress/Learn/assets/40762232/14faf02e-f000-43ac-8d31-1ff733ec9866">

**Comment by jonathanbossenger** [comment]
Closed as fixed
