### ISSUE TITLE
Feedback - Broken image and incomplete instructions for lesson a hands on experiment with the block editor

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2583]
## Description

In the tutorial series Getting Started With WordPress: Get Familiar, there is a broken image, and the instructions are incorrect/incomplete for 'A Hands-On Experiment With The Block Editor' under Start With a Single Post or Page. Step 2 of the instructions says "Start by clicking on / selecting the text that says, “It’s a whole new way to use WordPress. Try it right here!” This box, known as the “Block Toolbox” should appear on your screen like this:". When you open the experimental editor, the page does not contain that text. There is also a broken image under step 2. 

## Screenshots or screen recording (optional)

<img width="1282" alt="image" src="https://github.com/WordPress/Learn/assets/122839775/57c02af2-d0ac-4bc5-9af0-0e5b45b23f1c">

## Other information (optional)

The url is https://learn.wordpress.org/lesson/a-hands-on-experiment-with-the-block-editor/

**Comment by ironnysh** [comment]
# Feedback Validation Checklist:
- If this is reporting an issue, can you confirm/reproduce the issue? No: 

The issue has been fixed: The lesson was updated with the correct text and screenshot: https://learn.wordpress.org/lesson/a-hands-on-experiment-with-the-block-editor/.

Lesson page:
![Image](https://github.com/user-attachments/assets/d1a690d4-e757-4460-83ea-908815e05e07)

Experimental editor page:
![Image](https://github.com/user-attachments/assets/ab0e4cbf-841f-4d75-9a28-daac837c7ceb)


@WordPress/learn-editors

**Comment by ghost** [comment]
Awesome, thank you!

**Comment by ironnysh** [comment]
Thank _you_! :-)
