### ISSUE TITLE
Feedback - Gujarati lesson in an English course 

### ISSUE THREAD

**Issue by ironnysh** [WordPress/Learn#2587]
## Type of feedback

 //content and //dev
## Description

There’s a Gujarati lesson in the new Beginner Developer LP (all English). It’s the first lesson of the WordPress Hooks chapter:
https://learn.wordpress.org/lesson/gu-wordpress-hooks/

## Screenshots or screen recording (optional)

<img width="375" alt="image" src="https://github.com/WordPress/Learn/assets/63248335/d867e20d-cf08-41c3-9fbd-b0297c206384">

## Other information (optional)

I think this is the correct URL: https://learn.wordpress.org/lesson/wordpress-hooks/

**Comment by devmuhib009** [comment]
Hi @ironnysh 

Thanks for creating the issue. We already fixed the issue and still working so in future this do not happen again.
