### ISSUE TITLE
Meeting Agenda July 4th, 2024

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2589]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

This week’s meeting will be hosted by @digitalchild 

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- July 4 – [@Zeel Thakkar](https://wordpress.slack.com/team/U06S6SL174K)
- July 11 – [@Kruti](https://wordpress.slack.com/team/U075SJR8RDZ)
- July 18 – looking for volunteer
- July 25 - looking for volunteer

**2. Looking for feedback**

- @lada7042 set up a [GatherPress test site](https://demo.gatherpress.org/learn-wordpress-online-workshops/event/online-workshop-making-websites/) and needs help testing! Please Click the RSVP button and create a login to test RSVPing to the event!

- A plan for retiring the Faculty Program has been posted – as previously discussed and agreed by the team – with steps laid out from July 18, 2024 through September 12, 2024. https://make.wordpress.org/training/2024/07/02/project-thread-retiring-the-faculty-program/

**3. Looking for volunteers**

- We are looking for folks to [review tutorials](https://docs.google.com/spreadsheets/d/15ZMa3GFLb7Pp9n2j32vxnojctdWrT0WRzheo56Q_qtk/edit?gid=2045046859#gid=2045046859) and determine if we keep, update, or deprecate them.
- The [Thumbnail Creation Project](https://make.wordpress.org/training/2024/06/10/thumbnail-creation-project/) also requires volunteers to help make thumbnails for the new Learn site

**4. Updates from last week's dev-squad triage session**

- No dev squad last week 

**5. Other news**

- It was [reported](https://wordpress.slack.com/archives/C02RW657Q/p1719862484842059) that one of the lessons in the beginner developer pathway was replaced with a translated version
The original version seems to have been placed into draft mode, and the original content lost somehow. Feedback on ensuring processes are followed to ensure this is caught in the future before publishing.   
- The second course cohort wrapped and the recap post is up, including feedback survey results from participants and next steps: https://make.wordpress.org/training/2024/07/02/recap-the-second-learn-wordpress-course-cohort/
- [Thumbnail Creation Project](https://make.wordpress.org/training/2024/06/10/thumbnail-creation-project/)
  - The Thumbnail-a-thon online event on the 26th of June, with 18 participants working on creating thumbnails for the project. 
  - A total of 21 thumbnails were created for the project

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 13 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 28 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 4 issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have # issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have # issues awaiting a fix

## 3. Contribution Acknowledgement

- Props: 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - The [Beginner developer learning pathway](https://learn.wordpress.org/course/beginner-wordpress-developer/) was published on the 23rd of June.
  - The [Intermediate user learning pathway](https://learn.wordpress.org/course/intermediate-wordpress-user/) was published on the 3rd of July.
  - Other updates can be found on the [Project Thread](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)

- Update on Learn WP site remake: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4300
   - Heads-up that the site is nearly ready for formal QA/testing, and a post will be going up soon on the Training team p2 with instructions on what to test, and where to report bugs.
   - In the meantime everyone is welcome to preview the new theme here: https://learn.wordpress.org/?new-theme=1

## 5. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by digitalchild** [comment]
Open for discussion, should we create a script for meeting hosts in the handbook to make it easier for onboarding team reps and their meeting duties?

**Comment by westnz** [comment]
Learning Pathways
1. The [Beginner developer learning pathway](https://learn.wordpress.org/course/beginner-wordpress-developer/) was published on the 23rd of June.
2. The [Intermediate user learning pathway](https://learn.wordpress.org/course/intermediate-wordpress-user/) was published on the 3rd of July.
3. Other updates can be found on the [Project Thread](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)

**Comment by jonathanbossenger** [comment]
Translating lesson content: It looks like if translators assign a translated lesson to the original course and module, it replaces that lesson in the course (more information [here](https://wordpress.slack.com/archives/C02RW657Q/p1719862484842059)). We will need to investigate to confirm this, but until we do, it might be useful if translators of lesson content don't assign the course or module to a translated lesson.

**Comment by kathrynwp** [comment]
The second course cohort wrapped and the recap post is up, including feedback survey results from participants and next steps:

https://make.wordpress.org/training/2024/07/02/recap-the-second-learn-wordpress-course-cohort/

**Comment by kathrynwp** [comment]
I've posted a plan for retiring the Faculty Program – as previously discussed and agreed by the team – with steps laid out from July 18, 2024 through September 12, 2024.

https://make.wordpress.org/training/2024/07/02/project-thread-retiring-the-faculty-program/

**Comment by kathrynwp** [comment]
Update on Learn WP site remake: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4300

Heads-up that the site is nearly ready for formal QA/testing, and a post will be going up soon on the Training team p2 with instructions on what to test, and where to report bugs. 

In the meantime everyone is welcome to preview the new theme here: https://learn.wordpress.org/?new-theme=1

**Comment by digitalchild** [comment]
We have two volunteers for the note taker duties for the rest of the month. https://wordpress.slack.com/archives/C02RW657Q/p1720051848583349

**Comment by Zeelthakkar1207** [comment]
Meeting recap post published : https://make.wordpress.org/training/2024/07/10/training-team-meeting-recap-4th-july-2024/
