### ISSUE TITLE
Filter quiz and completed lessons from Lessons archive

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#2591]
On the Lessons archive there are items included which arguably aren't valuable to be displayed, eg. a Lesson which only holds a quiz:

<img src="https://github.com/WordPress/Learn/assets/1017872/49bb4eda-432a-4e10-b906-49776d391898" width="600">

In order to not waste screen real estate displaying these, we should filter them out.

### Questions

Can we do this simply by filtering using the content of the title?

If so what terms should be filtered; 'quiz', anything else?

**Comment by kathrynwp** [comment]
@westnz mentioned that some quiz lessons don't include the word quiz, but instead have titles like 'Test your knowledge' or 'Time to test your skills' and mentioned possibly updating those lessons' titles as being faster than figuring out other words to filter on. 

We could go through the Lessons to find and update those titles to add the word "Quiz", if we decide to proceed with title filtering. Also noting that some of the quizzes are in languages other than English so we might need to find some translations in order to update those.

Other words to possibly exclude:

- Conclusion
- Wrap up / Wrap Up / Wrap-up

**Comment by kathrynwp** [comment]
Another lesson title to exclude:

- Congratulations

**Comment by adamwoodnz** [comment]
> Also noting that some of the quizzes are in languages other than English so we might need to find some translations in order to update those.

Hmm this is an important point, thanks. We might be better off with another UI control for this, eg. a checkbox for 'Exclude Lesson from archives'

**Comment by westnz** [comment]
I think so, too, Adam.

**Comment by kathrynwp** [comment]
@adamwoodnz Agreed, I think a checkbox to exclude from archives (and the homepage) would be a great option.

**Comment by adamwoodnz** [comment]
This has shipped so there is now a settings section to control visibility in archives:

<img src="https://github.com/user-attachments/assets/a4f3eb31-cf09-4e03-bb12-ef9852d1bae8" width="300">

I have only applied it on one Lesson so far: https://learn.wordpress.org/lesson/quiz-time/

@kathrynwp @jonathanbossenger @westnz please try it out!

**Comment by westnz** [comment]
Thank you @adamwoodnz 
I tested it on these two lessons: 
1. https://learn.wordpress.org/lesson/conclusion-3/
2. https://learn.wordpress.org/lesson/conclusion/ 

When I go to 'View all lessons' and type 'Conclusion', they still appear?  
<img width="1599" alt="image" src="https://github.com/user-attachments/assets/680a3001-3b12-48a9-809c-58380c172569">

https://learn.wordpress.org/lesson/quiz-time/ also appears if I type 'Quiz.'

**Comment by adamwoodnz** [comment]
> When I go to 'View all lessons' and type 'Conclusion', they still appear?

Yes you're right, they don't seem to be excluded from search, only archive (https://learn.wordpress.org/lessons/?new-theme=1). Needs more work, thanks for testing.

**Comment by adamwoodnz** [comment]
This is caused by Jetpack search, and I've raised a new bug for it: https://github.com/WordPress/Learn/issues/2735
