### ISSUE TITLE
Display experience level on all lesson cards

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2595]
## Summary 

In the Figma mockups, all lessons have a level indicated on the card in the Lessons area on the homepage, as well as the Lessons archive page. But these levels aren't showing consistently on the site.

#### Card - Figma

![Learn_–_Figma](https://github.com/WordPress/Learn/assets/7662449/0c6ffbd5-0468-4283-96b9-273ac5ceda19)

#### Archive page - Figma

<img width="622" alt="Notification_Center" src="https://github.com/WordPress/Learn/assets/7662449/9088decd-cb3b-4ae0-850f-4dc89a931452">

## Issue

When previewing the new theme, I only see levels (i.e. Beginner, Intermediate, Advanced) displaying on some of the lessons at the moment, when visiting the Lessons archive at https://learn.wordpress.org/lessons/?new-theme=1

For example, there **is** a level showing for [Examining the state of your PHP code](https://learn.wordpress.org/lesson/examining-the-state-of-your-php-code/), which is part of the Beginner WordPress Developer Learning Pathway (LP) course:

But there **isn't** a level showing for [SEO strategies](https://learn.wordpress.org/lesson/seo-strategies/), which is part of the Intermediate WordPress Developer LP course.

<img width="802" alt="Lessons___Learn_WordPress" src="https://github.com/WordPress/Learn/assets/7662449/192ded14-b55e-4a81-bc99-3370529c4c99">

## Solution

The level would be a useful thing to always display on **all** lesson cards, even for those that are not standalone lessons. Since lesson cards often appear outside of the course to which they belong, having the level listed for them would provide valuable context to learners about whether a lesson is well suited to them or not. 

Is it possible to have it displayed consistently on all lessons, both standalone lessons, as well as those that are part of a course (whether a LP course or not)? 

Perhaps this is something that can be done without needing development time, by making sure an experience level is checked off for each individual lesson. For example, no experience level is checked for SEO strategies, which may explain why it's not showing in its card:

<img width="287" alt="Edit_Lesson_“SEO_strategies”_‹_Learn_WordPress_—_WordPress" src="https://github.com/WordPress/Learn/assets/7662449/22e16f76-d76a-4d80-b155-47e32ed0440b">

An experience level **is** checked for Examining the state of your PHP code:

<img width="260" alt="Edit_Lesson_“Examining_the_state_of_your_PHP_code”_‹_Learn_WordPress_—_WordPress" src="https://github.com/WordPress/Learn/assets/7662449/0fd166b4-48ed-4270-ac55-238e3e2beef4">

Or if there is a quick dev fix that would be faster than having to go back and edit many lessons manually, that would be welcome too.

**Comment by adamwoodnz** [comment]
> Perhaps this is something that can be done without needing development time, by making sure an experience level is checked off for each individual lesson. For example, no experience level is checked for SEO strategies, which may explain why it's not showing in its card:

This is correct, at the moment it's expected that Experience Level will be set per Lesson, so in the immediate term this can be resolved by setting this on Lessons in the Learning Pathway Courses.

A more long term approach could be looking up the Experience Level for the Lesson and using that, or if it's not set, looking up the Experience Level for the parent course, if it exists.

**Comment by kathrynwp** [comment]
Thanks, @adamwoodnz ! For now, I went ahead and bulk-edited the lessons belonging to the three launched Learning Pathway to add the experience level, since those are the courses we want to focus on for launch.

**Comment by kathrynwp** [comment]
I'll go ahead and close this since for now we're handling it on the content side by setting the experience level for individual lessons.
