### ISSUE TITLE
Bengali translation for "Exploring WordPress 6.5"

### ISSUE THREAD

**Issue by noruzzamans** [WordPress/Learn#2596]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/exploring-wordpress-6-5/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: devmuhib009
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by noruzzamans** [comment]
Hello, Translation reviewer. I have translated this document. [Please check it.](https://docs.google.com/document/d/1MItg9BIEoyjcDPaDSnBO4SIhYDPe0Jn419-otWnBZl4/edit?usp=sharing) Thanks

**Comment by devmuhib009** [comment]
Seems good to me. Please draft the post and submit subtitle to WPTV. Thanks

**Comment by noruzzamans** [comment]
Hello, I have submitted the subtitle file to WordPress TV and posted it on learn.wordpress. Please review both and approve them. Thanks

**Comment by devmuhib009** [comment]
Thanks for the translation: https://learn.wordpress.org/tutorial/bn-exploring-wordpress-6-5/

//published
