### ISSUE TITLE
Local navbar displays extra "dots" on the Online Workshops page

### ISSUE THREAD

**Issue by ndiego** [WordPress/Learn#2597]
If you navigate to the [Online Workshops](https://learn.wordpress.org/online-workshops/?new-theme=1) page and then scroll down the page, you will see a couple of extra dots in the local navbar. See the image below.

<img width="686" alt="image" src="https://github.com/WordPress/Learn/assets/4832319/b492872a-2f07-4222-ac41-611884bba28a">

**Comment by adamwoodnz** [comment]
Thanks for raising, I noted this on #2511, and this will be fixed in #2598
