### ISSUE TITLE
Lesson template - Stray pipe

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2601]
On lesson pages that are part of a course, there seems to be a stray pipe` | ` displaying to the left of the module name, near the top left:

### Examples

<img width="1496" alt="Log_In_With_WP-Admin___Learn_WordPress_and_Inbox__817__-_kathryn_a8c_com_-_Automattic_Mail" src="https://github.com/WordPress/Learn/assets/7662449/f73e0448-cb9b-482f-a7d4-2accdcda18bb">

from: https://learn.wordpress.org/lesson/how-to-log-in-with-wp-admin/

<img width="1498" alt="Introduction_to_WordPress___Learn_WordPress_and_Inbox__817__-_kathryn_a8c_com_-_Automattic_Mail" src="https://github.com/WordPress/Learn/assets/7662449/138bff95-3383-4171-be0c-ad485a2a74d0">

from: https://learn.wordpress.org/lesson/introduction-to-wordpress-2/

-----

Should this be removed, or is there some additional information intended to go to the left of the pipe? I don't think we need the course name there since it's already in the breadcrumbs at the top left. Couldn't find this anywhere in the Figma mockups.

**Comment by adamwoodnz** [comment]
Will be fixed as part of #2638
