### ISSUE TITLE
New Theme: Lessons should only show my language first.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2607]
## Description
When I visit https://learn.wordpress.org/lessons/?new-theme=1, it shows me lessons that are not my language.

## Step-by-step reproduction instructions (optional)

1. Go to https://learn.wordpress.org/lessons/?new-theme=1

## Screenshots or screen recording (optional)
![learn wordpress org_lessons__new-theme=1](https://github.com/WordPress/Learn/assets/1657336/5ba978c7-974b-4296-b57a-dddaf74a5469)

**Comment by adamwoodnz** [comment]
The old theme has a [this function](https://github.com/WordPress/Learn/blob/d11795d1126c09c634697ea03549881094a4ed44/wp-content/themes/pub/wporg-learn-2020/functions.php#L479) to prioritize Tutorials matching the locale, we can probably do something similar for Courses and Lessons.
