### ISSUE TITLE
New Theme: The my course page not logged in needs love.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2608]
## Description
When I'm not logged in and visit https://learn.wordpress.org/my-courses/?new-theme=1 I get a seemingly incomplete page.

## Screenshots or screen recording (optional)
<img width="1299" alt="Screenshot 2024-07-05 at 8 59 29 AM" src="https://github.com/WordPress/Learn/assets/1657336/8a27f11b-c150-4b48-aa12-17c1f3f6752e">

**Comment by adamwoodnz** [comment]
Fixed in #2592
