### ISSUE TITLE
New Theme: My Course returns all courses.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2609]
## Description
When I visit [my courses](https://learn.wordpress.org/my-courses/?new-theme=1), I see a lot of courses, many that I haven't interacted with.

## Screenshots or screen recording (optional)
![learn wordpress org_my-courses_](https://github.com/WordPress/Learn/assets/1657336/8471cc77-ad98-4717-aece-746fa5efc1d0)

**Comment by adamwoodnz** [comment]
Reproduced, behaviour is different from old theme, needs investigation.
