### ISSUE TITLE
Add visual indicator for workshop type to single workshop page

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#261]
As per this comment: https://github.com/WordPress/learn/issues/252#issuecomment-952415901

We need to add a visual cue to the single workshop page that indicates which type of workshop it is based on the `wporg_workshop_type` taxonomy. This must say something like "From the Faculty" or "From the Community" with a link to a page on the site that explains what this means.

This page needs to be created and we need to decide on what this visual cue would look like. I'll come back to this issue with some ideas, but happy to hear what anyone else thinks!

**Comment by hlashbrooke** [comment]
Here's an example of what I'm picturing here - I mocked this up using the browser inspector, so it could definitely be done better than this:
![Screenshot 2021-11-02 14 26 57](https://user-images.githubusercontent.com/1543143/139771985-241d4042-7d69-4147-ad32-79dcd66e472f.png)

**Comment by azhiya** [comment]
I think the location is great, makes it very visible.

**Comment by adamwoodnz** [comment]
Closing as Workshops (now Tutorials) are now deprecated.
