### ISSUE TITLE
New Theme: Image headers are different size.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2610]
## Description
When viewing [my courses](https://learn.wordpress.org/my-courses/?new-theme=1), I see an image header that is larger for one item.

## Screenshots or screen recording (optional)

<img width="773" alt="Screenshot 2024-07-05 at 9 03 00 AM" src="https://github.com/WordPress/Learn/assets/1657336/d7c4a712-7bfa-4230-abc2-7a843dd4ec86">

**Comment by adamwoodnz** [comment]
Fixed by https://github.com/WordPress/Learn/commit/79b4c42136f6d80a30ee927d3ef9eab0bc1af732
