### ISSUE TITLE
New Theme: Course section rendered differently.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2611]
_This may be a data problem._

## Description

When viewing [this course](https://learn.wordpress.org/course/wordpress-community-team-supporter-basics/?new-theme=1), I get the content presented like this:

<img width="889" alt="Screenshot 2024-07-05 at 9 05 00 AM" src="https://github.com/WordPress/Learn/assets/1657336/e43e264b-be69-4737-a3ec-60dd86e8c5ba">

However, If I visit [this course](https://learn.wordpress.org/course/intermediate-wordpress-user/?new-theme=1), I get it presented like this:

<img width="875" alt="Screenshot 2024-07-05 at 9 06 30 AM" src="https://github.com/WordPress/Learn/assets/1657336/fb7fceeb-3771-42f4-a041-42348ca00b82">

I would expect them to be the same.

**Comment by adamwoodnz** [comment]
The difference is due to Course 2 using Sensei Modules to group Lessons, and Course 1 not. I believe presentation is by design, see #2582
