### ISSUE TITLE
New Theme: License link is external and should be indicated as such.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2612]
## Description
On the course page, we have a link to the license. It should be denoted as external using the "↗", as are other links on the site.

It's also a super long link. Can we just link the word "License" maybe?

## Screenshots or screen recording (optional)

<img width="343" alt="Screenshot 2024-07-05 at 9 07 49 AM" src="https://github.com/WordPress/Learn/assets/1657336/95a7a510-d90b-4968-929d-753f8b9d5a56">

**Comment by adamwoodnz** [comment]
Thoughts @WordPress/meta-design ?

**Comment by jasmussen** [comment]
Yes, external links should have the ↗ arrow.

**Comment by adamwoodnz** [comment]
> It's also a super long link. Can we just link the word "License" maybe?

Sorry @jasmussen, my question was more around this

**Comment by jasmussen** [comment]
Ah, apologies, I missed that. I personally appreciate the full license, so you don't have to click it to find out what it is. I'd keep that as-is. This is also an aspect where I know @fcoveram's heart beats, so I'll defer to him.

**Comment by fcoveram** [comment]
I would not hide the license type for reasons of transparency and expectation. Instead, we can use its shorter version, "CC BY-SA 4.0 ↗" (I included the external arrow).

[Here is](https://creativecommons.org/share-your-work/cclicenses/) the official list of all licenses in case there is content under different ones.
