### ISSUE TITLE
New Theme - Playground callout on calendar page.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2617]
## Description
On https://learn.wordpress.org/online-workshops/?new-theme=1, there's a banner talking about opening Playground, why?

## Screenshots or screen recording (optional)

<img width="1249" alt="Screenshot 2024-07-05 at 9 29 10 AM" src="https://github.com/WordPress/Learn/assets/1657336/3de5daae-d1c7-4463-b30f-3898ee3362f8">

**Comment by adamwoodnz** [comment]
I think probably just [carried over from the old theme](https://learn.wordpress.org/online-workshops/?new-theme=0). @kathrynwp thoughts?

**Comment by kathrynwp** [comment]
@adamwoodnz Not sure when/why it was decided to add a callout to that specific page, but I agree, I don't think it makes sense to have it at the bottom of the new calendar page.
