### ISSUE TITLE
New Theme: Very long title on homepage.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2618]
## Description
On the homepage, we have a very long callout title. It's pretty hard to read and overwhelming. Can we make it more concise or update its treament?

## Screenshot
<img width="1260" alt="Screenshot 2024-07-05 at 9 32 06 AM" src="https://github.com/WordPress/Learn/assets/1657336/bd0afaf3-325e-4fdc-b0c5-066a462551d9">

@WordPress/meta-design

**Comment by jasmussen** [comment]
Very long indeed. If it's to be a paragraph, let's make it a paragraph, and merge it with the one below.

**Comment by adamwoodnz** [comment]
@thetinyl thoughts please?

**Comment by fcoveram** [comment]
I designed that section thinking that the long text wouldn't be overwhelming.

I can try a different layout, but to keep the section clean, I would avoid adding a white space or an image on the right side.

If the first paragraph in "Heading 4" style has fewer words, we can shift the whole layout to a 2/3 columns grid.

Looking forward to seeing @thetinyl's feedback

**Comment by thetinyl** [comment]
🤔 In my mind originally, this was two regular paragraphs. Though I can see how that might get lost without a heading as a waypoint. 

Here's a suggested update. Mostly the same text + heading:

> [HEADING]
> Share your WordPress expertise 
> ALT: Contribute your WordPress expertise
>
> [PARAGRAPH]
> Behind every course, lesson, and live workshop is a passionate collective of professionals working to offer the highest-quality educational content. If you love WordPress, have knowledge to share, and want to contribute to a thriving open source community—get involved with the Training team. 

CTA stays as-is. 

The text can be condensed, but in my opinion all parts of it provide welcome context for visitors both aware and unaware of the WordPress community and the work involved in Learn. There's also a level of aspiration here: "If I learn enough, I can help others learn too."

**Comment by adamwoodnz** [comment]
LGTM

**Comment by fcoveram** [comment]
I updated the mockup in the file's Design page. Here is a screenshot.

![CleanShot 2024-07-10 at 11 19 51@2x](https://github.com/WordPress/Learn/assets/895819/c9c5f67d-2105-4e93-9bc6-935630684190)

Notice that content uses 2/3 of the container
