### ISSUE TITLE
New Theme: Workshop card bottom not consistent.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2619]
## Description
On the homepage, I see workshops with differing title lengths. The bottom part of the card is inconsistent. I would expect the bottom to not float up for shorter titles.

## Screenshot

<img width="1251" alt="Screenshot 2024-07-05 at 9 34 33 AM" src="https://github.com/WordPress/Learn/assets/1657336/62c15fae-afc3-49da-bda9-35932cb6bb70">

**Comment by adamwoodnz** [comment]
Noting that this isn't the final state for these cards, they are intended to be like the other cards but we don't have [featured image support](https://github.com/WordPress/meeting-calendar/issues/153) yet. We could use the fallback featured image like other cards.

**Comment by adamwoodnz** [comment]
> Noting that this isn't the final state for these cards, they are intended to be like the other cards but we don't have [featured image support](https://github.com/WordPress/meeting-calendar/issues/153) yet. We could use the fallback featured image like other cards.

@WordPress/meta-design what do you think about doing this? It would mean that the layout for all cards would be consistent, but these online workshop cards would have the fallback image until we work out the featured image support, which so far has proved challenging.

Alternatively we could leave them as is and push the details to the bottom.

**Comment by jasmussen** [comment]
Can we do a min-height on the cards that is optimized for 3 lines of text, and then do a space-between stack layout where the title is top aligned and the metadata is bottom aligned?

**Comment by adamwoodnz** [comment]
> Alternatively we could leave them as is and push the details to the bottom.

> Can we do a min-height on the cards that is optimized for 3 lines of text, and then do a space-between stack layout where the title is top aligned and the metadata is bottom aligned?

👍 I think we're describing the same thing; and I'm guessing you mean 3 lines of text for the title only.

**Comment by jasmussen** [comment]
Yes! Thanks.
