### ISSUE TITLE
New Theme: Breadcrumb doesn't make sense.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2620]
## Description
I search for "block themes" in lessons and get this breadcrumb.

<img width="621" alt="Screenshot 2024-07-05 at 9 46 37 AM" src="https://github.com/WordPress/Learn/assets/1657336/045324de-31a2-4619-acc8-70fd51664376">

## Step-by-step reproduction instructions (optional)
1. Go to  https://learn.wordpress.org/lessons/
2. Search for "block themes"
3. Scroll down
4. Notice your breadcrumb reads "Learn WordPress Search results for: “block themes” Block theme styles"

I don't know where "Block theme styles" comes from.

**Comment by adamwoodnz** [comment]
Fixed by #2598
