### ISSUE TITLE
New Theme: Featured list on homepage has non-english course.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2621]
## Description
On the homepage, the featured course grid has a non-english course. That doesn't have value to me. We should show English by default. If I have a non-english language selected, we show courses that matches and maybe backfill with English.

Aside: Not sure how we order these, but I wouldn't suggest having community training courses as featured.

## Screenshot
<img width="962" alt="Screenshot 2024-07-05 at 9 54 40 AM" src="https://github.com/WordPress/Learn/assets/1657336/e84ca84e-cde2-4e0a-9b6a-e4f18b185bb5">

**Comment by kathrynwp** [comment]
The way courses are marked as featured is going to change – right now, every single course that's live has to be marked as featured, as a workaround. 

Before going live with the new site, only 6 specific courses will be manually set as featured. tl;dr the courses that are currently marked as featured won't be the same ones. I believe @adamwoodnz has a task for this somewhere so we don't forget.

**Comment by adamwoodnz** [comment]
> I believe @adamwoodnz has a task for this somewhere so we don't forget.

Correct, see https://github.com/orgs/WordPress/projects/40/views/26?pane=issue&itemId=70226616
