### ISSUE TITLE
New Theme: Menu collapses early but doesn't align with header grid.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2622]
## Description
Likely because there are many items in the menu, the menu collapses at 1400px. The arrow doesn't align with the header but instead aligns with the content.

To be quite honest, I don't think learning pathways should be in the menu at all and added that comment [in figma](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp?node-id=3473-43409#863674931).

## Screenshots or screen recording (optional)
<img width="1356" alt="Screenshot 2024-07-05 at 10 09 36 AM" src="https://github.com/WordPress/Learn/assets/1657336/7aa4621c-decf-4100-b19b-5166629fa40e">

**Comment by adamwoodnz** [comment]
@WordPress/meta-design thoughts please?

**Comment by jasmussen** [comment]
This is a curious one. _Technically_ it lines up:

<img width="426" alt="image" src="https://github.com/WordPress/Learn/assets/1204802/2c70c1da-bbce-4956-af83-e989d3de2c97">

Though Steve's assessment is accurate, optically it doesn't. But in exploring this, it feels like it's a side-effect of a somewhat unique collapsing behavior:

![collapsing](https://github.com/WordPress/Learn/assets/1204802/8b576aa7-647d-4f5d-a6ee-e597f0cbe3d6)

Note how it collapses to a dropdown twice. I'm sure there's nuance I'm missing, so looping in @fcoveram, but if it were possible to collapse at a later stage, and only once, it might be better?

**Comment by fcoveram** [comment]
The collapsed state of the local bar was thought to be next to the global header's medium variant. Here is a screenshot from the Design Library.

![Global header and local nav with spacing margins](https://github.com/WordPress/Learn/assets/895819/cececa7f-10f4-4429-8a6e-2ff3ae2dc878)

I agree that local nav items expand the area significantly, but while testing a prototype showing either the pathways or the content types, it felt like there were missing ways of browsing content. If users land on a Course, there should be an affordable way to see all Courses and the Courses related to a pathway.

Training team's input is crucial here to see what options we have. What do you think @kathrynwp @jonathanbossenger?

In terms of design, if we decide to continue showing both browsing ways, we could put the three content types in a dropdown menu. Similar to the current About page.

![Local menu of About page](https://github.com/WordPress/Learn/assets/895819/20a4dc30-64e7-43bd-bdf0-aed2389a45e0)

**Comment by adamwoodnz** [comment]
@ryelle as the most experienced local nav engineer, would you be able to take a look at this please?

**Comment by jonathanbossenger** [comment]
I'm afraid I'm not going to be much help here, I don't really use that menu when navigating around the Learn site.

**Comment by kathrynwp** [comment]
@fcoveram I'm not really following exactly what you need input on, would you mind clarifying a little more, maybe with a specific example? Thanks!

**Comment by fcoveram** [comment]
Sure. Sorry for not adding enough context.

## Problem 

The local nav, or the main navigation component of Learn, was thought to have all Learning Pathways inside a dropdown menu and the rest of links (Courses, Lessons, Online Workshops, and My courses) visible all the time to allow users browsing content in different ways.

The mockup looks like this.

![Mockup of global header and local nav of Learn section](https://github.com/WordPress/Learn/assets/895819/268daed8-8868-448a-bd7c-31f0940bb127)

The problem stated above is that all these items extend the nav area significantly and forces requires a change to the chevron menu icon before the global header changes to its simpler version. When that happens, both the global header and local nav create an odd margin; as shown in [this image](https://private-user-images.githubusercontent.com/1657336/345973512-7aa4621c-decf-4100-b19b-5166629fa40e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzM2NTEsIm5iZiI6MTcyMDUzMzM1MSwicGF0aCI6Ii8xNjU3MzM2LzM0NTk3MzUxMi03YWE0NjIxYy1kZWNmLTQxMDAtYjE5Yi01MTY2NjI5ZmE0MGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMTM1NTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGVmZDE4NjU1NWZlYzIwMjJiNGYyNDRiMmIxMzdiZTllZGQwNGE1ZTAyYjUwNGRmYTU1YWZkYzdkYjUzOWIwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HfJkAE048UvM5hsSN3wb7AKI3eCRS3S6issrbc2Dwq4).

## Solution

I envision two ways of addressing this change.

1. Remove items in the local nav and rely part of the browsing journey on links displayed in the pages
2. Group the items related to content type (Courses, Lessons, and Online Workshops) into a single dropdown element, similar to the Learning Pathways item with a chevron.

Here is a mockup for the second point with a sample label ("Content")

![Mockup of global header and local nav with fewer items](https://github.com/WordPress/Learn/assets/895819/007c53a5-9bda-49fe-a278-c9c4b9d480c1)

**Comment by kathrynwp** [comment]
Hi @fcoveram - where you say "as shown in this image" – that doesn't load for me.


> Remove items in the local nav and rely part of the browsing journey on links displayed in the pages
> Group the items related to content type (Courses, Lessons, and Online Workshops) into a single dropdown element, similar to the Learning Pathways item with a chevron.

I would really prefer if we could find a solution that doesn't add barriers for learners to navigate the site, which is what removing or condensing navigation items does, in my opinion.

If this isn't looking good aesthetically (I still can't see the problem, but I trust you that there is one) let's try to come up with an alternative solution that doesn't sacrifice user experience, making it as easy as possible for visitors to access the key parts of the site without removing items or tucking them away under a dropdown.

**Comment by ryelle** [comment]
I can add some context for _why_ this happens at what appears to be an arbitrary size. The switch happens here to prevent the menu from running into the (currently hidden) page title. For example, when you scroll down on the page, the title appears, and you can see that they're almost colliding at 1220px wide, so if your screen is <1220 (but larger than 890), the menu switches to the little collapsed dropdown. Like the expanded menu, this is aligned with the page content, not the download button.

| Menu at 1220px | Menu at 1219px |
|---|---|
| ![Screen Shot 2024-07-09 at 11 34 46](https://github.com/WordPress/Learn/assets/541093/515f863d-c171-4ded-98f7-4c4d16f07692) | ![Screen Shot 2024-07-09 at 11 38 20](https://github.com/WordPress/Learn/assets/541093/2f3ffc4d-8fc7-4149-9370-cde29e26d96b) |

The same thing happens on Developer pages with longer titles, [for example this page](https://developer.wordpress.org/advanced-administration/multisite/sites-multisite/), which switches to the dropdown at 1170px. Here's a video showing the switch.

https://github.com/WordPress/Learn/assets/541093/5f7cdf77-1de4-4e55-be7e-8d7ab2e3b47b

This will happen on any page with a long title, for example https://learn.wordpress.org/course/developing-with-the-wordpress-rest-api/. Shrinking the menu would help, but on these long-title pages it would still switch before the 890px breakpoint (which changes the global header).

If this page in particular is an issue, you could also remove the "Learning Pathway:" prefix from the local nav title.

**Comment by fcoveram** [comment]
> If this page in particular is an issue, you could also remove the "Learning Pathway:" prefix from the local nav title

I didn't understand this alternative, but if it's something we can test and see how it looks like, great.

## Section name in components and pages

I noticed that we're showing some sections differently depending on the component or the page you are looking at. I could have missed the decision of some of these, but I revisited the major changes we've implemented, and here is a table showing how the name changes.

| Section | Menu item in global header | Hero section in Homepage | Section name in local nav |
|:---|:---|:---|:---|
| News | News | News | News |
| Showcase | Showcase | Showcase | Showcase |
| Themes | Themes | Themes | Theme Directory |
| Plugins | Plugins | Plugins | Plugin Directory |
| Patterns | Patterns | Patterns | Patterns | 
| Documentation | Documentation | Documentation | Documentation |
| Forums | Forums | Forums | Forums |
| Developer | Developers | Developer Resources | WordPress Developer Resources |
 
For this issue, I think we can change the "WordPress Developer Resources" label in the local nav to be either "Developers" or "Developer Resources" and gain more space, and hopefully, prevent the layout break initially reported.

Generally speaking, I don't think the word "WordPress" and "Directory" are needed as the page provides enough context to convey users are in the WordPress site and seeing a content directory.

**Comment by ryelle** [comment]
> I didn't understand this alternative, but if it's something we can test and see how it looks like, great.

I was suggesting removing this part of the page title, which would shrink the space that the page title takes up, so the menu would have more space. That changes the breakpoint where it collapses to around 920px (in English, at least), so there's a smaller width-window between that & the global header breakpoint.

![screenshot](https://github.com/WordPress/Learn/assets/541093/d215f0ee-b87d-4510-8b9d-8f175be78cdf)

But as I said, this will still happen on other pages with long titles, like https://learn.wordpress.org/course/developing-with-the-wordpress-rest-api/ — view that page at 1300px wide, and the menu is collapsed to prevent collision.

Honestly, I think it makes sense to align this with the content, since once you scroll down, you no longer see the global header and it would look off-center if the menu was aligned to the download button.

<img width="1321" alt="Screenshot 2024-07-10 at 10 35 06 AM" src="https://github.com/WordPress/Learn/assets/541093/e421005a-8f25-4a85-97f3-f86e2efd8610">

> For this issue, I think we can change the "WordPress Developer Resources" label in the local nav to be either "Developers" or "Developer Resources" and gain more space, and hopefully, prevent the layout break initially reported.

Can you report this to the developer repo? Same for any other changes you're requesting on the other sites.

**Comment by fcoveram** [comment]
Now I understand the part that can be removed. Thanks for the clarification.

> Honestly, I think it makes sense to align this with the content, since once you scroll down, you no longer see the global header and it would look off-center if the menu was aligned to the download button.

Agree with this. But at the same time, the hierarchy should prioritize the nav elements and avoid hiding them when before the breakpoint shifts to the smaller version.

While designing the local nav, I explored a local nav version with a gradient overlapping the page name label when this overflows its container. Here is a mockup based on [the page](https://learn.wordpress.org/course/developing-with-the-wordpress-rest-api/) linked above.

![Local nav in small size with a long text in the page name section](https://github.com/WordPress/Learn/assets/895819/55ec0361-e9a1-469c-9d77-cbd19a56c71f)

Is it doable to replicate that effect in the large variant of local nav? Here is a prototype of what I have in mind.

https://github.com/WordPress/Learn/assets/895819/a4bd54d9-a9d9-4efc-89e3-14fda412b77f

**Comment by fcoveram** [comment]
I missed responding to this.

> Can you report this to the developer repo? Same for any other changes you're requesting on the other sites.

Yes. Doing it now.

**Comment by ryelle** [comment]
> Is it doable to replicate that effect in the large variant of local nav? Here is a prototype of what I have in mind.

Technically doable, but I don't think it's a great experience for the mid-sized screens to have a hidden page title.  And just about every page title would be hidden around 1000px, because there would only be space for 8-10 characters.

Also, while the overflow makes sense on small screens, where you touch to scroll often, it would introduce a scrollbar onto the page title on non-touch-screens (and since this happens on the larger-mid-sizes, will probably be desktop/laptops).

Your mockup stops at 1085px, so here's an example going all the way to the header breakpoint (890px). The page title becomes pretty much unreadable by 1000, and even the site title starts to be hidden right before the switch.

https://github.com/WordPress/Learn/assets/541093/e2e8cca7-6254-4709-acb7-24a586fe5586

Another option could be to simply _drop_ the page title when it would collide, so that only "Learn WordPress" is there:

https://github.com/WordPress/Learn/assets/541093/f28937eb-6cf2-4829-af57-0271f994e12e

Given all of that, I prefer the current implementation, followed by dropping the page title. But if you still think the overflow is the best approach, it can be done.

**Comment by fcoveram** [comment]
The overflow example looks really bad, you're right. I like the idea of dropping the page title. So +1 to that.

**Comment by ryelle** [comment]
> I like the idea of dropping the page title. So +1 to that.

Cool, let's do that. I've moved this over to a wporg-mu-plugins issue since it's site-wide, this doesn't need to be tied to Learn. https://github.com/WordPress/wporg-mu-plugins/issues/640
