### ISSUE TITLE
Product control for stock take 

### ISSUE THREAD

**Issue by StrictlyDancing** [WordPress/Learn#2623]
# Details

- Topic description: 
- Audience (User, Developer, Designer, Contributor, etc.): 
- Learning objectives (What will the learner be able to do as a result of this content?): 
- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): 
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by StrictlyDancing** [comment]
We have all our shoes on our web site but they are not linked to sales . If a shoe is sold we want it taken out of stock

**Comment by kaitohm** [comment]
It looks like you might be searching for help with your site. Please contact your host for support.
