### ISSUE TITLE
Lesson: Unlocking advanced SEO techniques: Part 2

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2624]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title:  Unlocking advanced SEO techniques: Part 2
- Topic description: 
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Advanced 

# Learning Objectives

# Related Resources and Other Notes

### Automation Code

//lesson

**Comment by westnz** [comment]
Part 1: https://github.com/WordPress/Learn/issues/2301

**Comment by westnz** [comment]
Part 2: [Script](https://docs.google.com/document/d/16twUzYVGn93WP6WxnkoIkOFQ1Smq-GiIdNLk8-Gtd7E/edit#heading=h.hzq71y3jflf4)

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/de34a739-1ec6-42a4-aa5c-313950944920

**Comment by digitalchild** [comment]
This is a good outline of technical SEO to build on part 1. For the broken link checker, you might want to mention that there are a number of plugins and services available to automate this. 

Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by kaitohm** [comment]
I like the fact the video shows both Yoast and Rank Math - two plugins!

## Content Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by westnz** [comment]
Thanks for the reviews @digitalchild and @kaitohm

**Comment by patelamitn** [comment]
Great work @westnz. I liked the section where schema structures are mentioned. Those are highly crucial for website data in the way they appear in search results.

**Comment by westnz** [comment]
//published
