### ISSUE TITLE
Landing page: Consider the same font size for pathway cards as course cards

### ISSUE THREAD

**Issue by jasmussen** [WordPress/Learn#2625]
It stands out to me that the font size is different inside the 4 pathway cards at the top, and the bigger “stacked” cards below:

![Image](https://github.com/WordPress/Learn/assets/1204802/defd5298-240c-40da-be2c-eae016a28f98)

In the top card, they’re 14, in the bottom card, they’re 16. I’d tend to either go 16 across all, or change the cards to 14.

This is also a note to self/for later when the second row of pathways gets implemented, because this is off in the Figma: [Figma](https://href.li/?https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=3473-43409&t=19mV6GnRSxbQzM21-1).

**Comment by adamwoodnz** [comment]
@fcoveram thoughts?

**Comment by fcoveram** [comment]
You're right @jasmussen. I'm drawn to go with 16px. I will apply the change in the mockups.
