### ISSUE TITLE
Unify pathway card hover style with themes, plugins

### ISSUE THREAD

**Issue by jasmussen** [WordPress/Learn#2628]
It’s nice that there’s a big gray hover style on these:

![Image](https://github.com/WordPress/Learn/assets/1204802/568c21d8-c734-4288-98fb-a34411c75f8c)

However we settled on a charcoal (almost black) border color on hover, instead of a background color change, for Plugins and Themes, it would probably be best to do the same here. That also avoids the discrepancy where the pathways cards have a hover style, but the course cards do not.

**Comment by ryelle** [comment]
@jasmussen This appears to be inheriting this style from the parent theme, and the same style is used on (at least) [Forums](https://wordpress.org/support/forums/) & [Developer Resources](https://developer.wordpress.org/) landing pages. Should it be updated everywhere?

<img width="574" alt="Screenshot 2024-07-11 at 5 18 43 PM" src="https://github.com/user-attachments/assets/d738ab7b-51bf-4f6a-931d-1f185c89b47f">
<img width="697" alt="Screenshot 2024-07-11 at 5 19 54 PM" src="https://github.com/user-attachments/assets/c07ab09a-62e7-4aa0-9c75-75c75a0c1e6d">

**Comment by jasmussen** [comment]
Excellent catch. I'm conflicted, the gray hover style is quite nice in most of those place. Perhaps we leave this as is. @WordPress/meta-design

**Comment by fcoveram** [comment]
The hover style of cards and other similar elements placed in grids is a big topic. I aim for consistency as well, but in this case, I would keep it as is and address the issue once we're done with the style updates of the site.

**Comment by adamwoodnz** [comment]
Closing, as it seems there is general agreement that consistency with other sites in the 'Learn' category is most important here, and therefore we should leave this as is for now. We can address later site wide if necessary.
