### ISSUE TITLE
Breadcrumbs: double dot

### ISSUE THREAD

**Issue by jasmussen** [WordPress/Learn#2629]
There’s a double dot on [this page](https://href.li/?https://learn.wordpress.org/course/beginner-wordpress-developer/):

![Image](https://github.com/WordPress/Learn/assets/1204802/9d2e878d-0c9b-4223-b7de-e5dc809ba37a)

**Comment by adamwoodnz** [comment]
Fixed by https://github.com/WordPress/Learn/issues/2511
