### ISSUE TITLE
Update "Join a Group Discussion" button

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#263]
The single workshop page includes a button labelled "Join a Group Discussion". This needs to be updated in the following ways:

1. The button label must be changed to "Join a Social Learning Space"
2. The link must be updated to https://learn.wordpress.org/social-learning/

**Comment by Sukhija-Aniket** [comment]
Can I work on this issue?

**Comment by hlashbrooke** [comment]
@Sukhija-Aniket Yes - you can work on any issue in the repo :)
