### ISSUE TITLE
Improve "no pathways found" message

### ISSUE THREAD

**Issue by jasmussen** [WordPress/Learn#2633]
We could use a better message or design treatment for “No [pathways] found.”:

![Image](https://github.com/WordPress/Learn/assets/1204802/b2a6f9d7-43a5-4fb1-9cba-d5e850e0df14)

Maybe just a border:

![Image](https://github.com/WordPress/Learn/assets/1204802/1293f399-58a3-48b9-9162-dc2edcea0b42)

**Comment by kathrynwp** [comment]
Looping in @thetinyl for any wording suggestions as well.

**Comment by thetinyl** [comment]
Hmmm. @adamwoodnz Is there any way to hide pathway levels that don't have any content available? So if only the Beginner level is there, then Inter and Adv sections don't show up at all (thus negating the need to have this kind messaging). 

If we need an empty state, I think there's an opportunity here for guidance. Someone looking in those sections is looking for more to learn, after all. We also want to hint at a future where there _will_ be content there. 

My suggestion (which is also generic and can be applied across the board):

> There’s nothing here yet. Check again soon or [find another course](https://learn.wordpress.org/courses/).

**Comment by adamwoodnz** [comment]
> Hmmm. @adamwoodnz Is there any way to hide pathway levels that don't have any content available? So if only the Beginner level is there, then Inter and Adv sections don't show up at all (thus negating the need to have this kind messaging).

I knew this would come up, and I tried a custom block based approach initially to make this easier, but ran into problems and settled on simple query loop blocks. It should be possible but given the effort involved and volume of other launch issues, I'd prefer to update the empty state for now. I will use your suggestion.

**Comment by thetinyl** [comment]
> It should be possible but given the effort involved and volume of other launch issues, I'd prefer to update the empty state for now.

Totally fair. I had a feeling you might've already thought through this. Thanks @adamwoodnz.

**Comment by adamwoodnz** [comment]
Opened a [post launch issue](https://github.com/WordPress/Learn/issues/2655) for not including a section if empty.

**Comment by adamwoodnz** [comment]
~How does this look, do you think the border is necessary with the longer message @jasmussen ?~ Please comment on [PR](https://github.com/WordPress/Learn/pull/2656)
