### ISSUE TITLE
Improve online workshop next/prev buttons

### ISSUE THREAD

**Issue by jasmussen** [WordPress/Learn#2634]
These are the next prev buttons:

![Image](https://github.com/WordPress/Learn/assets/1204802/8e2c84c8-8d1c-4e63-a109-aaade0011091)

They could be closer to the mockups:

![Image](https://github.com/WordPress/Learn/assets/1204802/88400c12-94a7-4f6e-b429-5a2eb16d826f)

In case it helps, there’s a style implemented for theme style variations. E.g. try [TT4](https://href.li/?https://wordpress.org/themes/twentytwentyfour/):

![Image](https://github.com/WordPress/Learn/assets/1204802/b79ab5a4-b650-4bba-9793-b1a4378ab9fb)

**Comment by adamwoodnz** [comment]
Fixed when the Meeting Calendar plugin UI was updated.
