### ISSUE TITLE
Workshops: Improve "Filter by team" dropdown

### ISSUE THREAD

**Issue by jasmussen** [WordPress/Learn#2635]
Can you change “filter by team” to be a dropdown similar to the course filters?

![Image](https://github.com/WordPress/Learn/assets/1204802/fe0d3c64-8e98-4cd1-9fef-3f6e503cdfd5)

I.e. something like this

![Image](https://github.com/WordPress/Learn/assets/1204802/8534e727-5873-471b-b6d8-6f0562a47e90)

You could place that on the right, left of these:

![Image](https://github.com/WordPress/Learn/assets/1204802/68aee588-3400-4399-8fb1-ca1b4c763772)

**Comment by adamwoodnz** [comment]
The team data has been removed, and the field isn't intended to be used, so this is no longer displayed. See https://github.com/WordPress/Learn/issues/2674

In future we may hide the field in the admin so it can't reappear.
