### ISSUE TITLE
Menu does not show on pages

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#264]
The top menu shows on archive pages and single pages for various post types.

Example of Workshops archive showing menu: https://learn.wordpress.org/workshops/
Example of page showing no menu: https://learn.wordpress.org/social-learning/

It looks like the template for pages is generally quite different to other post type templates, so this would be a larger fix to get that aligned, but the menu is a critical element that needs to display.

**Comment by nguyenhung15913** [comment]
Can I work on this issue ?

**Comment by hlashbrooke** [comment]
@nguyenhung15913 yes - please do! You don't need to worry about getting the templates to match at this stage - we're just focusing on getting the same menu in there.

**Comment by nguyenhung15913** [comment]
@hlashbrooke I installed packages by yarn successfully but when I run <code>yarn run create</code>. It gave me an error below. I have still been finding the solution for it. If you know it, please show me how to fix, thanks
![image](https://user-images.githubusercontent.com/69558780/139190736-c3064c2e-2d68-4a7a-a028-9c41f8c7995d.png)

**Comment by hlashbrooke** [comment]
It looks like you don't have SVN installed, or at least it hasn't been added to your PATH. I can't help you debug here as I'm not familiar with the dev side of things there. It looks like a generic enough error that it isn't unique to this repo though.

**Comment by nguyenhung15913** [comment]
Got it! I'll try

**Comment by hlashbrooke** [comment]
Related: #245
