### ISSUE TITLE
Bengali translation for "How to Create Low-Code Block Patterns"

### ISSUE THREAD

**Issue by noruzzamans** [WordPress/Learn#2640]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/how-to-create-low-code-block-patterns/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: devmuhib009
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by noruzzamans** [comment]
Hello, Translation reviewer. I have translated this document. [Please check it](https://docs.google.com/document/d/1JuW39WsYyvZ42hKyau1mhrpoL7TfoHWgXwBx-vTVwOg/edit?usp=sharing), Thanks

**Comment by devmuhib009** [comment]
Looking good to me, please draft the post and submit subtitle. Thanks

**Comment by noruzzamans** [comment]
Hi, I have drafted the post, but I did not get any TTML option to download the subtitle. Could you please tell me how to get this file? Thanks.
https://wordpress.tv/2022/01/24/how-to-create-low-code-block-patterns/

**Comment by devmuhib009** [comment]
I'll check. Thanks

**Comment by devmuhib009** [comment]
Translation published: https://learn.wordpress.org/tutorial/bn-how-to-create-low-code-block-patterns/

Thanks for your hard work.
//published

**Comment by noruzzamans** [comment]
Thnaks
