### ISSUE TITLE
Bengali translation for "WordPress editor modes for streamlining content creation"

### ISSUE THREAD

**Issue by noruzzamans** [WordPress/Learn#2641]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/wordpress-editor-modes-for-streamlining-content-creation/
- Link to original content's GitHub issue (optional): 
- Language you'll be translating to: Bengali
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: devmuhib009
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by noruzzamans** [comment]
Hello, Translation reviewer. I have translated this document. [Please check it.](https://docs.google.com/document/d/1NVcHTsW9Y7R2KTkhqHHnjWQTwCQIyvd-d8lNGBUXgd8/edit?usp=sharing) Thanks

**Comment by devmuhib009** [comment]
Hi, thanks for the translation. Seems good to me. Please draft the post and submit subtitle on WPTV. Thanks

**Comment by noruzzamans** [comment]
Hello, Translation Reviewer, 
I have posted a draft and submitted a subtitle on WPTV. My WP username is noruzzaman. Please review and approve my content. Thanks.

**Comment by devmuhib009** [comment]
Thanks for the translation. Published here: https://learn.wordpress.org/tutorial/bn-wordpress-editor-modes-for-streamlining-content-creation/

//published
