### ISSUE TITLE
Some freestanding lesson doesn't show the correct breadcrumbs

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/Learn#2644]
https://github.com/WordPress/Learn/pull/2598#issuecomment-2209652378

The issue in the example above has been fixed by saving the post again. The probable cause of the problem was that a lesson originally belonging to a course had its course deleted, but the related data in the lesson was not properly cleaned up.

**Comment by adamwoodnz** [comment]
Fixed by #2741
