### ISSUE TITLE
Code formatting on HTML and CSS code

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2646]
When adding code snippets using the Code block and setting the language setting to either HTML or CSS, even if they are correctly formatted in the code block, they appear in one line on the front end.

Example lesson: https://learn.wordpress.org/lesson/css/

This happens in both the current theme and the new theme.

![learn wordpress org_lesson_css_](https://github.com/WordPress/Learn/assets/180629/0918843f-16bf-47bc-852a-39b90a4edc84)

**Comment by jonathanbossenger** [comment]
@StevenDufresne would you have a moment to check on what could cause this?

I'm guessing it's something that needs to be fixed upstream on the WordPress.org codebase, but not sure where to start looking

**Comment by StevenDufresne** [comment]
It has something to do with how you pasted it. I moved it over to my code editor, copied and repasted and everything seems to be working as it should.

**Comment by StevenDufresne** [comment]
Since there's a simple fix, I've closed this ticket but if it's related to an automated process or something similar, I can investigate further. Does that work?

**Comment by jonathanbossenger** [comment]
Ooo interesting, thanks @StevenDufresne I didn't even think of that.

I paste from Markdown into the Block editor, so it might be something related to how my Markdown is configured. 

I'll watch for this in the future to figure out if I'm doing it wrong.
