### ISSUE TITLE
Feedback - Sticky header position incorrect on iOS safari

### ISSUE THREAD

**Issue by rjfrizz** [WordPress/Learn#2663]
## Type of feedback
//dev

## Description
For the new Learn WordPress site. Breadcrumb header on mobile for individual lesson page (ex https://learn.wordpress.org/lesson/website-optimization/) is sticky at an incorrect position (below top of page)

## Step-by-step reproduction instructions (optional)
1. Visit https://learn.wordpress.org/lesson/website-optimization/ on the new Learn WordPress site
2. Scroll down the page

## Other information (optional)

https://github.com/WordPress/Learn/assets/6667837/dc11eaad-d63b-4902-8651-f95a45421d1f

iOS version 17.5.1
Safari for iOS 17.5

**Comment by adamwoodnz** [comment]
@renintw note that I'm making significant changes to the single lesson template in https://github.com/WordPress/Learn/pull/2741 so we will likely have conflicts.

**Comment by outdoor2kode** [comment]
Thanks for the heads-up. While reviewing #2741 yesterday, I noticed this, so I decided to work on #2687 first. My new PR for this ticket will rebase #2741 if needed. Thanks!
