### ISSUE TITLE
New Theme - Online-Workshop links in list view not working.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2673]
## Description
When I click the list view for online-workshops, I get a location and View Recording link. Both appear to not be linking to anything.

## Step-by-step reproduction instructions (optional)
Please list the steps needed to reproduce or verify the feedback. For example:
1. Go to https://learn.wordpress.org/online-workshops/
2. Click the icon beside the calendar icon
3. Notice the "View Recording" link goes nowhere and so does the "Location" link.

## Screenshots or screen recording (optional)
<img width="1246" alt="Screenshot 2024-07-15 at 9 45 42 AM" src="https://github.com/user-attachments/assets/5ecde030-6920-4e07-bce0-3b1a36376fd0">

**Comment by adamwoodnz** [comment]
Will be fixed when https://github.com/WordPress/Learn/issues/2604 is resolved
