### ISSUE TITLE
New Theme - Remove "all" or "any" from "Level" dropdown.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#2676]
## Description
When I click through on a level from a card, I get to this page: https://learn.wordpress.org/?wporg_lesson_level=advanced. When I open the level menu, I get an "all" and also an "any" option. I don't know how these differ. 

I don't see that behavior on https://learn.wordpress.org/lessons/?post_type=lesson&wporg_lesson_level=advanced.

## Step-by-step reproduction instructions (optional)
Please list the steps needed to reproduce or verify the feedback. For example:
1. Go to https://learn.wordpress.org/?wporg_lesson_level=beginner
2. Open the "Level" menu

## Screenshots or screen recording (optional)
<img width="1215" alt="Screenshot 2024-07-15 at 10 16 48 AM" src="https://github.com/user-attachments/assets/40eee532-c484-4da3-a457-ed0f11f7d318">

**Comment by adamwoodnz** [comment]
'Any' is an existing level, while 'All' is added to allow clearing the filter, the same as other WordPress.org sites, eg. Pattern Directory:

![Image](https://github.com/user-attachments/assets/011db4d3-c0da-49a2-8614-7907b187e8e3)

I agree there needs to be some clean up to remove the 'Any' value.

**Comment by adamwoodnz** [comment]
@kathrynwp is this something you could help with? Not sure whether it should be done at launch to avoid modifying the existing site, or whether we can start now.

**Comment by kathrynwp** [comment]
Hi @adamwoodnz @StevenDufresne - Ah, I see how this is a bit confusing.

The "Any" value actually _does_ have a specific meaning. It's been used for courses which don't require specific WordPress knowledge, which mostly applies to Community team-related courses. So it seems like it's still needed?

So the way I understand the meanings are:

Any - "Course is suitable to learners with any WordPress level"

All - "View all courses"

Perhaps we could just change "All to "All courses" and "Any" to "Any level" – what do you think?

**Comment by adamwoodnz** [comment]
> Perhaps we could just change "All to "All courses" and "Any" to "Any level" – what do you think?

There are cases where the content type is mixed (for example in Steve's screenshot above), so I think just 'All' is better for consistency.

I understand the meaning, but for me if a Course doesn't have a level set then it is somewhat implied that it is for 'Any', and it will show up when 'All' is selected. I wonder how useful the 'Any' term is in practice. The fact that we would consider naming it 'Any level' within a control named 'Level' I think reflects that it is a confusing concept.

**Comment by westnz** [comment]
Hey folks
If I understand correctly, you will still see the courses suitable to learners with any WordPress level when you select 'All.' Having two terms is also a bit confusing to me. I would, therefore, also suggest just having 'All' and removing 'Any.'

**Comment by kathrynwp** [comment]
**Courses** - I manually unassigned the "Any" level from the handful of Community courses that had it assigned. 

**Lessons** - I don't see any lessons assigned to "Any."

<img width="1196" alt="Advanced___Learn_WordPress" src="https://github.com/user-attachments/assets/c16de490-f349-4ac4-9c48-de930c9e8545">

Looks like the 16 pieces of content that are still assigned to the "Any" level are all **Lesson Plans**. Since that content type is deprecated, I propose that we just go ahead and delete the "Any" level from the back end here, unless there's a reason not to:

https://learn.wordpress.org/wp-admin/edit-tags.php?taxonomy=level&post_type=lesson-plan

EDIT: I just noticed that if you remove the "Any" level from a lesson plan, as I did on one sample lesson plan it leaves a blank space on the single lesson plan, since these were designed to include a level:

<img width="1299" alt="What_is_W3_Total_Cache___Learn_WordPress" src="https://github.com/user-attachments/assets/ca8bb94b-7c3d-472d-8c45-d70a3aa77662">

Taken at: https://learn.wordpress.org/lesson-plan/what-is-w3-total-cache/

**Comment by adamwoodnz** [comment]
> Looks like the 16 pieces of content that are still assigned to the "Any" level are all **Lesson Plans**. Since that content type is deprecated, I propose that we just go ahead and delete the "Any" level from the back end here, unless there's a reason not to:
> 
> https://learn.wordpress.org/wp-admin/edit-tags.php?taxonomy=level&post_type=lesson-plan
> 
> EDIT: I just noticed that if you remove the "Any" level from a lesson plan, as I did on one sample lesson plan it leaves a blank space on the single lesson plan, since these were designed to include a level:

Yeah I agree, and I don't think the empty space is big deal, but we could conditonally render these fields.

**Comment by kathrynwp** [comment]
@adamwoodnz Just let me know if you think I should go ahead and delete the "Any" level, in this case! And I could also open a new issue for the conditional logic.

**Comment by adamwoodnz** [comment]
> [@adamwoodnz](https://github.com/adamwoodnz) Just let me know if you think I should go ahead and delete the "Any" level, in this case! And I could also open a new issue for the conditional logic.

Yes please for both!

**Comment by kathrynwp** [comment]
The "Any" experience level is now gone. 

I created an issue to make it conditional in #2737 – I set it for the post-launch milestone, since Lesson plans are not linked in the new navigation.

Closing, but feel free to reopen if anyone spots something else related!
