### ISSUE TITLE
Meeting Agenda July 18, 2024

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#2680]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- July 18 – [@Noruzzaman](https://wordpress.slack.com/team/U04A11X1J2H)
- July 25 – [@Jagir Bahesh](https://wordpress.slack.com/team/UVDSVS9PD)
- August 1 – @nazmul111 
- August 8 – needs volunteer

**2. Looking for feedback**

- Online Workshop Meetup.com survey – hosts, please share this survey
- item 2

**3. Looking for volunteers**

- [Brainstorm & Table Lead – WordCamp US 2024 Contributor Day](https://make.wordpress.org/training/2024/07/16/brainstorm-table-lead-wordcamp-us-2024-contributor-day/) - we are looking for table lead volunteers and ideas for WordCamp US Contributor Day-- please share your thoughts!
- [Project Thread: Content Maintenance Process Update Phase 1](https://make.wordpress.org/training/2024/06/28/project-thread-content-maintenance-process-update-phase-1/)

**4. Updates from last week's dev-squad triage session**

- item 1
- item 2

**5. Other news**

- [Gutenberg Times](https://gutenbergtimes.com/new-courses-on-learn-my-menu-theme-section-styles-playground-step-library-weekend-edition-299/) mentioned Learning Pathways
- WordCamp Canada was last week-- do attendees have any highlights to share?

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have # issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have # issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have # issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have # issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Faculty Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have # issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: 
- Props: 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - details
- [Project Thread: Content Maintenance Process Update Phase 1](https://make.wordpress.org/training/2024/06/28/project-thread-content-maintenance-process-update-phase-1/)
  - details

## 5. Contributor Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other Faculty or Training Team members help you in some way?

## 6. Open Discussions

- Continue conversation about Learn’s north star
- Are the meeting notes in its current form beneficial?

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kathrynwp** [comment]
### Learn WP launch 

Latest project update: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4313

### Testing the new site

We need more help [testing the new site](https://make.wordpress.org/training/2024/07/09/lets-start-testing-learn-wordpress-org/)! Interesting in helping? I’ll run a Contributor Hour tomorrow on Thursday, July 18 at 16 UTC to facilitate some testing in real time. Join me! [See time converted to your time zone](https://time.is/1600_18_July_2024_in_UTC). The Zoom link will be shared in the [#training](https://wordpress.slack.com/archives/C02RW657Q) channel in Slack 5 minutes before the call.

**Comment by kathrynwp** [comment]
Props to the three people who attended WordCamp Canada's Contributor Day and tested out the new Learn WordPress site: Ryan Frizzell, Teuila Mau, and Keith Noseworthy. Among them, they submitted five GitHub issues, and Teuila also created seven thumbnails! Thank you so much for your efforts in helping to make the new site the best it can be.

**Comment by Piyopiyo-Kitsune** [comment]
Notes: https://make.wordpress.org/training/2024/07/25/training-team-meeting-recap-18th-july-2024/
