### ISSUE TITLE
Feedback - Exit Course link on lesson leads to 404 when parent course is unpublished

### ISSUE THREAD

**Issue by cdils** [WordPress/Learn#2681]
## Type of feedback
//dev

## Description
"Exit Course" link on main Lessons pages sometimes works and sometimes 404s. I didn't click through all links, but it looks like "Exit Course" lessons for the Beginner WordPress Developer work and "Exit Course" lessons for Advanced WordPress Developer do not.

Examples where the Exit Course link doesn't work:

- https://learn.wordpress.org/lesson/adding-custom-user-roles-using-a-wordpress-plugin/
- https://learn.wordpress.org/lesson/using-caching-to-improve-website-performance-w3-total-cache-plugin/
- https://learn.wordpress.org/lesson/wordpress-taxonomies-2/
- https://learn.wordpress.org/lesson/creating-custom-post-types-and-taxonomies/

Examples where it does:
- https://learn.wordpress.org/lesson/website-optimization/
- https://learn.wordpress.org/lesson/wordpress-hooks/
- https://learn.wordpress.org/lesson/time-to-test-your-skills/

## Step-by-step reproduction instructions (optional)
1. From learn.wordpress.org, click on [Lessons](https://learn.wordpress.org/lessons/) in the Learn navigation (logged in state doesn't matter)
2. Click on the [Adding custom user roles using a WordPress plugin](https://learn.wordpress.org/lesson/adding-custom-user-roles-using-a-wordpress-plugin/
) lesson
3. From top right screen (at least that's the position on desktop), click the [Exit Course](https://learn.wordpress.org/?post_type=course&p=257841) Link
4. You're redirected to a "Sorry, we couldn't find this page" page. Note redirect URL structure: https://learn.wordpress.org/?post_type=course&p=257841

## Screenshots or screen recording (optional)
<img width="500" alt="Screenshot 2024-07-16 at 8 14 17 AM" src="https://github.com/user-attachments/assets/f61c2f3d-ea01-44a4-8774-e8338c5e196a">

## Other information (optional)
Testing on latest MacOS + Chrome

**Comment by adamwoodnz** [comment]
Thanks for raising this!

This is due to the fact that the Advanced course isn't published yet, but the contained lessons are. @jonathanbossenger @westnz this follows on from [our previous discussion about the publishing workflow](https://github.com/WordPress/Learn/issues/2599) - do we need to publish these before the parent course?

**Comment by westnz** [comment]
Hey @adamwoodnz, We definitely want to publish a lesson as soon as it is ready to be used and viewed by learners, even if the learning pathway will only be published at a later stage.

**Comment by adamwoodnz** [comment]
> Hey @adamwoodnz, We definitely want to publish a lesson as soon as it is ready to be used and viewed by learners, even if the learning pathway will only be published at a later stage.

Could you publish it as a standalone lesson until the course is published?

We could write logic to check if the parent is published, but I think the exit course button is really behaving that way it is intended to while the lesson belongs to a course. The breadcrumb also shows the parent course.

![Screenshot 2024-07-17 at 10 23 52 AM](https://github.com/user-attachments/assets/866dfcce-0135-4871-a15a-88e1bd9710b5)

**Comment by westnz** [comment]
I will wait for Jonathan to chime in here.

**Comment by jonathanbossenger** [comment]
I feel like we need to examine the reason why we want to publish lessons during development in the first place.

My memory of these things is not 100%, but what I remember is that we wanted to have a way for translators to be able to translate lesson content while a course/learning pathway is in development.

So initially, we published lessons as soon as they were ready.

However, we then discovered that there was a public preview feature that achieves that same goal. 

The public preview feature also allows learners to view the entire lesson content before the course/learning pathway is complete and published. It even allows them to view the content without taking the course. 

So, I'm wondering if publishing lessons that are part of a course in development is still strictly necessary if the public preview feature achieves the same goal, both for learners who want to view the content, and for translators.

**Comment by adamwoodnz** [comment]
Using public preview sounds good to me, ok with you @westnz?

**Comment by westnz** [comment]
> So, I'm wondering if publishing lessons that are part of a course in development is still strictly necessary if the public preview feature achieves the same goal, both for learners who want to view the content, and for translators.

I have tested putting one of the lessons to draft and selecting 'Enable public preview.' Unfortunately, it doesn't appear below lessons on the new website. This means most folks won't be able to access or find it. I believe it is important for a finished lesson to be available to learners below lessons as soon as it is completed. The content is fresh and offers immediate value to learners.

I am, therefore, unsure if public preview is the best way forward. 😃

**Comment by jonathanbossenger** [comment]
Shoot, that is a pity. 

@adamwoodnz the downside of creating each lesson as a stand-alone lesson first and then adding it to the course later is that it creates quite a bit of overhead to then create the course and modules and assign the right lessons to modules. 

Sensei doesn't allow us to create stand-alone lessons and assign them to modules without a course already being created to assign the modules to.

![Edit-Lesson-“New-Lesson-1”-‹-learn-wordpress-org-—-WordPress](https://github.com/user-attachments/assets/2a27b027-fd75-4a6c-bb9f-ac3c44b9f632)

It also can't easily be done in the Sensei Course edit screen. You can assign existing lessons, but not existing modules. And, you can't assign existing lessons inside a newly created module.

So, it would mean creating the empty course, then navigating to Modules and creating the modules in the course, and then navigating to Lessons, searching for the relevant lessons, and assigning them to the modules. 

At the moment, creating the course, the modules, and the lessons inside the Course edit screen is a much more straightforward workflow.

**Comment by cdils** [comment]
Just a thought, but as a simple way to solve the Exit Course link issue and not interfere with current publishing workflow, could that link/text be set to conditionally show based on whether a parent course is set to `publish`?

**Comment by adamwoodnz** [comment]
> Just a thought, but as a simple way to solve the Exit Course link issue and not interfere with current publishing workflow, could that link/text be set to conditionally show based on whether a parent course is set to `publish`?

Yes it seems like we might need a code based solution here then.

There are several parts of the UI which will need to change; the sidebar, breadcrumbs and exit course link all need to be hidden or modified, essentially rendering the Lesson as if it is standalone.

**Comment by jonathanbossenger** [comment]
@adamwoodnz I was thinking about this over the weekend.

How much work would it be to make this happen, compared to making it possible to create stand-alone lessons in Sensei but add them to modules without adding them to a course?

From a data POV, modules are just a custom taxonomy, so I'm assuming there's some Sensei-related code that adds this restriction. If we could remove/disable it, we might be able to publish stand-alone lessons grouped by specific modules, and then, once all the lessons are created, create the course and assign the modules to the new course.

**Comment by adamwoodnz** [comment]
> How much work would it be to make this happen, compared to making it possible to create stand-alone lessons in Sensei but add them to modules without adding them to a course?

Good question. I imagine checking whether there is a published parent course is likely easier, because we can do it in our pattern code, however I think your suggestion sounds like it might be cleaner. I'll investigate, thanks.

**Comment by jonathanbossenger** [comment]
If we are able to do this, and it's simple enough, would you be able to start a draft PR to test? I'd like to test the theory that if we can remove that restriction, we can build and publish courses from the lesson up, instead of from the course down, and how easier/more difficult it might be compared to what we do now.

**Comment by adamwoodnz** [comment]
> If we are able to do this, and it's simple enough, would you be able to start a draft PR to test?

It's not simple, but I've got a [draft](https://github.com/WordPress/Learn/pull/2740) ready. Hopefully I've understood correctly.

All that remains is being able to insert a pre-existing module into a course, and that looks trickier, as it probably involves deregistering the Sensei course outline inserter block and registering a custom one.

**Comment by adamwoodnz** [comment]
I've also raised an [alternative PR](https://github.com/WordPress/Learn/pull/2741) which follows the other approach; not rendering any of the course UI on the single lesson template if the course is unpublished. Essentially treating it exactly the same as a standalone lesson. This is much simpler and gets my vote.

**Comment by jonathanbossenger** [comment]
@adamwoodnz I'm also a fan of the simpler solution, whatever that turns out to be. In that case, the alternative PR gets my vote. I just assumed (incorrectly) that the original way was simpler, based on what I thought would be required to treat the lesson as standalone. It also means content creators don't have to change their workflows.

Thank you for exploring this with me though.

**Comment by adamwoodnz** [comment]
> @adamwoodnz I'm also a fan of the simpler solution, whatever that turns out to be. In that case, the alternative PR gets my vote. I just assumed (incorrectly) that the original way was simpler, based on what I thought would be required to treat the lesson as standalone. It also means content creators don't have to change their workflows.
> 
> Thank you for exploring this with me though.

You're welcome! It was an interesting deep dive into the Sensei plugin.
