### ISSUE TITLE
Bug: Some lessons don't display automatic excerpts

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2682]
## Type of feedback

//dev

## Description

Some lessons are missing an automatic excerpt.

## Step-by-step reproduction instructions 
1. View Lessons archives: https://learn.wordpress.org/lessons/
2. Go through pagination
3. Note that some lessons have a blank excerpt area

## Screenshots or screen recording

<img width="1233" alt="Lessons___Learn_WordPress" src="https://github.com/user-attachments/assets/74e7dc9b-c189-4910-bbfe-774b8b9d5570">

## Expected

When there's no custom/manual excerpt on a lesson, an automatic excerpt should be displayed, pulling through the first 16 words from the lesson.

**Comment by adamwoodnz** [comment]
Reproducible at https://learn.wordpress.org/?s=wrap+up&post_type=lesson

![Image](https://github.com/user-attachments/assets/d03b182e-bfea-46c0-8d76-a5e5ff26f1ae)

**Comment by outdoor2kode** [comment]
Is this still an issue? I went through about 20 pages of lessons and only found three lessons without excerpts. These three lessons indeed do not have any excerpts added. 
Is it expected that even if an excerpt is not added, there should still be an excerpt? 

I did notice that for some lessons without excerpts, the excerpt was automatically generated from the first few lines of the post. I compared the lessons without excerpts with those that had automatically generated excerpts and found that the lessons without excerpts had slightly different formatting—for example, an h2 that was incorrectly set as an h3, or some extra blank paragraphs were added. I tried adjusting the formatting to be consistent, but the excerpt still did not appear.

If automatic excerpt generation is expected, I will continue looking into this direction.

**Comment by adamwoodnz** [comment]
> Is it expected that even if an excerpt is not added, there should still be an excerpt?

Correct, there should be an automatic excerpt if a custom one has not been added.

**Comment by kathrynwp** [comment]
The first lesson currently on the Lessons pagbe is a good example of a lesson where a 16-word automatic excerpt is not being pulled as expected, as it is on other lessons:

https://learn.wordpress.org/lessons/

<img width="1261" alt="Lessons___Learn_WordPress" src="https://github.com/user-attachments/assets/22901e3a-0630-46bf-a52a-00059c535d5b">

Ideally it should be pulled from the first words in the Transcript section, skipping any resources links at the top:

<img width="1240" alt="What_is_WordPress_Multisite____Learn_WordPress" src="https://github.com/user-attachments/assets/b2fade82-828c-40fd-9e14-e51fe6e86a5f">

**Comment by outdoor2kode** [comment]
Issues summarized:

**1. What is WordPress Multisite?**

| Card | 
|-|
| ![image](https://github.com/user-attachments/assets/f449d60f-a896-4515-8af9-b1efc0cc193e) |

**2. When viewing "Why would a WordPress user need to run a local site" on the search page, the excerpt disappears.**

| Card | 
|-|
| ![image](https://github.com/user-attachments/assets/9aa48496-fda4-42d5-820b-59e2798839cb) |

**3. When "What is WordPress Multisite?" isn't the first item in the search results, the excerpt appears** 
| Card | 
|-|
| ![image](https://github.com/user-attachments/assets/f6cef1cc-66c1-40d6-9bbe-fe5b76f68a92) |

**4. Same for the featured lessons on the front page**

| Card |
|-|
| ![image](https://github.com/user-attachments/assets/b0c0f4e7-f091-483e-9c8b-21a4d50aa5bf) |
