### ISSUE TITLE
Feedback - Dashboard Icons Lesson Quiz: Different Layout and Non-interactive

### ISSUE THREAD

**Issue by kspilarski** [WordPress/Learn#2684]
## Type of feedback
//content

## Description

In the Dashboard Icons lesson https://learn.wordpress.org/lesson-plan/dashboard-icons/  the quiz is not interactive already displays the answers, which isn't the case for the other quizzes in Learn. 

For consistency, we can have the same layout for all quizzes.

## Step-by-step reproduction instructions (optional)

1. Go to https://learn.wordpress.org/lesson-plan/dashboard-icons/
2. Scroll down to the bottom of the page to see the Quiz  

## Screenshots or screen recording (optional)

The Dashboard Icons quiz is not interactive and it already shows the answers: 

<img width="982" alt="Screenshot 2024-07-16 at 18 29 00" src="https://github.com/user-attachments/assets/e71ae4a0-e56d-4e16-8c4b-223bd1944b3a">

I'm not sure if it's because of the length of the quiz, but the quizzes in other lessons are more interactive and has this layout, for example: 

<img width="1056" alt="Screenshot 2024-07-16 at 18 32 07" src="https://github.com/user-attachments/assets/01fafc4d-96a4-4921-973a-4aaf79789d65">

## Other information (optional)
Chrome 124, macOS 14.5

**Comment by kathrynwp** [comment]
I can understand why this looks wrong! Lesson plans are intended for instructors teaching courses in their own classrooms, not for students taking a course online, so I think that's why the course isn't interactive. (Lesson plans are also being deprecated in their current form.) Flagging for input from @westnz or @jonathanbossenger to see if this is expected behaviour.

**Comment by westnz** [comment]
That's correct, @kathrynwp. The answers were added for facilitators who might use the lesson plan and quiz questions. As you also highlighted, lesson plans are also being deprecated in their current form. Sorry for the confusion @kspilarski.

**Comment by kspilarski** [comment]
> ! Lesson plans are intended for instructors teaching courses in their own classrooms, not for students taking a course online

I see! I didn't know the context behind it, thanks for sharing that! 

>  Sorry for the confusion

No worries at all! I was just flagging what I thought looks like a different quiz layout than the other quizzes I took. 
Thank you both for checking!
