### ISSUE TITLE
Feedback - Incorrect Slug in Migrating your site Part 1 lesson

### ISSUE THREAD

**Issue by kspilarski** [WordPress/Learn#2685]
## Type of feedback
//content

## Description
The lesson **Migrating your site Part 1** link is https://learn.wordpress.org/lesson/xxx/ where the slug is `xxx` instead of `migrating-your-site-part-1....` 

While the part 2 lesson **Migrating your site Part 2**  is correct: `https://learn.wordpress.org/lesson/migrating-your-site-part-2-changing-your-host-but-keeping-your-domain/`

## Step-by-step reproduction instructions (optional)
1. go to Intermediate WordPress Course https://learn.wordpress.org/course/intermediate-wordpress-user/ and go to the final course: Site Migration and select "Migrating your site Part 1" 
2. Notice that the slug is xxx in the link  https://learn.wordpress.org/lesson/xxx/ 

Or go directly to https://learn.wordpress.org/lesson/xxx/

**Comment by kathrynwp** [comment]
@westnz could you please take a look at the slug here? Thanks!

**Comment by westnz** [comment]
That's odd. Thank you for flagging this Kel.

**Comment by westnz** [comment]
Fixed 😃

**Comment by kspilarski** [comment]
You're welcome, thanks for the quick fix!
