### ISSUE TITLE
Feedback - Final Lesson has 'Continue to next lesson' Button that Doesn't Open 

### ISSUE THREAD

**Issue by kspilarski** [WordPress/Learn#2687]
## Type of feedback
//content

## Description
After completing the quiz of the last lesson Mentoring WordCamps 
 https://learn.wordpress.org/quiz/how-to-be-a-wordcamp-mentor-3/ it displays a 'Continue to next lesson' button which is clickable but doesn't open anywhere.  

This is the same case for  the last lesson Meeting Structure: Running, Closing and Follow-up 
https://learn.wordpress.org/quiz/meeting-structure-running-closing-and-follow-up-3/ 

## Step-by-step reproduction instructions (optional)
1. Go to https://learn.wordpress.org/quiz/how-to-be-a-wordcamp-mentor-3/
2. Complete the quiz. 
3. Click 'Continue to next lesson' button. 

## Screenshots or screen recording (optional)
![Screen Capture on 2024-07-16 at 19-19-17](https://github.com/user-attachments/assets/a57b4ed2-b943-40e0-9fae-e3e81dba2637)

## Other information (optional)
Chrome 124, macOS 14.5

**Comment by outdoor2kode** [comment]
This is the original behavior of Sensei and is not related to the new theme. I have opened a PR to see if the Sensei team will accept the proposal.

**Comment by outdoor2kode** [comment]
The [proposed PR](https://github.com/Automattic/sensei/pull/7642) has been accepted and scheduled for the next version 4.24.2 release. At that time, the button here will change to a "Back to lesson" button.
