### ISSUE TITLE
Lesson: Exploring WordPress 6.6

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2688]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
- Content title: Exploring WordPress 6.6
- Topic description: New features that have landed with 6.6
- Audience (User, Developer, Designer, Contributor, etc.): User
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Related Resources and Other Notes
https://wordpress.org/news/2024/07/dorsey/

### Automation Code

//lesson

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/9dfaeda7-bfbf-4d29-9601-35b33254407a

**Comment by Soir7** [comment]
[+] Learning outcomes/objectives are clear.
[+] Technical concepts introduced in the content are accurate.
[+] The speed of demonstrations are easy to follow.
[+] The narration audio matches what is shown visually.
[+] Spelling and grammar are correct.
[+] Sound quality is consistent throughout the video.
[+] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
[ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)). **N/A**

Another winner, @westnz. 

General comments:

1. Nice how you demonstrated with side by side screens, showing how updates on pattern propagated to respective blocks (?)
2. Your enthusiasm is infectious.  :+)

Comments for section **Synced pattern overrides**:

1. You could preface explanation of syncing by saying **'Syncing enables you to (or syncing means)** create a pattern centrally....'. Another words, more specifically letting people know this is the definition of syncing.
2. Stating overrides apply only to following: Heading, Paragraph, Button, and Image blocks.*


*Source:  https://learn.wordpress.org/tutorial/creating-your-own-custom-synced-or-non-synced-patterns/

Thank you. 

Eileen

**Comment by westnz** [comment]
Thank you very much @Soir7. Appreciate it.
The topic of synced pattern overrides is tricky. 😉

**Comment by Soir7** [comment]
You are welcome, @westnz. Yes, synced pattern overrides topic is tricky. Your visuals helped greatly.

**Comment by kathrynwp** [comment]
Wow, you crammed a lot into a short video and I learned some things!

A few notes:

0:36 - I'm not sure about calling that icon "bulk select" as there's also a Bulk Edit link (though I'm not sure why I don't see it in your video!) – and this icon doesn't really allow you to select templates in bulk, does it? 🤔 What do you think about calling it the "View options" or "Options" icon, following what the tooltip says? 

<img width="1119" alt="Cursor_and_Editor_‹_Food_Connection_—_WordPress" src="https://github.com/user-attachments/assets/52fbe591-b29a-4b6c-9b85-bf5eb05398ca">

1:46 - I think your screen has two words flipped by accident? In your demo, it says "Grid Support Layout" - but did you mean "Grid Layout Support," as in your title slide and audio?

2:33 - where you say "tablet or mobile" - did you mean to say "tablet or mobile phone"? My first reaction was "Isn't a tablet a mobile device"? Then it occurred to me that you might mean a mobile phone... I'm not sure how common it is to use "mobile" as a noun in some variations of English, it might be more commonly used as an adjective in some places like the US and Canada - i.e. mobile phone, mobile device, etc. In any case, it felt to me like a word was missing, so I was distracted for a bit. :D 

5:22 - I would recommend not naming an element after a colour like in this example. Instead I would suggest giving it a functional name, like "Team member name." This is more future-proof, so if you change site-wide colours, for example, you won't have block names that no longer make sense (Not to mention, it looks black on my screen, not green!) Same thing for "Green image." I know these were just examples, but it would be good to model best practices at the same time, ideally!

7:53 - In the section about background images, I wonder if it's worth explaining why the background image doesn't show behind the whole page, and why you need to scroll down the footer to see it?

That's it!

**Comment by westnz** [comment]
Thank you so much for the helpful feedback @kathrynwp

**Comment by digitalchild** [comment]
Great overview. Some exciting featuers in this releaes. 

Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by westnz** [comment]
Thanks @digitalchild

**Comment by westnz** [comment]
//published
