### ISSUE TITLE
Feedback - Consider adding the Audience tag

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2690]
## Type of feedback

//dev

## Description

Adding the Audience tag to lesson cards

## Step-by-step reproduction instructions (optional)

1. Go to https://learn.wordpress.org/?new-theme=1
2. Scroll down to featured lessons
3.

<img width="1646" alt="Screenshot 2024-07-18 at 9 17 58 AM" src="https://github.com/user-attachments/assets/d82a05c3-9c18-464b-9ab5-cf7dcfe80121">

## Other information (optional)

When you look at a card, it only states the level.  Would it not be more helpful to learners to add the audience tag?  Then a user, for example, could immediately see if a lesson is meant for a developer or contributor, etc. I realize we need to ensure that the audience is set. Is there a way to bulk select this on courses? . <img width="1853" alt="Screenshot 2024-07-18 at 9 20 58 AM" src="https://github.com/user-attachments/assets/4f133d79-739c-41d3-843b-e44bfd4f98a2">

**Comment by adamwoodnz** [comment]
@WordPress/meta-design seeking your input on this please.

One thing to consider is that Audience is a multi select field, so we may need to display multiple audiences on a card.

Level is too, but it seems less likely we'd select multiple values for that.

**Comment by westnz** [comment]
Thanks Adam. In general, we don't select multiple audiences for our content.

**Comment by marko-srb** [comment]
Hey hey @adamwoodnz ! 

As I see there are limitations to what we can do here. 

1st point. I see old design (left card below) had duration of a course in the mockup. I couldn't follow decisions for its removal, but hope that removal was mutually agreed by parties involved. 

2snd point. If my assumption under 1st point is correct then we can add only competency/experience levels as tags (see right card below). Adding audience tag would mess things up (see second screenshot).

—

Based on those observations, I'd leave only experience levels for the launch, while leaving this issue open for discussing 'audience' tag after the launch...


<img width="1039" alt="Screen Shot 2024-07-25 at 23 29 48" src="https://github.com/user-attachments/assets/3a948474-a4e7-44fa-8e33-c867d1c5a412">

—

<img width="461" alt="Screen Shot 2024-07-25 at 23 32 11" src="https://github.com/user-attachments/assets/bb1527dc-edfc-4d76-8000-338ed070d817">

**Comment by kathrynwp** [comment]
Just chiming in to note that a lesson has only one level - either Beginner, Intermediate, or Advanced – not two or three at once, as in some of the mockups.

**Comment by kathrynwp** [comment]
I also want to point out that if we go with what I proposed in #2767 - namely, display the course to which a lesson belongs - that might negate the need to also display the audience. @westnz what do you think?

**Comment by westnz** [comment]
I think you are right @kathrynwp

**Comment by marko-srb** [comment]
Thanks @kathrynwp!

I guess with your comment we should have this solved. If this is not the case, I'd still suggest we leave this question for after the launch. But if you really need to add the 'audience' @adamwoodnz for some reason, I think this would be nice way to do it. 

You can ping me tomorrow if you need to go with 'audience' tag and I'll try to come up with icons for all audiences... 


<img width="556" alt="Screen Shot 2024-07-25 at 23 39 50" src="https://github.com/user-attachments/assets/4da80b3b-6c20-4b2f-a66a-1294cbdbef1d">

**Comment by kathrynwp** [comment]
I do think this can probably wait until after the launch, as we should take a bit of time to discuss what approach we think is best – displaying the audience, the course to which a lesson belongs, or some other approach to help learners scan the lesson archives and decide which lesson best suits them.

**Comment by adamwoodnz** [comment]
> 1st point. I see old design (left card below) had duration of a course in the mockup. I couldn't follow decisions for its removal, but hope that removal was mutually agreed by parties involved.

Duration is only displayed if set, but even with duration there should be enough room for an audience tag too.

I'm not sure what will work better, [seeing which course the lesson is from](https://github.com/WordPress/Learn/issues/2767) (which may or may not make the audience clear, but would differentiate between lessons with the same name), or audience (which might be the same for 2 different lessons and therefore wouldn't differentiate). I think maybe the course title might be the best bet, as it would provide more context than a tag, but we could fit both.

**Comment by kathrynwp** [comment]
@adamwoodnz My thought is that the course title – at least for the Learning Pathway courses – will always make both the level and audience clear, given our naming convention. i.e. 

Beginner WordPress User
Intermediate WordPress User
Advanced WordPress User
Intermediate Theme Developer
Beginner WordPress Developer
Intermediate Plugin Developer

It's less obvious for the older non-Learning Pathway courses.

**Comment by adamwoodnz** [comment]
> @adamwoodnz My thought is that the course title – at least for the Learning Pathway courses – will always make both the level and audience clear, given our naming convention. i.e.
> 
> ...
>
> It's less obvious for the older non-Learning Pathway courses.

Ok, shall we close this in favor of [adding the course title](https://github.com/WordPress/Learn/issues/2767) then? @fcoveram does this make sense to you?

**Comment by fcoveram** [comment]
It does @adamwoodnz. And I just shared a design in the ticket mentioned.
