### ISSUE TITLE
Course Landing page - remove the Average days to completion

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2695]
## Type of feedback

//dev
## Description

Currently, on course landing pages, and average days to completion value is displayed. However, this value could be both confusing (e.g if a content creator tests a course over a day, it's going to add 1 to that calculation) as well as daunting for new learners, and therefore doesn't have any real benefit. Suggest we simply remove it.

## Screenshots or screen recording (optional)

![learn wordpress org_course_beginner-wordpress-developer_](https://github.com/user-attachments/assets/e272f426-3097-4c3d-997c-41800b7d34e4)

**Comment by adamwoodnz** [comment]
@westnz @kathrynwp @Piyopiyo-Kitsune any other opinions on this one? Happy to remove it.

**Comment by westnz** [comment]
+1 to removing it.   It can be confusing and unhelpful to some.

**Comment by kathrynwp** [comment]
I see this has already been done, but I agree with removing it!

**Comment by adamwoodnz** [comment]
> I see this has already been done

Sorry, moving fast this week. I figured 2 votes was good enough, and it was easy to revert if there was disagreement :)

**Comment by kathrynwp** [comment]
100% - no worries! I think you made the right call.
