### ISSUE TITLE
Workshop Details block: editor script causes whitescreen when minified

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/Learn#27]
Then the script for the `workshop-details` block is built with `wp-scripts build`, the code is minified, and when it loads in the editor, you get a white screen of death. Curiously, the errors in the console relate to Jetpack, rather than our plugin. Nevertheless, if you disable our block, everything works again.

If the block script is instead built with `wp-scripts start`, the code is not minified, and no white screen of death occurs. 🤷‍♂️

**Comment by StevenDufresne** [comment]
There's an open issue with Gutenberg's `create-block`. 

Issue: 24269

**Comment by StevenDufresne** [comment]
Jetpack still seems broken:
![](https://d.pr/i/wVvwch.png)

I wonder if we should open an issue specifically for jetpack.

**Comment by StevenDufresne** [comment]
It appears to be related to Jetpack 8.8. 

I will update our package to 8.7 for now.

**Comment by coreymckrill** [comment]
The production site is running Jetpack 8.8 (as is the rest of wporg). I'd like to leave this open until we can commit minified block code to the repo without causing a WSOD (whether that's due to a Core fix or a Jetpack fix or something else)
