### ISSUE TITLE
Determining the correct hook

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2702]
# Details
 
 - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
 - Content title: Determining the correct hook
 - Topic description: How to determine which hook to use to achieve specific goals.
 - Audience (User, Developer, Designer, Contributor, etc.): Developer
 - Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate
# Prerequisites
 
 It is assumed that the learner has already completed the following lessons:

 - [Beginner WordPress developer](https://learn.wordpress.org/course/beginner-wordpress-developer/)
   - Modules 1 - 4
   - Module 5: WordPress Hooks
   - Module 6: An introduction to developing WordPress plugins
 # Learning Objectives
 
 - Describe when to use an action vs when to use a filter
 - Explain, with examples, how to use the [Action](https://developer.wordpress.org/apis/hooks/action-reference/) and [Filter](https://developer.wordpress.org/apis/hooks/filter-reference/) reference to determine the correct hook to use
 # Related Resources and Other Notes
 - https://developer.wordpress.org/apis/hooks/
 ### Automation Code
 
 //lesson

**Comment by CrochetFeve0251** [comment]
@jonathanbossenger from what I got from this issue, this section is here to teach the learner when to use a filter or an action?

**Comment by CrochetFeve0251** [comment]
Understand the purpose of an action vs a filter: (Maybe we can talk a bit about the [CQRS approach](https://martinfowler.com/bliki/CQRS.html?ref=blog.funda.nl))
- Action: Change the state without returning a value.
- Filter: See a value without changing the state

When to use an action:
- To signal an action will/has been going on to let thirdparties react or adapt to it.

When to use filter:
- Prevent magic values (Values not named in the code)
- Prevent imposing your choice to the user while offering a default solution.
- Hiding complex choice from lambda user not knowing what choice to make.

If you see other scenarios feel free to add them

**Comment by jonathanbossenger** [comment]
Hi @CrochetFeve0251, apologies if this wasn't clear. The objective of this lesson would be how to determine which hook or filter to use, in order to achieve a specific goal.

So, for example, if I want to enqueue admin-only scripts, which hook do I use? If I want to process a form submission, which hook should I use?

The general process would be:
- determine if I need an action or filter hook
- then review the relevant reference ([action](https://developer.wordpress.org/apis/hooks/action-reference/) or [filter](https://developer.wordpress.org/apis/hooks/filter-reference/)) to decide which hook should be used.

The beginner developer lessons on [Hooks](https://learn.wordpress.org/lesson/wordpress-hooks/), [Actions](https://learn.wordpress.org/lesson/action-hooks/) and [Filters](https://learn.wordpress.org/lesson/action-hooks/) does already cover the basic purpose of the two, but you certainly can expand on that based on what you've shared here already. 

Then after that, you can include the process of how to decide which one to use, when developing plugins.

**Comment by jonathanbossenger** [comment]
I see this lesson also had the wrong name for some reason, so I've updated it. It also didn't have prerequisite lessons or objectives set, so I've added those as well.

**Comment by jonathanbossenger** [comment]
@CrochetFeve0251 I'm checking in to see if you're still happy to continue with scripting the next lesson in this module?

**Comment by CrochetFeve0251** [comment]
@jonathanbossenger I started to work on it but I didn't push yet the script

**Comment by jonathanbossenger** [comment]
Thank you, no pressure from my side, just wanted to make sure the process is still enjoyable. 🙂

**Comment by MichelleBlanchette** [comment]
> So, for example, if I want to enqueue admin-only scripts, which hook do I use? If I want to process a form submission, which hook should I use?
> 
> The general process would be:
> - determine if I need an action or filter hook
> - then review the relevant reference ([action](https://developer.wordpress.org/apis/hooks/action-reference/) or [filter](https://developer.wordpress.org/apis/hooks/filter-reference/)) to decide which hook should be used.
> ...
> Then after that, you can include the process of how to decide which one to use, when developing plugins. 
> 
> 

When I think about which hook is best at an advanced level, I also consider (1) what data is made available in the hook's parameters and (2) the execution order of the hook. (eg. filtering a post's data before it is inserted into the database rather than acting on it after creation to then update it is generally more efficient)

These are the two main reasons I often cannot use a particular hook: it either doesn't provide crucial data needed for my custom functionality or it executes too early or late in the execution flow.

Additionally, a nifty trick is you can certainly use a filter hook as an action hook if it meets the necessary criteria. You simply perform your logic and then pass back the filtered value with no modifications to it.

Maybe these are also good concepts to consider for this lession.

**Comment by jonathanbossenger** [comment]
Logging that a [PR for the script has been created](https://github.com/wptrainingteam/learn-wp-content/pull/8). I will review this week.

**Comment by jonathanbossenger** [comment]
Script: https://github.com/wptrainingteam/learn-wp-content/blob/main/plugin-developer-learning-pathway/02-Advanced-Hooks/03-correct-the-hook.md

**Comment by jonathanbossenger** [comment]
Video for review: https://drive.google.com/file/d/1OtO1GN945fK2MwUwE1MtbvA6Ocn34Foq/view?usp=drive_link

**Comment by MichelleBlanchette** [comment]
> Video for review: https://drive.google.com/file/d/1OtO1GN945fK2MwUwE1MtbvA6Ocn34Foq/view?usp=drive_link

@jonathanbossenger I'm unable to access the video for review.

**Comment by jonathanbossenger** [comment]
@MichelleBlanchette apologies, this should be public now.

**Comment by MichelleBlanchette** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

I really enjoyed this lesson. The description and purpose of each mentioned hook was spot on and clearly communicated. I was particularly impressed by the explanation of the `plugins_loaded` hook and your tips for working with third-party plugins' hooks. 😁 Great work!

**Comment by jonathanbossenger** [comment]
WordPress.tv: https://wordpress.tv/2024/12/23/determining-the-correct-hook/

**Comment by jonathanbossenger** [comment]
00:00 Introduction
00:58 Finding available hooks
01:59 Important hooks to remember
03:12 Using hooks outside of WordPress Core

**Comment by jonathanbossenger** [comment]
https://youtu.be/Vy_k100F0Lw

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/determining-the-correct-hook/

**Comment by jonathanbossenger** [comment]
//publish
