### ISSUE TITLE
Nested blocks

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2704]
# Details
 
 - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
 - Content title: Nested blocks
 - Topic description: Nesting other blocks using InnerBlocks
 - Audience (User, Developer, Designer, Contributor, etc.): Developer
 - Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate
  # Prerequisites
 
 
 It is assumed that the learner has already completed the following lessons:
  - [Beginner WordPress developer](https://learn.wordpress.org/course/beginner-wordpress-developer/)
   - Modules 1 - 4
   - Module 5: WordPress Hooks
   - Module 6: An introduction to developing WordPress plugins
   - Module 7: An introduction to developing WordPress blocks
 # Learning Objectives
 
 - Explain how to use the InnerBlocks component to create nested blocks
 - Describe how to set specific blocks that can only be added to a nested block
 - Implement a block template inside a nested block
 - Set a default block when adding a nested block
 # Related Resources and Other Notes
 - https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/nested-blocks-inner-blocks/
 - https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/#innerblocks
 ### Automation Code
 
 //lesson

**Comment by jonathanbossenger** [comment]
Video for review: https://drive.google.com/file/d/1nix8e6DWAWXk8x7oZaLs4btPsYRhkRel/view?usp=sharing

[Guidelines for Reviewing Content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/).

**Comment by NewYorkerLaura** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [ ] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

Kudos on saying "inner blocks block" well and clearly. It's a tongue twister, NOT EASY!

Very clear audio, illustrative screens good and left up an appropriate time.

There is a reference at the 1:14 mark of a previous module on the block development module that should have been followed and a required previous set up. It would be helpful to have this link included in the "related references" area for easy accessibility in case the reader has inadvertently skipped this step.

Similarly at the 7:41 mark there are a variety of references to resources considering linking them as well

**Comment by RoelofWobben** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [X] Learning outcomes/objectives are clear.
- [X] Technical concepts introduced in the content are accurate.
- [X] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [X] Spelling and grammar are correct.
- [X] Sound quality is consistent throughout the video.
- [X] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [X] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

Nice voice and I like it that a example is shown.

**Comment by MichelleBlanchette** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Really great, concise tutorial that even goes on to clearly show common, powerful ways to customize InnerBlocks behavior. I always found InnerBlocks to be a daunting subject because it sounds so powerful and advanced, but this tutorial made it a breeze!

I just add one item for feedback:

03:22 - "add the _plugin_ to a post or page", should you instead say "add the _block_ to a post or page"?

**Comment by jonathanbossenger** [comment]
Thank you.

**Comment by BSICTVince** [comment]
Please tick all items you've confirmed:


- [x] Learning outcomes/objectives are clear.

- [x] Technical concepts introduced in the content are accurate.

- [x] The speed of demonstrations are easy to follow.

- [x] The narration audio matches what is shown visually.

- [x] Spelling and grammar are correct.

- [x] Sound quality is consistent throughout the video.

- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional 

- [x] Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.

This is exactly the kind of content I’ve been searching for—comprehensive, easy to understand, and highly informative, especially for those at the beginner level. It provides just the right amount of detail to make complex concepts more accessible.

**Comment by jonathanbossenger** [comment]
WordPress.tv: https://wordpress.tv/2024/10/11/nested-blocks/

**Comment by jonathanbossenger** [comment]
Youtube: https://youtu.be/FpKB2432w_E

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/nested-blocks/
