### ISSUE TITLE
Hidden Lessons appear in search results

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#2735]
This production Lesson is set to be hidden:

![Image](https://github.com/user-attachments/assets/67dc7283-e5c9-4b37-acef-3bb17bd3e417)

We added a new post meta `_lesson_archive_excluded` to the Lesson post type, to enable to hiding specific Lessons (eg. quizzes) from archive and search views.

This works in local development and for the lessons archive in production, **but not with Jetpack search running in production**. I have tested this on the [staging site](https://learn.wordpress.org/test/) without Jetpack Search running and it works.

### Steps to reproduce

1. Log in to production
2. Create a Lesson and privately publish it. This should mean admins can see it but not regular users. Use a name you can easily search for later.
4. On the frontend navigate to the [Lessons archive](https://learn.wordpress.org/lessons/?new-theme=1) and locate your Lesson in the grid.
5. In the admin check the post meta box in the sidebar for 'Hidden Lesson -> Exclude this lesson from the archive'
![Image](https://github.com/user-attachments/assets/2d9858c3-5de5-4e1b-9e93-99eba92d2e1b)
6. Refresh the frontend archive and the Lesson should be hidden
7. Search for your Lesson using the search box

#### Expected
The lesson remains hidden

#### Actual
The lesson is included in the search results

**Comment by adamwoodnz** [comment]
Related issue for filtering search results by Language: https://github.com/WordPress/Learn/issues/2577

**Comment by adamwoodnz** [comment]
The easiest way to solve this is likely using a taxonomy instead of post meta (see comments on https://github.com/WordPress/Learn/issues/2577). Given this only happens when searching specifically I think it can be addressed post launch.

**Comment by adamwoodnz** [comment]
Jetpack search indexing isn't picking up the new taxonomy, reopening while we investigate.

**Comment by trakos** [comment]
I've looked into it, and it appears that the indexing is picking up the new taxonomy correctly. It's only the search condition that isn't translated to ES. I've opened https://github.com/WordPress/Learn/pull/2843 as a potential fix - not sure if it that's the right approach, but it should at least showcase the problem.

**Comment by adamwoodnz** [comment]
@westnz @jonathanbossenger this taxonomy based filtering should be working now. https://learn.wordpress.org/?s=spam and https://learn.wordpress.org/?s=quiz&post_type=lesson both should be displaying content as expected.

I've migrated all the lessons that had the 'Hidden Lesson' post meta applied to the new Visibility taxonomy. From now on you can set this in the sidebar instead:

<img src="https://github.com/user-attachments/assets/f3ad3a86-b264-40ca-9a61-bd20813b9514" width="300">

I'll be removing the old setting next.
