### ISSUE TITLE
Convert lesson plan details into block widget

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#274]
The lesson plans have a static widget that shows lesson plan details.

Pull request #239 converts the sidebars into dynamic widget areas, but that widget is still hardcoded static content. This needs to be converted to a block widget. V1 would be fine to have the widget with no options so we can at least move it around, but v2 could have some options for what to show.

**Comment by ryelle** [comment]
@hlashbrooke is that this section?

<img width="325" alt="Screen Shot 2021-12-14 at 4 40 04 PM" src="https://user-images.githubusercontent.com/541093/146083645-4519fef2-6852-4ef3-86d4-22bccd8faac6.png">

**Comment by hlashbrooke** [comment]
Yeah that's it.

**Comment by adamwoodnz** [comment]
This should support translations too.

**Comment by adamwoodnz** [comment]
@hlashbrooke I'm starting to look into this and need some clarification please:

> so we can at least move it around

Can you give an example of another place this would be used? This will help me ensure the block is fit for purpose.

~How are you thinking you would use this? Given this isn't a block theme maybe a shortcode could work? That way you can use it in the editor or within a template.~

**Comment by hlashbrooke** [comment]
My thinking with saying we can move it around isn't to use it on other content types (since it's unique to Lesson Plans), but to allow us to move the widgets around as needed - this will allow us more flexibility with the sidebar layout as we add more content to it in the future. So no specific plans, but I was hoping for it to allow us flexibility as we move forward.

**Comment by adamwoodnz** [comment]
So using the widget editor you'd be able to include the Lesson Plan details block wherever you see fit within this Lesson Plan sidebar?

![Screen Shot 2022-09-06 at 11 26 28 AM](https://user-images.githubusercontent.com/1017872/188520348-6b86a615-c7df-4840-95b3-e6464a2a77ca.jpg)

**Comment by hlashbrooke** [comment]
Yes - exactly :)

**Comment by adamwoodnz** [comment]
At the moment the details and actions (print button, etc) are grouped. Is it ok for them to stay like that, or would it be beneficial to be able to split them and move independently?

![Screen Shot 2022-09-06 at 3 10 57 PM](https://user-images.githubusercontent.com/1017872/188539154-b7bdc7b7-65f4-428a-8f96-05f1f7f6060b.jpg)

**Comment by hlashbrooke** [comment]
If we could split them into separate blocks that we can move around as widgets, that would be ideal.
