### ISSUE TITLE
Quiz needs better design consistency

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/Learn#2745]
The quiz page has had some light styling updates but I feel like it needs more to be consistent with styles across the rest of the site

| Incomplete | Complete |
|--------|--------|
| ![Image](https://github.com/user-attachments/assets/e17cdcbf-bbbc-40be-86b7-3a01fc587487) | ![Image](https://github.com/user-attachments/assets/fb76a926-5b43-4a34-bbff-426753c35061) |

**Comment by adamwoodnz** [comment]
@WordPress/meta-design your input please

**Comment by marko-srb** [comment]
I am not sure about this issue. Although I do agree quiz could have some more fun, I don't think it differs from the lesson layout/design. Plus other forms on learn are pretty much the same. 

On the first look, I'd say this requires some visuals to be more fun. In that light we'd need some time to figure it out — meaning I think this is a task for after the launch. Or if you still think we need to do something before the launch, we might reuse some illustration styles for the hero of a 'success' page. Like attached (roughly).

Did you have something else in mind though? 


![image](https://github.com/user-attachments/assets/289523d6-afb2-4d29-9785-b60f27c2de26)

**Comment by adamwoodnz** [comment]
That looks great to me!

Should have been more specific sorry; I was mostly referring to font sizes/weights, style of success messages, and the grading box as you've identified.

**Comment by jasmussen** [comment]
Nice illustration. One nitpick: the top and bottom of the WordPress logo cause a tangent with this crop:
![Screenshot 2024-07-31 at 09 18 59](https://github.com/user-attachments/assets/549df2df-e6ec-444e-a595-3fe5a7751b72)

I'd either scale it down to avoid the tangent, or scale it up to make the crop look more intentional.

**Comment by marko-srb** [comment]
Yes, that was just a random quick test. However, here are two images (one for 100% success, one for 'try again') in case you want them implemented now. Fixed height across devices, just cut the sides of the images for smaller devices... 

@adamwoodnz in case you need this now. Styling is good, ok for now - no worries.

![Success Image](https://github.com/user-attachments/assets/6da44470-f847-4000-8b01-d4a6ddeb7a8e)
![Try Again Image](https://github.com/user-attachments/assets/112343f3-6ed3-4b2b-a967-e8fdf29668ee)

**Comment by outdoor2kode** [comment]
Closed as completed by https://github.com/WordPress/Learn/pull/2881.
