### ISSUE TITLE
Learning Pathways - Put into a grid

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2766]
### Issue

Since there's only a small number of courses in each Learning Pathway (LP) level (i.e. User, Developer) the Learning Pathways archive pages look a bit sparse/unfinished.

## Solution

Combine the different levels into one grid temporarily, until there are more LP courses.

Remove:
- "See all"
- Level heading
- Level description

<img width="1417" alt="Develop_with_WordPress___Learn_WordPress" src="https://github.com/user-attachments/assets/0f5acd1a-5e5d-47c4-aeb5-f4141e9e8bb9">

It would then look more like the search results template:

https://learn.wordpress.org/?s=user&wporg_learning_pathway=user&new-theme=1

<img width="1007" alt="Start_using_WordPress___Learn_WordPress" src="https://github.com/user-attachments/assets/eb28ac2e-79e7-4654-a79d-0e9f6cde81fe">

**Comment by marko-srb** [comment]
Yes, this fix should work well until there are more courses (when we can return to current)... Thanks @kathrynwp!

**Comment by adamwoodnz** [comment]
Ideally we would write logic so this switch would happen automatically. What would that be; a total number of courses for a pathway, or a certain number for each level?

**Comment by marko-srb** [comment]
@adamwoodnz , that's even better than manually. Nice. If we can make logic something like this:

achieve minimum 2 courses per each category/level
while minimum 3 courses in any single category/level

before switching back to current look, that would be great. If not, only the first condition then.

Thanks!
