### ISSUE TITLE
Lessons archive pages - Better distinguish between lessons with the same name

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2767]
## Issue

At the moment, there is no quick way for learners to distinguish between lessons with the same name. There may be lessons with the same name that are part of different courses, or standalone lessons with the same name.

## Details

1. Visit the lessons archive page - https://learn.wordpress.org/lessons/
2. Do a search for a term like `block` - https://learn.wordpress.org/?s=block&post_type=lesson

## Result

In the search results, observe two courses called "Block attributes"

<img width="346" alt="Lessons___Learn_WordPress" src="https://github.com/user-attachments/assets/2abcf92d-fc21-426f-8814-0d063668b2f9">

There's no way for a learner to distinguish between the two – without clicking into it and seeing the course that it's part of.

## Improvement

Could we display the name of the course to which the lesson belongs, or think of another way to distinguish among lessons with the same name? In the example above, even if we added a level to the second course, it would also be Beginner, so that wouldn't be enough.

Example of what it could look like:

<img width="348" alt="Lessons___Learn_WordPress" src="https://github.com/user-attachments/assets/bb7c1b0e-dd74-47a7-8d79-9a63e86d8b90">

**Comment by adamwoodnz** [comment]
@WordPress/meta-design your input please

**Comment by jasmussen** [comment]
It seems useful to include the course taxonomy, in this case "Beginner WordPress Developer", to differentiate, for contexts like these.

I'd prefer to defer to Francisco/Marko on this one, they have some context for these card designs that I do not. Such as, perhaps in most cases, these cards are shown in context of a course, and therefore it's only ever on _search results_ that you'd see them atomically split out. If that's the case, then I'd think we should only include this taxonomy on search results, so as to not make the cards uniformly more verbose. 

If we do that, perhaps the permalink could have this format: "[Course]: [Lesson]". I.e. "Beginner WordPress Developer: Block Attributes".

Another path to explore is to segment the search results into subheadings. Pseudo code:

```
<h3>Beginner WordPress Developer course</h3>

[Lesson cards]

<h3>Developing your first WordPress block</h3>

[Lesson cards]
```

---

On a higher level, there's an aspect to naming and curation here, where it would be useful for lesson authors to be mindful of this particular SEO, and perhaps try to search and ambiguate when a match is found, before they name lessons the same. 

Additionally, we should be uniform in how text-case is applied. Is it "Block attributes" or "Block Attributes"?

In both cases, there should be site-wide (i.e. applying to every section, News, Learn, Dev Resources, Documentation) about the above two items, so text-case and SEO are considered across every piece. @kathrynwp I wonder, is a "best practices" doc, that's global to the wp.org site, something you or the Learn team could help get underway? IIRc we've settled on _sentence case with capital letters for proper nouns_ as the main rule of thumb for most other content.

**Comment by kathrynwp** [comment]
> Such as, perhaps in most cases, these cards are shown in context of a course, and therefore it's only ever on search results that you'd see them atomically split out. If that's the case, then I'd think we should only include this taxonomy on search results, so as to not make the cards uniformly more verbose.

They are also shown on the Lessons archive page, which is linked off the homepage:

https://learn.wordpress.org/lessons/

For consistency, clarity, and usability, I think we should update the cards on the Lessons archive page as well, so they look the same on all types of archives. It's very useful for learners to know which course a lesson is part of, no matter whether they're seeing it here or via a search.

> Additionally, we should be uniform in how text-case is applied. Is it "Block attributes" or "Block Attributes"?

> In both cases, there should be site-wide (i.e. applying to every section, News, Learn, Dev Resources, Documentation) about the above two items, so text-case and SEO are considered across every piece. @kathrynwp I wonder, is a "best practices" doc, that's global to the wp.org site, something you or the Learn team could help get underway? IIRc we've settled on sentence case with capital letters for proper nouns as the main rule of thumb for most other content.

Yep, when creating the thumbnails we are following WordPress.org style, which is:

> Use sentence-case capitalization in titles and headings. Capitalize the first word in the title or heading, sub-heading, any proper nouns, and official terms. If a title or heading includes a colon, capitalize the following word.

Ref: https://make.wordpress.org/docs/style-guide/language-grammar/capitalization/

There may be older lessons or courses that do not follow this style; given all the tasks on everyone's to-do list before the launch, folks did not have time to go back and update the hundreds of lessons and courses with this capitalization, but going forward this is what's being used. :)

**Comment by adamwoodnz** [comment]
> I'd prefer to defer to Francisco/Marko on this one, they have some context for these card designs that I do not. Such as, perhaps in most cases, these cards are shown in context of a course, and therefore it's only ever on _search results_ that you'd see them atomically split out. If that's the case, then I'd think we should only include this taxonomy on search results, so as to not make the cards uniformly more verbose.
> 
> If we do that, perhaps the permalink could have this format: "[Course]: [Lesson]". I.e. "Beginner WordPress Developer: Block Attributes".

> For consistency, clarity, and usability, I think we should update the cards on the Lessons archive page as well, so they look the same on all types of archives. It's very useful for learners to know which course a lesson is part of, no matter whether they're seeing it here or via a search.

@fcoveram / @marko-srb your thoughts please?

**Comment by fcoveram** [comment]
Here are two ideas for this.

## Section below metadata (v1)

The card has a new section below the metadata row. I made a new icon to convey the course that is part of, and the link works as a regular one with an underline on hover. To keep the card as clean as possible, the tag element behaves as regular link without the background color.

![version 1 of lesson card in regular and hover state](https://github.com/user-attachments/assets/464fe56c-a3a9-4a3f-b5ac-641d07436db5)

Here is a mockup of how it might look like on the Lessons archive page among others without a related course.

![Lessons archive page with V1 of lesson card](https://github.com/user-attachments/assets/f0b10fd2-c9d3-447b-bce1-700c93095da9)

## Label below title (v2)

The card has a new label showing the course that is part of below title. As in the other variant, the tag element changes to be more simple.

![version 2 of lesson card in regular and hover state](https://github.com/user-attachments/assets/36dc3585-f151-4f9a-9b1a-36520503d06c)

And here on the Lessons archive page.

![Lessons archive page with V2 of lesson card](https://github.com/user-attachments/assets/4528aa21-ab8b-42da-bea9-eba83dec8a5b)

---

What do you think of this? I slightly lean on version 1.

**Comment by adamwoodnz** [comment]
> What do you think of this?

While I like the aesthetic of version 1, I think version 2 keeps the cards shorter, and having the course title closer to the lesson title helps with gaining context.

**Comment by Piyopiyo-Kitsune** [comment]
Agreed that version 2 looks good and immediately directive. The icon on version 1 may be hard to understand and could confuse visually-impaired learners.

**Comment by kathrynwp** [comment]
Thanks for these, @fcoveram. I also prefer version 2; I think having the course title closer to the lesson title allows you to better understand that the lesson is contained within something else.

**Comment by jasmussen** [comment]
Nice work!

**Comment by fcoveram** [comment]
Awesome. Let's go with version 2 then.

I updated the [Lesson archive mockup](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=5338-14899&m=dev) and added [a section](https://www.figma.com/design/ZKaf6u8mIHkAanluWafXAp/Learn?node-id=5338-15214&m=dev) with all cards and their variants. Let me know if something is missing.

**Comment by kathrynwp** [comment]
@fcoveram Looks good to me!

Just wanted to flag for all that the Figma lesson cards no longer match up with the design on the live site. For example, the time was removed, and the level now has a coloured background. Not a big deal, but just wanted everyone to be aware. :)

The lessons currently look like this on the live site:

<img width="1209" alt="Lessons___Learn_WordPress" src="https://github.com/user-attachments/assets/88889e9e-fff7-4933-a859-a14f0de99726">

**Comment by fcoveram** [comment]
Thanks for sharing the difference.

I will remove the time info and keep the new version of the level link, as per [the design](https://private-user-images.githubusercontent.com/895819/355994287-36dc3585-f151-4f9a-9b1a-36520503d06c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNDg3MzIsIm5iZiI6MTcyMzE0ODQzMiwicGF0aCI6Ii84OTU4MTkvMzU1OTk0Mjg3LTM2ZGMzNTg1LWYxNTEtNGY5YS05YjFhLTM2NTIwNTAzZDA2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQyMDIwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDhhM2U1ZmVhNWZkY2ZhMmViZGJjODA3ZmRjYTIxZmRlMDk2NTAyMTI3MTY5ZDNhNzExZTEwYTI4ZGJiMWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5SrO0z_UjO3qoQwSM4CjyoMZxUK-R2oXwHelUhKT7pM) agreed on above (version 2).

**Comment by adamwoodnz** [comment]
> For example, the time was removed

> I will remove the time info

FYI the time will be displayed if it is set on a lesson, but the field isn't being used. I don't see a need to make code changes for this. I'll update the experience level styling though.
