### ISSUE TITLE
Update search archive page filter labels

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#2787]
At the moment we have two filters which are not immediately obvious what they filter for:

- All -- used to distinguish skill level
- Type -- used to distinguish the content type

I recommend we update these labels to the following for clarity:

- All --> Skill Level
- Type --> Content Type

**Comment by outdoor2kode** [comment]
Related: https://github.com/WordPress/Learn/issues/2784

**Comment by ryelle** [comment]
These have been updated to

- Type: Any
- Level: All

<img width="312" alt="Screenshot 2024-08-01 at 4 08 53 PM" src="https://github.com/user-attachments/assets/147e4316-d879-400e-a778-9aa277521f72">

I went with single words to save space, but if they need the full label, we can reopen this issue.
