### ISSUE TITLE
Seems like an icon is missing for type = "Course"

### ISSUE THREAD

**Issue by kjnanda** [WordPress/Learn#2794]
Steps:

1. Visit this link : https://learn.wordpress.org/
2. Try with empty search
3.  Observe that here, you will find the list of the courses and tutorials. 
4. But it looks like the icon for course is not showing up like tutorial.
5. If the icon is not design then we should definitely thinking to add for "course" 😄 
 
<kbd>![image](https://github.com/user-attachments/assets/cd1c2122-b5df-4cb2-b34e-9f2a9d3433f8)</kbd>

**Comment by kathrynwp** [comment]
Hi @kjnanda - thanks for the report! What you're looking at is an old version of the site that is about to be replaced with a completely new one in just a few days. If you'd like to test the new site, please see the instructions here and feel free to submit any issues:

https://make.wordpress.org/training/2024/07/09/lets-start-testing-learn-wordpress-org/

**Comment by kjnanda** [comment]
@kathrynwp Sorry for the wrong report! 🙇🏻‍♀️
