### ISSUE TITLE
Courses: The search field doesn't get cleared even after clearing it

### ISSUE THREAD

**Issue by pooja-muchandikar** [WordPress/Learn#2796]
**STEPS TO REPRODUCE**

- Go to the courses page and enter any random text in the search field
- As expected there will be no result
- Now click on the `x` cross mark to clear the field

**OBSERVATIONS**
- Observe that even after clearing the field the random text is still visible
- After clearing the search field and if any filter is applied it still shows the random text

**EXPECTED RESULT**
- The search field should get cleared
- The filter should work as expected

https://github.com/user-attachments/assets/69703715-749d-48d9-9345-c3b1103b189e

**Comment by kathrynwp** [comment]
Hi @pooja-muchandikar - thanks very much for the report. This looks like a duplicate of #2694 so I'll go ahead and close this, but if you think it does differ, please let me know and I'll be glad to take another look.

**Comment by pooja-muchandikar** [comment]
Thanks @kathrynwp for informing.
