### ISSUE TITLE
Meeting Agenda August 1, 2024

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#2803]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @Piyopiyo-Kitsune ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- August 1 – [@nazmul111](https://profiles.wordpress.org/nazmul111/)
- August 8 – [@dhaval59](https://profiles.wordpress.org/dhaval59/)
- August 15 – Zeel Thakkar
- August 22 – needs volunteer

**2. Looking for feedback**

- 

**3. Looking for volunteers**

- [Call for contributors: Intermediate Plugin Developer learning pathway](https://make.wordpress.org/training/2024/07/30/call-for-contributors-intermediate-plugin-developer-learning-pathway/)
- [Project Thread: Content Maintenance Process Update Phase 1](https://make.wordpress.org/training/2024/06/28/project-thread-content-maintenance-process-update-phase-1/)

**4. Updates from last week's dev-squad triage session**

- item 1
- item 2

**5. Other news**

- The Welcome box on the Training Team site has been updated to be more concise
- The Learn WordPress redesign is due to launch tomorrow, August 2nd
- WCUS Training Team Table Leads
- Onboarding Hour
  - Destiny [@piyopiyofox](https://profiles.wordpress.org/piyopiyofox/) will be hosting onboarding hour in August. Zoom links will be provided in the #training Slack channel 5 minutes before for the dates and times
➡️ August 5 at 23:00 UTC - [Zoom link](https://us02web.zoom.us/j/83174682577?pwd=pNZZkvTHcBtVaauQu9uaPQcawyZBqc.1)
➡️ August 7 at 07:00 UTC - [Zoom link](https://us02web.zoom.us/j/89514653982?pwd=OqPeN1UurBC92gGGokiunq3IXhrjbC.1)
- Meet the new Learn WordPress
  - @kathrynwp will be hosting two sessions going over the newly launched Learn WordPress website
➡️ [Sign up for session 1](https://www.meetup.com/learn-wordpress-online-workshops/events/302434418/) / Aug. 6 - 14:00 UTC - [convert time](https://time.is/1400_06_August_2024_in_UTC)
➡️ [Sign up for session 2](https://www.meetup.com/learn-wordpress-online-workshops/events/302387426/) / Aug. 8 - 21:00 UTC - [convert time](https://time.is/2100_08_August_2024_in_UTC)
- Learn WordPress was mentioned in the [Meetup Organizer Newsletter: July 2024](https://make.wordpress.org/community/2024/07/29/meetup-organizer-newsletter-july-2024/)
- [Team Profile Badges](https://make.wordpress.org/training/handbook/about/team-profile-badges/) handbook page has been updated to be more clear. Kindly note that meeting note takers must publish 5 notes now to qualify for a Training Contributor badge.

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 3 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 29 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 2 issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have 0 issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 20 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: 
  - [Training Contributor](https://profiles.wordpress.org/associations/training-contributor/): [Md Golam Mubasshir Rafi](https://profiles.wordpress.org/gmrafi/), [Yagnik Sangani](https://profiles.wordpress.org/yagniksangani/), [Jagir Bahesh](https://profiles.wordpress.org/jagirbahesh/), [Noruzzaman](https://profiles.wordpress.org/noruzzaman/), [zeelthakkar](https://profiles.wordpress.org/zeelthakkar/), [Satyam Vishwakarma (Satya)](https://profiles.wordpress.org/hellosatya/)
  - [Training Team](https://profiles.wordpress.org/associations/training-team/): [Vagelis](https://profiles.wordpress.org/eboxnet/)
- Props: 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
  - details
- Project_2
  - details

## 5. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
Dev-squad update: there were no new PRs or bugs to triage.

**Comment by kathrynwp** [comment]
As part of the [Faculty Program retirement plan](https://make.wordpress.org/training/2024/07/02/project-thread-retiring-the-faculty-program/), I've drafted a new handbook page with a brief history of the Training Team. You'll find the draft here:

https://docs.google.com/document/d/1magOfvl1u14bniyHKHuhWWrt590dDSw7A3XQG0akLsE/edit?usp=sharing

Feedback is welcome before the page is published, ideally by August 6. I'm also specifically looking for help confirming the dates of some of the team reps.

**Comment by kathrynwp** [comment]
I received feedback that it's very easy to miss the more informal calls that are sometimes announced in the #training team channel but not posted on Meetup, such as:

- Coffee Hours
- Contributor Hours
- Hallway Hangouts

Is there some other way we can think of to announce these so that folks who don't read every part of Slack backscroll can get notified by email?

**Comment by kathrynwp** [comment]
Learn WordPress remake project update: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4319

**Comment by kaitohm** [comment]
No recap was published.
