### ISSUE TITLE
Feedback - A course called Tutorial Quizzes with lots of lessons being considered as quizzes

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2818]
## Type of feedback

//dev

## Description

These quizzes are wrapped in empty lessons and a course. We assume that they can be linked to tutorials, but it means they show up unexpectedly. We could write a custom exception to exclude content from this course.

## Step-by-step reproduction instructions (optional)

Got to learn.wordpress.org
Type 'spam'
Select the second option 
URL: https://learn.wordpress.org/?s=Spam

## Screenshots or screen recording (optional)

<img width="1155" alt="Screenshot 2024-08-02 at 1 35 04 PM" src="https://github.com/user-attachments/assets/4284ac56-fca9-4f30-97ea-2385c8310c4b">

## Other information (optional)

Desired outcome: These lessons should not appear in search.

**Comment by kathrynwp** [comment]
There are two related issues:

#2735 is for the bug where lessons that have the "hide this lesson on archives" checkbox are still being displayed on search archives.

#2823 is to hide the "container" course called Tutorial Quizzes from all archives and searches.

**Comment by adamwoodnz** [comment]
> There are two related issues:
> 
> [#2735](https://github.com/WordPress/Learn/issues/2735) is for the bug where lessons that have the "hide this lesson on archives" checkbox are still being displayed on search archives.
> 
> [#2823](https://github.com/WordPress/Learn/issues/2823) is to hide the "container" course called Tutorial Quizzes from all archives and searches.

IMO this course shouldn't be required and the symptoms outlined will be resolved by either one of these related issues, so closing this in favor of them.
