### ISSUE TITLE
Learn fallback image

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#282]
The Learn fallback image shows Discussion groups. A new design that reflects:

- Workshops
- Social Learning
- Lesson Plans
- Courses 

Should be created.

**Comment by hlashbrooke** [comment]
Good catch!

**Comment by hlashbrooke** [comment]
Thinking about this a bit more - I feel like a more generic image that doesn't specifically mention the content types might be better here. I'm happy to be shown otherwise though!

**Comment by courtneyr-dev** [comment]
That could work as well, however, let's make it more interesting than the fallback across team P2s.

**Comment by kaitohm** [comment]
Closing in favor of #1329
