### ISSUE TITLE
Feedback - Reorder the content blocks of the “Beginner WordPress User” course

### ISSUE THREAD

**Issue by viobru** [WordPress/Learn#2820]
## Type of feedback

//content

## Description

The content blocks of the “Beginner WordPress User” course are not displayed in logical order, but alphabetically.

The first content block should be “Getting started with WordPress” and not “Content Creation”.

## Screenshots or screen recording (optional)

![Beginner WordPress User Learn WordPress 2024-08-02 at 8 45 56 PM](https://github.com/user-attachments/assets/6505cb57-5f79-4667-aaad-76ef3140c053)

## Other information (optional)

The same happens for the “Intermediate WordPress User” course, but may not be that relevant in that case.

**Comment by jonathanbossenger** [comment]
@westnz I'm not sure how this happened, but I've reordered the modules according to the structure as [defined in the in the outlineoutline](https://github.com/WordPress/Learn/issues/1977). If you could please check this and make sure you're happy with the content as presented.

**Comment by kathrynwp** [comment]
@adamwoodnz I'm curious if you can tell how this happened? (I don't see anything in the revision history.) Thanks!

**Comment by westnz** [comment]
Thank you very much @jonathanbossenger!  You have re-ordered them correctly. I am also curious how that could've happened.

**Comment by adamwoodnz** [comment]
It looks like the order changed when [this revision](https://learn.wordpress.org/wp-admin/revision.php?revision=260984) was saved. Not sure how though.

**Comment by jonathanbossenger** [comment]
I'm going to close this out for now.
