### ISSUE TITLE
Hide a course composed just of quizzes

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2823]
Is there any way to hide this "utility" course from archives and searches?

https://learn.wordpress.org/course/tutorial-quizzes/

As it says on the page:

> This course exists to contain the quizzes for all [standalone tutorials](https://learn.wordpress.org/tutorials/) that do not form part of a course.

It looks strange to have it visible, since it is does not make sense for anyone to sign up for this – it's not a "real" course with modules.

<img width="938" alt="Tutorial_Quizzes___Learn_WordPress" src="https://github.com/user-attachments/assets/501f52ba-68cf-4666-a490-b032a008f76c">

I don't know if this course will be needed once [Tutorials are converted to Lessons](https://github.com/WordPress/Learn/issues/2393).

**Comment by adamwoodnz** [comment]
> I don't know if this course will be needed once [Tutorials are converted to Lessons](https://github.com/WordPress/Learn/issues/2393).

IMO this is the best path forward; all these tutorials that still have value should be migrated to lessons and can then have the respective quiz added directly.

If this will take time I think the fix for #2735 will at least make it possible to hide the lessons in the meantime. That fix is high priority and will be addressed asap.

**Comment by adamwoodnz** [comment]
Actually [quizzes for standalone lessons aren't supported](https://github.com/WordPress/Learn/issues/2643), so there would still need to be a parent course. [Hiding the lessons](https://github.com/WordPress/Learn/issues/2735) might be the only path forward.

**Comment by adamwoodnz** [comment]
Ultimately I think it would be good to avoid writing code to filter courses like this (only lessons having only a quiz). It feels like we should be able to find a better content based solution.

@westnz I remember you previously mentioned that you didn't think there would be a need for quizzes for standalone lessons, do you still hold that view?

@jonathanbossenger any thoughts?

**Comment by westnz** [comment]
> @westnz I remember you previously mentioned that you didn't think there would be a need for quizzes for standalone lessons, do you still hold that view?

To clarify, I said we won't need quizzes for standalone lessons. I believe Jonathan confirmed this as well. 😃

**Comment by adamwoodnz** [comment]
> > @westnz I remember you previously mentioned that you didn't think there would be a need for quizzes for standalone lessons, do you still hold that view?
> 
> To clarify, I said we won't need quizzes for standalone lessons. I believe Jonathan confirmed this as well. 😃

What I'm getting at is that these tutorials are planned to become standalone lessons, and they have quizzes. If there is no need for them to have the quizzes can we delete this course, lessons and quizzes then? And remove the links from the tutorials if they exist, prior to migration.

**Comment by westnz** [comment]
Now I am with you. I thought this might've affected learning pathway lessons as well, but now I realize this only relates to tutorials. 

I am happy to delete the course, and for these standalone tutorials that will become lessons, not to have quizzes. 

Some of these tutorials might be on the deprecation list as they have been updated.

**Comment by adamwoodnz** [comment]
> I am happy to delete the course, and for these standalone tutorials that will become lessons, not to have quizzes.

Great, I will leave it to the content team to resolve this then 🙂

**Comment by kathrynwp** [comment]
@adamwoodnz @westnz Just wanted to confirm:

> I am happy to delete the course, and for these standalone tutorials that will become lessons, not to have quizzes.

This can only happen once tutorials have been migrated to lessons, correct? TY!

**Comment by adamwoodnz** [comment]
> @adamwoodnz @westnz Just wanted to confirm:
> 
> > I am happy to delete the course, and for these standalone tutorials that will become lessons, not to have quizzes.
> 
> This can only happen once tutorials have been migrated to lessons, correct? TY!

Not necessarily; we could remove the links to the quizzes from the existing tutorials, and then trash the quizzes, lessons and course.

**Comment by kathrynwp** [comment]
Alright – thanks, @adamwoodnz ! 

@westnz I'll leave this in your hands but please let me know if I can do anything to help, happy to dive in.

**Comment by westnz** [comment]
Hey @adamwoodnz 

> Not necessarily; we could remove the links to the quizzes from the existing tutorials, and then trash the quizzes, lessons and course.

Do I need to open each tutorial, remove the quiz link, and then delete the quizzes one by one before I can delete the course?

Is there a simpler way?

**Comment by adamwoodnz** [comment]
> Do I need to open each tutorial, remove the quiz link

Unfortunately I don't think there's a quicker way to remove these links

> and then delete the quizzes one by one before I can delete the course?

You could delete the course first, but then you'll lose track of what Lessons are linked I imagine. At the moment [when editing](https://learn.wordpress.org/wp-admin/post.php?post=9083&action=edit) you can see the list of Lessons at the bottom:

![Screenshot 2024-08-19 at 12 03 20 PM](https://github.com/user-attachments/assets/8008d47a-4dab-4dfb-9290-bd32b80dc80f)

Any lessons we miss trashing will be left orphaned, and still show up in the archives. I've tried but can't find a way to get the list of lessons available for bulk editing.

**Comment by westnz** [comment]
Done

@adamwoodnz, as discussed, we can close this issue once you have taken care of the built-in functionality on tutorials. 
<img width="279" alt="Screenshot 2024-08-19 at 3 03 23 PM" src="https://github.com/user-attachments/assets/0c944cc3-4e71-482d-ae76-48d8b682bee9">
