### ISSUE TITLE
Meeting Agenda, 8th August 2024

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2825]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by MEETING_HOST._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- August 8 – [dhaval59](https://wordpress.slack.com/team/U075J452DV1)
- August 15 – [Zeel Thakkar](https://wordpress.slack.com/team/ULM1UU1B9)
- August 22 – [noruzzaman](https://wordpress.slack.com/team/U04A11X1J2H) 
- August 29 - Looking for volunteer

**2. Looking for feedback**

**3. Looking for volunteers**

- [Call for contributors: Intermediate Plugin Developer learning pathway](https://make.wordpress.org/training/2024/07/30/call-for-contributors-intermediate-plugin-developer-learning-pathway/)
- [Project Thread: Content Maintenance Process Update Phase 1](https://make.wordpress.org/training/2024/06/28/project-thread-content-maintenance-process-update-phase-1/)

**4. Updates from last week's dev-squad triage session**

- No dev squad this week

**5. Other news**

- The new [Learn WordPress](http://learn.wordpress.org/) design has launched! Read more about the journey to this launch in [Meet the new Learn WordPress](https://make.wordpress.org/training/2024/08/02/meet-the-new-learn-wordpress/)!
- item 2

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have # issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have # issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have # issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have # issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Contributors, Editors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have # issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: 
- Props: 

## 4. Project updates

- [Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)

## 5. Contributor Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other contributors or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kathrynwp** [comment]
On August 1, the new [Learn.WordPress.org](https://learn.wordpress.org/) went live. 🎉 Huge congratulations to everyone involved in this project, which has been so long in the making!

It was announced publicly in [this Make Training Team post](https://make.wordpress.org/training/2024/08/02/meet-the-new-learn-wordpress/), and [this WordPress.org News post](https://wordpress.org/news/2024/08/a-brand-new-way-to-learn-wordpress/).

This week there will be a few marketing initiatives to get the word out and introduce people to the new site:

- Get a guided tour of all the exciting Learn WordPress changes from the Training team’s Jonathan Bossenger, Wes Theron and Kathryn Presner. Check out the next edition on [Thursday, August 8 at 21:00 UTC](https://www.meetup.com/learn-wordpress-online-workshops/events/302387426/) or [watch the recording from August 6's workshop](https://wordpress.tv/2024/08/06/meet-the-new-learn-wordpress-org/).
- The Learn WordPress launch will be part of a [Media Corps Briefing on Wed. August 7](https://make.wordpress.org/media-corps/2024/08/01/upcoming-media-corps-briefing-scheduled-for-august-7/).

There has already been [a positive review in WPShout](https://wpshout.com/new-learn-wordpress-launches/).

(I also updated the project p2 thread with the same info: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4327)

**Comment by kathrynwp** [comment]
As part of the [Faculty Program retirement plan](https://make.wordpress.org/training/2024/07/02/project-thread-retiring-the-faculty-program/), I wrote up a new handbook page with a brief history of the Training Team and requested feedback. Thank you to all who provided suggestions and clarifications. I've gone ahead and published the new page, including a note at the bottom that if anyone has further clarifications or corrections to suggest, they can fill out the contact form, which will come into Help Scout.

https://make.wordpress.org/training/handbook/about/history-of-the-training-team/

**Comment by kathrynwp** [comment]
To add to the item about site launch:

---

There are a number of items on the post-launch list, which you can see here:

https://github.com/WordPress/Learn/milestone/21

If you encounter any bugs or want to suggest an enhancement, please use the feedback template in GitHub: 

https://github.com/WordPress/Learn/issues/new?assignees=&labels=Awaiting+Triage&projects=&template=00-feedback.md&title=Feedback+-

**Comment by kathrynwp** [comment]
Via Nilo Velez:

> You can filter by the "Learn WordPress" category
https://wordpress.tv/category/learn-wordpress/
>
> You can even subscribe to its feed
https://wordpress.tv/category/learn-wordpress/feed/

In order for this to work, we need to remember to add the `Learn WordPress` category when submitting videos to WordPress.tv. For Online Workshops, the category `Learn WordPress Online Workshops` should be added as well. Full steps to submitting a Learn WordPress video in these guides:

https://make.wordpress.org/training/handbook/guidelines/tutorials/publishing-a-tutorial/
https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/

**Comment by kathrynwp** [comment]
### Props

Props to Cynthia Norman for launching her first course, [Intermediate Theme Developer](https://learn.wordpress.org/course/intermediate-theme-developer/), and for participating in today's [Media Corps briefing](https://make.wordpress.org/media-corps/2024/08/01/upcoming-media-corps-briefing-scheduled-for-august-7/) to help promote the new site! 🎉 

Props to Roelof Wobben for completing the [Training Team Guide Program](https://make.wordpress.org/training/handbook/guide-program/), with Jonathan Bossenger as his Guide!

**Comment by Dhaval59** [comment]
I have created recap for 8th August 2024.
[Meeting Recap link](https://make.wordpress.org/training/2024/08/13/training-team-meeting-recap-8th-august-2024/)
