### ISSUE TITLE
Feedback - Incorrectly embedded video on Getting started with the WordPress dashboard

### ISSUE THREAD

**Issue by Contributor2230** [WordPress/Learn#2837]
## Type of feedback
//content

## Description
The embedded video on these pages plays videos in a playlist that do not match the lesson content:
* [Getting started with the WordPress dashboard](https://learn.wordpress.org/lesson/getting-started-with-the-wordpress-dashboard/) The first video in the playlist is an overview of WordPress 6.6, while the text of the lesson is an overview of the WordPress dashboard.
* [Understanding the difference between WordPress posts and pages](https://learn.wordpress.org/lesson/understanding-the-difference-between-wordpress-posts-and-pages/
) The first video in the playlist is an overview of WordPress 6.6, while the text of the lesson is the difference between posts and pages.

## Step-by-step reproduction instructions (optional)
1. Go to https://learn.wordpress.org/lesson/getting-started-with-the-wordpress-dashboard/
2. Play the embedded video at the beginning of the page
3. Go to https://learn.wordpress.org/lesson/understanding-the-difference-between-wordpress-posts-and-pages/
4. Play the embedded video at the beginning of the page

## Screenshots or screen recording (optional)
![Screenshot of beginning of video](https://github.com/user-attachments/assets/aae8bfad-2871-40e6-8c33-3c70cb3ee83e)

![Video doesn't match on posts and pages lesson](https://github.com/user-attachments/assets/7e03bb50-ea3e-44a7-b965-7a3409d4ec0d)

## Other information (optional)
Expected video for Getting started with the WordPress dashboard: https://www.youtube.com/watch?v=VCgWDVu-tOw

Expected video for Understanding the difference between WordPress posts and pages: https://www.youtube.com/watch?v=bSbRXQRNovA

It looks like the embeds attempt to reference the correct videos, however within the context of a playlist that does not contain the videos.

Actual src value for Getting started with the WordPress dashboard: https://www.youtube.com/embed/VCgWDVu-tOw?list=PL1pJFUVKQ7ETacCXdCCxwdAo-_xciwlQJ&enablejsapi=1&origin=https://learn.wordpress.org

Suggested src value for Getting started with the WordPress dashboard (no list parameter): https://www.youtube.com/embed/VCgWDVu-tOw?feature=oembed&enablejsapi=1&origin=https://learn.wordpress.org

Actual src value for Understanding the difference between WordPress posts and pages: https://www.youtube.com/embed/bSbRXQRNovA?list=PL1pJFUVKQ7ETacCXdCCxwdAo-_xciwlQJ&#038;enablejsapi=1&#038;origin=https://learn.wordpress.org

Suggested src value for Understanding the difference between WordPress posts and pages: https://www.youtube.com/embed/bSbRXQRNovA?feature=oembed&enablejsapi=1&origin=https://learn.wordpress.org

**Comment by jonathanbossenger** [comment]
@westnz checking in here, I think this has been resolved?

**Comment by westnz** [comment]
This has been resolved. Thank you!!
