### ISSUE TITLE
Meeting Agenda August 15, 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2841]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by lada7042._

Ice Breaker: What is one thing you like about the updated Learn WordPress site?

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- August 15 – [Zeel Thakkar](https://profiles.wordpress.org/zeelthakkar/)
August 22 – [noruzzaman](https://profiles.wordpress.org/noruzzaman/)
August 29 - [Marar Rithika](https://profiles.wordpress.org/rithika3/)
Sept. 5- Looking for volunteer

**2. Looking for feedback**

- Vote for the Learn WordPress North Star. Thank you for your feedback. The team reps narrowed it down to 3 options. Please vote 1, 2, or 3 in the thread 🧵 for the one you feel best conveys Learn WordPress' purpose.  Why we are part of this team?  

1. Learn WordPress makes WordPress knowledge accessible to all by empowering individuals around the world to create, contribute, and grow within the WordPress ecosystem. 
2. To make WordPress knowledge accessible to all through Learn WordPress, empowering everyone to create, contribute, and grow within the WordPress ecosystem. 
3. Learn WordPress is the source for the most up to date educational content on WordPress for Users, Developers, and Designers of WordPress. 

- Now that the new [Learn WordPress](https://learn.wordpress.org/) site has launched, There are a number of items on the post-launch list, which you can see here: https://github.com/WordPress/Learn/milestone/21
If you encounter any bugs or want to suggest an enhancement, please use the feedback template in GitHub: https://github.com/WordPress/Learn/issues/new?assignees=&labels=Awaiting+Triage&projects=&template=00-feedback.md&title=Feedback+-
- Course deprecation
With the initial learning pathways now published, some courses have become redundant or outdated. To streamline our offerings and ensure we provide the most current content to our learners, @westnz and @psykro propose deprecating the following courses and directing users to the relevant learning pathway.

- https://learn.wordpress.org/course/simple-site-design-with-full-site-editing/
- https://learn.wordpress.org/course/part-2-personalized-site-design-with-full-site-editing-and-theme-blocks/
- https://learn.wordpress.org/course/part-3-advanced-site-design-with-full-site-editing-site-editor-templates-and-template-parts/
- https://learn.wordpress.org/course/developing-with-the-wordpress-rest-api/
- https://learn.wordpress.org/course/converting-a-shortcode-to-a-block/
- https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-1/
- https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-2/

Deprecating these courses will help eliminate duplication and simplify updates, as the learning pathways will be easier to maintain and will consolidate content updates into a single location.

Please let us know if you feel any other courses should be deprecated and directed to a learning pathway or if there are any on this list we should consider keeping.

**3. Looking for volunteers**

- [Call for contributors: Intermediate Plugin Developer Learning Pathway](https://make.wordpress.org/training/2024/07/30/call-for-contributors-intermediate-plugin-developer-learning-pathway/)
- [Project Thread: Content Maintenance Process Update Phase 1](https://make.wordpress.org/training/2024/06/28/project-thread-content-maintenance-process-update-phase-1/)
- Call for testing: Playground block on Learn WordPress
Thanks to the work of @alexstine and @brandonpayton, we have been testing and fixing a11y issues in the Playground block on Learn WordPress. All of the outstanding issues have now been fixed, so we'd like to ask other a11y experts to help us test. 
You can find more details on this testing issue: https://github.com/WordPress/Learn/issues/2352

**4. Updates from last week's dev-squad triage session**

Dev squad triage recap for August 8, 2024

- Present, @psykro, @rfluethi, @noruzzaman, @digitalchild
- No new PRs
- One new bug triaged
  - https://github.com/WordPress/Learn/issues/2774
- The calendar for when these meetings occur has also been updated on our Training Team site welcome box, so please be mindful that the dev squad meets biweekly (every other week) on Thursdays [07:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?hour=07&min=00&sec=0). You can [view our scheduled meetings in this calendar](https://make.wordpress.org/meetings/#training).

**5. Other news**

- Content localization
Until we've been able to test TranslatePress and document a new process for content localization, please do not publish any new translated courses or lessons. (See https://github.com/WordPress/Learn/issues/2445 & https://github.com/WordPress/Learn/issues/2339) Do feel free to prepare translations outside of Sensei so they are ready to go once the new process has been determined.
- An update on last week's discussion about [adding categories to videos](https://wordpress.slack.com/archives/C02RW657Q/p1723078156643999) Thanks to [Jamie Madden](https://wordpress.slack.com/team/U0548P3UH) for bringing this to the team's attention and others' feedback. We did a little investigating and realized that a step for admins in the [Approving videos](https://make.wordpress.org/training/handbook/training-team-how-to-guides/approving-videos-and-subtitles-on-wordpress-tv/#approving-videos-502) was unclear. [Kathryn Presner](https://wordpress.slack.com/team/U02S3F8EK) & [Laura A](https://wordpress.slack.com/team/U0422D20MNF) updated the page for clarification. [Destiny](https://wordpress.slack.com/team/U02AZ6T2BRT) will be submitting an issue to add an Approve button for categories. Thank you to [nilovelez](https://wordpress.slack.com/team/U2SRWHG4C) for his feedback. 
- Notice block vs. Callout block
For those creating lessons, please note that:

Callout blocks are deprecated should no longer be used
Use the Notice block instead
If we’re updating a lesson, copy the text from the Callout block into a Notice block
 Kathryn also added a note to that effect on the [Create the Lesson on Learn.WordPress.org handbook page](https://href.li/?https://make.wordpress.org/training/handbook/lessons/create-the-lesson-on-learn-wordpress-org/).

reference/context: [https://github.com/WordPress/Learn/issues/2739#issuecomment-2276663747](https://href.li/?https://github.com/WordPress/Learn/issues/2739#issuecomment-2276663747)
- The previously announced [Faculty Program retirement plan](https://make.wordpress.org/training/2024/07/02/project-thread-retiring-the-faculty-program/), has progressed to the next step. The following Slack groups have been retired:
@faculty 
@faculty-admin 
@faculty-content-creators 
@faculty-editors
@faculty-smes
@faculty-dev-squad
@faculty-translation-coordinators
On Aug. 15 the private Faculty Program channel will be archived. As discussed with the team reps, we’ll give the changes a bit of time and see how it goes. If folks find a need to ping particular sets of people going forward and this channel and/or DMs aren’t working, we can come up with a solution at that point, like creating a new group or new channel, if needed.

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 1 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 30 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 4 issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have 0 issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Contributors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 20 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: 
- Props: [Jonathan](https://wordpress.slack.com/team/U0AHNQ65V), [Kathryn Presner](https://wordpress.slack.com/team/U02S3F8EK), and [Cynthia Norman](https://wordpress.slack.com/team/U05E2Q9N78U) for appearing on [Media Corps Briefing August 2024](https://make.wordpress.org/media-corps/2024/08/13/summary-of-august-2024-media-corps-briefing/) to talk about Learn WordPress and the Learning Pathways. 

## 4. Project updates

-[Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
[See the latest project update here](- See project update: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4336)

## 5. Contributor Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other contributor or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

- Jonathan brings this topic- Applying a feedback framework to GitHub issues related to the Learn WordPress site
I (@psykro) would like us to consider researching and applying some sort of feedback framework to GitHub issues related to the Learn WordPress site.

With the implementation of the new theme, we (the training team) are now able to better use more modern WordPress features and any new products that exist (now or in the future) in our ecosystem.

When suggesting, testing, and implementing any of these new features, it is important to find a balance between what we can control and what we can only influence. Some recent conversations come to mind, like the implementation of a translation plugin, the inclusion of the playground block, and the support for full-width alignment for lesson content.

When discussing these on GitHub, I think it's important that we have answers to the following questions in our minds: 

What is a feature vs. a bug? How do we decide the difference?

How do we determine what is a priority, and what is not?

Once something has been verified as "fixed" or "ready" how long should we wait for testing and feedback before it is implemented?

Before we implement something new, should we perform some sort of risk analysis, to determine the impact of this change?

I don't currently have answers to these questions, only opinions, so I'd like to start a discussion so that we can agree on a way forward and document it in our team handbook.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kathrynwp** [comment]
## Content localization

Until we've been able to test TranslatePress and document a new process for content localization, please do not publish any new translated courses or lessons. (See #2445 & #2339) Do feel free to prepare translations outside of Sensei so they are ready to go once the new process has been determined.

**Comment by kathrynwp** [comment]
## Notice block vs. Callout block

For those creating lessons, please note that:

- Callout blocks are deprecated should no longer be used
- Use the Notice block instead
- If we’re updating a lesson, copy the text from the Callout block into a Notice block

I also added a note to that effect on the [Create the Lesson on Learn.WordPress.org handbook page](https://href.li/?https://make.wordpress.org/training/handbook/lessons/create-the-lesson-on-learn-wordpress-org/).

reference/context: [https://github.com/WordPress/Learn/issues/2739#issuecomment-2276663747](https://href.li/?https://github.com/WordPress/Learn/issues/2739#issuecomment-2276663747)

**Comment by kathrynwp** [comment]
## Faculty program retirement updates

As part of the previously announced [Faculty Program retirement plan](https://make.wordpress.org/training/2024/07/02/project-thread-retiring-the-faculty-program/), the following Slack groups have been retired:

> @faculty 
> @faculty-admin 
> @faculty-content-creators 
> @faculty-editors
> @faculty-smes
> @faculty-dev-squad
> @faculty-translation-coordinators

On Aug. 15, the private Faculty Program channel will be archived. As discussed with the team reps, we’ll give the changes a bit of time and see how it goes. If folks find a need to ping particular sets of people going forward and this channel and/or DMs aren’t working, we can come up with a solution at that point, like creating a new group or new channel, if needed.

**Comment by jonathanbossenger** [comment]
## Course deprecation

With the initial learning pathways now published, some courses have become redundant or outdated. To streamline our offerings and ensure we provide the most current content to our learners, @westnz and @psykro propose deprecating the following courses and directing users to the relevant learning pathway. 

1. https://learn.wordpress.org/course/simple-site-design-with-full-site-editing/
2. https://learn.wordpress.org/course/part-2-personalized-site-design-with-full-site-editing-and-theme-blocks/
3. https://learn.wordpress.org/course/part-3-advanced-site-design-with-full-site-editing-site-editor-templates-and-template-parts/
4. https://learn.wordpress.org/course/developing-with-the-wordpress-rest-api/
5. https://learn.wordpress.org/course/converting-a-shortcode-to-a-block/
6. https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-1/
7. https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-2/

Deprecating these courses will help eliminate duplication and simplify updates, as the learning pathways will be easier to maintain and will consolidate content updates into a single location.

Please let us know if you feel any other courses should be deprecated and directed to a learning pathway or if there are any on this list we should consider keeping.

**Comment by jonathanbossenger** [comment]
## Call for testing: Playground block on Learn WordPress

Thanks to the work of @alexstine and @brandonpayton, we have been testing and fixing a11y issues in the Playground block on Learn WordPress. All of the outstanding issues have now been fixed, so we'd like to ask other a11y experts to help us test.

You can find more details on this testing issue: https://github.com/WordPress/Learn/issues/2352

**Comment by jonathanbossenger** [comment]
## Applying a feedback framework to GitHub issues related to the Learn WordPress site

I (@psykro) would like us to consider researching and applying some sort of feedback framework to GitHub issues related to the Learn WordPress site. 

With the implementation of the new theme, we (the training team) are now able to better use more modern WordPress features and any new products that exist (now or in the future) in our ecosystem.

When suggesting, testing, and implementing any of these new features, it is important to find a balance between what we can control and what we can only influence. Some recent conversations come to mind, like the implementation of a translation plugin, the inclusion of the playground block, and the support for full-width alignment for lesson content.

When discussing these on GitHub, I think it's important that we have answers to the following questions in our minds:
- What is a feature vs. a bug? How do we decide the difference? 
- How do we determine what is a priority, and what is not?
- Once something has been verified as "fixed" or "ready" how long should we wait for testing and feedback before it is implemented?
- Before we implement something new, should we perform some sort of risk analysis, to determine the impact of this change?

I don't currently have answers to these questions, only opinions, so I'd like to start a discussion so that we can agree on a way forward and document it in our team handbook.

**Comment by kathrynwp** [comment]
## Learn WordPress Relaunch

See project update: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4336

**Comment by Zeelthakkar1207** [comment]
Meeting recap post published : https://make.wordpress.org/training/2024/08/21/training-team-meeting-recap-15th-august-2024/
