### ISSUE TITLE
Meeting Agenda August 22, 2024

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2848]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by MEETING_HOST._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

August 22 – [noruzzaman](https://profiles.wordpress.org/noruzzaman/)
August 29 - [Marar Rithika](https://profiles.wordpress.org/rithika3/)
Sept. 5-  [Nishita Joshi ](https://profiles.wordpress.org/nishitajoshi/)
Sept. 12 - Looking for volunteer 

**2. Looking for feedback**

- Vote for the Learn WordPress North Star. Thank you for your feedback. The team reps narrowed it down to 3 options. Please vote 1, 2, or 3 in the thread 🧵 for the one you feel best conveys Learn WordPress' purpose. Why we are part of this team? 

1. Learn WordPress makes WordPress knowledge accessible to all by empowering individuals around the world to create, contribute, and grow within the WordPress ecosystem.
2. To make WordPress knowledge accessible to all through Learn WordPress, empowering everyone to create, contribute, and grow within the WordPress ecosystem.
3. Learn WordPress is the source for the most up-to-date educational content on WordPress for Users, Developers, and Designers of WordPress.

You can vote [here](https://docs.google.com/forms/d/e/1FAIpQLSddQEVzVeGKrP2iWWr98ZgwNqPca4Ed2DrOKV0lLzh-CfUPhw/viewform) 
 

- Now that the new [Learn WordPress](https://learn.wordpress.org/) site has launched. There are a number of items on the post-launch list, which you can see here: https://github.com/WordPress/Learn/milestone/21
         - If you encounter any bugs or want to suggest an enhancement, please use the [feedback template](https://github.com/WordPress/Learn/issues/new?assignees=&labels=Awaiting+Triage&projects=&template=00-feedback.md&title=Feedback+-) in GitHub.

**3. Looking for volunteers**

- [Call for contributors: Intermediate Plugin Developer Learning Pathway](https://make.wordpress.org/training/2024/07/30/call-for-contributors-intermediate-plugin-developer-learning-pathway/)
- [Project Thread: Content Maintenance Process Update Phase 1](https://make.wordpress.org/training/2024/06/28/project-thread-content-maintenance-process-update-phase-1/)
- Call for testing: Playground block on Learn WordPress
Thanks to the work of @alexstine and @brandonpayton, we have been testing and fixing a11y issues in the Playground block on Learn WordPress. All of the outstanding issues have now been fixed, so we'd like to ask other a11y experts to help us test.
You can find more details on this testing issue: https://github.com/WordPress/Learn/issues/2352

**4. Updates from last week's dev-squad triage session**

No dev squad this week. 

**5. Other news**

- An update to the ongoing discussion about [adding categories to videos](https://wordpress.slack.com/archives/C02RW657Q/p1723078156643999) [Destiny](https://wordpress.slack.com/team/U02AZ6T2BRT) has submitted a [trac](https://meta.trac.wordpress.org/ticket/7748) ticket to have the approve button added. 

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have # issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have # issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have # issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have # issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Contributors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have # issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: End of the month 
- Props: does anyone have any props for a fellow team member? :tada:

## 4. Project updates

-[Project Thread: Learning Pathways on Learn WordPress](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/)
[See the latest project update here](- See project update: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4336)

## 5. Contributor Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other contributor or Training Team members help you in some way?

## 6. Open Discussions

- Open discussions need a follow up place (GitHub, P2 etc), Looking for feedback should also have a follow up place (GitHub, P2 etc)

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by Piyopiyo-Kitsune** [comment]
Additional agenda items:

- #2850 -- Please review the new structure example and give us feedback on it in this GitHub issue by September 5th: https://make.wordpress.org/training/?p=112139&preview=1&_ppp=36e16d2836
  - Open discussions need a follow up place (GitHub, P2 etc)
  - Looking for feedback should also have a follow up place (GitHub, P2 etc)
- [Project Thread: Content Maintenance Process Update Phase 1](https://make.wordpress.org/training/2024/06/28/project-thread-content-maintenance-process-update-phase-1/)
  - [August 21st update](https://make.wordpress.org/training/2024/06/28/project-thread-content-maintenance-process-update-phase-1/#comment-4339)
  - Please vote on Learn WordPress’ north star by August 29th using this survey: https://forms.gle/6NR3iBAkL2z8bieK8
- Other news -- Team rep Destiny will be on parental leave from August 31 - March 2025.

**Comment by ghost** [comment]
Other news- [WCUS 2024 Contributor Day](https://make.wordpress.org/training/2024/08/20/wordcamp-us-2024-contributor-day/)

**Comment by kathrynwp** [comment]
Learn WordPress relaunch update: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4340

**Comment by kathrynwp** [comment]
### Press coverage of the Learn WP launch

On this week's The WordPress Way podcast, Abha Thakor interviews Nick Diego, Laura Adamonis, and Kathryn Presner about the new Learn WordPress site.
https://dothewoo.io/the-refresh-of-learn-wordpress-with-kathryn-presner-nick-diego-and-laura-adamonis/

**Comment by kaitohm** [comment]
https://make.wordpress.org/training/2024/08/28/training-team-meeting-recap-22-august-2024/
