### ISSUE TITLE
Proposal: New Meeting Notes Structure

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#2850]
I've drafted a new meeting note format to help our team streamline our notes going forward.

Please review the new structure example and give us feedback on it in this GitHub issue by September 5th: https://make.wordpress.org/training/?p=112139&preview=1&_ppp=36e16d2836

**Comment by westnz** [comment]
I like the new streamlined structure.

**Comment by jonathanbossenger** [comment]
- In the spirit of trying not to duplicate information, do we need to include the meeting note takers in the meeting notes?
- I appreciate the summary of each of the high level points

**Comment by noruzzamans** [comment]
I really appreciate the new meeting notes format. It's so easy to find the information I need.

**Comment by kaitohm** [comment]
I've made minor adjustments to the pattern, renamed it as "Recap for Training Team Meeting", and deleted the old pattern.
