### ISSUE TITLE
Add Facilitator Notes area to Lessons

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2855]
## Summary

Let's add a new section to individual lessons in Sensei, to house "Facilitator Notes"

### Purpose

The purpose of this section is to provide additional material associated with a lesson, geared to facilitators who would like to use the material to teach others. For example, content creators may include a list of prerequisites, objectives, or learning outcomes. 

### To keep in mind

- This is envisioned as a tab that allows visitors to toggle between the lesson content and the Facilitator Notes.
- The Facilitator Notes content should be compatible with TranslatePress.
- The link to the Facilitator Notes section should **not** appear if there's no content in the Facilitator Notes area.
- This section will be a freeform text area, blank by default.
- The data should be pulled out of a custom field within Sensei, connected to each lesson.

### Populating Facilitator Notes

I've separated this issue from the previous one in #2392, since we don't want to immediately run an automated content migration from Lesson Plans to Facilitator Notes, but instead undertake a more curated, manual survey of what content is currently living in Lesson Plans and what is worthwhile to move into which lesson(s), if any. 

Content creators might also undertake to add certain Facilitator Notes (such as prerequisites, learning outcomes, etc.) to the Learning Pathway courses, in lieu of trying to match up older lesson plans with newer lessons. 

### Where to add the link

Perhaps it could go below or above "Suggestions" in the left sidebar? 

<img width="1440" alt="theme_json_in_Classic_themes___Learn_WordPress" src="https://github.com/user-attachments/assets/c09db3be-321c-4067-a0bc-a7ff23adfe8a">

cc @westnz @jonathanbossenger @Piyopiyo-Kitsune

**Comment by westnz** [comment]
This is a tough one since having the Facilitator Notes in the course's left sidebar might be confusing. Could we explore displaying it directly on the lesson page instead? If we stick with the sidebar option, I suggest placing it below 'Suggestions,' but we'd need to add another Separator block.

**Comment by jonathanbossenger** [comment]
The location of the facilitator notes link should also take into account what happens when the link is clicked. 

Wherever we put the link, if a new learner clicks on it and sees the content, that will cause some confusion. Perhaps placing it somewhere that's not front and center to the learner but can be documented for facilitators?

The first place that comes to mind is the WordPress admin bar.

![learn wordpress org_lesson_wordpress-and-web-servers_](https://github.com/user-attachments/assets/3a24b657-be0e-4fd8-a8ec-97cd5abb944c)

Then, when the link is clicked, the notes slide on from the left of the lesson, as a sticky overlay.

![facilitator-1](https://github.com/user-attachments/assets/5177d98e-cb48-439c-8e7b-fdc5be0c60be)

This does mean it might overlay the lesson content a little on smaller resolutions, but as long as the facilitator can still scroll to see the content, I think that's ok.

![facilitator-2](https://github.com/user-attachments/assets/546cc542-303b-447d-8b98-351e67b936d6)

**Comment by kathrynwp** [comment]
Interesting idea to put it in the admin bar, but I'm concerned that it might be easily overlooked there. Since the Facilitator Notes aren't technically a WordPress/Sensei administrative action, but something visible to all (i.e. not related to editing or otherwise manipulating the lesson on the admin side.) I'm also wondering if it might not make sense to put them up in the admin area.

Looping in @WordPress/meta-design to see what ideas you might have.

**Comment by jasmussen** [comment]
The adminbar should never be visible to someone who isn't logged in. The fact that it is, at present, is a bug that should hopefully be fixed somewhat soon, as part of https://github.com/WordPress/wporg-mu-plugins/issues/647. 

So if facilitator notes are to be visible to someone who isn't logged in, the admin-bar is a non-starter. 

On the flipside, if facilitator notes should be visible _only_ to someone who's logged in, the admin-bar may be an acceptable place.

A link at the bottom of the sidebar could be okay with me. We can even add help-text below the link, which describes in more depth what those notes are about, and who they are for.

**Comment by kathrynwp** [comment]
I just realized that one issue with putting it in the sidebar is that the sidebar is only visible on lessons that are contained inside _published_ courses. Right now, we publish lessons even when the full course hasn't yet gone live (been published). For example, see this lesson in the yet-to-be-published Advanced WP User course:

https://learn.wordpress.org/lesson/why-would-a-wordpress-user-need-to-run-a-local-site/

There's no sidebar because right now it's acting as a "standalone" lesson, without being part of a published course. Down the road, once the Advanced WordPress User course is published, the sidebar will be present.

> So if facilitator notes are to be visible to someone who isn't logged in, the admin-bar is a non-starter.

I think the facilitator notes should probably be available to anyone who is previewing a lesson, even if they haven't registered to take the course. Previews are available even to logged-out users.

@jasmussen Given the above factors, can you think of anywhere else to put the link/tab? Maybe somewhere in this sticky bar, circled here:

<img width="1500" alt="Why_would_a_WordPress_user_need_to_run_a_local_site____Learn_WordPress" src="https://github.com/user-attachments/assets/582d9ed8-e775-47b7-8e8b-6283e9e880c2">

**Comment by jasmussen** [comment]
An older post here included a tab-bar for "instructor notes", I guess that's the same?

https://make.wordpress.org/training/2024/04/29/a-light-learn-lessons-visual-refresh/

Scroll to the bottom.

**Comment by jonathanbossenger** [comment]
Yes, that's it. I had a feeling it was discussed somewhere, but for the life of me, I could not remember where.

**Comment by kathrynwp** [comment]
Thanks, both – yes that's it, and I think it looks great! Copying here:

![instructor-notes](https://github.com/user-attachments/assets/00545000-3eb2-489e-9e6a-7ad7a48a96eb)

Not sure if you had this in mind, but when flipping over to the Facilitator Notes tab, we could keep the left sidebar present, so the facilitator can reference the lessons/modules while reading the notes.

**Comment by kathrynwp** [comment]
@adamwoodnz I think this is ready to go – please let me know if you need anything else for now. Thank you!

**Comment by adamwoodnz** [comment]
~Can we please have a visual for what it would look like when the notes tab is active?~

Edit: I missed this:

> when flipping over to the Facilitator Notes tab, we could keep the left sidebar present, so the facilitator can reference the lessons/modules while reading the notes.

If we keep the sidebar visible I assume that means that if a sidebar link is clicked, a navigation to the lesson or quiz will still occur as usual. When that happens will the instructor notes need to remain active? By default obviously the lesson/quiz content will be shown.

**Comment by jasmussen** [comment]
The idea for the tabs was from @Piyopiyo-Kitsune, it's possible she has additional nuance or detail.

**Comment by kathrynwp** [comment]
> If we keep the sidebar visible I assume that means that if a sidebar link is clicked, a navigation to the lesson or quiz will still occur as usual. When that happens will the instructor notes need to remain active? By default obviously the lesson/quiz content will be shown.

I'd love to hear what Destiny had in mind. From my POV, I think it makes sense to view the lesson whenever it's clicked in the sidebar (even if a visitor had the Facilitator Notes panel open) so that people can refer back and forth between the Facilitator Notes area and a particular lesson's content.

**Comment by jasmussen** [comment]
Another option is to just have a Details block at the bottom of all the sidebars in the course. Or even at the top. Not sure if we can cookie that to be open or closed, but essentially this:

<details><summary>Instructor notes</summary>

Tada! Here's an instructor note.

</details>

**Comment by kathrynwp** [comment]
@jasmussen Thank you so much for that alternative idea! 

I see two potential issues with this, but wonder what you think:
- limiting the lesson notes to the width of the sidebar might make them really hard to read. (See an example of a [lesson plan](https://learn.wordpress.org/lesson-plan/create-a-basic-child-theme-for-block-themes/) that might be ported over into the new Facilitator Notes section.)
- some lessons are full-width (sidebar-less), such as all the ones published before the course that they're part of is launched – see the one I mentioned earlier for an example: https://learn.wordpress.org/lesson/why-would-a-wordpress-user-need-to-run-a-local-site/

**Comment by jonathanbossenger** [comment]
Deleted my comment because I see @fcoveram has a revamped lesson flow proposal.

**Comment by kathrynwp** [comment]
Just wanted to note for anyone coming across this that discussion around the design of the Facilitator Notes area is now happening here:

https://github.com/WordPress/Learn/issues/2869

**Comment by kaitohm** [comment]
Closing in favor of #2869
