### ISSUE TITLE
If course hasn't launched yet, course links from lesson cards give a 404 

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/Learn#2856]
## Summary

Content creators currently publish lessons even before the full course that they're part of has gone live. This allows learners to access single lessons without needing to wait until the whole course is available. 

## Issue

Now that the course name is linked from individual lesson cards on archive pages, if a lesson card links out to a course that hasn't yet been published, the user gets a 404 page. An example is the Advanced WordPress User course, which hasn't yet launched.

## To replicate

1. Go to https://learn.wordpress.org/lessons/ in an incognito window.
2. Click on "[Advanced WordPress User](https://learn.wordpress.org/?post_type=course&p=257841)" on any lesson card, such as:

<img width="1223" alt="Lessons___Learn_WordPress" src="https://github.com/user-attachments/assets/432a1b3b-fe6d-4ee2-bfb4-d477574b5b03">

## Result 

404 not found.

## Possible solutions

- Don't display course name on lesson cards until a course is launched, or
- Don't publish lessons until course is launched (not ideal as some courses take a while to launch, as they consist of many lessons)

Any other potential solutions?

cc @westnz @jonathanbossenger

**Comment by westnz** [comment]
I would choose this solution: Don't display the course name on lesson cards until a course is launched.

**Comment by westnz** [comment]
I would suggest, "Don't display course name on lesson cards until a course is launched."
