### ISSUE TITLE
Feedback - How to create an animated timeline plugin

### ISSUE THREAD

**Issue by iambherulal** [WordPress/Learn#2858]
## Type of feedback

//content

## Description

I was following a tutorial and noticed an issue with the filename. It's not a typo, but rather a character issue. In the tutorial, a double dash in the filename is mistakenly shown as a single dash, while the code snippet still uses the double dash. When someone copies and pastes the filename, it causes a mismatch.

## Step-by-step reproduction instructions (optional)

Please list the steps needed to reproduce or verify the feedback. For example:
1. Go to - https://developer.wordpress.org/news/2024/06/13/how-to-create-an-animated-timeline-plugin/#animated-timeline-plugin-setup
2. In this section you can see the CSS and js files with the full path name, In the filename after the group there should a double dash.
    - /assets/scripts/core-blocks/group–animated-timeline.js -> assets/scripts/core-blocks/group--animated-timeline.js
    - /assets/styles/core-blocks/group–animated-timeline.css -> /assets/styles/core-blocks/group--animated-timeline.css
3. As you can see in the snippet - https://developer.wordpress.org/news/2024/06/13/how-to-create-an-animated-timeline-plugin/#register-custom-css-and-javascript-files

**Comment by jonathanbossenger** [comment]
Hello @iambherulal thanks for sharing your feedback.

The content you are sharing feedback on is part of the WordPress developer blog. That team manages their content and any feedback in a different repository, which you can find here: https://github.com/WordPress/developer-blog-content/

It would be best if you posted your feedback there.

This repository is for any content available on https://learn.wordpress.org/, so I am going to close this issue.
