### ISSUE TITLE
Feedback -Dead link on WordPress Beginner Developer course

### ISSUE THREAD

**Issue by nagpai** [WordPress/Learn#2859]
Thank you so much for the awesome course! I spotted a minor issue that I thought would be good to report.

## Type of feedback
There is a broken link on the [Custom Post types](https://learn.wordpress.org/lesson/custom-post-types/) section of the WordPress Beginner Developer course

## Description
The link to the text `Creating Tables with Plugins` leads to a link that seems broken - https://developer.wordpress.org/plugins/plugin-basics/creating-tables-with-plugins/

**Comment by jonathanbossenger** [comment]
Thank you @nagpai for reporting this, I'll be looking into what happened to that link.

**Comment by jonathanbossenger** [comment]
The missing page has been fixed, so the link now works.
