### ISSUE TITLE
Meeting Agenda August 29, 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2863]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @lada7042 ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- August 29 - [Marar Rithika](https://profiles.wordpress.org/rithika3/)
- Sept. 5- [Nishita Joshi](https://profiles.wordpress.org/nishitajoshi/) 
- Sept. 12- [Raj Chauhan](https://profiles.wordpress.org/chauhanraj754/)
- Sept. 19-  looking for a volunteer

**2. Looking for feedback**

- Today is the last day!! 
Vote [here](https://docs.google.com/forms/d/e/1FAIpQLSddQEVzVeGKrP2iWWr98ZgwNqPca4Ed2DrOKV0lLzh-CfUPhw/viewform)
   - Vote for the Learn WordPress North Star. Thank you for your feedback. The team reps narrowed it down to 3 options. Please vote 1, 2, or 3 in the thread :thread: for the one you feel best conveys Learn WordPress’ purpose. Why we are part of this team?
     - Learn WordPress makes WordPress knowledge accessible to all by empowering individuals around the world to create, contribute, and grow within the WordPress ecosystem.
     - To make WordPress knowledge accessible to all through Learn WordPress, empowering everyone to create, contribute, and grow within the WordPress ecosystem.
     - Learn WordPress is the source for the most up-to-date educational content on WordPress for Users, Developers, and Designers of WordPress.
 ⭐⭐⭐ Results will be posted August 30. ⭐⭐⭐
- [Proposal: New Meeting Notes Structure #2850](https://github.com/WordPress/Learn/issues/2850) -- Please review the new structure example and give us feedback on it in this GitHub issue by **September 5th**: You can see a preview of the new notes here:  https://make.wordpress.org/training/?p=112139&preview=1&_ppp=36e16d2836
- Drawing new learners to the new Learn.WordPress.org - Feedback wanted by Sept. 10
Now that the new [Learn WordPress](https://learn.wordpress.org/) is [out in the world](https://make.wordpress.org/training/2024/08/02/meet-the-new-learn-wordpress/), we want to have a steady flow of new learners discovering the site and taking advantage of the valuable resources it offers. This post is intended to gather ideas on which recurring activities the team should prioritize first, with the goal of bringing more learners to the site. Please have a look and provide your feedback by **September 10, 2024**:
https://make.wordpress.org/training/2024/08/28/drawing-new-learners-to-the-new-learn-wordpress-org/

**3. Looking for volunteers**

- Would you like to learn how to run the weekly meeting and be host September 19? Please reply in thread. 🧵 
   - Laura will reach out to set up a meeting. 
- Call for testing: Playground block on Learn WordPress
    - Thanks to the work of [@alexstine](https://github.com/alexstine) and [@brandonpayton](https://github.com/brandonpayton), we have been testing and fixing a11y issues in the Playground block on Learn WordPress. All of the outstanding issues have now been fixed, so we’d like to ask other a11y experts to help us test.
    - You can find more details on this testing issue: [Test Playground Block on Learn WordPress. #2352](https://github.com/WordPress/Learn/issues/2352)

**4. Updates from last week's dev-squad triage session**

- Please add any updates from the last meeting in the thread. 🧵 
- The calendar for when these meetings occur has also been updated on our Training Team site welcome box, so please be mindful that the dev squad meets biweekly (every other week) on Thursdays [07:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?hour=07&min=00&sec=0). You can [view our scheduled meetings in this calendar](https://make.wordpress.org/meetings/#training).

**5. Other news**

- item 1
- item 2

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 1 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 30 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 4 issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have 0 issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Contributors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 20 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: 
Congratulations to [Muhibul Haque](https://profiles.wordpress.org/devmuhib/)](https://profiles.wordpress.org/devmuhib/) on receiving the training team badge!! 🎆 
- Props: 

## 4. Project updates

- Learn WP Update
Project update: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4344
- Project_2
  - details

## 5. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kathrynwp** [comment]
### Content Maintenance Plan

Over the next two weeks, please add your thoughts on this question on the post linked below:

> What is Learn WordPress’s north star and content commitments?

> - For example, we have the [WordPress Codex](https://codex.wordpress.org/), [Documentation](https://wordpress.org/documentation/), and [Developer handbook](https://developer.wordpress.org/) sites which contain plenty of out of date content for those not on the most recent versions of WordPress. Do we really feel it’s necessary to duplicate this content further on Learn WordPress?
> - Is Learn WordPress the site where folks come to about the most relevant and up to date content on WordPress? Is it the place where we encourage and guide folks to be at the forefront of the software?

We also need a couple of folks to help move along this project. Who's interested in helping guide a plan for ongoing content maintenance for Learn WordPress? If you're looking for a way to get more involved with the Training Team, this might be it!

https://make.wordpress.org/training/2024/06/28/project-thread-content-maintenance-process-update-phase-1/ 

EDIT: Going to hold off on this, pending results of the current North Star survey question.

**Comment by kathrynwp** [comment]
### Learn WP Update

Project update: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4344

**Comment by kathrynwp** [comment]
### Drawing new learners to the new Learn.WordPress.org - Feedback wanted by Sept. 10

Now that the new [Learn WordPress](https://learn.wordpress.org/) is [out in the world](https://make.wordpress.org/training/2024/08/02/meet-the-new-learn-wordpress/), we want to have a steady flow of new learners discovering the site and taking advantage of the valuable resources it offers. This post is intended to gather ideas on which recurring activities the team should prioritize first, with the goal of bringing more learners to the site. Please have a look and provide your feedback by September 10, 2024:
https://make.wordpress.org/training/2024/08/28/drawing-new-learners-to-the-new-learn-wordpress-org/

**Comment by rithikamarar3** [comment]
Meeting recap post published : https://make.wordpress.org/training/2024/09/04/training-team-meeting-recap-29-august-2024/
