### ISSUE TITLE
Online Workshop: Submitting an enhancement to the WordPress Playground Block

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2870]
# Details

- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Online Workshop
- Content title: Submitting an enhancement to the WordPress Playground Block
- Topic description: The [WordPress Playground block](https://wordpress.org/plugins/interactive-code-block/) is a way to load an instance of WordPress Playground inside your WordPress site. It includes an interactive code editor, that currently only supports plugins. Over the course of the next few live streams, I will be working on submitting a PR so that it can also support themes.
- Audience (User, Developer, Designer, Contributor, etc.): Developer
- Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate

# Learning Objectives

- Setting up the playground tools code repository for local development
- Creating the PR to add the enhancement and submitting it for review
# Related Resources and Other Notes
- https://wordpress.org/plugins/interactive-code-block/
- https://github.com/WordPress/playground-tools/issues/351
- https://github.com/WordPress/playground-tools

### Automation Code

//online-workshop

**Comment by jonathanbossenger** [comment]
wp.tv: https://wordpress.tv/2024/09/06/submitting-an-enhancement-to-the-wordpress-playground-block/
youtube: https://www.youtube.com/watch?v=ec4GxqnxbXE

**Comment by jonathanbossenger** [comment]
## Online Workshop Details
- Date: 19 September 2024
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/303332585
- Co-host: N/A

## Online Workshop Development Checklist
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by Soir7** [comment]
Hi @jonathanbossenger,

I would be happy to co-host on Thursday!  This will be my first time co-hosting.  Is there a 'script/outline' I would follow?

I appreciate some type of 'walk through'.

Thanks!

Eileen

**Comment by jonathanbossenger** [comment]
Hello @Soir7, thanks for the offer to co-host.

I usually don't have a co-host for a live stream. It's slightly different format to a regular online workshop, and so there's no real need for someone to co-host.

**Comment by jonathanbossenger** [comment]
WP.tv: https://wordpress.tv/2024/10/05/wordpress-playground-block-code-editor-theme-support/

**Comment by jonathanbossenger** [comment]
YouTube: https://youtu.be/LAM6ps-jOwM
