### ISSUE TITLE
Meeting Agenda September 5, 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2872]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @lada7042 ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- Sept. 5- [Nishita Joshi](https://profiles.wordpress.org/nishitajoshi/)
- Sept. 12- [Raj Chauhan](https://profiles.wordpress.org/chauhanraj754/)
- Sept. 19- [noruzzaman](https://profiles.wordpress.org/noruzzaman/)
- Sept 26- looking for a volunteer

**2. Looking for feedback**

- ➡️ https://github.com/WordPress/Learn/issues/2850 -- Please review the new structure example and give us feedback on it in this GitHub issue by September 5th: You can see a preview of the new notes here: https://make.wordpress.org/training/?p=112139&preview=1&_ppp=36e16d2836
- ➡️ Drawing new learners to the new Learn.WordPress.org - Feedback wanted by Sept. 10
Now that the new [Learn WordPress](https://learn.wordpress.org/) is [out in the world](https://make.wordpress.org/training/2024/08/02/meet-the-new-learn-wordpress/), we want to have a steady flow of new learners discovering the site and taking advantage of the valuable resources it offers. This post is intended to gather ideas on which recurring activities the team should prioritize first, with the goal of bringing more learners to the site. Please have a look and provide your feedback by September 10, 2024:
https://make.wordpress.org/training/2024/08/28/drawing-new-learners-to-the-new-learn-wordpress-org/
- Re-evaluating the SME role
While making handbook pages during the process of retiring the Faculty Program, it came up during discussions with the team reps and content creators that we probably no longer need a separate role for [Subject Matter Expert (SME)](https://make.wordpress.org/training/handbook/getting-started/subject-matter-expert-onboarding/).

Perhaps we could combine the SME role with the [Editor role](https://make.wordpress.org/training/handbook/getting-started/editor-onboarding/)?

Since we're going to now try using the [GitHub Learn team](https://github.com/orgs/WordPress/teams/learn-editors) for reviews ([reference](https://make.wordpress.org/training/2024/07/02/project-thread-retiring-the-faculty-program/#comment-4349)), this single GitHub team could be pinged for feedback on GitHub issues, instead of the previous two separate groups.

Please provide feedback by Sept. 20.

**3. Looking for volunteers**
- Call for Contributors: Become an Online Workshop Host
Are you passionate about WordPress and helping others? The Training Team is seeking contributors to host [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)! Share your expertise, connect with a global audience, and make an impact. Host a live workshop in your preferred language and timezone, engage with attendees, and give back to the community. Expand your network while helping others improve their WordPress skills. [Apply to facilitate](https://learn.wordpress.org/online-workshops/apply-to-facilitate/) - we’re excited to work with you!
-
- item 2

**4. Updates from last week's dev-squad triage session**

Present, Jamie Madden (@digitalchild), Elliot Richmond (@erichmond), Jonathan (@psykro), Rico (@rfluethi)

No new PRs to triage
We do have a couple of open PRs that could do with a review, to confirm if they are still valid: https://github.com/WordPress/Learn/pulls?q=is%3Aopen+is%3Apr+label%3A%22%5BDev%5D+Needs+Review%22
One https://github.com/WordPress/Learn/issues/2852, and subsequently closed
We also discussed the list of [open issues from the Learning Pathway project](https://github.com/orgs/WordPress/projects/40/views/27?filterQuery=project%3ALearn+milestone%3A%22Learning+Pathways+Post-launch%22+priority%3AHigh%2CMedium) that could do with some help to get them over the line, and are calling on all interested developers to get involved.

The calendar for when these meetings occur has also been updated on our Training Team site welcome box, so please be mindful that the dev squad meets biweekly (every other week) on Thursdays [07:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?hour=07&min=00&sec=0). You can [view our scheduled meetings in this calendar](https://make.wordpress.org/meetings/#training).

**5. Other news**

- Jonathan and Wes will each run a Content creator coffee hour in their respective time zones. This is space for anyone creating content for Learn WordPress to meet and chat about content creation.

Jonathan – 10 September 2024 @ 13:00 UTC ([Zoom link](https://href.li/?https://us02web.zoom.us/j/81739311998?pwd=J0O7wbhiEgHEwsuoHGqXxBKhYj4n0M.1))
Wes – 24 September 2024 @ 21:00 UTC ([Zoom link](https://href.li/?https://us02web.zoom.us/j/84225598678?pwd=feCHH0N1f4aaeHjzEdborENa2hx55Y.1))
Details for both calls are in the [Training team calendar](https://make.wordpress.org/meetings/#training)
- [WP Tavern](https://wptavern.com/wordpress-training-team-seeks-ideas-to-attract-new-learners) covered our request for feedback on proposed ideas to draw new learners to Learn WP.
- Faculty Program retirement
With the [final step of deleting a half-dozen saved replies in Help Scout](https://make.wordpress.org/training/2024/07/02/project-thread-retiring-the-faculty-program/#comment-4354), the Faculty Program retirement plan is now complete!

This was a very manual process, so if anyone notices any lingering references to the Faculty Program, please ping the @tt-admins group in the [#training channel](https://wordpress.slack.com/archives/C02RW657Q) Slack so we can make the necessary updates.
- [WordCamp US Contributor Day Online Event](https://www.meetup.com/learn-wordpress-online-workshops/events/303117891/?eventOrigin=group_events_list)

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 2 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 27 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 4 issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have 0 issues requiring development
➡️ **Highlight** 
**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Contributors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 20 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: awarded at the last meeting of the month. Please fill out applications prior to the last Monday of the month so the team reps can review at their meeting. You must meet [Team badge requirements](https://make.wordpress.org/training/handbook/about/team-profile-badges/)
- Props: 

## 4. Project updates

- Learning Pathways Update
Project update: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4344
- Project_2
  - details

## 5. Contributor Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other contributor or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
## Content creator coffee hour

Jonathan and Wes will each run a Content creator coffee hour in their respective time zones. This is space for anyone creating content for Learn WordPress to meet and chat about content creation.

- Jonathan – 10 September 2024 @ 13:00 UTC ([Zoom link](https://href.li/?https://us02web.zoom.us/j/81739311998?pwd=J0O7wbhiEgHEwsuoHGqXxBKhYj4n0M.1))
- Wes – 24 September 2024 @ 21:00 UTC ([Zoom link](https://href.li/?https://us02web.zoom.us/j/84225598678?pwd=feCHH0N1f4aaeHjzEdborENa2hx55Y.1))

Details for both calls are in the [Training team calendar](https://make.wordpress.org/meetings/#training)

**Comment by jonathanbossenger** [comment]
## Updates from last week's dev-squad triage session

Present, Jamie Madden (@digitalchild), Elliot Richmond (@erichmond), Jonathan (@psykro), Rico (@rfluethi)

- No new PRs to triage
- We do have a couple of open PRs that could do with a review, to confirm if they are still valid: https://github.com/WordPress/Learn/pulls?q=is%3Aopen+is%3Apr+label%3A%22%5BDev%5D+Needs+Review%22
- One [new bug triaged](https://github.com/WordPress/Learn/issues/2852), and subsequently closed
- We also discussed the list of [open issues from the Learning Pathway project](https://github.com/orgs/WordPress/projects/40/views/27?filterQuery=project%3ALearn+milestone%3A%22Learning+Pathways+Post-launch%22+priority%3AHigh%2CMedium) that could do with some help to get them over the line, and are calling on all interested developers to get involved.

**Comment by kathrynwp** [comment]
## Faculty Program retirement

With the [final step of deleting a half-dozen saved replies in Help Scout](https://make.wordpress.org/training/2024/07/02/project-thread-retiring-the-faculty-program/#comment-4354), the Faculty Program retirement plan is now complete! 

This was a very manual process, so if anyone notices any lingering references to the Faculty Program, please ping the `@tt-admins` group in the [#training channel](https://wordpress.slack.com/archives/C02RW657Q) Slack so we can make the necessary updates.

**Comment by kathrynwp** [comment]
## Re-evaluating the SME role 

While making handbook pages during the process of retiring the Faculty Program, it came up during discussions with the team reps and content creators that we probably no longer need a separate role for [Subject Matter Expert (SME)](https://make.wordpress.org/training/handbook/getting-started/subject-matter-expert-onboarding/).

Perhaps we could combine the SME role with the [Editor role](https://make.wordpress.org/training/handbook/getting-started/editor-onboarding/)? 

Since we're going to now try using the [GitHub Learn team](https://github.com/orgs/WordPress/teams/learn-editors) for reviews ([reference](https://make.wordpress.org/training/2024/07/02/project-thread-retiring-the-faculty-program/#comment-4349)), this single GitHub team could be pinged for feedback on GitHub issues, instead of the previous two separate groups. 

Please provide feedback by Sept. 20.

**Comment by kathrynwp** [comment]
## Share your thoughts on how to draw new learners to Learn WordPress

[WP Tavern](https://wptavern.com/wordpress-training-team-seeks-ideas-to-attract-new-learners) covered our request for feedback on proposed ideas to draw new learners to Learn WP. 

[Please share your thoughts before the Sept. 10 deadline.](https://make.wordpress.org/training/2024/08/28/drawing-new-learners-to-the-new-learn-wordpress-org/)

**Comment by westnz** [comment]
## Call for Contributors: Become an Online Workshop Host

Are you passionate about WordPress and helping others? The Training Team is seeking contributors to host [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)! Share your expertise, connect with a global audience, and make an impact. Host a live workshop in your preferred language and timezone, engage with attendees, and give back to the community. Expand your network while helping others improve their WordPress skills. [Apply to facilitate](https://learn.wordpress.org/online-workshops/apply-to-facilitate/) - we’re excited to work with you!

**Comment by ghost** [comment]
meeting started on Slack- https://wordpress.slack.com/archives/C02RW657Q/p1725494485071629

**Comment by kaitohm** [comment]
https://make.wordpress.org/training/2024/09/12/training-team-meeting-recap-05-september-2024/
