### ISSUE TITLE
Meeting Agenda September 12, 2024

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2880]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by MEETING_HOST._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- Sept. 12 - [Raj Chauhan](https://profiles.wordpress.org/chauhanraj754/)
- Sept. 19 - [noruzzaman](https://profiles.wordpress.org/noruzzaman/)
- Sept 26 - looking for a volunteer
- Oct 3 - looking for volunteer

**2. Looking for feedback**

- Drawing new learners to the new Learn WordPress site
Please share your feedback on which idea we should start with first, to attract new learners to Learn WordPress. Deadline extended until Sept. 24. Big thanks to those who have shared their thoughts already, your input is appreciated!

https://make.wordpress.org/training/2024/08/28/drawing-new-learners-to-the-new-learn-wordpress-org/

**3. Looking for volunteers**

- Call for Contributors: Become an Online Workshop Host
Are you passionate about WordPress and helping others? The Training Team is seeking contributors to host [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)! Share your expertise, connect with a global audience, and make an impact. Host a live workshop in your preferred language and time zone, engage with attendees, and give back to the community. Expand your network while helping others improve their WordPress skills. [Apply to facilitate](https://learn.wordpress.org/online-workshops/apply-to-facilitate/) - we’re excited to work with you!

**4. Updates from last week's dev-squad triage session**

No meeting this week 

**5. Other news**

- WCUS Contributor Day Online

Join the Training Team online next week (Sept. 17, 16:00 UTC) during WordCamp US Contributor Day by signing up for the Online Workshop edition. Whether you're a new to the Training Team or an experienced contributor, everyone is welcome to spend an hour taking part in team activities.

https://www.meetup.com/learn-wordpress-online-workshops/events/303117891/

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 0 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 27 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 4 issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have 0 issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Contributors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 20 issues awaiting a fix

## 3. Contribution Acknowledgement

- Props: 

## 4. Project updates

- Project_1
  - details
- Project_2
  - details

## 5. Contributor Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other contributor or Training Team members help you in some way?

## 6. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kathrynwp** [comment]
## WCUS Contributor Day Online

Join the Training Team online next week (Sept. 17, 16:00 UTC) during WordCamp US Contributor Day by signing up for the Online Workshop edition. Whether you're a new to the Training Team or an experienced contributor, everyone is welcome to spend an hour taking part in team activities.

https://www.meetup.com/learn-wordpress-online-workshops/events/303117891/

**Comment by kathrynwp** [comment]
## Drawing new learners to the new Learn WordPress site

Please share your feedback on which idea we should start with first, to attract new learners to Learn WordPress. Deadline extended until Sept. 24. Big thanks to those who have shared their thoughts already, your input is appreciated!

https://make.wordpress.org/training/2024/08/28/drawing-new-learners-to-the-new-learn-wordpress-org/

**Comment by chauhanraj754** [comment]
Meeting recap post published: https://make.wordpress.org/training/2024/09/19/training-team-meeting-recap-12-september-2024/
