### ISSUE TITLE
Feedback - Remove automatically generated development files.

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#2883]
Every time I run `yarn run create` to set up the local development environment, I am presented with the following messages

```
/Users/jonathanbossenger/development/projects/learn.wordpress.org/.eslintrc.js already exists. Overwrite? [y/N] y
Copying .eslintrc.js to /Users/jonathanbossenger/development/projects/learn.wordpress.org/.eslintrc.js... Done.

/Users/jonathanbossenger/development/projects/learn.wordpress.org/.prettierrc.js already exists. Overwrite? [y/N] y
Copying .prettierrc.js to /Users/jonathanbossenger/development/projects/learn.wordpress.org/.prettierrc.js... Done.

/Users/jonathanbossenger/development/projects/learn.wordpress.org/.stylelintrc already exists. Overwrite? [y/N] y
Copying .stylelintrc to /Users/jonathanbossenger/development/projects/learn.wordpress.org/.stylelintrc... Done.

/Users/jonathanbossenger/development/projects/learn.wordpress.org/phpcs.xml.dist already exists. Overwrite? [y/N] y
Copying phpcs.xml.dist to /Users/jonathanbossenger/development/projects/learn.wordpress.org/phpcs.xml.dist... Done.
```

If these files are being created every time, can they be removed from source control?

**Comment by jonathanbossenger** [comment]
@adamwoodnz not sure if I'm missing something here.

**Comment by adamwoodnz** [comment]
The intended use  of `yarn run create` is for initial setup, and it isn't expected to be run again. These files don't exist in source control and are copied in from a shared repo, for consistency of the developer experience across the .org themes and plugins. Learn has a customised `phpcs.xml.dist` so it is an exception and is committed.

To simply start the environment and not re-run setup tasks you can run `yarn wp-env start`. I see the readme has no mention of that, would updating it help the situation?

**Comment by jonathanbossenger** [comment]
Aha, thanks, I wasn't aware of that. I'll add an update to the readme.
