### ISSUE TITLE
Meeting Agenda September 19, 2024 

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2886]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by Wes Theron._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- Sept. 19 - [noruzzaman](https://profiles.wordpress.org/noruzzaman/)
- Sept 26 - looking for a volunteer
- Oct 3 - looking for volunteer
- Oct 10 - looking for volunteer

Thank you to [noruzzaman](https://profiles.wordpress.org/noruzzaman/) or being our note taker this week.

**2. Looking for feedback**

- Comment on WordPress Contribution Health Dashboards: An Experiment

https://make.wordpress.org/project/2024/09/12/wordpress-contribution-health-dashboards-an-experiment/

- Drawing new learners to the new Learn WordPress site
Please share your feedback on which idea we should start with first, to attract new learners to Learn WordPress. Deadline extended until Sept. 24. Big thanks to those who have shared their thoughts already, your input is appreciated!

https://make.wordpress.org/training/2024/08/28/drawing-new-learners-to-the-new-learn-wordpress-org/

- Designer learning pathway outline 
Are you a designer? We would love your input on the [draft Designer learning pathway outline](https://docs.google.com/document/d/1u0WHj1_D2nlJDJ5-CveJVplcGSDb5QH07Wt_YFtQ1G8/edit). The aim is to start creating content for the Beginner pathway by the end of this month. 

**3. Looking for volunteers**

- Call for Contributors: Become an Online Workshop Host
Are you passionate about WordPress and helping others? The Training Team is seeking contributors to host [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)! Share your expertise, connect with a global audience, and make an impact. Host a live workshop in your preferred language and time zone, engage with attendees, and give back to the community. Expand your network while helping others improve their WordPress skills. [Apply to facilitate](https://learn.wordpress.org/online-workshops/apply-to-facilitate/) - we’re excited to work with you!

**4. Dev-squad triage session**

The next dev-squad triage session will be held Thursday, September 19, 07:00 UTC
Location: [#meta-learn](https://wordpress.slack.com/app_redirect?channel=meta-learn)
These bi-weekly sessions are where we triage any open PRs or new bugs opened on the Learn WordPress GitHub repository. 

Please share any updates from the previous session in this thread.

**5. Other news**

- Tour the New Learn WordPress

https://www.meetup.com/learn-wordpress-online-workshops/events/303117891/](https://wordpress.org/news/2024/09/tour-the-new-learn-wordpress/)

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 6 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 20 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 4 issues that require vetting

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Contributors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 22 issues awaiting a fix

## 3. Contribution Acknowledgement

- Props: 

## 4. Project updates

- Project_1
  - details
- Project_2
  - details

## 5. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by westnz** [comment]
Hey @jonathanbossenger 
Any updates from last week's dev-squad triage session?

**Comment by ghost** [comment]
Slack meeting start- https://wordpress.slack.com/archives/C02RW657Q/p1726704033549259

**Comment by ghost** [comment]
meeting recap- https://make.wordpress.org/training/2024/09/24/training-team-meeting-recap-19th-september-2024/
