### ISSUE TITLE
French translation for Tutorial "How to start using WordPress Playground"

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Learn#2887]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/how-to-start-using-wordpress-playground/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/1583
- Language you'll be translating to: french
- Have you arranged for someone to review this translation?: No
- Reviewer's GitHub username: beryl-dlg
- Other info: https://mypads2.framapad.org/mypads/?/mypads/group/learn-gd35829fb/pad/view/how-to-start-using-wordpress-playground-e423q79hx

**Comment by beryl-dlg** [comment]
Reviewed, thanks @jennydupuy

**Comment by jennydupuy** [comment]
Thanks @beryl-dlg 
This tutorial is now published: https://learn.wordpress.org/tutorial/fr-how-to-start-using-wordpress-playground/
