### ISSUE TITLE
Learning Pathway: Beginner Designer

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2889]
## Production status

**24/24 lessons published (100%)**

<br />

## Module 1

Objective: Introduction to designing with WordPress

### Lessons
- [x] #2890
- [x] #2891
- [x] #2892
- [x] #2893

## Module 2

Objective: Getting to know WordPress
### Lessons
- [x] #2894
- [x] #696
- [x] #694 

## Module 3

Objective: Web design best practices
### Lessons
- [x] #2895
- [x] #2896
- [x] #2201 

 ## Module 4

Objective: Customizing themes and templates
### Lessons
- [x] #706
- [x] #456 
- [x] #2255
- [x] #455 
- [x] #1462 
- [x] #2897

 ## Module 5

Objective: Layout composition 
### Lessons
- [x] #2898
- [x] #2899
- [x] #1419
- [x] #1192 

## Module 6

Objective: Working with media blocks
### Lessons
- [x] #3039
- [x] #2908
- [x] #913 
- [x] #2909

Draft [learning pathway outline](https://docs.google.com/document/d/1u0WHj1_D2nlJDJ5-CveJVplcGSDb5QH07Wt_YFtQ1G8/edit).

**Comment by westnz** [comment]
Let's use this on the intro page: https://www.youtube.com/watch?v=FcTLMTyD2DU

**Comment by Flickimp** [comment]
Happy to contribute Voice Recordings when needed.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/course/beginner-wordpress-designer/

**Comment by westnz** [comment]
//published
