### ISSUE TITLE
Overview of WordPress block theme terms and hierarchy

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2892]
Lesson: Introduction to Terminology and Theme Hierarchy  (smallest to largest)
**Architecture**

- Posts versus pages

**Design (conceptual understanding)** 

- Blocks
- Patterns
- Template Parts
- Template
- Theme

//lesson

**Comment by westnz** [comment]
Here is the completed [script](https://docs.google.com/document/d/1yl8SezB8xi2elRXCRVFZi2auX0OC2xOdPEDxF1dy8dE/edit#heading=h.gov4cepih39w).

Technical review: Joen
Editor: @Soir7

**Comment by westnz** [comment]
Technical review: Joen
Grammatical review: @Soir7

**Comment by Flickimp** [comment]
Happy to record the Voiceover.

**Comment by westnz** [comment]
Thank you, @Flickimp 👍

**Comment by ervanyuff** [comment]
Hi team, I would like to be involved in editing this video 📹

**Comment by westnz** [comment]
Many thanks @ervanyuff

**Comment by westnz** [comment]
Ervan, I have shared all the assets via Gmail. Once you receive the voice recording, you can start compiling and editing.

Thank you all for collaborating on this video.

**Comment by Flickimp** [comment]
@ervanyuff @westnz The Audio is a MP3, that I can't add here. Download from here (available until October 5th).

Download from here: [https://we.tl/t-R3iOEglLet](https://we.tl/t-R3iOEglLet)

**Comment by westnz** [comment]
Thank you very much @Flickimp!

**Comment by ervanyuff** [comment]
Hi team, here is the [Overview of WordPress block theme terms and hierarchy video](https://drive.google.com/file/d/1Q0dY-x3_kCF6lUfAaWsD0UllCtWl0ru-/view?usp=sharing). Please let me know if there any feedback. Thank you 🙏

**Comment by kaitohm** [comment]
//review

**Comment by westnz** [comment]
Review:
- 0:00 - 0:07 Can we re-record the title of the lesson at a faster pace, and you can cut out 'Lesson'
- 0:22 - 0:25 Remove this section as it was merely the heading in the script. We don't have to include it the narration.
- 0:33  The slide should read 'Posts', not 'Post
- 0:54 -1:00 Can we re-record "Posts, on the other hand, are dynamic, chronological content typically used for blogs or news updates."
- 0:56 - 0:57 The transition is off, please improve
- 4:05 -4:06 The screen jumps
- 4:33 - 4:40 The video doesn't work here as the person is working on a completely different platform. Just add a static screenshot of the hierarchy pyramid you used earlier in the video.

Good work, folks!! ⭐

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.  

*****  

Looks like much of what @westnz has listed above, remain in the video.  

Only 2 things I would suggest:  

- at 1:34 it might be helpful to use a different graphic that visualizes the hierarchy on a page/post. Or maybe edit the labels to use the hierarchy terminology. 

- at 2:55 where "Templates" is defined, perhaps add "...different page and post types..." 

That's it - Good job!

**Comment by digitalchild** [comment]
This is a nice and clear overview, I only have one observation. 

In the comparison of posts vs pages, you say pages are static while posts are dynamic. I would say that posts are time based, while pages aren't. 

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by westnz** [comment]
Thank you for the reviews!!

**Comment by westnz** [comment]
Hey @ervanyuff, we can go ahead and make the necessary updates/changes.

I have asked @Flickimp to re-record these sentences:
- 0:00 - 0:07 Can we re-record the title of the lesson at a faster pace, and you can cut out ‘Lesson’. Can you read "In this lesson, we'll provide an overview of WordPress block theme terms and hierarchy."
- 0:54 -1:00 Can we re-record “Posts on the other hand are dynamic content typically used for blogs or news updates. Posts are time-based entries displayed in reverse chronological order, so the newest posts appear first." (updated this section)
- 2:55 Please re-record "On the other hand, templates define the overall structure of different page and post types on your WordPress site." (updated this sentence)

**Comment by Flickimp** [comment]
Updated Audio is here: https://we.tl/t-as3kPJ3W7J
[https://we.tl/t-as3kPJ3W7J](url)

**Comment by ervanyuff** [comment]
Hi team, here's [the updated video](https://drive.google.com/file/d/1mOvAC_5uPKKwufS1e0_h9zQRmpS1laSN/view?usp=sharing). Please let me know if there's anything I've missed 🙏

**Comment by westnz** [comment]
Looks great, I will publish this lesson tomorrow. Thanks, Team!

**Comment by westnz** [comment]
//published
