### ISSUE TITLE
Designing with a block-first mindset

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2893]
Lesson: Block composition: think about designing in a block-first way.

- Become a competent block composer.

- Think about your site as a modular system: reusing design components. Example: Featured item, Newsletter signup, Query Loop

//lesson

**Comment by westnz** [comment]
Completed [script](https://docs.google.com/document/d/1m3j7W4cBJImFVdCxfzP9wDmPN8ku4BGD_wlDJmxelEs/edit).

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/f7ed1ec1-3ff0-4c35-aae2-ba1222f90324

**Comment by digitalchild** [comment]
A good overview of what block first design can be. When you mention patterns, you don't explain what a pattern is. You might want to mention that we have other lessons on what patterns are. You also don't explain what stack on mobile means, it is implied with responsive design. Might be a good idea to outline what that is. The lesson ends without an outro. 

## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [ ] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

**Comment by westnz** [comment]
//published
