### ISSUE TITLE
Finding a block theme for your design needs

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2894]
Lesson: Finding, selecting, and activating a block theme for your needs

- Selecting the most appropriate theme 
- Explain the concept of starting with a similar theme and configuring it from there.

//lesson

**Comment by westnz** [comment]
Here is the [script](https://docs.google.com/document/d/1WLlQIwdbenxj6NjphxpP58gy56OfSrxgdRp1e4adBko/edit).

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/6c30a546-4e99-4d8f-bc18-a023a4048edc

**Comment by kaitohm** [comment]
//review

**Comment by digitalchild** [comment]
Great overview, I didn't find any issues with this lesson for feedback. 

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by cynthianorman** [comment]
## Content Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

I found the lesson to meet all of the above items. Great work!

If not within this lesson then another you have planned within this pathway, I would consider adding the option of finding a theme within the WordPress dashboard. Many times site designers are trying to find a new theme with a site that already has content. For this reason, I believe it could be worth mentioning the advantages of using the Preview feature within the dashboard.

**Comment by westnz** [comment]
Thank you for reviewing @digitalchild and @cynthianorman

**Comment by westnz** [comment]
//published
