### ISSUE TITLE
Why use the WordPress Site Editor for design and prototyping

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2895]
Designing in the Site Editor and using it for prototyping. (theoretical introduction to the pros: save time on designer -> developer handover, get interactive preview, use the tool itself)

- The difference between web design and print design
- Web-related design principles (gestalt principles)

//lesson

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/4b38dbb8-de7c-475e-bc96-b9a695d4b746

**Comment by westnz** [comment]
//review

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist. 

Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial. 

*****  

@westnz felt like a bit of a quicker pace than usual on this one, but still wasn't too fast. I did have to pause/replay a couple of sections to make sure I was correctly understanding the process that was being explained.  

But all the info fit well, and was relevant to the topic and objectives outlined.  

A couple of notes on the Gestalt section:

- the first 2 visuals (Proximity and Similarity) were not immediately clear on what the discrepancies were. There was a red ✖️  and green ✔️ mark to indicate correct and incorrect but I had to pause the video to get a better look: 
	-- On the Proximity slide it looks like spacing was the main difference.  
	-- On the Similarity slide, the contrasting buttons appeared to be the issue. 
- Perhaps highlighting or zooming in on the incorrect parts might help. 
- or keeping the graphic up a little longer.
- or using different slides altogether 

That was really it - great work!

**Comment by westnz** [comment]
Thank you for the helpful feedback @quitevisible!

**Comment by westnz** [comment]
//published
