### ISSUE TITLE
Customizing theme settings: Colors, fonts, typography, and layouts

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2897]
Lesson: Customizing theme settings, colors, fonts, typography, and layouts.

- Global styles 
- Stylebook 

//lesson

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/cc5d4271-2acb-4a25-bd8f-5cee8e2af41e

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist. 

Please tick all items you've confirmed: 

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

*****  

Looks good @westnz - although it threw me for a second that you were using WP6.7 in the video.

**Comment by cynthianorman** [comment]
//review

**Comment by westnz** [comment]
Thank you for the reviews @quitevisible and @cynthianorman 

I will only publish this video after version 6.7 has been launched. 👍 

> Designers may want to know how to add pseudo-classes.

Thanks for this. Maybe a bit too advanced for the beginner learning pathway ⭐

**Comment by westnz** [comment]
//published
