### ISSUE TITLE
Dimensions: Padding, margin and block spacing

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2898]
Lesson: Block dimension settings

- Padding
- Dimension
- Block Spacing

//lesson

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/df80daa3-dcac-4a8a-8674-585d8ad0c355

**Comment by digitalchild** [comment]
This is a good tutorial, I have a couple of items I noticed. 

0:28 - You show the dimensions sometimes those features are hidden, might be worth adding 'if any settings are missing, you can enable them from the three dots' 

There is the ability to disconnect the dimensions and set them individually. This isn't covered in the video. This lets you set the top, left, bottom, right by clicking the lock for the setting.

Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by westnz** [comment]
//published
