### ISSUE TITLE
Designing with the Group block

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2899]
//lesson

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/ee8ddc2f-5046-4ee3-b912-80d941706c4e

**Comment by digitalchild** [comment]
Another nice and straightforward tutorial. 

My only question, why do you have to set a background with a stick block? 

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by westnz** [comment]
> My only question, why do you have to set a background with a stick block?

Could you elaborate, @digitalchild? If I understand correctly, you mean why you should change the background color when you make a Group block sticky? If you don't change the background, the Group block will be transparent, and the text you scroll over will be visible.

**Comment by digitalchild** [comment]
@westnz Yes that's what I mean. You say to change the background, but you don't say why.

**Comment by westnz** [comment]
//published
