### ISSUE TITLE
Online Workshop: Creating Your Own Simple Contact Form Plugin - part 2

### ISSUE THREAD

**Issue by laxmariappan** [WordPress/Learn#2901]
# Details
Online Workshop: Creating Your Own Simple Contact Form Plugin - part 2

- Topic description: This workshop covers how to validate form data, save entries to the database and send email notifications.
- Audience (User, Developer, Designer, Contributor, etc.): Developer (Beginner, intermediate)
- Learning objectives (What will the learner be able to do as a result of this content?):
  - Form validation: Validate form data using PHP.
  - Save form entries: Save form entries to the database using custom post type.
  - Send email notifications: Send email notifications to the site admin and the user who submitted the form.
  - Security: Implement security best practices to prevent spam and other security issues.
- Content type (Online Workshop, Lesson, Course, Tutorial, or Lesson Plan): Online Workshop
- WordPress version (optional): 6+
- Will you be creating this content? (Yes or No): Yes

# Related Resources

[Part 1: Creating Your Own Simple Contact Form Plugin](https://wordpress.tv/2024/09/12/creating-your-own-contact-form-plugin/)
[WordPress Plugin Handbook: Data Validation](https://developer.wordpress.org/apis/security/data-validation/)
[WordPress Plugin Handbook: Data Sanitization](https://developer.wordpress.org/apis/security/sanitizing/)
[Custom Post Types](https://developer.wordpress.org/plugins/post-types/)

## Topics to cover
- Form validation
- Save form entries
- Send email notifications
- Security best practices

## Workshop Outline
- Introduction
- Demo of the contact form plugin with validation, saving entries to the database, and sending email notifications
- Code walkthrough
- Q&A

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

**Comment by jonathanbossenger** [comment]
//online-workshop

**Comment by jonathanbossenger** [comment]
@laxmariappan looks good to me. Next step is for you to suggest a date and time, and I'll start working on the meetup.com event.

**Comment by laxmariappan** [comment]
@jonathanbossenger can we set the similar time like part 1? 

That is on a Wednesday 12:00 UTC.

I am open to other dates and time as well, thanks.

**Comment by jonathanbossenger** [comment]
Hey Lax, sure, Wednesday at 12:00UTC works. So that's next Wednesday 16 October.

I'll create the meetup event today and update the checklist.

**Comment by laxmariappan** [comment]
@jonathanbossenger that is great, let's do it on Wednesday 16 October

**Comment by jonathanbossenger** [comment]
@laxmariappan The meetup event has been created and added to the online workshop check list.

Looking forward to co-hosting with you on Wednesday.

**Comment by laxmariappan** [comment]
Thanks @jonathanbossenger same!

**Comment by jonathanbossenger** [comment]
## Online Workshop Details
- Date: 2024-10-23
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/304075363
- Co-host: @jonathanbossenger 

## Online Workshop Development Checklist
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign [a Co-host](https://make.wordpress.org/training/handbook/online-workshops/co-hosting-an-online-workshop/) to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
@laxmariappan new online workshop details added.

**Comment by laxmariappan** [comment]
Thanks @jonathanbossenger 🙌

**Comment by jonathanbossenger** [comment]
WordPress.tv: https://wordpress.tv/2024/10/24/creating-your-own-contact-form-plugin-part-2/

**Comment by jonathanbossenger** [comment]
//publish
