### ISSUE TITLE
Meeting Agenda September 26, 2024

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2906]
Training Team meetings start at [00:00 UTC weekly on Thursdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @lada7042._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

- Sept 26 - [Zeel Thakkar](https://profiles.wordpress.org/zeelthakkar/)
- Oct 3 - [Jagir Bahesh](https://profiles.wordpress.org/jagirbahesh/)
- Oct 10 - looking for volunteer
- Oct 17 - looking for volunteer

**2. Looking for feedback**

- Designer learning pathway outline
Are you a designer? We would love your input on the [draft Designer learning pathway outline](https://docs.google.com/document/d/1u0WHj1_D2nlJDJ5-CveJVplcGSDb5QH07Wt_YFtQ1G8/edit). The aim is to start creating content for the Beginner pathway by the end of this month.
- I added a new section below about upcoming events. I would love your thoughts? Is this useful or adds too much to the meeting?

**3. Looking for volunteers**

- Call for Contributors: Become an Online Workshop Host
Are you passionate about WordPress and helping others? The Training Team is seeking contributors to host [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)! Share your expertise, connect with a global audience, and make an impact. Host a live workshop in your preferred language and time zone, engage with attendees, and give back to the community. Expand your network while helping others improve their WordPress skills. [Apply to facilitate](https://learn.wordpress.org/online-workshops/apply-to-facilitate/) - we’re excited to work with you!
- item 2

**4. Updates from last week's dev-squad triage session**

- item 1
- item 2

**5. Other news**

- [Tour the New Learn WordPress](https://wordpress.org/news/2024/09/tour-the-new-learn-wordpress/)
- [Training team update – September 2024](https://make.wordpress.org/updates/2024/09/25/training-team-update-september-2024/)

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 10 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 20 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 4 issues that require vetting

**[Good first issues for developers](https://github.com/orgs/WordPress/projects/71/views/7)**

- See [Developing Learn WordPress](https://make.wordpress.org/training/handbook/training-team-how-to-guides/developing-learn-wordpress/) for instructions on contributing to the Learn WordPress code.
- We have 0 issues requiring development

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Contributors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 21 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: Badges awarded: Badges are awarded at the last meeting of the month. Please fill out applications prior to the last Monday of the month so the team reps can review at their meeting. You must meet [Team badge requirements](https://make.wordpress.org/training/handbook/about/team-profile-badges/)
- Props: Do you have someone from the team you want to celebrate!! :dance:
Please add to the thread :thread:

## 4. Project updates

- Learning Pathways Update
Project update: https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/#comment-4344
- Project_2
  - details

## 5. Upcoming Online Workshops to attend: :desktop_computer:
- [Creating a portfolio site with a block theme and patterns](https://www.meetup.com/learn-wordpress-online-workshops/events/303497771/?eventOrigin=group_events_list)
- 

## 6. Contributor Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other contributor or Training Team members help you in some way?

## 7. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by kathrynwp** [comment]
## Mentorship cohort

The Q4 mentorship program is very full, so they'll be using Online Workshops to deliver sessions on various aspects of the WP project, as well as introductions to the various teams, so we should expect to see those scheduled soon. They will also be open to the public.

**Comment by ghost** [comment]
Slack meeting start- https://wordpress.slack.com/archives/C02RW657Q/p1727308883252809

**Comment by Zeelthakkar1207** [comment]
Meeting recap post published : https://make.wordpress.org/training/2024/10/01/training-team-meeting-recap-26th-september-2024/
