### ISSUE TITLE
Using the WordPress Media & Text block

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2908]
Media & text block

**Comment by westnz** [comment]
//content

**Comment by westnz** [comment]
//lesson

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/4cfca498-aedb-4588-b9cb-3f9efb315d0d

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations is easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).
 
An excellent lesson, @westnz.

My only comment is about the missing `alt` text :-)

**Comment by rithikamarar3** [comment]
A powerful and beautifully delivered lesson, @westnz.

**Comment by westnz** [comment]
//published
