### ISSUE TITLE
Missing quiz for "Shipping Swag to Meetups and WordCamps" lesson

### ISSUE THREAD

**Issue by kharissulistiyo** [WordPress/Learn#2917]
Lesson URL: https://learn.wordpress.org/lesson/shipping-swag-to-meetups-and-wordcamps/

The quiz button does exist in the bottom of the lesson, but clicking it returns to a not-found page.

![Image](https://github.com/user-attachments/assets/b64c372a-f4e1-4865-8826-40b76022d9dd)

I am not sure if the quiz unavailability is intentional, but I don't see any note in the lesson content which explains this situation.

**Comment by kaitohm** [comment]
Thanks for reporting. This has now been fixed!

(Reference: [Slack discussion](https://wordpress.slack.com/archives/C02RW657Q/p1729233507191739))
