### ISSUE TITLE
Feedback - Add license explanation to Learn

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#2928]
## Type of feedback

//dev

## Description

I was recently asked by a community member what license Learn content was released under. It would be great if we could add the info publicly to the site somewhere.

@jonathanbossenger pointed out https://wordpress.tv/ says on the homepage...
> This work is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).

Perhaps we should put something similar in the site footer?

**Comment by adamwoodnz** [comment]
We include this on each Course, Lesson Plan and Tutorial, in the sidebar. Is that sufficient?

![Image](https://github.com/user-attachments/assets/2551f5f5-3a5e-4822-8ec0-e95a58b7f155)

**Comment by kaitohm** [comment]
Ah, nice. As long as it's somewhere. Thanks 🙌
