### ISSUE TITLE
Feedback - https://learn.wordpress.org/lesson/styling-your-site-globally/ typo

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2940]
## Type of feedback

// content 

## Description

// there is a typo in - https://learn.wordpress.org/lesson/styling-your-site-globally/ - in the Styling Your Site Globally Section. The sentence is - Think back to the color palette you decided upon for your website and the fonts you decided that are going to use; now is the time to use them! - it should be 'that you are going to use'. 

## Screenshots or screen recording (optional)

![Image](https://github.com/user-attachments/assets/e7e3c17b-cf62-4583-b4fc-893bd5259d1a)

## Other information (optional)

How can I submit a PR to fix small issues like this in future?

**Comment by ghost** [comment]
Can you assign this to me? I have learn.wordpress.org installed locally now

**Comment by digitalchild** [comment]
@j0eybrinkman Thanks for the feedback, I've gone ahead and adjust the text.
