### ISSUE TITLE
New page showing version-specific content

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#295]
We need a page that can be filtered with the URL to show all content for specific releases. Content must come from (and be grouped by) the major post types: `lesson-plan`, `course`, `wporg_workshop` and `meeting`. The existing `wporg_wp_version` taxonomy can be used for getting the correct posts.

I'm thinking the page URL should be something like `learn.wordpress.org/version/5.9` where `5.9` is the taxonomy term used for filtering. If no taxonomy term is specified then it should default to whatever the current version of WordPress is according to the WordPress.org API.

In terms of page layout - for courses, workshops, and social learning spaces we can use the same as what we have on the home page of the site already, but we would need a new block to display lesson plans that somewhat matches what we have on the existing lesson plan archive.

**Comment by courtneyr-dev** [comment]
I started experimenting @hlashbrooke using a page + query loop blocks with filters. https://learn.wordpress.org/?page_id=14180&preview=true

It'd be nice to explore using FSE features on LearnWP that reduce dev coding needed.  For instance, on this post, we mainly need featured image supports for lesson plans, and are hoping to see socialimagegenerator.com just merged into Jetpack so we don't need design to create all featured images. 

In this ticket, I think focusing on enhancing the layout, and perhaps rolling the page into a pattern where we just create each version number in the taxonomy filters would be amazing. 

Then we need to account for it in the site navigation.

**Comment by adamwoodnz** [comment]
@kaitohm do you think this is still necessary? Otherwise let's close.

**Comment by kaitohm** [comment]
Let's close for now. If we come across the need again in future, we can create a ticket again then.
