### ISSUE TITLE
Feedback - typo and content update to reflect cent os eol - https://learn.wordpress.org/lesson/wordpress-and-web-servers/

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2950]
## Type of feedback

//content

## Description

typo in the wordpress-and-web-servers lesson under the What is a web server? section (missing 'a'). Corrected sentence - A web server is a computer that is connected to the internet and is configured to serve web pages.

CentOS is listed as popular linux distros, the end of life for CentOS was June of 2024. Suggest replacing CentOS with Rocky since it is equivalent and EOL for current stable version isn't until 2032.

## Step-by-step reproduction instructions (optional)

1. Go to https://learn.wordpress.org/lesson/wordpress-and-web-servers/
2. Scroll down to What is a web server?

## Screenshots or screen recording (optional)

![Image](https://github.com/user-attachments/assets/e874dd18-fa7a-4a5e-96fa-bfe5765e7a63)

![Image](https://github.com/user-attachments/assets/93d7f8f6-10ac-458e-8991-e7f64ae8a223)

## Other information (optional)

https://www.redhat.com/en/topics/linux/centos-linux-eol

https://wiki.rockylinux.org/rocky/version/

**Comment by jonathanbossenger** [comment]
Thanks for reporting @j0eybrinkman I don't use CentOS, so I wasn't aware of this.

**Comment by ghost** [comment]
**Production-Ready Alternatives**

Rocky Linux and Alma Linux stand out as robust replacements for CentOS in production environments:

- Rocky Linux offers 1:1 binary compatibility with RHEL, aiming for "bug-for-bug" consistency. This makes it an ideal choice for organizations seeking a seamless transition from CentOS.
- Alma Linux provides binary compatibility with RHEL, focusing on Application Binary Interface (ABI) compatibility. While not claiming "bug-for-bug" compatibility, it ensures applications run as smoothly as they would on RHEL.

**Comment by jonathanbossenger** [comment]
The original script was a reference to the top [5 Linux distros by usage worldwide on W3Techs](https://w3techs.com/technologies/details/os-linux), so I'll update the list to replace CentOS with AlmaLinux.

**Comment by jonathanbossenger** [comment]
- [x] Fix typo in lesson
- [x] Upload edited lession video
