### ISSUE TITLE
Meeting Agenda October 15, 2024

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2951]
Training Team meetings start at [07:00 UTC weekly on Tuesdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

This week’s meeting will be hosted by @digitalchild 

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**
Oct 15 – [Sumit Singh](https://wordpress.slack.com/team/UNQE3NMEF)
Oct 22 – [Dapo](https://wordpress.slack.com/team/U07947N7L22)
Oct 29 - [Sancastiza](https://wordpress.slack.com/team/U05DY3DB60G)

**2. Looking for feedback**

- [Nomination for 2025 Training Team Reps](https://make.wordpress.org/training/2024/10/04/nomination-for-2025-training-team-reps/) Please nominate next year’s team reps on the post by October 25th.
- 

**3. Looking for volunteers**

- [Call for contributors: Designer Learning Pathway](https://make.wordpress.org/training/2024/09/30/call-for-contributors-designer-learning-pathway/) 
- Looking for volunteer to take over testing of [GatherPress](https://demo.gatherpress.org/) for the Training Team.
With [@Laura A](https://wordpress.slack.com/team/U0422D20MNF) departure from the team, we need someone to take over [liaising between the GatherPress project and the Training Team](https://make.wordpress.org/training/2024/06/27/training-team-testing-gatherpress/). Role includes:
    - Joining GatherPress Slack channel and staying updated on the project’s progress. 
    - Report back to the training team on a regular bases.
    - Run testing scenarios and provide feedback to the GatherPress project team.
    - Please comment here if you’d like to take this on :pray::skin-tone-3: :thread:

- After the recent Github updates, we have a bunch of new functionality we can utlize. It would be great if we can investigate these and implement them in our workflow. We are looking for people to work with Kaito to update the handbook and our processes. 
- 
**4. Updates from last week's dev-squad triage session**

- Join us this week in #meta-learn for the dev-squad

**5. Other news**

- [Announcing the next Learn WordPress Course Cohort.](https://make.wordpress.org/training/2024/10/13/announcing-the-next-learn-wordpress-course-cohort/)
-

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 4 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 22 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 4 issues that require vetting

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Contributors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 22 issues awaiting a fix

## 3. Contribution Acknowledgement

- Props: It’s time for Props! Do you have someone from the team you want to celebrate? :dance:
Please add to the thread :thread:

## 4. Project updates

Does anyone have any project updates? 

## 5. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by cynthianorman** [comment]
As a 2nd follow-up on creating a module quiz/activity review process, I've created this issue which contains a link to a Google doc. This document is currently a draft and I invite anyone to leave a comment there.
https://github.com/WordPress/Learn/issues/2946

**Comment by kaitohm** [comment]
[Training Team Meeting Recap – 15th October 2024](https://make.wordpress.org/training/2024/10/20/training-team-meeting-recap-15th-october-2024/)
