### ISSUE TITLE
Feedback - typo on https://learn.wordpress.org/lesson/php/

### ISSUE THREAD

**Issue by ghost** [WordPress/Learn#2953]
## Type of feedback

//content

## Description

There is a typo in the PHP lesson.

## Step-by-step reproduction instructions (optional)

1. Go to https://learn.wordpress.org/lesson/php/
2. Scroll to What is PHP?

Typo sentence - To see a simple example of what PHP can do, let’s take at the HTML page from the previous lessons, but use PHP to change the color of the heading element:

Corrected sentence - To see a simple example of what PHP can do, let’s take a look at the HTML page from the previous lessons, but use PHP to change the color of the heading element:

## Screenshots or screen recording (optional)

![Image](https://github.com/user-attachments/assets/deca98b1-06fc-47af-87e2-ecb64623f7bd)

**Comment by jonathanbossenger** [comment]
Good catch, will get this fixed.
