### ISSUE TITLE
Malicious/Suspicious links in the handbook

### ISSUE THREAD

**Issue by jennydupuy** [WordPress/Learn#2954]
In the page [Translating content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/), I detected these two links as malicious:

1.DownSub (`https://downsub.com/`)
2.YouTube Subtitle Download Helper(`https://chromewebstore.google.com/detail/youtube-subtitle-download/dpmmcccjdcgdjnlnicicdbnlmohhpagf`) 

see the reports of VirusTotal
https://www.virustotal.com/gui/url/a1e76c7f15db4c4627bbfa08161f3a4d883cda5fa99e07c5ce2f9f15464abbe4
https://www.virustotal.com/gui/url/559cad202e4cd61544e63ff1d28b36f94c90d2e65b6f84f09535318cb0a00597

I hope this issue will help.

**Comment by kaitohm** [comment]
Thanks for the report.

For now, I've replaced the following text in the handbook

> Download the automatically translated video captions from YouTube using free tools such as [DownSub](https://downsub.com/) or [YouTube Subtitle Download Helper](https://chromewebstore.google.com/detail/youtube-subtitle-download/dpmmcccjdcgdjnlnicicdbnlmohhpagf). Clean these up as necessary.

with

> This needs translating.

I had a look online for other free software and couldn't find anything that downloads the auto-translated captions. We might have to rely on manual translation methods for now.

**Comment by jennydupuy** [comment]
I’ve found this tool: https://www.downloadyoutubesubtitles.com/

**Comment by jennydupuy** [comment]
But the proposed formats are: SRT or VTT or TXT.

**Comment by kaitohm** [comment]
That tool looks great! I've updated the handbook to recommend that one.

**Comment by jennydupuy** [comment]
Be careful, the online tool https://www.downloadyoutubesubtitles.com/ is also malicious.
Sorry.

**Comment by kaitohm** [comment]
https://www.virustotal.com/gui/url/71641ca4b12fa4336721ce717f28f7c08c02a3cf018eecece02d2e27fdc119a4/detection doesn't show that https://www.downloadyoutubesubtitles.com/ is malicious. How did you find that, @jennydupuy ?

**Comment by jennydupuy** [comment]
Yes VirusTotal don’t indicated this as malicious, but when I click on a button to download SRT file another tab opens with ads, setup Opera program or porn content.
I have send a message to the site yesterday to let them know.

I have found a tool named 4k Video Downloader+ which allow you to download SRT file in the desired language.
https://www.4kdownload.com/fr/downloads/9#
In the free version, you can do 10 downloads by day. I think it's enough for our purposes.

**Comment by kaitohm** [comment]
Oh no! Thanks for catching that.

I've further updated [the handbook page](https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#a-learning-pathway-courses) to now direct folks to use 4K Video Downloader Plus. How does this look now?

**Comment by jennydupuy** [comment]
It’s ok but you can use plural form for "subtitle language" because we can select several languages in same time.
![Image](https://github.com/user-attachments/assets/7bcbbc7a-18f2-4500-a534-79a9186f19ca)

For me, two steps are missing:
- change the xml:lang=“en” tag to xml:lang=“new-language-code” in the TTML before exporting it.
- convert the translated SRT into txt, so as to have most of the text below the video, which then needs to be re-formatted and paragraph headings added.

With this tool: https://converts.me/tools/conversion/subtitle/all
we can edit the code of TTML file to modify the language tag before download it.

**Comment by kaitohm** [comment]
Hi @jennydupuy , Thanks for all the input.

I've updated [the handbook page](https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/) applying your suggestions.

I just didn't understand this part of your comment.
> convert the translated SRT into txt, so as to have most of the text below the video, which then needs to be re-formatted and paragraph headings added.

Could you explain this feedback to me once more, based on the revisions I've applied? Thanks 🙇‍♂

**Comment by jennydupuy** [comment]
Hi @kaitohm 

The text below the video under the heading “Transcript” is the same as the video's subtitles, only the presentation is different.
See this screenshot.
![Image](https://github.com/user-attachments/assets/b5bfea8b-c041-4b41-8be7-a523db29a3c8)

So you can transform the SRT file to show only the text (= convert it to TXT) that corresponds to the transcript, and add paragraph headings to this text in the right places (text highlited in pale red on the screenshot).

In the handbook, in the step 3 in paragraph "Learning Pathway Courses" replace the strikethrough text
![Image](https://github.com/user-attachments/assets/903188ef-8048-437b-996b-39636fb15ab2)

Then, the paragraph could be like this:
3. Each lesson will have up to 5 components that need translating. Include all these in the Google Document from step 2 except the captions.
The lesson title – This needs translating.
The captions on the video – _This needs be downloaded and corrected. See how to do this in the tip below._
The transcript in the lesson – _It is equivalent to captions text, but is presented differently with headings. See the tip below._
The headers throughout the transcript – Add translated headers to match the English transcript.
The quiz – Some lessons will have a quiz. Translate the questions and options in the same Google Document as above.

And the tip, coulb be like this (new text in italic):

_To modify the auto-generated captions on YouTube and generate the text of the transcript, then follow these steps._

1. Download the automatically translated video captions from YouTube using free tools such as [4K Video Downloder Plus](https://www.4kdownload.com/).
2. With 4K Video Downloader Plus, you can download translated captions by selecting the subtitle language(s) from the Download Video menu.
3. _Edit the captions in a text editor. Don’t remove the time markers._
4. Convert the caption file to the TTML file format using https://converts.me/tools/conversion/subtitle/all.
5. On line 2 of the TTML output, replace xml:lang=“en” with xml:lang=“NEW_LANGUAGE_CODE”, where NEW_LANGUAGE_CODE is [the two letter language code](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes) of the language the captions have been translated into.
6. Download the TTML file.
_7. With the same tool, convert also the caption file(s) to TXT file format using https://converts.me/tools/conversion/subtitle/all. 
8. Download the TXT file.
9. Copy the content of TXT file to the Google Document and add the headers at the right places._
10. Compress your caption file(s) _(translated SRT and TTML)_ as a ZIP file and upload it to the GitHub issue.
 ---------------------

Note that the translated SRT file can used on YouTube, the translated TTML file is used on wordpress.tv, when the reviewer has validated them.

I hope that my proposition seems more clear.

**Comment by kaitohm** [comment]
This is wonderful, @jennydupuy . It makes total sense to me!

I've updated [the handbook page](https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/) with your recommendations, making some minor adjustments to wording etc.

I think this issue is good to close now. What do you think?

**Comment by jennydupuy** [comment]
@kaitohm yes we can close.
I wanted to take part in today's meeting to explain this workflow and the tools, but I haven't yet reconnected to the Making WP slack.
I hope this workflow suits the team.
