### ISSUE TITLE
Wrong link to lesson "Einführung in WordPress"

### ISSUE THREAD

**Issue by rfluethi** [WordPress/Learn#2957]
## Step-by-step reproduction instructions (optional)
On the page "[https://learn.wordpress.org/?s=Einf%C3%BChrung+in+WordPress&post_type=lesson,"](https://learn.wordpress.org/?s=Einf%C3%BChrung+in+WordPress&post_type=lesson,%22) the lesson "Einführung in WordPress" is displayed correctly. However, the link for this lesson is incorrect. It leads to "[https://learn.wordpress.org/lesson/de-introduction-to-wordpress-2/"](https://learn.wordpress.org/lesson/de-introduction-to-wordpress-2/%22) instead of "[https://learn.wordpress.org/lesson/einfuhrung-in-wordpress/"](https://learn.wordpress.org/lesson/einfuhrung-in-wordpress/%22).

## Screenshots or screen recording (optional)

Overview page
![Image](https://github.com/user-attachments/assets/3f828f58-60ad-4fdb-8b5d-473638f257bb)

Wrong page
![Image](https://github.com/user-attachments/assets/e8f61fad-4235-4f9e-8ee9-7d9a1c594fe6)

Correct page
![Image](https://github.com/user-attachments/assets/8e933714-6dff-4e6e-b19b-9e8b40ba172b)

## Other information (optional)
Attention, not only is the video incorrect, but the transcription text is also wrong. It seems there are two entries in Sensei.

**Comment by rfluethi** [comment]
//content

**Comment by westnz** [comment]
I unpublished this version: [https://learn.wordpress.org/lesson/de-introduction-to-wordpress-2/"](https://learn.wordpress.org/lesson/de-introduction-to-wordpress-2/%22)

This is the only version of the lesson available now: https://learn.wordpress.org/lesson/einfuhrung-in-wordpress/
