### ISSUE TITLE
Meeting Agenda October 29, 2024

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#2983]
Training Team meetings start at [07:00 UTC weekly on Tuesdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @jonathanbossenger ._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

Oct 29 - [@Sancastiza](https://wordpress.slack.com/team/U05DY3DB60G)
Nov 5 - [@Dapo](https://wordpress.slack.com/team/U07947N7L22)
Nov 12 - Looking for volunteer 
Nov 19 - Looking for volunteer 

**2. Looking for feedback**

- Handbook page regarding creating quizzes/activities [@Cynthia Norman](https://wordpress.slack.com/team/U05E2Q9N78U) has drafted a handbook page about creating quizzes/activities for content on Learn WordPress and is looking for feedback. Thank you for drafting this page, Cynthia :raised_hands::skin-tone-3:
    - Please leave feedback directly in this GitHub issue: https://github.com/WordPress/Learn/issues/2946
- Looking for thoughts about how to add Facilitator Notes to Learn
   - Designers and developers are discussing how best to implement Facilitator Notes to Learn WordPress. The team will be concluding discussions and moving to implementation soon.
  - Join the discussion directly in this GitHub issue: https://github.com/WordPress/Learn/pull/2927
- [Brainstorm: Introducing Learning Pathways to users during onboarding](https://make.wordpress.org/training/2024/10/24/brainstorm-introducing-learning-pathways-to-users-during-onboarding/)
   - This post takes some of the ideas the team brainstormed in [Drawing new learners to the new Learn.WordPress.org](https://make.wordpress.org/training/2024/08/28/drawing-new-learners-to-the-new-learn-wordpress-org/) and is proposing concrete steps to getting them implemented.
   - Come leave your thoughts by November 8th.
- Retiring the Subject Matter Expert (SME) role in favor of the GitHub Editors group (continuation to [last week's discussion](https://wordpress.slack.com/archives/C02RW657Q/p1729581315037819))
   - The Training Team has tried using the SME role for two tasks: vetting content topics and assisting content creators. We’ve not seen SMEs vet content topics in a while. And we believe assisting content creators can be done in an editor capacity.
   - To simplify team roles and remove friction, team reps recommend removing the SME role and relying on the [GitHub Editors group](https://github.com/orgs/WordPress/teams/learn-editors) instead.
   - What do folks think about this proposal?

**3. Looking for volunteers**

- item 1
- item 2

**4. Updates from last week's Triage Squad session**

- No triage squad last week. Join us this week as we go through dev and content issues. 

**5. Other news**

- item 1
- item 2

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 2 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 23 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 2 issues that require vetting

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Contributors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 28 issues awaiting a fix

## 3. Contribution Acknowledgement

- Badges awarded: [Meagn Hanes](https://wordpress.slack.com/team/U02S3F3UT) 
- Props: 

## 4. Project updates

- Project_1
  - details
- Project_2
  - details

## 5. Upcoming Online Workshops

- [Developer Hours: Exploring the Twenty Twenty-Five Theme](https://www.meetup.com/learn-wordpress-online-workshops/events/304044317/)
- [Learn WordPress Study Hour](https://www.meetup.com/learn-wordpress-online-workshops/events/304140246/)
- [Learn WordPress Study Hour](https://www.meetup.com/learn-wordpress-online-workshops/events/304140285/) 

## 6. Contributor Updates

- What have you been working on and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other contributor or Training Team members help you in some way?

## 7. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by jonathanbossenger** [comment]
Note takers

- [@noruzzaman](https://wordpress.slack.com/team/U04A11X1J2H) has offered to take notes for November 12
- [@Dapo](https://wordpress.slack.com/team/U07947N7L22) has offered to take notes for November 19

FYI @kaitohm @digitalchild

**Comment by kaitohm** [comment]
This meeting started here: https://wordpress.slack.com/archives/C02RW657Q/p1730185237059949

**Comment by digitalchild** [comment]
Thanks @jonathanbossenger

**Comment by kaitohm** [comment]
https://make.wordpress.org/training/2024/11/02/training-team-meeting-recap-29th-october-2024/
