### ISSUE TITLE
Spanish translation for "Choosing and installing a theme"

### ISSUE THREAD

**Issue by rraventos** [WordPress/Learn#2985]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/choosing-and-installing-theme/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/758
- Language you'll be translating to: Spanish (Spain)
- Have you arranged for someone to review this translation?: No, I will ping Rocio Valdivia from the General Translation Editors Spanish team
- Reviewer's GitHub username: https://github.com/dorsvenabili
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by rraventos** [comment]
https://docs.google.com/document/d/1x8Kq-kBOce2d3n9wVQksx4SyO6qEZsDIIUqJ1JcK2kM/edit?usp=sharing

**Comment by dorsvenabili** [comment]
I've added a few suggestions to the doc, @rraventos. With that, it looks great and approved from my part! 
Thank you so much! :D

**Comment by rraventos** [comment]
I've made the changes suggested by @dorsvenabili in the document. Thank you!

**Comment by devmuhib009** [comment]
Hi @rraventos 
I just noticed you are translating a tutorial, but tutorials are no longer part of the navigation in the new Learn WordPress site and their content will be migrated into Lessons. I didn't notice this earlier. Please follow these [guidelines](https://github.com/WordPress/Learn/issues/2986) when translating tutorials.

**Comment by rraventos** [comment]
Sure and Thanks @devmuhib009. I will follow the mentioned guidelines.

**Comment by rraventos** [comment]
Hi @devmuhib009 and @dorsvenabili,
 
Following the guidelines, I have translated and submitted the .ttl subtitles in Spanish file to WordPress.tv in https://wordpress.tv/2023/10/09/choosing-and-installing-a-theme-2/

[choosing-and-installing-a-theme-ES.ttml.zip](https://github.com/user-attachments/files/17662376/choosing-and-installing-a-theme-ES.ttml.zip)

I think the only thing left is your approval for the captions to be shown in the video.

**Comment by devmuhib009** [comment]
Hi, I approved the TTML file on WPTV, but it's not working. I checked it with a JSON formatter, and it's showing an error. It looks like some needed code might have been removed, causing the error. Please fix it and resubmit. Thanks!

**Comment by rraventos** [comment]
Hi @devmuhib009,

I didn't realize that there were different versions of the tutorial on WPTV and previously I submitted the .ttl file to the wrong video. Sorry about that.

This is the URL of the latest video on WPTV https://wordpress.tv/2024/01/18/choosing-and-installing-a-theme-3/ where I re-submitted the TTML file for your approval.

Thanks!

**Comment by devmuhib009** [comment]
Hi, I just checked the original video embeded on the tutorial is https://wordpress.tv/2023/10/09/choosing-and-installing-a-theme-2/

So, please submit subtitle on this WPTV video. Subtitle is working on https://wordpress.tv/2024/01/18/choosing-and-installing-a-theme-3/

But if you visit the original tutorial page, it does not show the subtitle: https://learn.wordpress.org/tutorial/choosing-and-installing-theme/

Thanks

**Comment by rraventos** [comment]
Hi, I tried to submit the new translation file (both tutorials are different) 
[subtitles_2_es.ttml.zip](https://github.com/user-attachments/files/17679621/subtitles_2_es.ttml.zip)

at https://wordpress.tv/2023/10/09/choosing-and-installing-a-theme-2/ but I keep getting the following error: Unknown error. Please try again later.

Is it possible that you need to delete the previous submission? I don't know.

Thanks

**Comment by devmuhib009** [comment]
Hi, I added the subtitle file manually. Please check: https://learn.wordpress.org/tutorial/choosing-and-installing-theme/

Thanks

**Comment by rraventos** [comment]
Great and thank you!

**Comment by rraventos** [comment]
By the way, I have seen that the captions are updated in the video but in the page, in Subtitles it only says English.
https://learn.wordpress.org/tutorial/choosing-and-installing-theme/

**Comment by devmuhib009** [comment]
Hi, great catch, I just updated that too!
Thanks

**Comment by devmuhib009** [comment]
Hi @kaitohm 
Published the subtitle on WPTV following this [guideline](https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials). Should I close this ticket as completed?

**Comment by rraventos** [comment]
Yes, thanks!

**Comment by kaitohm** [comment]
@devmuhib009 Yup, this can be closed. Please use the `//-publish` command in a new comment, with no `-`.

**Comment by devmuhib009** [comment]
//publish
