### ISSUE TITLE
Spanish translation for "Building a home page with a block theme"

### ISSUE THREAD

**Issue by rraventos** [WordPress/Learn#2986]
# Details
- Link to original content: https://learn.wordpress.org/tutorial/building-a-home-page-with-a-block-theme/
- Link to original content's GitHub issue (optional): https://github.com/WordPress/Learn/issues/758
- Language you'll be translating to: Spanish (Spain)
- Have you arranged for someone to review this translation?: No, I will ping Rocio Valdivia from the General Translation Editors.
- Reviewer's GitHub username: https://github.com/dorsvenabili
- Other info: 

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by devmuhib009** [comment]
Hi, please follow tutorial translation guideline from here. 
https://make.wordpress.org/training/handbook/training-team-how-to-guides/content-localization/translating-content/#tutorials
You can submit the subtitle on WPTV. Thanks

**Comment by rraventos** [comment]
Sure and thanks @devmuhib009. I will follow the guideline.

**Comment by rraventos** [comment]
Hi, I have submited the subtitle on WPTV.
Thanks!

**Comment by devmuhib009** [comment]
Hi, Just approved. Thanks for translating the subtitle.
//publish
