### ISSUE TITLE
Use a better color combination for blocks

### ISSUE THREAD

**Issue by alanjacobmathew** [WordPress/Learn#299]
Some learn WP pages like [Social Learning](https://learn.wordpress.org/social-learning/), [Contribute](https://learn.wordpress.org/contribute/), [Workshop Presenter Application](https://learn.wordpress.org/workshop-presenter-application/) use certain blocks with dark background and dark text making it difficult to read.

![Learn wp_background ](https://user-images.githubusercontent.com/33965848/148634232-2904803b-a199-405f-a722-a7908866f251.png)

**Comment by hlashbrooke** [comment]
Thanks for this @alanjacobmathew! This was fine (white text on the same colour background), but there must have been a theme update that has affected things. I've switched these pages to use the 'callout' blocks that come from the handbook plugin.
