### ISSUE TITLE
Explore synced pattern overrides

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#2992]

**Comment by westnz** [comment]
//lesson

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/99d909b2-0d29-487a-80a1-589a6e4f0616

**Comment by quitevisible** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

*****  

This is such a great feature!
Good pace, clear, and succinct. 
Another good tut @westnz

**Comment by westnz** [comment]
Thank you so much @quitevisible!

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.

- [x] Technical concepts introduced in the content are accurate.

- [x] The speed of demonstrations are easy to follow.

- [x] The narration audio matches what is shown visually.

- [x] Spelling and grammar are correct.

- [X] Sound quality is consistent throughout the video.

- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.

- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).
Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

***

+1 on everything @quitevisible wrote :-)

**Comment by westnz** [comment]
Thank you @ironnysh 🙏

**Comment by westnz** [comment]
//published
