### ISSUE TITLE
Applying filtering doesn't work properly for Workshop page

### ISSUE THREAD

**Issue by alanjacobmathew** [WordPress/Learn#302]
Link: [https://learn.wordpress.org/workshops/](https://learn.wordpress.org/workshops/)

How to reproduce the issue:

- select any option other than 'WordPress Version' in the filter (say language: English)
- Apply filter

It shows no results even though there are a lot of it. 

Apparently if the WP version part is removed from the URL, the search works fine. 
Link: [https://learn.wordpress.org/workshops/?series=&topic=&language=en_US&captions=](https://learn.wordpress.org/workshops/?series=&topic=&language=en_US&captions=)

**Comment by hlashbrooke** [comment]
Oh great catch - thanks @alanjacobmathew!

@ryelle Could you look into this? Looks like the filters aren't behaving correctly with the new WP version filter in place.
