### ISSUE TITLE
Feedback - Incorrect Error Message on Content Feedback Form

### ISSUE THREAD

**Issue by nobodys-ghost** [WordPress/Learn#3026]
## Type of feedback

//dev

## Description

When using the form on the [Report Content Feedback page](https://learn.wordpress.org/report-content-feedback), putting the URL of the [Intro to the Site Editor YouTube video](https://www.youtube.com/watch?v=ILgA2GemwO0) prompts the error message "Please enter a valid URL", despite the fact it is a valid URL.

## Step-by-step reproduction instructions (optional)

1. Go to the [Report Content Feedback page](https://learn.wordpress.org/report-content-feedback)
2. Input the URL of the above YouTube video `https://www.youtube.com/watch?v=ILgA2GemwO0`
3. Click send

## Screenshots or screen recording (optional)

![Image](https://github.com/user-attachments/assets/7bcaa79b-7e23-4508-b524-96edc30a8a38)

## Other information (optional)

- I'm on Windows 11, running firefox version 132.0.2
- I tried to replicate the behavior with a few other valid URLs that end in query strings, and it threw the same error message for all of them
- I already reported the typo mentioned in the above screenshot.

**Comment by jonathanbossenger** [comment]
Hi @nobodys-ghost thanks for opening this issue.

The content feedback form on the Learn.WordPress.org website seems to require you to enter a link to a URL on the site.

@adamwoodnz could you confirm if this is indeed the case?

**Comment by adamwoodnz** [comment]
I've tested and it seems to be the URL parameter that fails the validation, as `https://www.youtube.com/watch` passes, but `https://www.youtube.com/watch?v=ILgA2GemwO0` does not.

We are not doing anything custom with validation here, it's a standard Jetpack contact form URL field. If we really want to support this format we'll need to raise an issue with Jetpack.

I guess the intended use of this form is for content on our platform, so reporting on our YouTube content is slightly unusual. Is this video embedded in one of our Lessons?

**Comment by nobodys-ghost** [comment]
It's embedded in the [Intro to the Site Editor](https://learn.wordpress.org/lesson/intro-to-the-site-editor/) lesson of the beginner WordPress course.

**Comment by adamwoodnz** [comment]
Thanks, I imagine that URL is what we'd expect to be entered into the feedback form 🙂

**Comment by jonathanbossenger** [comment]
Thanks everyone. So, while it seems that the bug does exist in the Jetpack form, it's also true that the URL we'd need to capture on that form is to content on learn.wordpress.org. The main reason for this is that if a change is required for the video, we'd also need to update the content on the lesson. So it's a happy coincidence that this "bug" reinforces that.

I've updated the form to make it clearer that the user needs to use URLs to content on learn.wordpress.org, and I'll close this issue.

@nobodys-ghost if you would like to report the bug to the Jetpack repository, you can do so here: https://github.com/Automattic/jetpack
