### ISSUE TITLE
Spanish translation for "Introduction to WordPress"

### ISSUE THREAD

**Issue by angelcabaleiro** [WordPress/Learn#3032]
# Details
- Link to original content: https://learn.wordpress.org/lesson/introduction-to-wordpress-2/
- Language you'll be translating to: Spanish
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: **need reviewer**

**Comment by angelcabaleiro** [comment]
Ok, I've it :)

Transcription:

Hola, te doy la bienvenida a esta introducción a WordPress. En esta lección, profundizaremos en los conceptos básicos, para ayudarte a entender lo que puedes llegar a conseguir con WordPress, incluso si eres principiante.


Resultados del aprendizaje
En esta lección aprenderás a definir WordPress, ver lo que se puede conseguir usando WordPress, hablaremos un poco sobre la importancia de los temas y plugins, entenderás lo que significa código abierto, y veremos algunos ejemplos de sitios web hechos con WordPress.


¿Qué es WordPress?
WordPress te permite crear tu propio sitio web o blog. 

En el mundo se han hecho millones de sitios web con WordPress, desde tiendas online y páginas web de pequeñas empresas hasta páginas web de empresas de renombre como la NASA, Walt Disney Company y la sala de prensa de Facebook.

WordPress como sistema de gestión de contenidos (CMS)
Pero lo primero es lo primero: WordPress es un CMS o sistema de gestión de contenidos. 

En términos sencillos, es una herramienta gratuita que te ayuda a crear, editar y gestionar tu propio sitio web o blog sin necesidad de aprender código. 

Tanto si tienes una pequeña empresa, escribes un blog sobre tu pasión o eres una persona que aspira a ser empresaria, WordPress te ofrece la plataforma perfecta para dar a conocer al mundo tus ideas, productos y servicios.


WordPress como código abierto
Otra cosa a destacar, es que WordPress es de código abierto.

Esto significa que es un software libre que cualquiera puede descargar y utilizar. 

También significa que cualquiera puede contribuir al código o en otras áreas para ayudar a mejorar WordPress. 

¡Tú también puedes participar!


Temas y plugins
Hay dos elementos importantes que debes recordar cuando empieces a crear tu sitio con WordPress: los temas y los plugins. 

Necesitarás un tema, que determinará el aspecto de tu sitio web. 

Y hay miles de temas gratuitos y de pago que puedes elegir. 

En segundo lugar, WordPress te permite instalar plugins para añadir funcionalidades adicionales a tu sitio web. 

Por ejemplo, puedes añadir plugins para vender productos o servicios en su página web, mejorar la seguridad o la velocidad de tu sitio web o añadir formularios, entre otras opciones.

Ten en cuenta que los temas y plugins que aparecen aquí son solo unos pocos ejemplos, ya que hay miles de temas y plugins en el repositorio que puedes usar para construir tu página web.


Ejemplos de sitios web con WordPress
¿Sabías que más del 40% de los sitios web del mundo están creados con WordPress? 

Puedes tener la seguridad de que se trata de una plataforma muy fiable, segura y sostenible. 

Vamos a ver algunos ejemplos de sitios web que se han construido con WordPress.

En primer lugar, tenemos la web de Spotify, una de las plataformas de música y podcast más conocidas y que ha hecho su web en WordPress.

El siguiente ejemplo es el sitio web de la Junta de Andalucía, donde podemos ver información sobre la junta de gobierno de Andalucía, becas y ayudas al estudio, formación profesional, trabajo, jubilación y servicios sanitarios entre otros.

El tercer ejemplo es la web del periódico de noticias La Vanguardia, que al igual que El Mundo o El País han apostado por WordPress como motor de sus páginas web de noticias en español.

El último ejemplo es el blog de CaixaBank, un banco español bastante conocido y que usa WordPress en el apartado de blog de su página web para mostrar noticias sobre economía, sostenibilidad e innovación.


Próximos pasos

En resumen, WordPress es una herramienta gratuita que puedes utilizar para crear un sitio web sin tener conocimientos de código. 

WordPress es utilizado por blogueros, propietarios de pequeños negocios y grandes empresas e incluso agencias gubernamentales. 

En definitiva, WordPress es para todo el mundo. 

Pero ahora te estarás preguntando ¿qué pasa después de descargar WordPress? 

¡Buena pregunta! Justo de eso vamos a hablar en nuestro próximo video, ya que necesitarás un nombre de dominio y un lugar donde alojar tu sitio web. 

Te deseamos lo mejor en este inicio de tu viaje con WordPress.

**Comment by angelcabaleiro** [comment]
I've some problems uploading the video, it's .mov, should it be other format?

**Comment by angelcabaleiro** [comment]
Hi there, I uploaded it to Youtube as a hidden video:

[https://www.youtube.com/watch?v=ZuilDPY8dVs](url)

**Comment by devmuhib009** [comment]
@Sancastiza could you please review or do you know someone who can review?

**Comment by Sancastiza** [comment]
Hi there, I'm very happy and ready to do that.

**Comment by angelcabaleiro** [comment]
> Hi there, I'm very happy and ready to do that.

Great, thank you @Sancastiza ^_^

**Comment by westnz** [comment]
[Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/)

**Comment by westnz** [comment]
**Review**

@nilovelez : "From the technical and the WPTV point of view, the video is perfect..."

See Slack thread: https://wordpress.slack.com/archives/C02RW657Q/p1733764606765009

**Comment by westnz** [comment]
Hey @angelcabaleiro 

Once again, great work. We can go ahead and publish this lesson. Can you please provide me with the Spanish subtitles as a .ttml file? Then, I will finalize it.  Here are the [guidelines](https://make.wordpress.org/training/handbook/guidelines/tutorials/tutorial-subtitles-and-transcripts/).

**Comment by angelcabaleiro** [comment]
Hi there @westnz!

Ok, I can't upload it here, so I added it in Drive: https://drive.google.com/file/d/1QnYHb6GfLFPapI90zqm15LxR60jL6Jre/view?usp=sharing ;)

**Comment by westnz** [comment]
Thank you @angelcabaleiro 👍

**Comment by westnz** [comment]
One more favor @angelcabaleiro 😄 
Can you please share the video via Google Drive as well? I was not able to download the video from YouTube.

**Comment by angelcabaleiro** [comment]
No problem @westnz :)

Here you go: https://drive.google.com/file/d/16bdmOp0lYCtjBDjfWGrYZ-vJmj_fnQ1a/view?usp=drive_link (.mov)

Or downloaded from YouTube (it optimizes it and transform it in .mp4): https://drive.google.com/file/d/1nH3VKTUFHn-8_met0mzZGkswy52X8DNx/view?usp=drive_link

**Comment by westnz** [comment]
Thank you!! Request to access has been sent.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/lesson/introduccion-a-wordpress/

**Comment by westnz** [comment]
//published
