### ISSUE TITLE
Utilizing the Gallery block

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#3039]
- Light Box
- Captioning

**Comment by westnz** [comment]
//lesson

**Comment by westnz** [comment]
https://github.com/user-attachments/assets/40b51caa-a770-4318-a8f6-9ed173baa489

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist

- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations is easy to follow.
- [x] The narration audio matches what is shown visually.
- [ ] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).
 
Beautiful and effective lesson, @westnz.

A couple of suggestions:
- I noticed that none of the images have an `alt` text.
- A grammatical correction: You mention the _amount_ of columns a few times throughout the video. Shouldn't it be the _number_ of columns?
- What do you think about renaming the lesson to “Utilize the Gallery block”?

**Comment by rithikamarar3** [comment]
A captivating and impactful lesson, @westnz.

**Comment by westnz** [comment]
Thank you for the feedback @ironnysh and @rithikamarar3

**Comment by westnz** [comment]
//published
