### ISSUE TITLE
Meeting Agenda December 3rd, 2024

### ISSUE THREAD

**Issue by digitalchild** [WordPress/Learn#3047]
Training Team meetings start at [07:00 UTC weekly on Tuesdays](https://make.wordpress.org/meetings/#training). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

_This week’s meeting will be hosted by @digitalchild._

## 1. News

**1. [Meeting Note Takers](https://make.wordpress.org/training/handbook/about/team-roles/)**

Dec 3 - [@the_gujarati](https://wordpress.slack.com/team/U0731JP6LMQ)
Dec 10 - [LeifQ](https://wordpress.slack.com/team/U02RRF742)
Dec 17 - [Rithika](https://wordpress.slack.com/team/U075PNSFTRB)
Dec 24 - No meeting this week 

**2. Looking for feedback**

No new items this week. 

**3. Looking for volunteers**

No projects looking for volunteers this week. 

**4. Updates from last week's Triage Squad session**

@jonathanbossenger can you give us an update here? 

Attendees: Dilip Modhavadiya, Jonathan, Zeel Thakkar, Jagir Bahesh, Prem Tiwari, iRonnysh

Issues triaged:
- #2968 
- #3026 

**5. Other news**

- item 1
- item 2

## 2. Come and Contribute

**[Content ready for review](https://github.com/orgs/WordPress/projects/33/views/17)**

- See [Guidelines for reviewing content](https://make.wordpress.org/training/handbook/training-team-how-to-guides/guidelines-for-reviewing-content-on-learn/) when reviewing content.
- We have 8 issues ready for review

**[Feedback awaiting validation](https://github.com/orgs/WordPress/projects/78/views/3)**

- See [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on validating feedback.
- We have 26 issues that require validation

**[Topics awaiting vetting](https://github.com/orgs/WordPress/projects/105/views/1)**

- See [Vetting Topic Ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/vetting-topic-ideas/) for step-by-step guidance on vetting topic ideas.
- We have 2 issues that require vetting

**[Validated feedback awaiting fix](https://github.com/orgs/WordPress/projects/78/views/4)**

- Contributors, see [Validating and Applying Content Feedback](https://make.wordpress.org/training/handbook/training-team-how-to-guides/how-we-use-github/validating-and-applying-content-feedback/) for step-by-step guidance on applying feedback that has been validated.
- We have 27 issues awaiting a fix

## 3. Contribution Acknowledgement

- Props: share your props in this thread. 

## 4. Project updates

- [Learning Pathway: Intermediate Plugin Developer #2044](https://github.com/WordPress/Learn/issues/2044) - 
[@Jonathan](https://wordpress.slack.com/team/U0AHNQ65V)
- [Learning Pathway: Beginner Designer #2889](https://github.com/WordPress/Learn/issues/2889) - 
[@westnz](https://wordpress.slack.com/team/U02CMLBKFV3)
- [Project thread: The third Learn WordPress Course Cohort](https://make.wordpress.org/training/2024/10/13/project-thread-the-third-learn-wordpress-course-cohort/) -  [@Lax Mariappan](https://wordpress.slack.com/team/UMM8U7LNQ) [@Jonathan](https://wordpress.slack.com/team/U0AHNQ65V)
- [Project Thread: Content Maintenance Process Update Phase 1](https://make.wordpress.org/training/2024/06/28/project-thread-content-maintenance-process-update-phase-1/) - 
[@Jamie Madden](https://wordpress.slack.com/team/U0548P3UH)

## 5. Upcoming Online Workshops

- [Developer Hours: Improve your workflows with WordPress development tools](https://www.meetup.com/learn-wordpress-online-workshops/events/304668126/)
- [Learn WordPress Study Hour](https://www.meetup.com/learn-wordpress-online-workshops/events/304657271/)
- [Learn WordPress Study Hour](https://www.meetup.com/learn-wordpress-online-workshops/events/304705091/)
- [Using and customizing WordPress media blocks](https://www.meetup.com/learn-wordpress-online-workshops/events/304789031/?slug=learn-wordpress-online-workshops&#038;eventId=303497771&#038;isFirstPublish=true)

## 6. Contributor Updates

- What have you been working on, and how has it been going?
- Anything you’ve accomplished since the last meeting?
- Do you have any blockers?
- Can other contributor or Training Team members help you in some way?

## 7. Open Discussions

If you have topics you’d like discussed in the meeting, please leave them as a comment on this issue.

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#training). If you are new to the Training Team, then come walk through [our onboarding program](https://make.wordpress.org/training/handbook/getting-started/) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #training Slack channel](https://wordpress.slack.com/archives/C02RW657Q) at any time.

**Comment by devmuhib009** [comment]
I am currently working on the [Contributor Learning Pathway outline](https://docs.google.com/spreadsheets/d/1gbDySSZ6d1v3OZYJSR5C_rZsWAbp2h2uwd15jP8B3nQ/edit?usp=sharing). I have completed the Beginner Learning Pathway and am now seeking feedback to refine it. Additionally, I need assistance in drafting the Intermediate and Advanced Learning Pathways.

**Comment by kaitohm** [comment]
https://make.wordpress.org/training/2024/12/08/training-team-meeting-recap-3rd-december-2024/
