### ISSUE TITLE
Add new Header

### ISSUE THREAD

**Issue by dd32** [WordPress/Learn#305]
WordPress.org is getting a new header, See afbe745caffc6206232397795abb177e8bff9a36

The Learn repo will need to import the https://github.com/WordPress/wporg-mu-plugins/ repo somehow.

Once that's done, 25087e4c56ec5c7d2734e891917f797de4eee2c5 can be reverted.

**Comment by adamwoodnz** [comment]
Closing as Learn runs WordPress/mu-plugins now
