### ISSUE TITLE
Add minutes suffix with duration on Lesson plan page

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/Learn#307]
On the right side of the lesson plan page, where the duration is shown, I think it would be appropriate to add the minutes/min suffix. What do you all think? At the moment it seems incomplete.
Here is the lesson plan link - 
https://learn.wordpress.org/lesson-plan/how-to-create-a-menu-with-the-navigation-block/

below is the screenshot attached- 
https://files.slack.com/files-pri/T024MFP4J-F030SPAHA9K/image.png

**Comment by outdoor2kode** [comment]
Hi @webtechpooja,

I'm thinking that we could just edit the `Name` here in `Duration` without any work on the code.
![image](https://user-images.githubusercontent.com/18050944/155502633-1d7db2df-1733-415b-bf0d-c1181fa6bc93.png)
<img width="1962" alt="image" src="https://user-images.githubusercontent.com/18050944/155504179-f147ad37-94df-4c4e-9477-e8d3977bd875.png">


Here are some results of editing only the `Name` in `Duration`. Is this what you expect?
![image](https://user-images.githubusercontent.com/18050944/155502864-b383b3da-5f3e-4778-9da2-1926acf4b429.png)
(Lesson Plans Page)

![image](https://user-images.githubusercontent.com/18050944/155502972-ead6eeb1-f6b2-4f45-befa-e772341f54d4.png)
(Lesson Page)

<img width="3110" alt="image" src="https://user-images.githubusercontent.com/18050944/155504341-4c0a742b-4b39-47f7-a42e-07f8b6758737.png">
(Add New)

**Comment by webtechpooja** [comment]
Wow! that is so easy to do. I was thinking we need to code for this. Ok, I'll do this. 
Thank you for guiding me on this.
