### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#326]
Criteria for official slides:

* Backwards compatible
* Reusable
* Minimal learning curve
* Ability to use without internet
* Design consistency between different sets of slides (theme)
* Maintainability
* Ease of updates
* Ability to account for different aspect ratios
* Accessible
* Open source

**Comment by kaitohm** [comment]
Noting most recent discussion: 
https://make.wordpress.org/training/2021/01/29/request-for-testing-slides-plugin/

**Comment by kaitohm** [comment]
Noting a possibly relevant feature announced by the Themes Team: https://make.wordpress.org/themes/2023/05/04/stacks-the-first-community-theme/
