### ISSUE TITLE
Title and intro text

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#36]
The current title text of "Help Others Learn WordPress" must be changed to simply "Learn WordPress" - this appears on the home page as well as in the header on all sub-pages.

The intro text below that title on the homepage must be changed to:

> Whether you’re a first-time blogger or seasoned developer, there’s always more to learn. From the contributors who make WordPress, these vast resources will help you learn more about WordPress and teach it to others.

**Comment by CdrMarks** [comment]
@hlashbrooke Should the last sentence begin with this?
> From the contributors who make WordPress

I think it limits the pool of presenters to those who have contributed to WordPress before.

**Comment by hlashbrooke** [comment]
Good point. I was modifying the existing wording there. Let's make it this:

> Whether you’re a first-time blogger or seasoned developer, there’s always more to learn. From community members all over the world, these vast resources will help you learn more about WordPress and teach it to others.

**Comment by CdrMarks** [comment]
I've updated the PR with this commit (https://github.com/WordPress/learn/pull/44/commits/b9abd74faa6280a6b81a162616da9dbbe3f30155) to include this change.

**Comment by hlashbrooke** [comment]
This is done for the home page, but the title on all the sub-pages still say "Help Others Learn WordPress" - those need to be updated too.

**Comment by hlashbrooke** [comment]
CC @StevenDufresne @CdrMarks 

It doesn't look like I have permission to reopen issues, so I can't change the status here.

**Comment by hlashbrooke** [comment]
In the intro text on the home page, "resourses" is incorrect spelling - that should be "resources".

**Comment by CdrMarks** [comment]
@coreymckrill I see on https://learn.wordpress.org/san-diego-troubleshooting-workshop/ the text "Help Others Learn WordPress" which Hugh would like to change to "Learn WordPress".  
![image](https://user-images.githubusercontent.com/3489003/89923455-42444780-dbc6-11ea-8c69-8a2764d97728.png)

I've reviewed **themes/pub/wporg-learn-2020/header.php** and https://learn.wordpress.org/wp-admin/options-general.php, but cannot see where this string is set.

**Comment by coreymckrill** [comment]
> the title on all the sub-pages still say "Help Others Learn WordPress"

Steve fixed this in 39dc428, and it looks right in my local dev environment, but it hasn't been deployed to production yet.
