### ISSUE TITLE
How to Create a Menu with the Navigation Block - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#374]
# Topic Description
Navigate your way around your website with the aid of the navigation block. This tutorial will walk a user through how to create a menu with the navigation block in the site editor of updated 6.4. The tutorial will use the 2024 theme. 

- Adding pages to a current navigation
- Setting up a new navigation menu
- How to move navigation items to different locations
- How to create a second navigation menu to use in a second location such as the footer or sidebar.

# Objective
- Learn the different blocks that can be used within the navigation block. 
- To have the user feel more at ease when creating a website’s navigation menu. 
- To increase awareness of UX/UI design principles and accessibility and how these things make navigating a website easier to use. 

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.

- 5.9 https://learn.wordpress.org/workshop/how-to-create-a-menu-with-the-navigation-block/ ( goes to the Lesson plan link)
- 5.9 https://learn.wordpress.org/tutorial/how-to-create-a-menu-with-the-navigation-block/
- 5.9 https://learn.wordpress.org/lesson-plan/how-to-create-a-menu-with-the-navigation-block/
6.2 https://wordpress.tv/2023/07/12/demystifying-the-navigation-block-how-to-set-up-your-sites-navigation-now-and-in-the-future/

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Tutorial [created](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial) and announced to the team for Q/A review
- [x] Tutorial reviewed and [ready to publish](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial)
- [x] Tutorial [submitted and published to WPTV](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#1-submit-your-video-to-wordpress-tv) 
- [x] Tutorial published on WPTV
- [x] Tutorial [captioned](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#2-generate-subtitles-and-a-transcript-for-your-video) 
- [x] Tutorial [created on Learn.WordPress.org](https://make.wordpress.org/training/handbook/tutorials/publishing-a-tutorial/#3-create-edit-your-workshop-post)
- [x] Tutorial post reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial [announced to Marketing Team](https://docs.google.com/spreadsheets/d/1rY9gyA0KljjlinPE2B0S2qfsN8Nz24_N_KzqB5CrYZM/edit#gid=469255212) for promotion

SEO keywords- 

- navigation block
- how to create a menu
- navigation menu items
- navigation bar
- list view
- select menu

**Comment by courtneyr-dev** [comment]
Needs to be revised: https://github.com/WordPress/gutenberg/pull/37454

**Comment by azhiya** [comment]
Please review https://github.com/WordPress/Documentation-Issue-Tracker/issues/297

**Comment by abhansnuk** [comment]
This is published on Learn WP, and needs some revisions for 6.0. Putting it back into the earlier column, in discussions with Hauwa and Courtney.

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/40413

**Comment by courtneyr-dev** [comment]
https://make.wordpress.org/core/2022/09/16/whats-new-in-gutenberg-14-1-15-september/

**Comment by courtneyr-dev** [comment]
https://www.youtube.com/watch?v=5ovtyIyFOoA&feature=youtu.be&ab_channel=DaveonWP&themeRefresh=1

**Comment by courtneyr-dev** [comment]
https://drive.google.com/file/d/1Xg7WGdjVD6USv73RjI7k_WOF8zQvf_iE/view

**Comment by courtneyr-dev** [comment]
[Fix Navigation block fallbacks and entity saving](https://github.com/WordPress/gutenberg/issues/42799).
[Navigation: Try making it possible for themes to have the X overlay the = icon](https://github.com/WordPress/gutenberg/pull/43576#top).
[Navigation: Try adding minimal animation to overlay.](https://github.com/WordPress/gutenberg/pull/43851#top)
[Add select icon for Navigation Block's menu button](https://github.com/WordPress/gutenberg/pull/43674#top).
[Use page list instead of placeholder as fallback](https://github.com/WordPress/gutenberg/pull/42735#top).

**Comment by Piyopiyo-Kitsune** [comment]
Same here-- will you be working on these revisions @courtneyr-dev as the noted assignee or does this require reassignment?

**Comment by courtneyr-dev** [comment]
6.2 Add List-Based Editing to Navigation Block https://make.wordpress.org/core/2022/11/23/whats-new-in-gutenberg-14-6-23-november/

**Comment by courtneyr-dev** [comment]
6.2 Add List-Based Editing to Navigation Block https://make.wordpress.org/core/2022/11/23/whats-new-in-gutenberg-14-6-23-november/

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/issues/41549

**Comment by ghost** [comment]
@courtneyr-dev Hi Courtney, I know you are at WordCamp so I don't expect a reply until next week. I am interested in taking this tutorial over and doing a revision for 6.2. Do you feel this is still a relevant topic? Do you have any other thoughts about it? Thank you

**Comment by ghost** [comment]
@courtneyr-dev  Hi Courtney, Wes reminded me that I commented on this tutorial and forgot to follow up. I would like to take it over if that is alright with you. Do you feel it is still an important topic for a tutorial?

**Comment by kaitohm** [comment]
@lada7042 I believe this is still a valuable Tutorial to work on. 6.3 introduced even more changes to how folks can edit their navigations within the Editor, and it's content I think many folks will find valuable.

@courtneyr-dev has been out sick for a while. I've gone ahead and re-assigned the content to you. Feel free to work on this as you have time 🙌

**Comment by ghost** [comment]
Started working on this tutorial

**Comment by courtneyr-dev** [comment]
WP 6.4 Visuals: [demo](https://drive.google.com/file/d/1VnCyVCAXhetNSzIiXuOf6TEQHb-HAzEr/view?usp=drive_link) of adding a button to a menu.
Adoption approach: N/A
Key Make Posts/GitHub/Trac Issue(s): Navigation block: add buttons to list of allowed blocks ([53966](https://github.com/WordPress/gutenberg/pull/53966)) 

@lada7042

**Comment by ghost** [comment]
Tutorial ready for review.  



https://github.com/WordPress/Learn/assets/24979729/246ae4be-18da-4040-8b4b-60c0ecb0b825

**Comment by ghost** [comment]
FYI- I know about the watermark. With the free version I only get 1 removal a month so saving it for final publishing.

**Comment by westnz** [comment]
Thank you for updating this tutorial @lada7042 
Great work! The learning outcomes/objectives are clear. The narration audio matches what is shown visually, and I could easily follow the explanations and examples. I think adding a short section about submenus and some of the sidebar settings might be helpful.

**Comment by priyanshi-vijay** [comment]
Hi @lada7042, 
I watched the video, and in my opinion, it's really good! It's easy to understand and teaches a lot. The goals of what you'll learn are clear. The audio matches what you see, so it's easy to follow.

**Comment by itsgajendraSingh** [comment]
Hii @lada7042,
After carefully examining the video, I believe it is exceptionally enlightening and has been conveyed in a manner that makes it easy to grasp.

**Comment by ghost** [comment]
Thank to all the reviewers, @westnz @priyanshi-vijay @itsgajendraSingh for taking the time to review the tutorial. I am going to add about 2 min. of the recommended additions of submenu and sidebar tools. Looking to publish next week.

**Comment by ghost** [comment]
Updated. Minus the watermarks. 

https://github.com/WordPress/Learn/assets/24979729/db45e6a2-3355-4691-8b24-7b977fc79716

**Comment by ghost** [comment]
Published! https://learn.wordpress.org/tutorial/how-to-create-a-menu-with-the-navigation-block-2/

**Comment by ghost** [comment]
Due to an issue. https://github.com/WordPress/Learn/issues/2093#issuecomment-1851254384 I needed to make edits to the video. Here is the updated version. https://github.com/WordPress/Learn/issues/2093#issuecomment-1851254384
