### ISSUE TITLE
⚠️ How to use the Review in Progress column👇

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#377]
The Review in Progress column is for lesson plans, workshops and courses that need to be reviewed for typos, grammar, understandability, completeness, general style, and instructional review.

[Team Guidelines](https://make.wordpress.org/training/handbook/guidelines/)

**To work on one of the issues in this column:**

1. Please assign yourself to the issue. If you are unable to do this, please comment on the issue and a team admin will assign you to the issue.
2. Then follow the checklist or workflow.
3. If any changes are needed or you have any questions, please make comments on the issue.
4. When you're done, update the label 'Review x complete', depending on how many reviews have been completed. 

**Issues move out of this list when the content has gone through:**

1.  An Instructional Review
2. Copyediting
3. Style guide review
4. Final review by Team Admin

The recommended timelines for creating content are:
- 2 weeks to draft content – with weekly check-ins
- 2 weeks for review and publish – with weekly check-ins
If you get stuck or are unable to continue working on the issue, just drop us a message on the GitHub issue.

**Checklist or Workflow **
1. Spelling errors
2. Grammar errors
7. Readability (use a tool such as https://www.perrymarshall.com/grade/, we should stay under 9th grade, but technical stuff may differ)
8. Adherence to the team's style guide https://make.wordpress.org/training/handbook/guidelines/lesson-plan-style-guide/
9. Adherence to the current template
10. Adherence to the current style guide
11. Quality and completeness of information
12. Any technical formatting details needing to be changed in order for the content to be published
13. Slide review or creation
14. Anything else needing attention before publication
15. Checklist: https://docs.google.com/document/d/1GZuIUgEuwTWfAQe9gElFYBwNSD9smUMCvgKjOZFEnwM/edit?usp=sharing
16.  Does the description fairly describe what is covered?
17. Have the objectives been written using [Bloom's Taxonomy](http://www.fresnostate.edu/academics/oie/documents/assesments/Blooms%20Level.pdf)?
18. Have the objectives been met?
19. Does the assessment (quiz) match the objectives?
20. Are the pre-requisite skills really necessary?
21. Will "students" be able to perform the exercises with what has been covered?
22. Does the lesson, workshop or course build from or duplicate material in other lessons, workshops or courses?
23. Instructional Review: https://docs.google.com/document/d/1RMH8l5oCR9acWph83pJO9owTcSWfVIRCm2r0aNw9rPA/edit?usp=sharing

**Comment by fikekomala** [comment]
I added the link to the team's style guide.

**Comment by ghost** [comment]
@courtneyr-dev The link for the Bloom's taxonomy does not work. The link within the google doc does work. https://make.wordpress.org/training/handbook/guidelines/blooms-taxonomy/
