### ISSUE TITLE
Search results: Differentiate between CPTs

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#38]
The search function searches the lesson plans and the workshops, but they are displayed in a single list with no visual distinction - example: https://learn.wordpress.org/?s=block

Could this be updated to show some sort of visual differentiator? Either a highlight of some kind or, better yet, display results in two columns/areas - one for each CPT.

**Comment by angelasjin** [comment]
I think the search function also searches beyond Learn WordPress. Is it supposed to do that? For example: https://learn.wordpress.org/?s=open+source

**Comment by CdrMarks** [comment]
@angelasjin I am seeing search results that include Lesson Plans which are part of this site.  Are you seeing content in the search results **not** from this site?

**Comment by angelasjin** [comment]
On closer inspection, no. But that 2010 post from Jen really surprised me!

**Comment by StevenDufresne** [comment]
@hlashbrooke Do we have any examples within .org that we particularly like?

**Comment by hlashbrooke** [comment]
It would be great if the individual results could use the same design/layout as the plugin search results cards: https://wordpress.org/plugins/search/block/ 

In terms of differentiating between workshops and lesson plans, I don't know of any existing examples elsewhere on .org, but I was thinking the simplest solution could be a different background colour to highlight them. We could even use a green/blue like on the homepage CTAs, but much more faded.
