### ISSUE TITLE
Featured image for workshops

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#39]
Right now, if a featured image is not set for a workshop then nothing is displayed on the frontend. Could this be changed so that, if a featured image is not set, a default generated thumbnail is displayed? Like what you see on the homepage of WPTV: https://wordpress.tv/

**Comment by tellyworth** [comment]
I added a quick implementation for this in #80.

I think the longer-term solution might be for Jetpack to fully support `wordpress.tv` embeds, since I _think_ it's supposed to generate & use automatic featured images for videos.

**Comment by coreymckrill** [comment]
There is an enhancement for this in the works in #89, but the basic functionality for this is now merged, so I'm going to call this fixed.
