### ISSUE TITLE
Managing Settings: Permalinks

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#393]
https://learn.wordpress.org/workshop/managing-settings-permalinks/

**Comment by azhiya** [comment]
Here is the link for the workshop: https://learn.wordpress.org/workshop/managing-settings-permalinks/

**Comment by westnz** [comment]
//lesson

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/ed951406-cb0b-4d6f-874a-a2f85f16fdd8

**Comment by pricelessopoku** [comment]
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Super helpful video @westnz

**Comment by westnz** [comment]
Thank you for reviewing @pricelessopoku

**Comment by westnz** [comment]
//published
