### ISSUE TITLE
Manage Settings: Privacy Policy

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#394]
# Topic Description
Setting up a privacy policy page.

**Comment by westnz** [comment]
//lesson

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/b8d236aa-11a0-4c34-90dd-d05b5f9adf55

**Comment by pricelessopoku** [comment]
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by westnz** [comment]
//published
