### ISSUE TITLE
Customizer: Site Icons and Logos - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#399]
In this lesson you will learn what is a site icon, where they are displayed and how to add one. You'll also learn how to add custom icons to your site.

https://github.com/wptrainingteam/customizer-site-icons-and-logo
https://learn.wordpress.org/lesson-plan/customizer-site-icons-and-logo/

CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit #1
- [ ] Copy edit #2
- [ ] Style guide review
- [ ] Testing #1
- [ ] Testing #2
- [ ] Testing #3
- [ ] Final review
- [ ] Publish

**Comment by azhiya** [comment]
The [lesson plan](https://learn.wordpress.org/lesson-plan/customizer-site-icons-and-logo/) has already been published. We can close this issue.
