### ISSUE TITLE
Dashboard Icons  - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#403]
In this lesson you will learn about dashboard icons, how they are composed, and how your themes, plugins, and posts benefit from using dashboard icons.

https://github.com/wptrainingteam/dashboard-icons

CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit #1
- [ ] Copy edit #2
- [ ] Style guide review
- [ ] Testing #1
- [ ] Testing #2
- [ ] Testing #3
- [ ] Final review
- [ ] Publish

**Comment by azhiya** [comment]
The [Dashboard Icons](https://learn.wordpress.org/lesson-plan/dashboard-icons/) has already been published. We can close this issue.
