### ISSUE TITLE
Customizer: Static Front Page vs. Content Feed - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#404]
https://learn.wordpress.org/lesson-plan/customizer-static-versus-content-front-page/
 Using the Theme Customizer, you can first preview how pages or posts will appear, then save and publish the settings.

https://github.com/wptrainingteam/customizer-static-versus-content-front-page

CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit #1
- [ ] Copy edit #2
- [ ] Style guide review
- [ ] Testing #1
- [ ] Testing #2
- [ ] Testing #3
- [ ] Final review
- [ ] Publish

**Comment by azhiya** [comment]
The [lesson plan](https://learn.wordpress.org/lesson-plan/customizer-static-versus-content-front-page/) has already been published. We can close this issue.
