### ISSUE TITLE
Customizer: Header and Background Images  - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#406]
https://learn.wordpress.org/lesson-plan/customizer-header-background-images/

Using the Theme Customizer, you can easily preview the look and feel of using header and background images across your website, and then save the settings as you decide to use them.

https://github.com/wptrainingteam/customizer-header-background-images

CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit #1
- [ ] Copy edit #2
- [ ] Style guide review
- [ ] Testing #1
- [ ] Testing #2
- [ ] Testing #3
- [ ] Final review
- [ ] Publish

**Comment by azhiya** [comment]
The [Customizer: Header And Background Images](https://learn.wordpress.org/lesson-plan/customizer-header-background-images/) has already been published. Let's close this.
