### ISSUE TITLE
Submit idea button goes to 404

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#41]
The button for submitting a workshop idea goes to a 404 page. This would be valuable to keep in so we can get suggestions for workshops people would like to see.

**Comment by StevenDufresne** [comment]
Yep.

Noting: It's mostly a configuration problem with our environment. We need to create the page and assign it to the existing template.

**Comment by CdrMarks** [comment]
I thought this might be an issue in the production environment, but see the 404 is seen in my local.

Local: 
* http://localhost:8888/submit-workshop-idea 404

Production: 
* https://learn.wordpress.org/submit-workshop-idea/ (presents option to submit a Workshop or Lesson Plan idea)
* Workshop: https://learn.wordpress.org/submit-workshop-idea/ (loops back to the page above)
* Lesson Plan: https://learn.wordpress.org/submit-lesson-idea 404

**Comment by tellyworth** [comment]
This was fixed temporarily in 05a4a10. I think the permanent fix is basically to implement #3.
