### ISSUE TITLE
Backing Up Your WordPress Site - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#418]
https://learn.wordpress.org/lesson-plan/backing-up-your-wordpress-site/

In this lesson you will learn of the fact that your WordPress.org self-hosted website contains physical files and a database, both of which need to be backed up on a regular schedule.

**After completing this lesson, you will be able to:**

* Identify the files of a WordPress installation.
* Perform a backup of physical files.
* Identify and be aware of the difference between FTP and SFTP.
* Export the database using PHPMyAdmin.
* Describe the best practices of maintaining and storing backup files.

https://github.com/wptrainingteam/backing-up-your-wordpress-site

https://make.wordpress.org/training/handbook/user-lessons/backing-up-your-wordpress-site/

https://learn.wordpress.org/lesson-plan/backing-up-your-wordpress-site/

CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit #1
- [ ] Copy edit #2
- [ ] Style guide review
- [ ] Testing #1
- [ ] Testing #2
- [ ] Testing #3
- [ ] Final review
- [ ] Publish

**Comment by azhiya** [comment]
@courtneyr-dev and @webtechpooja we have a [lesson plan](https://learn.wordpress.org/lesson-plan/backing-up-your-wordpress-site/). Can we mark this as published and close the issue?
