### ISSUE TITLE
What is a Theme

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#425]
https://learn.wordpress.org/lesson-plan/what-is-a-theme/

This lesson plan needs to be modified to match the current lesson plan template.

_Issue modified by @bsanevans to remove excess information._

**Comment by azhiya** [comment]
Hi, @HILAYTRIVEDI I think you've already updated this one. Is that correct?

**Comment by HILAYTRIVEDI** [comment]
Hello @azhiya, No I didn't as I think the whole plan needs to be redesigned as there is a lack of clarity and examples in this lesson plan.

**Comment by azhiya** [comment]
Ok, thanks.

**Comment by courtneyr-dev** [comment]
These are the types of themes by name: 

Block theme: a theme made for FSE using HTML templates and theme.json, allowing one to manage all parts of their site with blocks.
Universal theme: a theme that works with both the Customizer and the Site Editor.
Hybrid theme: a classic theme that adopts a feature(s) of FSE, like theme.json or the template editor.
Classic theme: a theme built the way we’ve been used to with PHP templates, functions.php, and more.
