### ISSUE TITLE
Home page CTAs

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#43]
There needs to be a couple of changes to the home page CTAs:

1. Swap the lesson plans and browse workshop CTAs around, so the workshops appear first and the lesson plans second.
2. The description for the workshops CTA must change to this:
 > Workshops are a great way to get hands-on with WordPress. Here are some workshops for you to level up your WordPress skills.

**Comment by hlashbrooke** [comment]
Could you please also do the first item in this issue:

1. Swap the lesson plans and browse workshop CTAs around, so the workshops appear first and the lesson plans second.

CC @coreymckrill since I'm unable to reopen issues.

**Comment by coreymckrill** [comment]
This was fixed [here](https://github.com/WordPress/learn/commit/8d40e45d4546e01670f66f8bf844d052e433ceaf), but somehow the change wasn't reflected on production until now.

**Comment by hlashbrooke** [comment]
I still don't see this fixed in production - or is that just because the code hasn't been pushed to the live site yet?

**Comment by coreymckrill** [comment]
That's weird, I could see the change on production... or maybe it was my wporg sandbox. Dion [added a cache buster](https://github.com/WordPress/learn/commit/832e1008813367a813350ef4f74b8ce7f83de0ae) to the stylesheet, which should fix it for good. What do you see now, @hlashbrooke?

**Comment by hlashbrooke** [comment]
It's working for me now since Dion busted the cache.
