### ISSUE TITLE
Anatomy of a Theme - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#431]
https://learn.wordpress.org/lesson-plan/anatomy-of-a-theme/

In this lesson you'll learn about the different files that make up a theme and how they work together to display your website.

**After completing this lesson, participants will be able to:**

*   Recognize that many files are needed to make a theme.
*   Identify the basic blocks are used in a WordPress theme.
*   Identify the files required to make a WordPress theme.

https://github.com/wptrainingteam/anatomy-of-a-theme

https://make.wordpress.org/training/handbook/theme-school/anatomy-of-a-theme/

[# Topic Description
Write a description of the topic here.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.

- 

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Workshop Development Checklist
- [ ] Workshop is submitted through https://learn.wordpress.org/workshop-presenter-application/
- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the workshop
- [ ] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [ ] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [ ] Workshop published on WPTV
- [ ] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [ ] Workshop created on Learn.WordPress.org
- [ ] Workshop post is reviewed for grammar, spelling, etc.
- [ ] Workshop published on Learn.WordPress.org
- [ ] Workshop announced to training team
- [ ] Workshop announced to creator
- [ ] Workshop announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by azhiya** [comment]
Lesson Plan: https://learn.wordpress.org/lesson-plan/anatomy-of-a-theme/

**Comment by azhiya** [comment]
This item first appeared on the was added to the [January 2022 Sprint ](https://make.wordpress.org/training/2022/01/04/january-2022-sprint/)

**Comment by azhiya** [comment]
Hi @ironprogrammer. Are you still working on this lesson plan?

**Comment by ironprogrammer** [comment]
Hi, @azhiya -- I sincerely apologize for my delayed response. I won't have bandwidth to work on this for a few weeks. If anyone else is available to take this on in the meantime, then please don't let me hold this up any longer 😔

**Comment by kaitohm** [comment]
Closing as next steps aren't clear.
