### ISSUE TITLE
Create a Post with the Block Editor

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/learn#433]
CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Description and Objectives finalized

**Comment by azhiya** [comment]
Workshop: https://learn.wordpress.org/workshop/how-to-create-a-post-or-page-with-the-wordpress-block-editor/
Lesson Plan: https://learn.wordpress.org/lesson-plan/how-to-create-a-post-or-page-with-the-wordpress-block-editor/
