### ISSUE TITLE
What is the difference between WordPress .Com and .Org?Workshop

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#442]
https://learn.wordpress.org/workshop/what-is-the-difference-between-wordpress-org-and-com/

# Topic Description
Write a description of the topic here.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

**Comment by azhiya** [comment]
Workshop: https://learn.wordpress.org/workshop/what-is-the-difference-between-wordpress-org-and-com/

**Comment by westnz** [comment]
Update notes:

- Basically the distinction needs to be made:
  - WordPress = free, open source software you can download and install to build a blog/website
  - [WordPress.org](http://wordpress.org/) = a site where you can download WordPress, also hosts WordPress plugins and themes, you can Learn about WordPress, get support and help, and contribute back to WordPress
  - [WordPress.com](http://wordpress.com/) = a managed WordPress hosting company, where you can pay to host a copy of WordPress, as well as other add ons like domains, backups etc.
- There's some added confusion around the fact that the term "WordPress" is overloaded. It can refer to the FOSS software that you can download and install, but it can also refer to the project as a whole or the community around the project.
- Similarly, "[WordPress.org](http://wordpress.org/)" may refer to the website, but it may also be used to refer to the community of contributors and/or their submitted work. 
- In marketing, they sometimes specify "WordPress project" or "WordPress community," which might be a patch that can be applied to the video scripts.

**Comment by eidolonnight** [comment]
Thanks for posting the conversation summary here @westnz and please consider me a volunteer to review the next iteration of this video.

I do want to add that the current video has been used to explain the differences to folks at Sprout, Facebook, LinkedIn, Twitter, etc. It helped us while we were seeking verification for the [official WordPress social accounts](https://make.wordpress.org/marketing/handbook/social-media-accounts/). So while the existing video might not be _perfect_ it has been extraordinarily beneficial.

**Comment by westnz** [comment]
#2988
