### ISSUE TITLE
Organizing your Media Library Workshop

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#445]
# Topic Description
Write a description of the topic here.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Workshop Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop published on WPTV
- [x] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [x] Workshop created on Learn.WordPress.org
- [x] Workshop post is reviewed for grammar, spelling, etc.
- [x] Workshop published on Learn.WordPress.org
- [x] Workshop announced to training team
- [x] Workshop announced to creator
- [x] Workshop announced to Marketing Team for promotion
- [x] Gather feedback from workshop viewers/participants

**Comment by azhiya** [comment]
Workshop: https://learn.wordpress.org/workshop/organizing-your-media-library/

**Comment by courtneyr-dev** [comment]
Revise to include Copy to clipboard. https://core.trac.wordpress.org/ticket/54426

**Comment by westnz** [comment]
Is "Copy to Clipboard" feature not meant for the "Using the Media Library Workshop": https://learn.wordpress.org/workshop/using-the-media-library/ 

My workshop mainly focuses on organizing your media.

**Comment by westnz** [comment]
Updated for the Intermediate User learning pathway.

**Comment by westnz** [comment]
//published

**Comment by westnz** [comment]
//published
