### ISSUE TITLE
Workshop template doesn't match

### ISSUE THREAD

**Issue by CdrMarks** [WordPress/Learn#45]
I browsed to https://learn.wordpress.org/wp-admin/post.php?post=505&action=edit on production and saw the following message:

>The content of your post doesn’t match the template assigned to your post type.
Screenshot:
![image](https://user-images.githubusercontent.com/3489003/89819696-790c5600-db11-11ea-8edc-8be25b50c576.png)

**Comment by StevenDufresne** [comment]
The `template_lock` that we set for workshops isn't respected. Possible related to https://github.com/WordPress/gutenberg/issues/17262.

If we can get the template lock to work, this shouldn't be an issue.

**Comment by hlashbrooke** [comment]
With the latest updates to the workshop template, this is no longer an issue. Closing this issue.
