### ISSUE TITLE
Using Page Templates - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#455]

**Comment by azhiya** [comment]
Templates workshop: https://learn.wordpress.org/workshop/templates/
Templates lesson plan: https://learn.wordpress.org/lesson-plan/templates/

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/199854036-80b70678-650b-4f9a-9ff4-faec67519d2e.mp4

**Comment by westnz** [comment]
I have updated this tutorial for 6.1. I will create a separate issue for the lesson plan.

**Comment by fikekomala** [comment]
Great work @westnz! I love the transitions.

**Comment by westnz** [comment]
Thank you @fikekomala

**Comment by westnz** [comment]
Updated and published: https://learn.wordpress.org/tutorial/templates/

**Comment by westnz** [comment]
Updated for 6.2

https://user-images.githubusercontent.com/89751452/228998050-3556b91e-589a-4cde-84cb-eaeee3995ebc.mp4

**Comment by ghost** [comment]
Great job on the presentation. This is one of those areas that is so hard for people to grasp the difference between the templates and pages/posts. Wes, you do a great job at breaking the process down into simple steps. The information is very understandable following along from home.

**Comment by kaitohm** [comment]
@westnz This has been open for a couple of months now. Feel free to publish the updated version 👍

**Comment by westnz** [comment]
Hey @bsanevans, I will publish this in June. Thanks for the ping.

**Comment by westnz** [comment]
Updated: https://learn.wordpress.org/tutorial/templates/

**Comment by westnz** [comment]
Updating this for 6.3

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/3fa366b6-bd2f-46b3-ab2d-910cdb7892b0

**Comment by gudrunfrank** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [x ] Learning outcomes/objectives are clear.
- [ x] Technical concepts introduced in the content are accurate.
- [x ] The speed of demonstrations are easy to follow. EXCELLENT!
- [x ] The narration audio matches what is shown visually.
- [x ] Spelling and grammar are correct.
- [x ] Sound quality is consistent throughout the video.
- [ x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Love these basic tutorials for beginners!

**Comment by westnz** [comment]
Thank you so much @gudrunfrank

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/templates/

**Comment by westnz** [comment]
Published in Sensei as part of the draft Beginner User learning pathway.
