### ISSUE TITLE
Workshops: Auto-generated excerpts will always be empty

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/Learn#46]
In #33 we're enabling excerpts for our workshop post type so that it can be used to show a summary of the workshop content in other places on the learn site where a workshop might be featured or called out. However, the `excerpt_remove_blocks` function that gets called during excerpt auto-generation is stripping out all of the workshop content, leaving a blank excerpt. This is because we're using `core/group` blocks in our content template, which `excerpt_remove_blocks` does not support (even though it supports `core/columns`). There's a [Core ticket](https://core.trac.wordpress.org/ticket/47637) about this issue, so it this behavior may change eventually, but in the mean time, we'll need to ensure that all featured workshops have a manual excerpt.

I'm opening this issue to document why our excerpts are blank, and provide a space to discussion alternative solutions (or inspire someone to submit a Core patch!)

**Comment by StevenDufresne** [comment]
Looking at the template, we could implement the layout without the groups. It would couple our CSS with Gutenberg classes which isn't great, but we would get the excerpt back in return.

With that being said, any updates to the templates would require an update to the existing data. I'm not sure what the options our for updating templates within existing content.

**Comment by coreymckrill** [comment]
> Looking at the template, we could implement the layout without the groups. It would couple our CSS with Gutenberg classes which isn't great, but we would get the excerpt back in return.

We might not even have to give up our custom classes. A lot of them could potentially be moved to other blocks (like the Columns block, or the individual nested Column blocks inside) and it may not even change the style hierarchy that much.

> With that being said, any updates to the templates would require an update to the existing data. I'm not sure what the options our for updating templates within existing content.

Yeah, that could end up being a pain. This might be a downside of using block templates instead of hard-coded theme templates for stuff like this. At least right now there aren't that many workshops so it wouldn't take too long to migrate stuff over.
