### ISSUE TITLE
Enqueueing Scripts and Styles - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#467]
https://learn.wordpress.org/lesson-plan/enqueueing-scripts-and-styles/

When you’re creating your theme, you may want to create additional stylesheets or JavaScript files

https://github.com/wptrainingteam/enqueueing-scripts-and-styles
https://github.com/wptrainingteam/enqueueing-scripts-and-styles-reworked

_Issue modified by @bsanevans to remove excess information._

**Comment by courtneyr-dev** [comment]
Revise this to the current lesson plan format and gear it toward classic themes with style.css.

**Comment by kaitohm** [comment]
Closing as low priority.
