### ISSUE TITLE
Template Hierarchy - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#470]
https://learn.wordpress.org/lesson-plan/template-hierarchy/
https://github.com/wptrainingteam/template-hierarchy

_Issue modified by @bsanevans to remove excess information._

**Comment by azhiya** [comment]
This needs to be revised for FSE. @HILAYTRIVEDI I've got you listed down for this. Is that correct?

**Comment by HILAYTRIVEDI** [comment]
Yes, I requested for this but, I didn't get any chance for reviewing this. Is this possible to allocate it to someone else?

**Comment by azhiya** [comment]
Sure, I'll leave it open so that someone can claim it.
