### ISSUE TITLE
Managing Widgets - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#478]
https://learn.wordpress.org/lesson-plan/managing-widgets/
https://github.com/wptrainingteam/managing-widgets

_Issue modified by @bsanevans to remove excess information._

**Comment by courtneyr-dev** [comment]
Revise to include Block themes (FSE)

**Comment by courtneyr-dev** [comment]
Show a related issue: https://github.com/WordPress/gutenberg/issues/39270

**Comment by kaitohm** [comment]
Closing in favor of #647
