### ISSUE TITLE
Troubleshooting Basics - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#479]
https://learn.wordpress.org/lesson-plan/troubleshooting-basics/
https://github.com/wptrainingteam/troubleshooting-basics

_Issue modified by @bsanevans to remove excess information._

**Comment by azhiya** [comment]
Update to include Site Health, plugin and native to Core

**Comment by courtneyr-dev** [comment]
This lesson doesn't follow the format
