### ISSUE TITLE
⚠️ How to use the Ready to Create - You Can Help column 👇

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#492]
These are the lesson plans, workshops and courses in need of a contributor to draft them up. 

**An issue is added to this column by a**
1. Team Admin

**To work on one of the issues in this column:**

1. Pick a topic, any topic!
2. Please assign yourself to the issue. If you are unable to do this, please comment on the issue and a Team Admin will assign you to the issue.
3. If you need access to Learn, comment on the GitHub issue with your .org ID.
4. If you need help creating content, we’ve got some great workshops videos ready for you to learn how to do this:
-- [Lesson plan about lesson plans](https://learn.wordpress.org/lesson-plan/how-to-create-a-lesson-plan/) and [workshops about lesson plans](https://learn.wordpress.org/workshop/how-to-create-a-lesson-plan/)
-- [Workshop about workshops](https://learn.wordpress.org/workshop/how-to-submit-a-workshop/)
5. Then follow the checklist or workflow.
6. If any changes are needed or you have any questions, please make comments on the issue.

**Issues move out of this column:**

1.  By a Content Creator when they have taken ownership of an issue.
2. If the Team decide not to pursue the idea at which point the issue can be closed or moved back to the "Ideas" column.

The recommended timelines for creating content are:
- 2 weeks to draft content – with weekly check-ins
- 2 weeks for review and publish – with weekly check-ins
If you get stuck or are unable to continue working on the issue, just drop us a message on the GitHub issue.

**Useful Resources**
[Lesson Plans](https://make.wordpress.org/training/handbook/lesson-plans/)
[Workshops](https://make.wordpress.org/training/handbook/workshops/)
[Courses](https://make.wordpress.org/training/handbook/courses/)

**Comment by ghost** [comment]
The link for Workshops under Useful Resources is broke. I assume this would be the correct link. https://make.wordpress.org/training/handbook/online-workshops/planning-an-online-workshop/
