### ISSUE TITLE
Migrate, Copy, or Clone a Site - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#494]
https://learn.wordpress.org/lesson-plan/migrate-copy-or-clone-a-site/

_Issue modified by @bsanevans to remove excess information._

**Comment by courtneyr-dev** [comment]
Needs to follow the lesson plan template, revisions are likely needed.

**Comment by yuliyang** [comment]
I will work on updating this lesson plan to new outlined format.

**Comment by yuliyang** [comment]
I updated it to the new outlined format.
This lesson plan is lacking some section content like Readiness Questions, Materials Needed, Exercises, and Assessment.

**Comment by kaitohm** [comment]
Thank you for updating the format, @yuliyang .

Would you like to fill in those empty sections and have someone review it for you? Or would you like to request someone else to work on that?

**Comment by yuliyang** [comment]
@bsanevans It would be great if someone could pick this up.

**Comment by kaitohm** [comment]
No problem, Yuli 👍 

## Next steps

This lesson plan is lacking some section content like Readiness Questions, Materials Needed, Exercises, and Assessment. We're looking for a content creator to fill these sections in, following the Lesson Template shown in the team handbook: https://make.wordpress.org/training/handbook/lesson-plans/lesson-plan-template/
