### ISSUE TITLE
Keeping WordPress Sites Secure

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#498]
In this lesson, you will learn how to keep your WordPress site secure. You may ask yourself, "Do I even need to worry about keeping my WordPress site secure?" And the answer would be, "Yes!" Most people think that they could never be hacked, but you will find that it can happen to anyone. By taking a few precautions you will gain not only security but a fair measure of peace of mind.

https://github.com/wptrainingteam/keeping-wordpress-sites-secure

_Issue modified by @bsanevans to remove excess information._

**Comment by kaitohm** [comment]
A lesson plan draft is created at the link above. We're looking for a content creator who will use this as a starting place to build out a lesson plan, aimed at beginner developers.

**Comment by kaitohm** [comment]
Closing issues marked with "Brand" in preference of creating Learning Path content.
