### ISSUE TITLE
Introduction to Common Plugins - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#503]
https://learn.wordpress.org/lesson-plan/introduction-to-common-plugins/

# Topic Description
In this lesson you will learn how plugins add functionality to your website. There are various plugins that can be used for: social media, backup, analytics, security, caching, etc. These plugins can benefit your WordPress site.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.

- https://github.com/wptrainingteam/introduction-to-common-plugins

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Development Checklist:
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the example lesson walk-through
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Announce to the Training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

# Repo Structure and Lesson Plan Template

> <span style="color:red">Please remove all blockquote comments such as this before publishing.</span>

## Description

> A short paragraph explaining what is covered in the lesson plan. This should be text that can be copied and used in a meetup or workshop description.

## Objectives

After completing this lesson, participants will be able to:

* Describe the benefits of installing the various Plugins on your site.
* Install Plugins that will be beneficial to your WordPress site.

> It’s required that you include a bulleted list of objective(s) for each lesson plan. Objectives should be worded as actions that the participant can do once they’ve finished. See [Bloom's Taxonomy of Action Verbs](http://www.fresnostate.edu/academics/oie/documents/assesments/Blooms%20Level.pdf) (PDF) as a reference. Avoid using words like "know," "understand," "be introduced to," etc. There should be one assement item for each objective (see below).

## Target Audience

Who is this lesson intended for? What interests/skills would they bring? Put an "x" in the brackets for all that apply.

* [ ] Users / Content Writers
* [ ] Designers
* [ ] Developers
* [ ] Speakers
* [ ] Organizers
* [ ] Kids

## Experience Level

How much experience would a participant need to get the most from this lesson? Put an "x" in the brackets for all that apply.

* [ ] Beginner
* [ ] Intermediate
* [ ] Advanced

## Type of Instruction

Which strategies will be used for this lesson plan? Put an "x" in the brackets for all that apply.

* [ ] Demonstration
* [ ] Discussion
* [ ] Exercises
* [ ] Feedback
* [ ] Lecture (Presentation)
* [ ] Slides
* [ ] Show & Tell
* [ ] Tutorial

## Time Estimate (Duration)

How long will it take to present this lesson? Put an "x" in the brackets for the one that applies.

* [ ] 1 hour or less
* [ ] 2-4 hours (half-day)
* [ ] 5-8 hours (full-day)
* [ ] 2 days
* [ ] 3 days or more

## Prerequisite Skills

Participants will get the most from this lesson if they have familiarity with:

* Skill 1
* Skill 2

> _For example:_
>
> *   Experience with HTML and CSS
> *   Completed the Basic WordPress Concepts lesson

## Readiness Questions

* Question 1
* Question 2

> A list of questions for participants to see if they have the background and skills necessary to learn and understand the lesson.
>
> _For example:_
>
> *   Do you want to makes changes to your theme yourself?
> *   Do you know how to write CSS?

## Slides

> Change the `/repo-name/` in the link to match the URL name of this repo.

*   [Slides](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/) (files included in this repo)

## Materials Needed

* Item 1
* Item 2

> A list of files, resources, equipment, or other materials the presenter will need for the lesson.
>
> _For example:_
>
> *   A local install of WordPress
> *   The files for the TwentySixteen theme

## Notes for the Presenter

* Note 1
* Note 2

> A list of any handy tips or other information for the presenter.
>
> _For example:_
>
> *  Participants may need to download the TwentySixteen theme before beginning
> *  What to do if there’s no projector or internet available
> *  What to do if a participant doesn’t have the necessary set up
> *  How to handle different opinions about the topic

## Lesson Outline

* First do this
* Then move on to this
* Finish with this

> The plan for the lesson. Outline form works well.
>
> _For example:_
>
> * Talk about what a theme is
> * Demonstrate how to install and activate a theme
> * Practice exercises to have participants find and install a theme on their own site

## Exercises

**Exercise name**

Short description of what the exercise does and what skills or knowledge it reinforces.

*   Short point or step of the exercise
*   And another one

> These are short or specific activities that help participants practice certain components of the lesson. They should not be fully scripted exercises, but rather something that participants could do on their own. For example, you can create an exercise based on one step of the Example Lesson.

## Assessment

There should be one assement item (or more) for each objective listed above. Each assessment item should support an objective; there should be none that don't.

**Write out the question.**

1.  Option
2.  Option
3.  Option
4.  Option

**Answer:** 3\. Correct answer

> A few questions to ask participants to evaluate their retention of the material presented. They should be a measure of whether the objectives were reached. Consider having a question for each objective.

## Additional Resources

* Resource 1
* Resource 2

> An optional section which can contain a list of resources that the presenter can use to get more information on the topic.
>
> _For example:_
>
> * Link to information on the Codex
> * Theme Review Team's Handbook

## Example Lesson

> An example of how the lesson plan can be implemented. Written in script form as one possible way an presenter might use this lesson plan at an event, with screenshots and instructions if necessary.

### Section Heading for Example Lesson

> You will likely need to break the Example Lesson down into multiple sections.

### Lesson Wrap Up

![](https://raw.githubusercontent.com/wptrainingteam/contributor-resources/master/images/lightbulb.png) Follow with the [Exercises](#Exercises) and [Assessment](#Assessment) outlined above.

**Comment by Kemmy99** [comment]
Can i work on this lesson plan please?

**Comment by Kemmy99** [comment]
Hi Hauwa
Welcome back. We sure missed you. Thanks for assigning me to this lesson
plan. How do I start writing the lesson plans on Github?. Please kindly
help.

Thank you,
Kemi

**Comment by azhiya** [comment]
hi @Kemmy99 glad to be back. 

There is an existing [Lesson Plan](https://learn.wordpress.org/lesson-plan/introduction-to-common-plugins/) but it looks like a revision is required. I'm not clear as to what. @courtneyr-dev are you able to confirm what needs to be amended on this lesson plan?

**Comment by Kemmy99** [comment]
Hello @courtneyr-dev please what am i to do with this lesson plan, is it to revise or to write? Thanks!

**Comment by azhiya** [comment]
Hi @Kemmy99 I've added the link to the [Google doc](https://docs.google.com/document/d/1Rrs3WvS3CcV5pOLzQuaP80LUsjjMGFbnw-V846Z03z0/edit?usp=sharing) that you put in Slack. Please update this on the Lesson plan and repost it for review. Don't forget if you are working on any content that has already been published, please check out the plugin[ #meta](https://make.wordpress.org/training/tag/meta/) created for us, it’s like a pull request inside the WP editor.

**Comment by Kemmy99** [comment]
Hello Hauwa,
Trust you are fine. i could not post the Lesson plan on
https://learn.wordpress.org/wp-admin/post-new.php?post_type=lesson-plan
because the Re-usable block template is not showing on my own dashboard. Is
there something i am doing wrongly. I have the Re-useable block on Make but
not on Learn.
Thanks
Kemi Makinde

**Comment by azhiya** [comment]
This issue was discussed in https://wordpress.slack.com/archives/C02RW657Q/p1657041079937669?thread_ts=1657040617.057159&cid=C02RW657Q

**Comment by Kemmy99** [comment]
Hi @azhiya i watched the video you sent me for the lesson plan. i have a screen shot of what my dashboard looks like and the updates on my dashboard. I have watched the video many times to be sure i am doing what is right
![Update dashboard](https://user-images.githubusercontent.com/90468756/177765695-b24269b4-3fca-46f5-831b-60576a3b3e37.png)
Please check

**Comment by Kemmy99** [comment]
Hello @azhiya i checked in my WordPress dashboard and i found this
Choosing And Installing Plugins. It has already been written, do you want me to summarise it or what? I dont really understand what to do. i am trying to get it right please.
![Choosing and installing plugins](https://user-images.githubusercontent.com/90468756/177909631-aa2e8de0-62c6-4ba0-b4f2-172135bbcf43.png)
The image shows what i have gotten on it on my dashboard. Thanks

**Comment by azhiya** [comment]
Hi @Kemmy99 my understanding is that you are updating the current [lesson plan](https://learn.wordpress.org/lesson-plan/introduction-to-common-plugins/) on Learn. Is that correct?

**Comment by Kemmy99** [comment]
Good morning Hauwa,
I asked a question on the Github about this update but I didn't get any
response. The lesson plan is totally different from what already exist. I
need clarification on it.

Thanks.

**Comment by webtechpooja** [comment]
Hello @Kemmy99, 

What are you looking to change/update in this lesson plan? Could you please share your thoughts on this?

The only thing I noticed in this lesson plan is missing the example lesson.

AFAIK this lesson plan is updated 4-5 months ago. and Somehow we missed closing this issue.

Thanks

**Comment by Kemmy99** [comment]
Hello Hauwa,
Its good to hear from you after a year. I have been off the group for a
year. I was pregnant at that time but lost the baby, so I just took time
off for myself.
I want to come back but I realise I am lost in the pull of information.
Where can I start from especially now that I know what I want to be doing
for the group?
I am not  a tech person, am into communication but I can translate our
lesson plans to Pidgin.
Where do I fit in again and where do I start from?

Thank you for reaching out to me.

Kemi Makinde ( Rushina)

**Comment by kaitohm** [comment]
Hi Kemi. Wow, I'm so sorry to hear of your loss. What a rough time you've had.
Let me connect with you in Slack. I'd like to help you get up to speed with translating content again. We can discuss next steps there.
