### ISSUE TITLE
Applying Duotone Filters to Change Color Effects - Workshop

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#513]
Workshop is submitted through https://learn.wordpress.org/workshop-presenter-application/

# Topic Description
Write a description of the topic here.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.

- https://learn.wordpress.org/lesson-plan/use-duotone-filters-to-change-color-effects/
- https://github.com/WordPress/gutenberg/issues/40061

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Workshop Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop published on WPTV
- [x] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [x] Workshop created on Learn.WordPress.org
- [x] Workshop post is reviewed for grammar, spelling, etc.
- [x] Workshop published on Learn.WordPress.org
- [x] Workshop announced to training team
- [x] Workshop announced to creator
- [x] Workshop announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by courtneyr-dev** [comment]
@westnz note https://github.com/WordPress/gutenberg/issues/40061

**Comment by westnz** [comment]
Please provide feedback by Thursday, 21 April 😃 Here is the [link](https://wordpress.slack.com/archives/C02RW657Q/p1649841435685499) to video in Slack.

**Comment by courtneyr-dev** [comment]
This looks good @westnz . Great work including the latest updates.

**Comment by westnz** [comment]
Thanks @courtneyr-dev!

**Comment by westnz** [comment]
This can be marked off of the May Sprint.

**Comment by abhansnuk** [comment]
Label reviewed for review in discussion with Courtney and Hauwa, has been reviewed.

**Comment by abhansnuk** [comment]
@westnz we are doing a lot of cross-collaboration for the release with documentation and Learn WordPress. It would be very helpful if you could add the following onto this issue, and any others with a priority for any you have done for 6.0 please. Thanks so much. A week to go, thanks for all you're doing to get the 6.0 items through.

- Could you please put the published link to workshops in the GitHub issue once it is published.

- The workshop needs to be the same name as the lesson plan, and the GitHub title needs to reflect the same.  Could you please update this GitHub issue. Thanks.

**Comment by westnz** [comment]
Published Workshop: https://learn.wordpress.org/workshop/applying-duotone-filters-to-change-color-effects/

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/40435
See also: https://make.wordpress.org/core/2022/04/28/whats-new-in-gutenberg-13-1-27-april/
Minor screenshot revision needed

**Comment by courtneyr-dev** [comment]
Add how to unset: https://github.com/WordPress/gutenberg/pull/39564

**Comment by Piyopiyo-Kitsune** [comment]
@westnz will you be working on these revisions or does this require reassigment?

**Comment by westnz** [comment]
Thanks, Desinty. I have taken note of this, but will only get to this a bit later. There are some other things that are taking precedence.

**Comment by westnz** [comment]
[Updated](https://learn.wordpress.org/tutorial/applying-duotone-filters-to-change-color-effects/) with small UI changes in the text portion with explanation + screenshots as [discussed ](https://make.wordpress.org/training/2022/05/27/training-team-meeting-may-24-26/)in the Training Team.

**Comment by abhansnuk** [comment]
Can we remove the 'priority low' label to this now that it is published? We could do this for other items too. Thanks.

**Comment by courtneyr-dev** [comment]
6.3 https://make.wordpress.org/core/2023/03/13/whats-new-in-gutenberg-15-3-13-march/#leveling-up-duotone

- Duotone: Use the style engine to generate CSS for Duotone. ([48281](https://github.com/WordPress/gutenberg/pull/48281))
- Duotone: Add Global Styles controls for blocks that support duotone. ([48255](https://github.com/WordPress/gutenberg/pull/48255))
- Use Duotone presets in block duotone attributes. ([48318](https://github.com/WordPress/gutenberg/pull/48318))
- Duotone: Use CSS variables instead of slugs in block attributes. ([48426](https://github.com/WordPress/gutenberg/pull/48426))

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/49838 6.3

Finally, Duotone styles are now generated using the [WordPress Style Engine](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-style-engine/), meaning that CSS is generated as part of the block supports CSS — rather than inline. 

Visuals: [image of Duotone Styles interface](https://drive.google.com/file/d/1uy7CxgzfLew5XJbAWYifsGxeQvgP2kdB/view?usp=sharing)

**Comment by westnz** [comment]
I will work on updating this tutorial this week.

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/6e2c10e2-f781-4cc6-8c94-4ab81241ab74

**Comment by digitalchild** [comment]
@westnz Another tutorial well done. Yet another feature I didn't know about. As per the checklist, everything is all good!

## Tutorial Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by westnz** [comment]
Thank you so much @digitalchild 👍

**Comment by Rashigupta2999** [comment]
Hi @westnz ,

I believe this video is fantastic for anyone looking to grasp the concept of the duotone filter. You've done a great job explaining the key points in a straightforward manner. 

Revision
There is a minor spelling mistake on the first slide where "Duotone" is spelled incorrectly in the Learning Outcomes slide. Could you please correct it?

**Comment by westnz** [comment]
Thank you, @Rashigupta2999. I will update those slides!

**Comment by westnz** [comment]
Thanks for the feedback. I will publish it this week.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/applying-duotone-filters-to-change-color-effects/
