### ISSUE TITLE
Finding Images Using Openverse - Workshop

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#515]
https://learn.wordpress.org/workshop/finding-images-using-openverse/

Workshop is submitted through https://learn.wordpress.org/workshop-presenter-application/

CHECKLIST: Workshop Development Checklist
- [x] Provide feedback of the idea
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop created
- [x] Workshop published on WPTV
- [x] Workshop created on Learn.WordPress.org
- [x] Lesson plan has been published
- [x] Vetted by instructional designers for content idea
- [x] Vetted by deputies for contributor reputation
- [x] Workshop published on Learn.WordPress.org
- [x] Workshop announced to training team
- [x] Workshop announced to creator
- [x] Workshop announced to Marketing Team for promotion
- [x] Workshop post is reviewed for grammar, spelling, etc.
- [x] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [ ] Gather feedback from workshop viewers/participants

**Comment by azhiya** [comment]
Hi, @parajapatisagr do you also want to create the video workshop?

**Comment by courtneyr-dev** [comment]
Marcus is already working on this.

**Comment by mburnette** [comment]
I'll take it :)

**Comment by mburnette** [comment]
Finally ready for feedback on this one! Link to [video in Slack](https://wordpress.slack.com/archives/C02RW657Q/p1650414001398659).

**Comment by hlashbrooke** [comment]
This is really great @mburnette - I love it!

I only have two items of feedback for things that I feel could be improved:

1. To make the title more helpful to people who may not already know about Openverse, I would suggest changing it to "Finding Images Using Openverse" or something similar.
2. The final where you show how to add images on WordPress.com could really just be summarised after the Jetpack demo by saying "this also works on WordPress.com" - this would not just keep us out of the muddy waters of .com/.org, but also the UI in the .com demo is identical to the Jetpack one, so it just feels like a repetition of the video.

Other than that - this is great - I like your pacing as it keeps things clear, and your screencasts are really effective, particularly with the zooming in to the relevant area of the UI that you're working with. Excellent work!

**Comment by westnz** [comment]
This is fantastic @mburnette!  My only comment was already addressed by @hlashbrooke under point 2.

**Comment by mburnette** [comment]
[Updated version](https://wordpress.slack.com/archives/C02RW657Q/p1650468980833459?thread_ts=1650414001.398659&cid=C02RW657Q) ready to review in Slack.

**Comment by courtneyr-dev** [comment]
Well done Marcus. Title switch makes sense here, but it's important we then rename the issue here in GitHub (we're all learning together) to make it easier to find.

**Comment by hlashbrooke** [comment]
The updated workshop is solid - I love it! I'm happy for this to go live according to the guide here: https://make.wordpress.org/training/handbook/workshops/publishing-a-workshop/ 🎉
