### ISSUE TITLE
Creating a Front Page in Block Themes - Workshop

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#516]
Workshop is submitted through https://learn.wordpress.org/workshop-presenter-application/
Lesson Plan https://learn.wordpress.org/wp-admin/post.php?post=11867

CHECKLIST: Workshop Development Checklist
- [x] Provide feedback of the idea
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop created
- [x] Workshop published on WPTV
- [x] Workshop created on Learn.WordPress.org
- [ ] Lesson plan has been published
- [x] Vetted by instructional designers for content idea
- [x] Vetted by deputies for contributor reputation
- [x] Workshop published on Learn.WordPress.org
- [ ] Workshop announced to training team
- [x] Workshop announced to creator
- [ ] Workshop announced to Marketing Team for promotion
- [x] Workshop post is reviewed for grammar, spelling, etc.
- [x] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [ ] Gather feedback from workshop viewers/participants

**Comment by wparasae** [comment]
This should be marked as completed I think; I'm not sure what next steps are for marketing and other things, so if there are steps I'm missing after the publication of this (or if I did this wrong at all!) please do let me know. Trying to be better about doing things the right way!

**Comment by westnz** [comment]
Published Tutorial: https://learn.wordpress.org/tutorial/creating-a-front-page-for-a-block-theme/

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/42331#top
