### ISSUE TITLE
Template Tour - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#517]
Workshop is submitted through https://learn.wordpress.org/workshop-presenter-application/
Lesson Plan https://learn.wordpress.org/lesson-plan/template-tour/

CHECKLIST: Workshop Development Checklist
- [x] Provide feedback of the idea
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop created
- [x] Workshop published on WPTV
- [x] Workshop created on Learn.WordPress.org
- [ ] Lesson plan has been published
- [ ] Vetted by instructional designers for content idea
- [ ] Vetted by deputies for contributor reputation
- [ ] Workshop published on Learn.WordPress.org
- [ ] Workshop announced to training team
- [ ] Workshop announced to creator
- [ ] Workshop announced to Marketing Team for promotion
- [ ] Workshop post is reviewed for grammar, spelling, etc.
- [x] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [ ] Gather feedback from workshop viewers/participants

**Comment by jonathanbossenger** [comment]
@courtneyr-dev I'm just thinking about what would make the most sense here.

I notice that the lesson plan is using 2013, so classic theme and PHP. However, we're now coming up to the second default block theme in TT3. 

So I'm thinking this for this tutorial it might be a good idea to cover the following:
- Introduction: What are Templates? (this can be the same content from the lesson plan, updated to include block themes
- Templates in Twenty Twenty-One
- Features Commonly Found in WordPress Classic Templates
- A Tour of page.php in Twenty Twenty-One
- Templates in Twenty Twenty-Two (or Three as it will probably be released by the time I record this)
- Features Commonly Found in WordPress Block Templates
- A Tour of page.html in Twenty Twenty-Two (or Three)
- A quick introduction to developing themes in the Site Editor

I'd love to hear your thoughts.

**Comment by jonathanbossenger** [comment]
I think we might need to split this into two tutorials, as it ends up being quite a long video...

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/203580982-ddb5aa87-bcfe-482c-809a-adc436436b48.mp4

I excluded the section on "A quick introduction to developing themes in the Site Editor" and was able to get a video tutorial down to under 10 minutes, which I think is ok for this topic.

**Comment by westnz** [comment]
Great job at keeping it under 10 minutes!

You are becoming a pro at using annotations. 

Suggestion:
0:40 -  1:41 Adding separate slides for each point.  When the slide came up, I started reading and couldn't focus on what was being said. You were still talking about point 1 while I was reading about the other points. 😄  Ensuring that each point correlates with what is being said helps a learner focus. I hope that makes sense 👍 

I find the 'slide transition' which you used a few times in the first part of the tutorial a bit strenuous on my eyes.  Please ignore if you don't agree. 😉

**Comment by jonathanbossenger** [comment]
Thanks for the feedback @westnz 

> Suggestion:
0:40 - 1:41 Adding separate slides for each point. When the slide came up, I started reading and couldn't focus on what was being said. You were still talking about point 1 while I was reading about the other points. 😄 Ensuring that each point correlates with what is being said helps a learner focus. I hope that makes sense 👍

Yeah, I'm so used to having code and its output to work with, I struggle when it comes to regular slides 😁 I think what I need to do there is animate each point in the slide as I start talking about it.

> I find the 'slide transition' which you used a few times in the first part of the tutorial a bit strenuous on my eyes. Please ignore if you don't agree. 😉

I'm using the default "Slide from Right" transition that ships with a new Google Slides presentation, so I'm open to alternative suggestions. I'm also wondering if this might be an after-effect of the process of rendering the video. I'll try and re-record the slide deck section and see if that helps with the transition.

**Comment by westnz** [comment]
Great stuff

You could also try out the gradient wipe in Camtasia:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/89751452/204365138-d2bbd3d3-eb13-46f7-86a4-755246bf4fc0.png">

**Comment by jonathanbossenger** [comment]
Quick update here, I tried to update just the slides section by importing each slide as an image, but it looks worse. 

In the future, I'll not apply transitions/animations in the slides, and then rather apply those transitions and animations in Camtasiam but for this video, I'm leaving it as is.

**Comment by westnz** [comment]
All good, Jonathan. Thanks for the update.

**Comment by jonathanbossenger** [comment]
This tutorial has been published https://learn.wordpress.org/tutorial/wordpress-theme-template-tour/
