### ISSUE TITLE
Using theme.json with classic themes - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#520]
Workshop is submitted through https://learn.wordpress.org/workshop-presenter-application/

CHECKLIST: Workshop Development Checklist
- [x] Provide feedback of the idea
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop created
- [ ] Workshop published on WPTV
- [x] Workshop created on Learn.WordPress.org
- [ ] Lesson plan has been published
- [ ] Vetted by instructional designers for content idea
- [ ] Vetted by deputies for contributor reputation
- [x] Workshop published on Learn.WordPress.org
- [ ] Workshop announced to training team
- [ ] Workshop announced to creator
- [ ] Workshop announced to Marketing Team for promotion
- [ ] Workshop post is reviewed for grammar, spelling, etc.
- [ ] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [ ] Gather feedback from workshop viewers/participants

**Comment by jonathanbossenger** [comment]
Relevant handbook doc - https://developer.wordpress.org/themes/advanced-topics/theme-json/#a-theme-json-can-be-added-to-any-theme

**Comment by jonathanbossenger** [comment]
Now that I've brought myself up to speed on block theme development, I'd like to tackle this one.

**Comment by jonathanbossenger** [comment]
Complete list of add_theme_support settings in theme.json

https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#backward-compatibility-with-add_theme_support

**Comment by jonathanbossenger** [comment]
Script - https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/theme-json-classic-themes.md

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/211569343-3ff8e11e-4892-4c30-8f47-225d2a6dd069.mp4

Tutorial ready for review

**Comment by westnz** [comment]
Review:

Solid video tutorial Jonathan!

I like how you familiarise the learner before moving to the lesson's core. 

I suggest slowing down the transition from 2:00 - 2:01 + 3:46 - 3:47 a bit so that the person watching can digest it before moving on.

PS: Remember to add a heading named 'Resources' and the links to the 'Introduction to theme.json' Tutorial + the 'Backward compatibility with add_theme_support' doc when you create the post.  But you probably already knew that :-)

**Comment by jonathanbossenger** [comment]
Thanks @westnz 

```
I suggest slowing down the transition from 2:00 - 2:01 + 3:46 - 3:47 a bit so that the person watching can digest it before moving on.
``` 

Thanks, will pad these out by a few seconds. 

```
PS: Remember to add a heading named 'Resources' and the links to the 'Introduction to theme.json' Tutorial + the 'Backward compatibility with add_theme_support' doc when you create the post. But you probably already knew that :-)
```

Also, it's worth noting [that in the script](https://github.com/jonathanbossenger/wp-content/blob/main/tutorials/theme-json-classic-themes.md), which I am including using the new "tutorial content format for developer-focused tutorials", I also link to the relevant documentation and links when those items are being discussed.

**Comment by jonathanbossenger** [comment]
Published https://learn.wordpress.org/tutorial/using-theme-json-with-classic-themes/
