### ISSUE TITLE
Finding Images Using the WordPress Photo Directory - Workshop

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#522]
https://learn.wordpress.org/workshop/finding-images-using-the-wordpress-photo-directory/

Workshop is submitted through https://learn.wordpress.org/workshop-presenter-application/

CHECKLIST: Workshop Development Checklist
- [x] Provide feedback of the idea
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop created
- [x] Workshop published on WPTV
- [x] Workshop created on Learn.WordPress.org
- [x] Lesson plan has been published
- [x] Vetted by instructional designers for content idea
- [x] Vetted by deputies for contributor reputation
- [x] Workshop published on Learn.WordPress.org
- [x] Workshop announced to training team
- [x] Workshop announced to creator
- [x] Workshop announced to Marketing Team for promotion
- [x] Workshop post is reviewed for grammar, spelling, etc.
- [x] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [ ] Gather feedback from workshop viewers/participants

**Comment by azhiya** [comment]
hi, @courtneyr-dev is Marcus also working on this one?

**Comment by guptaanillg** [comment]
Hi @azhiya — I am happy to work on this task unless someone is already working on it.

**Comment by courtneyr-dev** [comment]
Yes, Marcus is (team rep for Photos). I'll ask him to comment here so we can assign. We're just getting fully up to speed assigning issues here. Sorry for any confusion.

**Comment by mburnette** [comment]
Hey there! Happy to do this as well 👍

**Comment by mburnette** [comment]
[WordPress Photo Directory workshop video](https://wordpress.slack.com/archives/C02RW657Q/p1650469160805559) finally ready to be reviewed in Slack :)

**Comment by courtneyr-dev** [comment]
This one looks great as well @mburnette . Thank you! Do we need one other for how to submit photos? I'm thinking there might've been one made/shared from the Marketing team when the directory launched, but could be wrong.

**Comment by mburnette** [comment]
As far as I know, one has not been created for submitting photos. It's next up on my list, though.
