### ISSUE TITLE
Lesson - Taking Advantage of Query Loops

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#524]
https://learn.wordpress.org/workshop/taking-advantage-of-query-loops/
Workshop is submitted through https://learn.wordpress.org/workshop-presenter-application/

//tutorial

**Comment by azhiya** [comment]
Please review for https://github.com/WordPress/Documentation-Issue-Tracker/issues/283

**Comment by westnz** [comment]
The UI has changed slightly when you add a Query Loop block.  You now select 'choose' or 'start blank' at the start.  I see colours are also an option in the sidebar settings now. 
<img width="899" alt="image" src="https://user-images.githubusercontent.com/89751452/167917495-fa34c71b-90ff-4b4a-8c8e-654f3872e5be.png">

**Comment by westnz** [comment]
Dear Team!  @courtneyr-dev @azhiya I have updated the [workshop ](https://learn.wordpress.org/workshop/taking-advantage-of-query-loops/)and re-recorded sections, and audio, to include the new UI for the 6.0 release.  It is a massive task updating a workshop as you also need to re-create the video, subtitles, transcript etc.

**Comment by azhiya** [comment]
Thanks @westnz I'll move this to ready for review. I wonder what is the best way to manage this. Do we just create a whole new video or append a smaller video with the amendments?

**Comment by westnz** [comment]
Hi @azhiya!  That was the hardest part.  I had to create a new video (editing parts), redo the transcript, redo the subtitles etc.  It takes almost just as long to update a video as to create a new one.  Something to discuss moving forward as doing that doesn't seem sustainable moving forward.  You have made a very good suggestion.

**Comment by azhiya** [comment]
Hey @westnz I feel your pain, having to revise this just for that minor change in my opinion is not the right way to manage this. I'd be happy with just a note. I've put this on the agenda for next week.

Everything else looks good to go.

**Comment by westnz** [comment]
Awesome!  Thank you so much @azhiya

**Comment by westnz** [comment]
Link to workshop: https://learn.wordpress.org/workshop/taking-advantage-of-query-loops/

**Comment by courtneyr-dev** [comment]
6.1: patterns with the Query Loop, which reflects the intended post type, and the tools panel has been adopted to better consolidate the number of filters shown by default. Finally, folks who extend the Query Loop can also use an allowedControls property to determine what filters appear in variations to refine the UI based on their unique variation.

Visuals: [parent filter video](https://drive.google.com/file/d/11PqK90GxxULlsUd7pGVbl0XnSqnOkU4Q/view?usp=sharing), [tools panel video](https://drive.google.com/file/d/1U7kDLQ6YgSsnGJtqd8gzKKZyGg2GHHIc/view?usp=sharing).

Code examples: [video exploring registering a variation and including specific patterns](https://www.youtube.com/watch?v=oMBZViYiTvc) with [JS for registering a Query Loop variation](https://github.com/ryanwelcher/twitch/blob/trunk/themes/twitch-theme/variations/index.js) and [PHP for registering a pattern can be used with the variation](https://github.com/ryanwelcher/twitch/blob/trunk/themes/twitch-theme/functions.php#L42).

Adoption approach: opt-in.

Key Make Posts/GitHub/Trac Issue(s):

https://github.com/WordPress/gutenberg/pull/44093#top.
https://github.com/WordPress/gutenberg/pull/40933#top for querying pages.
https://github.com/WordPress/gutenberg/pull/43590#top.
UX: https://github.com/WordPress/gutenberg/pull/42629 to better organize the experience of working with filter options.
UX: https://github.com/WordPress/gutenberg/pull/43285#top for a more intuitive and predictable experience.
https://github.com/WordPress/gutenberg/pull/43632#top, which allows extenders to determine which controls show up for variations.
https://github.com/WordPress/gutenberg/pull/44137.

**Comment by westnz** [comment]
Will work on updating the tutorial this week.

**Comment by westnz** [comment]
New version. I re-recorded the whole tutorial and have made updates:

https://user-images.githubusercontent.com/89751452/204705407-5917a128-edb0-4c49-b34e-74685bccf3ff.mp4

**Comment by fikekomala** [comment]
I like how the video is structured, @westnz!
One thing, there's a long period of silence from 0:38-0:40, this is very minor, though.

**Comment by westnz** [comment]
Thank you @fikekomala

**Comment by westnz** [comment]
Update published: https://learn.wordpress.org/tutorial/taking-advantage-of-query-loops/

**Comment by courtneyr-dev** [comment]
WP 6.4 
Visuals: [YouTube video explaining improved pagination feature](https://youtu.be/y7YHFncLvD4).
Adoption approach:
Key Make Posts/GitHub/Trac Issue(s): Query block: Client-side pagination ([53812](https://github.com/WordPress/gutenberg/pull/53812)), make mid size parameter settable for Query Pagination block. ([#51216](https://github.com/WordPress/gutenberg/pull/51216)), Query block: Start prefetching on first click to next/previous. ([54781](https://github.com/WordPress/gutenberg/pull/54781))

**Comment by westnz** [comment]
I plan to update and use this tutorial in the User learning pathway project.

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/98065d4c-cbdd-4273-b8a5-0c7b368cbf0a

**Comment by devmuhib009** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [x] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [x] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Super useful tutorial, @westnz.

**Comment by westnz** [comment]
Thank you very much @devmuhib009 and @ironnysh

**Comment by westnz** [comment]
Published as part of the Intermediate user learning pathway.
