### ISSUE TITLE
⚠️ How to use the Ideas column 👇

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#525]
The "Ideas" column is a place to drop random ideas for lesson plans, workshops and courses. It is also the place to flesh out those ideas so they can move into the development workflow. 

**An issue is automatically added to this column when it is submitted using the provided templates for:**
1. [Lesson Plan](https://github.com/WordPress/Learn/issues/new?assignees=&labels=Awaiting+Triage%2C+%5BContent+Type%5D+Lesson+Plan&template=lesson-plan-template.md&title=Topic+-+Lesson+Plan)
2. [Workshop](https://github.com/WordPress/Learn/issues/new?assignees=&labels=Awaiting+Triage%2C+%5BContent+Type%5D+Workshop&template=workshop-template.md&title=Topic+-+Workshop)
3. Course (coming soon)

**To work on one of the issues in this column:**

1. Please assign yourself to the issue. If you are unable to do this, please comment on the issue and a Team Admin will assign you to the issue.
2. Then follow the checklist or workflow.
3. If any changes are needed or you have any questions, please make comments on the issue.

**Issues move out of this column:**

1.  By a Team Admin when the Curriculum Advisor, Subject Matter Expert or Instructional Designer has completed the checklist or workflow.
2. If the Team decide not to pursue the idea at which point the issue can be closed.

The recommended timelines for creating content are:
- 2 weeks to draft content – with weekly check-ins
- 2 weeks for review and publish – with weekly check-ins
If you get stuck or are unable to continue working on the issue, just drop us a message on the GitHub issue.

**Checklist or Workflow:**

1. The description is finalized
4. The objectives are set. You can use this generator to help draft objective statements  https://learning-objectives.easygenerator.com/
5. Research support and developer docs is complete
6. Marketing communications resources have been identified
7. An SEO review has been carried out
8. A review of related material on Learn has been carried out

**Useful Resources**
[Lesson Plans](https://make.wordpress.org/training/handbook/lesson-plans/)
[Workshops](https://make.wordpress.org/training/handbook/workshops/)
[Courses](https://make.wordpress.org/training/handbook/courses/)

**Comment by ghost** [comment]
Ok
