### ISSUE TITLE
WORKSHOP: Introduction to CSS

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#526]
Lesson plans that would make up this workshop:
1. What is CSS?
2. Use the Customizer to Add CSS to Your Site
3. Use Basic CSS to Modify Your Site's Appearance

**Comment by azhiya** [comment]
Revision needed. Include how to do this in block themes – are there areas of CSS that exceed FSE to include

**Comment by ghost** [comment]
Would the tutorial move away from using the customizer or do you feel it would still be relevant? Kathryn Presner just hosted a workshop 6/14/2023 about adding css in the site editor/additional css box and global style book. This would be a great resources to add to this tutorial. https://www.meetup.com/learn-wordpress-online-workshops/events/293617576/

**Comment by kaitohm** [comment]
Closing, as this topic is now outdated.
