### ISSUE TITLE
Lesson Plan: How to manage a staging/development site

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#542]
# Details

- Topic description:
- Audience (User, Developer, Contributor, etc.): Developers, Users
- Learning objectives: 
   - You will learn the difference between staging and live environments and the reason for using them in best practise.
   - In this workshop, we will make sure there are two distinct environments at the end of the workshop and make sure all the test contents are being applied to staging and proceed to testing before publish updates to live.
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson Plan
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue update by @bsanevans to match current topic vetting template._

**Comment by kaitohm** [comment]
Related: https://learn.wordpress.org/tutorial/wordpress-troubleshooting-basics-part-1/
