### ISSUE TITLE
Full Site Editing - User

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#548]
CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Description and Objectives finalized

**Comment by kaitohm** [comment]
https://learn.wordpress.org/lesson-plan/intro-to-site-editor-and-templates/
