### ISSUE TITLE
Full Site Editing Developer

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#549]
https://developer.wordpress.org/block-editor/tutorials/block-based-themes/

CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Description and Objectives finalized

**Comment by kaitohm** [comment]
https://learn.wordpress.org/course/a-developers-guide-to-block-themes-part-1/
