### ISSUE TITLE
Lesson Plan: Custom Taxonomy

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#556]
CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Description and Objectives finalized
- [ ] Gather links to Support and Developer Docs
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn

**Comment by kaitohm** [comment]
Closing, due to not enough information.

If you'd still like to see this content created, please create [a new Topic Idea issue](https://wordpress.slack.com/archives/C03B11FA16D/p1688486841217239?thread_ts=1687827128.413619&cid=C03B11FA16D) and fill out the information listed. Thanks.
