### ISSUE TITLE
Block Pattern Directory

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#562]
Related: 
https://learn.wordpress.org/lesson-plan/how-to-use-wordpress-block-patterns/
https://learn.wordpress.org/workshop/intro-to-block-patterns/
https://wordpress.org/patterns/

We may append to either using block patterns or a lesson/workshop specific to the directory.

CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Description and Objectives finalized
- [ ] Gather links to Support and Developer Docs
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn

**Comment by annezazu** [comment]
Going to close this out as there are already items in the Learn WP repo that cover the pattern directory: https://learn.wordpress.org/tutorial/using-block-patterns/ & https://learn.wordpress.org/lesson-plan/submitting-block-patterns-to-the-directory/ I don't see how this adds anything.

**Comment by courtneyr-dev** [comment]
I believe this was more about contributing to the Pattern Directory and/or vetting, rather than how to use it.

**Comment by annezazu** [comment]
That's also already done for contribution: https://learn.wordpress.org/tutorial/submitting-block-patterns-to-the-directory/ keeping it closed.
