### ISSUE TITLE
Gutenberg for Themers

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#565]

**Comment by annezazu** [comment]
I'm confused by this idea and think it should be closed compared to others in place: https://github.com/WordPress/Learn/issues/637 https://github.com/WordPress/Learn/issues/631 https://github.com/WordPress/Learn/issues/625 https://github.com/WordPress/Learn/issues/619

**Comment by azhiya** [comment]
Thanks for reviewing this @annezazu, I will close the issue for now. If need be, we can always reopen it.
