### ISSUE TITLE
Home Page buckets are not linked

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#57]
The buckets of content & links are not linked to anywhere. When addressing this, we should make sure the copy matches the links seeing that the copy reflects a post MVP state when there are advanced filters and numerous workshops. We only plan on launching with a couple and without advanced filtering.

### Screenshots
![](https://d.pr/i/v3Ek49.png)

**Comment by hlashbrooke** [comment]
Right now, none of that content is relevant or useful - I'd be more in favour of removing it entirely for now to be honest. I'd rather have that space looking empty in terms of content rather than having unnecessary content and links in there.

**Comment by StevenDufresne** [comment]
@hlashbrooke Sounds good. I'll pull it out.
