### ISSUE TITLE
Making Widgets

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#579]
Workshop & Lesson Plan around creating widgets

https://make.wordpress.org/core/2021/06/29/block-based-widgets-editor-in-wordpress-5-8/

https://developer.wordpress.org/themes/functionality/widgets/
https://developer.wordpress.org/block-editor/how-to-guides/widgets/
https://wordpress.org/support/article/appearance-customize-screen/#widgets
https://developer.wordpress.org/block-editor/how-to-guides/widgets/legacy-widget-block/#allowing-migration-to-a-block
https://wordpress.org/plugins/classic-widgets/

**Comment by kaitohm** [comment]
Closing as out dated.
