### ISSUE TITLE
Design for Theming - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#591]
# Details

- Topic description: This topic is aimed at designers that need to communicate with developers, and anticipating common code oriented considerations.
- Audience (User, Developer, Contributor, etc.): Designers
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson Plan
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue update by @bsanevans to match current topic vetting template._

**Comment by annezazu** [comment]
Want to note that we should incorporate what Make Design is doing to open source theme designs too: https://make.wordpress.org/design/2022/07/01/open-sourcing-theme-designs/
