### ISSUE TITLE
Adding Additional Fields - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#592]
# Details

- Topic description: Use of Pods or ACF would be good for this. Share how to add additional fields to a post and display them on front of site.
- Audience (User, Developer, Contributor, etc.): Developers
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson Plan
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue update by @bsanevans to match current topic vetting template._

**Comment by kaitohm** [comment]
Closing issues marked with "Brand" in preference of creating Learning Path content.
