### ISSUE TITLE
What is Duplicator - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#598]
# Details

- Topic description: How to duplicate posts/pages
- Audience (User, Developer, Contributor, etc.): Users
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): ~Lesson Plan~ Tutorial (changed based on SME feedback)
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue update by @bsanevans to match current topic vetting template._

**Comment by aplauche** [comment]
# Vetting Checklist for SMEs
Priority - either High, Medium or Low: Low
Feedback regarding the topic description: Needs more information, cannot tell if this will be limited to specific plugin?
Feedback regarding the learning objectives: None listed, suggested would be: 

1. Identify several plugins that offer duplication functionality and the pros and cons of each.
2. Understand any SEO implications for duplicated posts/pages.
3. Understand the process for installing an applicable plugin and the duplication workflow.

Any other feedback: This seems pretty ancillary to WordPress, but maybe a short tutorial could be helpful.

# Related Resources
https://wordpress.com/support/copy-a-post-or-page/

**Comment by kaitohm** [comment]
This topic is ready to be created. Please follow the handbook page [Creating a Tutorial](https://make.wordpress.org/training/handbook/tutorials/creating-a-tutorial/) for next steps.
