### ISSUE TITLE
Creating a Block - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#607]
# Details

- Topic description: Create a lesson plan about building a basic block and a plugin with multiple blocks included.
- Audience (User, Developer, Contributor, etc.): Developers
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson Plan
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

- https://make.wordpress.org/core/2021/07/01/block-styles-loading-enhancements-in-wordpress-5-8/
- https://developer.wordpress.org/block-editor/
- https://learn.wordpress.org/workshop/intro-to-gutenberg-block-development/ (needs to be audited/revised)

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue update by @bsanevans to match current topic vetting template._

**Comment by jonathanbossenger** [comment]
Folks, for August I'm preparing a series of tutorials on how to set up and use [Create Block](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/), as well as how to convert a [shortcode to a block](https://jonathanbossenger.com/2022/07/08/turning-a-shortcode-into-a-block/), so it makes sense to me that I work on this lesson plan at the same time.

**Comment by kaitohm** [comment]
@jonathanbossenger Were you able to work on this last year?

**Comment by jonathanbossenger** [comment]
@bsanevans I'll be honest, I have not. I'm going to move this back into the Topic Ideas column
