### ISSUE TITLE
Layout and Content Width - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#609]
# Details

- Topic description: Expand upon using full, wide, etc. widths to other blocks that may prompt for width settings.
- Audience (User, Developer, Contributor, etc.): Developers
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson Plan
- WordPress version (optional): 5.8
- Will you be creating this content? (Yes or No): 

# Related Resources

- https://make.wordpress.org/core/2021/06/29/on-layout-and-content-width-in-wordpress-5-8/

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue update by @bsanevans to match current topic vetting template._

**Comment by aplauche** [comment]
# Vetting Checklist for SMEs
- Priority: High
- Feedback regarding the topic description: 

Should cover the full/wide width, but also the "use content width" option within group blocks to give a full understanding of working with content widths in WordPress.

- Feedback regarding the learning objectives: 

None listed, suggested:
Understand how to set wide and content widths within theme.json
Understand how to apply these widths to blocks within the editor 
Understand how nesting blocks affects layout settings and the options available within nested groups
Understand the "useRootPaddingAwareAlignments" setting and how it interacts with content/layout widths

- Any other feedback: 

This topic is important and can be tough to fully grasp. I think a lesson plan would be helpful to give a framework for explaining this within group learning settings.


# Related Resources
https://wpengine.com/builders/block-layout-alignment-dimensions/
https://gutenbergmarket.com/news/understanding-use-root-padding-aware-alignments-in-block-themes

**Comment by kaitohm** [comment]
This topic is ready to be created. Please follow the handbook page [Lesson Plans](https://make.wordpress.org/training/handbook/lesson-plans/) for next steps.
