### ISSUE TITLE
Lesson Plan - Developing blocks for Global Settings & Styles

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#610]
# Details

- Topic description: Related to the Theme.json lesson plan, developing plugin blocks to appear in Global Styles might expand upon this. Share how to create blocks that have settings in Global Styles.
- Audience (User, Developer, Contributor, etc.): Developers
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson Plan
- WordPress version (optional): 6.1
- Will you be creating this content? (Yes or No): 

# Related Resources

- https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue update by @bsanevans to match current topic vetting template._

**Comment by courtneyr-dev** [comment]
This might be a bit granular, but https://github.com/WordPress/gutenberg/pull/38876 relates to Global Styles column borders. See also https://make.wordpress.org/core/2022/04/28/whats-new-in-gutenberg-13-1-27-april/.

**Comment by annezazu** [comment]
I was going to try to vet this but I'm a bit confused as to whether it's needed at all as I imagine it's covered by a course like this: https://learn.wordpress.org/course/introduction-to-block-development-build-your-first-custom-block/ @jonathanbossenger do you mind sharing your thoughts? I could see an individual lesson plan specifically around adding global controls, when it's best to, and when it may not make sense to do so.

**Comment by courtneyr-dev** [comment]
This is a proposal for a lesson plan it seems, not a course. So making a single lesson plan with the intended audience being teachers or meetup organizers presenting the topics, not folks taking the /courses.

**Comment by jonathanbossenger** [comment]
As @courtneyr-dev points out, we typically have 3 content types on Learn WordPress:

1. Tutorials, short videos where folks can learn something
2. Courses, longer learning experiences that contain both text and video 
3. Lesson Plans, that are aimed at teachers who want to teach a specific topic, either at a meetup or in creating a tutorial. 

So this is for a lesson plan, which is generally a text version of a tutorial, but also with more content aimed at helping someone teach others about this content.
