### ISSUE TITLE
Frequently Used Blocks - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#612]
# Details

- Topic description: Review the Common blocks and how these are often the most suggested.
- Audience (User, Developer, Contributor, etc.): Users
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson Plan
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue update by @bsanevans to match current topic vetting template._

**Comment by kaitohm** [comment]
# Vetting Checklist for SMEs
- Priority - either High, Medium or Low: Low
- Feedback regarding the topic description: Let's develop this content with two focuses.
   - Accessibility/SEO considerations folks should make when using Heading, Image, etc.
   - Introduce the different layout/grouping related blocks and how they can be used
- Feedback regarding the learning objectives: As there were no learning objectives submitted, let's use these:
   - Users will be able to write content with Heading blocks placed appropriately throughout, considering Accessibility and SEO best practices.
   - Users will understand the importance of alt text on images and know where they can edit this on their site.
   - Users will be able to create a variety of responsive layouts using the columns and row block and differentiate between the two.
   - Users will be able to create a new navigation menu in the navigation block and add that to the header of their site.
- Any other feedback: We're covering a lot of ground in this content. Try and keep this to an overview, and share related resources with students as needed for them to investigate further.

# Related Resources


- https://wordpress.tv/2023/07/12/demystifying-the-navigation-block-how-to-set-up-your-sites-navigation-now-and-in-the-future/

**Comment by kaitohm** [comment]
This topic is ready to be created. Please follow the handbook page [Lesson Plans](https://make.wordpress.org/training/handbook/lesson-plans/) for next steps.
