### ISSUE TITLE
How to use the Query Loop Block - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#613]
https://wordpress.org/support/article/query-loop-block/

# Topic Description
Write a description of the topic here.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.

- 

# Guidelines
Review the team guidelines (https://make.wordpress.org/training/handbook/guidelines/)

# Development Checklist:
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the example lesson walk-through
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Announce to the Training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

# Repo Structure and Lesson Plan Template

> <span style="color:red">Please remove all blockquote comments such as this before publishing.</span>

## Description

> A short paragraph explaining what is covered in the lesson plan. This should be text that can be copied and used in a meetup or workshop description.

## Objectives

After completing this lesson, participants will be able to:

* Objective 1
* Objective 2

> It’s required that you include a bulleted list of objective(s) for each lesson plan. Objectives should be worded as actions that the participant can do once they’ve finished. See [Bloom's Taxonomy of Action Verbs](http://www.fresnostate.edu/academics/oie/documents/assesments/Blooms%20Level.pdf) (PDF) as a reference. Avoid using words like "know," "understand," "be introduced to," etc. There should be one assement item for each objective (see below).

## Target Audience

Who is this lesson intended for? What interests/skills would they bring? Put an "x" in the brackets for all that apply.

* [ ] Users / Content Writers
* [ ] Designers
* [ ] Developers
* [ ] Speakers
* [ ] Organizers
* [ ] Kids

## Experience Level

How much experience would a participant need to get the most from this lesson? Put an "x" in the brackets for all that apply.

* [ ] Beginner
* [ ] Intermediate
* [ ] Advanced

## Type of Instruction

Which strategies will be used for this lesson plan? Put an "x" in the brackets for all that apply.

* [ ] Demonstration
* [ ] Discussion
* [ ] Exercises
* [ ] Feedback
* [ ] Lecture (Presentation)
* [ ] Slides
* [ ] Show & Tell
* [ ] Tutorial

## Time Estimate (Duration)

How long will it take to present this lesson? Put an "x" in the brackets for the one that applies.

* [ ] 1 hour or less
* [ ] 2-4 hours (half-day)
* [ ] 5-8 hours (full-day)
* [ ] 2 days
* [ ] 3 days or more

## Prerequisite Skills

Participants will get the most from this lesson if they have familiarity with:

* Skill 1
* Skill 2

> _For example:_
>
> *   Experience with HTML and CSS
> *   Completed the Basic WordPress Concepts lesson

## Readiness Questions

* Question 1
* Question 2

> A list of questions for participants to see if they have the background and skills necessary to learn and understand the lesson.
>
> _For example:_
>
> *   Do you want to makes changes to your theme yourself?
> *   Do you know how to write CSS?

## Slides

> Change the `/repo-name/` in the link to match the URL name of this repo.

*   [Slides](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/) (files included in this repo)

## Materials Needed

* Item 1
* Item 2

> A list of files, resources, equipment, or other materials the presenter will need for the lesson.
>
> _For example:_
>
> *   A local install of WordPress
> *   The files for the TwentySixteen theme

## Notes for the Presenter

* Note 1
* Note 2

> A list of any handy tips or other information for the presenter.
>
> _For example:_
>
> *  Participants may need to download the TwentySixteen theme before beginning
> *  What to do if there’s no projector or internet available
> *  What to do if a participant doesn’t have the necessary set up
> *  How to handle different opinions about the topic

## Lesson Outline

* First do this
* Then move on to this
* Finish with this

> The plan for the lesson. Outline form works well.
>
> _For example:_
>
> * Talk about what a theme is
> * Demonstrate how to install and activate a theme
> * Practice exercises to have participants find and install a theme on their own site

## Exercises

**Exercise name**

Short description of what the exercise does and what skills or knowledge it reinforces.

*   Short point or step of the exercise
*   And another one

> These are short or specific activities that help participants practice certain components of the lesson. They should not be fully scripted exercises, but rather something that participants could do on their own. For example, you can create an exercise based on one step of the Example Lesson.

## Assessment

There should be one assement item (or more) for each objective listed above. Each assessment item should support an objective; there should be none that don't.

**Write out the question.**

1.  Option
2.  Option
3.  Option
4.  Option

**Answer:** 3\. Correct answer

> A few questions to ask participants to evaluate their retention of the material presented. They should be a measure of whether the objectives were reached. Consider having a question for each objective.

## Additional Resources

* Resource 1
* Resource 2

> An optional section which can contain a list of resources that the presenter can use to get more information on the topic.
>
> _For example:_
>
> * Link to information on the Codex
> * Theme Review Team's Handbook

## Example Lesson

> An example of how the lesson plan can be implemented. Written in script form as one possible way an presenter might use this lesson plan at an event, with screenshots and instructions if necessary.

### Section Heading for Example Lesson

> You will likely need to break the Example Lesson down into multiple sections.

### Lesson Wrap Up

![](https://raw.githubusercontent.com/wptrainingteam/contributor-resources/master/images/lightbulb.png) Follow with the [Exercises](#Exercises) and [Assessment](#Assessment) outlined above.

**Comment by azhiya** [comment]
Hi, @westnz are you also working on the lesson plan?

**Comment by westnz** [comment]
Hey @azhiya! Sarah is working on this and has shared the Google draft doc with the Training team.

**Comment by azhiya** [comment]
@wparase I'm still unable to assign you to a GitHub issue.

**Comment by westnz** [comment]
Here is the link to Sarah's draft copy of the [lesson plan](https://docs.google.com/document/d/1AQCu2KFPB6R3GG1f5xIZvvvrKAvlGRThP592_j9GNQs/edit)

**Comment by azhiya** [comment]
Please review for https://github.com/WordPress/Documentation-Issue-Tracker/issues/283

**Comment by courtneyr-dev** [comment]
Please see https://github.com/WordPress/gutenberg/pull/38997

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/38063

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/38024

**Comment by wparasae** [comment]
Paused; the majority of this lesson plan is done in Google Docs, this just needs to be moved to Learn. If someone is interested in moving this across the finish line, please ping @arasae in the #training channel. Otherwise, I will get to this as my priorities allow.

**Comment by azhiya** [comment]
That's great @wparasae. If you've got no takers, I can work on moving it across.

**Comment by courtneyr-dev** [comment]
patterns with the Query Loop, which reflects the intended post type, and the tools panel has been adopted to better consolidate the number of filters shown by default. Finally, folks who extend the Query Loop can also use an allowedControls property to determine what filters appear in variations to refine the UI based on their unique variation. 

Visuals: [parent filter video](https://drive.google.com/file/d/11PqK90GxxULlsUd7pGVbl0XnSqnOkU4Q/view?usp=sharing), [tools panel video](https://drive.google.com/file/d/1U7kDLQ6YgSsnGJtqd8gzKKZyGg2GHHIc/view?usp=sharing).

Code examples: [video exploring registering a variation and including specific patterns](https://www.youtube.com/watch?v=oMBZViYiTvc) with [JS for registering a Query Loop variation](https://github.com/ryanwelcher/twitch/blob/trunk/themes/twitch-theme/variations/index.js) and [PHP for registering a pattern can be used with the variation](https://github.com/ryanwelcher/twitch/blob/trunk/themes/twitch-theme/functions.php#L42).

Adoption approach: opt-in. 

Key Make Posts/GitHub/Trac Issue(s): 

[Pass extra query args in REST API call for an accurate preview for extenders](https://github.com/WordPress/gutenberg/pull/44093#top).
[Add parents filter](https://github.com/WordPress/gutenberg/pull/40933#top) for querying pages. 
[Add a filter to build_query_vars_from_query_block](https://github.com/WordPress/gutenberg/pull/43590#top). 
UX: [Add filters with ToolsPanel](https://github.com/WordPress/gutenberg/pull/42629) to better organize the experience of working with filter options. 
UX: [Honor intended post type when previewing patterns and when replacing them with patterns](https://github.com/WordPress/gutenberg/pull/43285#top) for a more intuitive and predictable experience. 
[Add allowedControls in block variations for better extensibility](https://github.com/WordPress/gutenberg/pull/43632#top), which allows extenders to determine which controls show up for variations. 
[Draft of documentation for extending the query loop through variations](https://github.com/WordPress/gutenberg/pull/44137).

**Comment by wparasae** [comment]
Due to a transition, I have removed myself from this issue to allow someone else to work on this. :) If I find time to work on this in the next two weeks, I will comment below and happily reassign myself to this issue.

**Comment by courtneyr-dev** [comment]
WP 6.4 
Visuals: [YouTube video explaining improved pagination feature](https://youtu.be/y7YHFncLvD4).
Adoption approach:
Key Make Posts/GitHub/Trac Issue(s): Query block: Client-side pagination ([53812](https://github.com/WordPress/gutenberg/pull/53812)), make mid size parameter settable for Query Pagination block. ([#51216](https://github.com/WordPress/gutenberg/pull/51216)), Query block: Start prefetching on first click to next/previous. ([54781](https://github.com/WordPress/gutenberg/pull/54781))
