### ISSUE TITLE
Jobs.WordPress.Net

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#616]
How to submit a job post
How maintainers process submissions
How users can find jobs

CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Description and Objectives finalized
- [ ] Gather links to Support and Developer Docs
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn

**Comment by kaitohm** [comment]
Closing, as low priority for the team.
