### ISSUE TITLE
Course: Themes

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#619]

**Comment by annezazu** [comment]
When thinking about a Course on themes, it would be rad to talk about different types (perhaps just hybrid, block, classic): 

- Classic theme: a theme built the way we’ve been used to with PHP templates, functions.php, and more.
- Block theme: a theme made for FSE using HTML templates and theme.json, allowing one to manage all parts of their site with blocks.
- Hybrid theme: a classic theme that adopts a feature(s) of FSE, like theme.json or the template editor ([some insights here)](https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/).
- Universal theme: a theme that works with both the Customizer and the Site Editor.

I have a video that might be helpful for whoever takes this on: https://youtu.be/fMbrGDD-27Q

**Comment by kaitohm** [comment]
Content covered in https://learn.wordpress.org/lesson/different-types-of-themes-overview/
