### ISSUE TITLE
Course: Start Contributing to WordPress

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#620]

**Comment by annezazu** [comment]
# Vetting Checklist for SMEs
- Priority: unclear. 
- Feedback regarding the topic description: there is no description. In light of that, I'm curious what we're trying to accomplish here.
- Feedback regarding the learning objectives: Again, there is no description. 
- Any other feedback: I believe we should close this out in light of this which, while once more empty, has the potential for more nuance and impact: https://github.com/WordPress/Learn/issues/626

**Comment by courtneyr-dev** [comment]
I'll be opening this course proposal to coincide with the New Contributor Mentorship program shortly.
