### ISSUE TITLE
Course: Entry level developer courses for using PHP, JS, etc. in WordPress

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#622]

**Comment by annezazu** [comment]
# Vetting Checklist for SMEs
- Priority: high
- Feedback regarding the topic description: N/A
- Feedback regarding the learning objectives: N/A
- Any other feedback: I'd like to see this more deeply explored and defined but I agree with the concept in general. It's important we have pathways. Curious what @jonathanbossenger makes of this and what we might already have covered as I know you're working on a few plugin related courses. 

# Related Resources

https://developer.wordpress.org/block-editor/getting-started/create-block/
https://developer.wordpress.org/themes/basics/tools-resources/

**Comment by jonathanbossenger** [comment]
We actually have this as item **2 The programming languages of WordPress** in the "[Introduction to WordPress Development syllabus](https://make.wordpress.org/training/2023/03/29/introduction-to-wordpress-development-syllabus/)" post. Ideally, once all the tutorials on that list are created, we could circle back here and collect them together as a course.

**Comment by kaitohm** [comment]
Collating multiple resources from that syllabus into different courses is definitely something the team should work on, but once the content has been created. I'm closing this issue for now. Once the content in the syllabus has been created, we can map out what courses can be made, and what priority each have then.
