### ISSUE TITLE
Course: Advanced site management (beyond the basics in 101)

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#625]

**Comment by annezazu** [comment]
Would love to include block locking, pattern creation, and general "curation techniques" https://make.wordpress.org/core/2022/02/09/core-editor-improvement-curated-experiences-with-locking-apis-theme-json/

**Comment by annezazu** [comment]
# Vetting Checklist for SMEs
- Priority: Unclear. 
- Feedback regarding the topic description: Doesn't exist. 
- Feedback regarding the learning objectives: Doesn't exist. 
- Any other feedback: There's nothing listed here beyond my reference to curation techniques. I believe this needs to be expanded upon before we continue. Is this site management, as in multiple sites, or site management in terms of permissions or managing patterns or keeping plugins up to date or something else entirely?

**Comment by kaitohm** [comment]
I will close this for now, so that the team can prioritize other vetted topics.

If there is interest in pursuing this topic, please open a new issue with more details 🙇
