### ISSUE TITLE
Course: Developing for the block editor

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#627]

**Comment by annezazu** [comment]
# Vetting Checklist for SMEs
- Priority - either High, Medium or Low: Unclear. 
- Feedback regarding the topic description: There is no description. 
- Feedback regarding the learning objectives: There are no objectives. 
- Any other feedback: This needs to be fleshed out more. 

@bsanevans why did you move these without any description or objective to the vetting process? I'm a bit confused and don't have anything to really review, beyond a very high level idea. To me, there are a number of courses that address developing for the block editor, including building a block or converting a shortcode to a block: https://learn.wordpress.org/courses/#developing-with-wordpress I would opt for closing this out.

**Comment by kaitohm** [comment]
Thanks for checking, @annezazu . In future, issues like this wouldn't reach the vetting process unless they have more info. You may see few of these right now from an old and extensive backlog. I'll go through and do a sweep for similar issues later today 📝 

If there is interest in pursuing content on a similar topic, please open a new issue with more details 🙇‍♂️
