### ISSUE TITLE
Course: Theme.json

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#637]

**Comment by courtneyr-dev** [comment]
[outline support was also added to blocks and elements](https://github.com/WordPress/gutenberg/pull/43526) via theme.json. For more information about overall changes to theme.json, please see the [Expanded theme.json support and Styles options section below](https://docs.google.com/document/d/1MPH0lQKXLSj2Hegur_4B-wZRi_zPPJIUdXJfslO6JEo/edit#heading=h.vnuhkmgca0gc). 

Code examples: view examples provided in the [Styling elements in block themes dev note](https://make.wordpress.org/core/?p=98557&preview=true)

Adoption approach: opt-in. 

Key Make Posts/GitHub/Trac Issue(s):  

[Styling elements in block themes dev note](https://make.wordpress.org/core/?p=98557&preview=true).
[YouTube video from Dave Smith going over these new options](https://www.youtube.com/watch?v=XikXzLLojhk).

**Comment by annezazu** [comment]
# Vetting Checklist for SMEs
- Priority - either High, Medium or Low: Unclear.
- Feedback regarding the topic description: One does not exist. 
- Feedback regarding the learning objectives: One does not exist. 
- Any other feedback: 

I am closing this out in light of other, more high impact and nuanced theme.json related material: https://github.com/WordPress/Learn/issues?q=is%3Aissue+is%3Aopen+theme.json This feels like too much of a filler without enough detail.
