### ISSUE TITLE
Lesson Plan: Blogging with WordPress

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#638]
# Details

- Topic description: Docs team has need of content about blogging. This would not be how to use the software, but more around how to plan the content you create and what a blog is.  Blogs are the compilation of posts. A high level idea about blogging would be ideal. This can progress on to a workshop and a course.
- Audience (User, Developer, Contributor, etc.): Users
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson Plan
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_This issue was edited by @bsanevans to apply the recent topic idea template._

**Comment by wparasae** [comment]
For someone interested in writing a lesson plan/longer course for this, the following are ~3-4 hours of online workshop content that may help you write content:

1. [Start Blogging - Planning for your Audience + Discovering your 'Why'](https://wordpress.tv/2022/12/22/sarah-snow-kathryn-presner-start-blogging-in-2023-part-1-planning-to-reach-your-audience/)
2. [Start Blogging - Planning Blog Content](https://wordpress.tv/2023/01/11/start-blogging-in-2023-part-2-planning-your-blogs-content/)

Feel free to use and adapt! 

Related Graphic Organizers:
[Planning For Your Audience](https://docs.google.com/document/d/1PXFLo6uQTDHZtFHLOkAP71USewSF8RsobxhBnJdZhpU/edit?usp=sharing)
[Planning Your Content](https://docs.google.com/document/d/1PXFLo6uQTDHZtFHLOkAP71USewSF8RsobxhBnJdZhpU/edit?usp=sharing)

**Comment by kaitohm** [comment]
# Vetting Checklist for SMEs
- Priority - either High, Medium or Low: Medium
- Feedback regarding the topic description: I think this resource is needed. It would be great if we could also talk about using AI to generate content ideas. Mentioning SEO and accessibility in content structure would also be valuable.
- Feedback regarding the learning objectives:
   - Site users will be able to plan a series of post topics for their personal site.
   - They will be able to submit appropriate prompts to AI software (such as ChatGPT) to aid in their content planning.
   - They would be able to analyze their content structure from a perspective of SEO and accessibility awareness.
- Any other feedback: 

# Related Resources

**Comment by kaitohm** [comment]
This topic is ready to be created. Please follow the handbook page [Lesson Plans](https://make.wordpress.org/training/handbook/lesson-plans/) for next steps.
