### ISSUE TITLE
Block Theme Comment Block - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#641]
https://learn.wordpress.org/lesson-plan/displaying-the-post-comments-block-to-block-themes/

CHECKLIST: Development Checklist
- [x] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Description and Objectives finalized
- [x] Gather links to Support and Developer Docs
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [ ] Create an outline of the example lesson walk-through
- [ ] Announce to training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

**Comment by azhiya** [comment]
Hi @westnz. I'm moving this to "Drafts in Progress" and backtracking on labels and milestones.

**Comment by courtneyr-dev** [comment]
https://wordpress.slack.com/archives/C02RW657Q/p1648634996999119 cross referencing.
