### ISSUE TITLE
Build a site using a block theme (Twenty Twenty Two) - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#643]
Use this card when manually adding lesson plan ideas onto the Trello board.

CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Description and Objectives finalized
- [ ] Gather links to Support and Developer Docs
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Create an outline of the example lesson walk-through
- [ ] Announce to training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

**Comment by wparasae** [comment]
Hey friends, I ran a social learning space that is incomplete for this lesson plan in full, but has a LOT of good information to use as a starting point: https://wordpress.tv/2022/05/25/design-with-me-create-a-simple-website-for-your-small-business/

It's long, but I think it would be really useful as it's broken up into exercises and helps people build sites from start to almost finished. Just in case anyone wants to tackle this lesson plan, here's the social learning space that can help you with it.

**Comment by kaitohm** [comment]
I'm closing this, as it is now outdated.
