### ISSUE TITLE
How To Add and Remove Logo And Site Icon in Site Editor - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#645]
UPDATED - Published link: https://learn.wordpress.org/lesson-plan/how-to-add-and-remove-logo-and-site-icon-in-site-editor/

CHECKLIST: Development Checklist
- [x] Draft lesson plan
- [x] Copy edit
- [x] Style guide review
- [x] Instructional Review
- [x] Final review
- [x] Publish
- [x] Description and Objectives finalized
- [x] Gather links to Support and Developer Docs
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [x] Create an outline of the example lesson walk-through
- [x] Announce to training team
- [x] Announce to lesson plan creator
- [x] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

**Comment by azhiya** [comment]
This lesson plan is now ready for review: https://learn.wordpress.org/?p=14742&post_type=lesson-plan&preview=1&_ppp=f78358b7b6

**Comment by abhansnuk** [comment]
I can review this. Where are we saving review comments?

**Comment by courtneyr-dev** [comment]
Going live. Great job!

**Comment by courtneyr-dev** [comment]
Please review https://github.com/WordPress/gutenberg/pull/35892 for updates @azhiya

**Comment by azhiya** [comment]
You may also need to review:

- https://github.com/WordPress/gutenberg/pull/37920
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/265
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/287

**Comment by azhiya** [comment]
Workshop issue https://github.com/WordPress/Learn/issues/512

**Comment by azhiya** [comment]
Points to note:
- https://github.com/WordPress/gutenberg/pull/35892 was covered in the original lesson plan
- https://github.com/WordPress/gutenberg/pull/37920 references site title block which is not covered in this lesson plan. This lesson plan only covers adding or removing a site logo/icon.
- https://github.com/WordPress/Documentation-Issue-Tracker/issues/287 This change now means the 'Use as site icon" toggle in the Site Icon Block Settings is on by default. The change is very minor so I've updated the screenshots and made a note in the lesson plan.

The changes are scheduled to go live on May 24, 2022.

**Comment by abhansnuk** [comment]
Note: this is in revisions extended, it will be live on release day

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/issues/48608

**Comment by courtneyr-dev** [comment]
https://make.wordpress.org/core/2023/05/04/whats-new-in-gutenberg-15-7-03-may/#site-logo-replacement-via-the-sidebar 6.3

**Comment by courtneyr-dev** [comment]
[49992](https://github.com/WordPress/gutenberg/pull/49992)

**Comment by kaitohm** [comment]
@abhansnuk Will you be working on updating this content?
