### ISSUE TITLE
Searching Openverse - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#648]
Use this card when manually adding lesson plan ideas onto the Trello board.

CHECKLIST: Development Checklist
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Description and Objectives finalized
- [ ] Gather links to Support and Developer Docs
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Create an outline of the example lesson walk-through
- [ ] Announce to training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

**Comment by azhiya** [comment]
Hi, @parajapatisagr are you still working on this lesson plan?

**Comment by prajapatisagar** [comment]
@azhiya Yes, I am working on it.

**Comment by azhiya** [comment]
[Lesson Plan](https://learn.wordpress.org/?p=14881&post_type=lesson-plan&preview=1&_ppp=274a91313d) is now "Ready for Review"

**Comment by courtneyr-dev** [comment]
The exercise for this is directing folks to use the Photo directory. The exercise should use just Openverse, and perhaps include downloading an image and audio as well. 

In the walkthrough, describe how Openverse finds these assets. 

We do have already an example of this in https://learn.wordpress.org/lesson-plan/how-to-use-and-contribute-to-the-wordpress-photo-directory-and-openverse/. Perhaps we merge the issues for the time being and reopen if Openverse needs a dedicated lesson instead? @azhiya

**Comment by prajapatisagar** [comment]
Hello @courtneyr-dev & @azhiya 

Is there any improvement or update needed for this article? Can I have a review on this, please?

Thanks

**Comment by azhiya** [comment]
Hi @prajapatisagar apologies but we will need to merge this issue with this one: https://github.com/WordPress/Learn/issues/649 which has already been published.

I will close this one down.
