### ISSUE TITLE
How to Use and Contribute to the WordPress Photo Directory and Openverse - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#649]
https://learn.wordpress.org/lesson-plan/how-to-use-and-contribute-to-the-wordpress-photo-directory-and-openverse/

CHECKLIST: Development Checklist
- [x] Draft lesson plan
- [x] Copy edit
- [x] Style guide review
- [x] Instructional Review
- [x] Final review
- [x] Publish
- [x] Description and Objectives finalized
- [x] Gather links to Support and Developer Docs
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [x] Create an outline of the example lesson walk-through
- [x] Announce to training team
- [x] Announce to lesson plan creator
- [x] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

**Comment by mburnette** [comment]
Commenting here for updating the lesson plan to include new Jetpack/Openverse media integration
