### ISSUE TITLE
Submitting a block pattern to the directory - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#650]
Use this card when manually adding lesson plan ideas onto the Trello board.

CHECKLIST: Development Checklist
- [x] Draft lesson plan
- [x] Copy edit
- [x] Style guide review
- [x] Instructional Review
- [x] Final review
- [ ] Publish
- [ ] Description and Objectives finalized
- [x] Gather links to Support and Developer Docs
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [x] Create an outline of the example lesson walk-through
- [x] Announce to training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

**Comment by azhiya** [comment]
Hi, @westnz are you working on this? I've got you listed as the owner in the [March Sprint](https://make.wordpress.org/training/2022/03/03/march-2022-team-sprint/)

**Comment by westnz** [comment]
Hi @azhiya, Yes, I am almost finished with the workshop and lesson plan.

**Comment by azhiya** [comment]
Ok, I'm moving it to "Drafts in Progress"

**Comment by westnz** [comment]
Here is the link to the [Lesson Plan](https://learn.wordpress.org/wp-admin/post.php?post=15080&action=edit).

**Comment by westnz** [comment]
@azhiya Sorry, I published this as it was in the 'Published' column in Github.  Can you 'unpublish'?  It still needs a review.

**Comment by westnz** [comment]
Hey @azhiya Can we go ahead and publish this Lesson Plan?

**Comment by azhiya** [comment]
Yes of course @westnz. I've set it to publish tomorrow 15:00 UTC, but feel free to change it to earlier if you want.

**Comment by westnz** [comment]
Thanks so much @azhiya
