### ISSUE TITLE
Upgrade to Sensei Pro

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#664]
We currently use [Sensei](https://wordpress.org/plugins/sensei-lms/) to power the courses on Learn WordPress. Sensei now has a Pro version that comes with some additional features. Some notable ones for our use case are:
* Additional question types
* Quiz timer
* Content drip functionality
* Additional upcoming features

Sensei Pro usually costs US$149/year for support and updates, but the Sensei team at Automattic is happy to provide us with a 100% discount on that so it can be used for free on Learn WordPress.

Technically this is a simple matter to implement, but using a premium plugin on WordPress.org comes with some other ramifications that need to be discussed:
1. I could be wrong about this, but as far as I'm aware we don't currently have any premium plugin licences running anywhere on WordPress.org - this would make using Sensei Pro a first for the network and therefore likely needs approval before we use it.
2. Testing on local environments would become inherently difficult as the premium features would not be available for local environments - this would make reliable contributions tricky in some instances.

From a resources and development perspective, I feel that it makes more sense to upgrade to Sensei Pro in order to access these features, rather than researching and migrating to a different LMS plugin.

**Comment by alexstine** [comment]
> 2. Testing on local environments would become inherently difficult as the premium features would not be available for local environments - this would make reliable contributions tricky in some instances.

The other thing to look at is can the pro version be placed in open source GitHub/SVN. One thing we cannot do is have more closed source code. If the plugin requires a license key for pro features vs. pro files, can likely get away with it.

**Comment by chrisbadgett** [comment]
If you wish to remain with free repo listed plugins only, the free LifterLMS plugin has these features with no pro versions required:
- Additional question types (Multiple Choice, Picture Choice, True/False)
- Quiz timer
- Content drip functionality

As one of the creators of LifterLMS, I would be open to a conversation around making some premium LifterLMS features free in the core plugin on the repo to accommodate the WordPress Learn project. For example if you really wanted "Fill in the blank" question types in the free core plugin and not in our premium Advanced Quizzes add-on, I would be open to tradeoffs like that to support the WordPress community.

**Comment by chrisbadgett** [comment]
It's also likely that no matter which freemium LMS plugin you choose, the Learn project will likely end up wanting some premium features. Similar to ecommerce platforms, learning platforms can become complex. So eventually some add-on becomes desired for niche functionality or integration.

**Comment by hlashbrooke** [comment]
Thanks for your input and offer @chrisbadgett!

I think this is a key point:
> It's also likely that no matter which freemium LMS plugin you choose, the Learn project will likely end up wanting some premium features

With that in mind, it's easiest if we simply add Sensei Pro since that is what is already being used here.

> The other thing to look at is can the pro version be placed in open source GitHub/SVN. One thing we cannot do is have more closed source code.

Also a great point @alexstine. Since posting this I got in touch with the Sensei team and they're OK with us including the Pro version in this repo. I'm really relieved about that as it means the code will continue to be open-source and available to contributors.

With all of that in mind, does anyone have any objections to using Sensei Pro (and including it in this repo) going forward? In terms of technical management, the Pro code will need to be committed manually for now, but we can automate new releases being pulled across from the private Sensei Pro repo in the future.

**Comment by alexstine** [comment]
> With all of that in mind, does anyone have any objections to using Sensei Pro (and including it in this repo) going forward? In terms of technical management, the Pro code will need to be committed manually for now, but we can automate new releases being pulled across from the private Sensei Pro repo in the future.

That's great! I don't even worry so much about automating the syncing to this repo as long as the code is up to date so it is easy to track down bugs, adjust features, etc. What I mean is if it is on learn.wordpress.org, the code should live here. If that's possible, let's get this done! 👍

**Comment by hlashbrooke** [comment]
We're all sorted on the Sensei Pro side - we have a free lifetime subscription for the product that is registered to the learn@wordpress.org email address, and I have added the Pro code in this PR: https://github.com/WordPress/learn/pull/669

The Pro code is a separate plugin to Sensei core, so the free Sensei plugin from the Plugin Directory is still linked to this repo as an external, and the Pro code will now be included in the repo directly so all contributors will have access to all the code running on .org. I'd say that's a win all round, so I'm glad we can move forward here!
