### ISSUE TITLE
How to use the Group Block - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#674]
# Development Checklist:
- [x] Draft lesson plan
- [x] Copy edit
- [x] Style guide review
- [x] Instructional Review
- [ ] Final review
- [ ] Publish
- [x] Description and Objectives finalized
- [x] Gather links to Support and Developer Docs
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [x] Create an outline of the example lesson walk-through
- [ ] Announce to Training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

# Repo Structure and Lesson Plan Template

> <span style="color:red">Please remove all blockquote comments such as this before publishing.</span>

## Description

> A short paragraph explaining what is covered in the lesson plan. This should be text that can be copied and used in a meetup or workshop description.

## Objectives

After completing this lesson, participants will be able to:

* Objective 1
* Objective 2

> It’s required that you include a bulleted list of objective(s) for each lesson plan. Objectives should be worded as actions that the participant can do once they’ve finished. See [Bloom's Taxonomy of Action Verbs](http://www.fresnostate.edu/academics/oie/documents/assesments/Blooms%20Level.pdf) (PDF) as a reference. Avoid using words like "know," "understand," "be introduced to," etc. There should be one assement item for each objective (see below).

## Target Audience

Who is this lesson intended for? What interests/skills would they bring? Put an "x" in the brackets for all that apply.

* [ ] Users / Content Writers
* [ ] Designers
* [ ] Developers
* [ ] Speakers
* [ ] Organizers
* [ ] Kids

## Experience Level

How much experience would a participant need to get the most from this lesson? Put an "x" in the brackets for all that apply.

* [ ] Beginner
* [ ] Intermediate
* [ ] Advanced

## Type of Instruction

Which strategies will be used for this lesson plan? Put an "x" in the brackets for all that apply.

* [ ] Demonstration
* [ ] Discussion
* [ ] Exercises
* [ ] Feedback
* [ ] Lecture (Presentation)
* [ ] Slides
* [ ] Show & Tell
* [ ] Tutorial

## Time Estimate (Duration)

How long will it take to present this lesson? Put an "x" in the brackets for the one that applies.

* [ ] 1 hour or less
* [ ] 2-4 hours (half-day)
* [ ] 5-8 hours (full-day)
* [ ] 2 days
* [ ] 3 days or more

## Prerequisite Skills

Participants will get the most from this lesson if they have familiarity with:

* Skill 1
* Skill 2

> _For example:_
>
> *   Experience with HTML and CSS
> *   Completed the Basic WordPress Concepts lesson

## Readiness Questions

* Question 1
* Question 2

> A list of questions for participants to see if they have the background and skills necessary to learn and understand the lesson.
>
> _For example:_
>
> *   Do you want to makes changes to your theme yourself?
> *   Do you know how to write CSS?

## Slides

> Change the `/repo-name/` in the link to match the URL name of this repo.

*   [Slides](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/) (files included in this repo)

## Materials Needed

* Item 1
* Item 2

> A list of files, resources, equipment, or other materials the presenter will need for the lesson.
>
> _For example:_
>
> *   A local install of WordPress
> *   The files for the TwentySixteen theme

## Notes for the Presenter

* Note 1
* Note 2

> A list of any handy tips or other information for the presenter.
>
> _For example:_
>
> *  Participants may need to download the TwentySixteen theme before beginning
> *  What to do if there’s no projector or internet available
> *  What to do if a participant doesn’t have the necessary set up
> *  How to handle different opinions about the topic

## Lesson Outline

* First do this
* Then move on to this
* Finish with this

> The plan for the lesson. Outline form works well.
>
> _For example:_
>
> * Talk about what a theme is
> * Demonstrate how to install and activate a theme
> * Practice exercises to have participants find and install a theme on their own site

## Exercises

**Exercise name**

Short description of what the exercise does and what skills or knowledge it reinforces.

*   Short point or step of the exercise
*   And another one

> These are short or specific activities that help participants practice certain components of the lesson. They should not be fully scripted exercises, but rather something that participants could do on their own. For example, you can create an exercise based on one step of the Example Lesson.

## Assessment

There should be one assement item (or more) for each objective listed above. Each assessment item should support an objective; there should be none that don't.

**Write out the question.**

1.  Option
2.  Option
3.  Option
4.  Option

**Answer:** 3\. Correct answer

> A few questions to ask participants to evaluate their retention of the material presented. They should be a measure of whether the objectives were reached. Consider having a question for each objective.

## Additional Resources

* Resource 1
* Resource 2

> An optional section which can contain a list of resources that the presenter can use to get more information on the topic.
>
> _For example:_
>
> * Link to information on the Codex
> * Theme Review Team's Handbook

## Example Lesson

> An example of how the lesson plan can be implemented. Written in script form as one possible way an presenter might use this lesson plan at an event, with screenshots and instructions if necessary.

### Section Heading for Example Lesson

> You will likely need to break the Example Lesson down into multiple sections.

### Lesson Wrap Up

![](https://raw.githubusercontent.com/wptrainingteam/contributor-resources/master/images/lightbulb.png) Follow with the [Exercises](#Exercises) and [Assessment](#Assessment) outlined above.

**Comment by courtneyr-dev** [comment]
https://wordpress.org/support/article/group-block/

**Comment by courtneyr-dev** [comment]
Include https://github.com/WordPress/gutenberg/pull/40062

**Comment by courtneyr-dev** [comment]
Use this as a pre-req https://github.com/WordPress/Learn/issues/717

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/40176

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/39920

**Comment by azhiya** [comment]
Please review https://github.com/WordPress/Documentation-Issue-Tracker/issues/296

**Comment by courtneyr-dev** [comment]
Ready for review. https://learn.wordpress.org/wp-admin/post.php?post=18010&action=edit

**Comment by azhiya** [comment]
@courtneyr-dev Looks good, I've added the taxonomy. You might want to check that the timings are correct.

**Comment by westnz** [comment]
Hey @courtneyr-dev!  Great lesson plan.  I look forward to seeing the workshop as well.

Just a few small things. 

Lesson objectives - **maybe add full stops after each sentence.**

Assessment - **double-check the answer (see screen shot)**

<img width="887" alt="image" src="https://user-images.githubusercontent.com/89751452/169426756-4d9512d9-37c9-406c-841c-59bd6586308a.png">


Width: **Unsure what was meant by "Content within the block" (see screen shot)**

<img width="887" alt="image" src="https://user-images.githubusercontent.com/89751452/169426924-28a5fcce-301f-43b0-8e5a-e134ca8220c8.png">


"This is a query loop block with a border and featured image at the top, and inside is another group block that has padding to keep text spaced apart from the border." - **change query loop block to Query Loop block and group block to Group block**.

Group block layout:
This is the default setting of a group block. - **Group block**

Row 
The row block allows you to arrange blocks horizontally. - **Row block**

Additional Group block formatting 
select colors adjust typography - **comma between colors and adjust**

Well done 👍

**Comment by westnz** [comment]
Once the updates have been made, this lesson plan is ready to be published. 😃

**Comment by azhiya** [comment]
I'm removing the "Ready to publish" label as it looks like there are still a few changes that need to be made.

**Comment by kaitohm** [comment]
@courtneyr-dev Pinging you to put this on your radar again 😉 Once the feedback is incorporated, please publish this content. Thanks.

**Comment by courtneyr-dev** [comment]
WP 6.4 https://github.com/WordPress/gutenberg/pull/53934 
https://github.com/WordPress/gutenberg/pull/53735

**Comment by courtneyr-dev** [comment]
https://make.wordpress.org/core/?p=108291#naming-group-blocks-in-the-editor
https://github.com/WordPress/gutenberg/pull/53735

**Comment by courtneyr-dev** [comment]
Background image support has been added to the Group block, in line with the color controls. ([#53934](https://github.com/WordPress/gutenberg/pull/53934) & [#54439](https://github.com/WordPress/gutenberg/pull/54439))

**Comment by courtneyr-dev** [comment]
6.4
Visuals: [demo](https://drive.google.com/file/d/1mzjkXwtPyuGDCbfeurhSyDGP5DP747rD/view?usp=drive_link) showing renaming and reverting rename.
Adoption approach: N/A
Key Make Posts/GitHub/Trac Issue(s): Rename Group blocks in the Editor via Modal ([53735](https://github.com/WordPress/gutenberg/pull/53735)).

Visuals: [demo](https://drive.google.com/file/d/1uMBVp8CiCpZ3o7RYFetr6EkJQ7eKKyJ_/view?usp=drive_link) of adding a grouping, a Heading block, and adding a background image
Adoption approach: N/A
Key Make Posts/GitHub/Trac Issue(s): Add background image support to Group block ([53934](https://github.com/WordPress/gutenberg/pull/53934))
