### ISSUE TITLE
How to use the Group Block - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#675]
# Workshop Development Checklist

- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [ ] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [ ] Workshop published on WPTV
- [ ] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [ ] Workshop created on Learn.WordPress.org
- [ ] Workshop post is reviewed for grammar, spelling, etc.
- [ ] Workshop published on Learn.WordPress.org
- [ ] Workshop announced to training team
- [ ] Workshop announced to creator
- [ ] Workshop announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by courtneyr-dev** [comment]
https://wordpress.org/support/article/group-block/

**Comment by courtneyr-dev** [comment]
Include https://github.com/WordPress/gutenberg/pull/40062

**Comment by courtneyr-dev** [comment]
Use this as a pre-req https://github.com/WordPress/Learn/issues/718

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/39920

**Comment by azhiya** [comment]
Please review https://github.com/WordPress/Documentation-Issue-Tracker/issues/296

**Comment by westnz** [comment]
Hey @courtneyr-dev I see you are working on the Lesson Plan. Were you planning on creating the workshop as well? If so, I can find a different topic? Just let me know 😉

**Comment by courtneyr-dev** [comment]
WP 6.4 https://github.com/WordPress/gutenberg/pull/53934 
https://github.com/WordPress/gutenberg/pull/53735

**Comment by courtneyr-dev** [comment]
https://make.wordpress.org/core/?p=108291#naming-group-blocks-in-the-editor
https://github.com/WordPress/gutenberg/pull/53735

**Comment by courtneyr-dev** [comment]
Background image support has been added to the Group block, in line with the color controls. ([#53934](https://github.com/WordPress/gutenberg/pull/53934) & [#54439](https://github.com/WordPress/gutenberg/pull/54439))

**Comment by courtneyr-dev** [comment]
6.4
Visuals: [demo](https://drive.google.com/file/d/1mzjkXwtPyuGDCbfeurhSyDGP5DP747rD/view?usp=drive_link) showing renaming and reverting rename.
Adoption approach: N/A
Key Make Posts/GitHub/Trac Issue(s): Rename Group blocks in the Editor via Modal ([53735](https://github.com/WordPress/gutenberg/pull/53735)).

Visuals: [demo](https://drive.google.com/file/d/1uMBVp8CiCpZ3o7RYFetr6EkJQ7eKKyJ_/view?usp=drive_link) of adding a grouping, a Heading block, and adding a background image
Adoption approach: N/A
Key Make Posts/GitHub/Trac Issue(s): Add background image support to Group block ([53934](https://github.com/WordPress/gutenberg/pull/53934))

**Comment by westnz** [comment]
Hey @courtneyr-dev, I noticed this Issue is still assigned to you.  Are you still planning on creating this tutorial? 😃

**Comment by ghost** [comment]
Hi, @courtneyr-dev and @westnz, I was wondering if there are any updates on when this workshop is being presented? I am looking for a simple beginner topic to use as my first workshop. Please let me know asap. Thank you

**Comment by westnz** [comment]
Hey @lada7042 , this is a tutorial, so you are welcome to use this as your Online Workshop topic. You can create a new issue for that.

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/issues/2899
