### ISSUE TITLE
Difference between Wordpress Themes and Templates

### ISSUE THREAD

**Issue by HILAYTRIVEDI** [WordPress/Learn#684]
# Development Checklist:
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Description and Objectives finalized
- [ ] Gather links to Support and Developer Docs
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn

**Comment by kaitohm** [comment]
Published in [WordPress Theme Template Tour](https://learn.wordpress.org/tutorial/wordpress-theme-template-tour/).
