### ISSUE TITLE
April 2022 Sprint

### ISSUE THREAD

**Issue by azhiya** [WordPress/Learn#686]
#Monthly Training Team Sprint Checklist

- [x] Sprint planning - Week 1 ([April 2022 Sprint](https://make.wordpress.org/training/2022/04/01/april-2022-sprint/))
- [ ] Weekly check-in - Week 2 (Provide the Slack link)
- [ ] Weekly check-in - Week 3 (Provide the Slack link)
- [ ] Weekly check-in/Sprint retrospective - Week 4 (Provide the Slack or Make post link)
- [ ] Sprint retrospective - Week 5 (Provide the Make post link)

**Comment by azhiya** [comment]
@hlashbrooke has suggested we add the following items to the Sprint

Workshops
- Dashboard overview ([already has a lesson plan](https://learn.wordpress.org/lesson-plan/dashboard-overview/))
- User management ([already has a lesson plan](https://learn.wordpress.org/lesson-plan/user-management/))
- Choosing and installing plugins ([already has a lesson plan](https://learn.wordpress.org/lesson-plan/choosing-and-installing-plugins/))
- Managing Updates ([already has a lesson plan](https://learn.wordpress.org/lesson-plan/managing-updates/))
- Managing navigation menus

Lesson plans
- Managing navigation menus
- Intro to the Site Editor and Template Editor ([already has a workshop](https://learn.wordpress.org/workshop/intro-to-the-site-editor-and-template-editor/))

**Comment by azhiya** [comment]
In planning for April, one of the things I want to propose is that we prioritise the content development on Learn. Based on discussions we've had amongst ourselves and separate conversations with members of the 6.0 Documentation Leads, we are prioritising our workload to make it easier for people to identify what they need to be working on and allocate the limited resources we have for maximum effort. 

Proposal
* High - in time for the release
** New walkthrough 6.0 (5 April)
** About page & its message strategy (likely to be set by the walkthrough)
** Any dependencies from 5.9 related to 6.0
** Single source of truth documentation

* Medium - ideally in time for the release but could be after
** Feedback from Faculty, specifically curriculum advisors/subject matter experts
** Core Trac HelpHub, DevHub, DevNotes triage
** Needs Docs (DevHub) 
** Support forum
** GitHub Gutenberg issues

* Low - after the release 
** Dev notes
** Field guide
** Contributor suggestions

What do you think?

**Comment by azhiya** [comment]
I've published the [Sprint for April](https://make.wordpress.org/training/2022/04/01/april-2022-sprint/). Let me know what you think.

**Comment by wparasae** [comment]
I attended April 5th's Walkthrough and took some notes. There are some fun potential social learning spaces / lesson plans - to - workshop ideas at the very top: [Link to Sarah's Training Team Notes](https://docs.google.com/document/d/1NheIWzMxEsOxfPf7Am1joF4MqEzCWo2VoRr8s4ogoP0/edit?usp=sharing)

We may be able to use them for content ideas for the 6.0 release.
