### ISSUE TITLE
In mobile size button design is broken.

### ISSUE THREAD

**Issue by mdhimanshuchudasama** [WordPress/Learn#687]
In devices below 450px, the button design is broken. need to design it properly. Also, need some space between the button and text.
issue is on this page: https://learn.wordpress.org/
<img width="532" alt="Learn-wordpress" src="https://user-images.githubusercontent.com/71747654/161079772-d4a09f0b-271b-4a36-b905-3b8a10905088.png">

solution: 
`.wporg-learn-workshop-discussion-events .wp-block-button__link, .wporg-learn-workshop-discussion-events .wp-block-button__link{
    min-width: 80px;
    margin-left: 5px
}`

**Comment by hlashbrooke** [comment]
This has been done in a separate update.
