### ISSUE TITLE
404 page loads when clicking lesson complete

### ISSUE THREAD

**Issue by LukaszJaro** [WordPress/Learn#689]
When clicking 'complete lesson' on the last lesson of each accordion a 404 page appears. Only happens on last lesson for each section. 

![image](https://user-images.githubusercontent.com/10998875/161121148-297d4177-c319-426d-bd0d-0aa49869146c.png)

Here's the destination URL it takes me to:
https://learn.wordpress.org/learn/modules/18755077-block-themes/?course_id=10993?course_id=10993

**Comment by azhiya** [comment]
This is assigned to @wparasae

**Comment by wparasae** [comment]
Update: I was able to [recreate this issue twice](https://docs.google.com/document/d/1AyTs5IdgDsgKH83pchL-_NoSVBNxH1jPoZnXWI634d8/edit?usp=sharing), one on a new course on Learn (which has been deleted) and one on a test site. Pretty sure it's a bug, so I'm working on filing a report with the Sensei Team next.

**Comment by wparasae** [comment]
Report Filed: https://github.com/Automattic/sensei/issues/5008

**Comment by wparasae** [comment]
I applied a quick fix that Dadash found with this comment: 
[> Note that the 404 error happens only if the Module 2 has a description in it.](https://github.com/Automattic/sensei/issues/5008#issuecomment-1094886619)

The module descriptions have been temporarily removed and have been scheduled to be automatically be re-applied to the course in two weeks' time.

I set a reminder for myself in Slack to follow up on the issue on April 25th, 2022 and will comment with an update then if this is still ongoing.

**Comment by wparasae** [comment]
Issue is still ongoing; does not look to be resolved, but temporary workaround does seem to be working for the moment.

**Comment by wparasae** [comment]
This issue should be resolved; I will look into this before the meeting next week and double check, but this should be resolved.

**Comment by wparasae** [comment]
This issue is closed!
