### ISSUE TITLE
Getting to know the WordPress Dashboard - Workshop

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#694]
# Related Resources
- [ ] https://learn.wordpress.org/workshop/wordpress-dashboard-overview/ (you'll be revising this version and replacing it with a more current recording. Please briefly mention what users see under Appearance may be different based upon if they are using a Classic or Block theme.
- [ ] https://learn.wordpress.org/lesson-plan/dashboard-overview/
- [ ] https://wordpress.org/support/article/dashboard-screen/
- [ ] https://wordpress.org/support/article/first-steps-with-wordpress/

# Workshop Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop published on WPTV
- [x] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [x] Workshop created on Learn.WordPress.org
- [x] Workshop post is reviewed for grammar, spelling, etc.
- [x] Workshop published on Learn.WordPress.org
- [x] Workshop announced to training team
- [x] Workshop announced to creator
- [x] Workshop announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by courtneyr-dev** [comment]
https://learn.wordpress.org/workshop/wordpress-dashboard-overview/ is published. @hlashbrooke would you like this topic to be refreshed?

**Comment by hlashbrooke** [comment]
Yeah I would like a new workshop that is more concise and uses the existing lesson plan as the workshop structure.

**Comment by westnz** [comment]
Here is the link to the [video](https://wordpress.slack.com/archives/C02RW657Q/p1651646572769029) for feedback.  Please review by Thursday, 12 May. Many thanks

**Comment by hlashbrooke** [comment]
I love it - no notes from me! This is ready to ship IMO.

**Comment by azhiya** [comment]
Oops looks like this has already been reviewed by Hugh so I'm removing the Ready for Review label.

**Comment by westnz** [comment]
Link to workshop: https://learn.wordpress.org/workshop/getting-to-know-the-wordpress-dashboard/

**Comment by westnz** [comment]
Updated and published in Sensei as part of the draft Beginner User learning pathway.
