### ISSUE TITLE
Tutorial - User Management 

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#695]
# Related Resources

- [ ] https://learn.wordpress.org/workshop/user-management/ (you will be revising this and uploading the video to this location)
- [ ] https://learn.wordpress.org/lesson-plan/user-management/
- [ ] https://wordpress.org/support/article/roles-and-capabilities/

# Workshop Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop published on WPTV
- [x] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [x] Workshop created on Learn.WordPress.org
- [x] Workshop post is reviewed for grammar, spelling, etc.
- [x] Workshop published on Learn.WordPress.org
- [x] Workshop announced to training team
- [x] Workshop announced to creator
- [x] Workshop announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by westnz** [comment]
Note from @wparasae (Sarah Snow): "User management will need an update after the 6.0 release; please hold off until the feature freeze for this, as, to my understanding, user management may be available not only in the dashboard but at the block level." I will therefore wait before continuing with this workshop.

**Comment by azhiya** [comment]
Hey @westnz are there any further developments on this one?

**Comment by westnz** [comment]
Howdy @azhiya This is on hold until after the 6.0 release.

**Comment by westnz** [comment]
Hey @azhiya I have started working on the script, will try to get the workshop done by the end of next week.

**Comment by westnz** [comment]
Here is the link to the [video](https://wordpress.slack.com/archives/C02RW657Q/p1655952690863779)

**Comment by westnz** [comment]
Published Tutorial: https://learn.wordpress.org/tutorial/user-management-2/

**Comment by westnz** [comment]
Updated and added to the Beginner User learning pathway.
