### ISSUE TITLE
How to Choose and Install Plugins - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#696]
# Related Resources

- [x] https://learn.wordpress.org/workshop/how-to-choose-and-install-plugins/ (you'll be revising this workshop and replacing the video with a more current and shorter version)
- [ ] https://learn.wordpress.org/lesson-plan/choosing-and-installing-plugins/
- [ ] https://wordpress.org/support/article/plugins/
- [ ] https://wordpress.org/support/article/managing-plugins/

# Workshop Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop published on WPTV
- [x] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [x] Workshop created on Learn.WordPress.org
- [x] Workshop post is reviewed for grammar, spelling, etc.
- [x] Workshop published on Learn.WordPress.org
- [x] Workshop announced to training team
- [x] Workshop announced to creator
- [ ] Workshop announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by westnz** [comment]
Here is the link to the [video](https://wordpress.slack.com/archives/C02RW657Q/p1650623116764689) 😃

**Comment by Kemmy99** [comment]
I think the video is good and very simple to understand the instructions.

**Comment by westnz** [comment]
Published Tutorial: https://learn.wordpress.org/tutorial/searching-and-installing-a-plugin/

**Comment by westnz** [comment]
Updated and added to the Beginner User learning pathway.
