### ISSUE TITLE
Managing Menus (Classic) - Workshop

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#698]
# Related Resources

- [ ] https://learn.wordpress.org/lesson-plan/managing-menus/
- [ ] https://wordpress.org/support/article/appearance-menus-screen/

# Workshop Development Checklist

- [x] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [ ] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [ ] Workshop published on WPTV
- [ ] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [ ] Workshop created on Learn.WordPress.org
- [ ] Workshop post is reviewed for grammar, spelling, etc.
- [ ] Workshop published on Learn.WordPress.org
- [ ] Workshop announced to training team
- [ ] Workshop announced to creator
- [ ] Workshop announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by Kemmy99** [comment]
I would like to work on this workshop if not taken. Thanks!

**Comment by azhiya** [comment]
Hi @westnz have you claimed this or can @Kemmy99 claim it?

**Comment by westnz** [comment]
Hi @azhiya. I have not claimed it. @Kemmy99 can go ahead. Thank you

**Comment by Kemmy99** [comment]
Hello @courtneyr-dev  there is a mistake with this headline.Manging Menus.

**Comment by Kemmy99** [comment]
Manging Menus needs to be corrected. There is a mistake with managing. It is written as manging instead of managing. Thanks

**Comment by azhiya** [comment]
> Manging Menus needs to be corrected. There is a mistake with managing. It is written as manging instead of managing. Thanks

Updated.

**Comment by robinwpdeveloper** [comment]
I wanted to contribute on this but I think it requires well presented workshops.
Anyway, I will try something else first.

**Comment by kaitohm** [comment]
Closing in favor of prioritizing Learning Pathways content.
