### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#7]
### Purpose
To agree on an approach to support the new `workshop` post type and implement the designs shown here:
https://www.figma.com/file/UtmG8KQv3Csy8hNtuAWkwZ/Learn-WordPress?node-id=0%3A1

### Proposal
We can leverage the [learn theme beta project](https://github.com/wptrainingteam/learn-theme-beta) because ultimately it's where these workshops will probably live.

### Background Info
The learn theme beta currently has 2 custom post types:

1. `lesson-plan` ([Link](https://github.com/wptrainingteam/learn-theme-beta/blob/master/plugins/wporg-learn/inc/class-lesson-plan.php))
2. `workshop` ([Link](https://github.com/wptrainingteam/learn-theme-beta/blob/master/plugins/wporg-learn/inc/class-workshop.php))

The post types share taxonomies:

| Taxonomy        |    Example       |  Notes |
| ------------- |-------------| -----|
| Categories    |  `Popular` | Used for filtering on `lesson-plan`/`workshop` browser ([See Learn designs](https://wp.invisionapp.com/share/BNP0V7QXRF8#/screens/330323714)) | 
| [Audience](https://github.com/wptrainingteam/learn-theme-beta/blob/4fbeec7ecd51d6f7dbbb108eff50d1dd004ae844/plugins/wporg-learn/inc/class-lesson-plan.php#L149)    |     `All` | |
| [Duration](https://github.com/wptrainingteam/learn-theme-beta/blob/4fbeec7ecd51d6f7dbbb108eff50d1dd004ae844/plugins/wporg-learn/inc/class-lesson-plan.php#L67)    |`1 Hour` | |
| [Experience Level](https://github.com/wptrainingteam/learn-theme-beta/blob/4fbeec7ecd51d6f7dbbb108eff50d1dd004ae844/plugins/wporg-learn/inc/class-lesson-plan.php#L108)    |    `Beginner` | |
| [Instruction Type](https://github.com/wptrainingteam/learn-theme-beta/blob/4fbeec7ecd51d6f7dbbb108eff50d1dd004ae844/plugins/wporg-learn/inc/class-lesson-plan.php#L190)    |   `Presentation` | |
| [Lesson Group](https://github.com/wptrainingteam/learn-theme-beta/blob/4fbeec7ecd51d6f7dbbb108eff50d1dd004ae844/plugins/wporg-learn/inc/class-workshop.php#L67)    |  `Security` |This taxonomy is used to tie `lesson-plans` together so they can be added to different `workshop` ideas. Add lessons to a lesson group, add the lesson group to the workshop.   |  
| [Topics](https://github.com/wptrainingteam/learn-theme-beta/blob/4fbeec7ecd51d6f7dbbb108eff50d1dd004ae844/plugins/wporg-learn/inc/class-workshop.php#L108)  |    `Dashboard Overview`, `What you can do with WordPress` | This only exists for `workshop` post type.  |

### Suggestions:
I think we should turn off the current `workshop` with the aim of adding it back in later (as `workshop-ideas` maybe). We then create a new plugin that registers a `workshop` post type.

#### Tasks:
1. Remove references to current `workshop`, effectively disabling it. (We could move it into its own plugin.)
2. Create a new plugin with `workshop` Custom Post Type for new workshops

**Comment by tellyworth** [comment]
Yeah that makes sense. There's no reason to let the original design and IA get in the way. It doesn't look like there's anything in the old `workshop` CPT that isn't easily recreated in a fresh version.

**Comment by hlashbrooke** [comment]
I agree with the way forward there.

Since those CPTs already share taxonomies, you could definitely reuse those for the new `workshop` CPT - all of those would be relevant, except for the "Instruction Type" one.

**Comment by StevenDufresne** [comment]
Closing this as we are already in motion and have taken this approach.
