### ISSUE TITLE
# Team Roles - Content Development Project Board

### ISSUE THREAD

**Issue by azhiya** [WordPress/Learn#700]
We are proposing the following in line with [Faculty Program Structure] (https://make.wordpress.org/training/2022/01/31/faculty-program-structure-proposal/) and our [existing team roles](https://make.wordpress.org/training/handbook/about/team-roles/)

## Content Development Project Board

Content Triage Role (Subject Matter Experts, Instructional Designers, Curriculum Advisor)
* Notification when a new issue is created from these templates
** Lesson Plan Template
** Workshop Template
** Course Template

Content Creator Role
* Notification - issue moves to "Next Up - You Can Help"

Editor Role
* Notification (Copy editors, style guide, code) - issue moves to "Review in Progress"

Reviewer Role
* Notification (Instructional Designers) - item tagged as "Instructional Review"

Administrator Role
* Notification (Instructional Designers, Training Team Admin) - issue moves to "Ready to Publish"

**Comment by azhiya** [comment]
Hi, @webtechpooja @westnz @hlashbrooke we are brainstorming the team roles for the Content Development board. Please feel free to comment.

**Comment by azhiya** [comment]
Hugh, Wes, Courtney and I have been added to the Learn Content Triage team. A link has been sent to Pooja to join the WordPress team.

**Comment by azhiya** [comment]
At this stage, @courtneyr-dev and I do not think we need a Content Creator team/role on GitHub as they can just be general collaborators. We have merged the Editor and Reviewer roles into one team. If the need arises, we can split this out at a later date.

**Comment by azhiya** [comment]
With the Faculty program now live, I'd like to revisit this task. @piyopiyo-kitsune I'm adding you to the conversation as well.

**Comment by azhiya** [comment]
Do we think there is still a need to keep the [Team Roles column](https://github.com/WordPress/Learn/projects/4#column-18128194) and the cards in there? We used to keep this in Trello and we would list the team members against each card so people knew who was doing what. We would also use it to send targeted messages for that specific group/role. If we do decide it is worth keeping then I would suggest we streamline the roles so that they are more in line with the Faculty board groupings.

**Comment by digitalchild** [comment]
Faculty program is being retired.
