### ISSUE TITLE
Theme Customizer  - Workshop

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#703]
# Topic Description
Mention that this is for Classic and Hybrid themes

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ] https://learn.wordpress.org/workshop/using-the-theme-customizer/ (this is a revision you will be updating)

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Workshop Development Checklist

- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the workshop
- [ ] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [ ] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [ ] Workshop published on WPTV
- [ ] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [ ] Workshop created on Learn.WordPress.org
- [ ] Workshop post is reviewed for grammar, spelling, etc.
- [ ] Workshop published on Learn.WordPress.org
- [ ] Workshop announced to training team
- [ ] Workshop announced to creator
- [ ] Workshop announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by westnz** [comment]
Will it be enough to change the thumbnail and add it to the description?

**Comment by westnz** [comment]
@courtneyr-dev I have changed the title to read "Using the Theme Customizer (Classic and Hybrid Themes)" and in the description, I have added, "Please note that the Customizer is used with classic or hybrid themes."

**Comment by azhiya** [comment]
Hey @westnz I've tagged this as **Ready for Review** but now I'm wondering if this has already been reviewed.

**Comment by westnz** [comment]
Hi @azhiya This issue was under quick fixes.  I have only changed the above-mentioned information.  It must probably still be approved.

**Comment by azhiya** [comment]
Thanks Wes. I can see the updates. I'll move this to published.
