### ISSUE TITLE
How to Create a Post or Page with the WordPress Block Editor - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#704]
https://learn.wordpress.org/workshop/how-to-create-a-post-or-page-with-the-wordpress-block-editor/
# Topic Description
Write a description of the topic here.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Workshop Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [ ] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [ ] Workshop published on WPTV
- [ ] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [ ] Workshop created on Learn.WordPress.org
- [ ] Workshop post is reviewed for grammar, spelling, etc.
- [ ] Workshop published on Learn.WordPress.org
- [ ] Workshop announced to training team
- [ ] Workshop announced to creator
- [ ] Workshop announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by courtneyr-dev** [comment]
6.4 https://github.com/WordPress/gutenberg/pull/54282

**Comment by ghost** [comment]
@westnz Are you working on this? Was wondering if you are not could I take it over.

**Comment by westnz** [comment]
Hey @lada7042
I will connect with you via Slack.  I have started working on updating the script but would be keen to collaborate.

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/f61cf435-4af3-4b8a-84c5-104f91cbe2fe

**Comment by TinaCollier** [comment]
Hello @westnz ,

Thank you for creating another great tutorial! I took some notes while watching the tutorial:

1. All objectives were clearly met and elaborated upon
2. You explanation and examples of blocks, patterns, and media options were thorough and easily understandable
3. You discussed multiple ways of adding blocks including within the page, insert tab, and using the forward slash. You also provided us a great example of adding an image with forward slash, adding paragraphs within the page, and using the insert tab
4. You clearly differentiated between editing and the sidebar. 
5. You went into detail on how to use the block toolbar for a paragraph block
6. I appreciate your description and tutorial on using the list view. My one suggestion would be discussing nested blocks a bit further, but that could easily be a tutorial on its own.
7. I almost noted that we need to include the site editor, but then I saw that you included this section and an example of how to add the YouTube block to content
8. The last part of the tutorial quickly mentions posts and that we can add blocks to posts just like pages. You could discuss this a bit further if you wanted, but it isn't necessary for the overall purpose of the tutorial

Once again, you've created a great tutorial video for Learn.WordPress.org. A beginner user would find this extremely helpful in learning about the basics of blocks. Thank you for sharing!

Best regards,
Tina

**Comment by westnz** [comment]
Thank you for the thorough review.

Yes, I think nested blocks will come up in other tutorials.

**Comment by SierraTR** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [X ] Learning outcomes/objectives are clear.
- [X ] Technical concepts introduced in the content are accurate.
- [X ] The speed of demonstrations are easy to follow.
- [X ] The narration audio matches what is shown visually.
- [X ] Spelling and grammar are correct.
- [X ] Sound quality is consistent throughout the video.
- [X ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [X ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.
You covered all that you said you would - Here are a few things that I noticed:

1:55 You mention the block inserter within the page as a way to add blocks. You could mention that the 6 blocks that appear in the inserter are those blocks that you have most recently used and that the Browse all is another way to open the left sidebar block/pattern/media selection area.

2:20 You mention the Editing Area. There are actually three sections, the main one and two sidebars. The left sidebar for selecting blocks/patterns/media or viewing the list view and the right sidebar showing the settings/styling area for the block or page/post. Either of the two sidebar areas can be viewed or hidden with the little x at the top right of the column. At 3:32 you actually show that view with both sidebars hidden.

2:50 You describe the block toolbar and give a short explanation of each icon in the toolbar and what it permits.Except you skip over two icons. The rectangular 6-dot icon which permits drag/drop movement of the block. And the down caret which permits highlighting, footnotes, and other text styling options.

7:18 You state that creating a post is the same as creating a page. This is basically true when discussing adding content using the block editor. You might consider adding the exception that with a Post you must also select the desired category of the post and, and if desired, a featured image and custom excerpt. This could be covered by referring to another tutorial that covers those items.

**Comment by westnz** [comment]
Thank you for the helpful feedback @SierraTR

**Comment by westnz** [comment]
Published in Sensei as part of the draft Beginner User learning pathway.
