### ISSUE TITLE
Understanding the difference between WordPress posts and pages  - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#706]
https://learn.wordpress.org/workshop/posts-vs-pages-whats-the-difference/

# Topic Description
Write a description of the topic here.

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Workshop Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [x] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [x] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop published on WPTV
- [x] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [x] Workshop created on Learn.WordPress.org
- [x] Workshop post is reviewed for grammar, spelling, etc.
- [x] Workshop published on Learn.WordPress.org
- [x] Workshop announced to training team
- [x] Workshop announced to creator
- [ ] Workshop announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by kaitohm** [comment]
Has there been any progress on this issue, @wparasae ?

**Comment by wparasae** [comment]
@bsanevans Yes! I believe this refers to this tutorial: https://learn.wordpress.org/tutorial/posts-vs-pages-whats-the-difference/

Once upon a time, tutorials were called workshops #namingthingsishard 
This should be complete, and I will move it to the correct section.

**Comment by kaitohm** [comment]
Ooh, wonderful! You figured out while I was confused 😅 Thanks.

**Comment by westnz** [comment]
Updated video:

https://github.com/WordPress/Learn/assets/89751452/c511c1fd-e6d7-4100-a886-7bf3d54cd8e9

**Comment by digitalchild** [comment]
Another great, easy to follow tutorial @westnz  Only feedback I have, when you first mention that posts are for blog content, I would hesitate to say blog and say dynamic content such as blogs, news, articles updates etc. Which you mention further on in the video. Posts are also time relevant, while pages usually aren't.

**Comment by westnz** [comment]
Good point!  Thank you for the feedback @digitalchild

**Comment by askhellosatya** [comment]
This tutorial is fantastic, offering clear and straightforward instructions. @westnz; However, there are instances where a background voice interferes, impacting the overall quality. Consider editing those sections for a more effective presentation. By the way, you did a great job!

**Comment by westnz** [comment]
Hey @askhellosatya, could you please provide me with the time stamps where you heard a background voice?  Thanks for your feedback.

**Comment by askhellosatya** [comment]
Yes, I observed the background noise persisting from 0:48 to 1:30 and 2:15 to 3:10, remaining consistent across most parts of the video. It's a minor issue - there's a faint background noise reminiscent of an air conditioner's sound. However, aside from this, the video tutorial is exceptional; it's well-structured, easy to follow, and of high quality.

**Comment by westnz** [comment]
Great stuff, thank you for pointing me in the right direction.  I will have a look.  I appreciate your review.

**Comment by askdesign** [comment]
Excellent video. There is one little glitch for me.
I had trouble hearing the words in this sentence and had to replay several times to understand:
4:52 - "Did you know that you can also create **and edit**..."
"and edit" was the phrase I had trouble hearing correctly.
I like that you included what can be done to pages in the Site Editor.

**Comment by SierraTR** [comment]
## Tutorial Review Checklist
Please tick all items you've confirmed:
- [ ] Learning outcomes/objectives are clear.
- [ X] Technical concepts introduced in the content are accurate.
- [X ] The speed of demonstrations are easy to follow.
- [ X] The narration audio matches what is shown visually.
- [X ] Spelling and grammar are correct.
- [X ] Sound quality is consistent throughout the video.
- [ X] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [X ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Leave an additional comment below with feedback. You can also share what you liked about this Tutorial.

Another good job Wes.
I did notice that there was no introductory Learning outcomes/objectives page for learners to see what will be presented in the tutorial. With one you can include the content on categories and tags that might not be expected by just reading the tutorial title.

I listened to the audio with and without a headset and it evident that you re-recorded the problematic areas mentioned by the other reviewers. I noticed no problems.

**Comment by westnz** [comment]
Thank you for the feedback @askdesign and @SierraTR

**Comment by westnz** [comment]
Published in Sensei as part of the draft Beginner User learning pathway.
