### ISSUE TITLE
WebP - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#707]
# Topic Description
Review what the WebP format is, what impact this might have on website owners, where WebP format works and doesn't (such as OG:Image/link preview). Does WordPress automatically convert the format? Can you upload the format?  If this doesn't make it into core, what are plugin options in the interim to use for this? 

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- https://core.trac.wordpress.org/ticket/55443
- https://make.wordpress.org/core/2022/03/28/enabling-webp-by-default/
- https://developers.google.com/speed/webp

# Guidelines
Review the [team guidelines](https://make.wordpress.org/training/handbook/guidelines/)

# Development Checklist:
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the example lesson walk-through
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Announce to the Training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

# Repo Structure and Lesson Plan Template

> <span style="color:red">Please remove all blockquote comments such as this before publishing.</span>

## Description

> A short paragraph explaining what is covered in the lesson plan. This should be text that can be copied and used in a meetup or workshop description.

## Objectives

After completing this lesson, participants will be able to:

* Objective 1
* Objective 2

> It’s required that you include a bulleted list of objective(s) for each lesson plan. Objectives should be worded as actions that the participant can do once they’ve finished. See [Bloom's Taxonomy of Action Verbs](http://www.fresnostate.edu/academics/oie/documents/assesments/Blooms%20Level.pdf) (PDF) as a reference. Avoid using words like "know," "understand," "be introduced to," etc. There should be one assement item for each objective (see below).

## Target Audience

Who is this lesson intended for? What interests/skills would they bring? Put an "x" in the brackets for all that apply.

* [ ] Users / Content Writers
* [ ] Designers
* [ ] Developers
* [ ] Speakers
* [ ] Organizers
* [ ] Kids

## Experience Level

How much experience would a participant need to get the most from this lesson? Put an "x" in the brackets for all that apply.

* [ ] Beginner
* [ ] Intermediate
* [ ] Advanced

## Type of Instruction

Which strategies will be used for this lesson plan? Put an "x" in the brackets for all that apply.

* [ ] Demonstration
* [ ] Discussion
* [ ] Exercises
* [ ] Feedback
* [ ] Lecture (Presentation)
* [ ] Slides
* [ ] Show & Tell
* [ ] Tutorial

## Time Estimate (Duration)

How long will it take to present this lesson? Put an "x" in the brackets for the one that applies.

* [ ] 1 hour or less
* [ ] 2-4 hours (half-day)
* [ ] 5-8 hours (full-day)
* [ ] 2 days
* [ ] 3 days or more

## Prerequisite Skills

Participants will get the most from this lesson if they have familiarity with:

* Skill 1
* Skill 2

> _For example:_
>
> *   Experience with HTML and CSS
> *   Completed the Basic WordPress Concepts lesson

## Readiness Questions

* Question 1
* Question 2

> A list of questions for participants to see if they have the background and skills necessary to learn and understand the lesson.
>
> _For example:_
>
> *   Do you want to makes changes to your theme yourself?
> *   Do you know how to write CSS?

## Slides

> Change the `/repo-name/` in the link to match the URL name of this repo.

*   [Slides](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/) (files included in this repo)

## Materials Needed

* Item 1
* Item 2

> A list of files, resources, equipment, or other materials the presenter will need for the lesson.
>
> _For example:_
>
> *   A local install of WordPress
> *   The files for the TwentySixteen theme

## Notes for the Presenter

* Note 1
* Note 2

> A list of any handy tips or other information for the presenter.
>
> _For example:_
>
> *  Participants may need to download the TwentySixteen theme before beginning
> *  What to do if there’s no projector or internet available
> *  What to do if a participant doesn’t have the necessary set up
> *  How to handle different opinions about the topic

## Lesson Outline

* First do this
* Then move on to this
* Finish with this

> The plan for the lesson. Outline form works well.
>
> _For example:_
>
> * Talk about what a theme is
> * Demonstrate how to install and activate a theme
> * Practice exercises to have participants find and install a theme on their own site

## Exercises

**Exercise name**

Short description of what the exercise does and what skills or knowledge it reinforces.

*   Short point or step of the exercise
*   And another one

> These are short or specific activities that help participants practice certain components of the lesson. They should not be fully scripted exercises, but rather something that participants could do on their own. For example, you can create an exercise based on one step of the Example Lesson.

## Assessment

There should be one assement item (or more) for each objective listed above. Each assessment item should support an objective; there should be none that don't.

**Write out the question.**

1.  Option
2.  Option
3.  Option
4.  Option

**Answer:** 3\. Correct answer

> A few questions to ask participants to evaluate their retention of the material presented. They should be a measure of whether the objectives were reached. Consider having a question for each objective.

## Additional Resources

* Resource 1
* Resource 2

> An optional section which can contain a list of resources that the presenter can use to get more information on the topic.
>
> _For example:_
>
> * Link to information on the Codex
> * Theme Review Team's Handbook

## Example Lesson

> An example of how the lesson plan can be implemented. Written in script form as one possible way an presenter might use this lesson plan at an event, with screenshots and instructions if necessary.

### Section Heading for Example Lesson

> You will likely need to break the Example Lesson down into multiple sections.

### Lesson Wrap Up

![](https://raw.githubusercontent.com/wptrainingteam/contributor-resources/master/images/lightbulb.png) Follow with the [Exercises](#Exercises) and [Assessment](#Assessment) outlined above.

**Comment by caraya** [comment]
I'd like to take this one

**Comment by caraya** [comment]
Ready for review. 

https://learn.wordpress.org/wp-admin/post.php?post=18265&action=edit

**Comment by Piyopiyo-Kitsune** [comment]
Please assign me for reviewing 🙏

**Comment by Piyopiyo-Kitsune** [comment]
Hey there @caraya, great work! I did some light grammar/word editing and for other feedback you'll find it below:

- The information from this GitHub article will need to be removed from the lesson plan post before publishing
- "Support was first introduced in WordPress 5.8." --> Support for what? WebP?
- "(the feeling that Google wants to own everything)." -> is it necessary to say this in a lesson plan?
- It looks like the bullet list under "Creating WebP images in ImageMagick" may need t be reformatted
- Missing three links in the "Additional Resources" section

**Comment by caraya** [comment]
> Hey there @caraya, great work! I did some light grammar/word editing and for other feedback you'll find it below:
Thank you! I've addressed the requested changes below

> * The information from this GitHub article will need to be removed from the lesson plan post before publishing
I removed all the information from the template. Please let me know if I missed anything.

> * "Support was first introduced in WordPress 5.8." --> Support for what? WebP?
Yes. I reworded the sentence to indicate that WebP support was introduced in WordPress 5.8

> * "(the feeling that Google wants to own everything)." -> is it necessary to say this in a lesson plan?
No, it is not necessary. I removed the entire sentence. 

> * It looks like the bullet list under "Creating WebP images in ImageMagick" may need t be reformatted
Thank you. It's been fixed.

> * Missing three links in the "Additional Resources" section
The links were higher in the document. They've been moved to the bottom. Is this what you had in mind?

**Comment by Piyopiyo-Kitsune** [comment]
@caraya The changes look good to me! Nicely done!

**Comment by westnz** [comment]
Hey @azhiya, when did you plan to publish this lesson plan?  Looks like it is good to go 😉

**Comment by azhiya** [comment]
Hey @westnz published.

**Comment by westnz** [comment]
Thank you for all the publishing @azhiya 💪

**Comment by courtneyr-dev** [comment]
https://make.wordpress.org/core/2022/09/11/webp-in-core-for-6-1/

**Comment by caraya** [comment]
Some issues with WebP support. 

- Support for the format may be (or remain) in core, but it's dependent on the server running WordPress being built to support the format. 
- LocalWP wasn't built with such support until 6.4.3 so it made it hard to really test.
- I would suspect hosts would not be so quick to recompile the PHP binary with WebP support.
