### ISSUE TITLE
WebP - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#708]
# Details

- Topic description: Review what the WebP format is, what impact this might have on website owners, where WebP format works and doesn't (such as OG:Image/link preview). Does WordPress automatically convert the format? Can you upload the format? If this doesn't make it into core, what are plugin options in the interim to use for this?
- Audience (User, Developer, Contributor, etc.): Users, Developers
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Tutorial
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

- https://core.trac.wordpress.org/ticket/55443
- https://make.wordpress.org/core/2022/03/28/enabling-webp-by-default/
- https://developers.google.com/speed/webp

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue update by @bsanevans to match current topic vetting template._

**Comment by courtneyr-dev** [comment]
https://make.wordpress.org/core/2022/09/11/webp-in-core-for-6-1/

**Comment by kaitohm** [comment]
Related: https://learn.wordpress.org/lesson-plan/webp-images-in-wordpress/
