### ISSUE TITLE
Performance team & Performance Lab Plugin  - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#710]
# Details

- Topic description: What is the Performance team and what is the purpose of the Performance Lab plugin? Avoid super specifics of the plugin as the features here will continue to change. 
- Audience (User, Developer, Contributor, etc.): Developers
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Tutorial
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

- https://wordpress.org/plugins/performance-lab/
- https://make.wordpress.org/core/tag/performance/

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue update by @bsanevans to match current topic vetting template._

**Comment by kaitohm** [comment]
Tutorial of #709
