### ISSUE TITLE
CSS Grid - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#711]
# Details

- Topic description: A basic understanding of CSS Grid is needed as a prerequisite to understanding how content aligns. Show this first in plain HTML/CSS context, and share where in Site Editor one can find settings related to Grid. 
- Audience (User, Developer, Contributor, etc.): 
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): 
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout
- https://github.com/WordPress/gutenberg/issues/39651
- https://css-tricks.com/snippets/css/complete-guide-grid/

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue updated by @bsanevans to match the current topic vetting template._

**Comment by annezazu** [comment]
Noting this work around [the grid layout variation for the group block](https://make.wordpress.org/core/2024/02/28/whats-new-in-gutenberg-17-8-28-february/#grid-layout-variation) that's underway.
