### ISSUE TITLE
CSS Grid - Tutorial

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#712]
# Details

- Topic description: A basic understanding of CSS Grid is needed as a prerequisite to understanding how content aligns. Show this first in plain HTML/CSS context, and share where in Site Editor one can find settings related to Grid. 
- Audience (User, Developer, Contributor, etc.): Designers, Developers
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Tutorial
- WordPress version (optional): 
- Will you be creating this content? (Yes or No): 

# Related Resources

- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout
- https://css-tricks.com/snippets/css/complete-guide-grid/

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue update by @bsanevans to match current topic vetting template._

**Comment by kaitohm** [comment]
Tutorial of #711

**Comment by aplauche** [comment]
# Vetting Checklist for SMEs
- Priority:  Low
- Feedback regarding the topic description:

While understanding CSS grid is no doubt useful, I would put this at lower priority than more specifically WordPress focused topics like understanding how to effectively use the row / stack blocks. 

- Feedback regarding the learning objectives: 

None listed. Again I would prioritize being able to effectively use layout tools within WordPress, but this may fall into a different ticket.

- Any other feedback: 

At this stage I think a lesson around flexbox basics and then the group/row/stack would be more helpful. There is not really an implementation of CSS grid within WP at this point except if you are using plugins that add grid blocks like the one listed below in the article in related resources

# Related Resources
https://css-tricks.com/bringing-css-grid-to-wordpress-layouts/

**Comment by kaitohm** [comment]
Thanks for vetting this, @aplauche 🙌 Based on your feedback, and based on [the team prioritizing learning pathways](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) right now, I'll close this topic out. Our content creators can focus on other higher priority content 👍
