### ISSUE TITLE
Part 2: Personalized Site Design with Full Site Editing and Theme Blocks - Course

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#736]
Course link: https://learn.wordpress.org/course/part-2-personalized-site-design-with-full-site-editing-and-theme-blocks/

**Comment by westnz** [comment]
Changelog: 11 Aug 2023
- Updated the title of the course
- Updated the intro page description
- Updated the testing environment page
- Rehauled lessons 2 + 3 and updated them for the new 6.3 release
- Deleted lesson 4 (incorporated into lesson 3)
- Removed prerequisites 
- Removed 'pass required' for quizzes as adult learners don't always want to be limited and might only want to look at one lesson. 
- 
Changelog: 18 Aug 2023

- Swapped lessons 5 & 6
- Updated screenshots and videos for 6.3 (utilized documentation) + removed outdated content
- Added three videos from wordpress.tv 
- Updated quizzes + reflections and practical activities

The time it took to complete this course: approximately 16 -18 hours

**Comment by westnz** [comment]
Changelog: 18 Aug 2023

- Swapped lessons 5 & 6
- Updated screenshots and videos for 6.3
- Added three videos from wordpress.tv 
- Updated quizzes + reflections and practical activities
