### ISSUE TITLE
Part 3:Advanced Site Design using the Site Editor - Course

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#737]
Course link: https://learn.wordpress.org/course/part-3-advanced-site-design-with-full-site-editing-site-editor-templates-and-template-parts/

**Comment by azhiya** [comment]
Please review https://github.com/WordPress/Documentation-Issue-Tracker/issues/291.

**Comment by courtneyr-dev** [comment]
6.3 https://make.wordpress.org/core/2023/02/24/whats-new-in-gutenberg-15-2-22-february/#edit-templates-and-template-parts-fearlessly-with-revisions

https://make.wordpress.org/core/2023/03/22/whats-new-in-gutenberg-15-4-22-march/#updated-template-descriptions

**Comment by courtneyr-dev** [comment]
6.3 interface has changed, adds save https://github.com/WordPress/gutenberg/pull/47142

**Comment by westnz** [comment]
Changelog: 24 & 25 August 2023

- Updated Title
- Updated videos and screenshots for 6.3 
- Rearranged and updated lessons
- Removed redundant or out-of-date info + lessons
- Added new videos from wordpress.tv
- Updated quizzes + reflections and practical activities
- Removed 'pass required' for quizzes

The time it took to complete this course: approximately 16 -18 hours
