### ISSUE TITLE
Issue with select dropdown on Workshops page  

### ISSUE THREAD

**Issue by sumitsinghwp** [WordPress/Learn#740]
I have visited on https://learn.wordpress.org/workshops/  and i can able to open dropdown when client on other select box area instead of select drop-down icon right side.

More information you can see quick video.

 https://www.loom.com/share/8f76aeb4a29f42b99fd6297ece22d4f6

**Comment by hlashbrooke** [comment]
This has been resolved in another issue and PR, so closing this one.
