### ISSUE TITLE
Understanding Testing Instructions for Future WordPress Releases

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#744]
# Topic Description
The instructions given on future testing updates are wildly helpful, but sometimes can be confusing to newer users. This lesson plan aims to help users help themselves when they encounter obstacles in understanding directions, especially as they relate to unfamiliar or new terminology they may not yet know.

_Issue modified by @bsanevans to remove excess information._

**Comment by kaitohm** [comment]
This sounds like a good idea for a tutorial also. I've created a new issue for a tutorial: https://github.com/WordPress/Learn/issues/1082

**Comment by kaitohm** [comment]
Lesson plan of #1084

**Comment by devmuhib009** [comment]
@bsanevans I created a tutorial on this topic. My mistake, I didn't check topic ideas before making the video. However, please suggest me, if the turorial needs any adjustment. 
https://github.com/WordPress/Learn/issues/2269

**Comment by kaitohm** [comment]
No problem. Let's close this topic, and continue creating the Tutorial over on #2269 👍
