### ISSUE TITLE
Lesson Plan - Syntax Highlighter Code blocks formatting incorrectly

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#747]
When editing a Lesson Plan in the block editor, the Syntax Highlighter Code block does not display the code in the block.

![Edit-Lesson-Plan-“What-To-Include-In-functions-php-File”-‹-Learn-WordPress-—-WordPress](https://user-images.githubusercontent.com/180629/164313410-c2d39c99-bf88-4103-8412-00c2cdb5d285.png)

This seems to be related to the styling applied to the `.editor-styles-wrapper .wp-block-code` selector as well as the `.wp-block-code` selector, as disabling the `color` attribute for the former and the `padding` attribute for the latter returns the styling of that block to almost default.

![Screenshot from 2022-04-20 22-03-58](https://user-images.githubusercontent.com/180629/164314088-b9a4a52c-cbba-4f10-ac03-f4a0b988fb2f.png)

**Comment by hlashbrooke** [comment]
Is this still an issue with the updated code syntax block?

**Comment by jonathanbossenger** [comment]
No, now that we're using the new core code block in the editor. One just needs to update any existing instances of the old Syntax Highlighter Code blocks with the new core code block, which also has the benefit of the "copy" functionality on the front end.

**Comment by jonathanbossenger** [comment]
What we might want to do is review all existing lesson plans and update the code block. This might be something we could automate, but I'm not sure.
