### ISSUE TITLE
Como escolher e instalar plugins WordPress/ Choosing and Installing a Plugin Tutorial - Brazilian Portuguese

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#755]

**Comment by westnz** [comment]
Here is the link to the [workshop](https://wordpress.slack.com/archives/C02RW657Q/p1651783185672409).

**Comment by westnz** [comment]
Published Workshop: https://learn.wordpress.org/workshop/como-escolher-e-instalar-plugins-wordpress/

**Comment by kaitohm** [comment]
Updated the title from Workshop to Tutorial as per the name change.
