### ISSUE TITLE
Choosing and Installing a Theme Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#758]
https://learn.wordpress.org/lesson-plan/choosing-and-installing-themes/

**Comment by westnz** [comment]
Here is a [link](https://wordpress.slack.com/archives/C02RW657Q/p1653617911719669) to the video that was shared in the Training team Slack:

**Comment by peteringersoll** [comment]
I'm not a Github user so I'm not sure if I'm commenting in the right area or if this is feedback you're looking for. Anyway, at 45 seconds in, it is stated that "Plugins extend the functionality of your website, but themes change the look and layout of your site..." I think it's worth mentioning that themes can (dramatically) change the functionality of your site, change how the admin works, etc.

**Comment by peteringersoll** [comment]
Also, you might want to mention that the WP repository is the official site for plugins, but that there are premium themes also available and that often a free version in the repository may offer a premium theme directly from the developer or theme-selling site.

The last suggestion is a quick mention that thumbnails and sample sites are more suggestions and that things like images and, of course, works will change. You do mention theme previews giving an idea of what can be done. From my experience, I see that beginners often pick a theme based on the images used in a thumbnail and/or surprised when the them doesn't look like the thumbnail when activated.

**Comment by westnz** [comment]
Thank you @peteringersoll 👍

**Comment by westnz** [comment]
Published Tutorial: https://learn.wordpress.org/tutorial/choosing-and-installing-theme/

**Comment by courtneyr-dev** [comment]
https://core.trac.wordpress.org/ticket/56283

**Comment by Piyopiyo-Kitsune** [comment]
@westnz  can this be closed?

**Comment by westnz** [comment]
We can leave this open for now. Thanks @Piyopiyo-Kitsune

**Comment by robinpanthee** [comment]
wouldn't it be great if the video is of latest wordPress version? Overall, the video is super fine

**Comment by westnz** [comment]
Good point.  Thanks, @robinpanthee

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/49014 6.3

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/4188a5c7-a996-43b6-8975-bc3691674aa3

**Comment by wparasae** [comment]
This looks great, Wes! I really like the illustrations you used, they're very calming. :D I really like the overview you're giving of the 6.3 features. You've done an excellent job of highlighting the new dashboard from 6.3. 

These updates are solid. I appreciated the part where you talk about the user experience and draw attention to the reviews people have left and star ratings. Well done!

Options for revision:

1. Briefly add context: Some questions I had while watching around the 2:02-2:45 mark were, "What's the difference between a template and a page? Wait, what's a pattern?" At the same time, you don't want to get too deeply in the weeds with details there -- consider any resources on Learn to which you can refer people to learn more about these features, or add a brief sentence with a little more information about each one. For example, "I will change the style variation, which is BRIEF EXPLANATION" or "You can change the styles, which do BRIEF EXPLANATION". This will go a long way for beginners! :)

2. At 4:37 - Suggested add: Consider pointing out the "additional CSS" button in the customizer, as this is one way people make changes to their classic themes--through code. Here's an example screenshot you're welcome to use if you want:

<img width="1439" alt="Screenshot 2023-09-19 at 11 50 43 AM" src="https://github.com/WordPress/Learn/assets/101278360/9811f738-35fa-49cf-8b6e-d1c457720d66">

Excellent changes all around, however! Bravo!

**Comment by TinaCollier** [comment]
@westnz Hello Wes 👋  Thank you for sharing this great tutorial. 

My takeaways:

1. You clearly achieved all 4 of the objectives in the video: Differentiate between the 4 different types of themes. Find and evaluate themes. Install and update your theme. Access support for your theme.
2. You thoroughly explained the how a block theme works and walked through each part of the Editor. You spent less time on the other types of themes, but you mention that the Classic themes are the most common and have the most to choose from.
3. I like how you reviewed finding and evaluating a good theme. Its so important for users to understand the drawbacks with using a theme with little documentation and a low rating, so I appreciate you taking the time to discuss this part of the process.

Some suggestions I have:

1. You mention that there is a difference between the content and presentation: that a site's content doesn't change but the look of the site can using different themes. Would it be possible to include an example of two or more themes that contain the same content? This could be a screenshot of a page with the same content using different themes. It may help enhance the concept for some learners.
2. You quickly mention child themes at about 8:10 when updating a theme. I know it may be unnecessary for this tutorial, but it may be useful to mention what they are during the presentation.

I found this to be a great tutorial for beginner WordPress users. You manage to keep the high level concepts understandable while providing enough depth of information for the user to learn what a theme is, and how to install and manage one.

**Comment by westnz** [comment]
Thank you @wparasae and @TinaCollier, for the helpful feedback!!

**Comment by Zebedeu** [comment]
Hi,

Regarding the tutorial being proposed, it seems to be a very useful tool, covering the most important aspects especially for beginner users.

 For revision:

However, it is important to emphasize that not all theme options available in the repository will have the same appearance when activated. This is because some themes may require specific plugins to be installed or additional configurations to be made in order to achieve the same initial appearance.

**Comment by westnz** [comment]
Thank you @Zebedeu. That is a very good point!

**Comment by Rashigupta2999** [comment]
Hi @westnz ,

In my opinion, this video is excellent for beginners who want to understand themes. You explain all the important points in an easy-to-understand manner.

**Comment by westnz** [comment]
Much appreciated @Rashigupta2999

**Comment by westnz** [comment]
Thank you for reviewing. I will consolidate the feedback and publish it this week.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/choosing-and-installing-theme/

**Comment by westnz** [comment]
Updated and published in Sensei as part of the draft Beginner User learning pathway.
