### ISSUE TITLE
Principles of Free Software and the WordPress project Quiz question bugs

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#760]
[Open Source Basics and WordPress](https://learn.wordpress.org/course/open-source-basics-and-wordpress/) course, 
 [Principles of Free Software and the WordPress project Quiz](https://learn.wordpress.org/learn/quiz/principles-of-free-software-and-the-wordpress-project-3/) quiz.

1. In the third option of the first question, and ampersand character is not displaying correctly.
1. The 3rd question on the has a confusing answer selection. The answer marked as correct is the first option, but based on the text on the [Principles of Free Software and the WordPress project](https://learn.wordpress.org/lesson/principles-of-free-software-and-the-wordpress-project/) lesson, the last answer could also be correct.

**Comment by hlashbrooke** [comment]
Thanks - I have fixed the ampersand issue.

The issue with the incorrect answer is fine in the question itself, but the content of the lesson was actually incorrect in its assertion about the plugin/theme directories, so I have updated the lesson to be accurate.
