### ISSUE TITLE
Community Meeting Etiquette course is missing actions

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#761]
The [Community Meeting Etiquette](https://learn.wordpress.org/course/community-meeting-etiquette/) doesn't have the Course Signup, View Results, Course Progress, and Course Outline elements.

![learn wordpress org_course_community-meeting-etiquette_](https://user-images.githubusercontent.com/180629/168801367-2e5c4ee3-31c7-4925-8c12-4fe6a1ffd0dd.png)

**Comment by hlashbrooke** [comment]
Thanks for reporting - this is now fixed.
