### ISSUE TITLE
Inconsistencies within the Course titled 'Getting Started With WordPress: Get Setup'

### ISSUE THREAD

**Issue by chaion07** [WordPress/Learn#762]
Title: Why WordPress Is For Everyone Quiz
The Quiz: https://learn.wordpress.org/learn/quiz/3-why-wordpress-is-for-everyone/

One of the choices within question 1 has a spelling error
![image](https://user-images.githubusercontent.com/64467850/168994245-30cb5701-cf1e-47cf-9f2d-92350080d571.png)
This is a very easy fix.

Additionally the result of the quiz doesn't seem consistent either
![image](https://user-images.githubusercontent.com/64467850/168994399-066088fd-aff3-4f06-ad41-a36aad4831d4.png)
Since there is no right or wrong answer the quiz should identify any response for Question 2 as Correct.

Thanks!

**Comment by azhiya** [comment]
@wparasae I think this is one of yours, correct?

**Comment by azhiya** [comment]
Hi, @wparasae I've updated the spelling error but not show how to fix the issue with Question 2.

**Comment by chaion07** [comment]
> Hi, @wparasae I've updated the spelling error but not show how to fix the issue with Question 2.

Thanks @azhiya for the work so far on this.

**Comment by kaitohm** [comment]
I've fixed issue 2 by removing any feedback from this question.
