### ISSUE TITLE
Author archive - Lesson Plan

### ISSUE THREAD

**Issue by courtneyr-dev** [WordPress/Learn#764]
# Details

- Topic description:
   - Create the Author template
   - Demonstrate how to use the Author Name block and Author Bio block on posts
- Audience (User, Developer, Contributor, etc.): User
- Learning objectives: 
- Content type (Course, Tutorial, Online Workshop, or Lesson Plan): Lesson Plan
- WordPress version (optional): 6.0
- Will you be creating this content? (Yes or No): 

# Related Resources

# Next steps for SMEs
Please follow the team handbook "[Vetting topic ideas](https://make.wordpress.org/training/handbook/training-team-how-to-guides/vetting-topic-ideas/)" to vet this topic.

_Issue updated by @bsanevans to match the current topic vetting template._

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/36001

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/38269

**Comment by bsanevans** [comment]
@courtneyr-dev Could you update the issue with an audience, and some learning objectives, in preparation to be vetted by SMEs please? Thanks.
