### ISSUE TITLE
Nigerian Pidgin Translation: Choosing and Installing a Plugin - Workshop

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#766]

**Comment by westnz** [comment]
Hey @azhiya!  Could you please assign @Kemmy99 to this issue? Thanks

**Comment by azhiya** [comment]
I love that you are working on a Pidgin version of this @kemmy99. Please comment on the card so we can assign you.

**Comment by Kemmy99** [comment]
Thank you @azhiya and @westnz , I want to work on it.

**Comment by azhiya** [comment]
Hi, @Kemmy99 there are a number of different Pidgin translations https://en.wikipedia.org/wiki/Pidgin#Examples. I'm assuming this is the Nigerian pidgin, is that correct?

**Comment by Kemmy99** [comment]
Yes. This one below.
 https://en.wikipedia.org/wiki/Nigerian_Pidgin
 Not straight English. E.g- Na mi dey talk, instead of I am the one
speaking or talking.

**Comment by azhiya** [comment]
Updated the title to make it clear that it is Nigerian Pidgin.

**Comment by azhiya** [comment]
@Kemmy99 I've created the outline [Lesson Plan](https://learn.wordpress.org/?p=18979&post_type=lesson-plan&preview_id=18979) on Learn for you to update when you have finished drafting. I would recommend the title be in Nigerian Pidgin as well.

**Comment by westnz** [comment]
Hey @azhiya I think she is actually going to translate the current workshop and present it in Nigerian Pidgin.  I know this is on hold at the moment.  Sorry, I assume we need to update the title to state 'Workshop' at the end.

**Comment by azhiya** [comment]
I've updated the Title. Thanks @westnz

**Comment by kaitohm** [comment]
I'm closing this issues as it has been stale for a while. Please comment on the issue if someone would like to actively work on it again.
