### ISSUE TITLE
Update pages referencing Trello to point to GitHub

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#768]
1. https://make.wordpress.org/training/handbook/about/team-roles/
2. https://make.wordpress.org/training/handbook/about/our-contributor-ladder/
3. https://make.wordpress.org/training/handbook/getting-started/
4. https://make.wordpress.org/training/handbook/getting-started/how-we-work-together/
5. https://make.wordpress.org/training/handbook/getting-started/team-on-boarding/

**Comment by jomarieminney** [comment]
Also on the form here: https://make.wordpress.org/training/getting-started/contact/

**Comment by jomarieminney** [comment]
A lot of the links on the Getting Started > Team Onboarding also still link to Trello - e.g. Roadmaps.

**Comment by jomarieminney** [comment]
@jonathanbossenger while you are there.. there is also a typo on this page - Item 5 should be Reviewing not revewing ;)
https://make.wordpress.org/training/handbook/getting-started/training-team-how-to-guides/

**Comment by jomarieminney** [comment]
https://make.wordpress.org/training/handbook/getting-started/training-team-how-to-guides/reviewing-learn-content-errors/
More Trello

**Comment by jomarieminney** [comment]
https://make.wordpress.org/training/handbook/lesson-plans/auditing-lesson-plans/#trello

**Comment by jonathanbossenger** [comment]
@jomarieminney I've updated the references to Trello in the about and getting started sections, but not the reviewing/auditing sections, because I think those need to be reviewed/updated for Github, and it's not just a simple copy paste. I'll bring this up in the APAC training team meeting, but also during contributor day today.
