### ISSUE TITLE
Shortcodes not displaying as they are being rendered.

### ISSUE THREAD

**Issue by jomarieminney** [WordPress/Learn#769]
On this section of this page:
https://make.wordpress.org/training/getting-started/lesson-style-guide/#formatting
The shortcodes for emphasized texts are rendering on the page, so you can't actually see the shortcodes themselves. It might be better to use a code block here?
![image](https://user-images.githubusercontent.com/53484448/171256720-22f60526-a15c-48f8-b2fe-df0b576d6bb4.png)

**Comment by azhiya** [comment]
I've converted this page to Blocks and updated it.
