### ISSUE TITLE
Update Workshop Presenter Application form

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#775]
Hi there, we need to update the Workshop Presenter Application form on this page [here](https://learn.wordpress.org/workshop-presenter-application/) to remove the Presenter Details section which includes:

- WordPress.org User Name
- First Name
- Last Name
- Email
- Where can we find you online? Please share links to your website(s) and as many social media accounts as applicable, including but not limited to Twitter, Linkedin, Facebook, Instagram, etc.

Can we also update the name of this form from `Workshop Application Form` to `Workshop Submission Form`?

The code for this form lives [here](https://github.com/WordPress/Learn/blob/trunk/wp-content/plugins/wporg-learn/inc/form.php).

**Comment by hlashbrooke** [comment]
For reference, the plan is to separate the forms, so the current only captures workshop data (we'll still need the submitter's username to go through), and there's a separate form for a general application to become a presenter, but that will be created with Jetpack to go directly to the inbox.

**Comment by hlashbrooke** [comment]
@Piyopiyo-Kitsune Is this still something we need done from the dev team?

**Comment by Piyopiyo-Kitsune** [comment]
Sorry, I seem to have missed the ping here @hlashbrooke. We moved the application to Jetpack forms so this can be closed.
