### ISSUE TITLE
WordPress Action Hooks - Workshop

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#776]
# Topic Description
Covering the fundamentals of the WordPress Action Hooks system, how to register and use action hooks, action priority, and action arguments. 

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.

- [WordPress Hooks](https://developer.wordpress.org/plugins/hooks/)
- [Action hooks](https://developer.wordpress.org/reference/functions/add_action/)

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Workshop Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop published on WPTV
- [x] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [x] Workshop created on Learn.WordPress.org
- [x] Workshop post is reviewed for grammar, spelling, etc.
- [x] Workshop published on Learn.WordPress.org
- [x] Workshop announced to training team
- [x] Workshop announced to creator
- [ ] Workshop announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/176402305-0c6fa2f3-8a88-4d64-a3d0-4aea8bc978c2.mp4

**Comment by westnz** [comment]
Hey Jonathan!

- It was a good idea to break the workshops up in two.
- You clearly communicate the learning objectives.
- You have used annotations effectively.
- You go at a pace I think learners will be able to follow comfortably.

Well done!

**Comment by jonathanbossenger** [comment]
Thanks @westnz

**Comment by amitpatel0702** [comment]
Hi @jonathanbossenger,

- I must say, Video is concise.
- You have shown examples accurately wherever needed.
- The last point mentioning the action reference list is going to be helpful.
- Flow of the video and plan is very clear and point straight.
- **A suggestion:** Can we add the following statement somewhere into the first slide - **_WordPress Hooks allows you to insert custom code into WordPress Core via your custom code to modify anything._**

**Comment by jonathanbossenger** [comment]
Hi, @amitpatel0702, thanks for the feedback.

> A suggestion: Can we add the following statement somewhere into the first slide - WordPress Hooks allows you to insert custom code into WordPress Core via your custom code to modify anything.

I don't know if I would agree with that statement though, you're not actually inserting custom code into WordPress core, and you can't modify anything, only that which the action or filter hook provides. 

This is why I went with what the official WordPress documentation says about [Hooks](https://developer.wordpress.org/plugins/hooks/)

> Hooks are a way for one piece of code to **interact/modify** another piece of code at specific, pre-defined spots.

So you're either **interacting** with WordPress core (via actions, this video) or **modifying** a WordPress core variable (via filters, the [Filters](https://github.com/WordPress/Learn/issues/795) video).

Does this make sense?

**Comment by amitpatel0702** [comment]
Hi @jonathanbossenger,

It completely makes sense. Agree with you on that.

**Comment by jonathanbossenger** [comment]
This has been published https://learn.wordpress.org/tutorial/wordpress-action-hooks/
