### ISSUE TITLE
Presenter Style: The CSS is not being applied.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#78]
### Description
Locally, the styles are being applied. On `learn.wordpress.org` the presenter is not getting its style.

Either there is a conflict or the CSS should be rebuilt.

### Screenshot

| Learn.wordpress.org INCORRECT | localhost:8888 CORRECT |
| ----- | ----|
| ![](https://d.pr/i/kGkzAd.ong) | ![](https://d.pr/i/B2u9cN.png) |

You can verify that the changes work by making sure the `img` tag has the `.workshop-presenter_profile` class.

**Comment by StevenDufresne** [comment]
This also appears to be running an old CSS version. The box should have a border, not a box-shadow.
![](https://d.pr/i/bUPoZi.png)

**Comment by dd32** [comment]
This should be fixed as of 832e1008813367a813350ef4f74b8ce7f83de0ae I think, look good to you now @StevenDufresne ?

**Comment by StevenDufresne** [comment]
yes.
