### ISSUE TITLE
Horizontal Pyramid Gallery - Workshop

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#789]

**Comment by westnz** [comment]
Hey, @azhiya Could we please add this to the June Sprint?  Many thanks

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/175846507-321f6861-cef1-4b57-b31d-7dec651074d4.mp4

**Comment by samxmunoz** [comment]
This was a great tutorial & taught lots of interesting skills. 🎉 

Did you need to do anything special to the row so the columns wouldn't stack on mobile? That's the only thing I think may need to be added or mentioned @westnz.

**Comment by westnz** [comment]
Thank you so much @samxmunoz

**Comment by westnz** [comment]
Published Tutorial: https://learn.wordpress.org/tutorial/horizontal-pyramid-gallery/
