### ISSUE TITLE
List View Functionality - Workshop (Brazilian Portuguese)

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#791]

**Comment by westnz** [comment]
Here is the link to the video and feedback. https://wordpress.slack.com/archives/C02RW657Q/p1655844289202409

**Comment by fellyph** [comment]
@westnz I have included the new blocking block feature and add more time testing the list view that is why has more time them the english version.

**Comment by RafaelFunchal** [comment]
I reviewed the video shared [here](https://wordpress.slack.com/archives/C02RW657Q/p1655846878099269?thread_ts=1655844289.202409&cid=C02RW657Q). IMHO, it is perfect! <3

**Comment by westnz** [comment]
@fellyph You can go ahead and publish this workshop. Follow the same steps as last time. https://make.wordpress.org/training/handbook/workshops/publishing-a-workshop/

Let me know once the video and subtitles are uploaded onto wordpress.tv, then I can approve them for you.

Thank you for this amazing work!!

**Comment by fellyph** [comment]
Thanks! @RafaelFunchal @westnz

**Comment by westnz** [comment]
Published Tutorial: https://learn.wordpress.org/tutorial/introducao-a-visualizacao-em-lista/
