### ISSUE TITLE
Greek translation for Photo Directory lesson plan

### ISSUE THREAD

**Issue by vagelisp** [WordPress/Learn#793]
# Topic Description
Greek translation for Photo Directory lesson plan

# Related Resources
The original Lesson Plan
[How to Use and Contribute to the WordPress Photo Directory and Openverse](https://learn.wordpress.org/lesson-plan/how-to-use-and-contribute-to-the-wordpress-photo-directory-and-openverse/)

The translated version of the Lesson Plan in google docs
https://docs.google.com/document/d/1G24F-Xp0eLuZ-5D6kdQyRT_xWF6Ldr4wZuAswKVRdvk

**Comment by azhiya** [comment]
I've added this to the Content board. @bsanevans does this need to be reviewed further.

**Comment by kaitohm** [comment]
@azhiya I'm not familiar with the localization of material. Do we explicitly need a second person to review the translation? If no process has been determined here, then **_I suggest we publish this content as-is_**. (More localized stuff, the better!) We can always come back and make edits later, if need be.

**Comment by kaitohm** [comment]
@lenasterg conducted a review of the translation on this lesson plan, and has mentioned it looks perfect! ([Slack convo](https://wordpress.slack.com/archives/C02RP50LK/p1656308584855699))

I'll add this to learn.wordpress.org this week.

**Comment by azhiya** [comment]
> @azhiya I'm not familiar with the localization of material. Do we explicitly need a second person to review the translation? If no process has been determined here, then **_I suggest we publish this content as-is_**. (More localized stuff, the better!) We can always come back and make edits later, if need be.

Thanks @bsanevans there is no formalised process for the localisation of lesson plans. I'm happy to go with your suggestion of leaving it as-is and making edits later. We can always agree on a process at a later time if need be.

**Comment by kaitohm** [comment]
This lesson plan has now been published!

https://learn.wordpress.org/lesson-plan/%cf%80%cf%8e%cf%82-%ce%bd%ce%b1-%cf%87%cf%81%ce%b7%cf%83%ce%b9%ce%bc%ce%bf%cf%80%ce%bf%ce%b9%ce%ae%cf%83%ce%b5%cf%84%ce%b5-%ce%ba%ce%b1%ce%b9-%ce%bd%ce%b1-%cf%83%cf%85%ce%bd%ce%b5%ce%b9%cf%83%cf%86/

@vagelisp thanks for all your work on this!
- Could you just double check and make sure I've copied the Greek over to the new lesson plan correctly?
- Also, I've added a new Category to [Learn WordPress](https://learn.wordpress.org/) called `Ελληνικά`. Is that the correct Greek translation for the word "Greek"?

Once you've been able to confirm those two points, I think this GitHub issue is ready to be closed 🎉

**Comment by vagelisp** [comment]
Hello, @bsanevans, thanks for all the help. 

- The lesson plan looks great.
- `Ελληνικά` is perfect as a category name, thank you.

**Comment by kaitohm** [comment]
Cool! Thanks @vagelisp ! I'm marking this issue as completed.
