### ISSUE TITLE
How to Create a Post or Page with the WordPress Block Editor - Tutorial (Brazilian Portuguese)

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#794]

**Comment by westnz** [comment]
Here is the link to the video: https://wordpress.slack.com/archives/C02RW657Q/p1655921849888749

**Comment by westnz** [comment]
Review was left in Slack: 
<img width="392" alt="image" src="https://user-images.githubusercontent.com/89751452/178377012-ce1aa51d-c76b-49c1-a146-8fe63a69137d.png">

**Comment by azhiya** [comment]
Updated the title from Workshop to Tutorial as per the name change.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/como-criar-um-post-ou-pagina-com-o-editor-de-blocos-wordpress/
