### ISSUE TITLE
WordPress Filter Hooks - Workshop

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#795]
# Topic Description
Covering the fundamentals of the WordPress Filter Hooks system, how to register and use filter hooks, filter priority, and filter arguments. 

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.

- [WordPress Hooks](https://developer.wordpress.org/plugins/hooks/)
- [Filter hooks](https://developer.wordpress.org/reference/functions/add_filter/)

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Workshop Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [x] Workshop submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Workshop submitted to WPTV https://wordpress.tv/submit-video/
- [x] Workshop published on WPTV
- [x] Workshop is captioned https://learn.wordpress.org/handbook/handbook/workshop-captions-and-transcripts/
- [x] Workshop created on Learn.WordPress.org
- [x] Workshop post is reviewed for grammar, spelling, etc.
- [x] Workshop published on Learn.WordPress.org
- [x] Workshop announced to training team
- [x] Workshop announced to creator
- [x] Workshop announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/176387934-6c2b7148-5790-4470-afbd-7fde1d5a62d0.mp4

**Comment by westnz** [comment]
Hey Jonathan! **Same feedback as previous workshop** 😆 

- It was a good idea to break the workshops up in two.
- You clearly communicate the learning objectives.
- You have used annotations effectively.
- You go at a pace I think learners will be able to follow comfortably.

**Comment by jonathanbossenger** [comment]
Thanks @westnz

**Comment by amitpatel0702** [comment]
Hi @jonathanbossenger,

- You mentioned the difference between filter and action hooks in the initial part of the video very well.
- You explained the parameters part and content return type very well with an example.
- Learners can distinguish various ways to call the function using parameters through your example.
- Your workshop video is up to the mark with brief details that are required.

**Comment by jonathanbossenger** [comment]
Tutorial published https://learn.wordpress.org/tutorial/wordpress-filter-hooks/
