### ISSUE TITLE
Intro the Site Editor and Template Editor - Tutorial (Brazilian Portuguese)

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#796]

**Comment by westnz** [comment]
Here is the link to the video: https://wordpress.slack.com/archives/C02RW657Q/p1656007396457359

**Comment by paulopmt1** [comment]
Hello @westnz,
I loved the video. It was easy to follow and understand. The translation was 100%.

About the content, it was clear its focus was to show how to create new models and model parts. I'm pretty sure it will help our users!

Do we have a plan to create (or already have) videos like this showing how to use predefined layouts?

**Comment by westnz** [comment]
Thank you for reviewing @paulopmt1. We need to look into creating a video about predefined layouts. Good idea!

**Comment by azhiya** [comment]
I've updated the title from Workshop to Tutorial as per the name change.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/introducao-ao-editor-de-site-e-ao-editor-de-modelos/
