### ISSUE TITLE
WordPress Dashboard Issue

### ISSUE THREAD

**Issue by adnan159** [WordPress/Learn#799]
There is a issue in WordPress dashboard. Deprecated: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated 

https://prnt.sc/WHSC4O5gmxJB

**Comment by vagelisp** [comment]
Hello @adnan159, this repository is for [Learn.wordpress.org](https://learn.wordpress.org/).
This warning seems to be on a self-hosted WordPress installation. If that's the case, use the [support forum](https://wordpress.org/support/forums/) if you are seeking support, or https://make.wordpress.org/core/handbook/testing/reporting-bugs/ if you want to report a bug

**Comment by azhiya** [comment]
Closed as this is not related to Learn WordPress
