### ISSUE TITLE
Fix some of the awkward styles

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#8]
- Some titles are underlined, they shouldn't be.
- Lesson Plan: Checkboxes list have bullets, shouldn't.

**Comment by StevenDufresne** [comment]
I looked into the awkward layout here:

![](https://d.pr/i/Phxcd9.png)

This is an issue with the importer which doesn't distinguish between a list of text nodes and a list of checkboxes. Github itself adds specific styling for a list of checkboxes. We would need to update jetpack's parser or reparse it ourselves. Regardless of the solution, it should fall outside of the first milestone.

**Comment by hlashbrooke** [comment]
I'm closing this issue in light of it being covered by #245 going forward.
