### ISSUE TITLE
How to create a landing page with a block theme - Workshop

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#804]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/178191328-fcf72a52-b522-498e-8a34-5fd2155f7025.mp4

**Comment by amitpatel0702** [comment]
Thanks @westnz for such a lovely piece of learning video.

- I loved the way you presented Elements of a landing page.
- You presented **editing Custom template** template very way. You made it look easy.
- WPForms part was awesome as well. Very simple to set it up and start using it with Gutenberg.
- The last portion of using pattern was simply amazing.

**Comment by westnz** [comment]
Thank you for the feedback @amitpatel0702 Much appreciated.

**Comment by westnz** [comment]
I also want to show how you could use a Row block to create a testimonial.

<img width="1516" alt="image" src="https://user-images.githubusercontent.com/89751452/182275910-9dd4ceaa-0d87-43d4-8479-44fb5a35cdca.png">

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/creating-a-landing-page-with-a-block-theme/
