### ISSUE TITLE
WordPress Action Hooks - Lesson Plan

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#806]
# Topic Description
Lesson plan based on the soon to be published [WordPress Action Hooks workshop](url)

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.

- [WordPress Hooks](https://developer.wordpress.org/plugins/hooks/)
- [Action hooks](https://developer.wordpress.org/reference/functions/add_action/)

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Development Checklist:
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the example lesson walk-through
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Announce to the Training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

# Repo Structure and Lesson Plan Template

> <span style="color:red">Please remove all blockquote comments such as this before publishing.</span>

## Description

> A short paragraph explaining what is covered in the lesson plan. This should be text that can be copied and used in a meetup or workshop description.

## Objectives

After completing this lesson, participants will be able to:

* Objective 1
* Objective 2

> It’s required that you include a bulleted list of objective(s) for each lesson plan. Objectives should be worded as actions that the participant can do once they’ve finished. See [Bloom's Taxonomy of Action Verbs](http://www.fresnostate.edu/academics/oie/documents/assesments/Blooms%20Level.pdf) (PDF) as a reference. Avoid using words like "know," "understand," "be introduced to," etc. There should be one assement item for each objective (see below).

## Target Audience

Who is this lesson intended for? What interests/skills would they bring? Put an "x" in the brackets for all that apply.

* [ ] Users / Content Writers
* [ ] Designers
* [ ] Developers
* [ ] Speakers
* [ ] Organizers
* [ ] Kids

## Experience Level

How much experience would a participant need to get the most from this lesson? Put an "x" in the brackets for all that apply.

* [ ] Beginner
* [ ] Intermediate
* [ ] Advanced

## Type of Instruction

Which strategies will be used for this lesson plan? Put an "x" in the brackets for all that apply.

* [ ] Demonstration
* [ ] Discussion
* [ ] Exercises
* [ ] Feedback
* [ ] Lecture (Presentation)
* [ ] Slides
* [ ] Show & Tell
* [ ] Tutorial

## Time Estimate (Duration)

How long will it take to present this lesson? Put an "x" in the brackets for the one that applies.

* [ ] 1 hour or less
* [ ] 2-4 hours (half-day)
* [ ] 5-8 hours (full-day)
* [ ] 2 days
* [ ] 3 days or more

## Prerequisite Skills

Participants will get the most from this lesson if they have familiarity with:

* Skill 1
* Skill 2

> _For example:_
>
> *   Experience with HTML and CSS
> *   Completed the Basic WordPress Concepts lesson

## Readiness Questions

* Question 1
* Question 2

> A list of questions for participants to see if they have the background and skills necessary to learn and understand the lesson.
>
> _For example:_
>
> *   Do you want to makes changes to your theme yourself?
> *   Do you know how to write CSS?

## Slides

> Change the `/repo-name/` in the link to match the URL name of this repo.

*   [Slides](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/) (files included in this repo)

## Materials Needed

* Item 1
* Item 2

> A list of files, resources, equipment, or other materials the presenter will need for the lesson.
>
> _For example:_
>
> *   A local install of WordPress
> *   The files for the TwentySixteen theme

## Notes for the Presenter

* Note 1
* Note 2

> A list of any handy tips or other information for the presenter.
>
> _For example:_
>
> *  Participants may need to download the TwentySixteen theme before beginning
> *  What to do if there’s no projector or internet available
> *  What to do if a participant doesn’t have the necessary set up
> *  How to handle different opinions about the topic

## Lesson Outline

* First do this
* Then move on to this
* Finish with this

> The plan for the lesson. Outline form works well.
>
> _For example:_
>
> * Talk about what a theme is
> * Demonstrate how to install and activate a theme
> * Practice exercises to have participants find and install a theme on their own site

## Exercises

**Exercise name**

Short description of what the exercise does and what skills or knowledge it reinforces.

*   Short point or step of the exercise
*   And another one

> These are short or specific activities that help participants practice certain components of the lesson. They should not be fully scripted exercises, but rather something that participants could do on their own. For example, you can create an exercise based on one step of the Example Lesson.

## Assessment

There should be one assement item (or more) for each objective listed above. Each assessment item should support an objective; there should be none that don't.

**Write out the question.**

1.  Option
2.  Option
3.  Option
4.  Option

**Answer:** 3\. Correct answer

> A few questions to ask participants to evaluate their retention of the material presented. They should be a measure of whether the objectives were reached. Consider having a question for each objective.

## Additional Resources

* Resource 1
* Resource 2

> An optional section which can contain a list of resources that the presenter can use to get more information on the topic.
>
> _For example:_
>
> * Link to information on the Codex
> * Theme Review Team's Handbook

## Example Lesson

> An example of how the lesson plan can be implemented. Written in script form as one possible way an presenter might use this lesson plan at an event, with screenshots and instructions if necessary.

### Section Heading for Example Lesson

> You will likely need to break the Example Lesson down into multiple sections.

### Lesson Wrap Up

![](https://raw.githubusercontent.com/wptrainingteam/contributor-resources/master/images/lightbulb.png) Follow with the [Exercises](#Exercises) and [Assessment](#Assessment) outlined above.

**Comment by jonathanbossenger** [comment]
Lesson plan draft ready for review:

https://learn.wordpress.org/?p=19007&post_type=lesson-plan&preview=1&_ppp=2c7209ce7a

**Comment by kaitohm** [comment]
@jonathanbossenger This issue wasn't in the Content Development project board, which is probably why it never got reviewed. Could you generate another preview link, please?

**Comment by kaitohm** [comment]
Here is a new public review link https://learn.wordpress.org/?p=19007&post_type=lesson-plan&preview=1&_ppp=c8e901a221

**Comment by jonathanbossenger** [comment]
@bsanevans apologies, this notification didn't get to me. Thanks for posting the new preview link

**Comment by quitevisible** [comment]
I tried clicking the preview link above. Says it’s expired.

![Image](https://github.com/WordPress/Learn/assets/4922363/a1ec6fe2-6967-4781-a7e0-7af4ebdf0fda)

**Comment by jonathanbossenger** [comment]
Thanks, @quitevisible. Here's a new link:

https://learn.wordpress.org/?p=19007&post_type=lesson-plan&preview=1&_ppp=0e0d595fbc

Let me know if you can't access that one, and I'll try and find a different way to share the info.

**Comment by quitevisible** [comment]
That link works @jonathanbossenger . Some observations moving from start to finish of the Lesson Plan...

- The link to 'slides' currently goes to 404 page ( https://wptrainingteam.github.io/lesson-plans/repo-name/slides/ )  
- The last 2 questions and answer choices in the Assessment are identical, but have different answers. (screenshot-01)  
- A few callback function names seem to not match up (screenshots 02,03)  

Before jumping into a lesson or course, I generally like to scan through the outline first, to get a feel for whether or not I'll be able to comprehend and digest the content. This was structured well and provided good reference links, enough for me to feel comfortable diving into setting up a child theme and dev environment to complete the exercises. Looking forward to revisiting it once published live!  

*****  

#### screenshot-01  

<img width="589" alt="Screenshot-01" src="https://github.com/WordPress/Learn/assets/4922363/f8fcacfa-4b78-4fbc-9377-5a190f43c87d">  

### screenshot-02  

<img width="624" alt="Screenshot-02" src="https://github.com/WordPress/Learn/assets/4922363/408e9c31-f6fe-4aa0-9a1c-d8a9986be87f">  


### screenshot-03  

<img width="627" alt="Screenshot-03" src="https://github.com/WordPress/Learn/assets/4922363/95bf502a-5935-49e5-8a12-5fbd0403edf0">

**Comment by jonathanbossenger** [comment]
@quitevisible I know this is months late, but I wanted to thank you for your feedback. I will review, and incorporate the updates where needed.

**Comment by yuliyang** [comment]
In the end, the link "Action Reference" or reference section, you may also want to link to the developer resource that has the latest hooks:
https://developer.wordpress.org/reference/hooks/

**Comment by jonathanbossenger** [comment]
@yuliyang thanks for the feedback.

I'd prefer to also keep the link to the Codex page, primarily because it contains all the hooks on one page and, more importantly, in hook-firing order. I'm in the process of [migrating this page over to DevHub](https://github.com/WordPress/Documentation-Issue-Tracker/issues/370), so once that's done I can update this lesson plan with the new link. 

I have however added the link to the reference page as well. More information is always good.
