### ISSUE TITLE
Add language meta field for lesson plans

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#811]
Workshops have an autocomplete meta field for the workshop language, but lesson plans do not. We need to add this same meta field to lesson plans and then filter the lesson plan archive page based on the language the site is currently being viewed in (which is how workshops currently work).

**Comment by hlashbrooke** [comment]
Once we have this in place for courses, online workshops and lesson plans, then I'd like to integrate this meta field with the existing locale switcher so that content in the selected locale is given priority in all queries.

**Comment by piermario** [comment]
Hello @hlashbrooke! Have you considered adding a language filter in the lesson plan result page sidebar as well? Would that be harder than implementing the language priority function linked to the existing locale switcher? Thanks for your consideration. :)

**Comment by hlashbrooke** [comment]
Yeah - we have that for Tutorials and it makes sense to have it on Lesson Plans - I actually thought we did have it, but just checked now and I see we don't.

**Comment by piermario** [comment]
Thanks for checking! A boy can dream, then. 😇

**Comment by adamwoodnz** [comment]
Done in #1030
