### ISSUE TITLE
Creating a new header with blocks - Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#812]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/182048700-b7aa0b2d-94c0-497d-af5d-6ee5b0f986e9.mp4

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/creating-a-new-header-with-blocks/

**Comment by azhiya** [comment]
Closing this now that it has bene published.

**Comment by courtneyr-dev** [comment]
6.1 

Visuals: [footer patterns image](https://drive.google.com/file/d/1x2VGZJv6FnLqJQcYjvhe4dGTLKWSbdaR/view?usp=sharing), [replacing a header with a pattern video](https://drive.google.com/file/d/1vu00VdOcZ5Eo9RBIVJahfY0alAoXK_pc/view?usp=sharing).

Adoption approach: N/A

Key Make Posts/GitHub/Trac Issue(s): 

[Bundle new collection of Header and Footer block patterns](https://github.com/WordPress/gutenberg/pull/43157#top)
[Introduce new “banner” category](https://github.com/WordPress/gutenberg/pull/44203)
[Introduce new “footer” category](https://github.com/WordPress/gutenberg/pull/44200)

**Comment by courtneyr-dev** [comment]
6.1 changes pushed to 6.2
