### ISSUE TITLE
Customizing a footer with patterns - Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#813]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/189012893-9f02e482-9aca-4adb-acf3-3dd4776938cf.mp4

**Comment by westnz** [comment]
**Review: Courtney Patubo Kranzke** 

"At about 6:00, I wasn't sure what changing the navigation orientation to vertical did — it wasn't visually apparent to me. Is it worth explaining what that does quickly? Or is it something obvious that everyone else knows and it's only me learning for the first time"

**Comment by westnz** [comment]
**Review: Sarah Snow**

"I love that you talk about "why" -- it aims to improve user experience indeed. Good adult learning principal! Around the :11 mark, you might consider showing an example of a footer to orient the viewer a little quicker, but that's an optional add."

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/customizing-a-footer-with-patterns/

**Comment by courtneyr-dev** [comment]
6.1 changes: 

Visuals: [footer patterns image](https://drive.google.com/file/d/1x2VGZJv6FnLqJQcYjvhe4dGTLKWSbdaR/view?usp=sharing), [replacing a header with a pattern video](https://drive.google.com/file/d/1vu00VdOcZ5Eo9RBIVJahfY0alAoXK_pc/view?usp=sharing).

Adoption approach: N/A

Key Make Posts/GitHub/Trac Issue(s): 

[Bundle new collection of Header and Footer block patterns](https://github.com/WordPress/gutenberg/pull/43157#top)
[Introduce new “banner” category](https://github.com/WordPress/gutenberg/pull/44203)
[Introduce new “footer” category](https://github.com/WordPress/gutenberg/pull/44200)

**Comment by courtneyr-dev** [comment]
6.1 changes pushed to 6.2
