### ISSUE TITLE
Renaming content types

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#818]
As per [this discussion about the naming of workshops and social learning spaces](https://make.wordpress.org/training/2022/07/03/discussion-naming-content-types-on-learn-wordpress/), we are changing these content types' names as follows:

* Workshops -> Tutorials
* Social learning spaces -> Online workshops

In order to do this, we will need to make a number of changes around the site - some in the code and some in the content. Here is a comprehensive list of the needed changes:

**Page titles and slugs:**

- [x] Social learning page: `/social-learning` -> `/online-workshops`
- [x] Code of conduct page: `/social-learning/code-of-conduct` -> `/online-workshops/code-of-conduct`
- [x] Workshop presenter application page: `/workshop-presenter-application` -> `/tutorial-presenter-application`

**Code changes:**

- [x] `wporg_workshop` post type labels and slugs
- [x] Meta data links on single workshop pages
- [x] `/social-learning` button on single workshop posts
- [x] Navigation menu (this is hard-coded in the template)
- [x] `/workshops` links on home page
- [x] `/social-learning` links on home page
- [x] The meetup group slug for the social learning block on the home page: `wordpress-social-learning` -> `learn-wordpress-online-workshops`
- [x] Multiple references on the home page to workshops and social learning spaces

**Coded redirects:**

- [x] Single workshop posts: `/workshop/.+ => /tutorial/$1`
- [x] Workshops page: `/workshops` -> `/tutorials` (including pagination - e.g. `/tutorials/page/2`)
- [x] Workshop presenter application page: `/workshop-presenter-application` -> `/tutorial-presenter-application`
- [x] Social learning page: `/social-learning` -> `/online-workshops`
- [x] Code of conduct page: `/social-learning/code-of-conduct` -> `/online-workshops/code-of-conduct`

**Pages that will need to have their content updated in multiple locations:**

- [x] https://learn.wordpress.org/social-learning/
- [x] https://learn.wordpress.org/contribute/
- [x] https://learn.wordpress.org/workshop-presenter-application/

We'll also need to review [the handbook](https://make.wordpress.org/training/handbook/) for any names and links that need to be changed.

**Comment by hlashbrooke** [comment]
Noting that after these changes have been made we must remember to flush the site's permalinks.

**Comment by hlashbrooke** [comment]
**Order of actions:**
- [x] 1. Prepare a complete PR for all the necessary code changes and redirects
- [x] 2. Update all necessary page titles and slugs
- [x] 3. Update meetup group name and slug
- [x] 4. Merge and deploy PR
- [x] 5. Flush site permalinks
- [x] 6. Update references and links in page content where necessary

**Comment by hlashbrooke** [comment]
The code changes are being done in the `818/content-name-changes` branch.

**Comment by hlashbrooke** [comment]
All code changes, except for redirects, have been included in PR #819

**Comment by dd32** [comment]
Redirects added in https://github.com/WordPress/Learn/commit/ad8f71670fd163590dad04bde43347aa7cd41c41 (in #819) and above checkboxes marked off.

Note that the redirect for `social-learning/code-of-conduct` isn't listed in the code, as the redirect for the parent page `social-learning` handles it for us.

**Comment by hlashbrooke** [comment]
All looks good to me - thanks @dd32!

**Comment by hlashbrooke** [comment]
This has been deployed and all updates in content have been made. Closing this issue now.

We still need to update the handbook and any other locations that are not on Learn WordPress directly.
