### ISSUE TITLE
Learn WordPress Content Error Report - Ticket # 136397

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#826]
# Error Description
- Content URL: https://learn.wordpress.org/learn/quiz/a-hands-on-experiment-with-the-block-editor/

Questions 3 and 4 of the quiz of this lesson require the learner to view an image. However, the image is not shown.

# Error Report Checklist:
- [x] Error Validated
- [ ] Error fix proposed
- [ ] Error fix reviewed
- [ ] Error fix published

**Comment by kaitohm** [comment]
@wparasae I see you are the course creator for this. Do you still have the data for questions 3 and 4?

**Comment by zobinadevain** [comment]
<a href='https://capmistoi-6241.weebly.com'>.</a>
<a href='https://capmistoi-6242.weebly.com'>.</a>
<a href='https://capmistoi-6243.weebly.com'>.</a>
<a href='https://capmistoi-6244.weebly.com'>.</a>
<a href='https://capmistoi-6245.weebly.com'>.</a>
<a href='https://capmistoi-6246.weebly.com'>.</a>
<a href='https://capmistoi-6247.weebly.com'>.</a>
<a href='https://capmistoi-6248.weebly.com'>.</a>
<a href='https://capmistoi-6249.weebly.com'>.</a>
<a href='https://capmistoi-6250.weebly.com'>.</a>

**Comment by devmuhib009** [comment]
Another issue created #2207

**Comment by kaitohm** [comment]
Closing in favor of #2207
