### ISSUE TITLE
Customizing your single posts template - Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#827]
//tutorial

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/180699657-6ebc206e-98ff-470f-8036-6ac43ac589b4.mp4

**Comment by amitpatel0702** [comment]
Thanks @westnz. Both the Scenarios explained Very well.

And yes, the last portion to roll back all customization part was amazing.

It would be great if you would had executed steps at **3:27** ,**3:32** & **3:33** slightly slower.

**Comment by westnz** [comment]
Thanks for the feedback @amitpatel0702 

I will have a look at slowing the clip speed.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/customizing-your-post-content-layout/

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/e6ea7fb4-ee90-41ff-853b-d739a82d1f3c

**Comment by nhrrob** [comment]
This is pretty good. 
Didn't know about this template editing process earlier. 
This tutorial will help a lot of people.

**Comment by eirichmond** [comment]
This instructional guide effectively outlines the initial steps for customising the single template, making it clear and easy to follow.

One additional point I'd like to suggest is regarding the accessibility of templates. While you've illustrated one entry point towards the end of the demonstration, highlighting the second entry point for customisation, I believe it would enhance clarity, especially for new users, to mention that templates can be accessed through two routes:
Design > Templates
&
Design > Templates > Manage All Templates

Is it worth mentioning this from the outset? It's important to note that both routes lead to the same destination, facilitating the editing of the single post template or any other template.

![templates](https://github.com/WordPress/Learn/assets/525490/0e8408bc-4c29-486e-9491-4b89e30bfe50)

Overall, great job on the tutorial.

**Comment by westnz** [comment]
Thank you very much for the feedback @nhrrob and @eirichmond

**Comment by westnz** [comment]
Updated and published as part of the Intermediate user learning pathway in Sensei.
