### ISSUE TITLE
Theme: Form is not made for typos

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/Learn#83]
_Copied from https://meta.trac.wordpress.org/ticket/5372_

If a typo error is found, there is a link to the form https://wordcampcentral.survey.fm/learn-wordpress-workshop-application

That form is not really meant for sharing errors on the site.

![Capture](https://user-images.githubusercontent.com/916023/90079502-f88a5880-dcbc-11ea-8d72-b47318052dcb.PNG)

**Comment by coreymckrill** [comment]
@hlashbrooke any thoughts on this one? Should we have a separate form for reporting content issues? Either that or we could just remove that line.

**Comment by CdrMarks** [comment]
A user submitted this form with the following non-application submission:
> not a workshop; I'm here following your link for presenting suggestions or suggesting improvements to your page https://learn.wordpress.org/lesson-plan/custom-post-types/. What happened is that you mention a plugin that is outdated and removed from plugin repository. Now that I'm filling this, I would also like to suggest you to change the form you are linking because this not a suggestion form and it is annoying filling al this data.

**Comment by hlashbrooke** [comment]
I created a page with a reporting form that sends emails to our temporary Help Scout address (learn-wordpress@mu.helpscoutapp.com) - once learn@wordpress.org is setup I'll change it to that. Here's the page with the form: https://learn.wordpress.org/report-content-errors/

Could you update the link in the sidebar to point to that?
