### ISSUE TITLE
[Related Course: Create a Custom Block Theme #1] What a Theme Designer Needs to Know: Anatomy of a Block Theme - Lesson Plan

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#833]
### **IMPORTANT:** 
** This lesson plan belongs to part of a greater course, [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631) **
**Please reach out to @arasae (Sarah Snow) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
This lesson aims to explore the fundamental components of a basic block theme setup (a high-level overview, we will get into the specifics in later lesson plans), especially in regard to:

style.css - Brings a theme into existence.
functions.php - A safety feature for all themes.
theme.json - The options toggle.
templates & template parts - The building blocks of every theme.
patterns - Optional extras that can enhance a theme.

It's important to cover what each of these things does and how they work together. 

This lesson may also touch on script debug, what it does and how it is used.

## Objectives

After completing this lesson, participants will be able to:

* Define the key elements of a block theme, what each file does, and why it is required when making a new theme
* Analyze how the anatomy of a block theme works together

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Development Checklist:
- [x] Review any related material on Learn
- [x] Description and Objectives finalized
- [ ] Gather links to Support, other learn.wordpress.org existing resources, and Developer Docs
- [x] Create an outline of the example lesson walk-through
- [x] Draft lesson plan
- [ ] Consider quiz questions to add here.
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Announce to the Training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

# Repo Structure and Lesson Plan Template

> <span style="color:red">Please remove all blockquote comments such as this before publishing.</span>

## Description

> A short paragraph explaining what is covered in the lesson plan. This should be text that can be copied and used in a meetup or workshop description.

## Target Audience

Who is this lesson intended for? What interests/skills would they bring? Put an "x" in the brackets for all that apply.

* [x] Users / Content Writers
* [x] Designers
* [x] Beginner-Level Developers
* [ ] Developers
* [ ] Speakers
* [ ] Organizers
* [ ] Kids

## Experience Level

How much experience would a participant need to get the most from this lesson? Put an "x" in the brackets for all that apply.

* [ ] Beginner
* [x] Intermediate
* [ ] Advanced

## Type of Instruction

Which strategies will be used for this lesson plan? Put an "x" in the brackets for all that apply.

* [x] Text-and-Image-Based, Remote-First Course
* [ ] Exercises
* [ ] Slides
* [ ] Video Tutorial

## Time Estimate (Duration)

How long will it take to present this lesson? Put an "x" in the brackets for the one that applies.
* [ ] 1-5 Minutes
* [ ] 5-10 Minutes
* [ ] 15+ Minutes
* [ ] 1 hour or less

## Prerequisite Skills

Participants will get the most from this lesson if they have familiarity with:
_These are important to include in case someone wants to use this lesson plan in-person as a stand-alone lesson._
* Skill 1
* Skill 2

> _For example:_
>
> *   Experience with HTML and CSS
> *   Completed the Basic WordPress Concepts lesson

## Readiness Questions
_These are important to include in case someone wants to use this lesson plan in-person as a stand-alone lesson._
* Question 1
* Question 2

> A list of questions for participants to see if they have the background and skills necessary to learn and understand the lesson.
>
> _For example:_
>
> *   Do you want to makes changes to your theme yourself?
> *   Do you know how to write CSS?

## Slides
_If someone wanted to run this lesson as a stand-alone Online Live Workshop or at an in-person WordCamp, you could create slides for this here; if you run a Live Online Workshop on one of these topics or find someone else has, related slides would be welcome!_

> Change the `/repo-name/` in the link to match the URL name of this repo.

*   [Slides](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/) (files included in this repo)

## Materials Needed

* Item 1
* Item 2

> A list of files, resources, equipment, or other materials the presenter will need for the lesson.
>
> _For example:_
>
> *   A local install of WordPress
> *   The files for the TwentySixteen theme

## Notes for the Presenter
_/Include any tips needed to present this topic for a Live Online Workshop or in an in-person classroom setting._

* Note 1
* Note 2

> A list of any handy tips or other information for the presenter.
>
> _For example:_
>
> *  Participants may need to download the TwentySixteen theme before beginning
> *  What to do if there’s no projector or internet available
> *  What to do if a participant doesn’t have the necessary set up
> *  How to handle different opinions about the topic

## Lesson Outline

* First do this
* Then move on to this
* Finish with this

> The plan for the lesson. Outline form works well.
>
> _For example:_
>
> * Talk about what a theme is
> * Demonstrate how to install and activate a theme
> * Practice exercises to have participants find and install a theme on their own site

## Exercises
_What someone will DO with what they learn in each lesson; most lessons have at least one related exercise._

**Exercise name**

Short description of what the exercise does and what skills or knowledge it reinforces.

*   Short point or step of the exercise
*   And another one

> These are short or specific activities that help participants practice certain components of the lesson. They should not be fully scripted exercises, but rather something that participants could do on their own. For example, you can create an exercise based on one step of the Example Lesson.

## Assessment
_These assessments will be autograded on Learn.WordPress.org._
There should be one assessment item (or more) for each objective listed above. Each assessment item should support an objective; there should be none that don't.

**Write out the question.**

1.  Option
2.  Option
3.  Option
4.  Option

**Answer:** 3\. Correct answer

> A few questions to ask participants to evaluate their retention of the material presented. They should be a measure of whether the objectives were reached. Consider having a question for each objective.

## Additional Resources

* Resource 1
* Resource 2

> An optional section which can contain a list of resources that the presenter can use to get more information on the topic.
>
> _For example:_
>
> * Link to information on the Codex
> * Theme Review Team's Handbook

## Example Lesson [Written for a text-and-image based, multimedia course rather than for a live classroom setting]

> An example of how the lesson plan can be implemented. Written in script form as one possible way an presenter might use this lesson plan at an event, with screenshots and instructions if necessary.

### Section Heading for Example Lesson

> You will likely need to break the Example Lesson down into multiple sections.

### Lesson Wrap Up

![](https://raw.githubusercontent.com/wptrainingteam/contributor-resources/master/images/lightbulb.png) Follow with the [Exercises](#Exercises) and [Assessment](#Assessment) outlined above.

**Comment by wparasae** [comment]
The content for this overview is basically covered in the existing tutorial; I am going to include it and potentially write a quiz.

**Comment by wparasae** [comment]
This is ready for review: https://learn.wordpress.org/learn/lesson/what-a-new-theme-developer-needs-to-know-anatomy-of-a-block-theme/

**Comment by kaitohm** [comment]
This is now live!

**Comment by kaitohm** [comment]
This content has been published as part of a [Course](https://make.wordpress.org/training/handbook/courses/). Anyone is now free to pick this up and create a [Lesson Plan](https://make.wordpress.org/training/handbook/lesson-plans/) that covers the same content.

Published as Course content here: https://learn.wordpress.org/learn/lesson/what-a-new-theme-developer-needs-to-know-anatomy-of-a-block-theme/

**Comment by Piyopiyo-Kitsune** [comment]
Can remove the Course content type label for this issue since a lesson plan needs to be created now?

**Comment by courtneyr-dev** [comment]
WP 6.4 https://make.wordpress.org/core/2023/10/15/introducing-block-hooks-for-dynamic-blocks/

**Comment by kaitohm** [comment]
Closing in favor of prioritizing Learning Pathways content.
