### ISSUE TITLE
Your First Template: Create A Style Guide Using the Site Editor

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#839]
### **IMPORTANT:** 
** This lesson plan belongs to part of a greater course, [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631) **
**Please reach out to @arasae (Sarah Snow) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
This lesson aims to teach people how to create a style guide in the site editor; you can't revise a blank piece of paper, but you can copy and paste some minimal code and manipulate it so that your overall site has a strong look and feel that can be changed in one centralized location.

`Removed in favor of Style Guide: Users at this level should already have a good grasp of template parts. This should be a [brief] review of template parts. Plan to link out to more advanced resources that dig deeply into what template parts are and how they work together with the rest of themes; the goal of this is focus more on design best practices and look at where template parts live within a theme's code. It should invite them to design a header and footer template part of their own, but we may want to create copyable patterns of a theme or two (specifically its template parts) similar to what exists in the pattern directory that someone could copy and paste so that they don't have to spend a lot of time designing something brand new unless they want to. I'm not sure how hard this would be to do, but it's a consideration we should keep in mind when we have design elements like this.`

## Objectives

After completing this lesson, participants will be able to:

* Design a style guide of their own using only the site editor

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Development Checklist:
- [ ] Review any related material on Learn
- [x] Description and Objectives finalized
- [ ] Gather links to Support, other learn.wordpress.org existing resources, and Developer Docs
- [ ] Create an outline of the example lesson walk-through
- [ ] Draft lesson plan
- [ ] Copy edit
- [ ] Style guide review
- [ ] Instructional Review
- [ ] Final review
- [ ] Publish
- [ ] Announce to the Training team
- [ ] Announce to lesson plan creator
- [ ] Announce to marketing
- [ ] Gather feedback from lesson plan users about the quality

# Repo Structure and Lesson Plan Template

> <span style="color:red">Please remove all blockquote comments such as this before publishing.</span>

## Description

> A short paragraph explaining what is covered in the lesson plan. This should be text that can be copied and used in a meetup or workshop description.

## Target Audience

Who is this lesson intended for? What interests/skills would they bring? Put an "x" in the brackets for all that apply.

* [x] Users / Content Writers
* [x] Designers
* [x] Beginner-Level Developers
* [ ] Developers
* [ ] Speakers
* [ ] Organizers
* [ ] Kids

## Experience Level

How much experience would a participant need to get the most from this lesson? Put an "x" in the brackets for all that apply.

* [ ] Beginner
* [x] Intermediate
* [ ] Advanced

## Type of Instruction

Which strategies will be used for this lesson plan? Put an "x" in the brackets for all that apply.

* [x] Text-and-Image-Based, Remote-First Course
* [ ] Exercises
* [ ] Slides
* [ ] Video Tutorial

## Time Estimate (Duration)

How long will it take to present this lesson? Put an "x" in the brackets for the one that applies.
* [ ] 1-5 Minutes
* [ ] 5-10 Minutes
* [ ] 15+ Minutes
* [ ] 1 hour or less

## Prerequisite Skills

Participants will get the most from this lesson if they have familiarity with:
_These are important to include in case someone wants to use this lesson plan in-person as a stand-alone lesson._
* Skill 1
* Skill 2

> _For example:_
>
> *   Experience with HTML and CSS
> *   Completed the Basic WordPress Concepts lesson

## Readiness Questions
_These are important to include in case someone wants to use this lesson plan in-person as a stand-alone lesson._
* Question 1
* Question 2

> A list of questions for participants to see if they have the background and skills necessary to learn and understand the lesson.
>
> _For example:_
>
> *   Do you want to makes changes to your theme yourself?
> *   Do you know how to write CSS?

## Slides
_If someone wanted to run this lesson as a stand-alone Online Live Workshop or at an in-person WordCamp, you could create slides for this here; if you run a Live Online Workshop on one of these topics or find someone else has, related slides would be welcome!_

> Change the `/repo-name/` in the link to match the URL name of this repo.

*   [Slides](https://wptrainingteam.github.io/lesson-plans/repo-name/slides/) (files included in this repo)

## Materials Needed

* Item 1
* Item 2

> A list of files, resources, equipment, or other materials the presenter will need for the lesson.
>
> _For example:_
>
> *   A local install of WordPress
> *   The files for the TwentySixteen theme

## Notes for the Presenter
_/Include any tips needed to present this topic for a Live Online Workshop or in an in-person classroom setting._

* Note 1
* Note 2

> A list of any handy tips or other information for the presenter.
>
> _For example:_
>
> *  Participants may need to download the TwentySixteen theme before beginning
> *  What to do if there’s no projector or internet available
> *  What to do if a participant doesn’t have the necessary set up
> *  How to handle different opinions about the topic

## Lesson Outline

* First do this
* Then move on to this
* Finish with this

> The plan for the lesson. Outline form works well.
>
> _For example:_
>
> * Talk about what a theme is
> * Demonstrate how to install and activate a theme
> * Practice exercises to have participants find and install a theme on their own site

## Exercises
_What someone will DO with what they learn in each lesson; most lessons have at least one related exercise._

**Exercise name**

Short description of what the exercise does and what skills or knowledge it reinforces.

*   Short point or step of the exercise
*   And another one

> These are short or specific activities that help participants practice certain components of the lesson. They should not be fully scripted exercises, but rather something that participants could do on their own. For example, you can create an exercise based on one step of the Example Lesson.

## Assessment
_These assessments will be autograded on Learn.WordPress.org._
There should be one assessment item (or more) for each objective listed above. Each assessment item should support an objective; there should be none that don't.

**Write out the question.**

1.  Option
2.  Option
3.  Option
4.  Option

**Answer:** 3\. Correct answer

> A few questions to ask participants to evaluate their retention of the material presented. They should be a measure of whether the objectives were reached. Consider having a question for each objective.

## Additional Resources

* Resource 1
* Resource 2

> An optional section which can contain a list of resources that the presenter can use to get more information on the topic.
>
> _For example:_
>
> * Link to information on the Codex
> * Theme Review Team's Handbook

## Example Lesson [Written for a text-and-image based, multimedia course rather than for a live classroom setting]

> An example of how the lesson plan can be implemented. Written in script form as one possible way an presenter might use this lesson plan at an event, with screenshots and instructions if necessary.

### Section Heading for Example Lesson

> You will likely need to break the Example Lesson down into multiple sections.

### Lesson Wrap Up

![](https://raw.githubusercontent.com/wptrainingteam/contributor-resources/master/images/lightbulb.png) Follow with the [Exercises](#Exercises) and [Assessment](#Assessment) outlined above.

**Comment by wparasae** [comment]
The following lesson is ready for review:

Your First Template: Create A Style Guide Using the Site Editor: [Review Module 3, Lesson 4 Here](https://learn.wordpress.org/wp-admin/post.php?post=20150&action=edit) / [Leave Feedback for Module 3, Lesson 4 Here](https://github.com/WordPress/Learn/issues/839)

Specific Questions For Feedback (Leave all feedback for this lesson in a comment on this issue)
a. Is the content correct? Are there any errors?
b. Is the content too long / too short / just right? Why or why not?
c. What revisions might you suggest for added clarity?

Please leave any feedback for this module in a comment on this post.

**Comment by westnz** [comment]
Review:

- Check grammar / typo
<img width="776" alt="image" src="https://user-images.githubusercontent.com/89751452/203900064-d84a2cb3-280d-4ea3-99f6-026060c3bc07.png">

- The building material example is fantastic.  It will help the learner's creative juices to start flowing.

- I got a bit lost here. Maybe I can't see the quiz in the backend.  Is the image interactive? 
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/89751452/203902149-77f666a9-5050-49b5-ab18-51178aa0998a.png">

**Comment by wparasae** [comment]
Changes made.

Yes, the image is interactive; I need to publish it to make sure it works!

**Comment by Piyopiyo-Kitsune** [comment]
Can we remove the Course content type label for this issue since a lesson plan needs to be created now?

**Comment by wparasae** [comment]
Closing this issue; this was a need prior to WordPress 6.2, but with the new Stylebook, this can be removed.
