### ISSUE TITLE
Theme: Breadcrumbs not always shown

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/Learn#84]
_Copied from https://meta.trac.wordpress.org/ticket/5373_

https://learn.wordpress.org/lesson-plan/high-level-overview/ is showing breadcrumbs correctly, but clicking on 'Lessons Plans', the breadcrumbs disappear.

![Capture](https://user-images.githubusercontent.com/916023/90079615-42733e80-dcbd-11ea-8d55-9faf89e16bdd.PNG)

**Comment by bestony** [comment]
I think it not just a Code Question, also need help from designer.

for example,should i put breadcrumbs on page top ?  or just below the Big Title?

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/13283837/153982572-1fbd031b-6347-43a3-92cd-4e1ff1053962.png">

i can give some help if someone can clearify this.
