### ISSUE TITLE
Using Block Attributes - Tutorial

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#860]
# Topic Description
Implement block attributes in your custom block, to enable user's to edit block data

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [Block attributes](https://developer.wordpress.org/block-editor/getting-started/create-block/attributes/)

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [x] Tutorial submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [x] Tutorial submitted to WPTV https://wordpress.tv/submit-video/
- [x] Tutorial published on WPTV
- [x] Tutorial is captioned https://make.wordpress.org/training/handbook/workshops/workshop-subtitles-and-transcripts/
- [x] Tutorial created on Learn.WordPress.org
- [x] Tutorial post is reviewed for grammar, spelling, etc.
- [x] Tutorial published on Learn.WordPress.org
- [x] Tutorial announced to training team
- [x] Tutorial announced to creator
- [x] Tutorial announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by jonathanbossenger** [comment]
https://user-images.githubusercontent.com/180629/188438258-451a11de-c825-40a0-b765-ab7dada02057.mp4

**Comment by webtechpooja** [comment]
@askaryabbas has volunteered to review this. and @bsanevans will give a non-dev review on it.

**Comment by kaitohm** [comment]
I gave this a review, Jonathan! I have just enough coding experience to understand what you're doing there :)

## Comments
I love how your code is crisp and easy to see! Also, I liked how you demonstrated searching for stuff in the handbook at the very end of the video. Having visuals for even "simple" tasks like that is very helpful!

At 6:00, you copy-paste code from somewhere. Was that brought in from a codex somewhere? Or is it code you wrote prior to the recording so you could drop it in? Adding some narration along these lines would help clarify that: "Let me copy-paste some code I wrote for this, then explain what each line of the code means."

This is nitpicking, but at 10:55, does line 16 of your code need a semicolon at the end? 😅

**Comment by askaryabbas** [comment]
Hi @jonathanbossenger, I checked and reviewed the video, great work and that's a great way to describe the codes, and easy to understand.

I did not find any code issue, it's perfect, however, to avoid confusion and make everything clear, it's good to follow what @bsanevans suggested, it will help beginners too.

Here are a few suggestions from my side too.
- Can show the source page from where InspectorControls and TextControl copied before or after pasting the code.
- Can show @wordpress/components page in which TextControl is present.
- Can show @wordpress/block-editor page in which InspectorControls are present.
- The import statement on line number 16 at 10:55 needs a semicolon ( ; )
- Can use @wordpress/i18n component and __( ) localization function for static text in Edit and Save functions, it will help beginners to follow the WordPress Standard each time they code. 
- Can show the output page at the front-end with dynamic data so beginners also will have a full idea of how dynamic data rendering, it will also avoid confusion if they break anything in the code by following this video and data is not rendering at the front-end.

Thank you @jonathanbossenger for your hard work and excellent video and @bsanevans for the meaningful suggestions 🙂

**Comment by jonathanbossenger** [comment]
@bsanevans thanks for the review

> At 6:00, you copy-paste code from somewhere. Was that brought in from a codex somewhere?

No, and part of the reason is that it's different for each block. I was trying to show how to use it, without going into too much detail, to keep the video short. But I like your idea of explaining what I'm doing there. 

>at 10:55, does line 16 of your code need a semicolon at the end

Good catch, yes it should have a semi-colon. However, this is probably a case of [Automatic semicolon insertion](https://en.wikibooks.org/wiki/JavaScript/Automatic_semicolon_insertion) doing its job, so I think it's ok to leave that as is for this round.

**Comment by jonathanbossenger** [comment]
@askaryabbas thank you for your review.

> Can show the source page from where InspectorControls and TextControl copied before or after pasting the code.
> Can show @wordpress/components page in which TextControl is present.
> Can show @wordpress/block-editor page in which InspectorControls are present.

As I mentioned to @bsanevans it's not coming from anywhere, and I didn't want to spend too much extra time in diving into the Settings Sidebar, InspectorControl, TextControl, etc, as it would make the video very long. What I plan to do is record a small voice-over update for this video to cover this.

> The import statement on line number 16 at 10:55 needs a semicolon ( ; ) 

See my earlier comment to @bsanevans about [Automatic semicolon insertion](https://en.wikibooks.org/wiki/JavaScript/Automatic_semicolon_insertion) doing its job

> Can use @wordpress/i18n component and __( ) localization function for static text in Edit and Save functions, it will help beginners to follow the WordPress Standard each time they code.

I'm actually planning a separate tutorial on localization, in which I plan to cover that topic separately

> Can show the output page at the front-end with dynamic data so beginners also will have a full idea of how dynamic data rendering, it will also avoid confusion if they break anything in the code by following this video and data is not rendering at the front-end.

I'm not sure what you're meaning here, could please you elaborate?

**Comment by jonathanbossenger** [comment]
I have added an update at 5:48 with a view of the Toolbar and Sidebar handbook doc, and an explanation.

https://user-images.githubusercontent.com/180629/190391784-f9e05958-282d-4ce5-a29e-36eb785d1293.mp4

I also intend to add the code to the written transcript for this tutorial, when it is added to Learn WordPress. (See how I've [done that previously](https://learn.wordpress.org/tutorial/converting-a-shortcode-into-a-block/), in this case with Terminal commands) That way the learner can copy/paste the code from the transcript.

**Comment by askaryabbas** [comment]
Excellent work @jonathanbossenger,

I love the way you demonstrate everything in the video tutorials 🙂 
My previous comment was only suggestions, but I see it's not necessary as those will be described in the different tutorials, and here we try to make the video as short as possible.

I see you have updated the video and added an update at 5:48 with a view of the Toolbar and Sidebar handbook document.
That's perfect, everything is clear in the video and well described.

I believe it is ready to be published. Well done 🙂

**Comment by jonathanbossenger** [comment]
> My previous comment was only suggestions, but I see it's not necessary as those will be described in the different tutorials, and here we try to make the video as short as possible.

Not a problem @askaryabbas I'm always open to suggestions. The problem I always struggle with is balancing the length of the video with how much content to include, so I tend to try and focus on one core concept, with a plan to cover other concepts in future tutorials.

I really do appreciate your feedback and suggestions, because it confirms that I'm on the right track, and helps me define future videos 😊

**Comment by mburridge** [comment]
Great tutorial @jonathanbossenger! You explain everything very clearly. 👌

**Comment by jonathanbossenger** [comment]
https://wordpress.tv/2022/09/23/using-block-attributes-to-enable-user-editing/
