### ISSUE TITLE
Greek translation for "Introduction To Common Plugins" lesson plan

### ISSUE THREAD

**Issue by vagelisp** [WordPress/Learn#866]
# Topic Description
The Greek translation for [Introduction To Common Plugins](https://learn.wordpress.org/lesson-plan/introduction-to-common-plugins/) lesson plan

# Related Resources
The original Lesson Plan
[Introduction To Common Plugins](https://learn.wordpress.org/lesson-plan/introduction-to-common-plugins/)

The translated version of the Lesson Plan in google docs
https://docs.google.com/document/d/1qOZGzfowR9d7MRh_sf96D01MevW0Mi4A4H13FQrfKaU/

I requested a review from @lenasterg and the rest of the Greek polyglots team.

**Comment by lenasterg** [comment]
Hi. 
I reviewed the translation @vagelisp made. 
It's OK to publish. 

Bests, 
Lena

**Comment by azhiya** [comment]
Thanks @lenasterg @vagelisp am I right in that you created the lesson plan? I just want to make sure the right person is assigned to the card.

**Comment by vagelisp** [comment]
Hello @azhiya, yes, that is correct. 
I can add the content if someone duplicates the original lesson ( I have editor access on the website ).
Thanks.

**Comment by azhiya** [comment]
@vagelisp Do you mean all the text or just the [lesson plan outline](https://learn.wordpress.org/?p=20095&post_type=lesson-plan&preview=1&_ppp=97f1e4cc40)

**Comment by vagelisp** [comment]
I don't mind @azhiya, whatever works for you best. 
I could even create a draft of the lesson plan from scratch. Whatever you think it's the best.
Last time @bsanevans duplicated the original lesson plan, and I replaced the content.

**Comment by azhiya** [comment]
@vagelisp What I created is the general outline. I can copy the text across if you'd like but I won't be able to do that until much later on today.

**Comment by vagelisp** [comment]
@azhiya ah sorry I didn't realise that you already did that. 
I thought the link was for the original lesson plan.
Thanks so much for creating this, I'll let you know once the content is ready.

**Comment by vagelisp** [comment]
Hello again @azhiya; I added the content.
Thanks.

**Comment by kaitohm** [comment]
This looks good! I added `Categories`, `Instruction Type`, `Included Content`, and `Meta Data` in the right sidebar to match the original lesson plan. The lesson is now published! https://learn.wordpress.org/lesson-plan/%ce%b5%ce%b9%cf%83%ce%b1%ce%b3%cf%89%ce%b3%ce%ae-%cf%83%cf%84o%cf%85%cf%82-%cf%80%ce%b9%ce%bf-%ce%ba%ce%bf%ce%b9%ce%bd%ce%bf%cf%8d%cf%82-%cf%84%cf%8d%cf%80%ce%bf%cf%85%cf%82-%cf%80%cf%81%ce%bf%cf%83/
