### ISSUE TITLE
Review templates - Lesson

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#869]
# IMPORTANT
**This lesson plan belongs to part of a greater course, [Extend a Low Code Block Theme](https://github.com/WordPress/Learn/issues/821) which depends on the completion of  [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631)**

**Please reach out to @jonathanbossenger (Jonathan Bossenger) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
The goal of this lesson is to review how creating templates work in a block theme, reviewing this lessons from the first course

- [Your First Template: Create A Landing Page](https://github.com/WordPress/Learn/issues/838)

This lesson will also cover some of the additional templates that can be created from the Site Editor, for example:

- Creating a default page template
- Creating a blog archive template for blog posts

# Objectives
After completing this lesson, participants will be able to:

- Review the landing page template created in the first course
- Create additional templates, based on the available options in the Site Editor

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Lesson for review: 

[Block Theme Templates](https://learn.wordpress.org/lesson/templates-2/)

## Review checklist

Reviewers: this is not an extensive list, but it would be helpful if you can keep the following questions in mind while reviewing.

1. Are there any spelling/grammar issues or anything that doesn't make sense?
2. Is the content technically correct?
3. Does the layering of information successfully build from lesson to lesson
4. Can you follow the steps outlined in the course
5. Does the lesson contain enough relevant links to documentation (WordPress documentation, or any other relevant documentation)

**Comment by jonathanbossenger** [comment]
Draft Lesson: https://github.com/jonathanbossenger/block-theme-course/blob/main/module-01/02-Review-Templates.md

I have not taken screenshots at this time, as I want to make sure to take screenshots following the contents of the Create a Block Theme (Low Code) course, which I will do once the first few modules of that course are ready to be reviewed.

**Comment by westnz** [comment]
### Feedback - Block Theme Templates

- You explain what block theme templates are very well and highlight the advantage of using a block theme.

- This was a bit confusing to me:

Did you want to say, 'In the last lesson, you **will** create an empty index.html template file.'? Why then jump into 'Let's add some content to this template.' I would suggest providing more clarity here. 
<img width="826" alt="image" src="https://user-images.githubusercontent.com/89751452/192647826-0cf3b14f-365a-496f-95e5-203fef046870.png">

- I was wondering if there is a way to add a border around screenshots in Sensei to show a clear break from the content.  This is something I had in mind when I created the FSE course as well. Something to look into when the content is transferred.

- I mentioned using colours to make the 'Do' and 'Note' sections stand out in the previous lesson, but then I realised these action steps are not in Sensei yet. Are you planning on using Call Out blocks for these?   

- Are the examples from the screenshot below supposed to have **'Do:'** in front of them like the others? There are some other action steps without 'Do:' in front of them as well.  This is important for uniformity/cohesion. 

<img width="931" alt="image" src="https://user-images.githubusercontent.com/89751452/192649680-71ce832b-1d2a-468a-9c3a-211f795550f6.png">

- Should this have **'Note:'** in front of it? There are some others like this as well. This is important for uniformity/cohesion. 

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/89751452/192650782-2f7d6935-0140-417d-9a55-a6b0764ce74a.png">

- Is the text always so close to the Template List View when you do this? Just something that caught my eye. 

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/89751452/192651105-9266c80e-1059-4e00-8806-d368fc35aef8.png">

**Spelling/Punctuation** 

- Ensure 'Site Editor' is in capital letters throughout the course.

- Change query loop block to Query Loop block.  

- Add a full stop after 'template'.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/89751452/192651445-995ebfee-f87c-489c-b935-a54f3371d831.png">

**Comment by jonathanbossenger** [comment]
Thanks for the review feedback @westnz 

> Did you want to say, 'In the last lesson, you will create an empty index.html template file.'?

It was supposed to be 'In the last lesson, you created an empty index.html template file.' Fixed

> I was wondering if there is a way to add a border around screenshots in Sensei to show a clear break from the content.

Yes, I noticed this as well, and I plan to add a 1px border around the images. I actually had this exact same issue when I was creating content at my previous position, we had an inline CSS snippet we had to add to each and every image. 🙈

> Are you planning on using Call Out blocks for these?

As discussed in the previous review comments, yes. Unfortunately, they just don't exist on GitHub.

> Are the examples from the screenshot below supposed to have 'Do:' in front of them like the others?
> Should this have 'Note:' in front of it?

Thanks for picking this up, I started adding the Do or Note or Tip heading to the quote blocks in markdown about halfway through this module when the idea came to me, and probably forgot to go back and ensure they were all there. Fixed

> Is the text always so close to the Template List View when you do this? Just something that caught my eye.

This is probably only because I've not applied any styles via theme.json to the theme yet, so there's no layout or spacing implemented on the theme itself.

> Ensure 'Site Editor' is in capital letters throughout the course.

I was confused by this one, as the [developer handbook](https://developer.wordpress.org/themes/block-themes/creating-new-themes-using-the-site-editor/) has it as Site Editor, but the [support handbook](https://wordpress.org/support/article/site-editor/) does not. However, I'll make sure to stick to Site Editor going forward. Fixed (as well as the rest of the spelling/punctuation errors.

**Comment by westnz** [comment]
Great stuff!

`It was supposed to be 'In the last lesson, you created an empty index.html template file.' Fixed`
Maybe you should rather say 'previous' instead of 'last'.

**Comment by annezazu** [comment]
>One of the main advantages of block themes over classic themes, is that you can edit existing templates or create new theme templates from the Site Editor.

When would you do each? I'd touch on that a bit to share some best practices. 

Otherwise, this looks solid to me!

**Comment by jonathanbossenger** [comment]
Thanks for the feedback @annezazu 

> When would you do each? I'd touch on that a bit to share some best practices.

That's a solid point, I'll add some content around when you might do each.

**Comment by wparasae** [comment]
1. **Quick typo!**

> One of the main advantages of block themes over classic themes, is that you can edit existing templates or create new theme templates from the Site Editor.

Remove comma between themes and is :) 

/EDIT/ - I didn't see there was more information below a screenshot! Facepalm... reviewing properly now..

2. **Quick Revision** - Consider adding [this tutorial about taking advantage of query loops](https://learn.wordpress.org/tutorial/taking-advantage-of-query-loops/) for user idea-generation to this sentence: 

"Go ahead and add a query loop to the template, the pagination block, and a spacer to allow a bit of space between the query loop and the pagination."

**Random Thoughts** - I wonder if a tutorial on theme blocks might be useful to refer to as a form of remediation. I'm not sure your audience will necessary need that, but it's something to consider. :) Otherwise, this looks good so far!

**Comment by jonathanbossenger** [comment]
Thanks for the feedback @wparasae I've made the updates and suggestions.

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/templates-2/
