### ISSUE TITLE
Review template parts - Lesson

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#870]
# IMPORTANT
**This lesson plan belongs to part of a greater course, [Extend a Low Code Block Theme](https://github.com/WordPress/Learn/issues/821) which depends on the completion of  [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631)**

**Please reach out to @jonathanbossenger (Jonathan Bossenger) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
The goal of this lesson is to review how creating templates parts work in a block theme, reviewing this lesson from the first course

- [Block Theme Building Blocks: Create a Header and Footer Template Parts](https://github.com/WordPress/Learn/issues/839)

This lesson will also cover how to add a general template part from the Site Editor

# Objectives
After completing this lesson, participants will be able to:

- Review the header and footer templates created in the first course
- Create an additional general template part, and add it to an existing template.

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Lesson for Review

[Block Theme Template Parts](https://learn.wordpress.org/lesson/template-parts-3/)

## Review checklist

Reviewers: this is not an extensive list, but it would be helpful if you can keep the following questions in mind while reviewing.

1. Are there any spelling/grammar issues or anything that doesn't make sense?
2. Is the content technically correct?
3. Does the layering of information successfully build from lesson to lesson
4. Can you follow the steps outlined in the course
5. Does the lesson contain enough relevant links to documentation (WordPress documentation, or any other relevant documentation)

**Comment by jonathanbossenger** [comment]
Draft Lesson: https://github.com/jonathanbossenger/block-theme-course/blob/main/module-01/03-Review-Template-Parts.md

I have not taken screenshots at this time, as I want to make sure to take screenshots following the contents of the Create a Block Theme (Low Code) course, which I will do once the first few modules of that course are ready to be reviewed.

**Comment by westnz** [comment]
### Feedback: Block Theme Template Parts

- Is this not the link to the correct [Supplemental Video](https://learn.wordpress.org/tutorial/template-parts/)?

- You have clearly explained everything step-by-step. Nice work! One suggestion is to add Step 1, Step 2, Step 3 etc. to make the process even more clear. 

- Please note my comments about 'Note:' and 'Do:' in the previous lesson.  Should these steps like these have 'Do:' in front of it?

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/89751452/192657725-84e4e8d8-d0d8-484e-b8a2-8f9b8b0fcede.png">

**Spelling/Grammar**

- Replace 'of' with 'are' = 'Template parts are very similar to blocks'

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/89751452/192657086-a1695832-babb-4eb7-8b33-c46bc2361848.png">

- 'Editor' + 'Site Editor' should always be in capital letters.

- Replace 'idea' with 'ideal' + add a comma after 'At this point' and change 'was' to 'were' (subjunctive mood) = 'At this point, you probably agree that it would be ideal if the navigation were aligned to the right.' 

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/89751452/192657386-472dd74e-629e-493f-9196-1961cc6c5c16.png">

- Make sure 'Template Part block' is written the same everywhere. Some are all in lower case:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/89751452/192657978-fac3b684-e747-4679-a96f-a11f9297ab86.png">

**Comment by jonathanbossenger** [comment]
Thanks for the review feedback @westnz 

Noted and fixed the same changes for the action headings, and Site Editor.

Fixed all the spelling/grammar errors. It really is great having you review and catch these things! I tend to sometimes be so deep into the code I forget how to English! 😁

**Comment by annezazu** [comment]
>Template parts are very similar to blocks, in that they are reusable pieces of content that can be inserted into multiple places.

Template parts are blocks (from what I understand). They are blocks that carry specific semantic meaning so I might present them that way, similar to how reusable blocks are still blocks with unique functionality. 

>The Editor will ask you to give the template part a name, and select to either create a general template part, a header template part or a footer template part.

I might clarify when to use each but perhaps that's a bit overkill. Maybe it makes more sense to clarify when you might create a General template part. 

> You can use Group blocks and Row blocks to group and align elements in the template part.

I'd also talk about patterns here, unless it's intentional that you want folks to solely create from scratch. This is especially true with header and footer patterns being integrated into 6.1 for all to use (could use those as a base to build from).

**Comment by jonathanbossenger** [comment]
@annezazu thanks for the review

> Template parts are blocks (from what I understand).

I think I made a mistake here, that should be `Template parts are very similar to reusable blocks`. Would that fix make it clearer that I'm going for this direct comparision between template parts and reusable blocks, the latter being a known thing by now?

> I might clarify when to use each but perhaps that's a bit overkill. Maybe it makes more sense to clarify when you might create a General template part.

There is a later module - Module 4: Creating Custom Templates and Template Parts - where I plan to discuss this.

> I'd also talk about patterns here, unless it's intentional that you want folks to solely create from scratch.

There is a later module - Module 6: Theme Patterns - where I plan to discuss patterns.

**Comment by annezazu** [comment]
Yes! That would definitely clear things up. Sounds great re: everything else.

**Comment by wparasae** [comment]
Read through this! This is strong review, Jonathan - people familiar with this will be able to breeze through this, while also introducing beginners to new terminology.

**Comment by jonathanbossenger** [comment]
Thanks @annezazu and @wparasae for your feedback.

**Comment by jonathanbossenger** [comment]
https://learn.wordpress.org/lesson/template-parts-3/
