### ISSUE TITLE
Customizing a header with patterns

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#872]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/185012892-08e60c2f-8708-47fb-bf4d-35288290939e.mp4

**Comment by westnz** [comment]
Channing Ritter Feedback: "This looks great, Wes — great job explaining this and I love how you highlight different parts of the UI as you’re doing the walkthrough.

One note around 4:04 when discussing changing the color of the Site Title — you can either toggle “make title link to home” to remove the link color from the title OR you can change the link color at the Site Title level (which will override the color applied at the Group level). It might be nice to mention that in the VO as well if it’s not too much trouble to edit but not a big deal either way, just another option."

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/customizing-a-header-with-patterns/

**Comment by azhiya** [comment]
I've closed this since it's now published.
