### ISSUE TITLE
Add language filtering option for lesson plans

### ISSUE THREAD

**Issue by lenasterg** [WordPress/Learn#874]
URL: https://learn.wordpress.org/lesson-plans/
It would be very helpful if we had a language filtering options (language category or tag). 
So the locales team could better promote the lesson-plans written in their own language, ex. Greek 

Bests, 
Lena

**Comment by vagelisp** [comment]
Hi Lena, 
I believe that's related to #811

**Comment by piermario** [comment]
Hello @lenasterg and @vagelisp! 

I was just browsing lesson plans to find something I could start localizing in Italian. I noticed there's English and Greek (good job!) content so far. I had seen Spanish and Japanese content as well, but I have no way to look for these languages as far as I know. 

As Lena suggested, contents would be much easier to browse and narrow down with a language filtering option. My first choice would be a having language filter in the sidebar, along with the existing filters. Perhaps another multiple choice checkbox or rather a dropdown for future scalability?

I checked [#811](https://github.com/WordPress/Learn/issues/811), yet I'm afraid that @hlashbrooke's idea of just using the existing locale switcher might be harder to discover and not too intuitive. I, for one, didn't even consider switching locale to see content in another language, as I mostly use wp.org in English. 

While we have little or no content in our language, I think it would be much easier to choose the lesson plans language using a filter in the sidebar, which I find more intuitive.

Thanks in advance for your consideration! :) 

Best, 

Piermario

**Comment by vagelisp** [comment]
Hello @piermario 
The sidebar filter is better for checking content in other languages; however, for people that use their native languages, that would be a great feature. ( I don’t use Greek as my primary language in WP either, so I get what you mean )

**Comment by piermario** [comment]
Hello Vagelis, thanks for your feedback!

Sure, I agree that a language priority linked to the existing locale switcher will make things easier for speakers of the selected locale. However I still root for a sidebar language filter, which might be very useful while contents in some languages are few or none. For example, Italian currently has only 1 localized workshop and no lesson plans. A filter would help users narrow down content in a language they speak that has more content at the moment.

**Comment by lenasterg** [comment]
Hi. Do we have any updates on that? 
Currently, the https://learn.wordpress.org/lesson-plans/ is in practice UNUSABLE, due to lack of language filtering, and it's going to be worse, as more lessons in more languages are imported.

**Comment by piermario** [comment]
I'm still with @lenasterg on this one. Leaving language selection to the Locale Switcher only might not be as obvious as one might think, and I see way more use cases for a simple language filtering option in the sidebar, as folks who speak more than one language might want to search content in the languages they speak, even for lack of content quantity in their native language.

**Comment by piermario** [comment]
Hello, friends. 
Just checking on the status of this Issue. I still believe it's an important one and would make a ton of difference in improving the usability of a locale results page. 

We're finally getting up to speed with the translation of Italian content. When I try to check for Italian Lesson Plans, even with the Locale set to Italian in the upper right menu, I get a recently published lesson plan, then all sorts of other languages. The next Italian lesson plan is somewhere in the third page. Users might not bother browsing for content, and probably assume that there's just one lesson plan in Italian.

Screenshot: https://drive.google.com/open?id=1gniPHHzGiaz-68ZBwRAtV8D_ldaClaUf

(also, thanks to @courtneyr-dev for moving this Issue to [Learn WP Website Development](https://github.com/orgs/WordPress/projects/71)) 🌟

**Comment by lidialab** [comment]
Hi Learn team!

I agree about the need for language-based filtering that does not depend on one's browser settings, as I use English as my main UI language for browsers too.

And I would also like to be able to select content that other locales will create in their native languages (for example, French and Spanish: I don't speak them, but I can more or less understand them).

+1 to this issue!

**Comment by piermario** [comment]
Hello @bsanevans @adamwoodnz! 

Any update about this request? During today's Contributor Day at WordCamp Torino we ran a Learn table and worked to onboard and introduce new possible contributors to the team. Without a language filter in the sidebar (or at the top of the page, like on the Tutorials page) content in specific languages is quite frustrating to navigate.

Selecting a locale doesn't prioritize Italian (in our case) content, and is quite puzzling. 

Being able to filter content in one or more languages, would be great for people who speak more than one language and narrow down the available resources.

Sorry to keep pushing for this, but it's really crucial to help us show the project's potential to both possible users and contributors.

Thanks in advance! 

cc: @margheweb @lidialab

**Comment by kaitohm** [comment]
Thanks for the feedback, @piermario . I reached out to Adam this week, and I see he's added this to his To-dos.

@adamwoodnz Thanks for looking into this for us. Is it safe to presume this is now being worked on and we should get an update soon?

**Comment by adamwoodnz** [comment]
> Is it safe to presume this is now being worked on and we should get an update soon?

I intend to allocate time this week, yes :)

**Comment by piermario** [comment]
Thanks @adamwoodnz and @bsanevans! 
Awesome news! 🌟

**Comment by adamwoodnz** [comment]
While working on this I've had to ensure that all lesson plans have the right language set, and I've found some that don't. The  following need to be updated, likely by their author:

[Како припремити план лекција?](https://learn.wordpress.org/lesson-plan/%d0%ba%d0%b0%d0%ba%d0%be-%d0%bf%d1%80%d0%b8%d0%bf%d1%80%d0%b5%d0%bc%d0%b8%d1%82%d0%b8-%d0%bf%d0%bb%d0%b0%d0%bd-%d0%bb%d0%b5%d0%ba%d1%86%d0%b8%d1%98%d0%b0/) @bsanevans

**Comment by kaitohm** [comment]
I've updated that, @adamwoodnz . Feel free to ping me with any others.

**Comment by piermario** [comment]
Thank you so much @adamwoodnz and @bsanevans! 
So happy to see that it's finally live on Learn! 🌟
