### ISSUE TITLE
Learn WordPress Content (August 2022 Sprint page) Error Report

### ISSUE THREAD

**Issue by amitpatel0702** [WordPress/Learn#880]
### Bug Description

There are still a few sections on Learn WordPress website showing Social Learning Spaces instead of Online Workshops.

Content URL -  [https://make.wordpress.org/training/2022/08/08/august-2022-sprint](https://make.wordpress.org/training/2022/08/08/august-2022-sprint)

Team Links Section --> 1. --> 4. Social Learning Spaces

**Social Learning Spaces must be renamed to Online Workshops.**

![CleanShot 2022-08-08 at 12 31 21@2x](https://user-images.githubusercontent.com/98820728/183362725-5430d81b-ccf5-498e-a0e5-0c11f21b4d8d.jpg)

**Comment by webtechpooja** [comment]
@amitpatel0702 Thank you for reporting.
 I have updated links in sprint, agenda and reusable blocks as well. So next time we will have the correct name and link.

**Comment by amitpatel0702** [comment]
Thanks @webtechpooja.
