### ISSUE TITLE
Learn WordPress Content (eligibility criteria link) Error Report - Ticket

### ISSUE THREAD

**Issue by amitpatel0702** [WordPress/Learn#881]
### # Error Description

- Content URL: [https://make.wordpress.org/training/handbook/faculty-program/reviewing-volunteer-applications/](https://make.wordpress.org/training/handbook/faculty-program/reviewing-volunteer-applications/)

**The link Eligibility Criteria leads to "Not Found" as shown in the attached image.**

![CleanShot 2022-08-08 at 11 58 33@2x](https://user-images.githubusercontent.com/98820728/183369719-d69dd8b9-ba8e-4e9b-b1cc-6f99de962950.jpg)

# Error Report Checklist:
- [x] Error Validated
- [x] Error fix proposed
- [x] Error fix reviewed
- [x] Error fix published

**Comment by webtechpooja** [comment]
Hey @amitpatel0702,

Thanks for indicating the broken link. I have updated the link. Now it is working fine. it was related to the name change (Workshop -> Tutorials).
