### ISSUE TITLE
Exporting a Template or Template Part Code to a Theme File - Lesson

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#885]
# IMPORTANT
**This lesson plan belongs to part of a greater course, [Extend a Low Code Block Theme](https://github.com/WordPress/Learn/issues/821) which depends on the completion of  [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631)**

**Please reach out to @jonathanbossenger (Jonathan Bossenger) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
The goal of this lesson is learn how to fiew the template or template file source code in the editor, save that code in the relevant file in the theme, and configure the custom template or template file in the theme.json.

# Objectives
After completing this lesson, participants will be able to:

- View the template/part content
- Copy and paste the content into the correct file in the theme
- Register the template/part in the theme.json

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Draft for review
[Exporting Custom Templates and Template parts](https://github.com/jonathanbossenger/block-theme-course/blob/main/module-04/02-Exporting-Custom-Templates-Template-Parts.md)

## Review checklist

Reviewers: this is not an extensive list, but it would be helpful if you can keep the following questions in mind while reviewing.

1. Are there any spelling/grammar issues or anything that doesn't make sense?
2. Is the content technically correct?
3. Does the layering of information successfully build from lesson to lesson
4. Can you follow the steps outlined in the course
5. Does the lesson contain enough relevant links to documentation (WordPress documentation, or any other relevant documentation)

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/issues/1194
