### ISSUE TITLE
Personalizing your 404 Template

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#888]
//tutorial

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/185815724-389e8a99-a3cc-4660-8aa5-c58257708a73.mp4

**Comment by kaitohm** [comment]
Great video! I just have one comment.

I don't believe themes are required to offer a 404 template. In other words, not every block theme may have a 404 template for folks to edit.

Reference from https://wordpress.org/support/article/template-editor/
> Many block themes offer other built-in templates like... the 404 template to customize the layout of the 404 error page...

I think we should mention that somewhere, just in case someone watching the video is using a theme without a 404 page template. Or maybe something like "Many themes offer a 404 page template. In this video, I'm using the XYZ theme."

**Comment by westnz** [comment]
Good point.  Thank you @bsanevans!

**Comment by amitpatel0702** [comment]
- Great presentation.
- Easy to understand for all audience types.
- You covered both scenarios (Custom 404, and the other one using patterns) very well.
- Yes, regarding Ben's point - Most of the themes including default WordPress themes provide a 404 template, and in case one is not able to find a 404 template, then he/she needs to create 404.php and then follow similar steps.

**Comment by westnz** [comment]
Thank you @amitpatel0702!!

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/personalizing-your-404-template/

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/c83abe26-b4e9-4e2b-b816-a51520c07ea3

**Comment by nhrrob** [comment]
Looks good and clean. Mobile Focal Point is a new thing I learnt. 
Ready to publish I believe. 🎉

**Comment by westnz** [comment]
Published as part of the Intermediate User learning pathway in Sensei.
