### ISSUE TITLE
Introduction to Block Theme Development (For Beginners) - Tutorial

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#891]
# Topic Description
While it's possible to create a brand new, custom block theme of your own with very little code, there are times when someone will need to dig into a theme's code in order to make their theme dreams a reality. This tutorial helps a new developer explore what each required file does and introduces them to the very basics of code to prepare them for future lessons on block theme development.

Objective: Beginning developers will be able to create the necessary files of a block theme

- Part of [a larger course on block theme development](https://github.com/WordPress/Learn/issues/631)
- A mini-lesson as part of [this lesson plan on setting up your block theme's development environment](https://github.com/WordPress/Learn/issues/834)

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [x] Vetted by instructional designers for content idea
- [x] Provide feedback of the idea
- [x] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [x] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [x] Description and Objectives finalized
- [x] Create an outline of the workshop
- [ ] Tutorial submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [ ] Tutorial submitted to WPTV https://wordpress.tv/submit-video/
- [ ] Tutorial published on WPTV
- [ ] Tutorial is captioned https://make.wordpress.org/training/handbook/workshops/workshop-subtitles-and-transcripts/
- [ ] Tutorial created on Learn.WordPress.org
- [ ] Tutorial post is reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial announced to training team
- [ ] Tutorial announced to creator
- [ ] Tutorial announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by wparasae** [comment]
Asking for feedback and moving into "review" column. https://wordpress.slack.com/archives/C02RW657Q/p1661286621177259

**Comment by westnz** [comment]
This is excellent Sarah! It was easy to follow and informative!

One suggestion - 11-33sec  maybe you could just have a static example to help the viewer to focus on what is being said.

**Comment by westnz** [comment]
Feedback from @vagelisp 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/89751452/186271068-d3777c1c-66e3-4ce8-95a7-62ee98b44793.png">

**Comment by wparasae** [comment]
I will make that change, Wes. Thank you! And thank you for dropping the comment in here as well. I appreciate it!

**Comment by colorful-tones** [comment]
- 1:09 – 1:11 Local (Flywheel) "Go to site folder". It seems out of sequence and could probably be edited out.
- 1:26 – 1:53 You cover how it can be confusing to find Local's site files. However, you kind of touched on this in my first line item ☝️ . So, maybe you could edit out the 1:09 – 1:11 and put it back in to replace this section. Also, it is worth noting that it is pretty easy to find Local's site files (seen in your original screenshot at 1:09) and I'm also attaching another screenshot of how you can find them, which could be featured.

This is such a helpful addition. Thanks for the awesome work!

![Screen Shot 2022-08-30 at 5 07 49 PM](https://user-images.githubusercontent.com/405912/187544912-1695b2af-a86b-49b6-94c4-66f84bede884.png)
