### ISSUE TITLE
Overview of Theme Development For Beginners - Tutorial

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#892]
# Topic Description
For many intermediate WordPress users, the process used to design a brand new theme from scratch is a mystery. This tutorial aims to clarify how theme designers and developers work together to create a new theme, template by template, comparing classic methods with block methods for theme design.

This is part of a [larger course on block themes](https://github.com/WordPress/Learn/issues/631). It is a mini-lesson as [part of this lesson plan](https://github.com/WordPress/Learn/issues/832).

# Related Resources
Links to related content on Learn, HelpHub, DevHub, GitHub Gutenberg Issues, DevNotes, etc.
- [ ]

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Tutorial Development Checklist

- [ ] Vetted by instructional designers for content idea
- [ ] Provide feedback of the idea
- [ ] Gather links to Support and Developer Docs
- [ ] Consider any MarComms (marketing communications) resources and link to those
- [ ] Review any related material on Learn
- [ ] Define several SEO keywords to use in the article and where they should be prominently used
- [ ] Description and Objectives finalized
- [ ] Create an outline of the workshop
- [ ] Tutorial submitted to the team for Q/A review https://blog.wordpress.tv/submission-guidelines/ & https://make.wordpress.org/training/2021/08/17/proposal-brand-guidelines-for-learn-wordpress-content/
- [ ] Tutorial submitted to WPTV https://wordpress.tv/submit-video/
- [ ] Tutorial published on WPTV
- [ ] Tutorial is captioned https://make.wordpress.org/training/handbook/workshops/workshop-subtitles-and-transcripts/
- [ ] Tutorial created on Learn.WordPress.org
- [ ] Tutorial post is reviewed for grammar, spelling, etc.
- [ ] Tutorial published on Learn.WordPress.org
- [ ] Tutorial announced to training team
- [ ] Tutorial announced to creator
- [ ] Tutorial announced to Marketing Team for promotion
- [ ] Gather feedback from workshop viewers/participants

**Comment by Piyopiyo-Kitsune** [comment]
@jonathanbossenger this should be covered in your upcoming learning pathway, correct?

**Comment by jonathanbossenger** [comment]
Yup, this is covered in the [beginner developer pathway](https://github.com/WordPress/Learn/issues/1984#module-04)
