### ISSUE TITLE
An Introduction to Global Styles variations - Lesson

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#896]
# IMPORTANT
**This lesson plan belongs to part of a greater course, [Extend a Low Code Block Theme](https://github.com/WordPress/Learn/issues/821) which depends on the completion of  [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631)**

**Please reach out to @jonathanbossenger (Jonathan Bossenger) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
The goal of this lesson is to introduce the concept of Global Styles variations, and how this can be beneficial for a block theme

# Objectives
After completing this lesson, participants will be able to:

- Understand what a Global Styles variation is
- Understand how Global Styles are used in the Site Editor to enhance a block theme
- Differentiate between the Global Styles set in the theme.json vs a variation

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

**Comment by courtneyr-dev** [comment]
WP 6.1 Fluid Typography https://github.com/WordPress/gutenberg/pull/39529

**Comment by jonathanbossenger** [comment]
I plan to tackle this next week

**Comment by westnz** [comment]
Review:

Short and sweet!
