### ISSUE TITLE
How to Create and Register a Global Styles variation - Lesson

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#897]
# IMPORTANT
**This lesson plan belongs to part of a greater course, [Extend a Low Code Block Theme](https://github.com/WordPress/Learn/issues/821) which depends on the completion of  [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631)**

**Please reach out to @jonathanbossenger (Jonathan Bossenger) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
The goal of this lesson is to learn how to create and register a Global Styles variation in a block theme

# Objectives
After completing this lesson, participants will be able to:

- Create the required styles directory
- Create a new style variation manually in code
- Create a new style variation by using Create Block Theme

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

**Comment by courtneyr-dev** [comment]
WP 6.1 Fluid Typography https://github.com/WordPress/gutenberg/pull/39529

**Comment by jonathanbossenger** [comment]
I plan to tackle this next week

**Comment by westnz** [comment]
Review:

Logical and clear instructions!

Should the title not be H1 and the main headings H2?  Maybe they are, and I just can't see the difference:
<img width="922" alt="image" src="https://user-images.githubusercontent.com/89751452/203646699-2ff7828c-aad1-447e-b485-6fb312558eab.png">

Ensure all sentences have full stops. Also, proofread point 4:
<img width="922" alt="image" src="https://user-images.githubusercontent.com/89751452/203646841-b67b7b9e-3df5-4e5e-a5e2-c94f1dc0d589.png">

Ensure all sentences have full stops. I think json should be JSON? I see here it is all written in lowercase:
<img width="922" alt="image" src="https://user-images.githubusercontent.com/89751452/203647251-7e8da9ec-ea53-4b9c-b559-5a07d45db7cf.png">

Add full stops :-)
<img width="922" alt="image" src="https://user-images.githubusercontent.com/89751452/203647877-b8ef8d50-6e28-48b5-8f83-af2dc6239efe.png">

Remove the full stop after 'attribute'
<img width="922" alt="image" src="https://user-images.githubusercontent.com/89751452/203648131-51d3ed31-3801-404d-be5e-d47b9ffea7ee.png">

**Comment by jonathanbossenger** [comment]
> Should the title not be H1 and the main headings H2? Maybe they are, and I just can't see the difference:

They actually are, it's the front-end design for headers of Learn WordPress.

Thanks for catching the other items, updated them.

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/49014 @jonathanbossenger likely this should be revised at some point to mention viewing them as well from the new location in 6.3

**Comment by courtneyr-dev** [comment]
https://make.wordpress.org/core/2023/05/20/whats-new-in-gutenberg-15-8-may-17/#add-revisions-ui-50089

**Comment by jonathanbossenger** [comment]
Style variations will be covered/updated for the [Intermediate Theme Developer learning pathway](https://github.com/WordPress/Learn/issues/2045), so closing in favor of that.
