### ISSUE TITLE
Integration: Install theme/plugins on .org

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/Learn#9]
Particularly interested in seeing style/class conflicts.

**Comment by coreymckrill** [comment]
First step: 92b420d99f73fd6fc4e18d526b510262c8d1800e

**Comment by coreymckrill** [comment]
Consolidated plugins: 38c404cb5ebcb1100e8c699e38c7834b681dd670

**Comment by coreymckrill** [comment]
Add plugin and theme to the meta.svn repo:
https://meta.trac.wordpress.org/changeset/10130
https://meta.trac.wordpress.org/changeset/10131

**Comment by coreymckrill** [comment]
Added an external in dotorg.svn for the plugin in meta.svn. This was not necessary for the theme because the entire themes/pub directory is already an external.

**Comment by coreymckrill** [comment]
The plugin and theme are now running here: https://learn.wordpress.org/
