### ISSUE TITLE
Online Workshop - What is the Domain Name System?

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#904]
# Event Details
- Title: What is the Domain Name System?
- Level: Intermediate
- Target Audience: Users
- Meetup event link: https://www.meetup.com/learn-wordpress-online-workshops/events/287874977/
- Co-host: @amitpatel0702 

This is a stand-alone workshop, but builds on a previous workshop I did on a similar topic: [Introducing... Domains!](https://www.meetup.com/learn-wordpress-online-workshops/events/287565176/)

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by kaitohm** [comment]
This is the outline I posted on Meetup...
---

Did you enjoy the previous workshop [Introducing… Domains!](https://wordpress.tv/2022/08/12/introducing-domains/) ? If so, then you’ll enjoy this workshop, too! We’ll be continuing our discussions around domains, this time by taking a closer look at DNS - the Domain Name System.

Every site needs a domain. But every domain needs DNS records set for it to direct people to your site! In this workshop, we’ll be looking at how DNS work, and what the most common types of DNS records are. We’ll also look at the DNS records you need to configure to get your site up and running. Some questions we’ll be answering include:

- How does the Domain Name System work?
- What are DNS records?
- What DNS records do I need for my site?
- Where can I edit my domain’s DNS records?
- What is “domain record propagation”?

This workshop will also have an open floor discussion about domains. So come prepared with your domain-related questions, and we’ll take time to answer those, too!

This session will be held in an APAC friendly time. If you cannot get to the live session, keep an eye out for the recording we’ll be publishing on wordpress.tv after the session is completed :-)

**Comment by kaitohm** [comment]
Here are my slides for this session: https://docs.google.com/presentation/d/1XD8oGKkAs_m-PwRKAdr6fOtQ2fLCFxHLWgvVuTRwHeM/edit?usp=sharing

Feel free to leave comments in the slides, or here in GitHub. Thanks.

**Comment by amitpatel0702** [comment]
All Seems perfect and ready for execution. :)

**Comment by kaitohm** [comment]
I'll be conducting this session a second time at a different timezone. Here are details of the second session.

# Event Details
- Date: October 14th
- Meetup event link: https://www.meetup.com/learn-wordpress-online-workshops/events/288128302/
- Co-host: @westnz 

This is a stand-alone workshop, but builds on a previous workshop of a similar topic: https://github.com/WordPress/Learn/issues/911

# Online Workshop Checklist:
- [x]  Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x]  Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x]  Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x]  Hold Online Workshop
- [x]  Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ]  Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by amitpatel0702** [comment]
That's awesome !!! Just wanted to confirm a few steps - Are you planning to run an online workshop with the same slides without uploading that workshop in WordPress.tv?

**Comment by kaitohm** [comment]
@amitpatel0702 That's right. I may make slight tweaks based on feedback from the first session. But the goal is to conduct the exact same workshop just at a different time for folks in other timezones to also attend.

**Comment by kaitohm** [comment]
### Post-session resources

- Here is a link to the uploaded video on WordPress.tv: https://wordpress.tv/2022/08/29/what-is-the-domain-name-system/
- This is a link to my final slides: https://docs.google.com/presentation/d/1XD8oGKkAs_m-PwRKAdr6fOtQ2fLCFxHLWgvVuTRwHeM/edit?usp=sharing
- And this is the PDF version of those slides: https://drive.google.com/file/d/1EcRCwEJedeMa9i-fzKvpA7awLC_MyDV4/view?usp=sharing

**Comment by kaitohm** [comment]
I have conducted the second session on this topic. I used the same slides as those mentioned above. I did not upload any new recording to WordPress.tv, as the session was not that much different from the last one.

This is now compelete!
