### ISSUE TITLE
Adding a pattern from the Pattern Directory to your theme - Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#906]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/187097063-f4c076e6-eedc-4943-b956-babaab93bd76.mp4

**Comment by azhiya** [comment]
@vagelisp has volunteered to review this.

**Comment by vagelisp** [comment]
Hello @westnz; I reviewed the video and it's great. I believe it is ready to be published. Well done.

**Comment by westnz** [comment]
Great stuff!  Thank you for your feedback and time @vagelisp

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/adding-a-pattern-from-the-pattern-directory-to-your-theme/

**Comment by courtneyr-dev** [comment]
Reusable blocks: Rename to 'Patterns' and add the option to also add a non-synced Pattern ([51144](https://github.com/WordPress/gutenberg/pull/51144))
Patterns: Add renaming, duplication, and deletion options ([52270](https://github.com/WordPress/gutenberg/pull/52270))
6.3
