### ISSUE TITLE
Online Workshop - Introducing... Domains!

### ISSUE THREAD

**Issue by kaitohm** [WordPress/Learn#911]
# Event Details
- Title: Introducing... Domains!
- Description: An introductory session to what domains are and what a good domain for a personal site may be.
- Target Audience: Beginners
- Other info: I've conducted this session once (previous Meetup event, WordPress.tv recording), but am conducting it again at a different timezone.
- Date: September 29th 0 UTC
- Meetup event: https://www.meetup.com/learn-wordpress-online-workshops/events/288128197/
- Co-host: @westnz 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by kaitohm** [comment]
The slides are ready for content/editorial review: https://docs.google.com/presentation/d/1FAWyqurywPWRRvV524OoZhyG6Wg5WYkUskCmH5LKwvk/edit?usp=sharing

**Comment by maion11** [comment]
Hi @bsanevans, checked and reviewed the content. They look great and are ready to be executed. Thanks :)

**Comment by kaitohm** [comment]
Just noting @kryzpt and @vagelisp both also [gave me feedback on my slides](https://wordpress.slack.com/archives/C02RW657Q/p1661751004814819). Thanks for the review, everyone!

**Comment by kaitohm** [comment]
I previously uploaded a recording of the first session I did on this topic to WordPress.tv, which can be found here: https://wordpress.tv/2022/08/12/introducing-domains/


Slides (Google Slides): https://docs.google.com/presentation/d/1FAWyqurywPWRRvV524OoZhyG6Wg5WYkUskCmH5LKwvk/edit?usp=sharing

Slides (PDF): [20220929 Introducing... Domains.pdf](https://github.com/WordPress/Learn/files/9680282/20220929.Introducing.Domains.pdf)
