### ISSUE TITLE
Uncovering the Cover Block

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#913]
//lesson

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/188335975-8b3bb6f4-fddf-4433-9a2d-be4ef570d804.mp4

**Comment by azhiya** [comment]
@artdecotech has volunteered to review this.

**Comment by artdecotech** [comment]
Hi @westnz – this is a great tutorial! I learned a lot.

One concern during the Roger Lister CTA example, the text is not legible when it is in front of his face, I wonder if that would be the case on small screen sizes? I have read that it's important to keep contrast and mobile screen sizes in mind when using the Cover block. Showing how to preview the page on mobile might be helpful here. Not a show stopper though.

Looking at other tutorials online, I wonder if it would make sense to show a cover block in line with text around it / alternate alignment options beyond full width.

Great work! I'd be happy to publish it as is, but just a few thoughts as I reviewed it. I loved the intro image too, better than just the boring blue. And it looks like a Cover block :D

**Comment by westnz** [comment]
Hey @artdecotech 

Thank you very much for the feedback. 

`the text is not legible when it is in front of his face`
When you open the List View and Sidebar Settings that usually happens, but when you close it you will see that everything is in proportion.  Showing the mobile screen preview is a great idea.  I will see how it looks. 

`show a cover block in line with text around it / alternate alignment options beyond full width.`
Can you share a screenshot of an example?  The only problem is that the tutorial is already longer than intended. 

Really appreciate your input!

**Comment by amitpatel0702** [comment]
Hi @westnz,

Thanks for the great tutorial. Here are my comments.

- You covered the following crucial topics very well.

1. Cover block is a container block and it can contain other blocks in it.
2. Focal point setting which is really helpful for mobile views.
3. Dual tone settings in the background.

- I like your style of presentation. Loved the way you added  "Color to match Roger's shirt"  🙂 
- Overall extremely helpful tutorial explaining the power of Cover Block.

Thanks.

**Comment by westnz** [comment]
Thank you very much @amitpatel0702

**Comment by westnz** [comment]
Review: CTA example
M: "should not use headers for text size or styling, headers are for identifying sections"

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/uncovering-the-cover-block/

**Comment by courtneyr-dev** [comment]
6.3 https://make.wordpress.org/core/2023/03/22/whats-new-in-gutenberg-15-4-22-march/#color-and-layout-support-for-cover-block

**Comment by courtneyr-dev** [comment]
https://github.com/WordPress/gutenberg/pull/41153 6.3
[image of text color controls](https://drive.google.com/file/d/1ieKtIOucrZ35oVxVkSM4uLz0eGvsxysM/view?usp=sharing), [image of layout controls](https://drive.google.com/file/d/1mQlI7w4x1GVs_BNee7IjNQb8P_nnVzol/view?usp=sharing).
https://github.com/WordPress/gutenberg/pull/45326
Add text color controls and borders support ([41153](https://github.com/WordPress/gutenberg/pull/41153)).
Add text color controls ([41572](https://github.com/WordPress/gutenberg/pull/41572)).
Simplify cover block description. ([50355](https://github.com/WordPress/gutenberg/pull/50355)).
Add constrained/flow layout to Cover block ([45326](https://github.com/WordPress/gutenberg/pull/45326)).

**Comment by westnz** [comment]
I plan to update and use this tutorial in the learning pathway project.

**Comment by ghost** [comment]
@westnz I am giving myself a due date of June 7th for this lesson.

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/45bee740-849e-4133-8b75-5d2dd7b8c795

**Comment by moltilearn** [comment]
Another review for contributor day today, and here is my comment.
Thanks for your great video, i followed your instructions step-by-step and could create the examples with ease. I struggled with the parallax example at 4.40 with the block spacing setting, I didn't see the option. We at contributor day found out that it depents on the theme, in my case I use Neve, after changing the theme to Twenty Twenty-Two, the block spacing option is there. Do we need to mention that it can be different depending on theme set?   
Cheers from Torino.

**Comment by ironnysh** [comment]
## Tutorial/Lessons Review Checklist
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.
- [ ] [Brand Usage Guidelines](https://make.wordpress.org/training/handbook/guidelines/brand-usage-guidelines/) and [Promotional Guidelines](https://make.wordpress.org/training/handbook/guidelines/promotional-guidelines/) are being followed.
- [ ] Media assets are all in the public domain ([CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)).

Great tutorial, @westnz. The hands-on demos are very cool.

There's one a11y issue with the hero video example: it defaults to `autoplay` and `loop`, which is a WCAG violation (and somewhat annoying 😅).

The problem is caused by how the block was coded in Gutenberg (see [this open issue](https://github.com/WordPress/gutenberg/issues/38975)), but I think it's worth pointing out in the lesson.

**Comment by westnz** [comment]
Thank you for the feedback folks

@ironnysh, I think I am going to use another example instead of the video banner then.

**Comment by westnz** [comment]
New version ready for review:
https://github.com/WordPress/Learn/assets/89751452/590941c2-8001-4d3f-bfb3-e06399e20c86

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/70b7090c-4707-4cc6-96d9-ed3ba8010926

**Comment by westnz** [comment]
Added a new version and re-recorded the first example.

**Comment by westnz** [comment]
//published
