### ISSUE TITLE
Add Code Syntax Block upgrades to Learn

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#925]
DevHub recently received upgrades to the Code Syntax Block that make code blocks much more useful and easier to use. We'd like to get these improvements added to Learn as well.

Here's an example of the upgrades in action: https://developer.wordpress.org/block-editor/reference-guides/data/data-core-blocks/

And this is where I'm told the upgrades were implemented: https://github.com/WordPress/wporg-developer/blob/34e370515f48dab03a0c4fd444bff1c4e151f52c/source/wp-content/themes/wporg-developer/js/function-reference.js

**Comment by adamwoodnz** [comment]
Reopening to fix some lint issues
