### ISSUE TITLE
Use locale switcher selection to prioritise content

### ISSUE THREAD

**Issue by hlashbrooke** [WordPress/Learn#939]
_This is dependent on #811, which is being worked on in PR #931_

Once we have the locale meta field for all content types, it would be great if that could be used to bring all content for the locale selected by the switcher to the top of all queries.

Tutorials already have this prioritisation applied, see [wporg_archive_query_prioritize_locale](https://github.com/WordPress/Learn/blob/trunk/wp-content/themes/pub/wporg-learn-2020/functions.php#L477)

**Comment by adamwoodnz** [comment]
Update: Language meta field was added to all post types in #1030

**Comment by adamwoodnz** [comment]
Fixed by https://github.com/WordPress/Learn/pull/2657
