### ISSUE TITLE
Online Workshop - Code With Me: Code Your First Settings in Theme.json

### ISSUE THREAD

**Issue by wparasae** [WordPress/Learn#956]
# Event Details
- Title: Code With Me: Code Your First Settings in Theme.json
- Description: This online workshop introduces intermediate WordPress users and/or beginning developers to the easiest settings to use in theme.json, specifically utilizing AppearanceTools and Layout (Content Width). If there is time, we may move into Colors and/or Headings.
- Target Audience: Beginning Developers / Intermediate WordPress Users
- Date: Sep 22, 2022
- Meetup.com event link:
- Co-host: @jonathanbossenger 
- Other info: This live workshop requires users install a local WordPress environment and utilize a text editor that supports schema.

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by jonathanbossenger** [comment]
@wparasae closing this ticket.
