### ISSUE TITLE
Online Workshop - Media Tips & Tricks

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [WordPress/Learn#958]
# Event Details
- Title: Media Tips & Tricks
- Description: In this workshop, we'll go over some tips & tricks for working with media in WordPress, including:
Organizing your Media Library, Adding & removing images, Regenerating thumbnails, Applying Duotone Filters to Change Color Effects
- Target Audience: Users
- Date: 23 September 2022
- Meetup.com event link: https://www.meetup.com/learn-wordpress-online-workshops/events/288610335/
- Co-host: @wparasae 
- Other info: 

# Online Workshop Checklist:
- [x] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [x] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [x] Hold Online Workshop
- [x] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [x] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by courtney-pk** [comment]
This video has been posted on WPTV:
https://wordpress.tv/2022/09/23/media-tips-tricks/
Captions still to come,  but considering this issue closed!
