### ISSUE TITLE
Tools: Import and Export content in WordPress - Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#960]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/191639777-c1134402-64b5-4e54-a776-e0539b3ca18a.mp4

**Comment by hlashbrooke** [comment]
This is solid @westnz - I like it a lot! I'm happy for this to be published as it stands now.

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/tools-import-and-export/

**Comment by westnz** [comment]
Updated for the Intermediate user learning pathway.

**Comment by westnz** [comment]
//published
