### ISSUE TITLE
Block Spacing - Tutorial

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#965]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/191881717-e99ba920-9f2f-4b02-9aea-6e4cb242ff76.mp4

**Comment by hlashbrooke** [comment]
This is great! Short, yet effective :)

**Comment by robinwpdeveloper** [comment]
This is really good. Will help everyone.
Looks Good To Me 👍

**Comment by westnz** [comment]
Thank you for the feedback @robinwpdeveloper

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/block-spacing/
