### ISSUE TITLE
The Block Theme For This Course

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#968]
# IMPORTANT
**This lesson belongs to part of a greater course, [Extend a Low Code Block Theme](https://github.com/WordPress/Learn/issues/821) which depends on the completion of  [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631)**

**Please reach out to @jonathanbossenger (Jonathan Bossenger) in the #training team Slack if you would like to help with this lesson.**

# Topic Description
The goal of this lesson is to review the block theme that learners will be building as the learning outcome of this course. 

# Objectives
After completing this lesson, participants will have an understanding of what they are working towards.

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

# Lesson for Review

_Please note that this content is being migrated over to [Learn WordPress](https://learn.wordpress.org/), and during that process, updates and corrections are being implemented on the lesson content. If you don't have access to Learn WordPress, you can review using the source markdown file, but that information might be out of date._

- [Learn WordPress Lesson](https://learn.wordpress.org/lesson/the-block-theme-for-this-course/)
- [Source markdown file](https://github.com/jonathanbossenger/block-theme-course/blob/main/module-02/01-Block-Theme-For-This-Course.md)

## Review checklist

Reviewers: this is not an extensive list, but it would be helpful if you can keep the following questions in mind while reviewing.

1. Are there any spelling/grammar issues or anything that doesn't make sense?
2. Is the content technically correct?
3. Does the layering of information successfully build from lesson to lesson
4. Can you follow the steps outlined in the course
5. Does the lesson contain enough relevant links to documentation (WordPress documentation, or any other relevant documentation)

**Comment by westnz** [comment]
- You have made the aim of the course clear and provided resources about design.
- Twenty **Twenty-Three** instead of Twenty Twenty Three
- To learn more about the process of **designing** a theme instead of To learn more about the process of design a theme
- ...Figma design to copy **it** to your own Figma account instead of ...Figma design to copy if to your own Figma account

**Comment by jonathanbossenger** [comment]
Thanks, @westnz. In the process of migrating the data from markdown to Sensei, I picked up those, and a few other errors. I need to find a better spelling/grammar checker for my markdown files.
