### ISSUE TITLE
Managing Settings: Media

### ISSUE THREAD

**Issue by westnz** [WordPress/Learn#970]

**Comment by westnz** [comment]
https://user-images.githubusercontent.com/89751452/193155715-b463f2a0-bb82-4c76-8461-8ed5b4f3e371.mp4

**Comment by hlashbrooke** [comment]
Looks good to me - explained clearly and succinctly.

**Comment by wparasae** [comment]
This looks good! I learned something new about WordPress :) I really liked that you explained why people make these choices at the end.

One optional opportunity for change is between 1:35-1:55 - the arrow felt like it should be pointing to the Image Size _or_ the Image Dimensions. It pulled my gaze -- I think you made that choice to encompass both the image size and the dimensions, though, so this is more an artistic suggestion over a "must change" - your choice if it's worth the effort to change!

**Comment by jonathanbossenger** [comment]
Great video @westnz, clear and concise.

**Comment by westnz** [comment]
Thank you for the feedback!

**Comment by westnz** [comment]
Published: https://learn.wordpress.org/tutorial/managing-settings-media/

**Comment by westnz** [comment]
https://github.com/WordPress/Learn/assets/89751452/bfb59a06-3fbd-42db-b8ca-d949adebf8b3

**Comment by dd32** [comment]
## Tutorial/Lessons Review Checklist
Please tick all items you've confirmed:
- [x] Learning outcomes/objectives are clear.
- [x] Technical concepts introduced in the content are accurate.
- [x] The speed of demonstrations are easy to follow.
- [x] The narration audio matches what is shown visually.
- [x] Spelling and grammar are correct.
- [x] Sound quality is consistent throughout the video.

LGTM 👍

**Comment by westnz** [comment]
//published
