### ISSUE TITLE
Italian translation for Lesson Plan "Setting A Static Page As Your Homepage"

### ISSUE THREAD

**Issue by piermario** [WordPress/Learn#980]
# Details
- Link to original content: https://learn.wordpress.org/lesson-plan/setting-a-static-page-as-your-homepage/
- Language you'll be translating to: Italian
- Have you arranged for someone to review this translation?: Yes
- Reviewer's GitHub username: lidialab
- Other info: 

The translation is currently on Google Docs, waiting for Lidia's proofreading/editing

# Next Steps
Once translated, please link or upload your translated files in a comment on this issue, and request a [translation review](https://make.wordpress.org/training/handbook/content-localization/#translation-review).

**Comment by piermario** [comment]
Hello, friends!

The translation above has been reviewed by @lidialab, a qualified fellow Polyglot and Italian GTE.

We completed editing and proofreading, so I created a draft for the lesson page on Learn.

Here's the link to the draft: https://learn.wordpress.org/?p=24454&post_type=lesson-plan&preview_id=24454

What's next? 

Thanks in advance! :)

Piermario

**Comment by courtneyr-dev** [comment]
Published at https://learn.wordpress.org/lesson-plan/imposta-una-pagina-statica-come-homepage/
