### ISSUE TITLE
Online Workshop - Building a Simple Block

### ISSUE THREAD

**Issue by courtney-pk** [WordPress/Learn#990]
# Event Details
- Title: Building a Simple Block _(working title, not final)_
- Description: Come build blocks with us! Ebonie Butler will be joining us to demonstrate the process of building a simple block. (to be updated)
- Target Audience: Users & Developers
- Date: TBD 2023
- Meetup.com event link: TK
- Co-host: Ebonie Butler
- Other info: 

# Online Workshop Checklist:
- [ ] Create Online Workshop event on [Learn WordPress Online Workshops](https://www.meetup.com/learn-wordpress-online-workshops/)
- [ ] Add Online Workshop to [Online Workshop calendar](https://learn.wordpress.org/online-workshops/)
- [x] Assign Co-host to event (Remove the "Needs Co-host" tag from issue once assigned)
- [ ] Hold Online Workshop
- [ ] Complete [After an Online Workshop](https://make.wordpress.org/training/handbook/online-workshops/after-an-online-workshop/) next steps
- [ ] Add link to slides and/or WordPress.tv video to GitHub issue

**Comment by kaitohm** [comment]
Are you still working on this, @courtney-pk ?
