### ISSUE TITLE
Greek Lesson plan block pattern

### ISSUE THREAD

**Issue by vagelisp** [WordPress/Learn#992]
# Topic Description
I just made PR #991 to add the Greek version of the block pattern for the Lesson plans.
I used what we already use for the translation content, 

@lenasterg @theo-gk, can you please verify the translation?

Thanks so much.

**Comment by vagelisp** [comment]
@courtneyr-dev FYI

**Comment by theo-gk** [comment]
I didn't review this in time, already merged. @vagelisp 

Notes:
::216 - Missing accent
::226 - Missing accent
::244 - Missing letter "ν" -> **στον** δικό τους ιστότοπο
::258 - Missing letter "ς" -> **άσκησης**
::286 - Capitalize first letter -> **Δεν πρέπει**

Great, this translation will be useful

**Comment by vagelisp** [comment]
@theo-gk No probs, thanks for the review. I'll fix these asap.

**Comment by vagelisp** [comment]
~~::216 - Missing accent~~
~~::226 - Missing accent~~
~~::244 - Missing letter "ν" -> στον δικό τους ιστότοπο~~
~~::258 - Missing letter "ς" -> άσκησης~~
~~::286 - Capitalize first letter -> Δεν πρέπει~~

All fixed, I made a new PR #993
