### ISSUE TITLE
Disabling Theme Settings in theme.json

### ISSUE THREAD

**Issue by jonathanbossenger** [WordPress/Learn#996]
# IMPORTANT
**This lesson plan belongs to part of a greater course, [Extend a Low Code Block Theme](https://github.com/WordPress/Learn/issues/821) which depends on the completion of  [Create a Custom Block Theme #1](https://github.com/WordPress/Learn/issues/631)**

**Please reach out to @jonathanbossenger (Jonathan Bossenger) in the #training team Slack if you would like to help with this lesson plan.**

# Topic Description
The goal of this lesson is to learn how to disable Site editor features by disabling settings in theme.json.

# Objectives
After completing this lesson, participants will be able to:

- Disable/enable specific settings in the Site editor
- Understand which settings are enabled when enabling appearanceTools

# Guidelines
Review the [team guidelines] (https://make.wordpress.org/training/handbook/guidelines/)

**Comment by ryanwelcher** [comment]
I'll be taking this on :)

**Comment by justintadlock** [comment]
@jonathanbossenger I've talked with @ryanwelcher and am taking over for this module.

I've started work here: https://github.com/justintadlock/block-theme-course/tree/main/module-09

Currently, there's a short outline in the `readme.md`, and I've roughed out lesson 1 (really, extremely rough right now).

**Comment by westnz** [comment]
Review:

Logical flow and clear explanations!

Including the code and screenshots of how it looks in the post editor is helpful!
